from pathlib import Path
import json,hashlib,datetime,shutil,subprocess,sys,html
from PIL import Image
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');root=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001';source=root/'panning_contact/attempt_01';out=b/'audit/job_pan_gripping_pose_study_v2_20261001';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
evaluation='Established warm child face, rainbow locks/full fin, tan cyan-lens cap and teal/lilac geologist costume stay recognizable. Rounded brown/plum contours and broad painted values preserve the picture-book family. Both connected arms now grip the pan rim, at a believable shared scale rather than low crawling palms beside a giant bowl. Pan remains broad lavender/aqua with clear open water. Source finish/identity4.6; static grip4.6. One hand grips the side/near rim and the other the far rim, differing from the initial both-near-rim brief but producing clear contact. Broad neutral-field alpha inspections are clean; native black-display glow is trace alpha below8, not a baked opaque backdrop. Full subject is inside the canvas, though head margin is33px. Table support, arrival/pickup, rocking, release/return and full ordinary routes remain independent gaps.'
qualification='Native generated output, both white/aqua displays and uniform whole-canvas derivative directly inspected. Static source-only drafting score; no accepted motion, complete game, target-device/child/owner or release claim.'
sr=dict(id='GEO-PAINT-PANNING-CONTACT-01',path=rel(source/'native.png'),sha256=sha(source/'native.png'),dimensions=list(Image.open(source/'native.png').size),source_score=4.6,static_grip_score=4.6,status='SELECTED_STATIC_SOURCE_ONLY_UNBOUND',evaluation=evaluation,qualification=qualification,native_direct_review=True,neutral_previews_direct_review=[rel(source/'audit_white.png'),rel(source/'audit_aqua.png')],technical_derivative_direct_review=rel(source/'whole_canvas_1024.png'),mounted_score=None,complete_action_score=None,owner_approval=None)
write(source/'SOURCE_REVIEW.json',sr)
review=json.loads((root/'REVIEW_V4.json').read_text());review.update(previous_review=rel(root/'REVIEW_V4.json'),reviewed_utc=now,native_outputs_directly_reviewed=16,neutral_native_displays_directly_reviewed=30,technical_derivatives_directly_reviewed=11)
review['qualification']='All16 native ImageGen outputs,30 neutral fields and11 whole-canvas derivatives directly inspected. Every292 teacher/geology/pan native comparison directly reviewed. Connected static grip4.6 is separate from articulated motion, tabletop support4.3 and ordinary full routes. Undersize room remains reference-only. Originals/rejected attempts/history preserved; no production binding/device/child/owner/final acceptance.'
review['items'].append(dict(sr,source_record=rel(source/'GENERATION_RECORD.json')))
der=source/'whole_canvas_1024.png';review['technical_derivatives'].append(dict(path=rel(der),sha256=sha(der),dimensions=list(Image.open(der).size),source_path=rel(source/'native.png'),source_sha256=sha(source/'native.png'),method='Uniform whole-canvas RGBA normalization only',alpha_preserved=True,pixel_repair=False,source_score=4.6,status='SELECTED_STATIC_TECHNICAL_DERIVATIVE_UNBOUND',evaluation='Complete generated character/pan contact and alpha preserved. Whole derivative directly inspected; static source quality4.6 does not supply missing rocking/travel/pickup/release acting.',qualification=qualification))
review['native_context_reports'].append(rel(out/'index.html'));write(root/'REVIEW_V5.json',review)
write(root/'GENERATED_NATIVE_REGISTER_V5.json',dict(status='16_NATIVE_GENERATED_SOURCE_FILES_PRESERVED',sources=[dict(path=x['path'],sha256=x['sha256'],dimensions=x['dimensions'],score=x['source_score'],status=x['status']) for x in review['items']],qualification=review['qualification']))
views=json.loads((out/'native_views/CAPTURE_RECEIPT.json').read_text())['views'];rows=[]
for v0 in views:
 v=dict(v0);inv=v['state']=='invitation';p=out/'native_views'/v['path'];assert sha(p)==v['sha256'];v.update(archive_path=rel(p),direct_native_review=True,reviewed_utc=now,scores=dict(actor_identity_finish=None if inv else 4.6,static_hand_rim_contact=None if inv else 4.6,actor_tabletop_support=None if inv else 4.3,grain_finish=None if inv else 4.5,grain_basin_containment=None if inv else 4.6,mineral_water_contact=4.5 if 'partial' in v['state'] else None,invitation_object_contact=4.5 if inv else None,scene_coherence=4.4 if inv else 4.5,articulated_panning_motion=None,complete_action=None),evaluation='Invitation unchanged; the new gripping source is absent, so no new actor contact is scored. Existing static pan/slab contact4.5 provisional retains its earlier qualification.' if inv else 'The new complete generated pose makes both grips and physical actor/pan scale readable4.6; head, face, fingers and full fin remain clear at this width. Grains stay inside authored aqua water4.6, but their tiny12px material is4.5 provisional. Tail sits across the slab front without an authored compression/support shadow, so tabletop support4.3 remains weak. '+('Recovered mineral stays inside water with a joined base/contact4.5 provisional. ' if 'partial' in v['state'] else '')+'This selected static state after inherited input does not prove rocking: the disposable fixture translates the whole connected card with pan_visual_x and supplies no articulated frames, approach, pickup, release or return. No full action pass.',qualification='Phase-selected native static contact study; inherited partial one-finger panning input and325 unchanged production sources. All6 views directly inspected. No complete naturally timed ordinary training/story route, target device/child/owner or final report acceptance.',owner_acceptance=None,production_binding_changed=False);rows.append(v)
assert len(rows)==6;write(out/'REVIEW.json',dict(status='6_OF6_DIRECT_STATIC_REVIEW_CONTACT4_6_MOTION_OPEN',views=rows,directly_reviewed=6,total_teacher_geology_pan_views=292,qualification='Static grip4.6; tabletop support4.3 and authored rocking/travel/pickup/release/return remain priorities. Overall goal not complete.'))
cards=['<article><h2>'+html.escape(v['id'])+'</h2><img src="native_views/'+v['path']+'" alt="'+v['id']+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+' '+str(x)+'/5' for k,x in v['scores'].items() if x is not None))+'</p><small>'+html.escape(v['qualification'])+'</small></article>' for v in rows]
(out/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Geologist connected pan gripping pose</title><style>body{font:17px/1.5 system-ui;background:#eef5f4;color:#302949;max-width:1500px;margin:auto;padding:24px}article{background:white;padding:20px;margin:25px 0}img{width:100%;height:auto}</style><h1>Geologist new gripping pose — all6 native views</h1><p>Both raised arms grip the pan4.6. Static source quality4.6; tabletop support4.3 and real articulated rocking/travel/pickup/release/return remain open. The whole-card displacement in this disposable study is not accepted job action. Current illustrated library:292 direct teacher/geology/pan comparisons,16 ImageGen originals,30 neutral displays and11 technical derivatives.</p><p><a href="REVIEW.json">Individual scores/hashes</a> · <a href="PROFILE.json">Exact source/transforms</a> · <a href="PROCESS_RECEIPT.json">Machine receipt</a> · <a href="../job_pan_actor_contact_study_v1_20261001/index.html">Unchanged-pose reuse failure</a> · <a href="../../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html">Every source and rejected attempt</a></p>'+''.join(cards),encoding='utf-8')
shutil.copyfile(__file__,out/'executed_record_geologist_contact_v130.py')
banner='<section id="panning-contact-current-v5"><h2>Current source review:16 originals,30 neutral fields,11 derivatives</h2><p>New connected Roshan/pan pose4.6 fixes the documented static grip gap. Existing identity/costume/pan design are the references. Both native widths directly inspected; static hand contact4.6, tabletop support4.3. Real articulated panning and full ordinary routes remain unaccepted.</p><p><a href="REVIEW_V5.json">Current individual source record</a> · <a href="../../../audit/job_pan_gripping_pose_study_v2_20261001/index.html">All6 native context views</a></p><img src="panning_contact/attempt_01/audit_aqua.png" alt="Roshan gripping the pan with both hands" style="max-width:900px;width:100%;height:auto"><p><a href="panning_contact/attempt_01/native.png">Unchanged native</a> · <a href="panning_contact/attempt_01/PROMPT.txt">Exact prompt</a> · <a href="panning_contact/attempt_01/GENERATION_RECORD.json">Provenance</a></p></section>'
p=root/'index.html';s=p.read_text();assert 'panning-contact-current-v5' not in s;i=s.index('<h1');end=s.index('</h1>',i)+5;s=s[:end]+banner+s[end:];p.write_text(s,encoding='utf-8')
lic=b/'ASSET_LICENSES.md';existing=lic.read_text()
with lic.open('a',encoding='utf-8',newline='\n') as f:
 for p in [source/'native.png',source/'audit_white.png',source/'audit_aqua.png',der]+[out/'native_views'/v['path'] for v in rows]:
  if rel(p) not in existing:f.write('\n| `'+rel(p)+'` | '+('Codex built-in ImageGen2026-10-01; owner-authorized named two-hand contact repair; existing geologist/pan reference designs' if p.parent==source else 'Godot4.7.2 exact disposable native job review capture; source/transforms in PROFILE.json')+' | '+('OpenAI generated output terms; original game art' if p.parent==source else 'Project art/capture provenance; underlying licenses retained')+' | '+('https://openai.com/policies/terms-of-use/' if p.parent==source else 'Local native review; no third-party download')+' | '+('Unmodified provider-native RGBA' if p.name=='native.png' else 'Neutral audit field only; no source repair' if p.name.startswith('audit_') else 'Uniform whole-canvas normalization only' if p==der else 'Unmodified lossless native viewport capture; no source or overlay postprocessing')+'; SHA256 '+sha(p)+' |\n')
builder=b/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v17.py';assert not builder.exists();previous=builder.with_name('build_current_job_item_register_v16.py');code=previous.read_text().replace('build_current_job_item_register_v16.py','build_current_job_item_register_v17.py').replace("geo_prefix+'/REVIEW_V4.json'","geo_prefix+'/REVIEW_V5.json'").replace('15 generated originals,28 neutral displays and10 technical derivatives','16 generated originals,30 neutral displays and11 technical derivatives');builder.write_text(code,encoding='utf-8')
ip=b/'design/audit_impacts/job-pan-painted-placement-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(p) for prefix in [root,out] for p in prefix.rglob('*') if p.is_file()}|{rel(builder),'ASSET_LICENSES.md','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/ALL_ITEMS.html','audit/job_artwork_refinement_live/STATUS.json','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v17.py'});write(ip,d)
run=subprocess.run([sys.executable,'-X','utf8','-B',str(builder)],cwd=b,capture_output=True);(b/'tmp/build_register_v17.stdout.log').write_bytes(run.stdout);(b/'tmp/build_register_v17.stderr.log').write_bytes(run.stderr);assert run.returncode==0,run.stderr.decode(errors='replace')[-800:]
counts=json.loads((b/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text())['counts']
for p in [b/'audit/job_review_v2_20261001/index.html',b/'audit/job_artwork_refinement_live/index.html']:
 s=p.read_text();banner='<section id="pan-grip-current-priority"><h2>Current pan static grip4.6 —292 directly reviewed native comparisons</h2><p>New complete geologist character/pan contact pose makes both grips clear at1280/1600. Tabletop support4.3 and real articulated panning/travel/pickup/release/return remain priorities. Current source library16 native ImageGen originals/30 neutral fields/11 whole-canvas derivatives. Every earlier attempt and score remains visible.</p><p><a href="../job_pan_gripping_pose_study_v2_20261001/index.html">All6 new illustrated grip views</a> · <a href="../job_geode_embedded_mount_v2_20261001/index.html">Crystals rooted inside the opened geode</a></p></section>';assert 'pan-grip-current-priority' not in s;i=s.index('<h1');end=s.index('</h1>',i)+5;s=s[:end]+banner+s[end:];p.write_text(s,encoding='utf-8')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Panning-grip continuation (2026-10-01): [every6 new native grip view](job_pan_gripping_pose_study_v2_20261001/index.html) directly inspected,292 total teacher/geology/pan comparisons. New connected pose retains established identity and pan design with static grip4.6; tabletop support4.3 and articulated rocking/travel/pickup/release/return remain open. [Current16 originals/30 neutral fields/11 derivatives](../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html) include every earlier draft. Known register'+str(counts['registered_items'])+' entries/'+str(counts['unique_source_files'])+' sources; incomplete all-job coverage remains explicit. No production binding, finding closure, complete route/device/child/owner/final-report approval. [Impact](../design/audit_impacts/job-pan-painted-placement-20261001.json).';s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+entry+'\n',1);master.write_text(s,encoding='utf-8')
ledger=b/'design/05_DOC_LEDGER.md';lines=ledger.read_text().splitlines();needle='| `assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html`';lines=[('| `assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html` | 🟣 | `CANDIDATE`;16 ImageGen native originals,30 neutral fields and11 whole-canvas derivatives directly reviewed. Embedded geode source4.6/isolated object4.5 provisional; new static pan grip4.6/tabletop support4.3. Every292 teacher/geology/pan comparison directly inspected. The1672×941 room remains reference-only; articulated motion, complete ordinary routes/device/child/owner/final approval remain open. |' if line.startswith(needle) else line) for line in lines];lines.append('| `audit/job_pan_gripping_pose_study_v2_20261001/index.html` | 🟣 | `CANDIDATE`; all6 new native static gripping views directly reviewed at1280/1600. Both hand/rim contacts4.6; tabletop support4.3. Whole-card displacement is an incomplete static review mechanism, not accepted panning action. Every earlier source/failed reuse opinion retained. Full routes/device/child/owner/report pending. |');ledger.write_text('\n'.join(lines)+'\n',encoding='utf-8')
findings=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text();start=s.index('\n## MA-PLAY-004\n');end=s.find('\n## ',start+1);section=s[start:end];lines=section.splitlines();hit=next(i for i,line in enumerate(lines) if line.startswith('| history |'));lines[hit]=lines[hit].rstrip().removesuffix('|').rstrip()+' 2026-10-01 new static pan grip:6 additional native views/292 total; generated connected pose4.6 resolves isolated hand/rim clarity, tabletop support4.3 and articulated rocking/travel/pickup/release/return remain priorities. `audit/job_pan_gripping_pose_study_v2_20261001/index.html` retains every view/hash. Production sources unchanged; lifecycle and full-route/device/child/owner acceptance unchanged. |';s=s[:start]+'\n'.join(lines)+'\n'+s[end:];findings.write_text(s,encoding='utf-8')
d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html'}|{rel(p) for p in out.rglob('*') if p.is_file()});d['validation'].append(dict(command='All6 new native gripping views and native/white/aqua/whole derivative directly inspected',result='PASS',evidence=rel(out/'REVIEW.json')+'; static grip4.6/tabletop4.3; inspection complete but articulated action remains unaccepted'));write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(rel(p) for prefix in [out,source] for p in prefix.rglob('*') if p.is_file());allowed.update({rel(root/'REVIEW_V5.json'),rel(root/'GENERATED_NATIVE_REGISTER_V5.json'),rel(root/'index.html')});write(allow,sorted(allowed));print(json.dumps(dict(counts=counts,direct_native_contexts=292,native_generated_sources=16)))
