from pathlib import Path
import json,datetime,hashlib,shutil,copy,html,collections,subprocess,os
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');L=R/'audit/job_artwork_refinement_live';F=R/'audit/job_geology_complete_actions_v1_20261003';P=R/'audit/job_geology_painted_invitation_fit_v1_20261003';T=R/'assets_src/imagegen/geologist_specimen_tray_v1_20261003'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat();base='1652a9bb33af0d11a594b5996df66d2266c02d39'
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
ip=R/'design/audit_impacts/job-geology-complete-action-register-20261003.json'
d=read(R/'design/audit_impacts/job-geology-complete-actions-20261003.json');d.update(id='job-geology-complete-action-register-20261003',baseline=base,scope='Extend the refreshable individually scored library with directly reviewed complete actual fossil/pan actions and one new unbound text-only tray source. Preserve exact V39 history, all originals/failures and every source/mounted/action distinction. Include all884 current complete-action frames,58 actual selected views and the independently rejected58-view counterfactual prop-fit trial. Preserve immutable S16023 anonymous byte verification in complete bounded journal shards. Update supplemental master/finding/ledger facts without lifecycle closure or acceptance transfer.',files=['audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/CURRENT_BOUNDARY_REFRESH.json','audit/job_artwork_refinement_live/all_items.html','audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/ALL_ITEMS_V39.original.json','audit/job_artwork_refinement_live/all_items_V39.original.html','audit/job_artwork_refinement_live/BOUNDARY_V39.original.json','audit/job_artwork_refinement_live/review_tools/build_geology_review_library_v445.py','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md'],validation=[dict(command='V445 exact prior register/history and literal source-boundary refresh',result='PENDING',evidence='All source and production hashes must remain literal; individual native/ordered-frame review is separate.')],acceptance_gaps='377 source reviews and broad actual-use/ordinary-route discovery remain; current fossil3.2/pan3.4/contact2.7/room2.8 and Nursery wholewash3.9 remain weak. New tray source4.6 and counterfactual material4.5 are unbound. Device/child/owner/comprehensive all-job/integration/release and both pending exact auto-review approval actions remain open.')
write(ip,d)
for source,dst in [('ALL_ITEMS.json','ALL_ITEMS_V39.original.json'),('all_items.html','all_items_V39.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V39.original.json')]:
 if (L/dst).exists():assert sha(L/source)==sha(L/dst),'Resume requires exact unchanged V39 current and historical bytes'
 else:shutil.copyfile(L/source,L/dst)
shutil.copyfile(Path(__file__),L/'review_tools'/Path(__file__).name)
reg=read(L/'ALL_ITEMS.json');assert len(reg['items'])==1802;byid={x['id']:x for x in reg['items']}
freview=read(F/'DIRECT_REVIEW.json');assert freview['consecutive_frames']==884 and all(x['direct_review'] for x in freview['frames']+freview['views'])
assert {x['path']:x['sha256'] for x in read(F/'SOURCE_CURRENT_BEFORE_CAPTURE.json')['source_files']}=={x['path']:x['sha256'] for x in read(R/'audit/job_geode_current_recheck_v1_20261002/SOURCE_CURRENT_BEFORE_CAPTURE.json')['source_files']}
work='assets/opera/worlds/geology/painted_work_v1_20261001/'
existing=len(byid);new=0
for op in freview['individual_objects']:
 id=op['id'];w='1280';view=freview['views'][op['evidence_view_index']];assert view['viewport'][0]==1280
 if id in byid:
  q=byid[id];q.setdefault('mounted_review_history',[]).append({k:copy.deepcopy(q.get(k)) for k in ['current_mounted_score','current_complete_action_score','evaluation','refinement','current_capture_review','current_reviewed_utc','image_path','source_qualification']})
 else:
  image='pan.png' if id.startswith('GEO-PAN') else 'fossil.png';path=work+image
  # Find the exact already registered painted source; no new image identity invented.
  candidates=[x for x in reg['items'] if x['path']==path];assert candidates,path
  src=candidates[0];q=dict(id=id,aliases=[id],kind='runtime prop region',path=path,earlier_sha256=sha(R/path),current_checkout_sha256=sha(R/path),current_byte_status='EXACT_EARLIER_BYTES',source_dimensions=src['source_dimensions'],historical_source_score=None,current_source_score=None,preview_path=path,native_reference_observations=[],protected_original=False,original_reports=[],families=['Geologist',op['label']],owner_acceptance=None,current_binding='scripts/opera_geology_surface.gd',binding_sha256=sha(R/'scripts/opera_geology_surface.gd'));reg['items'].append(q);byid[id]=q;new+=1
 q.update(label=op['label'],current_mounted_score=op['score'],current_complete_action_score=op['score'] if op['lane'] in ['complete_action','complete_component_action','complete_transition','mounted_object_and_drag'] else None,priority=op['priority'],evaluation=op['evaluation'],refinement=op['refinement'],image_path=view['path'],image_scope='Actual complete native canvas; named material/object/action lane is separately scored.',source_qualification=freview['qualification'],current_capture_review='audit/job_geology_complete_actions_v1_20261003/DIRECT_REVIEW.json',current_reviewed_utc=now,capture_family='geode_current_v1',owner_acceptance=None,latest_refinement=dict(report='audit/job_geology_complete_actions_v1_20261003/index.html#'+id,note=op['evaluation']))
 q['original_reports']=list(dict.fromkeys(q['original_reports']+[q['latest_refinement']['report']]))
assert new==18 and len(reg['items'])==1820
tray='assets_src/imagegen/geologist_specimen_tray_v1_20261003/attempt01/native.png';assert sha(R/tray)=='6d91458161f5d234354293c1836fe26b07306377916cd18ec59e785fd76a5cbb'
reg['items'].append(dict(id='GEO-TRAY-SOURCE-01',aliases=[],kind='source',path=tray,label='Fresh painted hollow specimen tray',source_dimensions=[1254,1254],earlier_sha256=sha(R/tray),current_checkout_sha256=sha(R/tray),current_byte_status='EXACT_EARLIER_BYTES',historical_source_score=4.6,latest_source_score=4.6,current_source_score=4.6,current_mounted_score=None,current_complete_action_score=None,priority=False,evaluation='Fresh text-only complete painted source4.6 provisional; rim/style/perspective4.6, full alpha contour4.5 and110px counterfactual readability4.5. A1 actual prop-fit trial layout3.5 is rejected independently; current flat runtime trays remain2.9. Native preserved unchanged and unbound.',refinement='Keep source; review all reserved lower placements, normalize whole canvas to<=1024 before any runtime import and establish current in-game evidence after binding.',families=['Geologist','Fresh unbound specimen tray'],original_reports=['assets_src/imagegen/geologist_specimen_tray_v1_20261003/index.html'],source_qualification='PROVISIONAL_STATIC_SOURCE_ONLY_UNBOUND;6 individual component opinions. Exact native/generated/prompt hashes and license recorded. No blocked old Nursery reference upload.',preview_path=tray,image_path=tray,image_scope='Complete fresh native source; painted-tray source opinions only.',latest_refinement=dict(report='assets_src/imagegen/geologist_specimen_tray_v1_20261003/index.html',note='Six individual source opinions plus separately qualified counterfactual trial.'),native_reference_observations=[],protected_original=False,owner_acceptance=None))
a=reg['items'];c=reg['counts'];c.update(unique_source_files=sum(x['kind'] in ['source','runtime source'] for x in a),individual_pose_cells=sum(x['kind']=='pose cell' for x in a),additional_runtime_prop_regions=sum(x['kind'] in ['runtime prop region','runtime use/action'] for x in a),individual_source_object_regions=sum(x['kind']=='source object region' for x in a),registered_items=len(a),exact_earlier_bytes=sum(x['current_byte_status']=='EXACT_EARLIER_BYTES' for x in a),inclusive_current_source_priorities=sum(x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3'] and x['current_source_score'] is not None and x['current_source_score']<=4.5 for x in a),unique_source_file_priorities=sum(x['kind'] in ['source','runtime source'] and x['current_source_score'] is not None and x['current_source_score']<=4.5 for x in a),current_geode_mounted_priorities=sum(x.get('capture_family')=='geode_current_v1' and x['current_mounted_score'] is not None and x['current_mounted_score']<=4.5 for x in a),unreviewed_current_source=sum(x['kind'] in ['source','runtime source'] and x['current_source_score'] is None for x in a),new_fresh_geologist_tray_sources=1)
assert c['unique_source_files']==1264 and c['additional_runtime_prop_regions']==103 and c['registered_items']==1821 and c['current_geode_mounted_priorities']==38
reg.update(updated_utc=now,display_revision='V40_COMPLETE_CURRENT_FOSSIL_PAN_AND_FRESH_TRAY',scope='V40 known register:1264 unique source files+328 pose cells+103 runtime state/use/action entries+126 source object regions=1821.713 inclusive source/cell/region priorities (572 unique source files including two runtime-source entries),38 current Geologist priorities,10 Nursery priorities and377 source reviews outstanding. All884 actual complete fossil/pan frames and58 actual selected canvases directly reviewed: whole fossil3.2/pan3.4/contact2.7. One new text-only tray source4.6/110px counterfactual4.5 remains unbound; failed A1 layout3.5 preserved. All783 production bytes unchanged; no source-to-action/owner acceptance transfer.',qualification='713 is the known source/cell/region inclusive<=4.5 priority count;38 Geologist and10 Nursery current mounted/action priorities are separate.572 unique source-file priorities (570 primary-source entries plus two runtime-source entries) and377 source reviews remain. A score4.5 meets the provisional floor and still remains an inclusive priority. Complete action opinions are now present for the exact captured actual fossil/pan route only, not ordinary story/alljobs/device/child/owner acceptance. Native materials can pass while contact/action fails. Every earlier original opinion/history, rejected source/motion/fit and both pending upload/status approvals are retained. Hash refresh detects changes but does not play, review or generate. Reference/capture frames never inflate source-item counts.')
for path,scope in [('audit/job_geology_complete_actions_v1_20261003/index.html','All884 consecutive actual complete fossil/pan frames,58 selected actual views and22 individual object/action opinions.'),('assets_src/imagegen/geologist_specimen_tray_v1_20261003/index.html','One fresh text-only painted tray source and6 component opinions; provisional4.6 and unbound.'),('audit/job_geology_painted_invitation_fit_v1_20261003/index.html','Separate non-runtime prop-fit trials;A1 layout3.5 rejected, individual material floors do not approve current production.')]:reg['review_resources'].append(dict(path=path,scope=scope))
write(L/'ALL_ITEMS.json',reg)
s=(L/'all_items.html').read_text();insert='<p><a href="../job_geology_complete_actions_v1_20261003/index.html">Complete current fossil and panning review: every884 frame,58 selected canvases and22 individual opinions</a>. Fossil3.2/pan3.4/contact2.7 remain priorities. <a href="../../assets_src/imagegen/geologist_specimen_tray_v1_20261003/index.html">Fresh painted tray source4.6</a> and <a href="../job_geology_painted_invitation_fit_v1_20261003/index.html">separate reversible prop-fit trials</a> remain unbound. All783 production sources unchanged.</p>'
s=s.replace('</header>',insert+'</header>',1).replace('23 inclusive state/use/action priorities remain; flat room2.8/contact2.7 are not approved by the improved geode.','That dated27-opinion recheck is retained. V40 has45 current Geologist opinions/38 inclusive priorities after the complete fossil/pan review; flat room2.8/contact2.7 remain weak.')
(L/'all_items.html').write_text(s,encoding='utf-8',newline='\n')
p=L/'index.html';s=p.read_text();s=s.replace('</header>',insert+'</header>',1) if '</header>' in s else s.replace('</main>',insert+'</main>',1);p.write_text(s,encoding='utf-8',newline='\n')
# Exact immutable parent verification; reconstruct complete journal, never truncate.
out=F/'previous_s_remote_verified';out.mkdir(exist_ok=False);src=R/'tmp/nursery_review_s_remote_v432';result=read(src/'RESULT.json');assert result['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and result['files_including_manifest']==16023 and result['revision']==base
shutil.copyfile(src/'RESULT.json',out/'RESULT.json');raw=(src/'VERIFICATION_JOURNAL.jsonl').read_bytes();lines=raw.splitlines(keepends=True);assert len(lines)==16023 and b''.join(lines)==raw
parts=[];buf=bytearray()
def flush():
 if not buf:return
 path=out/f'JOURNAL_{len(parts)+1:03d}.jsonl';path.write_bytes(buf);parts.append(dict(path=path.relative_to(R).as_posix(),bytes=len(buf),sha256=sha(path)));buf.clear()
for line in lines:
 if len(buf)+len(line)>900000:flush()
 buf.extend(line)
flush();assert b''.join((R/x['path']).read_bytes() for x in parts)==raw
write(out/'JOURNAL_INDEX.json',dict(status='EXACT_COMPLETE_ORDERED_JOURNAL_RECONSTRUCTION',literal_original_bytes=len(raw),literal_original_sha256=hashlib.sha256(raw).hexdigest(),rows=len(lines),parts=parts,qualification='Concatenate listed shard bytes in listed order. Every S16023 anonymous verification row retained. No payload hashes or dates changed. Publication evidence only.'))
shutil.copyfile(R/'tmp/nursery_review_s_publish_v432/HOSTED_R_FINAL.json',out/'HOSTED_R_FINAL.json')
def rel(p):return p.relative_to(R).as_posix()
def link(page,path):return os.path.relpath(R/path,page.parent).replace('\\','/')
css='body{margin:0;background:#edf4fa;color:#28334b;font:17px/1.5 system-ui}main{max-width:1440px;margin:auto;padding:24px}header,article,section{background:white;border-radius:16px;padding:22px;margin:18px 0}a{color:#514196}img{display:block;max-width:100%;height:auto;margin:auto}figure{margin:10px 0}figcaption,small{display:block;color:#526076}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #d3deea;text-align:left;vertical-align:top;padding:12px}code,pre{font-size:12px;overflow-wrap:anywhere;white-space:pre-wrap}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:18px}.grid article{margin:0}button,input,select{font:inherit;padding:8px}.priority{color:#914515}.provisional{color:#327267}'
def start(title,lead):return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+'</title><style>'+css+'</style><main><header><a href="../job_artwork_refinement_live/all_items.html">Individual review library</a><h1>'+title+'</h1><p>'+lead+'</p></header>'
def image(page,path,caption):return '<figure><a href="'+html.escape(link(page,path))+'"><img loading="lazy" src="'+html.escape(link(page,path))+'" alt="'+html.escape(caption)+'"></a><figcaption>'+html.escape(caption)+'</figcaption></figure>'
def opinions(rows,page,views=None):
 out='<section><h2>Individual evaluations</h2><p>Drafting scores;<=4.5 remains a refinement priority. Source/material, placement and full action are independent. Owner approval remains pending.</p><div class="grid">'
 for r in rows:
  out+='<article id="'+html.escape(r['id'])+'"><h3>'+html.escape(r.get('label',r.get('item',r['id'])))+'</h3><p><strong>'+str(r['score'])+'/5</strong> · '+html.escape(r.get('lane','source only'))+'</p><p>'+html.escape(r['evaluation'])+'</p><p>'+html.escape(r.get('refinement',''))+'</p>'
  if views is not None:out+=image(page,views[r['evidence_view_index']]['path'],'Exact1280 native context: '+r['label'])
  out+='</article>'
 return out+'</div></section>'
page=F/'index.html';body=start('Geologist: complete fossil and panning actions','Every884 consecutive native input/wait frame and58 selected complete canvases inspected at1280/1600,85 ordered boards and34 complete native details. Fossil3.2/5,pan3.4/5,working hands2.7/5. All783 actual production sources unchanged. These are actual normal Library/all4 earned phases/return and Opera elevator replay captures; readback slows timing. Ordinary story/device/child/owner/all-job acceptance remains open.')
body+='<section><h2>What the full sequence reveals</h2><p>The painted soil, fossil, bowl and crystals are strong reusable materials. Brushing clears a grid; the intact fossil suddenly changes into three straight strips. Panning translates an unchanged oval, removes grains in steps and adds complete clusters at reversals3,6,9. Roshan stays remote at the left. These failed relationships remain individually addressable below.</p><p>The geode still opens to reveal rooted crystals in its two halves and holds on its painted support. Its earlier318-frame opening-to-return review remains unchanged. This new report fills fossil/pan timing coverage without transferring the good geode or material score to the whole job.</p><p><a href="DIRECT_REVIEW.json">Every individual frame/view/opinion/hash</a> · <a href="CAPTURE_RETRY_PLAN_V436.json">Preserved first capture failure and strict actual-event helper retry</a> · <a href="previous_s_remote_verified/RESULT.json">Previous exact S16023-file anonymous remote receipt</a></p></section>'
body+=opinions(freview['individual_objects'],page,freview['views'])
body+='<section><h2>All58 selected actual states</h2><div class="grid">'
for x in freview['views']:body+='<article>'+image(page,x['path'],str(x['viewport'][0])+'px · '+x['state']+' · canvas '+str(x['whole_canvas_score'])+'/5')+'<code>'+x['sha256']+'</code></article>'
body+='</div></section><section><h2>Every consecutive actual frame</h2><p>Every captured frame is shown and links to its untouched native full canvas. Recorded timestamps describe the slowed readback fixture, not ordinary device timing. Per-frame canvas scores describe the visible state; full action scores also judge neighboring continuity and contact.</p>'
for w in [1280,1600]:
 frames=[x for x in freview['frames'] if x['width']==w];body+='<details><summary>'+str(w)+'px: every'+str(len(frames))+' consecutive frame</summary><div class="grid">'
 for x in frames:body+='<article>'+image(page,x['path'],str(w)+' #'+str(x['index'])+' · '+x['beat']+' · '+str(x['whole_canvas_score'])+'/5')+'<p>'+html.escape(x['frame_evaluation'])+'</p><code>'+x['sha256']+'</code></article>'
 body+='</div></details>'
body+='</section><section><h2>Evidence boundaries</h2><p>Failed attempt01 retains449 images and its failing receipt; it was not promoted or counted among the884 successful retry frames. The stale end-of-pan assertion observed a reused next-phase surface after slow readback. The helper retry records the real intentional gesture and completion/pending state before reuse. No production phase, input, reward, save or timing change was made.</p><p>The existing official4.7.2 local82/82 machine receipt remains separately source-bound to783 unchanged members and all53 raw diagnostics. Fresh helper parser/inference/analyzer and both-width capture gates pass. A green machine check does not pass graphics, strict-zero2D debt, device, child, owner or release.</p></section></main></html>';page.write_text(body,encoding='utf-8',newline='\n')
page=T/'index.html';tr=read(T/'attempt01/DIRECT_SOURCE_REVIEW.json');gen=read(T/'attempt01/GENERATION.json');body=start('Geologist: painted specimen tray source','One fresh text-only ImageGen source after relevant reuse inventory. Native4.6 provisional; alpha/contour4.5 and110px counterfactual readability4.5. Current flat trays2.9 remain; source unbound. No existing image was uploaded.')
body=body.replace('../job_artwork_refinement_live/all_items.html',link(page,'audit/job_artwork_refinement_live/all_items.html'))
body+='<section>'+image(page,tray,'Exact1254×1254 native RGBA; click for original bytes')+'<p><a href="PROMPT.txt">Exact generation prompt</a> · <a href="attempt01/GENERATION.json">Generation, native/prompt hashes and provenance</a> · <a href="PLAN.json">Reuse inventory and named gap</a> · <a href="'+link(page,'audit/job_geology_painted_invitation_fit_v1_20261003/index.html')+'">Independent placement trials</a></p><code>'+sha(R/tray)+'</code></section>'+opinions(tr['opinions'],page)+'<section><p>Original generated pixels are unchanged. The native remains non-runtime; its actual alpha>=2 subject and shadow are addressed with a10px-margin AtlasTexture region only in the review fixture. Remote alpha1 haze is outside that source window. No alpha mask, repair, cinematic delivery or runtime normalization is claimed. Source selection does not approve actor clearance or complete action.</p></section></main></html>';page.write_text(body,encoding='utf-8',newline='\n')
page=P/'index.html';pr=read(P/'DIRECT_REVIEW_ATTEMPT01.json');pb=read(P/'QA_BOARD_MANIFEST.json');a2=read(P/'DIRECT_REVIEW_ATTEMPT02.json');body=start('Geologist: reversible painted prop placement trials','Review-only Library backdrop substitution; production sources/code are unchanged. A1 layout3.5 rejected for actor overlap. A2 lower placement clears the actor in all eight native invitations: selected clearance4.5, support scale3.8 and whole composition4.0. Both trials remain unbound and separately preserved.')
body+='<section><p>Exact failed A1 helper sources and all58 selected canvases are preserved. The actual Opera developer second entry deliberately uses unchanged production, and is not candidate-placement evidence. Painted materials may pass while staging fails. No owner approval or in-game repair is inferred.</p><p><a href="DIRECT_REVIEW_ATTEMPT01.json">A1 eleven individual opinions</a> · <a href="LOWER_FIT_PLAN_V443.json">A2 bounded placement plan</a></p></section>'+opinions(pr['individual_objects'],page)+'<section><h2>Every58 selected A1 full canvas</h2><div class="grid">'
for b in pb['boards']:
 for x in b['members']:body+='<article>'+image(page,x['path'],str(b['width'])+'px · '+x['state']+' · A1 rejected layout')+'<code>'+x['sha256']+'</code></article>'
body+='</div></section><section><h2>A2: lower placement</h2><p>All58 selected canvases on10 boards plus8 complete native invitation canvases directly reviewed. The source materials retain their floor, and selected actor clearance improves. The oversized support remains3.8 and flat room2.8; whole composition4.0. Production and intervening motion remain independently unapproved.</p><a href="DIRECT_REVIEW_ATTEMPT02.json">Every A2 opinion and selected view</a></section>'+opinions(a2['individual_objects'],page)+'<section><h2>All58 selected A2 canvases</h2><div class="grid">'
for x in a2['views']:body+='<article>'+image(page,x['path'],str(x['viewport'][0])+'px · '+x['state']+' · A2 selected view')+'<code>'+x['sha256']+'</code></article>'
body+='</div></section><section><p>The flat room2.8, live working contact2.7, complete fossil3.2 and pan3.4 remain separate priorities. No complete counterfactual invitation-motion/device/child/owner pass is claimed from selected canvases.</p></section></main></html>';page.write_text(body,encoding='utf-8',newline='\n')
note='Complete current Geologist action continuation (2026-10-03): [all884 consecutive actual fossil/pan frames,58 selected canvases and22 individual evaluations](job_geology_complete_actions_v1_20261003/index.html) directly reviewed at1280/1600 on85 ordered boards plus34 native details. Whole fossil3.2/pan3.4/working contact2.7 fail; materials4.5–4.6 remain reusable. Geode rooted opening/support unchanged. [One fresh text-only tray source](../assets_src/imagegen/geologist_specimen_tray_v1_20261003/index.html)4.6 provisional/110px counterfactual4.5 remains unbound; first58-view placement trial3.5 rejected for actor overlap and preserved. V40 holds1821 known entries/713 source-cell-region priorities/38 Geologist/10 Nursery priorities/377 source reviews outstanding; all783 production bytes unchanged. Actual Library/elevator fixture/readback bounds, both pending exact upload/status approvals, complete actual-use/ordinary-route/device/child/owner/all-job/integration/release and finding lifecycle gaps remain open. Complete S16023 anonymous immutable byte-verification receipt/journal retained in bounded reconstructible shards.'
mp=R/'audit/MASTER_AUDIT_2026-08-09.md';s=mp.read_text();assert '## 0. Planning entry\n' in s;s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+note+'\n',1);mp.write_text(s,encoding='utf-8',newline='\n')
fp=R/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=fp.read_text();lines=s.splitlines();lines.insert(2,note.replace('(job_geology','(../job_geology').replace('(../assets_src','(../../assets_src'));fp.write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
lp=R/'design/05_DOC_LEDGER.md';s=lp.read_text();s+='\n| `audit/job_geology_complete_actions_v1_20261003/DIRECT_REVIEW.json` | 🟢 | `SUPPORTING_CURRENT`; all884 complete actual fossil/pan frames/58 selected canvases,22 individual opinions. Fossil3.2/pan3.4/contact2.7 remain weak; exact783 production sources unchanged. No lifecycle or external acceptance. |\n| `assets_src/imagegen/geologist_specimen_tray_v1_20261003/attempt01/DIRECT_SOURCE_REVIEW.json` | 🟢 | `SUPPORTING_CURRENT`; one new text-only unbound tray native4.6/alpha4.5/110px counterfactual4.5,6 opinions; source selection does not pass staging/action. |\n| `audit/job_geology_painted_invitation_fit_v1_20261003/DIRECT_REVIEW_ATTEMPT01.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact58-view non-runtime A1 trial3.5 rejected for actor overlap,11 separate material/layout opinions. Preserved fixture/native bytes; current production unchanged. |\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V39.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact1802-entry register before complete fossil/pan action evidence and new tray source. |\n'
lp.write_text(s,encoding='utf-8',newline='\n')
for packet,impact in [(F,'job-geology-complete-actions-20261003.json'),(T,'job-geology-specimen-tray-20261003.json'),(P,'job-geology-painted-invitation-fit-20261003.json')]:
 p=R/'design/audit_impacts'/impact;d=read(p);d['files']=sorted(set(d['files'])|{rel(x) for x in packet.rglob('*') if x.is_file()});write(p,d)
d=read(ip);d['files']=sorted(set(d['files'])|{rel(x) for x in out.rglob('*') if x.is_file()});write(ip,d)
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B','audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v35.py'],cwd=R,check=True,creationflags=subprocess.CREATE_NO_WINDOW)
stamp=read(L/'CURRENT_BOUNDARY_REFRESH.json');assert stamp['status']=='CURRENT_CAPTURE_BOUNDARIES_MATCH' and stamp['registered_source_matches']==1821 and stamp['geode_capture_source_count']==783
print(json.dumps(c));print('V40_PAGES_AND_REGISTER_SOURCE_BOUND|ALL1821_ITEM_HASHES/ALL783_PRODUCTION_BOUNDARY_MATCH|OWNER_PENDING')
