from pathlib import Path
import datetime,hashlib,html,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef'); f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002'; prefix=f.relative_to(b).as_posix(); live=b/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest(); now=datetime.datetime.now(datetime.timezone.utc).isoformat(); esc=html.escape
reviews=[read(p) for p in sorted(f.glob('attempt_*/REVIEW.json'))]; assert len(reviews)==9
gallery=''; source_entries=[]; cells=[]
for r in reviews:
 path=r['native_path']; assert sha(b/path)==r['sha256']; n=int(Path(path).parent.name[-2:]); w,h=r['dimensions']; cols=4 if n in [1,2] else 2 if n==10 else 3; rows=1 if n==10 else 2
 whole_score=r.get('sheet_score',r.get('unmounted_sequence_score'))
 source_entries.append(dict(id='GEO-COHERENT-SOURCE-A'+str(n),path=path,score=whole_score,dimensions=[w,h],kind='source',region=None,evaluation=r['qualification'],report=prefix+'/attempt_%02d/REVIEW.json'%n))
 gallery+='<h2>Attempt '+str(n)+' · '+esc(r['status'])+'</h2><figure><a href="attempt_%02d/native.png">'%n+'<img class="whole" src="attempt_%02d/native.png"'%n+' alt="Native complete attempt '+str(n)+'"></a><figcaption>Complete source score '+str(whole_score)+'/5 · SHA256 '+r['sha256']+'<p>'+esc(r['qualification'])+'</p><a href="attempt_%02d/REVIEW.json">Every individual opinion</a> · <a href="attempt_%02d/PROMPT.txt">Exact built-in prompt</a> · <a href="attempt_%02d/GENERATION.json">Native/reference provenance</a></figcaption></figure><div class="cells">'%(n,n,n)
 for x in r['cells']:
  x=dict(x); x['native_path']=path; x['sha256']=r['sha256']; x['report']=prefix+'/attempt_%02d/REVIEW.json'%n; cells.append(x); rect=x['source_rect']; region=[rect[0],rect[1],rect[2]-rect[0],rect[3]-rect[1]]
  source_entries.append(dict(id=x['id'],path=path,score=x['score'],dimensions=[w,h],kind='source object region',region=region,evaluation=x['evaluation'],report=x['report']))
  col=x['state_index']%cols; row=x['state_index']//cols
  gallery+='<article id="'+esc(x['id'])+'"><h3>'+esc(x['id'])+' · '+str(x['score'])+'/5</h3><figure class="region" style="aspect-ratio:'+str(region[2])+'/'+str(region[3])+'"><img src="attempt_%02d/native.png"'%n+' alt="'+esc(x['id'])+'" style="position:absolute;max-width:none;width:'+str(cols*100)+'%;height:'+str(rows*100)+'%;left:'+str(-col*100)+'%;top:'+str(-row*100)+'%"></figure><p>'+esc(x['evaluation'])+'</p><small>Exact source region '+esc(json.dumps(region))+' · material '+str(x.get('material_score','—'))+'/5; owner acceptance pending</small></article>'
 gallery+='</div>'
assert len(cells)==54
for x in read(f/'NORMALIZATION.json')['atlases']:
 assert sha(b/x['path'])==x['sha256']; n=int(Path(x['path']).parent.name[-2:]); source_entries.append(dict(id='GEO-COHERENT-POT-A'+str(n),path=x['path'],score=4.5,dimensions=x['dimensions'],kind='source',region=None,evaluation=x['method']+' Each selected source cutout reaches4.5 provisional; whole-canvas derivative does not establish mounted sequence/contact.',report=prefix+'/NORMALIZATION.json'))
write(f/'REVIEW.json',dict(status='ALL9_RETURNED_NATIVE_SHEETS_AND54_INDIVIDUAL_STATES_REVIEWED',reviewed_utc=now,source_reviews=reviews,individual_states=cells,selection='SELECTED_PILOT_STATES.json',normalization='NORMALIZATION.json',failed_no_image='attempt_09/FAILURE.json',qualification='Every source trial and exact prompt retained. A8 six cutouts/source4.5 plus A10 selected bridge4.5 form a seven-state non-runtime pilot. First A10 requested bridge geometry3.9 is excluded. A1/A2/A3/A5/A6/A7 rejected boundaries remain. A4 material4.6 is opaque/unmounted sequence4.4. Residual edge quality at4.5 remains inclusive priority. Current production geode continuous4.2 remains separate; pilot action/device/child/owner/global acceptance pending.'))
(f/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geode authored opening source library</title><style>body{margin:0;background:#eef4fa;color:#25304a;font:17px/1.5 system-ui}main{max-width:1460px;margin:auto;padding:24px}figure,article{background:white;padding:18px;border-radius:14px;margin:0;min-width:0}figure{margin-bottom:18px}.whole{width:100%;height:auto;display:block}.cells{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.region{position:relative;overflow:hidden;padding:0;background:repeating-conic-gradient(#dce5ed 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}small{font-size:12px;overflow-wrap:anywhere;display:block}</style><main><a href="../../../audit/job_artwork_refinement_live/all_items.html">All known job items</a><h1>Geode opening: every authored trial and individual state</h1><p>Nine returned native sheets,54 individually reviewed states and two complete-canvas derivatives. One additional tool attempt returned no image; its failure receipt is preserved. All built-in prompts, exact references, hashes and rejections remain inspectable.</p><p>Six A8 cutouts and the selected A10 bridge reach the provisional4.5 source floor. This is a seven-state non-runtime mounted pilot. Source quality does not pass complete-action continuity, hand contact, production binding, device, child or owner review. Current actual game opening remains4.2 until separately repaired/reviewed.</p><p><a href="REVIEW.json">Complete written source library</a> · <a href="SELECTED_PILOT_STATES.json">Seven exact selected atlas regions</a> · <a href="../../../audit/job_geode_coherent_pilot_v1_20261002/index.html">Mounted pilot evidence</a> · <a href="../../../audit/job_geology_river_runtime_v1_20261002/timed.html">Current actual production opening4.2</a></p>'+gallery+'<h2>Complete-canvas POT derivatives for pilot</h2>'+''.join('<figure><a href="attempt_%02d/whole_canvas_2048x1024.png">'%n+'<img class="whole" src="attempt_%02d/whole_canvas_2048x1024.png"'%n+' alt="Complete POT derivative A'+str(n)+'"></a><figcaption>Uniform entire-canvas scale only; native original preserved, no alpha cleanup; <a href="NORMALIZATION.json">provenance</a></figcaption></figure>' for n in [8,10])+'</main></html>',encoding='utf-8',newline='\n')
old=read(live/'ALL_ITEMS.json'); assert old['counts']['registered_items']==1647
shutil.copyfile(live/'ALL_ITEMS.json',live/'ALL_ITEMS_V26.json'); (live/'all_items_V26.html').write_text((live/'all_items.html').read_text(encoding='utf-8').replace('ALL_ITEMS.json','ALL_ITEMS_V26.json'),encoding='utf-8',newline='\n')
for x in source_entries:
 score=x['score']; item=dict(id=x['id'],aliases=[x['id']],kind=x['kind'],path=x['path'],region=x['region'],earlier_sha256=sha(b/x['path']),historical_source_score=score,evaluation=x['evaluation'],refinement='Preserve original/rejected source. Inclusive4.5 priority remains; inspect selected source geometry, complete mounted opening and contact separately.',families=['Geologist','Authored coherent opening source trial'],original_reports=[x['report'],prefix+'/index.html'],source_qualification='Direct native source/cell review; source floor does not prove mounted/action/device/child/owner acceptance.',preview_path=x['path'],native_reference_observations=[],current_checkout_sha256=sha(b/x['path']),current_byte_status='EXACT_REVIEWED_SOURCE_BYTES',current_source_score=score,source_dimensions=x['dimensions'],priority=score<=4.5,protected_original=False,current_mounted_score=None,current_complete_action_score=None,image_path=x['path'],image_scope='Native whole source' if x['kind']=='source' else 'Exact native source region rendered by CSS; original pixels preserved')
 old['items'].append(item)
old['created_utc']=now; old['scope']='Union of known Day One/Day Two discovery sources,328 pose cells,38 runtime prop regions and104 individually reviewed source-object regions, including every authored geode source trial. Not proof of exhaustive actual use, all-job action or owner acceptance.'
old['counts'].update(unique_source_files=len({x['path'] for x in old['items']}),individual_source_object_regions=104,registered_items=len(old['items']),inclusive_current_source_priorities=sum(x['priority'] for x in old['items']),unreviewed_current_source=sum(x['current_source_score'] is None for x in old['items']))
old['counts']['exact_earlier_bytes']+=len(source_entries)
write(live/'ALL_ITEMS.json',old)
assert old['counts']['registered_items']==1712
(live/'all_items.html').write_text((live/'all_items.html').read_text(encoding='utf-8').replace('50 source-object','104 source-object'),encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s+='\n| '+chr(96)+prefix+'/index.html'+chr(96)+' | 🟣 | '+chr(96)+'CANDIDATE'+chr(96)+'; nine returned native geode sheets/54 individually scored states/two whole-canvas derivatives, all rejected trials and one no-image tool failure preserved. Seven selected authored cutouts provisional source4.5; non-runtime mounted/continuous/action/owner acceptance separate. | \n'
s='\n'.join('| '+chr(96)+'audit/job_artwork_refinement_live/all_items.html'+chr(96)+' | 🟣 | '+chr(96)+'CANDIDATE'+chr(96)+'; currentV27 known register1712 entries/1242 source files/328 pose cells/38 runtime regions/104 source regions. Inclusive'+str(old['counts']['inclusive_current_source_priorities'])+' source priorities and388 unassigned remain. Every geode trial/source region included; mounted/action/device/child/owner/global acceptance separate. |' if 'audit/job_artwork_refinement_live/all_items.html' in row and row.startswith('|') else row for row in s.split('\n'));p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name); shutil.copyfile(__file__,live/'review_tools/build_current_job_item_register_v27.py')
for name,folder in [('job-geode-coherent-opening-20261002',f),('job-geology-river-painted-runtime-20261002',b/'audit/job_geology_river_runtime_v1_20261002')]:
 ip=b/('design/audit_impacts/'+name+'.json');d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in folder.rglob('*') if p.is_file()}|{p.relative_to(b).as_posix() for p in live.rglob('*') if p.is_file()}|{'design/05_DOC_LEDGER.md','ASSET_LICENSES.md'});write(ip,d)
p=b/'tmp/v2_preview_allowed.json';write(p,sorted(set(read(p))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{p.relative_to(b).as_posix() for p in live.rglob('*') if p.is_file()}))
print(json.dumps(old['counts']))
