from pathlib import Path
import json,hashlib,datetime,shutil,subprocess,time
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');L=R/'audit/job_artwork_refinement_live';F=R/'audit/job_geology_complete_actions_v1_20261003';p=L/'ALL_ITEMS.json'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda b:hashlib.sha256(b).hexdigest();raw=p.read_bytes();old=json.loads(raw);assert len(raw)>4194304 and len(old['items'])==1821
failed=read(F/'gates/game2d.receipt.json');assert failed['status']=='FAIL_PRESERVED'
out=L/'registry_format_history_v40';out.mkdir(exist_ok=False);parts=[]
for i in range(0,len(raw),900000):
 dest=out/f'ALL_ITEMS_V40.over_budget.part{i//900000+1:02d}.txt';chunk=raw[i:i+900000];dest.write_bytes(chunk);parts.append(dict(path=dest.relative_to(R).as_posix(),bytes=len(chunk),sha256=sha(chunk)))
assert b''.join((R/x['path']).read_bytes() for x in parts)==raw
compact=(json.dumps(old,separators=(',',':'),ensure_ascii=False)+'\n').encode('utf-8');assert json.loads(compact)==old and len(compact)<4194304;p.write_bytes(compact)
receipt=L/'REGISTRY_FORMAT_REPAIR_V457.json';write(receipt,dict(status='IDENTICAL_COMPLETE_STRUCTURED_REGISTER_COMPACTED',checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),prior_bytes=len(raw),prior_literal_sha256=sha(raw),current_bytes=len(compact),current_literal_sha256=sha(compact),registered_items=1821,structured_objects_equal=True,existing_scan_limit_bytes=4194304,scan_limit_changed=False,source_or_score_change=False,failed_gate='audit/job_geology_complete_actions_v1_20261003/gates/game2d.receipt.json',prior_exact_reconstruction=parts,qualification='Only JSON whitespace outside strings changes. Every field, opinion, date, number, source hash and image remains equal. Concatenate listed prior shard bytes in order for exact over-budget preformat bytes. Complete failed gate retained; no detector/manifest/security/gate weakening or 3D addition.'))
ip=R/'design/audit_impacts/job-geology-complete-action-register-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{x['path'] for x in parts}|{receipt.relative_to(R).as_posix(),(L/'review_tools'/Path(__file__).name).relative_to(R).as_posix()});d['validation'].append(dict(command='Complete structured JSON equality before/after compact formatting',result='PASS',evidence=receipt.relative_to(R).as_posix()));d['scope']+=' Compact only current register JSON whitespace after its4.21MB size exceeded the unchanged4MiB signature-scan budget. Preserve exact preformat bytes in reconstructible <=900k shards and all failed gate outputs. Every1821 record and all values remain equal; no scan-limit/detector/debt-manifest relaxation.';write(ip,d);shutil.copyfile(Path(__file__),L/'review_tools'/Path(__file__).name)
G=F/'gates';label='game2d_compact_v2';args=['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B','tools/audit_game_2d.py','--regression-gate'];ip2=R/'design/audit_impacts/job-geology-complete-actions-20261003.json';d=read(ip2);d['files']=sorted(set(d['files'])|{(G/(label+'.'+ext)).relative_to(R).as_posix() for ext in ['stdout.log','stderr.log','receipt.json']});write(ip2,d)
start=datetime.datetime.now(datetime.timezone.utc).isoformat();tick=time.monotonic();outputs=[G/(label+'.'+ext) for ext in ['stdout.log','stderr.log']];assert not any(x.exists() for x in outputs)
with outputs[0].open('wb') as o,outputs[1].open('wb') as e:result=subprocess.run(args,cwd=R,stdout=o,stderr=e,timeout=1800,creationflags=subprocess.CREATE_NO_WINDOW)
gate=G/(label+'.receipt.json');write(gate,dict(status='PASS' if result.returncode==0 else 'FAIL_PRESERVED',command=args,process_exit=result.returncode,started_utc=start,finished_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),elapsed_seconds=time.monotonic()-tick,stdout_sha256=sha(outputs[0].read_bytes()),stderr_sha256=sha(outputs[1].read_bytes()),qualification='Fresh unchanged existing regression gate after JSON-only formatting repair. Failed v1 retained; no strict-zero2D/graphics/action/owner acceptance.'))
d=read(ip2);d['validation'].append(dict(command=' '.join(args),result='PASS' if result.returncode==0 else 'FAIL',evidence=gate.relative_to(R).as_posix()));write(ip2,d)
print('REGISTRY_IDENTICAL_OBJECTS_COMPACT_BYTES',len(compact));print(label,result.returncode);assert result.returncode==0
