from pathlib import Path
from PIL import Image
import datetime, hashlib, html, json, posixpath, shutil

r = Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f = r / 'audit/job_wash_root_remaining_sequences_v1_20261002'
old = r / 'audit/day_two_wash_complete_action_v1_20261001/root_route_attempt_03'
prefix = f.relative_to(r).as_posix()
read = lambda p: json.loads(p.read_text(encoding='utf-8-sig'))
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
def write(p, d):
    p.write_text(json.dumps(d, indent=2, ensure_ascii=False) + '\n', encoding='utf-8', newline='\n')
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
m = read(f / 'BOARD_MANIFEST.json')
assert len(m['frames']) == 1818 and len(m['boards']) == 95 and len(m['cases']) == 7
assert not (f / 'REVIEW.json').exists(), 'Preserve an existing review before revision.'

# These are the recorded opinions from direct inspection of all 95 complete
# ordered boards and three whole native details for each of these seven cases.
doctor = [
 ('BASIN', 'Mounted basin and faucet', 2.9, 'artwork in context', 'The cyan ellipse, plum rim and yellow faucet are flat graphic symbols against the authored painted architecture. The basin has no honest physical support at its mounted position.', 'Reuse the reviewed painted basin family if suitable; stage it as one supported physical object.'),
 ('HANDS', 'Peach hand symbols', 2.2, 'visible artwork and wash subject', 'Peach discs and wrist wedges have no readable fingers, palms or connection to Roshan. They do not make the washing subject clear.', 'Use authored connected hands with readable palms and a quiet clean ending.'),
 ('RUB', 'White wash loops', 2.3, 'visible feedback and action', 'White loops grow inside the basin, but no palms rub together and no water stream visibly rinses them. The loops communicate a held input rather than the required washing action.', 'Show distinct reach, rub, water-on rinse and clean rest states.'),
 ('CONTACT', 'Roshan-to-basin contact', 2.3, 'spatial relationship', 'Roshan stays at the left medical doorway while the basin is far right above seats. Her body does not reach the work object.', 'Stage the actor at the actual basin and synchronize authored hand contact before progress.'),
 ('SPACE', 'Wash popup placement', 2.3, 'mounted composition', 'The basin covers unrelated right-side seats and a garden nook while the invitation and actor remain left. The task has two conflicting locations.', 'Use one room-owned work location and consistent viewport/world coordinates at both widths.'),
 ('OVAL', 'Dark wash oval', 3.2, 'visible graphic in context', 'The dark oval supplies contrast but dims unrelated architecture and garden furniture without establishing a supported workspace.', 'Restrict contrast to the working subject and basin.'),
 ('PIPS', 'Warm progress pip row', 4.0, 'visible feedback in context', 'The warm dots are readable, but are remote from Roshan and spread over a garden. They do not supply missing washing semantics.', 'Place restrained progress feedback beside the physical washing object.'),
 ('PUFF', 'Pink completion puff', 3.2, 'visible feedback in context', 'A brief flat pink puff appears remotely over the basin and disappears. It acknowledges success without revealing clean hands or a resolved rinse.', 'Keep feedback near the accepted clean subject and preserve a readable clean rest.'),
 ('REST', 'Clean resting state', 2.2, 'sequence relationship', 'Completion leaves hand symbols and loop graphics rather than a matched clean subject visibly resting after a rinse.', 'Make the final wash state physically and visually distinct from progress.'),
 ('WORKPOSE', 'Doctor working pose fit', 2.3, 'actor/action relationship', 'The painted Doctor pose fits the character identity, but its gesture does not reach the remote basin or enact palm rubbing.', 'Reuse identity-stable poses only where their hands and tool action meet the actual surface.'),
 ('ROOM', 'Painted medical room material', 4.6, 'visible painted material only', 'Cream, lavender and aqua architecture has rounded forms, broad painted shading and coherent plum contours. This material opinion excludes the wash overlay and native-coverage/composition acceptance.', 'Preserve the authored material; repair the mounted action separately.'),
 ('LAYOUT', 'Room coverage and wash composition', 3.0, 'whole mounted canvas', 'Blurred side extensions dilute the sharp painted room; the independent basin dominates the right. The 1600 canvas adds broad navy outer margins. This does not establish required native background coverage.', 'Provide native room coverage and stage the action within its painted space.'),
 ('ACTOR', 'Painted Doctor identity/material', 4.6, 'visible character material only', 'The rainbow tail, warm face and painted costume remain coherent with the established character family. A material pass does not approve her wash pose, contact or scene placement.', 'Preserve identity while binding an appropriate washing action.'),
 ('NEXT', 'Next FIND target ring', 3.2, 'next-phase mounted feedback', 'The wash overlay disappears and a cyan ring points to a left patient. This is a new phase invitation, not a completed career or return, and the ring remains a flat graphic overlay.', 'Review FIND action separately; keep pointer feedback restrained and near its subject.')
]
nursery = [
 ('SUBJECT', 'Missing washing subject', 1.5, 'missing mounted subject relationship', 'The work oval stays empty throughout held washing: no basin, faucet, hands, rubbing or rinse is visible. No absent source image is scored or approved.', 'Establish a visible supported basin and connected washing subject, then audit a fresh current capture.'),
 ('CONTACT', 'Actor-to-wash contact', 1.5, 'spatial/action relationship', 'Roshan remains left holding a baby and an orange towel while progress occurs in the distant empty oval. There is no contact with a washing object.', 'Stage a coherent reach and connected hand action at the actual wash location.'),
 ('VERB', 'Reach, rub and rinse readability', 1.5, 'sequence relationship', 'The preserved sequence shows no hand rubbing, visible rinsing water or dirt removal. A baby-holding pose and pips do not demonstrate washing hands.', 'Show the literal non-reader action and a matching clean rest before advancing.'),
 ('WORKPOSE', 'Baby-and-towel pose during WASH HANDS', 1.8, 'actor/action relationship', 'The identity-stable painted pose is readable as baby care, but both baby and towel occupy the gesture while the requested wash action is absent.', 'Preserve the pose for appropriate care beats and use a connected wash pose for this phase.'),
 ('OVAL', 'Empty dark work oval', 3.0, 'visible graphic in context', 'The large translucent oval darkens the right nursery pod and blurred side space. Its emptiness makes the target look like missing artwork.', 'Mount the intended subject at one honest work location with restrained local contrast.'),
 ('PIPS', 'Warm progress pip row', 4.0, 'visible feedback in context', 'The warm dots fill clearly, but advancing dots over an empty oval give no evidence of successful washing.', 'Keep progress beside the visible working subject; require the action before rewarding it.'),
 ('PUFF', 'Remote pink completion puff', 3.2, 'visible feedback in context', 'A pink puff briefly appears over the empty oval, far from Roshan. It supplies celebration without a visible clean subject.', 'Resolve the actual washed hands, then place modest feedback at that result.'),
 ('REST', 'Missing clean resting state', 1.5, 'sequence relationship', 'After acceptance Roshan gestures happily and the oval persists; there are no matching clean hands, basin or water-off resting state.', 'Show and hold a quiet clean ending distinct from the active wash.'),
 ('ROOM', 'Painted nursery material', 4.6, 'visible painted material only', 'Shell pods, moons and hanging stars have warm painted depth, rounded contours and compatible aqua/lavender color. This opinion excludes screen coverage, composition and the wash task.', 'Preserve the authored nursery design and improve its mounted coverage.'),
 ('LAYOUT', 'Nursery whole-canvas coverage', 2.7, 'mounted composition', 'A small sharp central painted room is surrounded by blurred side columns and large cyan top/bottom patches. At 1600, navy outer margins further reduce the usable composition; required native coverage remains unproved.', 'Reuse the approved room identity while supplying genuinely native playable-screen coverage.'),
 ('SPACE', 'Invitation, actor and work-area relationship', 2.6, 'mounted composition', 'The invitation and actor belong to the left nursery doorway, while the empty task oval extends far right into blurred space. The job does not share one readable location.', 'Give this work beat one coordinate-owned physical location.'),
 ('ACTOR', 'Painted Nursery identity/material', 4.6, 'visible character material only', 'Roshan keeps her established warm face, rainbow hair/tail and aqua costume. The baby reads as a soft swaddled care subject. This does not approve the pose for washing.', 'Preserve these stable designs and fit action-specific gestures to the task.'),
 ('NURSE', 'Left nursery nurse placement', 3.3, 'mounted placement', 'The painted adult nurse holds a baby in the blurred far-left extension, separated from the sharp central room and Roshan. The placement weakens the shared nursery space.', 'Bring the existing approved cutout into the authored room at a deliberate scale and layer.'),
 ('NEXT', 'Next CATCH BABIES invitation', 3.2, 'next-phase mounted feedback', 'The wash oval disappears, Roshan opens her arms and a ring surrounds a swaddled baby. This confirms only the next-phase invitation; the catching contact and complete animation are outside this washing sequence.', 'Audit the full actual catching action independently and keep the pointer subordinate to the painted subject.')
]

for b in m['boards']:
    assert sha(r / b['path']) == b['sha256']
    b.update(direct_review=True, reviewed_utc=now)
case_reviews = []
all_opinions = []
details = []
for c in m['cases']:
    cid = c['id']; ns = 'nursery' in cid
    frames = [x for x in m['frames'] if x['case'] == cid]
    assert [x['capture_index'] for x in frames] == list(range(c['frame_count']))
    first = lambda key: next(x['capture_index'] for x in frames if x[key])
    facts = {'first_interaction_request': first('interaction_requested'), 'first_hotspot_opening': first('hotspot_opening'), 'first_task_open': first('task_open'), 'opened_event_label': c['opened_frame'], 'first_surface_held': first('surface_held'), 'first_surface_complete': first('surface_completion'), 'completion_event_label': c['accepted_frame'], 'first_next_phase': next(x['capture_index'] for x in frames if x['phase_index'] == 1), 'next_phase_event_label': c['advanced_frame']}
    scores = {'complete_wash_workflow': 1.8 if ns else 2.7, 'actor_contact_spatial_relation': 1.5 if ns else 2.3, 'washing_subject_rub_and_rinse': 1.5 if ns else 2.2, 'basin_artwork': None if ns else 2.9}
    for x in frames:
        assert sha(r / x['path']) == x['sha256']
        i = x['capture_index']
        if i < facts['first_interaction_request']:
            lane = 'passive start'; note = 'The invitation pulses beside the painted room without earned washing progress.'
        elif i < facts['first_hotspot_opening']:
            lane = 'input-requested approach'; note = 'Roshan travels to the left job invitation. This arrival does not establish contact with the distant work area.'
        elif i < facts['first_task_open']:
            lane = 'hotspot opening'; note = 'The left invitation opens after approach; no actual washing is shown.'
        elif i < facts['first_surface_held']:
            lane = 'wash opened, before hold'; note = 'An empty dark oval opens far right; no mounted wash subject appears.' if ns else 'A flat basin and peach hand symbols open far right over seats, apart from Roshan.'
        elif i < facts['first_surface_complete']:
            lane = 'intentional held wash'; note = 'Progress dots advance over the empty oval while Roshan holds a baby and towel at left. No basin, hand rubbing or rinse is visible.' if ns else 'Progress and white loops advance around the basin. Roshan remains left; peach symbols do not enact a connected rub and rinse.'
        elif i < facts['first_next_phase']:
            lane = 'earned feedback and wait'; note = 'A brief remote pink puff and cheerful gesture acknowledge completion; the empty oval never reveals a clean washed subject.' if ns else 'A brief remote pink puff and happy pose acknowledge completion; loop graphics remain without a matched clean hand/rinse result.'
        else:
            lane = 'next CATCH BABIES phase armed' if ns else 'next FIND phase armed'; note = 'The wash oval disappears and a baby invitation ring appears. This is a next-phase invitation, not a full catching-action or career-completion review.' if ns else 'The wash widget disappears and a left patient invitation ring appears. This is the next FIND phase, not a completed Doctor career or room return.'
        x.update(direct_review=True, reviewed_utc=now, owner_acceptance=None, review_lane=lane, evaluation=note, scores=scores.copy())
    opinions = [dict(id=cid.upper()+'-'+oid, case=cid, name=name, score=score, scope=scope, evaluation=note, refinement=refine, priority=score<=4.5, reviewed_utc=now, owner_acceptance=None) for oid,name,score,scope,note,refine in (nursery if ns else doctor)]
    cd = [dict(case=cid, frame=i, path=frames[i]['path'], sha256=frames[i]['sha256'], direct_review=True, reviewed_utc=now) for i in [110,185,252]]
    details.extend(cd); all_opinions.extend(opinions)
    case_reviews.append(dict(case=cid, scores=scores, transition_facts=facts, individual_objects=opinions, native_details=cd, frame_count=len(frames), board_count=sum(b['case']==cid for b in m['boards']), direct_review=True, review_kind='fresh direct review of unchanged dated native capture', basin_source_artwork_review=None if ns else 'visible mounted symbol only; no isolated source approval', qualification='Independent direct inspection for this exact case and width. Shared-looking art does not inherit a pass from another route.'))

m.update(status='ALL1818_PRESERVED_NATIVE_FRAMES_DIRECTLY_REVIEWED', reviewed_utc=now)
write(f / 'BOARD_MANIFEST.json', m)
profile = read(old / 'PROFILE.json'); checks=[]
for p,h in profile['source_before'].items():
    file=r/p; cur=sha(file) if file.is_file() else None
    checks.append(dict(path=p,capture_sha256=h,current_sha256=cur,match=cur==h))
write(f/'HISTORICAL_CAPTURE_SOURCE_FRESHNESS.json', dict(status='DATED_CAPTURE_SOURCE_BOUNDARY_COMPARED', checked_utc=now, source_count=len(checks), matched=sum(x['match'] for x in checks), changed_or_unavailable=[x for x in checks if not x['match']], qualification='These October 1 native images remain dated evidence. Current source differences cannot be assumed irrelevant to these jobs; this review does not create a current capture or current runtime acceptance.'))
review=dict(status='ALL_SEVEN_REMAINING_PRESERVED_WASH_CASES_REVIEWED_WEAK_ACTION',reviewed_utc=now,capture_baseline=profile['baseline'],publication_baseline=read(f/'PLAN.json')['baseline'],cases=case_reviews,frames=m['frames'],boards=m['boards'],native_details=details,individual_objects=all_opinions,counts=dict(cases=7,frames=1818,complete_boards=95,native_details=21,individual_opinions=len(all_opinions),all_eight_cases_with_separate_doctor_review_frames=2074),source_freshness='HISTORICAL_CAPTURE_SOURCE_FRESHNESS.json',owner_acceptance=None,qualification='All 1,818 preserved October 1 native frames directly inspected on 95 ordered whole-canvas boards plus 21 full native details. No interpolated, generated, cropped or substitute action frames. Actual first boolean states and later event labels are separately recorded. These are all seven remaining complete WASH-phase fixture cases, alongside the earlier 256-frame Doctor review: all eight preserved cases now have direct review. They do not establish an ordinary MainMenu story launch, all later job phases, newly rendered current gameplay, device/child/owner acceptance or a completed repair. Nursery has no visible mounted washing subject, so absent basin source artwork is unscored. Material-only opinions do not approve scene coverage, contact, action or overall design compliance.')
write(f/'REVIEW.json',review)
esc=html.escape; url=lambda p:posixpath.relpath(p,prefix)
def figure(p,caption,cls=''):
    with Image.open(r/p) as im:w,h=im.size
    return f'<figure class="{cls}"><a href="{esc(url(p))}"><img loading="lazy" width="{w}" height="{h}" src="{esc(url(p))}" alt="{esc(caption)}"></a><figcaption>{esc(caption)}</figcaption></figure>'
css='body{background:#eef4f9;color:#26374d;margin:0;font:17px/1.6 system-ui}main{max-width:1220px;margin:auto;padding:24px}section,article,details{background:white;padding:22px;margin:22px 0;border:1px solid #ccd8e4;border-radius:18px}h1,h2,h3{color:#49347b;line-height:1.25}a{color:#49347b}figure{margin:18px 0;background:#f1f7fb}img{display:block;width:100%;height:auto}figcaption{padding:12px;overflow-wrap:anywhere}.weak{border-left:6px solid #ba7848}summary{cursor:pointer;font-weight:650}select{font:inherit;padding:10px;max-width:100%}table{border-collapse:collapse;width:100%;font-size:15px}td,th{padding:10px;border-bottom:1px solid #ccd8e4;text-align:left;overflow-wrap:anywhere}code{overflow-wrap:anywhere}'
parts=[f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Washing audit · all seven remaining preserved routes</title><style>{css}</style><main><h1>Washing: all seven remaining preserved routes</h1><p><strong>1,818 consecutive native frames · 95 complete ordered boards · 21 native details · 98 individual object and relationship opinions.</strong> Together with the separate 256-frame Doctor training review, every frame of all eight preserved October 1 washing cases has now been directly inspected.</p><p>Nursery workflow <strong>1.8/5</strong>; visible subject and contact <strong>1.5/5</strong>. Every Nursery version has an empty washing oval while progress completes. Doctor workflow <strong>2.7/5</strong>; contact <strong>2.3/5</strong>; hand symbols <strong>2.2/5</strong>; basin <strong>2.9/5</strong>. Every score at or below 4.5 remains a refinement priority.</p><p>These are fresh opinions of <strong>dated October 1 captures</strong>, not newly captured current gameplay. Training and birthday catalog are separately inspected at 1280 and 1600 widths. The fixture initializes catalog state before actual hotspot/held input; it does not establish ordinary MainMenu story entry, all later phases, target-device/child/owner acceptance or a repaired washing action.</p><nav><a href="../job_review_v2_20261001/index.html">Current all-jobs review</a> · <a href="../job_wash_root_doctor_sequence_v1_20261002/index.html">Separate 256-frame Doctor training review</a> · <a href="REVIEW.json">Every frame and individual opinion</a> · <a href="HISTORICAL_CAPTURE_SOURCE_FRESHNESS.json">Dated/current source comparison</a></nav><section><h2>The two concrete failures</h2><p>Nursery: Roshan arrives left holding a baby and towel, while the dark work oval stays empty on the right. Pips and a pink puff acknowledge successful input without showing a basin, connected hands, rubbing, rinsing or a clean ending. This is missing mounted action; an absent source image has no artwork score.</p><p>Doctor: a flat cyan basin, yellow faucet and peach hand symbols appear far right over seats. Roshan remains at the left medical invitation. White loops do not show palms rubbing or a water-on rinse; completion does not reveal a matched clean subject.</p><p>The painted rooms and characters retain useful material quality. Their narrowly scoped 4.6 opinions do not approve whole-canvas coverage, action fit, spatial contact or overall design-language compliance. The Nursery has a small sharp painted center surrounded by blurred columns and broad cyan patches; at 1600 both jobs also expose navy outer margins.</p></section><label for="case-filter">Show route: </label><select id="case-filter"><option value="all">All seven cases</option>']
for cr in case_reviews:parts.append(f'<option value="{cr["case"]}">{esc(cr["case"].replace("_"," "))}</option>')
parts.append('</select>')
for cr in case_reviews:
    cid=cr['case']; ns='nursery' in cid; frames=[x for x in m['frames'] if x['case']==cid]; facts=cr['transition_facts']
    parts.append(f'<section class="case" data-case="{cid}" id="{cid}"><h2>{esc(cid.replace("_"," "))}</h2><p>{cr["frame_count"]} real frames, {cr["board_count"]} complete boards; independently inspected. Workflow {cr["scores"]["complete_wash_workflow"]}/5, contact {cr["scores"]["actor_contact_spatial_relation"]}/5, subject {cr["scores"]["washing_subject_rub_and_rinse"]}/5. '+('No visible Nursery basin: source artwork score withheld.' if ns else 'Visible mounted basin symbol: 2.9/5.')+'</p><h3>Native details</h3>')
    for x in cr['native_details']:parts.append(figure(x['path'],f'Native frame {x["frame"]} · '+frames[x['frame']]['evaluation'],'native-detail'))
    parts.append('<h3>Each object and relationship</h3>')
    for x in cr['individual_objects']:parts.append(f'<article class="opinion {"weak" if x["priority"] else "material"}" id="{x["id"]}"><h3>{esc(x["name"])} · {x["score"]}/5</h3><p>Scope: {esc(x["scope"])}.</p><p>{esc(x["evaluation"])}</p><p>Next refinement: {esc(x["refinement"])}</p></article>')
    parts.append('<h3>First actual states and recorded event labels</h3><table><thead><tr><th>Transition</th><th>First actual native frame</th><th>Event label</th></tr></thead><tbody>')
    for name,actual,label in [('Interaction request','first_interaction_request',None),('Hotspot opening','first_hotspot_opening',None),('Task open','first_task_open','opened_event_label'),('Held wash','first_surface_held',None),('Surface complete','first_surface_complete','completion_event_label'),('Next phase','first_next_phase','next_phase_event_label')]:parts.append(f'<tr><td>{name}</td><td>{facts[actual]}</td><td>{facts[label] if label else "—"}</td></tr>')
    parts.append('</tbody></table><h3>Every ordered frame</h3><p>Read left to right, top to bottom. Each real native canvas appears exactly once, uniformly scaled for display. Final-board blank cells are explicitly excluded. Click any board for its full image; unchanged native frames are linked below.</p>')
    for b in (x for x in m['boards'] if x['case']==cid):parts.append(figure(b['path'],f'Frames {b["first_frame"]}–{b["last_frame"]} · {b["count"]} real frames, all directly inspected.','ordered-board'))
    parts.append('<details><summary>Every unchanged native frame and its written evaluation</summary>')
    for x in frames:parts.append(f'<p><a href="{esc(url(x["path"]))}">Frame {x["capture_index"]:04d}</a> · {esc(x["review_lane"])} · {esc(x["evaluation"])}</p>')
    parts.append('</details></section>')
parts.append('<section><h2>Evidence and remaining work</h2><p>These 1,818 frames and the separately reviewed 256 Doctor frames complete direct review of all eight preserved WASH-phase cases. Earlier reports that say these seven cases were pending retain their dated history; this continuation supersedes that pending-review count, not their captured source facts.</p><p>Current-source washing captures, ordinary story entry, the full next phases, actual target-device behavior and final owner acceptance remain open. No washing runtime, mechanics, rewards, saves or protected originals were changed in this review. The geode regression run is separate evidence and cannot grant washing visual acceptance.</p></section></main><script>document.getElementById("case-filter").addEventListener("change",e=>document.querySelectorAll("section.case").forEach(s=>s.hidden=e.target.value!=="all"&&s.dataset.case!==e.target.value));</script></html>')
(f/'index.html').write_text(''.join(parts),encoding='utf-8',newline='\n')
p=f/'PLAN.json';d=read(p);d.update(status='ALL1818_DATED_NATIVE_FRAMES_REVIEWED_ACTION_REMAINS_WEAK',review='REVIEW.json',reviewed_utc=now);write(p,d)
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
note='All preserved washing cases review continuation (2026-10-02): [all seven remaining routes: 1,818 native October 1 frames on 95 complete ordered boards, 21 native details and 98 individual opinions](job_wash_root_remaining_sequences_v1_20261002/index.html) directly inspected separately. Together with the earlier 256-frame Doctor review, all 2,074 frames of the eight preserved training/birthday-catalog WASH cases at 1280/1600 are now reviewed. All four Nursery cases have an empty work oval while progress completes: workflow 1.8, visible subject/contact 1.5; absent basin source artwork is unscored. The remaining three Doctor cases independently retain workflow 2.7/contact 2.3/hand symbols 2.2/basin 2.9. Dated pending-review counts in earlier reports remain history and are superseded only for review coverage. Actual first states and later event labels are separated. These are dated fixture images, not current captures, ordinary story entry, later-phase/device/child/owner acceptance or a wash repair. MA-VIS-006 and MA-PLAY-004 stay open at their existing lifecycle states.'
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
    p=r/rel;s=p.read_text(encoding='utf-8');n=note.replace('](job_wash_','](../job_wash_') if '/findings/' in rel else note;s=s.replace('\n\n','\n\n'+n+'\n\n',1);p.write_text(s,encoding='utf-8',newline='\n')
p=r/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s+='\n| `'+prefix+'/index.html` | 🔵 | `SUPPORTING_CURRENT` fresh direct review of all 1,818 preserved October 1 native frames across seven separately inspected WASH cases, 95 boards, 21 native details and 98 individual opinions. Together with the separate Doctor review all eight dated cases have frame coverage. Nursery missing mounted subject remains 1.5, workflow 1.8; absent basin source is unscored. Doctor workflow 2.7/contact 2.3/subject 2.2/basin 2.9. Dated/current sources qualified; no current capture, repair, later-phase or owner acceptance. |\n';p.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/job_review_v2_20261001/index.html';s=p.read_text(encoding='utf-8');start=s.index('<p id="remaining-wash"');end=s.index('</p>',start)+4;s=s[:start]+'<p id="remaining-wash"><a href="../job_wash_root_remaining_sequences_v1_20261002/index.html">All seven remaining preserved washing routes: 1,818 frames now reviewed</a>. With the separate Doctor report, all 2,074 frames of all eight dated cases are directly reviewed. Nursery has no visible washing subject (1.5/5); Doctor contact and action remain weak. Current-source capture, washing repairs, later phases and owner acceptance remain open. Earlier pending counts remain dated history.</p>'+s[end:];p.write_text(s,encoding='utf-8',newline='\n')
ip=r/'design/audit_impacts/job-wash-root-remaining-sequences-review-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in f.rglob('*') if p.is_file()}|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/index.html'});d['validation']=[dict(command='Direct review of every preserved frame in seven remaining WASH cases',result='PASS',evidence=prefix+'/REVIEW.json; every 1818 native frame and 95 board hash rechecked, 21 native details, 98 qualified opinions.')];d['acceptance_gaps']=review['qualification'];write(ip,d)
allow=r/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|set(d['files'])))
print(json.dumps(dict(frames=1818,boards=95,native_details=21,opinions=len(all_opinions),source_count=len(checks),current_source_matches=sum(x['match'] for x in checks),transitions={x['case']:x['transition_facts'] for x in case_reviews})))
