from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003';Q=P/'comparison_a3';OLD=P/'comparison_a2';IP=B/'design/audit_impacts/job-candy-local-far-fold-a3-20261003.json'
BASE='ae3880df4244139a4f681034b530a5ee2c68895d';PY='C:/Users/Peter/AppData/Local/Python/bin/python.exe'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip()==BASE and not Q.exists();Q.mkdir();(Q/'review_tools').mkdir();(Q/'inputs').mkdir();(Q/'prompts').mkdir();(Q/'workflows').mkdir()
source=B/'assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt13/native.png';s=read(source.with_name('SOURCE.json'));r=read(source.with_name('DIRECT_REVIEW.json'));assert sha(source)==s['sha256'] and r['whole_source_score']==4.5 and not s['runtime_bound']
prompt='''Roshan finishes folding the attached gold flap across the remaining red crescent of the same sweet. Her screen-left coral oven mitten already clamps the flap directly over the sweet. From0.0-1.1s that mitten carries the lower free gold edge down and forwards over the red crescent, pressing the gold paper snugly around the supported oval. The paper moves with that grasp, not by itself. By1.1s the sweet is covered by this flap. From1.1-1.7s the left mitten opens its grasp and lifts just clear of the finished fold; the paper stays folded. The screen-right mitten continues gently bracing the same sweet throughout. The front remainder of the original gold sheet stays on the lavender table. One continuous useful fold and small release.
Locked front camera. Preserve the same sweet underneath the paper, same size and location, same two connected quilted mittens, painted child/costume and lavender table. No waving or outer-corner lifting. No necks or end twists yet, no new wrapper/candy, no moving table, no extra anatomy, glow, text or scenery. The red surface becomes occluded by the attached paper; the object is still physically supported underneath it.
Sound: silence.
'''
(Q/'prompts/CANDY-FOLD-A3.txt').write_text(prompt,encoding='utf-8',newline='\n')
old=read(OLD/'MANIFEST.json');m=json.loads(json.dumps(old));m.update(id='candy-far-fold-a3-20261003',created_utc=now(),baseline=BASE,intention='Complete the far-flap closure from the existing truthful partial fold, then release that local grasp; one substep of the original whole wrapping workflow.',source_path=source.relative_to(B).as_posix(),source_sha256=sha(source),source_review=source.with_name('DIRECT_REVIEW.json').relative_to(B).as_posix(),input_path='inputs/CANDY-FOLD-A3.png',input_sha256=None,prompt_path='prompts/CANDY-FOLD-A3.txt',prompt_sha256=sha(Q/'prompts/CANDY-FOLD-A3.txt'),queue_name='candy_far_fold_a3_20261003',intended_component_only=True,comparison='A2 rejected1.8: every41 canvas retained a stationary far-corner grip and exposed sweet. A3 changes source to the existing A13 lower-edge partial fold plus action-first fold/occlusion/release brief. Same seed, installed workflow, model, dimensions, steps and fps; not a single-variable comparison. No full-wrap or current-game score transfer.')
for binding in m['renderer']['bindings']:
 src=OLD/binding['packet_path'];assert sha(src)==binding['sha256'];target=Q/binding['packet_path'];target.parent.mkdir(exist_ok=True,parents=True);shutil.copyfile(src,target);assert sha(target)==binding['sha256']
job=json.loads(json.dumps(m['jobs'][0]));job.update(id='CANDY-FOLD-A3',source_path=m['source_path'],source_sha256=m['source_sha256'],input_path=m['input_path'],input_sha256=None,prompt_path=m['prompt_path'],prompt_sha256=m['prompt_sha256'],queue_name=m['queue_name']);m['jobs']=[job]
write(Q/'MANIFEST.json',m)
write(Q/'PLAN.json',dict(planned_utc=now(),baseline=BASE,intention=m['intention'],profile='design/animation/ROSHAN_MOVEMENT_LANGUAGE.md',register='Quiet concentrating Ribbon Glide: useful mitten/paper change, steady support and readable payoff.',source=s,source_review=r['qualification'],reuse_inventory='Reuse exact existing A13 single whole source, no fresh art generation. Earlier A1 whole2.4 and A2 component1.8 remain rejected; A12 grip4.3 remains rejected. A13 partial source4.5 does not pass motion, exact coverage4.2 remains failed.',required_evidence=['Every41 native canvas directly inspected at original resolution','Attached flap advances in concert with lower-edge mitten grasp','Same supported sweet becomes occluded by that same gold flap','Small local release leaves the paper folded without a contour/candy-size jump','Two connected hands and stable identity/support throughout','Complete whole wrapping still separately requires entry, near-fold, neck grip, opposing twist and release, actual ordinary input/exit/interruption and owner review'],scope='Local reference-only component; no runtime binding or cinematic delivery. Does not redefine the original full wrapping or all-job goal.',production_sources_unchanged_required=783,owner_acceptance=None))
shutil.copyfile(OLD/'review_tools/normalize_complete_fold_source.gd',Q/'review_tools/normalize_complete_fold_source.gd')
worker=(OLD/'review_tools/queue_candy_far_fold_a2_v548.py').read_text(encoding='utf-8').replace('comparison_a2','comparison_a3').replace('CANDY-FOLD-A2','CANDY-FOLD-A3').replace('candy_local_fold_a2_active_20261003','candy_local_fold_a3_active_20261003');(Q/'review_tools/queue_candy_far_fold_a3_v560.py').write_text(worker,encoding='utf-8',newline='\n')
archiver=(OLD/'review_tools/archive_candy_far_fold_a2_v548.py').read_text(encoding='utf-8').replace('comparison_a2','comparison_a3').replace('CANDY-FOLD-A2','CANDY-FOLD-A3').replace('candy_local_fold_a2_active_20261003','candy_local_fold_a3_active_20261003').replace('CANDY FAR LONG-EDGE FOLD A2','CANDY FAR LONG-EDGE FOLD A3').replace('CANDY_A2_NATIVE_ARCHIVED','CANDY_A3_NATIVE_ARCHIVED')
# Preserve dispatcher safety unchanged; update only exact archival validation pointers.
archiver=archiver.replace('job-candy-local-wrap-continuity-20261003.json','job-candy-local-far-fold-a3-20261003.json').replace('Developed local quiet-idle FIFO Candy A1 and exact native output archival','Developed local quiet-idle FIFO Candy partial far-fold A3 and exact native output archival').replace("evidence='assets_src/local_motion/candy_wrap_continuity_v1_20261003/attempt01/RENDER_RECEIPT.json; every41 visual review pending.'","evidence='assets_src/local_motion/candy_wrap_continuity_v1_20261003/comparison_a3/attempt01/RENDER_RECEIPT.json; every41 visual review pending.'")
(Q/'review_tools/archive_candy_far_fold_a3_v560.py').write_text(archiver,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,Q/'review_tools'/Path(__file__).name)
rules=read(B/'design/audit_impacts/job-candy-local-wrap-continuity-20261003.json')['rules']
write(IP,dict(id='job-candy-local-far-fold-a3-20261003',scope='Continue the original full Candy wrapping and all-job audit using a separately declared local far-flap closure/release component from the existing A13 partial-fold source. A1/A2 failed semantic action; use the better already-generated lower-edge grasp and revise the action-first prompt, keeping developed renderer/admission/seed/settings identical. Preserve each native frame, audit every canvas and contact/identity/material/action, extend the illustrated review after actual evidence; no production binding, source-score transfer or cinematic delivery.',baseline=BASE,rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],files=sorted(p.relative_to(B).as_posix() for p in Q.rglob('*') if p.is_file()),validation=[dict(command='Whole-source technical normalization and directly inspect exact model input before dispatch',result='PENDING',evidence='New source A13 exact native hash in PLAN/MANIFEST; source4.5 is not action acceptance.'),dict(command='Developed local90-second-quiet FIFO and exact installed bytes/benchmark admission',result='PENDING',evidence='No render submitted yet; worker records a unique native prompt id and never cancels other jobs.'),dict(command='Directly inspect every41 native frame and each whole contact/fold/payoff',result='PENDING',evidence='No inferred scores before native outputs exist.')],acceptance_gaps='Far-fold closure/release component unrendered and unreviewed. Original whole wrapping and in-game WRAP2.8, neck pinch/opposing twist/complete release, ordinary game inputs/exit, target-device, child, owner, every job phase and comprehensive report acceptance remain open. No finding closure/integration/release.'))
write(Q/'REVIEW_STATUS.json',dict(status='SOURCE_BOUND_COMPONENT_INPUT_PREPARATION',runtime_integration=False,owner_approval=None))
print('A3 declared before input/render; original full wrapping and all-job success unchanged.')
