from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');Q=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/comparison_a3';IP=B/'design/audit_impacts/job-candy-local-far-fold-a3-20261003.json';PY='C:/Users/Peter/AppData/Local/Python/bin/python.exe'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
 n=p.with_name(p.name+'.v561_next');n.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n');n.replace(p)
m=read(Q/'MANIFEST.json');input=Q/m['input_path'];before=sha(input);gd=Q/'review_tools/normalize_complete_fold_source.gd'
engine=['C:/Users/Peter/AppData/Local/Programs/MermaidReefTools/Godot/4.7.2/godot_console.exe','--headless','--path',str(B),'--script',str(gd),'--',str(B/m['source_path']),str(input)]
p=subprocess.run(engine,cwd=B,capture_output=True,check=True,creationflags=subprocess.CREATE_NO_WINDOW);(Q/'NORMALIZATION.stdout.log').write_bytes(p.stdout);(Q/'NORMALIZATION.stderr.log').write_bytes(p.stderr);assert sha(input)==before
write(Q/'NORMALIZATION_RECEIPT.json',dict(status='PASS_IDENTICAL_WHOLE_SOURCE_TECHNICAL_NORMALIZATION',checked_utc=now(),command=engine,exit=p.returncode,source_sha256=m['source_sha256'],input_sha256=sha(input),whole_source=True,repeat_reason='Initial engine invocation succeeded and input was directly inspected; repeat only preserves missing raw transformation streams and proves identical output bytes.',qualification='Whole1254-square source uniformly448-square on896x512 RGB neutral mat; no crop/local repair or motion/frame synthesis. Native source preserved.'))
with Image.open(input) as im:assert im.size==(896,512) and im.mode=='RGB'
m['input_sha256']=sha(input);m['jobs'][0]['input_sha256']=sha(input);write(Q/'MANIFEST.json',m)
write(Q/'INPUT_DIRECT_REVIEW.json',dict(reviewed_utc=now(),input_sha256=sha(input),dimensions=[896,512],mode='RGB',full_native_image_seen=True,whole_original_source_preserved=True,observations='Complete hat/hair/connected body and two mittens, entire lavender worktop and attached gold sheet are intact. Lower mitten meets the flap over a remaining red crescent; suitable partial starting pose for declared component. No motion result or measured anchor tolerance is inferred.',qualification='Input delivery inspection only; source4.5 remains provisional, previous exact coverage4.2 remains failed. All whole wrapping and actual game acceptance open.'))
commands={'parser':[PY,'-X','utf8','-B','-m','gdtoolkit.parser',str(gd)],'inference':[PY,'-X','utf8','-B','tools/lint_inference.py',str(gd)]};rows=[]
for label,cmd in commands.items():
 r=subprocess.run(cmd,cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(Q/(label+'.stdout.log')).write_bytes(r.stdout);(Q/(label+'.stderr.log')).write_bytes(r.stderr);rows.append(dict(label=label,command=cmd,exit=r.returncode,status='PASS' if r.returncode==0 else 'FAIL'));assert r.returncode==0
write(Q/'NORMALIZATION_SCRIPT_GATES.json',dict(status='PASS',checked_utc=now(),script_sha256=sha(gd),commands=rows,qualification='Exact source helper syntax/inference and actual official4.7.2 execution only; no visual/owner acceptance.'))
checker=[PY,'-X','utf8','-B',str(Q/'review_tools/queue_candy_far_fold_a3_v560.py'),'--check'];r=subprocess.run(checker,cwd=B,capture_output=True,check=True,creationflags=subprocess.CREATE_NO_WINDOW);(Q/'ADMISSION_CHECK.stdout.log').write_bytes(r.stdout);(Q/'ADMISSION_CHECK.stderr.log').write_bytes(r.stderr)
write(Q/'ADMISSION_CHECK.json',dict(status='PASS_SOURCE_INPUT_PROMPT_INSTALLED_WORKFLOW_BYTES',checked_utc=now(),command=checker,exit=r.returncode,manifest_sha256=sha(Q/'MANIFEST.json'),qualification='Unique render is not yet dispatched. Native queue90-second quiet window and successful matching benchmark are checked again by the unchanged developed worker before submission.'))
shutil.copyfile(__file__,Q/'review_tools'/Path(__file__).name)
licenses=(B/'ASSET_LICENSES.md').read_bytes();path=input.relative_to(B).as_posix();assert ('| `'+path+'` |').encode() not in licenses;licenses+=('\n| `'+path+'` | Whole source A13 technical model-input normalization by official Godot4.7.2 | Original project ImageGen artwork; exact source attribution retained | MANIFEST.json, NORMALIZATION_RECEIPT.json and INPUT_DIRECT_REVIEW.json | Whole-canvas uniform resize/neutral mat only; original preserved, reference-only, no runtime/cinematic/owner acceptance. |\n').encode();n=(B/'ASSET_LICENSES.md').with_name('ASSET_LICENSES.md.v561_next');n.write_bytes(licenses);n.replace(B/'ASSET_LICENSES.md')
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in Q.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'][0]=dict(command='Official Godot4.7.2 whole-source normalization, exact native input inspection, syntax and inference',result='PASS',evidence='NORMALIZATION_RECEIPT.json, INPUT_DIRECT_REVIEW.json, NORMALIZATION_SCRIPT_GATES.json; input fully seen and raw streams preserved.');d['validation'].append(dict(command='Exact developed worker source/input/prompt/installed workflow check before dispatch',result='PASS',evidence='ADMISSION_CHECK.json; successful check is not a render or visual pass.'));write(IP,d)
print('A3 inspected input + official4.7.2 helper/parser/inference + exact developed admission bindings PASS; dispatch not yet submitted.')
