from pathlib import Path
import json,hashlib,shutil,subprocess,sys,datetime,html
from PIL import Image
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');previous=b/'assets_src/local_motion/day2_doctor_wash_rub_study_v1_20261001';packet=b/'assets_src/local_motion/day2_geologist_pan_motion_v1_20261001';packet.mkdir(exist_ok=False);(packet/'inputs').mkdir();(packet/'prompts').mkdir();(packet/'.gdignore').write_text('')
base='edbf2a60e4a73ca149ee53b7f8d01990afd32198'
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert subprocess.run(['git','rev-parse','HEAD'],cwd=b,capture_output=True,check=True).stdout.decode().strip()==base
shutil.copytree(previous/'workflows',packet/'workflows');source=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/panning_contact/attempt_01/native.png'
im=Image.open(source);assert im.mode=='RGBA' and im.size==(1536,1024);small=im.resize((768,512),Image.Resampling.LANCZOS);field=Image.new('RGBA',(896,512),(223,244,244,255));field.alpha_composite(small,(64,0));input_path=packet/'inputs/geologist_pan_full_source.png';field.convert('RGB').save(input_path)
prompt='''One static camera shot of this exact painted storybook mermaid child holding this exact shallow lavender pan. The background stays the same plain pale aqua field. She wants to wash the pan gently. At0.0-0.25s she looks into the water and holds both rim grips steady. At0.25-0.75s her attached forearms and elbows gently tilt the pan a little toward her left; both hands stay visibly gripping the same rim places. At0.75-1.25s she gently tilts the pan the other way, with small articulated elbow/wrist motion and mild water-surface movement contained inside. At1.25-1.70s the pan and hands settle back to the starting neutral held position. Her head, cap, face, hair, costume, curled mermaid tail and complete rainbow fin remain still and recognizable. The body does not slide or bounce as one sticker. Keep the vessel rigid, broad, shallow and the same size; fingers stay attached and never pass through the wall. No extra grains, crystals, people, limbs, tools, legs, glitter or scene; no pan detachment, spill, realistic texture, camera motion or zoom. Preserve the exact2D painted illustration style and colours. Sound: silence.'''
(packet/'prompts/geologist_pan_full_source.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
old_manifest=json.loads((previous/'MANIFEST.json').read_text());renderer=old_manifest['renderer'];renderer['bindings']=[dict(x) for x in renderer['bindings']]
for binding in renderer['bindings']:
 if binding['packet_path']=='workflows/render_gguf.py':binding['installed_path']=str(packet/'workflows/render_gguf.py')
 assert sha(packet/binding['packet_path'])==binding['sha256']
 if binding.get('check_installed_bytes',True):assert sha(Path(binding['installed_path']))==binding['sha256']
renderer['quality_limits']='Reuses the established successful same-settings GGUF benchmark and unchanged pinned wrapper/workflow/model bindings. No installations, restarts, cancellations, extra prompts or delivery acceptance.'
worker=packet/'run_geologist_comfy_pan_v134.py';code=(previous/'run_doctor_comfy_study_v43.py').read_text().replace('day2_doctor_wash_rub_study_v1_20261001','day2_geologist_pan_motion_v1_20261001').replace('doctor_local_rub_study_v1_20261001','geologist_local_pan_study_v1_20261001');worker.write_text(code,encoding='utf-8',newline='\n')
profile=dict(status='PREPARED_LOCAL_MOTION_REFERENCE_ONLY',baseline=base,created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),intention='Roshan gently washes the pan by rocking it with connected wrists/elbows while both hands maintain their rim grips.',personality='Existing Roshan Ribbon Glide attentive-work register; calm purposeful action and settle, no new canon or anatomy.',event='Prospective geologist PAN gesture response study only; no input/progress/reward implementation.',phases={'ready':[0,.25],'left':[.25,.75],'right':[.75,1.25],'settle':[1.25,1.7]},anchors={'fixed':'Head/face/cap/hair/costume/torso/curled tail/full fin and neutral field','allowed':'Small articulated elbow/wrist travel and rigid-pan tilt; water remains inside. Both hands keep exact rim contact.','native_hand_landmarks':[[783,649],[1110,550]],'native_water_center':[1090,689]},source={'path':rel(source),'sha256':sha(source),'dimensions':[1536,1024],'source_score':4.6,'static_hand_rim_score':4.6,'owner_accepted':False},normalization={'operation':'Uniform whole-canvas768x512 RGBA normalization centered64,0 on896x512 neutral aqua RGB model input. Complete source and all native pixels retained; no cropping, masking, repair, isolated limb movement or new scene. Reference-only technical preparation.','input_path':rel(input_path),'input_sha256':sha(input_path),'scaled_dimensions':[768,512],'position':[64,0],'background_rgba':[223,244,244,255]},loop_contract='Compare entry/left/right/settle and every41 native frame. No looping or return is accepted before direct review.',interruptions='No shipping clip, navigation, lifecycle, saved effect or reward is implemented; actual game remains unchanged.',acceptance_criteria='Every frame preserves character identity and topology; fingers maintain rim contact; vessel stays rigid and water contained; visible local articulated movement, stable torso/tail and clear neutral return. Full job pickup/travel/placement/routes/device/child/owner/cinematic acceptance remain separate.',qualification='LOCAL_MOTION_REFERENCE_ONLY. Useful motion study cannot supply runtime/cinematic delivery pixels by relabeling.')
write(packet/'PROFILE.json',profile)
job=dict(id='GEO-PAN-MOTION-REFERENCE01',queue_name='d2m_geologist_pan_v1_20261001',seed=2026100134,source_path=rel(source),source_sha256=sha(source),input_path='inputs/geologist_pan_full_source.png',input_sha256=sha(input_path),prompt_path='prompts/geologist_pan_full_source.txt',prompt_sha256=sha(packet/'prompts/geologist_pan_full_source.txt'))
manifest=dict(id='DAY2-GEOLOGIST-PAN-LOCAL-V1',acceptance='LOCAL_MOTION_REFERENCE_ONLY',owner_approval=None,runtime_integration=False,renderer=renderer,job=job,profile='PROFILE.json',output_state='Prepared; no prompt submitted or motion score assigned.',reused_art='New static hand/pan source4.6 reused intact for the named missing articulated panning action. All inherited jobs/rewards remain unchanged.',worker_sha256=sha(worker));write(packet/'MANIFEST.json',manifest)
shutil.copyfile(__file__,packet/'executed_prepare_geologist_comfy_pan_v134.py');shutil.copyfile(Path(__file__).with_name('inspect_comfy_pan_admission_v132.json'),packet/'READ_ONLY_ADMISSION_CHECK.json')
(packet/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Geologist local panning motion study</title><style>body{font:18px/1.55 system-ui;color:#302949;background:#eef5f4;max-width:1100px;margin:auto;padding:24px}img{width:100%;height:auto}</style><h1>Geologist panning motion — local reference only</h1><p>Prepared from the new connected gripping source4.6. No motion score assigned; every41 output frame requires direct inspection. The unchanged developed ComfyUI GGUF896×512/41-frame/24-step workflow checks exact inputs, a matching successful benchmark, no duplicate name, and a90-second quiet queue. No other jobs are cancelled or restarted.</p><img src="inputs/geologist_pan_full_source.png" alt="Exact complete-canvas local model input"><p><a href="MANIFEST.json">Exact bindings and hashes</a> · <a href="PROFILE.json">Intention, anchors, timing and gaps</a> · <a href="prompts/geologist_pan_full_source.txt">Exact prompt</a></p><p>Motion reference cannot be used as runtime/cinematic delivery by relabeling. Full ordinary routes, child/device/owner and final report remain open.</p>',encoding='utf-8')
lic=b/'ASSET_LICENSES.md'
with lic.open('a',encoding='utf-8',newline='\n') as f:f.write('\n| `'+rel(input_path)+'` | Derived from owner-authorized Codex ImageGen panning contact source; source SHA256 '+sha(source)+' | OpenAI generated output terms; original project art | https://openai.com/policies/terms-of-use/ | Uniform complete-canvas normalization and neutral RGB field only for local motion reference; no source repair. SHA256 '+sha(input_path)+' |\n')
remote=b/'audit/job_review_v2_20261001/pan_contact_remote_verified_v4';remote.mkdir(exist_ok=False)
for folder in ['pan_contact_publish_v133','pan_contact_remote_v133']:
 for p in (b/'tmp'/folder).iterdir():
  if p.is_file():shutil.copyfile(p,remote/(folder+'_'+p.name))
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();s+='\n| `'+rel(packet/'index.html')+'` | 🟣 | `CANDIDATE_REFERENCE_ONLY`; new static pan grip4.6 reused for the named articulated panning gap via unchanged developed ComfyUI GGUF41-frame workflow. Prepared source/input/prompt/workflow hashes and movement profile; no motion, runtime/cinematic, full-route/device/child/owner acceptance. |\n| `'+rel(remote/'pan_contact_remote_v133_RESULT.json')+'` | 🔵 | `GENERATED_REPORT`; anonymous normal-TLS exactedbf2a60 supplement269 payload files plus manifest verified every byte/hash. Publication proof only; whole-job visual/device/child/owner and new exact-head hosted gates remain separate. |\n';ledger.write_text(s,encoding='utf-8')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Local panning study preparation (2026-10-01): [complete source/input/prompt/profile and developed workflow](../'+rel(packet/'index.html')+') for the named missing articulated hand/elbow panning action. Static grip4.6 has no motion score. Same successful GGUF896×512/41-frame/24-step benchmark and exact bindings, no service restart/cancellation; inspect every native output frame and clear return. [Publishededbf2a60 anonymous270-file receipt]('+rel(remote/'pan_contact_remote_v133_RESULT.json').removeprefix('audit/')+') preserved. [Impact](../design/audit_impacts/job-geologist-panning-local-motion-20261001.json). No production binding, completed route/device/child/owner/report acceptance.';s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+entry+'\n',1);master.write_text(s,encoding='utf-8')
files=sorted({rel(p) for prefix in [packet,remote] for p in prefix.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md'})
write(b/'design/audit_impacts/job-geologist-panning-local-motion-20261001.json',dict(id='job-geologist-panning-local-motion-20261001',baseline=base,scope='Prepare and queue one reference-only local geologist panning motion study using the newly inspected static grip source and unchanged developed ComfyUI GGUF workflow. Bind exact source/input/prompt/worker/workflow bytes and movement profile, preserve all previous opinions and immutable remote receipt. No service/model changes, other-job cancellation or production game input/reward/save edits.',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-INT-02','DL-INT-03','DL-INT-06','DL-MED-01','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-03','DL-QA-06','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-VIS-08'],findings=['MA-PLAY-004','MA-VIS-006'],files=files,validation=[dict(command='Read-only exact developed workflow/benchmark/local native queue inspection',result='PASS',evidence=rel(packet/'READ_ONLY_ADMISSION_CHECK.json')),dict(command='Direct41-frame local motion/source contact audit',result='PENDING',evidence='No submission/output yet; static source score4.6 is not motion acceptance.')],acceptance_gaps='Every native motion frame, identity/topology/contact/non-zero motion/return, naturally timed ordinary job routes, target-device/child/owner/final comprehensive report; no runtime/cinematic/release acceptance.'))
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(files);write(allow,sorted(allowed));print(json.dumps(dict(packet=rel(packet),worker=rel(worker),input=rel(input_path),source_sha256=sha(source),worker_sha256=sha(worker))))
