from pathlib import Path
import datetime, hashlib, json, shutil, subprocess
from PIL import Image

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_grotto_native2k_v1_20261002';assert not f.exists();(f/'attempt_01').mkdir(parents=True)
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
paths=['assets_src/imagegen/geologist_painted_rebuild_v1_20261001/grotto/attempt_01/native.png','assets_src/geologist_rebuild_2026-09-05/geology_grotto_candidate.png','assets_src/imagegen/opera_codex_2026-08-02/native/opera_stage_finale_master_native.png']
inventory=[]
for rel in paths:
 with Image.open(b/rel) as im:dim=list(im.size)
 inventory.append(dict(path=rel,sha256=sha(b/rel),dimensions=dim,reuse_assessment='Painted reference exists, but1672x941 native does not meet2048x2048 per-screen coverage. Padding/upscaling cannot create native coverage. Finale stage is also a different setting, not a substitute geology room.'))
prompt='''Create one new complete opaque high-resolution background painting for the Mermaid Roshan Geologist game. Output a genuinely native 2048 x 2048 pixel square image or larger; native resolution is required, do not place a smaller finished picture in a larger border. This is a game-room environment, with no characters or live gameplay objects baked in.

REFERENCE IMAGE 1 is the appearance and setting reference: preserve its welcoming lavender-and-aqua stone geology grotto, four empty rounded wall alcoves, large central opening onto a calm turquoise sea, cream rounded supporting shelves and a broad warm sand-colored floor. Repaint a new high-resolution square master in the same polished 2D children's storybook style, using broad calm painted value bands, restrained texture, rounded handmade forms and plum contours. Never photorealistic, PBR, glossy 3D, flat vector, harsh black shadows or neon. Keep the scene high-key and the floor readable behind small bright mermaid cutouts.

Composition: all important room scenery lies in the central 16:9 horizontal window from22% to78% of the square height. At the center of that window, the four EMPTY alcoves flank the single distant sea opening, two on each side. The lower half of that central window is an unobstructed continuous pale warm floor, without islands, furniture, tables, crystals, fossils, signs or pathways. Extend natural rock ceiling above and floor below the window, so the whole square is a continuous painted scene rather than a framed thumbnail. Sparse aqua coral appears only at the outermost sides. No lettering, UI, actors, tools, badges, treasure piles or embedded crystals. The interactive stone, fossil, pan and geode will be separate existing authored game objects. Preserve the reference's gentle palette and room identity; render genuinely higher native pixel detail rather than blurry upscale.'''
(f/'attempt_01/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'PLAN.json',dict(status='NATIVE_RESOLUTION_GAP_GENERATION_PENDING',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseline=subprocess.check_output(['git','rev-parse','HEAD'],cwd=b,text=True).strip(),scope='Replace specifically weak live procedural geology room2.8 with a genuinely native2048-square painting meeting the existing per-screen raster rule. Inventory suitable existing references first; source identity/palette reusable but native coverage insufficient.',rules=['DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-LAY-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-AUTH-05','DL-AUTH-06','DL-AUTH-07'],findings=['MA-VIS-006','MA-PLAY-004','MA-OPERA-012'],inventory=inventory,generation_method='Built-in image_gen, one reference bound for game-room appearance, no protected book art.',references=[dict(role='room appearance/identity only',**inventory[0])],prompt_sha256=sha(f/'attempt_01/PROMPT.txt'),required_native_dimensions=[2048,2048],required_evidence=['Native returned dimensions; never padding/upscale as native coverage.','Direct full image and individual environment-object/style/layout review at source.','If native coverage passes and artwork>=4.5, preserve whole native and derive non-overlapping runtime cards separately with provenance.','Subsequent actual runtime input/completion/return, Mobile/Speedy and device/child/owner review.'],qualification='No generation/style/dimension pass presumed. Current frozen368 production remains unchanged. Missing native coverage keeps an otherwise good image reference-only. No all-job, owner, lifecycle, integration or release acceptance.'))
shutil.copyfile(__file__,f/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-grotto-native-resolution-20261002.json';write(ip,dict(id='job-geology-grotto-native-resolution-20261002',scope='Inventory and named native-resolution replacement gap for currently procedural geology room, preserve all references and attempts outside runtime.',baseline=subprocess.check_output(['git','rev-parse','HEAD'],cwd=b,text=True).strip(),rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-LAY-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-QA-01','DL-QA-02','DL-QA-03','DL-QA-06'],findings=['MA-VIS-006','MA-PLAY-004','MA-OPERA-012'],files=sorted(p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()),validation=[dict(command='Existing relevant source inventory and literal native dimensions',result='PASS',evidence=f.relative_to(b).as_posix()+'/PLAN.json; all3 relevant existing room/stage1672x941.'),dict(command='Requested native2048-square built-in generation',result='PENDING',evidence=f.relative_to(b).as_posix()+'/attempt_01/PROMPT.txt; output not yet returned.')],acceptance_gaps='No returned source, runtime binding, action, device/child/owner or global acceptance yet. Original game files and protected references unchanged.'))
print('Prepared named native-resolution gap; one existing grotto appearance reference, production unchanged.',flush=True)
