from pathlib import Path
import datetime, hashlib, html, json, shutil
from PIL import Image

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_grotto_native2k_v1_20261002';a=f/'attempt_01'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
native=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-b1940b10-49b9-41ca-bb20-a48b6a796d31.png');assert not (a/'native.png').exists();shutil.copyfile(native,a/'native.png');assert sha(native)==sha(a/'native.png')
with Image.open(native) as im:dim=list(im.size);mode=im.mode
assert dim==[1254,1254]
plan=read(f/'PLAN.json');ref=plan['references'][0]
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=1,recorded_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),prompt_path=(a/'PROMPT.txt').relative_to(b).as_posix(),prompt_sha256=sha(a/'PROMPT.txt'),references=[ref],transparent_background_requested=False,native_source_path=str(native),native_path=(a/'native.png').relative_to(b).as_posix(),native_sha256=sha(native),native_dimensions=dim,native_mode=mode,native_preserved_bytes=True,output_hint='Built-in tool returned exec-b1940b10-49b9-41ca-bb20-a48b6a796d31.png and displayed the generated image inline.',required_dimensions=[2048,2048],native_resolution_gate='FAIL',acceptance='REFERENCE_ONLY_NATIVE_RESOLUTION_FAILED',qualification='Prompt requested genuine2048-square or larger; returned1254-square. No upscale, padding, slicing or binding is presented as resolution satisfaction. No root cause or tool maximum is inferred from one result.'))
items=[('GRO-N2K-001','Whole square master',4.5,'The welcoming lavender/aqua grotto, broad pale floor and four empty alcoves retain the existing setting and leave live objects separate. The surplus ceiling/floor frames the central play window. Painted source style is provisionally4.5, with more small rock planes in the ceiling than ideal. Native1254-square fails the mandatory2048-square resolution gate; this is reference-only, not a runtime replacement.'),('GRO-N2K-002','Central sea opening',4.6,'A single clear sky-to-turquoise-sea opening provides a calm central landmark. Soft clouds and broad water bands remain subordinate to foreground actors. No live crystal, fossil or work object is baked into this opening.'),('GRO-N2K-003','Left outer empty alcove',4.6,'Rounded lavender cavity, cream arch and simple supporting shelf are child-readable and high-key. The empty recess can receive a separate existing work object without duplicating painted gameplay props.'),('GRO-N2K-004','Left inner empty alcove',4.6,'The cream arch and aqua lower stone separate this empty recess from the distant central opening. Rounded shelf contact has a visible lavender shadow and follows the room palette.'),('GRO-N2K-005','Right inner empty alcove',4.6,'The separate empty recess and rounded cream support mirror the room grammar without identical mechanical repeated marks. Its pale interior keeps future colored work props readable.'),('GRO-N2K-006','Right outer empty alcove',4.6,'The outer niche preserves the rounded warm rim and cool lavender cavity. The source does not bake in the interactive geode, so the selected authored geode can remain one object.'),('GRO-N2K-007','Unobstructed floor',4.6,'Broad pale warm stone/sand values provide figure-ground separation for small bright characters. The central floor is free of stools, islands, tables, trays and crystals; actor/support contact still requires real mounted review.'),('GRO-N2K-008','Rock ceiling',4.4,'Numerous small faceted painted patches add more texture than the broad-mass design rule prefers. Much lies outside the intended central16:9 play window, but the full master still contains this density. Do not infer a live defect from the unused upper region; mounted framing remains untested.'),('GRO-N2K-009','Outer coral and stone framing',4.5,'Sparse aqua coral and lavender corner rock frame the empty floor. The lowest stone triangles are outside most of the central play window. Isolated source framing reaches the floor provisionally; phone presentation and occlusion are unreviewed.')]
write(a/'REVIEW.json',dict(status='ALL9_SOURCE_ITEMS_REVIEWED_REFERENCE_ONLY',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_sha256=sha(native),native_dimensions=dim,individual_items=[dict(id=i,label=l,score=s,evaluation=e,direct_review=True,owner_acceptance=None,runtime_score=None) for i,l,s,e in items],native_resolution_gate='FAIL_1254x1254_BELOW_2048x2048',whole_source_style_score=4.5,runtime_score=None,qualification='One complete returned image directly inspected, nine individually written source/component opinions. Source score never waives native coverage; no production binding, complete action, device/child/owner, finding or all-job acceptance.'))
plan['status']='REFERENCE_ONLY_NATIVE_RESOLUTION_FAILED';plan['returned_native_dimensions']=dim;plan['next_action']='Preserve this attempt; do not repeat an identical prompt or label an upscale2K native. A later genuine native/tile solution must meet2048-square coverage and object continuity before binding.';write(f/'PLAN.json',plan)
sections=''.join('<article><h2>'+html.escape(l)+' · '+str(s)+'/5 source</h2><p>'+html.escape(e)+'</p></article>' for i,l,s,e in items)
refs=''.join('<figure><img src="../../../'+x['path']+'" alt="Existing '+html.escape(x['path'])+'"><figcaption>'+html.escape(x['path'])+' · '+str(x['dimensions'])+'</figcaption></figure>' for x in plan['inventory'])
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geology grotto · native resolution attempt</title><style>body{font:17px/1.6 system-ui;background:#edf2f7;color:#26374c;margin:0}main{max-width:1150px;padding:24px;margin:auto}img{max-width:100%;height:auto}figure{margin:20px 0}article{background:white;border:1px solid #b5c3d5;border-radius:14px;padding:15px;margin:15px 0}.gap{background:#fff0ca;border:1px solid #c6a354;padding:18px;border-radius:14px}a{color:#374cac}figcaption{overflow-wrap:anywhere}</style><main><h1>Geology grotto: native-resolution attempt1</h1><p class="gap">Reference only. The prompt requested a genuinely native2048×2048 background; the returned image is1254×1254. This attempt fails the resolution gate. Existing live room2.8 is unchanged. Whole source style4.5 provisional does not grant runtime readiness.</p><figure><img src="attempt_01/native.png" alt="Returned1254-square grotto; reference only"><figcaption>Complete native returned image, exact bytes preserved. No padded/upscaled derivative.</figcaption></figure><p><a href="attempt_01/GENERATION.json">Generation and hashes</a> · <a href="attempt_01/PROMPT.txt">Exact prompt</a> · <a href="attempt_01/REVIEW.json">Nine individual source evaluations</a> · <a href="PLAN.json">Inventory and gap</a></p>'+sections+'<h2>Existing appearance and reuse inventory</h2>'+refs+'</main></html>'
(f/'index.html').write_text(page,encoding='utf-8',newline='\n');shutil.copyfile(__file__,f/Path(__file__).name)
license_path=b/'ASSET_LICENSES.md';s=license_path.read_text(encoding='utf-8');s+='\n| `'+(a/'native.png').relative_to(b).as_posix()+'` | Built-in Codex image_gen,2026-10-02 | Generated project artwork; existing game-room appearance reference | `'+(a/'GENERATION.json').relative_to(b).as_posix()+'` | Exact1254-square native preserved;2048-square request failed; reference-only, no image edit or runtime binding. |\n';license_path.write_text(s,encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-geology-grotto-native-resolution-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation']=[v for v in d['validation'] if v['command']!='Requested native2048-square built-in generation']+[dict(command='Requested native2048-square built-in generation',result='FAIL',evidence=(a/'GENERATION.json').relative_to(b).as_posix()+'; returned1254x1254, no native2K claim.'),dict(command='Direct complete returned image and9 source/component reviews',result='PASS',evidence=(a/'REVIEW.json').relative_to(b).as_posix()+'; whole source4.5/ceiling4.4, reference-only.')];d['acceptance_gaps']='Native resolution failed; image remains outside runtime. Live room2.8/contact2.7, actual sequence/device/child/owner, all-job and finding acceptance remain open.';write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';v=read(allow);write(allow,sorted(set(v)|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|set(paths['path'] for paths in plan['inventory'])))
print('Preserved returned1254-square native and all9 opinions; resolution failure remains explicit.',flush=True)
