from pathlib import Path
import datetime, hashlib, html, json, shutil

r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def read(p): return json.loads(p.read_text(encoding='utf-8'))
def write(p,d): p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return p.relative_to(r).as_posix()
style='body{margin:0;background:#edf4fa;color:#25304a;font:17px/1.5 system-ui}main{max-width:1320px;margin:auto;padding:24px}header,article,section{background:white;border-radius:16px;padding:20px;margin-bottom:18px}a{color:#504096}h1,h2,h3{line-height:1.25}code,a{overflow-wrap:anywhere}img,video{display:block;max-width:100%;height:auto;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:18px}.grid article{min-width:0;margin:0}.score{font-weight:bold;color:#8e451f}small{display:block;overflow-wrap:anywhere}figure{margin:0;background:#d0f0f1;border-radius:12px}'
clean=r/'assets_src/imagegen/day2_doctor_wash_reach_clean_v1_20261001'
native=clean/'attempt01_native.png'
assert sha(native)=='d9963855f8ce6c75d7859a2085fdd45e0a80dfde8c24ac0761413a30395668a8'
evaluation=('The complete painted figure keeps the child face, rainbow forelock, coral-trim doctor coat, turquoise shirt, heart satchel and connected curled rainbow tail with a paired fin. The upper palm stays over the back of the relaxed lower hand in the outward reach. Visible soap and floating bubbles are removed on both neutral review backgrounds; the bare-hand contour remains attached and readable. The rendering still uses more scale and hair detail than the quietest game atlases, so the source meets the 4.5 drafting floor without claiming a higher style match. This is a static clean-result candidate, not a demonstrated rinse, a continuous transition or a runtime replacement.')
review=dict(id='WASH-DOCTOR-REACH-CLEAN-A01',status='SOURCE_FLOOR_MET_UNBOUND_CONTEXT_PENDING',checked_utc=now,path=rel(native),sha256=sha(native),dimensions=[1122,1402],source_score=4.5,pose_meaning_score=4.5,mounted_score=None,complete_action_score=None,evaluation=evaluation,qualification='Complete built-in image-generation edit; native RGBA preserved exactly. Full native/white/aqua directly inspected. Drafting source opinion only; no owner, game, device or cinematic acceptance.',direct_full_native_review=True,review_backgrounds=[dict(path=rel(clean/f),sha256=sha(clean/f)) for f in ['attempt01_review_white.png','attempt01_review_aqua.png']],source_reference=dict(path='assets_src/imagegen/day2_doctor_wash_reach_v1_20261001/attempt01_native.png',sha256='50a63f9c7465c2b39418cd58dd5bbeef19072279416c7cadbf533d8645b41b1a'),prompt=read(clean/'ATTEMPT01_PROMPT.json'),alpha_inspection=read(clean/'ATTEMPT01_ALPHA.json'),source_pixel_repair=False,runtime_integration=False,owner_approval=None,next_gap='Check hand registration against the soapy outward source and the literal sink; visibly demonstrate wet/rub/rinse/clean/settle/return before an action pass.')
write(clean/'ATTEMPT01_REVIEW.json',review)
(clean/'index.html').write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor outward clean-hands source</title><style>{style}</style><main><header><a href="../../../audit/job_review_v2_20261001/index.html">Current audit entry</a><h1>Doctor: matching outward clean hands</h1><p class="score">Source 4.5/5 · mounted and complete action pending</p><p>{html.escape(evaluation)}</p><p><a href="ATTEMPT01_REVIEW.json">Individual written review and provenance</a> · <a href="ATTEMPT01_PROMPT.json">Exact generation prompt</a> · <a href="../day2_doctor_wash_reach_v1_20261001/index.html">Preserved soapy reaching source</a></p></header><div class="grid"><article><h2>White review background</h2><img src="attempt01_review_white.png" alt="Complete clean-hands doctor on a white review background"></article><article><h2>Aqua review background</h2><img src="attempt01_review_aqua.png" alt="Complete clean-hands doctor on an aqua review background"></article></div><section><h2>Native original</h2><figure><img src="attempt01_native.png" alt="Unmodified native RGBA clean-hands doctor"></figure><code>{sha(native)}</code><p>Original provider output is preserved. Background composites are display evidence, not repaired source art. Owner acceptance remains pending.</p></section></main></html>',encoding='utf-8',newline='\n')
motion=r/'assets_src/local_motion/day2_doctor_wash_reach_rub_study_v1_20261001'
attempt=motion/'attempt_01'
catalog=read(attempt/'FRAME_CATALOG.json')
assert len(catalog['native_frames'])==41
def frame_opinion(i):
 if i==0:return 4.5,4.5,'The initial full figure preserves the outward reaching wrists, relaxed lower fingers, attached small lather, coat, satchel and paired fin. The static hand contact is clearer than the earlier chest clasp; no motion is established by this frame.'
 if i==1:return 4.4,4.4,'A small rise of the contacting hand pair has begun. The full painted body remains coherent, but the requested initial stillness is already changing.'
 if i<=8:return 4.4,4.2,'During the requested entry hold both forearms lift and the lower hand rotates upward with the upper palm. Foam reshapes locally. The lifted pair does not isolate a palm sliding across a supported hand; head and full tail remain recognizable.'
 if i<=17:return 4.4,4.3,'The contacting hands remain raised almost horizontally through this part of the stroke interval. Small finger/foam changes preserve attachment, but provide little readable palm travel over the lower hand. The body is broadly stable with minor coat/hair shading variation.'
 if i<=23:return 4.4,4.2,'The forearms lower together and the foam/fingers shift. This reads as moving the entire hand pair rather than one upper palm rubbing over a stationary back of hand; contact is attached but the purposeful stroke remains weak.'
 if i<=28:return 4.4,4.3,'The hands rise again toward the raised horizontal cluster and briefly settle. The painted figure and paired fin stay coherent. There is no clear one-stroke endpoint or independently supported lower hand.'
 if i<=35:return 4.4,4.2,'The hand pair lowers again during the requested return, with mild foam/finger blurring. This second broad forearm movement does not match the intended single rub and exact return to the original relaxed downward lower hand.'
 return 4.4,4.3,'The hands finish in the raised horizontal cluster and become quiet. The lower fingers still point more outward than in the native input/initial frame. The last hold is recognizable, but does not restore the precise entry geometry or demonstrate clean hands.'
items=[]
for x in catalog['native_frames']:
 p=motion/x['path'];assert sha(p)==x['sha256']
 ident,static,text=frame_opinion(x['index'])
 items.append(dict(id=f"DOCTOR-REACH-RUB-A01-F{x['index']:04d}",index=x['index'],timestamp_seconds=x['timestamp_seconds'],path=x['path'],sha256=x['sha256'],dimensions=x['dimensions'],direct_full_native_review=True,painted_style_score=4.5,identity_static_score=ident,hand_contact_static_score=static,individual_static_score=static,evaluation=text,runtime_action_score=None,cinematic_delivery_accepted=False))
motion_review=dict(status='ALL41_NATIVE_FRAMES_REVIEWED_REFERENCE_BELOW_MOTION_FLOOR',checked_utc=now,direct_full_native_views=41,frames_unreviewed=0,items=items,sequence_scores=dict(painted_style=4.5,body_identity=4.4,visible_palm_over_hand_stroke=3.9,entry_stillness=3.8,exact_return=4.0,overall_motion_reference=4.0),evaluation='The new outward source is easier to read than the earlier chest-clasp reference. Every complete 896x512 native frame was directly inspected. Both forearms lift before the requested entry hold ends, spend long intervals in a raised cluster, lower together twice and finish raised. The upper palm does not visibly travel over an independently supported lower hand. Foam changes and broad hand-pair movement remain substitutes for the intended rub. Coherent painted identity and attached hands do not pass the logical action or exact return.',machine=dict(status='PASS_RENDER_AND_NATIVE_DECODE_ONLY',state_path='attempt_01/WORKER_STATE.json',state_sha256=sha(attempt/'WORKER_STATE.json'),provider_prompt_id='ec90ecb4-2fc0-4d96-bbc2-1d3eb4248d55',frame_count=41,dimensions=[896,512],fps=24),source_score_not_transferred=4.5,source_qualification='New outward-reaching source-only opinion; no runtime binding.',qualification='LOCAL_MOTION_REFERENCE_ONLY. Native generated videos and lossless decoded frames preserved. No frame interpolation, duplicate-frame repair, subject warping, composited delivery, runtime integration, owner acceptance or cinematic delivery acceptance.',runtime_integration=False,owner_approval=None,complete_washing_action_score=None,next_iteration='Require the lower wrist/forearm to remain supported and still while only the upper palm travels over its back; preserve exact entry and end contact. Contextual sink water/rinse and a matching clean ending remain separate open tests.')
write(attempt/'REVIEW.json',motion_review)
cards=''.join(f'<article><h3>Frame {x["index"]:02d} · {x["timestamp_seconds"]:.3f}s</h3><img loading="lazy" src="{x["path"]}" alt="Full native doctor outward rubbing study frame {x["index"]}"><p class="score">Static hand contact {x["individual_static_score"]}/5 · identity {x["identity_static_score"]}/5</p><p>{html.escape(x["evaluation"])}</p><small>{x["sha256"]}</small></article>' for x in items)
(motion/'index.html').write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor outward rub: all native frames</title><style>{style}</style><main><header><a href="../../../audit/job_review_v2_20261001/index.html">Current audit entry</a><h1>Doctor outward reach: local rubbing study</h1><p class="score">Motion reference 4.0/5 · purposeful stroke 3.9 · entry 3.8 · exact return 4.0</p><p>{html.escape(motion_review["evaluation"])}</p><p>All 41 native frames directly reviewed. Local motion reference only; complete washing, runtime, device, child, owner and cinematic delivery acceptance remain open.</p><p><a href="attempt_01/REVIEW.json">Every frame and written sequence evaluation</a> · <a href="attempt_01/FRAME_CATALOG.json">Original machine decode catalog</a> · <a href="attempt_01/WORKER_STATE.json">Render receipt</a> · <a href="../day2_doctor_wash_rub_study_v1_20261001/index.html">Preserved earlier chest-clasp failure</a></p></header><section><h2>Unmodified native video</h2><video controls preload="metadata" src="attempt_01/native_output.webm"></video></section><div class="grid">{cards}</div></main></html>',encoding='utf-8',newline='\n')
for folder in [clean,motion]:shutil.copyfile(Path(__file__),folder/'executed_record_reach_clean_and_motion_reviews_v67.py')
license=r/'ASSET_LICENSES.md';text=license.read_text(encoding='utf-8')
for filename in ['attempt01_native.png','attempt01_review_white.png','attempt01_review_aqua.png']:
 p=clean/filename
 if f'`{rel(p)}`' not in text:text+=f'\n| `{rel(p)}` | OpenAI built-in image generation, full-character targeted clean-hands edit from the preserved reaching source; native SHA-256 `{sha(native)}`. | Owner-directed generated review art; source provenance preserved. | Internal built-in tool, 2026-10-01. | '+('Byte-identical provider native RGBA; no repairs; unbound source 4.5 only.' if filename=='attempt01_native.png' else 'Neutral review-background composite only, whole source unchanged; no delivery or source repair.')+' |\n'
license.write_text(text,encoding='utf-8',newline='\n')
template=read(r/'design/audit_impacts/job-doctor-reach-local-rub-study-20261001.json')
cleanimpact=dict(id='job-doctor-reach-clean-source-20261001',scope='Preserve the complete fresh clean-hands ending for the outward reaching doctor, then directly review native/white/aqua source identity, hand attachment and soap removal. Earlier chest-clean source and all original game art remain untouched.',baseline='56d66f63e375b61cf02936b426a05a2b92c14d3b',rules=template['rules']+['DL-ASSET-02'],findings=template['findings'],files=sorted([rel(p) for p in clean.rglob('*') if p.is_file()]+['ASSET_LICENSES.md']),validation=[dict(command='Direct full native/white/aqua clean-reaching source review',result='PASS',evidence=rel(clean/'ATTEMPT01_REVIEW.json')+'; source-only drafting 4.5, no mounted/action pass.')],acceptance_gaps='Source-only 4.5; sink registration, clean transition, complete wet/rub/rinse/settle/return and runtime/device/child/owner/cinematic acceptance remain open.')
write(r/'design/audit_impacts/job-doctor-reach-clean-source-20261001.json',cleanimpact)
template['files']=sorted(set(template['files'])|{rel(p) for p in motion.rglob('*') if p.is_file()})
template['validation'].append(dict(command='Direct review of every complete 896x512 native frame and declared entry/stroke/return',result='FAIL',evidence=rel(attempt/'REVIEW.json')+'; 41/41 directly reviewed, overall reference 4.0, stroke 3.9, entry 3.8, exact return 4.0.'))
template['acceptance_gaps']='Machine render/decode pass, source-only 4.5 and native painted style 4.5 do not pass action/reference 4.0. All 41 directly reviewed; logical independent upper-palm rub, entry stillness, exact return and complete contextual washing remain below/open. No runtime/device/child/owner/cinematic acceptance.'
write(r/'design/audit_impacts/job-doctor-reach-local-rub-study-20261001.json',template)
allow=r/'tmp/v2_preview_allowed.json';d=read(allow)
if isinstance(d,list):d=sorted(set(d)|{rel(p) for f in [clean,motion] for p in f.rglob('*') if p.is_file()})
elif isinstance(d,dict):
 key=next(k for k,v in d.items() if isinstance(v,list));d[key]=sorted(set(d[key])|{rel(p) for f in [clean,motion] for p in f.rglob('*') if p.is_file()})
write(allow,d)
print(json.dumps(dict(clean_source=4.5,new_motion_reference=4.0,direct_frames=41,unreviewed_frames=0,runtime_integration=False)))
