from pathlib import Path
import datetime, hashlib, json, shutil, subprocess

r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
d=r/'assets_src/imagegen/day2_doctor_wash_reach_clean_v1_20261001';assert not d.exists();d.mkdir();(d/'.gdignore').write_text('',encoding='utf-8')
source='assets_src/imagegen/day2_doctor_wash_reach_v1_20261001/attempt01_native.png';digest=hashlib.sha256((r/source).read_bytes()).hexdigest();assert digest=='50a63f9c7465c2b39418cd58dd5bbeef19072279416c7cadbf533d8645b41b1a'
prompt='''Edit this complete transparent Doctor Roshan sprite for the exact clean-hands ending of the SAME side-basin washing action. Return one new complete transparent RGBA full-body2D storybook sprite, matching this source framing and every unchanged identity/body detail.

Preserve her softly oval child face, large drawn brown eyes, brown curls, pearl flower, broad rainbow forelock to image right, ivory coral-trim doctor coat and heart patch, teal blouse, lavender waistband, heart medicine satchel at image left, rainbow scale tail curved right, and BOTH connected fin lobes. Keep the exact head/body proportions, face angle, gaze toward the hands, head/hair/costume/satchel/torso/tail/fin shape, positions and warm drawn/plum outline style. All head, hair, hands, satchel, tail and fin remain intact within the same generous transparent margins. Matte painted2D finish and aqua/lavender shadows stay unchanged.

Only clean the same TWO ATTACHED OUTWARD-REACHING hands: remove ALL soap/lather/bubbles completely. Keep both forearms reaching to image right, not clasped at the chest. Keep the lower hand and wrist in their existing relaxed down/right orientation near x=733,y=739 on the1122x1402 source. Keep the upper hand palm-down, resting very gently on the back of the lower hand near x=684,y=680, with a tiny visible air gap at the fingertips to show the rubbing has stopped. Preserve connected shoulders/elbows/wrists and readable grouped child fingers. The clean skin has the same matte warmth. Her small smile is quietly satisfied; do not introduce a big cheer or move her head/body. This is a small clean-result pose change, not a new character design.

No foam, bubbles, sparkle, dust puff, sink, faucet, basin, water jet, tool, patient, background, ground/shadow plate, text, UI or sheet. No floating hands, extra fingers/limbs, detached wrists, adult anatomy, opened theatrical palms, giant head, realistic3D/plastic rendering, colour pumping, halo or sticker rim. Preserve the full native figure; do not crop or repair it with composited source pixels.'''
record={'id':'WASH-DOCTOR-REACH-CLEAN-KEY01','status':'GENERATION_PENDING_UNBOUND','baseline':subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip(),'prepared_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'gap':'The new outward-reaching working pose has baked-in lather. Earlier clean source has chest-level palms and fails mounted clean-result4.0; it cannot finish this outward contact without a spatial jump. Legacy cheer/tool or dust-puff completion is semantically wrong. One complete matching clean-reaching ending is needed; reuse the existing sink, no scene/costume redesign.','input':{'path':source,'sha256':digest,'role':'Complete unbound outward-reaching doctor draft, source-only4.5'},'prompt':prompt,'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'method':'Built-in imagegen complete RGBA edit; original and provider output retained; no manual source-pixel repair.','movement_profile':'design/animation/ROSHAN_MOVEMENT_LANGUAGE.md','evidence':'audit/day_two_wash_contact_study_v1_20261001/attempt_04/REVIEW.json; all76 native contact views retained, best4.4 below floor.','source_score':None,'mounted_clean_score':None,'whole_action_score':None,'runtime_bound':False,'owner_accepted':False,'qualification':'Source-only clean consequence gap; timing/rinsing/contact/quiet return, native game-scale, device/child/owner and cinematic delivery remain separate.'}
(d/'ATTEMPT01_PROMPT.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8');(r/'tmp/reach_clean_prompt_v65.txt').write_text(prompt,encoding='utf-8');shutil.copyfile(__file__,d/'executed_prepare_reach_clean_source_v65.py')
ip=r/'design/audit_impacts/job-wash-contact-study-20261001.json';x=json.loads(ip.read_text(encoding='utf-8'));x['scope']+=' Generate one matching complete clean-reaching ending for the named lather/pose-continuity gap; earlier chest-level clean source cannot truthfully finish the outward pose.';x['files']=sorted(set(x['files'])|{p.relative_to(r).as_posix() for p in d.rglob('*') if p.is_file()});x['validation'].append({'command':'Complete generated clean-reaching source/native context/whole-action review','result':'PENDING','evidence':(d/'ATTEMPT01_PROMPT.json').relative_to(r).as_posix()+'; source and context still need individual review.'});ip.write_text(json.dumps(x,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':record['status'],'source_sha256':digest,'prompt_sha256':record['prompt_sha256']}))
