from pathlib import Path
import datetime,hashlib,html,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');raw=r/'tmp/doctor_sink_contact_v34';out=r/'audit/day_two_wash_contact_study_v1_20261001/attempt_01';assert not out.exists();out.mkdir(parents=True)
(out.parent/'.gdignore').write_text('',encoding='utf-8')
process=json.loads((raw/'PROCESS_RECEIPT.json').read_text(encoding='utf-8'));assert process['status']=='PASS_STATIC_CAPTURE_ONLY' and process['source_unchanged']
shutil.copytree(raw/'native_views',out/'native_views')
for name in ['PROFILE.json','PROCESS_RECEIPT.json','parser.stdout.log','parser.stderr.log','inference.stdout.log','inference.stderr.log','analyzer.stdout.log','analyzer.stderr.log','native.stdout.log','native.stderr.log']:shutil.copyfile(raw/name,out/name)
shutil.copyfile(r/'tmp/capture_doctor_sink_contact_v34.gd',out/'executed_capture_doctor_sink_contact_v34.gd')
shutil.copyfile(Path(__file__).with_name('prepare_and_run_doctor_contact_v34.py'),out/'executed_prepare_and_run_doctor_contact_v34.py')
shutil.copyfile(__file__,out/'executed_archive_first_sink_contact_review_v35.py')
capture=json.loads((out/'native_views/CAPTURE_RECEIPT.json').read_text(encoding='utf-8'));assert len(capture['views'])==26
items=[]
for n,row in enumerate(capture['views']):
 p=out/'native_views'/row['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==row['sha256']
 if row['variant'].startswith('original'):
  contact=2.3;composition=2.9;text='The production actor remains at the left stethoscope station while detached schematic hands and a giant flat basin occupy the right. The spatial and style mismatch persists at this width. This static original does not include the entire action.'
 elif row['sink_in_front']:
  contact=2.3 if row['sink_extent']<210 else 2.0;composition=3.0 if row['sink_extent']<210 else 2.8;text='The full painted sink in front covers the rubbing hands and forearms. At this scale the faucet interrupts the chest/face reading and the cabinet hides much of the body; the child cannot inspect the washing contact. A standalone source score does not pass this montage.'
 else:
  contact=3.6 if row['sink_extent']==150 else 3.8;composition=3.8 if row['sink_extent']==150 else 4.0;text='The connected washing hands remain visible, but placing the entire sink behind Roshan lets her torso/tail occlude its rim and cabinet. The depth relationship is ambiguous and no causal water contact or clean payoff is demonstrated. Use a front-rim layer from this same existing sink before commissioning more sink artwork.'
 items.append({'id':'DOCTOR-SINK-A01-%02d'%n,'path':row['path'],'sha256':row['sha256'],'native_dimensions':row['viewport'],'direct_full_native_review':True,'static_contact_score':contact,'static_composition_score':composition,'complete_action_score':None,'evaluation':text,'geometry':{k:row.get(k) for k in ['source','sink_extent','sink_in_front','character_rect','hand_source_landmark','hand_local','sink_rect']}})
review={'status':'ALL26_STATIC_NATIVE_VIEWS_REVIEWED_BELOW_CONTACT_FLOOR','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':'c2116877de10202c40e1d939c77eb3646b5f202f','direct_full_native_views':26,'views_unreviewed':0,'sources_changed':False,'source_opinions':'Doctor source6/key1 remain4.5 unbound; sink first cell retains earlier source4.6. These source opinions do not change after a failed placement test.','items':items,'next_refinement':'Reuse the same first sink cell with basin/back behind the child and its front rim/cabinet in front. Test hand offset and preserve the full connected character pixels. Then audit the actual timed washing action and clean result.','qualification':'Static test-only composition after real viewport approach. Old actor, task surface and station overlay hidden only in fixture. No shipping binding, progress, complete motion/return, device/child/owner or cinematic acceptance.'}
(out/'REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
cards=''.join('<article id="'+x['id']+'"><h2>'+x['id']+'</h2><p>'+html.escape(x['path'])+' · '+str(x['native_dimensions'][0])+' × '+str(x['native_dimensions'][1])+'</p><p>Static contact '+str(x['static_contact_score'])+'/5 · composition '+str(x['static_composition_score'])+'/5</p><a href="native_views/'+x['path']+'"><img loading="lazy" src="native_views/'+x['path']+'" alt="'+html.escape(x['path'])+'"></a><p>'+html.escape(x['evaluation'])+'</p></article>' for x in items)
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor sink contact: rejected first placement</title><style>body{font:18px/1.55 system-ui;background:#eef4fa;color:#253447;margin:0}main{max-width:1180px;margin:auto;padding:24px}header,article{background:white;border-radius:20px;padding:22px;margin:0 0 22px}h1{line-height:1.15}img{display:block;max-width:100%;height:auto}p,a{overflow-wrap:anywhere}</style><main><header><a href="../../job_review_v2_20261001/index.html">Preserved review checkpoint</a><h1>Doctor washing: all 26 first sink placements reviewed</h1><p>Every native view below was directly inspected. This first placement fails the 4.5/5 contact floor: the sink either obscures the hands or falls behind the whole body. The source images remain unchanged. The next refinement will reuse the existing sink with explicit basin and front-rim draw order.</p><p><a href="REVIEW.json">Every individual written score and geometry</a> · <a href="PROCESS_RECEIPT.json">Unchanged-source process evidence</a> · <a href="native_views/CAPTURE_RECEIPT.json">Exact capture hashes</a></p><p>'+html.escape(review['qualification'])+'</p></header>'+cards+'</main></html>'
(out/'index.html').write_text(page,encoding='utf-8',newline='\n')
license=r/'ASSET_LICENSES.md';s=license.read_text(encoding='utf-8')
for x in items:
 p=(out/'native_views'/x['path']).relative_to(r).as_posix();assert p not in s;s+='\n| '+p+' | Codex official Godot4.7.2 contact study2026-10-01 | Project diagnostic capture; underlying sources retain provenance | Test-only unchanged artwork with explicit scale/layer placement | Lossless native screenshot; below contact floor, no shipping or complete-action acceptance. |\n'
license.write_text(s,encoding='utf-8',newline='\n')
impact=r/'design/audit_impacts/job-wash-contact-study-20261001.json';d=json.loads(impact.read_text(encoding='utf-8'));d['files']=sorted({x.relative_to(r).as_posix() for x in out.parent.rglob('*') if x.is_file()}|{'ASSET_LICENSES.md'});d['validation']=[{'command':'Official Godot4.7.2 parser/inference/analyzer/native static contact capture','result':'PASS','evidence':(out/'PROCESS_RECEIPT.json').relative_to(r).as_posix()+'; original source hashes match.'},{'command':'Direct original-size visual review of each26 native views','result':'FAIL','evidence':(out/'REVIEW.json').relative_to(r).as_posix()+'; contact2.0–3.8 and composition2.8–4.0, all below floor.'}];impact.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
allow=r/'tmp/v2_preview_allowed.json';a=set(json.loads(allow.read_text(encoding='utf-8')));a.update(d['files']);allow.write_text(json.dumps(sorted(a),indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':review['status'],'views':26,'runtime_sources_changed':False,'current_b_index':'Preserved immutable c211 map; new study is a separate uncommitted revision.'}))
