from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
P=R/'assets_src/local_motion/nursery_connected_scrub_v3_20261002';A=P/'attempt01';L=R/'audit/job_artwork_refinement_live'
ip=R/'design/audit_impacts/job-nursery-scrub-fresh-a3-20261002.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
idx=read(A/'INDEX.json');assert len(idx['frames'])==41 and len(idx['boards'])==7
assert not (A/'DIRECT_REVIEW.json').exists()
frames=[]
for x in idx['frames']:
 assert sha(R/x['path'])==x['sha256']
 i=x['index'];score=4.5 if i==0 else (4.4 if i<11 else (4.1 if i<26 else (3.3 if i<30 else 2.9)))
 detail='Initial low joined palms/down gaze and intact source identity; this static contact does not demonstrate reciprocal rubbing.' if i==0 else ('Palms remain almost at the initial contact point; minor outline/lather changes do not show a stroke across the opposite palm.' if i<11 else ('An extra pale trace appears around the tap/spout/rim while the palms remain essentially static. The off-tap/source fixture is no longer fully stable.' if i<26 else ('A new curved white trace emerges beside/above the hair and grows toward the fixture, unrelated to the intended palm scrub.' if i<30 else 'A tall white outlined arch joins the hair area to the basin/tap base; the off-tap/contact/material story fails while the hands still do not perform two reciprocal rubs.')))
 frames.append(dict(**x,visual_frame_score=score,evaluation='Frame'+str(i)+' at'+format(x['timestamp_seconds'],'.3f')+'s: '+detail+' Down gaze remains readable. Current game and still-source opinions are unchanged.',direct_native_board_review=True,full_native_detail_review=i in [0,4,8,12,16,20,24,26,28,32,36,39,40],current_game_score=None,owner_acceptance=None))
components=[('Meaningful reciprocal rubbing',2.8,'No two readable reciprocal palm strokes are established. Small lather/edge changes accompany an almost held hand-contact pose.'),('Low connected palm/arm contact',4.4,'Both forearms remain connected and low palms maintain contact above the basin. Partial soap occlusion and absence of a readable slide keep this distinct from accepted washing.'),('Attention and face',4.6,'The fresh source clearly looks down toward the joined hands; that attention remains through all41 frames. This is a reference opinion, not a repair of the current game attention3.8.'),('Hair/headwear/face identity',4.5,'The pink headband, cream shell-flower, brown curls/trailing rainbow and simplified child face remain recognizable. Late phantom material beside the head is separately rejected.'),('Costume/tail/paint stability',4.3,'The main apron/gingham/tail contours and colors stay recognizable, but pocket/star and scale/highlight shimmer remain. No seamless source-family or gameplay transition is established.'),('Tap/basin/lather/material truth',3.0,'From the middle, extra pale traces change the tap/rim. From26 the new white arc grows beside the head, ending as a tall head-to-basin arch. This is not contained hand lather or an off-tap fixture.'),('Entry/exit continuity',3.0,'Entry retains source contact; exit adds a large invented white arch. The take cannot return cleanly to its source or claim a loop.'),('Whole motion reference',2.7,'Attentive face improves, but no meaningful scrub and a severe late invented-material event fail the4.5 floor. Reject and preserve; do not bind to the game.')]
rv=dict(status='ALL41_NATIVE_FRAMES_REVIEWED_REFERENCE_ACTION_REJECTED',reviewed_utc=now(),boards_reviewed=[x['path'] for x in idx['boards']],native_frame_count=41,full_native_details=[0,4,8,12,16,20,24,26,28,32,36,39,40],individual_frames=frames,component_evaluations=[dict(label=l,score=s,evaluation=e) for l,s,e in components],reference_action_score=2.7,reciprocal_rubbing_score=2.8,attention_score=4.6,palm_contact_score=4.4,fixture_material_score=3.0,current_game_action_score=3.9,current_game_attention_score=3.8,runtime_integration=False,cinematic_delivery=False,owner_acceptance=None,qualification='All41 native full canvases directly inspected row-major on seven nonoverlapping native-size boards with no source resampling;13 additional original full-native details directly inspected. Native videos and direct-decoded frames preserved, no interpolation or pixel repair. Fresh-source static4.5/down-gaze4.6 does not pass motion, current game or cinematic delivery. Every failure and original input/prompt/workflow/dispatch manifest retained.')
write(A/'DIRECT_REVIEW.json',rv)
write(P/'REVIEW_STATUS.json',dict(status='MACHINE_RENDER_COMPLETE_VISUAL_REJECTED',native_frame_count=41,reference_action_score=2.7,attention_score=4.6,review='attempt01/DIRECT_REVIEW.json',runtime_integration=False,cinematic_delivery=False,owner_acceptance=None,current_game_action_score=3.9,current_game_attention_score=3.8,score_transfer=False,manifest_and_dispatch_inputs_preserved=True))
video=next(x for x in idx['outputs'] if x['path'].endswith('.webm'))
rel=lambda path:(R/path).relative_to(P).as_posix()
gallery=''.join('<a href="'+rel(x['path'])+'"><img src="'+rel(x['path'])+'" width="1792" height="1640" alt="Complete native-size A3 board: frames'+str(x['first'])+' to'+str(x['first']+x['count']-1)+'"></a>' for x in idx['boards'])
details=''.join('<article id="FRAME-'+str(x['index'])+'"><strong>Frame'+str(x['index'])+' — '+str(x['visual_frame_score'])+'/5</strong><p>'+html.escape(x['evaluation'])+'</p><a href="'+rel(x['path'])+'">Unchanged full native896×512 image</a><p class="hash">'+x['sha256']+'</p></article>' for x in frames)
cards=''.join('<article><strong>'+html.escape(l)+' — '+str(s)+'/5</strong><p>'+html.escape(e)+'</p></article>' for l,s,e in components)
(P/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Fresh-source Nursery A3: rejected motion</title><style>body{font:18px system-ui;max-width:1150px;margin:36px auto;padding:0 20px;color:#253449;background:#f2f5fa}img,video{width:100%;height:auto}article{background:white;border-radius:14px;padding:18px;margin:12px 0}.hash{font-size:13px;overflow-wrap:anywhere}</style><h1>Fresh-source Nursery A3: rejected action2.7</h1><p>Fresh attentive source, same rub prompt/seed/admitted settings/developed workflow as A2. Every41 native frame directly reviewed on7 complete native-size boards plus13 full-native details. Attention4.6 improves; reciprocal rubbing2.8 and fixture/material3.0 fail. The hands remain nearly held; late frames invent a white head-to-basin arch.</p><p>Current game wash3.9/attention3.8 and fresh still4.5 remain unchanged. This is a rejected local motion reference, with no runtime/cinematic/device/child/owner/all-job acceptance.</p><video controls preload="metadata" src="'+rel(video['path'])+'"></video>'+cards+'<h2>All41 native frames in sequence</h2>'+gallery+'<h2>Every individual frame and written evaluation</h2>'+details+'<p><a href="attempt01/DIRECT_REVIEW.json">Complete individual/frame review</a> · <a href="attempt01/RENDER_RECEIPT.json">Native render receipt</a> · <a href="MANIFEST.json">Preserved bound manifest</a> · <a href="SOURCE_COMPARISON.json">Source-only comparison</a> · <a href="../nursery_connected_scrub_v2_20261002/index.html">Preserved rejected A2</a> · <a href="../../imagegen/nursery_scrub_attention_fresh_v1_20261002/index.html">Two fresh paintings/all22 source components</a> · <a href="../../../audit/job_artwork_refinement_live/all_items.html">Individual job library</a></p></html>',encoding='utf-8',newline='\n')
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
hist=L/'history_v36_before_a3_reference';assert not hist.exists();hist.mkdir()
for name in ('ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json'):shutil.copyfile(L/name,hist/(name+'.original'))
reg=read(L/'ALL_ITEMS.json');assert len(reg['items'])==1802
reg.update(display_revision='V37_REJECTED_FRESH_SOURCE_NURSERY_A3',updated_utc=now())
reg['scope']=reg['scope'].replace('V36 known register:','V37 known register:',1)+' Source-only local Nursery A3 adds a complete41-frame reference review: attention4.6, rubbing2.8, fixture3.0 and whole reference2.7 rejected. No new current-runtime/source scores or counted items.'
reg['qualification']+=' Fresh-source A3 all41 native frames inspected; attentive4.6, whole reference2.7 rejected because palms hold and late phantom arch. No score transfer or accepted runtime/cinematic motion.'
reg['review_resources'].append(dict(path=P.relative_to(R).as_posix()+'/index.html',scope='All41 native fresh-source local A3 frames on7 native-size boards/13 original details;8 component/action opinions; reference2.7 rejected.'))
write(L/'ALL_ITEMS.json',reg)
h=L/'all_items.html';raw=h.read_text(encoding='utf-8');raw=raw.replace('V36_FRESH_NURSERY_ATTENTION_AND_REJECTED_A2','V37_REJECTED_FRESH_SOURCE_NURSERY_A3');raw=raw.replace('<script>','<p>Fresh-source local A3: <a href="../../'+P.relative_to(R).as_posix()+'/index.html">Every41 native frame/eight component opinions; attention4.6, action2.7 rejected</a>. Palms hold; late white head-to-basin arch fails material truth. Fresh still4.5/current game wash3.9 remain separate.</p><script>',1);h.write_text(raw,encoding='utf-8',newline='\n')
note='Fresh-source Nursery A3 review continuation (2026-10-02): [all41 native frames on7 complete native-size boards and13 full-native details](../assets_src/local_motion/nursery_connected_scrub_v3_20261002/index.html) directly inspected. Reference attention4.6, low palm contact4.4; reciprocal rubbing2.8/fixture-material3.0/whole action2.7 rejected. Hands nearly hold; extra tap traces followed by a large white head-to-basin arch fail material truth. Fresh still4.5, current game wash3.9/attention3.8 and all783 production bytes unchanged. Known registerV37 retains1802 counted entries; reference-frame opinions are separately linked, not accepted source/runtime additions. Both blocked approvals and all device/child/owner/all-job/integration/release gaps remain; finding lifecycles unchanged.'
master=R/'audit/MASTER_AUDIT_2026-08-09.md';raw=master.read_text(encoding='utf-8');raw=raw.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+note+'\n',1).replace('### Development task index\n','### Development task index\n\n'+note+'\n',1);master.write_text(raw,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';raw=ledger.read_text(encoding='utf-8');raw=raw.replace('`CANDIDATE_REFERENCE_ONLY`; fresh attentive text-only A2 source reused locally','`REJECTED_REFERENCE_STUDY`; fresh attentive text-only A2 source reused locally').replace('All41 native frames pending direct review; current production/action3.9/attention3.8 unchanged.','All41 native frames directly inspected on7 native-size boards plus13 full-native details. Attention4.6; reciprocal2.8/fixture3.0/action2.7 rejected. Current production/action3.9/attention3.8 unchanged.');ledger.write_text(raw,encoding='utf-8',newline='\n')
findings=R/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';raw=findings.read_text(encoding='utf-8');raw+='\nFresh-source Nursery A3 review (2026-10-02): [all41 native frames/eight separate opinions](../../assets_src/local_motion/nursery_connected_scrub_v3_20261002/index.html) directly inspected. Attention4.6 remains, but reciprocal2.8/fixture-material3.0/whole reference2.7 rejected; nearly held hands and late phantom white head-to-basin arch. Current wash3.9/attention3.8 and all783 production bytes unchanged. MA-VIS-006/MA-PLAY-004/MA-OPERA-012 lifecycle states remain open; no accepted runtime/action/cinematic/device/child/owner/all-job/integration/release claim.\n';findings.write_text(raw,encoding='utf-8',newline='\n')
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v35.py')],cwd=R,check=True)
d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in P.rglob('*') if x.is_file()}|{x.relative_to(R).as_posix() for x in hist.rglob('*') if x.is_file()}|{(L/name).relative_to(R).as_posix() for name in ('ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json')}|{findings.relative_to(R).as_posix()});d['validation'].append(dict(command='All41 native canvases direct review on7 native-size boards plus13 original full-native details',result='FAIL',evidence=(A/'DIRECT_REVIEW.json').relative_to(R).as_posix()+'; action2.7 rejected, attention4.6 separate.'));d['acceptance_gaps']='All41 native frames reviewed, reference2.7 rejected/rubbing2.8/material3.0; gaze4.6 is reference-only. Failed native/output/dispatch/source preserved. Current game wash3.9/attention3.8, fresh still4.5 and all783 literal production bytes unchanged. No runtime/cinematic/device/child/owner/all-job/integration/release acceptance or pending-approval bypass. Next bounded refinement must address actual reciprocal motion and false material before any binding.';write(ip,d)
print('A3_ALL41_REVIEWED_REJECTED|attention4.6|rub2.8/material3.0/action2.7|V37 count1802 unchanged|all783 sources unchanged')
