from pathlib import Path
import datetime, hashlib, html, json, shutil

r = Path.cwd()
f = r/'assets_src/imagegen/day2_boxing_single_gloves_v1_20261001'
now = datetime.datetime.now(datetime.timezone.utc).isoformat()
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
read = lambda p: json.loads(p.read_text(encoding='utf-8'))
def write(p, obj):
    p.write_text(json.dumps(obj, indent=2, ensure_ascii=False)+'\n', encoding='utf-8', newline='\n')
assert not (f/'REVIEW.json').exists(), 'Preserve earlier review'
data = read(f/'native_static_fit_v1/CAPTURE_RECEIPT.json')
assert len(data['views']) == 24
rows = []
for v in data['views']:
    assert sha(f/'native_static_fit_v1'/v['path']) == v['sha256']
    assert v['landed_punches']==0 and v['phase_progress']==0 and v['stars']==0
    painted = v['treatment']=='painted'
    rows.append(dict(**v, directly_viewed=True,
        inspection=('Complete individual native image' if painted else 'Complete-canvas thumbnail on one of two six-view boards'),
        glove_style_and_mounted_fit_score=4.6 if painted else 4.0,
        contact_static_fit_score=4.6 if painted and v['pose']!='idle' else None,
        complete_action_score=None,
        opinion=('Continuous padded mitten silhouette, inward side thumb, coral/teal cuff identity and cream shell medallion remain legible. Broad matte paint bands and plum contours match the room and target mitts. Both hands remain complete and clear of the viewport edge in these staged positions. Contact cloud leaves the imp face readable.' if painted else 'Flat compound circles and heavy uniform violet outlines appear much simpler than the painted target mitts, costume and room. Thumb-like bump and small cuff are readable, but their material treatment is below the shared style bar.')))
write(f/'native_static_fit_v1/VISUAL_REVIEW.json', dict(status='ALL_24_STATIC_VIEWS_DIRECTLY_REVIEWED', reviewed_utc=now, views=rows,
    supplied_frame_count=24, painted_individual_native_view_count=12, original_complete_board_view_count=12,
    qualification='Appearance-only diagnostic subclass in actual career room, with staged idle/left/right contact positions. No touch requests or chronological action; zero hits, phase progress and stars. Two widths and two modes, not all routes or device/owner acceptance.'))
profile=read(f/'PROFILE.json');profile['initial_status']=profile['status'];profile['status']='TWO_SELECTED_SOURCES_AND_STATIC_FITS_4_6_UNBOUND'
profile['updated_utc']=now
profile['acceptance_gaps']='Individual native sources and 12 painted native static mounted/contact views meet the drafting target at4.6. Rejected left finger-lobe attempt4.3 is preserved. Whole-canvas1024 normalization is technical only. Timed input/contact/release, remaining boxing modes and actual job/training routes, phone, child, owner and complete report approval remain open; production glove drawings are still unchanged at this review boundary.'
write(f/'PROFILE.json',profile)
for name in ['LEFT_SELECTED_SOURCE_REVIEW.json','RIGHT_SELECTED_SOURCE_REVIEW.json']:
    d=read(f/name);d['initial_mounted_score']=d['mounted_score'];d['mounted_score']=4.6
    d['mounted_scope']='Both widths, jab/imp, idle and both contact positions; appearance-only native fixture. Timed/route acceptance remains open.';write(f/name,d)
prompt=read(f/'LEFT_ATTEMPT_01_PROMPT.json')
if 'prompt' in prompt:prompt['prompt_sha256']=hashlib.sha256(prompt['prompt'].encode()).hexdigest();write(f/'LEFT_ATTEMPT_01_PROMPT.json',prompt)
review=dict(status=profile['status'],reviewed_utc=now, original_control_score=4.0,
    individual_items=[dict(id='BOXING-GLOVE-LEFT-V1',source='left_attempt_02_native.png',source_sha256=sha(f/'left_attempt_02_native.png'),runtime_size_candidate='left_whole_canvas_1024.png',normalized_sha256=sha(f/'left_whole_canvas_1024.png'),source_score=4.6,static_mounted_score=4.6,timed_action_score=None,owner_approved=False),dict(id='BOXING-GLOVE-RIGHT-V1',source='right_attempt_01_native.png',source_sha256=sha(f/'right_attempt_01_native.png'),runtime_size_candidate='right_whole_canvas_1024.png',normalized_sha256=sha(f/'right_whole_canvas_1024.png'),source_score=4.6,static_mounted_score=4.6,timed_action_score=None,owner_approved=False)],
    rejected_attempts=[read(f/'LEFT_ATTEMPT_01_REVIEW.json')],
    visual_evidence='native_static_fit_v1/VISUAL_REVIEW.json',machine_evidence='native_static_fit_v1/PROCESS_RECEIPT.json',
    acceptance_gaps=profile['acceptance_gaps'])
write(f/'REVIEW.json',review)
def fig(path, caption):
    return '<figure><a href="'+html.escape(path)+'"><img loading="lazy" src="'+html.escape(path)+'" alt="'+html.escape(caption)+'"></a><figcaption>'+html.escape(caption)+'</figcaption></figure>'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Boxing — individual painted glove replacements</title><style>body{font:17px/1.55 system-ui;background:#eef4ff;color:#26304e;margin:0}main{max-width:1180px;margin:auto;padding:24px}section{background:white;padding:20px;border-radius:16px;margin:18px 0}h1,h2,h3{line-height:1.2}a{color:#514195}img{max-width:100%;display:block;height:auto}figure{margin:16px 0}figcaption{font-size:14px;color:#4c5368}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:18px}.source{background:repeating-conic-gradient(#dce5ed 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}.source img{width:300px;margin:auto}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:9px;border-bottom:1px solid #d8dfec}</style><main><h1>Boxing gloves — independent painted replacements</h1><p><a href="../../../audit/job_artwork_refinement_live/index.html">All-jobs library</a> · <a href="REVIEW.json">Individual scores and evidence</a> · <a href="PROFILE.json">Reuse inventory and generation gap</a></p><section><h2>Two individual source and static-fit drafts at 4.6/5</h2><p>The current procedural controls score 4.0: their flat circles and heavy uniform ink feel simpler than the painted mitts, boxer costume and room. The approved glove-pair card is fused at its center, so it cannot supply two complete independently controlled contours. The boxer costume sheet contains body-attached gloves with a different perspective. New generation is limited to the two missing standalone gameplay props.</p><p>The coral-cuff left glove and teal-cuff right glove preserve distinct hand identity, with inward side thumbs and one continuous padded mitten dome each. Matte warm paint bands, restrained aqua/lavender shading, plum contours and small cream shell medallions fit the toy world. The first left attempt was rejected for finger-like lobes and preserved. The corrected left and first right native sources each score 4.6.</p><p>All 12 painted native static views were inspected individually, and all 12 original views were inspected on two complete-canvas boards. Both sources also score 4.6 mounted at rest and at staged left/right contact in jab and imp rooms at 1280 and 1600 widths. These are static appearance comparisons. Timed movement, actual input and all boxing modes remain separate. Production bindings are unchanged at this review boundary.</p></section><section><h2>Selected individual artwork</h2><div class="grid"><div class="source">'''
page+=fig('left_attempt_02_native.png','Left glove, attempt 2 — native source 4.6; coral cuff, thumb to viewer right')+'</div><div class="source">'+fig('right_attempt_01_native.png','Right glove, attempt 1 — native source 4.6; teal cuff, thumb to viewer left')+'</div></div><table><tr><th>Individual item</th><th>Source /5</th><th>Mounted static /5</th><th>Timed action</th></tr><tr><td>Left painted glove</td><td>4.6</td><td>4.6</td><td>Pending</td></tr><tr><td>Right painted glove</td><td>4.6</td><td>4.6</td><td>Pending</td></tr><tr><td>Procedural control style</td><td>4.0</td><td>4.0</td><td>Earlier complete action 4.0</td></tr></table></section><section><h2>Rejected first left attempt</h2><div class="source">'+fig('left_attempt_01_native.png','Preserved rejection — source 4.3; finger-like lobes 4.1, matte material 4.6')+'</div><p>Separate finger-like knuckle lobes read as a padded bare fist. The successful correction requires one smooth protective mitten dome. No pixels from this rejected source enter a runtime candidate.</p></section><section><h2>Existing art and technical normalization</h2><div class="grid">'+fig('../../../assets/opera/worlds/widgets/widget_push_boxer_mover.png','Approved fused glove pair D2A-0546 — source 4.5; unable to supply two intact independent cards')+fig('../../../assets/opera/worlds/widgets/widget_track_boxer_mover.png','Approved target mitts — style and contact reference; retained unchanged')+'</div><p>The complete 1254×1254 native canvases are uniformly normalized to 1024×1024 by Lanczos. No crop, mask, repaint, warp, isolated resizing or subject repair occurs. Native originals and prompt/source hashes remain preserved in <a href="NORMALIZATION_PROFILE.json">the normalization record</a>. The two complete cards use the existing glove position, depth scale and angle in the unbound appearance-only diagnostic renderer.</p></section><section><h2>All 24 complete native static comparisons</h2><p>Each mode and width has an original control and painted candidate at idle, left contact and right contact. Contact positions and cloud are explicitly staged, with zero input, hits, phase progress or stars. Correct hand ownership and sequence are not established by this fixture.</p><div class="grid">'
for v in rows:page+=fig('native_static_fit_v1/'+v['path'],v['path'].replace('_',' ')+' — glove static style '+str(v['glove_style_and_mounted_fit_score'])+'/5')
page+='</div></section><section><h2>Bounded evidence and remaining work</h2><p><a href="native_static_fit_v1/PROCESS_RECEIPT.json">Parser, inference, three official Godot 4.7.2 analyzers, normalization and native capture all pass</a>; literal source bytes are unchanged across this capture. All 24 images retain exact hashes. Desktop native appearance review does not establish phone performance, child readability, actual job-day/training traversal, or owner approval.</p><p>The nearby <a href="../../../audit/day_two_boxing_puff_reuse_v1_20261001/index.html">puff review</a> retains an abrupt fade ending at 4.2 and imp reaction/recovery acting at 3.8. Painted gloves do not clear those separate weaknesses. Reversible binding, both-hand timed review and shared regression checks are the next bounded work. Hundreds of other job items and the comprehensive owner-approved report remain open.</p></section></main></html>'
(f/'index.html').write_text(page,encoding='utf-8',newline='\n')
t=f/'review_tools';t.mkdir()
for p in [Path(__file__),r/'tmp/run_boxing_single_glove_fit_v1.py']:shutil.copyfile(p,t/p.name)
lic=r/'ASSET_LICENSES.md';text=lic.read_text(encoding='utf-8')
for p in sorted(f.rglob('*')):
    if not p.is_file() or p.suffix.lower() not in ['.png','.webp']:continue
    rel=p.relative_to(r).as_posix()
    if '`'+rel+'`' in text:continue
    if p.parent==f:
        detail='OpenAI built-in imagegen; fresh text-only source with zero uploaded references; exact prompts/hashes in source profile; whole-canvas1024 derivatives use uniform technical normalization; rejected left attempt retained outside runtime; no owner approval'
        row=f'| `{rel}` | OpenAI imagegen | Generated project artwork; review candidate | Local built-in imagegen | {detail} |\n'
    else:row=f'| `{rel}` | Mermaid Roshan project art / Godot native capture | Existing project provenance; review-only derivative | Local project | Complete native static fixture or uniformly scaled complete-canvas review board; source hashes retained; no played chronology or owner approval |\n'
    text+=row
lic.write_text(text,encoding='utf-8',newline='\n')
attr=r/'.gitattributes';a=attr.read_text();rule=f'{f.relative_to(r).as_posix()}/** -text'
if rule not in a:attr.write_text(a+'\n'+rule+'\n',encoding='utf-8',newline='\n')
impact=r/'design/audit_impacts/day-two-boxing-single-gloves-v1-20261001.json';d=read(impact)
d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','.gitattributes','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/STATUS.json'})
d['validation'].extend([dict(command='All24 native static original/candidate views reviewed',result='PASS',evidence=(f/'native_static_fit_v1/VISUAL_REVIEW.json').relative_to(r).as_posix()),dict(command='Parser/inference/three official4.7.2 analyzers, whole-canvas normalization and native static capture',result='PASS',evidence=(f/'native_static_fit_v1/PROCESS_RECEIPT.json').relative_to(r).as_posix())]);d['acceptance_gaps']=profile['acceptance_gaps'];write(impact,d)
master=r/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8')
paragraph='Boxing individual-glove refinement (2026-10-01): [two painted source candidates and all24 native static comparisons](../assets_src/imagegen/day2_boxing_single_gloves_v1_20261001/index.html) replace the measured4.0 procedural-style gap in review only. Corrected coral left and teal right sources/static fits are4.6; first left finger-lobe attempt4.3 remains rejected. Reuse inventory records why the fused approved pair and body-attached atlas cannot provide intact independently controlled contours. Original control drawings remain unchanged at this review boundary. Timed input/all modes/routes/device/child/owner acceptance and the complete report remain open. [Impact](../design/audit_impacts/day-two-boxing-single-gloves-v1-20261001.json).\n\n'
assert 'Boxing individual-glove refinement (2026-10-01)' not in s;s=s.replace('Boxing puff exact-reuse review',paragraph+'Boxing puff exact-reuse review',1);master.write_text(s,encoding='utf-8',newline='\n')
ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');s+='\n| `assets_src/imagegen/day2_boxing_single_gloves_v1_20261001/index.html` | 🟣 | `CANDIDATE`; two individual painted glove sources and12 direct native static painted fits4.6. All24 static views reviewed, originals on two full-canvas boards; rejected finger-lobe attempt4.3 preserved. Whole-canvas1024 normalization and source hashes recorded. Production draws unchanged at review boundary; timed/mode/route/device/child/owner/global acceptance remain open. |\n';ledger.write_text(s,encoding='utf-8',newline='\n')
entry=r/'audit/job_artwork_refinement_live/index.html';s=entry.read_text(encoding='utf-8');s=s.replace('<p><a href="../day_two_boxing_puff', '<p><a href="../../assets_src/imagegen/day2_boxing_single_gloves_v1_20261001/index.html">Boxing gloves: two individual painted sources and static fits 4.6; rejected left finger-lobe draft retained</a>. Timed/all-mode review remains pending.</p><p><a href="../day_two_boxing_puff',1);entry.write_text(s,encoding='utf-8',newline='\n')
status=r/'audit/job_artwork_refinement_live/STATUS.json';d=read(status);d['current_boxing_gloves']=dict(status=profile['status'],review=review['visual_evidence'],report=(f/'index.html').relative_to(r).as_posix(),individual_source_static_scores=[4.6,4.6],timed_acceptance=False,owner_approved=False);write(status,d)
print('Glove source/static report completed; 24 views reviewed; production unchanged.')
