"""Rebuild the review from exact, existing Mobile captures; never grades assets."""
from pathlib import Path
import ast, hashlib, html, json
import numpy as np
from PIL import Image, ImageDraw
OUT=Path(__file__).resolve().parent
REPO=next(p for p in OUT.parents if (p/'project.godot').exists())
B=REPO/'assets_src/sky_lagoon/animated_rebuild_v1_2026-09-20'
CAP=OUT.parent/'twelve_cloud_render'
ns={}
for node in ast.parse((B/'build_six_screen_color_audit.py').read_text()).body:
 if isinstance(node,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='PATCHES' for t in node.targets):
  exec(compile(ast.Module(body=[node],type_ignores=[]),'patches','exec'),ns)
patches=ns['PATCHES']
patches['arrival'].update({'tree_canopy':[30,180,85,224],'cream_flower':[589,416,608,446],'purple_berries':[489,638,518,665],'shore_rock':[180,470,202,488],'high_cloud':[754,142,775,160],'HUD':[43,39,68,52],'tree_trunk':[25,246,43,271]})
patches['meadow'].update({'high_cloud':[532,151,551,171],'cream_flower':[144,411,162,437],'shore_rock':[1161,444,1180,459]})
patches['castle'].update({'high_cloud':[215,167,235,182],'cream_flower':[1104,566,1123,587],'gold_trim':[1050,334,1071,342],'roof':[1135,240,1152,253],'portrait':[949,257,1000,313],'window':[1130,389,1140,408],'bridge_post':[844,485,852,499]})
patches['castle']['mountain']=[686,151,714,173]
patches['castle']['castle_wall']=[778,407,792,433]
findings=[
 {'priority':'P1','family':'Foreground foliage / rear hedges','finding':'Smooth rounded foreground clumps have pale highlights and lower saturation than the fine, dappled rear hedge. Large pointed foreground leaves are darker. A universal foreground brightness or saturation adjustment would push one family further out of balance.','action':'Match leaf shape and painted highlight width first; then grade only the offending leaf material. Preserve the purple berries and intentional front-to-back contrast.','decision':'Color-only clump trial not selected; one pointed-leaf replacement has entered eight-cel contextual review, not runtime acceptance.'},
 {'priority':'P1','family':'Night foliage','finding':'Large foreground leaves lose internal shadow detail at night. This is a value-range and ambient-tint problem, not a reason to brighten every leaf or change the whole night palette.','action':'Test a restrained leaf-shadow lift against its adjoining hedge in all three views. Keep roots and gaps dark enough to read depth.','decision':'Existing night-only leaf lift was too localized to resolve the scene; not selected.'},
 {'priority':'P1','family':'Lawn and animated grass','finding':'Yellow-green lawn marks remain much brighter than many foreground leaf masses, and sparse bright moving flecks do not describe coherent whole grass.','action':'Anchor grass colors to its own lawn patch, animate complete connected tufts and preserve quieter grass around paths. Review root shade and blade highlights across every cel.','decision':'One accent tuft is implemented; broad ground-cover motion and cross-screen lawn coherence remain open.'},
 {'priority':'P2','family':'Flowers and berries','finding':'Cream/yellow flowers are strong local accents, especially beside the castle. Purple berry identity is useful, but repeated pale clusters draw a visual rhythm unrelated to the planting groups.','action':'Keep cream, pink and purple distinct. Limit repeated pale clusters and align each flower group with a plausible supporting plant; no global desaturation.','decision':'Needs grouped planting review and whole-cel comparisons.'},
 {'priority':'P2','family':'Sky, high clouds, cloud sea and mountains','finding':'Cool distance colors support depth. Some high cloud cards have broader purple shadow lobes than the fine cloud sea. Equalizing their contrast would flatten the panorama.','action':'Compare cloud shadow hue and edge softness at drift extremes while retaining lower contrast in the distant banks.','decision':'Twelve cloud cards now have multiple cels; the low cloud sea remains an unintegrated motion study.'},
 {'priority':'P2','family':'Water and shore stones','finding':'Cyan water reads clearly against lavender/grey shore stones. Darker water gives the bridge a useful boundary; bright ripple highlights need event-state review.','action':'Preserve shore continuity; audit ripple onset/peak/fade and water cels for hue or luminance pumping, separately from fixed shoreline samples.','decision':'These six stills do not establish all water interaction states.'},
 {'priority':'P2','family':'Paths, left castle approach and bridge','finding':'Lavender main paths and the pale warm bridge remain distinguishable in these views. The left uphill approach is deliberately less prominent, but must remain discoverable.','action':'Protect the route palette and path clearances during plant edits; inspect bridge flex/contact poses and path edges at all camera positions.','decision':'No route recoloring proposed from these samples alone.'},
 {'priority':'P2','family':'Castle walls, roofs, gold and windows','finding':'Purple architecture and warm trim form a coherent focal point. Night ambient tint dims windows and reflective accents with opaque surfaces; those materials need independent treatment.','action':'Separate modest warm window/glint accents from wall ambient grade; avoid restoring day-bright walls. Keep the four towers and protected portrait intact.','decision':'Night emission and entry hierarchy remain open.'},
 {'priority':'P2','family':'Playground, tree and props','finding':'Muted aqua playground surfaces fit the cool landscape. Their broad smooth paint differs from foliage detail, appropriately for another material; lighting consistency still needs contact-state review.','action':'Preserve material distinction. Check shared night tint, contact shadows and side-by-side duplicates at camera overlaps.','decision':'Do not force props to match plant saturation.'},
 {'priority':'OPEN','family':'Roshan, animals, portrait, HUD and interaction cues','finding':'Roshan and HUD stay bright at night, aiding visibility. They are not environmental palette targets. The portrait contains many identity colors, so a single rectangle average has no grading authority.','action':'Preserve protected colors. Audit cue visibility at action peaks and phone size, with actors and HUD shown in context.','decision':'Actor samples are mixed-pixel diagnostics only; animal, transient cue, device and owner acceptance remain open.'}
]
def measure(im,box):
 c=im.crop(box); rgb=np.asarray(c,dtype=float)/255
 lin=np.where(rgb<=.04045,rgb/12.92,((rgb+.055)/1.055)**2.4)
 l=lin@np.array([.2126,.7152,.0722]); hsv=np.asarray(c.convert('HSV'),dtype=float)/255
 return {'linear_luminance_p10_p50_p90':np.percentile(l,[10,50,90]).round(5).tolist(),'HSV_saturation_median':round(float(np.median(hsv[:,:,1])),5),'sRGB_median':np.median(rgb.reshape(-1,3),axis=0).round(4).tolist()}
board=Image.new('RGB',(1280,1140),'#203039'); marked=Image.new('RGB',(1280,2160)); rows=[]; sources=[]
for i,(stage,areas) in enumerate(patches.items()):
 images={}
 for col,mode in enumerate(['day','night']):
  p=CAP/f'{stage}_{mode}.png'; im=Image.open(p).convert('RGB'); assert im.size==(1280,720); images[mode]=im
  sources.append({'path':p.relative_to(REPO).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'dimensions':list(im.size)})
  board.paste(im.resize((640,360)),(col*640,i*380));ImageDraw.Draw(board).text((col*640+8,i*380+364),f'{stage} / {mode} / current checkpoint',fill='white')
 ann=images['day'].copy();draw=ImageDraw.Draw(ann)
 for n,(name,box) in enumerate(areas.items(),1):
  rows.append({'stage':stage,'sample_id':n,'material':name,'rect_xyxy':box,**{mode:measure(im,box) for mode,im in images.items()}})
  draw.rectangle(box,outline='#ff4560',width=2);draw.text((box[0],max(0,box[1]-12)),str(n),fill='white',stroke_width=2,stroke_fill='#70202f')
 marked.paste(ann,(0,i*720))
board.save(OUT/'day-night-board.jpg',quality=94);marked.save(OUT/'sample-map.jpg',quality=94)
report={'status':'OPEN_FINDINGS_NOT_VISUAL_ACCEPTANCE','checkpoint':'73a7c21b3ecc1e84d72ed040d7fb79f956533cdc','scope':f'{len(rows)} mapped material samples across three stages in daylight and night. Visible material-family coverage, not every pixel, every pose, every interaction or full pan coverage.','method':'Exact existing Godot 4.7.2 Forward Mobile captures. Linear-light Rec.709 luminance and HSV saturation within unmasked rectangles. Different species, shade, mixed pixels and unsynchronized dynamic poses confound comparisons; values are diagnostics, never universal grading targets.','sources':sources,'samples':rows,'findings':findings,'rollback':'Review only: no runtime colors, protected sources or saved-game settings changed.','required_next_evidence':['Same-species leaf-band comparisons and edge composites for each proposed correction','Matched per-cel temporal color checks; distinguish coverage change from palette flicker','All camera overlaps, cloud drift extremes and route clearances','Bridge contact; ripple onset, peak and fade; animal and touch-cue states','Target-device and owner acceptance'],'owner_score':3.5,'new_quality_score':None}
(OUT/'AUDIT.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
esc=html.escape
cards=''.join(f"<article><b>{esc(f['priority'])} · {esc(f['family'])}</b><p>{esc(f['finding'])}</p><p><strong>Next:</strong> {esc(f['action'])}</p><small>{esc(f['decision'])}</small></article>" for f in findings)
trs=''.join(f"<tr><td>{r['stage']} {r['sample_id']}</td><td>{r['material']}</td>"+''.join(f"<td>{r[m]['linear_luminance_p10_p50_p90'][1]:.3f}</td><td>{r[m]['HSV_saturation_median']:.3f}</td>" for m in ['day','night'])+'</tr>' for r in rows)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sky Lagoon color review</title><style>body{margin:24px auto;padding:0 20px;max-width:1280px;background:#172731;color:#e5edf0;font:16px/1.55 system-ui}h1{font-size:28px}img{max-width:100%;height:auto}article{padding:18px;background:#223944;margin:12px 0;border-radius:8px}small{color:#bdd0d7}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:7px;text-align:left;border-bottom:1px solid #49606a}a{color:#9cdef3}</style><h1>Sky Lagoon — material color review</h1><p>All three screens, daylight and night. Current checkpoint 73a7c21b. Findings remain open; the latest owner score is 3.5/5. No new score or acceptance is claimed.</p><p>Foreground and background do not need identical saturation. They need compatible painted materials, deliberate depth and readable routes. This review changes no runtime colors.</p><img src="day-night-board.jpg" alt="Three screens, day at left and night at right"><h2>Corrections in priority order</h2>'''+cards+'''<h2>Mapped diagnostics</h2><p>These mixed-pixel samples are review aids, not grading targets. L is linear luminance; S is HSV saturation. Day/night poses are not synchronized.</p><details><summary>Show sample map</summary><img src="sample-map.jpg" alt="Material sample locations"></details><table><thead><tr><th>Screen / ID</th><th>Material</th><th>Day L</th><th>Day S</th><th>Night L</th><th>Night S</th></tr></thead><tbody>'''+trs+'''</tbody></table><p><a href="AUDIT.json">Exact source hashes, measurements and acceptance gaps</a></p></html>'''
(OUT/'index.html').write_text(page,encoding='utf-8')
print('COLOR_REVIEW',len(rows),'samples',len(sources),'source images',len(findings),'material-family decisions')
