from pathlib import Path
import datetime, hashlib, json, re, shutil

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/reuse/geology_geode_emblems_v1_20261002'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
plan=read(f/'PLAN.json');assert plan['status']=='UNBOUND_REUSE_CANDIDATE'
source='assets/opera/worlds/geology/coherent_geode_v1_20261002/opening_six_states.png';region=[96.974069898534,68.112739571590,473.325817361894,421.375422773393]
resource='[gd_resource type="AtlasTexture" load_steps=2 format=3]\n\n[ext_resource type="Texture2D" path="res://'+source+'" id="1_geode"]\n\n[resource]\natlas = ExtResource("1_geode")\nregion = Rect2('+', '.join(str(x) for x in region)+')\nfilter_clip = true\n';p=f/'closed_geode_unbound.tres';assert not p.exists();p.write_text(resource,encoding='utf-8',newline='\n')
for rel in ['assets/opera/worlds/geology/painted_geode_v1_20261001/closed.png','scripts/opera_hotspot_catalog.gd']:
 plan['inventory'].append(dict(path=rel,sha256=sha(b/rel),bytes=(b/rel).stat().st_size))
plan['scope']+=' Also retain one matching closed-state window for the current geode invitation; actual Library-route capture and literal catalog show the invitation still uses the previous closed source. The old source is acceptable isolated art; this reuse aims at invitation-to-opening identity continuity, not novelty.'
plan['additional_candidate']=dict(path=p.relative_to(b).as_posix(),region=region,width=142,expected_height=142*region[3]/region[2],proposed_runtime_resource='assets/opera/worlds/geology/coherent_geode_v1_20261002/closed_geode.tres',literal_current_binding='scripts/opera_hotspot_catalog.gd GEODE path painted_geode_v1_20261001/closed.png, region192,213,645,602,142x132.5333333333',required_changes='Future catalog path/resource-dimension/presentation allowlist for only the same closed geode, preserve offset, arming, hit target, phase/progress/save/return. Current frozen production untouched.')
plan['required_evidence'].append('After future binding: inspect exact same closed invitation/opening identity, actual reach/target geometry and whole-cache decoded texture budget. Metadata reuse holds the full atlas in memory.')
write(f/'PLAN.json',plan)
scale=142/region[2];crop=f'<div class="crop" style="width:142px;height:{region[3]*scale}px"><img src="../../../{source}" alt="Same opening-family closed geode at142px; unbound" style="width:{2048*scale}px;height:{1024*scale}px;left:{-region[0]*scale}px;top:{-region[1]*scale}px"></div>'
old=[192,213,645,602];oldscale=142/old[2];oldcrop=f'<div class="crop" style="width:142px;height:{old[3]*oldscale}px"><img src="../../../assets/opera/worlds/geology/painted_geode_v1_20261001/closed.png" alt="Existing older closed invitation at142px" style="width:{1024*oldscale}px;height:{1024*oldscale}px;left:{-old[0]*oldscale}px;top:{-old[1]*oldscale}px"></div>'
section='<article id="closed-invitation"><h2>142 pixels · matching closed invitation</h2><div class="compare" style="background:#193046"><figure>'+oldcrop+'<figcaption>Existing approved source</figcaption></figure><figure>'+crop+'<figcaption>Same opening-family source</figcaption></figure></div><p>The actual invitation currently uses the previous closed geode. Its standalone source is acceptable, while exact invitation-to-opening identity remains separate. This same-source metadata candidate uses the current seven-state family and preserves its aspect. Isolated comparison review pending; no production binding is changed.</p></article>'
p=f/'index.html';s=p.read_text(encoding='utf-8');assert s.endswith('</main></html>');s=s[:-len('</main></html>')]+section+'</main></html>';s=''.join(re.sub(r'(?<=[a-z])(?=\d)',' ',x) if i%2==0 else x for i,x in enumerate(re.split(r'(<[^>]*>)',s)));p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/Path(__file__).name)
licenses=b/'ASSET_LICENSES.md';s=licenses.read_text(encoding='utf-8');s+='\n| `'+(f/'closed_geode_unbound.tres').relative_to(b).as_posix()+'` | Existing built-in Codex geode source, AtlasTexture metadata | Same generated-project-art provenance as `'+source+'` | `'+f.relative_to(b).as_posix()+'/PLAN.json` | Matching closed-state source window; pixels and alpha intact; unbound invitation continuity candidate. |\n';licenses.write_text(s,encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-geology-geode-emblem-reuse-20261002.json';d=read(ip);d['scope']+=' Additional unbound same-family closed invitation metadata and actual catalog trace; acceptable original preserved, no invented source defect.';d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'assets/opera/worlds/geology/painted_geode_v1_20261001/closed.png'}))
print('Prepared same-family closed invitation metadata; current production frozen.',flush=True)
