from pathlib import Path
import datetime, hashlib, html, json, shutil, subprocess

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f=b/'assets_src/reuse/geology_geode_emblems_v1_20261002';assert not f.exists();f.mkdir(parents=True)
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
baseline=subprocess.check_output(['git','rev-parse','HEAD'],cwd=b,text=True).strip();assert baseline=='c6f03791aee93f1443d423dd50334804e37313fb'
source='assets/opera/worlds/geology/coherent_geode_v1_20261002/opening_six_states.png'
assert sha(b/source)=='e47a731414210ef70c0b5fffce2828922a15611c6093c244811ee0a283534503'
region=[1392.270574971815,556.446448703495,617.632468996618,393.668545659527]
resource='[gd_resource type="AtlasTexture" load_steps=2 format=3]\n\n[ext_resource type="Texture2D" path="res://'+source+'" id="1_geode"]\n\n[resource]\natlas = ExtResource("1_geode")\nregion = Rect2('+', '.join(str(x) for x in region)+')\nfilter_clip = true\n'
(f/'open_geode_unbound.tres').write_text(resource,encoding='utf-8',newline='\n')
inventory=[]
for rel in [source,'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/attempt_08/native.png','assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/attempt_08/GENERATION.json','assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/attempt_08/PROMPT.txt','assets/opera/worlds/ui/crests/opera_crest_geologist.svg','assets/opera/worlds/props/goal_geologist.svg','scripts/castle_career_routes.gd','scripts/opera_career_world_2d.gd']:
 inventory.append(dict(path=rel,sha256=sha(b/rel),bytes=(b/rel).stat().st_size))
write(f/'PLAN.json',dict(status='UNBOUND_REUSE_CANDIDATE',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseline=baseline,owner_direction='Geode opens to reveal crystals inside it; continue reversible weak-art refinement.',scope='Replace the specifically observed flat Library crest and normal OperaAct celebration emblem with the same authored open geode. No new art generation or pixel modification; one shared AtlasTexture references the current reviewed POT source.',inventory=inventory,region=region,gap_evidence='audit/job_geology_room_route_v1_20261002/REVIEW.json; actual Library crest and celebration emblem each2.9, celebration composition3.2.',proposed_runtime_resource='assets/opera/worlds/geology/coherent_geode_v1_20261002/open_geode.tres',proposed_binding_changes={'scripts/castle_career_routes.gd':'Geologist crest literal path only; preserve50px size/touch rail/save routing.','scripts/opera_career_world_2d.gd':'Geologist goal prop literal path only; preserve220px size/normal completion/reward/return.'},required_evidence=['Inspect isolated reuse at50,80,175,220px on real stage/Library palette.','After current frozen CI and checkpoint: bind only if readable, import officialGodot4.7.2, parser/inference/analyzer plus applicable probes.','Capture ordinary actual Library/elevator entry, four phases, normal celebration and earned Library return at1280/1600; inspect every image/frame.','Freeze new production hashes and run all82 probes before publication/integration claim.'],generation_method='No generation: shared AtlasTexture window, authored alpha preserved, no edited image output.',acceptance_gaps='Unbound preview has no runtime/action/device/child/owner score. Room2.8/contact2.7, stage curtains2.9 and overall celebration3.2 remain separately open. Current frozen368-source suite does not verify a later binding.'))
ip=b/'design/audit_impacts/job-geology-geode-emblem-reuse-20261002.json'
write(ip,dict(id='job-geology-geode-emblem-reuse-20261002',scope='Inventory and reversible shared open-geode resource candidate for two actual flat vector defects; inspect small and celebration presentations before changing frozen production.',baseline=baseline,rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-INT-01','DL-INT-02','DL-INT-03','DL-INT-04','DL-INT-06','DL-INT-12','DL-SAVE-01','DL-SAVE-02','DL-QA-01','DL-QA-02','DL-QA-03','DL-QA-06'],findings=['MA-VIS-006','MA-PLAY-004','MA-OPERA-012'],files=[],validation=[dict(command='Source inventory and pure metadata AtlasTexture reuse',result='PASS',evidence=f.relative_to(b).as_posix()+'/PLAN.json; identical existing generated source, no protected pixels or frozen production edited.'),dict(command='Actual mounted icon/celebration and fresh complete suite',result='PENDING',evidence='Unbound preview; later production not yet implemented.')],acceptance_gaps='Every source/preview/mounted/action/device/child/owner claim remains separate. No finding closure or integration/release.'))
source_url='../../../'+source
old_crest='../../../assets/opera/worlds/ui/crests/opera_crest_geologist.svg';old_goal='../../../assets/opera/worlds/props/goal_geologist.svg'
cards=[]
for width,palette,label in [(50,'#f6f9ff','Actual Library crest size'),(80,'#f6f9ff','Optional enlarged inspection only'),(175,'#193046','Room destination size study only'),(220,'#594062','Actual celebration goal size')]:
 scale=width/region[2];height=region[3]*scale
 art=f'<div class="crop" style="width:{width}px;height:{height}px"><img src="{source_url}" alt="Same open geode at{width}px; unbound preview" style="width:{2048*scale}px;height:{1024*scale}px;left:{-region[0]*scale}px;top:{-region[1]*scale}px"></div>'
 old=old_crest if width<=80 else old_goal
 cards.append(f'<article id="size-{width}"><h2>{width} pixels · {html.escape(label)}</h2><div class="compare" style="background:{palette}"><figure><img class="old" src="{old}" style="width:{width}px;height:{width}px" alt="Existing flat geologist emblem at{width}px"><figcaption>Existing</figcaption></figure><figure>{art}<figcaption>Painted reuse</figcaption></figure></div><p>Object/source readability review pending. This browser comparison does not contain the game actors, touch, completion or return.</p></article>')
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Open geode · crest and celebration reuse review</title><style>body{font:17px/1.6 system-ui;margin:0;background:#edf3f7;color:#253449}main{max-width:1100px;padding:24px;margin:auto}h1{font-size:30px}article{background:white;border:1px solid #a8b5cc;border-radius:18px;padding:20px;margin:18px 0}.compare{display:flex;align-items:center;justify-content:space-around;gap:20px;padding:28px;border-radius:15px;min-height:115px}figure{margin:0;display:flex;flex-direction:column;align-items:center}figcaption{background:#f6f9ff;color:#253449;padding:2px 12px;border-radius:10px;margin-top:12px}.crop{position:relative;overflow:hidden;flex-shrink:0}.crop img{position:absolute;max-width:none}a{color:#354bac}p{max-width:85ch}.qualification{background:#fff2cf;padding:15px;border-radius:10px}</style><main><h1>Open geode: carry the painted object through the route</h1><p class="qualification">Unbound source reuse study. The normal Library card and actual normal OperaAct celebration still use the flat vector emblem. Their current individual scores are2.9/5; the celebration composition is3.2/5. This page proposes the same rooted-crystal geode already used during opening, preserving the source pixels and its alpha.</p><p>No generated replacement image is needed for these two defects. One shared AtlasTexture window can serve both presentations. These previews are shown at literal CSS pixel sizes and preserve the original aspect. Optional sizes are labeled separately.</p><p><a href="../../../audit/job_geology_room_route_v1_20261002/index.html">Actual route and individual evaluations</a> · <a href="PLAN.json">Inventory, hashes and next evidence</a></p>'+''.join(cards)+'<p>Room, actor contact, curtains, motion and complete route acceptance remain separate. The frozen368-source suite applies to the existing opening; it does not verify this unbound metadata candidate. All originals are preserved.</p></main></html>'
(f/'index.html').write_text(page,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/Path(__file__).name)
licenses=b/'ASSET_LICENSES.md';s=licenses.read_text(encoding='utf-8');s+='\n| `'+f.relative_to(b).as_posix()+'/open_geode_unbound.tres` | Existing Codex imagegen geode; AtlasTexture metadata only | Same provenance as `'+source+'`; generated project artwork | `'+f.relative_to(b).as_posix()+'/PLAN.json` | Exact alpha-preserving source window; no pixel modification or new generation; unbound review candidate. |\n';licenses.write_text(s,encoding='utf-8',newline='\n')
d=read(ip);d['files']=sorted({p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';a=read(allow);a=sorted(set(a)|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{source,'assets/opera/worlds/ui/crests/opera_crest_geologist.svg','assets/opera/worlds/props/goal_geologist.svg'});write(allow,a)
print('Prepared unbound same-source crest/goal reuse; no368 frozen source changed.',flush=True)
