from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
base='6edb4ca8c57bfbfe3123636863a29c95165ac23f'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()==base
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def rel(p):return p.relative_to(r).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
v=r/'assets_src/vector/job_geology_teacher_refinement_v1_20261001'
correction=v/'OWNER_CORRECTION_V1.json';assert not correction.exists()
geo=sorted(p for p in v.glob('*.svg') if not p.name.startswith('teacher_'))
assert len(geo)==6
write(correction,dict(status='OWNER_REJECTED_GEOLOGY_VECTOR_STYLE_SOURCE_FLOORS_WITHDRAWN',recorded_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),source_revision=base,owner_instruction="How did the geologist artwork pass audit? It's all flat vector graphics! This needs a rebuild with imagen for certain. Coming along though, teacher game is improving nicely.",reason='The isolated4.5 vector drafting opinions were too generous: softened silhouettes and gradients do not establish the required painted storybook finish. The owner rejects the geology vector approach and explicitly commissions ImageGen rebuilding. Every prior prompt, candidate and score remains preserved as dated history. Four earlier selected geology source floors are withdrawn; teacher is separate and remains provisional.',items=[dict(path=rel(p),sha256=sha(p),current_source_score=3.9,current_status='REJECTED_BY_OWNER_FLAT_VECTOR_STYLE',earlier_score_evidence=[rel(v/'ATTEMPT01_REVIEW.json'),rel(v/'ATTEMPT02_REVIEW.json')],replacement_medium='Built-in ImageGen painted raster source; source/native mount/action scores remain separate.') for p in geo],teacher_scope='Teacher source attempts unchanged; owner says game is improving, not a final creative/device/action acceptance.',runtime_originals_unchanged=True))
s=(v/'index.html').read_text(encoding='utf-8');marker='<body>'
assert marker in s
s=s.replace(marker,marker+'<aside style="padding:18px;background:#fff0df;border:3px solid #9b5267"><strong>Owner correction: geology vectors rejected.</strong> The six geology vector drafts below are retained as history. Their earlier source-floor marks are withdrawn for the required painted storybook style; current source-style opinion3.9. Geology is being rebuilt with ImageGen. Teacher drafts remain separate and provisional. <a href="OWNER_CORRECTION_V1.json">Exact correction and hashes</a></aside>',1)
(v/'index.html').write_text(s,encoding='utf-8',newline='\n')
out=r/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001';assert not out.exists();out.mkdir();(out/'.gdignore').write_text('')
shutil.copyfile(__file__,out/'executed_prepare_geology_imagegen_rebuild_v88.py')
style='One polished hand-painted 2D storybook game prop for Mermaid Roshan, a preschool pastel toy playset. Soft matte gouache illustration, rounded handmade silhouette, fine varied plum/brown ink contour, a few broad painted cream/aqua/lavender value washes. Warm and high-key, gentle painted dimensionality, restrained grouped brush marks. It must look like a carefully painted picture-book object, never a flat SVG/vector diagram, geometric logo, photorealistic mineral specimen, rendered3D object or glossy plastic. Isolated complete object centered with generous clear margins on genuine transparent RGBA, no ground plate, checkerboard, scenery, writing, grid or UI.'
jobs=[
 dict(id='fossil',gap='Vector spiral slab lacks painted physical material; enlarged source is stretched and later cut into three assembly regions.',prompt=style+' Paint one broad, gently irregular oval lavender sandstone slab viewed straight at its front face, with a single large warm golden-cream ammonite fossil clearly embedded in the stone. The shell has one clean readable spiral and only6–8 broad gently rounded ridges, not dozens of tiny chambers. Keep stone and shell one attached sturdy toy-like mass. Two or three calm color/value groups, subtle lavender underside, no glitter, dense speckles or harsh white highlights. Leave the entire oval slab uncropped. Square native canvas, requested1024x1024.'),
 dict(id='layered_rock',gap='Layer-wall specimen is a coarse vector; existing PAN rock invitation also has a separate semantic misuse.',prompt=style+' Paint one chunky rounded cross-section sandstone specimen, straight-on with a small top plane, showing exactly three broad horizontal mineral strata: soft lavender upper layer, warm golden-cream middle layer, pale aqua lower layer. Preserve the simple three-color learning groups, with two large warm cream mineral inclusions in the middle area. Gentle irregular rounded stone edges and broad painted material values; no crisp vector stripes, black wedges, distributed pebbles, writing or diagram arrows. Square native canvas, requested1024x1024.'),
 dict(id='washing_pan',gap='Current procedural thick ellipse is flat; rock invitation does not depict panning.',prompt=style+' Paint one empty shallow mineral-washing pan seen slightly from above, a broad open ellipse with a thick rounded lavender stone rim and pale aqua water inside. The interior opening is generous and unobstructed for separately placed mineral grains and child touch input. One clear near rim and quiet soft reflection, substantial handmade bowl depth, no handle, stones, crystals, brush, drops outside the bowl or busy waves. Preserve one complete symmetrical readable pan suitable for back-and-forth panning. Square native canvas, requested1024x1024.'),
 dict(id='closed_geode',gap='Current split rock is a pair of flat dark procedural half ellipses; needs painted closed identity suitable for later matching split states.',prompt=style+' Paint one friendly round lavender geode stone viewed straight-on. It is closed, with a single narrow gently irregular vertical seam at the center to show where it will split. A softly chunky rounded silhouette, broad lilac highlight and aqua/lavender underside, only a few grouped restrained stone marks. No visible interior or crystals yet, no black center hole, no fracture fragments, no sharp realistic texture. Whole object uncropped, square native canvas requested1024x1024.'),
 dict(id='crystal_reward',gap='Current two-crystal reward and crest are flat vector silhouettes, partly hidden during actual geode opening.',prompt=style+' Paint exactly two generously sized gently faceted crystals, one pale aqua and one lavender, growing from one attached rounded light-lavender mineral base. The aqua crystal is slightly taller at left, lavender crystal at right. Use only2–3 broad painted facets per crystal, restrained cream glints, a clear joined silhouette and a soft painted base. Friendly mineral toy, no glitter, neon, dense facets, extra crystal spikes, gold pedestal or magical aura. Square native canvas, requested1024x1024.'),
]
for job in jobs:job.update(attempt=1,status='GENERATION_PENDING_UNBOUND',prompt_sha256=hashlib.sha256(job['prompt'].encode()).hexdigest(),transparent_background=True,reference_images=[],source_score=None,mounted_score=None,complete_action_score=None,owner_approval=None)
old=['assets_src/geologist_rebuild_2026-09-05/geology_props_candidate.png','assets_src/geologist_rebuild_2026-09-05/geology_props_alpha_retry.png','assets_src/geologist_rebuild_2026-09-05/geology_grotto_candidate.png','assets_src/minigame_art_quality_2026-09-05/geode-open-alpha-attempt02/native.png']
write(out/'GENERATION_QUEUE_V1.json',dict(status='OWNER_COMMISSIONED_PAINTED_GEOLOGY_REBUILD',baseline=base,prepared_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),owner_correction=rel(correction),inventoried_sources=[dict(path=p,sha256=sha(r/p),direct_native_review=True) for p in old],reuse_decision='Earlier geology prop sheets are explicitly REJECTED_RUNTIME with baked RGB checkerboards. Older grotto1672x941 is reference-only below2048x2048 native coverage. Older open geode has dense glossy facets and noisy edges unsuitable for simple child-readable painted replacement. Existing Roshan/imp atlases and the approved painted brush remain untouched/reused. Generate only named missing/owner-rejected prop and surface gaps.',jobs=jobs,followups=['Matching painted open-geode interior/halves must retain the accepted closed-geode identity, exact split seam and contact geometry; do not independently redesign states.','Painted fossil/river work surface and full friendly grotto environment need their own complete native evidence; do not retain flat procedural panels as accepted final art.','Full background needs at least2048x2048 native coverage per actual playable screen; undersize generated master stays reference-only, never silently upscale to claim native resolution.','All isolated generated art must pass actual alpha and phone-size placement/action review. Preserve every failed native output; no runtime binding until its independent evidence supports it.'],runtime_binding_changed=False,cinematic_delivery=False))
(out/'index.html').write_text('<!doctype html><html><meta charset="utf-8"><title>Painted geology rebuild</title><body><h1>Owner-directed ImageGen geology rebuild</h1><p>Flat geology vector floors are withdrawn. New painted fossil, layered rock, panning bowl, closed geode and crystal reward are being generated separately, then checked in native gameplay context. Painted work surfaces and room art remain part of the rebuild.</p><p><a href="GENERATION_QUEUE_V1.json">Exact prompts, gap inventory and pending states</a> · <a href="../../vector/job_geology_teacher_refinement_v1_20261001/OWNER_CORRECTION_V1.json">Owner correction</a></p><p>Original game artwork, characters and teacher improvements are preserved. No overall floor or owner acceptance is claimed.</p></body></html>',encoding='utf-8')
template=read(r/'design/audit_impacts/job-vector-mounted-review-20261001.json')
write(r/'design/audit_impacts/job-geology-painted-rebuild-20261001.json',dict(id='job-geology-painted-rebuild-20261001',scope='Owner rejects flat vector geology and commissions an ImageGen painted-art rebuild. Correct overly generous earlier geology source-floor claims without rewriting prior review receipts/maps. Inventory existing rejected raster and native procedural mounts; preserve teacher work, protected/current character art and runtime originals. Generate distinct painted geology props, then matching work/room surfaces and independent native context/action reviews.',baseline=base,rules=sorted(set(template['rules'])|{'DL-ASSET-02','DL-PERF-06','DL-MED-01'}),findings=['MA-VIS-006','MA-PLAY-004'],files=sorted([rel(correction),rel(v/'index.html')]+[rel(p) for p in out.rglob('*') if p.is_file()]),validation=[dict(command='Owner correction and relevant existing asset inventory/native review',result='PASS',evidence=rel(correction)+'; existing raster sheets rejected RGB checkerboard and undersize room source preserved.'),dict(command='Built-in ImageGen generation, actual alpha/native/context/complete-action review',result='PENDING',evidence=rel(out/'GENERATION_QUEUE_V1.json'))],acceptance_gaps='Geology vector source floors withdrawn. New generated sources, exact painted split/reveal/material states, mounted interactions, complete career/story/device/child/owner and full background native resolution remain open. No other source scores or teacher acceptance invented.'))
print(json.dumps(dict(status='PAINTED_GEOLOGY_REBUILD_PREPARED',jobs=[dict(id=j['id'],prompt_sha256=j['prompt_sha256']) for j in jobs],withdrawn_geo_vectors=len(geo))))
