from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess,sys,os
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/imagegen/candy_wrap_transition_keys_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-wrap-transition-keys-20261003.json';BASE='296b2adc8cf4e9b3adbc27a5b5d281471893f6bf'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.v666_next');t.write_bytes(raw);t.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip()==BASE
for name,source in [('midturn_attempt04','exec-edfd6766-c93f-458c-b740-11bdb3c2928c.png'),('release_attempt04','exec-7ce938ba-efe0-4007-b3b0-a38efcaf6020.png')]:
 M=P/name;src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017')/source;assert not (M/'native.png').exists();shutil.copyfile(src,M/'native.png');d=read(M/'GENERATION_REQUEST.json');raw=(M/'native.png').read_bytes();d.update(status='GENERATED_DIRECT_REVIEW_PENDING',native_path=(M/'native.png').relative_to(B).as_posix(),native_sha256=sha(raw),native_dimensions=list(Image.open(M/'native.png').size),native_bytes=len(raw),original_generated_path=str(src),saved_utc=now(),modifications='None:exact complete native bytes copied.');write(M/'GENERATION_RECEIPT.json',d)
op={
'midturn_attempt04': [('two_owned_hand_groups',4.5,'Two sleeve-owned mitten groups are readable, although the left thumb is mostly hidden behind its neck.'),('left_under_roll',4.4,'Left thumb-side lobe sits beneath the neck as in the finished-twist reference; attachment is occluded and no new middle roll is established.'),('right_over_roll',4.4,'Right broad quilted back lies across the upper neck.'),('opposing_midpoint_stage',3.8,'Pose closely repeats the finished endpoint; it does not add a clear halfway wrist orientation.'),('partially_wound_paper',3.7,'Both necks retain multiple tight diagonal encircling bands; the request for a single loose crossing fold was not achieved.'),('continuous_wrapper',4.5,'Covered oval, two necks and broad fans remain one wrapper.'),('covered_table_supported_oval',4.5,'Single opaque oval remains on the purple counter.'),('cuff_thumb_attachment',4.4,'Each hand remains cuff-owned; the left thumb web is hidden by the gold neck rather than explicitly resolved.'),('identity_costume',4.5,'Main face, rainbow lock and costume remain coherent.'),('painted_room',4.4,'Inherited ornamented painted context remains provisional.'),('whole_source_for_midturn',4.2,'Rejected for intended midpoint:near-finished winds and endpoint-like hand orientations leave the missing transition unfilled.')],
'release_attempt04': [('two_owned_hand_groups',4.6,'Exactly two complete coral hand groups, each continuous through its own teal/gold cuff to a sleeve.'),('thumb_conservation',4.6,'Each thumb has a continuous coral web; no coral fragment remains on either neck.'),('all_gold_clearance',4.5,'Purple tabletop visibly separates both gloves from the necks and fan upper edges.'),('early_release_stage',4.5,'Hands remain low and close above their former neck contacts, before the final wide rest.'),('quiet_supported_release_pose',4.5,'No wave, palm display or lifted candy; both intact gloves relax back.'),('thin_paper_neck_material',4.5,'Short flattened diagonal creases replace protruding rounded coils; necks read as gathered gold sheet, not rope.'),('continuous_fans',4.5,'Broad pleated fans remain continuously attached outside both necks.'),('covered_table_supported_oval',4.5,'Same single opaque oval remains registered and supported.'),('cuff_thumb_attachment',4.6,'Mitten/cuff/sleeve topology stays coherent in this still.'),('identity_and_inherited_room',4.4,'Main identity stays recognizable; room ornamentation4.4 is independently provisional.'),('whole_source_for_early_release',4.5,'Provisional early-release source floor achieved. This one still does not prove withdrawal motion, complete wrapping or current-game/training fit.')]
}
for name,items in op.items():
 M=P/name;r=read(M/'GENERATION_RECEIPT.json');write(M/'DIRECT_REVIEW.json',dict(checked_utc=now(),method='DIRECT_COMPLETE_NATIVE_CANVAS_REVIEW',native_path=r['native_path'],native_sha256=r['native_sha256'],dimensions=r['native_dimensions'],source_score=items[-1][1],disposition='PROVISIONAL_EARLY_RELEASE_SOURCE4_5_ONLY' if name.startswith('release') else 'REJECTED_FOR_INTENDED_TRANSITION_STAGE',opinions=[dict(id=k,score=s,evaluation=e) for k,s,e in items],direct_complete_native_review=True,mounted_score=None,sequence_score=None,action_score=None,runtime_integration=False,owner_acceptance=None,qualification='Individual still review only. Inherited room4.4, temporal motion, current-game/training, device/child/owner and complete action stay separately open. Source4.5 remains inclusive priority.'))
names=[f'{stage}_attempt{i:02d}' for stage in ['midturn','release'] for i in range(1,5)];reviews=[read(P/name/'DIRECT_REVIEW.json') for name in names];assert all(len(r['opinions'])==11 and r['direct_complete_native_review'] for r in reviews)
relations=[('fold_to_cover',4.4,'Existing partial-fold and cover stills show the same supported sweet disappearing under the gold sheet. They do not supply the intervening fold/press motion.'),('cover_to_neck_grip',4.4,'Covered oval and wide attached fans continue into two neck grips. Gathering trajectory and hand contact onset remain unproved.'),('neck_grip_to_midturn_candidate',3.7,'The fourth candidate jumps to near-finished neck winds and endpoint-like hands; a readable halfway opposed roll is still missing.'),('midturn_candidate_to_finished_twist',3.6,'Candidate and finished endpoint have too little meaningful wrist/paper progression to explain torque. Do not promote the rejected middle key.'),('finished_twist_to_early_release',4.4,'Two complete mittens disengage above the supported paper in the new source; flattened neck fold profiles differ slightly from the twist endpoint. Thumb ownership improves, but the temporal withdrawal is not established.'),('early_release_to_final_rest',4.4,'Low close hands widen to the earlier hands-clear rest while the opaque oval and wide fans broadly remain supported. Source still comparison does not prove the path or settle timing.')]
write(P/'NEIGHBOR_SOURCE_REVIEW.json',dict(checked_utc=now(),method='DIRECT_COMPLETE_NATIVE_STILL_NEIGHBOR_COMPARISON',opinions=[dict(id=k,source_relationship_score=s,evaluation=e,temporal_score=None,current_game_score=None) for k,s,e in relations],complete_wrapping_score=None,runtime_integration=False,owner_acceptance=None,qualification='Six static source relationships only;not six motion passes. No blending or interpolation.'))
plan=read(P/'PLAN.json');put(P/'PRE_GENERATION_PLAN.json',(P/'PLAN.json').read_bytes());plan.update(status='EIGHT_NATIVE_SOURCES_REVIEWED_EARLY_RELEASE4_5_MIDTURN_STILL_MISSING',finished_review_utc=now(),native_sources=8,individual_source_component_opinions=88,static_neighbor_opinions=6,best_midturn_source_score=4.2,early_release_source_score=4.5);write(P/'PLAN.json',plan)
summary=dict(status=plan['status'],reviewed_utc=now(),native_sources=8,individual_source_component_opinions=88,static_neighbor_opinions=6,total_individual_opinions=94,midturn_scores=[4.0,4.1,4.0,4.2],early_release_scores=[4.1,4.3,4.2,4.5],best_midturn_source_score=4.2,selected_midturn_key=None,selected_early_release_key=P.relative_to(B).as_posix()+'/release_attempt04/native.png',early_release_source_score=4.5,prior_twist_motion_score=2.2,prior_release_motion_score=1.7,current_game_wrap_score=2.8,complete_wrapping_score=None,new_motion_dispatched=False,runtime_integration=False,device_acceptance=None,child_acceptance=None,owner_acceptance=None,qualification='Seven rejected intended-stage drafts plus one provisional early-release source. Source4.5 remains inclusive priority;none establishes a temporal sequence or actual-game binding. All complete native pixels preserved,not cinematic delivery frames. Full broad job objective unchanged.')
write(P/'REVIEW_SUMMARY.json',summary)
write(P/'NEXT_ACTION_PLAN.json',dict(status='MISSING_OPPOSITE_MIDTURN_AND_ACTUAL_GAME_BINDING_REMAIN',full_objective='Complete widespread job/day/training artwork and logical physical workflow audit,refine every weak in-game object,then comprehensive owner review.',next_steps=['Use the new early-release still as a narrow source reference, preserving complete thumb/cuff ownership and the short flat gold-paper necks. Independently audit any withdrawal trajectory.','Replace the rejected midpoint with a genuinely different maintained-contact opposite wrist orientation and partially closed paper; no held finished endpoint or facial acting substitutes for torque.','Resolve actual story job/Opera training wrapper and actor binding:current turquoise magic widget/current whisk work poses do not match the proposed gold contact family. Do not bind Candy wrapping to birthdayGLAZE.','Before runtime changes, complete authored state/socket/timing/ownership/interruption contract and test actual input-contact-save owners. No progress on timer or reference movie end.','Continue all294 pending primary source opinions,other job outputs/individual objects/shared sources/procedural states and broad action workflows. Current source-only work does not close them.','After actual-source/context/action validation,collect ordinary route,device,child and owner evidence and comprehensive report approval.'],minimum_drafting_target=4.5,inclusive_priority_threshold=4.5,runtime_acceptance=None,owner_acceptance=None))
put(P/'CURRENT_BINDING_INVENTORY.json',Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/NEXT_CANDY_MATCHING_INVENTORY_V652.json').read_bytes())
# Preserve the current library literally before adding individually reviewed sources.
old=P/'previous_v54';assert not old.exists();old.mkdir()
for name in ['ALL_ITEMS.json','CURRENT_BOUNDARY_REFRESH.json','index.html','all_items.html']:put(old/name,(L/name).read_bytes())
reg=read(L/'ALL_ITEMS.json');prior_items=list(reg['items']);part=reg['item_shards'];assert len(prior_items)==2064
for name,r in zip(names,reviews):
 receipt=read(P/name/'GENERATION_RECEIPT.json');stage=name.split('_')[0];i=int(name[-2:]);sid='CANDY-'+('MIDTURN' if stage=='midturn' else 'EARLY-RELEASE')+'-'+f'{i:02d}';path=receipt['native_path'];score=r['source_score'];evaluation=r['opinions'][-1]['evaluation']
 item=dict(aliases=[sid],path=path,earlier_sha256=r['native_sha256'],current_checkout_sha256=r['native_sha256'],current_byte_status='EXACT_REVIEWED_GENERATION_BYTES',historical_source_score=None,current_source_score=score,current_mounted_score=None,current_complete_action_score=None,source_dimensions=r['dimensions'],preview_path=path,image_path=path,image_scope='Complete exact native unbound transition-pose candidate;not temporal/current-game/cinematic delivery acceptance',families=['Day Two','Candy Maker','Unbound gold-wrapper '+stage+' source'],original_reports=[P.relative_to(B).as_posix()+'/index.html'],source_qualification='Complete native directly reviewed;11 individual opinions. '+r['disposition']+'. No motion,current-game or owner acceptance.',evaluation=evaluation,refinement='Resolve actual matching, full physical trajectory and owner context separately; source4.5 stays priority.' if score==4.5 else 'Correct the named failed midpoint/material/contact stage while preserving identity,table support,one sheet,two continuous sleeve-owned mittens and broad fans.',priority=True,protected_original=False,owner_acceptance=None,native_reference_observations=[],id=sid,kind='source',individual_review_utc=r['checked_utc'],latest_refinement=dict(report=P.relative_to(B).as_posix()+'/index.html#'+name,note=f'{stage} attempt {i}: source {score}/5,11 individual opinions;motion/current-game lanes unassigned.'))
 reg['items'].append(item)
reg.update(display_revision='V55',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v55.py',scope='V55:2160 individually addressable entries,1308 primary sources/328 pose cells/151 runtime-use-action entries/373 source regions.1063 inclusive source-cell-region priorities,686 unique priority sources,294 pending primary opinions. Eight complete native transition drafts/88 component and6 static-neighbor opinions:midturn best4.2 still rejected,early-releaseA4 source4.5 provisional. Previous localtwist2.2/release1.7 and current actualWRAP2.8 unchanged. No newmotion,game/training binding or scoretransfer. All prior2064 root item dictionaries and literal88-item part preserved. Full physical actions,broad all-jobs/day/training,ordinary routes,device,child,owner and comprehensive report acceptance remain open.')
c=reg['counts'];c.update(unique_source_files=1308,registered_items=2160,inclusive_current_source_priorities=1063,unique_source_file_priorities=686,new_candy_transition_sources=8)
reg['current_byte_status_counts']['EXACT_REVIEWED_GENERATION_BYTES']+=8
reg['review_resources'].append(dict(path=P.relative_to(B).as_posix()+'/index.html',scope='Eight complete transition-pose natives/88 individual component and6 static-neighbor opinions. Early-releaseA4 source4.5 provisional;midturn best4.2 rejected. No motion/current-game acceptance.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304 and reg['items'][:2064]==prior_items and reg['item_shards']==part
put(L/'review_tools/refresh_current_job_review_v55.py',(L/'review_tools/refresh_current_job_review_v54.py').read_bytes())
for name in ['index.html','all_items.html']:
 p=L/name;s=p.read_text();marker='<details id="historical-';i=s.index(marker);head=s[:i];tail=s[i:];head+='<p><a href="../../assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/index.html">New: every midpoint and early-release source draft</a> — early release 4.5 provisional; midpoint remains below the floor. Actual game WRAP 2.8.</p>';put(p,(head+tail).encode())
css='body{margin:0;background:#edf4fa;color:#25304a;font:17px/1.55 system-ui}main{max-width:1120px;margin:auto;padding:24px}h1,h2,h3{line-height:1.25}a{color:#49398c}section,article{background:white;border-radius:16px;padding:20px;margin:24px 0}nav{display:flex;flex-wrap:wrap;gap:16px}img{display:block;width:100%;height:auto;aspect-ratio:1672/941;object-fit:contain}table{width:100%;border-collapse:collapse;table-layout:fixed}td,th{padding:10px;text-align:left;vertical-align:top;border-bottom:1px solid #dbe1ed;overflow-wrap:anywhere}th:first-child{width:25%}th:nth-child(2){width:10%}.qualification{background:#fff1d4;padding:16px;border-radius:12px}.current-images{display:grid;grid-template-columns:1fr 1fr;gap:24px}.current-images img{aspect-ratio:1/1;max-height:420px;background:#d5cfe6}code{overflow-wrap:anywhere}details{margin:18px 0}@media(max-width:640px){main{padding:12px}.current-images{grid-template-columns:1fr}td,th{padding:6px;font-size:14px}}'
out=['<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gold-wrapper transition keys — individual source review</title><style>'+css+'</style></head><body><main><h1>Gold-wrapper hands: midpoint and early release</h1><p class="qualification"><strong>Early release source: 4.5/5 provisional. Opposite wrist midpoint: best 4.2/5, still rejected.</strong> Every one of eight complete native drafts has eleven individual source opinions. Six neighboring still relationships are separately reviewed. These 94 opinions do not approve an animation or the current game.</p><p>The fourth release drawing keeps each thumb connected to its mitten and sleeve, leaves purple space between hands and paper, and restores short flat paper creases. The midpoint attempts still jump toward completed winds or fail to show a clear opposite wrist pair. All seven failed drafts remain visible below.</p><nav><a href="#release_attempt04">New clean early-release source</a><a href="#causal-coverage">Full intended sequence and missing state</a><a href="../../../audit/job_artwork_refinement_live/all_items.html">All 2,160 registered items</a><a href="../../local_motion/candy_twist_release_components_v1_20261003/index.html">Previous rejected motion components</a><a href="REVIEW_SUMMARY.json">Exact scores and qualifications</a></nav><section><h2>What still has to match in the game</h2><p>Current story-job and Opera-training WRAP remains 2.8/5. The actual widget is the turquoise shell-badged sweet with decorative spiral; the current valid actor atlas uses four work poses holding a whisk away from the sweet. Neither binds the gold paper or these contact hands. The portrait fallback is not evidence that the displayed atlas performs wrapping.</p><div class="current-images"><figure><img src="../../../assets/opera/worlds/widgets/widget_crank_candymaker_mover.png" alt="Current turquoise Candy widget with purple spiral"><figcaption>Actual wrapper widget: decorative already-wrapped state.</figcaption></figure><figure><img src="../../../assets/opera/worlds/actors/animation/roshan_candymaker_sheet_a.png" alt="Current Candy actor atlas"><figcaption>Actual actor atlas: work is row three, four whisk poses.</figcaption></figure></div><p><a href="CURRENT_BINDING_INVENTORY.json">Exact current source paths, hashes and selector facts</a> · <a href="../../../audit/job_candy_workflow_current_v1_20261003/index.html">626 actual game canvases and 48 current-use opinions</a>. All 783 recorded production literals remain unchanged.</p></section><section id="causal-coverage"><h2>Intended causal coverage — still comparisons only</h2><p>Fold → cover → gather → opposite midturn → finish twist → early release → quiet rest. The middle key below is rejected and shown to expose the gap. These sources are not a playable clip; the six table rows assess static relationships, with temporal scores unassigned.</p>']
inv=read(P/'REUSE_INVENTORY.json')['sources'];paths={x['role']:x['path'] for x in inv};stages=[('Partial fold',paths['fold'],'Existing source 4.5 provisional; temporal fold pending.'),('Cover and press',paths['cover'],'Existing source 4.5 provisional; continuous cover motion pending.'),('Gather and neck grip',paths['grip'],'Existing source 4.5 provisional; contact onset pending.'),('Missing opposite midpoint — rejected draft',P.relative_to(B).as_posix()+'/midturn_attempt04/native.png','4.2 rejected; not a selected sequence key.'),('Finished twist endpoint',paths['twisted'],'Existing source 4.5 provisional; wrist trajectory pending.'),('Early clean release',P.relative_to(B).as_posix()+'/release_attempt04/native.png','New source 4.5 provisional; withdrawal trajectory pending.'),('Hands-clear final rest',paths['rest'],'Existing source 4.5 provisional; settle trajectory pending.')]
def rel(path):return os.path.relpath(B/path,P).replace('\\','/')
for title,path,note in stages:out.append('<details class="coverage-stage"><summary>'+html.escape(title)+' — '+html.escape(note)+'</summary><img src="'+rel(path)+'" alt="Complete source: '+html.escape(title)+'"></details>')
out.append('<table><thead><tr><th>Static neighbor relationship</th><th>Score/5</th><th>Evaluation</th></tr></thead><tbody>')
for k,s,e in relations:out.append('<tr class="neighbor-opinion"><td>'+html.escape(k.replace('_',' '))+'</td><td>'+str(s)+'</td><td>'+html.escape(e)+'</td></tr>')
out.append('</tbody></table></section>')
# Lead with the useful new source;preserve every rejected original below it.
for name in ['release_attempt04']+[n for n in names if n!='release_attempt04']:
 r=read(P/name/'DIRECT_REVIEW.json');title=name.replace('_attempt',' attempt ');out.append('<article id="'+name+'"><h2>'+html.escape(title)+' — '+str(r['source_score'])+'/5</h2><p>'+html.escape(r['opinions'][-1]['evaluation'])+'</p><img loading="lazy" src="'+name+'/native.png" alt="Complete native '+title+'"><p><a href="'+name+'/PROMPT.txt">Exact ImageGen prompt</a> · <a href="'+name+'/GENERATION_RECEIPT.json">Native provenance and references</a> · <a href="'+name+'/DIRECT_REVIEW.json">Individual review</a></p><table><thead><tr><th>Individual component</th><th>Score/5</th><th>Evaluation</th></tr></thead><tbody>')
 for c in r['opinions']:out.append('<tr class="component-opinion"><td>'+html.escape(c['id'].replace('_',' '))+'</td><td>'+str(c['score'])+'</td><td>'+html.escape(c['evaluation'])+'</td></tr>')
 out.append('</tbody></table></article>')
out.append('<section><h2>Review and remaining work</h2><p>Built-in ImageGen edited complete flattened source scenes. Every native 1672×941 image is preserved without pixel repair, cropping, compositing, blending or interpolation. Exact prompts, source hashes and rejected attempts are retained. The new still reaches the source floor only; it remains an inclusive ≤4.5 priority.</p><p>Previous developed local motion remains rejected: twist 2.2/5 and release 1.7/5. No new motion was dispatched here. Full wrapper workflow, actual story job and Opera training, all other weak job objects and 294 pending primary source opinions, ordinary routes, device, child, owner and comprehensive report approval remain open.</p><p><a href="PLAN.json">Iteration record</a> · <a href="POSE_COVERAGE_CONTRACT.json">Draft state contract and unresolved geometry</a> · <a href="NEXT_ACTION_PLAN.json">Full remaining objective</a> · <a href="REUSE_INVENTORY.json">Reuse and named gaps</a></p></section></main></body></html>');put(P/'index.html',''.join(out).encode())
# Lossless durable archive of the preceding exact remote verification.
D=P/'previous_AD_remote_verified';D.mkdir();S=B/'tmp/component_remote_v651';result=read(S/'RESULT.json');assert result['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and result['revision']==BASE and result['files_including_manifest']==24850 and not result['failed_files']
for src,name in [(S/'RESULT.json','RESULT.json'),(B/'tmp/component_publish_v651/RECEIPT.json','PUBLICATION_RECEIPT.json'),(S/'FINAL_STATUS.json','FINAL_STATUS.json')]:put(D/name,src.read_bytes())
raw=(S/'VERIFICATION_JOURNAL.jsonl').read_bytes();lines=raw.splitlines(keepends=True);assert len(lines)==24850 and all(json.loads(x)['matches'] for x in lines);parts=[];group=[];size=0
def emit():
 payload=b''.join(group);p=D/f'JOURNAL_{len(parts)+1:03d}.jsonl';put(p,payload);assert len(payload)<=900000;parts.append(dict(path=p.relative_to(B).as_posix(),bytes=len(payload),sha256=sha(payload),rows=len(group)))
for line in lines:
 if group and size+len(line)>899000:emit();group=[];size=0
 group.append(line);size+=len(line)
if group:emit()
assert b''.join((B/x['path']).read_bytes() for x in parts)==raw
write(D/'JOURNAL_SHARDS.json',dict(status='ALL24850_PRIOR_AD_ANONYMOUS_ROWS_LOSSLESSLY_PRESERVED',original_journal_sha256=sha(raw),rows=24850,shards=parts,max_shard_bytes=900000,revision=BASE))
H=P/'previous_AD_hosted_snapshot';H.mkdir();cmd=['C:/Program Files/GitHub CLI/gh.exe','run','view','37124629454','--repo','Ebonyks/mermaid-roshan-reef','--json','databaseId,status,conclusion,headSha,url,jobs'];rr=subprocess.run(cmd,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW,timeout=60);put(H/'RUN.json',rr.stdout);put(H/'stderr.log',rr.stderr);assert rr.returncode==0;hosted=json.loads(rr.stdout);assert hosted['headSha']==BASE;write(H/'VERIFICATION.json',dict(status='ACTUAL_PRIOR_EXACT_HEAD_HOSTED_SNAPSHOT',checked_utc=now(),command=cmd,exit_code=0,revision=BASE,run_id=hosted['databaseId'],run_status=hosted['status'],run_conclusion=hosted['conclusion'],raw_sha256=sha(rr.stdout),qualification='Observed exact-head status only;pending stays pending,no predicted green/integration/creative acceptance.'))
boundary=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json';d=read(boundary);assert len(d['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in d['members']);write(P/'PRODUCTION_BOUNDARY_AFTER.json',dict(status='ALL783_LITERAL_PRODUCTION_MEMBERS_UNCHANGED',checked_utc=now(),baseline=BASE,members=783,boundary_sha256=sha(boundary.read_bytes()),runtime_changed=False,current_wrap_score=2.8))
note='Candy transition-source continuation (2026-10-03): [every eight complete native midpoint/early-release draft and94 individual opinions](TRANSITIONS). Seven intended-stage rejections preserved;early-releaseA4 source4.5 provisional with intact thumbs/cuffs,purple clearance and flat thin-paper necks. Midturn best4.2 remains rejected;no selected midpoint or newmotion. Prior localtwist2.2/release1.7,current actualWRAP2.8 and all783 production literals unchanged. Actual turquoise widget/current whisk work poses do not bind the proposed gold family. V55 known2160 entries/1308 primary sources/1063 inclusive priorities/686 unique source priorities/294 pending primary opinions;all prior2064 root dictionaries and literal88-item part preserved. Full causal wrapping,broad jobs/day/training/ordinary routes/device/child/owner/comprehensive approval remain open. MA-VIS-006 CONFIRMED_OPEN;MA-PLAY-004 IN_PROGRESS. No integration/release.'
for path,link in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/index.html'),('audit/animation/README.md','../../assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/index.html')]:
 p=B/path;s=p.read_text();n=note.replace('TRANSITIONS',link)
 if 'MASTER_AUDIT' in path:
  for marker in ['## 0. Planning entry','### Development task index']:assert marker in s;s=s.replace(marker,marker+'\n\n'+n,1)
 else:i=s.index('\n')+1;s=s[:i]+'\n'+n+'\n'+s[i:]
 put(p,s.encode())
p=B/'design/05_DOC_LEDGER.md';s=p.read_text();s+='\n| `assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`;eight complete transition sources/88 component and6 static-neighbor opinions. Early-releaseA4 source4.5 provisional,midturn best4.2 rejected. Prior motion/current game and broad acceptance remain separate. |\n| `assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/previous_v54/ALL_ITEMS.json` | ⚪ | `HISTORICAL_SUPPORTING`;literal V54 root before eight source additions;all2064 prior item dictionaries and88-item part preserved. |\n';put(p,s.encode())
p=B/'.gitattributes';put(p,p.read_bytes()+b'\nassets_src/imagegen/candy_wrap_transition_keys_v1_20261003/** -text\n')
p=B/'ASSET_LICENSES.md';raw=p.read_bytes();rows=[]
for name in names:
 r=read(P/name/'GENERATION_RECEIPT.json');path=r['native_path'];assert path.encode() not in raw;rows.append('| `'+path+'` | Built-in OpenAI ImageGen complete same-scene transition source;existing project Roshan/gold-wrapper references | OpenAI generated output; inherited project identity/source attribution preserved | `'+P.relative_to(B).as_posix()+'/'+name+'/GENERATION_RECEIPT.json` binds exact prompt/reference hashes | Exact full native1672×941 bytes preserved;no pixel repair. Individually reviewed source only;not motion/runtime/cinematic/device/child/owner approval. |')
put(p,raw+('\n'+'\n'.join(rows)+'\n').encode())
put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes())
# Update coverage before refresh and later gate artifacts.
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS.json','CURRENT_BOUNDARY_REFRESH.json','index.html','all_items.html','review_tools/refresh_current_job_review_v55.py']}|{'.gitattributes','ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md','design/05_DOC_LEDGER.md'});d['validation'] += [dict(command='Fourth full-native early-release source and11 individual opinions',result='PASS',evidence=P.relative_to(B).as_posix()+'/release_attempt04/DIRECT_REVIEW.json;source4.5 provisional only,room4.4,all action/game lanes unassigned.'),dict(command='Every four midpoint candidate and44 individual opinions',result='FAIL',evidence=P.relative_to(B).as_posix()+'/REVIEW_SUMMARY.json;best4.2 and no selected midpoint.'),dict(command='Six full-native static neighbor relationships',result='FAIL',evidence=P.relative_to(B).as_posix()+'/NEIGHBOR_SOURCE_REVIEW.json;missing midturn/consequence,full temporal trajectory unassigned.'),dict(command='Runtime import/parser/lint/full probes for source-only review',result='NOT_APPLICABLE',evidence='No new production.gd/asset/import changes;all783 literals unchanged. Existing official4.7.2 82/82 process0 separately scoped;actual hosted snapshot retained.'),dict(command='All24850 preceding AD anonymous remote rows preserved',result='PASS',evidence=D.relative_to(B).as_posix()+'/JOURNAL_SHARDS.json;fullRESULT/initialpublicationreceipt/finalstatus separately preserved.')];write(IP,d)
cmd=['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v55.py')];rr=subprocess.run(cmd,cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);put(P/'REFRESH.stdout.log',rr.stdout);put(P/'REFRESH.stderr.log',rr.stderr);assert rr.returncode==0,rr.stderr.decode(errors='replace')[-1000:];stamp=read(L/'CURRENT_BOUNDARY_REFRESH.json');assert stamp['registered_source_matches']==stamp['registry_items']==2160 and stamp['candy_capture_boundary_match']
write(P/'REGISTER_PRESERVATION_CHECK.json',dict(status='ALL2160_SOURCE_HASHES_MATCH_PRIOR2064_DICTIONARIES_AND88_ITEM_PART_PRESERVED',checked_utc=now(),registry_items=2160,previous_item_dictionaries=2064,previous_item_dictionaries_unchanged=read(L/'ALL_ITEMS.json')['items'][:2064]==prior_items,literal_item_shards=part,root_bytes=(L/'ALL_ITEMS.json').stat().st_size,root_limit_bytes=4194304,inclusive_source_priorities=1063,unique_priority_sources=686,pending_primary_opinions=294))
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});write(IP,d)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for p in L.rglob('*') if p.is_file()}))
print('V55_COMPLETE_SOURCE_REPORT_8_NATIVE_94_OPINIONS_PRIOR24850_JOURNAL_ROWS_PRESERVED',hosted['status'],hosted['conclusion'],(L/'ALL_ITEMS.json').stat().st_size,flush=True)
