from pathlib import Path
import datetime, hashlib, json, subprocess, shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
P=B/'assets_src/imagegen/candy_wrap_transition_keys_v1_20261003'
IP=B/'design/audit_impacts/job-candy-wrap-transition-keys-20261003.json'
BASE='296b2adc8cf4e9b3adbc27a5b5d281471893f6bf'
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
sha=lambda raw:hashlib.sha256(raw).hexdigest()
def put(p,raw):
 p.parent.mkdir(parents=True,exist_ok=True); n=p.with_name(p.name+'.v654_next'); n.write_bytes(raw); n.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip()==BASE
assert not P.exists(); P.mkdir(parents=True)
prior=json.loads((B/'design/audit_impacts/job-candy-twist-release-components-20261003.json').read_text())
authorities=['audit/MASTER_AUDIT_2026-08-09.md','design/06_COMPREHENSIVE_DESIGN_LANGUAGE.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','design/AUDIT_DEVELOPMENT_CONTRACT.md','design/animation/ROSHAN_MOVEMENT_LANGUAGE.md','design/animation/ANIMATION_PRODUCTION_PROTOCOL.md']
write(P/'AUTHORITY_START.json',dict(checked_utc=now(),baseline=BASE,previous_goal_turn='PROGRESS: both components rendered and every82 native frame plus24 components reviewed; missing opposed roll/paper closure and detached release thumb identified.',rules=prior['rules'],findings=prior['findings'],authority=[dict(path=p,sha256=sha((B/p).read_bytes())) for p in authorities],qualification='Original whole-job objective retained. No lifecycle or acceptance changes.'))
sources=[('fold','assets_src/imagegen/candy_wrap_scene_context_v1_20261003/attempt02/native.png'),('cover','assets_src/imagegen/candy_cover_pose_v1_20261003/attempt01/native.png'),('grip','assets_src/imagegen/candy_neck_grip_pose_v1_20261003/attempt04/native.png'),('twisted','assets_src/imagegen/candy_twist_release_pose_v1_20261003/twist_attempt05/native.png'),('rest','assets_src/imagegen/candy_twist_release_pose_v1_20261003/release_attempt05/native.png'),('current_atlas','assets/opera/worlds/actors/animation/roshan_candymaker_sheet_a.png'),('current_widget','assets/opera/worlds/widgets/widget_crank_candymaker_mover.png')]
rows=[]
for role,path in sources:
 p=B/path; raw=p.read_bytes(); im=Image.open(p); rows.append(dict(role=role,path=path,sha256=sha(raw),bytes=len(raw),dimensions=list(im.size),mode=im.mode,acceptance='SOURCE_STILL_PROVISIONAL_ONLY' if role not in ['current_atlas','current_widget'] else 'ACTUAL_BOUND_SOURCE_NO_ACTION_ACCEPTANCE'))
write(P/'REUSE_INVENTORY.json',dict(checked_utc=now(),baseline=BASE,sources=rows,prior_component_reviews=[dict(path=x,sha256=sha((B/x).read_bytes())) for x in ['assets_src/local_motion/candy_twist_release_components_v1_20261003/release_a1/attempt01/DIRECT_REVIEW.json','assets_src/local_motion/candy_twist_release_components_v1_20261003/twist_a1/attempt01/DIRECT_REVIEW.json']],reuse='Reuse clean full-scene grip, finished twist and rest sources as identity/layout/material inputs. Existing endpoints are held stills;41-frame twist has no readable wrist roll/paper winding and41-frame release loses thumb/cuff ownership. No reusable accepted middle-turn or early clean release state is established.',current_game='Valid1024x1024 Candy atlas selects work row2 at7fps; all four work poses hold a whisk away from the current256px turquoise shell-badged widget. Gold family remains proposed replacement; no runtime binding or score transfer.',named_gaps=['A readable half-turn maintaining both neck grips, opposite wrist orientations and continuous thin gold paper.','Early simultaneous release: the whole thumb leaves with its own mitten and cuff, while supported candy, twisted necks and fans remain fixed.'],no_redesign='Keep the existing character/costume/room/prop family; no new identities or protected originals.'))
common="Use case: precise-object-edit. Asset type: complete flattened painted storybook action-pose source, one single landscape canvas. Preserve the reference scene's entire framing, purple counter, mermaid character identity and proportions, face, brown hair with rainbow lock, teal-and-gold hat and vest, white puff sleeves and teal/gold cuffs. Preserve the same covered oval sweet in thin opaque gold paper, same wide continuous pleated fans, same deep plum contours and broad warm painted bands against the cool room. Exactly two coral quilted mittens, each attached through its own cuff to its own forearm. Every thumb belongs continuously to its mitten; no loose coral oval, extra hand, extra cuff or detached anatomy. No new objects, tools, lettering, motion lines, sparkles, grid, panels or inset. Keep the entire scene flattened, not cutouts or compositing."
prompts={
'midturn_attempt01':common+" Input image1 is the clean untwisted neck-grip edit target; image2 is the finished-twist material/pose reference. Change only the two wrist orientations and the short paper necks to ONE clear midpoint of the opposing twist. The left mitten rolls UNDER its neck: its attached thumb arcs down and toward the viewer, the broad finger mass tips slightly away. The right mitten rolls OVER its neck: its quilted back rotates toward the viewer and down across the top. These are opposite rolls about the candy's horizontal long axis, not pulls sideways. Both hands keep contact with their own short neck between oval and fan, never grip fan tips. The left and right gold neck pleats wind in opposite directions by about a quarter-turn, only partially tightened, visibly between the parallel entry pleats and the finished short wind. The oval stays on the tabletop, unchanged in centre, size and coverage; the broad fans remain attached beyond each neck. Keep cuffs structurally attached to the rotated hands and the face quietly attentive at the candy. No new finished rings before the midpoint, no rods, rope, bowed wire or detached thumb. Return one complete scene.",
'release_attempt01':common+" Input image1 is the finished-twist edit target; image2 is the relaxed hands-clear rest reference. Change only both complete mitten-and-cuff hand groups to ONE early clean-release state immediately after letting go. Each whole mitten, including its connected thumb, moves a small distance back and outward toward its own wrist. Both mittens now have a clearly visible narrow purple-table gap from their former gold neck contact; all coral glove material has left the gold paper. Hands stay low, close to their just-released necks, not up like a wave and not spread to the final wide rest yet. They relax around their intact thumbs; cuffs stay continuous and sleeve-owned. Keep the exact single wrapped gold oval, two short opposite paper winds and broad fans absolutely supported on the same tabletop. No paper pulled into a cuff, no extra coral fragment on the neck, no extra thumb left behind, no reaching or new twist. Face and room stay quiet and unchanged. Return one complete scene."
}
for name,prompt in prompts.items():
 M=P/name; M.mkdir(); put(M/'PROMPT.txt',(prompt+'\n').encode())
 refs=[rows[2],rows[3]] if name.startswith('midturn') else [rows[3],rows[4]]
 write(M/'GENERATION_REQUEST.json',dict(status='READY_NAMED_GAP_ONLY_NOT_GENERATED',attempt=1,method='BUILTIN_IMAGEGEN_COMPLETE_FLATTENED_SOURCE',references=refs,prompt_path=(M/'PROMPT.txt').relative_to(B).as_posix(),prompt_sha256=sha((M/'PROMPT.txt').read_bytes()),source_score=None,mounted_score=None,sequence_score=None,action_score=None,owner_acceptance=None,qualification='A source pose does not establish temporal motion or current-game fit. Not cinematic review delivery or runtime pixels.'))
write(P/'PLAN.json',dict(status='NAMED_TRANSITION_POSES_PREPARED_ONLY',baseline=BASE,created_utc=now(),stages=['fold existingC2','fully cover existingR1','gather/neck grip existingN4','opposite midturn missing','finished twist existingT5','early release missing','hands-clear rest existingR5'],threshold=4.5,inclusive_priority_threshold=4.5,current_wrap_score=2.8,previous_twist_motion_score=2.2,previous_release_motion_score=1.7,complete_wrapping_score=None,runtime_integration=False,owner_acceptance=None,required=['Direct full-native review of every candidate and individual components.','Neighbor comparisons distinguish authored pose coverage from unsupported temporal trajectories.','Actual story job and Opera training binding must use this exact wrapper/owned hand family at actual contact.','Ordinary route and input/contact/cancel/save/device/child/owner evidence.','Whole broad job audit, all294 pending primary source opinions and every weak job object remain required.']))
contract=dict(status='DRAFT_NOT_IMPLEMENTED_OR_ACCEPTED',baseline=BASE,lane='INTERACTIVE_GAMEPLAY_POSE_COVERAGE_PLANNING_ONLY',intent='Roshan folds one sheet over one sweet, gathers its two necks, rolls opposite wrists to close the paper, releases without moving the supported candy, then rests.',sequence=['partial_fold','cover_press','neck_grip','opposed_midturn','twist_complete','early_release','hands_clear_rest'],timings=None,geometry=None,geometry_gap='Measure hand sockets, cuff ownership, sweet centre and fan boundaries in each native source before declaring a runtime socket contract. No fabricated measurements.',binding_gap='Current turquoise widget/current whisk work row have not been replaced. No birthdayGLAZE binding.',gameplay_owner='Existing career-world input/target/save owner must validate live action/contact and cancellation; pose ending alone cannot award progress.',interruption_gap='No new runtime implementation; far/near input, zero input, repeated tap, pause, exit, re-entry and save remain unverified for replacement.',qualification='Seven coverage states are not an accepted motion clip. No interpolation/blending/warping to repair missing contact.')
write(P/'POSE_COVERAGE_CONTRACT.json',contract)
boundary=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json'; d=json.loads(boundary.read_text()); assert len(d['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in d['members'])
write(P/'PRODUCTION_BOUNDARY_BEFORE.json',dict(status='ALL783_LITERAL_MEMBERS_UNCHANGED',checked_utc=now(),baseline=BASE,boundary_path=boundary.relative_to(B).as_posix(),boundary_sha256=sha(boundary.read_bytes()),members=783,runtime_changed=False))
put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes())
write(IP,dict(id='job-candy-wrap-transition-keys-20261003',scope='Reversible same-scene full-frame ImageGen source corrections for missing opposite wrist midpoint and whole-thumb/cuff clean-release pose; individual source and neighbor review, illustrated library and exact review publication. Preserve rejected local references and actual game mismatched wrapper/whisk evidence. No runtime integration or acceptance.',baseline=BASE,rules=prior['rules'],findings=prior['findings'],files=sorted(p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()),validation=[dict(command='Authority and reuse/current-binding inventory',result='PASS',evidence=(P/'REUSE_INVENTORY.json').relative_to(B).as_posix()),dict(command='Direct candidate and neighbor review / library / source-only gates / publication',result='PENDING',evidence='No generation or predicted outcome yet.')],acceptance_gaps='Full physical sequence and actual in-game story/training wrapper binding; currentWRAP2.8;294 pending primary opinions and all other weak individual jobs/states/outputs/actions; device/child/owner/comprehensive report approval and strict-zero2D remain open.'))
print('PREPARED_NAMED_GAPS_AND_NEW_IMPACT',P.relative_to(B).as_posix())
