from pathlib import Path
import json,hashlib,shutil,datetime
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/imagegen/candy_wrap_transition_keys_v1_20261003';IP=B/'design/audit_impacts/job-candy-wrap-transition-keys-20261003.json'
sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.v660_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
for name,source in [('midturn_attempt02','exec-6b88e8a9-b778-40d3-9ae6-254ca3e748c9.png'),('release_attempt02','exec-242418f0-aef1-4e0b-b1d2-afaf8d610de2.png')]:
 M=P/name;src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017')/source;assert not (M/'native.png').exists();shutil.copyfile(src,M/'native.png');d=json.loads((M/'GENERATION_REQUEST.json').read_text());raw=(M/'native.png').read_bytes();d.update(status='GENERATED_DIRECT_REVIEW_PENDING',native_path=(M/'native.png').relative_to(B).as_posix(),native_sha256=sha(raw),native_dimensions=list(Image.open(M/'native.png').size),native_bytes=len(raw),original_generated_path=str(src),saved_utc=now(),modifications='None:exact complete native bytes copied.');write(M/'GENERATION_RECEIPT.json',d)
opinions={
'midturn_attempt02': [('exactly_two_owned_mittens',4.6,'Two complete mittens remain sleeve-owned with no detached coral parts.'),('left_under_roll',4.2,'Lower left finger mass curls beneath the neck and the attached thumb remains above; clearer intermediate silhouette, but axial wrist roll is modest.'),('right_over_roll',4.0,'Right broad glove largely preserves entry orientation; opposite roll pair is still weak.'),('maintained_neck_grips',4.5,'Both mittens keep their own necks rather than fan tips.'),('partially_wound_paper',3.7,'Gold necks remain mostly parallel gathered bands with no readable partial crossing; stage consequence is missing.'),('one_continuous_wrapper',4.5,'One covered oval and both attached broad fans remain clear.'),('supported_covered_oval',4.5,'Opaque oval remains on the purple table.'),('cuff_hand_attachment',4.5,'Cuffs remain continuous; left cuff broadens and turns compared with the entry.'),('identity_costume',4.5,'Main face/hair/teal/coral costume family stays coherent.'),('quiet_room_style',4.4,'Existing finely decorated painted room remains provisional.'),('whole_source_for_midturn',4.1,'Rejected:better left hand silhouette, but opposite right roll and partially winding paper still insufficient.')],
'release_attempt02': [('exactly_two_owned_mittens',4.6,'Two complete low hands, both thumb webs attached to their own mitten bodies.'),('clean_neck_disengagement',4.6,'No coral material remains on either gold neck.'),('clearance_from_all_paper',4.5,'Purple tabletop separates both mittens from necks and fan upper edges.'),('early_release_stage',4.5,'Hands are back above the neck region, close to the former contact rather than at final wide rest.'),('quiet_two_hand_rest',4.5,'Both whole hands remain low and relaxed, with intact cuffs.'),('short_opposed_neck_winds',3.8,'Thin-paper winds grow into rounded bulky rope-like coils, especially the right end; this changes the wrapper material.'),('fan_conservation',4.4,'Broad gold fans remain continuous and broadly registered, with small upper-profile changes.'),('supported_covered_oval',4.5,'One opaque oval remains supported and registered.'),('cuff_hand_attachment',4.6,'Both cuff/mitten connections stay intact.'),('identity_costume_room',4.4,'Main identity is coherent, inherited room stays separate.'),('whole_source_for_early_release',4.3,'Rejected for bulky coil material despite a substantially cleaner low-handed release pose.')]
}
for name,items in opinions.items():
 M=P/name;r=json.loads((M/'GENERATION_RECEIPT.json').read_text());write(M/'DIRECT_REVIEW.json',dict(checked_utc=now(),method='DIRECT_COMPLETE_NATIVE_CANVAS_REVIEW',native_path=r['native_path'],native_sha256=r['native_sha256'],dimensions=r['native_dimensions'],source_score=items[-1][1],disposition='REJECTED_FOR_INTENDED_TRANSITION_STAGE',opinions=[dict(id=k,score=s,evaluation=e) for k,s,e in items],direct_complete_native_review=True,mounted_score=None,sequence_score=None,action_score=None,runtime_integration=False,owner_acceptance=None,qualification='Still-source review only;no temporal/current-game acceptance.'))
common=(P/'midturn_attempt01/PROMPT.txt').read_text().split(' Input image1')[0]
requests={
'midturn_attempt03':common+' Image1 is the intermediate-grip edit target. Keep its LEFT glove, thumb, cuff, face, room, purple table, sweet oval and two fans unchanged. Change only the RIGHT wrist/mitten orientation and the short gold neck fold direction. Roll the RIGHT wrist OVER the right neck, so the quilted broad finger-back lies noticeably more horizontally across the TOP of that neck and its attached thumb is behind the grip toward the hair. It must oppose the left glove that curls UNDER the left neck. Keep each entire mitten owned by its own cuff, no detached thumbs. On each short neck show one broad shallow diagonal S-fold, in opposite directions, beginning to wind thin paper. These are partially turned flattened pleats, not finished circular rings or thick rope coils. Both hands retain their neck grips and all fans remain outside the hands. Return one complete flattened same-scene midpoint source.',
'release_attempt03':common+' Image1 is the clean low-handed early-release edit target. Preserve both complete mittens, their attached thumbs, cuffs, sleeves, their exact low positions and purple gaps, plus face, room, gold oval and broad fan shapes. Change ONLY the two bulbous neck coils. Image2 supplies the thin flat gold-paper material and short finished winds. Redraw each neck as two or three short FLAT diagonal pressed paper folds flush with the gathered sheet; same warm gold, no tubular braid, raised rope coil, knot, extra ribbon or separate material. Keep the opposite winding directions and both fans continuously joined. This is one already closed sweet immediately after both hands release it; no further twist or movement. Return one complete flattened scene.'
}
for name,prompt in requests.items():
 M=P/name;assert not M.exists();M.mkdir();put(M/'PROMPT.txt',(prompt+'\n').encode());prev=P/name.replace('03','02');r=json.loads((prev/'GENERATION_RECEIPT.json').read_text());refs=[dict(role='edit_target',path=r['native_path'],sha256=r['native_sha256'],dimensions=r['native_dimensions'])]
 if name.startswith('release'):
  path='assets_src/imagegen/candy_twist_release_pose_v1_20261003/release_attempt05/native.png';refs.append(dict(role='thin_paper_material',path=path,sha256=sha((B/path).read_bytes()),dimensions=list(Image.open(B/path).size)))
 write(M/'GENERATION_REQUEST.json',dict(status='READY_NAMED_CORRECTION_NOT_GENERATED',attempt=3,method='BUILTIN_IMAGEGEN_COMPLETE_FLATTENED_SOURCE',references=refs,prompt_path=(M/'PROMPT.txt').relative_to(B).as_posix(),prompt_sha256=sha((M/'PROMPT.txt').read_bytes()),previous_rejected_review=(prev/'DIRECT_REVIEW.json').relative_to(B).as_posix(),source_score=None,mounted_score=None,sequence_score=None,action_score=None,owner_acceptance=None,qualification='Full native source still;not temporal motion/runtime/cinematic delivery.'))
put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes());d=json.loads(IP.read_text());d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});d['validation'].append(dict(command='Second full-native midpoint and release sources/22 individual opinions',result='FAIL',evidence=P.relative_to(B).as_posix()+'/midturn_attempt02/DIRECT_REVIEW.json and release_attempt02/DIRECT_REVIEW.json;4.1/4.3 rejected for missing opposite pair/paper wind and bulky rope-like necks.'));write(IP,d)
print('FOUR_COMPLETE_NATIVES_44_OPINIONS_PRESERVED_THIRD_TARGETED_CORRECTIONS_READY')
