from pathlib import Path
import json,hashlib,shutil,datetime
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/imagegen/candy_wrap_transition_keys_v1_20261003';IP=B/'design/audit_impacts/job-candy-wrap-transition-keys-20261003.json'
sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.v657_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
M=P/'release_attempt01';src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-51c6c47a-6a7e-43c7-88e2-fe1a6443022e.png');assert not (M/'native.png').exists();shutil.copyfile(src,M/'native.png');d=json.loads((M/'GENERATION_REQUEST.json').read_text());raw=(M/'native.png').read_bytes();d.update(status='GENERATED_DIRECT_REVIEW_PENDING',native_path=(M/'native.png').relative_to(B).as_posix(),native_sha256=sha(raw),native_dimensions=list(Image.open(M/'native.png').size),native_bytes=len(raw),original_generated_path=str(src),saved_utc=now(),modifications='None:exact complete native bytes copied.');write(M/'GENERATION_RECEIPT.json',d)
opinions={
'midturn_attempt01':[( 'exactly_two_owned_mittens',4.6,'Two principal coral mitten groups remain sleeve-owned; no loose coral oval in this still.'),('left_under_roll',3.5,'Left broad glove remains near the entry silhouette and thumb-side orientation; requested under-roll midpoint is weak.'),('right_over_roll',4.2,'Right quilted back slopes across the upper neck; clearer over-contact than the entry, but not a strong opposite pair.'),('maintained_neck_grips',4.5,'Both groups overlap their own necks between the covered oval and wide fans.'),('partially_wound_paper',3.5,'Several tight oblique gold bands already encircle both necks, reading as near-finished winds rather than a quarter-turn midpoint.'),('one_continuous_wrapper',4.5,'Gold oval, necks and pleated fans remain one readable wrapper.'),('supported_covered_oval',4.5,'No red sweet revealed; oval remains on the same purple table.'),('cuff_hand_attachment',4.5,'Each teal/gold cuff feeds into its own coral hand without the local release fragment defect.'),('identity_costume',4.5,'Teal hat/vest, coral bows, white sleeves and rainbow forelock remain readable.'),('quiet_room_style',4.4,'Inherited painted room remains coherent but finely ornamented; no new room acceptance.'),('whole_source_for_midturn',4.0,'Attractive complete source rejected for intended stage: not enough left-under roll and paper winds appear too complete.')],
'release_attempt01': [('exactly_two_owned_mittens',4.6,'Both complete thumbs remain connected to their own mitten/cuff groups; no coral piece stays on a neck.'),('clean_neck_disengagement',4.5,'Both hands leave their old neck contacts.'),('clearance_from_all_paper',3.8,'Hands move outward over the fan upper edges; both glove/fan contours have near-touching tangencies rather than clear purple separation.'),('early_release_stage',3.5,'Hands move far outward toward final rest instead of a small first disengagement close to the necks.'),('quiet_two_hand_rest',4.3,'Hands stay low and coherent; stage differs from intended early release.'),('short_opposed_neck_winds',4.5,'Supported short diagonal winds remain visible on both gold necks.'),('fan_conservation',4.1,'Right fan upper profile/extent changes and both fans move closer to glove silhouettes; continuity is not exact.'),('supported_covered_oval',4.5,'Single opaque oval remains supported and broadly registered.'),('cuff_hand_attachment',4.6,'Teal/gold cuff and coral mitten connections are intact in this still.'),('identity_costume_room',4.4,'Main identity remains readable; inherited room and small rendering drift stay separately provisional.'),('whole_source_for_early_release',4.1,'Rejected for premature wide hand placement and glove/fan tangencies despite improved thumb ownership.')]
}
for name,items in opinions.items():
 M=P/name;receipt=json.loads((M/'GENERATION_RECEIPT.json').read_text());write(M/'DIRECT_REVIEW.json',dict(checked_utc=now(),method='DIRECT_COMPLETE_NATIVE_CANVAS_REVIEW',native_path=receipt['native_path'],native_sha256=receipt['native_sha256'],dimensions=receipt['native_dimensions'],source_score=items[-1][1],disposition='REJECTED_FOR_INTENDED_TRANSITION_STAGE',opinions=[dict(id=k,score=s,evaluation=e) for k,s,e in items],direct_complete_native_review=True,mounted_score=None,sequence_score=None,action_score=None,runtime_integration=False,owner_acceptance=None,qualification='Individual still review only;no temporal or current-game acceptance.'))
common=(P/'midturn_attempt01/PROMPT.txt').read_text().split(' Input image1')[0]
requests={
'midturn_attempt02':common+' Input image1 is the untwisted grip edit target and the only visual input. Show ONE intermediate opposite wrist roll, visibly different from that upright two-mitten entry. Keep both cuff attachments in their current positions, but rotate the LEFT hand about the horizontal gold neck: its quilted finger-back tips AWAY, its one continuously attached thumb swings UNDER the neck and toward the viewer. Show the thumb joined by a broad coral web to the glove side, not a separate red oval. At the same time the RIGHT glove rolls the opposite way, its broad quilted back turning OVER the right neck toward the viewer. Both mittens remain gripping their own short necks. Gold necks have only ONE shallow diagonal crossing fold each, in opposite directions, still loose and partly gathered; do not draw tight finished rings, helical rope coils or already completed twists. Keep the single covered oval and two broad attached fans supported in their exact existing locations, and preserve the full scene and face. This is the half-turn between gathering and finishing, not another held entry or completed twist. Return one complete flattened scene.',
'release_attempt02':common+' Input image1 is the finished-twist edit target and the only visual input. Show ONE very early clean release. Both whole coral mittens let go and move BACK toward Roshan into the clear purple tabletop immediately ABOVE their respective necks, with the thumbs still continuously joined to their mittens and cuffs. Keep each hand close above its former neck, not spread outward over the fan. Each relaxed mitten has a clearly visible purple gap of about one quarter mitten-height from EVERY gold edge, including the fans. Do not raise a palm like a wave. Keep the exact gold oval, neck winds, wide fans, table support, face and room fixed. No detached thumb on the neck, no gold touching a cuff, no change of paper shape, no extra hands. The final wide rest has not yet happened; this is the first small withdrawal with the entire thumb moving with its glove. Return one complete flattened scene.'
}
inv=json.loads((P/'REUSE_INVENTORY.json').read_text())['sources']
for name,prompt in requests.items():
 M=P/name;assert not M.exists();M.mkdir();put(M/'PROMPT.txt',(prompt+'\n').encode());ref=next(x for x in inv if x['role']==('grip' if name.startswith('midturn') else 'twisted'))
 write(M/'GENERATION_REQUEST.json',dict(status='READY_NAMED_CORRECTION_NOT_GENERATED',attempt=2,method='BUILTIN_IMAGEGEN_COMPLETE_FLATTENED_SOURCE',references=[ref],prompt_path=(M/'PROMPT.txt').relative_to(B).as_posix(),prompt_sha256=sha((M/'PROMPT.txt').read_bytes()),previous_rejected_review=(P/(name.replace('02','01'))/'DIRECT_REVIEW.json').relative_to(B).as_posix(),source_score=None,mounted_score=None,sequence_score=None,action_score=None,owner_acceptance=None,qualification='Complete same-scene source still only,not temporal motion/runtime/cinematic delivery.'))
put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes());d=json.loads(IP.read_text());d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});d['validation'].append(dict(command='First complete native midpoint and early-release sources/22 individual opinions',result='FAIL',evidence=P.relative_to(B).as_posix()+'/midturn_attempt01/DIRECT_REVIEW.json and release_attempt01/DIRECT_REVIEW.json;4.0/4.1 rejected for intended stages,not floor acceptance.'));write(IP,d)
print('TWO_NATIVE_REJECTED_DRAFTS_ARCHIVED_22_OPINIONS_TWO_NARROW_RETRIES_READY')
