from pathlib import Path
import datetime,hashlib,json,re,collections
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/imagegen/candy_wrap_transition_keys_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-wrap-transition-keys-20261003.json';G=P/'gates_v1';R=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp')
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.v672_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
proof=read(R/'TRANSITION_BROWSER_OBSERVATIONS_V670.json');stages=read(R/'TRANSITION_STAGE_OBSERVATIONS_V671.json');assert proof['report']['articles']==8 and proof['report']['componentRows']==88 and proof['report']['neighborRows']==6 and proof['report']['stages']==7 and not proof['report']['overflow']
assert 'V55: 2,160' in proof['library']['summary'] and proof['library']['historyLinks']==83 and not proof['library']['historyOpen'] and not proof['library']['overflow'];assert proof['item']['matching']==1 and 'Mounted: unassigned' in proof['item']['item'] and 'Complete action: unassigned' in proof['item']['item'] and '4.5/5' in proof['item']['item']
image=proof['release']['image'];assert image['loaded'] and [image['width'],image['height']]==[1672,941] and image['top']>=0 and image['bottom']<=image['viewport']
assert len(stages['stages'])==7 and stages['allOpenedThenClosed'] and all(x['loaded'] and [x['width'],x['height']]==[1672,941] for x in stages['stages'])
for name in ['TRANSITION_BROWSER_OBSERVATIONS_V670.json','TRANSITION_STAGE_OBSERVATIONS_V671.json']:put(P/name,(R/name).read_bytes())
shots=[]
for name in ['TRANSITION_REPORT_V669.jpg','EARLY_RELEASE_SOURCE_V669.jpg','CURRENT_LIBRARY_V670.jpg','INDIVIDUAL_RELEASE_ENTRY_V670.jpg']:
 dst=P/name;assert not dst.exists();put(dst,(R/name).read_bytes());im=Image.open(dst);assert im.format=='JPEG';shots.append(dict(path=dst.relative_to(B).as_posix(),sha256=sha(dst.read_bytes()),dimensions=list(im.size),role='Actual local-browser QA screenshot only'))
write(P/'BROWSER_VERIFY_V672.json',dict(status='ACTUAL_REPORT_CURRENT_V55_LIBRARY_8_ARTICLES_94_OPINION_ROWS_7_DISCLOSURES_VERIFIED',checked_utc=now(),observations=[dict(path=(P/name).relative_to(B).as_posix(),sha256=sha((P/name).read_bytes())) for name in ['TRANSITION_BROWSER_OBSERVATIONS_V670.json','TRANSITION_STAGE_OBSERVATIONS_V671.json']],screenshots=shots,source_native_direct_reviews=8,source_components=88,static_neighbors=6,mounted_score=None,complete_action_score=None,qualification='Actual desktop report/register observation and native source review;no game,motion,device,child,owner or all-job acceptance. Full rendered early-release image is visible in saved proof.'))
for name in ['index.html','all_items.html']:
 previous=(P/'previous_v54'/name).read_text();current=(L/name).read_text();links=lambda s:collections.Counter(re.findall(r'<a\b[^>]*href="([^"]+)"',s));a=links(previous);b=links(current);assert all(b[k]>=v for k,v in a.items()),name
old=read(P/'previous_v54/ALL_ITEMS.json');new=read(L/'ALL_ITEMS.json');assert len(old['items'])==2064 and new['items'][:2064]==old['items'] and new['item_shards']==old['item_shards'];assert (L/'ATLAS_STATE_ITEMS_V51.json').stat().st_size==236473 and sha((L/'ATLAS_STATE_ITEMS_V51.json').read_bytes())=='7d39a5c8d7d6348688e7cafa3684e208b6cab429c13b5a1ba793db5c676614b7'
write(P/'LIBRARY_PRESERVATION.json',dict(status='ALL_PRIOR2064_ROOT_DICTIONARIES_LITERAL88_ITEM_PART_LINK_MULTIPLICITIES_PRESERVED',checked_utc=now(),new_source_items=8,total_items=2160,root_sha256=sha((L/'ALL_ITEMS.json').read_bytes()),root_bytes=(L/'ALL_ITEMS.json').stat().st_size,root_limit=4194304,qualification='Only8 reviewed sources/current metadata and report links added;no earlier opinion or score changed. Current mounted/action claims remain separate.'))
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();rows=[]
for x in shots:
 assert x['path'].encode() not in raw;rows.append('| `'+x['path']+'` | Actual local-browser screenshot of reviewed transition report/register | Original project QA layout and inherited displayed-art attribution | `'+P.relative_to(B).as_posix()+'/BROWSER_VERIFY_V672.json` binds exact observed pixels | QA proof only;no game,motion,device,child or owner acceptance. |')
put(licenses,raw+('\n'+'\n'.join(rows)+'\n').encode())
authority=['audit/MASTER_AUDIT_2026-08-09.md','design/06_COMPREHENSIVE_DESIGN_LANGUAGE.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','design/AUDIT_DEVELOPMENT_CONTRACT.md','design/animation/ROSHAN_MOVEMENT_LANGUAGE.md','design/animation/ANIMATION_PRODUCTION_PROTOCOL.md'];language=(B/authority[1]).read_text();rules=read(IP)['rules'];assert all(k in language for k in rules);findings=(B/authority[2]).read_text().splitlines();headings=[s for s in findings if re.match(r'^#{1,6} .*MA-(VIS-006|PLAY-004)',s)];assert len(headings)==2
write(P/'AUTHORITY_RECHECK_V672.json',dict(status='APPLICABLE_AUTHORITY_RULES_FINDINGS_RECHECKED_DURING_REVIEW',checked_utc=now(),members=[dict(path=p,sha256=sha((B/p).read_bytes()),bytes=(B/p).stat().st_size) for p in authority],rules=rules,findings=headings,excerpts=[dict(rule=k,text=language[max(0,language.find(k)-20):language.find(k)+800]) for k in ['DL-VIS-07','DL-INT-03','DL-MOT-11','DL-MOT-13','DL-QA-03','DL-QA-07']],qualification='Source-only review and still/temporal/current-game separation. No finding lifecycle or authority/threshold/release changes.'))
put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes())
oldrunner=(B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003/review_tools/run_endpoint_gate_v633.py').read_text();newrunner=oldrunner.replace('assets_src/imagegen/candy_twist_release_pose_v1_20261003','assets_src/imagegen/candy_wrap_transition_keys_v1_20261003').replace('CANDIDATE_ENDPOINT_SOURCE_V633.json','CANDIDATE_TRANSITION_SOURCE_V672.json');put(P/'review_tools/run_transition_gate_v672.py',newrunner.encode())
assert not G.exists();G.mkdir();d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}|{(G/(label+suffix)).relative_to(B).as_posix() for label in ['authority','development','document_tests','game2d','register_parts'] for suffix in ['.stdout.log','.stderr.log','.receipt.json']}|{(G/'CANDIDATE_TRANSITION_SOURCE_V672.json').relative_to(B).as_posix()});d['validation'].append(dict(command='Actual browser report/current-library/individual-source verification',result='PASS',evidence=P.relative_to(B).as_posix()+'/BROWSER_VERIFY_V672.json;8 articles/88 components/6 neighbors/7 disclosures,all native source dimensions,unassigned action lanes,no overflow.'));d['validation'].append(dict(command='Source-only structural/document/2D no-regression/register gates',result='PENDING',evidence=G.relative_to(B).as_posix()+';exact-source runner prepared,no predicted result.'));write(IP,d)
members=[]
for path in d['files']:
 p=B/path
 if not p.is_file() or path.startswith(G.relative_to(B).as_posix()+'/'):continue
 members.append(dict(path=path,bytes=p.stat().st_size,sha256=sha(p.read_bytes())))
write(G/'CANDIDATE_TRANSITION_SOURCE_V672.json',dict(status='EXACT8_NATIVE_SOURCE94_OPINION_CURRENT_V55_BYTES_FROZEN_BEFORE_GATES',baseline=d['baseline'],frozen_utc=now(),members=members,member_count=len(members),qualification='Literal source/report/browser/library boundary before checks;gate/impact/publication metadata separately sealed. No creative/action/owner/integration/release acceptance.'))
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}));print('TRANSITION_SOURCE_FREEZE',len(members),'4 browser proofs,all prior opinions/links preserved',flush=True)
