from pathlib import Path
import json,hashlib,shutil,datetime
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/imagegen/candy_wrap_transition_keys_v1_20261003';IP=B/'design/audit_impacts/job-candy-wrap-transition-keys-20261003.json'
sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.v663_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
cases=[('midturn_attempt03','exec-167d7e7a-f712-4b30-b1e2-f3bed0223b39.png',4.0),('release_attempt03','exec-75e945fa-31fa-4947-9061-79f582ef150f.png',4.2)]
for name,source,score in cases:
 M=P/name;src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017')/source;assert not (M/'native.png').exists();shutil.copyfile(src,M/'native.png');d=json.loads((M/'GENERATION_REQUEST.json').read_text());raw=(M/'native.png').read_bytes();d.update(status='GENERATED_DIRECT_REVIEW_PENDING',native_path=(M/'native.png').relative_to(B).as_posix(),native_sha256=sha(raw),native_dimensions=list(Image.open(M/'native.png').size),native_bytes=len(raw),original_generated_path=str(src),saved_utc=now(),modifications='None:exact native full-frame bytes copied.');write(M/'GENERATION_RECEIPT.json',d)
op={
'midturn_attempt03':[('two_owned_hand_groups',4.6,'Two complete mitten/cuff groups;no loose coral oval.'),('left_under_roll',3.6,'Left broad quilted back now crosses above the neck rather than preserving the previous under silhouette.'),('right_over_roll',4.1,'Right contact remains readable but near the previous orientation.'),('opposing_pair',3.5,'Both broad backs dominate the upper necks; opposite underside/over grip pair is not clear.'),('partially_wound_necks',3.9,'Left neck gains a hanging thick folded loop, while right changes to a diagonal crossing; material/state asymmetry is too large.'),('continuous_wrapper',4.4,'Wide gold fans remain joined to opaque oval,but left hanging material grows.'),('covered_table_supported_oval',4.5,'Single oval stays supported.'),('cuff_and_thumb_ownership',4.5,'Thumbs stay part of their own glove silhouettes.'),('identity',4.5,'Recognizable costume and face retained.'),('painted_room',4.4,'Inherited painted context stays separate.'),('whole_source_for_midturn',4.0,'Rejected:unrequested left-hand change weakens opposite roll and adds hanging gold material.')],
'release_attempt03':[('two_owned_hand_groups',4.6,'Two intact mitten/cuff groups.'),('all_thumbs_leave_with_hands',4.6,'No loose coral material remains on necks.'),('all_gold_clearance',4.4,'Hands mostly clear paper,with close right-fan/mitten contour.'),('early_release_stage',3.5,'Both hands change to wide final rest,although the edit explicitly required preserving early close positions.'),('neck_material',4.4,'Reduced neck coils read flatter thanA2,but several curvedbands remain.'),('fan_conservation',4.3,'Fan silhouettes remain broadly samefamily,not literal fixedshapes.'),('covered_table_supported_oval',4.5,'Single oval stays ontable.'),('cuff_and_thumb_ownership',4.6,'Cuffs and glove connections intact.'),('identity',4.5,'Main identity stays recognizable.'),('painted_room',4.4,'Context provisional.'),('whole_source_for_early_release',4.2,'Rejected as early release:improvedneckmaterial,but reference contamination shifts both hands to finalwidestill.')]
}
for name,_,score in cases:
 M=P/name;r=json.loads((M/'GENERATION_RECEIPT.json').read_text());write(M/'DIRECT_REVIEW.json',dict(checked_utc=now(),method='DIRECT_COMPLETE_NATIVE_CANVAS_REVIEW',native_path=r['native_path'],native_sha256=r['native_sha256'],dimensions=r['native_dimensions'],source_score=score,disposition='REJECTED_FOR_INTENDED_TRANSITION_STAGE',opinions=[dict(id=k,score=s,evaluation=e) for k,s,e in op[name]],direct_complete_native_review=True,mounted_score=None,sequence_score=None,action_score=None,runtime_integration=False,owner_acceptance=None,qualification='Still review only,no temporal/current-game acceptance.'))
common=(P/'midturn_attempt01/PROMPT.txt').read_text().split(' Input image1')[0]
req={
'midturn_attempt04':(common+' Input image1 is the finished opposing grip edit target. Make a single clearly EARLIER halfway-through-twist pose by loosening each gold neck to just one broad shallow diagonal paper fold in the opposite directions,not multiple completed helical bands. Keep both neck grips and the existing left-under/right-over wrist silhouettes;the left connected thumb stays under its neck,the right broad back stays across the upper neck. The left thumb must have a visible broad coral web connecting it to its mitten,never a detached oval. Keep short thin-paper necks,no hangingloop,no thickrope,no newmaterial. Preserve sweetcentre,oval,fans,table,cuffs,face and allscene. Return one complete scene with partially turned paper,not the finished wrapped endpoint.','assets_src/imagegen/candy_twist_release_pose_v1_20261003/twist_attempt05/native.png'),
'release_attempt04':(common+' Input image1 is the early clean-release edit target and ONLY reference. KEEP BOTH HANDS EXACTLY WHERE THEY ARE:low,close above their own necks,thumbs attached,purplegaps,cuffs and sleeves unchanged. Only flatten the two goldneckcoils:replace roundedprotrudingrope-likebumps with two short pressed DIAGONAL FLAT PAPER CREASES flush against the gathered sheet,oppositelywound,thinsoftpaper. No roundedtubes,knot,braid,ring,extramaterial. Keep exactoval,fanoutline,table,sweetposition,faceandroom. Do not changehands towidefinalrest. Return one complete scene;onlythetwo goldneckmaterialpatches change.','assets_src/imagegen/candy_wrap_transition_keys_v1_20261003/release_attempt02/native.png')}
for name,(prompt,path) in req.items():
 M=P/name;assert not M.exists();M.mkdir();put(M/'PROMPT.txt',(prompt+'\n').encode());write(M/'GENERATION_REQUEST.json',dict(status='READY_NAMED_CORRECTION_NOT_GENERATED',attempt=4,method='BUILTIN_IMAGEGEN_COMPLETE_FLATTENED_SOURCE',references=[dict(role='edit_target',path=path,sha256=sha((B/path).read_bytes()),dimensions=list(Image.open(B/path).size))],prompt_path=(M/'PROMPT.txt').relative_to(B).as_posix(),prompt_sha256=sha((M/'PROMPT.txt').read_bytes()),source_score=None,mounted_score=None,sequence_score=None,action_score=None,owner_acceptance=None,qualification='Same-scene complete native source only.'))
put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes());d=json.loads(IP.read_text());d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});d['validation'].append(dict(command='Third complete native candidates/22 individual opinions',result='FAIL',evidence=P.relative_to(B).as_posix()+'/midturn_attempt03/DIRECT_REVIEW.json and release_attempt03/DIRECT_REVIEW.json;4.0/4.2 rejected for wrongpair/growingfold and wrongreleasestage.'));write(IP,d)
print('SIX_NATIVE_DRAFTS_66_OPINIONS_REJECTED_TWO_FOCUSED_FOURTH_RETRIES_PREPARED')
