from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
P=R/'assets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002'
BASE='72a15c1c49456e37d81c733b8dd6ef4cdc736a45'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert not P.exists()
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R).decode().strip()==BASE
blocked=read(R/'assets_src/imagegen/nursery_palm_attention_v1_20261002/REFERENCE_UPLOAD_BLOCK.json')
assert blocked['reference_uploaded'] is False
P.mkdir();(P/'review_tools').mkdir();(P/'.gdignore').write_text('',encoding='utf-8')
plan=dict(status='PLANNED_BEFORE_FRESH_GENERATION',baseline=BASE,created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),scope='One fresh text-only built-in ImageGen Nursery palm-rubbing/attention source candidate, applying owner request for fresh generation and simplified 2D style. No existing reference image is transmitted, no edit of the blocked palm02 target is attempted, no existing or protected artwork changes. New candidate and every failure preserved separately; no runtime binding or score inherited.',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-VIS-08','DL-MOT-01','DL-MOT-03','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-01','DL-QA-03','DL-QA-06'],findings=['MA-VIS-006','MA-PLAY-004'],gap='Current Nursery attention3.8 and A1 motion attention3.1 remain weak: forward gaze ignores the washing action. The earlier exact palm02 reference-edit upload remains pending separate explicit permission; no such upload or edit occurs here. A new independently generated source may improve attention and simplified anatomy but must independently earn style/identity/contact review.',inventory=[dict(path='assets_src/imagegen/nursery_wash_connected_v1_20261002/rub_palm_attempt02/native.png',sha256=sha(R/'assets_src/imagegen/nursery_wash_connected_v1_20261002/rub_palm_attempt02/native.png'),reuse_assessment='Existing static-source floor4.5, already preserved and reused by local A1/A2. Head/eyes look forward; current attention remains3.8. Not supplied to image generator.'),dict(path='assets_src/local_motion/nursery_connected_scrub_v1_20261002/attempt01/DIRECT_REVIEW.json',sha256=sha(R/'assets_src/local_motion/nursery_connected_scrub_v1_20261002/attempt01/DIRECT_REVIEW.json'),reuse_assessment='Every41 frame reviewed; failed clasp/action3.6/attention3.1. Reference motion cannot repair still gaze source.')],generation_method='Built-in image_gen, fresh new generation from text only; omit referenced_image_paths and num_last_images_to_include; transparent_background true',reference_images=[],reference_upload_block_preserved=True,required_evidence=['Native transparent RGBA image preserved separately and exact SHA/dimensions/provenance','Direct native and whole-canvas neutral QA review of style, face/costume/tail identity, anatomy/contact, gaze, basin/faucet/support, clipping/alpha and practical scale','No automatic source acceptance at returned dimensions or successful generation','Subsequent ordinary runtime/action/device/child/owner gates remain open; any local animation study uses separately approved developed local workflow'])
write(P/'PLAN.json',plan)
prompt='''Use case: illustration-story. Create one brand-new transparent RGBA game artwork sprite from this text description. One complete character and one connected washing prop, no layout sheet, no text. Do not draw a photograph or a realistic person.
Roshan is a cheerful little mermaid child with a large round storybook head, warm medium peach skin, big simple brown eyes, rounded cheeks, long brown curls with a broad pastel rainbow lock, and a small gold shell tiara. She wears a pale aqua nursery apron over a simple lavender gingham blouse with short rounded sleeves; a small crescent-moon patch on the apron. Her long curled iridescent lavender/aqua tail ends in two broad rounded rainbow fin lobes. Show her entire tiara, curls, arms, body, curled tail and both fin tips with generous clear padding; no crop.
She quietly washes her hands at a small friendly aqua basin on a broad stable lavender pedestal. Three-quarter view, Roshan on the left and basin on the right, at a practical waist-level work height. Her head tilts gently down and both pupils unmistakably look at the touching palms. Both forearms visibly connect to her own shoulders through low bent elbows. Her far hand is cupped horizontally above the inside of the basin; her near palm rests flat across it in a low sliding-rub pose. Soft small child fingers, with a distinct near palm and far cupped palm; no raised clasp, clapping or prayer pose. A tiny contained patch of white lather lies only between the palms. The tap is off and no soap connects to the spout. Both hands are clearly inside the basin boundary, ready for two short horizontal rubbing strokes. Gentle attentive expression.
Polished painted 2D storybook toy-playset style: rounded silhouettes, confident navy-purple contour lines, broad clean pastel paint bands, aqua/lavender shadows, restrained highlights and very sparse brush grain. Simplify facial and hand anatomy; no realistic skin, pores, gloss, rendered 3D lighting, harsh gradients or fine busy textures. Child-readable at small game size. Quiet costume, body, tail and fixture; the hands are the focus. Preserve one coherent whole painting rather than disconnected limbs. Actual transparent background, no scenery, floor rectangle, backplate, labels, frames, arrows, sparkles, extra character, tool, duplicated hand, extra arm or extra fingers. Only a soft painted contact shadow directly under the basin pedestal and tail.
'''
(P/'PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n');plan['prompt_sha256']=sha(P/'PROMPT.txt');write(P/'PLAN.json',plan)
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
write(R/'design/audit_impacts/job-nursery-fresh-attention-20261002.json',dict(id='job-nursery-fresh-attention-20261002',scope=plan['scope'],baseline=BASE,rules=plan['rules'],findings=plan['findings'],files=sorted(p.relative_to(R).as_posix() for p in P.rglob('*') if p.is_file()),validation=[dict(command='Fresh text-only built-in ImageGen source; direct individual review',result='PENDING',evidence=P.relative_to(R).as_posix()+'/PLAN.json')],acceptance_gaps='Only one new still-source candidate; no exact approved source identity presumed, no runtime/action/mounted/device/child/owner/all-job acceptance. Blocked original reference upload remains explicitly blocked and has not occurred. Preserve native/failures and separately judge style/identity/gaze/contact before local studies or runtime binding.'))
print('FRESH_NURSERY_ATTENTION_PLAN|No reference images or uploads|No existing edits|Named gaze/anatomy/style gap|Direct review pending')
