from pathlib import Path
import datetime,hashlib,html,json,shutil
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
S=R/'assets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002'
M=R/'assets_src/local_motion/nursery_connected_scrub_v2_20261002'
L=R/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
items=[('FRESH-NUR-A2-01','Painted style',4.6,'Broad pastel value bands, rounded chibi silhouette and clean purple contours read as painted storybook art. Skin and fingers remain simplified; no lifelike photographic anatomy.'),('FRESH-NUR-A2-02','Face and gaze',4.6,'Downward head angle and both pupils clearly attend to the rubbing palms. Quiet smile supports helping rather than presenting to the camera.'),('FRESH-NUR-A2-03','Nursery hair/headwear identity',4.5,'Pink headband, cream shell-flower clip, brown curls/bangs and broad trailing rainbow lock restore the current Nursery design description. Fresh drawing remains a new source, not an exact approved-source edit.'),('FRESH-NUR-A2-04','Nursery costume identity',4.5,'Aqua apron, lilac gingham puff sleeves and cream-edged collar, chest gold star/pink shell and scalloped lavender crescent/three-stars pocket restore the known costume grammar. Waist/sleeve proportions still need actual-family transition review.'),('FRESH-NUR-A2-05','Connected arms',4.6,'Both low elbows, forearms and wrists connect continuously to her shoulders/body. No detached arm or extra limb; practical work height.'),('FRESH-NUR-A2-06','Palm contact',4.5,'Near fingers lie across a separate cupped far palm low inside the basin boundary. Foam hides part of the far palm, keeping this at the inclusive floor; no continuous rubbing movement is established.'),('FRESH-NUR-A2-07','Contained lather',4.6,'Small foam patch remains between hands. No lather reaches the spout, no uncontrolled splash/reward effect and off tap is clear.'),('FRESH-NUR-A2-08','Tail and fin identity',4.5,'Complete curled aqua/lilac/pink iridescent tail and two large rainbow fin lobes retain child-readable identity. Larger scale bands and paler fin are a fresh variant requiring mounted/family/phone review.'),('FRESH-NUR-A2-09','Basin and support',4.5,'Warm cream rim, aqua bowl/turquoise water, short gold down-spout/cross-handle, lavender pedestal/cream scallops and broad rounded foot restore the existing fixture grammar. Work/support relation is a still-source opinion.'),('FRESH-NUR-A2-10','Complete contours and alpha',4.5,'All major tiara-free headband, hair, body, hands, tail/fin and pedestal contours are visible. Alpha>=8 bounds retain about4% margins; the requested10% was not delivered, and low-alpha trace reaches canvas limits. Whole-canvas technical padding is required before runtime packaging; no cropped limb or repaired pixel is claimed.'),('FRESH-NUR-A2-11','Whole static source',4.5,'Meaningful down-gaze and connected low palm pose restore style/identity at a provisional source floor. Preserve native unchanged, test the exact source at actual work scale and the approach/rub/rinse/clean transitions. Source selection does not pass motion or current game.')]
g=read(S/'attempt02/GENERATION.json');assert sha(S/'attempt02/native.png')==g['sha256']
review=dict(status='PROVISIONALLY_SELECTED_STATIC_SOURCE_ONLY_UNBOUND',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),generation=g,individual_items=[dict(id=i,label=l,score=s,evaluation=e,direct_native_review=True,mounted_score=None,complete_action_score=None,owner_acceptance=None) for i,l,s,e in items],whole_source_score=4.5,style_score=4.6,gaze_score=4.6,palm_contact_score=4.5,current_game_action_score=3.9,current_game_attention_score=3.8,reference_uploaded=False,existing_target_edited=False,qualification='Entire newly returned native plus separate current Nursery source directly inspected. Fresh text-only generation; no exact-source edit or reference transmission. Raw native alpha/padding limitations retained. No actual mounting, animation/transition, device, child, owner or all-job acceptance.')
write(S/'attempt02/SOURCE_REVIEW.json',review)
p=read(S/'PLAN.json');p.update(status='A2_PROVISIONAL_STATIC_FLOOR45_A1_REJECTED_UNBOUND',attempt02_review='attempt02/SOURCE_REVIEW.json');write(S/'PLAN.json',p)
old=read(S/'attempt01/SOURCE_REVIEW.json')
def cards(rows):return ''.join('<article><strong>'+html.escape(x['label'])+' — '+str(x['score'])+'/5</strong><p>'+html.escape(x['evaluation'])+'</p></article>' for x in rows)
(S/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Fresh Nursery attention sources</title><style>body{font:18px system-ui;max-width:1050px;margin:36px auto;padding:0 20px;background:#f1f5fa;color:#25334a}img{width:100%;height:auto;background:#dfedf1}article{background:white;border-radius:14px;padding:18px;margin:12px 0}</style><h1>Fresh Nursery attention sources</h1><p>Two fresh text-only built-in ImageGen attempts. No existing reference image uploaded or target edited. A2 reaches the provisional4.5 still-source floor; gaze/style4.6, palm contact4.5. Current game action3.9/attention3.8 remain unchanged. Both originals and all22 individual reviews are preserved.</p><h2>A2: current unbound static candidate</h2><a href="attempt02/native.png"><img src="attempt02/native.png" width="1230" height="1278" alt="Full fresh A2 native Nursery painting, attentive low hand contact"></a>'+cards(review['individual_items'])+'<p><a href="attempt02/SOURCE_REVIEW.json">Complete A2 review</a> · <a href="attempt02/GENERATION.json">Native provenance</a> · <a href="attempt02/PROMPT.txt">A2 final prompt</a></p><h2>A1: rejected continuity4.1</h2><a href="attempt01/native.png"><img src="attempt01/native.png" width="1230" height="1278" alt="Preserved rejected fresh A1 source"></a>'+cards(old['individual_items'])+'<p><a href="attempt01/SOURCE_REVIEW.json">Complete A1 review</a> · <a href="PROMPT.txt">A1 final prompt</a> · <a href="../../local_motion/nursery_connected_scrub_v2_20261002/index.html">Rejected local A2 motion: every41 native frame</a></p><p>Native files are unchanged outside runtime. No full motion/transition/mounted/device/child/owner/all-job approval; pending original reference upload remains blocked.</p></html>',encoding='utf-8',newline='\n')
idx=read(M/'attempt01/INDEX.json');assert len(idx['frames'])==41 and len(idx['boards'])==3
frames=[]
for row in idx['frames']:
 assert sha(R/row['path'])==row['sha256']
 i=row['index'];frames.append(dict(**row,directly_reviewed_on_ordered_whole_canvas_board=True,full_native_detail_review=i in [0,4,8,12,16,20,24,28,32,36,39,40],visual_frame_score=4.5 if i==0 else (4.4 if i<24 else 4.2),evaluation='Low connected palm contact is retained but no discernible reciprocal stroke is represented; bubbles/foam change above the contact. Forward gaze persists.'+(' Late costume/tail value patches and contour shimmer weaken stability.' if i>=24 else ''),runtime_score=None,owner_acceptance=None))
components=[('Character identity',4.5,'Body/face/headband/rainbow tail remain recognizable; successful identity does not approve the motion.'),('Costume/contour stability',4.1,'Late gingham, apron/tail patches and contours crawl while the requested body stillness is otherwise maintained.'),('Connected palm contact',4.4,'Hands stay low, joined and near the basin rather than rising into A1 clasp. Finger detail remains small and soft.'),('Reciprocal rubbing action',2.8,'No clear two-stroke back-and-forth slide across the cupped palm. The sequence mostly holds the source pose; foam/bubble changes are not rubbing.'),('Attention',3.1,'Original forward gaze remains disconnected from the hands. No down-gaze repair was requested in this controlled prompt-only comparison.'),('Fixture/tap/lather relation',4.4,'Basin support and off tap remain recognizable; small foam/bubble changes occur near contact and slight fixture shimmer remains.'),('Entry/exit contact',4.3,'Low source contact remains at entry/exit, but late source contour/material drift prevents a seamless-loop claim.'),('Whole motion reference',3.0,'Better than clasping for contact; too static to demonstrate the intended action. Rejected below4.5. Current game action3.9 unchanged.')]
motion=dict(status='ALL41_NATIVE_FRAMES_REVIEWED_REFERENCE_ACTION_REJECTED',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),boards_reviewed=[x['path'] for x in idx['boards']],native_frame_count=41,full_native_details=[0,4,8,12,16,20,24,28,32,36,39,40],individual_frames=frames,component_evaluations=[dict(label=l,score=s,evaluation=e) for l,s,e in components],reference_action_score=3.0,reciprocal_rubbing_score=2.8,attention_score=3.1,current_game_action_score=3.9,current_game_attention_score=3.8,runtime_integration=False,cinematic_delivery=False,owner_acceptance=None,qualification='All41 native canvases directly inspected in row-major sequence on three full-canvas ordered boards;12 additional unchanged full-native images inspected. Direct video decoding, never full-frame cinematic regeneration. No current-game or still-source score transfer. A1 and A2 failed takes preserved.')
write(M/'attempt01/DIRECT_REVIEW.json',motion);write(M/'REVIEW_STATUS.json',dict(status='MACHINE_RENDER_COMPLETE_VISUAL_REJECTED',native_frame_count=41,reference_action_score=3.0,review='attempt01/DIRECT_REVIEW.json',runtime_integration=False,cinematic_delivery=False,owner_acceptance=None,current_game_action_score=3.9,score_transfer=False,manifest_and_dispatch_inputs_preserved=True))
video=next(x for x in idx['outputs'] if x['path'].endswith('.webm'));video_rel=(R/video['path']).relative_to(M).as_posix()
gallery=''.join('<a href="'+(R/x['path']).relative_to(M).as_posix()+'"><img src="'+(R/x['path']).relative_to(M).as_posix()+'" width="1792" height="1140" alt="A2 ordered native frame board starting'+str(x['first'])+'"></a>' for x in idx['boards'])
details=''.join('<article><p>Frame'+str(x['index'])+' at'+format(x['timestamp_seconds'],'.3f')+'s — visual'+str(x['visual_frame_score'])+'/5</p><a href="'+(R/x['path']).relative_to(M).as_posix()+'">Full native image</a><p>'+html.escape(x['evaluation'])+'</p><small>'+x['sha256']+'</small></article>' for x in frames)
(M/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Nursery scrub A2 review</title><style>body{font:18px system-ui;max-width:1150px;margin:36px auto;padding:0 20px;color:#253449;background:#f2f5fa}img,video{width:100%;height:auto}article{background:white;border-radius:14px;padding:16px;margin:12px 0}small{overflow-wrap:anywhere}</style><h1>Nursery scrub A2: rejected action3.0</h1><p>Same source/input/seed/settings/developed workflow as A1; prompt only changed. Every41 native frame was directly inspected on3 ordered whole-canvas boards, with12 additional full-native views. Better low contact4.4, but reciprocal rubbing2.8, attention3.1 and late costume/contour stability4.1 fail the4.5 floor. Current game action3.9/attention3.8 unchanged.</p><video controls preload="metadata" src="'+video_rel+'"></video>'+''.join('<article><strong>'+l+' — '+str(s)+'/5</strong><p>'+e+'</p></article>' for l,s,e in components)+gallery+'<h2>Every individual native frame</h2>'+details+'<p><a href="attempt01/DIRECT_REVIEW.json">Complete individual review</a> · <a href="attempt01/RENDER_RECEIPT.json">Exact native render receipt</a> · <a href="MANIFEST.json">Preserved bound dispatch manifest</a> · <a href="../nursery_connected_scrub_v1_20261002/index.html">Rejected A1</a> · <a href="../../imagegen/nursery_scrub_attention_fresh_v1_20261002/index.html">Fresh still attention candidates</a></p><p>Local motion reference only. No runtime, cinematic, device, child, owner or all-job acceptance; no external reference image uploaded.</p></html>',encoding='utf-8',newline='\n')
hist=L/'history_v35_before_fresh_nursery';assert not hist.exists();hist.mkdir()
for name in ('ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json'):shutil.copyfile(L/name,hist/(name+'.original'))
reg=read(L/'ALL_ITEMS.json');assert len(reg['items'])==1778
new=[]
for attempt,rv,whole in [('attempt01',old,4.1),('attempt02',review,4.5)]:
 path=(S/attempt/'native.png').relative_to(R).as_posix();digest=sha(R/path);source_id='FRESH-NUR-SOURCE-'+attempt[-2:]
 base=dict(aliases=[],path=path,earlier_sha256=digest,current_checkout_sha256=digest,current_byte_status='EXACT_EARLIER_BYTES',source_dimensions=[1230,1278],preview_path=path,image_path=path,image_scope='Complete fresh native source; individual component assessment is specified separately',families=['Fresh Nursery source candidates'],original_reports=[S.relative_to(R).as_posix()+'/index.html'],source_qualification=rv['status']+'; static source only, current game unchanged',protected_original=False,current_mounted_score=None,current_complete_action_score=None,owner_acceptance=None,latest_source_sha256=digest,native_reference_observations=[],latest_refinement=dict(report=S.relative_to(R).as_posix()+'/index.html',note='Fresh text-only source; no existing reference uploaded. Static score does not pass mounted/current action.'),refinement='Review actual work size and all state/approach/contact/rub/rinse/clean/return transitions before binding.')
 new.append(dict(**base,id=source_id,kind='source',historical_source_score=whole,latest_source_score=whole,current_source_score=whole,priority=whole<=4.5,evaluation=rv['individual_items'][-1]['evaluation']))
 for obj in rv['individual_items']:
  new.append(dict(**base,id=obj['id'],parent_source_id=source_id,kind='source object region',label=obj['label'],historical_source_score=obj['score'],latest_source_score=obj['score'],current_source_score=obj['score'],priority=obj['score']<=4.5,evaluation=obj['evaluation'],individual_scope='Named component evaluated within complete native source; no extracted object or runtime score.'))
reg['items']+=new;assert len(reg['items'])==1802
c=reg['counts'];c.update(unique_source_files=1263,individual_source_object_regions=126,registered_items=1802,exact_earlier_bytes=sum(x.get('current_byte_status')=='EXACT_EARLIER_BYTES' for x in reg['items']),inclusive_current_source_priorities=sum(x.get('current_source_score') is not None and x['current_source_score']<=4.5 for x in reg['items'] if x['kind'] not in ('runtime prop region','runtime use/action')),new_fresh_nursery_source_files=2,new_fresh_nursery_component_opinions=22)
reg['display_revision']='V36_FRESH_NURSERY_ATTENTION_AND_REJECTED_A2';reg['qualification']+=' Fresh Nursery A1 rejected4.1, A2 provisional static floor4.5 with down-gaze/style4.6, both unbound; local motion A2 rejected3.0 after all41 native frames reviewed. No current-source/mounted/action acceptance transfer.'
reg['review_resources']=reg.get('review_resources',[])+[dict(path=S.relative_to(R).as_posix()+'/index.html',scope='Two fresh stills/22 individual component evaluations'),dict(path=M.relative_to(R).as_posix()+'/index.html',scope='Every41 native local A2 frame and eight component/action opinions; rejected3.0')]
write(L/'ALL_ITEMS.json',reg)
h=(L/'all_items.html').read_text(encoding='utf-8');h=h.replace('V35_CURRENT_GEODE_RECHECK','V36_FRESH_NURSERY_ATTENTION_AND_REJECTED_A2');addition='<p>Fresh Nursery source review: <a href="../../'+S.relative_to(R).as_posix()+'/index.html">A1 rejected4.1 / A2 unbound static4.5, all22 components</a> · <a href="../../'+M.relative_to(R).as_posix()+'/index.html">Local A2 action rejected3.0, all41 native frames</a>. Current game and Geologist opinions unchanged.</p>';h=h.replace('<script>',addition+'<script>',1);(L/'all_items.html').write_text(h,encoding='utf-8',newline='\n')
for p in (S,M):shutil.copyfile(__file__,p/'review_tools'/Path(__file__).name)
for ip,p,extra in [(R/'design/audit_impacts/job-nursery-fresh-attention-20261002.json',S,{(L/'ALL_ITEMS.json').relative_to(R).as_posix(),(L/'all_items.html').relative_to(R).as_posix(),(L/'CURRENT_BOUNDARY_REFRESH.json').relative_to(R).as_posix()}|{x.relative_to(R).as_posix() for x in hist.rglob('*') if x.is_file()}),(R/'design/audit_impacts/job-nursery-scrub-a2-20261002.json',M,set())]:
 d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in p.rglob('*') if x.is_file()}|extra);d['validation'].append(dict(command='Direct native source/component and local A2 full41-frame review',result='PASS' if p==S else 'FAIL',evidence=p.relative_to(R).as_posix()+'/index.html; source selection and failed action remain separate.'));write(ip,d)
ledger=R/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');s=s.replace('All41 native frames pending direct review, current game action3.9/attention3.8 unchanged.','All41 native frames directly reviewed on3 ordered boards plus12 full-native details; low contact4.4 but reciprocal2.8/attention3.1/reference3.0 rejected. Current game action3.9/attention3.8 unchanged.').replace('`CANDIDATE_REFERENCE_ONLY`; prompt-only low reciprocal-rub A2','`REJECTED_REFERENCE_STUDY`; prompt-only low reciprocal-rub A2').replace('A2 restores established design description and padding; no runtime/action/device/child/owner/all-job acceptance','A2 restores established design description, whole source4.5/gaze/style4.6/palm4.5; raw padding/low-alpha trace and actual transition review remain open. Both natives/all22 opinions preserved, no runtime/action/device/child/owner/all-job acceptance');ledger.write_text(s,encoding='utf-8',newline='\n')
print('NURSERY_REVIEW_RECORDED|FreshA2 unbound still4.5 gaze/style4.6|A1 rejected4.1|localA2 all41 reviewed action3.0 rejected|Library1802 entries|Current production unchanged')
