from pathlib import Path
import datetime,hashlib,json,shutil
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
P=R/'assets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
g=read(P/'attempt01/GENERATION.json');assert sha(P/'attempt01/native.png')==g['sha256']
items=[('FRESH-NUR-A1-01','Painted style',4.5,'Rounded child face and broad lavender/aqua paint bands improve simplification; fine curls/scales and softly rendered skin still make this an inclusive refinement priority.'),('FRESH-NUR-A1-02','Face and gaze',4.6,'The tilted head and pupils clearly attend to the touching palms. Childlike rounded cheeks, broad eyes and quiet smile read without text.'),('FRESH-NUR-A1-03','Roshan hair/headwear continuity',4.1,'New gold tiara and forehead rainbow forelock replace the established Nursery pink headband/cream shell clip and broad trailing rainbow lock; beautiful independent drawing does not preserve the current costume family.'),('FRESH-NUR-A1-04','Nursery apron/blouse continuity',4.0,'Aqua apron and lilac gingham remain, but collar, chest star/shell ornaments and lilac moon/stars pocket are replaced by a cream-edged aqua moon pocket. Rebuild the established details before source selection.'),('FRESH-NUR-A1-05','Connected arms',4.6,'Both upper arms and low elbows connect visibly to the torso; neither wrist floats. Anatomical proportions are simplified and consistent.'),('FRESH-NUR-A1-06','Palm-rubbing contact',4.6,'Near palm lies over a distinct cupped far palm above the basin, with low wrists and finger overlap rather than a raised prayer clasp. This still is not proof of reciprocal motion.'),('FRESH-NUR-A1-07','Contained lather',4.6,'Small white foam lies between the palms; none reaches the off tap and no wash outcome is falsely displayed.'),('FRESH-NUR-A1-08','Tail/fin continuity',4.4,'Complete curved tail and paired rainbow fin retain identity, but scale colours/order and pale washed fin differ from the current stronger lavender/rainbow family; compare at actual size.'),('FRESH-NUR-A1-09','Basin/tap/pedestal continuity',4.2,'Support is clear and usable, but shell-fluted rim/bowl, curved tap and ornate base replace the existing cream-rim basin/cross-handle tap/simple scalloped pedestal.'),('FRESH-NUR-A1-10','Whole-canvas padding/shadow',4.2,'Major body and fin silhouettes are present, but shadow reaches left and bottom native limits instead of generous transparent padding. Alpha edge bounds alone do not establish a cropped limb.'),('FRESH-NUR-A1-11','Complete source and family fit',4.1,'Useful down-gaze and low reciprocal-contact pose, but costume/hair/fixture continuity remains materially below4.5. Preserve as rejected, unbound source; no current-game score transfer.')]
review=dict(status='REJECTED_SOURCE_CONTINUITY_BELOW45',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),generation=g,individual_items=[dict(id=i,label=l,score=s,evaluation=e,direct_native_review=True,current_mounted_score=None,current_complete_action_score=None,owner_acceptance=None) for i,l,s,e in items],complete_source_score=4.1,painted_style_score=4.5,gaze_score=4.6,palm_contact_score=4.6,reference_uploaded=False,existing_image_edited=False,current_game_action_score=3.9,current_game_attention_score=3.8,qualification='Entire returned fresh native generation and separate preserved current palm02 source inspected directly. No reference was submitted to ImageGen. New source identity differences are honest defects; low score preserved. Current game and prior source opinions unchanged.')
write(P/'attempt01/SOURCE_REVIEW.json',review)
plan=read(P/'PLAN.json');write(P/'PLAN.original_before_a1_review.json',plan);plan.update(status='ATTEMPT01_REJECTED_SOURCE_CONTINUITY_BELOW45',attempt01_review='attempt01/SOURCE_REVIEW.json');write(P/'PLAN.json',plan)
(P/'attempt02').mkdir()
prompt='''Use case: illustration-story. One brand-new transparent RGBA game sprite from text only. One complete little mermaid child washing her own hands at one basin. Preserve the following exact Nursery design description. No photo, realistic person, scene, typography or sheet.
Roshan has a large rounded storybook head, warm medium peach skin, big simple brown eyes and shoulder-length brown curls with bangs. Wear a salmon-pink fabric headband with one cream shell-flower clip beside the bangs. A broad saturated pastel rainbow lock trails behind her brown hair to the left. NO gold crown, tiara, forehead rainbow swoop or waist-length hair.
Costume: lavender gingham blouse, short rounded puff sleeves and a rounded lilac collar edged in pale cream. Pale aqua apron with a small gold star and pink shell ornament vertically on the upper chest. Scalloped lavender front pocket containing a small yellow crescent moon and three simple yellow stars. Lavender gingham hem under the apron. One long curled iridescent tail with broad aqua, lilac and pink rainbow scale bands, ending in two oversized broad fin lobes coloured coral-pink, yellow, aqua, blue and lavender. Entire tail and both fin tips visible.
Three-quarter work view: Roshan left, basin right at waist height. Her head tips down and both pupils unmistakably look at her touching hands. Both elbows stay low and forearms visibly join her own shoulders. Her far hand cups horizontally inside the basin boundary; her near palm lies low and flat across that palm, poised for a tiny horizontal sliding rub. Clearly separate, simple small child fingers. Only a small soft patch of white lather between the contacting palms. No raised clasp, clap or prayer hands. Gentle attentive smile; body quiet.
The basin is a rounded aqua bowl with a broad warm-cream rim and quiet turquoise water, one short gold downward spout with a simple gold cross-handle, tap OFF. One simple lavender pedestal with a cream scalloped lower band and broad rounded oval base. No shell-fluted bowl, ornate relief or extra prop. No foam trail or running water at the off tap.
Polished 2D painted storybook toy-playset style, not realistic: rounded forms, clean navy-purple contours, broad pastel value bands, aqua/lavender shadows, restrained highlights, sparse paint grain and simple facial/hand anatomy. Avoid glossy realistic skin, pores, detailed rendering or 3D. Child-readable at small game size. Draw the entire connected character/fixture with at least10 percent clear transparent margin on EVERY side, including below both short contact shadows. No body, fin, hair, pedestal or shadow reaches the canvas edge. Actual transparent background; no floor/backplate, borders, arrows, sparkles, detached limbs, duplicated hands, extra fingers or extra characters.
'''
(P/'attempt02/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(P/'attempt02/PLAN.json',dict(status='PLANNED_BEFORE_FRESH_GENERATION',generation_method='Built-in ImageGen fresh text-only, no references, transparent background',references=[],reference_uploaded=False,existing_target_edited=False,prompt_sha256=sha(P/'attempt02/PROMPT.txt'),target='Restore existing Nursery design and full padding while preserving useful down-gaze and low touching-palms semantics; attempt01 remains rejected.',required_review='All individual identity/style/contact/gaze/fixture/alpha/padding components before any source selection; no runtime/action or owner score presumed.'))
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
attrs=R/'.gitattributes';attrs.write_bytes(attrs.read_bytes()+b'\nassets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002/** -text\n')
lic=R/'ASSET_LICENSES.md';lic.write_bytes(lic.read_bytes()+b'\n| `assets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002/**` | Built-in OpenAI ImageGen, fresh text-only transparent Nursery source attempts | Original project-generated draft artwork | Exact native/prompt SHA256 and generation/review records | No existing reference uploaded or original edited. Attempt01 rejected for costume/hair/fixture continuity4.1; originals retained outside runtime. No game/cinematic/device/child/owner acceptance. |\n')
ledger=R/'design/05_DOC_LEDGER.md';ledger.write_bytes(ledger.read_bytes()+b'\n| `assets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002/index.html` | '+ '🟣'.encode()+b' | `CANDIDATE_SOURCE`; fresh text-only ImageGen with no reference upload. Native A1 down-gaze/contact4.6 but costume/hair/fixture continuity fails, whole source4.1; rejected unbound original and11 individual opinions preserved. A2 restores established design description and padding; no runtime/action/device/child/owner/all-job acceptance or bypass of pending original-image upload. |\n')
(P/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Fresh Nursery attention sources</title><style>body{font:18px system-ui;max-width:1050px;margin:36px auto;padding:0 20px;background:#f0f5fa;color:#25334a}img{width:100%;height:auto;background:#ddeff3}article{padding:18px;margin:12px 0;background:white;border-radius:14px}</style><h1>Fresh Nursery attention sources</h1><p>Text-only generation, no reference uploads and no existing image edits. A1 improves gaze and palm contact, but changes the established Nursery costume, hair and fixture. Whole source4.1: rejected and unbound. Current game action3.9/attention3.8 remain unchanged.</p><img src="attempt01/native.png" alt="Rejected fresh A1 full native painting">'+''.join('<article><strong>'+l+' — '+str(s)+'/5</strong><p>'+e+'</p></article>' for i,l,s,e in items)+'<p><a href="attempt01/SOURCE_REVIEW.json">All individual reviews</a> · <a href="attempt01/GENERATION.json">Native provenance</a> · <a href="PROMPT.txt">A1 final prompt</a> · <a href="attempt02/PROMPT.txt">A2 planned prompt</a></p><p>Native originals preserved. No mounted, complete motion, device, child, owner or all-job approval.</p></html>',encoding='utf-8',newline='\n')
ip=R/'design/audit_impacts/job-nursery-fresh-attention-20261002.json';d=read(ip);d['files']=sorted({p.relative_to(R).as_posix() for p in P.rglob('*') if p.is_file()}|{'.gitattributes','ASSET_LICENSES.md','design/05_DOC_LEDGER.md'});d['validation'].append(dict(command='Direct whole native fresh A1/source-family comparison',result='FAIL',evidence='assets_src/imagegen/nursery_scrub_attention_fresh_v1_20261002/attempt01/SOURCE_REVIEW.json;11 individual opinions; source4.1 continuity failure preserved.'));write(ip,d)
print('FRESH_A1_REJECTED|11 individual reviews|gaze/contact4.6|continuity/source4.1|No source/runtime score transfer|A2 text-only prompt planned')
