from pathlib import Path
import datetime, hashlib, html, json, shutil

r = Path(__file__).resolve().parents[1]
f = r / 'audit/day_two_boxing_live_refinement_v1_20261001'
read = lambda p: json.loads(p.read_text(encoding='utf-8'))
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
def write(p, data):
    p.write_text(json.dumps(data, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
def fig(path, caption):
    return '<figure><a href="'+html.escape(path)+'"><img loading="lazy" src="'+html.escape(path)+'" alt="'+html.escape(caption)+'"></a><figcaption>'+html.escape(caption)+'</figcaption></figure>'

capture = read(f/'native_actions_v1/CAPTURE_RECEIPT.json')
boards = read(f/'native_actions_v1/inspection_boards/MANIFEST.json')['boards']
edges = read(f/'native_edges_v2/CAPTURE_RECEIPT.json')['views']
assert len(capture['actions']) == 20 and len(capture['frames']) == 1402 and len(boards) == 58 and len(edges) == 16
assert sorted(i for b in boards for i in b['frame_indices']) == list(range(1402))
assert all(v['inside_action_surface'] and v['hits'] == 0 and v['progress'] == 0 for v in edges)
contacts = [8,51,94,137,321,502,541,583,625,667,710,753,796,839,1022,1202,1241,1283,1325,1367]
direct_extra = [324,505,624,666]
actions = []
for i,a in enumerate(capture['actions']):
    mode=a['mode']; contact=contacts[i]; first=a['first_frame']; last=a['last_frame']
    assert capture['frames'][contact]['progress'] == 1
    assert capture['frames'][last]['impact_time'] == 0
    lane_score = 4.6 if mode in ('boxing_guide','boxing_jab') else (4.2 if mode in ('boxing_guard','boxing_imp') else 4.0)
    detail = {
        'boxing_guide': 'The correctly owned hand moves to its own painted mitt, gets one readable contact puff, and stays at the completed guide target as the existing rule requires. The other hand retains its contrasting cuff. The effect clears without a hard alpha cut.',
        'boxing_jab': 'The complete mitten follows the requested forward path, lands against the painted mitt, then returns after release. The existing target advances with accepted work, and the completed contact cloud fades at its recorded contact point. This is one accepted jab, not a complete four-jab round.',
        'boxing_guard': 'The whole glove reaches the guard target and blocks the naturally timed counter without inventing a landed punch. The glove and puff fit the painted stage. The incoming counter remains a flat circle and arrow rather than readable authored glove action, so this sequence stays a priority.',
        'boxing_imp': 'The glove contacts the padded body while the face stays visible; one accepted punch follows the actual recover window. The complete puff clears. The imp changes whole-card poses abruptly and the bopped key does not establish connected recovery acting; the acting lane remains 3.8.',
        'boxing_belt': 'The approach glove is visible, but completion calls the existing cancellation/reset path during the accepted event. The next rendered frame already has both gloves at rest while the puff appears at the medallion. The missing rendered contact/return is a sequencing priority; improved bitmap art does not repair it.'
    }[mode]
    row={**a,'action_index':i,'agent_review':'DIRECT','ordered_frame_indices':list(range(first,last+1)),
         'full_native_contact_frame':contact,'full_native_final_frame':last,
         'individual_glove_art_and_contour_score':4.6,'puff_art_and_fade_score':4.6,
         'played_fixture_sequence_score':lane_score,'whole_job_route_score':None,'evaluation':detail,
         'evidence_boundary':'These action images retain the presentation-v1 source SHA. The subsequent edge-only repair is bounded by exact function equivalence and 160 unchanged interior drag positions; images are never relabeled as post-repair captures.'}
    actions.append(row)
visual={'status':'DIRECT_ALL_1402_ORDERED_FRAMES_20_CONTACTS_20_FINALS',
        'reviewer':'Codex agent visual inspection; drafting opinion only; owner approval pending',
        'reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
        'capture_receipt_sha256':sha(f/'native_actions_v1/CAPTURE_RECEIPT.json'),
        'method':'All 58 complete-canvas ordered boards directly inspected, covering every native frame once; all 20 first-progress contact frames and all 20 final frames additionally inspected at full native canvas. Four additional guard/approach views were inspected at full canvas. No continuous playback or phone inspection is claimed.',
        'boards':[dict(b,agent_review='DIRECT') for b in boards], 'actions':actions,
        'additional_full_native_indices':direct_extra,
        'full_native_indices':sorted(set(contacts+[a['last_frame'] for a in actions]+direct_extra)),
        'ordinary_root_input_and_hud_routes':'PENDING','device_child_owner_acceptance':'PENDING'}
write(f/'native_actions_v1/VISUAL_REVIEW.json',visual)
write(f/'native_edges_v2/VISUAL_REVIEW.json',{'status':'DIRECT_ALL_16_CURRENT_FULL_NATIVE_EDGE_VIEWS','reviewer':visual['reviewer'],
        'views':[dict(v,agent_review='DIRECT',complete_contour_fit_score=4.6,evaluation='The complete authored thumb, mitten dome and cuff stay within the actual action surface at this corner; no screen-cut contour is visible. Geometry is conservative and the native full canvas confirms the fit.') for v in edges],
        'qualification':'Two hands, four actual handler corner drags, both 1280 and 1600 widths. Zero accepted work and zero awards. Earlier clipped-edge failure is preserved separately; no route/device/owner pass.'})

priorities=[
    {'id':'BOX-LIVE-COUNTER-01','item':'Guard incoming counter representation','score':4.0,'priority':True,'evidence_frames':[320,501,1021,1201],'evaluation':'Flat coral disk and straight yellow arrow remain visibly separate from the authored mitten materials. They indicate direction but do not show a friendly glove counter. Inventory authored reusable incoming glove artwork before generating any replacement.'},
    {'id':'BOX-LIVE-IMP-ACT-01','item':'Imp connected reaction and recovery acting','score':3.8,'priority':True,'evidence_frames':[540,541,582,583,1240,1241,1282,1283],'evaluation':'Source keys preserve the friendly identity, but sudden complete-pose substitutions do not explain anticipation, body contact and recovery. Preserve all approved identity sources; evaluate authored bridge states against exact action timing.'},
    {'id':'BOX-LIVE-BELT-RETURN-01','item':'Belt rendered contact and return','score':3.8,'priority':True,'evidence_frames':[624,625,666,667,1324,1325,1366,1367],'evaluation':'The accepted completion resets the glove to rest before the contact frame is rendered. Preserve cancellation on interruption; separate successful completion presentation from the interruption reset, then measure real contact/return and the parent transition.'},
    {'id':'BOX-SHARED-PUFF-01','item':'Marked puff in shared career-world drawing contexts','score':2.5,'priority':True,'source_path':'assets/opera/worlds/props/fx_bop_puff.png','evaluation':'The boxing surface now uses exact clean existing art, but opera_career_world_2d.gd still binds the marked source in shared drawing contexts. This is an unchanged source opinion; current shared-context mounted and action scores remain unassigned.'}
]
items=[
    {'id':'BOX-LEFT-GLOVE-V1','name':'Painted left glove','path':'assets/opera/worlds/widgets/refinement_v1/boxing_glove_left.png','source_score':4.6,'static_mount_score':4.6,'current_edge_fit_score':4.6,'timed_individual_art_score':4.6,'evaluation':'Broad smooth coral mitten, right-facing authored thumb, gold shell and coral cuff retain a single readable contour. Matte painted bands, purple ink and aqua/lavender shadow fit the toy storybook stage. Complete-canvas texture is drawn intact with the existing position/depth/angle. The first left attempt with finger lobes remains rejected.'},
    {'id':'BOX-RIGHT-GLOVE-V1','name':'Painted right glove','path':'assets/opera/worlds/widgets/refinement_v1/boxing_glove_right.png','source_score':4.6,'static_mount_score':4.6,'current_edge_fit_score':4.6,'timed_individual_art_score':4.6,'evaluation':'The independently generated left-facing thumb and teal cuff distinguish the right hand while keeping the same coral mitten palette and matte material. Positive scale avoids accidentally reversing its authored hand. Whole painted contour survives contact, return and corner requests.'},
    {'id':'BOX-PUFF-REUSE-V1','name':'Exact existing clean puff','path':'assets/opera/worlds/props/fx_dust_puff.png','source_score':4.6,'static_mount_score':4.6,'timed_art_and_fade_score':4.6,'evaluation':'Existing rounded white/lavender painted cloud removes the stray dark marks. The whole card expands modestly and alpha tends continuously to zero; every inspected final has no residual cloud. This rating evaluates effect artwork and fading only; the belt still lacks a rendered glove-contact beat.'}
]
for item in items:item['sha256']=sha(r/item['path']);item['owner_approved']=False
review={'status':'SCOPED_REVERSIBLE_RUNTIME_PROP_REFINEMENT_REVIEWED_SEQUENCING_PRIORITIES_OPEN','created_utc':visual['reviewed_utc'],
        'baseline':'5b8bfb989ca8012924115d45901252808edb9b62','current_runtime_surface_sha256':sha(r/'scripts/opera_boxing_surface.gd'),
        'individual_items':items,'actions':actions,'priorities':priorities,
        'machine_evidence':['native_actions_v1/PROCESS_RECEIPT.json','native_edges_v2/PROCESS_RECEIPT.json','PRODUCTION_EQUIVALENCE.json','BOUNDARY_REPAIR_EQUIVALENCE_V2.json'],
        'visual_evidence':['native_actions_v1/VISUAL_REVIEW.json','native_edges_v2/VISUAL_REVIEW.json'],
        'preserved_failures':['native_edges_v1/VISUAL_REJECTION.json','../day_two_boxing_puff_reuse_v1_20261001/REVIEW.json','../../assets_src/imagegen/day2_boxing_single_gloves_v1_20261001/REVIEW.json'],
        'current_full_ci':{'status':'RUNNING_PENDING','path':'../day_one_pool_live_refinement_v2_20261001/full_ci_current_retry_v3/RECEIPT.json','production_source_files':325,'earlier_retry_status':'FAIL_81_OF_82; exact direct picture-games recheck passes but does not waive the red full suite'},
        'qualification':'Explicit actual career catalog phase fixtures, production local GUI handlers and process timers. Career-world processing is frozen to isolate the surface; phase progress is recorded without assigning persistent stars. Ordinary root/HUD routing, complete phase sets/training/job-day traversal, parent transition timing, listening/continuous playback, device/child/owner review and comprehensive all-job quality remain pending.',
        'all_job_pass':False,'owner_approved':False,'finding_closed':False}
write(f/'REVIEW.json',review)
profile=read(f/'PROFILE.json');profile['initial_status']=profile.get('initial_status',profile['status']);profile['status']=review['status'];profile['review']='REVIEW.json';profile['runtime_surface_sha256']=review['current_runtime_surface_sha256'];profile['acceptance_gaps']=review['qualification'];write(f/'PROFILE.json',profile)

css='''body{margin:0;background:#f6f1fb;color:#202139;font:17px/1.55 system-ui}main{max-width:1280px;margin:auto;padding:26px}section{background:white;border:1px solid #d8cde3;border-radius:18px;padding:24px;margin:24px 0}h1{font-size:36px;margin:0 0 14px}h2{font-size:27px;margin:0 0 14px}h3{font-size:21px}a{color:#5840a0}table{border-collapse:collapse;width:100%}td,th{border:1px solid #d8cde3;padding:11px;text-align:left;vertical-align:top}figure{margin:0 0 20px}img{display:block;width:100%;height:auto;border-radius:10px;background:repeating-conic-gradient(#ede6f2 0 25%,#fff 0 50%) 0/20px 20px}figcaption{padding:9px 3px;font-size:15px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.notice{background:#fff1cc;border-left:5px solid #dfac39;padding:16px}select,button,input{font:inherit;padding:8px}#frame{width:100%}.source img{height:320px;object-fit:contain}.bad{color:#983f54}code{overflow-wrap:anywhere}@media(max-width:720px){.grid{grid-template-columns:1fr}main{padding:14px}section{padding:15px}h1{font-size:29px}table{font-size:14px}}'''
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Boxing live artwork and action review</title><style>'+css+'</style><main><h1>Boxing: painted gloves, clean contacts, unfinished acting</h1><p>First-pass iterative review · source, mounted appearance and sequence scores are separate · owner approval pending</p><p><a href="../job_artwork_refinement_live/index.html">All-job artwork library</a> · <a href="REVIEW.json">Complete structured review</a> · <a href="ACTION_CONTRACT_V1.json">Action contract</a></p><p class="notice">The two glove bitmaps and the clean puff artwork meet the 4.6 drafting bar in this bounded review. The guard counter, imp acting and belt contact/return remain priorities. This report gives no whole-job or all-job quality pass. The full 325-file validation run is pending.</p><section><h2>Each individual replacement</h2><div class="grid source">'
for item in items:page+=fig('../../'+item['path'],item['name']+' — individual art 4.6/5')+'<p>'+html.escape(item['evaluation'])+'</p>'
page+='</div><table><tr><th>Item</th><th>Source</th><th>Mounted</th><th>Timed artwork</th><th>Current boundary</th></tr>'
for item in items:page+='<tr><td>'+item['name']+'</td><td>4.6</td><td>4.6</td><td>4.6</td><td>'+('16 native corners 4.6' if 'glove' in item['name'].lower() else 'Fades to zero; finals clear')+'</td></tr>'
page+='</table><p><a href="../../assets_src/imagegen/day2_boxing_single_gloves_v1_20261001/index.html">Preserved original, rejected finger-lobe attempt, fresh selected sources and 24 static comparisons</a>. Runtime cards are exact copies of the complete-canvas 1024 normalizations; approved targets, imp, background and protected sources are preserved.</p></section><section><h2>Review every recorded action</h2><p>20 actual local-handler requests: both hands, five modes, 1280×720 and 1600×720. Every one of 1,402 frames was directly reviewed on 58 ordered full-canvas boards; all 20 contacts and 20 finals were also inspected at full native canvas. Select an action and use the slider or buttons to inspect its original frames. Playback speed and phone performance were not measured.</p><label>Action <select id="action"></select></label><p><button id="previous">Previous frame</button> <button id="contact">First accepted event</button> <button id="end">Final frame</button> <button id="next">Next frame</button></p><input id="slider" type="range"><p id="detail"></p><a id="frameLink"><img id="frame" alt="Original native action frame"></a><p id="actionReview"></p></section><section><h2>Remaining weaknesses, individually scored</h2><table><tr><th>Item</th><th>Score /5</th><th>Written evaluation</th></tr>'
for p in priorities:page+='<tr><td>'+p['item']+'</td><td class="bad">'+str(p['score'])+'</td><td>'+p['evaluation']+'</td></tr>'
page+='</table><div class="grid">'+fig('native_actions_v1/frame_0320.webp','Guard counter before accepted block — flat disk/arrow remains 4.0')+fig('native_actions_v1/frame_0540.webp','Imp recover key before accepted hit — connected acting remains 3.8')+fig('native_actions_v1/frame_0624.webp','Belt approach: glove near the medallion')+fig('native_actions_v1/frame_0625.webp','Next rendered belt frame: accepted effect, glove already reset — return 3.8')+'</div><p>The belt weakness is recorded from the actual completion path, not inferred from an unused source. The shared marked puff remains a separate source priority in career-world drawings; its current mounted/action contexts still require review.</p></section><section><h2>Current complete contours at all 16 boundaries</h2><p>The first native edge attempt exposed clipping and remains preserved. The repaired production handler clamps only dragging margins to 144px left/right, 152px top and 128px bottom. All 160 recorded interior action drag positions are unchanged under both clamps; <a href="BOUNDARY_REPAIR_EQUIVALENCE_V2.json">the exact equivalence record</a> retains both production hashes. The action images keep their original pre-edge-repair source boundary. These 16 views use the current repaired source and actual corner drags with zero hits, progress and awards.</p><div class="grid">'
for v in edges:page+=fig('native_edges_v2/'+v['path'],v['path']+' — complete contour 4.6/5; inside geometry true')
page+='</div><details><summary>Retained rejected edge views</summary><div class="grid">'+fig('native_edges_v1/1280_hand0_corner0.webp','Original tight clamp cuts the coral glove at top-left — 4.0')+fig('native_edges_v1/1280_hand1_corner3.webp','Original tight clamp cuts the teal glove at bottom-right — 4.0')+'</div><a href="native_edges_v1/VISUAL_REJECTION.json">Exact failure and review scope</a></details></section><section><h2>All ordered frame boards and written action evaluations</h2>'
for a in actions:
    page+='<details><summary>'+a['mode']+' · '+str(a['width'])+' · '+('left' if a['hand']==0 else 'right')+' · sequence '+str(a['played_fixture_sequence_score'])+'/5</summary><p>'+a['evaluation']+'</p>'
    page+=fig('native_actions_v1/frame_'+str(a['full_native_contact_frame']).zfill(4)+'.webp','First accepted event, frame '+str(a['full_native_contact_frame']))
    for b in boards:
        if b['action']==a['action_index']:page+=fig('native_actions_v1/'+b['path'],'Every frame '+str(b['frame_indices'][0])+'–'+str(b['frame_indices'][-1])+' — direct ordered review')
    page+='</details>'
page+='</section><section><h2>Verification and acceptance still required</h2><p><a href="native_actions_v1/PROCESS_RECEIPT.json">Parser, inference, import, official Godot 4.7.2 analyzers and all-mode native capture</a> pass at the original action boundary. <a href="native_edges_v2/PROCESS_RECEIPT.json">Current repaired-source edge checks</a> pass and all 16 views are directly reviewed. The <a href="../day_one_pool_live_refinement_v2_20261001/full_ci_current_retry_v3/RECEIPT.json">new full suite</a> is pending; the earlier 81/82 result remains a retained failure.</p><p>'+review['qualification']+'</p><p>No master finding is closed. Hundreds of other individual job assets/actions and the comprehensive user-approved report remain unfinished.</p></section></main>'
payload={'actions':actions,'frames':capture['frames']}
page+='<script>const data='+json.dumps(payload,separators=(',',':'))+';const action=document.getElementById("action"),slider=document.getElementById("slider");data.actions.forEach((a,i)=>{const o=document.createElement("option");o.value=i;o.textContent=`${a.mode} · ${a.width} · ${a.hand===0?"left":"right"} · sequence ${a.played_fixture_sequence_score}/5`;action.append(o)});function show(){const f=data.frames[Number(slider.value)],a=data.actions[Number(action.value)];document.getElementById("frame").src="native_actions_v1/"+f.path;document.getElementById("frameLink").href="native_actions_v1/"+f.path;document.getElementById("detail").textContent=`Frame ${f.index} · ${f.seconds.toFixed(3)}s · actual progress ${f.progress} · effect alpha ${f.declared_draw_alpha.toFixed(3)} · ${f.width}×720`;document.getElementById("actionReview").textContent=a.evaluation}function choose(){const a=data.actions[Number(action.value)];slider.min=a.first_frame;slider.max=a.last_frame;slider.value=a.first_frame;show()}action.onchange=choose;slider.oninput=show;document.getElementById("previous").onclick=()=>{slider.value=Math.max(Number(slider.min),Number(slider.value)-1);show()};document.getElementById("next").onclick=()=>{slider.value=Math.min(Number(slider.max),Number(slider.value)+1);show()};document.getElementById("contact").onclick=()=>{slider.value=data.actions[Number(action.value)].full_native_contact_frame;show()};document.getElementById("end").onclick=()=>{slider.value=slider.max;show()};choose();</script></html>'
(f/'index.html').write_text(page,encoding='utf-8',newline='\n')

tools=f/'review_tools';tools.mkdir(exist_ok=True)
for p in [Path(__file__),r/'tmp/run_live_boxing_v1.py',r/'tmp/run_boxing_edges_v1.py',r/'tmp/run_boxing_edges_v2.py',r/'tmp/record_boxing_boundary_equivalence_v2.py']:
    shutil.copyfile(p,tools/p.name)
impact=r/'design/audit_impacts/day-two-boxing-live-refinement-v1-20261001.json';d=read(impact)
d['validation']=[{'command':'Parser/inference/import/official4.7.2 analyzers and actual20 local-handler actions','result':'PASS','evidence':'native_actions_v1/PROCESS_RECEIPT.json; source bound before edge repair'},
 {'command':'Current16 edge drags and exact160 interior drag equivalence','result':'PASS','evidence':'native_edges_v2/PROCESS_RECEIPT.json; BOUNDARY_REPAIR_EQUIVALENCE_V2.json'},
 {'command':'Individual prop artwork and complete-frame visual review within declared fixture scope','result':'PASS','evidence':'REVIEW.json; all1402 ordered frames,20 contacts,20 finals and16 current edges directly inspected. Prop art4.6; guard/imp/belt sequence priorities remain4.2/4.2/4.0; no whole-job acceptance.'},
 {'command':'Current325-source unmodified fullCI and ordinary route/device/child/owner acceptance','result':'PENDING','evidence':review['current_full_ci']['path']+'; earlier81/82 failure retained; external acceptance not obtained.'}]
d['acceptance_gaps']=review['qualification'];d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in f.rglob('*') if p.is_file()}|{'audit/findings/ACTIVE_FINDINGS_2026-08-13.md'});write(impact,d)
master=r/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8')
marker='Boxing reversible live refinement (2026-10-01): '
paragraph=marker+'[Current individual artwork and all20 native action requests](day_two_boxing_live_refinement_v1_20261001/index.html) bind two complete painted gloves at new reversible paths and reuse the exact existing clean puff in OperaBoxingSurface. Source/mounted/timed individual art4.6 and all16 current complete-contour edge views4.6 are bounded drafting opinions. All1402 ordered native frames on58 boards plus all20 contacts/finals directly reviewed; guide/jab fixture sequences4.6, guard/imp4.2, belt4.0. Incoming counter4.0, imp acting3.8, belt rendered contact/return3.8 and shared marked puff source2.5 remain priorities. Earlier clipping preserved; exact edge-only equivalence proves all160 interior action drags unchanged, while capture hashes retain their original boundary. Current325-file wholeCI is pending; earlier81/82 remains red. Ordinary routes, full job/training phases, device/child/owner/global acceptance and the comprehensive report remain open. [Impact](../design/audit_impacts/day-two-boxing-live-refinement-v1-20261001.json). No finding closure.\n\n'
assert marker not in s;s=s.replace('Boxing individual-glove refinement',paragraph+'Boxing individual-glove refinement',1);master.write_text(s,encoding='utf-8',newline='\n')
ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');s+='\n| `audit/day_two_boxing_live_refinement_v1_20261001/index.html` | 🟣 | `CANDIDATE`; reversible boxing-only painted gloves/clean-puff binding, individual art4.6, all16 current edge views4.6, 1402 native frames on58 ordered boards and20 contact/final pairs directly reviewed. Guide/jab sequences4.6; guard/imp4.2; belt4.0. Counter4.0, imp acting3.8, belt return3.8, shared marked-puff source2.5 remain priorities. Exact160 interior drag equivalence retains pre-edge action hashes. Full325-file CI pending; ordinary routes/full phases/device/child/owner/global acceptance open. |\n';ledger.write_text(s,encoding='utf-8',newline='\n')
findings=r/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text(encoding='utf-8');start=s.index('## MA-VIS-006');end=s.index('## MA-VIS-007',start);part=s[start:end];old='[Current review](../day_one_pool_live_refinement_v2_20261001/REVIEW.json). |';new=old[:-2]+' 2026-10-01 boxing continuation: reversible individual glove/puff artwork4.6 and16 current edge fits4.6 are recorded in [scoped review](../day_two_boxing_live_refinement_v1_20261001/REVIEW.json); all1402 ordered frames and20 contact/final pairs reviewed. Counter4.0, imp acting3.8 and belt completion return3.8 remain priorities. FullCI/ordinary routes/device/child/owner/global acceptance remain open; lifecycle unchanged. |';assert old in part;part=part.replace(old,new,1);s=s[:start]+part+s[end:];findings.write_text(s,encoding='utf-8',newline='\n')
entry=r/'audit/job_artwork_refinement_live/index.html';s=entry.read_text(encoding='utf-8');p='<p><a href="../day_two_boxing_live_refinement_v1_20261001/index.html">Current boxing: individually painted gloves and clean puff4.6; all20 actual action requests and16 repaired boundary views</a>. Counter, imp acting and belt contact/return remain named priorities; fullCI and comprehensive approval pending.</p>';s=s.replace('<p><a href="../../assets_src/imagegen/day2_boxing_single_gloves',p+'<p><a href="../../assets_src/imagegen/day2_boxing_single_gloves',1);entry.write_text(s,encoding='utf-8',newline='\n')
status=r/'audit/job_artwork_refinement_live/STATUS.json';d=read(status);d['current_boxing_live_refinement']={'status':review['status'],'report':f.relative_to(r).as_posix()+'/index.html','runtime_surface_sha256':review['current_runtime_surface_sha256'],'items':items,'priorities':priorities,'reviewed_frames':1402,'native_actions':20,'current_edge_views':16,'full_ci':'RUNNING_PENDING','ordinary_routes_and_full_phases':'PENDING','owner_approved':False};write(status,d)
for path in [r/'assets_src/imagegen/day2_boxing_single_gloves_v1_20261001/index.html',r/'audit/day_two_boxing_puff_reuse_v1_20261001/index.html']:
    s=path.read_text(encoding='utf-8');relative='../../../audit/day_two_boxing_live_refinement_v1_20261001/index.html' if 'assets_src' in path.parts else '../day_two_boxing_live_refinement_v1_20261001/index.html'
    note='<p class="notice">Historical review boundary retained below. <a href="'+relative+'">Subsequent reversible live binding and current action/edge review</a> now exist. Earlier source hashes, failures and unbound opinions retain their original scope.</p>'
    assert note not in s;s=s.replace('<main>','<main>'+note,1);path.write_text(s,encoding='utf-8',newline='\n')
lic=r/'ASSET_LICENSES.md';s=lic.read_text(encoding='utf-8')
for p in sorted(f.rglob('*')):
    if not p.is_file() or p.suffix.lower() not in ('.png','.webp'):continue
    rel=p.relative_to(r).as_posix()
    if '`'+rel+'`' not in s:s+=f'| `{rel}` | Mermaid Roshan existing/generated project artwork / Godot native capture | Existing source provenance; review-only evidence | Local project | Complete native handler frame or uniformly displayed whole-canvas inspection board; no generated motion or accepted cinematic delivery pixels; exact source hashes retained |\n'
lic.write_text(s,encoding='utf-8',newline='\n')
for prefix,record in [('assets_src/imagegen/day2_boxing_single_gloves_v1_20261001','day-two-boxing-single-gloves-v1-20261001'),('audit/day_two_boxing_puff_reuse_v1_20261001','day-two-boxing-puff-reuse-v1-20261001')]:
    p=r/'design/audit_impacts'/f'{record}.json';d=read(p);d['files']=sorted(set(d['files'])|{q.relative_to(r).as_posix() for q in (r/prefix).rglob('*') if q.is_file()});write(p,d)
print('Live report completed: all1402 ordered frames,20 full contacts/finals,16 current full-native edges; three individual4.6 artwork opinions; sequence priorities retained.')
