from pathlib import Path
import datetime,hashlib,json,shutil,re
r=Path(__file__).resolve().parents[1]
pool=r/'audit/day_one_pool_live_refinement_v2_20261001'
live=r/'audit/day_two_boxing_live_refinement_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
ci=read(pool/'full_ci_current_retry_v3/RECEIPT.json')
assert ci['status']=='PASS_UNMODIFIED_CURRENT_FULL_SUITE' and ci['overall_process_exit']==0
assert ci['source_unchanged'] and len(ci['source_checks'])==325 and len(ci['probe_results'])==82
assert all(x['process_exit']==0 for x in ci['probe_results'])
assert all(hashlib.sha256((r/x['path']).read_bytes()).hexdigest()==x['after_sha256'] for x in ci['source_checks'])
message=f"The current unmodified official-Godot4.7.2 full suite passes overall0 with all82 trusted probe processes0 in exact order and all325 literal production-source hashes unchanged. All{ci['raw_diagnostic_count']} raw engine diagnostics remain inspectable. Earlier81/82 full failures and the narrow unchanged picture-games retry are retained. This is local source-bound machine verification; ordinary full played routes, complete graphics/action coverage, hosted exact-head results, phone/child/owner acceptance and integration/release remain separate."
write(pool/'FULL_CI_STATUS_CURRENT.json',dict(status='PASS_CURRENT_FULL_RETRY_V3_82_OF_82_325_LITERAL_SOURCES',updated_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),full_receipt='full_ci_current_retry_v3/RECEIPT.json',earlier_failures=['full_ci_current_v1/RECEIPT.json','full_ci_current_retry_v2/RECEIPT.json'],explanation=message))
p=pool/'REVIEW.json';d=read(p);d['machine']=message+' Earlier focused and native-capture evidence retains its own recorded source boundary; presentation equivalence is declared separately.';write(p,d)
p=pool/'index.html';s=p.read_text();a=s.index('<section><h2>Current full-suite results and preserved failures</h2>');b=s.index('<section><h2>Machine evidence and acceptance still required</h2>',a);s=s[:a]+f'<section><h2>Current full-suite results and preserved failures</h2><p>{message}</p><a href="full_ci_current_retry_v3/RECEIPT.json">Current full suite:82/82,325 unchanged source hashes</a> · <a href="full_ci_current_v1/RECEIPT.json">Earlier pool timing failure</a> · <a href="full_ci_current_retry_v2/RECEIPT.json">Earlier full81/82 failure</a> · <a href="probe_mg2d_process_retry_v1/RECEIPT.json">Unchanged picture-games direct retry</a> · <a href="FULL_CI_STATUS_CURRENT.json">Current verification status</a></section>'+s[b:];p.write_text(s,encoding='utf-8',newline='\n')
p=live/'REVIEW.json';d=read(p);d['current_full_ci']=dict(status=ci['status'],path='../day_one_pool_live_refinement_v2_20261001/full_ci_current_retry_v3/RECEIPT.json',production_source_files=325,probe_processes=82,raw_diagnostics=ci['raw_diagnostic_count'],qualification=message);write(p,d)
p=live/'index.html';s=p.read_text();s=s.replace('The current full325-source suite is running.',message).replace('Current full325-source suite is running.',message).replace('The full 325-file validation run is pending.',message).replace('RUNNING_PENDING',ci['status']);s=re.sub(r'(<a href="[^"]+/full_ci_current_retry_v3/RECEIPT.json">)new full suite(</a>) is pending; the earlier 81/82 result remains a retained failure\.',r'\1current full suite\2 passes82/82 with325 literal source hashes unchanged; earlier81/82 failures and raw diagnostics remain inspectable. Local machine evidence does not grant visual or external acceptance.',s);p.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/job_artwork_refinement_live/STATUS.json';d=read(p);q=d['current_pool_refinement'];q['current_full_ci']=message;q['full_ci_status']=ci['status'];q['full_ci_in_progress']=False;d['current_boxing_live_refinement']['full_ci_status']=ci['status'];d['current_boxing_live_refinement']['full_ci_evidence']='audit/day_one_pool_live_refinement_v2_20261001/full_ci_current_retry_v3/RECEIPT.json';write(p,d)
p=r/'audit/job_artwork_refinement_live/index.html';s=p.read_text();a=s.index('<section><h2>Current-source reconciliation</h2>');b=s.index('<section><h2>Current replacement review</h2>',a);s=s[:a]+f'<section><h2>Current-source reconciliation</h2><p>{message}</p><a href="../day_one_pool_live_refinement_v2_20261001/full_ci_current_retry_v3/RECEIPT.json">Current local full-suite receipt</a></section>'+s[b:];p.write_text(s,encoding='utf-8',newline='\n')
for name in ['audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md']:
 p=r/name;s=p.read_text();s=s.replace('Current325-file wholeCI is pending; earlier81/82 remains red.','Current325-file wholeCI passes82/82 with unchanged literal hashes; earlier81/82 failures are preserved.').replace('Full325-file CI pending;','Current325-file fullCI passes82/82;').replace('The current literal321-file full retry passes pool after the synchronous-helper-only repair but remains red81/82 because picture-games exits127. Its exact unchanged direct retry exits0 with321 hashes matching; it does not waive the red fullsuite. New boxing presentation now requires a fresh wholeCI source snapshot.','The current unmodified full325-file retry passes82/82 with all literal source hashes unchanged; earlier321-file81/82 failure and exact direct retry remain inspectable. Local source-bound machine verification does not establish hosted, visual or external acceptance.');p.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=p.read_text();needle='candidate discovery and reference observations confer no new visible/action acceptance. |';assert needle in s;s=s.replace(needle,'candidate discovery and reference observations confer no new visible/action acceptance. Current full325-source retry now passes82/82 with all literal hashes unchanged and raw diagnostics retained; this source-bound machine result does not close the finding or external acceptance. |',1);p.write_text(s,encoding='utf-8',newline='\n')
for ident,folder in [('day-one-pool-live-refinement-v2-20261001',pool),('day-two-boxing-live-refinement-v1-20261001',live)]:
 p=r/'design/audit_impacts'/f'{ident}.json';d=read(p)
 if ident.startswith('day-two-boxing-live'):
  old='Current325-source unmodified fullCI and ordinary route/device/child/owner acceptance';d['validation']=[x for x in d['validation'] if x['command']!=old];d['validation']+=[dict(command='Current325-source unmodified official4.7.2 fullCI',result='PASS',evidence='audit/day_one_pool_live_refinement_v2_20261001/full_ci_current_retry_v3/RECEIPT.json; all82 processes0 and325 literal hashes MATCH; no external acceptance.'),dict(command='Ordinary complete played routes/device/child/owner/all-job acceptance',result='PENDING',evidence='REVIEW.json; artwork/sequence and fixture limitations remain explicit.')]
  d['acceptance_gaps']=d['acceptance_gaps'].replace('FullCI/','')
 d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in folder.rglob('*') if p.is_file()});write(p,d)
shutil.copyfile(Path(__file__),live/'review_tools'/Path(__file__).name)
print(message)
