from pathlib import Path
import json,hashlib,shutil,subprocess,sys,datetime,html
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
def read(p):return json.loads((r/p).read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def rel(p):return p.relative_to(r).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat();geo='assets_src/imagegen/geologist_painted_rebuild_v1_20261001';prefix=geo+'/washing_pan/attempt_02'
record=read(prefix+'/GENERATION_RECORD.json')
review=dict(id='GEO-PAINT-WASHING_PAN-02',path=record['native_path'],sha256=record['native_sha256'],dimensions=record['native_dimensions'],source_score=4.6,status='SELECTED_SOURCE_ONLY_MOUNT_GEOMETRY_PENDING',evaluation='Confident warm-plum outer and inner contours, broad matte lavender bands and calmer aqua water improve the prior fine-textured pan. Cream reflections are grouped and the shallow attached sidewall remains readable. Full opaque silhouette is complete with margins. Measured opaque width1517/height737 gives2.06 aspect, not the requested1.75: preserve actual aspect when mounting. Native invitation squashing, rim/grain containment, flat mineral payoff and connected hands remain below target.',qualification='Direct generated native, both white/aqua alpha displays and1024x585 uniform whole-canvas derivative inspected. Source-only agent drafting score; no runtime replacement or complete-action/device/child/owner acceptance.',source_record=prefix+'/GENERATION_RECORD.json',native_direct_review=True,neutral_previews_direct_review=[prefix+'/audit_white.png',prefix+'/audit_aqua.png'],mounted_score=None,complete_action_score=None,owner_approval=None)
write(r/(prefix+'/SOURCE_REVIEW.json'),review)
d=read(geo+'/REVIEW_V2.json');d['previous_review']=geo+'/REVIEW_V2.json';d['reviewed_utc']=now;d['items'].append(review);tech=read(prefix+'/whole_canvas_1024.json');tech.update(source_score=4.6,status='TECHNICAL_DERIVATIVE_UNBOUND',evaluation=review['evaluation']);d['technical_derivatives'].append(tech);d['native_outputs_directly_reviewed']=14;d['neutral_native_displays_directly_reviewed']=26;d['technical_derivatives_directly_reviewed']=9;d['native_context_reports'].append('audit/job_pan_painted_mount_v2_20261001/index.html');d['acceptance_gaps'].append('New-pan invitation aspect, in-bowl grain/mineral containment and inherited actor contact remain priorities');write(r/(geo+'/REVIEW_V3.json'),d)
native=read(geo+'/GENERATED_NATIVE_REGISTER_V2.json');native['previous_register']=geo+'/GENERATED_NATIVE_REGISTER_V2.json';native['status']='FOURTEEN_NATIVE_GENERATIONS_PRESERVED';native['records'].append(record);write(r/(geo+'/GENERATED_NATIVE_REGISTER_V3.json'),native)
out=r/'audit/job_pan_painted_mount_v2_20261001';archive=out/'native_views';archive.mkdir();temp=r/'tmp/pan_painted_mount_v107/native_views';receipt=read(rel(temp/'CAPTURE_RECEIPT.json'));assert len(receipt['views'])==18;shutil.copyfile(temp/'CAPTURE_RECEIPT.json',archive/'CAPTURE_RECEIPT.json')
views=[];licenses=[];e=html.escape
qualification='Exact unmodified native Godot4.7.2 Mobile desktop capture directly inspected. Isolated PAN fixture, actual viewport approach and three inherited reversals; no completed ordinary panning job, career/training/story route, device, child or owner acceptance.'
for v in receipt['views']:
 p=temp/v['path'];assert sha(p)==v['sha256'];shutil.copyfile(p,archive/v['path']);q=dict(v);paint=v['variant']=='painted_staging';new=v['variant']!='original';invite=v['state']=='invitation';partial='partial' in v['state']
 scores=dict(object_finish=4.6 if new and not invite else 4.4 if paint else 3.9 if invite else 3.5,object_semantics=4.4 if paint or not invite else 3.0,object_geometry=4.0 if paint and invite else 4.4 if new and not invite else None,scene_style=4.3 if paint else 2.8,layout=4.2 if paint else 3.0,water_containment=None if invite else 4.1 if new else 4.3,mineral_finish=3.8 if partial else None,mineral_containment=3.4 if partial and new else None,actor_work_contact=None if invite else 2.7,complete_action=None)
 if invite:
  text='Painted staging finally shows the washing pan, but the wide oval is squashed into a near-circle by the square invitation box. It floats without shelf or hand support; geometry4.0 remains a priority.' if paint else 'Invitation still shows a layered rock, including the literal painted-rock substitution. Its medium improves in the literal lane but it remains the wrong cue for panning; semantic3.0. New pan pixels are not present here.'
 else:
  text=('New pan has stronger plum contours, calmer broad aqua values and a clearer lavender sidewall; isolated visible finish4.6. Its2.06 native aspect is stretched by the inherited work rectangle; geometry4.4.' if new else 'Current procedural pan remains a flat set of thick-outlined ellipses, finish3.5.')+' Lowest grains touch the front rim instead of remaining clearly within water; new-pan containment4.1. '+('After three real reversals the mineral still uses a flat outlined pentagon and overlaps the new front rim, finish3.8/containment3.4. ' if partial else '')+'Roshan remains distant with no connected hand contact,2.7. Painted room/work material helps coherence but slab aspect and complete action still require repair.'
 q.update(archive_path=rel(archive/v['path']),direct_native_review=True,reviewed_utc=now,scores=scores,evaluation=text,qualification=qualification,production_binding_changed=False,owner_acceptance=None,priority_dimensions=[k for k,value in scores.items() if value is not None and value<=4.5]);views.append(q)
 licenses.append('| `'+rel(archive/v['path'])+'` | Mermaid Roshan native Godot4.7.2 Mobile project capture | Project review evidence; existing source licenses retained | `audit/job_pan_painted_mount_v2_20261001/PROFILE.json` | Unmodified lossless review-only capture; no runtime/owner/action acceptance. |')
write(out/'REVIEW.json',dict(schema='reef.individual-native-graphics-review.v1',status='18_OF18_NATIVE_VIEWS_DIRECTLY_REVIEWED_OPEN_CONTEXT_PRIORITIES',reviewed_utc=now,native_views=18,directly_reviewed=18,process_receipt=rel(out/'PROCESS_RECEIPT.json'),qualification=qualification,views=views))
cards=''.join('<article id="'+e(q['id'])+'"><h2>'+e(q['id'])+'</h2><a href="native_views/'+e(q['path'])+'"><img loading="lazy" src="native_views/'+e(q['path'])+'" alt="'+e(q['id'])+'"></a><p>'+e(q['evaluation'])+'</p><pre>'+e(json.dumps(q['scores'],indent=2))+'</pre><p>'+e(qualification)+'</p><code>'+q['sha256']+'</code></article>' for q in views)
(out/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painted pan revision2</title><style>body{background:#eef2fa;color:#27304b;font:17px/1.5 system-ui}main{max-width:1380px;margin:auto}article,header{background:white;border-radius:14px;padding:20px;margin:24px}img{width:100%}pre{white-space:pre-wrap}code{overflow-wrap:anywhere}</style><main><header><h1>Painted pan revision2 — every18 native view evaluated</h1><p>Source finish4.6 and isolated visible pan finish4.6 are separate from invitation geometry4.0, work geometry4.4, new-rim containment4.1/mineral3.4 and actor contact2.7. These are continued priorities. <a href="REVIEW.json">Complete individual written evaluations and exact hashes</a>.</p></header>'+cards+'</main></html>',encoding='utf-8',newline='\n')
license_path=r/'ASSET_LICENSES.md'
with license_path.open('a',encoding='utf-8',newline='\n') as stream:stream.write('\n'+'\n'.join(licenses)+'\n')
old=r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v14.py';body=old.read_text().replace('build_current_job_item_register_v14.py','build_current_job_item_register_v15.py').replace("geo=read(geo_prefix+'/REVIEW_V2.json')","geo=read(geo_prefix+'/REVIEW_V3.json')").replace('13 generated originals,24 neutral displays and8 technical derivatives','14 generated originals,26 neutral displays and9 technical derivatives');new=r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v15.py';new.write_text(body,encoding='utf-8',newline='\n');subprocess.run([sys.executable,'-X','utf8','-B',str(new)],cwd=r,check=True)
counts=read('audit/job_artwork_refinement_live/ALL_ITEMS.json')['counts'];assert counts['registered_items']==1555 and counts['unique_source_files']==1184
for f in ['audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html']:
 p=r/f;s=p.read_text();start=s.index('<section id="geode-embedded-owner-correction">');end=s.index('</section>',start)+len('</section>');block=s[start:end].replace('All202 native comparison','All220 native comparison').replace('1553 items/1182 unique','1555 items/1184 unique');block=block.replace('</section>','<p><a href="../job_pan_painted_mount_v2_20261001/index.html">All18 new-pan views</a>: source/visible finish4.6; invitation4.0, work geometry4.4, grain containment4.1/mineral containment3.4 and contact2.7 stay priorities.</p></section>');p.write_text(s[:start]+block+s[end:],encoding='utf-8',newline='\n')
p=r/(geo+'/index.html');s=p.read_text().replace('13 native ImageGen originals,24 neutral alpha displays and8 whole-canvas','14 native ImageGen originals,26 neutral alpha displays and9 whole-canvas').replace('href="REVIEW_V2.json">Current written','href="REVIEW_V3.json">Current written');s=s.replace('</main>','<article id="'+review['id']+'"><h2>'+review['id']+' —4.6/5 source</h2><img src="washing_pan/attempt_02/audit_aqua.png" alt="Refined painted washing pan"><p>'+e(review['evaluation'])+'</p><p><a href="../../../audit/job_pan_painted_mount_v2_20261001/index.html">Every18 new native pan context and individual score</a></p></article></main>');p.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text();pos=s.index('Geode embedded-crystal correction');s=s[:pos]+'Pan continuation (2026-10-01): [source revision2 and all18 native views](job_pan_painted_mount_v2_20261001/index.html) directly reviewed: broad matte painted finish4.6 source/isolated visible object; square invitation distortion4.0, work geometry4.4, new-rim containment4.1/mineral containment3.4 and connected-hand2.7 remain priorities. Current known register1555 entries/1184 sources/579 inclusive priorities/388 unassigned; total220 native comparisons individually scored.14 generated geology natives/26 neutral displays/9 whole-canvas derivatives preserved. No completed-job, device/child/owner or final report acceptance.\n\n'+s[pos:];p.write_text(s,encoding='utf-8',newline='\n')
p=r/'design/05_DOC_LEDGER.md';s=p.read_text();s=s.replace('`CANDIDATE`;13 native ImageGen painted originals,24 neutral alpha displays and8 whole-canvas','`CANDIDATE`;14 native ImageGen painted originals,26 neutral alpha displays and9 whole-canvas').replace('All202 teacher/geology native comparisons individually scored.','All220 teacher/geology/pan native comparisons individually scored.');s+='\n| `audit/job_pan_painted_mount_v2_20261001/index.html` | 🟣 | `CANDIDATE`; all18 native source/literal/painted-room PAN views directly inspected. New source/isolated visible finish4.6; invitation geometry4.0, work geometry4.4, grain/rim4.1 and mineral/rim3.4/contact2.7 remain priorities. Actual partial inherited input; full ordinary route/device/child/owner approval pending. |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/geology_regression_gate_v105.json'),r/'audit/job_review_v2_20261001/geology_supplement_gates_v1/REGRESSION_GATE_TOOL_RECEIPT.json');shutil.copyfile(__file__,out/'executed_record_pan_review_v108.py')
impact=r/'design/audit_impacts/job-geology-painted-rebuild-20261001.json';d=read(rel(impact));d['files']=sorted(set(d['files'])|{rel(p) for prefix in [geo,'audit/job_pan_painted_mount_v2_20261001','audit/job_review_v2_20261001/geology_supplement_gates_v1'] for p in (r/prefix).rglob('*') if p.is_file()}|{'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v15.py','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v15.py'});d['validation'].extend([dict(command='Direct review14 native originals/26 neutral alpha displays/9 uniform derivatives and220 native context images',result='PASS',evidence=geo+'/REVIEW_V3.json; audit/job_pan_painted_mount_v2_20261001/REVIEW.json'),dict(command='python -X utf8 -B tools/audit_game_2d.py --regression-gate',result='PASS',evidence='audit/job_review_v2_20261001/geology_supplement_gates_v1/REGRESSION_GATE_TOOL_RECEIPT.json; NO_REGRESSION, strict remains UNSATISFIED')]);write(impact,d)
allowed=r/'tmp/v2_preview_allowed.json';paths=set(json.loads(allowed.read_text()));paths.update(rel(p) for prefix in [geo,'audit/job_pan_painted_mount_v2_20261001'] for p in (r/prefix).rglob('*') if p.is_file());write(allowed,sorted(paths))
print('Current register',counts,'; all220 native context images directly reviewed.')
