from pathlib import Path
import json,hashlib,datetime,shutil,subprocess,sys,html
from PIL import Image
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');root=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001';grain=root/'pan_grain/attempt_01';impact=b/'design/audit_impacts/job-pan-painted-placement-20261001.json'
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
review=json.loads((root/'REVIEW_V3.json').read_text());source=json.loads((grain/'SOURCE_REVIEW.json').read_text());review['previous_review']=rel(root/'REVIEW_V3.json');review['reviewed_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();review['baseline']='dea7425a1e09752bd5102fc445bd2f84b96c0010';review['native_outputs_directly_reviewed']=15;review['neutral_native_displays_directly_reviewed']=28;review['technical_derivatives_directly_reviewed']=10
review['qualification']='All15 original ImageGen native outputs,28 neutral fields and10 whole-canvas derivatives directly inspected. Current source-only opinions, previous rejected drafts and under-resolution1672x941 room remain separately qualified. All source pixels preserved; no production binding, complete route, device/child/owner or final-report acceptance.'
review['items'].append(dict(id='GEO-PAINT-PAN-GRAIN-01',path=rel(grain/'native.png'),sha256=sha(grain/'native.png'),dimensions=list(Image.open(grain/'native.png').size),source_score=4.6,status='SELECTED_SOURCE_ONLY_UNBOUND',evaluation=source['evaluation'],qualification=source['qualification'],source_record=rel(grain/'GENERATION_RECORD.json'),native_direct_review=True,neutral_previews_direct_review=source['neutral_previews_direct_review'],mounted_score=None,complete_action_score=None,owner_approval=None))
review['technical_derivatives'].append(dict(path=rel(grain/'whole_canvas_1024.png'),sha256=sha(grain/'whole_canvas_1024.png'),dimensions=[1024,683],source_path=rel(grain/'native.png'),source_sha256=sha(grain/'native.png'),method='Uniform whole-canvas RGBA normalization only',alpha_preserved=True,pixel_repair=False,qualification='Directly inspected complete-canvas technical derivative4.6; no production binding or complete action pass.',source_score=4.6,status='SELECTED_TECHNICAL_REVIEW_DERIVATIVE_UNBOUND',evaluation='Complete authored grain and alpha preserved. Native15px fixture material directly inspected separately; source score is not complete-action acceptance.'))
review['native_context_reports'].append('audit/job_pan_painted_mount_v3_20261001/index.html');write(root/'REVIEW_V4.json',review)
register=dict(status='15_NATIVE_GENERATED_SOURCE_FILES_PRESERVED',sources=[dict(path=x['path'],sha256=x['sha256'],dimensions=x['dimensions'],score=x['source_score'],status=x['status']) for x in review['items']],qualification=review['qualification']);write(root/'GENERATED_NATIVE_REGISTER_V4.json',register)
banner='<section id="pan-grain-current-v4"><h2>Current source review:15 originals,28 neutral fields,10 derivatives</h2><p>Current15th source is one matte painted honey-ochre pan grain4.6, replacing the named flat dot3.8. Earlier images and dated opinions remain preserved below. Pan/slab/crystal sources are reused. Source scores and isolated native object improvements do not pass connected action or the final owner report.</p><p><a href="REVIEW_V4.json">Current individual source record</a> · <a href="../../../audit/job_pan_painted_mount_v3_20261001/index.html">Every new pan placement view and retained failures</a></p><img src="pan_grain/attempt_01/audit_aqua.png" alt="New painted pan grain" style="max-width:700px;width:100%;height:auto"><p><a href="pan_grain/attempt_01/native.png">Unchanged generated native</a> · <a href="pan_grain/attempt_01/audit_white.png">White alpha inspection</a> · <a href="pan_grain/attempt_01/PROMPT.txt">Exact ImageGen prompt</a> · <a href="pan_grain/attempt_01/GENERATION_RECORD.json">Provenance</a></p></section>'
p=root/'index.html';s=p.read_text();assert 'pan-grain-current-v4' not in s;i=s.index('<h1');end=s.index('</h1>',i)+5;s=s[:end]+banner+s[end:];p.write_text(s,encoding='utf-8')
license=b/'ASSET_LICENSES.md';existing=license.read_text()
with license.open('a',encoding='utf-8',newline='\n') as f:
 for name in ['native.png','audit_white.png','audit_aqua.png','whole_canvas_1024.png']:
  p=grain/name
  if rel(p) not in existing:f.write('\n| `'+rel(p)+'` | Codex built-in ImageGen2026-10-01; owner-authorized named flat-grain repair; project pan style reference | OpenAI generated output terms; original game art | https://openai.com/policies/terms-of-use/ | '+('Unmodified provider-native RGBA' if name=='native.png' else 'Neutral audit backdrop only; no source repair' if name.startswith('audit_') else 'Uniform entire-canvas1024 normalization only; authored alpha retained')+'; source SHA256 '+sha(grain/'native.png')+'; file SHA256 '+sha(p)+' |\n')
source_builder=b/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v15.py';new_builder=source_builder.with_name('build_current_job_item_register_v16.py');assert not new_builder.exists();code=source_builder.read_text().replace('build_current_job_item_register_v15.py','build_current_job_item_register_v16.py').replace("geo_prefix+'/REVIEW_V3.json'","geo_prefix+'/REVIEW_V4.json'").replace('14 generated originals,26 neutral displays and9 technical derivatives','15 generated originals,28 neutral displays and10 technical derivatives');new_builder.write_text(code,encoding='utf-8');shutil.copyfile(__file__,grain/'executed_update_geology_source_library_v121.py')
d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in root.rglob('*') if p.is_file()}|{rel(new_builder),'ASSET_LICENSES.md','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/ALL_ITEMS.html','audit/job_artwork_refinement_live/STATUS.json','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v16.py'});write(impact,d)
r=subprocess.run([sys.executable,'-X','utf8','-B',str(new_builder)],cwd=b,capture_output=True);(b/'tmp/build_register_v16.stdout.log').write_bytes(r.stdout);(b/'tmp/build_register_v16.stderr.log').write_bytes(r.stderr);assert r.returncode==0,r.stderr.decode(errors='replace')[-800:]
d=json.loads((b/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text());print(json.dumps(d['counts']))
