from pathlib import Path
import datetime, hashlib, html, json, re, shutil, subprocess

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_training_shared_source_review_v1_20261002';assert not f.exists();f.mkdir()
live=b/'audit/job_artwork_refinement_live';read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
baseline=subprocess.check_output(['git','rev-parse','HEAD'],cwd=b,text=True).strip()
source_rows=[('D1V2-0048','assets/castle/training/training_grotto_backdrop.png',4.6,'The broad cool aqua central opening and lavender/cream rock pillars frame a clear play area. Sparse floor bands remain high-key and the shell forms are rounded, with restrained navy/plum contour. The baked wand rack is a decorative corner feature, not a scored interactive target. Source style4.6; the2048x1024 runtime file is a whole-canvas resized derivative, so its dimensions do not prove native2048-square coverage. Actual Mobile training presentation and 3D migration remain separate.','CombatTutorial TRAINING_BACKDROP_PATH and _add_training_backdrop; reads this picture through a TextureRect. This is CombatTutorial background art, not Geologist Opera training.'),('D1V2-0049','assets/castle/training/verb_chip_hold.png',4.6,'The simple rounded lavender chip has a clean dark-purple border, broad painted value bands and a warm yellow-to-pink partial ring. Its large grouped marks read as a compact interface cue. This symbolic UI function can use restrained graphic simplification without replacing an illustrated room or character. The still does not by itself demonstrate sustained touch; hold timing/hand/voice require actual encounter review.','EncounterGestureGuide2D.HOLD_CHIP_PATH, _ready and _draw;82px noninteractive cue when mode==hold.'),('D1V2-0050','assets/castle/training/verb_chip_tap.png',4.6,'A single large cream star within the warm pink round chip has a clear purple outer contour and calm highlights. Its silhouette is readable as a small interface symbol and fits the pastel toy-playset palette. The static star does not by itself teach a tap; the actual pointer motion and verbal cue are separate evidence.','EncounterGestureGuide2D.TAP_CHIP_PATH, _ready and _draw;82px noninteractive cue for non-hold modes.')]
components=[('TRAINING-COMP-01','Left shell pillar',4.6,'Broad lavender stone, cream shell capital and rounded base remain clear against the aqua center.'),('TRAINING-COMP-02','Right shell pillar',4.6,'The matching cream/lavender support preserves rounded stone and leaves the center unobstructed.'),('TRAINING-COMP-03','Left purple hanging pennant',4.6,'One broad cool purple leaf-like form provides sparse framing, without high-contrast texture.'),('TRAINING-COMP-04','Left green hanging pennant',4.6,'The restrained green/aqua hanging form remains subordinate to the clear training area.'),('TRAINING-COMP-05','Right green hanging pennant',4.6,'The broad leaf banner and simple diagonal painted bands repeat the room palette calmly.'),('TRAINING-COMP-06','Right purple hanging pennant',4.6,'The short purple companion banner frames the right pillar without filling the center.'),('TRAINING-COMP-07','Pink wand in corner rack',4.5,'The pink ring-ended wand is decorative baked scenery with a small visible loop. The source reaches the floor provisionally; do not infer target readability from an enlarged source.'),('TRAINING-COMP-08','Lavender wand in corner rack',4.5,'The separate lavender loop and warm handle fit the surrounding palette. It remains one baked decorative object and has no individual interactive evidence.'),('TRAINING-COMP-09','Aqua wand in corner rack',4.5,'The cyan loop-ended wand provides a third simple color distinction. Corner rack detail should stay subordinate to the active encounter, which is unreviewed here.'),('TRAINING-COMP-10','Open central training field',4.6,'A broad light aqua value field gives clear potential figure-ground separation. No new target or job mechanic is inferred from this still.'),('TRAINING-COMP-11','Pale lavender floor',4.6,'Calm broad floor bands provide simple support and avoid dense repeated detail in the play area.')]
write(f/'REVIEW.json',dict(status='THREE_EXISTING_SOURCES_AND11_SOURCE_COMPONENTS_REVIEWED',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseline=baseline,sources=[dict(id=i,path=p,sha256=sha(b/p),score=s,evaluation=e,binding_trace=t,direct_review=True,runtime_score=None,complete_action_score=None,owner_acceptance=None) for i,p,s,e,t in source_rows],individual_components=[dict(id=i,label=l,score=s,evaluation=e,direct_review=True,runtime_score=None,owner_acceptance=None) for i,l,s,e in components],source_scripts=[dict(path=p,sha256=sha(b/p)) for p in ['scripts/combat_tutorial.gd','scripts/encounter_gesture_guide_2d.gd']],qualification='Direct existing-source review and literal binding trace; no game rendering/capture performed. Shared cues and CombatTutorial background are dependencies, not an invented Geologist lesson. All source/actual-action/device/child/owner/strict2D acceptance remains separate. No original edited or art generated.'))
figures=''.join('<article><h2>'+html.escape(i)+' · '+str(s)+'/5 source</h2><figure><img src="../../'+p+'" alt="'+html.escape(p)+'"><figcaption>'+html.escape(p)+'</figcaption></figure><p>'+html.escape(e)+'</p><p><strong>Binding:</strong> '+html.escape(t)+'</p></article>' for i,p,s,e,t in source_rows)
details=''.join('<article><h3>'+html.escape(l)+' · '+str(s)+'/5 source</h3><p>'+html.escape(e)+'</p></article>' for i,l,s,e in components)
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shared training artwork · individual source review</title><style>body{margin:0;background:#edf3f8;color:#26354c;font:17px/1.6 system-ui}main{max-width:1150px;margin:auto;padding:24px}article{background:white;border:1px solid #b7c4d6;border-radius:16px;padding:20px;margin:20px 0}figure{margin:0;background:#e3edf6;border-radius:12px}img{display:block;max-width:100%;height:auto;max-height:650px;margin:auto}figcaption{overflow-wrap:anywhere;padding:10px}a{color:#41499b}</style><main><h1>Shared training artwork: three missing source evaluations</h1><p>The existing CombatTutorial grotto and shared encounter tap/hold cues now have individual written source opinions. This is a source-and-binding trace, not an actual played training audit or a Geologist lesson. No production pixels or frozen game files changed.</p><p><a href="REVIEW.json">Complete fourteen individual opinions and source hashes</a> · <a href="../job_artwork_refinement_live/all_items.html">Current individual register</a></p>'+figures+'<h2>Eleven separately evaluated background components</h2>'+details+'<p>Current source style4.6 does not grant complete training/action/device/child/owner acceptance. Existing native background coverage and measured3D debt remain separate.</p></main></html>'
page=''.join(re.sub(r'(?<=[a-z])(?=\d)',' ',x) if i%2==0 else x for i,x in enumerate(re.split(r'(<[^>]*>)',page)));(f/'index.html').write_text(page,encoding='utf-8',newline='\n');shutil.copyfile(__file__,f/Path(__file__).name)
d=read(live/'ALL_ITEMS.json');assert d['counts']['registered_items']==1721 and d['counts']['unreviewed_current_source']==388;assert not (live/'ALL_ITEMS_V29.json').exists();shutil.copyfile(live/'ALL_ITEMS.json',live/'ALL_ITEMS_V29.json');(live/'all_items_V29.html').write_text((live/'all_items.html').read_text(encoding='utf-8').replace('ALL_ITEMS.json','ALL_ITEMS_V29.json'),encoding='utf-8',newline='\n')
for i,p,s,e,t in source_rows:
 x=next(x for x in d['items'] if x['id']==i);assert x['path']==p and x['current_source_score'] is None and x['current_checkout_sha256']==sha(b/p);x['current_source_score']=s;x['evaluation']=e;x['priority']=s<=4.5;x['source_qualification']='Fresh direct2026-10-02 literal current source review; '+t+' No actual played, complete-action, device/child/owner acceptance.';x['original_reports']=sorted(set(x['original_reports'])|{f.relative_to(b).as_posix()+'/index.html'});x['native_reference_observations'].append(dict(path=f.relative_to(b).as_posix()+'/REVIEW.json',method='Direct current source inspection, literal binding trace',score=s,sha256=sha(b/p)))
gpath='assets_src/imagegen/geologist_grotto_native2k_v1_20261002/attempt_01/native.png';gsha=sha(b/gpath);assert not any(x['path']==gpath and x['kind']=='source' for x in d['items'])
d['items'].append(dict(id='GRO-NATIVE2K-001',aliases=['GRO-NATIVE2K-001'],kind='source',path=gpath,region=None,earlier_sha256=gsha,historical_source_score=None,current_source_score=4.5,evaluation='Whole native1254-square source style4.5 provisional, ceiling4.4. Requested2048-square resolution failed: this complete returned image is reference-only and no runtime background is bound.',refinement='Preserve the exact native and measured failed dimension gate. A later genuine native/tile solution must satisfy2048-square coverage and object continuity; do not count padding/upscale as native detail.',families=['geologist','unbound native-resolution attempt'],original_reports=['assets_src/imagegen/geologist_grotto_native2k_v1_20261002/index.html'],source_qualification='Direct full returned native inspection and nine source/component opinions; resolution gate failed, no actual runtime score.',preview_path=gpath,native_reference_observations=[],current_checkout_sha256=gsha,current_byte_status='EXACT_EARLIER_BYTES',source_dimensions=[1254,1254],priority=True,protected_original=False,current_mounted_score=None,current_complete_action_score=None,image_path=gpath,image_scope='Returned native, reference-only1254-square; no native2K or binding claim'))
d['created_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();d['scope']=d['scope'].replace('V29','V30')+' V30 adds three directly inspected shared-training source opinions and one failed-native-resolution grotto source; no live/global acceptance.';c=d['counts'];c['unique_source_files']+=1;c['registered_items']+=1;c['exact_earlier_bytes']+=1;c['inclusive_current_source_priorities']+=1;c['unreviewed_current_source']-=3;assert c['registered_items']==1722 and c['unreviewed_current_source']==385;write(live/'ALL_ITEMS.json',d)
note='Source/reuse continuation (2026-10-02): [three shared training sources and eleven individual background components](job_training_shared_source_review_v1_20261002/index.html) directly inspected with literal caller traces; this is not Geologist Opera training or complete-action acceptance. [Same painted open-geode crest/goal reuse](../assets_src/reuse/geology_geode_emblems_v1_20261002/index.html) reaches isolated50px4.5/80–220px4.6, still unbound. [New grotto native-resolution attempt](../assets_src/imagegen/geologist_grotto_native2k_v1_20261002/index.html) returned1254-square despite2048-square request; source4.5/ceiling4.4, reference-only and failed coverage explicitly preserved. V30 known register1722 entries/1245 source files/676 inclusive source priorities/385 unassigned; these are known source opinions, not676 weak live objects or exhaustive runtime acceptance. Existing room2.8/contact2.7/normal celebration3.2 remain open; no finding lifecycle, owner, integration or release acceptance.'
note=re.sub(r'(?<=[a-z])(?=\d)',' ',note)
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
 p=b/rel;s=p.read_text(encoding='utf-8');n=note.replace('](job_training','](../job_training').replace('](../assets_src/','](../../assets_src/') if '/findings/' in rel else note;s=s.replace('\n\n','\n\n'+n+'\n\n',1);p.write_text(s,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s=s.replace('V29 known register1721','V30 known register1722');p.write_text(s,encoding='utf-8',newline='\n')
p=live/'index.html';s=p.read_text(encoding='utf-8');needle='<body>';assert needle in s;s=s.replace(needle,needle+'<aside style="padding:18px;background:#fff2d4"><strong>Current source/reuse supplement:</strong> <a href="../job_training_shared_source_review_v1_20261002/index.html">Three shared training sources</a> · <a href="../../assets_src/reuse/geology_geode_emblems_v1_20261002/index.html">Unbound painted geode crest/goal</a> · <a href="../../assets_src/imagegen/geologist_grotto_native2k_v1_20261002/index.html">Grotto resolution failure preserved</a>. V30:1722 entries,676 inclusive source priorities,385 unassigned. Actual mounted/action/device/owner acceptance remains separate.</aside>',1);p.write_text(s,encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-training-shared-source-review-20261002.json';write(ip,dict(id='job-training-shared-source-review-20261002',scope='Complete three missing shared training-source opinions with explicit caller trace, eleven individual background details; V30 union register adds a separately failed native-resolution source and current source/reuse links.',baseline=baseline,rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-LAY-07','DL-ASSET-01','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-QA-01','DL-QA-02','DL-QA-03','DL-QA-06'],findings=['MA-VIS-006','MA-PLAY-004','MA-OPERA-012'],files=sorted({p.relative_to(b).as_posix() for folder in [f,live] for p in folder.rglob('*') if p.is_file()}|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md'}),validation=[dict(command='Direct native/source and literal caller review',result='PASS',evidence=f.relative_to(b).as_posix()+'/REVIEW.json;3 sources and11 components; no active gameplay claim.'),dict(command='Register V30 counts and exact source hashes',result='PASS',evidence='audit/job_artwork_refinement_live/ALL_ITEMS.json;1722 known entries,676 inclusive source priorities,385 unassigned, originals untouched.'),dict(command='Rendered register/browser layout and authority/development gates',result='PENDING',evidence='Latest source supplement not yet browser/gate verified.')],acceptance_gaps='Source/caller review only. Actual training, complete action, full live-use coverage, native backdrop resolution, strict2D/device/child/owner and all-job acceptance remain open. No production change or lifecycle closure.'))
allow=b/'tmp/v2_preview_allowed.json';v=read(allow);write(allow,sorted(set(v)|{p.relative_to(b).as_posix() for folder in [f,live] for p in folder.rglob('*') if p.is_file()}|{p for i,p,s,e,t in source_rows}))
print('V30:1722 known entries,1245 source files,676 inclusive source priorities,385 unassigned;14 source/component opinions, no production edit.',flush=True)
