from pathlib import Path
import json,hashlib,shutil,subprocess
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');root=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001';base='edbf2a60e4a73ca149ee53b7f8d01990afd32198';assert subprocess.run(['git','rev-parse','HEAD'],cwd=b,capture_output=True,check=True).stdout.decode().strip()==base
refs=[root/'closed_geode/attempt_01/native.png',root/'open_geode/attempt_02/native.png']
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
common='''Use case: illustration-story. Generate ONE isolated painted geode opening-state game sprite, with genuine RGBA transparency; not a scene, diagram, sheet, caption or cinematic frame.
IMAGE_1 is the selected CLOSED geode identity: preserve that round lavender outer rock, broad brush-painted facets, aqua lower band, plum outer contour and central vertical seam. IMAGE_2 is the selected FULLY OPEN identity: preserve its thick cream inner rim and concave lavender cavities, with crystals rooted inside both cavities. Left cavity has a tall cyan crystal, a lilac crystal and a small cyan crystal; right has a tall lilac crystal, a medium cyan crystal and a small cyan crystal. All crystals are permanent joined growths inside the stone, never loose loot, separate prizes or falling objects. These are endpoint identity/material references only; create a new truthful intermediate opening pose, not a pixel blend or collage of them.
The left and right shell halves belong to ONE geode, with matching outer silhouette and mating curved seam. The left half remains on the left and the right half on the right. The rock opens by the two halves parting and turning outward a little so the interior is gradually revealed. Preserve their thickness and volume, not two flat wafer stickers. Keep all exposed crystals embedded in the concave cavity walls. Hidden crystal portions must stay occluded by real stone, never relocate outward or vanish from a visible cavity.
Style: polished broad hand-painted 2D picture-book toy geology, matte lavender/aqua/cream values and strong rounded plum contour. Match both references exactly in visual family. No flat vector substitution, photographic gemstone microtexture, fine speckle, glossy3D render, new mineral colours or realistic rock. Full readable rock silhouette inside a generous transparent margin. No ground, backdrop, shadows beneath, labels, glints, particles, coins, new props, detached crystals, hands or characters.
'''
states={
'early_crack':'Opening pose: the geode has only JUST CRACKED OPEN, about10percent of its final opening. The two rounded outer halves still dominate, almost the same compact outline as the closed geode. A narrow curved vertical gap separates the mating seam; only a thin cream inner lip, narrow lavender concavity and a restrained glimpse of the embedded cyan/lilac tips can be seen deep inside. Most of each cavity and its rooted crystals is truthfully hidden by the still mostly closed shell. Each half turns outward only about8degrees. Do not show two fully frontal open bowls or the complete six crystals yet. Outer occupied width approximately1.10times its height.',
'middle_open':'Opening pose: the geode is HALFWAY OPEN, about50percent of its final opening. Both halves have parted modestly and turned outward about35degrees, showing slanted partial concave interiors with the three ROOTED crystals in each cavity. Visible thick lavender outer sides still occupy aboutone-third of each half, so this is plainly between the compact closed stone and the fully frontal open cavities. Do not simply repeat the final fully open two-bowl view. The gap is modest and no wider thanone-tenth of the geode total width. Outer occupied width approximately1.45times its height.'}
payload=[];files=set()
for name,direction in states.items():
 out=root/('opening_geode/'+name+'/attempt_01');out.mkdir(parents=True,exist_ok=False);prompt=common+direction;(out/'PROMPT.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n');write(out/'PLAN.json',dict(status='PREPARED_NAMED_OPENING_CONTINUITY_GAP',baseline=base,gap='Earlier closed-to-fully-faced pair switches immediately on first positive pull. Embedded endpoint passes isolated4.5 but does not prove a truthful opening transition. Existing closed/full art cannot show newly occluded oblique cavity poses by whole-card reuse.',inventory=[dict(path=rel(p),sha256=sha(p),role=r) for p,r in zip(refs,['closed_shell_identity','embedded_cavity_crystal_identity'])],state=name,direction=direction,prompt_sha256=sha(out/'PROMPT.txt'),generation_method='builtin_imagegen_new_static_gameplay_opening_pose',transparent_background=True,attempt=1,production_binding_changed=False,owner_approval=None));shutil.copyfile(__file__,out/'executed_prepare_geode_opening_states_v135.py');files.update(rel(p) for p in out.rglob('*') if p.is_file());payload.append(dict(state=name,prompt=prompt,references=[str(p) for p in refs]))
write(b/'design/audit_impacts/job-geode-opening-continuity-20261001.json',dict(id='job-geode-opening-continuity-20261001',baseline=base,scope='Reversible static geode opening-state refinement for owner-directed embedded interior semantics and the named abrupt closed-to-frontal transition. Reuse accepted drafting endpoints; generate only two missing occluded intermediate poses, preserve all old sources and decisions, and independently inspect native/source and exact native input-state views. No production input/reward/save/source edits or cinematic delivery claim.',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-INT-02','DL-INT-03','DL-INT-04','DL-INT-06','DL-MED-01','DL-QA-03','DL-QA-06','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-VIS-08'],findings=['MA-PLAY-004','MA-VIS-006'],files=sorted(files),validation=[dict(command='Inventory closed/opened source and exact existing first-pull drawing',result='PASS',evidence='audit/job_geode_embedded_mount_v2_20261001/attempt_02/study_surface.gd; source roles/hashes in every PLAN.json'),dict(command='Two intermediate generated source and native view audits',result='PENDING',evidence='Sources not yet generated; no pass assigned.')],acceptance_gaps='Intermediate identity/topology/occlusion/opening continuity, exact mounted input/shape/context, full articulated actor/work action and complete ordinary routes/device/child/owner/final report.'))
print(json.dumps(payload))
