from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_twist_release_components_v1_20261003';IP=B/'design/audit_impacts/job-candy-twist-release-components-20261003.json';PY='C:/Users/Peter/AppData/Local/Python/bin/python.exe'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
 t=p.with_name(p.name+'.v639_next');t.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());t.replace(p)
reviews=dict(release='The complete fixed landscape retains two owned mitten contacts on already-opposite twisted short gold-paper necks,one supported covered low oval,two outward broad fans and the same scene/character. Only whole-canvas896x504 scaling plus4px top/bottom padding occurred. The intended next action is disengagement;no motion is yet shown.',twist='The exact reused whole-canvas normalized input retains both attached thumb/palm grips on soft open lengthwise neck folds of the same supported gold-covered oval and two outward fans. No crop/local repair or new source pixels;opposite wrist movement is not yet shown.')
for stage in ['release','twist']:
 M=P/(stage+'_a1');m=read(M/'MANIFEST.json');source_review=read(B/m['source_review']);assert source_review['source_pose_score']==4.5 and source_review['motion_score'] is None and not source_review['runtime_bound']
 write(M/'INPUT_DIRECT_REVIEW.json',dict(status='DIRECT_COMPLETE896x512_INPUT_REVIEWED_NO_CROP_OR_LOCAL_REPAIR',reviewed_utc=now(),input_sha256=m['input_sha256'],source_sha256=m['source_sha256'],observed=reviews[stage],source_still_score=4.5,motion_score=None,source_score_transfer=False,runtime_bound=False,owner_acceptance=None))
 m['input_visual_review']=dict(status='DIRECT_COMPLETE_NORMALIZED_INPUT_REVIEWED',evidence=(M/'INPUT_DIRECT_REVIEW.json').relative_to(B).as_posix(),input_sha256=m['input_sha256'],source_score_transfer=False);m['status']='EXACT_SOURCE_INPUT_PROMPT_SEVEN_BINDINGS_DIRECTLY_REVIEWED_ADMISSION_CHECK_PENDING';write(M/'MANIFEST.json',m)
 cmd=[PY,'-X','utf8','-B',str(M/'review_tools'/('queue_'+stage+'_a1_v638.py')),'--check'];r=subprocess.run(cmd,cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(M/'checks/admission.stdout.log').write_bytes(r.stdout);(M/'checks/admission.stderr.log').write_bytes(r.stderr);write(M/'checks/ADMISSION_RECEIPT.json',dict(status='PASS' if r.returncode==0 else 'FAIL',checked_utc=now(),command=cmd,exit_code=r.returncode,manifest_sha256=sha(M/'MANIFEST.json'),qualification='Exact one-source/input/prompt/seven unchanged graph bindings admitted;not a motion or owner approval.'));assert r.returncode==0,r.stderr.decode(errors='replace')
 submitted=M/'checks/SUBMITTED_MANIFEST.exact.json';shutil.copyfile(M/'MANIFEST.json',submitted);assert sha(submitted)==sha(M/'MANIFEST.json');write(M/'checks/SUBMISSION_BOUNDARY.json',dict(status='EXACT_LITERAL_MANIFEST_PRESERVED_BEFORE_DISPATCH',checked_utc=now(),submitted_manifest_path=submitted.relative_to(B).as_posix(),submitted_manifest_sha256=sha(submitted),runtime_integration=False,qualification='Direct byte copy before any worker launch,not a later reconstruction.'))
 print(stage,r.stdout.decode().strip(),'SUBMITTED_SHA',sha(submitted),flush=True)
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name);d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});d['validation'].append(dict(command='Both complete normalized inputs and literal pre-dispatch manifest admission',result='PASS',evidence=P.relative_to(B).as_posix()+'/release_a1/checks/ADMISSION_RECEIPT.json and twist_a1/checks/ADMISSION_RECEIPT.json;each actual source4.5 verified,seven unchanged bindings and submitted exact bytes preserved before dispatch. Render/native review pending.'));write(IP,d)
