from pathlib import Path
import ast,json
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');C=B/'assets_src/local_motion/candy_twist_release_components_v1_20261003';IP=B/'design/audit_impacts/job-candy-twist-release-components-20261003.json'
s=(B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003/review_tools/publish_endpoint_review_v634.py').read_text(encoding='utf-8')
s=s.replace("C=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003'","C=B/'assets_src/local_motion/candy_twist_release_components_v1_20261003'").replace('job-candy-twist-release-pose-20261003.json','job-candy-twist-release-components-20261003.json').replace("BASE='930614f3e8ab0d89177409ba92a2dd28dc228d54'","BASE='b6501351a854cc0133b17a74d557ce1c4d14b5af'").replace("MAP='audit/job_review_v2_20261001/CANDY_TWIST_RELEASE_ENDPOINT_FILES_V26.json'","MAP='audit/job_review_v2_20261001/CANDY_TWIST_RELEASE_COMPONENT_FILES_V27.json'").replace("PRIOR='audit/job_review_v2_20261001/CANDY_SPECIFIC_GRIP_MOTION_FILES_V25.json'","PRIOR='audit/job_review_v2_20261001/CANDY_TWIST_RELEASE_ENDPOINT_FILES_V26.json'").replace('v26_unchanged_dependency_shards','v27_unchanged_dependency_shards').replace('tmp/endpoint_publish_v634','tmp/component_publish_v651').replace('tmp/endpoint_remote_v634','tmp/component_remote_v651').replace('tmp/endpoint_sealed_v634','tmp/component_sealed_v651').replace('v634_next','v651_next').replace('PUBLICATION_BOUNDARY_V634.json','PUBLICATION_BOUNDARY_V651.json').replace('EXACT_SHARDED_ENDPOINT_REVIEW_BYTES_SEALED','EXACT_SHARDED_COMPONENT_REVIEW_BYTES_SEALED').replace('previous_AB_remote_verified','previous_AC_remote_verified')
start=s.index('def checks():\n');end=s.index('\ndef run(',start)
checks='''def checks():
    assert git('rev-parse','HEAD').decode().strip()==BASE and git('branch','--show-current').decode().strip()==BRANCH
    for label in ['authority','development','document_tests','game2d','register_parts']:assert read(C/'gates_v1'/(label+'.receipt.json'))['status']=='PASS',label
    sys.path.insert(0,str(L/'review_tools'));from register_parts_v51 import load_register
    reg=load_register(L);assert reg['display_revision']=='V54' and len(reg['items'])==2152 and reg['counts']['inclusive_current_source_priorities']==1055 and reg['counts']['unique_source_file_priorities']==678 and reg['counts']['unreviewed_current_source']==294
    stamp=read(L/'CURRENT_BOUNDARY_REFRESH.json');assert stamp['registry_items']==stamp['registered_source_matches']==2152 and stamp['assembled_registry_parts_verified'] and stamp['registry_root_sha256']==sha((L/'ALL_ITEMS.json').read_bytes()) and stamp['registry_parts']==reg['item_shards']
    previous=read(C/'previous_v53/ALL_ITEMS.json');current=read(L/'ALL_ITEMS.json');assert current['items']==previous['items'] and len(current['items'])==2064 and current['item_shards']==previous['item_shards']
    review=read(C/'REVIEW_SUMMARY.json');assert review['native_frames']==82 and review['individual_frame_opinions']==82 and review['component_opinions']==24 and review['total_individual_opinions']==106 and review['release_score']==1.7 and review['twist_score']==2.2 and review['source_endpoint_score']==4.5 and review['current_game_wrap_score']==2.8 and review['complete_wrapping_score'] is None and not review['runtime_integration'] and review['owner_acceptance'] is None
    for stage,score in [('release',1.7),('twist',2.2)]:
        M=C/(stage+'_a1');A=M/'attempt01';r=read(A/'DIRECT_REVIEW.json');idx=read(A/'INDEX.json');m=read(M/'checks/SUBMITTED_MANIFEST.exact.json');receipt=read(A/'RENDER_RECEIPT.json');state=read(A/'DISPATCH_STATE.json')
        assert len(r['frames'])==len(idx['frames'])==41 and len(r['components'])==12 and r['whole_component_score']==score and r['acceptance']=='LOCAL_MOTION_REFERENCE_ONLY' and not r['runtime_integration'] and r['complete_wrapping_score'] is None and r['owner_acceptance'] is None and not r['endpoint_conditioned']
        assert state['manifest_sha256']==idx['submitted_manifest_sha256']==sha((M/'checks/SUBMITTED_MANIFEST.exact.json').read_bytes()) and receipt['status']=='PASS' and receipt['source_sha256']==m['input_sha256'] and receipt['settings']==m['renderer']['settings'] and receipt['prompt_id']==idx['prompt_id']
        assert sha((M/m['input_path']).read_bytes())==m['input_sha256'] and sha((M/m['prompt_path']).read_bytes())==m['prompt_sha256']==receipt['prompt_sha256']
        job=m['jobs'][0];assert sha((B/job['source_path']).read_bytes())==job['source_sha256'] and len(m['renderer']['bindings'])==7
        for binding in m['renderer']['bindings']:assert sha((M/binding['packet_path']).read_bytes())==binding['sha256']
        for i,(frame,opinion) in enumerate(zip(idx['frames'],r['frames'])):assert frame['index']==opinion['index']==i and frame['sha256']==opinion['sha256']==sha((B/frame['path']).read_bytes()) and opinion['direct_complete_native_review'] and opinion['whole_component_motion_score'] is None and opinion['current_game_score'] is None
        for row in idx['outputs']+idx['boards']:assert sha((B/row['path']).read_bytes())==row['sha256']
    proof=read(C/'BROWSER_OBSERVATIONS_V649.json');assert proof['library']['summary'].startswith('V54: 2,152') and proof['report']['componentRows']==24 and all(v['error'] is None and v['width']==896 and v['height']==512 for v in proof['report']['videos']) and not proof['library']['overflow']
    snapshot=read(C/'gates_v1/CANDIDATE_COMPONENT_SOURCE_V647.json')
    for row in snapshot['members']:
        if row['path']=='.gitattributes':continue # Exact added map/shard text attributes are separately sealed after source checks.
        assert [(B/row['path']).stat().st_size,sha((B/row['path']).read_bytes())]==[row['bytes'],row['sha256']],row['path']
    prior=read(C/'previous_AC_remote_verified/RESULT.json');assert prior['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and prior['files_including_manifest']==24611
    boundary=read(P/'PRODUCTION_BOUNDARY.json');assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members'])
'''
s=s[:start]+checks+s[end:]
s=s.replace('PENDING_EXACT_TEN_ENDPOINT_REVIEW_STAGED_SEAL','PENDING_EXACT_REJECTED_COMPONENT_REVIEW_STAGED_SEAL').replace('PREPARED_EXACT_TWIST_RELEASE_ENDPOINT_PUBLICATION_SCOPE','PREPARED_EXACT_TWIST_RELEASE_COMPONENT_PUBLICATION_SCOPE')
oldline=next(x for x in s.splitlines() if 'manifest=dict(schema=' in x);qualification='V54 known2152 entries/1300 primary sources/1055 inclusive source-cell-region priorities/678 unique source priorities/294 unreviewed primary sources. Two sequential unchanged developed-local Comfy references:release1.7 rejected for detached coral thumb/broken cuffs/no quiet rest;opposed twist2.2 rejected for absent wrist roll and paper closure. Every82 complete native frame and24 components/106 opinions individually reviewed. Exact manifests saved before dispatch,all native videos/frames/receipts/workflows preserved. Gold source endpoints4.5 provisional,current actual WRAP2.8/all783 production literals unchanged. Single conditioned start image;target endpoint human QC only. Existing2064 root dictionaries/literal88-item part unchanged,4MiB ceiling retained. Current-first library preserves all old historical links/opinions,actual browser proof,52 document tests/9 register-integrity tests and all24611 prior AC anonymous remote rows. No runtime,protected-original,3D,security/gate/workflow,finding lifecycle,dev/master integration/release or complete fold-cover-gather-opposite-twist-supported-release/actual jobs/Opera training/ordinary route/device/child/owner/comprehensive all-job acceptance.'
s=s.replace(oldline,oldline[:oldline.index("qualification='V53")]+"qualification="+repr(qualification)+')')
start=s.index("message=OUT/'COMMIT_MESSAGE.txt';");end=s.index("\nrun('commit'",start)
message='Audit specific gold-wrapper twist and release motion components\n\nPreserve both developed-local native references,every82 complete decoded frame and24 named component opinions. Release1.7 rejected for detached thumb/broken cuffs/no quiet rest. Opposed twist2.2 rejected for absent wrist roll/paper closure despite conserved hands/fans. Exact submitted manifests precede dispatch;all native outputs/workflows/receipts retained.\n\nKeep source endpoints4.5 provisional,current actual WRAP2.8 and all783 production literals unchanged. Preserve V54 known2152 entries,all2064 item dictionaries/literal88-item part and source/mounted/action lane separation. Current-first library retains all dated notices/links. Actual browser proofs,52 document tests/9 integrity tests and all24611 prior AC anonymous remote rows preserved.\n\nNo runtime or cinematic binding,finding closure,integration or release. Full causal wrapping,actual story job/Opera training,ordinary routes,device,child,owner and comprehensive all-job acceptance remain open.\n'
s=s[:start]+"message=OUT/'COMMIT_MESSAGE.txt';message.write_text("+repr(message)+",encoding='utf-8',newline='\\n')"+s[end:]
ast.parse(s);p=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/publish_component_review_v651.py');p.write_bytes(s.encode())
def put(p,raw):t=p.with_name(p.name+'.v651_next');t.write_bytes(raw);t.replace(p)
put(C/'review_tools'/Path(__file__).name,Path(__file__).read_bytes());d=json.loads(IP.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in C.rglob('*') if p.is_file()});put(IP,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());print('EXACT_COMPONENT_TOPIC_PUBLISHER_BUILT',flush=True)
