from pathlib import Path
import copy,datetime,hashlib,html,json,subprocess,sys
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_twist_release_components_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-twist-release-components-20261003.json';BASE='b6501351a854cc0133b17a74d557ce1c4d14b5af'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):p.parent.mkdir(parents=True,exist_ok=True);t=p.with_name(p.name+'.v645_next');t.write_bytes(raw);t.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip()==BASE
reviews={stage:read(P/(stage+'_a1/attempt01/DIRECT_REVIEW.json')) for stage in ['release','twist']}
assert reviews['release']['whole_component_score']==1.7 and reviews['twist']['whole_component_score']==2.2 and all(r['native_frames_reviewed']==41 and r['component_opinions']==12 and not r['runtime_integration'] for r in reviews.values())
for stage,r in reviews.items():
 M=P/(stage+'_a1');plan=read(M/'PLAN.json');put(M/'PRE_DISPATCH_PLAN.json',(M/'PLAN.json').read_bytes());plan['status']=r['status'];plan['terminal_review']=(M/'attempt01/DIRECT_REVIEW.json').relative_to(B).as_posix();plan['whole_component_score']=r['whole_component_score'];write(M/'PLAN.json',plan)
plan=read(P/'PLAN.json');put(P/'PRE_DISPATCH_PLAN.json',(P/'PLAN.json').read_bytes());plan.update(status='BOTH_COMPONENTS_RENDERED_EVERY82_NATIVE_FRAME_AND24_COMPONENT_OPINIONS_REVIEWED_REJECTED',finished_review_utc=now(),new_motion_scores={'release':1.7,'twist':2.2})
for job in plan['jobs']:job['status']=reviews[job['stage']]['status'];job['review']=P.relative_to(B).as_posix()+'/'+job['stage']+'_a1/attempt01/DIRECT_REVIEW.json'
write(P/'PLAN.json',plan)
summary=dict(status=plan['status'],reviewed_utc=now(),native_frames=82,individual_frame_opinions=82,component_opinions=24,total_individual_opinions=106,release_score=1.7,twist_score=2.2,source_endpoint_score=4.5,current_game_wrap_score=2.8,complete_wrapping_score=None,runtime_integration=False,device_acceptance=None,child_acceptance=None,owner_acceptance=None,acceptance='LOCAL_MOTION_REFERENCE_ONLY',endpoint_conditioned=False,qualification='Each whole component was reviewed separately. Stable contacts/fans in twist do not prove the absent wrist roll;release support does not repair detached thumb/cuff topology. No score transfer to source endpoints,complete wrapping,current job or training. The two reference clips are not an accepted authored full-frame cinematic.')
write(P/'REVIEW_SUMMARY.json',summary)
write(P/'NEXT_ACTION_PLAN.json',dict(status='REPAIR_NAMED_HAND_OWNERSHIP_AND_TWIST_CAUSALITY_BEFORE_FURTHER_ACCEPTANCE',full_objective='Complete fold→cover→gather→opposite wrist twists→supported release on the same sweet/sheet,then actual job and Opera training fit and broad all-job refinement.',next_steps=[
'Inspect existing clean source hands and isolated approved identity references before generation;do not change approved character design.',
'For release, revise only the thumb/cuff contact seam so each withdrawing mitten remains one continuous sleeve-owned shape; preserve the gold sweet and broad fans. Source and motion opinions remain separate.',
'For twist, make the missing left-under/right-over mid-turn and short closed-paper geometry explicit in independently reviewed source keys. No static hold or facial acting substitutes for torque.',
'Use the existing developed local workflow only within its actual single-start-image capability; target pictures are human QC refs unless a documented graph actually conditions them. Never claim endpoint conditioning that is absent.',
'Review every new frame/action and iterate the named failures. Do not paste,warp,morph or interpolate rejected motion into delivered frames.',
'After coherent full action passes,verify actual story job and Opera training with matching owner identity/material/sockets,then ordinary route/device/child/owner review. Continue all remaining job/source/pose/object priorities and294 pending primary opinions.'
],minimum_drafting_target=4.5,inclusive_priority_threshold=4.5,current_game_wrap_score=2.8,owner_acceptance=None))
sys.path.insert(0,str(L/'review_tools'));from register_parts_v51 import load_register
reg=read(L/'ALL_ITEMS.json');prior=read(P/'previous_v53/ALL_ITEMS.json');assert reg['items']==prior['items'] and reg['item_shards']==prior['item_shards'] and len(reg['items'])==2064
reg.update(display_revision='V54',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v54.py',scope='V54:2152 known individually addressable entries,1300 primary sources/328 pose cells/151 runtime-use-action entries/373 source object regions.1055 inclusive source-cell-region priorities,678 unique priority sources,294 pending primary opinions. Two new developed-local Comfy component references:release1.7 rejected for detached coral thumb/broken cuffs/no quiet rest;opposite twist2.2 rejected for absent wrist roll/paper closure. Every82 native frame and24 components individually reviewed in the linked illustrated report;these decoded reference frames are not new independent ImageGen sources or accepted cinematic frames. Current WRAP2.8/all783 production literals unchanged. Existing2064 root entries and literal88-item part preserved. Full causal wrapping,actual story job/Opera training/ordinary routes/device/child/owner and comprehensive all-jobs approval remain open.')
reg['review_resources'].append(dict(path=P.relative_to(B).as_posix()+'/index.html',scope='Two bounded local-reference components:all82 complete native frames/24 components/106 opinions;release1.7 and twist2.2 rejected. Source endpoints4.5/current WRAP2.8 remain separate.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304
put(L/'review_tools/refresh_current_job_review_v54.py',(L/'review_tools/refresh_current_job_review_v53.py').read_bytes())
for name in ['index.html','all_items.html']:
 p=L/name;s=p.read_text(encoding='utf-8')
 # Correct spacing in the newly added current text only; preserved archive text stays literal.
 start=s.index('<details id="historical-');head=s[:start];tail=s[start:]
 for a,b in [('artwork,individual','artwork, individual'),('opinions,mounted','opinions, mounted'),('composition,complete','composition, complete'),('wrapping,pouring,mixing,plucking','wrapping, pouring, mixing, plucking'),('and123','and 123'),('changes,run','changes, run'),('opinions;dated','opinions; dated'),('days,Opera','days, Opera'),('source,cell,region','source, cell, region'),('Mounted,complete-action,device,child','Mounted, complete-action, device, child'),(',then reload',', then reload')]:head=head.replace(a,b)
 put(p,(head+tail).encode())
css='body{margin:0;background:#edf4fa;color:#25304a;font:17px/1.55 system-ui}main{max-width:1120px;margin:auto;padding:24px}h1,h2{line-height:1.2}a{color:#443b93}section{background:white;padding:20px;border-radius:16px;margin:24px 0}nav{display:flex;flex-wrap:wrap;gap:14px}p,td,code{overflow-wrap:anywhere}img,video{display:block;width:100%;height:auto;aspect-ratio:7/4}table{width:100%;border-collapse:collapse;table-layout:fixed}td,th{padding:10px;text-align:left;vertical-align:top;border-bottom:1px solid #dbe1ed}th:first-child{width:22%}th:nth-child(2){width:9%}.qualification{background:#fff1d4;padding:16px;border-radius:12px}'
out=['<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Specific gold wrapper — twist and release motion review</title><style>'+css+'</style></head><body><main><h1>Do the hands support this gold wrapper in motion?</h1><p class="qualification"><strong>Both new motion components fail the4.5/5 drafting floor.</strong> Supported release1.7/5; opposite wrist twist2.2/5. All82 complete native frames and24 named component opinions are individually preserved. Static endpoint sources remain4.5 provisional and actual game WRAP remains2.8/5.</p><p>The twist reference keeps its hands and paper fans together, but the wrists do not make the opposed turns and the gold neck folds never wind closed. The release keeps the covered sweet supported, but leaves extra coral thumb material at the neck and breaks the glove/cuff shapes as the palms lift. Neither component demonstrates the required physical wrapping workflow.</p><nav><a href="release_a1/index.html">Release movie and all41 frame reviews</a><a href="twist_a1/index.html">Twist movie and all41 frame reviews</a><a href="REVIEW_SUMMARY.json">106 individual opinion summary</a><a href="../../../audit/job_artwork_refinement_live/all_items.html">Full2152-entry register</a><a href="../../imagegen/candy_twist_release_pose_v1_20261003/index.html">Ten source endpoint candidates</a></nav><section><h2>Relationship to the actual game</h2><p>The current live Candy widget is a turquoise decorative wrapper with a magic spiral. These gold-paper paintings are unbound replacement studies. The current story job and Opera training do not yet use these hands or this wrapper family. Source beauty and local motion cannot pass actual-game matching. All783 recorded production literals remain unchanged.</p><p>Still required: partial fold → opaque cover → gather → opposite wrist twists → supported release with the same sweet and sheet, two coherent sleeve-owned hands, conserved fans and stable table support. Then test the authored family in the actual job and training with matching identity, sockets and action timing. Device, child, owner and comprehensive all-job approval remain open.</p></section>']
for stage,r in reviews.items():
 M=P/(stage+'_a1');idx=read(M/'attempt01/INDEX.json');movie=next(x['path'] for x in idx['outputs'] if x['path'].endswith('.mp4'));rel=lambda x:Path(x).relative_to(P.relative_to(B)).as_posix();out.append('<section id="'+stage+'"><h2>'+stage.title()+' component — '+str(r['whole_component_score'])+'/5, rejected</h2><video controls preload="metadata" src="'+rel(movie)+'"></video><p><a href="'+stage+'_a1/index.html">Every native frame, its own score and evaluation</a> · <a href="'+stage+'_a1/checks/SUBMITTED_MANIFEST.exact.json">Literal manifest saved before dispatch</a> · <a href="'+stage+'_a1/attempt01/RENDER_RECEIPT.json">Actual terminal render receipt</a></p><h2>Final native canvas</h2><img src="'+rel(idx['frames'][-1]['path'])+'" alt="Complete rejected '+stage+' endpoint frame40"><table><thead><tr><th>Individual relationship</th><th>Score/5</th><th>Evaluation</th></tr></thead><tbody>')
 for c in r['components']:out.append('<tr class="component-opinion"><td>'+html.escape(c['id'].replace('_',' '))+'</td><td>'+str(c['score'])+'</td><td>'+html.escape(c['evaluation'])+'</td></tr>')
 out.append('</tbody></table></section>')
out.append('<section><h2>Generation and review boundaries</h2><p>Both jobs reused exact reviewed whole-scene source images through the unchanged developed local Comfy graph:896×512,41 frames at24fps,24 steps and the pinned GGUF models. Its single start image is conditioned; the target endpoint is a human QC reference only. Every native video, workflow, submitted manifest, receipt and decoded frame is preserved. QA boards use original-size frames without creative pixel changes.</p><p><a href="NEXT_ACTION_PLAN.json">Named corrections and full remaining objective</a> · <a href="PLAN.json">Task plan and rule coverage</a> · <a href="LIBRARY_LAYOUT_PRESERVATION.json">Current-first library and preserved history evidence</a></p></section></main></body></html>');put(P/'index.html',''.join(out).encode())
# Preserve complete previous publication evidence rather than truncating its journal.
remote=P/'previous_AC_remote_verified';remote.mkdir();source=B/'tmp/endpoint_remote_v634';r=read(source/'RESULT.json');assert r['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and r['revision']==BASE and r['files_including_manifest']==24611 and not r['failed_files']
for src,name in [(source/'RESULT.json','RESULT.json'),(B/'tmp/endpoint_publish_v634/RECEIPT.json','PUBLICATION_RECEIPT.json')]:put(remote/name,src.read_bytes())
raw=(source/'VERIFICATION_JOURNAL.jsonl').read_bytes();lines=raw.splitlines(keepends=True);assert len(lines)==24611 and all(readrow['matches'] for readrow in map(json.loads,lines));parts=[];group=[];size=0
def emit():
 payload=b''.join(group);p=remote/f'JOURNAL_{len(parts)+1:03d}.jsonl';put(p,payload);assert len(payload)<=900000;parts.append(dict(path=p.relative_to(B).as_posix(),bytes=len(payload),sha256=sha(payload),rows=len(group)))
for line in lines:
 if group and size+len(line)>899000:emit();group=[];size=0
 group.append(line);size+=len(line)
if group:emit()
assert b''.join((B/x['path']).read_bytes() for x in parts)==raw;write(remote/'JOURNAL_SHARDS.json',dict(status='ALL24611_EXACT_AC_ANONYMOUS_REMOTE_ROWS_LOSSLESSLY_PRESERVED',revision=BASE,original_bytes=len(raw),original_sha256=sha(raw),original_rows=len(lines),parts=parts,shard_max_bytes=900000,qualification='Complete previous AC exact remote evidence only,not proof of the new component revision or hosted/creative acceptance. Initial pending receipt remains separate.'))
H=P/'previous_AC_hosted_snapshot';H.mkdir();cmd=['C:/Program Files/GitHub CLI/gh.exe','run','view','37121917534','--repo','Ebonyks/mermaid-roshan-reef','--json','databaseId,headSha,status,conclusion,url,jobs'];rr=subprocess.run(cmd,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);put(H/'RUN.json',rr.stdout);put(H/'RUN.stderr.log',rr.stderr);assert rr.returncode==0;data=json.loads(rr.stdout);assert data['headSha']==BASE;write(H/'VERIFICATION.json',dict(status='ACTUAL_PRIOR_EXACT_HEAD_HOSTED_SNAPSHOT',checked_utc=now(),command=cmd,exit_code=0,revision=BASE,run_id=data['databaseId'],run_status=data['status'],run_conclusion=data['conclusion'],jobs=[dict(name=j['name'],status=j['status'],conclusion=j['conclusion']) for j in data['jobs']],raw_sha256=sha(rr.stdout),qualification='Observed hosted status only;pending remains pending. No predicted green,creative acceptance or integration.'))
boundary_path=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json';boundary=read(boundary_path);assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members']);write(P/'PRODUCTION_BOUNDARY_AFTER.json',dict(status='ALL783_CURRENT_LITERAL_PRODUCTION_MEMBERS_UNCHANGED',checked_utc=now(),source_boundary=boundary_path.relative_to(B).as_posix(),boundary_sha256=sha(boundary_path.read_bytes()),members=783,current_wrap_score=2.8,runtime_changed=False,qualification='Review/reference-only changes,no fresh game/action/device/child/owner acceptance.'))
note='Specific Candy motion-component continuation (2026-10-03): [both developed-local references and every82 native frame/24 components](COMPONENTS). Supported release1.7 rejected:detached coral thumb material,broken cuffs and no quiet coherent rest. Opposite twist2.2 rejected:grips/fans conserved,but wrist roll and paper closure absent. Exact submitted manifests saved before dispatch;all native videos/frames/receipts/workflows preserved. Source endpoints4.5/current actual WRAP2.8/all783 production literals unchanged. V54 known2152 entries/1055 inclusive source-cell-region priorities/678 unique priority sources/294 pending primary opinions;2064 root dictionaries and literal88-item part unchanged. Library now leads with verified current register;all earlier notices preserved in dated historical disclosures. Full fold-cover-gather-opposite-twist-supported-release,actual jobs/Opera training/ordinary routes/device/child/owner/comprehensive acceptance remain required. MA-VIS-006 remains CONFIRMED_OPEN;MA-PLAY-004 remains IN_PROGRESS. No finding closure,integration or release.'
for path,link in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/local_motion/candy_twist_release_components_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/local_motion/candy_twist_release_components_v1_20261003/index.html'),('audit/animation/README.md','../../assets_src/local_motion/candy_twist_release_components_v1_20261003/index.html')]:
 p=B/path;t=p.read_text(encoding='utf-8');n=note.replace('COMPONENTS',link)
 if path.endswith('MASTER_AUDIT_2026-08-09.md'):
  for marker in ['## 0. Planning entry','### Development task index']:assert marker in t;t=t.replace(marker,marker+'\n\n'+n,1)
 else:i=t.index('\n')+1;t=t[:i]+'\n'+n+'\n'+t[i:]
 put(p,t.encode())
p=B/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8');t+='\n| `assets_src/local_motion/candy_twist_release_components_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; two reference components,82 native frames/24 named component opinions. Release1.7/twist2.2 rejected;source endpoints4.5/current WRAP2.8 stay separate. Full causal action,actual jobs/Opera training/device/child/owner open. |\n| `assets_src/local_motion/candy_twist_release_components_v1_20261003/previous_v53/ALL_ITEMS.json` | ⚪ | `HISTORICAL_SUPPORTING`; literal V53 root before review-resource update;2064 item dictionaries and88-item part unchanged. Earlier HTML preserved before current-first layout. |\n';put(p,t.encode())
p=B/'.gitattributes';t=p.read_text(encoding='utf-8');t+='\nassets_src/local_motion/candy_twist_release_components_v1_20261003/** -text\n';put(p,t.encode())
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();rows=[]
for stage in ['release','twist']:
 M=P/(stage+'_a1');idx=read(M/'attempt01/INDEX.json');items=idx['outputs']+idx['frames']+idx['boards']+[dict(path=p.relative_to(B).as_posix()) for p in (M/'inputs').glob('*.png')]
 for x in items:
  path=x['path'];assert path.encode() not in raw;role='Decoded whole local reference frame' if 'index' in x else ('Labeled original-size QA board' if x.get('qa_only') else ('Complete source normalized as developed-workflow input' if '/inputs/' in path else 'Complete local Comfy motion reference video'));rows.append('| `'+path+'` | '+role+';exact reviewed project gold-wrapper source through pinned local workflow | Existing pinned model/workflow receipts and inherited project character/wrapper attribution | `'+M.relative_to(B).as_posix()+'/MANIFEST.json` and `'+M.relative_to(B).as_posix()+'/attempt01/INDEX.json` bind bytes | '+('Whole-canvas896×504 normalization with4px top/bottom padding only;original native source preserved.' if '/inputs/' in path else 'Original output pixels preserved;QA boards retain original-size complete frames without resampling.')+' Rejected reference,no runtime/cinematic/device/child/owner approval. |')
put(licenses,raw+('\n'+'\n'.join(rows)+'\n').encode());put(P/'review_tools'/Path(__file__).name,Path(__file__).read_bytes());put(P/'review_tools/build_review_candy_twist_v644.py',Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/build_review_candy_twist_v644.py').read_bytes())
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS.json','CURRENT_BOUNDARY_REFRESH.json','index.html','all_items.html','review_tools/refresh_current_job_review_v54.py']}|{'.gitattributes','ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md','design/05_DOC_LEDGER.md'});write(IP,d)
cmd=['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v54.py')];rr=subprocess.run(cmd,cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);put(P/'REFRESH.stdout.log',rr.stdout);put(P/'REFRESH.stderr.log',rr.stderr);assert rr.returncode==0,rr.stderr.decode(errors='replace');assert read(L/'CURRENT_BOUNDARY_REFRESH.json')['registered_source_matches']==2152;assembled=load_register(L);assert assembled['items'][:2064]==prior['items'] and len(assembled['items'])==2152
write(P/'REGISTER_PRESERVATION_CHECK.json',dict(status='V54_ALL2152_SOURCE_HASHES_MATCH_ALL2064_DICTIONARIES_AND88_ITEM_PART_UNCHANGED',checked_utc=now(),root_bytes=(L/'ALL_ITEMS.json').stat().st_size,unchanged_primary_item_dictionaries=2064,unchanged_literal_part=prior['item_shards'],registered_items=2152,inclusive_source_priorities=1055,unique_priority_sources=678,pending_primary_opinions=294,qualification='Only review-resource/version metadata and library layout change;individual source/action scores and existing thresholds unchanged.'))
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});d['validation'].append(dict(command='V54 known-source refresh and all previous opinion preservation',result='PASS',evidence=P.relative_to(B).as_posix()+'/REGISTER_PRESERVATION_CHECK.json;2152 literal matches,2064 dictionaries and88-item part unchanged,4MiB ceiling retained.'));d['validation'].append(dict(command='Previous AC exact anonymous remote verification journal preservation',result='PASS',evidence=remote.relative_to(B).as_posix()+'/JOURNAL_SHARDS.json;every24611 row losslessly preserved.'));d['validation'].append(dict(command='Runtime import/parser/lint/full probes for source-only component references',result='NOT_APPLICABLE',evidence='New reference art stays under assets_src/.gdignore;all783 production literals unchanged. No new runtime.gd/asset/import changes. Existing official4.7.2 82/82 process0 remains scoped;actual hosted status separately recorded.'));write(IP,d)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for p in L.rglob('*') if p.is_file()}));print('COMPONENT_REPORT_V54_COMPLETE|82 frames24 components106 opinions|all previous2152 entries preserved|prior24611 remote rows archived|all783 production literals unchanged',data['status'],data['conclusion'],flush=True)
