from pathlib import Path
import datetime,hashlib,json,re,shutil
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_twist_release_components_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-twist-release-components-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 t=p.with_name(p.name+'.v640_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
# Extend coverage before changing the public review layout.
d=read(IP);d['scope']+=' Also organize the existing illustrated library so its verified current register leads,all dated/historical notices remain accessible in labelled disclosures,and no earlier mounted score becomes a current claim.';d['files']=sorted(set(d['files'])|{(L/x).relative_to(B).as_posix() for x in ['index.html','all_items.html']}|{P.relative_to(B).as_posix()+'/LIBRARY_LAYOUT_PRESERVATION.json',P.relative_to(B).as_posix()+'/previous_v53/index.html',P.relative_to(B).as_posix()+'/previous_v53/all_items.html'});d['validation'].append(dict(command='Current-first library layout and labelled historical evidence',result='PENDING',evidence='Actual earlier browser DOM began with historical V51/older current claims. Preserve literal prior HTML,retain all links/opinions,keep the fail-closed root/part/stamp verification and validate actual browser rendering. No opinion/score changes.'));write(IP,d)
H=P/'previous_v53';H.mkdir();before={}
for name in ['index.html','all_items.html','ALL_ITEMS.json','CURRENT_BOUNDARY_REFRESH.json']:
 p=L/name;raw=p.read_bytes();shutil.copyfile(p,H/name);before[name]=dict(bytes=len(raw),sha256=sha(raw))
old=(L/'index.html').read_text(encoding='utf-8');doc=old.lower().index('<!doctype');main_start=old.index('<main>',doc)+len('<main>');main_end=old.rindex('</main>');archive=old[:doc]+old[main_start:main_end]
# Archive JavaScript as inert text while keeping its full literal original in the snapshot.
archive=re.sub(r'<script(?:\s[^>]*)?>',lambda m:'<script type="text/plain" data-historical-script="true">',archive)
css='body{margin:0;background:#edf4fa;color:#25304a;font:17px/1.55 system-ui}main{max-width:1180px;margin:auto;padding:24px}h1,h2{line-height:1.2}a{color:#443b93}section,details{background:white;padding:20px;border-radius:16px;margin:20px 0}nav{display:flex;flex-wrap:wrap;gap:14px}p,td,code{overflow-wrap:anywhere}img{max-width:100%;height:auto}table{width:100%;table-layout:fixed}summary{cursor:pointer;font-weight:650}details[open]>summary{margin-bottom:18px}.qualification{background:#fff1d4;padding:16px;border-radius:12px}'
intro='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mermaid Roshan — current job artwork audit</title><style>'+css+'</style></head><body><main><h1>Mermaid Roshan jobs — current artwork audit</h1><section id="current-review"><h2>Current individual register</h2><p id="current-register-summary-v640">Checking the exact register and source boundary…</p><p class="qualification">Source artwork,individual pose/object opinions,mounted composition,complete physical actions and owner acceptance are separate. A good still does not prove wrapping,pouring,mixing,plucking or a supported release. Earlier Geologist/Nursery mounted claims remain withheld when their recorded shared source no longer matches.</p><nav><a href="all_items.html">Browse every individual item and priority</a><a href="../../assets_src/local_motion/candy_twist_release_components_v1_20261003/index.html">New twist/release component studies</a><a href="../../assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html">Ten corrected endpoint candidates and123 evaluations</a><a href="../job_review_v2_20261001/index.html">Dated illustrated job reviews</a></nav><p>After game changes,run the register’s recorded refresh command and reload. Source or binding changes withhold earlier current opinions;dated evidence remains preserved. <a href="CURRENT_BOUNDARY_REFRESH.json">Current literal source-boundary record</a> ·<a href="ALL_ITEMS.json">Written register root</a></p></section><details id="historical-review-entry"><summary>Earlier review entry and historical updates — dated evidence</summary><p class="qualification">Everything below is preserved historical review text. Dates,counts and words such as “current” describe those earlier snapshots;they do not override today’s verified register or grant fresh gameplay/owner acceptance. All original links remain available.</p>'
script='''<script src="review_tools/load_register_parts_v51.js"></script><script>
loadVerifiedRegisterV51().then(async d=>{
 const response=await fetch('CURRENT_BOUNDARY_REFRESH.json',{cache:'no-store'});if(!response.ok)throw Error('Source-boundary record unavailable');const s=await response.json();
 if(s.registry_root_sha256!==d.verified_root_sha256||s.registry_items!==d.items.length||s.registered_source_matches!==d.items.length||s.assembled_registry_parts_verified!==true||JSON.stringify(s.registry_parts)!==JSON.stringify(d.item_shards||[]))throw Error('Source-boundary/register mismatch;current claims withheld');
 const c=d.counts;document.querySelector('#current-register-summary-v640').textContent=`${d.display_revision}: ${d.items.length.toLocaleString()} individually addressable entries; ${c.inclusive_current_source_priorities.toLocaleString()} inclusive source/cell/region priorities (${c.unique_source_file_priorities} unique priority sources); ${c.unreviewed_current_source} primary source opinions still required. Register updated ${d.updated_utc||d.created_utc}; source boundary checked ${d.last_boundary_refresh}. Counts do not establish visual or owner acceptance.`;
}).catch(e=>{document.querySelector('#current-register-summary-v640').textContent='Current register unavailable;all current count/acceptance claims withheld: '+e.message});
</script>'''
put(L/'index.html',(intro+archive+'</details>'+script+'</main></body></html>\n').encode())
old=(L/'all_items.html').read_text(encoding='utf-8');doc=old.lower().index('<!doctype');header_start=old.index('<header>',doc)+len('<header>');header_end=old.index('</header>',header_start);inside=old[header_start:header_end];h1=re.search(r'<h1>.*?</h1>',inside,re.S);summary=re.search(r'<p id="summary">.*?</p>',inside,re.S);assert h1 and summary
history=old[:doc]+inside[:h1.start()]+inside[h1.end():];history=history.replace(summary.group(),'',1)
current=h1.group()+'<p>Browse the current verified individual register across job days,Opera training/shared sources and preserved study history. Every source,cell,region and action keeps its own qualification. Mounted,complete-action,device,child and owner acceptance remain independent.</p>'+summary.group()+'<p>Refresh after game changes with the command recorded in <a href="ALL_ITEMS.json">ALL_ITEMS.json</a>,then reload. <a href="CURRENT_BOUNDARY_REFRESH.json">Latest literal boundary comparison</a> ·<a href="index.html">Current audit entry</a> ·<a href="../../assets_src/local_motion/candy_twist_release_components_v1_20261003/index.html">Twist/release studies</a></p><details id="historical-register-notices"><summary>Earlier source studies and audit notices — dated evidence</summary><p>These preserved notices retain their original dates,counts and scoped opinions. Earlier uses of “current” do not override the verified register below,and changed bindings keep mounted claims withheld.</p>'+history+'</details>'
put(L/'all_items.html',(old[doc:header_start]+current+old[header_end:]).encode())
assert (L/'index.html').read_text().lower().startswith('<!doctype') and (L/'all_items.html').read_text().lower().startswith('<!doctype')
assert sha((L/'ALL_ITEMS.json').read_bytes())==before['ALL_ITEMS.json']['sha256'] and sha((L/'CURRENT_BOUNDARY_REFRESH.json').read_bytes())==before['CURRENT_BOUNDARY_REFRESH.json']['sha256']
for name in ['index.html','all_items.html']:
 prior=(H/name).read_text(encoding='utf-8');current=(L/name).read_text(encoding='utf-8');oldlinks=re.findall(r'<a\b[^>]*href="([^"]+)"',prior);newlinks=re.findall(r'<a\b[^>]*href="([^"]+)"',current);assert all(newlinks.count(x)>=oldlinks.count(x) for x in set(oldlinks)),name
write(P/'LIBRARY_LAYOUT_PRESERVATION.json',dict(status='LITERAL_PRIOR_HTML_PRESERVED_ALL_LINKS_RETAINED_OPINIONS_AND_STAMP_UNCHANGED',checked_utc=now(),before=before,after={name:dict(bytes=(L/name).stat().st_size,sha256=sha((L/name).read_bytes())) for name in ['index.html','all_items.html']},qualification='Layout/history qualification only. Prior invalid pre-doctype notices now live in labelled historical disclosures. All existing links retained;register item dictionaries and source stamp literal unchanged. Existing strict part loader unchanged;new entry verifies exact root/part/stamp before current counts. Actual browser review pending.'))
placeholder='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gold wrapper — twist/release component studies</title><style>'+css+'</style><main><h1>Specific gold wrapper — motion component studies</h1><p>Two bounded references are prepared through the existing developed local Comfy workflow. The supported-release study is being rendered;the separate twist study follows. Native frame review and both motion scores are still pending. This page records preparation only;live worker state and terminal evidence will be archived after completion.</p><p>Source endpoints4.5 provisional;previous combined motion1.8 rejected;actual game WRAP2.8 unchanged. Full fold→cover→gather→opposite twists→supported release and actual job/Opera training/device/child/owner acceptance remain open.</p><nav><a href="PLAN.json">Current task plan and required evidence</a><a href="release_a1/MANIFEST.json">Release component contract</a><a href="twist_a1/MANIFEST.json">Opposite twist component contract</a><a href="../../../audit/job_artwork_refinement_live/all_items.html">All-item register</a></nav></main></html>'
put(P/'index.html',placeholder.encode());shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()});write(IP,d)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}));print('CURRENT_FIRST_LAYOUT_ALL_LINKS_RETAINED_REGISTER_AND_STAMP_LITERAL_UNCHANGED',flush=True)
