from pathlib import Path
import json,hashlib,shutil,subprocess,sys
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001'
def rel(p):return p.relative_to(r).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
report=json.loads((out/'REVIEW.json').read_text(encoding='utf-8'));report['technical_derivatives_directly_reviewed']=7;write(out/'REVIEW.json',report)
src=r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v12.py';code=src.read_text(encoding='utf-8')
insert='''# V13 owner correction is current; earlier source scores/receipts remain history.
geo_prefix='assets_src/imagegen/geologist_painted_rebuild_v1_20261001'
geo=read(geo_prefix+'/REVIEW.json')
for x in geo['items']+geo['technical_derivatives']:
 p=x['path'];actual=hashlib.sha256((r/p).read_bytes()).hexdigest();assert actual==x['sha256']
 items[p]=dict(id=x.get('id','GEO-PAINT-TECH-'+p.split('/')[-3].upper()),aliases=[],kind='source',path=p,source_dimensions=x['dimensions'],earlier_sha256=actual,historical_source_score=x['source_score'],evaluation=x['evaluation'],refinement='Named painted source only. Actual invitation/work drawing, material scale, fossil assembly, panning containment, geode reveal, complete route and owner acceptance remain separate.',families=['Geologist painted rebuild','Unbound ImageGen source/technical review'],original_reports=[geo_prefix+'/index.html'],source_qualification=x.get('qualification','Whole-canvas technical derivative only; inherited exact-source opinion, all seven derivatives directly inspected, no runtime/mounted/action pass.'),preview_path=p,native_reference_observations=[],runtime_binding_state=x['status'],latest_refinement=dict(report=geo_prefix+'/index.html',note='Owner rejected flat geology vectors;12 new generated originals,22 neutral displays and7 technical derivatives directly inspected. Native room remains undersize reference-only. Source floor does not grant in-game acceptance.'))
correction=read('assets_src/vector/job_geology_teacher_refinement_v1_20261001/OWNER_CORRECTION_V1.json')
for x in correction['items']:
 q=items[x['path']];q['earlier_written_evaluation']=q['evaluation'];q['latest_source_score']=x['current_source_score'];q['latest_source_sha256']=x['sha256'];q['evaluation']='Owner rejected the flat vector geology medium. Earlier isolated drafting source-floor opinion was too generous and is withdrawn. Original candidate and exact dated score remain available as history.';q['source_qualification']='Current owner-rejected vector draft; prior4.5 is not current acceptance.';q['runtime_binding_state']=x['current_status'];q['latest_refinement']=dict(report=geo_prefix+'/index.html',note='Painted ImageGen rebuild commissioned and started. Six vector sources are rejected; teacher is separate and remains provisional.')
'''
needle="for q in items.values():\n p=q['path']"
assert code.count(needle)==1;code=code.replace(needle,insert+needle)
code=code.replace('build_current_job_item_register_v12.py','build_current_job_item_register_v13.py')
code=code.replace('Five separately named source-floor replacements are unbound; complete interactions remain open.','Earlier geology vector floor claims are withdrawn by owner correction; painted ImageGen rebuild is separately reviewed and unbound. Teacher remains provisional; complete interactions remain open.')
target=src.with_name('build_current_job_item_register_v13.py');assert not target.exists();target.write_text(code,encoding='utf-8',newline='\n')
subprocess.run([sys.executable,'-X','utf8','-B',str(target)],cwd=r,check=True)
counts=json.loads((r/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text(encoding='utf-8'))['counts']
notice='<section class="notice" id="geology-owner-correction"><h2>Geology source floors withdrawn: painted rebuild underway</h2><p>The owner rejects the flat geology vectors. Six candidate vector scores are now3.9 and earlier4.5 opinions are preserved as history. <a href="'+('../../assets_src/' if 'live' else '')+'">Rebuild</a></p></section>'
for path in ['audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html']:
 p=r/path;s=p.read_text(encoding='utf-8');s=s.replace('Five reversible vector replacements at source-only4.5','Historical vector drafts: geology floor claims withdrawn').replace('Eight vector drafts are preserved: three rejected first drafts and five selected source floors.','Eight vector drafts are preserved as history: six geology candidates are now owner-rejected; the two teacher drafts stay separate and provisional.')
 banner='<section class="notice" id="geology-owner-correction"><h2>Geology: owner correction and painted rebuild</h2><p>Earlier geology vector source floors were too generous and are withdrawn. Six vector drafts are now3.9 and rejected; their old opinions remain history. <a href="../../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html">Twelve fresh ImageGen originals and individual painted-source evaluations</a> replace the named style gaps in review only. Seven selected prop/work sources and seven whole-canvas1024 derivatives are unbound. The1672×941 room stays reference-only below2048×2048 native coverage. Invitations, contacts, actions and final owner approval remain open.</p><p>The current register contains'+str(counts['registered_items'])+' addressable entries and'+str(counts['unique_source_files'])+' source files, with'+str(counts['inclusive_current_source_priorities'])+' inclusive priorities and'+str(counts['unreviewed_current_source'])+' unassigned source opinions. Counts include unbound/rejected/shared sources, not only live weak objects.</p></section>'
 assert 'id="geology-owner-correction"' not in s;s=s.replace('</main>',banner+'</main>');p.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');s=s.replace('Current nursery/teacher/geology direct review (2026-10-01):','Historical nursery/teacher/geology source review before owner correction (2026-10-01):');s=s.replace('[Five reversible vector replacement sources](../assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html) meet source-only4.5 after three first drafts at4.4 were preserved.','[Earlier reversible vector replacement sources](../assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html) initially received source-only4.5; the subsequent owner correction withdraws every geology passing-source claim, preserving the dated earlier opinions as history.')
entry='\nOwner geology correction and painted rebuild (2026-10-01): [Six flat vector geology drafts are rejected and their source floors withdrawn](../assets_src/vector/job_geology_teacher_refinement_v1_20261001/OWNER_CORRECTION_V1.json). [Twelve fresh ImageGen originals,22 neutral displays and7 technical derivatives](../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html) have individual source-only opinions; the pan4.5 remains an inclusive priority. Selected painted prop/work sources are unbound, while actual room1672×941 fails2048×2048 native per-screen coverage and remains reference-only. Earlier alpha edge/halo interpretation is corrected without rewriting native outputs or historical receipts. Teacher feedback remains provisional. Register'+str(counts['registered_items'])+' entries/'+str(counts['unique_source_files'])+' sources/'+str(counts['inclusive_current_source_priorities'])+' inclusive priorities/'+str(counts['unreviewed_current_source'])+' unassigned source opinions; complete contexts/actions/device/child/owner/report remain open. [Impact](../design/audit_impacts/job-geology-painted-rebuild-20261001.json). No finding closure.\n'
assert 'Owner geology correction and painted rebuild (2026-10-01)' not in s;s=s.replace('## 0. Planning entry','## 0. Planning entry\n'+entry);p.write_text(s,encoding='utf-8',newline='\n')
p=r/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8')
s+='\n| `assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html` | 🟣 | `CANDIDATE`; owner-rejected geology vector source floors withdrawn, twelve native ImageGen painted originals,22 neutral alpha displays and seven1024 whole-canvas technical derivatives directly reviewed with individual source-only opinions. The1672×941 grotto is reference-only and fails native background coverage. Runtime invitations, work binding, contact, assembly/reveal, complete training/story/device/child/owner and final report remain open. |\n'
s=s.replace('Five reversible vector replacement sources','Earlier reversible vector replacement sources')
row='| `assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html`'
lines=s.splitlines()
for i,line in enumerate(lines):
 if line.startswith(row):lines[i]=row+' | 🟣 | `REJECTED_GEOLOGY_STYLE / TEACHER_CANDIDATE`; six flat geology vector drafts and their dated earlier4.5 opinions are preserved as history, current owner rejection source3.9 supersedes their selected-floor claim. Painted ImageGen rebuild is separate; teacher remains provisional. No runtime, complete action or owner approval. |'
p.write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
shutil.copyfile(__file__,out/'executed_update_geology_library_v94.py')
p=r/'design/audit_impacts/job-geology-painted-rebuild-20261001.json';d=json.loads(p.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{rel(p) for p in out.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/index.html'}|{rel(p) for p in (r/'audit/job_artwork_refinement_live').rglob('*') if p.is_file()}|{rel(target)});d['validation'].append(dict(command='Build V13 exact-hash register with current owner rejection overlay and twelve new individually reviewed ImageGen sources',result='PASS',evidence='audit/job_artwork_refinement_live/ALL_ITEMS.json'));write(p,d)
print(json.dumps(counts))
