from pathlib import Path
import datetime,hashlib,json,shutil,subprocess,html
from PIL import Image
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001'
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def rel(p):return p.relative_to(r).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
data=json.loads((out/'GENERATED_NATIVE_REGISTER_V1.json').read_text(encoding='utf-8'))
ri=Path(__file__).with_name('geology_imagegen_v93_room_input.json'); room=json.loads(ri.read_text(encoding='utf-8'))
dst=out/'grotto/attempt_01';dst.mkdir(parents=True,exist_ok=True);native=dst/'native.png'
assert not native.exists();shutil.copyfile(room['provider_native_path'],native)
(dst/'PROMPT.txt').write_text(room['prompt']+'\n',encoding='utf-8',newline='\n');im=Image.open(native)
record=dict(id='grotto',attempt=1,native_path=rel(native),native_sha256=sha(native),native_dimensions=list(im.size),mode=im.mode,prompt_sha256=hashlib.sha256(room['prompt'].encode()).hexdigest(),prompt_path=rel(dst/'PROMPT.txt'),generation_method='BUILT_IN_CODEX_IMAGEGEN',provider_native_path=room['provider_native_path'],provider_native_preserved=True,transparent_background_requested=False,reference_images=[],source_direct_generated_display_review=True,source_score=None,mounted_score=None,complete_action_score=None,owner_approval=None,runtime_binding_changed=False,audit_previews=[],native_background_requirement_met=im.width>=2048 and im.height>=2048,qualification='REFERENCE_ONLY: requested3840x2160; actual native size is reported literally. No upscale or runtime coverage pass.')
write(dst/'GENERATION_RECORD.json',record);data['records'].append(record);data['status']='TWELVE_NATIVE_GENERATIONS_PRESERVED';write(out/'GENERATED_NATIVE_REGISTER_V1.json',data)
opinions={
('fossil',1):(4.3,'REJECTED_UNBOUND_SOURCE','Fine mottled mineral texture and thin contour are too specimen-like for the broad painted toy language. Opaque slab is complete but has only43/28px side margins; earlier edge-touch warning came from low-opacity trace alpha, not a cropped opaque fossil. Kept as first draft.'),
('fossil',2):(4.6,'SELECTED_SOURCE_ONLY_UNBOUND','Strong plum contour, one warm readable spiral and broad brushed cream/lavender values now read as a painted picture-book object. Full opaque silhouette remains inside the canvas. Existing work-grid cover, source stretching, assembly thirds and actor contact require independent gameplay review.'),
('layered_rock',1):(4.6,'SELECTED_SOURCE_ONLY_UNBOUND','Exactly three large colored strata and two calm inclusions retain teaching clarity while broad gouache values and a rounded plum silhouette supply the missing painted material. This specimen must not serve as a semantic substitute for a washing-pan invitation.'),
('washing_pan',1):(4.5,'SOURCE_FLOOR_UNBOUND_PRIORITY','Aqua interior is generous and unobstructed, lavender rim has painted depth, and the whole bowl is readable. Fine water/material texture and relatively light contour remain less cohesive than the strongest new props;4.5 remains an inclusive refinement priority. Touch-grain containment and actual panning are unreviewed.'),
('closed_geode',1):(4.6,'SELECTED_SOURCE_ONLY_UNBOUND','Simple rounded lilac body, aqua underside and a single readable central seam carry broad matte painted values. No tiny facets or visible interior. Source passes the drafting floor; seam cue alignment and matching opening action remain separate.'),
('crystal_reward',1):(4.6,'SELECTED_SOURCE_ONLY_UNBOUND','Exactly two distinct aqua/lavender crystals on one attached mineral base, broad painted facets and clear plum silhouette. Color and light fit the new prop family without dense realistic glitter. Actual reward visibility and crest-size use still need review.'),
('open_geode',1):(4.6,'SELECTED_SOURCE_ONLY_CONTINUITY_PENDING','Two painted halves retain the closed source colors and material, with quiet cream interior faces and no extra reward pixels. Source finish is strong. The open silhouette is wider than the closed reference; source-to-state continuity remains4.4 provisional, pending normalized geometry and actual reveal/contact review.'),
('work_surface',1):(4.4,'EARLIER_UNSELECTED_SOURCE','Warm painted slab is complete and physically readable, but fine contour and busy uneven edge values weaken the quiet work surface. Initial apparent halo rejection is corrected: native alpha/white/aqua display shows mostly trace-opacity surrounding color, not a solid baked backdrop. Preserve both the initial judgment and this measured correction.'),
('work_surface',2):(4.5,'EARLIER_SOURCE_FLOOR_UNSELECTED','Quiet light center and slender lavender thickness are useful, but the very broad footprint and pale outer contour are weaker than attempt4. Native white/aqua composites show the apparent glow is trace-opacity color. Source-only4.5 does not approve a work-grid fit.'),
('work_surface',3):(4.5,'EARLIER_SOURCE_FLOOR_UNSELECTED','ImageGen background-removal request kept a faint native color field; measured alpha and neutral displays clarify that the field is trace opacity. Slab has a usable painted center, though its wide shape and fine contour are less robust. No source pixels were manually masked or repaired.'),
('work_surface',4):(4.6,'SELECTED_SOURCE_ONLY_UNBOUND','Varied plum silhouette, creamy quiet top and grouped lavender thickness supply a clear painted working prop. White/aqua native checks show a clean readable edge. Wide object footprint must be matched to the actual work rectangle without obscuring touch or reward pixels.'),
('grotto',1):(4.6,'REFERENCE_ONLY_NATIVE_RESOLUTION_FAILED','A welcoming high-key painted room with four empty edge alcoves, three broad strata and a quiet open floor resolves the flat procedural visual direction. Actual native1672x941 falls below2048x2048 per-screen coverage despite the requested3840x2160. This source is a layout/style reference only, never a runtime-resolution pass.')}
items=[];derivatives=[]
for rec in data['records']:
    score,status,evaluation=opinions[(rec['id'],rec['attempt'])]
    item=dict(id='GEO-PAINT-'+rec['id'].upper()+'-%02d'%rec['attempt'],path=rec['native_path'],sha256=rec['native_sha256'],dimensions=rec['native_dimensions'],source_score=score,status=status,evaluation=evaluation,qualification='Direct generated-native and every available neutral white/aqua display inspected. Source-only drafting opinion; not mounted/action/device/child/owner acceptance.',source_record=rec['native_path'].replace('native.png','GENERATION_RECORD.json'),native_direct_review=True,neutral_previews_direct_review=[x['path'] for x in rec['audit_previews']],mounted_score=None,complete_action_score=None,owner_approval=None)
    if rec['id']=='open_geode':item['provisional_state_continuity_score']=4.4
    if rec['id']=='grotto':item['runtime_resolution_pass']=False
    write((r/rec['native_path']).with_name('SOURCE_REVIEW.json'),item);items.append(item)
    if status.startswith('SELECTED_SOURCE_ONLY') or status=='SOURCE_FLOOR_UNBOUND_PRIORITY':
        source=Image.open(r/rec['native_path']);target=out/rec['id']/('attempt_%02d'%rec['attempt'])/'whole_canvas_1024.png'
        assert source.size==(1254,1254);source.resize((1024,1024),Image.Resampling.LANCZOS).save(target)
        d=dict(path=rel(target),sha256=sha(target),dimensions=[1024,1024],source_path=rec['native_path'],source_sha256=rec['native_sha256'],method='WHOLE_CANVAS_UNIFORM_DOWNSCALE_1254_TO_1024_RGBA_PNG',alpha_preserved=True,pixel_repair=False,qualification='Technical derivative only, no independent mounted/action score. Full native original retained; no crop, mask, recolor, separate layer or alpha cleanup.',source_score=score,status='TECHNICAL_DERIVATIVE_UNBOUND',evaluation=evaluation)
        write(target.with_suffix('.json'),d);derivatives.append(d)
report=dict(status='OWNER_REJECTED_VECTOR_SOURCE_FLOORS_WITHDRAWN_PAINTED_REBUILD_IN_PROGRESS',baseline='6edb4ca8c57bfbfe3123636863a29c95165ac23f',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),items=items,technical_derivatives=derivatives,native_outputs_directly_reviewed=12,neutral_native_displays_directly_reviewed=22,qualification='All12 generated originals and22 neutral alpha displays directly inspected. Seven selected source/floor props, seven technical derivatives, retained earlier drafts and an undersize room reference. Source scores do not establish actual game graphics, complete action or owner approval.',initial_alpha_interpretation_correction='Early fossil edge-touch warning reflects alpha<=15 trace rather than a cropped opaque contour. Early work-surface halo rejection was overly literal about the native display: alpha/white/aqua reveal trace opacity, not a solid background. Earlier source/display judgments remain as chronology; final source opinions above use exact native/neutral evidence.',acceptance_gaps=['Painted native room coverage >=2048x2048 per playable screen','Real invitations must draw the named objects','Actual work-area binding and unclipped geode reward','Fossil scale and three-piece assembly geometry','Connected brush/hand/work contact','Full uninterrupted training/story route, child/device/owner and comprehensive report'])
write(out/'REVIEW.json',report)
cards=[]
for x in items:
    native_rel=Path(x['path']).relative_to(out.relative_to(r)).as_posix();j=x['source_record'].split('/')[-2];preview=native_rel.replace('native.png','audit_aqua.png') if x['neutral_previews_direct_review'] else native_rel
    cards.append('<article id="'+x['id']+'"><h2>'+html.escape(x['id'])+' — '+str(x['source_score'])+'/5 source</h2><p>'+html.escape(x['status'])+'</p><img src="'+preview+'" alt="'+html.escape(x['id'])+'"><p>'+html.escape(x['evaluation'])+'</p><p><a href="'+native_rel+'">Preserved native PNG</a> · <a href="'+native_rel.replace('native.png','PROMPT.txt')+'">Exact prompt</a> · <a href="'+native_rel.replace('native.png','GENERATION_RECORD.json')+'">Generation and alpha record</a></p><code>'+x['sha256']+'</code></article>')
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painted geology rebuild — source review</title><style>body{background:#edf4f6;color:#27314c;font:17px/1.5 system-ui;margin:0}main{max-width:1250px;margin:auto;padding:24px}article,header,section{background:white;padding:20px;border-radius:16px;margin:18px 0}img{max-width:100%;height:auto}code{overflow-wrap:anywhere;font-size:12px}.notice{border-left:5px solid #bd705b;padding:14px;background:#fff1e9}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:18px}.grid article{min-width:0}a{color:#4a4699}</style><main><header><a href="../../../audit/job_artwork_refinement_live/all_items.html">Complete known-item library</a><h1>Geologist: painted artwork rebuild</h1><p class="notice">Owner rejected the flat vector approach. Its earlier passing source marks are withdrawn and retained as history. This is a fresh built-in ImageGen prop/work/room draft; no current game, full action or owner approval is claimed.</p><p>Twelve native generations are preserved, with individual evaluations and seven whole-canvas technical derivatives. Selected fossil, layered rock, closed/open geode, crystal reward and work slab have source-only4.6 opinions; the pan is source-only4.5 and remains a refinement priority. The room is only1672×941 native and stays reference-only below the required2048×2048 per playable screen.</p><p><a href="REVIEW.json">Complete written source review</a> · <a href="GENERATION_QUEUE_V1.json">Initial reuse inventory and commissioned gaps</a> · <a href="GENERATED_NATIVE_REGISTER_V1.json">Every original and prompt/hash record</a> · <a href="../../vector/job_geology_teacher_refinement_v1_20261001/OWNER_CORRECTION_V1.json">Owner correction</a></p></header><section><h2>What the earlier audit missed</h2><p>Rounded contours and vector gradients were treated too generously as painted finish. Native gameplay also hides several purportedly replaced objects: river, fossil and geode invitations show only halos, fossil dust covers the image, and geode halves conceal most of the reward. The procedural room and work surface remain separate rebuild gaps. A source score cannot pass an object absent from visible pixels.</p><p>Neutral alpha checks correct the initial apparent edge/halo interpretation: these are mostly trace-opacity pixels, not a cropped opaque fossil or solid backdrop. All attempts and the correction remain inspectable.</p><p>Current native placement and full brush/pan/open/assembly actions remain under review. Teacher improvements are preserved separately; the owner’s positive feedback is not final approval.</p></section><div class="grid">'+''.join(cards)+'</div></main></html>'
(out/'index.html').write_text(page,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,out/'executed_review_geology_sources_v93.py');shutil.copyfile(ri,out/'executed_geology_imagegen_v93_room_input.json')
license_path=r/'ASSET_LICENSES.md';lic=license_path.read_text(encoding='utf-8')
for p in sorted(out.rglob('*.png')):
    path=rel(p)
    if '`'+path+'`' not in lic:
        lic+='\n| `'+path+'` | Owner-commissioned Codex built-in ImageGen geology review; generated/native or whole-canvas neutral audit display/technical derivative, exact source/prompt in generation record | OpenAI generated artwork; project-use provenance recorded, not a third-party open-source grant | local-generation/no external source URL | Native originals untouched; derivatives explicitly qualified in `'+rel(out/'REVIEW.json')+'`; unbound review only |'
license_path.write_text(lic+'\n',encoding='utf-8',newline='\n')
geo=r/'design/audit_impacts/job-geology-painted-rebuild-20261001.json';d=json.loads(geo.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{rel(p) for p in out.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Direct review of12 generated natives and22 neutral alpha displays; measured dimensions/alpha; preserved exact original prompts/hashes',result='PASS',evidence=rel(out/'REVIEW.json')));d['acceptance_gaps']='Source-only opinions do not pass actual jobs. Native room1672x941 fails background coverage; full invitations/work surfaces/contact/assembly/reveal/training/story/device/child/owner/comprehensive report remain open.';write(geo,d)
print(json.dumps(dict(native_generations=len(items),neutral_displays=22,technical_derivatives=len(derivatives),background_actual=im.size,background_requirement_met=False)))
