from pathlib import Path
import json, hashlib, shutil
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/panning_contact/attempt_01'
out.mkdir(parents=True,exist_ok=False)
prompt='''Use case: illustration-story. Generate ONE new transparent game action cutout, not a sheet or a scene. This repairs the missing geologist panning/gripping gesture in Mermaid Roshan.
IMAGE_1 is the established Roshan geologist identity and costume atlas ONLY: preserve her exact friendly child face, large brown eyes, brown hair with rainbow locks, tan exploration cap with round cyan goggles, lilac puff sleeves, teal pocket vest, brown utility belt and pouch, iridescent lavender/aqua mermaid tail and complete rainbow fluke. Use the full-fin cells as identity authority. Do not copy the atlas poses or multiple figures.
IMAGE_2 is the approved washing-pan design, material, colour and basin shape ONLY. Preserve its broad shallow elliptical form (about 2.06 times wider than high), deep plum contour, painted lavender rim and aqua water. It contains no grains or crystals in this new cutout; those are interactive separate objects in the game.
Primary request: One complete Roshan on the LEFT, facing three-quarter RIGHT, visibly holding the pan on the RIGHT with BOTH hands. Her torso is upright and leaning forward slightly; her tail curls left and rests comfortably, complete rainbow fin visible. Her two elbows are bent and lifted above her waist. Both hands unmistakably grip the near rim of the pan: thumbs rest on its upper lip and fingers curl down over the outside wall. One grip is at the near-left rim and the other further along the near rim. Arms connect naturally to both shoulders. The pan is supported at her waist/elbow level, with its unobstructed shallow aqua water clearly visible from above. The pan is approximately as wide as Roshan including her curled tail; she must look physically able to hold it, not miniature beside a giant bowl. This is the neutral held panning position, ready to rock the pan gently. No arm through water, no loose palms on an invisible floor, no crawling or kneeling human legs.
Style: polished 2D hand-painted children's storybook gameplay art matching the references. Rounded readable silhouettes, warm-brown/plum contours, broad matte cream/aqua/lavender value bands, restrained brush texture. Preserve the character's familiar proportions and expression; no realistic anatomy, photoreal materials, 3D lighting or glossy plastic redesign. Make the hand-to-rim contact exceptionally clear even at small phone size.
Composition: one connected character-and-pan action cutout on a landscape canvas, full head, full tail, full fin, both hands, both arms, complete pan all inside a generous transparent margin. No ground plane, room, backdrop, text, shadow beneath the group, extra tools, extra limbs, extra characters, crystals, grains, sparkles, labels or white sticker border. Genuine RGBA transparency outside the authored cutout. This is a new static gameplay contact pose, not a cinematic frame or completed animation.'''
(out/'PROMPT.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
refs=[b/'assets/opera/worlds/actors/animation/roshan_geologist_sheet_a.png',b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/washing_pan/attempt_02/native.png']
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
plan=dict(status='PREPARED_NAMED_CONTACT_GAP',baseline='dea7425a1e09752bd5102fc445bd2f84b96c0010',source_gap='Every16 current atlas cell inspected; no two-handed raised rim grip. Whole-card reuse preserves identity4.6 but native contact4.2/work semantics3.8 in all6 study views. Generate only a new connected static panning contact pose, reusing established identity/costume/pan design references.',inventory=[dict(path=rel(refs[0]),sha256=sha(refs[0]),regions=16,directly_inspected=True,reuse_failure='Idle/travel/wave/point/crystal/low palm poses do not grip the pan. Work0 palms rest low on the slab.'),dict(path=rel(refs[1]),sha256=sha(refs[1]),reuse='Approved source design4.6 retained as exact visual authority; current oversized detached mounting fails the contact purpose.')],references=[dict(path=rel(p),sha256=sha(p),role=r) for p,r in zip(refs,['identity_costume_full_fin_only','pan_identity_material_geometry_only'])],prompt_path=rel(out/'PROMPT.txt'),prompt_sha256=sha(out/'PROMPT.txt'),generation_method='builtin_imagegen_new_static_contact_pose',attempt=1,transparent_background=True,production_binding_changed=False,required_evidence=['Native alpha/neutral-source direct review','Exact prompt/reference/native hashes','Native 1280/1600 task view and inherited input placement audit','Separate static contact from complete motion/routes/device/child/owner'],owner_approval=None)
(out/'PLAN.json').write_text(json.dumps(plan,indent=2)+'\n',encoding='utf-8')
shutil.copyfile(__file__,out/'executed_prepare_geologist_contact_v126.py')
ip=b/'design/audit_impacts/job-pan-painted-placement-20261001.json';d=json.loads(ip.read_text());d['scope']+=' New continuation: generate one separately versioned connected static panning contact pose for the documented missing raised two-hand rim grip. Preserve all previous unchanged-actor reuse studies and their failed gesture scores. Existing costume/identity and pan material design are bound references, with no production source or reward/input edits.';d['rules']=sorted(set(d['rules'])|{'DL-ASSET-04','DL-ASSET-05','DL-INT-03'});d['files']=sorted(set(d['files'])|{rel(p) for p in out.rglob('*') if p.is_file()});d['validation'].append(dict(command='Direct16-cell geologist atlas inventory and6-view reuse study before generation',result='PASS',evidence='audit/job_pan_actor_contact_study_v1_20261001/REVIEW.json; panning pose3.8 remains a named generation gap'))
ip.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8');print(json.dumps(dict(path=rel(out),prompt=prompt,references=[str(p) for p in refs])))
