from pathlib import Path
import json,hashlib,datetime,html,shutil
from PIL import Image
r=Path.cwd();f=r/'assets_src/imagegen/day1_playroom_sign_v2_20261001';out=f/'native_hall_fit_v3';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
c=json.loads((out/'CAPTURE_RECEIPT.json').read_text());write(out/'VISUAL_REVIEW.json',{'status':'ALL_FOUR_SETTLED_STATIC_VIEWS_INSPECTED','views':[dict(v,directly_viewed=True,individual_sign_score=4.6 if 'candidate' in v['path'] else 4.5,whole_hall_frame_score=None) for v in c['views']],'opinion':'All four original/candidate complete canvases directly inspected after separate viewport-stage reconstruction and a0.65-second settle of the existing room fade. Candidate bear stays a recognizable warm teddy at the actual sign scale, with two complete ears, navy contour and a continuous cream/gold scalloped ring. The50–77px-scale face remains distinct from the neighboring paint palette, water drop and bubbles. The flatter painted shading follows the named design language and removes the original top-ring interruption. Individual static candidate sign4.6 at both widths; whole-hall/action/route/device/child/owner scores are not inherited.'})
p=f/'attempt_02_whole_canvas_256.png';profile=json.loads((f/'NORMALIZATION_PROFILE.json').read_text());profile.update(output=p.relative_to(r).as_posix(),output_sha256=sha(p),normalizer='normalize_whole_canvas.gd',normalizer_sha256=sha(f/'normalize_whole_canvas.gd'),complete_canvas_preserved=True,selected_for_review=True,runtime_bound=False);write(f/'NORMALIZATION_PROFILE.json',profile)
a=json.loads((f/'ATTEMPT_02_REVIEW.json').read_text());a.update(status='SOURCE_AND_UNBOUND_STATIC_SIGN_FIT_PROVISIONAL_4_6',mounted_score=4.6,mounted_evidence='native_hall_fit_v3/VISUAL_REVIEW.json',runtime_bound=False,owner_approved=False);write(f/'ATTEMPT_02_REVIEW.json',a)
review={'id':'D1N-0072','status':'REPLACEMENT_DRAFT_4_6_ORIGINAL_STILL_BOUND','updated_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original':{'path':'assets/flats/castle/main_hall_redraw_2026-08-03/signs/sign_playroom.png','sha256':'22d9a3df8eda3b95ae93250165a64a947b4157a70b4405f90dc4d600edccd7df','source_score':4.5,'priority':True,'opinion':'Friendly honey-brown teddy and warm border already fit the playroom. A short flat dark/tan/cream fragment at twelve o’clock breaks the scalloped ring. This is a named coherence defect, not a missing bear or canvas-edge clipping.'},'attempts':[{'attempt':1,'path':'attempt_01_native.png','sha256':sha(f/'attempt_01_native.png'),'score':4.4,'material_score':4.3,'decision':'REJECTED_FURRY_MATERIAL','opinion':'The repaired ring is coherent4.6, but plush/fur strokes and more lifelike shading exceed the game’s broad matte painted bands. Preserve this rejected fresh candidate.'},{'attempt':2,'path':'attempt_02_native.png','sha256':sha(f/'attempt_02_native.png'),'score':4.6,'decision':'PROVISIONAL_SOURCE_SELECTION','opinion':a['opinion']}],'normalized_review_file':p.relative_to(r).as_posix(),'normalized_sha256':sha(p),'static_native_sign_score_1280':4.6,'static_native_sign_score_1600':4.6,'native_evidence':'native_hall_fit_v3/VISUAL_REVIEW.json','earlier_fixture_limits':['native_hall_fit_v1/VISUAL_REVIEW.json','native_hall_fit_v2/VISUAL_REVIEW.json'],'technical':'Native generator originals preserved unchanged. Uniform1254-square whole-canvas resize to175-square and centered transparent padding to256-square; no crop, mask, warp, subject editing or copied reference pixels. Existing sign node scale/position/depth were reused only in the diagnostic fit.','gaps':'Original remains bound. These are static exact-node fits with a directly centered hall fixture, not ordinary touch navigation, all-hall approval, device/child/owner acceptance or a whole-game4.5 pass. The original remains an inclusive priority until a later bounded binding/review.'};write(f/'REVIEW.json',review)
helpers=f/'review_tools';helpers.mkdir(exist_ok=True)
for name in ['run_playroom_sign_hall_fit_v1.py','run_playroom_sign_hall_fit_v2.py','run_playroom_sign_hall_fit_v3.py','prepare_playroom_sign_refinement_v2.py']:
 if (r/'tmp'/name).exists():shutil.copyfile(r/'tmp'/name,helpers/name)
style='body{margin:0;background:#eef3fa;color:#273249;font:17px/1.5 system-ui}main{max-width:1160px;margin:auto;padding:24px}section,article{background:white;border-radius:16px;padding:20px;margin:18px 0}img{display:block;max-width:100%;height:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.grid article{margin:0}a{color:#56409b}.icon{background:#ddd9ee;padding:12px;box-sizing:border-box}.weak{border-left:5px solid #b1565f}small{display:block;color:#4c5570}code{overflow-wrap:anywhere}'
body=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Playroom teddy sign — individual reversible refinement</title><style>'+style+'</style><main><h1>D1N-0072: playroom teddy sign</h1><p>Replacement draft4.6 for source style and the inspected static doorway fits. The original4.5 sign remains in the game. This opinion does not grant owner approval or a whole-hall pass.</p><nav><a href="../../../audit/job_artwork_refinement_live/index.html">All-jobs library</a> · <a href="REVIEW.json">Individual review and exact hashes</a> · <a href="PROFILE_AND_PROMPT.json">Source gap, existing-art inventory and first prompt</a></nav><section><h2>Named border defect and preserved first rejection</h2><div class="grid"><article class="weak"><h3>Original4.5: interrupted upper ring</h3><img class="icon" src="../../../assets/flats/castle/main_hall_redraw_2026-08-03/signs/sign_playroom.png" alt="Original teddy sign with flat upper border fragment"><p>'+html.escape(review['original']['opinion'])+'</p></article><article class="weak"><h3>Fresh attempt1:4.4, rejected material</h3><img class="icon" src="attempt_01_native.png" alt="Preserved rejected furry teddy medallion"><p>'+html.escape(review['attempts'][0]['opinion'])+'</p><a href="ATTEMPT_01_REVIEW.json">Exact first-attempt review</a></article></div></section><section><h2>Fresh attempt2: broad painted bands, complete scallops</h2><div class="grid"><article><img class="icon" src="attempt_02_native.png" alt="Fresh matte painted teddy medallion"><p>'+html.escape(a['opinion'])+'</p><a href="ATTEMPT_02_PROMPT.json">Exact second prompt</a> · <a href="ATTEMPT_02_REVIEW.json">Source and mounted opinions</a></article><article><h3>256px review file</h3><img class="icon" src="attempt_02_whole_canvas_256.png" alt="Complete candidate canvas normalized to existing padded sign footprint"><p>'+html.escape(review['technical'])+'</p><a href="NORMALIZATION_PROFILE.json">Whole-canvas provenance</a><small>Draft only; original and runtime binding unchanged.</small></article></div></section><section><h2>Actual native doorway fit after viewport and fade settle</h2><p>All four complete views directly inspected. The new face reads clearly beside the palette, water drop and bubbles, with its complete contour and top ring. The helper rebuilds the actual hall at each viewport and changes only this sign texture for the diagnostic; no ordinary route or touch interaction is claimed.</p>']
for width in [1280,1600]:
 body+=['<h3>'+str(width)+'×720</h3><div class="grid">']
 for kind in ['original','candidate']:body+=['<article><h4>'+kind.title()+' · '+('4.5' if kind=='original' else '4.6')+'</h4><img src="native_hall_fit_v3/'+str(width)+'_'+kind+'.webp" alt="Settled complete native '+kind+' sign view at'+str(width)+'"></article>']
 body+=['</div>']
body+=['<a href="native_hall_fit_v3/VISUAL_REVIEW.json">Direct review scope</a> · <a href="native_hall_fit_v3/CAPTURE_RECEIPT.json">Exact frame hashes and sign bounds</a> · <a href="native_hall_fit_v3/PROCESS_RECEIPT.json">Exact4.7.2 parser, inference, analyzer and source checks</a></section><section><h2>Preserved fixture problems</h2><p>Attempt1 resized an existing stage and exposed wide-frame fitting artifacts. Attempt2 reconstructed each stage but took the originals before the existing room fade settled. Both were retained and individually qualified; attempt3 is the settled comparison.</p><a href="native_hall_fit_v1/VISUAL_REVIEW.json">Attempt1 limitation</a> · <a href="native_hall_fit_v2/VISUAL_REVIEW.json">Attempt2 limitation</a></section><section><h2>Remaining acceptance</h2><p>'+html.escape(review['gaps'])+'</p></section></main></html>'];(f/'index.html').write_text('\n'.join(body)+'\n',encoding='utf-8')
lic=r/'ASSET_LICENSES.md';t=lic.read_text();rows=[]
for p in sorted(f.rglob('*')):
 if p.suffix.lower() not in ['.png','.webp']:continue
 rel=p.relative_to(r).as_posix()
 if f'`{rel}`' not in t:rows.append(f'| `{rel}` | OpenAI generated medallion and project-owned Godot diagnostic | Project review evidence; runtime/owner acceptance pending | '+('Uniform complete-canvas normalization; native preserved, no subject edits' if p.name=='attempt_02_whole_canvas_256.png' else 'Lossless complete native actual-hall readback; fixture scope and exact source hashes in adjacent receipts')+' |')
lic.write_text(t+'\n'+'\n'.join(rows)+'\n',encoding='utf-8')
attrs=r/'.gitattributes';t=attrs.read_text();line='assets_src/imagegen/day1_playroom_sign_v2_20261001/** -text';assert line not in t;attrs.write_text(t+'\n'+line+'\n',encoding='utf-8')
i=r/'design/audit_impacts/day-one-playroom-sign-v2-20261001.json';d=json.loads(i.read_text());d['scope']+=' Preserve two fresh text-only candidates and all12 native fixture views. First source4.4/material4.3 rejected; second source4.6. Whole-canvas normalization to the existing padded256 card and all four settled original/candidate native exact-sign-node views give candidate static fit4.6 at1280/1600. Earlier post-build resize and fade-timing fixture limitations stay explicit. Original remains bound; no interaction/global/owner pass.';d['validation']=[v for v in d['validation'] if v['command']!='Generated source identity/style and normalized native navigation fit'];d['validation'] += [{'command':'Exact4.7.2 native settled-static hall fit and direct all-four complete view review','result':'PASS','evidence':'assets_src/imagegen/day1_playroom_sign_v2_20261001/native_hall_fit_v3/PROCESS_RECEIPT.json and VISUAL_REVIEW.json; source/individual static sign4.6 only. Earlier fixture limitations preserved.'}];d['acceptance_gaps']=review['gaps'];d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in f.rglob('*') if p.is_file()}|{'.gitattributes','ASSET_LICENSES.md'});write(i,d)
print('Sign report, normalization,12 preserved native views and',len(rows),'new license rows written.')
