from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003';A=T/'attempt02';assert not A.exists();A.mkdir()
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-ee5c0143-3e9e-4b62-b303-ed2b31c5fbbf.png');shutil.copyfile(src,A/'native.png')
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
with Image.open(src) as im:dims=list(im.size);mode=im.mode;alpha=list(im.getchannel('A').getextrema())
plan=read(T/'PLAN_A2.json');assert sha(src)==sha(A/'native.png')
write(A/'SOURCE.json',dict(attempt=2,method='builtin_imagegen_precise_object_edit',original_path=str(src),native_path=(A/'native.png').relative_to(B).as_posix(),sha256=sha(src),dimensions=dims,mode=mode,alpha_extrema=alpha,prompt=plan['prompt'],prompt_sha256=plan['prompt_sha256'],references=[dict(path=plan['source_path'],sha256=plan['source_sha256'])],native_preserved=True,runtime_ready=False,runtime_bound=False,owner_acceptance=None))
r=read(T/'attempt01/DIRECT_REVIEW.json');r.update(status='REJECTED_TARGETED_EDIT_STILL_SIX_RINGS',reviewed_utc=now(),native_sha256=sha(src));r['opinions'][0]['evaluation']='The targeted edit still returns six rings: coral, peach, yellow, mint, aqua and lavender-grey. It changes shape/shading but does not insert a distinct apricot ring.';r['qualification']='Complete A2 native directly inspected; the same missing-apricot-ring defect persists. Source4.1 rejected, no runtime/motion/owner acceptance. A3 will use the existing design in words and only the approved material reference, avoiding a six-ring edit target.';write(A/'DIRECT_REVIEW.json',r)
prompt='''Paint ONE complete seven-ring stacking toy for a polished 2D children’s storybook game, isolated on a truly transparent background. Exactly SEVEN separate thick rounded donut rings are assembled on one central plum peg. Count the seven distinct curved front bands from the base upward:
1 bottom: coral-pink, widest.
2: pale peach, visibly its own ring above the coral.
3: apricot-orange, visibly its own ring above peach and below yellow.
4: butter-yellow.
5: mint-green.
6: powder-aqua.
7 top: pale lavender-grey, smallest.
There are THREE separate warm rings BELOW the yellow ring: coral, peach and apricot. The apricot band must not merge with peach or yellow. Each of the seven has its own clean plum contour and broad curved painted front face. All seven touch and decrease in diameter upward around the SAME peg; their diameter proportions from bottom to top are approximately100%,88%,76%,64%,52%,40%,28%. No ring is floating, absent or duplicated.
The gently tapered exposed plum peg ends in a safe rounded cap and carries one small pale-gold scallop-shell decoration. Below the seven rings is a low oval deep-plum pedestal with a gold top rim and one gold scallop-shell badge at its front. The pedestal and rim are not an eighth ring.
Use the supplied painted aqua/plum pouf ONLY for broad hand-painted satin light/midtone/lavender-shadow bands and rounded storybook finish. No cushion panels, beads or pouf design. Toy front three-quarter view, centered, complete top/base, generous transparent padding. Soft handmade rounded forms, clean plum contours, child-readable large bands, restrained highlights. Raster storybook painting, not flat vector, not photographed plastic or realistic3D.
Return one whole assembled toy only. No numbers/labels/text, no hands/characters/room/floor/shadow, no atlas or panels. Preserve seven-ring assembly, shell-base identity and the specified pastel color order.'''
write(T/'PLAN_A3.json',dict(status='SEVEN_RING_FRESH_LAYOUT_WORDS_WITH_ONLY_MATERIAL_REFERENCE_PLANNED',planned_utc=now(),attempt=3,changed_variable='Remove six-ring candidate as edit target; specify existing seven-ring object in words with count/color/diameter boundaries. Only the approved existing pouf supplies painted material style.',prior_failed_sources=[dict(path=(T/f'attempt{i:02d}/native.png').relative_to(B).as_posix(),sha256=sha(T/f'attempt{i:02d}/native.png'),whole_source_score=4.1,actual_ring_count=6) for i in [1,2]],reference_path='assets/flats/castle/dream_house/cloud_pouf.png',reference_sha256=sha(B/'assets/flats/castle/dream_house/cloud_pouf.png'),prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),required_ring_count=7,runtime_bound=False,owner_acceptance=None))
lic=B/'ASSET_LICENSES.md';raw=lic.read_bytes();path=(A/'native.png').relative_to(B).as_posix();assert ('| `'+path+'` |').encode() not in raw;raw+=('\n| `'+path+'` | Builtin ImageGen precise-object whole-source edit | Original generated project artwork with OpenAI; prior source attribution retained | SOURCE.json binds exact native/prompt/reference hashes | Complete original RGBA candidate preserved; six-ring count rejected, no production/owner acceptance. |\n').encode();n=lic.with_name(lic.name+'.v568_next');n.write_bytes(raw);n.replace(lic)
shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-playroom-painted-stacking-toy-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'][-1].update(result='FAIL',evidence=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix()+'; A2 still6 rings, whole4.1.');d['validation'].append(dict(command='A3 existing seven-ring layout in words, approved material-only reference',result='PENDING',evidence='PLAN_A3.json; no predicted count/style/source acceptance.'));write(ip,d)
print(json.dumps(dict(status='A2_SIX_RINGS_PRESERVED_A3_MATERIALLY_DIFFERENT_INPUT_PLANNED',actual_ring_count=6,whole_source_score=4.1,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())))
