from pathlib import Path
import datetime,hashlib,html,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003';A=T/'attempt01';assert not A.exists();A.mkdir()
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-7e0ea5a4-87fe-4e15-b853-5972e96bf3c9.png');shutil.copyfile(src,A/'native.png')
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
with Image.open(src) as im:dims=list(im.size);mode=im.mode;alpha=list(im.getchannel('A').getextrema())
assert sha(src)==sha(A/'native.png');plan=read(T/'PLAN.json')
write(A/'SOURCE.json',dict(attempt=1,method='builtin_imagegen_style_transfer',original_path=str(src),native_path=(A/'native.png').relative_to(B).as_posix(),sha256=sha(src),dimensions=dims,mode=mode,alpha_extrema=alpha,prompt=plan['prompt'],prompt_sha256=plan['prompt_sha256'],references=[dict(path=x,sha256=sha(B/x)) for x in plan['reference_paths']],native_preserved=True,runtime_ready=False,runtime_bound=False,owner_acceptance=None))
op=[('Exactly seven distinct conserved rings',2.0,'Only six distinct rings are present: coral, peach, yellow, mint, aqua and lavender-grey. The separate apricot ring is missing.'),('Rounded painted shape language',4.5,'Broad donut volumes and rounded plum cap replace the flat fills and sharp point. Painted mass reads clearly.'),('Established shell/base identity',4.5,'One low plum/gold base and its front gold scallop badge remain; the exposed peg has its matching small shell.'),('Material bands and contour',4.5,'Soft broad satin bands and clean plum separation fit the painted family; highlights remain somewhat glossy.'),('Complete canvas and transparency',4.5,'Whole toy and clear outer padding are present on native RGBA; no background remnants or detached source fragments.'),('Assembled rest-state support',4.4,'The visible six rings rest as a readable continuous stack, but the absent seventh invalidates conservation against the intended object.'),('Whole assembled source',4.1,'Rejected for wrong ring count. Painted quality alone cannot override topology or pass the source against the specific seven-ring design.')]
write(A/'DIRECT_REVIEW.json',dict(status='REJECTED_SIX_RINGS_INSTEAD_OF_SEVEN',reviewed_utc=now(),direct_complete_native_review=True,native_sha256=sha(src),whole_source_score=4.1,actual_ring_count=6,required_ring_count=7,opinions=[dict(item=i,score=s,evaluation=e,priority=s<=4.5) for i,s,e in op],qualification='Complete original native directly inspected. Source-only, rejected; no runtime/motion/owner acceptance. Preserve the failed native while inserting the missing apricot ring in a separate candidate.',runtime_bound=False,owner_acceptance=None))
prompt='''Use case: precise-object-edit
Image1 is the complete painted stacking-toy candidate to repair. Preserve its painted storybook style, plum peg with rounded cap and gold shell, all existing six rings, gold-rimmed plum base, front shell badge, three-quarter view, clean contours and true alpha background.
It has ONLY SIX rings. Insert ONE missing rounded APRICOT-ORANGE donut ring between the peach ring and the butter-yellow ring. The final whole toy must have EXACTLY SEVEN clearly separate rings, from bottom to top: coral-pink, peach, apricot-orange, butter-yellow, mint-green, powder-aqua, pale lavender-grey. Count them individually before returning. The apricot ring is a full distinct ring, with a visible curved front band, central peg hole and its own plum boundary; it is not a painted stripe on peach or yellow. All seven decrease in diameter toward the top and rest on one another around the same peg.
Return one complete whole toy centered with generous transparent padding, not an atlas or crop. Let the stack accommodate the added ring naturally while preserving the same design. No additional ring, extra badge, hands, room, text, panel borders, vector-flat fills, realistic3D render or detached shadow. This is the assembled rest state only.'''
write(T/'PLAN_A2.json',dict(status='TARGETED_MISSING_APRICOT_RING_REPAIR_PLANNED',planned_utc=now(),attempt=2,source_path=(A/'native.png').relative_to(B).as_posix(),source_sha256=sha(A/'native.png'),source_rejection='Only six of required seven rings; whole source4.1',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),required_ring_count=7,originals_preserved=True,runtime_bound=False,owner_acceptance=None))
lic=B/'ASSET_LICENSES.md';raw=lic.read_bytes();path=(A/'native.png').relative_to(B).as_posix();assert ('| `'+path+'` |').encode() not in raw
raw+=('\n| `'+path+'` | Builtin ImageGen painted whole stacking-toy candidate | Original generated project artwork with OpenAI; original game/style source attribution retained | SOURCE.json records prompt/reference/native hashes | Exact complete RGBA original, separate non-runtime candidate; six-ring topology rejected, no destructive edit or acceptance. |\n').encode();n=lic.with_name(lic.name+'.v567_next');n.write_bytes(raw);n.replace(lic)
shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-playroom-painted-stacking-toy-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'][1].update(result='FAIL',evidence=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix()+'; A1 has6 rings, whole4.1. Painted quality does not accept wrong topology.');d['validation'].append(dict(command='Targeted A2 missing-apricot-ring whole-source repair',result='PENDING',evidence='PLAN_A2.json; no predicted seven-ring or source quality pass.'));write(ip,d)
print(json.dumps(dict(status='A1_WRONG_RING_COUNT_PRESERVED_A2_PLANNED',native_dimensions=dims,alpha=alpha,actual_rings=6,required_rings=7,whole_source_score=4.1,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())))
