from pathlib import Path
import copy,datetime,hashlib,html,json,os,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003';L=B/'audit/job_artwork_refinement_live';P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003';S=B/'audit/job_shared_background_review_v1_20261003';A=T/'attempt03';assert not A.exists();A.mkdir()
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-012215cd-8370-4f18-9561-b2711f38d7cc.png');shutil.copyfile(src,A/'native.png')
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();esc=lambda x:html.escape(str(x))
def put(p,raw):n=p.with_name(p.name+'.v569_next');n.write_bytes(raw);n.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
with Image.open(src) as im:dims=list(im.size);mode=im.mode;alpha=list(im.getchannel('A').getextrema());bbox=list(im.getchannel('A').getbbox())
assert sha(src)==sha(A/'native.png');plan=read(T/'PLAN_A3.json')
write(A/'SOURCE.json',dict(attempt=3,method='builtin_imagegen_new_whole_object_material_reference',original_path=str(src),native_path=(A/'native.png').relative_to(B).as_posix(),sha256=sha(src),dimensions=dims,mode=mode,alpha_extrema=alpha,alpha_bbox=bbox,prompt=plan['prompt'],prompt_sha256=plan['prompt_sha256'],references=[dict(path=plan['reference_path'],sha256=plan['reference_sha256'],role='painted_material_only')],object_design_authority='Existing seven-ring toy documented in PLAN.json reuse inventory and PLAN_A3.json',native_preserved=True,runtime_ready=False,runtime_bound=False,owner_acceptance=None))
opinions=[('Exactly seven distinct conserved rings',4.5,'Seven separate bands are now present in order: coral, peach, apricot, yellow, mint, aqua, lavender-grey. The pedestal is separately identifiable and not counted as a ring.'),('Rounded painted shape language',4.5,'Broad rounded bands and safe plum peg cap replace flat fills and the sharp dark spike; the stepped silhouette is readable.'),('Established shell/base identity',4.5,'Low plum/gold base and front shell badge preserve the same established toy motif; one small matching peg-shell remains.'),('Material bands and contour',4.5,'Painted satin highlights, colored midtones and plum contact separations match the current storybook prop family. Gloss remains a refinement priority at the inclusive floor.'),('Complete canvas and transparency',4.5,'Complete whole RGBA toy is preserved with no background or source fragments. Bottom alpha padding is tight; provide whole-canvas technical padding before any eventual runtime conversion.'),('Assembled rest-state support',4.5,'All seven bands visibly rest as one contiguous ordered stack around the same central peg. This still does not establish ring motion through the peg.'),('Whole assembled source',4.5,'Provisional static drafting floor for the assembled toy. Original whole sheet3.0 and its actual use/action scores remain unchanged; eight-state conservation and in-game mounting/phone/child/owner acceptance remain open.')]
write(A/'DIRECT_REVIEW.json',dict(status='SEVEN_RING_ASSEMBLED_SOURCE_4_5_PROVISIONAL_ONLY',reviewed_utc=now(),direct_complete_native_review=True,native_sha256=sha(src),whole_source_score=4.5,actual_ring_count=7,required_ring_count=7,opinions=[dict(item=i,score=s,evaluation=e,priority=s<=4.5) for i,s,e in opinions],qualification='Complete original native directly inspected. Seven-ring assembled still reaches4.5 source-only drafting floor and remains an inclusive priority. No atlas/action/runtime/device/child/owner acceptance; preserve rejected A1/A2 six-ring originals.',runtime_bound=False,owner_acceptance=None))
css='body{font:18px/1.5 system-ui;max-width:1100px;margin:30px auto;padding:20px;background:#edf4fa;color:#25344b}a{color:#504096}img{display:block;max-width:100%;height:auto;background:repeating-conic-gradient(#dae5ee 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}article,header{background:white;border-radius:18px;padding:22px;margin:24px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}li{margin:12px 0}.pair{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}small{overflow-wrap:anywhere}'
body='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Painted seven-ring stacking toy</title><style>'+css+'</style><header><h1>Painted seven-ring stacking toy</h1><p>Current whole source D2X-0065:3.0/5. Three new originals were generated and individually reviewed. A1/A2 each4.1 rejected for six rings; A3 reaches4.5 for the assembled seven-ring still. No current runtime replacement or complete motion pass.</p><p><a href="../../../audit/job_artwork_refinement_live/all_items.html">Individual artwork library</a> · <a href="../../../audit/job_shared_background_review_v1_20261003/index.html#D2X-0065">Current source review</a> · <a href="PLAN.json">Reuse inventory and initial prompt</a></p></header><article><h2>Existing object and reusable material style</h2><div class="pair"><div><img src="../../../assets/flats/castle/interactions_v2/playroom_stacking_toy_sheet.png" alt="Unchanged current eight-state flat toy atlas"><p>Current source3.0; original preserved.</p></div><div><img src="../../../assets/flats/castle/dream_house/cloud_pouf.png" alt="Unchanged painted material reference"><p>Existing painted pouf4.6; material-only reference.</p></div></div></article>'
for i in [1,2,3]:
 a=T/f'attempt{i:02d}';r=read(a/'DIRECT_REVIEW.json');s=read(a/'SOURCE.json');items=''.join('<li><strong>'+esc(x['item'])+' · '+str(x['score'])+'/5</strong>: '+esc(x['evaluation'])+'</li>' for x in r['opinions'])
 section='<article id="attempt'+str(i)+'"><h2>A'+str(i)+' · '+str(r['whole_source_score'])+'/5 · '+str(r['actual_ring_count'])+' rings</h2><p>'+esc(r['status'])+'</p><a href="attempt'+str(i).zfill(2)+'/native.png"><img src="attempt'+str(i).zfill(2)+'/native.png" width="'+str(s['dimensions'][0])+'" height="'+str(s['dimensions'][1])+'" alt="Complete native painted toy attempt'+str(i)+'"></a><ul>'+items+'</ul><p>'+esc(r['qualification'])+'</p><p><a href="attempt'+str(i).zfill(2)+'/SOURCE.json">Native/reference/prompt provenance</a> · <a href="attempt'+str(i).zfill(2)+'/DIRECT_REVIEW.json">Individual evaluations</a></p><details><summary>Exact ImageGen prompt</summary><pre>'+esc(s['prompt'])+'</pre></details></article>'
 body+=section
body+='</html>';put(T/'index.html',body.encode())
write(T/'COMPLETE_SOURCE_REVIEW.json',dict(status='ALL3_NATIVE_SOURCES_AND21_INDIVIDUAL_COMPONENT_OPINIONS_REVIEWED',reviewed_utc=now(),attempts=[dict(path=(T/f'attempt{i:02d}/native.png').relative_to(B).as_posix(),sha256=sha(T/f'attempt{i:02d}/native.png'),review=read(T/f'attempt{i:02d}/DIRECT_REVIEW.json')) for i in [1,2,3]],selected_source=(A/'native.png').relative_to(B).as_posix(),qualification='A3 selected for subsequent authored states and fit review only. All original game sources/runtime remain unchanged. All three source opinions remain separate; no source prestige transfer.'))
lic=B/'ASSET_LICENSES.md';raw=lic.read_bytes();path=(A/'native.png').relative_to(B).as_posix();assert ('| `'+path+'` |').encode() not in raw;raw+=('\n| `'+path+'` | Builtin ImageGen whole painted seven-ring source | Original generated project artwork with OpenAI; established object and material reference attribution retained | SOURCE.json binds exact native/prompt/reference hashes | Exact complete RGBA original preserved; assembled still4.5 provisional only, no destructive replacement, runtime, motion or owner acceptance. |\n').encode();put(lic,raw)
for name,target in [('ALL_ITEMS.json','ALL_ITEMS_V47.original.json'),('all_items.html','all_items_V47.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V47.original.json')]:assert not (L/target).exists();shutil.copyfile(L/name,L/target)
reg=read(L/'ALL_ITEMS.json');assert reg['display_revision']=='V47' and len(reg['items'])==2044
tmpl=next(x for x in reg['items'] if x['id']=='CANDY-M-SOURCE-13')
for i in [1,2,3]:
 a=T/f'attempt{i:02d}';s=read(a/'SOURCE.json');r=read(a/'DIRECT_REVIEW.json');z=copy.deepcopy(tmpl)
 for key in ['region','parent_source_id','label','latest_refinement']:z.pop(key,None)
 z.update(id=f'PLAY-STACK-SOURCE-{i:02d}',aliases=[f'PLAY-STACK-SOURCE-{i:02d}'],kind='source',path=s['native_path'],earlier_sha256=s['sha256'],current_checkout_sha256=s['sha256'],historical_source_score=None,current_source_score=r['whole_source_score'],evaluation=r['opinions'][-1]['evaluation'],refinement='For A1/A2 preserve missing-apricot-ring rejection. A3 needs independent eight-state ring conservation/contact/loop and actual game fit before any binding.',families=['Day Two shared','Playroom','Unbound stacking-toy replacements'],original_reports=[T.relative_to(B).as_posix()+'/index.html'],source_qualification=r['qualification']+' Native NPOT review source is not runtime-ready.',preview_path=s['native_path'],image_path=s['native_path'],image_scope='Complete preserved original assembled toy; no crop or motion acceptance',native_reference_observations=[],current_byte_status='EXACT_REVIEWED_GENERATION_BYTES',source_dimensions=s['dimensions'],priority=True,protected_original=False,current_mounted_score=None,current_complete_action_score=None,individual_review_utc=r['reviewed_utc'],latest_refinement=dict(report=T.relative_to(B).as_posix()+'/index.html#attempt'+str(i),note=r['qualification']))
 reg['items'].append(z)
old=next(x for x in reg['items'] if x['id']=='D2X-0065');assert old['current_source_score']==3.0;old['latest_refinement']=dict(report=T.relative_to(B).as_posix()+'/index.html',note='Three separately preserved source candidates; A1/A2 six-ring4.1 rejected, A3 seven-ring assembled4.5 provisional, unbound. Current whole atlas/action scores unchanged.')
pri=[x for x in reg['items'] if x.get('current_source_score') is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3']];unique={x['path'] for x in pri if x['kind'] in ['source','runtime source']};pending=[x for x in reg['items'] if x['kind']=='source' and x.get('current_source_score') is None]
assert len(reg['items'])==2047 and len(pri)==950 and len(unique)==661 and len(pending)==294
reg['counts'].update(unique_source_files=1283,registered_items=2047,inclusive_current_source_priorities=950,unique_source_file_priorities=661,unreviewed_current_source=294,new_painted_stacker_sources=3)
reg.update(display_revision='V48',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v48.py',scope='V48:2047 known entries/1283 primary sources/328 pose cells/151 runtime-use-action entries/285 source object regions.950 inclusive source-cell-region priorities/661 unique source-file priorities/294 unreviewed primary sources.65 existing omitted shared originals directly reviewed. Three new whole stacking-toy sources preserve6-ring A1/A2 failures4.1 and selected7-ring A3 assembled still4.5 provisional. All164 Candy local frames/40 component opinions reviewed; A3 1.5/A4 0.8 rejected. Current WRAP2.8 and783 production members unchanged. No complete source-cell/action/all-job/owner/integration/release acceptance.')
reg['current_byte_status_counts']['EXACT_REVIEWED_GENERATION_BYTES']+=3
reg['review_resources'].append(dict(path=T.relative_to(B).as_posix()+'/index.html',scope='Three whole toy sources/21 individual component opinions; A1/A2 six rings4.1 rejected, A3 seven-ring assembled4.5 provisional only.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304
shutil.copyfile(L/'review_tools/refresh_current_job_review_v47.py',L/'review_tools/refresh_current_job_review_v48.py')
notice='<p><a href="../../assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003/index.html">New painted stacking toy: three whole originals/21 individual opinions</a> · A1/A2 six rings4.1 rejected; A3 seven-ring assembled still4.5 provisional. V48:2047 entries/950 inclusive source-cell-region priorities/661 unique source priorities/294 primary sources still unreviewed. Existing source and game action acceptance remain separate.</p>'
for name in ['index.html','all_items.html']:
 t=(L/name).read_text(encoding='utf-8').replace('refresh_current_job_review_v47.py','refresh_current_job_review_v48.py');t=t.replace('<h1>',notice+'<h1>',1);put(L/name,t.encode())
p=S/'index.html';t=p.read_text();t=t.replace('<h1>','<p><a href="../../assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003/index.html">Three reversible painted stacking-toy candidates</a>: seven-ring A3 assembled4.5 provisional, current atlas3.0 unchanged.</p><h1>',1);put(p,t.encode())
summary='Painted stacking-toy continuation (2026-10-03): [three preserved whole natives and21 individual component opinions](TOY) directly reviewed after six-source reuse inventory. A1/A2 each4.1 rejected for only six rings; A3 has seven distinct conserved rings and reaches assembled still4.5 provisional, unbound. Current whole atlas D2X-0065 stays3.0; eight-state conservation/contact, mounted job/training, device/child/owner/comprehensive report acceptance remain open. V48 known2047 entries/1283 primary sources/950 source-cell-region priorities/661 unique source priorities/294 unreviewed primary sources. All65 newly assigned shared opinions and164 Candy local frames remain separate; current game WRAP2.8/all783 literal production members unchanged. Finding lifecycle, integration and release unchanged.'
for path,link in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003/index.html')]:
 p=B/path;t=p.read_text();note=summary.replace('TOY',link)
 if path.endswith('MASTER_AUDIT_2026-08-09.md'):
  for marker in ['## 0. Planning entry','## Development task index']:assert marker in t;t=t.replace(marker,marker+'\n\n'+note,1)
 else:i=t.index('\n')+1;t=t[:i]+'\n'+note+'\n'+t[i:]
 put(p,t.encode())
p=B/'design/05_DOC_LEDGER.md';t=p.read_text();t+='\n| `assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; six-source reuse inventory/three preserved whole native candidates/21 component opinions. A1/A2 six-ring4.1 rejected; A3 seven-ring assembled4.5 provisional only, no runtime/action/owner acceptance. |\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V47.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact2044-entry register after65 existing omitted source opinions and before three new whole assembled stacking-toy candidates. |\n';put(p,t.encode())
shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-playroom-painted-stacking-toy-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()});d['validation'][-1].update(result='PASS',evidence=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix()+'; seven distinct rings and assembled source4.5 provisional. Exact failed A1/A2 preserved; no motion/runtime pass.');d['acceptance_gaps']='Selected A3 assembled still4.5 is an inclusive priority, not an eight-state/action/game fit pass. Current whole source3.0 remains unchanged. Phone-size edge hierarchy, ring-through-peg contact/loop, runtime conversion, job/training/device/child/owner/comprehensive report acceptance remain open.';write(ip,d)
ip=B/'design/audit_impacts/job-candy-shared-library-continuation-20261003.json';d=read(ip);d['scope']+=' V48 adds three separately preserved painted toy source opinions after the named six-source reuse gap; current runtime source remains3.0.';d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS_V47.original.json','all_items_V47.original.html','BOUNDARY_V47.original.json','review_tools/refresh_current_job_review_v48.py']});write(ip,d)
allow=B/'tmp/v2_preview_allowed.json';allowed=read(allow);write(allow,sorted(set(allowed)|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}))
res=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v48.py')],cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);assert res.returncode==0,res.stderr.decode();print(res.stdout.decode().strip());assert read(L/'CURRENT_BOUNDARY_REFRESH.json')['registered_source_matches']==2047
print(json.dumps(dict(status='A3_SEVEN_RING_SOURCE_SAVED_REGISTER_V48',dimensions=dims,alpha_bbox=bbox,source_score=4.5,registered_items=2047,inclusive_priorities=950,unique_priority_sources=661,primary_unreviewed=294,register_bytes=(L/'ALL_ITEMS.json').stat().st_size)))
