from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003';assert not T.exists();T.mkdir(parents=True);(T/'review_tools').mkdir()
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
paths=['assets/flats/castle/rooms/room_playroom_item_stacking_toy.png','assets/flats/castle/interactions/playroom_stacking_toy_atlas.png','assets/flats/castle/interactions_v2/playroom_stacking_toy_sheet.png','assets_src/imagegen/castle_object_animations_v2/play_craft_pool/playroom_stacking_toy_sheet_chroma.png','assets_src/blender/qa_pearl_castle_kit/pearl_rainbow_stacker.png','assets/flats/castle/dream_house/cloud_pouf.png']
notes=[('3.0','Existing tiny room crop has flat toy bands and surrounding background fragments; not a clean reusable painted source.'),('1.8','Legacy atlas carries large upper background remnants and missing horizontal object bands; unsuitable reuse.'),('3.0','Current eight-state atlas preserves seven rings and shell base but has flat uniform fills and a sharp dark peg.'),('3.0','Original magenta source contains the same flat design and pointed peg; transparent derivation cannot fix its painted-material gap.'),('2.5','Legacy model-render concept is a different design/material and superseded3D lane; not a runtime/model fallback.'),('4.6','Already-reviewed painted aqua/plum pouf supplies broad painted material bands and rounded contour only; no pouf design enters the toy.')]
inventory=[]
for path,(score,note) in zip(paths,notes):
 p=B/path
 with Image.open(p) as im:dims=list(im.size);mode=im.mode
 inventory.append(dict(path=path,sha256=sha(p),dimensions=dims,mode=mode,direct_original_review=True,source_score=float(score),evaluation=note,reusable_for_requested_whole_stacker=path==paths[-1],role='material_style_only' if path==paths[-1] else 'existing_reuse_inventory'))
prompt='''Use case: style-transfer / illustration-story
Asset type: one whole assembled interactive stacking-toy source, transparent RGBA, for the Mermaid Roshan polished 2D storybook game.
Image1 is the current eight-state stacking-toy sheet. Use only its FIRST TOP-LEFT toy as the exact object design/layout authority. Return ONE whole assembled toy, not an atlas. Image2 is material/style reference only: its rounded painted aqua/plum forms and broad satin value bands. Do not add pouf cushions, bead strings or upholstery to the toy.
Redraw the toy as a polished painted 2D raster illustration. Preserve the low oval deep-plum base with golden top rim and single small golden scallop-shell badge at its front. Preserve exactly SEVEN stacked rounded donut rings, decreasing in diameter from bottom to top: coral-pink, peach, apricot, pale butter yellow, mint green, powder aqua, pale lavender-grey. All seven have one central hole around the same peg. The peg is plum and gently tapered; soften its exposed tip into a small rounded toy cap, no sharp spike. Keep the small pale-gold shell decoration on the exposed lower peg.
Complete toy centered, mild elevated front three-quarter view matching Image1, clearly visible full base and top, 10 percent transparent padding on every side. All rings rest on one another; no floating rings or missing/duplicated ring. Broad hand-painted light/midtone/lavender-shadow bands, restrained highlights, clean plum contours, matte-to-satin painted toy finish. Friendly oversized child-readable forms. Match the game’s painted storybook props rather than flat vector fills, realistic 3D plastic, photography, PBR, grainy texture, white sticker rims or thin scratchy outlines.
True transparent background; no room, floor, detached cast shadow, hands, characters, text, labels, panel borders, atlas cells or additional object. Preserve the original object identity and seven-ring physical assembly. This is only its assembled rest state, not an animation or accepted runtime asset.'''
write(T/'PLAN.json',dict(status='ONE_NAMED_FLAT_STACKING_TOY_GAP_REGENERATION_PLANNED',planned_utc=now(),baseline='ae3880df4244139a4f681034b530a5ee2c68895d',source_item='D2X-0065',current_whole_source_score=3.0,scope='Only complete assembled rest-state painted replacement; preserve seven rings/base/shell design and original source/atlases. No new room scene or runtime replacement.',reuse_inventory=inventory,generated_gap='Existing reusable sources cannot supply painted broad value bands, clean contours and rounded exposed peg without redraw. Current material-style reference is reusable but is a different prop.',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),reference_paths=[paths[2],paths[-1]],required_evidence=['Complete returned native/alpha/dimensions/hash preserved','Individual whole-source and topology/material/style evaluations','Regenerate named failed feature if below4.5','Independent eight-state sequence/runtime/game/device/child/owner acceptance remains open'],runtime_bound=False,owner_acceptance=None))
write(B/'design/audit_impacts/job-playroom-painted-stacking-toy-20261003.json',dict(id='job-playroom-painted-stacking-toy-20261003',scope='Reversibly regenerate only the named D2X-0065 flat-material stacking-toy assembled source after all relevant existing sources were inventoried. Preserve seven-ring geometry and established shell-base palette; soften the exposed sharp peg. All originals and current runtime preserved.',baseline='ae3880df4244139a4f681034b530a5ee2c68895d',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-04','DL-VIS-05','DL-VIS-07','DL-MED-01','DL-READ-01','DL-READ-02','DL-READ-03','DL-MOT-10','DL-MOT-11','DL-QA-03','DL-QA-07'],findings=['MA-VIS-006','MA-PLAY-004'],files=[(T/'PLAN.json').relative_to(B).as_posix(),(T/'review_tools'/Path(__file__).name).relative_to(B).as_posix()],validation=[dict(command='Inventory and directly inspect all six relevant existing source/style candidates',result='PASS',evidence=(T/'PLAN.json').relative_to(B).as_posix()+'; exact dimensions/hashes/reuse gap.'),dict(command='Builtin ImageGen whole assembled source and direct review',result='PENDING',evidence='No predicted source/topology/style/runtime acceptance.')],acceptance_gaps='Assembled source only; eight-state ring conservation/peg passage/contact/loop, actual mounted job/training use, phone/device/child/owner and complete report acceptance remain open.'))
shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name);print(json.dumps(dict(status='STACKER_REUSE_GAP_AND_PROMPT_RECORDED',references=6,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())))
