from pathlib import Path
import datetime, hashlib, json, shutil, sys
root=Path(sys.argv[1]);family=root/'assets_src/imagegen/geologist_river_components_v1_20261001';family.mkdir(exist_ok=False)
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
refs=['assets/opera/worlds/geology/painted_work_v1_20261001/pan.png','assets/opera/worlds/geology/painted_work_v1_20261001/work_slab.png','assets/opera/worlds/geology/painted_work_v1_20261001/fossil_soil.png']
inventory=dict(checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),named_gap='Actual river dry grid3.5 and wet line/circle channels3.8 lack painted excavation components.',current_native_evidence='audit/job_geology_painted_work_v1_20261001/attempt_04/native_views/geologist_1280_river_earned_completion.webp',mechanics='9x5 cells; any source-connected excavated path can reach the target. Isolated excavations remain dry. No fixed four-connection requirement.',scoped_named_search=['assets/opera','assets_src/concepts','assets_src/imagegen'],named_search_result=[dict(path='assets_src/imagegen/combat_tutorial_2026-08-01/training_grotto_backdrop_native.png',dimensions=[1774,887],suitability='Full room reference, no isolated excavated channel; undersize as native2048x2048 background.')],reviewed_reuse=[dict(path=p,sha256=sha(root/p),material_score=4.6,limitation='Useful painted palette/material reference. None supplies top-down circular excavation and straight open channel silhouettes.') for p in refs],generation_limit='One bounded four-prop source sheet first; retry only individually failed components. Preserve native files and every opinion. No room/background/character redesign, no runtime binding or motion acceptance.')
write(family/'REUSE_INVENTORY.json',inventory);(family/'.gdignore').write_text('',encoding='utf-8')
prompt='''Create one transparent RGBA sprite source sheet for the Mermaid Roshan geology river-digging activity. A polished hand-painted 2D picture-book toy-playset language: broad gouache cream/ochre value bands, aqua/lavender shadows, confident dark-plum contours, rounded handmade masses and very sparse grouped detail. Clearly illustrated and tactile, not photographic, not flat vector, not a 3D render. The three bound pictures are MATERIAL/PALETTE REFERENCES ONLY: IMAGE_1 supplies quiet painted aqua water and lavender edges; IMAGE_2 supplies warm cream stone, broad lavender shading and plum contour; IMAGE_3 supplies warm earth. Do not reproduce their basin/slab/soil-bed shapes or perspective.

Exactly FOUR separate complete props on a genuinely transparent square canvas in a roomy 2x2 arrangement. No connecting pieces, board, labels, numbers, tile frames, fake transparency checks, cast shadows outside silhouettes or extra objects. Every prop has a complete clean outer contour, generous transparent separation and ample outer margins. Paint all four in an EXACT TOP-DOWN orthographic view, no visible front face or perspective ellipse.

UPPER LEFT: one round shallow excavated earth hole, about380x380 at a1024 sheet scale: chunky softly irregular cream/ochre rim, plum outer contour, lavender inside-edge shade, calm warm ochre dry floor. UPPER RIGHT: the SAME round excavation design and outer contour, filled with luminous calm aqua water, two broad hand-painted pale reflection strokes. The painted rim stays fully around the water.

LOWER LEFT: one horizontal straight excavated channel, about440x130 at a1024 sheet scale: softly rounded ends, thick matching cream/ochre lips along the long sides, plum outer contour, lavender depth edge, dry warm-ochre floor. LOWER RIGHT: the SAME horizontal channel shape, filled with calm aqua water, two broad pale painted reflections. Keep each channel long and straight so copies can connect between round excavation nodes. End shapes are blunt-rounded, not tapered forks. Water stays inside the rim. Major dark contours are intentionally bold enough to read at54px node size in a child's game; edges have gentle painted variation rather than mathematically perfect vector curves. Keep the core interiors calm with no noise, gravel scattering, crystal, fossil, hands, characters, text or UI. Square1024x1024 composition; actual transparent background.'''
(family/'PROMPT_ATTEMPT_01.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(family/'GENERATION_PENDING.json',dict(status='PROMPT_RECORDED_BEFORE_GENERATION',prompt_path=family.relative_to(root).as_posix()+'/PROMPT_ATTEMPT_01.txt',prompt_sha256=sha(family/'PROMPT_ATTEMPT_01.txt'),reference_paths=refs,reference_sha256=[sha(root/p) for p in refs],method='BUILTIN_CODEX_IMAGEGEN',transparent_background=True,attempt=1,source_acceptance=None,runtime_binding=False))
shutil.copyfile(Path(__file__),family/Path(__file__).name)
write(root/'design/audit_impacts/job-geology-river-painted-source-20261001.json',dict(id='job-geology-river-painted-source-20261001',baseline='e1b431f49258eef1d293b11a732353f0a3aa12e9',scope='Continue the owner-commissioned reversible in-job regeneration into the remaining named river graphics gap. Inventory shows no suitable isolated top-down excavation/channel shapes; use the existing painted pan/slab/soil only as material references. Generate and individually audit four bounded dry/wet components outside runtime; preserve all originals/attempts. Keep9x5 arbitrary connected excavation, original job code and current full-CI349-source boundary unchanged. No background/character redraw, production binding or visual/owner/global acceptance.',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08'],findings=['MA-PLAY-004','MA-VIS-006'],files=sorted(p.relative_to(root).as_posix() for p in family.rglob('*') if p.is_file()),validation=[dict(command='Reuse inventory and actual native river inspection',result='PASS',evidence=family.relative_to(root).as_posix()+'/REUSE_INVENTORY.json; direct current1280 dry/wet stills. PASS means inventory/read coverage; graphics remain3.5/3.8.'),dict(command='Native ImageGen source and each of four components',result='PENDING',evidence='No image generated or directly reviewed yet.')],acceptance_gaps='Generation/native individual source review pending. Actual mounting, transition/contact/timeline, ordinary route/training/story, physical device, child and owner remain open. Existing current full suite does not validate an unbound new source as runtime.'))
print('RIVER_GAP184|inventory/prompt/hash/rules recorded before generation; no frozen runtime change')
