from pathlib import Path
from PIL import Image
import datetime,hashlib,html,json,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'audit/job_source_review_hall_craft_v1_20261001';assert not out.exists();out.mkdir();(out/'.gdignore').write_text('')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
rows=[]
signroot='assets/flats/castle/main_hall_redraw_2026-08-03/signs/'
for name,note in [
 ('sign_bubble_bath.png','Three soft ivory bubbles sit on a scalloped cream/gold badge. Warm dark contours and one broad pearl highlight fit the painted toy-playset language. The bubbles remain distinct; actual wayfinding meaning at the mounted scale is a separate review.'),
 ('sign_craft_room.png','The rounded paint palette and brush carry distinct pastel paint dots inside the common shell badge. Warm-brown contour, cream frame and restrained painted highlights keep the emblem coherent with the other room icons. Small brush-tip readability requires the mounted view.'),
 ('sign_mermaid_pool.png','One aqua drop is immediately distinct against the cream badge. Its broad graphic highlight, plum rim and simple mass fit the icon family; there is no tiny text dependency in this source. Navigation/context acceptance remains separate.'),
 ('sign_playroom.png','A rounded teddy face, clear ears and simple smile read coherently inside the shell badge. Warm brown/plum lines and soft peach fills fit the playful room family. This source opinion does not pass the actual route or child recognition test.')]:
 p=signroot+name;im=Image.open(r/p);rows.append({'id':'HALL-SOURCE-'+name.removesuffix('.png').upper(),'path':p,'sha256':sha(r/p),'dimensions':list(im.size),'source_score':4.6,'evaluation':note,'complete_action_score':None,'mounted_score':None,'direct_review':'Exact whole PNG directly viewed at original resolution in this continuation.'})
manifestpath='assets/flats/castle/interactions_v2/castle_interactions_v2.json';manifest=json.loads((r/manifestpath).read_text());assets={x['id']:x for x in manifest['assets']}
specs=[
 ('idea_board',4.5,[4.5]*8,'Cream shell framing, pastel paper shapes and brown/plum contours fit the room. The small low-contrast note pictures and densely arranged paint jars keep the source at the drafting floor; mounted note-flip clarity and target emphasis remain priorities.'),
 ('paint_table',4.4,[4.5,4.4,4.4,4.4,4.4,4.4,4.5,4.5],'The shell-trimmed table is coherent, but the primary moving brush is thin and low-emphasis beside many tiny supplies. Several brush states are fragile at small scale. Preserve the table art and test a stronger local working brush before commissioning a whole furniture redraw.'),
 ('palette',4.5,[4.6,4.5,4.5,4.5,4.5,4.5,4.6,4.6],'The broad pastel palette wells and rounded wheeled shell cart fit the room. Brush contact and pigment differences are small compared with the supply detail, so the full sheet stays at the source floor. Mixing direction, well contact and the visible colour consequence require the native action.'),
 ('ribbon_rack',4.6,[4.6]*8,'Broad pastel ribbons, rounded gold rod ends and clear separated strips form a strong intact painted prop. The pink ribbon extension is visible in the authored cells. Rod position varies across cells; do not infer a stable unroll/retract sequence or invent a continuity defect without the actual configured timeline and mounted capture.')]
cells=[]
for name,score,cell_scores,note in specs:
 p='assets/flats/castle/interactions_v2/craft_room_'+name+'_sheet.png';im=Image.open(r/p);spec=assets['craft_room_'+name];assert spec['grid']==[4,2] and list(im.size)==[spec['cell_size'][0]*4,spec['cell_size'][1]*2]
 rows.append({'id':'CRAFT-SOURCE-'+name.upper(),'path':p,'sha256':sha(r/p),'dimensions':list(im.size),'source_score':score,'evaluation':note,'complete_action_score':None,'mounted_score':None,'direct_review':'All eight authored cells visible in the exact whole native PNG directly viewed at original resolution. This is static cell review, not a played timeline.','declared_timeline':spec['timeline_sequence'],'timeline_frame_duration_seconds':spec['frame_duration_seconds'],'semantic_action':spec['semantic_action'],'historical_source_acceptance':spec['normalized_use_review']})
 for n,cell_score in enumerate(cell_scores):
  x,y=n%4,n//4;w,h=spec['cell_size'];cells.append({'id':'CRAFT-'+name.upper()+'-CELL-%02d'%n,'path':p,'sha256':sha(r/p),'source_dimensions':list(im.size),'region':[x*w,y*h,w,h],'cell_index':n,'source_score':cell_score,'evaluation':note+' Individually inspected atlas cell%d, column%d/row%d. The declared source/timeline mapping is recorded, but its actual mounted action is not passed.'%(n,x,y),'complete_action_score':None,'mounted_score':None})
review={'status':'PARTIAL_INDIVIDUAL_SOURCE_AND_STATIC_CELL_REVIEW','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_items':rows,'prop_cells':cells,'source_count':8,'prop_cell_count':32,'whole_native_pngs_directly_viewed':8,'all_declared_32_cells_directly_viewed':True,'source_manifest':{'path':manifestpath,'sha256':sha(r/manifestpath)},'rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-03','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-READ-01','DL-MOT-11','DL-MOT-12'],'qualification':'Exact unchanged source PNGs and32 static cells assessed. Existing approved art is preserved; the September30 idea-board transparency successor is inspected as current bytes. A declared resource/reference or historical source approval does not prove visible pixels, current mounted quality, complete action, phone, child or owner acceptance. No regeneration is authorized merely by a style preference; reuse/local refinement is the first option for the named thin-brush/readability gap.'}
(out/'REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
sourcecards=''.join('<article><h2>'+html.escape(x['id'])+' · '+str(x['source_score'])+'/5</h2><img src="../../'+x['path']+'" alt="'+html.escape(x['id'])+'"><p>'+html.escape(x['evaluation'])+'</p><small>'+html.escape(x['path'])+' · '+x['sha256']+'</small></article>' for x in rows)
cellcards=''
for x in cells:
 scale=220/max(x['region'][2:]);w,h=x['source_dimensions'];rx,ry,rw,rh=x['region'];style='width:%gpx;height:%gpx;left:%gpx;top:%gpx'%(w*scale,h*scale,-rx*scale+(220-rw*scale)/2,-ry*scale+(220-rh*scale)/2)
 cellcards+='<article><h3>'+html.escape(x['id'])+' · '+str(x['source_score'])+'/5</h3><div class="cell"><img style="'+style+'" src="../../'+x['path']+'" alt="'+html.escape(x['id'])+' exact unchanged region"></div><p>'+html.escape(x['evaluation'])+'</p><small>Region '+str(x['region'])+'; whole-source hash '+x['sha256']+'</small></article>'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hall and craft: individual source audit</title><style>body{margin:0;background:#eef4f8;color:#25334b;font:17px/1.55 system-ui}main{max-width:1300px;margin:auto;padding:24px}header,article{background:white;padding:20px;border-radius:16px;margin-bottom:18px}h1,h2,h3{line-height:1.25}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:20px}article{min-width:0}article>img{width:100%;height:330px;object-fit:contain;background:repeating-conic-gradient(#dce5ed 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}small,a{overflow-wrap:anywhere}small{display:block;font-size:12px}.cell{width:220px;height:220px;margin:auto;position:relative;overflow:hidden;background:repeating-conic-gradient(#dce5ed 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}.cell img{position:absolute;max-width:none;object-fit:fill}</style><main><header><a href="../job_review_v2_20261001/index.html">Current review entry</a><h1>Hall and craft: eight source images and32 prop cells</h1><p>Every source PNG and every declared cell below was directly inspected. Scores are first-pass source opinions. Original art remains unchanged.</p><p>The paint-table brush reads weakly at small scale,4.4. Idea-board and palette sheets sit at the source floor4.5; note-flip clarity and mixing contact/consequence remain priorities. Ribbon artwork4.6 does not pass its unroll/retract timeline; current mounted actions, phone, child and owner review remain pending.</p><p><a href="REVIEW.json">Complete individual evaluations, hashes and timeline declarations</a></p></header><h2>Whole source images</h2><div class="grid">'''+sourcecards+'''</div><h2>Every craft prop cell</h2><p>These are CSS views of exact source regions with one uniform scale. No appearance pixels, contour or source file were edited.</p><div class="grid">'''+cellcards+'''</div></main></html>'''
(out/'index.html').write_text(page,encoding='utf-8');shutil.copyfile(Path(__file__),out/'executed_review_hall_and_craft_sources_v10.py')
old=r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v3.py';new=old.with_name('build_current_job_item_register_v4.py');assert not new.exists();code=old.read_text().replace('import datetime, hashlib, json, shutil, subprocess, posixpath','import datetime, hashlib, json, shutil, subprocess, posixpath\nfrom PIL import Image')
needle='hashes={}';addition="""# Current individual hall/craft source and exact prop-cell opinions.
hallcraft=read('audit/job_source_review_hall_craft_v1_20261001/REVIEW.json')
for opinion in hallcraft['source_items']:
 p=opinion['path'];q=items[p];q['earlier_written_evaluation']=q['evaluation'];q['earlier_preview_path']=q['preview_path'];q['preview_path']=p;q['latest_source_score']=opinion['source_score'];q['latest_source_sha256']=opinion['sha256'];q['evaluation']=opinion['evaluation'];q['source_qualification']='Current exact whole source directly inspected; static/source opinion only; mounted/actions remain pending.';q['latest_refinement']=dict(report='audit/job_source_review_hall_craft_v1_20261001/index.html',note='Eight whole native PNGs and32 static prop cells directly inspected; no complete current action or mounted acceptance.',evidence=opinion)
for opinion in hallcraft['prop_cells']:
 ident=opinion['id'];items[ident]=dict(id=ident,aliases=[],kind='runtime prop region',path=opinion['path'],region=opinion['region'],source_dimensions=opinion['source_dimensions'],earlier_sha256=opinion['sha256'],historical_source_score=opinion['source_score'],evaluation=opinion['evaluation'],refinement='Test actual configured timeline, work contact, visible consequence and quiet return at native scale; source floor is not complete action acceptance.',families=['Day One craft room','Static individual prop-cell review'],original_reports=['audit/job_source_review_hall_craft_v1_20261001/index.html'],source_qualification='Declared runtime atlas region, current exact source directly viewed; mounted/action/device/child/owner scores unassigned.',preview_path=opinion['path'],native_reference_observations=[],latest_refinement=dict(report='audit/job_source_review_hall_craft_v1_20261001/index.html',note='Exact static cell/source opinion; actual played timeline remains unreviewed.'))
"""
assert needle in code;code=code.replace(needle,addition+needle)
code=code.replace("q['priority']=q['current_source_score']", "if 'source_dimensions' not in q and p.endswith(('.png','.jpg','.jpeg','.webp')):q['source_dimensions']=list(Image.open(r/p).size)\n q['priority']=q['current_source_score']")
code=code.replace('additional_runtime_prop_regions=6','additional_runtime_prop_regions=sum(q[\'kind\']==\'runtime prop region\' for q in rows)').replace('build_current_job_item_register_v3.py','build_current_job_item_register_v4.py').replace('pool prop regions =','prop regions =').replace('240 source pose cells and6 current pool prop regions','240 source pose cells,6 current pool regions and32 individually inspected craft prop regions')
# Generate uniform source-region previews using actual atlas dimensions, never a forced square atlas.
start=code.index("html=html.replace('src=\"");end=code.index("html=html.replace('<figure><img loading=",start)
code=code[:start]+"html=html.replace('let registry,filtered=[],page=0;', \"const regionStyle=q=>{const s=220/Math.max(q.region[2],q.region[3]),d=q.source_dimensions;return 'position:absolute;width:'+(d[0]*s)+'px;height:'+(d[1]*s)+'px;left:'+(-q.region[0]*s+(220-q.region[2]*s)/2)+'px;top:'+(-q.region[1]*s+(220-q.region[3]*s)/2)+'px;object-fit:fill'};let registry,filtered=[],page=0;\")\nhtml=html.replace('src=\"${esc(url(q.image_path))}\" alt=', 'src=\"${esc(url(q.image_path))}\" ${q.kind===\\'runtime prop region\\'&&q.image_path===q.path?\\'style=\"\\'+regionStyle(q)+\\'\"\\':\\'\\'} alt=')\n"+code[end:]
new.write_text(code,encoding='utf-8');subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(new)],cwd=r,check=True)
p=r/'design/05_DOC_LEDGER.md';s=p.read_text();s+='\n| `audit/job_source_review_hall_craft_v1_20261001/index.html` | 🟣 | `CANDIDATE`; eight directly inspected whole native source images and32 individually reviewed static craft prop cells. Source scores are bounded first-pass opinions; existing artwork is unchanged and configured timelines, mounted/action/device/child/owner acceptance remain open. |\n';p.write_text(s,encoding='utf-8')
p=r/'audit/job_review_v2_20261001/index.html';s=p.read_text();s=s.replace('</main>','<section><h2>Hall and craft individual sources</h2><p><a href="../job_source_review_hall_craft_v1_20261001/index.html">Eight exact sources and32 individual prop cells</a>; the table brush4.4 and source-floor notes/palette remain priorities. Full current actions are pending.</p></section></main>');p.write_text(s,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in out.rglob('*') if x.is_file()]+[new.relative_to(r).as_posix()]));d['scope']+=' Review eight exact hall/craft sources and32 individual prop cells, preserve approved originals and identify local brush/readability gaps; correct gallery source-region scaling using actual atlas dimensions without changing any game or art source.';d['validation'].append({'command':'Direct whole hall/craft source and32 static-cell review','result':'PENDING','evidence':'audit/job_source_review_hall_craft_v1_20261001/REVIEW.json; source evaluations recorded, actual configured/mounted actions and browser region layout remain pending.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'source_items_directly_reviewed':8,'static_prop_cells_directly_reviewed':32,'sources_changed':0,'gallery_uniform_region_scale':'Browser review pending'}))
