from pathlib import Path
import json,hashlib,datetime,shutil,html
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');packet=b/'assets_src/local_motion/day2_geologist_pan_motion_v2_20261001';out=packet/'attempt_01';retry=b/'assets_src/local_motion/day2_geologist_pan_motion_v3_20261001';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-geologist-panning-local-motion-20261001.json';d=json.loads(ip.read_text());d['scope']+=' Individually review all41 second native frames and preserve its below-floor3.8 motion. Prepare a third comparable prompt-only trial: simplify the instruction to clear repeated left/right rocking. Source/input/seed/settings/model/workflow remain identical; no new source generation or runtime/cinematic delivery.';write(ip,d)
cat=json.loads((out/'FRAME_CATALOG.json').read_text());rows=[]
for v0 in cat['native_frames']:
 v=dict(v0);i=v['index'];assert sha(packet/v['path'])==v['sha256']
 if i<=4:phase='entry';ev='Stable recognizable painted identity and connected rim grips. Small water changes do not establish panning. No obvious spilling.';act=None;ret=None;body=4.6;rigid=4.6
 elif i<=15:phase='intended left roll';ev='The vessel rises/flattens slightly as a nearly level bowl. No clear left-down/right-up roll is visible. Grips and child identity remain; restrained body movement cannot substitute for the missing verb.';act=3.2;ret=None;body=4.5;rigid=4.4
 elif i<=27:phase='intended reversal';ev='The bowl stays almost level with minor water/shape changes. Directional reversal remains unreadable, though both hands are attached. Fewer exterior water marks than attempt1; water is mostly inside.';act=3.2;ret=None;body=4.5;rigid=4.4
 else:phase='intended neutral return';ev='Pan/hands gradually lower and move left; they do not restore the starting pose. Head and torso drift slightly. Painted identity and full fin remain, but no clean loop or neutral return is accepted.';act=3.8;ret=3.8;body=4.4;rigid=4.4
 v.update(visual_review='DIRECT_NATIVE_ORIGINAL_RESOLUTION',reviewed_utc=now,phase=phase,scores=dict(painted_identity=4.6 if i<5 else 4.5,hand_rim_contact=4.5,body_stability=body,vessel_rigidity=rigid,water_containment=4.4,intended_action=act,neutral_return=ret),evaluation=ev,owner_approval=None,runtime_accepted=False);v['visual_score']=min(s for s in v['scores'].values() if s is not None);rows.append(v)
assert len(rows)==41;qualification='All41 original896x512 frames directly inspected,82 across the two attempts. Scores are separate state/phase opinions, not an average that hides the failed action. No angles or pixel distances claimed as measurements. Local Wan reference is not runtime/cinematic delivery or owner acceptance.'
review=dict(status='ALL41_DIRECTLY_REVIEWED_MOTION_RETRY_REQUIRED',reviewed_utc=now,source_score=4.6,motion_reference_score=3.8,alternating_panning_score=3.2,neutral_return_score=3.8,hand_contact_score=4.5,water_containment_score=4.4,frames=rows,qualification=qualification,previous_attempt='assets_src/local_motion/day2_geologist_pan_motion_v1_20261001/attempt_01/REVIEW.json');write(out/'REVIEW.json',review);cat.update(status=review['status'],native_frames=rows,visual_review=rel(out/'REVIEW.json'));write(out/'FRAME_CATALOG.json',cat)
head='<!doctype html><meta charset="utf-8"><style>body{font:18px/1.5 system-ui;color:#302949;background:#eef5f4;max-width:1200px;margin:auto;padding:24px}article{background:white;padding:20px;margin:24px 0}img,video{width:100%;height:auto}small{overflow-wrap:anywhere}</style>'
cards=['<article><h2>Frame '+str(v['index'])+' · '+format(v['timestamp_seconds'],'.3f')+'s · '+v['phase']+'</h2><img loading="lazy" src="native_frames/'+Path(v['path']).name+'" alt="Native frame '+str(v['index'])+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+': '+str(s)+'/5' for k,s in v['scores'].items() if s is not None))+'</p><small>SHA256 '+v['sha256']+'</small></article>' for v in rows]
(out/'index.html').write_text(head+'<h1>Panning attempt2 —3.8/5; retry required</h1><p>Alternating action3.2/return3.8/grip4.5/water4.4. Source remains4.6. Every41 frame shown with separate criteria.</p><video controls src="native_output.mp4"></video><p>'+html.escape(qualification)+'</p><a href="REVIEW.json">Individual evaluations/hashes</a>'+''.join(cards),encoding='utf-8')
m=json.loads((packet/'MANIFEST.json').read_text());assert sha(out/'MANIFEST_AT_SUBMISSION.json')==json.loads((out/'WORKER_STATE.json').read_text())['manifest_sha256'];m.update(output_state='Native machine PASS;41 frames directly reviewed; motion3.8/action3.2/return3.8 remain below floor. Input/settings/seed unchanged.',visual_review='attempt_01/REVIEW.json');write(packet/'MANIFEST.json',m)
(packet/'index.html').write_text(head+'<h1>Second panning motion —3.8/5</h1><p>More contained water; alternating action3.2 and return3.8 still fail. Every41 original frame individually reviewed; no production acceptance.</p><video controls src="attempt_01/native_output.mp4"></video><p><a href="attempt_01/index.html">Every native frame/evaluation</a> · <a href="MANIFEST.json">Current status</a> · <a href="attempt_01/MANIFEST_AT_SUBMISSION.json">Exact original submission</a> · <a href="../day2_geologist_pan_motion_v3_20261001/index.html">Short action-prompt retry</a></p>',encoding='utf-8')
retry.mkdir(exist_ok=False);(retry/'.gdignore').write_text('');shutil.copytree(packet/'workflows',retry/'workflows');shutil.copytree(packet/'inputs',retry/'inputs');(retry/'prompts').mkdir()
prompt='''She actively washes the pan by rocking it from side to side. Both hands grip the rim. She lowers the LEFT side while raising the RIGHT side, then reverses and lowers the RIGHT side while raising the LEFT. Repeat this clear rocking once, then settle back into the starting level pose. Her elbows and wrists bend to move the rigid pan; her head, torso and curled mermaid tail stay quiet. Water swishes inside without spilling. Preserve this exact painted child, outfit, full fin and pan design. Fixed camera and plain aqua background. No extra objects or body movement. Sound: silence.'''
(retry/'prompts/geologist_pan_full_source.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n');worker=retry/'run_geologist_comfy_pan_v146.py';worker.write_text((packet/'run_geologist_comfy_pan_v142.py').read_text().replace('day2_geologist_pan_motion_v2_20261001','day2_geologist_pan_motion_v3_20261001').replace('geologist_local_pan_study_v2_20261001','geologist_local_pan_study_v3_20261001'),encoding='utf-8',newline='\n')
rm=json.loads((out/'MANIFEST_AT_SUBMISSION.json').read_text());rm.update(id='DAY2-GEOLOGIST-PAN-LOCAL-V3',previous_attempt=rel(out/'REVIEW.json'),visual_review=None,output_state='Prepared shorter action-first prompt trial; no visual score.',worker_sha256=sha(worker));rm['job'].update(id='GEO-PAN-MOTION-REFERENCE03',queue_name='d2m_geologist_pan_v3_20261001',prompt_sha256=sha(retry/'prompts/geologist_pan_full_source.txt'))
for binding in rm['renderer']['bindings']:
 if binding['packet_path']=='workflows/render_gguf.py':binding['installed_path']=str(retry/'workflows/render_gguf.py')
 assert sha(retry/binding['packet_path'])==binding['sha256']
assert sha(retry/'inputs/geologist_pan_full_source.png')==rm['job']['input_sha256'] and rm['job']['seed']==2026100134;write(retry/'MANIFEST.json',rm)
profile=json.loads((packet/'PROFILE.json').read_text());profile.update(status='PREPARED_SHORTER_PROMPT_REFERENCE_RETRY',previous_motion_review=rel(out/'REVIEW.json'),phases={'ready':'starting level grip','work':'two clear alternating left/right rocks','settle':'return to starting level grip'},single_changed_factor='Shorter action-first prompt only. Source/input/seed/settings/workflow identical.');write(retry/'PROFILE.json',profile);write(retry/'COMPARABILITY.json',dict(source_and_input_identical=True,seed_identical=True,settings_identical=True,workflow_bindings_identical=True,changed_factor='Prompt only, simplified active verb',previous_prompt_sha256=m['job']['prompt_sha256'],new_prompt_sha256=rm['job']['prompt_sha256'],source_sha256=rm['job']['source_sha256'],input_sha256=rm['job']['input_sha256'],previous_motion=3.8,qualification=qualification));shutil.copyfile(__file__,retry/'executed_prepare_retry_v146.py');shutil.copyfile(__file__,out/'executed_record_review_v146.py')
(retry/'index.html').write_text(head+'<h1>Panning attempt3 — shorter active prompt</h1><p>Prepared; no visual score. Same source/input/seed/settings/workflow. Previous two attempts preserve all82 directly reviewed native frames; both motion3.8.</p><img src="inputs/geologist_pan_full_source.png" alt="Unchanged model input"><p><a href="prompts/geologist_pan_full_source.txt">Exact simplified action prompt</a> · <a href="MANIFEST.json">Bindings</a> · <a href="COMPARABILITY.json">Comparable trial</a></p><p>LOCAL_MOTION_REFERENCE_ONLY; no production/cinematic/owner acceptance.</p>',encoding='utf-8')
with (b/'ASSET_LICENSES.md').open('a',encoding='utf-8',newline='\n') as f:f.write('\n| `'+rel(retry/'inputs/geologist_pan_full_source.png')+'` | Byte-identical original complete-canvas geologist model input | OpenAI generated output terms; original project art | https://openai.com/policies/terms-of-use/ | No new pixels; prompt-only motion trial. SHA256 '+rm['job']['input_sha256']+' |\n')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();s+='\n| `'+rel(retry/'index.html')+'` | 🟣 | `CANDIDATE_REFERENCE_ONLY`; shorter action prompt with identical source/input/seed/workflow/settings. Previous two attempts82 native frames individually inspected; both motion3.8; current output unscored until direct review. |\n';ledger.write_text(s,encoding='utf-8')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Panning reference retry2 (2026-10-01): [every41 second native frame](../'+rel(out/'index.html')+') directly reviewed;82 across two attempts. Motion3.8/action3.2/return3.8/grip4.5/water4.4 remain separate. [Third prompt-only study](../'+rel(retry/'index.html')+') uses a shorter action-first instruction with unchanged source/input/seed/settings/workflow. No runtime/cinematic/route/device/child/owner acceptance.';s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+entry+'\n',1);master.write_text(s,encoding='utf-8')
d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(p) for prefix in [packet,retry] for p in prefix.rglob('*') if p.is_file()});d['validation'].append(dict(command='Direct original-resolution inspection of every41 second native frame',result='PASS',evidence=rel(out/'REVIEW.json')+'; inspection complete, action3.2 and return3.8 remain failed.'));write(ip,d);allow=b/'tmp/v2_preview_allowed.json';a=set(json.loads(allow.read_text()));a.update(d['files']);write(allow,sorted(a));print('Second41 DIRECT;82 total; third prompt-only worker prepared')
