from pathlib import Path
import shutil
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');F=R/'audit/job_geology_complete_actions_v1_20261003'
s=(R/'assets_src/local_motion/nursery_connected_scrub_v4_20261002/review_tools/publish_nursery_review_s_v432.py').read_text(encoding='utf-8')
for a,b in [('tmp/nursery_review_s_publish_v432','tmp/geology_review_t_publish_v455'),('tmp/nursery_review_s_remote_v432','tmp/geology_review_t_remote_v455'),('tmp/nursery_review_s_sealed_v428.json','tmp/geology_review_t_sealed_v456.json'),('EXACT_SCOPED_MOTION_SOURCE_S_BLOBS_SEALED','EXACT_SCOPED_GEOLOGY_T_BLOBS_SEALED'),("==1802","==1821"),('37083138864','37086150331'),('HOSTED_R_FINAL.json','HOSTED_S_FINAL.json'),('EXACT_PARENT_R_HOSTED_FINAL','EXACT_PARENT_S_HOSTED_FINAL'),('WAITING_EXACT_PARENT_R_HOSTED_COMPLETION_NO_CANCEL','WAITING_EXACT_PARENT_S_HOSTED_COMPLETION_NO_CANCEL'),('Exact parent R','Exact parent S'),('PUBLISHED_NURSERY_SOURCE_TOPIC_REVISION','PUBLISHED_GEOLOGY_REVIEW_TOPIC_REVISION')]:
 assert a in s,a;s=s.replace(a,b)
a="for label in ('game2d','authority','development','document_tests'):\n assert read(R/'assets_src/local_motion/nursery_connected_scrub_v4_20261002/gates'/(label+'_v1.receipt.json'))['status']=='PASS',label\nassert read(R/'assets_src/local_motion/nursery_connected_scrub_v4_20261002/REVIEW_STATUS.json')['status']=='MACHINE_RENDER_COMPLETE_VISUAL_REJECTED'"
b="C=R/'audit/job_geology_complete_actions_v1_20261003'\nfor label in ('game2d_compact_v2','authority','development','document_tests'):\n assert read(C/'gates'/(label+'.receipt.json'))['status']=='PASS',label\ncr=read(C/'DIRECT_REVIEW.json');assert cr['consecutive_frames']==884 and all(x['direct_review'] for x in cr['frames']+cr['views'])\nassert read(R/'audit/job_geology_painted_invitation_fit_v1_20261003/DIRECT_REVIEW_ATTEMPT03.json')['whole_fit_score']==4.2\nassert read(R/'assets_src/imagegen/geologist_specimen_tray_v1_20261003/attempt01/DIRECT_SOURCE_REVIEW.json')['runtime_binding'] is False"
assert a in s;s=s.replace(a,b)
start=s.index("msg=out/'COMMIT_MESSAGE.txt'");end=s.index("run('commit'",start)
message='Record complete geology action audit and reversible painted tray trials\n\nInspect every884 consecutive actual fossil and panning input/wait frame,58 selected full canvases,85 ordered boards and34 original native details at1280/1600. Record22 individual material,object,contact,transition and complete-action opinions. Fossil3.2/pan3.4/contact2.7 remain weak despite reusable painted materials4.5–4.6. Preserve first failed capture and exact helper retry, actual earned Library return and separate Opera elevator replay. Existing rooted geode opening/celebration remains unchanged. No production source or gameplay change.\n\nGenerate one fresh text-only painted specimen tray after named-gap reuse inventory. Preserve exact1254-square native RGBA,prompt/generation hashes and all6 source opinions; complete source4.6/alpha4.5/110px readability4.5 remain provisional. Capture and individually inspect all58 selected native canvases plus8 original invitation details for each of three unbound counterfactual layouts. Preserve A1 actor overlap3.5 and A2 oversized support3.8/whole4.0; A3 three small conserved supports achieves selected material/scale/clearance4.5 but whole room4.2 remains below floor. Production flat room2.8/trays2.9 and working contact/action are independently weak. No complete counterfactual travel or source-to-runtime acceptance.\n\nRefresh illustrated register to1821 individually addressable entries:1264 source files,328 pose cells,103 runtime use/action/prop entries and126 source-object regions.713 known source/cell/region priorities,572 unique file priorities including two runtime-source entries,38 current Geologist and10 Nursery mounted/action priorities;377 source reviews outstanding. Retain exact V39 register/page/boundary history. Preserve complete immutable S16023-file anonymous verification and exact hosted success.\n\nNew register indentation exceeded unchanged4MiB signature scan budget. Preserve all failed gate outputs and exact preformat bytes in bounded reconstructible shards; compact only JSON whitespace with identical structured objects/all1821 values. No scanner/debt-manifest/gate weakening. Fresh existing authority,coverage,52 document tests and corrected2D no-regression pass. Strict-zero2D and creative acceptance remain unsatisfied. Postcommit existing gates run before topic push and all required closed-map files are anonymously byte-verified.\n\nNo protected original,production code/art,security/workflow change,rejected reference upload/browser status action,owner approval,finding lifecycle closure,complete all-job/device/child acceptance,dev/master integration or release.\n'
s=s[:start]+"msg=out/'COMMIT_MESSAGE.txt';msg.write_text("+repr(message)+",encoding='utf-8',newline='\\n')\n"+s[end:]
s=s.replace("print('EXACT_PARENT_S_HOSTED_FINAL',hosted['conclusion'],flush=True);break","assert hosted['conclusion']=='success';print('EXACT_PARENT_S_HOSTED_FINAL',hosted['conclusion'],flush=True);break")
s=s.replace('Durable topic review checkpoint only. Visual/current-action/all-job/device/child/owner/integration/release remain open; blocked imagegen reference upload remains blocked.','Durable geology action/source/three-trial review checkpoint only. All783 production bytes unchanged. Current fossil3.2/pan3.4/contact2.7/room2.8 remain weak. New tray4.6 and A3 selected prop floors4.5 remain unbound; whole counterfactual room4.2. Complete all-job/device/child/owner/integration/release and both exact rejected upload/browser-status actions remain open.')
target=F/'review_tools/publish_geology_checkpoint_t_v455.py';assert not target.exists();compile(s,str(target),'exec');target.write_text(s,encoding='utf-8',newline='\n');shutil.copyfile(Path(__file__),F/'review_tools'/Path(__file__).name)
print('T_PUBLISHER_PREPARED_NOT_EXECUTED')
