from pathlib import Path
import json,shutil,datetime,hashlib
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');F=R/'audit/job_geology_complete_actions_v1_20261003';ip=R/'design/audit_impacts/job-geology-complete-action-register-20261003.json'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
patterns=['audit/job_geology_complete_actions_v1_20261003/**','audit/job_geology_painted_invitation_fit_v1_20261003/**','assets_src/imagegen/geologist_specimen_tray_v1_20261003/**','audit/job_artwork_refinement_live/registry_format_history_v40/**','audit/job_artwork_refinement_live/ALL_ITEMS_V39.original.json','audit/job_artwork_refinement_live/all_items_V39.original.html','audit/job_artwork_refinement_live/BOUNDARY_V39.original.json']
attrs=R/'.gitattributes';raw=attrs.read_bytes();s=raw.decode('utf-8');assert all(x+' -text' not in s for x in patterns)
extra='\n# Exact geology action/placement provenance, native outputs and register history.\n'+'\n'.join(x+' -text' for x in patterns)+'\n';attrs.write_bytes(raw+extra.encode('utf-8'))
receipt=F/'RAW_PUBLICATION_ATTRIBUTES_V459.json';write(receipt,dict(status='EXACT_NEW_REVIEW_PATHS_PRESERVE_LITERAL_BYTES',checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),prior_attributes_sha256=hashlib.sha256(raw).hexdigest(),current_attributes_sha256=hashlib.sha256(attrs.read_bytes()).hexdigest(),new_patterns=patterns,reason='Initial scoped staged-byte verification caught CRLF-to-LF conversion in authority.stdout.log. Retain all literal diagnostic/native/source-history hashes via same existing -text review packet pattern. No original/source pixel changes or CI/security/gate weakening. Restage only exact scoped files with attributes respected.',production_source_change=False,owner_acceptance=None))
d=read(ip);d['files']=sorted(set(d['files'])|{'.gitattributes',receipt.relative_to(R).as_posix(),(F/'review_tools'/Path(__file__).name).relative_to(R).as_posix()});d['scope']+=' Add exact new non-runtime review paths/history -text attributes so all raw Windows diagnostics and native-source evidence retain literal published bytes; first staged verification caught line-ending conversion before any commit/push. Reprocess only scoped index files. No production/security/workflow/gate change.';write(ip,d);shutil.copyfile(Path(__file__),F/'review_tools'/Path(__file__).name)
print('EXACT_QA_RAW_BYTE_ATTRIBUTES_ADDED|NO_PRODUCTION_OR_GATE_CHANGE')
