from pathlib import Path
import datetime,hashlib,json,shutil,html,copy
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
F=R/'audit/job_geology_complete_actions_v1_20261003';P=R/'audit/job_geology_painted_invitation_fit_v1_20261003';T=R/'assets_src/imagegen/geologist_specimen_tray_v1_20261003';L=R/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
frows=[]
def opinion(id,label,score,note,repair,lane,view):
 frows.append(dict(id=id,label=label,score=score,priority=score<=4.5,evaluation=note,refinement=repair,lane=lane,evidence_view_index=view,owner_acceptance=None))
opinion('GEO-FOSSIL-SOIL','Soil material on the supported fossil',4.6,'Rounded pebbles, warm gouache and plum edge preserve the painted toy material. The whole cover remains legible at both widths.','Reuse this source; repair the clearing relationship rather than regenerate good soil.','mounted_material',5)
opinion('GEO-FOSSIL-CLEARING','Continuous brush clearing boundary',3.9,'A floating painted brush responds to the pointer, but square cells disappear with straight stepped edges. The exposed fossil reads as an image wipe; remaining dirt vanishes when26 cells are reached.','Give the cleared footprint rounded, child-readable brushed edges and truthful local material removal. Preserve progress and contact ownership.','complete_component_action',6)
opinion('GEO-BRUSH-MOUNT','Brush material and contact with soil',4.5,'Soft aqua bristles and the plum-contoured handle remain legible. Bristles sit at the erasure position; the handle has no Roshan hand around it.','Keep the brush painting; review actual grip separately. Inclusive4.5 refinement remains.','mounted_material',6)
opinion('GEO-FOSSIL-FRACTURE','Soil-to-broken-fossil transition',3.2,'At1280 frames108→109 and1600 frames105→106, the remaining dirt and brush disappear and the fossil instantly becomes three widely spaced vertical strips in front of a translucent intact target. No fracture edge or reveal explains the change.','Author readable natural broken edges and a conserved reveal-to-assembly transition with embodied handling. Do not conceal the jump with a reward effect.','complete_component_action',7)
for id,label in [('GEO-FOSSIL-LEFT','Left fossil piece'),('GEO-FOSSIL-CENTRE','Centre fossil piece'),('GEO-FOSSIL-RIGHT','Right fossil piece')]:
 opinion(id,label,3.6,'The original spiral/material is conserved, but this piece ends at an arbitrary perfectly vertical image-third cut. During drag it is a thin rectangular slice rather than a believable broken stone.','Reuse approved fossil identity with separately authored complementary fracture contours and small readable edge depth; audit each piece and joined result.','mounted_object_and_drag',7)
opinion('GEO-FOSSIL-TARGET','Translucent intact assembly target',4.2,'The single complete spiral helps indicate the answer without words. Its washed-out transparent painting overlaps unsnapped pieces and makes material ownership less clear.','Preserve one recognizable destination; reduce overlap and strengthen a simple readable target silhouette without implying a second physical specimen.','mounted_relationship',8)
opinion('GEO-FOSSIL-JOINED','Joined painted fossil',4.5,'Three exact conserved thirds reconstruct one complete golden spiral and lavender surround. The intact endpoint is readable, but the path contains arbitrary straight cuts and an unexplained break.','Keep the intact source and aspect. Repair separate piece/transition/contact weaknesses; a good endpoint does not pass the whole action.','mounted_material',10)
opinion('GEO-FOSSIL-HAND','Roshan handling the fossil and brush',2.7,'Through every brushing and assembly frame Roshan remains low at the left, making a crawling/digging pose. Her hands never grip the central brush or any moving stone piece.','Build a reviewed intention/contact/release clip contract at the actual work surface; preserve costume/tail/identity and exact input progress.','complete_component_action',8)
opinion('GEO-FOSSIL-FULL','Whole fossil brush-to-assembly action',3.2,'Both complete sequences retain attractive materials and successful intentional assembly, but remote hands, grid erasure, instant three-strip separation and rigid unheld dragging prevent a truthful complete action.','Repair contact, natural fracture contours and conserved clearing-to-assembly before rerendering every frame. Endpoint/source scores are separate.','complete_action',7)
opinion('GEO-PAN-MATERIAL','Pan, water painting and support material',4.6,'The broad lavender bowl, aqua inner water and pale stone support retain coherent painted bands, complete contour and readable scale at both widths.','Reuse these source materials; repair their physical action/hand ownership.','mounted_material',12)
opinion('GEO-PAN-ROCKING','Visible pan rocking at reversals',3.4,'Across all nine reversals the entire oval translates horizontally. Its perspective and water painting remain fixed; no opposite tilt or meaningful wash motion is visible.','Author two readable rocking directions with hand grip and conserved bowl identity; connect motion to real reversals rather than completion time.','complete_component_action',13)
opinion('GEO-PAN-GRAINS','Grain material and containment',4.5,'Small warm painted grains remain inside the bowl in all captured states. The count reduces abruptly and positions shuffle while the water is unchanged.','Reuse the grain source; make removal follow visible washing instead of disappearing at a count threshold.','mounted_material',15)
opinion('GEO-PAN-FLOW','Water and sediment during washing',3.2,'The same flat water reflection travels with the bowl. Grains are removed in discrete steps; there is no visible silt separation or outflow that explains the wash.','Use restrained authored painted water/sediment states that show material leaving or settling while preserving the actual progress rules.','complete_component_action',14)
opinion('GEO-PAN-CRYSTAL','Painted crystal cluster material',4.6,'Cyan and lavender crystals retain a continuous readable rooted cluster in the pan. Small mineral identities are preserved and contained.','Reuse this good source; reveal it truthfully rather than redesign it.','mounted_material',15)
opinion('GEO-PAN-REVEAL','Mineral reveal at wash thresholds',3.3,'A complete cluster appears instantly at reversals3,6 and9, with simultaneous grain-count changes.1280 frames307→308 and1600 frames298→299 expose the first pop. These are progress additions, not uncovering.','Keep clusters in place and uncover them through conserved sediment removal; audit neighboring frames so the cluster does not grow or teleport.','complete_component_action',15)
opinion('GEO-PAN-HAND','Roshan grasping the pan',2.7,'Roshan remains remote at the lower left with empty reaching hands throughout. No hand owns either bowl edge or its reversals.','Author working grips and release at the real pan; do not move an unattached static hand over the bowl to claim acting.','complete_component_action',13)
opinion('GEO-PAN-ACTION','Whole pan washing action',3.4,'Both complete sequences are intentionally earned and use good painted bowl/materials. Sideways translation, unchanged water, abrupt crystal additions and remote hands fail the meaningful action standard.','Repair reciprocal grip/rocking and material uncovering, then review every input/wait/completion frame at both widths.','complete_action',15)
opinion('GEO-FOSSIL-PAN-RESET','Completed fossil to pan invitation',4.0,'The intact fossil holds for the completion; Roshan switches to a generic raised-crystal celebration at the left. The work surface then vanishes and flat invitation props reappear. The route succeeds, but its material/acting transition is abrupt.','Keep the completed object visibly owned through release/celebration and make the next invitation read without a material reset pop.','complete_transition',11)
opinion('GEO-PAN-GEODE-RESET','Completed pan to geode invitation',4.0,'The three crystals remain in the pan during the earned hold. A generic clap/crystal pose replaces working intent; the bowl and slab then switch directly to the invitation layout.','Review release/celebration/next-goal sequencing while retaining rooted pan contents and player agency.','complete_transition',17)
opinion('GEO-CONTACT','Overall observed working-hand ownership',2.7,'Both fossil and pan actions independently retain remote low-left Roshan while the central tool/material moves without her grip. This confirms the existing contact weakness; good source paintings do not fix it.','Repair each job-specific movement/contact contract and review exact complete actions separately.','complete_component_action',13)
native_views=[5,6,7,8,9,10,12,13,14,15,16]
native_frames={1280:[108,109,204,205,307,308],1600:[105,106,298,299,418,419]}
board=read(F/'QA_BOARD_MANIFEST_V1.json');assert len(board['boards'])==85
for b in board['boards']:assert sha(R/b['path'])==b['sha256'];b['direct_review']=True;b['reviewer']='Codex direct visual inspection';b['reviewed_utc']=now
board['status']='ALL85_COMPLETE_ORDERED_BOARDS_DIRECTLY_REVIEWED';write(F/'QA_BOARD_MANIFEST_V1.json',board)
allframes=[];allviews=[]
for w in [1280,1600]:
 cap=read(F/f'attempt02/CAPTURE_{w}.json');assert len(cap['views'])==29
 for x in cap['views']+cap['motion_frames']:assert sha(R/x['path'])==x['sha256']
 for i,x in enumerate(cap['views']):
  phase=x.get('phase_index');s=x['state'];score=2.8 if s=='invitation' or s=='actual_dev_geologist_entry' else 4.0 if s in ['actual_earned_library_return','actual_opera_venue'] else 3.2 if phase==1 else 3.4 if phase==2 else 4.1 if phase in [0,3] else 4.5
  x.update(direct_review=True,reviewed_utc=now,reviewer='Codex',review_scope='Complete canvas directly inspected on ordered board; selected details additionally native.',whole_canvas_score=score,native_detail=i in native_views,owner_acceptance=None,opinion_links=[r['id'] for r in frows if r['evidence_view_index']==i]);allviews.append(copy.deepcopy(x))
 for x in cap['motion_frames']:
  phase=x['phase_index'];s=x['surface'];stage=s.get('stage');complete=s.get('complete',False)
  if phase==1:
   beat='Fossil invitation/approach' if x['goal_anchor']=='crystal_gallery' and stage=='FOSSIL_BRUSH' and not s.get('cleared') else ('Fossil earned endpoint/hold' if complete else 'Fossil vertical-strip assembly' if s.get('fossil_stage')==1 else 'Fossil brush/grid clearing')
   score=4.0 if complete else 3.2;note='Painted fossil/soil conserved; remote hands persist. '+('Joined endpoint holds; generic raised-crystal acting is separate.' if complete else 'Rigid vertical strip pieces remain unheld.' if s.get('fossil_stage')==1 else 'Brush/grid-cleared material relationship remains weak.')
  elif phase==2:
   beat='Pan earned endpoint/hold' if complete else 'Pan translation/washing';score=4.0 if complete else 3.4;note='Good painted bowl; remote empty hands, unchanged water and threshold grain/mineral changes remain. Reversal state='+str(s.get('reversals'))+', minerals='+str(s.get('minerals'))+'.'
  else:beat='Next geode invitation';score=2.8;note='Actual return to the still-flat room invitation; geode opening is separately reviewed in the earlier current report.'
  x.update(direct_review=True,reviewer='Codex direct complete-canvas inspection',reviewed_utc=now,whole_canvas_score=score,frame_evaluation=note,beat=beat,native_detail=x['index'] in native_frames[w],scores={'whole_canvas':score},owner_acceptance=None)
  allframes.append(x)
 write(F/f'attempt02/CAPTURE_{w}.json',cap)
assert len(allframes)==884 and len(allviews)==58
review=dict(schema='reef.geology-complete-action-review.v1',status='BOTH_COMPLETE_ACTIONS_REVIEWED_BELOW_FLOOR',reviewed_utc=now,reviewer='Codex direct visual review; no owner approval claimed',widths=[1280,1600],selected_views=58,consecutive_frames=884,boards=85,native_details=34,production_sources=783,production_sources_changed=0,fossil_complete_action_score=3.2,pan_complete_action_score=3.4,individual_objects=frows,frames=allframes,views=allviews,qualification='Actual normal Library card/all4 intentionally earned phases/Library return and Opera elevator replay/Back. All884 captured input/wait frames directly inspected at full-canvas aspect on85 ordered boards;34 complete native details inspected separately. Readback slows wall clock: this is action/content evidence, not natural timing, mobile/device, child or owner acceptance. No enabled two-act/ChapterTwo Geologist route is inferred. First failed1280 attempt449 frames and raw diagnostics remain separately preserved, not promoted. Good endpoints/source materials do not pass complete actions. Geode rooted-opening repair and its earlier full318-frame evidence remain unchanged.',owner_acceptance=None)
write(F/'DIRECT_REVIEW.json',review)
prows=[]
def fit(id,label,score,note,refinement):prows.append(dict(id=id,label=label,score=score,priority=score<=4.5,evaluation=note,refinement=refinement,owner_acceptance=None,lane='nonruntime_counterfactual_fit'))
fit('FIT-A1-TRAY-LEFT','Left tray material/silhouette at110px',4.5,'The aqua hollow floor, lavender wall and continuous cream rim read as one painted tray. Edge detail simplifies but silhouette remains clear.','Keep source; move prop below actor travel before binding.')
fit('FIT-A1-TRAY-MIDDLE','Middle tray material/silhouette at110px',4.5,'The same exact source stays distinct from its neighbors; Roshan later overlaps its upper rim in the pan invitation.','Material floor only; actor-clearance relationship fails separately.')
fit('FIT-A1-TRAY-RIGHT','Right tray material/silhouette at110px',4.5,'The third reuse remains complete and clearly separated, without a second painted background copy.','Retain conserved source; verify continuous travel and phone size before binding.')
fit('FIT-A1-FOSSIL','Reused invitation fossil material at105px',4.5,'The intact golden spiral and lavender stone remain legible on a pale painted slab. Roshan obscures it in the fossil invitation.','Keep source; repair its reserved position.')
fit('FIT-A1-SUPPORT','Two reused stone supports',4.5,'The same approved stone painting keeps coherent pale/lavender material and complete contour. The long slab is unnecessarily large behind small trays.','Reduce slab and place its contents consistently while preserving aspect and travel clearance.')
fit('FIT-A1-MINERAL','Reused crystal display beside rival',4.5,'The cyan/lavender cluster is readable and clears the rival at selected invitations. It replaces the flat polygon crystal/ring drawing.','Keep the good exact source and review whole approach, work hide and reappearance.')
fit('FIT-A1-DUPLICATION','Single ownership of replacement props',4.6,'Named old flat fossil/tray/crystal drawings are absent from this substituted Library backdrop; one shared source provides each named prop.','Retain exclusive drawing ownership. Developer second entry remains actual unchanged production and is labeled separately.')
fit('FIT-A1-CLEARANCE','Roshan/prop travel clearance',3.5,'Atboth widths Roshan overlaps the fossil in phase1 and the trays in phases2/3. Higher quality sources cannot pass this positional relationship.','Reserve a lower foreground prop lane outside her invitation travel/standing silhouettes; recapture all four invitations.')
fit('FIT-A1-WORK-HIDE','Selected working-state prop hiding',4.5,'The candidate invitation props hide when the real work surface opens, preserving one primary task surface. Only selected states, not intervening motion, are covered here.','Review continuous reveal/approach/closing before actual production binding.')
fit('FIT-A1-ROOM','Existing room wall/floor/spotlights',2.8,'Wide hard polylines and flat angled spotlights remain literal. Painted objects improve contrast but do not make the room a finished storybook space.','Find or generate a compliant native-coverage room master after inventory; no upsampled coverage claim.')
fit('FIT-A1-WHOLE','Whole invitation placement trial',3.5,'Good painted props are undermined by actor occlusion and the retained flat room. This is a failed layout trial with provisional individual material floors.','Preserve A1 and recapture reserved lower placement; do not bind or transfer scores to current production.')
pb=read(P/'QA_BOARD_MANIFEST.json');assert len(pb['boards'])==10
for b in pb['boards']:assert sha(R/b['path'])==b['sha256'];b['direct_review']=True;b['reviewed_utc']=now
pb['status']='ALL58_SELECTED_CANVASES_DIRECTLY_REVIEWED';write(P/'QA_BOARD_MANIFEST.json',pb)
write(P/'DIRECT_REVIEW_ATTEMPT01.json',dict(status='LAYOUT_REJECTED_ACTOR_OCCLUSION',reviewed_utc=now,selected_views=58,boards=10,native_details=8,whole_fit_score=3.5,individual_objects=prows,qualification='Explicit non-runtime Library backdrop substitution only. No actual production source/code changes.8 invitation details inspected at native width plus all58 selected canvases on10boards. No intervening motion, runtime/device/child/owner or all-job acceptance. Actual Opera developer second entry uses unchanged flat production backdrop and is not candidate evidence. All783 production source hashes unchanged.',owner_acceptance=None))
tr=read(T/'attempt01/DIRECT_SOURCE_REVIEW.json')
for x in tr['opinions']:
 if x.get('id')=='TRAY-S06':x.update(score=4.5,priority=True,evaluation='At110px, both widths retain an empty aqua floor, cream rim and shallow lavender wall. Fine outline detail simplifies. A1 placement fails actor clearance independently; this does not pass actual current mounting.',evidence='audit/job_geology_painted_invitation_fit_v1_20261003/DIRECT_REVIEW_ATTEMPT01.json',owner_acceptance=None)
tr['small_scale_counterfactual_review']='audit/job_geology_painted_invitation_fit_v1_20261003/DIRECT_REVIEW_ATTEMPT01.json';write(T/'attempt01/DIRECT_SOURCE_REVIEW.json',tr)
for packet,impact in [(F,'job-geology-complete-actions-20261003.json'),(P,'job-geology-painted-invitation-fit-20261003.json'),(T,'job-geology-specimen-tray-20261003.json')]:
 shutil.copyfile(Path(__file__),packet/'review_tools'/Path(__file__).name)
 ip=R/'design/audit_impacts'/impact;d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in packet.rglob('*') if x.is_file()});d['validation'].append(dict(command='Codex direct complete ordered board and native-detail review V442',result='PASS',evidence='Direct visual review completed; quality failures retained in '+(packet/'DIRECT_REVIEW.json' if packet==F else packet/'DIRECT_REVIEW_ATTEMPT01.json' if packet==P else packet/'attempt01/DIRECT_SOURCE_REVIEW.json').relative_to(R).as_posix()));write(ip,d)
print('GEOMETRY_REVIEWS|884 actual frames/58 actual stills/22 opinions;58 counterfactual stills/11 opinions;trial A1 rejected3.5')
