from pathlib import Path
import datetime,hashlib,html,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
packet=r/'assets_src/local_motion/day2_doctor_wash_rub_study_v1_20261001';out=packet/'attempt_01'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
catalog=json.loads((out/'FRAME_CATALOG.json').read_text(encoding='utf-8'));assert len(catalog['native_frames'])==41
items=[]
for row in catalog['native_frames']:
 assert sha(packet/row['path'])==row['sha256'];i=row['index']
 if i<=1:
  hand=4.3;identity=4.5;text='The initial complete character remains recognizable with the full curled tail/paired fin, coherent coat and satchel. Attached foam and wrists remain visible. The small hand cluster is still difficult to separate into two distinct contacting hands at this study size.'
 elif i<=5:
  hand=4.2;identity=4.4;text='The hands begin turning within the requested entry hold. The foam/finger cluster reshapes while the head/face shading shifts slightly. Local contact remains attached, but the entry is not still and the small hand articulation is ambiguous.'
 elif i<=29:
  hand=4.0;identity=4.4;text='Both forearms remain attached and the broad storybook body/paired fin is preserved. The hands turn into a clasped stack as the lather contracts/reshapes. The requested small stroke over the back of one distinct hand is not clearly legible; mouth/face shading and costume detail also drift slightly.'
 else:
  hand=4.2;identity=4.4;text='One palm opens and the other hand crosses it, giving clearer separated fingers. This is a changed ending rather than the requested return to the initial soapy clasp. Foam remains on a different hand/wrist area, and the face/coat detail differs slightly from the entry.'
 items.append({'id':'DOCTOR-RUB-A01-F%04d'%i,'index':i,'timestamp_seconds':row['timestamp_seconds'],'path':row['path'],'sha256':row['sha256'],'dimensions':row['dimensions'],'direct_full_native_review':True,'painted_style_score':4.5,'identity_static_score':identity,'hand_contact_static_score':hand,'individual_static_score':min(hand,identity),'evaluation':text,'runtime_action_score':None,'cinematic_delivery_accepted':False})
review={'status':'ALL41_NATIVE_FRAMES_REVIEWED_REFERENCE_BELOW_MOTION_FLOOR','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'direct_full_native_views':41,'frames_unreviewed':0,'items':items,'sequence_scores':{'painted_style':4.5,'body_identity_continuity':4.4,'purposeful_back_of_hand_rubbing':4.0,'entry_stillness':3.8,'return_to_initial_contact':3.5,'overall_reference_motion':4.0},'evaluation':'The local workflow renders a coherent painted child and keeps the broad body/fin family recognizable. Motion is largely local to the hands. It still misses the requested action: clasp rotation and lather reshaping replace a clearly readable back-of-hand stroke, the entry starts moving early, and the end opens one palm instead of returning. Minor face/coat shading/detail drift remains. The reference is useful for rejecting these motions; it does not reach4.5.','next_refinement':'Establish a distinct hand-over-hand reach with visible palms/back contact before the next motion trial. Compare an existing consecutive source key or an exact missing-purpose pose; keep the same unchanged developed workflow and preserve this failed trial. Native sink contact and the full wet/rub/rinse/clean/settle/return sequence still need their own review.','source_opinion':'Original complete doctor source6 retains source-only4.5; this video failure does not rewrite its source opinion.','qualification':'LOCAL_MOTION_REFERENCE_ONLY. All41 decoded views directly reviewed; no playback/device/child/owner, gameplay or cinematic delivery acceptance. Full-frame regeneration evidence is absent and the video cannot be relabelled as accepted delivery pixels.'}
write(out/'REVIEW.json',review);shutil.copyfile(__file__,out/'executed_write_doctor_motion_review_v48.py')
movement={'status':'INHERITED_MOVEMENT_INTERPRETATION_REVIEW_ONLY','source':'design/animation/ROSHAN_MOVEMENT_LANGUAGE.md','source_sha256':sha(r/'design/animation/ROSHAN_MOVEMENT_LANGUAGE.md'),'interpretation':'Doctor washing inherits Roshan noticing with her eyes and deciding with her hands. Careful local work uses the everyday Ribbon Glide register after arrival, followed by a quiet settle. These are acting interpretations, not new story facts.','attention':'Look toward connected washing hands and the basin; background, hair, satchel and tail remain quiet at contact.','support':'This isolated reference supplies no world support/locomotion authority. The contextual fixture preserves current station arrival but needs exact body/support staging before acceptance.','rhythm':'Small deliberate rub with clear contact and generous stillness; no whole-card rocking or generic idle bounce. Entry/exit holds in the study are evaluated against actual motion, not inferred from prompt text.','emotional_registers':'Everyday focused helping is the studied register. A clean result may earn a small pleased smile and quiet open hands; no exaggerated cheer, new dialogue or random celebration is commissioned.','action_vocabulary':'Wet hands, rub palms/back of hands with attached wrists, rinse visible lather into basin, show clean hands, settle and return. Only one isolated rub is tested here; other verbs remain missing coverage.','coverage_gaps':'Source6 and consecutive key1 are source-only4.5; clean ending source-only4.5 reads4.0 in the closer fixture. All58 context views remain below floor. No directional/locomotion, interruption, ordinary route or complete wash acceptance.'}
write(packet/'MOVEMENT_INTERPRETATION_V1.json',movement)
cards=''.join('<article id="'+x['id']+'"><h2>Frame'+str(x['index'])+' · '+format(x['timestamp_seconds'],'.3f')+'seconds</h2><p>Individual static'+str(x['individual_static_score'])+'/5 · hand/contact'+str(x['hand_contact_static_score'])+'/5 · painted style'+str(x['painted_style_score'])+'/5</p><a href="'+x['path']+'"><img loading="lazy" src="'+x['path']+'" alt="'+x['id']+' full native frame"></a><p>'+html.escape(x['evaluation'])+'</p><small>SHA256 '+x['sha256']+'</small></article>' for x in items)
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor hand-rubbing local study:41-frame review</title><style>body{font:18px/1.55 system-ui;background:#eef4fa;color:#253447;margin:0}main{max-width:1180px;margin:auto;padding:24px}section,article{background:white;border-radius:20px;padding:22px;margin:0 0 22px}img,video{max-width:100%;height:auto}p,a,small{overflow-wrap:anywhere}video{display:block;width:896px}</style><main><section><h1>Doctor rubbing study: all41 native frames reviewed</h1><p>Overall local reference motion4.0/5 · back-of-hand action4.0 · return3.5 · source6 remains4.5 only</p><p>'+html.escape(review['evaluation'])+'</p><video controls preload="metadata" poster="inputs/doctor_rub_full_source.png"><source src="attempt_01/native_output.mp4" type="video/mp4"><source src="attempt_01/native_output.webm" type="video/webm"></video><p><a href="attempt_01/REVIEW.json">Individual41-frame written evaluations</a> · <a href="attempt_01/FRAME_CATALOG.json">Exact frame hashes</a> · <a href="attempt_01/RENDER_RECEIPT.json">Developed local CLI execution</a> · <a href="MANIFEST.json">Source/input/prompt/workflow bindings</a> · <a href="PROFILE.json">Clip contract</a> · <a href="MOVEMENT_INTERPRETATION_V1.json">Inherited Roshan movement interpretation</a></p><p>'+html.escape(review['qualification'])+'</p><p>'+html.escape(review['next_refinement'])+'</p></section>'+cards+'</main></html>'
(packet/'index.html').write_text(page,encoding='utf-8',newline='\n')
impact=r/'design/audit_impacts/job-doctor-local-rub-study-20261001.json';d=json.loads(impact.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{x.relative_to(r).as_posix() for x in packet.rglob('*') if x.is_file()});d['validation'].append({'command':'Direct original-size review of every41 decoded native frames','result':'FAIL','evidence':(out/'REVIEW.json').relative_to(r).as_posix()+'; isolated action4.0, entry3.8 and return3.5. Reference-only and original outputs preserved.'});write(impact,d)
allow=r/'tmp/v2_preview_allowed.json';a=set(json.loads(allow.read_text(encoding='utf-8')));a.update(d['files']);write(allow,sorted(a))
print(json.dumps({'status':review['status'],'frames':41,'overall_motion':4.0,'return':3.5,'runtime_acceptance':False}))
