from pathlib import Path
import json,hashlib,html,datetime,shutil
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');out=b/'audit/job_pan_actor_contact_study_v1_20261001';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
views=json.loads((out/'native_views/CAPTURE_RECEIPT.json').read_text())['views'];rows=[]
for v0 in views:
 v=dict(v0);inv=v['state']=='invitation';p=out/'native_views'/v['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==v['sha256'];v.update(archive_path=rel(p),direct_native_review=True,reviewed_utc=now,scores=dict(actor_identity_finish=4.6,actor_tabletop_placement=4.4 if not inv else None,actor_pan_contact=4.2 if not inv else None,pose_work_semantics=3.8 if not inv else None,object_finish=4.6,object_geometry=4.6,scene_coherence=4.4,complete_action=None),evaluation='Same unchanged invitation art; no actor-work contact exists in this state, so none is scored.' if inv else 'The unchanged complete pose now sits on the left slab instead of working remotely from the floor. One hand approaches the outside pan wall, improving static contact2.7 to4.2, while the other palm still rests on the slab. Her low crawl-like wrists do not grip or pan the vessel; work semantics3.8. Whole-card positioning cannot repair the missing panning gesture. Identity, full fin and original pixels remain intact4.6; source reuse alone does not reach the action floor.',qualification='Only a disposable native static position/layer study using the unchanged approved work atlas. Actual inherited panning input and three reversals; no complete ordinary career/training/story route, timed acting, target-device/child/owner or final-report acceptance.',owner_acceptance=None,production_binding_changed=False);rows.append(v)
assert len(rows)==6;write(out/'REVIEW.json',dict(status='6_OF6_DIRECTLY_REVIEWED_REUSE_DOES_NOT_PASS_PANNING_GESTURE',views=rows,directly_reviewed=6,total_teacher_geology_pan_views=286,qualification='Static contact improves4.2 but remains below4.5. Named gap is raised panning/gripping arms; do not regenerate unchanged identity art for novelty.'))
cards=['<article><h2>'+v['id']+'</h2><img src="native_views/'+v['path']+'" alt="'+v['id']+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+' '+str(x)+'/5' for k,x in v['scores'].items() if x is not None))+'</p><small>'+html.escape(v['qualification'])+'</small></article>' for v in rows]
(out/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Geologist pan actor reuse contact study</title><style>body{font:17px/1.5 system-ui;background:#eef5f4;color:#302949;max-width:1500px;margin:auto;padding:24px}article{background:white;padding:20px;margin:25px 0}img{width:100%;height:auto}</style><h1>Geologist actor reuse — all6 native views</h1><p>6/6 directly inspected. Existing whole-card placement improves contact2.7 to4.2 but retains crawl-like low wrists and work semantics3.8. This is an incomplete prototype. Source identity/full fin4.6 stays unchanged. A real panning/gripping pose is the named gap; complete motion/routes/device/child/owner/report remain open.</p><p><a href="REVIEW.json">Individual scores/hashes</a> · <a href="PROFILE.json">Exact source and transforms</a> · <a href="PROCESS_RECEIPT.json">Machine receipt</a> · <a href="../job_pan_painted_mount_v3_20261001/index.html">Previous source and detail iterations</a></p>'+''.join(cards),encoding='utf-8');shutil.copyfile(__file__,out/'executed_record_pan_actor_review_v125.py')
license=b/'ASSET_LICENSES.md';existing=license.read_text()
with license.open('a',encoding='utf-8',newline='\n') as f:
 for v in rows:
  if v['archive_path'] not in existing:f.write('\n| `'+v['archive_path']+'` | Project-owned Godot4.7.2 Mobile static actor fixture; all underlying provenance retained | Internal review evidence | Exact complete viewport capture; unchanged atlas/whole-card position only, no pixel repair; SHA256 '+v['sha256']+' |\n')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();row='| `audit/job_pan_actor_contact_study_v1_20261001/index.html` | 🟣 | `CANDIDATE`; all6 unchanged-atlas whole-card static actor contact views directly inspected. Identity/full fin4.6 preserved, tabletop placement4.4 and pan contact4.2 improve but fail the4.5 action floor; low crawling wrists/work semantics3.8 identify a missing panning/gripping pose. No complete timed route/device/child/owner/report acceptance. |';assert row.split('`')[1] not in s;ledger.write_text(s+'\n'+row+'\n',encoding='utf-8')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Actor-contact reuse continuation (2026-10-01): [all6 additional native pan actor views](job_pan_actor_contact_study_v1_20261001/index.html) directly reviewed bring the teacher/geology/pan total to286. Unchanged full-fin atlas identity4.6; whole-card positioning improves static contact2.7 to4.2 but leaves low crawling wrists and panning semantics3.8. No source identity redesign or complete acting pass. Raised panning/gripping arms remain the named gap. Current register1557/1186/579 inclusive priorities/388 unassigned unchanged. [Impact](../design/audit_impacts/job-pan-painted-placement-20261001.json). All ordinary training/story/device/child/owner/final report gates remain open.\n\n';s=s.replace('## 0. Planning entry\n\n','## 0. Planning entry\n\n'+entry,1);master.write_text(s,encoding='utf-8')
for f in ['audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html']:
 p=b/f;s=p.read_text();banner='<section id="pan-actor-reuse-priority"><h2>Current actor contact priority —286 directly inspected native comparisons</h2><p>Existing whole geologist pose repositioned intact: source identity/full fin4.6, tabletop placement4.4, static pan contact4.2, panning/gripping semantics3.8. This identifies the missing raised-hand panning pose; it does not establish timed acting. Every6 additional view remains inspectable.</p><p><a href="../job_pan_actor_contact_study_v1_20261001/index.html">All6 illustrated actor reuse views</a></p></section>';i=s.index('<h1');end=s.index('</h1>',i)+5;s=s[:end]+banner+s[end:];p.write_text(s,encoding='utf-8')
findings=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text();ident='MA-PLAY-004';start=s.index('\n## '+ident+'\n');end=s.find('\n## ',start+1);section=s[start:end];lines=section.splitlines();hit=next(i for i,l in enumerate(lines) if l.startswith('| history |'));lines[hit]=lines[hit].rstrip().removesuffix('|').rstrip()+' 2026-10-01 actor reuse:6 additional native views/286 total confirm source identity4.6, static contact4.2 and panning pose semantics3.8. Moving the original whole card cannot supply missing raised gripping arms; every score/failed context remains inspectable at `audit/job_pan_actor_contact_study_v1_20261001/index.html`. Lifecycle and full-route/device/child/owner acceptance remain unchanged. |';s=s[:start]+'\n'.join(lines)+'\n'+s[end:];findings.write_text(s,encoding='utf-8')
impact=b/'design/audit_impacts/job-pan-painted-placement-20261001.json';d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in out.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html'});d['validation'].append(dict(command='Every6 unchanged-atlas native static-contact view directly inspected',result='PASS',evidence=rel(out/'REVIEW.json')+'; review complete, pose/action still fails4.5 floor'));write(impact,d)
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(rel(p) for p in out.rglob('*') if p.is_file());write(allow,sorted(allowed));print('All6 actor views recorded;286 total direct comparisons; panning pose remains3.8')
