from pathlib import Path
import datetime,hashlib,json,shutil,sys
from PIL import Image,ImageOps
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
old=r/'assets_src/local_motion/day2_batch1_20260930'
packet=r/'assets_src/local_motion/day2_doctor_wash_reach_rub_study_v1_20261001'
assert not packet.exists()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
baseline='56d66f63e375b61cf02936b426a05a2b92c14d3b'
source=r/'assets_src/imagegen/day2_doctor_wash_reach_v1_20261001/attempt01_native.png'
assert sha(source)=='50a63f9c7465c2b39418cd58dd5bbeef19072279416c7cadbf533d8645b41b1a'
impact=r/'design/audit_impacts/job-doctor-reach-local-rub-study-20261001.json'
d={'id':'job-doctor-reach-local-rub-study-20261001','scope':'After the first chest-clasp study failed motion4.0/return3.5, one full-character rub/return trial of the new outward-reaching source through the unchanged developed local ComfyUI GGUF workflow. Audit exact hand/body/identity drift and entry/exit; source/static/art opinions do not pass runtime action. Preserve all output and failed history.','baseline':baseline,'rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-MED-01','DL-ASSET-01','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-VIS-08','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-INT-02','DL-QA-03'],'findings':['MA-PLAY-004','MA-VIS-006'],'files':['ASSET_LICENSES.md'],'validation':[{'command':'Pinned developed ComfyUI CLI quick GGUF study','result':'PENDING','evidence':'assets_src/local_motion/day2_doctor_wash_reach_rub_study_v1_20261001/MANIFEST.json; no output graded yet.'}],'acceptance_gaps':'Source-only4.5 draft not owner accepted; all-frame motion identity/topology/contact/entry-exit, complete washing/runtime/device/child/owner and cinematic delivery remain open.'}
write(impact,d)
packet.mkdir();(packet/'.gdignore').write_text('',encoding='utf-8')
for sub in ['inputs','prompts','workflows']:(packet/sub).mkdir()
m=json.loads((old/'MANIFEST.json').read_text(encoding='utf-8'));renderer=m['renderer']
for binding in renderer['bindings']:
 archived=old/binding['packet_path'];assert sha(archived)==binding['sha256']
 if binding.get('check_installed_bytes',True):assert sha(Path(binding['installed_path']))==binding['sha256'],binding['installed_path']
 shutil.copyfile(archived,packet/binding['packet_path'])
assert sha(packet/'workflows/render_gguf.py')=='68f0f69e390531a04e267fd6e591f7d17d3a9959871e694058e3c4f225affa41'
inputpath=packet/'inputs/doctor_rub_full_source.png'
with Image.open(source) as native:
 assert native.size==(1122,1402) and native.mode=='RGBA'
 scaled=ImageOps.contain(native,(896,500),method=Image.Resampling.LANCZOS)
 canvas=Image.new('RGBA',(896,512),(230,244,245,255));position=((896-scaled.width)//2,(512-scaled.height)//2)
 canvas.alpha_composite(scaled,position);canvas.convert('RGB').save(inputpath)
prompt='Locked camera, one continuous shot of this complete small mermaid doctor in the exact same polished drawn2D storybook style and neutral aqua field. Her upper hand already rests palm-down on the BACK of the lower hand; her forearms reach out to image right. 0.00-0.30seconds: hold this exact connected contact still. 0.30-1.10: make ONE clearly visible short rubbing stroke: only the UPPER palm slides gently along the BACK of the LOWER hand toward its knuckles, then starts back. The lower hand remains relaxed, wrist attached, fingers pointing down/right in their original grouped shape. 1.10-1.50: the upper palm slides back to the exact initial contact. 1.50-1.70: settle in that initial pose. Keep BOTH hands in contact throughout; never open the lower palm or separate into a gesture. Lather stays small and attached at the contact. Keep her face, gaze, head, brown curls/rainbow lock, flower, doctor coat, satchel, torso, curled rainbow tail and paired fin fixed in identity, shape, scale and canvas position; only local wrist/forearm articulation may accompany the upper palm stroke. Keep the plain aqua field still. No sink/water is requested in this isolated rub reference. Warm brown/plum contours, broad matte painted values and aqua/lavender shadows stay stable. No clasping swap, hand opening, detached wrists, extra fingers/limbs, moving head/body/tail, fin changes, new objects/tools, foam growth, camera move, cuts, whole-card translation, photorealism,3D/plastic texture, sparkle, text or background invention. Sound: silence.\n'
promptpath=packet/'prompts/doctor_rub_full_source.txt';promptpath.write_text(prompt,encoding='utf-8',newline='\n')
profile={'status':'PREPARED_LOCAL_MOTION_REFERENCE_ONLY','baseline':baseline,'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'intention':'Roshan makes one clear upper-palm stroke along the back of her relaxed lower hand, then returns to exact initial outward contact.','event':'Prospective doctor WASH gesture response study; no gameplay event, reward or wash progress is implemented.','phases':{'entry':[0.0,0.30],'rub':[0.30,1.10],'return':[1.10,1.50],'settle':[1.50,1.70]},'anchors':{'fixed':'Face/head/hair/costume/torso/satchel/tail/paired fin and neutral field','allowed':'Only small articulated forearm/hand travel with stable connected wrists; attached existing foam','source_hand_landmark':[684,680]},'source':{'path':source.relative_to(r).as_posix(),'sha256':sha(source),'dimensions':[1122,1402],'score':4.5,'owner_accepted':False},'normalization':{'operation':'Whole full-character RGBA uniformly fit within896x500, centred on896x512 neutral aqua field; RGB is solely the established local model input. No cropping, subject translation/repair, painting, source masks or new scene pixels.','scaled_dimensions':list(scaled.size),'position':list(position),'background_rgba':[230,244,245,255],'input_sha256':sha(inputpath)},'loop_contract':'Entry and final contact should match; no accepted looping/return exists. Inspect every41 native frames and any hand/body drift.','interruptions':'No shipping clip, lifecycle, pause/focus/Back/reload or handoff is implemented. Game input/progress/save ownership remains unchanged.','acceptance_criteria':'Full frame identity/topology/contour/palette remain fixed; hand motion is local, connected, non-zero, anatomically coherent and returns. Motion must be directly reviewed rather than inferred from process PASS. No sink contact or complete wash acceptance follows.','qualification':'LOCAL_MOTION_REFERENCE_ONLY; all unreviewed motion/contact/device/child/owner/cinematic gates remain open.'}
write(packet/'PROFILE.json',profile)
renderer=dict(renderer);renderer['bindings']=[dict(x) for x in renderer['bindings']]
for binding in renderer['bindings']:
 if binding['packet_path']=='workflows/render_gguf.py':binding['installed_path']=str(packet/binding['packet_path']);binding['note']='Byte-identical frozen developed wrapper copy; no installed workflow or model changes.'
renderer['admission']='One-study worker checks the exact source/input/prompt/workflow bytes, matching same-settings prior successful quantized benchmark, absence of a previous named submission and a90-second quiet native queue before invoking the developed CLI. Never post a separate prompt, cancel jobs or restart service.'
manifest={'id':'DAY2-DOCTOR-REACH-RUB-LOCAL-V1','acceptance':'LOCAL_MOTION_REFERENCE_ONLY','owner_approval':None,'runtime_integration':False,'renderer':renderer,'job':{'id':'WASH-DOCTOR-REACH-RUB-REFERENCE01','queue_name':'d2m_doctor_reach_rub_v1_20261001','seed':2026100111,'source_path':profile['source']['path'],'source_sha256':sha(source),'input_path':'inputs/'+inputpath.name,'input_sha256':sha(inputpath),'prompt_path':'prompts/'+promptpath.name,'prompt_sha256':sha(promptpath)},'profile':'PROFILE.json','output_state':'Not submitted yet; no artistic score assigned.','reused_art':'Outward-reaching source already meets source-only4.5. No new art is generated for novelty; this single video study probes the exact missing articulated hand-rubbing motion. Existing sink contact is audited separately.'}
write(packet/'MANIFEST.json',manifest)
shutil.copyfile(__file__,packet/'executed_prepare_doctor_comfy_study_v42.py')
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor local hand-rubbing study</title><style>body{font:18px/1.55 system-ui;background:#eef4fa;color:#253447}main{max-width:1000px;margin:auto;padding:24px}img{max-width:100%;height:auto}p,a{overflow-wrap:anywhere}</style><main><h1>Doctor hand rubbing: local motion study</h1><p>Prepared reference-only study using the developed ComfyUI GGUF quick workflow:896×512,41frames,24steps. No motion or runtime acceptance yet.</p><p><a href="MANIFEST.json">Exact source/input/prompt/workflow bindings</a> · <a href="PROFILE.json">Intention, anchors and clip contract</a> · <a href="prompts/doctor_rub_full_source.txt">Motion prompt</a></p><img src="inputs/doctor_rub_full_source.png" alt="Whole-source normalized doctor rubbing input"><p>Original complete source remains preserved. Video output will be graded frame by frame; sink contact and the complete wet/rub/rinse/clean/return sequence remain open.</p></main></html>'
(packet/'index.html').write_text(page,encoding='utf-8',newline='\n')
license=r/'ASSET_LICENSES.md';s=license.read_text(encoding='utf-8');path=inputpath.relative_to(r).as_posix();assert path not in s
s+='\n| '+path+' | Existing generated doctor washing outward-reaching source; full-source normalized input2026-10-01 | Source provenance in PROFILE.json and original imagegen record | Uniform full-canvas fit and neutral aqua RGB field for developed local workflow | Diagnostic local motion input only; original unchanged, no runtime/cinematic or owner acceptance. |\n'
license.write_text(s,encoding='utf-8',newline='\n')
d['files']=sorted(set(d['files'])|{x.relative_to(r).as_posix() for x in packet.rglob('*') if x.is_file()});write(impact,d)
allow=r/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text(encoding='utf-8')));allowed.update(d['files']);write(allow,sorted(allowed))
print(json.dumps({'status':'PREPARED_ONE_LOCAL_REFERENCE_STUDY','source_sha256':sha(source),'input_sha256':sha(inputpath),'bindings_verified':len(renderer['bindings']),'runtime_integrated':False}))
