from pathlib import Path
from PIL import Image
import datetime, hashlib, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001';out=f/'wet_attempt_01';out.mkdir(exist_ok=False)
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-9e62c3fe-fe2e-451d-8e9d-8b8e8c8abb33.png');p=out/'native_generated.png';shutil.copyfile(src,p);sha=hashlib.sha256(p.read_bytes()).hexdigest();assert sha==hashlib.sha256(src.read_bytes()).hexdigest()
im=Image.open(p);assert im.mode=='RGBA' and im.size==(1254,1254);a=im.getchannel('A').point(lambda x:255 if x>4 else 0);parts=[]
for ident,box,ports,note in [('ENDCAP_RIGHT',(0,0,627,627),['RIGHT'],'One right open port; round left end/bowl has intact exterior banks. Water reaches the right plane, with no internal ring.'),('ELBOW_UP_RIGHT',(627,0,1254,627),['UP','RIGHT'],'Two open ports and one continuously aqua rounded bend. Exterior earth banks follow the outside elbow without crossing the water.'),('TEE_LEFT_RIGHT_UP',(0,627,627,1254),['LEFT','RIGHT','UP'],'Three broad open arms share one clear aqua centre; lower side closes with exterior earth bank.'),('CROSS_ALL',(627,627,1254,1254),['UP','RIGHT','DOWN','LEFT'],'All four open arms share one clear interior with exterior corner banks only. No rail or circular wall divides the middle.')]:
 q=a.crop(box).getbbox();region=[q[0]+box[0],q[1]+box[1],q[2]-q[0],q[3]-q[1]]
 parts.append({'id':'GEO-RIVER-JUNCTION-WET-A01-'+ident,'path':p.relative_to(b).as_posix(),'sha256':sha,'source_dimensions':[1254,1254],'region':region,'expected_ports':ports,'observed_ports':ports,'source_score':4.6,'material_score':4.6,'source_geometry_score':4.6,'runtime_bound':False,'evaluation':note+' Broad matte ochre/cream, lavender shade and plum contour match the selected source family. Exact runtime port calibration/sampling/join widths remain pending.','qualification':'Fresh complete native generated atlas and each4 objects directly inspected. Source-only4.6; not actual mounted/joined/network/action/device/child/owner acceptance.'})
write(out/'REVIEW.json',{'status':'FOUR_WET_JUNCTIONS_SOURCE4_6_UNBOUND','native_path':p.relative_to(b).as_posix(),'native_sha256':sha,'native_dimensions':[1254,1254],'source_score':4.6,'components':parts,'reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'qualification':'All4 complete visible shapes directly inspected from fresh generated native. No generated pixels edited; native source preserved; whole-canvas normalization and actual adjacency still pending.'})
j=read(f/'GENERATION_PENDING.json');j.update(status='NATIVE_WET_RESULT_PRESERVED_SOURCE_REVIEW4_6',generator_original_path=str(src),native_path=p.relative_to(b).as_posix(),native_sha256=sha,native_dimensions=[1254,1254],pixel_modifications='None; exact generated complete RGBA original.');write(out/'PROVENANCE.json',j)
prompt='''Edit IMAGE_1 into the matching DRY excavation atlas. IMAGE_1 is the edit target and exact topology/composition authority: preserve the four complete transparent cutouts in the same2-by2 positions, every exterior earth bank, the same matching open-port edges, contours, stem widths, centres and rounded shapes. Preserve alpha and all transparent gaps. The upper-left is a one-port right-facing dead-end; upper-right elbow opens up/right; lower-leftT opens left/right/up; lower-right cross opens all four directions. No cap, divider, internal ring or bank rail may be added to an open corridor. No extra port.
Change ONLY the aqua-water interiors to clear warm ochre/lavender DRY loose earth. IMAGE_2 is a dry-earth MATERIAL/COLOR reference only; use its broad matte painted loam value bands, calm sand/ochre middle and lavender depth. Water is entirely absent in all four cutouts: no aqua, turquoise, white water glints, liquid, flow arrows or wet shine. Retain the cream/ochre exterior banks and plum outline unchanged in style. This is polished2D storybook game bitmap art, simple broad handmade forms, readable at88pixels, matching IMAGE_1. No photorealism, no glossy3D, no flat vector icon medium, no labels, numbers, grid, background scene, character or board. Preserve the complete atlas and native transparency; return a new complete matching dry atlas.'''
(f/'PROMPT_DRY_ATTEMPT_01.txt').write_text(prompt,encoding='utf-8',newline='\n')
refs=[p.relative_to(b).as_posix(),'assets_src/imagegen/geologist_river_components_v1_20261001/attempt_01/native_generated.png']
write(f/'GENERATION_DRY_PENDING.json',{'status':'DRY_JUNCTION_NATIVE_PENDING','prompt_path':(f/'PROMPT_DRY_ATTEMPT_01.txt').relative_to(b).as_posix(),'prompt_sha256':hashlib.sha256((f/'PROMPT_DRY_ATTEMPT_01.txt').read_bytes()).hexdigest(),'reference_paths':refs,'reference_sha256':[hashlib.sha256((b/q).read_bytes()).hexdigest() for q in refs],'reference_roles':['EDIT_TARGET_WET_TOPOLOGY_COMPOSITION_ALPHA','REFERENCE_DRY_EARTH_MATERIAL_ONLY'],'method':'BUILTIN_CODEX_IMAGEGEN','transparent_background':True,'attempt':1,'runtime_bound':False})
shutil.copyfile(__file__,f/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-junction-source-20261001.json';d=read(ip);d['scope']+=' Fresh wet native4.6 has four open-interior endcap/elbow/T/cross shapes; preserve every original and source opinion. Generate the matching dry palette only, keeping wet topology/ports/composition as edit authority and existing dry node as material reference. Source finish does not validate actual joins.';d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});d['validation'].append({'command':'Every fresh wet native object','result':'PASS','evidence':(out/'REVIEW.json').relative_to(b).as_posix()+'. All4 source4.6 unbound; actual port fit pending.'});write(ip,d)
print(json.dumps({'native':p.relative_to(b).as_posix(),'sha256':sha,'components':[(x['id'],x['region']) for x in parts],'source_score':4.6}))
