from pathlib import Path
import datetime, hashlib, json, shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');s=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001';f=b/'audit/job_river_join_study_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat()
a=s/'dry_attempt_03';src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-198fed5f-5c8c-47eb-b431-d439fe9d80fc.png');dst=a/'native_generated.png';assert not dst.exists();shutil.copyfile(src,dst);assert sha(src)==sha(dst)
im=Image.open(dst);assert im.mode=='RGBA';p=read(a/'GENERATION_PENDING.json');p.update(status='GENERATED_EDGE_CORRECTION_FAILED_DIRECT_SOURCE4_4',generator_original_path=str(src),native_path=dst.relative_to(b).as_posix(),native_sha256=sha(dst),native_dimensions=list(im.size),pixel_modifications='None; exact generated complete RGBA original.');write(a/'PROVENANCE.json',p)
parts=[]
for name,rect in [('ENDCAP',[53,119,556,423]),('ELBOW',[756,60,448,485]),('TEE',[47,688,544,424]),('CROSS',[686,653,511,519])]:
 parts.append(dict(id='GEO-RIVER-JUNCTION-DRY-A03-'+name,path=dst.relative_to(b).as_posix(),sha256=sha(dst),source_dimensions=list(im.size),region=rect,source_score=4.4,direct_review=True,runtime_bound=False,mounted_score=None,complete_action_score=None,owner_acceptance=None,evaluation='Calm golden floor and rounded painted bank identity retained; targeted correction still leaves conspicuous red/orange fringe at open port edges. Complete '+name.lower()+' remains source4.4 rejected; no normalization or mounted acceptance.',qualification='Exact generated native preserved; each complete component directly inspected; no pixel cleanup.',reviewed_utc=now))
write(a/'REVIEW.json',dict(native_path=dst.relative_to(b).as_posix(),sha256=sha(dst),source_dimensions=list(im.size),source_score=4.4,direct_review=True,components=parts,reviewed_utc=now,qualification='Targeted edge edit failed; original and all four components4.4. Preserve rejected draft outside runtime.'))
a=s/'dry_attempt_04';a.mkdir(exist_ok=False)
prompt='''Use case: stylized-concept
Asset type: transparent raster atlas of four dry excavated river channel components for a preschool 2D storybook game.
Create a fresh clean atlas with four separate complete objects on a genuinely transparent canvas. Polished hand-painted toy-world illustration: warm golden ochre earth, broad matte painterly value bands, narrow lavender wall shade, clean dark plum contours, rounded chunky soil banks. High-key, child-readable. No photorealism, vector flat fills, 3D, or glossy realism.
Arrange a 2 by 2 atlas with ample transparent separation: upper left a rounded dead-end bowl with one straight open port pointing right; upper right an L bend with two straight open ports pointing up and right; lower left a T junction with three straight open ports pointing up, left and right; lower right a cross junction with four straight open ports. Every channel floor is calm medium-light golden earth. Raised banks run only along the outer sides, never across an open port and never across the centre. All ports have the same channel width and same level golden floor for seamless repeat connections. Banks are generous rounded scalloped masses with a plum edge, little clustered texture, no individual pebble noise. Interior pigment is low contrast and even in every direction; narrow wall shadow stays local to the wall.
Four objects only, generous padding, full intact silhouettes. Outside objects is fully transparent with clean colour-correct antialiasing. Open port ends are clean straight cuts with golden floor and plum bank ends. No coloured fringe, halo, glow, exterior speck, drop shadow, checkerboard, ground plate, text or labels. Keep a consistent clean painted game-art finish.
'''
p=s/'PROMPT_DRY_ATTEMPT_04.txt';p.write_text(prompt,encoding='utf-8',newline='\n');write(a/'GENERATION_PENDING.json',dict(status='PRE_GENERATION_NAMED_SOURCE_EDGE_GAP',attempt=4,method='BUILTIN_CODEX_IMAGEGEN_FRESH_FOUR_COMPONENT_ATLAS',prompt_path=p.relative_to(b).as_posix(),prompt_sha256=sha(p),reference_paths=[],reference_sha256=[],transparent_background=True,runtime_bound=False,named_gap='A2 and targeted A3 complete-source open port edges remain visibly red-fringed4.4, despite mounted inner portions4.5. Fresh generation limited to the same four dry open-channel components, no character or room redesign. Existing candidates preserved. Layout/calibration must be reviewed anew.',review_evidence='assets_src/imagegen/geologist_river_junctions_v1_20261001/dry_attempt_03/REVIEW.json'))
shutil.copyfile(__file__,s/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-junction-source-20261001.json';d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in s.rglob('*') if x.is_file()});write(ip,d)
print(prompt)
