from pathlib import Path
from PIL import Image, ImageChops
import datetime, hashlib, json, shutil, subprocess
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001';out=f/'dry_attempt_01';out.mkdir(exist_ok=False)
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-27a59b98-1e49-4129-a726-e83c67c0a132.png');p=out/'native_generated.png';shutil.copyfile(src,p);sha=hashlib.sha256(p.read_bytes()).hexdigest();assert sha==hashlib.sha256(src.read_bytes()).hexdigest()
im=Image.open(p);assert im.size==(1254,1254) and im.mode=='RGBA';a=im.getchannel('A').point(lambda v:255 if v>4 else 0);wet=read(f/'wet_attempt_01/REVIEW.json');wa=Image.open(b/wet['native_path']).getchannel('A').point(lambda v:255 if v>4 else 0)
parts=[];measurement=[]
for x,box in zip(wet['components'],[(0,0,627,627),(627,0,1254,627),(0,627,627,1254),(627,627,1254,1254)]):
 y=dict(x);y['id']=x['id'].replace('WET','DRY');y['path']=p.relative_to(b).as_posix();y['sha256']=sha;q=a.crop(box).getbbox();y['region']=[q[0]+box[0],q[1]+box[1],q[2]-q[0],q[3]-q[1]];y['evaluation']='The same declared '+','.join(x['expected_ports'])+' port topology remains open and the shared centre is clear dry ochre/lavender loam, with no aqua water or water glints. Broad matte cream/ochre banks and plum contour match the wet counterpart. Source-only4.6; actual switching/ports/joined dry networks remain pending.';y['qualification']='Matching dry edit complete native and all4 shapes directly inspected from fresh generated output. Exact whole original retained; no source pixel/alpha cleanup. Shape comparison is measured separately, not presumed pixel equality.';parts.append(y)
 ca=a.crop(box);cw=wa.crop(box);inter=sum(ImageChops.multiply(ca,cw).histogram()[128:]);union=sum(ImageChops.lighter(ca,cw).histogram()[128:]);measurement.append({'id':y['id'],'wet_region':x['region'],'dry_region':y['region'],'opaque_shape_iou_alpha_gt4':inter/union,'bbox_delta':[v-u for u,v in zip(x['region'],y['region'])]})
write(out/'REVIEW.json',{'status':'FOUR_DRY_JUNCTIONS_SOURCE4_6_UNBOUND','native_path':p.relative_to(b).as_posix(),'native_sha256':sha,'native_dimensions':[1254,1254],'source_score':4.6,'components':parts,'reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'qualification':'All4 dry shapes and whole native directly inspected. Pair placement is not assumed identical; read-only native alpha/bounds comparison retained. Source4.6 does not approve actual adjacency.'})
j=read(f/'GENERATION_DRY_PENDING.json');j.update(status='NATIVE_DRY_RESULT_PRESERVED_SOURCE_REVIEW4_6',generator_original_path=str(src),native_path=p.relative_to(b).as_posix(),native_sha256=sha,native_dimensions=[1254,1254],pixel_modifications='None; exact complete generated edit original preserved.');write(out/'PROVENANCE.json',j)
write(f/'PAIR_GEOMETRY.json',{'status':'NATIVE_ALPHA_GEOMETRY_MEASURED_NOT_PIXEL_EQUALITY','measurements':measurement,'method':'Read-only alpha>4 binary IoU in disjoint native quadrants; no transformed image saved. Bounds/IoU measure silhouette only, not individual port widths, style/contact or runtime switching.','qualification':'Every wet/dry counterpart separately inspected; future atlas calibration/sampling remains required.'})
ff='C:/Users/Peter/AppData/Local/Programs/MermaidReefTools/FFmpeg/8.1.2/bin/ffmpeg.exe';derivatives=[]
for lane in ['wet_attempt_01','dry_attempt_01']:
 q=f/lane;native=q/'native_generated.png';target=q/'whole_canvas_1024.png';cmd=[ff,'-hide_banner','-loglevel','error','-i',str(native),'-vf','scale=1024:1024:flags=lanczos,format=rgba','-frames:v','1',str(target)]
 result=subprocess.run(cmd,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(q/'normalization.stdout.log').write_bytes(result.stdout);(q/'normalization.stderr.log').write_bytes(result.stderr);assert result.returncode==0 and Image.open(target).mode=='RGBA'
 derivatives.append({'path':target.relative_to(b).as_posix(),'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'source_path':native.relative_to(b).as_posix(),'source_sha256':hashlib.sha256(native.read_bytes()).hexdigest(),'dimensions':[1024,1024],'method':'ONE_UNIFORM_COMPLETE_CANVAS_LANCZOS_SCALE_1254_TO1024_RGBA','pixel_repair':False,'alpha_cleanup':False,'source_score':4.6,'direct_review':False,'runtime_bound':False})
write(f/'TECHNICAL_DERIVATIVES.json',{'status':'COMPLETE_CANVAS_NORMALIZATION_DIRECT_REVIEW_PENDING','derivatives':derivatives})
shutil.copyfile(__file__,f/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-junction-source-20261001.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});d['validation'].append({'command':'Every fresh dry native object and wet/dry silhouette bounds','result':'PASS','evidence':(out/'REVIEW.json').relative_to(b).as_posix()+';'+(f/'PAIR_GEOMETRY.json').relative_to(b).as_posix()+'. All4 source4.6 unbound; IoU alone is not actual port/action acceptance.'});write(ip,d)
print(json.dumps({'native':p.relative_to(b).as_posix(),'sha256':sha,'paired_geometry':measurement,'derivatives_direct_review_pending':2}))
