from pathlib import Path
import datetime, hashlib, json, shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');s=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat()
a=s/'dry_attempt_04';src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-cd457569-49b3-4738-9cf1-42b8b65b0fe6.png');dst=a/'native_generated.png';assert not dst.exists();shutil.copyfile(src,dst);assert sha(src)==sha(dst);im=Image.open(dst)
p=read(a/'GENERATION_PENDING.json');p.update(status='FRESH_GENERATED_EXTERIOR_GLOW_FAILED_DIRECT_SOURCE3_8',generator_original_path=str(src),native_path=dst.relative_to(b).as_posix(),native_sha256=sha(dst),native_dimensions=list(im.size),native_mode=im.mode,pixel_modifications='None; exact generated complete original.');write(a/'PROVENANCE.json',p)
parts=[]
for name,rect in [('ENDCAP',[163,43,502,433]),('ELBOW',[920,28,468,433]),('TEE',[120,515,588,450]),('CROSS',[903,505,488,464])]:
 parts.append(dict(id='GEO-RIVER-JUNCTION-DRY-A04-'+name,path=dst.relative_to(b).as_posix(),sha256=sha(dst),source_dimensions=list(im.size),region=rect,source_score=3.8,direct_review=True,runtime_bound=False,mounted_score=None,complete_action_score=None,owner_acceptance=None,evaluation='Fresh '+name.lower()+' has readable open topology and broad golden/plum painting, but a large authored brown/lavender exterior glow remains around it. Complete source3.8 is rejected for exterior contamination; material4.4 is warmer/darker than selected family and repeat-fit unreviewed.',qualification='Exact fresh output and every component directly reviewed. No pixel/background cleanup or mounted pass.',reviewed_utc=now))
write(a/'REVIEW.json',dict(native_path=dst.relative_to(b).as_posix(),sha256=sha(dst),source_dimensions=list(im.size),source_score=3.8,direct_review=True,components=parts,reviewed_utc=now,qualification='Fresh4 source3.8 rejected: large brown/lavender exterior glow, darker banks; no whole-canvas derivative or runtime binding.'))
a=s/'dry_attempt_05';a.mkdir(exist_ok=False);target=dst.relative_to(b).as_posix()
prompt='''Use case: background-extraction
Asset type: four separate transparent painted game-object cutouts in one atlas.
Image1 is the EDIT TARGET. Keep the four dry excavated channel objects and their exact open-port topology, placement, shape, bank thickness, plum contours, lavender inner wall shadows and calm golden floor painting. Extract the four solid earth objects cleanly: remove all of the broad brown, gold and lavender glow/background haze outside their silhouettes. Absolutely every pixel outside the four solid earth bank/floor silhouettes must be fully transparent; no glow, halo, haze, shadow, vignette, coloured matte, background plane or exterior decoration. Preserve only the authored solid earth banks and channel floors, including their crisp straight open ends. Inside each channel remains solid painted earth, not transparent. Antialias only immediately alongside the object boundary using its own edge colours.
Also lighten only the raised soil banks from dark burnt orange to soft golden ochre and cream while retaining the same broad painted value bands and lavender shadow. Keep the calm golden channel floors unchanged. Full intact four objects, exact layout and open port geometry; no added objects, no text, no vector redraw, no photorealism or 3D. Return a clean RGBA atlas with genuine transparency and no exterior glow.
'''
p=s/'PROMPT_DRY_ATTEMPT_05.txt';p.write_text(prompt,encoding='utf-8',newline='\n');write(a/'GENERATION_PENDING.json',dict(status='PRE_GENERATION_NAMED_EXTERIOR_CUTOUT_GAP',attempt=5,method='BUILTIN_CODEX_IMAGEGEN_CLEAN_BACKGROUND_EXTRACTION_LIGHTER_BANK_EDIT',prompt_path=p.relative_to(b).as_posix(),prompt_sha256=sha(p),reference_paths=[target],reference_sha256=[sha(dst)],transparent_background=True,runtime_bound=False,named_gap='Fresh4 source3.8 has broad exterior brown/lavender glow and dark banks. Correct only exterior isolation and bank lightness, preserve solid object topology/floor/layout. No manual alpha cleanup or pixel compositing.',review_evidence='assets_src/imagegen/geologist_river_junctions_v1_20261001/dry_attempt_04/REVIEW.json'))
shutil.copyfile(__file__,s/Path(__file__).name);ip=b/'design/audit_impacts/job-geology-river-junction-source-20261001.json';d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in s.rglob('*') if x.is_file()});write(ip,d)
print('Preserved A4',sha(dst),im.mode,im.size); print(prompt)
