from pathlib import Path
import datetime, hashlib, json, shutil, subprocess
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geology_river_runtime_v1_20261002';f.mkdir(exist_ok=False);(f/'review_tools').mkdir();(f/'runtime_gate').mkdir();(f/'.gdignore').write_text('',encoding='utf-8')
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat();base='40b1c7bfe025f284507c586fea61b9dd76b61423'
ip=b/'design/audit_impacts/job-geology-river-painted-runtime-20261002.json'
write(ip,dict(id=ip.stem,baseline=base,scope='Replace only the flat geology river drawing and flat excavation bed with the exact painted image regions reviewed in V7. Preserve9x5 grid, arbitrary connected paths, stroke/input/save/completion and other phases. Separate exact runtime copies preserve all original PNGs. Cache imported textures and atlas regions; river-only loading limits memory. Complete A2 source red fringes remain failed4.4 outside the selected visible join planes; actual complete in-game region/network4.5 provisional still needs direct ordinary-route review. New fresh glow attempts remain rejected outside runtime.',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-INT-01','DL-INT-02','DL-INT-03','DL-INT-04','DL-INT-06','DL-SAVE-01','DL-SAVE-02','DL-QA-03','DL-QA-06'],findings=['MA-PLAY-004','MA-VIS-006'],files=['scripts/opera_geology_surface.gd'],validation=[dict(command='Selected painted regions in exact V7 inherited-input river studies',result='PASS',evidence='audit/job_river_join_study_v1_20261001/REVIEW_V7.json: every28 current native1280/1600 states directly inspected. Bed4.6/joined dry-wet4.5 provisional; no actor/full-room/action acceptance.')],acceptance_gaps='Actual production route, naturally timed complete action, actor contact/room/training/story, full-suite/strict2D/device/child/owner/all-job acceptance remain open. No dev/master integration or release.'))
assets=b/'assets/opera/worlds/geology/painted_river_v1_20261002';assets.mkdir(exist_ok=False);sources=[('nodes.png','assets_src/imagegen/geologist_river_components_v1_20261001/attempt_01/whole_canvas_1024.png'),('dry_straight.png','assets_src/imagegen/geologist_river_components_v1_20261001/attempt_02/whole_canvas_1024.png'),('wet_straight.png','assets_src/imagegen/geologist_river_junctions_v1_20261001/straight_attempt_02/whole_canvas_1024.png'),('dry_junctions.png','assets_src/imagegen/geologist_river_junctions_v1_20261001/dry_attempt_02/whole_canvas_1024.png'),('wet_junctions.png','assets_src/imagegen/geologist_river_junctions_v1_20261001/wet_attempt_02/whole_canvas_1024.png'),('earth_bed.png','assets_src/imagegen/geologist_river_bed_v1_20261002/attempt_01/whole_canvas_1024x512.png')];rows=[]
for name,source in sources:
 target=assets/name;shutil.copyfile(b/source,target);assert sha(target)==sha(b/source);im=Image.open(target);assert im.mode=='RGBA' and max(im.size)==1024
 # Import metadata uses a unique UID generated by Godot, never copied from another resource.
 template=(b/'assets/opera/worlds/geology/painted_work_v1_20261001/fossil.png.import').read_text(encoding='utf-8');import re
 template=re.sub(r'^uid="[^"]+"\n','',template,flags=re.M)
 resource=target.relative_to(b).as_posix();digest=hashlib.md5(('res://'+resource).encode()).hexdigest();template=re.sub(r'path="res://\.godot/imported/[^\"]+"','path="res://.godot/imported/'+name+'-'+digest+'.ctex"',template,count=1);template=re.sub(r'source_file="[^\"]+"','source_file="res://'+resource+'"',template);template=re.sub(r'dest_files=\[[^\]]+\]','dest_files=["res://.godot/imported/'+name+'-'+digest+'.ctex"]',template);assert 'compress/mode=0' in template;(assets/(name+'.import')).write_text(template,encoding='utf-8',newline='\n')
 rows.append(dict(id='GEO-RIVER-RUNTIME-'+name.upper().replace('.PNG',''),path=resource,source_path=source,sha256=sha(target),source_sha256=sha(b/source),source_dimensions=list(im.size),pixel_modifications='None; exact complete derivative bytes copied. Atlas regions sample authored pixels without raster edits.',visible_region_score=4.6 if name in ['nodes.png','earth_bed.png'] else 4.5,complete_source_score=4.4 if name in ['nodes.png','dry_junctions.png'] else 4.6,owner_acceptance=None,runtime_binding_state='REVERSIBLE_TOPIC_CANDIDATE_PENDING_ACTUAL_REVIEW'))
write(f/'ARTWORK_ITEMS.json',dict(baseline=base,created_utc=now,items=rows,qualification='Whole-source rejected subregions and selected visible runtime regions retain distinct scores. No source pixel or alpha cleanup; ordinary-route review pending.'))
p=b/'scripts/opera_geology_surface.gd';text=p.read_text(encoding='utf-8');(f/'BASELINE_OPERA_GEOLOGY_SURFACE.txt').write_text(text,encoding='utf-8',newline='\n');before=sha(p)
text=text.replace('## River drawing, room composition and actor contact retain their own priorities.','## Painted river regions retain separate room, actor and complete-action reviews.')
text=text.replace('const CRYSTALS_PATH := WORK_ART + "mineral.png"','const CRYSTALS_PATH := WORK_ART + "mineral.png"\nconst RIVER_ART := "res://assets/opera/worlds/geology/painted_river_v1_20261002/"\nconst RIVER_NATIVE_TO_RUNTIME := 1024.0 / 1254.0')
text=text.replace('var _fossil_soil_texture: Texture2D = null','var _fossil_soil_texture: Texture2D = null\nvar _river_source_textures: Dictionary = {}\nvar _river_atlas_regions: Dictionary = {}\nvar _river_dry_circle: Texture2D = null\nvar _river_wet_circle: Texture2D = null\nvar _river_earth: Texture2D = null')
needle='\t_fossil_soil_texture = _geode_atlas(WORK_ART + "fossil_soil.png", Rect2(72, 171, 881, 684))';assert text.count(needle)==1
text=text.replace(needle,needle+'''\n\t_river_atlas_regions.clear()
\t_river_source_textures.clear()
\t_river_dry_circle = null
\t_river_wet_circle = null
\t_river_earth = null
\tif mode == "geology_river":
\t\t_river_earth = _optional_texture(RIVER_ART + "earth_bed.png")
\t\t_river_dry_circle = _river_region("nodes.png", Rect2(44, 167, 560, 547))
\t\t_river_wet_circle = _river_region("nodes.png", Rect2(655, 167, 560, 547))
''')
code=(b/'audit/job_river_join_study_v1_20261001/join_surface_v7.gd').read_text(encoding='utf-8');start=code.index('func _draw_circle_art');end=code.index('func _draw_work_surface');circle=code[start:end].replace('_draw_circle_art','_draw_river_circle_art').replace('wet_circle if wet else dry_circle','_river_wet_circle if wet else _river_dry_circle').replace('\tvar size_now :=','\tif art == null:\n\t\treturn\n\tvar size_now :=')
start=code.index('func _mask(');fields=code[start:];fields=fields.replace('_mask(','_river_neighbor_mask(').replace('_draw_field(','_draw_river_field(').replace('_draw_circle_art(','_draw_river_circle_art(').replace('var source_path := JUNCTIONS + ("wet_attempt_02/" if wet else "dry_attempt_02/") \\\n\t\t+ "whole_canvas_1024.png"','var source_path := "wet_junctions.png" if wet else "dry_junctions.png"').replace('(JUNCTIONS + "straight_attempt_02/whole_canvas_1024.png") if wet \\\n\t\t\telse (PARTS + "attempt_02/whole_canvas_1024.png")','"wet_straight.png" if wet else "dry_straight.png"').replace('_region(source_path,region_now)','_river_region(source_path,region_now)')
assert 'JUNCTIONS' not in fields and 'PARTS' not in fields
fields=fields.replace('\tdraw_set_transform(center,angle)','\tif art == null:\n\t\treturn\n\tdraw_set_transform(center,angle)')
cache='''func _river_region(source_name: String, native_rect: Rect2) -> Texture2D:
\tvar key := source_name + str(native_rect)
\tif _river_atlas_regions.has(key):
\t\treturn _river_atlas_regions[key] as Texture2D
\tif not _river_source_textures.has(source_name):
\t\t_river_source_textures[source_name] = _optional_texture(RIVER_ART + source_name)
\tvar source := _river_source_textures[source_name] as Texture2D
\tif source == null:
\t\treturn null
\tvar atlas := AtlasTexture.new()
\tatlas.atlas = source
\tatlas.region = Rect2(native_rect.position * RIVER_NATIVE_TO_RUNTIME,
\t\tnative_rect.size * RIVER_NATIVE_TO_RUNTIME)
\t_river_atlas_regions[key] = atlas
\treturn atlas


'''
start=text.index('func _draw_river()');end=text.index('func _river_flow_indices()',start);text=text[:start]+cache+circle+fields+'\n\n'+text[end:]
needle='\t# River excavation retains its diagram until a matching material is reviewed.\n\tif mode != "geology_river" and _work_slab_texture != null:';assert needle in text;text=text.replace(needle,'\tif mode == "geology_river" and _river_earth != null:\n\t\tdraw_texture_rect(_river_earth,\n\t\t\tRect2(Vector2(248.0, 114.0), Vector2(1024.0, 512.0)), false)\n\t\treturn\n\tif mode != "geology_river" and _work_slab_texture != null:')
p.write_text(text,encoding='utf-8',newline='\n');write(f/'IMPLEMENTATION.json',dict(baseline=base,changed_script=p.relative_to(b).as_posix(),before_sha256=before,after_sha256=sha(p),scope='Drawing only; inherited grid, stroke/save/progress/flow/completion code unchanged. Imported texture and AtlasTexture caches, cleared when modes configure. River textures only loaded for river mode.',mechanic_methods_unchanged=['_river_stroke','river_path_cell_center','_river_connected','_river_flow_indices','progress_snapshot','restore_progress']))
# Preserve the tested actual career viewport-touch sequence, changing output location only.
old='audit/job_geology_painted_work_v1_20261001';new=f.relative_to(b).as_posix();capture=(b/(old+'/capture_geology_painted_work.gd')).read_text(encoding='utf-8').replace(old+'/attempt_04/',new+'/attempt_01/');(f/'capture_geology_river_runtime.gd').write_text(capture,encoding='utf-8',newline='\n')
runner=(b/(old+'/review_tools/run_geology_work_gates_v173.py')).read_text(encoding='utf-8').replace(old,new).replace('job-geology-painted-work-20261001.json',ip.name).replace('run_geology_work_gates_v173.py','run_geology_river_gates_v216.py').replace('capture_geology_painted_work.gd','capture_geology_river_runtime.gd').replace('geology_work_'+"'",'geology_river_'+"'").replace('v154','v216').replace('painted_work_v1_20261001','painted_river_v1_20261002');(f/'review_tools/run_geology_river_gates_v216.py').write_text(runner,encoding='utf-8',newline='\n')
ci=(b/(old+'/review_tools/run_geology_work_full_ci_v177.py')).read_text(encoding='utf-8').replace(old,new).replace('job-geology-painted-work-20261001.json',ip.name).replace('run_geology_work_full_ci_v177.py','run_geology_river_full_ci_v216.py')
ci=ci.replace("previous=json.loads((root/'audit/job_geode_runtime_v1_20261001/full_ci_v2/SOURCE_BEFORE.json').read_text())", "previous=json.loads((root/'audit/job_geology_painted_work_v1_20261001/full_ci_v1/SOURCE_BEFORE.json').read_text())")
ci=ci.replace("paths={r['path'] for r in previous['source_files']}","paths={r['path'] for r in previous['source_files']}\n paths.update('assets/opera/worlds/geology/painted_river_v1_20261002/'+name+suffix for name in ['nodes.png','dry_straight.png','wet_straight.png','dry_junctions.png','wet_junctions.png','earth_bed.png'] for suffix in ['', '.import'])\n paths.add('audit/job_geology_river_runtime_v1_20261002/capture_geology_river_runtime.gd')")
ci=ci.replace("paths.update(['scripts/opera_hotspot_catalog.gd','scripts/opera_world_hotspot_2d.gd','audit/job_geology_river_runtime_v1_20261002/capture_geology_painted_work.gd'])","paths.update(['scripts/opera_hotspot_catalog.gd','scripts/opera_world_hotspot_2d.gd'])")
(f/'review_tools/run_geology_river_full_ci_v216.py').write_text(ci,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
licenses=b/'ASSET_LICENSES.md';text=licenses.read_text(encoding='utf-8');text+='\n'+'\n'.join('| `'+x['path']+'` | Owner-commissioned built-in ImageGen; source '+x['source_path']+' | Project-generated reversible candidate; owner acceptance pending | audit/job_geology_river_runtime_v1_20261002/ARTWORK_ITEMS.json | Exact full derivative copy; source SHA '+x['sha256']+'. Atlas regions preserve pixels; source rejected extras remain explicit; selected visible detail4.5 provisional, full action pending. |' for x in rows)+'\n';licenses.write_text(text,encoding='utf-8',newline='\n')
d=read(ip);d['files']=sorted(set(d['files'])|{'ASSET_LICENSES.md'}|{p.relative_to(b).as_posix() for folder in [f,assets] for p in folder.rglob('*') if p.is_file()});write(ip,d)
print('Bound exact6 painted-river sources; mechanic methods unchanged; actual-route/full-suite verification pending.')
