from pathlib import Path
import datetime, hashlib, json, re, shutil, subprocess
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geology_river_runtime_v1_20261002';s=b/'audit/job_river_join_study_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write(s/'BROWSER_QA_V25_V7_SOURCEV2.json',dict(checked_utc=now,method='Read-only CUA DOM evaluation of rendered localhost allowlisted galleries.',observations=[dict(url='http://127.0.0.1:8880/audit/job_river_join_study_v1_20261001/index_v7.html?revision=river-v7',cards=28,images=28,loaded=28,broken=0,document_width=1265,viewport_width=1280),dict(url='http://127.0.0.1:8880/audit/job_artwork_refinement_live/all_items.html?revision=register-v25',filter='all',query='GEO-RIVER-',matches=55,pages=[dict(cards=30,loaded=30,pending=0,broken=0),dict(cards=25,loaded=25,pending=0,broken=0)],document_width=1265,viewport_width=1280),dict(url='http://127.0.0.1:8880/assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html?revision=source-v2',images=43,loaded=43,pending=0,broken=0,regions=30,document_width=1265,viewport_width=1280)],qualification='Exact rendered gallery verification, no saved browser screenshot claimed, not actual-use or complete-action/owner acceptance.'))
before=(f/'BASELINE_OPERA_GEOLOGY_SURFACE.txt').read_text(encoding='utf-8');after=(b/'scripts/opera_geology_surface.gd').read_text(encoding='utf-8')
def function(text,name):
 start=text.index('func '+name+'(');end=text.find('\nfunc ',start+1);return text[start:end if end>=0 else len(text)].strip()
names=['_river_stroke','river_path_cell_center','_river_connected','_river_flow_indices','progress_snapshot','restore_progress'];checks=[]
for name in names:
 a=function(before,name);z=function(after,name);assert a==z,name;checks.append(dict(method=name,before_sha256=hashlib.sha256(a.encode()).hexdigest(),after_sha256=hashlib.sha256(z.encode()).hexdigest(),unchanged=True))
write(f/'MECHANIC_UNCHANGED.json',dict(status='EXACT_SIX_MECHANIC_METHODS_UNCHANGED',checked_utc=now,functions=checks,qualification='Mechanical source proof separate from intentional/passive/save/completion and full-suite execution.'))
p=b/'design/05_DOC_LEDGER.md';text=p.read_text(encoding='utf-8');text='\n'.join('| `audit/job_artwork_refinement_live/all_items.html` | 🟣 | `CANDIDATE`; currentV25 known register1641 entries/1225 exact-source candidates/328 pose cells/38 runtime prop regions/50 source-object regions. Inclusive605 current source priorities and388 unassigned opinions remain. Every river iteration individually scored with failed edges/glows retained. Shared candidates do not prove exhaustive actual-use, mounted/action or owner acceptance. |' if '`audit/job_artwork_refinement_live/all_items.html`' in line else line for line in text.split('\n'));p.write_text(text,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
for name,folder in [('job-geology-river-join-study-20261001',s),('job-geology-river-junction-source-20261001',b/'assets_src/imagegen/geologist_river_junctions_v1_20261001'),('job-geology-river-bed-source-20261002',b/'assets_src/imagegen/geologist_river_bed_v1_20261002'),('job-geology-river-painted-runtime-20261002',f)]:
 ip=b/('design/audit_impacts/'+name+'.json');d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in folder.rglob('*') if p.is_file()}|({'design/05_DOC_LEDGER.md'} if name=='job-geology-river-painted-runtime-20261002' else set()));write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';d=read(allow);assert isinstance(d,list);write(allow,sorted(set(d)|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}))
q=subprocess.run(['git','diff','--name-only','-z'],cwd=b,capture_output=True,check=True);paths=[p.decode() for p in q.stdout.split(b'\0') if p];q2=subprocess.run(['git','status','--porcelain','-z','--untracked-files=no'],cwd=b,capture_output=True,check=True)
print('Actual content diff',len(paths),'files;',sum(p.endswith('.import') for p in paths),'import metadata files; status entries',len([x for x in q2.stdout.split(b'\0') if x]));print('Mechanic methods unchanged6; browser library43/43 and register55/55 PASS.')
