from pathlib import Path
import datetime, hashlib, html, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geology_river_runtime_v1_20261002';prefix=f.relative_to(b).as_posix()
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat()
views=[]
for width in [1280,1600]:
 # Preserve the first wrapper's false failure: it searched for the unrelated four-phase marker.
 gate=f/'runtime_gate';original=read(gate/('network%dv1.receipt.json'%width))
 assert original['process_exit']==0 and original['blocking_diagnostics']==[]
 logs=gate/('network%dv1.stdout.log'%width);assert sha(logs)==original['stdout_sha256']
 assert 'RIVER_JOIN_CAPTURE|PASS|'+str(width)+'|14views|ONE_COMPLETION|VISUAL_PENDING' in logs.read_text(encoding='utf-8')
 write(gate/('network%dv2.validation.json'%width),dict(status='PASS_CORRECT_MARKER_VALIDATION',reviewed_utc=now,first_receipt='network%dv1.receipt.json'%width,process_exit=0,stdout_sha256=sha(logs),stderr_sha256=original['stderr_sha256'],reason='The first wrapper incorrectly required ALL4_INTENTIONAL_PHASES for this isolated14-state network fixture. Correct marker and exit0 with no blocking diagnostics independently confirm the recorded run. No capture rerun, script change or overwritten failure receipt.',qualification='Actual renderer14 input/flow/restore/completion assertions; not actor/room/action/global approval.'))
 d=read(f/('network_attempt_01/MANIFEST_%d.json'%width));assert len(d['views'])==14
 for x in d['views']:
  x=dict(x);assert sha(b/x['path'])==x['sha256'];x['direct_review']=True;x['scores']=dict(earth=4.6,visible_network=4.6 if x['state'] in ['dry_initial','isolated_dry'] else 4.5,actor_contact=None,room=None,complete_action=None)
  x['evaluation']='Direct native actual-renderer review: painted earth and rounded excavation/source bowls remain clear. '+('No joined network at this state.' if x['state'] in ['dry_initial','isolated_dry'] else 'Continuous open ports keep the actual corner/T/cross/loop topology readable; small bank/value steps remain an inclusive4.5 provisional priority.')
  x['qualification']='Actual production OperaGeologySurface, no drawing subclass/override. Real viewport touches and unchanged progress methods. An isolated network test; no actor/room/ordinary route/timed action/device/child/owner score.'
  views.append(x)
review=dict(status='ALL28_ACTUAL_RENDERER_NETWORK_VIEWS_DIRECTLY_INSPECTED',reviewed_utc=now,views=views,qualification='Dry isolated/straight/corner/T/cross and connected wet network, arbitrary branches, JSON-restored partial work and quiet single completion are independently checked at both widths. Every28 still directly reviewed, bed4.6, selected joined shapes4.5 provisional; actor/room/continuous action excluded.')
write(f/'NETWORK_REVIEW.json',review)
esc=html.escape;cards=''.join('<figure><a href="../../'+esc(x['path'])+'"><img loading="eager" src="../../'+esc(x['path'])+'" alt="'+esc(x['state'])+' '+str(x['dimensions'][0])+'"></a><figcaption>'+str(x['dimensions'][0])+' · <b>'+esc(x['state'])+'</b><p>'+esc(x['evaluation'])+'</p><small>'+x['sha256']+'</small></figcaption></figure>' for x in views)
(f/'network.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Production river join review</title><style>body{margin:0;background:#eef4fa;font:17px/1.5 system-ui;color:#25304a}main{padding:24px;max-width:1460px;margin:auto}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,600px),1fr));gap:18px}figure{margin:0;padding:18px;border-radius:14px;background:white;min-width:0}img{width:100%;height:auto;display:block}small{font-size:12px;overflow-wrap:anywhere;display:block}</style><main><a href="index.html">Actual four-phase geology review</a><h1>Actual production river: every joined shape</h1><p>All28 native1280/1600 views directly inspected. This fixture uses the production renderer without a drawing override. Bed4.6; current joined shapes4.5 provisional. Actual viewport inputs check dry isolated components, source-connected wetting, corners, T branches, crosses, loops, JSON restore and single earned completion.</p><p><a href="NETWORK_REVIEW.json">Written scores and exact hashes</a> · <a href="runtime_gate/network1280v2.validation.json">1280 corrected marker receipt</a> · <a href="runtime_gate/network1600v2.validation.json">1600 corrected marker receipt</a>. First wrapper false-failure receipts remain preserved. Actor/room/full timed action/device/child/owner acceptance is separate.</p><section>'+cards+'</section></main></html>',encoding='utf-8',newline='\n')
p=f/'index.html';text=p.read_text(encoding='utf-8').replace('<a href="REVIEW.json">Complete written evaluations','<a href="network.html">Every28 additional actual-renderer join/restore state</a> · <a href="REVIEW.json">Complete written evaluations');p.write_text(text,encoding='utf-8',newline='\n')
p=f/'REVIEW.json';d=read(p);d['network_review']='NETWORK_REVIEW.json';d['counts']['additional_direct_actual_renderer_network_views']=28;d['machine_evidence']['network_1280']='runtime_gate/network1280v2.validation.json';d['machine_evidence']['network_1600']='runtime_gate/network1600v2.validation.json';write(p,d)
p=b/'ASSET_LICENSES.md';text=p.read_text(encoding='utf-8')+'\n### Actual production river join native review (2026-10-02)\n\n'
for x in views:
 if x['path'] not in text:text+='| `'+x['path']+'` | Native Godot4.7.2 Mobile desktop capture of licensed painted river regions | Project review evidence; underlying source licenses retained | `'+prefix+'/NETWORK_REVIEW.json` | Lossless WebP native viewport, unmodified pixels; direct review, SHA256 '+x['sha256']+' |\n'
p.write_text(text,encoding='utf-8',newline='\n')
write(f/'BROWSER_QA_V26_ACTUAL.json',dict(checked_utc=now,method='Read-only CUA DOM evaluation',observations=[dict(url='http://127.0.0.1:8880/'+prefix+'/index.html?revision=actual-river-v1',images=46,loaded=46,broken=0,objects=37,document_width=1265,viewport_width=1280)],qualification='Rendered exact gallery only; no saved browser screenshot or owner approval claimed.'))
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-painted-runtime-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Actual production renderer14 states at each width; every28 native stills directly inspected',result='PASS',evidence=prefix+'/NETWORK_REVIEW.json; marker-only first wrapper failure corrected by bothv2.validation.json receipts without replacing evidence.'));write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{p.relative_to(b).as_posix() for p in (b/'assets/opera/worlds/geology/painted_river_v1_20261002').rglob('*') if p.is_file()}))
print('All28 actual-renderer joins reviewed; first wrapper false-failure preserved and independently corrected; preview six runtime PNG paths now allowed.')
