from pathlib import Path
import datetime, hashlib, html, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f=b/'audit/job_geology_river_runtime_v1_20261002'; prefix=f.relative_to(b).as_posix()
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest(); now=datetime.datetime.now(datetime.timezone.utc).isoformat()
m=read(f/'TIMED_CAPTURE_MANIFEST.json'); frames=[]
for x in m['frames']:
 x=dict(x); assert sha(b/x['path'])==x['sha256']; n=x['index']; tail=n>=112
 x['direct_review']=True; x['review_method']='Every native frame represented once in a directly inspected ordered board. Threshold frames31/32/65/66 additionally inspected at native resolution at both widths.'
 x['native_detail_review']=n in [31,32,65,66]
 x['scores']=dict(geode_material=4.6,embedded_crystal_semantics=4.6,working_hand_contact=None if n>=92 else 2.7,actor_celebration_transition=4.0 if 92<=n<112 else None,adjacent_state_continuity=4.2 if n in [32,66] else None,production_exit=None)
 state='closed prepared seam' if n<2 else 'early crack' if n<32 else 'middle opening' if n<66 else 'fully open embedded cavities'
 x['evaluation']=state.capitalize()+'. Crystals remain rooted inside the mineral cavities; no detached loot layer. '
 if n==32:x['evaluation']+='The early-to-middle artwork swap abruptly widens the object at the40-pixel pull threshold; continuous opening fails the4.5 floor.'
 elif n==66:x['evaluation']+='The middle-to-full artwork swap widens the object and lowers its upper edge by about30 canvas pixels while the base stays planted; continuous opening fails the4.5 floor.'
 elif tail:x['evaluation']+='Post-job fixture tail: the completion callback is empty, so guide/Roshan hide and the underlying world appears behind the retained work panel. This is not evidence of the real castle/story/room return.'
 elif n>=92:x['evaluation']+='Clapping keeps identity and the crystals embedded, but the working-pose to clap transition is abrupt. Celebration transition4.0 provisional, distinct from source identity4.6.'
 else:x['evaluation']+='The actor remains at the lower-left floor with hands away from the raised work object; contact2.7. The painting does not establish connected acting.'
 x['priority']=n in [32,66] or n<112; x['owner_acceptance']=None; frames.append(x)
boards=[]
for x in m['boards']:
 x=dict(x); assert sha(b/x['path'])==x['sha256']; x['direct_review']=True; x['review_method']='Every cell inspected in row-major order; complete12-frame board, no sampling.'; boards.append(x)
sources=[]
for p in sorted((b/'assets/opera/worlds/geology/painted_geode_v1_20261001').glob('*.png')):sources.append(dict(path=p.relative_to(b).as_posix(),sha256=sha(p)))
r=dict(schema='reef.continuous-geode-review.v1',reviewed_utc=now,status='EVERY312_NATIVE_RENDERED_FRAMES_REVIEWED_ON26_ORDERED_BOARDS_WITH8_NATIVE_THRESHOLD_DETAILS',baseline='40b1c7bfe025f284507c586fea61b9dd76b61423',frames=frames,boards=boards,source_art=sources,production_script=dict(path='scripts/opera_geology_surface.gd',sha256=sha(b/'scripts/opera_geology_surface.gd')),scores=dict(continuous_opening=4.2,geode_material=4.6,embedded_crystal_semantics=4.6,working_hand_contact=2.7,celebration_transition=4.0,production_exit=None),findings=[dict(id='GEO-TIMED-OPEN-01',score=4.2,frames=[31,32],evaluation='Early/middle source swap at pull40 abruptly expands the geode silhouette.'),dict(id='GEO-TIMED-OPEN-02',score=4.2,frames=[65,66],evaluation='Middle/full source swap at pull90 abruptly expands silhouette and drops the top about30 canvas pixels; base remains planted.'),dict(id='GEO-TIMED-CONTACT',score=2.7,evaluation='Hands remain on the lower-left floor away from the work object; source material improvement does not repair performing the action.'),dict(id='GEO-TIMED-CLAP',score=4.0,evaluation='Celebration switches abruptly from the remote working pose. Source identity4.6 remains separate.'),dict(id='GEO-TIMED-TAIL',score=None,evaluation='Empty fixture completion callback does not exercise actual production exit. No production return defect or score inferred.')],counts=dict(native_frames=312,ordered_boards=26,native_threshold_details=8,frames_per_width=156),qualification='Actual production renderer and intentional viewport input/ordinary four-phase advancement. This continuous fixture uses no freeze or explicit JSON restore interruption. Readback slows wall-clock playback; timestamps are retained and no human/device timing acceptance is claimed. Earlier sampled4.5 opinions remain valid only for their sampled boundary; this later continuous opening is4.2 and is a refinement priority. Every312 frame reviewed via complete ordered boards, not312 native detail inspections. Not authored cinematic delivery, complete production exit, training/story, device, child or owner approval.')
write(f/'TIMED_REVIEW.json',r)
esc=html.escape
bc=''.join('<figure><a href="../../'+esc(x['path'])+'"><img src="../../'+esc(x['path'])+'" alt="'+str(x['width'])+' frames '+str(x['first_frame'])+'–'+str(x['last_frame'])+'"></a><figcaption>'+str(x['width'])+' · frames '+str(x['first_frame'])+'–'+str(x['last_frame'])+' · row-major, every frame reviewed<small>'+x['sha256']+'</small></figcaption></figure>' for x in boards)
fc=''.join('<article><a href="../../'+esc(x['path'])+'">'+str(x['width'])+' frame '+str(x['index'])+'</a><p>'+esc(x['evaluation'])+'</p><small>'+esc(json.dumps(x['scores']))+' · SHA256 '+x['sha256']+'</small></article>' for x in frames)
(f/'timed.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geode continuous opening review</title><style>body{margin:0;background:#eef4fa;color:#25304a;font:17px/1.5 system-ui}main{max-width:1460px;margin:auto;padding:24px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,600px),1fr));gap:18px}figure,article{background:white;padding:18px;border-radius:14px;margin:0;min-width:0}img{width:100%;height:auto;display:block}small{font-size:12px;overflow-wrap:anywhere;display:block}.frames{grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}</style><main><a href="index.html">Actual geology review</a><h1>Geode: every frame from opening through celebration</h1><p>Continuous opening4.2/5: the two source swaps jump in width, and the fully open swap drops the top about30 canvas pixels. Individual painted material and rooted crystal semantics4.6. Working contact2.7 and celebration pose transition4.0 remain priorities. Earlier sampled still4.5 was provisional and did not prove these in-between frames.</p><p>All312 native frames appear once on26 ordered boards; all board cells directly reviewed, plus8 native threshold details. Every individual frame has a written evaluation below. Frame readback slows wall-clock playback; this is not exact device/human timing acceptance.</p><p>The tail after frame111 is fixture-only: its empty completion callback does not exercise the real production return. No castle/story/room-return defect or score is inferred.</p><p><a href="TIMED_REVIEW.json">Complete scores, source hashes and per-frame evaluations</a> · <a href="TIMED_CAPTURE_MANIFEST.json">Preserved initial capture manifest</a></p><section>'+bc+'</section><h2>Individual frame evaluations and original native files</h2><section class="frames">'+fc+'</section></main></html>',encoding='utf-8',newline='\n')
# Correct one report-only source typo; preserve the historical sampled assessment.
p=f/'REVIEW.json'; d=read(p)
for x in d['individual_objects']:
 if x['id']=='GEO-ACTUAL-WORK-SLAB':x['source']='assets/opera/worlds/geology/painted_work_v1_20261001/work_slab.png'
 if x['id']=='GEO-ACTUAL-GEODE-OPENING':x['later_continuous_review']=dict(path=prefix+'/TIMED_REVIEW.json',score=4.2,reason='Later full opening exposes threshold jumps; original sampled opinion retained at its evidence boundary.')
d['timed_review']='TIMED_REVIEW.json'; write(p,d)
p=f/'index.html'; s=p.read_text(encoding='utf-8').replace('painted_work_v1_20261001/slab.png','painted_work_v1_20261001/work_slab.png').replace('<h1>Geologist: actual game artwork review</h1>','<h1>Geologist: actual game artwork review</h1><p><a href="timed.html">Later continuous geode review: every312 frames, opening4.2 and two threshold jumps</a>. Sampled still scores below retain their earlier boundary.</p>'); p.write_text(s,encoding='utf-8',newline='\n')
text='Later continuous geode review (2026-10-02): every312 rendered frames reviewed on26 complete ordered boards, plus8 native threshold details. [Illustrated per-frame evaluations]({link}) record continuous opening4.2: abrupt width swaps at40/90 pull and about30px top drop at full opening. Material/rooted crystal semantics4.6, working contact2.7 and celebration transition4.0 remain separate. Earlier sampled4.5 remains a dated provisional still opinion. The post-job tail has an empty fixture callback and does not establish production return. Readback slows wall-clock pacing; full production exit/training/story/device/child/owner/final all-job acceptance and lifecycle remain open.'
p=b/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');s=s.replace('# Mermaid Roshan: Reef of Light — game-wide master audit\n','# Mermaid Roshan: Reef of Light — game-wide master audit\n\n'+text.format(link='job_geology_river_runtime_v1_20261002/timed.html')+'\n',1);p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=p.read_text(encoding='utf-8');at=s.index('\n## ',s.index('## MA-PLAY-004')+len('## MA-PLAY-004'));s=s[:at]+'\n'+text.format(link='../job_geology_river_runtime_v1_20261002/timed.html')+'\n'+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s+='\n| `'+prefix+'/timed.html` | 🟣 | `CANDIDATE`; every312 actual geode native frame reviewed on26 complete ordered boards plus8 native threshold details. Continuous opening4.2 supersedes a full-action inference from sampled still4.5; historical sampled score retained. Embedded semantics/material4.6, contact2.7/celebration transition4.0 remain separate; slowed readback and fixture-only tail do not prove natural device timing or production exit. No lifecycle/owner/global acceptance. |\n';p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/job_artwork_refinement_live/index.html';s=p.read_text(encoding='utf-8');at=s.index('<main>')+len('<main>');s=s[:at]+'<section><h2>Current continuous geode opening</h2><p><a href="../job_geology_river_runtime_v1_20261002/timed.html">Every312 frames and individual evaluations</a>: opening4.2 remains a priority after two threshold jumps. Crystals stay embedded4.6; contact2.7 and celebration transition4.0 remain. Earlier sampled scores retain their boundaries.</p></section>'+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n### Continuous geode native and ordered-board review (2026-10-02)\n\n'
for x in frames+boards:
 if x['path'] not in s:s+='| `'+x['path']+'` | Godot4.7.2 Mobile capture of existing licensed project artwork | Project review evidence; source licenses retained | `'+prefix+'/TIMED_REVIEW.json` | '+('Complete12-frame row-major board made by uniform whole-scene ffmpeg downscale and tiling; review only, no delivery art' if 'first_frame' in x else 'Unmodified native lossless WebP viewport capture')+'; SHA256 '+x['sha256']+' |\n'
p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-painted-runtime-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/index.html'});d['validation'].append(dict(command='Every312 continuous geode frame on26 ordered boards plus8 native threshold details',result='PASS',evidence=prefix+'/TIMED_REVIEW.json: evidence complete, graphics opening4.2 FAIL floor; no creative pass.'));d['acceptance_gaps']+=' Later continuous geode opening4.2 and celebration transition4.0 remain priorities; fixture tail does not exercise production exit.';write(ip,d)
p=b/'tmp/v2_preview_allowed.json';write(p,sorted(set(read(p))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}))
print('312 per-frame opinions,26 directly inspected boards,8 native threshold details; continuous opening4.2 recorded without rewriting historical still4.5.')
