from pathlib import Path
import datetime, hashlib, html, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f=b/'audit/job_geology_river_runtime_v1_20261002'; prefix=f.relative_to(b).as_posix()
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat()
sources=read(f/'ARTWORK_ITEMS.json')
for x in sources['items']:x['runtime_binding_state']='BOUND_REVERSIBLE_TOPIC_CANDIDATE_DIRECT_NATIVE_REVIEW';x['latest_runtime_report']=prefix+'/REVIEW.json'
sources['qualification']='Six exact complete runtime copies. Whole-source red fringes/unused closed ports retain failed scores; directly reviewed selected game-visible regions are scored separately. No source pixel cleanup or owner/global approval.'
write(f/'ARTWORK_ITEMS.json',sources)
objects=[]
def obj(id,name,score,evaluation,phases,refinement,source=None):
 objects.append(dict(id='GEO-ACTUAL-'+id,name=name,visible_graphics_score=score,evaluation=evaluation,phases=phases,refinement=refinement,source=source,priority=score<=4.5,owner_acceptance=None,complete_action_score=None))
obj('ROOM-WALL','Room wall',2.8,'Large uniform navy/teal polygons read as a vector placeholder around the painted props. Painted material, contour and scale relationships are missing.',['ALL'],'Inventory suitable painted room sources; native per-screen coverage must meet the master rule.','scripts/opera_career_world_2d.gd')
obj('ROOM-FLOOR','Room floor',2.8,'The flat purple floor gives no painted ledge/contact hierarchy for Roshan or the work station.',['ALL'],'Replace only this measured room material gap using a qualified source.','scripts/opera_career_world_2d.gd')
obj('ROOM-STRATA','Six strata bands',2.6,'Six thick zigzag lavender bands cross behind every task. Their repeated straight geometry overwhelms the rounded painted objects.',['ALL'],'A coherent painted cave/strata scene needs quieter value bands and authored irregular edges.','scripts/opera_career_world_2d.gd')
obj('INVITATION-TRAY','World invitation tray',2.9,'Solid tan rectangle remains flat and untextured, with no visual support for the geology invitation.',['INVITATION'],'Reuse the exact painted work support if its world-scale composition can pass.','scripts/opera_career_world_2d.gd')
obj('INVITATION-RING','World invitation pan ring',3.0,'Plain circular purple ring on the tan tray differs from the painted rounded pan used inside the task.',['INVITATION'],'Reuse the approved current pan painting with preserved aspect; inspect mounted readability.','scripts/opera_career_world_2d.gd')
for n in range(1,4):obj('SHELF-'+str(n),'World outlined shelf '+str(n),3.0,'A thin square aqua outline reads as a target UI box rather than a painted exhibit or room prop.',['INVITATION'],'Reuse a suitable painted tray/exhibit support without covering the touch target.','scripts/opera_career_world_2d.gd')
obj('WORLD-CRYSTALS','World crystal silhouette cluster',3.0,'Large flat turquoise/lavender triangles have no painted rim/material treatment and remain visibly inconsistent with the new embedded geode.',['INVITATION'],'Inspect existing painted mineral cutout reuse and world aspect/scale before generating.','scripts/opera_career_world_2d.gd')
obj('WORLD-CUE','World target ring',3.9,'Aqua target ring stays readable, but its heavy uniform line overlaps the guide/exhibit and lacks clear scene ownership.',['INVITATION'],'Tune placement and weight after the exhibit painting is mounted.','scripts/opera_career_world_2d.gd')
obj('ROSHAN-IDENTITY','Roshan geologist identity',4.6,'Established face, rainbow fin, lavender eyes and explorer outfit stay painted and recognizable at both widths.',['ALL'],'Preserve this approved identity family.','assets/characters/roshan_25d/')
obj('ROSHAN-WORK-CONTACT','Roshan working contact',2.7,'Her crawling hands touch the lower-left floor while the river, fossil, pan and geode sit far above/right. The selected pose does not visibly perform the job.',['TASK_OPEN','PARTIAL_WORK'],'Use a connected work pose and measured hand sockets; inspect the entire reach/work/release/return.','scripts/opera_career_world_2d.gd')
obj('ROSHAN-CELEBRATION','Roshan completion still',4.5,'Visible celebration is readable and preserves identity. Geode completion claps without removing its crystals; stills do not prove acting transitions.',['EARNED_COMPLETION'],'Review the full transition/contact and ordinary exit; retain as an inclusive priority.','assets/characters/roshan_25d/')
obj('IMP-IDENTITY','Geology guide artwork',4.6,'Painted purple guide, teal coat and magnifier retain a strong child-readable silhouette.',['ALL'],'Reuse this established guide artwork.','assets/opera/')
obj('IMP-CONTACT','Guide work placement',3.8,'The guide is visible but stands away from the objects; some invitation overlap with the crystal/ring remains.',['ALL'],'Review guide placement and meaningful pointing/teaching contact.','scripts/opera_career_world_2d.gd')
obj('RIVER-EARTH','River earth bed',4.6,'Broad painted cream/gold excavation bed with lavender outline/shadow contains the grid at both widths. This is a wide prop, not a qualified room background.',['RIVER'],'Preserve complete authored canvas and review foreground/actor work context.',sources['items'][-1]['path'])
obj('RIVER-NODES','River spring and outlet bowls',4.6,'Rounded painted pools stay legible in the actual task; source sheet includes rejected unused connectors which are not passed by these bowls.',['RIVER'],'Inspect every actual joined shape and flow consequence.',sources['items'][0]['path'])
for id,name in [('DRY','Dry excavation joins'),('WET','Wet river joins')]:obj('RIVER-'+id,name,4.5,'Current visible joining uses matte gold banks and quiet aqua water rather than diagram circles. Small bank/value steps remain at some joins; reached the provisional floor in directly reviewed final/open states.',['RIVER'],'Review arbitrary corner/T/cross/isolated/restore states with the actual renderer; full timed stroke and actor contact remain open.','scripts/opera_geology_surface.gd')
obj('RIVER-BRUSH','River held brush drawing',4.5,'Small painted brush is clearer than the former diagram treatment, but captured endpoints cannot establish exact hand contact during a stroke.',['RIVER'],'Inspect continuous actual stroke with hand socket alignment.','scripts/opera_geology_surface.gd')
obj('WORK-SLAB','Fossil/pan/geode stone support',4.6,'Complete cream stone slab retains painterly edges, purple bands and authored aspect under the three tasks.',['FOSSIL','PAN','GEODE'],'Preserve this exact canvas; inspect actor height/contact.','assets/opera/worlds/geology/painted_work_v1_20261001/slab.png')
obj('FOSSIL-MATERIAL','Fossil image',4.6,'Rounded cream spiral fossil/brown earth material has readable painted separation and established palette.',['FOSSIL'],'Preserve the conserved source image.','assets/opera/worlds/geology/painted_work_v1_20261001/fossil.png')
obj('FOSSIL-SOIL','Fossil soil cover',4.6,'Brown painted soil has depth, restrained colour and an authored edge before clearing.',['FOSSIL'],'Preserve the exact current painted soil.','assets/opera/worlds/geology/painted_work_v1_20261001/fossil_soil.png')
obj('FOSSIL-CLEARING','Partial fossil clearing',3.9,'The partial reveal retains a straight horizontal cover boundary and reads as a mask cutoff rather than brushed earth.',['FOSSIL'],'Refine the revealed boundary locally without changing the intentional progress mechanic.','scripts/opera_geology_surface.gd')
for n in range(1,4):obj('FOSSIL-PIECE-'+str(n),'Conserved fossil third '+str(n),4.5,'This exact source third rejoins the original fossil. Literal straight cuts and faint target support still look like a rectangular puzzle partition.',['FOSSIL'],'Retain exact painting/identity; inspect partition/support and naturally timed snap.', 'assets/opera/worlds/geology/painted_work_v1_20261001/fossil.png')
obj('PAN-MATERIAL','Pan and water',4.6,'Purple painted rim and quiet aqua basin preserve authored aspect and keep grains/minerals within the bowl at the reviewed extremes.',['PAN'],'Retain this art and containment; inspect hand-connected motion.','assets/opera/worlds/geology/painted_work_v1_20261001/pan.png')
obj('PAN-GRAINS','Pan sediment grains',4.6,'Small warm ochre painted grains remain clear on aqua and fit the prop language at both widths.',['PAN'],'Preserve restrained contrast and count readability.','assets/opera/worlds/geology/painted_work_v1_20261001/grain.png')
obj('PAN-MINERALS','Pan found mineral cutouts',4.6,'Painted aqua/lavender clusters remain contained in the bowl after completion. These belong to panning; the geode has no detached rewards.',['PAN'],'Review the full pan settling/finding sequence separately.','assets/opera/worlds/geology/painted_work_v1_20261001/mineral.png')
obj('PAN-ACTION','Pan horizontal motion',3.8,'Left/right stills show the complete pan translating horizontally while Roshan stays away. They do not show convincing gripping or articulated rocking.',['PAN'],'Reuse the tested connected gripping pose in a reversible action study and inspect full travel/return.','scripts/opera_geology_surface.gd')
for id,name in [('CLOSED','Closed geode'),('EARLY','Early cracked geode'),('MIDDLE','Middle opening geode'),('OPEN','Open geode')]:obj('GEODE-'+id,name,4.6,'Authored lavender/gold stone remains polished and rounded. Revealed aqua/lavender crystals sit inside the cavities and remain there through completion.',['GEODE'],'Preserve crystal attachment and review all in-between frames.', 'assets/opera/worlds/geology/painted_geode_v1_20261001/')
obj('GEODE-OPENING','Geode sampled opening sequence',4.5,'Actual inputs advance closed to early crack, middle and full cavity states before earned completion. Both halves expose embedded crystals; no loot-drop overlay. Sampled still continuity reaches the provisional floor.',['GEODE'],'Inspect the complete naturally timed opening, hand pull, release and return; owner acceptance pending.','scripts/opera_geology_surface.gd')
obj('GEODE-SEAM-CUES','Geode seam touch cues',3.9,'Five yellow/aqua circles correctly signal touch states but retain flat heavy geometry over the painted stone.',['GEODE'],'Review restrained cue weight/placement without changing input or progress.','scripts/opera_geology_surface.gd')
views=[]
for width in [1280,1600]:
 capture=read(f/('attempt_01/CAPTURE_%d.json'%width))
 for x in capture['views']:
  x=dict(x);x['path']=prefix+'/attempt_01/'+x['path'];x['sha256']=sha(b/x['path']);x['direct_native_review']=True
  scores={'room':2.8,'actor_work_contact':None if x['state'] in ['invitation','earned_completion'] else 2.7}
  phase=x['phase'];state=x['state'];scores['visible_material']=4.6
  if state=='invitation':scores['world_invitation_support']=2.9
  if phase=='RIVER' and state!='invitation':scores['visible_network']=4.6 if state=='task_open' else 4.5
  if phase=='FOSSIL':scores['clearing']=3.9 if state=='partial_brush' else None;scores['partition_support']=4.5 if state in ['brushed','one_piece','two_pieces','earned_completion'] else None
  if phase=='PAN' and state!='invitation':scores['containment']=4.6;scores['sampled_motion']=3.8 if state in ['pan_left','pan_right','partial_pan'] else None
  if phase=='GEODE':scores['embedded_crystal_semantics']=4.6 if state in ['early_crack','middle_open','full_interior_before_award','earned_completion'] else None;scores['sampled_opening']=4.5 if state in ['early_crack','middle_open','full_interior_before_award','earned_completion'] else None
  x['scores']=scores;x['evaluation']='Direct native inspection. '+('Invitation still exposes the weak flat room and outlined exhibit props.' if state=='invitation' else 'Painted work materials improve the scene; room and remote working pose remain separately weak.')
  x['qualification']='Actual production renderer/default four-phase career sequence. Test fixture supplies career entry; work and ordinary advancement use viewport touches. Every current still inspected, no full timed action/castle/training/story/device/child/owner acceptance.'
  views.append(x)
assert len(views)==46
ci=read(f/'full_ci_v1/RECEIPT.json')
review=dict(schema='reef.actual-geology-art-review.v1',reviewed_utc=now,baseline='40b1c7bfe025f284507c586fea61b9dd76b61423',status='46_CURRENT_NATIVE_STILLS_DIRECTLY_REVIEWED',views=views,individual_objects=objects,source_items=sources['items'],counts=dict(native_views=46,direct_native_views=46,individual_visible_objects=len(objects),visible_priorities=sum(x['priority'] for x in objects)),machine_evidence=dict(route_1280='runtime_gate/capture1280v1.receipt.json',route_1600='runtime_gate/capture1600v1.receipt.json',mechanic_unchanged='MECHANIC_UNCHANGED.json',full_suite='full_ci_v1/RECEIPT.json',full_suite_status_at_review=ci['status']),qualification='First-pass drafting opinions. Overall graphics are not passed by averaging strong props against weak surroundings. Latest current renderer river visible joins4.5 provisional/bed4.6; painted geology materials4.6 separate from room2.8, contact2.7, clearing3.9 and pan action3.8. Training/story and all-job final owner report remain open. No lifecycle closure or dev/master release.')
write(f/'REVIEW.json',review)
esc=html.escape
cards=''.join('<article id="'+esc(x['id'])+'"><h3>'+esc(x['id'])+' · '+esc(x['name'])+'</h3><p><b>'+str(x['visible_graphics_score'])+'/5'+(' · priority' if x['priority'] else '')+'</b></p><p>'+esc(x['evaluation'])+'</p><p>'+esc(x['refinement'])+'</p><small>'+esc(str(x['source']))+'</small></article>' for x in objects)
images=''
for width in [1280,1600]:
 for phase in ['RIVER','FOSSIL','PAN','GEODE']:
  images+='<h2>'+phase+' · '+str(width)+'×720</h2><div class="views">'
  for x in views:
   if x['phase']==phase and x['viewport'][0]==width:images+='<figure id="'+esc(x['id'])+'"><a href="../../'+esc(x['path'])+'"><img loading="eager" src="../../'+esc(x['path'])+'" alt="'+esc(x['id'])+'"></a><figcaption><b>'+esc(x['state'])+'</b><p>'+esc(x['evaluation'])+'</p><p>'+esc(json.dumps(x['scores']))+'</p><small>'+x['sha256']+'</small></figcaption></figure>'
  images+='</div>'
text='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Actual geology artwork · painted river candidate</title><style>body{margin:0;background:#eef4fa;color:#25304a;font:17px/1.5 system-ui}main{max-width:1460px;margin:auto;padding:24px}a{color:#51408d}header,article,figure{background:white;padding:18px;border-radius:14px;margin:0}header{margin-bottom:24px}.objects{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.views{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,600px),1fr));gap:18px}img{width:100%;height:auto;display:block}h1,h2,h3{line-height:1.2}small{font-size:12px;overflow-wrap:anywhere;display:block}p{overflow-wrap:anywhere}figure{min-width:0}</style><main><header><a href="../job_artwork_refinement_live/all_items.html">All known job items</a><h1>Geologist: actual game artwork review</h1><p>The geode opens to reveal crystals inside both halves and keeps them embedded through completion. The river now uses the exact painted source regions and wide earth bed in the reversible game candidate.</p><p>Every 46 current native stills directly reviewed at 1280/1600. Current river joins 4.5 provisional, earth/material 4.6. Room 2.8, working contact 2.7, fossil clearing 3.9 and pan motion 3.8 still need repair. Individual source, mounted, sampled sequence and full-action acceptance stay separate.</p><p><a href="REVIEW.json">Complete written evaluations, individual scores and hashes</a> · <a href="ARTWORK_ITEMS.json">Six source identities</a> · <a href="MECHANIC_UNCHANGED.json">Unchanged input/save/flow methods</a> · <a href="full_ci_v1/RECEIPT.json">Current full-suite receipt</a> · <a href="../job_river_join_study_v1_20261001/index_v7.html">Preserved isolated river V7</a> · <a href="../../assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html">All source generations and rejections</a></p><p>Test entry fixture supplies the career entry. Actual viewport touches earn all four phases and advance normally. The images below follow the recorded timeline, including five prepared seams before the crack. Complete timed action, castle/training/story, physical device, child and owner approval remain open.</p></header><h2>Each visible item and relationship</h2><div class="objects">'''+cards+'</div>'+images+'</main></html>'
(f/'index.html').write_text(text,encoding='utf-8',newline='\n')
licenses=b/'ASSET_LICENSES.md';text=licenses.read_text(encoding='utf-8')+'\n### Actual geology painted-river capture review (2026-10-02)\n\n'
for x in views:
 if x['path'] not in text:text+='| `'+x['path']+'` | Native Godot4.7.2 Mobile desktop capture of existing licensed project art | Project review evidence; underlying original licenses retained | `'+prefix+'/REVIEW.json` | Lossless native viewport WebP, unmodified pixels; actual route fixture, direct review; SHA256 '+x['sha256']+' |\n'
licenses.write_text(text,encoding='utf-8',newline='\n')
# A separate fixture checks the actual production renderer, with no drawing override.
code=(b/'audit/job_river_join_study_v1_20261001/capture_join_study_v7.gd').read_text(encoding='utf-8').replace('res://audit/job_river_join_study_v1_20261001/attempt_07/','res://'+prefix+'/network_attempt_01/').replace('preload("res://audit/job_river_join_study_v1_20261001/join_surface_v7.gd")','preload("res://scripts/opera_geology_surface.gd")').replace('Non-runtime subclass, actual inherited9x5 input/flow. Isolated component/network drawing study; absent actor/room/route not scored.','Actual production surface renderer and9x5 viewport input/flow/save. Isolated network capture; absent actor/room/route not scored.')
(f/'capture_production_river_network.gd').write_text(code,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-painted-runtime-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Direct inspect every46 current native actual-route images',result='PASS',evidence=prefix+'/REVIEW.json: graphics opinions explicitly separate; actual route/input at both widths.'));d['acceptance_gaps']='Room2.8, actor contact2.7, fossil clearing3.9, pan action3.8, full timed/training/story/device/child/owner/all-job acceptance remain open. Current full suite still running at this review recording; see final receipt. No finding closure/integration/release.';write(ip,d)
print('46 actual native views; '+str(len(objects))+' individual visible object/relationship evaluations saved.')
