from pathlib import Path
import datetime, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geology_river_runtime_v1_20261002';prefix=f.relative_to(b).as_posix()
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
p=f/'capture_production_river_network.gd';s=p.read_text(encoding='utf-8').replace('"subclass":"res://audit/job_river_join_study_v1_20261001/join_surface_v7.gd"','"subclass":null').replace('No production binding; actual source scores4.6 do not pass joints/flatbed/full actor-work context.','Current production renderer without drawing override; isolated network review does not pass actor/room/full timed action.');p.write_text(s,encoding='utf-8',newline='\n')
text='Actual painted-river runtime continuation (2026-10-02): [{link}all46 ordinary four-phase native captures{end}] directly inspected at1280/1600;37 individual visible objects/relationships have written opinions. Six exact complete runtime copies bind the painted river in a reversible topic candidate; selected visible network4.5 provisional/earth4.6. Whole-source unused closed ports/red fringes4.4 and glow attempts3.8 remain failed and preserved. Exact six input/path/flow/save methods unchanged; ordinary intentional phase advancement captures pass both widths. Full unmodified current officialGodot4.7.2 suite is running; final state is recorded separately in its receipt, no inherited pass. Room2.8, hands away from objects2.7, fossil clearing3.9 and pan action3.8 remain priorities. Geode opens with crystals embedded in both halves through completion, sampled progression4.5 provisional/material4.6. Known registerV26 has1647 entries/1231 source files/328 pose cells/38 runtime regions/50 source regions/607 inclusive priorities/388 unassigned. Full timed action/training/story/device/child/owner/final all-job report remain open; no lifecycle closure/integration/release.'
# Add facts in the current authority entry and preserve every historical boundary.
p=b/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');s=s.replace('# Mermaid Roshan: Reef of Light — game-wide master audit\n','# Mermaid Roshan: Reef of Light — game-wide master audit\n\n'+text.format(link='',end='') .replace('[all46 ordinary four-phase native captures]', '[all46 ordinary four-phase native captures](job_geology_river_runtime_v1_20261002/index.html)')+' [Impact](../design/audit_impacts/job-geology-river-painted-runtime-20261002.json).\n',1);p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=p.read_text(encoding='utf-8');at=s.index('\n## ',s.index('## MA-PLAY-004')+len('## MA-PLAY-004'));s=s[:at]+'\n'+text.format(link='',end='').replace('[all46 ordinary four-phase native captures]','[all46 ordinary four-phase native captures](../job_geology_river_runtime_v1_20261002/index.html)')+' [Impact](../../design/audit_impacts/job-geology-river-painted-runtime-20261002.json). MA-PLAY-004 stays IN_PROGRESS; MA-VIS-006 is not closed.\n'+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s='\n'.join('| `audit/job_artwork_refinement_live/all_items.html` | 🟣 | `CANDIDATE`; currentV26 known register1647 entries/1231 source files/328 pose cells/38 runtime regions/50 source regions. Inclusive607 source priorities and388 unassigned remain. Current exact source copies retain complete-source scores independent of game-visible regions. Shared candidates do not prove exhaustive actual-use, mounted/action or owner acceptance. |' if '`audit/job_artwork_refinement_live/all_items.html`' in row else row for row in s.split('\n'));s+='\n| `'+prefix+'/index.html` | 🟣 | `CANDIDATE`; every46 actual ordinary four-phase native view directly reviewed with37 individual object/relationship scores. Six painted-river source copies now bind reversibly; actual visible joins4.5 provisional/earth4.6, room2.8/contact2.7/clearing3.9/pan action3.8 remain. Source rejections and historical boundaries preserved. Current full-suite receipt supplies machine state separately; no timed/training/story/device/child/owner/global pass or finding closure. |\n';p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/job_artwork_refinement_live/index.html';s=p.read_text(encoding='utf-8');s=s.replace('<h1>Mermaid Roshan jobs artwork — live review entry</h1>','<h1>Mermaid Roshan jobs artwork — live review entry</h1><p><a href="../job_geology_river_runtime_v1_20261002/index.html">Current actual geology artwork: painted river, embedded geode and every46 native views</a></p>',1);p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
families=[('job-geology-river-join-study-20261001','audit/job_river_join_study_v1_20261001'),('job-geology-river-junction-source-20261001','assets_src/imagegen/geologist_river_junctions_v1_20261001'),('job-geology-river-bed-source-20261002','assets_src/imagegen/geologist_river_bed_v1_20261002'),('job-geology-river-painted-runtime-20261002',prefix)]
shared=['ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v26.py']
for name,folder in families:
 ip=b/('design/audit_impacts/'+name+'.json');d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in (b/folder).rglob('*') if p.is_file()}|(set(shared)|{p.relative_to(b).as_posix() for p in (b/'audit/job_artwork_refinement_live').rglob('*') if p.is_file()} if name.endswith('runtime-20261002') else set()));write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(b).as_posix() for _,folder in families for p in (b/folder).rglob('*') if p.is_file()}|{p.relative_to(b).as_posix() for p in (b/'audit/job_artwork_refinement_live').rglob('*') if p.is_file()}))
print('Current register/master/active evidence/ledger and exact preview allowlist updated; lifecycle unchanged.')
