extends SceneTree

func _initialize() -> void:
	var image_ready: Image = Image.load_from_file("res://assets_src/imagegen/nursery_wash_connected_v1_20261002/ready_attempt01/native.png")
	assert(not image_ready.is_empty())
	image_ready.resize(1024, 1024, Image.INTERPOLATE_LANCZOS)
	assert(image_ready.save_png("res://assets/opera/worlds/nursery/wash_connected_v1_20261002/ready.png") == OK)
	var image_wet: Image = Image.load_from_file("res://assets_src/imagegen/nursery_wash_connected_v1_20261002/wet_attempt01/native.png")
	assert(not image_wet.is_empty())
	image_wet.resize(1024, 1024, Image.INTERPOLATE_LANCZOS)
	assert(image_wet.save_png("res://assets/opera/worlds/nursery/wash_connected_v1_20261002/wet.png") == OK)
	var image_rub_palm: Image = Image.load_from_file("res://assets_src/imagegen/nursery_wash_connected_v1_20261002/rub_attempt01/native.png")
	assert(not image_rub_palm.is_empty())
	image_rub_palm.resize(1024, 1024, Image.INTERPOLATE_LANCZOS)
	assert(image_rub_palm.save_png("res://assets/opera/worlds/nursery/wash_connected_v1_20261002/rub_palm.png") == OK)
	var image_rub_back: Image = Image.load_from_file("res://assets_src/imagegen/nursery_wash_connected_v1_20261002/rub_back_attempt01/native.png")
	assert(not image_rub_back.is_empty())
	image_rub_back.resize(1024, 1024, Image.INTERPOLATE_LANCZOS)
	assert(image_rub_back.save_png("res://assets/opera/worlds/nursery/wash_connected_v1_20261002/rub_back.png") == OK)
	var image_rinse: Image = Image.load_from_file("res://assets_src/imagegen/nursery_wash_connected_v1_20261002/rinse_attempt01/native.png")
	assert(not image_rinse.is_empty())
	image_rinse.resize(1024, 1024, Image.INTERPOLATE_LANCZOS)
	assert(image_rinse.save_png("res://assets/opera/worlds/nursery/wash_connected_v1_20261002/rinse.png") == OK)
	var image_clean: Image = Image.load_from_file("res://assets_src/imagegen/nursery_wash_connected_v1_20261002/clean_attempt01/native.png")
	assert(not image_clean.is_empty())
	image_clean.resize(1024, 1024, Image.INTERPOLATE_LANCZOS)
	assert(image_clean.save_png("res://assets/opera/worlds/nursery/wash_connected_v1_20261002/clean.png") == OK)
	print("NURSERY_WASH|WHOLE_CANVAS_POT_NORMALIZATION|PASS")
	quit(0)
