from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');F=R/'audit/job_nursery_wash_connected_v1_20261002';V=F/'remote_verified_v1'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
baseline='c2538760639d79b063152ce5530807c04545ba6e'
assert subprocess.run(['git','rev-parse','HEAD'],cwd=R,capture_output=True,check=True).stdout.decode().strip()==baseline
remote=R/'tmp/connected_nursery_checkpoint_o_remote_v386';pub=R/'tmp/connected_nursery_checkpoint_o_publish_v386';result=read(remote/'RESULT.json')
assert result['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and result['revision']==baseline and result['files_including_manifest']==15118 and not result['failed_files']
journal=remote/'VERIFICATION_JOURNAL.jsonl';rows=[json.loads(l) for l in journal.read_text(encoding='utf-8').splitlines()];assert len(rows)==15118 and len({r['path'] for r in rows})==15118 and all(r['matches'] for r in rows)
original_boundary=read(F/'SOURCE_CURRENT_MACHINE_V3.json')['source_files'];assert len(original_boundary)==783 and all(sha(R/r['path'])==r['sha256'] for r in original_boundary)
target=F/'review_tools'/Path(__file__).name
destinations=[V/n for n in ['RESULT.json','VERIFICATION_JOURNAL.jsonl','PUBLISH_RECEIPT.json','HOSTED_PROBES_SNAPSHOT_V1.json','BOUNDARY_UNCHANGED.json','index.html','publish_connected_nursery_checkpoint_o_v386.py']]+[V/(name+'.'+kind+'.log') for name in ['fetch','commit','authority','development','push'] for kind in ['stdout','stderr']]+[target]
ip=R/'design/audit_impacts/job-nursery-published-verification-20261002.json'
write(ip,{'id':'job-nursery-published-verification-20261002','scope':'Persist complete anonymous immutable-byte verification for the connected Nursery topic checkpoint c2538760: all15118 required payload/reference files, complete per-file journal, publisher commands and unchanged783 local source boundary. Record hosted probes as a separate dated snapshot; preserve every creative/action/device/child/owner/integration/release limit and the explicit pending imagegen-reference upload. No artwork, production/source behavior, metadata settings, finding lifecycle, protected originals or release changes.','baseline':baseline,'rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-05','DL-ASSET-06','DL-QA-01','DL-QA-02','DL-QA-03','DL-QA-06'],'findings':['MA-VIS-006','MA-PLAY-004','MA-OPERA-012'],'files':sorted({p.relative_to(R).as_posix() for p in destinations}|{'audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md'}),'validation':[{'command':'Anonymous immutable topic payload/reference verification','result':'PASS','evidence':(V/'RESULT.json').relative_to(R).as_posix()},{'command':'Unchanged783 local production/test/capture/import/UID members','result':'PASS','evidence':(V/'BOUNDARY_UNCHANGED.json').relative_to(R).as_posix()}]})
assert not V.exists();V.mkdir();shutil.copyfile(Path(__file__),target)
shutil.copyfile(remote/'RESULT.json',V/'RESULT.json');shutil.copyfile(journal,V/'VERIFICATION_JOURNAL.jsonl');shutil.copyfile(pub/'RECEIPT.json',V/'PUBLISH_RECEIPT.json');shutil.copyfile(pub/'publish_connected_nursery_checkpoint_o_v386.py',V/'publish_connected_nursery_checkpoint_o_v386.py')
for name in ['fetch','commit','authority','development','push']:
 for kind in ['stdout','stderr']:shutil.copyfile(pub/(name+'.'+kind+'.log'),V/(name+'.'+kind+'.log'))
gh='C:/Program Files/GitHub CLI/gh.exe';p=subprocess.run([gh,'run','view','37075551850','--repo','Ebonyks/mermaid-roshan-reef','--json','status,conclusion,headSha,url'],cwd=R,capture_output=True,check=True)
hosted=json.loads(p.stdout);assert hosted['headSha']==baseline
write(V/'HOSTED_PROBES_SNAPSHOT_V1.json',{'observed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'run':hosted,'qualification':'Dated exact revision hosted probe snapshot. Only completed/success establishes a green hosted suite; publication/creative/device/child/owner gates are separate.'})
write(V/'BOUNDARY_UNCHANGED.json',{'status':'PASS_ALL783_LITERAL_LOCAL_MEMBERS_UNCHANGED','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'count':783,'source_boundary':'../SOURCE_CURRENT_MACHINE_V3.json','source_boundary_sha256':sha(F/'SOURCE_CURRENT_MACHINE_V3.json'),'publication_split':'543 exact revision source/import members plus240 literal non-runtime generated UID snapshots.','no_production_or_artwork_change':True})
status='success' if hosted['status']=='completed' and hosted['conclusion']=='success' else hosted['status']+'/'+(hosted['conclusion'] or 'pending')
doc='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connected Nursery — immutable publication verification</title><style>body{margin:0;background:#edf5f8;color:#25334b;font:17px/1.55 system-ui}main{max-width:1080px;margin:auto;padding:24px}a{color:#504096}article{background:white;border-radius:16px;padding:22px;margin:18px 0}code{overflow-wrap:anywhere}h1,h2{line-height:1.25}</style><main><a href="../index.html">Current illustrated Nursery review</a><h1>Every required review file is available at the immutable checkpoint</h1><article><p>All 15,118 required payload/reference files, including the manifest, were fetched anonymously over normally verified TLS and matched exact bytes and SHA-256. No Authorization header was used. Verification interval: '+html.escape(result['started_utc'])+' to '+html.escape(result['finished_utc'])+'.</p><p><a href="'+result['entry_url']+'">GitHub review entry</a> · <a href="'+result['tree_url']+'">Immutable revision/tree</a> · <a href="'+result['manifest_url']+'">Direct manifest</a></p><p>Revision <code>'+baseline+'</code><br>Manifest SHA-256 <code>'+result['map_sha256']+'</code><br>Sorted payload SHA-256 <code>'+result['payload_sha256']+'</code></p><p><a href="RESULT.json">Verification result</a> · <a href="VERIFICATION_JOURNAL.jsonl">Complete lossless per-file journal</a> · <a href="PUBLISH_RECEIPT.json">Publisher receipt</a></p></article><article><h2>Separate machine and creative claims</h2><p>Local official Godot4.7.2 unmodified full suite: 82/82, process0, all783 frozen local members unchanged;53 raw diagnostics retained. Publication accounts for543 revision source/import files and240 preserved generated script UID snapshots.</p><p>Hosted probes at the recorded observation: '+html.escape(status)+'. <a href="'+hosted['url']+'">Exact-revision hosted run</a> · <a href="HOSTED_PROBES_SNAPSHOT_V1.json">Dated snapshot</a>.</p><p>Six selected static states4.5–4.6; meaningful washing3.9, attention3.8, room2.9 and transition4.0 remain priorities. Local motion A1 is rejected3.6 after all41 frames were reviewed. Dated Doctor whole washing remains2.7. These scores do not grant device, child, owner, complete all-job, integration or release acceptance.</p><p>Targeted eyes-to-hands imagegen edit remains blocked pending explicit reference-file/destination authorization. No reference was uploaded; publishing this review does not authorize or bypass that transmission.</p></article></main></html>'
(V/'index.html').write_text(doc,encoding='utf-8',newline='\n')
master=R/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8');note='Connected Nursery publication receipt (2026-10-02): [immutable review c2538760 — all 15,118 required remote files verified anonymously byte-for-byte](job_nursery_wash_connected_v1_20261002/remote_verified_v1/index.html). Complete per-file journal, exact hashes, normal TLS access and check interval are preserved. All783 frozen local members remain unchanged; publication distinguishes543 revision source/import files from240 generated UID snapshots. Static4.5–4.6, meaningful wash3.9, attention3.8 and room2.9 are separate drafting opinions; failed local motion3.6, dated Doctor2.7, current Geologist rerender, comprehensive all-job/device/child/owner/integration/release remain open. Hosted status is recorded separately; no finding lifecycle change or imagegen-reference upload authorization.\n\n'
assert 'Connected Nursery publication receipt (2026-10-02)' not in s;pos=s.index('\n')+1;s=s[:pos]+'\n'+note+s[pos:];master.write_text(s,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');s+='\n| `audit/job_nursery_wash_connected_v1_20261002/remote_verified_v1/index.html` | 🔵 | `SUPPORTING_CURRENT`; immutable c2538760 review payload/reference verification: all15118 files anonymously fetched with normal TLS and exact byte/SHA matches; complete lossless journal.783 local members unchanged,543 revision source/import +240 generated UID snapshots. Hosted dated status, source/static/action/device/child/owner and release claims separate; blocked imagegen upload still blocked. |\n';ledger.write_text(s,encoding='utf-8',newline='\n')
print('NURSERY_REMOTE_RECEIPT_DURABLE|15118 exact anonymous remote files|783 unchanged|hosted '+status+'|creative and upload gates open')
