from pathlib import Path
import datetime, hashlib, html, json, shutil
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
F=R/'audit/job_nursery_wash_connected_v1_20261002'
O=F/'doctor_dated_full_review_v1'
P=R/'assets_src/local_motion/nursery_connected_scrub_v1_20261002'
S2=R/'assets_src/imagegen/nursery_palm_attention_v1_20261002'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
ip=R/'design/audit_impacts/job-nursery-wash-connected-20261002.json'
imp=read(ip)
imp['scope']+=' Record the explicit reference-upload auto-review rejection and pending owner authorization without transmitting the file or bypassing the rejected action. Complete the new dated Doctor review with individual scored components, all 24 ordered boards and 12 native details; preserve older Doctor opinions and withhold current mounted approval. The local Nursery A1 render is machine-complete but rejected after review of all 41 native frames.'
new=[O/'DIRECT_REVIEW.json',O/'index.html',S2/'REFERENCE_UPLOAD_BLOCK.json',P/'REVIEW_STATUS.json',F/'review_tools'/Path(__file__).name]
imp['files']=sorted(set(imp['files'])|{p.relative_to(R).as_posix() for p in new})
write(ip,imp)
shutil.copyfile(Path(__file__),new[-1])
plan=read(S2/'PLAN.json')
plan['status']='BLOCKED_AWAITING_EXPLICIT_REFERENCE_UPLOAD_APPROVAL'
plan['generation_started']=False
plan['reference_uploaded']=False
plan['block_receipt']=(S2/'REFERENCE_UPLOAD_BLOCK.json').relative_to(R).as_posix()
write(S2/'PLAN.json',plan)
write(S2/'REFERENCE_UPLOAD_BLOCK.json',{'recorded_utc':now,'status':'AUTO_REVIEW_REJECTED_BEFORE_UPLOAD','action':'Built-in image generation: targeted eyes-to-hands edit of the preserved complete Nursery palm-wash source','source_path':plan['inventory'][0]['path'],'source_sha256':plan['inventory'][0]['sha256'],'prompt_path':(S2/'PROMPT.json').relative_to(R).as_posix(),'prompt_sha256':sha(S2/'PROMPT.json'),'proposed_destination':'OpenAI built-in image-generation service','review_reason':'The nested image-generation call would upload a private project artwork reference to an external image-generation service. General generation authorization did not establish explicit authorization for this exact payload and destination. Do not bypass through a workaround or indirect execution.','reference_uploaded':False,'generation_started':False,'question_status':'PENDING_USER_RESPONSE','question':'Approve sending this exact preserved Nursery palm-wash native artwork to OpenAI built-in image generation solely for the look-to-hands pose?','independent_work':'Dated Doctor review, machine gates and illustrated reporting continue; the overall goal remains active.'})
idx=read(O/'INDEX.json')
assert len(idx['boards'])==24 and len(idx['native_details'])==12 and idx['frame_total']==1023
for row in idx['boards']+idx['native_details']:assert sha(R/row['path'])==row['sha256']
components=[
 ('DOC-DATED-USE-01','Basin painting and material',2.9,'A clear aqua oval is recognizable as a basin, but its flat fill and isolated purple rim do not match the broad painted bands and authored volume of the surrounding room. Reuse a complete painted basin assembly at an intentional support plane.'),
 ('DOC-DATED-USE-02','Tap and operating cues',3.0,'The large yellow arch and pink/teal dots read as a generic symbol. No legible connected outlet-to-hands stream establishes wetting or rinsing. Paint the tap, outlet and handles coherently and show its actual on/off state.'),
 ('DOC-DATED-USE-03','Individual washing-hand symbols',2.2,'The peach mitten shapes terminate at arbitrary ends over the bowl; they are separated from the visible body. They do not explain a palm/back-of-hand scrub. Replace them with authored complete body-connected work poses.'),
 ('DOC-DATED-USE-04','Body-to-tool contact',2.3,'Roshan remains far left, gesturing near her face while the washing symbols sit at the right. Her wrists and attention never reach the basin in these frames. Mount a single coherent actor/contact assembly before scoring action.'),
 ('DOC-DATED-USE-05','Reciprocal rubbing action',2.4,'Across every ordered frame, changing rings and highlights show progress but do not show opposite palms making readable reciprocal strokes. Directional pose changes must demonstrate the actual rub while conserving hands, wrists and the basin.'),
 ('DOC-DATED-USE-06','Wet, rinse and clean consequence',2.2,'There is no clear wet-to-lather-to-rinse-to-clean hand sequence connected to the actor. The final state still relies on symbolic effects. Show water meeting the hands, contained foam and a legible clean-hand end state.'),
 ('DOC-DATED-USE-07','Foam and progress overlays',2.5,'White rings dominate the small work target and do not establish lather between two contacting palms. Keep foam local to the work, with purposeful change rather than progress substituted by concentric graphics.'),
 ('DOC-DATED-USE-08','Earned celebration presentation',2.4,'Pearls and rings celebrate the earned hold but do not communicate the actual washed result. Preserve reward ownership and timing while showing clean palms and restrained context-specific effects.'),
 ('DOC-DATED-USE-09','Room and activity composition',2.8,'The ornate painted promenade retains appealing pastel identity. The detached dark work oval obscures its invitations; blurred edge copies and rectangular crop seams undermine the room. Plan an authored work surface and explicit actor/support placement.'),
 ('DOC-DATED-USE-10','Wide viewport composition',2.9,'The 1600-wide view exposes navy side fields while the crowded central composition remains small. Compose for both widths with readable work placement, avoiding empty border area and duplicated blurred scenery.'),
 ('DOC-DATED-USE-11','Wash-to-next-phase continuity',3.0,'The detached wash oval disappears and Roshan swaps to a different tool/pose for the next invitation. The route is mechanically readable in the fixture, but the physical consequence and actor transition remain abrupt. Review entry, earned result, clearing and the next task together.'),
 ('DOC-DATED-USE-12','Complete meaningful wash',2.7,'The preserved four fixture sequences do not demonstrate body-connected wetting, reciprocal scrubbing, rinsing and clean palms. This retains the prior dated whole-action opinion; none of these scores approve current rendered Doctor gameplay.')]
review={'status':'DIRECT_DATED_REVIEW_COMPLETE_PRIORITIES_OPEN','reviewed_utc':now,'reviewer':'Root direct visual inspection','qualification':idx['qualification'],'coverage':{'ordered_boards':24,'all_consecutive_frames':1023,'unchanged_native_details':12,'cases':4,'widths':[1280,1600]},'review_method':'Every frame inspected on complete ordered QA boards; all twelve listed native details separately inspected at original resolution. Scores are drafting opinions for dated captures. Small boards establish ordering, not unseen fine anatomy. Native details substantiate material/contact judgements.','inclusive_priority_threshold':4.5,'generation_floor':4.5,'current_render_acceptance':False,'complete_career_reward_verified':False,'ordinary_birthday_route_verified':False,'device_acceptance':None,'child_acceptance':None,'owner_acceptance':None,'items':[{'id':i,'name':n,'score':s,'priority':True,'evaluation':e,'kind':'DATED_MOUNTED_OR_ACTION_OPINION','evidence_index':(O/'INDEX.json').relative_to(R).as_posix()} for i,n,s,e in components],'evidence':[{'path':r['path'],'sha256':r['sha256']} for r in idx['boards']+idx['native_details']],'older_reviews_preserved':['audit/job_wash_root_doctor_sequence_v1_20261002/index.html','audit/job_wash_root_remaining_sequences_v1_20261002/index.html'],'no_source_or_mechanics_change':True}
write(O/'DIRECT_REVIEW.json',review)
idx['status']='DIRECT_DATED_DOCTOR_REVIEW_COMPLETE';idx['direct_review']=(O/'DIRECT_REVIEW.json').relative_to(R).as_posix();write(O/'INDEX.json',idx)
cards=''.join('<article><h3>'+html.escape(n)+' — '+str(s)+'/5</h3><p>'+html.escape(e)+'</p><small>'+i+' · dated mounted/action opinion</small></article>' for i,n,s,e in components)
details=''.join('<figure><a href="../../../../'+r['path']+'"><img loading="lazy" src="../../../../'+r['path']+'" alt="'+html.escape(r['case'])+' dated native frame '+str(r['frame'])+'"></a><figcaption>'+html.escape(r['case'])+' · frame '+str(r['frame'])+' · original native pixels</figcaption></figure>' for r in idx['native_details'])
boards=''.join('<figure><a href="'+Path(r['path']).name+'"><img loading="lazy" src="'+Path(r['path']).name+'" alt="'+html.escape(r['case'])+' ordered frames '+str(r['first'])+' to '+str(r['first']+r['count']-1)+'"></a><figcaption>'+html.escape(r['case'])+' · all frames '+str(r['first'])+'–'+str(r['first']+r['count']-1)+'</figcaption></figure>' for r in idx['boards'])
doc='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor washing — complete dated visual review</title><style>body{background:#eef5f5;color:#20313f;font:17px/1.55 system-ui;margin:0}main{max-width:1250px;margin:auto;padding:24px}a{color:#235b90}article{background:white;padding:20px;border-radius:16px;margin:14px 0}img{max-width:100%;height:auto}figure{margin:20px 0;padding:12px;background:white;border-radius:14px}small,figcaption{color:#486271}h1,h2,h3{line-height:1.25}</style><main><a href="../index.html">Return to current Nursery report</a><h1>Doctor washing: dated captures remain below the action standard</h1><p>All 1,023 consecutive preserved baseline frames across four training/authored catalog fixtures were directly reviewed on 24 complete boards, plus twelve native details. These images predate the current Nursery changes. They provide historical evidence; current Doctor rendering, ordinary story entry, complete career rewards and device/child/owner acceptance remain unverified.</p><p>The complete dated wash remains 2.7/5. Twelve components and interactions below are inclusive priorities at ≤4.5. The older review files and their scores remain preserved. No Doctor production art or mechanics changed in this review.</p><p><a href="DIRECT_REVIEW.json">Individual evaluations and evidence hashes</a> · <a href="INDEX.json">Complete coverage index</a></p>'+cards+'<h2>Every native detail</h2>'+details+'<h2>Every ordered frame</h2><p>Boards are QA thumbnails. Open any board for the full image; use the native details above for fine material and contact assessment.</p>'+boards+'</main></html>'
(O/'index.html').write_text(doc,encoding='utf-8',newline='\n')
write(P/'REVIEW_STATUS.json',{'status':'MACHINE_RENDER_COMPLETE_VISUAL_REJECTED','reviewed_utc':now,'native_frame_count':41,'reference_action_score':3.6,'direct_review':'attempt01/DIRECT_REVIEW.json','machine_render_receipt':'attempt01/RENDER_RECEIPT.json','runtime_integration':False,'cinematic_delivery':False,'owner_acceptance':None,'current_game_action_score':3.9,'score_transfer':False,'manifest_and_dispatch_inputs_preserved':True})
ledger=R/'design/05_DOC_LEDGER.md';text=ledger.read_text(encoding='utf-8')
old='`CANDIDATE_REFERENCE_STUDY`; one exact native ComfyUI submission through the unchanged developed GGUF workflow, current installation/input/prompt hashes and quiet admission bound. Tests connected palm strokes and attentive gaze; native output/frame review pending. Static floor does not transfer to motion or current gameplay. No runtime/cinematic/device/child/owner acceptance.'
newtext='`REJECTED_REFERENCE_STUDY`; exact native ComfyUI A1 machine render complete, all 41 unchanged native frames directly reviewed. Reference action 3.6, contact 3.8, attention 3.1; clasp arc/hold does not show reciprocal scrubbing. Original input/prompt/workflow/dispatch and failed QA layout preserved. Current game action remains 3.9; no runtime/cinematic/device/child/owner acceptance.'
assert old in text;text=text.replace(old,newtext,1)
if 'doctor_dated_full_review_v1/index.html`' not in text:text+='\n| `audit/job_nursery_wash_connected_v1_20261002/doctor_dated_full_review_v1/index.html` | 🟣 | `DATED_EVIDENCE`; all 1023 preserved Doctor baseline frames on 24 ordered boards and 12 native details directly reviewed. Twelve individual priorities; complete wash retains 2.7. Training/authored catalog fixtures only; no current-render, birthday-route, full-career reward, device/child/owner acceptance. |\n'
ledger.write_text(text,encoding='utf-8',newline='\n')
page=F/'index.html';t=page.read_text(encoding='utf-8');mark='<script';pos=t.index(mark)
section='<section id="doctor-dated-review"><h2>Doctor wash: complete dated review</h2><p>All 1,023 preserved Doctor frames on 24 ordered boards, plus twelve full native details, are directly reviewed. Twelve individual contact, material and sequencing priorities retain the dated whole wash at 2.7/5. Current Doctor rendering and normal story routes remain unverified.</p><p><a href="doctor_dated_full_review_v1/index.html">Read all evaluations and view every Doctor frame</a></p></section>\n'
t=t[:pos]+section+t[pos:];page.write_text(t,encoding='utf-8',newline='\n')
library=R/'audit/job_artwork_refinement_live/all_items.html';t=library.read_text(encoding='utf-8');assert '<body' in t
# Link historical evidence without silently altering current item scores/counts.
pos=t.index('<main') if '<main' in t else t.index('<body')+len('<body>')
link='<p class="review-history"><a href="../job_nursery_wash_connected_v1_20261002/doctor_dated_full_review_v1/index.html">Doctor dated complete wash review: 12 individual priorities, all 1023 frames</a> · <a href="../../assets_src/local_motion/nursery_connected_scrub_v1_20261002/index.html">Nursery local motion A1: rejected 3.6/5</a>. Historical/reference scores do not approve current gameplay.</p>\n'
t=t[:pos]+link+t[pos:];library.write_text(t,encoding='utf-8',newline='\n')
imp=read(ip);imp['files']=sorted(set(imp['files'])|{p.relative_to(R).as_posix() for p in F.rglob('*') if p.is_file()}|{p.relative_to(R).as_posix() for p in S2.rglob('*') if p.is_file()}|{(P/'REVIEW_STATUS.json').relative_to(R).as_posix()})
imp['validation'].append({'command':'Root direct dated Doctor visual review: all 24 ordered boards / 1023 frames and 12 native details','result':'PASS','evidence':(O/'DIRECT_REVIEW.json').relative_to(R).as_posix()})
imp['validation'].append({'command':'OpenAI built-in image-generation reference edit authorization','result':'PENDING','evidence':(S2/'REFERENCE_UPLOAD_BLOCK.json').relative_to(R).as_posix()})
write(ip,imp)
print('DOCTOR_DATED_REVIEW|1023 frames|24 boards|12 native details|12 individual priorities|current claims withheld')
print('REFERENCE_UPLOAD|auto-review rejection recorded|no upload|explicit response pending')
