from pathlib import Path
import hashlib,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=r/'audit/job_geology_painted_work_v1_20261001';s=r/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/fossil_soil/attempt_01'
assert not s.exists();s.mkdir(parents=True)
prompt='''Use case: stylized game asset. Make one new transparent-background painted soil patch for a preschool mermaid geology brushing game. A compact shallow patch of loose golden ochre soil, viewed straight down, with a wide rounded rectangular footprint about1.87:1. Fill the footprint with continuous broad hand-painted light sand and warm ochre value bands, two or three calm pebble clusters and occasional lavender shadows. Its edge is gently irregular and softly crumbled, with restrained deep-plum contour; no hard geometric frame. The soil must fully conceal a fossil placed underneath until brushed away. Keep central surface calm and opaque. Polished2D picture-book/toy-playset illustration, pastel high-key palette, soft brush texture, matte material, handmade rounded forms. No photographic dirt, vector diagram, dramatic3D perspective, fossil, crystals, tools, hands, characters, words, labels, border or background scenery. Single isolated asset centred with generous genuinely transparent padding on all sides. Please output a1024x1024 RGBA canvas. Source must be complete and uncut. The intended soil footprint will display about560x300 pixels; texture remains clear and restrained at that size.'''
(s/'PROMPT.txt').write_text(prompt,encoding='utf-8');(s/'PROVENANCE_PENDING.json').write_text(json.dumps({'status':'GENERATION_PENDING','named_gap':'Current fossil brushing cover is a uniform flat brown rectangle: material3.2 and interactive edge3.0. All six existing painted source objects were inventoried; none is a loose-soil cover. Native current evidence attempt02 fossil task_open/partial_brush.','generation_method':'OpenAI built-in image_gen; new standalone source, zero appearance bindings.','prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'attempt':1,'transparent_background':True,'source_score':None,'mounted_score':None,'owner_acceptance':None},indent=2)+'\n',encoding='utf-8')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
p=r/'design/audit_impacts/job-geology-painted-work-20261001.json';d=json.loads(p.read_text());d['scope']+=' Actual attempt02 brushing exposes the flat brown cover3.2 as a remaining named material gap. Six reviewed candidates inventory cannot supply loose earth; generate one bounded transparent top-down painted soil patch. Preserve every source/attempt, prompt/hash, alpha and native output; bind only after direct review with unchanged cell-clearing behavior.';d['files']=sorted(set(d['files'])|{x.relative_to(r).as_posix() for folder in [s,f] for x in folder.rglob('*') if x.is_file()});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print(prompt)
