from pathlib import Path
import datetime, hashlib, json, re, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');work=b/'audit/job_geology_painted_work_v1_20261001';river=b/'assets_src/imagegen/geologist_river_components_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
utc=datetime.datetime.now(datetime.timezone.utc).isoformat()
write(river/'LIBRARY_RENDER_QA.json',{'status':'PASS_DIRECT_BROWSER_SOURCE_AND_REGISTER_REVIEW','checked_utc':utc,'source_url':'http://127.0.0.1:8880/assets_src/imagegen/geologist_river_components_v1_20261001/index.html?revision=source-v1','viewport':[1280,720],'document_scroll_width':1265,'loaded_images':12,'image_count':12,'individual_component_windows':6,'whole_original_views':2,'whole_derivative_views':2,'actual_game_comparisons':2,'annotation_correction':'First quadrant split at627 clipped nodes and polluted closed-channel windows. Direct whole-native reinspection corrected top/bottom split to790 in transparent gap; no image pixels modified. Corrected browser views show complete nodes and closed channels.','register_snapshot':'V22:1596 entries/1210 source files/328 pose cells/38 runtime prop regions/20 source-object regions/584 inclusive priorities/388 unassigned/5 changed/0 missing','register_search':'GEO-RIVER','priority_filter_matches':4,'all_filter_matches':10,'visible_broken_register_images':0,'register_region_sizes':[[220,87.1875],[220,86.890625],[220,214.890625],[220,214.890625],[220,55.921875],[220,56.25]],'qualification':'Actual CUA browser render/search review. Native source acceptance4.6 remains separate from unbound runtime network/action/owner. No browser screenshot file fabricated; original source/game images are preserved in report.'})
p=b/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');old='| Job artwork review | [Expanded job graphics library](day2_job_contexts_2026-09-30/REPORT.md); [earlier source/planned-contest review](day2_art_library_2026-09-30/REPORT.md) |';new='| Job artwork review | [Current illustrated review entry and individual register](job_artwork_refinement_live/index.html); [expanded job graphics library](day2_job_contexts_2026-09-30/REPORT.md); [earlier source/planned-contest review](day2_art_library_2026-09-30/REPORT.md) |';assert old in s;s=s.replace(old,new,1);p.write_text(s,encoding='utf-8',newline='\n')
mp=b/'audit/job_review_v2_20261001/GEOLOGY_PAINTED_WORK_REVIEW_SUPPLEMENT_FILES_V7.json';assert not mp.exists();write(mp,{'schema':'reef.immutable-review-supplement.v1','status':'EXACT_CANONICAL_BLOB_SEAL_PENDING','base_revision':'e1b431f49258eef1d293b11a732353f0a3aa12e9','qualification':'Placeholder before final gates. Sealer replaces this with exact canonical Git-blob bytes after current82/82 receipt and individual library checks.'})
shutil.copyfile(__file__,work/'review_tools'/Path(__file__).name)
for name,folder in [('job-geology-painted-work-20261001.json',work),('job-geology-river-painted-source-20261001.json',river)]:
 p=b/'design/audit_impacts'/name;d=read(p);d['files']=sorted(set(d['files'])|{q.relative_to(b).as_posix() for q in folder.rglob('*') if q.is_file()}|({mp.relative_to(b).as_posix()} if folder==work else set()));write(p,d)
print('Browser QA, current task index and map placeholder covered before final gates.')
