from pathlib import Path
import hashlib,json,datetime,shutil,html,os
from PIL import Image
B=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
C=B/'audit/job_candy_workflow_current_v1_20261003';D=B/'audit/job_candy_wrap_contact_runtime_v1_20261003';M=B/'assets_src/imagegen/candy_wrap_contact_v1_20261003'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
# Preserve generated original pixels and hash. This bridge was directly seen in the generation result.
a=M/'attempt08';a.mkdir(exist_ok=True)
generated=Path(r'C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-58bc5fb8-b379-45f7-8327-ef2e474b930f.png')
if not (a/'native.png').exists():shutil.copyfile(generated,a/'native.png')
assert sha(generated)==sha(a/'native.png')
im=Image.open(a/'native.png');assert im.size==(1254,1254) and im.mode=='RGBA'
s={'native_path':(a/'native.png').relative_to(B).as_posix(),'sha256':sha(a/'native.png'),'generated_original_path':str(generated),'generated_original_sha256':sha(generated),'dimensions':list(im.size),'mode':im.mode,'alpha_extrema':list(im.getchannel('A').getextrema()),'prompt_path':(M/'PROMPT_A8.txt').relative_to(B).as_posix(),'prompt_sha256':sha(M/'PROMPT_A8.txt'),'attempt':8,'generation_method':'builtin_image_gen','reference':read(M/'PLAN_A8.json')['reference'],'modifications':'None; exact generated native RGBA preserved','production_binding':False,'owner_acceptance':None}
write(a/'SOURCE.json',s)
bridge_rows=[('Half edge fold',4.5,'Mittens support a partly folded continuous gold sheet, retaining an exposed central sweet. Static contact only.'),('Slide to necks',4.1,'Paper necks are already tightly twisted; this skips the intended untwisted sliding/contact bridge and reverses chronology when followed by A7 pinch.'),('Half opposing roll',4.4,'Opposing grip is understandable, but belly enlarges and sits higher than A7; the action continuity gap remains.'),('Relaxed settle',4.2,'Mittens still clasp the finished necks; requested release/relaxation is absent. Belly remains oversized.'),('Whole bridge source',4.1,'Partial fold improves, but premature twists, sweet size/height drift and absent relaxed settle reject the bridge sheet. Preserve exact native and do not bind it.')]
write(a/'DIRECT_REVIEW.json',{'status':'REJECTED_BRIDGE_CONTINUITY','reviewed_utc':now,'direct_native_review':True,'opinions':[{'item':i,'score':v,'evaluation':e} for i,v,e in bridge_rows],'production_binding':False,'owner_acceptance':None,'qualification':'Directly inspected generated native; static source/individual states only. No actual use, complete action, technical import, device or owner acceptance.'})
sheet=read(M/'COMPLETE_SOURCE_REVIEW.json')
assert len(sheet['sources']) in (7,8)
sheet['sources']=[x for x in sheet['sources'] if x['attempt']!=8]+[{'attempt':8,'source':s,'whole_source_score':4.1,'source_review':read(a/'DIRECT_REVIEW.json'),'state_opinions':[{'state':x[0],'region':[j%2*627,j//2*627,627,627],'score':x[1],'scope':'Missing authored bridge-state candidate; static/source only, rejected complete sheet.'} for j,x in enumerate(bridge_rows[:4])],'production_binding':False,'owner_acceptance':None}]
sheet['reviewed_utc']=now;sheet['qualification']='All8 native sources directly viewed. A7 static endpoint sheet4.5 provisional; exact A5 actual four-key action4.1 rejected. A8 missing-bridge sheet4.1 rejected for premature twisted necks and size/settle drift. 1254RGBA NPOT originals remain outside runtime. No technical-ready, animated/action, device or owner pass.';write(M/'COMPLETE_SOURCE_REVIEW.json',sheet)
# All42 complete ordered boards were directly inspected; original details below were seen separately.
q=read(D/'QA_BOARD_MANIFEST_CONTACT_A5.json')
assert len(q['boards'])==42
for board in q['boards']:
 assert sha(B/board['path'])==board['sha256'];board['direct_review']=True
 for member in board['members']:
  assert sha(B/member['path'])==member['sha256'];member['direct_review']=True;member['review_scope']='Complete ordered canvas inspected in QA board; original-size details named separately.'
q['status']='ALL42_ORDERED_BOARDS_DIRECTLY_REVIEWED';q['reviewed_utc']=now;write(D/'QA_BOARD_MANIFEST_CONTACT_A5.json',q)
caps={w:read(D/f'attempt05/CAPTURE_training_{w}.json') for w in [1280,1600]}
details=[]
for w in [1280,1600]:
 for n in [8,9,80,81,136,137,168,169]:
  f=caps[w]['motion_frames'][n];assert sha(B/f['path'])==f['sha256'];details.append({'path':f['path'],'sha256':f['sha256'],'direct_original_native_review':True,'native_size':[w,720],'index':n})
 for n in [8,11,12]:
  f=caps[w]['views'][n];assert sha(B/f['path'])==f['sha256'];details.append({'path':f['path'],'sha256':f['sha256'],'direct_original_native_review':True,'native_size':[w,720],'tag':f['tag']})
rows=[('Open sheet contact',4.5,'Both connected mittens contact the actual gold sheet at table level. Complete source proportions are preserved at the real dock size.',9),('Folded long edges',4.5,'Golden paper wraps the belly and hands contact the lifted edges. This is a good static endpoint; the incoming movement is separately rejected.',81),('Narrow neck pinch',4.5,'Both mittens grip narrow connected necks instead of outer fans. Belly remains on the table. Static endpoint only.',137),('Opposing wrist twist',4.6,'Wrist poses oppose visibly while both necks stay attached to the gold fans and central belly. Individual endpoint/material opinion.',169),('Wrapper material match',4.5,'Same golden creases, scalloped fans, navy/plum contours and broad painted highlights as the candidate wrapper. Source match does not establish full motion.',169),('Connected arms and anatomy',4.5,'Exactly two sleeves/forearms connect mittens to the torso throughout the four keys. No detached hand substitute.',137),('Table and sweet support continuity',4.2,'Top-to-bottom row change moves tabletop and sweet upward by a few pixels. The same target rectangle cannot correct inconsistent authored anchors.',137),('Head and torso continuity',4.1,'Head/costume changes at key81 and137 are abrupt even though the source region and draw rectangle are fixed. These are pose keys, not temporal in-betweens.',81),('Whole fold/pinch/twist causality',4.2,'Paper finally becomes an enclosed sweet, but three instant jumps omit the actual fold and sliding grip. All input-driven canvases are inspected; four endpoints alone do not pass acting.',137),('Visible-paper touch cue',4.0,'Hub/circle now sits by paper and hands instead of face. Large inherited lens persists, and the demo marker can cover the sweet or extend below the tabletop.',9),('Opening opacity and ownership',4.0,'First connected work frame8 is translucent at both sizes, then opaque at9. Native details show no simultaneous full-tail duplicate here; previous A2 duplicate remains historical. Initial transparency remains weak.',8),('Exit and next invitation ownership',3.6,'Final recorded phase3 endpoint briefly has neither worker drawing nor room actor, while later selected invitation restores Roshan. A good later still does not accept the exact exit transition.',206),('Whole actual wrapper action',4.1,'Matching connected contact is substantially improved from current production2.8, but pose/support snaps, initial translucency and a missing actor on exit remain below4.5. Candidate remains unbound.',169)]
opinions=[]
for i,(label,score,evaluation,n) in enumerate(rows,1):
 ev=[]
 for w in [1280,1600]:
  index=min(n,len(caps[w]['motion_frames'])-1);f=caps[w]['motion_frames'][index];ev.append({'path':f['path'],'sha256':f['sha256'],'native_size':[w,720],'index':index})
 opinions.append({'id':f'CANDY-CONTACT-A5-{i:02d}','item':label,'score':score,'evaluation':evaluation,'evidence':ev,'priority':score<=4.5,'scope':'Unbound actual-input drawing/contact study; never current production acceptance','production_binding':False,'owner_acceptance':None})
receipts=[read(p) for p in sorted((D/'runtime_gate_a05').glob('*.receipt.json'))];assert len(receipts)==8 and all(x['status']=='PASS' for x in receipts)
review={'status':'ALL_ACTUAL_CONTACT_CANVASES_REVIEWED_WHOLE_ACTION_REJECTED','reviewed_utc':now,'reviewer':'Codex drafting visual review','source':'assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt07/native.png','source_sha256':sha(M/'attempt07/native.png'),'coverage':{'consecutive_canvases':412,'phase2_canvases':410,'phase3_endpoints':2,'selected_views':32,'ordered_boards':42,'original_native_details':len(details)},'opinions':opinions,'direct_native_details':details,'machine_status':'Eight focused parser/inference/official4.7.2 analyzer/capture checks pass; idle, stationary/repeated taps, release and resumed circle verified. Exact native1280/1600 sizes asserted.','qualification':'Unbound surface drawing substitute plus explicitly declared hub at visible paper, smaller .16 circle above inherited .13 dead zone and presentation-only room actor visibility. Original209 inherited properties/signals, completion/goal/reward/save remain inherited. Raw generic receipt phrase original input/geometry is qualified here: pivot/radius deliberately differ. Four authored static keys are not temporal in-betweens. Current game/new birthday route repair remain separate. Readback/desktop Mobile is not natural timing or target-device evidence.','binding_changed':False,'all783_frozen_sources_unchanged_during_capture':True,'missing_evidence':['Accepted full contact motion and interruptions','Natural timing','Target phone','Child','Owner','All-job comprehensive approval'],'owner_acceptance':None,'finding_lifecycles_changed':False}
write(D/'DIRECT_REVIEW_A5.json',review)
contract=D/'CLIP_CONTRACT_V2.json';old=read(contract);preserve=D/'CLIP_CONTRACT_V2.before_A5_review.original.json'
if not preserve.exists():shutil.copyfile(contract,preserve)
old['status']='ACTUAL_ACTION_REVIEWED_REJECTED_4_1_UNBOUND';old['current_review']='audit/job_candy_wrap_contact_runtime_v1_20261003/DIRECT_REVIEW_A5.json';old['whole_action_score']=4.1;old['source_floor_not_action_acceptance']=True;old['next_gap']='Missing authored fold/grip/twist bridges, stable head/table/sweet anchors and exact entry/exit ownership. A8 bridge4.1 separately rejected.';write(contract,old)
style='body{max-width:1500px;margin:auto;padding:24px;background:#f6f0ff;color:#292043;font:17px/1.5 system-ui}a{color:#473679}img{max-width:100%;height:auto;background:repeating-conic-gradient(#ded4ea 0% 25%,#f6f0ff 0% 50%) 0/24px 24px}article,details{padding:16px;margin:14px 0;border:1px solid #d7c6e5;border-radius:12px;background:white}summary{cursor:pointer;font-weight:bold}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:18px}figcaption{font-size:13px;overflow-wrap:anywhere}figure{margin:10px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}input[type=range]{width:90%}.weak{color:#96351f}'
esc=html.escape
def fig(base,v):
 p=Path(os.path.relpath(B/v['path'],base)).as_posix();return '<figure><a href="'+esc(p)+'"><img loading="lazy" src="'+esc(p)+'"></a><figcaption>'+esc(v.get('tag',v['path']))+' · '+esc(v['sha256'])+'</figcaption></figure>'
def page(title,body):return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><style>'+style+'</style><main><h1>'+esc(title)+'</h1>'+body+'</main></html>\n'
body='<p><strong>Current game does not match the golden-paper wrapper:2.8/5.</strong> This separately mounted A7 contact study improves static grips to4.5–4.6, but the complete actual action is <strong class="weak">4.1/5 · rejected/unbound</strong>. No production wrapper/contact replacement has been accepted.</p><p>Every412 consecutive canvases and32 selected views reviewed on42 ordered boards, plus22 original native details, at native1280×720 and1600×720. Four poses are static authored keys; they cannot stand in for missing fold/grip movement.</p><p>Eight focused machine checks pass. Idle, stationary/repeated touch, release and resumed circle cannot earn false progress. Hub is deliberately moved to the visible paper; original completion/goal/reward/save logic is inherited. Exact windowed pixel sizes are asserted. Target device, natural timing, interruptions, child and owner remain pending.</p><nav><a href="../job_candy_workflow_current_v1_20261003/index.html">Current Candy game and birthday findings</a> · <a href="../../assets_src/imagegen/candy_wrap_contact_v1_20261003/index.html">All8 source attempts</a> · <a href="DIRECT_REVIEW_A5.json">Exact review</a> · <a href="CLIP_CONTRACT_V2.json">Clip contract</a> · <a href="../job_artwork_refinement_live/all_items.html">All-item library</a></nav>'
body+='<div class="grid">'+''.join(fig(D,caps[1280]['motion_frames'][n]) for n in [9,81,137,169])+'</div><h2>Individual contact and transition evaluations</h2>'
for o in opinions:body+='<article id="'+o['id']+'"><h3>'+esc(o['item'])+' · '+str(o['score'])+'/5</h3><p>'+esc(o['evaluation'])+'</p><details><summary>Exact native evidence at both sizes</summary><div class="grid">'+''.join(fig(D,v) for v in o['evidence'])+'</div></details></article>'
body+='<h2>Complete ordered capture inspection</h2><p>Manual scrub displays every complete captured canvas with its actual saved state. Playback is for audit inspection; slow viewport readback does not establish natural gameplay timing. No blended/generated frames are added.</p>'
players=[]
for w,cap in caps.items():
 frames=[dict(path=Path(os.path.relpath(B/v['path'],D)).as_posix(),index=v['index'],state=v['state']) for v in cap['motion_frames']];players.append({'width':w,'frames':frames})
 body+=f'<article><h3>{w}×720 · {len(frames)} consecutive canvases</h3><img id="frame{w}" src="{frames[0]["path"]}"><input id="scrub{w}" type="range" min="0" max="{len(frames)-1}" value="0"><button id="play{w}">Play ordered capture</button><pre id="state{w}"></pre></article>'
 body+='<details><summary>'+str(w)+' · all16 selected canvases</summary><div class="grid">'+''.join(fig(D,v) for v in cap['views'])+'</div></details>'
body+='<details><summary>All42 ordered boards directly reviewed</summary>'+''.join(fig(D,v) for v in q['boards'])+'</details><h2>Rejected earlier fixtures and source revisions</h2><p>A2:303 consecutive canvases/32 selected views fully reviewed; whole3.8 rejected. A03 analyzer failure precedes gameplay; A04 resized to1920×1080 mid-sort and failed before WRAP. Exact original scripts, outputs and failed diagnostics remain preserved. A05 corrects explicit window mode and asserts actual pixels; it does not alter gameplay to make a failed capture pass.</p><p><a href="DIRECT_REVIEW_A2.json">Earlier A2 review</a> · <a href="FIXTURE_CORRECTION_V512.json">A03 analyzer failure</a> · <a href="FIXTURE_WINDOW_CORRECTION_V513.json">A04 window change</a> · <a href="DIMENSIONS_RECHECK_V513.json">Complete native-size inventory</a></p>'
body+='<script>const captures='+json.dumps(players,separators=(',',':'))+';for(const c of captures){const s=document.getElementById("scrub"+c.width),im=document.getElementById("frame"+c.width),st=document.getElementById("state"+c.width),p=document.getElementById("play"+c.width);let timer=null;const show=()=>{const f=c.frames[Number(s.value)];im.src=f.path;st.textContent=JSON.stringify({index:f.index,state:f.state},null,2)};s.addEventListener("input",show);p.addEventListener("click",()=>{if(timer){clearInterval(timer);timer=null;p.textContent="Play ordered capture";return}p.textContent="Stop inspection";timer=setInterval(()=>{s.value=(Number(s.value)+1)%c.frames.length;show()},150)});show()}</script>'
(D/'index.html').write_text(page('Candy wrapper · actual hand contact and complete action study',body),encoding='utf-8',newline='\n')
# Rebuild the source page including all eight originals, each distinct state and preserved exact prompts.
body='<p>Eight reversible built-in ImageGen source attempts. Every complete native source and all32 individual states directly reviewed. A7 static endpoints4.5–4.6; exact in-game contact action4.1 remains rejected. A8 bridges4.1 fail chronology/size/settle and are not used.</p><p><a href="../../../audit/job_candy_wrap_contact_runtime_v1_20261003/index.html">Complete actual-input contact study</a> · <a href="COMPLETE_SOURCE_REVIEW.json">All exact source/state evaluations</a></p>'
for e in sheet['sources']:
 body+='<article id="attempt'+str(e['attempt'])+'"><h2>Attempt'+str(e['attempt'])+' · complete source '+str(e['whole_source_score'])+'/5</h2>'+fig(M,{'path':e['source']['native_path'],'sha256':e['source']['sha256']})+'<p>'+esc(' · '.join(x['state']+':'+str(x['score'])+'/5' for x in e['state_opinions']))+'</p>'+''.join('<p><strong>'+esc(o['item'])+' '+str(o['score'])+'/5.</strong> '+esc(o['evaluation'])+'</p>' for o in e['source_review']['opinions'])+'<details><summary>Exact generation prompt</summary><pre>'+esc((M/f'PROMPT_A{e["attempt"]}.txt').read_text())+'</pre><a href="attempt'+f'{e["attempt"]:02d}'+'/SOURCE.json">Original provenance</a></details></article>'
(M/'index.html').write_text(page('Candy Maker · all connected wrapping source iterations',body),encoding='utf-8',newline='\n')
cp=C/'index.html';cp.write_text(cp.read_text().replace('href="DIMENSIONS_RECHECK_LINK.txt"','href="../job_candy_wrap_contact_runtime_v1_20261003/DIMENSIONS_RECHECK_V513.json"'),encoding='utf-8',newline='\n')
shutil.copyfile(Path(__file__),C/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-workflow-current-20261003.json';d=read(ip)
d['scope']='Current Candy audit of all4 normal phases and all4 birthday phases through actual Kitchen card/input; complete wrapping/glaze circle sequences at1280/1600 and selected other-phase canvases. One production file repairs four absent Chapter2 station bindings using existing painted pitcher/berry/tray invitations; no input/goal/state/save/reward/completion change. Preserve failed unmodified route and all fixture/analyzer/window-size failures. Three separately preserved wrapper sources and eight connected hand/paper source attempts remain outside runtime, each complete original and individual state reviewed. A2 unbound actual contact3.8 fails original face hub/duplicate entry; revised A5 explicitly moves hub to visible paper, reduces circle above unchanged dead zone and hides/restores room actor only from real phase/task/panel. Exact209 inherited properties/signals, completion and saved effects remain unchanged. Passive/stationary/repeated/release/resume guards and windowed pixel-size assertions pass, but whole A5 action4.1 fails pose/support snaps, initial opacity and exit actor absence. Missing bridge A8 source4.1 rejected; no contact source binding or source-to-action acceptance transfer. Current birthday wrong-tier/duplicate berry and cake-occlusion defects stay open; all candidates and history preserved.'
d['acceptance_gaps']='Current WRAP2.8 and birthday GLAZE2.6; unbound sourceA7 static4.5 does not pass complete actual action4.1. Missing authored hand/paper continuity and entry/exit ownership; A8 bridge4.1 rejected. Birthday cake0x3F/0x7F semantics, duplicate berries and occlusion need repair. Separate Opera elevator, all other complete actions, full preceding story, natural timing, target device, child, owner, comprehensive all-job, integration/release acceptance remain open. Finding lifecycle states unchanged.'
d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for root in [C,D,M,B/'assets_src/imagegen/candy_wrap_states_v1_20261003'] for p in root.rglob('*') if p.is_file()})
d['validation'].append({'command':'Directly inspect every42 A5 ordered boards and22 original native details; all8 connected native sources and32 states','result':'PASS','evidence':'audit/job_candy_wrap_contact_runtime_v1_20261003/DIRECT_REVIEW_A5.json'});write(ip,d)
print(json.dumps({'A5_frames':412,'A5_boards':42,'native_details':len(details),'individual_opinions':len(opinions),'source_attempts':8,'A5_whole':4.1,'bridge_whole':4.1,'binding':False}))
