from pathlib import Path
import json,shutil,hashlib,datetime
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
m=b/'assets_src/imagegen/candy_wrap_contact_v1_20261003'
dest=m/'attempt09';assert not dest.exists();dest.mkdir()
original=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-9a6b3dbd-b00c-4a15-8dac-32360e999dfb.png')
shutil.copyfile(original,dest/'native.png')
prompt="Use case: illustration-story. Transparent 2D game atlas, exactly four complete square cells in an equal 2 by 2 grid.\nReference image: Roshan identity, original coral mittens connected to her two arms, cream sleeves, teal costume, rainbow hair, lavender table and this specific golden paper. Preserve the same painted outlines, broad soft value bands and rounded storybook shapes.\n\nDraw four NEW bridge poses to complete wrapping this same little oval candy. Use the TOP-LEFT reference cell's head, torso, table outline and sweet center as the identical anchor in every cell. The table never shifts; the sweet never grows or lifts. Her calm closed-mouth smile and head stay fixed. Only connected elbows/mittens and the paper change.\n\nTop-left: both mittens lift the long edges halfway over the exposed red sweet, a continuous paper sheet still partly open.\nTop-right: the long edges now overlap and hide the red sweet; the mittens slide toward the narrow ends. Show loose gathered paper necks with a simple straight fold. They are NOT twisted yet: no coiled rings, beads, knots or spirals.\nBottom-left: both mittens pinch those loose necks and begin one small opposite wrist roll, left up and right down. Very small first creases, not a finished tight twist. Candy belly stays precisely the same width and table position.\nBottom-right: finished gold wrapper rests on the table, attached fan ends and clearly twisted narrow necks. BOTH mittens have visibly LET GO and rest on the table just outside the fans, with a small clear gap from the paper.\n\nFour complete independently contained silhouettes with transparent gutters; no text, arrows, ghost hands, floating hands, extra arms, whisk or tools. No appearance change to distinguish cells. Preserve real alpha. This is authored intermediate-state art, not a movie or approval claim."
(m/'PROMPT_A9.txt').write_text(prompt,encoding='utf-8')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
im=Image.open(dest/'native.png')
source={'native_path':(dest/'native.png').relative_to(b).as_posix(),'sha256':sha(dest/'native.png'),'generated_original_path':str(original),'generated_original_sha256':sha(original),'dimensions':list(im.size),'mode':im.mode,'alpha_extrema':list(im.getchannel('A').getextrema()),'prompt_path':(m/'PROMPT_A9.txt').relative_to(b).as_posix(),'prompt_sha256':sha(m/'PROMPT_A9.txt'),'attempt':9,'generation_method':'builtin_image_gen','reference':{'path':(m/'attempt07/native.png').relative_to(b).as_posix(),'sha256':sha(m/'attempt07/native.png'),'role':'identity/material/support continuity; direct native inspected'},'modifications':'None; exact native RGBA preserved','production_binding':False,'owner_acceptance':None}
assert source['sha256']==source['generated_original_sha256']
review={'status':'REJECTED_BRIDGE_CONTINUITY','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'direct_native_review':True,'opinions':[{'item':'Half edge fold','score':4.5,'evaluation':'Mittens support one partly folded gold sheet around the exposed sweet. Static contact only.'},{'item':'Slide to untwisted necks','score':4.1,'evaluation':'Raised ring-like bands still close the necks before the intended pinch and twist; the central sweet becomes much wider and taller. Chronology and conserved candy size fail.'},{'item':'First opposing wrist roll','score':4.3,'evaluation':'Two hands stay connected and contact the wrapper, but the belly remains enlarged and the neck is already tightly coiled. This is not the missing small initial roll.'},{'item':'Released settle','score':4.5,'evaluation':'Both mittens visibly release and rest outside attached fans; the wrapped sweet has readable narrow twisted necks. Static endpoint only.'},{'item':'Whole bridge source','score':4.1,'evaluation':'Release is improved. Premature closure and candy-size/support drift reject the complete bridge sheet. Do not bind it or transfer endpoint scores to full action.'}],'production_binding':False,'owner_acceptance':None,'qualification':'Every native state directly inspected; exact generation source preserved. Static source review does not establish current gameplay, complete motion, technical import, device, child or owner acceptance.'}
for name,d in [('SOURCE.json',source),('DIRECT_REVIEW.json',review)]: (dest/name).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
shutil.copyfile(__file__,b/'audit/job_candy_workflow_current_v1_20261003/review_tools/persist_candy_source_a9_v521.py')
ip=b/'design/audit_impacts/job-candy-workflow-current-20261003.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in m.rglob('*') if p.is_file()}|{'audit/job_candy_workflow_current_v1_20261003/review_tools/persist_candy_source_a9_v521.py'});ip.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print('Preserved A9 native',source['sha256'],'and all four separate state evaluations; whole4.1 rejected.')

