from pathlib import Path
import json, hashlib, datetime, shutil
B=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
M=B/'assets_src/imagegen/candy_wrap_contact_v1_20261003'
C=B/'audit/job_candy_workflow_current_v1_20261003'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
prompt='''Use case: illustration-story
Asset type: four authored intermediate hand-and-paper states for the existing 2D Candy Maker wrapping action; transparent RGBA, precisely the same 2 by 2 square grid as the reference.
Input image 1: appearance, identity, costume, table geometry and golden-paper wrapper reference. Preserve its Roshan identity, waist-up framing, two connected arms, sleeves, coral oven mittens, teal vest, hat, rainbow hair, outline and broad painted shading. This is a continuity repair, not a redesign.
Primary request: draw ONLY the four missing intermediate actions described below. Each cell shows the same complete Roshan upper body and lavender table, with exactly the same head center, shoulder height, table outline and tabletop baseline. Keep her small calm smile and downward attention identical in every cell; no head bob or torso scale change. Keep the sweet belly centered on the same point of the tabletop, same size and never lifted.
Top-left: between reference open sheet and reference folded sheet. Both mittens lift the two long paper edges halfway toward the exposed coral oval sweet. One continuous golden paper sheet, partial fold, sweet still partly exposed.
Top-right: between reference folded sheet and reference neck pinch. The paper now encloses the sweet; both mittens slide inward to just touch the two narrow necks. Broad end fans stay attached and supported. Do not grasp outer fan tips.
Bottom-left: between reference neck pinch and reference opposite wrist twist. Both mittens firmly grip the narrow necks, left wrist beginning to roll up and right wrist beginning to roll down. Only a small half-turn, two attached creased gold necks; sweet belly remains fixed on the table.
Bottom-right: settled end immediately after reference wrist twist. Same finished golden-paper sweet, narrow twisted necks and attached fans. Both mittens gently relax next to the necks without moving the sweet or table.
Composition: four complete independent square cells, equal quadrants, transparent gutters and full contours within each cell. No text, arrows, motion marks, background scene, duplicated/extra fingers, disconnected hands, whisk or utensils. Smooth authored continuity in the connected elbows/mittens and paper between these action stages. Do not change appearance-bearing parts merely to differentiate the cells. Preserve real transparency.'''
(M/'PROMPT_A8.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
plan={'attempt':8,'purpose':'Fill missing authored hand/paper transitions identified in complete actual A5 action review; no speculative redesign','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'generation_method':'builtin_image_gen','reference':{'path':'assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt07/native.png','sha256':sha(M/'attempt07/native.png'),'role':'identity/material/support/continuity reference; direct native inspected'},'prompt_sha256':sha(M/'PROMPT_A8.txt'),'production_binding':False,'acceptance':'Direct review every native bridge, measured quarter sampling and anchored actual-input replay required. Endpoints/source score never grants whole motion acceptance.','rules':['DL-MOT-01','DL-MOT-02','DL-MOT-03','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-ASSET-04'],'finding_lifecycle_changed':False}
(M/'PLAN_A8.json').write_text(json.dumps(plan,indent=2)+'\n',encoding='utf-8',newline='\n')
shutil.copyfile(Path(__file__),C/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-workflow-current-20261003.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{(M/'PROMPT_A8.txt').relative_to(B).as_posix(),(M/'PLAN_A8.json').relative_to(B).as_posix(),(C/'review_tools'/Path(__file__).name).relative_to(B).as_posix()});d['scope']+=' Generate only missing authored intermediate hand-and-paper states after actual A5 pose-snap review; preserve A7 endpoint source and all earlier failures. New bridge source stays unbound until its exact source/contact/action review.';ip.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
print(json.dumps({'prompt':prompt,'reference':str(M/'attempt07/native.png')}))
