from pathlib import Path
import datetime,hashlib,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');c=b/'audit/job_candy_workflow_current_v1_20261003';k=b/'audit/job_geology_fossil_reveal_continuity_v1_20261003';base=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
shots=[]
for name in ['CandyCurrentReportV524.png','CandyContactReportV524.png','CandySourcesReportV524.png','CandyLibraryStatesV524.png']:
 target=c/name;assert not target.exists();shutil.copyfile(base/name,target);shots.append({'path':target.relative_to(b).as_posix(),'sha256':sha(target),'source':'cua_repl browser screenshot, original bytes preserved','qualification':'Temporary browser QA at actual report viewport, not gameplay/device/owner acceptance.'})
old=base/'FossilRevealReportV487.png'
if old.exists():
 target=k/old.name;assert not target.exists();shutil.copyfile(old,target)
 d={'status':'PRESERVED_EARLIER_TEMPORARY_BROWSER_SCREENSHOT','path':target.relative_to(b).as_posix(),'sha256':sha(target),'qualification':'Earlier fossil candidate page inspected before the later Candy station source repair. Screenshot is report QA only, never refreshed current-game or owner evidence.'}
 (k/'BROWSER_QA_SCREENSHOT_V487.json').write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
receipt={'status':'PASS_SCOPED_TEMPORARY_BROWSER_REPORT_QA','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checks':[{'report':'Current Candy workflow','result':'PASS','observed':'48 individual opinion articles; four top complete native canvases loaded, two1280x720 and two1600x720.'},{'report':'Unbound contact action','result':'PASS','observed':'Manual native1280 scrub reached exact frame81; displayed file0081 and natural width1280. Play advanced to82; Stop stopped and kept82. Source/action scores remain separate, whole4.1 rejected.'},{'report':'Contact source history','result':'PASS','observed':'Ten source articles; last complete source loaded1254x1254; forty native states individually graded in saved source review. Latest whole4.2 rejected.'},{'report':'V44 all-job register','result':'PASS','observed':'1277 sources+328 pose cells+151 use/action entries+178 source regions=1934 entries;772 source/cell/region priorities,585 unique source priorities,48 current Candy priorities,377 source reviews pending. Search CANDY-M-A10 displays four loaded individually scored state records; no mounted/action acceptance.'},{'report':'Golden material source history','result':'PASS','observed':'All three source-attempt sections and independent material/sampling/contact limitations visible.'}],'screenshots':shots,'qualification':'Report rendering, labels, search and inspection controls only. Hidden/lazy image elements were not falsely counted as decoded. Full source/frame direct reviews and immutable byte verification are separate. No browser persistence/status operation, retry of rejected action, owner approval or production art binding.'}
(c/'BROWSER_QA_V525.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
shutil.copyfile(__file__,c/'review_tools/save_candy_browser_qa_v525.py')
for ip,families in [(b/'design/audit_impacts/job-candy-workflow-current-20261003.json',[c]),(b/'design/audit_impacts/job-geology-fossil-reveal-continuity-20261003.json',[k])]:
 d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for folder in families for p in folder.rglob('*') if p.is_file()});ip.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print('Preserved four Candy browser screenshots, scoped QA and the earlier fossil screenshot; no creative approval claim.')
