export type ShotStatus = "ready" | "prep";
export type ShotKind = "reel" | "shot";

export type Shot = {
  id: string;
  title: string;
  beat: string;
  duration: string;
  status: ShotStatus;
  still: string;
  video?: string;
  kind: ShotKind;
  chapter: string;
  loop?: boolean;
};

export const FILM = {
  title: "Day One",
  chapter: "Sky Lagoon, bathroom, pool, garden loops, swim",
  logline:
    "The painted Sky Lagoon lives. Garden water, leaves, and clouds loop. Roshan cleans the bathroom and pool, then swims.",
};

export const SHOTS: Shot[] = [
  {
    id: "SHOT-SKY-LIVING",
    title: "Sky Lagoon",
    beat: "Trees, grass, and clouds move on the painted castle lawn. Locked camera.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/SHOT-SKY-LIVING.jpg",
    video: "/movies/SHOT-SKY-LIVING.mp4",
    kind: "reel",
    chapter: "Sky Lagoon",
    loop: true,
  },
  {
    id: "REEL-DAY-ONE",
    title: "Day One",
    beat: "Bathroom then pool — the cut.",
    duration: "54s",
    status: "ready",
    still: "/stills/SHOT-BATH-SINK.jpg",
    video: "/movies/DAY-ONE.mp4",
    kind: "reel",
    chapter: "Day One",
  },
  {
    id: "REEL-BATHROOM",
    title: "Bathroom",
    beat: "Sink, tub, drain, toilet.",
    duration: "24s",
    status: "ready",
    still: "/stills/SHOT-BATH-SINK.jpg",
    video: "/movies/DAY-ONE-BATHROOM.mp4",
    kind: "reel",
    chapter: "Bathroom",
  },
  {
    id: "REEL-POOL",
    title: "Pool",
    beat: "Skim, three waterfall lanes, plug.",
    duration: "30s",
    status: "ready",
    still: "/stills/SHOT-POOL-SKIM.jpg",
    video: "/movies/DAY-ONE-POOL.mp4",
    kind: "reel",
    chapter: "Pool",
  },
  {
    id: "SL2-W01",
    title: "Water drift",
    beat: "Turquoise highlight bands drift sideways. Spot loop.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/SL2-W01.jpg",
    video: "/movies/SL2-W01.mp4",
    kind: "shot",
    chapter: "Garden loops",
    loop: true,
  },
  {
    id: "SL2-W02",
    title: "Shore lap",
    beat: "One painted lap touches the stones and recedes.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/SL2-W02.jpg",
    video: "/movies/SL2-W02.mp4",
    kind: "shot",
    chapter: "Garden loops",
    loop: true,
  },
  {
    id: "SL2-P01",
    title: "Huckleberry",
    beat: "Leaf sprays flex in a tiny breeze, then settle.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/SL2-P01.jpg",
    video: "/movies/SL2-P01.mp4",
    kind: "shot",
    chapter: "Garden loops",
    loop: true,
  },
  {
    id: "SL2-C01",
    title: "Cloud wisps",
    beat: "Interior cloud folds drift. Outer bank stays.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/SL2-C01.jpg",
    video: "/movies/SL2-C01.mp4",
    kind: "shot",
    chapter: "Garden loops",
    loop: true,
  },
  {
    id: "RSW-01",
    title: "Everyday swim",
    beat: "Notice right, one rounded tail stroke, glide, settle.",
    duration: "6s",
    status: "ready",
    still: "/stills/RSW-01.jpg",
    video: "/movies/RSW-01.mp4",
    kind: "shot",
    chapter: "Swim",
  },
  {
    id: "RSW-02",
    title: "Excited swim",
    beat: "Two quick tail efforts into a buoyant glide.",
    duration: "6s",
    status: "ready",
    still: "/stills/RSW-02.jpg",
    video: "/movies/RSW-02.mp4",
    kind: "shot",
    chapter: "Swim",
  },
  {
    id: "RSW-03",
    title: "Curious swim",
    beat: "Glance lower-right, inspect, resume the stroke.",
    duration: "6s",
    status: "ready",
    still: "/stills/RSW-03.jpg",
    video: "/movies/RSW-03.mp4",
    kind: "shot",
    chapter: "Swim",
  },
  {
    id: "RSW-04",
    title: "Playful bank",
    beat: "One shallow downward-right curve, then level out.",
    duration: "6s",
    status: "ready",
    still: "/stills/RSW-04.jpg",
    video: "/movies/RSW-04.mp4",
    kind: "shot",
    chapter: "Swim",
  },
  {
    id: "RSW-05",
    title: "Bored to delighted",
    beat: "Wait, ask, then commit to an eager glide.",
    duration: "6s",
    status: "ready",
    still: "/stills/RSW-05.jpg",
    video: "/movies/RSW-05.mp4",
    kind: "shot",
    chapter: "Swim",
  },
  {
    id: "RSW-06",
    title: "Focused offer",
    beat: "Purposeful swim, slow, open hand toward destination.",
    duration: "6s",
    status: "ready",
    still: "/stills/RSW-06.jpg",
    video: "/movies/RSW-06.mp4",
    kind: "shot",
    chapter: "Swim",
  },
  {
    id: "RSW-07",
    title: "Swim loop",
    beat: "In-place everyday stroke for extraction.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/RSW-07.jpg",
    video: "/movies/RSW-07.mp4",
    kind: "shot",
    chapter: "Swim",
    loop: true,
  },
  {
    id: "RSW-08",
    title: "Livelier loop",
    beat: "Two compact tail pulses, in-place, for extraction.",
    duration: "6s loop",
    status: "ready",
    still: "/stills/RSW-08.jpg",
    video: "/movies/RSW-08.mp4",
    kind: "shot",
    chapter: "Swim",
    loop: true,
  },
  {
    id: "SHOT-BATH-SINK",
    title: "Sink",
    beat: "Scrub the center basin. A clean patch stays.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-BATH-SINK.jpg",
    video: "/movies/SHOT-BATH-SINK.mp4",
    kind: "shot",
    chapter: "Bathroom",
  },
  {
    id: "SHOT-BATH-TUB",
    title: "Tub",
    beat: "Scrub the dirty rim. A clean stripe stays.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-BATH-TUB.jpg",
    video: "/movies/SHOT-BATH-TUB.mp4",
    kind: "shot",
    chapter: "Bathroom",
  },
  {
    id: "SHOT-BATH-DRAIN",
    title: "Drain",
    beat: "Open the original outlet. The waterline falls.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-BATH-DRAIN.jpg",
    video: "/movies/SHOT-BATH-DRAIN.mp4",
    kind: "shot",
    chapter: "Bathroom",
  },
  {
    id: "SHOT-BATH-TOILET",
    title: "Toilet",
    beat: "Scrub the pink bowl. Dirt clears.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-BATH-TOILET.jpg",
    video: "/movies/SHOT-BATH-TOILET.mp4",
    kind: "shot",
    chapter: "Bathroom",
  },
  {
    id: "SHOT-POOL-SKIM",
    title: "Skim",
    beat: "Net lifts the litter. Fixtures stay.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-POOL-SKIM.jpg",
    video: "/movies/SHOT-POOL-SKIM.mp4",
    kind: "shot",
    chapter: "Pool",
  },
  {
    id: "SHOT-POOL-FALL-1",
    title: "Lane 1",
    beat: "Scrub the left waterfall. Water starts to run.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-POOL-FALL-1.jpg",
    video: "/movies/SHOT-POOL-FALL-1.mp4",
    kind: "shot",
    chapter: "Pool",
  },
  {
    id: "SHOT-POOL-FALL-2",
    title: "Lane 2",
    beat: "Scrub the center waterfall. Two lanes flow.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-POOL-FALL-2.jpg",
    video: "/movies/SHOT-POOL-FALL-2.mp4",
    kind: "shot",
    chapter: "Pool",
  },
  {
    id: "SHOT-POOL-FALL-3",
    title: "Lane 3",
    beat: "Scrub the right waterfall. Pink plug stays.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-POOL-FALL-3.jpg",
    video: "/movies/SHOT-POOL-FALL-3.mp4",
    kind: "shot",
    chapter: "Pool",
  },
  {
    id: "SHOT-POOL-PULL",
    title: "Plug",
    beat: "Pull the pink obstruction from the seahorse.",
    duration: "6s",
    status: "ready",
    still: "/stills/SHOT-POOL-PULL.jpg",
    video: "/movies/SHOT-POOL-PULL.mp4",
    kind: "shot",
    chapter: "Pool",
  },
];
