from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess
from PIL import Image
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/vector/job_geology_teacher_refinement_v1_20261001'
report=r/'audit/job_source_review_nursery_teacher_geology_v1_20261001'
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(r).as_posix()
second=read(out/'ATTEMPT02_PROVENANCE.json')
evaluations=['Warm clay values now keep the fossil as one rounded stone instead of stacked purple color stripes. The shallow large spiral remains intact, the restrained bottom shadow and clear contour support the toy-prop language, and the broad highlight stays in one calm cluster. Native-source drafting floor4.5; brush contact, reveal, mount and complete action remain pending.','The three familiar colored strata and two mineral dots stay clear. Subtle broad values make the rounded stone less diagram-flat without adding speckling or changing the educational color groups. The outer contour remains controlled for the intended128px prop. Native-source drafting floor4.5; a rock image still cannot prove panning or a meaningful excavation sequence.','The broader attached supports now read as small sturdy toy-board legs instead of bent wires. The warm rim, grouped lavender base value and exact six non-text lesson shapes stay calm and readable. Native-source drafting floor4.5; current190px mounting and every PATTERN/COUNT/ADD/MATCH input/action/result/return remain unreviewed.']
items=[]
for x,evaluation in zip(second['items'],evaluations):
 assert sha(r/x['path'])==x['sha256'];preview=out/(Path(x['path']).stem+'_native.png')
 q=dict(x);q.update(status='SOURCE_FLOOR_MET_UNBOUND_CONTEXT_PENDING',source_score=4.5,evaluation=evaluation,direct_full_native_review=True,preview_path=rel(preview),preview_sha256=sha(preview),mounted_score=None,complete_action_score=None);items.append(q)
write(out/'ATTEMPT02_REVIEW.json',dict(status='ALL3_SECOND_NATIVE_VECTOR_DRAFTS_DIRECTLY_REVIEWED_SOURCE_FLOOR_MET',checked_utc=now,items=items,qualification='Every complete256x256 second native raster directly inspected. Source-only4.5; no new current game binding or mounted/action/device/child/owner acceptance.'))
first=read(out/'ATTEMPT01_REVIEW.json')
selected=items+first['items'][3:]
write(out/'SELECTED_SOURCES_V1.json',dict(status='FIVE_UNBOUND_REPLACEMENT_SOURCES_MEET4_5_DRAFT_FLOOR',checked_utc=now,items=selected,all_source_scores_at_least_4_5=True,runtime_integration=False,mounted_acceptance=False,whole_job_action_acceptance=False,owner_approval=None,qualification='Five replacement source files are available separately. Three earlier4.4 drafts remain preserved and individually evaluated. Current original game vectors remain bound; source acceptance does not repair or pass their actual interactions.'))
shutil.copyfile(Path(__file__),out/'executed_record_attempt02_and_register_v76.py')
style='body{background:#edf4fa;color:#26304b;font:17px/1.5 system-ui;margin:0}main{max-width:1320px;margin:auto;padding:24px}header,article{background:white;border-radius:16px;padding:20px;margin-bottom:18px}h1,h2{line-height:1.25}a{color:#504096}img{display:block;width:256px;max-width:100%;height:auto;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:18px}.grid article{min-width:0}.image{background:#d0f0f1;border-radius:10px;padding:12px}.score{font-weight:bold}code,small{display:block;overflow-wrap:anywhere}'
cards=''.join(f'<article id="{x["id"]}"><h2>{html.escape(x["id"])}</h2><figure class="image"><img loading="lazy" src="{Path(x["preview_path"]).name}" alt="Complete native vector candidate {html.escape(x["id"])}"></figure><p class="score">Source {x["source_score"]}/5 · attempt {x["attempt"]} · mounted/action pending</p><p>{html.escape(x["evaluation"])}</p><p><a href="{Path(x["path"]).name}">Original SVG candidate</a></p><small>{x["sha256"]}</small></article>' for x in items+first['items'])
(out/'index.html').write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Teacher and geology reversible vector refinements</title><style>{style}</style><main><header><a href="../../../audit/job_review_v2_20261001/index.html">Current audit entry</a><h1>Teacher and geology: reversible vector refinements</h1><p>Five selected replacement sources meet the 4.5/5 drafting floor. The original world/UI symbols scored4.0–4.4; all originals and actual game bindings stay preserved. Three first drafts at4.4 remain in the history below.</p><p><a href="SELECTED_SOURCES_V1.json">Five selected files and exact source provenance</a> · <a href="ATTEMPT01_REVIEW.json">First-attempt evaluations</a> · <a href="ATTEMPT02_REVIEW.json">Second-attempt evaluations</a> · <a href="../../../audit/job_source_review_nursery_teacher_geology_v1_20261001/index.html">Current original art and individual reviews</a></p><p>Source artwork only: current game-size mounting, semantic action/contact, full training/story sequences and owner acceptance remain open.</p></header><div class="grid">{cards}</div></main></html>',encoding='utf-8',newline='\n')
sources=read(report/'REVIEW.json');pillows=next(x for x in sources['sources'] if x['path'].endswith('/pillows.png'));image=Image.open(r/pillows['path'])
for i,x in enumerate(sources['source_object_regions']):
 px=6+i*203;width=203 if i<4 else 202;region=[px,115,width,117];preview=report/(x['id'].lower()+'.png');image.crop((px,115,px+width,232)).save(preview)
 x.update(region=region,source_dimensions=list(image.size),preview_path=rel(preview),preview_sha256=sha(preview),region_qualification='Exact non-overlapping native audit extraction inside the actual runtime strip6,115,1014,117. These five audit rectangles do not invent individual runtime UV bindings.')
write(report/'REVIEW.json',sources)
s=(report/'index.html').read_text(encoding='utf-8')
for x in sources['sources']+sources['source_object_regions']:
 s=s.replace('<article><h2>'+x['id']+'</h2>','<article id="'+x['id']+'"><h2>'+x['id']+'</h2>')
for x in sources['source_object_regions']:
 s=s.replace('<h2>'+x['id']+'</h2>','<h2>'+x['id']+'</h2><figure class="image"><img loading="lazy" src="'+Path(x['preview_path']).name+'" alt="Exact native individual '+x['id']+'"></figure>')
s=s.replace('</header>','<p><a href="../../assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html">Five reversible source-floor replacements and preserved rejected drafts</a></p></header>',1)
(report/'index.html').write_text(s,encoding='utf-8',newline='\n')
license=r/'ASSET_LICENSES.md';text=license.read_text(encoding='utf-8')
for x in sources['source_object_regions']:
 p=r/x['preview_path']
 if f'`{x["preview_path"]}`' not in text:text+=f'\n| `{x["preview_path"]}` | Exact native audit crop of `{x["source_path"]}`, source SHA-256 `{x["source_sha256"]}`, region `{x["region"]}`. | Project original, all rights reserved; selected ImageGen attempt03 provenance retained. | Internal individual source review, 2026-10-01. | Non-overlapping audit-only extraction, no scaling/source repair or invented runtime binding; source-only4.6. |\n'
license.write_text(text,encoding='utf-8',newline='\n')
builder=r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v11.py';s=builder.read_text(encoding='utf-8')
needle="for q in items.values():\n p=q['path']\n if p not in hashes:";assert s.count(needle)==1
addition="""# Newly direct current nursery/teacher/geology opinions and exact source-object regions.
ntg=read('audit/job_source_review_nursery_teacher_geology_v1_20261001/REVIEW.json')
for x in ntg['sources']:
 q=items[x['path']];q['earlier_written_evaluation']=q['evaluation'];q['latest_source_score']=x['source_score'];q['latest_source_sha256']=x['sha256'];q['evaluation']=x['evaluation'];q['source_qualification']=x['qualification'];q['preview_path']='audit/job_source_review_nursery_teacher_geology_v1_20261001/'+x['preview_paths'][-1];q['latest_refinement']=dict(report='audit/job_source_review_nursery_teacher_geology_v1_20261001/index.html',note='Seven current sources directly inspected; nursery art4.6, original vectors4.0–4.4. Five separately named source-floor replacements are unbound; complete interactions remain open.')
for x in ntg['source_object_regions']:
 items[x['id']]=dict(id=x['id'],aliases=[],kind='source object region',path=x['source_path'],region=x['region'],source_dimensions=x['source_dimensions'],earlier_sha256=x['source_sha256'],historical_source_score=x['source_score'],evaluation=x['evaluation'],refinement='Current exact strip is loaded in the nursery catch surface. Review full-body connection, catching/settling contact and actual safe return; source-only4.6 is not action acceptance.',families=['Nursery catching','Individual cushion source object'],original_reports=['audit/job_source_review_nursery_teacher_geology_v1_20261001/index.html#'+x['id']],source_qualification=x['region_qualification'],preview_path=x['preview_path'],native_reference_observations=[])
for filename in ['ATTEMPT01_REVIEW.json','ATTEMPT02_REVIEW.json']:
 for x in read('assets_src/vector/job_geology_teacher_refinement_v1_20261001/'+filename)['items']:
  p=x['path'];items[p]=dict(id=x['id'],aliases=[],kind='source',path=p,source_dimensions=x['dimensions'],earlier_sha256=x['sha256'],historical_source_score=x['source_score'],evaluation=x['evaluation'],refinement='Preserve original vector/binding and failed first draft. Native-source floor is separate from actual world/UI mounting, input contact/consequence, full training/story timeline and owner acceptance.',families=['Teacher or geology','Reversible code-native vector source'],original_reports=['assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html#'+x['id']],source_qualification=x['qualification'],preview_path=x['preview_path'],native_reference_observations=[],runtime_binding_state=x['status'])
"""
s=s.replace(needle,addition+needle)
s=s.replace("registered_items=len(rows),","individual_source_object_regions=sum(q['kind']=='source object region' for q in rows),registered_items=len(rows),")
s=s.replace('328 individually catalogued pose cells and 38 prop regions','328 individually catalogued pose cells, 38 runtime prop regions and 5 source-object regions')
s=s.replace('build_current_job_item_register_v11.py','build_current_job_item_register_v12.py')
insert="html=html.replace('${c.additional_runtime_prop_regions} prop regions = ${c.registered_items}', '${c.additional_runtime_prop_regions} runtime prop regions + ${c.individual_source_object_regions} source object regions = ${c.registered_items}')\n"
s=s.replace("(out/'all_items.html').write_text(html,",insert+"(out/'all_items.html').write_text(html,",1)
new=r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v12.py';new.write_text(s,encoding='utf-8',newline='\n')
proc=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(new)],cwd=r,capture_output=True,text=True,encoding='utf-8');assert proc.returncode==0,proc.stderr
counts=read(r/'audit/job_artwork_refinement_live/ALL_ITEMS.json')['counts'];assert counts['registered_items']==1532 and counts['unique_source_files']==1161 and counts['inclusive_current_source_priorities']==571 and counts['unreviewed_current_source']==388
for p in [r/'audit/MASTER_AUDIT_2026-08-09.md',r/'design/05_DOC_LEDGER.md',r/'audit/job_review_v2_20261001/index.html',r/'audit/job_artwork_refinement_live/index.html']:
 s=p.read_text(encoding='utf-8');s=s.replace('1519 entries','1532 entries').replace('1153 source files','1161 source files').replace('558 inclusive source priorities','571 inclusive source priorities').replace('395 unassigned source opinions','388 unassigned source opinions').replace('Search 1,519 known','Search 1,532 known').replace('contains 558 source priorities','contains 571 source priorities').replace('and395 unassigned current source opinions','and 388 unassigned current source opinions').replace('catalogues 1153 source files','catalogues 1161 source files')
 if p.suffix=='.html' and 'Current nursery/teacher/geology sources' not in s:
  s=s.replace('</main>','<section><h2>Current nursery/teacher/geology sources</h2><p><a href="../job_source_review_nursery_teacher_geology_v1_20261001/index.html">Seven current sources and five individual cushions</a> · <a href="../../assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html">Five reversible vector replacements at source-only4.5</a>.</p><p>Eight vector drafts are preserved: three rejected first drafts and five selected source floors. Original vectors remain bound and complete world/UI/action acceptance remains open. The known register now has1532 entries:1161 source files,328 pose cells,38 runtime prop regions and5 source-object regions;571 inclusive source priorities and388 unassigned source opinions.</p></section></main>',1)
 if p.name=='MASTER_AUDIT_2026-08-09.md' and 'Current nursery/teacher/geology direct review' not in s:s+='\nCurrent nursery/teacher/geology direct review (2026-10-01): [seven current sources and five individually illustrated cushions](job_source_review_nursery_teacher_geology_v1_20261001/index.html) retain nursery source4.6 and identify five vector source priorities4.0–4.4. [Five reversible vector replacement sources](../assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html) meet source-only4.5 after three first drafts at4.4 were preserved. Register1532 =1161 source files +328 pose cells +38 runtime prop regions +5 source-object regions;571 inclusive priorities and388 unassigned source opinions. Current originals/bindings, complete interaction/training/story/device/child/owner acceptance and finding lifecycles remain unchanged. [Impact](../design/audit_impacts/job-nursery-teacher-geology-native-review-20261001.json).\n'
 p.write_text(s,encoding='utf-8',newline='\n')
recordfile=r/'design/audit_impacts/job-nursery-teacher-geology-native-review-20261001.json';record=read(recordfile)
record['files']=sorted(set(record['files'])|{rel(p) for p in out.rglob('*') if p.is_file()}|{rel(p) for p in report.rglob('*') if p.is_file()}|{rel(new),'audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v12.py','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/all_items.html','audit/job_artwork_refinement_live/STATUS.json','design/audit_impacts/job-review-separate-v2-20261001.json'})
record['validation'].append(dict(command='Direct full native second-source review and source-floor selection',result='PASS',evidence=rel(out/'SELECTED_SOURCES_V1.json')+'; five source-only4.5 files, no actual runtime/mount/action acceptance.'))
record['acceptance_gaps']='Seven current exact source reviews and five cushions complete; five vector source floors4.5 unbound. Current actual world/UI mount, source-to-object semantics, every training/story action/contact/consequence/return and device/child/owner/cinematic/whole-game acceptance remain open.';write(recordfile,record)
allow=r/'tmp/v2_preview_allowed.json';d=read(allow);paths={rel(p) for f in [report,out] for p in f.rglob('*') if p.is_file()}|{rel(new),'audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v12.py'}
if isinstance(d,list):d=sorted(set(d)|paths)
else:
 key=next(k for k,v in d.items() if isinstance(v,list));d[key]=sorted(set(d[key])|paths)
write(allow,d);print(json.dumps(dict(counts=counts,selected_source_files=5,selected_source_floor=4.5,runtime_integration=False)))
