from pathlib import Path
import json,hashlib,html,datetime,shutil
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');parent=b/'audit/job_pan_painted_mount_v3_20261001';out=parent/'attempt_04'
def rel(p):return p.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();rows=[]
for v0 in json.loads((out/'native_views/CAPTURE_RECEIPT.json').read_text())['views']:
 v=dict(v0);p=out/'native_views'/v['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==v['sha256'];inv=v['state']=='invitation';partial=v['state']=='partial_panning_reversals'
 v.update(archive_path=rel(p),direct_native_review=True,reviewed_utc=now,scores=dict(object_finish=4.6,object_geometry=4.6,object_semantics=4.6,slab_finish=4.6 if inv else None,slab_geometry=4.6,invitation_support=4.5 if inv else None,grain_finish=4.6 if not inv else None,grain_containment=4.6 if not inv else None,mineral_finish=4.6 if partial else None,mineral_containment=4.6 if partial else None,mineral_water_contact=4.5 if partial else None,scene_style=4.4,actor_work_contact=2.7 if not inv else None,complete_action=None),evaluation='The intact oval pan now sits over the intact small cream/lavender slab instead of leaving the earlier gap. Isolated invitation contact reaches provisional4.5; parent halo and slight invitation bob still require naturally timed review.' if inv else 'Pan/slab maintain authored ratios4.6. New15px grain sprites show broad honey/cream/plum values4.6 with every visible grain inside the water4.6. Roshan remains remote from the pan2.7; no connected-action pass.' ,qualification='Direct individual unmodified Godot4.7.2 Mobile native desktop capture at1280/1600. Only changed painted lane captured after measured contact correction; compare earlier original/literal lanes through their retained galleries. Three inherited reversals, no completion/award/save, ordinary route or device/child/owner approval.',owner_acceptance=None,production_binding_changed=False)
 if partial:v['evaluation']+=' The whole painted mineral cluster remains in the basin4.6; a restrained contact ellipse now overlaps its base and reaches provisional static water contact4.5. Naturally timed reveal, underwater depth and full action remain open.'
 v['priority_dimensions']=[k for k,x in v['scores'].items() if x is not None and x<=4.5];rows.append(v)
assert len(rows)==6;review=dict(schema='reef.individual-native-graphics-review.v1',status='6_OF6_CHANGED_PAINTED_VIEWS_DIRECTLY_REVIEWED_ACTION_OPEN',native_views=6,directly_reviewed=6,views=rows,reviewed_utc=now,qualification='Source and isolated finish4.6; selected static contacts4.5 provisional. Inclusive priority rule still retains4.5. Actor contact2.7, complete route, native room coverage, target device/child/owner/final report remain open.');write(out/'REVIEW.json',review);shutil.copyfile(__file__,out/'executed_record_pan_final_review_v122.py')
styles='<style>body{background:#eef5f4;color:#302949;font:17px/1.5 system-ui;max-width:1500px;margin:auto;padding:24px}article{background:white;padding:20px;margin:28px 0}img{width:100%;height:auto}small{display:block}a{color:#4850a7}</style>'
cards=[]
for v in rows:cards.append('<article id="'+v['id']+'"><h2>'+v['id']+'</h2><img src="native_views/'+v['path']+'" alt="'+v['id']+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+' '+str(x)+'/5' for k,x in v['scores'].items() if x is not None))+'</p><small>'+html.escape(v['qualification'])+'</small></article>')
(out/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Pan final changed contact study</title>'+styles+'<h1>Pan contact study — every6 changed native view</h1><p>6/6 directly reviewed. Intact source/ratios/grains/mineral finish4.6; static invitation/water contact4.5 provisional. Connected Roshan action2.7 and complete routes remain open.</p><p><a href="REVIEW.json">All individual scores/hashes</a> · <a href="PROCESS_RECEIPT.json">Machine receipt</a> · <a href="../index.html">Complete iteration library</a></p>'+''.join(cards),encoding='utf-8')
allrows=[]
for folder in [parent,parent/'attempt_02',parent/'attempt_03',out]:allrows.extend(json.loads((folder/'REVIEW.json').read_text())['views'])
assert len(allrows)==60;write(parent/'ALL_NATIVE_REVIEWS.json',dict(status='60_OF60_DIRECT_NATIVE_PAN_VIEWS_REVIEWED',native_views=60,directly_reviewed=60,views=allrows,current_final_report=rel(out/'REVIEW.json'),all_teacher_geology_pan_native_views=280,qualification='Includes all failed/unimproved original/literal/painted variants, not60 accepted objects. Source/isolated scores do not pass acting, native room resolution, complete routes or owner report.'))
shutil.copyfile(parent/'index.html',parent/'initial_review.html')
(parent/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Painted pan iterative audit — all60 views</title>'+styles+'<h1>Painted pan — all60 native iteration views</h1><p>Every image directly reviewed. Current pan/slab/grain/mineral source and visible material4.6. Final isolated invitation and mineral-water contact4.5 provisional. The earlier hidden support, distorted pan, flat grains and displaced contact remain inspectable; none are overwritten. Roshan hands remain disconnected2.7. Room is1672x941 reference-only, not runtime-ready. No complete panning, ordinary training/story, device/child/owner or comprehensive final approval.</p><p><a href="attempt_04/index.html">Current6 corrected painted views</a> · <a href="initial_review.html">Initial18 aspect/containment views</a> · <a href="attempt_02/index.html">18 painted-grain/hidden-support views</a> · <a href="attempt_03/index.html">18 visible-support/displaced-contact views</a> · <a href="ALL_NATIVE_REVIEWS.json">All60 individual scores and hashes</a></p><img src="attempt_04/native_views/geologist_1280_pan_partial_panning_reversals_painted_staging.webp" alt="Current painted panning partial action"><p><a href="../../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html">All15 preserved source originals and their reviews</a></p>',encoding='utf-8')
license=b/'ASSET_LICENSES.md';existing=license.read_text()
with license.open('a',encoding='utf-8',newline='\n') as f:
 for v in rows:
  if v['archive_path'] not in existing:f.write('\n| `'+v['archive_path']+'` | Project-owned Godot4.7.2 Mobile native fixture; underlying art provenance retained | Internal review evidence | Unchanged complete viewport pixels, partial inherited input only; SHA256 '+v['sha256']+' |\n')
# Preserve executable dependency of the recorded wrapper along with its resolved logic.
shutil.copyfile(Path(__file__).parent/'capture_pan_support_v118.py',out/'capture_pan_support_v118.py')
shutil.copyfile(Path(__file__).parent/'record_pan_geometry_v113.py',parent/'record_pan_geometry_v113.py')
impact=b/'design/audit_impacts/job-pan-painted-placement-20261001.json';d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in parent.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Every60 native pan view directly inspected, including current6 changed views; total280 direct teacher/geology/pan comparisons',result='PASS',evidence=rel(parent/'ALL_NATIVE_REVIEWS.json')+'; scope is inspection, not overall action acceptance'));write(impact,d)
print('All60 pan views/280 total native comparisons individually reviewed; acting remains open')
