from pathlib import Path
import datetime, hashlib, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_river_bed_v1_20261002';f.mkdir(exist_ok=False);(f/'.gdignore').write_text('',encoding='utf-8')
refs=['assets/opera/worlds/geology/painted_work_v1_20261001/fossil_soil.png','assets/opera/worlds/geology/painted_work_v1_20261001/work_slab.png']
sha=lambda p:hashlib.sha256((b/p).read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
prompt='''Use case: illustration-story.
Asset type: one isolated broad top-down loose-earth excavation bed for the Mermaid Roshan geologist river game, transparent RGBA sprite.
Input image1: material/palette reference only (existing painted fossil soil); image2: broad painted value-band and plum/lavender style reference only (stone slab). Do not fit their silhouettes or copy their front faces. Generate a new complete raster illustration of the specifically missing wide earth bed.
Subject/composition: One continuous shallow patch of warm sandy loam seen directly from above. Broad approximately2:1 footprint, a gently irregular nearly-rectangular handmade silhouette with softly rounded corners. Keep the usable clear central soil area very broad, at least88% of its width and84% of its height; the game overlays a wide9-by5 excavation field. The whole object fills most of the horizontal canvas width, with its entire contour and a small transparent margin visible. Preserve the wide top-down aspect; no thick raised lip, front face, perspective tabletop, bowl or small oval.
Style: polished painted2D children's storybook toy playset. Rounded forms, calm broad ochre/cream painted value bands, restrained lavender contact/depth shadows and clean plum/brown authored contour. Specific visible earth material, a few rounded stones grouped only at the outside corners. Quiet central soil suitable for clear aqua river paths. Matte hand-painted finish; no photographic grain, PBR texture, shiny plastic, vector-flat fills, dense hatching or scattered fine speckles.
Do not paint water, channels, route lines, dug holes, fossils, crystals, grid, labels, symbols, UI frame, cards or lettering. No characters or tools. This is one physical ground prop, not a new room or scene. Transparent outside the complete object, preserve clean authored alpha. Nothing cropped off.'''
(f/'PROMPT_ATTEMPT_01.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
reuse={'baseline':'40b1c7bfe025f284507c586fea61b9dd76b61423','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'named_gap':'Flat procedural river workbed3.2 in every78 directly reviewed isolated native state; broad actual room remains separate2.8. Need top-down wide earth prop behind unchanged792x380 grid.', 'search_scope':['assets/opera','assets_src/imagegen','assets_src/concepts'],'search_terms':['soil','earth','excavation','river (excluding driver)'],'reviewed_reuse':[{'path':refs[0],'sha256':sha(refs[0]),'native_region':[72,171,881,684],'source_score':4.6,'limitation':'Good preserved soil source for fossil cover. Authored footprint1.288:1 at width930 becomes722high, extending outside playable surface; fitting height450 gives580wide, failing792wide grid. Stretching/erasing rim would materially fail authored geometry.'},{'path':refs[1],'sha256':sha(refs[1]),'native_region':[68,332,889,369],'source_score':4.6,'limitation':'Good preserved stone slab source for specimen tasks. At width930 height386 includes substantial front face. Putting all380 grid height on it moves the lower-row excavation onto the vertical face. It is not a top-down loose-earth field.'}],'generation_limit':'One new complete top-down wide ground prop only. Preserve original and every failed candidate. Uniform whole-canvas technical derivative only; no production binding, full-room2048native coverage or action/device/owner claim.'}
write(f/'REUSE_INVENTORY.json',reuse);write(f/'GENERATION_PENDING.json',{'attempt':1,'method':'BUILT_IN_IMAGEGEN','prompt_path':(f/'PROMPT_ATTEMPT_01.txt').relative_to(b).as_posix(),'prompt_sha256':sha((f/'PROMPT_ATTEMPT_01.txt').relative_to(b).as_posix()),'references':[{'path':p,'sha256':sha(p),'role':'MATERIAL_STYLE_ONLY_NOT_GEOMETRY'} for p in refs],'runtime_bound':False})
shutil.copyfile(__file__,f/Path(__file__).name)
write(b/'design/audit_impacts/job-geology-river-bed-source-20261002.json',{'id':'job-geology-river-bed-source-20261002','baseline':'40b1c7bfe025f284507c586fea61b9dd76b61423','scope':'Bounded fresh ImageGen top-down wide earth bed only after all78 native current river studies expose flatworkbed3.2. Existing fossil soil and specimen slab directly reviewed and their authored ratio/front-face failures recorded before generation. Preserve all original/native/prompt/reference hashes and derivatives. No production, room, actor, protected pixels, security, release or global acceptance.','rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-MOT-02','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08'],'findings':['MA-PLAY-004','MA-VIS-006'],'files':sorted(p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()),'validation':[{'command':'Reuse inventory and native78 workbed views','result':'PASS','evidence':'assets_src/imagegen/geologist_river_bed_v1_20261002/REUSE_INVENTORY.json;audit/job_river_join_study_v1_20261001/REVIEW_V4.json. Direct review4.6 reusable source materials; ratio/frontface failures justify only missing wide field.'}],'acceptance_gaps':'Fresh native source review, technical derivative, actual mounting/joins/contact/room/complete action/training/story/device/child/owner/all-job report remain pending.'})
print('One wide-earth named gap recorded; sources preserved, generation not yet acceptance.')
