from pathlib import Path
import datetime, hashlib, json, shutil, subprocess
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');s=b/'assets_src/imagegen/geologist_river_bed_v1_20261002';f=b/'audit/job_river_join_study_v1_20261001';a=s/'attempt_01';py='C:/Users/Peter/AppData/Local/Python/bin/python.exe'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
original=a/'native_generated.png';im=Image.open(original);assert im.size==(1774,887) and im.mode=='RGBA';alpha=im.getchannel('A');box=alpha.point(lambda v:255 if v>4 else 0).getbbox();assert box==(37,51,1739,833)
pending=read(s/'GENERATION_PENDING.json');write(a/'PROVENANCE.json',dict(native_path=original.relative_to(b).as_posix(),native_sha256=sha(original),native_dimensions=list(im.size),native_mode=im.mode,source_tool_path='C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-ab3e9761-2a21-4ff4-af3c-ba43d76d8ff6.png',source_tool_sha256=sha(original),method='BUILT_IN_IMAGEGEN_FRESH_ILLUSTRATION_STORY',attempt=1,prompt_path=pending['prompt_path'],prompt_sha256=pending['prompt_sha256'],references=pending['references'],used_as_runtime_pixels=False,pixel_repair=False,alpha_cleanup=False))
write(a/'REVIEW.json',dict(id='GEO-RIVER-BED-A01',native_path=original.relative_to(b).as_posix(),sha256=sha(original),source_dimensions=list(im.size),source_score=4.6,source_material_score=4.6,source_geometry_score=4.6,region=[37,51,1702,782],alpha_gt4_bbox=list(box),direct_review=True,original_preserved=True,runtime_bound=False,mounted_score=None,complete_action_score=None,owner_acceptance=None,evaluation='One complete broad2.176:1 top-down loam patch with clear quiet centre, softly irregular rounded outline and clustered exterior corner stones. Ochre/cream broad painted bands and lavender/plum edge match the preserved source family. Authored upper/lower/left/right contour is complete: dominant alpha stays35–54px from the native edges. Sparse tiny marks remain subordinate. Source4.6 only; actual grid and stones/ports must be inspected after mounting.',qualification='Direct complete generated native and exact preserved local1774x887 RGBA original inspected. Isolated ground prop, not full-room/background2048 coverage or production/complete-action/device/child/owner acceptance.',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat()))
ff='C:/Users/Peter/AppData/Local/Programs/MermaidReefTools/FFmpeg/8.1.2/bin/ffmpeg.exe';derivative=a/'whole_canvas_1024x512.png';assert not derivative.exists()
cmd=[ff,'-hide_banner','-loglevel','warning','-i',str(original),'-vf','scale=1024:512:flags=lanczos','-frames:v','1','-pix_fmt','rgba',str(derivative)];p=subprocess.run(cmd,cwd=b,capture_output=True,check=True)
(a/'normalization.stdout.log').write_bytes(p.stdout);(a/'normalization.stderr.log').write_bytes(p.stderr)
write(s/'TECHNICAL_DERIVATIVES.json',dict(status='COMPLETE_CANVAS_DERIVATIVE_DIRECT_REVIEW_PENDING',derivatives=[dict(path=derivative.relative_to(b).as_posix(),sha256=sha(derivative),source_path=original.relative_to(b).as_posix(),source_sha256=sha(original),dimensions=[1024,512],method='ONE_UNIFORM_COMPLETE_CANVAS_1774x887_TO1024x512_RGBA_LANCZOS',command=cmd,pixel_repair=False,alpha_cleanup=False,direct_review=False,source_score=None,runtime_bound=False)]))
# New version uses the full original-aspect canvas; actual inherited input remains intact.
target=f/'join_surface_v5.gd';assert not target.exists();code=(f/'join_surface_v4.gd').read_text(encoding='utf-8')
code=code.replace('var wet_circle: Texture2D','var wet_circle: Texture2D\nvar wide_earth: Texture2D')
code=code.replace('\tsuper._load_textures()','\tsuper._load_textures()\n\tvar soil_image := Image.load_from_file("res://assets_src/imagegen/geologist_river_bed_v1_20261002/attempt_01/whole_canvas_1024x512.png")\n\tassert(soil_image != null and soil_image.get_size() == Vector2i(1024,512))\n\twide_earth = ImageTexture.create_from_image(soil_image)',1)
needle='func _mask(cell: Vector2i) -> int:';code=code.replace(needle,'func _draw_work_surface() -> void:\n\t# Source-transparent full canvas, authored2:1 aspect, no flat panel below it.\n\tdraw_texture_rect(wide_earth,Rect2(Vector2(248.0,114.0),Vector2(1024.0,512.0)),false)\n\n'+needle)
target.write_text(code,encoding='utf-8',newline='\n')
target=f/'capture_join_study_v5.gd';assert not target.exists();target.write_text((f/'capture_join_study_v4.gd').read_text(encoding='utf-8').replace('/attempt_04/','/attempt_05/').replace('/join_surface_v4.gd','/join_surface_v5.gd'),encoding='utf-8',newline='\n')
target=f/'run_river_join_capture_v204.py';assert not target.exists();target.write_text((f/'run_river_join_capture_v200.py').read_text(encoding='utf-8').replace("out=f/'attempt_04'","out=f/'attempt_05'").replace('capture%dv4','capture%dv5').replace('river_join_%d_v200','river_join_%d_v204').replace('capture_join_study_v4.gd','capture_join_study_v5.gd'),encoding='utf-8',newline='\n')
write(f/'BED_MOUNT_V5.json',dict(status='ISOLATED_FULL_CANVAS_SOIL_MOUNT_PENDING',source_path=derivative.relative_to(b).as_posix(),source_sha256=sha(derivative),complete_canvas_rect=[248,114,1024,512],source_alpha_gt4_canvas_bbox=list(box),game_bbox=[248+37*1024/1774,114+51*512/887,1702*1024/1774,782*512/887],river_grid=[360,180,792,380],method='Whole complete2:1 raster at authored aspect; no crop, per-subject scaling, pixel repair, atlas extraction or warp. Fixed-grid placement unchanged.',qualification='One missing ground prop; source4.6 does not accept active path, depth, port continuity, actor or full-room/action/device/child/owner.'))
shutil.copyfile(__file__,s/Path(__file__).name)
# Paginated register shows every card immediately, reducing misleading pending lazy image state.
builder=b/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v23.py';code=builder.read_text(encoding='utf-8').replace('loading="lazy"','loading="eager"');builder.write_text(code,encoding='utf-8',newline='\n');shutil.copyfile(builder,b/'audit/job_artwork_refinement_live/review_tools'/builder.name)
subprocess.run([py,'-X','utf8','-B',str(builder)],cwd=b,check=True)
for name,folder in [('job-geology-river-join-study-20261001',f),('job-geology-river-bed-source-20261002',s)]:
 ip=b/('design/audit_impacts/'+name+'.json');d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in folder.rglob('*') if p.is_file()});write(ip,d)
print('Native source4.6 preserved;1024x512 derivative and new isolated bed mounting pending direct review.')
