"""Record the owner-directed V32 scope and exact source inputs before editing."""
from pathlib import Path
import hashlib, json, shutil
V=Path(__file__).resolve().parent; L=V.parents[1]; R=L.parents[2]
BASE='07734bb43018ffdefef3644f337db8fa46038d5b'
def save(p,q):p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='\n')
def rel(p):return p.resolve().relative_to(R.resolve()).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
V.mkdir(parents=True,exist_ok=True);(V/'art').mkdir(exist_ok=True)
if not (V/'BOOK_BASELINE.json').exists():shutil.copyfile(L/'book.json',V/'BOOK_BASELINE.json')
rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-06','DL-ASSET-08']
scope='Restore existing rainbow waterfall colors and explicit magical-pool dialogue; merge repeated rainbow Puff reflection/thanks/rest pages; reallocate one page to source-derived dusty-castle inspection; close with a quiet clean-room result, preserving both reveal turns and34 total pages.'
save(V/'REVISION_SCOPE.json',dict(baseline=BASE,date='2026-10-01',scope=scope,rules=rules,findings=[],no_findings_reason='Static picture-book owner clarification; no game/runtime/master-finding repair or closure.',owner_direction='The swimming pool makes water rainbow colored. Combine former31 with the other rainbow Puff page to free story space.',delivery=dict(repository='Ebonyks/mermaid-roshan-reef',branch='codex/mermaid-roshan-picture-book',access='Anonymous HTTPS at immutable Git revision'),evidence_required=['Native source/derivative/prompt hashes','Whole-contour alpha and low-bank measurements','Mapped before/after34-page proof','Exact original source preservation and PDF pixel/text checks','Independent current character/style/language review','Authority/coverage gates and remote anonymous byte verification'],acceptance='Internal editorial evidence does not establish owner/child/qualified SLP/physical-print or game-wide satisfaction.'))
atlas=L/'art/event_borders/attic_atlas.png';bank=L/'revisions/v29_polish/art/bank30_tiny.png';bunny=L.parent/'archive/rough_v5/art/grand_puff_jump_sheet.png';room=L/'revisions/v29_polish/art/table22.png';attic=R/'assets_src/cinematics/overnight_recut_repairs_2026-09-12/references/dusty_attic_arena_native_1254.png'
jobs=[
dict(id='dusty_chest',transparent=True,refs=[str(atlas)],prompt='Use case: background-extraction. Extract ONLY the complete dusty blue-and-gold chest at the upper right of the supplied atlas onto genuine transparent alpha. Preserve its exact rounded arched lid, navy contours, gold bands, central shell/pearl lock, blue painted wood and fluffy pale-lavender cobweb dust on the lid and edges. Remove ALL backing squares, diffuse background halos and every other atlas item. Keep the entire authored chest silhouette with a generous transparent margin; no chopped edges. Render clean native contours at generous resolution for a children\'s book, without redesigning the chest or changing its texture/style. No sticker rim, no text, no scene, no new props. One isolated existing object only.'),
dict(id='shell_cobweb',transparent=True,refs=[str(atlas)],prompt='Use case: background-extraction. Extract ONLY the complete upper-middle group of the supplied atlas: the pale spiral conch on the left and pale scallop shell on the right joined by the existing fine dusty cobweb. Preserve both whole shell silhouettes, their exact colors/navy contours and the connecting web geometry. Genuine transparent alpha everywhere behind and BETWEEN all fine web strands. Remove diffuse grey/background halos and all other atlas items. No rectangular plate, outline sticker rim, new symbols, new objects or scene. Crisp generous native resolution for a children\'s book, retaining the supplied painted texture and proportions.'),
dict(id='dirty_bank04',transparent=False,refs=[str(bank),str(bunny),str(attic)],prompt='Use case: precise-object-edit. IMAGE1 is the exact edit target: blue watercolor stationery with dotted borders and low dual mounds. Change ONLY the existing little object groups on the lower left and lower right banks. Keep the top85%, central38–62% void, frame size, blue wash, dots, bubbles, shells, mounds and all other pixels unchanged. Left bank: replace the two ring-playing bunnies and rings with ONE tiny canonical lavender curl-ear dust bunny peeking curiously beside a closed dusty castle book, nose tilted toward its dusty cover. IMAGE2 fixes bunny identity: two spiral ears with pearl joints, curled cloud body, pearl paws, large navy eyes; friendly curious rather than angry. Right bank: keep the small open castle book and curved shell lamp, but add very light cobweb dust across their own surfaces, echoing the dusty belongings in IMAGE3. No grey dust smear on the page, no brush, sponge, chest or separate web/shell group. Every visible new subject must begin below85% canvas height and be at most12% canvas width AND height, tucked into the slopes with subtle contact shadow and a little mound overlap. Small contextual bank performance, never large foreground mascots. No characters or props in the writing area. Clean crisp bubbles without codec noise. Same1484x1060 composition.'),
dict(id='clean_room30',transparent=False,refs=[str(room)],prompt='Use case: precise-object-edit. This supplied existing clean craft-room painting is the exact edit target, not a scene-design reference. Remove ONLY Roshan and the brush she is holding, filling their vacated contour-shaped area with a natural continuation of the already existing brick wall, floor tiles and clean tabletop. Keep every other pixel/composition feature unchanged: room architecture, all tables, rims, feet, shelves, sorted paint bottles/cups, ribbon rack, picture board, palette and lighting. Preserve the right tabletop as clean, no paint spill. The complete existing room becomes a quiet completion/status picture after the cleaning story; do not invent a new room, camera, action, people, props or photorealistic materials. Keep painted2D pastel/navy-contour book style and1484x1060 framing. No text. This is bounded character/held-prop removal and local gap filling, not full-scene redraw.')]
jobs.append(dict(id='dusty_chest_clean',transparent=True,refs=[str(V/'art/dusty_chest_attempt1.png')],prompt='Use case: background-extraction. Correct the transparency of this supplied chest cutout. Preserve the blue/gold dusty chest itself EXACTLY. Remove the entire soft grey/black/lavender haze surrounding it: that haze is unwanted backing, not dust, shadow or part of the object. Every pixel beyond the chest\'s actual contour and the tiny cobweb strands ATTACHED to it must have alpha ZERO, including above, below, sides and corners. The chest itself must be fully opaque, with only fine edge antialias transparency. Keep the contour-following dust attached to the lid; no diffuse cloud outside it. No drop shadow, luminous aura, gradient, black background, sticker outline or new scene. One complete cleanly isolated existing chest on genuine transparent alpha. Keep generous clear margins.'))
for j in jobs:
 j['reference_hashes']=[dict(path=rel(Path(p)),sha256=sha(Path(p))) for p in j['refs']]
 j['prompt_sha256']=hashlib.sha256(j['prompt'].encode()).hexdigest()
save(V/'generation_jobs.json',dict(jobs=jobs,reason='Existing atlas props have baked diffuse halos and insufficient large-page contours; the new early page needs a unique relevant low bank. Existing clean-room source depicts ongoing scrubbing, so bounded character/brush removal makes the closing status unambiguous. Rainbow source, character cutouts, door, covers and other scenes are reused.'))
impact=R/'design/audit_impacts/picture-book-rainbow-story-v32-20261001.json'
save(impact,dict(id='picture-book-rainbow-story-v32-20261001',scope=scope,baseline=BASE,rules=rules,findings=[],no_findings_reason='Owner-directed static-book refinement; no canonical game finding changes.',files=sorted(rel(p) for p in V.rglob('*') if p.is_file()),validation=[dict(command='Mapped native visual review and source/PDF export checks',result='PENDING',evidence=rel(V/'REVISION_SCOPE.json'))],acceptance_gaps='Owner/child/qualified SLP/physical-print review remains separate. No game/runtime changes.'))
print(json.dumps(dict(baseline=BASE,jobs=len(jobs),scope_record=rel(V/'REVISION_SCOPE.json'))))
