from pathlib import Path
import datetime, hashlib, html, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f=b/'audit/job_geode_coherent_pilot_v1_20261002'; prefix=f.relative_to(b).as_posix()
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat();bt=chr(96)
frames=[];boards=[];names=['closed prepared seam','early crack','quarter opening','new bridging opening','half opening','three-quarter opening','fully open cavities']
for width in [1280,1600]:
 m=read(f/f'BOARD_MANIFEST_{width}.json')
 for x in m['frames']:
  x=dict(x);assert sha(b/x['path'])==x['sha256'];n=x['index'];state=x['authored_state']
  x.update(direct_review=True,native_detail_review=n in [31,32,41,42],owner_acceptance=None)
  x['review_method']='Every native frame inspected once on a complete ordered board, row-major; frames31/32/41/42 additionally inspected at native resolution at both widths.'
  x['scores']=dict(geode_material=4.6,embedded_crystal_semantics=4.6,cutout_edges=4.5,geode_opening=4.5,working_hand_contact=2.7 if n<92 else None,celebration_transition=4.0 if 92<=n<112 else None,production_exit=None)
  x['evaluation']=names[state].capitalize()+'. Two separately readable stone cavities retain rooted crystal clusters; no loose crystal reward sprites. The authored state preserves aspect with a fixed350px height and planted base.'
  if n in [32,42]:x['evaluation']+=' Native threshold detail: the bridging/half state advances the cavity reveal without the former full-state vertical drop. The half-state reveal still changes width by about53 canvas pixels; accepted only at the provisional4.5 floor, with room for refinement.'
  if n>=112:x['evaluation']+=' Empty-callback fixture tail only; no actual room/castle/story return is exercised or scored.'
  elif n>=92:x['evaluation']+=' Roshan is visible through the clap, but her abrupt working-to-clap change remains4.0.'
  else:x['evaluation']+=' Roshan remains away from the elevated geode, hands at the lower-left floor; contact remains2.7.'
  x['priority']=True;frames.append(x)
 for x in m['boards']:
  x=dict(x);assert sha(b/x['path'])==x['sha256'];x.update(direct_review=True,review_method='Every cell directly inspected in row-major order; complete12-frame board.');boards.append(x)
assert len(frames)==312 and len(boards)==26
selected=read(b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/SELECTED_PILOT_STATES.json')
states=[]
for x in selected['states']:
 x=dict(x);x['sha256']=sha(b/x['path']);x.update(mounted_score=4.5,material_score=4.6,owner_acceptance=None,priority=True)
 x['evaluation']=names[x['index']].capitalize()+': authored contour and mineral palette fit the painted props; crystals remain inside the shells. Minor fringe and discrete state change keep this at the inclusive4.5 refinement boundary.'
 states.append(x)
r=dict(schema='reef.coherent-geode-pilot-review.v1',reviewed_utc=now,baseline='40b1c7bfe025f284507c586fea61b9dd76b61423',status='UNBOUND_7_STATE_PILOT_PROVISIONAL_OPENING4.5',states=states,frames=frames,boards=boards,counts=dict(native_frames=312,ordered_boards=26,native_threshold_details=8,authored_states=7),scores=dict(geode_opening=4.5,geode_material=4.6,embedded_crystal_semantics=4.6,edges=4.5,room=2.8,working_hand_contact=2.7,celebration_transition=4.0,production_exit=None),scripts=[dict(path=prefix+'/study_surface.gd',sha256=sha(f/'study_surface.gd')),dict(path=prefix+'/capture.gd',sha256=sha(f/'capture.gd')),dict(path='scripts/opera_geology_surface.gd',sha256=sha(b/'scripts/opera_geology_surface.gd'))],qualification='Non-runtime seven-state pilot inherits production input/progress/save and ordinary earned four-phase advancement after initial surface rebind. Every312 frame inspected on26 boards,8 native details; no interpolation, morphing or pixel cleanup. Discrete authored-state gameplay is not cinematic delivery. Readback slows timing; empty completion callback does not exercise actual production exit. Current production still uses earlier four-state geode with continuous opening4.2; this unbound pilot does not override that score. Device, child, owner, actual-route/training/story and all-job acceptance remain open.',current_production_machine_evidence=dict(path='audit/job_geology_river_runtime_v1_20261002/full_ci_v1/RECEIPT.json',qualification='Full unmodified suite82/82,362 source bytes unchanged,57 raw diagnostics retained. This pass applies only to the frozen current production source; no inherited full-suite or creative acceptance for pilot or future binding.'))
write(f/'REVIEW.json',r);esc=html.escape
bc=''.join('<figure><a href="../../'+esc(x['path'])+'"><img src="../../'+esc(x['path'])+'" alt="'+str(x['width'])+' frames '+str(x['first_frame'])+'–'+str(x['last_frame'])+'"></a><figcaption>'+str(x['width'])+' · frames '+str(x['first_frame'])+'–'+str(x['last_frame'])+' · every12 cells inspected<small>'+x['sha256']+'</small></figcaption></figure>' for x in boards)
fc=''.join('<article><a href="../../'+esc(x['path'])+'">'+str(x['width'])+' frame '+str(x['index'])+'</a><p>'+esc(x['evaluation'])+'</p><small>'+esc(json.dumps(x['scores']))+' · '+x['sha256']+'</small></article>' for x in frames)
sc=''.join('<article><b>State '+str(x['index'])+': '+names[x['index']]+' — '+str(x['mounted_score'])+'/5</b><p>'+esc(x['evaluation'])+'</p><small>'+esc(x['source_id'])+' · '+x['sha256']+'</small></article>' for x in states)
(f/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seven-state geode opening pilot</title><style>body{margin:0;background:#eef4fa;color:#25304a;font:17px/1.5 system-ui}main{max-width:1460px;margin:auto;padding:24px}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,600px),1fr));gap:18px}figure,article{background:white;padding:18px;border-radius:14px;margin:0;min-width:0}img{width:100%;height:auto;display:block}small{font-size:12px;overflow-wrap:anywhere;display:block}.frames{grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}</style><main><a href="../job_artwork_refinement_live/index.html">All-job review library</a><h1>The geode opens to reveal crystals inside</h1><p>Unbound seven-state pilot: opening4.5/5 provisional, material and embedded-crystal semantics4.6. A stable base, preserved proportions and intermediate authored paintings improve the former4.2 opening. Minor fringe and the discrete half-state width change remain at the inclusive refinement boundary.</p><p>Every312 native frame is displayed once on26 ordered boards; every cell inspected, plus8 native transition details. Each frame has a written evaluation below. Room2.8, hands away from the work2.7 and abrupt clap transition4.0 remain separate priorities.</p><p>This pilot inherits actual input and ordinary four-phase advancement. Readback slows timing. The empty-callback tail does not exercise the real return. Current production retains the earlier four-state geode; no actual-production, device, child, owner or all-job acceptance is claimed.</p><p><a href="REVIEW.json">Complete review and hashes</a> · <a href="../../assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/index.html">All sources, rejected generations and individual cutouts</a> · <a href="../job_geology_river_runtime_v1_20261002/timed.html">Earlier actual production opening4.2</a></p><section class="frames">'+sc+'</section><h2>Every ordered frame</h2><section>'+bc+'</section><h2>Individual evaluations and native images</h2><section class="frames">'+fc+'</section></main></html>',encoding='utf-8',newline='\n')
note='Seven-state geode pilot continuation (2026-10-02): [every312 pilot frames on26 complete boards, plus8 native threshold details]({link}) directly inspected. Seven individual mounted states/continuous opening4.5 provisional, material/rooted crystals4.6; stable base and preserved proportions improve the earlier actual opening4.2. Minor fringe/discrete reveal remains at the inclusive refinement threshold. This pilot is unbound; current production retains its four-state geode. Room2.8/contact2.7/clap transition4.0 remain priorities. Separately the current painted-river production completes the unmodified full officialGodot4.7.2 suite82/82 with362 unchanged literal source hashes and57 raw diagnostics retained. That machine result applies only to its frozen production, not this pilot or a future binding. Training/story/actual return/device/child/owner/all-job acceptance and finding lifecycle remain open.'
p=b/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');at=s.index('\n')+1;s=s[:at]+'\n'+note.format(link='job_geode_coherent_pilot_v1_20261002/index.html')+'\n'+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=p.read_text(encoding='utf-8');at=s.index('\n## ',s.index('## MA-PLAY-004')+len('## MA-PLAY-004'));s=s[:at]+'\n'+note.format(link='../job_geode_coherent_pilot_v1_20261002/index.html')+'\n'+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s+='\n| '+bt+prefix+'/index.html'+bt+' | 🟣 | '+bt+'CANDIDATE'+bt+'; every312 non-runtime pilot frames directly reviewed on26 boards plus8 native details; seven mounted states/opening4.5 provisional, rooted semantics/material4.6, room2.8/contact2.7/clap4.0 remain separate. Current actual geode4.2 remains unchanged. No actual-production/device/child/owner/global acceptance. |\n';p.write_text(s,encoding='utf-8',newline='\n')
for rel in ['audit/job_artwork_refinement_live/index.html','assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/index.html','audit/job_geology_river_runtime_v1_20261002/index.html']:
 p=b/rel;s=p.read_text(encoding='utf-8');link='../../'+prefix+'/index.html' if rel.startswith('audit/') else '../../../'+prefix+'/index.html'
 reg='all_items.html' if rel=='audit/job_artwork_refinement_live/index.html' else ('../job_artwork_refinement_live/all_items.html' if rel.startswith('audit/') else '../../../audit/job_artwork_refinement_live/all_items.html')
 at=s.index('<main>')+len('<main>');s=s[:at]+'<section><p><a href="'+link+'">Seven-state geode pilot: all312 frames, provisional opening4.5</a>. Unbound; current actual geode opening4.2 retained. <a href="'+reg+'">Current registerV27:1712 entries,666 inclusive priorities,388 unassigned</a>.</p></section>'+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n### Seven-state geode pilot frame evidence (2026-10-02)\n\n'
for x in frames+boards:
 if x['path'] not in s:s+='| '+bt+x['path']+bt+' | Godot4.7.2 Mobile non-runtime capture of licensed project art and identified ImageGen geode sheets | Project review evidence; original source provenance retained | '+bt+prefix+'/REVIEW.json'+bt+' | '+('Complete12-frame ordered board by uniform whole-scene ffmpeg downscale and tiling; no delivery art' if 'first_frame' in x else 'Native lossless WebP viewport capture')+'; SHA256 '+x['sha256']+' |\n'
p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/index.html','audit/job_geology_river_runtime_v1_20261002/index.html','assets_src/imagegen/geologist_geode_coherent_states_v1_20261002/index.html'})
d['validation'].append(dict(command='Every312 non-runtime pilot frames on26 boards plus8 native transition details',result='PASS',evidence=prefix+'/REVIEW.json; bounded provisional opening4.5, no actual-production or owner acceptance.'));write(ip,d)
p=b/'tmp/v2_preview_allowed.json';write(p,sorted(set(read(p))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}))
print('312 pilot evaluations,26 boards,8 native details,7 states; unbound opening4.5 provisional. Current actual4.2 preserved.')
