from pathlib import Path
import datetime, hashlib, html, json, os, re, shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'audit/job_shared_background_review_v1_20261003'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
    t=p.with_name(p.name+'.v564_next');t.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n');t.replace(p)
data={}
def opinion(num,score,evaluation,refinement):data[f'D2X-{num:04d}']=(score,evaluation,refinement)
kitchen=[
(4.5,'Rounded lavender stone, cream arches and a readable shell window fit the painted world. The lamp is very bright and the shelf gathers several small glossy accents.','Reuse the architecture; review lamp emphasis and small shelf decorations with the child and active cards in the actual room.'),
(4.6,'The broad cream hood and oversized shell crest have coherent painted bands and a clear toy silhouette; the quiet lower wall leaves useful figure contrast.','Reuse the same source. Preserve the hood and shell across the joined master; no novelty redraw.'),
(4.5,'The large column is readable, with consistent lavender bands. The shelf cluster and warm oven crown add detail and bright accents close together.','Check the native oven card ownership and shelf hierarchy in the real room; retain shared architecture and avoid repainting split objects tile by tile.'),
(4.5,'Rounded purple cooking pot, gold sconce and cream arches are coherent. Two warm highlights and shell clutter compete for attention within this crop.','Review the lamp/pot emphasis at mounted size; reuse the painted shapes and resolve any live-card duplication from actual ownership evidence.'),
(4.6,'The large teal cabinet and broad cream worktop read clearly, with useful pale value bands and rounded shell handles. There is space for action above the counter.','Reuse. Evaluate any worktop props as separately owned live cards, with current child/actor scale.'),
(4.6,'Quiet lavender wall and mint floor provide strong separation; the cabinet terminates naturally with the next tile. Broad material bands are restrained.','Reuse the unchanged pixels; preserve the complete counter and floor joins.'),
(4.5,'The oven has a clear rounded door, cream housing and shell emblem. Its baked presentation is attractive, but this source alone cannot prove correct interaction-card ownership.','Trace and capture the working oven over this background before claiming ownership/contact acceptance; preserve the painted design.'),
(4.4,'The kettle, mug, pearl bowl, coral and seaweed create a dense right-side cluster with many glossy accents. It is much more detailed than the quiet central work area.','Priority: simplify this local decorative cluster or isolate the intended live prop after inspecting actual room scale; reuse the stronger kettle/cabinet painting before any redesign.'),
(4.6,'Mint floor, broad curved grout and soft shell motifs remain low contrast. Cabinet feet and floor contact are coherent with the row above.','Reuse the continuous floor. Do not add an independent camera or tile-specific lighting repair.'),
(4.6,'The quiet aqua floor and broad shell arcs support child-readable foreground contrast without fine realistic grain.','Reuse exactly; keep the master floor motif continuous.'),
(4.6,'The pale floor light remains a broad painted band rather than sharp specular glare; shell spacing is coherent and restrained.','Reuse; check current actor/contact shadows separately.'),
(4.5,'Floor is coherent and low contrast. The large pot fragment at the top is a intentional continuation of the adjacent painting, but it adds a strong right-edge mass.','Review the complete plant/occlusion at mounted scale; retain its single identity across the adjacent tile.')]
for i,(s,e,f) in enumerate(kitchen,12):opinion(i,s,e,f)
opera=[
(4.5,'Cream shell column, lavender drapery and blue doorway form a coherent soft painted frame. Small brick/cloth details are finer than the large doorway cue.','Reuse architecture; check the complete source joins and live invitation scale.'),
(4.5,'Quiet central wall leaves useful space for the owned performance cards. The small stars and repeated brick pattern slightly weaken the broad-value treatment.','Retain quiet staging; assess pattern contrast behind the actual performers rather than adding more decoration.'),
(4.5,'The center-right wall matches its sibling palette and keeps a readable shell-drapery band, with repeated small stars/brick detail.','Reuse the joined wall and test actor/goal contrast in the actual stage.'),
(4.5,'Doorway, rounded shell column and drapery mirror the opposite side coherently. The crop has no independently invented boundary object.','Reuse the continuous painting and retain each doorway/column once.'),
(4.1,'The balcony is readable, but a row of irregular pale patches interrupts the painted lavender fascia between shell emblems. These look like unfinished surface cleanup.','Priority: locally repair the pale fascia remnants on the complete approved source, preserving the rail, shell emblems and boundary geometry.'),
(4.5,'Broad lavender stage front and quiet purple floor provide space for the actor. The surface is restrained but slightly dull compared with the brighter career family.','Review mounted actor contrast and stage contact; reuse until actual play demonstrates a material/readability gap.'),
(4.5,'The same broad stage lip and low-detail floor carry through the center-right tile with a readable boundary.','Reuse the continuous stage and verify current performer/support ownership separately.'),
(4.1,'The right balcony repeats the irregular pale fascia patches seen on the left; their sharp ragged edges spoil the otherwise soft shell/rail painting.','Priority: repair the same named local cleanup gap with the whole joined-source identity and geometry preserved.')]
for i,(s,e,f) in enumerate(opera,32):opinion(i,s,e,f)
source_notes={
40:(4.0,'Eight magic-book poses keep the pearl/shell support and useful cover/page stages, but cover mottling, thin grey contours and washed pages have less painted depth than the accepted career props.','Reuse the same book identity and truthful page topology; improve broad painted bands and major contour contrast, then audit each authored turn in motion.'),
41:(3.9,'The table is stable across eight poses, but its narrow grey outlines and largely uniform tabletop/pedestal bands feel flatter than the Kitchen family. Shell opening is readable in stills only.','Keep the table base and shell identity; repaint with broad lavender/aqua value bands and stronger major contours, then check hinge/support contact.'),
42:(3.6,'The pearl lamp is mostly grey with weak contrast. The pearl sinks below the shell rim instead of demonstrating an obvious lamp-state change; the final pink corona is a sharp uneven patch.','Keep shell/pearl identity, improve painted color/contours, and specify a truthful light action. Do not equate pearl travel with accepted lighting or motion.'),
43:(3.6,'The stack has understandable books, but a ragged cyan background fragment remains behind every pose. Fine page lines, muted contours and the irregular leftover silhouette fail clean object isolation.','Priority: remove only the non-book background remnant while preserving books/pearl, then improve broad painted material and audit opening page continuity.'),
44:(3.9,'All eight small right-lamp states retain a dark open-rim notch and thin pale contours. The brightness changes are visible, but fine speckled edges and compact scale weaken the source.','Preserve shell identity and support; repair rim/edge cleanup and use broad warm light/aqua shadow bands. Verify at actual mounted size.'),
45:(4.0,'The eight chandeliers have a coherent purple ring and hanging pearl, but the narrow ring, tiny lights and very fine isolated edges make the material feel sketchy.','Reuse ring geometry; strengthen broad painted contours/material and check each light state at mounted size before motion acceptance.'),
46:(3.0,'The left chair loses a large wedge through its left seat/back. Small jagged edge scraps remain; this is an incomplete furniture silhouette rather than a clean reusable full object.','Priority: inspect foreground ownership, then restore the intended complete chair at a new derivative/source path without hiding Roshan behind broad background pixels.'),
47:(2.9,'The right chair has a large missing upper-back wedge, a cut arm and ragged outer edge fragments; books remain but the chair silhouette is incomplete.','Priority: restore the named missing chair portions with targeted ImageGen while retaining the established chair/books design and proper foreground ownership.'),
64:(3.8,'The nook contains many tiny washed-out stuffie faces. Ear/face shapes vary between eight poses, and the thin outlines provide weak separation in a dense cluster.','Preserve the accepted stuffie identities. Simplify broad value groups and define which toy actually moves; verify identities and motion individually.'),
65:(3.0,'Eight stacking-toy states are dominated by flat uniform bands and a hard dark pointed peg. Ring lifts are legible, but the material does not match the stronger painted toy family.','Priority: regenerate the same ring toy with broad painted bands, soft plum contours and a rounded toy peg. Preserve ring palette/order and base identity; audit ring conservation/contact before binding.'),
66:(4.3,'The three colored blocks are rounded and readable, with visible painted faces; their thin contours and rough edges are weaker than the strong career props. Separation poses float without contact evidence.','Reuse the three-block identity where possible; clean the edges and strengthen large value bands. Audit actual support/reassembly contact independently.'),
67:(4.2,'Eight tent states preserve the navy/cream tent shape and gradual closing aperture. Cloth reads as nearly uniform flat panels, while the small stuffies lose detail through the narrow opening.','Keep the tent/toy identity; improve painted cloth bands and maintain truthful occlusion of the same toys as the flaps close.'),
69:(4.4,'The friendly purple critter has readable large eyes and rounded painted masses. The detached curl to its right is ambiguous as a tail, trail or separate object.','Review current hop/use to determine that curl ownership. Keep the approved friendly identity; do not count a source still as accepted hop motion.'),
70:(3.8,'Eight sailboat poses are tiny, pale and edged with scattered fine pixels. Mast/sail orientation changes abruptly between the first and later cells.','Preserve the boat identity and mast topology; clean edges and verify one physically continuous sail action at actual scale.'),
71:(3.9,'The left toy tub is readable, but upper toy/crown fragments and a pale floor strip remain at its edges. Large flat teal surfaces lack broad painted depth.','Repair only unowned fragments and clarify the intended foreground silhouette; reuse the tub/stuffies and test occlusion in the actual room.'),
72:(3.9,'The right tub repeats coarse top/left fragments and a pale lower strip. Its stuffies overlap into a dense flat cluster with weak contour distinction.','Priority cleanup of background remnants and individual toy silhouettes, retaining approved stuffie identity and sparse foreground ownership.'),
109:(4.6,'The teal hutch has rounded cream/gold framing, broad painted cabinet bands and recognizable shell/coral props. It matches the stronger existing toy-playset family.','Reuse this source; evaluate its actual mounted hierarchy and card ownership separately.'),
110:(4.5,'The stool has a clear round aqua cushion and stable chunky feet, with a readable shell/gold motif. Fine surface lines and dark foot shadows are modest polish priorities.','Reuse; check actual child/actor scale and contact without changing the approved furniture design.'),
111:(4.6,'The shell chandelier has broad warm painted bands, a clear gold rim and coherent chain. It is materially stronger than the thin Library chandelier sheet.','Prefer this existing painted material reference where identity fits; no automatic substitution of a different lamp.'),
117:(4.6,'The movie frame has a rounded purple/gold silhouette, broad painted relief and a quiet navy content opening. Small shell motifs remain subordinate.','Reuse, checking the exact live video opening, aspect and touch/occlusion separately.'),
118:(4.6,'The cloud settee has large friendly cloud masses, a simple rainbow and broad teal cushions. Painted values and contour hierarchy fit the game family.','Reuse the approved settee; audit actual occlusion and figures seated on it separately.'),
119:(4.6,'The pouf is a broad rounded aqua/purple toy form with restrained warm bead accents and clear painted cushion divisions.','Reuse exactly; verify current contact/scale and keep it a single owned card.'),
120:(4.5,'The pink bowl has a clear scalloped silhouette and warm corn. Numerous small kernels and repeated highlights are a minor density concern at small sizes.','Reuse first, then inspect the actual mounted bowl at child-readable scale before simplifying any corn.'),
125:(4.5,'The hall architecture has coherent painted shells, cream columns and a blue window. Repeated pearl/brick details and highlights are much finer than major toy shapes.','Preserve the accepted joined hall; inspect invitation/actor contrast at runtime rather than redesigning the scene.'),
126:(4.5,'The cream column, gold doors and lavender wall retain the hall identity. The repeated small shell/brick pattern is visually busy in the native crop.','Reuse approved architecture; reduce detail only for a demonstrated mounted hierarchy failure.'),
130:(4.3,'The floor carries dense woven/pearl patterning and sharp glossy reflections beneath a strong red runner. It approaches realistic material detail rather than broad painted bands.','Priority review: soften fine reflection/texture emphasis on the complete approved master if actual actor readability confirms the gap; never regenerate separate cross-tile architecture.'),
131:(4.3,'The sibling floor repeats dense patterning and many narrow column reflections; the red carpet adds another detailed band. Major doorway shapes stay coherent.','Assess mounted figure contrast and preserve all hall/door geometry. Any local material repair must retain the joined master identity.'),
137:(4.5,'The house sign is friendly and materially coherent, with a clear roof/window and shell frame. Small pearl details can blur at its actual doorway size.','Reuse; inspect at the actual sign size with the non-reading route cue.'),
139:(4.6,'The open book has a clear center fold and strong golden/plum framing. It remains recognizable without text and fits the existing route emblem family.','Reuse the exact icon, then verify actual mounted contrast/size and voice/pointer correspondence.')}
for i,(s,e,f) in source_notes.items():opinion(i,s,e,f)
for i in range(74,82):
    if i<78:opinion(i,4.3,'Soft lavender masonry and cream/aqua architecture preserve the toy-room identity, but tiny repeated balusters, fine chandelier lines and faint contours weaken the broad-form treatment.','Reuse approved room geometry. Prioritize contour/detail contrast only where actual toy/actor mounting loses hierarchy; preserve boundary objects once.')
    else:opinion(i,4.3,'The pink floor is dominated by many repeated outlined paving shapes; its fine pattern is stronger and busier than the quiet broad-painted floor language.','Review actual actor/prop contrast; if repair is needed, soften only floor detail on the joined master while preserving architecture and contact planes.')
for i in range(112,116):opinion(i,2.8 if i<114 else 2.5,'Flat uniform ceiling/column/window bands and hard geometry are mixed with a stamped stone texture.' if i<114 else 'Oversized dark perspective-grid lines cross small differently aligned floor squares. The grid dominates the surface and breaks the painted toy material language.','Priority: rebuild the same room architecture/material in ImageGen, preserve layout/door/column facts and continuous master joins; verify native per-screen coverage and actual furniture/actor hierarchy separately.')
for i in range(121,125):opinion(i,2.7 if i<123 else 2.4,'The flat ceiling/columns sit against a repetitive stone texture, with little shared painted material across the components.' if i<123 else 'A rigid dark perspective grid overlays a saturated red patterned floor and small isolated yellow polygons. It conflicts with the much stronger painted movie furniture.','Priority: rebuild the same room with broad painted materials and a quiet consistent floor, preserving layout/content opening and continuous master joins; audit furniture/actor composition and native coverage before binding.')
inventory=read(P/'PENDING_DAY_TWO_SHARED_SOURCES.json')['items'];assert set(data)=={x['id'] for x in inventory} and len(data)==65
rows=[]
for x in inventory:
    assert sha(B/x['path'])==x['sha256'];s,e,f=data[x['id']]
    rows.append(dict(x,status='DIRECT_COMPLETE_NATIVE_SOURCE_REVIEWED',source_score=s,evaluation=e,refinement=f,priority=s<=4.5,direct_original_size=True,current_mounted_score=None,current_complete_action_score=None,owner_acceptance=None))
write(P/'DIRECT_SOURCE_REVIEW.json',dict(status='ALL65_OMITTED_SHARED_DAY_TWO_PRIMARY_SOURCES_DIRECTLY_REVIEWED',reviewed_utc=now(),baseline=read(P/'PLAN.json')['baseline'],source_count=65,inclusive_priorities=sum(x['priority'] for x in rows),below_floor=sum(x['source_score']<4.5 for x in rows),sources=rows,qualification='Every65 complete native source seen individually at original resolution. Opinions concern exact source art, not accepted current job mounting/action, target-device, child or owner. No primary source added or double-counted. Authored cells and complete sequences remain separately qualified. No original source pixel changed.'))
# Assemble additional unchanged-pixel QA joins. Their direct contextual review remains pending.
joins=[]
groups=[('OPERA',lambda x:'/room_opera_hall_background_' in x['path']),('PLAYROOM',lambda x:'/room_playroom_background_' in x['path']),('DINING',lambda x:'/room_dining_room_background_' in x['path']),('MOVIE',lambda x:'/room_movie_lounge_background_' in x['path']),('HALL_PARTIAL_C0_C1',lambda x:'/tiles/main_hall_room_led_' in x['path'])]
for name,predicate in groups:
    group=[x for x in rows if predicate(x)];w,h=group[0]['dimensions'];positions=[(int(re.search(r'_r(\d+)_c(\d+)\.png$',x['path'])[1]),int(re.search(r'_r(\d+)_c(\d+)\.png$',x['path'])[2])) for x in group]
    canvas=Image.new('RGB',((1+max(c for r,c in positions))*w,(1+max(r for r,c in positions))*h))
    for x,(r,c) in zip(group,positions):
        with Image.open(B/x['path']) as im:canvas.paste(im.convert('RGB'),(c*w,r*h))
    target=P/(name+'_UNCHANGED_NATIVE_QA_JOIN.png');canvas.save(target)
    joins.append(dict(name=name,path=target.relative_to(B).as_posix(),sha256=sha(target),dimensions=list(canvas.size),sources=[x['id'] for x in group],scope='Only columns0-1; not the whole7280x2048 hall' if name.startswith('HALL') else 'Complete current source tile family',qa_only=True,resampled=False,production_pixels=False,direct_join_context_review=False))
write(P/'ADDITIONAL_QA_JOINS.json',dict(joins=joins,qualification='Non-resampled unchanged-pixel reconstruction for source context only. Full contextual joins remain pending until directly inspected.'))
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-shared-background-source-review-20261003.json';impact=read(ip)
impact['rules']=sorted(set(impact['rules'])|{'DL-READ-01','DL-READ-02','DL-READ-03','DL-LAY-08'})
impact['validation']=[impact['validation'][0],dict(command='Every65 complete original native shared source directly inspected with one written score/refinement/hash each',result='PASS',evidence='DIRECT_SOURCE_REVIEW.json; source review coverage only, weak opinions remain failures. Extra contextual joins separately pending.')]
impact['files']=sorted(set(impact['files'])|{x.relative_to(B).as_posix() for x in P.rglob('*') if x.is_file()});write(ip,impact)
print('65 exact source opinions recorded;',sum(x['priority'] for x in rows),'inclusive priorities;',sum(x['source_score']<4.5 for x in rows),'below4.5; source pixels unchanged.')
