from pathlib import Path
import json, hashlib, datetime, shutil, subprocess, html, os

R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
K=R/'audit/job_geology_fossil_reveal_continuity_v1_20261003';L=R/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
esc=lambda x:html.escape(str(x),quote=True)
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()=='c5977ebb29bb2011b20fc149ad350290f045045c'
assert not (K/'DIRECT_REVIEW_ATTEMPT01.json').exists()
boundary=read(K/'SOURCE_CURRENT_BEFORE_CAPTURE.json')['source_files']
assert len(boundary)==783 and all(sha(R/x['path'])==x['sha256'] for x in boundary)
m=read(K/'QA_BOARD_MANIFEST_A1.json');assert len(m['boards'])==48
for b in m['boards']:
 assert sha(R/b['path'])==b['sha256'];b['direct_review']=True
 for v in b['members']:
  assert sha(R/v['path'])==v['sha256'];v['direct_review']=True
m.update(status='ALL437_CONSECUTIVE_FRAMES_AND58_SELECTED_CANVASES_DIRECTLY_REVIEWED',reviewed_utc=now)
write(K/'QA_BOARD_MANIFEST_A1.json',m)
caps={w:read(K/f'attempt01/CAPTURE_{w}.json') for w in (1280,1600)}
details=[];reviewed=[];thresholds=[]
for w,c in caps.items():
 f=c['motion_frames'];t=next(x['index'] for x in f if x.get('surface',{}).get('fossil_stage')==1);z=next(x['index'] for x in f if x.get('surface',{}).get('complete'))
 assert (t,z)==((106,202) if w==1280 else (105,201))
 chosen=[next(v for v in c['views'] if v.get('phase_index')==1 and v.get('state')==s) for s in ('task_open','brushed','one_piece','earned_completion')]+[f[i] for i in (20,54,t-1,t,144,z)]
 assert len(chosen)==10
 for x in chosen:
  assert sha(R/x['path'])==x['sha256'];details.append({'path':x['path'],'sha256':x['sha256'],'direct_review':True,'scope':'Original entire native canvas directly inspected separately from the ordered QA boards.'})
 for kind in ('motion_frames','views'):
  for x in c[kind]:
   assert sha(R/x['path'])==x['sha256'];reviewed.append({'path':x['path'],'sha256':x['sha256'],'width':w,'kind':kind,'direct_review':True,'index_or_state':x.get('index',x.get('state')),'review_method':'Every entire consecutive canvas on full-aspect row-major boards; twenty original native canvases inspected separately.'})
 thresholds.append({'width':w,'brush_last_index':t-1,'assembly_first_index':t,'complete_first_index':z,'cleared_at_last_brush':len(f[t-1]['surface']['cleared']),'cleared_at_assembly':len(f[t]['surface']['cleared']),'soil_cells_total':40,'remaining_cells_hidden_at_switch':14})
opinions=[]
def op(item,ident,score,evaluation,refinement):
 opinions.append({'item':item,'id':ident,'score':score,'priority_inclusive':score<=4.5,'meets_floor_provisional':score>=4.5,'evaluation':evaluation,'refinement':refinement,'scope':'K A1 unbound reveal/home placement candidate. Source material, contacts, transitions and whole action are independent lanes; no production or owner/device/child acceptance.'})
op('left fragment','GEO-FOSSIL-LEFT',4.5,'The wide lavender outer arc and uneven inner break retain the painted stone bands and warm shell lobes. The exposed plum cut is readable during the left drag; no source distortion or artificial rectangular strip remains.','Retain the conserved source and partition. Review physical touch separation and source-scale edge aliasing in a runtime binding; exactly4.5 remains a priority.')
op('middle fragment','GEO-FOSSIL-CENTRE',4.5,'The narrow central piece contains the original spiral eye, distinct top stone cap and two complementary irregular breaks. It retains its identity while dragged and rejoins without a second spiral.','Preserve the same source UVs and adjacent-snap contour suppression; improve the guide behind this piece rather than redrawing suitable material.')
op('right fragment','GEO-FOSSIL-RIGHT',4.5,'The right lavender rim and large golden shell lobe balance the left piece. Its plum break contour follows the original alpha, and the final snap restores the continuous original arc.','Keep this exact shared partition and original raster. Runtime/device-scale touch clarity is still pending.')
op('reassembled fossil','GEO-FOSSIL-JOINED',4.5,'Both native aspects restore the continuous warm spiral and lavender outer stone. Shared internal strokes disappear only after neighboring pieces snap; the restored specimen persists through the completion span.','Preserve the joined original and inspect actual runtime restore/repeat. This provisional material floor does not accept the surrounding action.')
op('intact fossil material','GEO-WORK-FOSSIL',4.5,'The unchanged broad lavender planes, warm shell values and authored contour still fit the painted storybook language. Suitable source material is reused without new generation.','Keep the original source and provenance; do not transfer this material score to interaction/contact.')
op('buried-fragment position continuity','GEO-FOSSIL-FRACTURE',4.5,'Fragments are already broken beneath the dirt, and their exposed footprints remain in the same homes during the brush-to-assembly switch. The previous automatic remote fan-out is absent in every reviewed frame at both widths.','Keep discoverable broken pieces in place. This narrow continuity floor excludes residual dirt removal and guide appearance, which remain separately below floor.')
op('soil clearing','GEO-FOSSIL-CLEARING',3.9,'Brushing still erases large rectangular cells with hard horizontal and vertical edges. At26 of40 cleared cells, the remaining14 cells disappear together. Source-quality soil does not make this coarse removal read like brushing.','Develop localized gradual removal with truthful brush coverage; retain intentional one-finger progress and inspect the entire action after any change.')
op('brush-to-assembly transition','GEO-FOSSIL-FRACTURE',4.2,'Native pairs1280:105→106 and1600:104→105 retain the same fragment placement, a substantial continuity improvement. Remaining dirt still vanishes instantly and an intact ghost appears behind the broken pieces at the same switch.','Repair the residual-soil switch and the target reveal as separate reversible changes; no phase forcing or automatic completion.')
op('working hand contact','GEO-FOSSIL-HAND',2.7,'Roshan remains at the left edge with reaching hands far from the brush, dirt and dragged fragments. The brush follows input without an established grip or tool-to-hand contact.','Build a connected work/contact pose and tool anchor against the actual surface; audit every drag and interrupted action.')
op('ghost fossil target','GEO-FOSSIL-TARGET',4.0,'The intact placement guide sits behind compact broken pieces and reads as a pale second fossil, especially during the first snap. Source material is clear, but doubled shell lobes weaken the visual instruction.','Refine target visibility/staging through all drags without concealing the true fragments or requiring text.')
op('room','GEO-ROOM',2.8,'Flat purple bands, broad generic lights and empty stage geometry remain visibly weaker than the painted slab, specimen and characters. This candidate changes none of that environment.','Qualify an existing painted room with required native coverage before generation; audit layering, contact and clear interaction space.')
op('earned completion transition','GEO-FOSSIL-PAN-RESET',4.0,'The completed fossil remains on its slab through the earned celebration and next-phase transition. Roshan changes to a generic raised-crystal pose rather than acknowledging the restored specimen through connected acting.','Retain the completed specimen and refine a truthful acknowledge/return action; actual normal return remains separate machine evidence.')
op('whole fossil action','GEO-FOSSIL-FULL',3.8,'Keeping the discovered pieces in place improves the complete action over the previous3.6 trial. Coarse soil removal, doubled guide, remote hands and generic completion still prevent the4.5 floor. Actual production remains separately scored3.2.','Continue reveal/contact/guide refinement, then recapture the complete actual action. No average or material-floor transfer.')
rev={'status':'POSITION_CONTINUITY4_5_PROVISIONAL_WHOLE_ACTION3_8_BELOW_FLOOR','reviewed_utc':now,'consecutive_frames':437,'fossil_frames':435,'next_phase_endpoints':2,'selected_views':58,'ordered_boards':48,'native_details':details,'reviewed_canvases':reviewed,'threshold_pairs':thresholds,'opinions':opinions,'production_binding':False,'owner_acceptance':None,'source_sha256':sha(R/'assets/opera/worlds/geology/painted_work_v1_20261001/fossil.png'),'fixture_sha256':{'capture':sha(K/'capture.gd'),'surface':sha(K/'reveal_surface.gd')},'qualification':'Explicit non-runtime reveal/home substitution, not draw-only: homes639/780/921,y400 intentionally change. Original raster, inherited input, targets,24px margins, state, actual callbacks and completion retained. Actual Library card/four intentional phases/earned Library return plus separate elevator developer replay/Back. Full fossil only; other phases selected views. Main/Castle entry fixture, isolated saves, desktop Mobile and slow readback do not establish ordinary story travel/natural pacing/device/child/owner/all-job acceptance. All783 production files remain unchanged.'}
write(K/'DIRECT_REVIEW_ATTEMPT01.json',rev)
write(K/'MACHINE_REVIEW_STATUS.json',{'status':rev['status'],'machine_checks':'SIX_FRESH_PASS','direct_review':True,'consecutive_frames':437,'selected_views':58,'boards':48,'native_details':20,'component_opinions':13,'whole_action_score':3.8,'production_binding':False,'owner_acceptance':None,'review':'DIRECT_REVIEW_ATTEMPT01.json'})
for old,new in [('ALL_ITEMS.json','ALL_ITEMS_V41.original.json'),('all_items.html','all_items_V41.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V41.original.json')]:
 assert not (L/new).exists();shutil.copyfile(L/old,L/new)
reg=read(L/'ALL_ITEMS.json');old=read(L/'ALL_ITEMS_V41.original.json');byid={x['id']:x for x in reg['items']}
for o in opinions:
 byid[o['id']].setdefault('candidate_reviews',[]).append({'attempt':'K1 · '+o['item'],'report':K.relative_to(R).as_posix()+'/index.html#opinions','review':K.relative_to(R).as_posix()+'/DIRECT_REVIEW_ATTEMPT01.json','score':o['score'],'evaluation':o['evaluation'],'refinement':o['refinement'],'production_binding':False,'scope':o['scope'],'reviewed_utc':now})
reg.update(display_revision='V42_FOSSIL_REVEAL_HOME_CANDIDATE_HISTORY',updated_utc=now)
reg['scope']+=' V42 appends13 unbound reveal/home opinions after all437 frames/58 views: position continuity4.5 provisional, transition4.2 and whole3.8 belowfloor. Current production scores and1821 counts remain unchanged.'
reg['review_resources'].append({'path':K.relative_to(R).as_posix()+'/index.html','scope':'Unbound reveal/home candidate;437 frames/58 views fully reviewed. Position continuity4.5 provisional;whole3.8. Current production unchanged.'})
(L/'ALL_ITEMS.json').write_text(json.dumps(reg,separators=(',',':'),ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert len(reg['items'])==1821 and reg['counts']==old['counts'] and (L/'ALL_ITEMS.json').stat().st_size<4194304
oldby={x['id']:x for x in old['items']};assert all(x.get('current_mounted_score')==oldby[x['id']].get('current_mounted_score') for x in reg['items'])
t=(L/'all_items.html').read_text(encoding='utf-8-sig');assert '</header>' in t
t=t.replace('</header>','<p><a href="../job_geology_fossil_reveal_continuity_v1_20261003/index.html">New: fossil reveal and home continuity</a> — every437 frame,58 views and13 evaluations. Unbound whole action3.8; current production remains separate.</p></header>',1)
(L/'all_items.html').write_text(t,encoding='utf-8',newline='\n')
write(K/'REGISTER_CHANGE_PROOF_V42.json',{'status':'CANDIDATE_HISTORY_ONLY_CURRENT_SCORES_AND_COUNTS_UNCHANGED','before_sha256':sha(L/'ALL_ITEMS_V41.original.json'),'after_sha256':sha(L/'ALL_ITEMS.json'),'counts':reg['counts'],'candidate_opinions_added':13,'current_mounted_scores_unchanged':True,'production_files_unchanged':783})
def url(p):return esc(os.path.relpath(R/p,K).replace('\\','/'))
def view(p,label):return '<figure><a href="'+url(p)+'"><img loading="lazy" src="'+url(p)+'" alt="'+esc(label)+'"></a><figcaption>'+esc(label)+'</figcaption></figure>'
parts=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fossil reveal continuity review</title><style>body{margin:0;background:#eef3f6;color:#23324a;font:16px/1.5 system-ui}main{max-width:1320px;margin:auto;padding:24px}header,section{background:white;padding:24px;border-radius:16px;margin-bottom:24px}a{color:#305b98}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:20px}figure{margin:0}img{width:100%;height:auto}figcaption{font-size:14px}table{border-collapse:collapse;width:100%}td,th{padding:12px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top}details{padding:14px;background:#f3f4f9;margin:16px 0}summary{cursor:pointer;font-weight:650}.list{columns:3;font-size:13px}.list a{display:block}input{width:100%}button,select{font:inherit;padding:8px}#caption{overflow-wrap:anywhere}.table{overflow:auto}@media(max-width:700px){main{padding:8px}.list{columns:1}table{min-width:800px}}</style><main><header><h1>Discover the same broken fossil beneath the soil</h1><p>The reversible trial keeps all three fragments in place as brushing reveals them. Position continuity reaches a provisional4.5/5; the entire fossil action remains3.8/5 because hard dirt cells, sudden residual-soil removal, doubled guide and remote hands still need refinement.</p><p>This is an unbound reveal/home placement change, not a draw-only change. Current production artwork, inputs and scores remain unchanged. Exactly4.5 meets the provisional floor and remains a priority.</p><p><a href="../job_artwork_refinement_live/all_items.html">Complete1821-item library</a> · <a href="../job_geology_painted_fracture_trial_v1_20261003/index.html">Previous fracture trials</a> · <a href="../job_geode_current_recheck_v1_20261002/index.html">Corrected geode with crystals rooted inside</a></p><p>All437 consecutive canvases (435 fossil+2 next-phase endpoints),58 selected views,48 ordered boards and20 original native details directly inspected;13 individual written opinions. All783 production hashes unchanged. Phone, child, owner and comprehensive all-job acceptance remain open.</p></header>']
parts.append('<section><h2>Revealed fragments and restored fossil</h2><div class="grid">')
for s in ('brushed','one_piece','earned_completion'):
 x=next(x for x in caps[1280]['views'] if x.get('phase_index')==1 and x.get('state')==s);parts.append(view(x['path'],s+' · original1280×720 canvas'))
parts.append('</div></section><section><h2>Every consecutive frame</h2><p>Inspect the threshold change, all three drags/snaps and earned completion. Captured timestamps include slow readback; they do not establish natural device pacing.</p><select id="lane"><option value="1280">1280×720</option><option value="1600">1600×720</option></select> <button id="prev">Previous</button> <button id="next">Next</button><input id="slider" type="range" value="0" min="0"><a id="full"><img id="frame" alt="Original full captured canvas"></a><p id="caption"></p></section><section id="opinions"><h2>Individual evaluations</h2><div class="table"><table><tr><th>Item</th><th>/5</th><th>Evaluation</th><th>Refinement</th></tr>')
for o in opinions:parts.append('<tr><td>'+esc(o['item'])+'</td><td>'+str(o['score'])+'</td><td>'+esc(o['evaluation'])+'</td><td>'+esc(o['refinement'])+'</td></tr>')
parts.append('</table></div><p><a href="DIRECT_REVIEW_ATTEMPT01.json">Complete direct review, hashes and qualifications</a></p></section>')
for w,c in caps.items():
 parts.append(f'<section><h2>{w}×720 original evidence</h2><details><summary>All29 selected full canvases</summary><div class="grid">')
 for x in c['views']:parts.append(view(x['path'],str(x.get('phase_index','route'))+' · '+x['state']))
 parts.append('</div></details><details><summary>Every consecutive original frame</summary><div class="list">')
 for x in c['motion_frames']:parts.append('<a href="'+url(x['path'])+'">'+str(x['index'])+' · '+esc(x['surface'].get('stage',''))+' · '+x['sha256'][:12]+'</a>')
 parts.append('</div></details><details><summary>All24 ordered QA boards</summary><div class="grid">')
 for b in m['boards']:
  if b['width']==w:parts.append(view(b['path'],b['kind']+' · '+str(b['first'])+'–'+str(b['last'])+' · row-major; final blanks are not frames'))
 parts.append('</div></details></section>')
parts.append('<section><h2>Twenty original native details</h2><div class="grid">')
for x in details:parts.append(view(x['path'],Path(x['path']).name))
parts.append('</div></section><section><h2>Method, machine checks and boundaries</h2><p>'+esc(rev['qualification'])+'</p><p>Six fresh local checks pass: parser, inference, officialGodot4.7.2 analyzers for fixture/surface, and independent actual-input captures at1280/1600. Machine success does not accept the visuals. Review-candidate files are separate and originals remain intact.</p><p><a href="PLAN.json">Scoped plan/source inventory</a> · <a href="reveal_surface.gd">Candidate surface</a> · <a href="capture.gd">Actual-input fixture</a> · <a href="SOURCE_CURRENT_BEFORE_CAPTURE.json">All783 literal production hashes</a> · <a href="REGISTER_CHANGE_PROOF_V42.json">V42 candidate-only proof</a></p><p>Previous U publication: every20087 required remote files anonymously fetched with normal TLS and exact byte/hash comparison. Complete journal preserved losslessly in10 parts. This proves previous U publication only; this new draft requires separate publication verification.</p><p><a href="previous_u_remote_verified/RESULT.json">U receipt, revision and access/time</a> · <a href="previous_u_remote_verified/JOURNAL_INDEX.json">All20087 rows — lossless journal</a> · <a href="https://github.com/Ebonyks/mermaid-roshan-reef/tree/c5977ebb29bb2011b20fc149ad350290f045045c">Immutable U tree</a></p><p>Remaining work includes all other job actions and377 source opinions. Nursery reference upload and browser persistence approval requests remain pending; neither action has been retried. No finding closure, integration or release acceptance.</p></section>')
lanes={str(w):[{'path':os.path.relpath(R/x['path'],K).replace('\\','/'),'index':x['index'],'stage':x['surface'].get('stage',''),'complete':x['surface']['complete'],'time_msec':x['time_msec'],'sha256':x['sha256']} for x in c['motion_frames']] for w,c in caps.items()}
parts.append('<script>const lanes='+json.dumps(lanes,separators=(',',':'))+';const lane=document.getElementById("lane"),s=document.getElementById("slider"),f=document.getElementById("frame"),a=document.getElementById("full"),c=document.getElementById("caption");function show(){const q=lanes[lane.value];s.max=q.length-1;s.value=Math.min(Number(s.value),q.length-1);const x=q[s.value];f.src=x.path;a.href=x.path;c.textContent=`Frame ${x.index}/${q.length-1} · ${x.stage} · complete ${x.complete} · captured ${x.time_msec}ms · SHA-256 ${x.sha256}`;}lane.onchange=()=>{s.value=0;show()};s.oninput=show;document.getElementById("prev").onclick=()=>{s.value=Math.max(0,Number(s.value)-1);show()};document.getElementById("next").onclick=()=>{s.value=Math.min(Number(s.max),Number(s.value)+1);show()};show();</script></main></html>')
(K/'index.html').write_text('\n'.join(parts)+'\n',encoding='utf-8',newline='\n')
note='Fossil reveal/home continuation (2026-10-03): [reversible candidate and all437 frames/58 views](PATH) directly reviewed on48 boards plus20 original native details;13 individual opinions. Buried-piece position continuity4.5 provisional, brush/assembly transition4.2, guide4.0, whole3.8 belowfloor. Homes deliberately change; source raster/input/targets/state/callbacks remain inherited. V42 candidate history only; all783 production files and current scores/counts unchanged. No device/child/owner/all-job/finding closure/integration/release acceptance.'
for p,prefix in [(R/'audit/MASTER_AUDIT_2026-08-09.md',''),(R/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../')]:
 t=p.read_text(encoding='utf-8-sig');n=note.replace('PATH',prefix+K.relative_to(R/'audit').as_posix()+'/index.html')
 if 'MASTER_AUDIT' in p.name:t=t.replace('### Development task index\n','### Development task index\n\n'+n+'\n',1)
 else:t+='\n'+n+' MA-VIS-006/MA-PLAY-004/MA-OPERA-012 retain their existing lifecycle states.\n'
 p.write_text(t,encoding='utf-8',newline='\n')
p=R/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8-sig');t+='\n| `'+K.relative_to(R).as_posix()+'/index.html` | 🟣 | `CANDIDATE_REVIEW`; explicit non-runtime reveal/home placement change. All437 frames/58 views/48 boards/20 native details directly reviewed;13 opinions, whole3.8 belowfloor, position continuity4.5 provisional. V42 current production scores/counts and all783 production files unchanged. Complete previous U20087-row anonymous journal preserved losslessly. No action/device/child/owner/all-job/finding closure/integration/release acceptance. |\n';p.write_text(t,encoding='utf-8',newline='\n')
p=R/'ASSET_LICENSES.md';t=p.read_text(encoding='utf-8-sig');t+='\n| `'+K.relative_to(R).as_posix()+'/attempt01/native_{frames,views}/*`, `qa_boards/*` | Native game review captures and QA thumbnails; unchanged original painted fossil/soil/slab sources retain existing rows | Project review evidence; underlying source licenses unchanged | Local officialGodot4.7.2 actual-input capture | Explicit non-runtime reveal/home placement candidate; full native canvases, lossless capture, FFmpeg QA scaling/tiling only. No source bitmap edit, protected change or cinematic delivery. |\n';p.write_text(t,encoding='utf-8',newline='\n')
p=R/'.gitattributes';t=p.read_text(encoding='utf-8-sig');t+='\n# Exact fossil reveal evidence and preserved V41 originals.\n'+K.relative_to(R).as_posix()+'/** -text\naudit/job_artwork_refinement_live/ALL_ITEMS_V41.original.json -text\naudit/job_artwork_refinement_live/all_items_V41.original.html -text\naudit/job_artwork_refinement_live/BOUNDARY_V41.original.json -text\n';p.write_text(t,encoding='utf-8',newline='\n')
shutil.copyfile(Path(__file__),K/'review_tools'/Path(__file__).name)
ip=R/'design/audit_impacts/job-geology-fossil-reveal-continuity-20261003.json';d=read(ip)
d['scope']+=' Full direct review complete:437frames/58views/48boards/20native details,13 opinions. Position continuity4.5 provisional, whole3.8 belowfloor. V42 candidate-only register history; original V41 bytes preserved.'
d['validation'][1].update(result='PASS',evidence=K.relative_to(R).as_posix()+'/DIRECT_REVIEW_ATTEMPT01.json; review complete, visual failures remain.')
d['acceptance_gaps']='Whole action3.8, clearing3.9, transition4.2, guide4.0, contact2.7, room2.8, completion4.0 remain belowfloor; actual production scores unchanged. Story/natural pacing/device/child/owner/all-job/integration/release and finding closure open. Previous U verified20087 files; K requires independent publication. U hosted checks still separate.'
d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in K.rglob('*') if x.is_file()}|{(L/x).relative_to(R).as_posix() for x in ('ALL_ITEMS.json','all_items.html','ALL_ITEMS_V41.original.json','all_items_V41.original.html','BOUNDARY_V41.original.json')}|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','ASSET_LICENSES.md','.gitattributes'})
write(ip,d)
plan=read(K/'PLAN.json');plan['rules']=d['rules'];write(K/'PLAN.json',plan)
allowed=R/'tmp/v2_preview_allowed.json';a=read(allowed);assert isinstance(a,list);write(allowed,sorted(set(a)|{x.relative_to(R).as_posix() for x in K.rglob('*') if x.is_file()}))
assert all(sha(R/x['path'])==x['sha256'] for x in boundary)
print(json.dumps({'status':rev['status'],'boards':48,'frames':437,'views':58,'native_details':20,'opinions':13,'production_unchanged':783,'register_items':1821,'html_bytes':(K/'index.html').stat().st_size}))
