from pathlib import Path
import datetime,hashlib,json,re,shutil,subprocess,sys
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geode_coherent_runtime_v1_20261002';route=b/'audit/job_geology_room_route_v1_20261002';live=b/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def prose(s):return s
failed=read(f/'full_ci_v2/RECEIPT.json');assert failed['status']=='FAIL_PRESERVED_CURRENT_FULL_SUITE' and [(x['probe'],x['process_exit']) for x in failed['probe_results'] if x['process_exit']]==[('probe_passive',127)]
ci=read(f/'full_ci_v3/RECEIPT.json');assert ci['status']=='PASS_UNMODIFIED_CURRENT_FULL_SUITE' and ci['source_unchanged'] and len(ci['source_checks'])==368 and len(ci['probe_results'])==82 and ci['overall_process_exit']==0
assert all(hashlib.sha256((b/x['path']).read_bytes()).hexdigest()==x['before_sha256'] for x in ci['source_checks'])
for rel in ['audit/job_geology_room_route_v1_20261002/index.html','audit/job_artwork_refinement_live/index.html']:
 p=b/rel;s=p.read_text(encoding='utf-8');s=''.join(prose(x) if i%2==0 else x for i,x in enumerate(re.split(r'(<[^>]*>)',s)));p.write_text(s,encoding='utf-8',newline='\n')
for name in ['REVIEW.json','OBJECTS.json']:
 p=route/name;d=read(p)
 def clean(x):
  if isinstance(x,dict):
   return {k:prose(v) if k in ['evaluation','qualification','metadata_correction'] and isinstance(v,str) else clean(v) for k,v in x.items()}
  if isinstance(x,list):return [clean(v) for v in x]
  return x
 write(p,clean(d))
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
write(route/'BROWSER_QA.json',dict(status='PASS',recorded_utc=now,url='http://127.0.0.1:8880/audit/job_geology_room_route_v1_20261002/index.html',viewport_width=1280,document_width=1265,images=89,loaded_images=89,broken_images=0,object_articles=86,native_still_articles=58,frame_evaluations=316,qualification='Read-only browser DOM and screenshot observed. All illustrations loaded; loading/layout is not creative, device, child or owner acceptance. Prose spacing normalization follows this observed content.'))
# Explicit completion fact is additive; earlier pending receipts/opinions retain their dates.
diag=read(f/'full_ci_v3/ENGINE_DIAGNOSTICS.json');raw_count=diag.get('count',diag.get('diagnostic_count',None))
summary='Corrected coherent geode machine checkpoint (2026-10-02): fresh unmodified official Godot4.7.2 full suite3 passes82/82, process0; failed suite2 passive127/81 other probes0 remains separately preserved; all368 literal source hashes unchanged. [Full receipt and retained raw diagnostics](job_geode_coherent_runtime_v1_20261002/full_ci_v3/RECEIPT.json). This verifies the frozen current geode/river production, not visual satisfaction or the extra Library-route capture fixture. Every312 dedicated opening frames/seven mounted states4.5 provisional and all58 Library-route stills/316 consecutive real celebration/return frames remain separately reviewed. Real celebration emblem2.9/composition3.2, room2.8/contact2.7/clearing3.9/pan3.8/caption4.0 remain weak. No all-job/owner acceptance, lifecycle closure, dev/master integration or release.'
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
 p=b/rel;s=p.read_text(encoding='utf-8');note=summary.replace('](job_geode_','](../job_geode_') if '/findings/' in rel else summary;s=s.replace('\n\n','\n\n'+prose(note)+'\n\n',1);p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
old=b/'audit/job_geology_river_runtime_v1_20261002/review_tools'
seal=(old/'seal_geology_checkpoint_j_v241.py').read_text(encoding='utf-8')
replacements={"work=b/'audit/job_geology_river_runtime_v1_20261002'":"work=b/'audit/job_geode_coherent_runtime_v1_20261002'",'geology_checkpoint_j_seal_v241':'geology_checkpoint_k_seal_v258','geology_checkpoint_j_sealed.json':'geology_checkpoint_k_sealed.json',"baseline='40b1c7bfe025f284507c586fea61b9dd76b61423'":"baseline='c6f03791aee93f1443d423dd50334804e37313fb'",'GEOLOGY_RIVER_GEODE_REVIEW_SUPPLEMENT_FILES_V8.json':'GEOLOGY_COHERENT_GEODE_ROUTE_REVIEW_SUPPLEMENT_FILES_V9.json','full_ci_v1':'full_ci_v3','==362':'==368',"['parserv3','inferencev3','authorityv2','developmentv2','2dv1']":"['parserv2','inferencev2','authorityv1','developmentv1','2dv1']","['job-geology-river-join-study-20261001.json','job-geology-river-junction-source-20261001.json','job-geology-river-bed-source-20261002.json','job-geology-river-painted-runtime-20261002.json','job-geode-coherent-opening-20261002.json']":"['job-geode-coherent-runtime-20261002.json','job-geology-room-route-review-20261002.json','job-geology-geode-emblem-reuse-20261002.json','job-geology-grotto-native-resolution-20261002.json','job-training-shared-source-review-20261002.json']",'GEOLOGY_PAINTED_WORK_REVIEW_SUPPLEMENT_FILES_V7.json':'GEOLOGY_RIVER_GEODE_REVIEW_SUPPLEMENT_FILES_V8.json','git(\'add\',\'--\',mp)':'git(\'add\',\'-f\',\'--\',mp)','and362-source':'and368-source'}
for old_text,new in replacements.items():assert old_text in seal,old_text;seal=seal.replace(old_text,new)
start=seal.index("'qualification':'Additive exact canonical");end=seal.index("'}\nwrite(b/mp,m)",start)
seal=seal[:start]+"'qualification':'Additive canonical Git-blob checkpoint: reversible actual seven-state coherent geode; every312 dedicated opening frames,26 boards,8 native details and seven object states4.5 provisional/rooted4.6; rejected mount4.3 and interrupted suite preserved. Actual Library/elevator route: all58 native stills,316 continuous frames,27 boards,4 native details,86 individual mounted object/relationship opinions; actual stage vector emblem2.9/celebration3.2 and earned Library return are separately shown. V30 register1722 known entries has676 inclusive source priorities and385 unassigned; source union is not exhaustive live-use acceptance. Fresh officialGodot4.7.2 unmodified full suite3 82/82 with368 unchanged literal sources and raw diagnostics retained applies only to that frozen production. Extra route fixture has independent parser/analyzer/capture receipts. Earlier closed maps immutable; no all-job/device/child/owner/lifecycle/integration/release acceptance."+seal[end:]
(b/'tmp/seal_geology_checkpoint_k_v258.py').write_text(seal,encoding='utf-8',newline='\n')
pub=(old/'publish_geology_checkpoint_j_v242.py').read_text(encoding='utf-8')
for a,c in [('geology_checkpoint_j_publish_v242','geology_checkpoint_k_publish_v259'),('geology_checkpoint_j_remote_v242','geology_checkpoint_k_remote_v259'),('geology_checkpoint_j_sealed.json','geology_checkpoint_k_sealed.json'),('publish_geology_checkpoint_j_v242.py','publish_geology_checkpoint_k_v259.py'),('audit/job_geology_river_runtime_v1_20261002/full_ci_v1/','audit/job_geode_coherent_runtime_v1_20261002/full_ci_v3/'),('==362','==368'),("'source_count':362","'source_count':368"),('/audit/job_geode_coherent_pilot_v1_20261002/index.html','/audit/job_geology_room_route_v1_20261002/index.html')]:assert a in pub,a;pub=pub.replace(a,c)
start=pub.index('msg.write_text(');end=pub.index("\nrun('commit'",start)
message='Bind coherent painted geode and audit actual Library route\n\nUse seven authored geode states with crystals embedded inside the stone. Preserve the fixed center/base and ordinary seam/pull mechanics, save and rewards;59 existing surface methods remain literal unchanged. Dedicated actual opening312 frames/seven states4.5 provisional, material/rooted crystals4.6. Rejected mounting4.3, interrupted suite1 and failed suite2 passive127 preserved. Same painted geode crest/goal reuse4.5/4.6 remains unbound; new grotto1254-square fails2048-square native coverage and remains reference-only. Three shared-training sources and11 components individually reviewed with caller trace.\n\nReview actual Library picture-card entry, four intentional phases, normal OperaAct celebration and earned room return; elevator replay entry/cancel separate. Every58 native stills/316 continuous frames/27 boards/4 native details and86 individual object/relationship opinions included. Real celebration still reverts to flat emblem2.9/composition3.2; room2.8/contact2.7/clearing3.9/pan3.8/caption4.0 remain weak.\n\nFresh officialGodot4.7.2 unmodified full suite3 82/82 with368 unchanged literal sources, raw diagnostics retained. Extra review fixture independently parsed/analyzed/captured. V30 register1722 known entries,676 inclusive source priorities/385 unassigned. Qualified reversible topic review checkpoint, no all-job/device/child/owner acceptance, finding closure, dev/master integration or release. Prior immutable maps unchanged.\n'
pub=pub[:start]+'msg.write_text('+repr(message)+",encoding='utf-8')"+pub[end:];(b/'tmp/publish_geology_checkpoint_k_v259.py').write_text(pub,encoding='utf-8',newline='\n');shutil.copyfile(b/'tmp/publish_geology_checkpoint_k_v259.py',f/'review_tools/publish_geology_checkpoint_k_v259.py')
mp=b/'audit/job_review_v2_20261001/GEOLOGY_COHERENT_GEODE_ROUTE_REVIEW_SUPPLEMENT_FILES_V9.json';assert not mp.exists();write(mp,dict(status='UNSEALED_LOCAL_PLACEHOLDER_NOT_DELIVERY'))
ip=b/'design/audit_impacts/job-geode-coherent-runtime-20261002.json';d=read(ip)
d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for folder in [f,route,live] for p in folder.rglob('*') if p.is_file()}|{mp.relative_to(b).as_posix()}|{f.relative_to(b).as_posix()+'/runtime_gate/'+label+ext for label in ['authorityv1','developmentv1','2dv1'] for ext in ['.stdout.log','.stderr.log','.receipt.json']})
d['validation'].append(dict(command='Fresh unmodified officialGodot4.7.2 full suite',result='PASS',evidence=f.relative_to(b).as_posix()+'/full_ci_v3/RECEIPT.json;82/82,368 unchanged literal source hashes, all raw diagnostics retained.'));d['acceptance_gaps']='Machine suite passes82/82 on368 frozen sources; visual room2.8/contact2.7/normal stage emblem2.9/celebration3.2/clearing3.9/pan3.8/caption4.0 and inclusive geode4.5 remain. No all-job/owner acceptance or finding closure/integration/release.';write(ip,d)
for label,args in [('authorityv1',[sys.executable,'-X','utf8','-B','tools/audit_document_authority.py']),('developmentv1',[sys.executable,'-X','utf8','-B','tools/audit_development.py','--base','auto']),('2dv1',[sys.executable,'-X','utf8','-B','tools/audit_game_2d.py'])]:
 t=datetime.datetime.now(datetime.timezone.utc);q=subprocess.run(args,cwd=b,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(f/'runtime_gate'/f'{label}.stdout.log').write_bytes(q.stdout);(f/'runtime_gate'/f'{label}.stderr.log').write_bytes(q.stderr);write(f/'runtime_gate'/f'{label}.receipt.json',dict(status='PASS' if q.returncode==0 else 'FAIL',command=args,process_exit=q.returncode,started_utc=t.isoformat(),finished_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),qualification='2D no-regression is not strict zero-debt satisfaction.' if label=='2dv1' else 'Machine authority/coverage gate; no creative acceptance.'));print(label,q.returncode,q.stdout.decode(errors='replace')[-1700:],flush=True);assert q.returncode==0
print('K prepared; current source boundary368, production still frozen.',flush=True)
