from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');R=B/'assets_src/imagegen/candy_cover_pose_v1_20261003';G=R/'gates_v1';G.mkdir();IP=B/'design/audit_impacts/job-candy-cover-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):n=p.with_name(p.name+'.v592_next');n.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());n.replace(p)
src=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/CANDY_COVER_REPORT_BROWSER_V592.jpg');dst=R/'BROWSER_COVER_REPORT_V592.jpg';shutil.copyfile(src,dst)
with Image.open(dst) as im:screenshot_dimensions=list(im.size);screenshot_format=im.format
assert screenshot_format=='JPEG'
write(R/'BROWSER_VERIFY_V592.json',dict(status='ACTUAL_COVER_REPORT_TWO_NATIVE_IMAGES_TEN_OPINIONS_NO_OVERFLOW',checked_utc=now(),url='http://127.0.0.1:8880/assets_src/imagegen/candy_cover_pose_v1_20261003/index.html?revision=cover-v1#cover',viewport=[1280,720],document_width=1265,loaded_images=[dict(path='../candy_wrap_scene_context_v1_20261003/attempt02/native.png',dimensions=[1672,941],loaded=True),dict(path='attempt01/native.png',dimensions=[1672,941],loaded=True)],individual_opinion_rows=10,cover_screen_bounds=dict(left=76.5,top=33.0625,width=1112,height=625.828125,bottom=658.890625),screenshot_path=dst.relative_to(B).as_posix(),screenshot_sha256=sha(dst.read_bytes()),screenshot_dimensions=screenshot_dimensions,screenshot_format=screenshot_format,qualification='Actual desktop report observation and screenshot, not actual game, animation, target-phone, child or owner acceptance. Complete-cover endpoint and current2.8 runtime score remain distinct.'))
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();row=('\n| `'+dst.relative_to(B).as_posix()+'` | Actual local browser screenshot of new Candy complete-cover source report | Original project QA layout and inherited displayed-art attribution | `assets_src/imagegen/candy_cover_pose_v1_20261003/BROWSER_VERIFY_V592.json` binds exact screenshot and observed loaded images/opinions | QA screenshot only, no production/cinematic pixels, motion/game/device/child/owner acceptance. |\n').encode();assert dst.relative_to(B).as_posix().encode() not in raw;n=licenses.with_name(licenses.name+'.v592_next');n.write_bytes(raw+row);n.replace(licenses)
H=R/'previous_x_hosted_complete_v592';H.mkdir();cmd=['C:/Program Files/GitHub CLI/gh.exe','run','view','37111673023','--repo','Ebonyks/mermaid-roshan-reef','--json','databaseId,headSha,status,conclusion,url,jobs'];rr=subprocess.run(cmd,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(H/'RUN.json').write_bytes(rr.stdout);(H/'RUN.stderr.log').write_bytes(rr.stderr);assert rr.returncode==0,rr.stderr.decode(errors='replace');data=json.loads(rr.stdout);assert data['headSha']=='2b109a233c14050567aaa84dc975119b2e18a77e';assert data['status']=='completed' and data['conclusion']=='success';assert all(j['status']=='completed' and j['conclusion']=='success' for j in data['jobs'])
write(H/'VERIFICATION.json',dict(status='EXACT_X_HOSTED_RUN_TERMINAL_SUCCESS',checked_utc=now(),command=cmd,exit_code=rr.returncode,revision=data['headSha'],run_id=data['databaseId'],url=data['url'],raw_sha256=sha(rr.stdout),jobs=[dict(name=j['name'],status=j['status'],conclusion=j['conclusion']) for j in data['jobs']],qualification='Actual hosted API terminal run/job conclusions only, no warning-free subprocess claim. Prior pending snapshot remains history. This does not grant new Y/Z hosted PASS, visual/action/device/child/owner/all-job/integration/release acceptance or strict zero2D debt.'))
old=(B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/review_tools/run_context_gate_v587.py').read_text(encoding='utf-8');old=old.replace("G=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/gates_v3'","G=B/'assets_src/imagegen/candy_cover_pose_v1_20261003/gates_v1'").replace('assets_src/local_motion/candy_wrap_continuity_v1_20261003/gates_v3/CANDIDATE_CONTEXT_SOURCE_V587.json','assets_src/imagegen/candy_cover_pose_v1_20261003/gates_v1/CANDIDATE_COVER_SOURCE_V593.json').replace('CANDIDATE_CONTEXT_SOURCE_V587.json','CANDIDATE_COVER_SOURCE_V593.json');assert "G=B/'assets_src/imagegen/candy_cover_pose_v1_20261003/gates_v1'" in old
runner=R/'review_tools/run_cover_gate_v593.py';runner.write_bytes(old.encode());shutil.copyfile(__file__,R/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in R.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Actual illustrated cover report browser verification',result='PASS',evidence='assets_src/imagegen/candy_cover_pose_v1_20261003/BROWSER_VERIFY_V592.json;both1672x941 images/10 opinions/no horizontal overflow and exact screenshot. This is review-page QA only.'));d['validation'].append(dict(command='Runtime Godot import/parser/lint/probes for source-only review additions',result='NOT_APPLICABLE',evidence='No production asset,script or import delta. assets_src/.gdignore and audit/.gdignore exclude all changed review artwork; all783 literal production members remain source-bound unchanged. Existing full82/82 official4.7.2 and terminal X hosted machine evidence remain scoped; new hosted run separate.'))
for label in ['authority','development','document_tests','game2d']:
    for suffix in ['.stdout.log','.stderr.log','.receipt.json']:d['files'].append((G/(label+suffix)).relative_to(B).as_posix())
snapshot=G/'CANDIDATE_COVER_SOURCE_V593.json';d['files'].append(snapshot.relative_to(B).as_posix());d['files']=sorted(set(d['files']));write(IP,d)
members=[]
for path in d['files']:
    p=B/path
    if not p.is_file() or path.startswith(G.relative_to(B).as_posix()+'/'):continue
    members.append(dict(path=path,bytes=p.stat().st_size,sha256=sha(p.read_bytes())))
write(snapshot,dict(status='EXACT_COVER_REVIEW_SOURCE_FROZEN_BEFORE_FRESH_GATES',baseline=d['baseline'],frozen_utc=now(),member_count=len(members),members=members,exclusions=['gates_v1 process outputs and this self metadata','self-describing impact record','publication root/shards to be separately staged-sealed later'],qualification='Historical pre-gate review state. Later gate receipts/publication metadata and impact result updates receive a separate final exact staged seal. No current whole-motion/game/owner/all-job acceptance.'))
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in R.rglob('*') if p.is_file()}))
print('COVER_BROWSER_PROOF_AND_FRESH_GATES_PREPARED',len(members),screenshot_dimensions,flush=True)
