from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
R=B/'assets_src/imagegen/candy_cover_pose_v1_20261003'
source='assets_src/imagegen/candy_wrap_scene_context_v1_20261003/attempt02/native.png'
sha=lambda raw:hashlib.sha256(raw).hexdigest()
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
    p.parent.mkdir(parents=True,exist_ok=True);n=p.with_name(p.name+'.v589_next');n.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());n.replace(p)
base=subprocess.run(['git','rev-parse','HEAD'],cwd=B,capture_output=True,text=True,check=True).stdout.strip()
assert base=='a77521a4f43b831b67fbf3b88f18fd1c5d51707a'
assert not R.exists();R.mkdir(parents=True)
prompt='''Use case: precise-object-edit
Image 1 is the complete existing painted Candy Maker scene. Make exactly one targeted action-pose change: complete the far-edge fold over the SAME red oval sweet. Return the ENTIRE same 16:9 landscape painting.
Preserve the exact character face, eyes, brown hair, rainbow ribbon, hat, costume, sleeve-to-arm connections, two coral quilted oven mittens, camera, character size, lavender worktop and candy-factory background. Keep exactly TWO hands, each belonging to her original visible forearm. Preserve ONE original red sweet in its exact position and size, on the same single gold sheet. No extra character, hand, bare finger, sweet, table prop or decoration.
Change only the already partially folded gold flap and the two existing mitten contact poses. The far gold flap now bends physically down and forward over the rounded top of the supported sweet. Its free edge reaches the near/front lower side of that sweet, completely hiding ALL red of the sweet under the opaque same gold paper. It conforms gently to the original small oval volume; it is not a new giant lump, bag, tube, disconnected ribbon or flat curtain. The rest of the original sheet remains attached and spread on the table around that SAME covered sweet, with its free side ends still open for the later neck pinches and opposite twists. Do not finish those later twists yet.
Her original screen-left mitten presses the left-center of this just-laid-down flap onto the rounded covered sweet; her original screen-right mitten braces and presses its right edge. The two contacts visibly belong to the same physical fold. Show only the existing rounded mitten palms/thumbs; do not grow fingers or add floating hands. Keep the head and body fixed; preserve the original small supported sweet location and tabletop registration.
Keep the same painted 2D storybook material, plum outlines, broad satin gold value bands and restrained paper creases. No photorealism, realistic 3D, vector placeholder, UI, text, sparkle, glowing substitute, cropping, collage or new scene. This is one complete covering-and-pressing key pose, not a motion sequence and not final acceptance.'''
(R/'PROMPT.txt').write_bytes((prompt+'\n').encode())
inventory=[]
for path,reason in [(source,'Reuse exact clean contextual painting, provisional starting still4.5; only partial cover. Whole current motion fails.'),('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt03/native.png','Earlier4-key source has gold contact endpoints4.5 but face/table/sweet registration continuity4.2; its fold key still exposes red ends. Not the exact clean contextual complete cover.'),('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt04/native.png','Earlier registration edit failed4.1 and changes wrapper belly size. Not reusable for this exact endpoint.'),('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt13/native.png','Existing isolated partial-fold source4.5; coverage4.2, different whole scene context.'),('assets/opera/worlds/widgets/widget_crank_candymaker_mover.png','Existing decorative prewrapped candy lacks supported sheet/fold/contact states; established current workflow review2.8 retained.')]:
    raw=(B/path).read_bytes();inventory.append(dict(path=path,sha256=sha(raw),reuse_evaluation=reason))
native_hash=sha((B/source).read_bytes());assert native_hash=='b126a8ab0f1c0d1e720588335beb3bdb6f1e2b4153ff1e2deeacaf5443d2ec62'
write(R/'PLAN.json',dict(status='SPECIFIC_COVER_POSE_PLANNED_NO_OUTPUT_YET',planned_utc=now(),baseline=base,scope='One targeted complete-cover-and-press pose derived from clean painted context; preserve originals, no production binding or additional Comfy retry before direct still review.',profile='design/animation/ROSHAN_MOVEMENT_LANGUAGE.md',references=[dict(path=source,sha256=native_hash,role='edit_target_exact_full_scene_identity_and_partial_gold_fold')],reuse_inventory=inventory,prompt=prompt,prompt_sha256=sha((R/'PROMPT.txt').read_bytes()),generation_method='built_in_imagegen_precise_object_edit',required_evidence=['native dimensions/mode/hash/exact prompt and reference hashes','Direct full image and same-source comparison: exactly two attached mittens, one conserved supported sweet, continuous gold sheet, complete opaque cover and pressing contact','Individual source/style/contact/material/registration opinions; no transfer to whole motion or runtime score','Preserve failed candidate and iterate only its named defect; neck pinch/opposite twist/release and actual game/training/device/child/owner remain independently open'],current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None))
dest=R/'review_tools'/Path(__file__).name;dest.parent.mkdir();shutil.copyfile(__file__,dest)
rules=json.loads((B/'design/audit_impacts/job-candy-painted-context-source-20261003.json').read_text(encoding='utf-8-sig'))['rules']
write(B/'design/audit_impacts/job-candy-cover-pose-20261003.json',dict(id='job-candy-cover-pose-20261003',scope='Targeted reversible complete gold-paper covering/pressing pose to repair the missing physical endpoint after A5/A6 local reference rejection; preserve exact contextual identity/material and originals. No runtime, cinematic delivery or release.',baseline=base,rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],files=sorted(p.relative_to(B).as_posix() for p in R.rglob('*') if p.is_file()),validation=[dict(command='Existing source and rejected motion reuse inventory before built-in imagegen',result='PASS',evidence='assets_src/imagegen/candy_cover_pose_v1_20261003/PLAN.json; exact current clean source hash and unchanged2.8 production score.'),dict(command='Direct native covering pose and individual component review',result='PENDING',evidence='No generated output yet; no still or motion score claimed.'),dict(command='Fresh authority/development/2D no-regression gates before publication',result='PENDING',evidence='New pose scope only; previous gates do not transfer to changed review files.')],acceptance_gaps='Complete wrapper neck pinches/opposing twists/release, all continuous motion and game/training uses, phone/device/child/owner approval and comprehensive all-job report remain open. Static output cannot grant motion/runtime/cinematic acceptance.'))
print('PREPARED_ONE_TARGETED_COVER_POSE',base,native_hash,sha((R/'PROMPT.txt').read_bytes()),flush=True)
