from pathlib import Path
import copy,datetime,hashlib,json,shutil,subprocess
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');R=B/'assets_src/imagegen/candy_cover_pose_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-cover-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):n=p.with_name(p.name+'.v591_next');n.write_bytes(raw);n.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
for name,target in [('ALL_ITEMS.json','ALL_ITEMS_V49.original.json'),('all_items.html','all_items_V49.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V49.original.json')]:assert not (L/target).exists();shutil.copyfile(L/name,L/target)
reg=read(L/'ALL_ITEMS.json');assert reg['display_revision']=='V49' and len(reg['items'])==2049
s=read(R/'attempt01/SOURCE.json');r=read(R/'attempt01/DIRECT_REVIEW.json');z=copy.deepcopy(next(x for x in reg['items'] if x['id']=='CANDY-CONTEXT-SOURCE-02'))
z.update(id='CANDY-COVER-SOURCE-01',aliases=['CANDY-COVER-SOURCE-01'],path=s['native_path'],earlier_sha256=s['native_sha256'],current_checkout_sha256=s['native_sha256'],current_source_score=4.5,evaluation=r['opinions'][-1]['evaluation'],refinement='Preserve this complete-cover/press endpoint. Independently verify the actual far-edge fold trajectory, stable release, neck pinches/opposite twists and current game/training use; inherited room4.4 remains weak.',families=['Day Two','Candy Maker','Unbound complete-cover endpoint'],original_reports=[R.relative_to(B).as_posix()+'/index.html'],source_qualification='One complete targeted native directly compared with prior clean partial-fold source. Coverage4.6/whole still4.5 provisional; no fold trajectory, motion or runtime acceptance.',preview_path=s['native_path'],image_path=s['native_path'],image_scope='Complete preserved covering-and-pressing still only',source_dimensions=s['dimensions'],individual_review_utc=r['reviewed_utc'],latest_refinement=dict(report=R.relative_to(B).as_posix()+'/index.html#cover',note='Ten individual source opinions. Same gold paper now covers the sweet; current WRAP remains2.8 and all6 local motion studies rejected.'))
reg['items'].append(z);pri=[x for x in reg['items'] if x.get('current_source_score') is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3']];unique={x['path'] for x in pri if x['kind'] in ['source','runtime source']};pending=[x for x in reg['items'] if x['kind']=='source' and x.get('current_source_score') is None]
assert len(reg['items'])==2050 and len(pri)==953 and len(unique)==664 and len(pending)==294
reg['counts'].update(unique_source_files=1286,registered_items=2050,inclusive_current_source_priorities=953,unique_source_file_priorities=664,unreviewed_current_source=294,new_candy_cover_sources=1)
reg.update(display_revision='V50',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v50.py',scope='V50:2050 known entries/1286 primary sources/328 pose cells/151 runtime-use-action entries/285 source object regions.953 inclusive source-cell-region priorities/664 unique source-file priorities/294 unreviewed primary sources. One targeted native complete-cover/press pose and10 opinions: cover4.6/whole still4.5 provisional/inherited room4.4. All246 six local native motion frames/60 components remain rejected independently, including A5 3.1/A6 2.6. Current WRAP2.8/all783 production literals unchanged. Full fold/neck pinch/twists/release/current game/training/device/child/owner/comprehensive all-job acceptance remains open.')
reg['current_byte_status_counts']['EXACT_REVIEWED_GENERATION_BYTES']+=1;reg['review_resources'].append(dict(path=R.relative_to(B).as_posix()+'/index.html',scope='One complete-cover-and-press still/10 opinions: coverage4.6,whole source4.5 provisional,room4.4. No motion/runtime acceptance.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304;shutil.copyfile(L/'review_tools/refresh_current_job_review_v49.py',L/'review_tools/refresh_current_job_review_v50.py')
notice='<p class="current-cover-review"><a href="../../assets_src/imagegen/candy_cover_pose_v1_20261003/index.html">Latest: targeted gold-paper complete cover and pressing pose, original and10 written opinions</a> · Cover endpoint4.6/whole still4.5 provisional; room4.4 remains weak. <strong>V50:2050 known entries/953 source-cell-region priorities/664 unique priority sources/294 unreviewed primary sources.</strong> Current WRAP2.8 and all six local motion rejections remain separate.</p>'
for name in ['index.html','all_items.html']:
    p=L/name;t=p.read_text(encoding='utf-8').replace('refresh_current_job_review_v49.py','refresh_current_job_review_v50.py');assert '<h1>' in t;t=t.replace('<h1>',notice+'<h1>',1);put(p,t.encode())
note='Targeted Candy cover-pose continuation (2026-10-03): [one complete preserved ImageGen covering-and-pressing native and10 individual source opinions](COVER) reuse the clean partial-fold scene. Same opaque gold sheet now fully hides the supported sweet: endpoint4.6/whole still4.5 provisional/inherited room4.4. This is one still, not a fold trajectory or motion acceptance. All246 A1-A6 native local frames/60 opinions remain separately rejected, A5 3.1/A6 2.6; current WRAP2.8/all783 production literals unchanged. V50 known2050 entries/1286 primary sources/953 source-cell-region priorities/664 unique priority sources/294 unreviewed primary sources. Full fold/neck pinch/opposing twists/release, current game/training/device/child/owner/comprehensive report, finding lifecycle, integration and release remain open.'
for path,link in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/imagegen/candy_cover_pose_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/imagegen/candy_cover_pose_v1_20261003/index.html'),('audit/animation/README.md','../../assets_src/imagegen/candy_cover_pose_v1_20261003/index.html')]:
    p=B/path;t=p.read_text(encoding='utf-8');snote=note.replace('COVER',link)
    if path.endswith('MASTER_AUDIT_2026-08-09.md'):
        for marker in ['## 0. Planning entry','### Development task index']:assert marker in t;t=t.replace(marker,marker+'\n\n'+snote,1)
    else:i=t.index('\n')+1;t=t[:i]+'\n'+snote+'\n'+t[i:]
    put(p,t.encode())
ledger=B/'design/05_DOC_LEDGER.md';t=ledger.read_text(encoding='utf-8');t+='\n| `assets_src/imagegen/candy_cover_pose_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; one targeted complete gold-cover/pressing native and10 individual source opinions. Cover endpoint4.6,whole still4.5 provisional,inherited room4.4; all six local motion failures/current WRAP2.8 remain separate. No game/action/device/child/owner acceptance. |\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V49.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact2049-entry register before one targeted covering-and-pressing source. |\n';put(ledger,t.encode())
attrs=B/'.gitattributes';at=attrs.read_text(encoding='utf-8');at+='\nassets_src/imagegen/candy_cover_pose_v1_20261003/** -text\naudit/job_artwork_refinement_live/ALL_ITEMS_V49.original.json -text\naudit/job_artwork_refinement_live/all_items_V49.original.html -text\naudit/job_artwork_refinement_live/BOUNDARY_V49.original.json -text\n';put(attrs,at.encode())
dst=R/'review_tools'/Path(__file__).name;shutil.copyfile(__file__,dst)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in R.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS.json','index.html','all_items.html','CURRENT_BOUNDARY_REFRESH.json','ALL_ITEMS_V49.original.json','all_items_V49.original.html','BOUNDARY_V49.original.json','review_tools/refresh_current_job_review_v50.py']}|{'.gitattributes','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md','design/05_DOC_LEDGER.md'});write(IP,d)
rr=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v50.py')],cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(R/'REFRESH.stdout.log').write_bytes(rr.stdout);(R/'REFRESH.stderr.log').write_bytes(rr.stderr);assert rr.returncode==0,rr.stderr.decode(errors='replace');assert read(L/'CURRENT_BOUNDARY_REFRESH.json')['registered_source_matches']==2050
d=read(IP);d['files']=sorted(set(d['files'])|{(R/n).relative_to(B).as_posix() for n in ['REFRESH.stdout.log','REFRESH.stderr.log']});d['validation'].append(dict(command='V50 literal known-item/current Candy boundary refresh',result='PASS',evidence='audit/job_artwork_refinement_live/CURRENT_BOUNDARY_REFRESH.json;2050/2050 source hashes/all783 current Candy production sources match, older shared-world mounted claims withheld.'));write(IP,d)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in R.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for p in L.rglob('*') if p.is_file()}))
print(rr.stdout.decode().strip());print('V50_REVIEW_REGISTERED',len(reg['items']),len(pri),len(unique),len(pending),(L/'ALL_ITEMS.json').stat().st_size,flush=True)
