from pathlib import Path
import json,hashlib,datetime,shutil,html
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');parent=b/'audit/job_geode_opening_states_v3_20261001';out=parent/'attempt_03';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
previous=json.loads((parent/'attempt_02/REVIEW.json').read_text());capture=json.loads((out/'native_views/CAPTURE_RECEIPT.json').read_text());rows=[]
for old,v0 in zip(previous['views'],capture['views']):
 assert old['id']==v0['id'];v=dict(old);v.update(v0);p=out/'native_views'/v['path'];assert sha(p)==v['sha256'];v.update(archive_path=rel(p),reviewed_utc=now,direct_native_review=True)
 if v['authored_opening_state']=='fully_open':v['scores']['endpoint_base_continuity']=4.5;v['evaluation']='Full endpoint retains three rooted cyan/lilac crystals in each cream-rimmed cavity4.6. Whole intact cards now share the515px base with closed/intermediate350h states: the15px rise is corrected, static base continuity4.5 provisional. Source pixels and cavity identities are unchanged. Halves remain on the painted slab without a loose crystal or reward layer. Remote actor contact2.7, timed opening/ordinary routes and under-resolution room remain open.'
 v['qualification']='Every10 new surrounding native view directly inspected at1280/1600. Only full endpoint centreY+15 changed; all325 production sources/input/rewards/save remain unchanged. This static base correction does not pass remote actor contact, timed opening, complete routes, device/child/owner or final report.';rows.append(v)
assert len(rows)==10;write(out/'REVIEW.json',dict(status='10_OF10_DIRECT_NATIVE_BASE_CORRECTION_REVIEW',views=rows,directly_reviewed=10,total_teacher_geology_pan_views=312,previous_review=rel(parent/'attempt_02/REVIEW.json'),qualification='Static endpoint base4.5 provisional; embedded material4.6. Invitation3.8 and remote actor2.7 remain priorities. All312 selected native comparisons directly inspected; no overall game acceptance.'))
cards=['<article><h2>'+v['id']+'</h2><img src="native_views/'+v['path']+'" alt="'+v['id']+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+': '+str(s)+'/5' for k,s in v['scores'].items() if s is not None))+'</p></article>' for v in rows]
head='<!doctype html><meta charset="utf-8"><style>body{font:18px/1.5 system-ui;color:#302949;background:#eef5f4;max-width:1500px;margin:auto;padding:24px}article{background:white;padding:20px;margin:24px 0}img{width:100%;height:auto}</style>'
(out/'index.html').write_text(head+'<h1>Geode opening — corrected common base</h1><p>Every10 native view directly inspected. Source material/embedded crystals4.6; selected static progression/base4.5 provisional. The invitation3.8 and distant working actor2.7 remain weak.</p><p><a href="REVIEW.json">Individual scores and hashes</a> · <a href="../attempt_02/REVIEW.json">Preserved15px-rise draft</a> · <a href="PROCESS_RECEIPT.json">Native machine evidence</a></p>'+''.join(cards),encoding='utf-8')
p=parent/'index.html';s=p.read_text();i=s.index('</h1>')+5;banner='<section id="current-base-attempt03"><h2>Current endpoint placement — shared base</h2><p>Every10 updated view inspected;312 total selected teacher/geology/pan comparisons. Full endpoint centreY+15 fixes the measured base rise. Base/static progression4.5 provisional and embedded material4.6; invitation3.8/remote actor2.7 remain priorities.</p><img src="attempt_03/native_views/geologist_1280_geode_fully_open_embedded_interior_painted_staging.webp" alt="Crystals rooted inside opened geode"><p><a href="attempt_03/index.html">All10 current native views and written evaluations</a></p></section>';assert 'current-base-attempt03' not in s;s=s[:i]+banner+s[i:];p.write_text(s,encoding='utf-8');shutil.copyfile(__file__,out/'executed_record_base_review_v144.py')
with (b/'ASSET_LICENSES.md').open('a',encoding='utf-8',newline='\n') as f:
 for v in rows:p=out/'native_views'/v['path'];f.write('\n| `'+rel(p)+'` | Godot4.7.2 native reversible whole-card geode base-alignment capture | Project capture; underlying original artwork licenses retained | Local native capture | Unmodified complete viewport; source art unchanged. SHA256 '+sha(p)+' |\n')
for p in [b/'audit/job_review_v2_20261001/index.html',b/'audit/job_artwork_refinement_live/index.html']:
 s=p.read_text();i=s.index('</h1>')+5;banner='<section id="geode-current-base312"><h2>Current geode opening —312 native comparisons</h2><p>Crystals stay rooted inside both cavities. Every10 latest base-corrected view directly inspected; static base/progression4.5 provisional and source material4.6. Invitation3.8, remote actor2.7 and full timed/ordinary routes remain priorities. <a href="../job_geode_opening_states_v3_20261001/attempt_03/index.html">Current illustrated geode</a>; <a href="../../assets_src/local_motion/day2_geologist_pan_motion_v1_20261001/attempt_01/index.html">All41 first panning motion frames</a>: motion3.8/action3.4/return3.6; prompt-only retry underway.</p></section>';assert 'geode-current-base312' not in s;p.write_text(s[:i]+banner+s[i:],encoding='utf-8')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Geode base correction (2026-10-01): [all10 current native views](job_geode_opening_states_v3_20261001/attempt_03/index.html) directly inspected,312 selected teacher/geology/pan comparisons. Intact full cards centreY+15 correct the15px base rise: static base/progression4.5 provisional, embedded material4.6. Invitation3.8/remote actor2.7, full timed opening/routes/device/child/owner/final report remain open. Earlier attempts including first capture failure preserved;325 production sources unchanged.';s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+entry+'\n',1);master.write_text(s,encoding='utf-8')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();s+='\n| `'+rel(out/'index.html')+'` | 🟣 | `CANDIDATE`;10 new native views directly inspected at1280/1600. Whole endpoint centreY+15 aligns the515px base; static base/progression4.5 provisional, embedded source4.6. Invitation3.8/remote actor2.7/full timed route/device/child/owner remain open.312 total selected native comparisons. |\n';ledger.write_text(s,encoding='utf-8')
findings=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text();start=s.index('\n## MA-PLAY-004\n');end=s.find('\n## ',start+1);sec=s[start:end];lines=sec.splitlines();i=next(i for i,x in enumerate(lines) if x.startswith('| history |'));lines[i]=lines[i].rstrip().removesuffix('|').rstrip()+' 2026-10-01 geode base correction: all10 additional views/312 total directly inspected. Endpoint centreY+15 removes15px rise; static base4.5 provisional. Invitation3.8/remote contact2.7 and timed/routes/device/child/owner remain open; no production change/lifecycle closure. |';s=s[:start]+'\n'.join(lines)+'\n'+s[end:];findings.write_text(s,encoding='utf-8')
ip=b/'design/audit_impacts/job-geode-opening-continuity-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in parent.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html'});d['validation'].append(dict(command='Direct original-resolution review of all10 corrected common-base native views',result='PASS',evidence=rel(out/'REVIEW.json')+'; static base4.5 provisional; remote actor2.7 and invitation3.8 remain failed.'));write(ip,d)
packet=b/'assets_src/local_motion/day2_geologist_pan_motion_v1_20261001';m=json.loads((packet/'MANIFEST.json').read_text());m.pop('visual_review');m['output_state']='Prepared; no prompt submitted or motion score assigned.';submission=packet/'attempt_01/MANIFEST_AT_SUBMISSION.json';write(submission,m);state=json.loads((packet/'attempt_01/WORKER_STATE.json').read_text());assert sha(submission)==state['manifest_sha256'];mi=b/'design/audit_impacts/job-geologist-panning-local-motion-20261001.json';md=json.loads(mi.read_text());md['files']=sorted(set(md['files'])|{rel(submission)});md['validation'].append(dict(command='Original first-motion submission manifest reconstruction verified against worker SHA256',result='PASS',evidence=rel(submission)+'; exact original bytes, not revised current status.'));write(mi,md)
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(d['files']);allowed.update(md['files']);write(allow,sorted(allowed));print('DIRECT312; common base4.5 provisional; original submission manifest hash PASS')
