from pathlib import Path
import json,hashlib,shutil,subprocess,sys,time
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');parent=b/'audit/job_geode_opening_states_v3_20261001';old=parent/'attempt_02';out=parent/'attempt_03'
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-geode-opening-continuity-20261001.json';d=json.loads(ip.read_text());d['scope']+=' Correct the measured15px endpoint base rise by moving the intact320h full endpoint cards down15px in a new disposable attempt03. Shared base515 remains fixed, all authored source pixels/input/progress production remain unchanged. Recheck all10 selected surrounding states at both widths; no source redraw for a placement defect.';d['files']=sorted(set(d['files'])|{rel(out/p) for p in ['.gdignore','capture.gd','study_surface.gd','PROFILE.json','SOURCE_BEFORE.json','PROCESS_RECEIPT.json','executed_correct_base_v143.py']});write(ip,d)
out.mkdir(exist_ok=False);(out/'.gdignore').write_text('');code=(old/'capture.gd').read_text();assert 'res://tmp/geode_opening_v139/native_views/' in code;code=code.replace('res://tmp/geode_opening_v139/native_views/','res://tmp/geode_opening_base_v143/native_views/').replace('res://'+rel(old/'study_surface.gd'),'res://'+rel(out/'study_surface.gd'));(out/'capture.gd').write_text(code,encoding='utf-8',newline='\n')
code=(old/'study_surface.gd').read_text();needle='\tvar half_height := 320.0\n';assert needle in code;code=code.replace(needle,needle+'\t# Whole-card placement: keep the350h closed/intermediate baseline515.\n\tcenter.y += (350.0 - half_height) * 0.5\n');(out/'study_surface.gd').write_text(code,encoding='utf-8',newline='\n');shutil.copyfile(old/'SOURCE_BEFORE.json',out/'SOURCE_BEFORE.json');profile=json.loads((old/'PROFILE.json').read_text());profile.update(previous_attempt=rel(old/'REVIEW.json'),changes='Only full endpoint whole-card centreY+15px:350h intermediate/320h full states share bottom515. Source native pixels, ratios and inherited input/progress are unchanged. No extra crystal drawing or loot. Invitation/contact/action gaps remain separate.');write(out/'PROFILE.json',profile);shutil.copyfile(__file__,out/'executed_correct_base_v143.py')
def cover():
 d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in parent.rglob('*') if p.is_file()});write(ip,d)
cover();native=b/'tmp/geode_opening_base_v143/native_views';native.mkdir(parents=True);before=json.loads((out/'SOURCE_BEFORE.json').read_text());assert len(before)==325 and all(sha(b/p)==h for p,h in before.items())
godot='C:/Users/Peter/AppData/Local/Programs/MermaidReefTools/Godot/4.7.2/godot_console.exe';commands=[('parser',[sys.executable,'-X','utf8','-B','-m','gdtoolkit.parser',rel(out/'capture.gd'),rel(out/'study_surface.gd')]),('inference',[sys.executable,'-X','utf8','-B','tools/lint_inference.py',rel(out/'capture.gd'),rel(out/'study_surface.gd')]),('analyzer',[godot,'--headless','--path',str(b),'--check-only','--script','res://'+rel(out/'capture.gd')]),('native',[godot,'--path',str(b),'--script','res://'+rel(out/'capture.gd')])];rows=[]
for name,cmd in commands:
 so=out/(name+'.stdout.log');se=out/(name+'.stderr.log');so.touch();se.touch();cover();start=time.monotonic()
 with so.open('wb') as a,se.open('wb') as c:
  try:p=subprocess.run(cmd,cwd=b,stdout=a,stderr=c,timeout=180,creationflags=subprocess.CREATE_NO_WINDOW);exit_code=p.returncode;timed=False
  except subprocess.TimeoutExpired:exit_code=None;timed=True
 rows.append(dict(name=name,command=cmd,process_exit=exit_code,timed_out=timed,seconds=time.monotonic()-start,stdout=rel(so),stderr=rel(se)));print(name,exit_code,flush=True)
 if exit_code!=0:print(se.read_text(encoding='utf-8',errors='replace')[-1200:],flush=True);break
passed=len(rows)==4 and all(x['process_exit']==0 for x in rows) and (native/'CAPTURE_RECEIPT.json').is_file() and len(json.loads((native/'CAPTURE_RECEIPT.json').read_text())['views'])==10 and all(sha(b/p)==h for p,h in before.items())
if passed:shutil.copytree(native,out/'native_views')
write(out/'PROCESS_RECEIPT.json',dict(status='PASS_MACHINE_NATIVE_CAPTURE' if passed else 'FAIL_PRESERVED',processes=rows,original325_sources_unchanged=all(sha(b/p)==h for p,h in before.items()),expected_views=10,qualification='Every10 surrounding native views require direct inspection; no complete timed action/route/device/child/owner acceptance.'));cover();d=json.loads(ip.read_text());d['validation'].append(dict(command='Whole-card geode base alignment: parser/inference/official4.7.2 analyzer/native input capture',result='PASS' if passed else 'FAIL',evidence=rel(out/'PROCESS_RECEIPT.json')));write(ip,d);raise SystemExit(0 if passed else 1)
