from pathlib import Path
import datetime, hashlib, html, json, shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_river_join_study_v1_20261001';s=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat()
rv=read(f/'REVIEW_V5.json');views=[]
for width in [1280,1600]:
 m=read(f/'attempt_06'/('MANIFEST_%d.json'%width));assert len(m['views'])==14
 for x in m['views']:
  assert sha(b/x['path'])==x['sha256'];state=x['state'];old=next(q for q in rv['current_native_views'] if q['state']==state and q['dimensions'][0]==width)
  for key in ['material_score','mounted_detail_score','work_bed_context_score','complete_action_score','actor_contact_score','owner_acceptance']:x[key]=old[key]
  dry=state.startswith('isolated_dry') or state=='dry_initial';mixed=state in ['connected_straight','connected_corner','connected_t_branch','connected_cross','partial_json_restored']
  sample=old['sampled_state_score'] if dry else 4.4 if mixed else 4.5
  note=old['evaluation'] if dry else 'Wet river centres now retain calm continuous painted aqua without cut white glints; matching straight and branch surfaces reduce abrupt port-value planes. Small remaining bank/value steps keep the wet detail at4.5 provisional. '
  if mixed:note+='The simultaneously visible isolated dry loop still has conspicuous ochre/lavender port planes4.4, so this complete sampled state remains4.4. Wet improvement does not pass that dry network.'
  elif not dry:note+='This sampled filled network reaches4.5 provisional, with all ground islands and arbitrary paths open. It remains an inclusive refinement priority and grants no actor/full-room/complete-action acceptance.'
  x.update(id='RIVER-JOIN-V6-%d-%s'%(width,state.upper()),direct_review=True,sampled_state_score=sample,network_score=None if state in ['dry_initial','isolated_dry'] else old['network_score'] if dry else 4.5,wet_network_score=None if dry else 4.5,dry_network_score=4.4 if mixed or state=='isolated_dry_cross' else old['network_score'] if dry else None,priority=sample<=4.5,evaluation=note,reviewed_utc=now)
  views.append(x)
rv.update(schema='reef.river-join-study.v6',reviewed_utc=now,status='ALL28_V6_NATIVE_DIRECT_WET4_5_PROVISIONAL_DRY_LOOP4_4_REMAINS',current_native_views=views,direct_native_views_all_attempts=134,prior_reviews=rv['prior_reviews']+['audit/job_river_join_study_v1_20261001/REVIEW_V5.json'],qualification='All28 V6 native stills directly inspected at both widths;134 direct across preserved attempts. Soil4.6; wet detail4.5 provisional improves failed4.4. Dry isolated loops4.4 retain port-value seams and keep mixed states4.4. No actor/room/production/full-action/device/child/owner/all-game acceptance.');write(f/'REVIEW_V6.json',rv);write(f/'attempt_06/DIRECT_REVIEW.json',rv)
style='body{font:17px/1.5 system-ui;background:#e9eeef;color:#292542;margin:auto;max-width:1180px;padding:26px}img{display:block;max-width:100%;height:auto}article{background:white;padding:18px;margin:24px 0;border-radius:12px}code{overflow-wrap:anywhere}a{color:#45318b}'
cards=''.join('<article id="%s"><h2>%s · sampled state%s/5</h2><img src="%s" alt="%s" loading="eager"><p>%s</p><p>Bed4.6; wet detail%s. Full action/actor/room/owner unassigned.</p><code>%s</code></article>'%(x['id'],x['id'],x['sampled_state_score'],x['path'].split('job_river_join_study_v1_20261001/')[1],x['id'],html.escape(x['evaluation']),x['wet_network_score'],x['sha256']) for x in views)
(f/'index_v6.html').write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>River V6 water review</title><style>'+style+'</style><h1>River V6: calmer painted water, remaining dry seams</h1><p>Every28 latest native state directly inspected;134 direct preserved. Wet detail4.5 provisional, dry loop4.4 remains below floor, painted soil4.6. Mixed states remain4.4 because the weak dry loop is simultaneously visible.</p><p><a href="index_v5.html">V5 and prior failures</a> · <a href="REVIEW_V6.json">Individual written reviews and hashes</a></p><p>Both actual inherited-input captures pass JSON restoration, source-connected wetting/arbitrary paths/single completion. No production binding, actor/room/full action/device/child/owner pass.</p>'+cards,encoding='utf-8',newline='\n')
for folder in ['wet_attempt_02','straight_attempt_02']:
 p=s/folder/'TECHNICAL_DERIVATIVE.json';d=read(p);assert sha(b/d['path'])==d['sha256'];d.update(direct_review=True,source_score=4.6,reviewed_utc=now,qualification='Complete1024 RGBA derivative directly inspected, full contours and broad painted surface retained. Whole uniform transform only, no alpha cleanup. Source4.6; V6 wet detail4.5 provisional, dry loop4.4 below floor.');write(p,d)
target='assets_src/imagegen/geologist_river_junctions_v1_20261001/dry_attempt_01/native_generated.png';ref='assets_src/imagegen/geologist_river_components_v1_20261001/attempt_02/native_generated.png';assert sha(b/target)=='86eac09710c17cbf298068ae6fe9480a49571bd9a776f4a2fac13b79ffff926b'
a=s/'dry_attempt_02';a.mkdir(exist_ok=False)
prompt='''Use case: precise-object-edit
Asset type: transparent 2D painted dry river junction atlas for a preschool storybook game.
Image1 is the EDIT TARGET: four dry excavated earth shapes: endcap, elbow, T and cross. Preserve the exact four-object layout, outline silhouettes, channel widths, native positions, open ports, ochre rounded raised banks, lavender bank shadows, plum contours and transparent exterior. Image2 is the matching straight-channel MATERIAL REFERENCE; use only the upper dry channel’s earth colour.
Change only the recessed dry earth painting inside all four shapes, to make repeat connections consistent. Use one even medium-light golden ochre base across the entire interior of every shape and every open port, matching the centre of the upper dry reference strip. Retain low-contrast broad hand-painted pigment bands. Remove the directional interior dark-to-light gradients and bright diagonal streaks that change abruptly when rotated. Every open port has the same calm golden earth value as every other port. Keep the gentle narrow plum/lavender wall recess directly alongside the raised banks; keep it local to the wall, not crossing an open port or spreading across the channel floor. Preserve the existing warm rounded banks and outer outlines as closely as possible.
Polished 2D illustrated children’s storybook raster painting; full intact authored contours, calm readable material, no aqua water, no vector replacement, no photorealism, no 3D. Exactly the same four objects and open ports, no labels, no extra props, no ground background. This is a targeted interior-lighting correction, not a redesign.
'''
p=s/'PROMPT_DRY_ATTEMPT_02.txt';p.write_text(prompt,encoding='utf-8',newline='\n');write(a/'GENERATION_PENDING.json',dict(status='PRE_GENERATION_NAMED_GAP',attempt=2,method='BUILTIN_CODEX_IMAGEGEN_TARGETED_DRY_PORT_LIGHTING_EDIT',prompt_path=p.relative_to(b).as_posix(),prompt_sha256=sha(p),reference_paths=[target,ref],reference_sha256=[sha(b/target),sha(b/ref)],transparent_background=True,runtime_bound=False,named_gap='Every134 isolated native river still directly reviewed. V6 wet detail4.5 provisional but actual dry loop4.4 has conspicuous ochre/lavender terminal-plane values across rotated junctions, keeping mixed states4.4. Existing same-family source4.6 fails repetition; target only recessed dry-floor lighting, preserve banks and silhouettes.',review_evidence='audit/job_river_join_study_v1_20261001/REVIEW_V6.json'))
shutil.copyfile(__file__,f/Path(__file__).name)
for name,folder in [('job-geology-river-junction-source-20261001',s),('job-geology-river-join-study-20261001',f)]:
 ip=b/('design/audit_impacts/'+name+'.json');d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in folder.rglob('*') if x.is_file()});d['acceptance_gaps']='Every134 native isolated-study still directly reviewed; bed4.6/wet detail4.5 provisional/dry loops4.4 below floor. Production, actor, room, full action/training/story/device/child/owner/all-game acceptance unfinished.';write(ip,d)
print(prompt)
