from pathlib import Path
import datetime, hashlib, html, json, shutil, subprocess

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f=b/'audit/job_river_join_study_v1_20261001'
s=b/'assets_src/imagegen/geologist_river_bed_v1_20261002'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
prior=read(f/'REVIEW_V4.json')
scores={'dry_initial':4.6,'isolated_dry':4.6,'isolated_dry_straight':4.5,'isolated_dry_corner':4.5,'isolated_dry_t':4.5,'isolated_dry_cross':4.4}
views=[]
for width in [1280,1600]:
 m=read(f/'attempt_05'/('MANIFEST_%d.json'%width));assert len(m['views'])==14
 assert read(f/'runtime_gate'/('capture%dv5.receipt.json'%width))['process_exit']==0
 for x in m['views']:
  assert sha(b/x['path'])==x['sha256'];state=x['state'];score=scores.get(state,4.4)
  if state in ['dry_initial','isolated_dry']:
   note='The complete painted top-down soil replaces the flat panel. Rounded plum contour, clustered edge stones, broad warm earth bands and clear aqua source match the painted family. Entire actual grid lies within the quiet soil centre at this width, with no bank, stone or viewport clipping. Isolated state4.6; no connected-network, actor, full room or timed-action acceptance.'
  elif state in ['isolated_dry_straight','isolated_dry_corner','isolated_dry_t']:
   note='Dry channel retains one continuous open centre and smaller port shoulders; painted soil now supports the full grid without front-face overlap or corner-stone obstruction. Small bank/value differences keep this sampled joined geometry4.5 provisional and an inclusive refinement priority.'
  elif state=='isolated_dry_cross':
   note='Dry loop and four-way junction are continuous and legible on the complete soil bed. Abrupt ochre/lavender terminal-plane values remain visible around several ports. Joined network4.4 still below floor; bed4.6 is a separate improvement.'
  else:
   note='Source-connected aqua water and preserved actual topology are clear on the complete earth field. Straight segments and rotated branches still meet at abrupt glint/value planes, especially at right-angle and dense-loop junctions. Wet network4.4 remains below floor; earth field4.6 does not pass those joins.'
   if state=='partial_json_restored':note+=' The exact partial topology survives actual JSON restoration; machine save success is independent of art quality.'
   if state in ['connected_complete','quiet_single_completion']:note+=' Actual completion remains exactly once, with no repeat reward; this is a sampled still, not a complete acting pass.'
  x.update(id='RIVER-JOIN-V5-%d-%s'%(width,state.upper()),direct_review=True,material_score=4.6,mounted_detail_score=4.6,sampled_state_score=score,network_score=None if state in ['dry_initial','isolated_dry'] else score,work_bed_context_score=4.6,sampled_wetting_score=4.6 if state.startswith('connected') or state in ['formerly_isolated_now_wet','quiet_single_completion'] else None,complete_action_score=None,actor_contact_score=None,owner_acceptance=None,priority=score<=4.5,evaluation=note,reviewed_utc=now)
  views.append(x)
rv=dict(schema='reef.river-join-study.v5',baseline=prior['baseline'],reviewed_utc=now,status='ALL28_V5_NATIVE_STILLS_DIRECTLY_REVIEWED_BED4_6_WET_NETWORK4_4_BELOW_FLOOR',current_native_views=views,prior_reviews=['audit/job_river_join_study_v1_20261001/'+p for p in ['REVIEW.json','REVIEW_V3.json','REVIEW_V4.json']],direct_native_views_all_attempts=106,inherited_input_flow='PASS_BOTH14_STATE_CAPTURES_REAL_INPUT_JSON_RESTORE_SINGLE_COMPLETION',production_binding=False,qualification='Each of the28 latest native stills directly inspected separately at1280 and1600. Prior78 direct stills retained: V1 failed helper2,V2 overlay20,V3 port-width28,V4 scale28. New bed4.6 and isolated initial4.6; selected dry joints4.5 provisional; dry cross/wet network4.4 remain priorities. No actor, actual room, routes/training/story, complete timed action, phone, child, owner or all-game acceptance.')
write(f/'REVIEW_V5.json',rv);write(f/'attempt_05/DIRECT_REVIEW.json',rv)
style='body{font:17px/1.5 system-ui;background:#e9eeef;color:#292542;margin:0 auto;max-width:1180px;padding:26px}img{display:block;max-width:100%;height:auto}article{background:white;padding:18px;margin:24px 0;border-radius:12px}code{overflow-wrap:anywhere}a{color:#45318b}'
cards=''.join('<article id="%s"><h2>%s · %s/5</h2><img src="%s" alt="%s" loading="eager"><p>%s</p><p>Painted soil4.6. Full action, actor contact and owner acceptance unassigned.</p><code>%s</code></article>'%(x['id'],x['id'],x['sampled_state_score'],x['path'].split('job_river_join_study_v1_20261001/')[1],x['id'],html.escape(x['evaluation']),x['sha256']) for x in views)
(f/'index_v5.html').write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>River join study V5</title><style>'+style+'</style><h1>River V5: painted earth field, remaining water seams</h1><p>Every28 current native still directly reviewed;106 direct across preserved attempts. Soil and isolated initial state4.6, selected dry joins4.5 provisional, dry cross and wet network4.4 below floor.</p><p><a href="index_v4.html">Prior scale study</a> · <a href="index_v3.html">Prior port-width study</a> · <a href="index.html">Earlier overlay/helper studies</a> · <a href="REVIEW_V5.json">Individual scores and hashes</a> · <a href="../../assets_src/imagegen/geologist_river_bed_v1_20261002/index.html">New complete soil source</a></p><p>Inherited touch/isolated-dry/source-connected flow/arbitrary branches/JSON restore/single completion pass at1280 and1600. All349 production files remain the I checkpoint bytes. Actor/room/training/story/complete timed action/device/child/owner review remains open.</p>'+cards,encoding='utf-8',newline='\n')
tech=read(s/'TECHNICAL_DERIVATIVES.json');d=tech['derivatives'][0];assert sha(b/d['path'])==d['sha256']
d.update(direct_review=True,source_score=4.6,evaluation='Complete1024x512 RGBA derivative directly inspected: full rounded authored contour and all corner-stone clusters retained, quiet broad painted field, no visible clipping or destructive cleanup. Source4.6 and V5 bed-context4.6; source review does not pass wet joins4.4 or full action.',reviewed_utc=now)
tech['status']='COMPLETE_CANVAS_DERIVATIVE_DIRECTLY_REVIEWED4_6_UNBOUND';write(s/'TECHNICAL_DERIVATIVES.json',tech)
native=read(s/'attempt_01/REVIEW.json')
sr=dict(schema='reef.river-bed-source.v1',baseline=prior['baseline'],status='SOURCE_AND_V5_ISOLATED_BED4_6_UNBOUND_WET_JOINS4_4_PENDING',native_originals=[native],technical_derivatives=[d],qualification='One complete generated top-down ground prop. Both exact native and uniform complete-canvas derivative directly reviewed. V5 inspected bed-context4.6 at both widths; no production, full-room native2048 coverage, actor/contact, complete-action, device, child or owner approval.',latest_refinement=dict(report='audit/job_river_join_study_v1_20261001/index_v5.html',note='Each28 latest native state directly reviewed,106 direct total. Bed4.6, selected dry joins4.5 provisional, wet network4.4. No actual production binding or complete-action acceptance.'))
write(s/'REVIEW.json',sr)
scards=''.join('<article><h2>%s · 4.6/5 source</h2><img src="%s" alt="Complete painted river soil bed"><p>%s</p><code>%s</code></article>'%(label,row.get('native_path',row.get('path')).split('geologist_river_bed_v1_20261002/')[1],html.escape(row['evaluation']),row['sha256']) for label,row in [('Native original1774×887',native),('Whole-canvas derivative1024×512',d)])
(s/'index.html').write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Painted river earth source</title><style>'+style+'</style><h1>Painted river earth field</h1><p>'+html.escape(sr['qualification'])+'</p><p><a href="REUSE_INVENTORY.json">Why existing soil and slab failed this grid</a> · <a href="PROMPT_ATTEMPT_01.txt">Exact ImageGen prompt</a> · <a href="REVIEW.json">Source scores and provenance</a> · <a href="../../../audit/job_river_join_study_v1_20261001/index_v5.html">Every28 mounted study state</a></p>'+scards,encoding='utf-8',newline='\n')
# Correct relative link: source folder is three levels below repository root.
p=s/'index.html';t=p.read_text(encoding='utf-8').replace('../../../audit/','../../../audit/');p.write_text(t,encoding='utf-8',newline='\n')
code=(b/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v23.py').read_text(encoding='utf-8')
needle="for q in items.values():\n p=q['path']\n if p not in hashes:";assert code.count(needle)==1
block='''\n# V24 wide-earth source additions, no duplicate region count for the same whole prop.\nbed_prefix='assets_src/imagegen/geologist_river_bed_v1_20261002'\nbed=read(bed_prefix+'/REVIEW.json')\nfor num,x in enumerate(bed['native_originals']+bed['technical_derivatives'],1):\n p=x.get('native_path',x.get('path'));actual=hashlib.sha256((r/p).read_bytes()).hexdigest()\n items[p]=dict(id='GEO-RIVER-BED-WHOLE-%02d'%num,aliases=[],kind='source',path=p,earlier_sha256=actual,historical_source_score=x['source_score'],evaluation=x['evaluation'],refinement='Preserve this complete authored earth field. Bed-context4.6 in both isolated V5 views is separate from water joins4.4 and actor/contact/full-room/action review.',families=['Geologist river earth','Unbound source study'],original_reports=[bed_prefix+'/index.html'],source_qualification=bed['qualification'],preview_path=p,native_reference_observations=[],runtime_binding_state='UNBOUND_SOURCE_STUDY',latest_refinement=bed['latest_refinement'])\nfor q in items.values():\n if q['id'].startswith('GEO-RIVER-'):\n  q['latest_refinement']=dict(report='audit/job_river_join_study_v1_20261001/index_v5.html',note='Every106 isolated native study still directly reviewed. Source4.6, bed4.6, dry selected4.5 provisional, wet joints4.4. All349 production bytes unchanged; full actor/room/action/owner acceptance remains open.')\n\n'''
code=code.replace(needle,block+needle).replace('build_current_job_item_register_v23.py','build_current_job_item_register_v24.py').replace('job-geology-river-junction-source-20261001.json','job-geology-river-bed-source-20261002.json')
target=b/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v24.py';assert not target.exists();target.write_text(code,encoding='utf-8',newline='\n');shutil.copyfile(target,b/'audit/job_artwork_refinement_live/review_tools'/target.name)
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(target)],cwd=b,check=True)
licenses=b/'ASSET_LICENSES.md';text=licenses.read_text(encoding='utf-8');add=[]
for file in sorted(s.rglob('*.png')):
 p=file.relative_to(b).as_posix()
 if '`'+p+'`' not in text:add.append('| `'+p+'` | Owner-commissioned built-in Codex ImageGen; project material references recorded | Project-generated review artwork; owner acceptance pending | assets_src/imagegen/geologist_river_bed_v1_20261002/REVIEW.json | Native preserved; derivative one uniform complete1774×887→1024×512 RGBA transform. No crop/warp/alpha repair. Source4.6 and isolated bed-context4.6, unbound; not full-room or wet-network acceptance. |')
for file in sorted((f/'attempt_05').rglob('*.webp')):
 p=file.relative_to(b).as_posix()
 if '`'+p+'`' not in text:add.append('| `'+p+'` | Exact native Godot4.7.2 Mobile-rendered review screenshot; original source provenance retained | Project review evidence | audit/job_river_join_study_v1_20261001/index_v5.html | Native lossless WebP preserved; every current still directly reviewed. Isolated inherited-input study, not runtime source or full-action acceptance. |')
licenses.write_text(text+'\n'+'\n'.join(add)+'\n',encoding='utf-8',newline='\n')
paragraph='River earth continuation (2026-10-02): [complete painted ground source](../assets_src/imagegen/geologist_river_bed_v1_20261002/index.html) and [all106 preserved native study stills](job_river_join_study_v1_20261001/index_v5.html) directly reviewed. New source/isolated bed4.6 fits the full grid at both widths; selected dry joins4.5 provisional, dry cross/wet network4.4 remain priorities. Both14-state actual inherited-input captures pass with JSON restore and single completion. All349 production bytes unchanged; no new runtime binding, full-suite/hosted/actor/room/training/story/action/device/child/owner/global acceptance or finding closure. RegisterV24 has1610 entries/1216 source files/328 poses/38 runtime regions/28 source regions/584 inclusive priorities/388 unassigned opinions. [Impact](../design/audit_impacts/job-geology-river-bed-source-20261002.json).'
p=b/'audit/MASTER_AUDIT_2026-08-09.md';t=p.read_text(encoding='utf-8');assert paragraph not in t;parts=t.split('\n',1);p.write_text(parts[0]+'\n\n'+paragraph+'\n'+parts[1],encoding='utf-8',newline='\n')
p=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';t=p.read_text(encoding='utf-8');start=t.index('## MA-PLAY-004');end=t.find('\n## ',start+1);assert end>start;t=t[:end]+'\nRiver earth evidence (2026-10-02): [all106 native studies](../job_river_join_study_v1_20261001/index_v5.html) retain every prior failure. New complete earth source and directly inspected V5 mounted bed4.6 at both widths replace the flat-bed study3.2; dry cross/wet network4.4 still fail the floor. Actual input/save/single-completion pass. All349 production bytes unchanged; no actor/room/full action/training/story/device/child/owner evidence or finding closure.\n'+t[end:];p.write_text(t,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8');t+='\n| `audit/job_river_join_study_v1_20261001/index_v5.html` | 🟣 | `CANDIDATE`; every106 preserved native study still directly reviewed, latest28 separately at1280/1600. Painted earth/source4.6, selected dry joins4.5 provisional, dry cross/wet network4.4 remain priorities. Actual inherited input/save/single completion pass; production unchanged. Full actor/room/action/device/child/owner acceptance open. |\n| `assets_src/imagegen/geologist_river_bed_v1_20261002/index.html` | 🟣 | `CANDIDATE`; exact1774×887 native ImageGen ground prop and uniform complete1024×512 derivative directly reviewed4.6; isolated V5 bed-context4.6. Reuse gap/provenance retained; unbound, no full-room background or wet-network/action/owner acceptance. |\n';p.write_text(t,encoding='utf-8',newline='\n')
p=b/'audit/job_artwork_refinement_live/index.html';t=p.read_text(encoding='utf-8');t=t.replace('All78 individually scored native study states','All106 individually scored native study states').replace('../job_river_join_study_v1_20261001/index_v4.html','../job_river_join_study_v1_20261001/index_v5.html').replace('wet joined network4.4 and flat work bed3.2 remain priorities.','wet joined network4.4 remains a priority; the complete earth field now scores4.6 in both isolated viewport studies.');p.write_text(t,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/Path(__file__).name)
snapshot=read(b/'audit/job_geology_painted_work_v1_20261001/full_ci_v1/SOURCE_BEFORE.json');rows=snapshot['source_files'];assert len(rows)==349
checked=[dict(path=x['path'],baseline_sha256=x['sha256'],current_sha256=sha(b/x['path'])) for x in rows];assert all(x['baseline_sha256']==x['current_sha256'] for x in checked)
write(f/'PRODUCTION_UNCHANGED_V5.json',dict(baseline=prior['baseline'],checked_utc=now,status='ALL349_LITERAL_PRODUCTION_FILES_EXACT_I_BYTES',source_files=checked,qualification='Exact byte comparison to I82/82 unmodified full-suite source snapshot, not a repeated full-suite or hosted/visual/owner pass.'))
write(f/'LIBRARY_RENDER_QA_V23.json',dict(checked_utc=now,url='http://127.0.0.1:8880/audit/job_artwork_refinement_live/all_items.html?revision=register-v23',observed={'query':'GEO-RIVER-','filter':'all','cards':22,'loaded':22,'pending':0,'broken':0,'document_width':1265,'viewport_width':1280},qualification='Read-only browser DOM inspection of current V23 filtered page before V24 update. Every source card image loaded, no horizontal overflow; no saved browser screenshot or actual-use acceptance claimed.'))
shared={'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/index.html','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v24.py','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v24.py'}
for name,folder in [('job-geology-river-join-study-20261001',f),('job-geology-river-junction-source-20261001',b/'assets_src/imagegen/geologist_river_junctions_v1_20261001'),('job-geology-river-bed-source-20261002',s)]:
 ip=b/('design/audit_impacts/'+name+'.json');d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in folder.rglob('*') if p.is_file()}|shared);d['acceptance_gaps']='Every106 isolated native study still directly reviewed; wide source/bed4.6, selected dry joints4.5 provisional, wet joins4.4 below floor. No new production/actor/room/training/story/full-action/device/child/owner/global acceptance or lifecycle closure.';d['validation'].append(dict(command='V5 exact native direct review and unchanged production comparison',result='PASS',evidence='audit/job_river_join_study_v1_20261001/REVIEW_V5.json;PRODUCTION_UNCHANGED_V5.json. All28 current views directly reviewed, total106; exact349 bytes unchanged. Visual water seams remain below floor.'));write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';a=read(allow);assert isinstance(a,list);write(allow,sorted(set(a)|{p.relative_to(b).as_posix() for folder in [f,s] for p in folder.rglob('*') if p.is_file()}))
print('Recorded every28 V5 native still, source derivative4.6, V24 register, exact349 production bytes; no wet-network pass.')
