from pathlib import Path
import datetime, hashlib, html, json, re, shutil, subprocess

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_river_join_study_v1_20261001';s=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001'
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
prev=read(f/'REVIEW_V3.json');notes={x['state']:x['evaluation'] for x in prev['current_native_views']}
scores={'dry_initial':4.3,'isolated_dry':4.3,'isolated_dry_straight':4.5,'isolated_dry_corner':4.5,'isolated_dry_t':4.5,'isolated_dry_cross':4.4,'connected_straight':4.4,'connected_corner':4.4,'connected_t_branch':4.4,'connected_cross':4.4,'partial_json_restored':4.4,'formerly_isolated_now_wet':4.4,'connected_complete':4.4,'quiet_single_completion':4.4}
notes.update(isolated_dry_corner='Uniform branch scale now matches most adjacent endcap bank widths; dry elbow is continuous with small handmade value differences. Isolated sampled geometry4.5 provisional; flat work bed3.2 and complete action remain open.',isolated_dry_t='Dry T retains one open centre and materially smaller port shoulders; small bank/value changes are visible. Isolated sample4.5 provisional and still an inclusive priority.',isolated_dry_cross='Four-way dry loop joins are narrower and continuous. Several terminal planes remain recognizable from abrupt ochre/lavender value transitions.',connected_corner='Uniform scale removes the conspicuous elbow shoulders. Water has a visible colour/highlight step at the old-strip/new-elbow boundary; clear flow is not seamless painted water.',connected_t_branch='Wet T branches now match port widths more closely, but the central water and old straight segment retain abrupt value changes.',connected_cross='Open four-way water remains source-connected. Several port-plane highlight/value changes and small bank transitions remain visible.',partial_json_restored='JSON restores the exact actual cross topology and source-connected wetting. Same mounted water/value seam priorities4.4 remain; save success is separate.',formerly_isolated_now_wet='Actual input connects and fills the formerly dry network, preserving arbitrary branches. Wet interiors are continuous, but repeated glint changes and bank/value terminal planes remain visible.',connected_complete='Actual arbitrary route reaches the target and completes once. Water remains continuous around ground islands; repeated tile lighting/highlight differences and the flat board keep the assembled study below floor.',quiet_single_completion='Repeated touch is quiet and completion stays exactly once. The same completed drawing still has water/highlight and bank-value seams; actor/contact/full action are absent.')
views=[]
for width in [1280,1600]:
 m=read(f/'attempt_04'/('MANIFEST_%d.json'%width));assert len(m['views'])==14
 for x in m['views']:
  assert sha(b/x['path'])==x['sha256'];state=x['state']
  x.update(id='RIVER-JOIN-V4-%d-%s'%(width,state.upper()),direct_review=True,material_score=4.6,mounted_detail_score=4.5,sampled_state_score=scores[state],network_score=None if state in ['dry_initial','isolated_dry'] else scores[state],work_bed_context_score=3.2,sampled_wetting_score=4.6 if state.startswith('connected') or state in ['formerly_isolated_now_wet','quiet_single_completion'] else None,complete_action_score=None,actor_contact_score=None,owner_acceptance=None,priority=True,evaluation=notes[state],reviewed_utc=now)
  views.append(x)
rv={'schema':'reef.river-join-study.v4','baseline':'40b1c7bfe025f284507c586fea61b9dd76b61423','reviewed_utc':now,'status':'ALL28_V4_NATIVE_STILLS_DIRECTLY_REVIEWED_WET_NETWORK4_4_BELOW_FLOOR','current_native_views':views,'prior_reviews':['audit/job_river_join_study_v1_20261001/REVIEW.json','audit/job_river_join_study_v1_20261001/REVIEW_V3.json'],'direct_native_views_all_attempts':78,'inherited_input_flow':'PASS_BOTH14_STATE_CAPTURES_REAL_INPUT_JSON_RESTORE_SINGLE_COMPLETION','production_binding':False,'qualification':'Every28 latest actual native still directly inspected at each width. Total78 direct isolated-study stills includes V1 failed helper2,V2 overlay20,V3 port-width28,V4 scale28. Source4.6/dry sample4.5/wet joins4.4/bed3.2 are separate opinions. No actor, actual room, routes/training/story, full timed action, device, child, owner or all-game acceptance.'}
write(f/'REVIEW_V4.json',rv);write(f/'attempt_04'/'DIRECT_REVIEW.json',rv)
style='body{font:17px/1.5 system-ui;background:#e9eeef;color:#292542;margin:0 auto;max-width:1180px;padding:26px}img{display:block;max-width:100%;height:auto}article{background:white;padding:18px;margin:24px 0;border-radius:12px}code{overflow-wrap:anywhere}a{color:#45318b}'
cards=''.join('<article id="%s"><h2>%s · %s/5</h2><img src="%s" alt="%s" loading="lazy"><p>%s</p><p>Painted material4.6; flat bed3.2. Full action, actor contact and owner acceptance unassigned.</p><code>%s</code></article>'%(x['id'],x['id'],x['sampled_state_score'],x['path'].split('job_river_join_study_v1_20261001/')[1],x['id'],html.escape(x['evaluation']),x['sha256']) for x in views)
(f/'index_v4.html').write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>River join study V4</title><style>'+style+'</style><h1>River join study V4: continuous channels, remaining painted seams</h1><p>Every28 current native still directly reviewed;78 direct across preserved attempts. Source material4.6, selected isolated dry joins4.5 provisional, wet network4.4 and flat bed3.2. All scores have separate evidence boundaries.</p><p><a href="index_v3.html">Earlier28 port-width views</a> · <a href="index.html">Earlier22 overlay/helper views</a> · <a href="REVIEW_V4.json">Every individual written score/hash</a> · <a href="../../assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html">Eight individual wet/dry sources</a></p><p>Inherited one-finger stroke/isolated-dry/source-connected flow/arbitrary branches/JSON restore/single completion pass at1280 and1600. Actual parent production graphics are unchanged; full action/actor/room/phone/owner review remains open.</p>'+cards,encoding='utf-8')
d=read(s/'REVIEW.json');d['latest_refinement']={'report':'audit/job_river_join_study_v1_20261001/index_v4.html','note':'Every28 V4 native state directly inspected; selected dry joins4.5 provisional, wet network4.4, flat bed3.2. Every78 preserved native study still directly reviewed; no production or full-action acceptance.'};d['status']='SOURCE4_6_UNBOUND_ACTUAL_V4_WET_JOINS4_4_REJECTED';write(s/'REVIEW.json',d)
p=s/'index.html';t=p.read_text(encoding='utf-8').replace('index_v3.html','index_v4.html').replace('All28 actual grid states and join scores','All28 latest grid states and join scores').replace('Actual V3 joins4.0–4.4.','Actual V4 wet joins4.4; dry selected4.5 provisional.');p.write_text(t,encoding='utf-8',newline='\n')
# Retain immutable historical V22 while adding distinct individually scored source items.
src=b/'audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v22.py';code=src.read_text(encoding='utf-8')
block='''
# V23 bounded junction additions; prior source scores do not pass actual joins.
junction_prefix='assets_src/imagegen/geologist_river_junctions_v1_20261001'
junction=read(junction_prefix+'/REVIEW.json')
for num,x in enumerate(junction['native_originals']+junction['technical_derivatives'],1):
 p=x.get('native_path',x.get('path'));actual=hashlib.sha256((r/p).read_bytes()).hexdigest()
 items[p]=dict(id='GEO-RIVER-JUNCTION-WHOLE-%02d'%num,aliases=[],kind='source',path=p,earlier_sha256=actual,historical_source_score=4.6,evaluation='Complete painted junction atlas directly inspected: four dry or wet open-interior endcap/elbow/T/cross objects. Native original or uniform complete1024 derivative preserved. Source4.6 does not pass actual wet joins4.4 or flat bed3.2.',refinement='Continue shared painted port lighting/value seams and actual work context; do not accept a joined network from the isolated source score.',families=['Geologist river junctions','Unbound source study'],original_reports=[junction_prefix+'/index.html'],source_qualification=junction['qualification'],preview_path=p,native_reference_observations=[],runtime_binding_state='UNBOUND_SOURCE_STUDY',latest_refinement=junction['latest_refinement'])
for x in junction['components']:
 items[x['id']]=dict(id=x['id'],aliases=[],kind='source object region',path=x['path'],region=x['region'],source_dimensions=x['source_dimensions'],earlier_sha256=x['sha256'],historical_source_score=x['source_score'],evaluation=x['evaluation'],refinement='Source geometry4.6 has open ports. Actual joined lighting/width/value and flat work bed remain independent priorities; no production binding.',families=['Geologist river junctions','Individual unbound component'],original_reports=[junction_prefix+'/index.html#'+x['id']],source_qualification=x['qualification'],preview_path=x['path'],native_reference_observations=[],runtime_binding_state='UNBOUND_SOURCE_STUDY',latest_refinement=junction['latest_refinement'])
for q in items.values():
 if q['id'].startswith('GEO-RIVER-'):
  q['latest_refinement']=dict(report='audit/job_river_join_study_v1_20261001/index_v4.html',note='Every78 isolated native study still directly reviewed. Earlier overlay3.6–3.9 rejected; V3 port steps4.0–4.4 rejected; V4 selected dry4.5 provisional/wet4.4/flat bed3.2. Production/actor/full-action/owner scores stay separate.')

'''
needle="for q in items.values():\n p=q['path']\n if p not in hashes:";assert code.count(needle)==1;code=code.replace(needle,block+needle)
code=code.replace('build_current_job_item_register_v22.py','build_current_job_item_register_v23.py').replace('and 20 source-object regions','and 28 source-object regions').replace('plus20 source-object regions including six embedded geode details and six river candidates','plus28 source-object regions including six embedded geode details, six first river candidates and eight dry/wet junctions').replace('job-geology-river-painted-source-20261001.json','job-geology-river-junction-source-20261001.json')
target=b/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v23.py';assert not target.exists();target.write_text(code,encoding='utf-8',newline='\n');shutil.copyfile(target,b/'audit/job_artwork_refinement_live/review_tools'/target.name)
# Keep exact current source snapshot separate from the inherited I full-CI result.
snapshot=read(b/'audit/job_geology_painted_work_v1_20261001/full_ci_v1/SOURCE_BEFORE.json');rows=snapshot['source_files'];assert len(rows)==349
checked=[dict(path=x['path'],baseline_sha256=x['sha256'],current_sha256=sha(b/x['path'])) for x in rows];assert all(x['baseline_sha256']==x['current_sha256'] for x in checked)
write(f/'PRODUCTION_UNCHANGED_V4.json',dict(baseline='40b1c7bfe025f284507c586fea61b9dd76b61423',checked_utc=now,status='ALL349_LITERAL_PRODUCTION_FILES_EXACT_I_BYTES',source_files=checked,qualification='No production implementation or asset change since the I82/82 unmodified full suite. This is an exact byte comparison, not a repeated full-suite, hosted, visual or owner pass.'))
licenses=b/'ASSET_LICENSES.md';text=licenses.read_text(encoding='utf-8');add=[]
for file in sorted(s.rglob('*.png')):
 p=file.relative_to(b).as_posix()
 if '`'+p+'`' not in text:add.append('| `'+p+'` | Owner-commissioned built-in Codex ImageGen; exact recorded project material references | Project-generated review artwork; owner acceptance pending | assets_src/imagegen/geologist_river_junctions_v1_20261001/REVIEW.json | Original preserved; complete uniform1254→1024 RGBA transform only for derivative. Source4.6, unbound; no alpha/paint repair or actual joined-network acceptance. |')
for file in sorted(f.rglob('*.webp')):
 p=file.relative_to(b).as_posix()
 if '`'+p+'`' not in text:add.append('| `'+p+'` | Exact native Godot4.7.2 Mobile-rendered review screenshot; underlying project source provenance retained | Project review evidence | audit/job_river_join_study_v1_20261001/index_v4.html | Native lossless WebP preserved, no pixel edits; isolated actual-inherited-input study, not runtime source or complete-action acceptance. |')
licenses.write_text(text+'\n'+'\n'.join(add)+'\n',encoding='utf-8',newline='\n')
paragraph='River junction continuation (2026-10-02): [eight individual wet/dry painted sources](../assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html) preserve two native originals/two uniform1024 derivatives, all source4.6 unbound. [All78 isolated native study stills](job_river_join_study_v1_20261001/index_v4.html) directly reviewed: overlay joins3.6–3.9 rejected; V3 port steps4.0–4.4 rejected; V4 selected dry joins4.5 provisional and wet network4.4/flat bed3.2 remain priorities. Inherited real-input flow, arbitrary branches, JSON restore and single completion pass at both widths; all349 production files still match checkpoint40b1c7bf. No new production/full-suite/hosted/actor/room/training/story/device/child/owner/global pass or finding closure. RegisterV23 adds four source files/eight object regions; individual mounted/action scores remain qualified in the specific reports. [Study impact](../design/audit_impacts/job-geology-river-join-study-20261001.json), [source impact](../design/audit_impacts/job-geology-river-junction-source-20261001.json).'
p=b/'audit/MASTER_AUDIT_2026-08-09.md';t=p.read_text(encoding='utf-8');assert paragraph not in t;parts=t.split('\n',1);p.write_text(parts[0]+'\n\n'+paragraph+'\n'+parts[1],encoding='utf-8',newline='\n')
p=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';t=p.read_text(encoding='utf-8');start=t.index('## MA-PLAY-004');end=t.find('\n## ',start+1);assert end>start
history='\nRiver artwork evidence (2026-10-02): [all78 isolated native river studies](../job_river_join_study_v1_20261001/index_v4.html) and [eight dry/wet source objects](../../assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html) directly inspected. Source4.6; V4 wet network4.4 and flat bed3.2 fail the floor, selected dry joins4.5 provisional. Real inherited input/flow/JSON restore/single completion pass at both widths; all349 I production bytes unchanged. Absent actor/contact/full room/training/story/complete timed action/device/child/owner evidence means this drawing study cannot close MA-PLAY-004 or MA-VIS-006. Earlier failures retained.\n'
t=t[:end]+history+t[end:];p.write_text(t,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8');t+='\n| `audit/job_river_join_study_v1_20261001/index_v4.html` | 🟣 | `CANDIDATE`; every78 preserved isolated native still directly reviewed, current28 states at1280/1600. Overlay3.6–3.9, V3 port steps4.0–4.4 rejected; V4 selected dry4.5 provisional/wet4.4/flatbed3.2. Actual inherited input/flow/save/singlecompletion passes; all349 production bytes unchanged. No actor/room/full action/training/story/device/child/owner/global acceptance. |\n| `audit/job_river_join_study_v1_20261001/index_v3.html` | 🔵 | `SUPPORTING_CURRENT`; all28 directly reviewed port-field study states. Material4.6, joined wet geometry4.0–4.4 rejected; originals and individual evidence retained. |\n| `audit/job_river_join_study_v1_20261001/index.html` | 🔵 | `SUPPORTING_CURRENT`; all22 original overlay/helper native views directly reviewed; joins3.6–3.9 rejected. First stationary-drag helper failure preserved; no production change. |\n| `assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html` | 🟣 | `CANDIDATE`; two complete native ImageGen originals/two uniform1024 derivatives/eight individually reviewed wet/dry endcap/elbow/T/cross source components4.6. V4 wet joins4.4/bed3.2 below floor; unbound, owner/full-action acceptance open. |\n'
p.write_text(t,encoding='utf-8',newline='\n')
live=b/'audit/job_artwork_refinement_live/index.html';t=live.read_text(encoding='utf-8');insertion='<section><h2>Painted river: source artwork and every joined-grid draft</h2><p><a href="../job_river_join_study_v1_20261001/index_v4.html">All78 individually scored native study states</a> · <a href="../../assets_src/imagegen/geologist_river_junctions_v1_20261001/index.html">Eight wet/dry junction source items</a></p><p>Sources4.6; selected dry samples4.5 provisional; wet joined network4.4 and flat work bed3.2 remain priorities. Production, actor contact and full-action approval are separate.</p></section>'
t=t.replace('</main>',insertion+'</main>');assert insertion in t;live.write_text(t,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/Path(__file__).name)
for ip,folder in [(b/'design/audit_impacts/job-geology-river-join-study-20261001.json',f),(b/'design/audit_impacts/job-geology-river-junction-source-20261001.json',s)]:
 d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in folder.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/index.html','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v23.py','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v23.py'});d['acceptance_gaps']='Every78 isolated native still and every2 original/2 derivative/8 source components directly reviewed. V4 wet network4.4 and flat bed3.2 remain priorities; selected dry4.5 provisional. Production/actor/room/full action/training/story/device/child/owner/global unfinished. No lifecycle closure.';d['validation'].append({'command':'Current V4 direct review plus unchanged production source comparison','result':'PASS','evidence':'audit/job_river_join_study_v1_20261001/REVIEW_V4.json;audit/job_river_join_study_v1_20261001/PRODUCTION_UNCHANGED_V4.json. Direct coverage and exact349 bytes pass, visual wet joins remain rejected.'});write(ip,d)
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(target)],cwd=b,check=True)
print('V23 written; every78 native view/4 PNG license recorded; current source and review boundaries preserved.')
