from pathlib import Path
from PIL import Image
import datetime, hashlib, html, json, posixpath, re, shutil, subprocess
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_river_join_study_v1_20261001';base='40b1c7bfe025f284507c586fea61b9dd76b61423';assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=b,text=True).strip()==base
read=lambda p:json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
utc=datetime.datetime.now(datetime.timezone.utc).isoformat()
opinions={'dry_initial':(4.3,'The two complete painted endpoint bowls remain readable, but they float on the broad flat board. There is no new route/actor teaching evidence in this isolated study.'),'isolated_dry':(4.3,'The excavated isolated node remains visibly ochre/dry and only the source endpoint has aqua water. Material is painted, but the60px node is small and the surrounding flat bed remains weak.'),'connected_straight':(3.9,'Aqua filling correctly follows source connectivity. The two long pale bank rails continue through the round node interiors; the result resembles plumbing laid over small bowls, not one continuous excavated river.'),'connected_corner':(3.7,'The horizontal and vertical rails stop and overlap at the round centre. Water occupies the correct connected cells, but bank bars cross the shared interior and the corner is visibly assembled.'),'connected_t_branch':(3.6,'Three channel runs cross the round node with internal cream/plum rails. The branch is mechanically correct but visually resembles a pipe diagram; the painted material does not hide the junction defect.'),'connected_cross':(3.6,'Four arms meet with bank segments crossing the central water. Repeated ring nodes and narrow connectors stay diagram-like; require a painted open-interior junction.'),'partial_json_restored':(3.6,'The saved partial cross restores without a stale held touch or completion. Its bank bars and repeated circular nodes retain the same visual join defect; machine restore is not creative acceptance.'),'formerly_isolated_now_wet':(3.6,'The earlier dry node visibly turns aqua after its neighbour connects to the source. This sampled cause/consequence is clear, while the assembled rail junctions remain3.6.'),'connected_complete':(3.6,'All source-connected cells and the target fill correctly and one completion is emitted. The full pattern still reads as thin orthogonal pipes over ring bowls; no whole-job or continuous acting pass.'),'quiet_single_completion':(3.6,'The completed network persists and further input emits no duplicate reward. This view contains no actor return or room, and the complete network retains the rail/ring artifact.')}
items=[]
for width in [1280,1600]:
 m=read(f/('attempt_02/MANIFEST_%d.json'%width));assert len(m['views'])==10
 for x in m['views']:
  score,evaluation=opinions[x['state']];x['id']='RIVER-JOIN-V2-%d-%s'%(width,x['state'].upper());x.update(direct_review=True,material_score=4.6,mounted_detail_score=4.5 if x['state'] in ['dry_initial','isolated_dry'] else score,network_score=None if x['state'] in ['dry_initial','isolated_dry'] else score,sampled_state_score=score,work_bed_context_score=3.2,sampled_wetting_score=4.6 if x['state']=='formerly_isolated_now_wet' else None,complete_action_score=None,actor_contact_score=None,owner_acceptance=None,evaluation=evaluation,priority=True);items.append(x)
archives=[]
for p in sorted((f/'attempt_01/native_views').glob('*.webp')):
 archives.append({'path':p.relative_to(b).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'dimensions':list(Image.open(p).size),'direct_review':True,'sampled_state_score':4.3,'qualification':'First machine capture fails after this initial still because the helper attempts stationary excavation. Direct native initial view inspected separately; no later state or failed-machine pass.'})
assert len(items)==20 and len(archives)==2
literal=read(b/'audit/job_geology_painted_work_v1_20261001/full_ci_v1/SOURCE_BEFORE.json')['source_files'];assert all(hashlib.sha256((b/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in literal)
review={'schema':'reef.river-join-study.v1','baseline':base,'reviewed_utc':utc,'status':'ALL22_NATIVE_VIEWS_DIRECTLY_REVIEWED_NETWORK_REJECTED3_6_TO3_9','current_native_views':items,'first_failed_capture_views':archives,'direct_count':22,'runtime_bound':False,'source_material_score':4.6,'connected_network_range':[3.6,3.9],'flat_work_bed_context':3.2,'production_literal349_unchanged':True,'qualification':'Exact officialGodot4.7.2 Mobile desktop non-runtime drawing subclass, inherited input/flow/save. Every20 current native views and2 failed initial views directly inspected, independent per-state opinions. Source finish4.6 does not pass network joins. Absent actor/room and continuous transitions receive no score. No owner/device/child/runtime/all-job acceptance.','next_specific_gap':'Round nodes plus complete straight strips leave bank bars in branch/corner centres. Need painted endcap/elbow/T/cross junction variants with continuous aqua or earth interiors and banks only along exterior edges.'};write(f/'REVIEW.json',review)
rel=lambda p:posixpath.relpath(p,f.relative_to(b).as_posix());cards=[]
for x in items:
 cards.append('<article id="'+x['id']+'"><h3>'+html.escape(x['state'].replace('_',' ').title())+' · '+str(x['dimensions'][0])+'×720</h3><a href="'+rel(x['path'])+'"><img loading="lazy" src="'+rel(x['path'])+'" alt="'+html.escape(x['id'])+'"></a><p><strong>Sampled state '+str(x['sampled_state_score'])+'/5</strong> · material4.6 · bed3.2 · complete action unassigned</p><p>'+html.escape(x['evaluation'])+'</p><details><summary>Individual source and state evidence</summary><pre>'+html.escape(json.dumps(x,indent=2))+'</pre></details></article>')
before=''.join('<article><h3>Preserved failed stationary fixture · '+str(x['dimensions'][0])+'</h3><img loading="lazy" src="'+rel(x['path'])+'" alt="Preserved first initial river still"><p>'+html.escape(x['qualification'])+'</p></article>' for x in archives)
report='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painted river joins — individual native review</title><style>body{margin:0;background:#eef3f8;color:#26304a;font:17px/1.5 system-ui}main{max-width:1320px;margin:auto;padding:24px}header,section,article{background:white;padding:20px;border-radius:16px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(490px,1fr));gap:18px}.grid article{margin:0;min-width:0}img{width:100%;height:auto}a{color:#504096;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}h1,h2,h3{line-height:1.25}@media(max-width:700px){main{padding:12px}.grid{grid-template-columns:1fr}}</style><main><header><a href="'+rel('audit/job_artwork_refinement_live/index.html')+'">All-job review</a><h1>Painted river joins: rejected network draft</h1><p>Every20 current native views and2 failed initial stills directly reviewed. Source material4.6; joined straight3.9, corner3.7, branches/cross/full network3.6. Sources remain unbound. The clear bank rails crossing node interiors fail the intended continuous river.</p><p>The actual inherited9×5 logic retains passive no-progress, isolated dry excavation, source-connected wetting, arbitrary branches, JSON restore/cancel and one completion. These checks do not approve the artwork or absent actor/room.</p><a href="REVIEW.json">Complete individual evaluations</a> · <a href="SOURCE_INVENTORY.json">Exact reuse inventory</a></header><h2>Every current native state, in order</h2><div class="grid">'+''.join(cards)+'</div><h2>Both first failed attempts</h2><div class="grid">'+before+'</div><section><h2>Machine verification and next iteration</h2><p>Both corrected1280/1600 captures pass with10 states each and one completion. The first helper asks a stationary drag to excavate; the unchanged parent correctly requires at least2px travel. The retry changes only that helper to12px motion. All349 current production literal sources remain unchanged. Full82/82 belongs to the separately published painted-work checkpoint.</p><p>Generate only missing endcap/elbow/T/cross port shapes with continuous earth/water interiors. Keep the nodes/open straight strips and all failed views. Actual production binding, whole action/contact, room, training/story/routes/device/child/owner and comprehensive final approval remain open.</p></section></main></html>'
(f/'index.html').write_text(report,encoding='utf-8',newline='\n');shutil.copyfile(__file__,f/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-river-join-study-20261001.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});d['validation'] += [{'command':'Inherited native river cases at1280/1600','result':'PASS','evidence':f.relative_to(b).as_posix()+'/runtime_gate/capture1280v2.receipt.json;capture1600v2.receipt.json. Narrow mechanics/input, not graphics acceptance.'},{'command':'Every current/failed native join image','result':'PASS','evidence':f.relative_to(b).as_posix()+'/REVIEW.json.22/22 direct coverage; joined network rejected3.6–3.9.'}];d['acceptance_gaps']='Joined network3.6–3.9 remains rejected/unbound; flat bed3.2, actor/room/fulltimed work/routes/training/story/device/child/owner/global open.';write(ip,d)
source=b/'assets_src/imagegen/geologist_river_junctions_v1_20261001';assert not source.exists();source.mkdir();(source/'.gdignore').write_text('',encoding='utf-8')
refs=['assets_src/imagegen/geologist_river_components_v1_20261001/attempt_02/native_generated.png','assets_src/imagegen/geologist_river_components_v1_20261001/attempt_01/native_generated.png']
prompt='''Generate a NEW transparent RGBA game sprite atlas: four separate matching top-down painted shallow water trench JUNCTIONS arranged in a clean2-by2 grid, generous transparent gaps. Reference images are MATERIAL/COLOR/PAINT STYLE ONLY. Replace their closed circular-ring junction topology. This is polished2D storybook bitmap art for Mermaid Roshan, broad matte cream/ochre earth banks, broad lavender shade, clean plum contour, calm aqua water with a few large pale value bands. Rounded handmade toy-playset shapes, simple and readable at88pixels. No realism, no glossy3D, no vector icon look, no typography, no arrows, no numbers, no grid drawn into pixels.
Each object is a compact junction tile occupying a comparable square footprint; identical broad water-corridor width across all four. Water occupies roughly45percent of each port width and remains visibly continuous across the CENTRE. Banks belong ONLY along the OUTSIDE boundary of the trench. Never draw a complete ring or an internal rail across the water.
UPPER LEFT: a rounded dead-end basin with exactlyONE open straight port pointing RIGHT; its other three sides are closed earth banks. At the right short end aqua water touches the transparent boundary; no cap.
UPPER RIGHT: one90-degree ELBOW, open ports pointing UP and RIGHT, continuous broad water around the rounded bend. No internal corner bar and no third port.
LOWER LEFT: oneT junction, open ports LEFT, RIGHT and UP, bottom side closed. Water passes through a SINGLE CLEAR centre with no divider.
LOWER RIGHT: onePLUS cross junction, open ports UP, RIGHT, DOWN and LEFT, all four reach a SINGLE CLEAR shared water centre. Four separate rounded outer earth corners; never a closed circle beneath the arms.
All open ports have straight matching terminal edges, with water reaching the short end and bank material only at the two flanking margins. Whole complete objects, no cropped ends; keep transparent separation between the four sprites. Their4.6 painted materials must match the references, but their geometry must solve the junction requirement. No scenes, characters, board, huge panorama, shadows outside the authored sprite, internal cream rails, closed port caps, narrow pipework or decorative stones. Output one fresh complete atlas with native alpha.'''
(source/'PROMPT_WET_ATTEMPT_01.txt').write_text(prompt,encoding='utf-8',newline='\n')
inventory={'baseline':base,'current_components_review':'assets_src/imagegen/geologist_river_components_v1_20261001/REVIEW.json','actual_join_review':f.relative_to(b).as_posix()+'/REVIEW.json','inventory_decision':'Reuse passing painted materials and preserved isolated/straight components. All20 corrected plus2 failed native join views directly inspected: straight3.9/corner3.7/T/cross/full3.6. Neither existing complete ring nodes nor straight strips can supply clean junction interiors without material topology changes. Generate only compact port-specific junction shapes.','proposed_runtime_sampling':'Select by existing four-neighbour cleared-cell mask; isolate0/currentcircle, opposite2/existing straight centre region, one/endcap, adjacent2/elbow, three/T, four/cross. Normal2D rotations allowed; preserve inherited9x5positions/input/flow/save. Sampling and all adjacency joins remain pending.'};write(source/'REUSE_INVENTORY.json',inventory)
write(source/'GENERATION_PENDING.json',{'status':'WET_JUNCTION_NATIVE_PENDING','prompt_path':(source/'PROMPT_WET_ATTEMPT_01.txt').relative_to(b).as_posix(),'prompt_sha256':hashlib.sha256((source/'PROMPT_WET_ATTEMPT_01.txt').read_bytes()).hexdigest(),'reference_paths':refs,'reference_sha256':[hashlib.sha256((b/p).read_bytes()).hexdigest() for p in refs],'method':'BUILTIN_CODEX_IMAGEGEN','transparent_background':True,'attempt':1,'runtime_bound':False})
ip=b/'design/audit_impacts/job-geology-river-junction-source-20261001.json';write(ip,{'id':'job-geology-river-junction-source-20261001','baseline':base,'scope':'Generate bounded wet/dry port-specific junction atlas shapes only after direct22-native join rejection3.6–3.9. Reuse selected materials/straight/isolated shapes; preserve all native attempts/prompts/hashes. Fresh wet endcap/elbow/T/cross sheet first, no generation budget spent on passing source novelty. Native source-only scores and actual network mounting remain separate; no production/character/background/security changes or owner/global acceptance.','rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-MOT-02','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08'],'findings':['MA-PLAY-004','MA-VIS-006'],'files':sorted(p.relative_to(b).as_posix() for p in source.rglob('*') if p.is_file()),'validation':[{'command':'Reuse inventory and all22 native join views','result':'PASS','evidence':(source/'REUSE_INVENTORY.json').relative_to(b).as_posix()+';'+f.relative_to(b).as_posix()+'/REVIEW.json. Direct coverage passes; joined geometry remains rejected.'}],'acceptance_gaps':'Native generation/source review pending; actual sampling/joins/transition/contact/room/routes/training/story/device/child/owner/global remain open.'})
print('All22 native joins individually reviewed; bounded fresh wet junction generation prepared.')
