from pathlib import Path
import datetime,hashlib,json,re,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'audit/job_review_v2_20261001/hosted_corrected_supplement_v1';assert not out.exists();out.mkdir()
(out/'.gdignore').write_text('')
gh='C:/Program Files/GitHub CLI/gh.exe';revision='56d66f63e375b61cf02936b426a05a2b92c14d3b';run='36944960786'
for name,args in [('state',['--json','status,conclusion,headSha,jobs,url,createdAt,updatedAt']),('log',['--log'])]:
 proc=subprocess.run([gh,'run','view',run,'--repo','Ebonyks/mermaid-roshan-reef',*args],cwd=r,capture_output=True)
 (out/(name+'.stdout.'+('json' if name=='state' else 'log'))).write_bytes(proc.stdout);(out/(name+'.stderr.log')).write_bytes(proc.stderr);assert proc.returncode==0,(name,proc.stderr.decode('utf-8','replace'))
state=json.loads((out/'state.stdout.json').read_text(encoding='utf-8'));assert state['headSha']==revision and state['status']=='completed' and state['conclusion']=='success'
log=(out/'log.stdout.log').read_text(encoding='utf-8')
trusted=[x for x in log.splitlines() if '\tRun trusted probes\t' in x]
headings=[x.split('=== ',1)[-1].split(' ===',1)[0] for x in trusted if '=== ' in x and 'probe_' in x]
literal_matches=[x for x in log.splitlines() if 'GAME2D|' in x and any(q in x for q in ['NO_REGRESSION','UNSATISFIED','ALL OK'])]
receipt=dict(status='PASS_EXACT_C_HOSTED_PROBE_SUITE',checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),revision=revision,run_url=state['url'],run_conclusion=state['conclusion'],jobs=[dict(name=x['name'],status=x['status'],conclusion=x['conclusion'],failed_steps=[q['name'] for q in x['steps'] if q['conclusion']=='failure']) for x in state['jobs']],raw_state_sha256=hashlib.sha256((out/'state.stdout.json').read_bytes()).hexdigest(),raw_log_sha256=hashlib.sha256((out/'log.stdout.log').read_bytes()).hexdigest(),raw_log_bytes=(out/'log.stdout.log').stat().st_size,trusted_heading_count=len(headings),trusted_unique_headings=len(set(headings)),headings=headings,game2d_matching_rows=literal_matches[-12:],qualification='Exact published C hosted success only. Prior M coverage failure and A oversized-manifest failure remain preserved. New uncommitted reaching/shared/vector evidence has no exact-head hosted acceptance yet. Green machine probes do not establish complete4.5 graphics, action, strict2D, target-device, child, owner or release acceptance.')
(out/'RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8',newline='\n');shutil.copyfile(Path(__file__),out/'executed_archive_corrected_supplement_hosted_pass_v78.py')
(out/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Exact corrected review hosted pass</title><style>body{background:#edf4fa;color:#25304a;font:17px/1.5 system-ui}main{max-width:1000px;margin:auto;padding:24px}a,code{overflow-wrap:anywhere}</style><main><a href="../index.html">Current audit entry</a><h1>Published corrected review: hosted machine pass</h1><p>Exact revision<code>'+revision+'</code> completes both hosted jobs successfully. This records machine validation of the published checkpoint; new review files, complete visual action, device, child and owner acceptance remain separate.</p><p><a href="'+state['url']+'">GitHub run</a> · <a href="RECEIPT.json">Exact receipt and log hashes</a> · <a href="state.stdout.json">Original completed state</a> · <a href="log.stdout.log">Full original log</a></p><p><a href="../hosted_current_b_failure_v1/RECEIPT.json">Earlier coverage failure is preserved</a> · <a href="../current_supplement_remote_v1/index.html">Exact239-file anonymous byte verification</a></p></main></html>',encoding='utf-8',newline='\n')
for file in [r/'audit/job_review_v2_20261001/index.html',r/'audit/job_artwork_refinement_live/index.html']:
 s=file.read_text(encoding='utf-8')
 link='hosted_corrected_supplement_v1/index.html' if file.parent.name=='job_review_v2_20261001' else '../job_review_v2_20261001/hosted_corrected_supplement_v1/index.html'
 if 'Exact published corrected review hosted pass' not in s:s=s.replace('</main>','<section><h2>Exact published corrected review hosted pass</h2><p><a href="'+link+'">Published revision56d66f63: both hosted jobs succeed</a>. Earlier sourceA scanner and M coverage failures remain preserved. New source/contact/vector additions are separate review evidence and do not inherit an exact-head hosted result or creative acceptance.</p></section></main>',1)
 file.write_text(s,encoding='utf-8',newline='\n')
master=r/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8')
if 'Published corrected review checkpoint56d66f63' not in s:s+='\nPublished corrected review checkpoint56d66f63 (2026-10-01): [exact hosted Probe Suite36944960786](job_review_v2_20261001/hosted_corrected_supplement_v1/index.html) completes both jobs successfully after the separately preserved M coverage failure. The239-file corrected supplement had already passed anonymous exact-byte verification. This is bounded published machine evidence; new uncommitted source/region/motion/contact/vector additions, all visual/action/device/child/owner and strict2D acceptance remain separate. No integration, release or finding closure.\n'
s=s.replace('328 pose cells and 38 prop regions, with 571','328 pose cells, 38 runtime prop regions and 5 source-object regions, with 571')
master.write_text(s,encoding='utf-8',newline='\n')
active=r/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=active.read_text(encoding='utf-8');start=s.index('## MA-2D-002');end=s.index('\n## ',start+3);section=s[start:end]
if '36944960786' not in section:
 rows=section.splitlines();idx=next(i for i,x in enumerate(rows) if x.startswith('| history |'))
 rows[idx]=rows[idx].rsplit('|',1)[0]+' 2026-10-01 later: corrected published review56d66f63 passes exact hosted Probe Suite36944960786, both jobs success; [raw receipt](../job_review_v2_20261001/hosted_corrected_supplement_v1/RECEIPT.json). The originalA oversized manifests and M coverage failure remain immutable history. Bounded current scan/traceability succeeds; strict zero-debt and lifecycle closure are not claimed. |'
 s=s[:start]+'\n'.join(rows)+'\n'+s[end:]
active.write_text(s,encoding='utf-8',newline='\n')
template=json.loads((r/'design/audit_impacts/job-native-supplement-gates-20261001.json').read_text(encoding='utf-8'))
record=dict(id='job-corrected-supplement-hosted-pass-20261001',scope='Archive exactC completed hosted machine state/full log and verification hashes after its corrected coverage passes. Preserve all earlier failures and immutable byte maps. Append current bounded evidence to master/library and MA-2D-002 history without lifecycle closure; new review-only additions remain a separate candidate.',baseline=revision,rules=template['rules'],findings=sorted(set(template['findings'])|{'MA-2D-002'}),files=sorted([p.relative_to(r).as_posix() for p in out.rglob('*') if p.is_file()]+['audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']),validation=[dict(command='gh run view36944960786 --json and --log, exacthead/completed/success assertions',result='PASS',evidence=out.relative_to(r).as_posix()+'/RECEIPT.json')],acceptance_gaps=receipt['qualification'])
(r/'design/audit_impacts/job-corrected-supplement-hosted-pass-20261001.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8',newline='\n')
print(json.dumps(dict(revision=revision,hosted='success',raw_log_bytes=receipt['raw_log_bytes'],trusted_heading_count=receipt['trusted_heading_count'],strict2d_accepted=False)))
