from pathlib import Path
import datetime,hashlib,html,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geology_room_route_v1_20261002';pfx=f.relative_to(b).as_posix();read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));esc=html.escape
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert not (f/'REVIEW_DRAFT_METADATA_V1.json').exists();shutil.copyfile(f/'REVIEW.json',f/'REVIEW_DRAFT_METADATA_V1.json');shutil.copyfile(f/'index.html',f/'index_DRAFT_METADATA_V1.html')
d=read(f/'REVIEW.json');s=(f/'index.html').read_text(encoding='utf-8');nfixed=0
for x in d['frames']:
 stage=x['phase_index']==4 and x['game']=='opera';returned=x['game']=='level2'
 if stage:
  old=x['evaluation'];x['evaluation']='Actual normal OperaAct celebration replaces the open geode task with a large flat two-crystal emblem2.9. The same procedural strata/trays/crystal scenery remains; curtains2.9/lights3.2/confetti4.4 appear. This is a real shipping lifecycle transition, unlike the earlier empty callback. Mounted celebration composition3.2; no crystal is animated flying out of the geode. The surface data remains allocated but phase4 no longer draws that task.'
  x['scores'].update(geode_opening=None,rooted_crystals=None,working_contact=None,celebration_emblem=2.9,celebration_composition=3.2);s=s.replace('<h3>'+str(x['width'])+' frame'+str(x['index'])+'</h3><p>'+esc(old)+'</p>','<h3>'+str(x['width'])+' frame'+str(x['index'])+'</h3><p>'+esc(x['evaluation'])+'</p>');nfixed+=1
for w in [1280,1600]:d['frame_ranges'][str(w)]['first_celebration_frame']=min(x['index'] for x in d['frames'] if x['width']==w and x['phase_index']==4)
assert nfixed==57
ev=[next(x['path'] for x in d['frames'] if x['width']==w and x['phase_index']==4) for w in [1280,1600]]
for key,name,score,note in [('WIN-EMBLEM','Normal celebration crystal emblem',2.9,'Flat two-crystal vector replaces the newly opened painted specimen; current authored interior does not appear in this stage.'),('WIN-TRANSITION','Task to normal celebration relationship',3.2,'Large open geode/slab instantly disappears as diagram-like stage and emblem return. Restore authored visual continuity while preserving real completion callback/reward timing.'),('WIN-CURTAINS','Normal celebration stage curtains',2.9,'Broad untextured purple polygons and round overhead forms lack the painted shell-stage material.'),('WIN-LIGHTS','Normal celebration footlights',3.2,'Simple flat circles and narrow border read as schematic fixtures.'),('WIN-CONFETTI','Normal celebration confetti',4.4,'Small bright rectangular sparks read as celebration without obscuring faces, but the distribution is generic and flat.')]:
  x=dict(id='GEO-ROUTE-'+key,name=name,mounted_score=score,complete_action_score=None,evaluation=note,evidence=ev,direct_review=True,owner_acceptance=None,priority=True);d['individual_objects'].append(x)
  article='<article id="'+x['id']+'"><h3>'+esc(name)+' · '+str(score)+'/5</h3><p>'+esc(note)+'</p><small>'+x['id']+' · priority · complete action unassigned</small><p>'+' · '.join('<a href="../../'+e+'">Native '+str(w)+'</a>' for w,e in zip([1280,1600],ev))+'</p></article>'
  s=s.replace('</section><h2>Every native task and route state',article+'</section><h2>Every native task and route state',1)
d['counts']['individual_objects']=len(d['individual_objects']);assert d['counts']['individual_objects']==86;d['metadata_correction']='Initial review draft mistakenly treated allocated surface metadata as a visible task after phase4. Exact actual phase_index distinguishes57 celebration frames; earlier wrong draft retained as rejected diagnostic, not acceptance.';d['metadata_corrected_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat()
write(f/'REVIEW.json',d);write(f/'OBJECTS.json',dict(objects=d['individual_objects'],review='REVIEW.json',qualification=d['qualification']));(f/'index.html').write_text(s,encoding='utf-8',newline='\n')
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md']:
 p=b/rel;t=p.read_text(encoding='utf-8');t=t.replace('[81 individual mounted objects/relationships','[86 individual mounted objects/relationships').replace('and81 individual mounted object opinions','and86 individual mounted object opinions');p.write_text(t,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name);ip=b/'design/audit_impacts/job-geology-room-route-review-20261002.json';a=read(ip);a['files']=sorted(set(a['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});a['validation'].append(dict(command='Compare phase4 visible celebration with raw capture phase_index and native images',result='PASS',evidence=pfx+'/REVIEW.json;57 celebration frames corrected; rejected draft retained.'));write(ip,a)
allow=b/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}));print(json.dumps(dict(corrected_frames=nfixed,objects=86,ranges=d['frame_ranges'])))
