from pathlib import Path
import datetime,hashlib,html,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef'); f=b/'audit/job_geology_room_route_v1_20261002'; pfx=f.relative_to(b).as_posix();live=b/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat();esc=html.escape;bt=chr(96)
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert not (f/'REVIEW.json').exists()
snap=read(b/'audit/job_geode_coherent_runtime_v1_20261002/full_ci_v2/SOURCE_BEFORE.json')['source_files'];assert len(snap)==368 and all(sha(b/x['path'])==x['sha256'] for x in snap)
notes={
'normal_library_card':(4.0,'Painted Library shelves, shell chairs and warm stone4.6 provide an established storybook setting. All three career pictures are visible. The Geologist crest is a flat two-crystal vector2.9; the caption covers the lower fin4.0. Keep the protected family portrait unchanged. Wider capture preserves the centered1280 canvas with side margins; no game card is clipped.'),
'phase0_invitation':(2.8,'Layered rock invitation4.6 has broad painted bands and a rounded silhouette. Floating blue halo/support relationship3.8. The geometric strata2.8, tan fossil rectangle/ring3.0, three outlined trays3.0 and unpainted crystal cluster3.0 remain visibly bound. Painted actors4.6 conflict with the diagram-like room; imp support3.0.'),
'phase0_task_open':(2.7,'Painted earth4.6 and clear source/destination wells4.6 make the large task readable; invitation cursor4.5. Roshan reaches at floor height far from the raised bed: working contact2.7. This is a contact/composition failure, not a reason to redesign her approved costume.'),
'phase0_earned_completion':(2.8,'Connected painted water/earth network4.5 provisional has clear wet/dry meaning and a continuous endpoint. Minor component seams remain. Roshan raises a loose blue crystal after the river task: celebration relevance4.0, distinct from a crystal being expelled by the geode. Room remains2.8.'),
'phase1_invitation':(2.8,'Golden spiral fossil invitation4.6 is recognizable and has painted mineral edging. Floating ring/support3.8 and the flat strata/trays/crystals remain below standard. Do not let the fossil source pass clear the room.'),
'phase1_task_open':(2.7,'Painted soil4.6 conceals the fossil on a rounded slab4.6. Actor hands remain remote2.7. The objective is large and unobscured. Material quality and hand contact have independent opinions.'),
'phase1_partial_brush':(2.7,'Brush source4.6 has readable bristles and a warm handle, but it floats above the work and is detached from Roshan2.7. Soil disappears in a straight rectangular row3.9 rather than a convincing brushed patch. Exposed fossil and slab retain painted4.6.'),
'phase1_brushed':(2.7,'Three conserved fossil thirds each retain source material4.6; cropped boundaries are mechanically straight. Ghost target/assembly4.5 provisional reads clearly. Bottom pieces extend toward the slab rim and Roshan remains remote2.7. This still does not establish every assembly-motion frame.'),
'phase1_one_piece':(2.7,'Left third is correctly seated in the ghost spiral while center/right pieces remain separate. Conserved fossil identity4.6; sampled assembly4.5. Straight vertical cut boundaries and remote hands2.7 remain priorities.'),
'phase1_two_pieces':(2.7,'Left and middle thirds reconnect the same spiral; right third remains available. Material4.6, sampled assembly4.5. No regenerated mismatched fossil fragments. Hands remain remote2.7.'),
'phase1_earned_completion':(2.8,'Completed fossil preserves the original spiral and stone rim4.6; sampled assembly4.5. Roshan raises an unrelated crystal4.0 while the fossil remains on the slab. Flat room2.8 is still visible.'),
'phase2_invitation':(2.8,'Painted aqua-water pan4.6 matches the prop family, but floats above Roshan with a blue diagram halo3.8. Actual procedural room2.8 and tray/crystal siblings3.0 remain.'),
'phase2_task_open':(2.7,'Pan/water/slab each4.6. Twenty ordinary gold grain instances have warm painted surfaces4.6 and stay inside the basin. Roshan crouches away from the rim2.7. Source quality does not supply the missing grip or rocking action.'),
'phase2_pan_right':(2.7,'Pan translates right while retaining a level oval4.6; action3.8 reads as sliding rather than tilting. Grains remain contained and shift within water. Detached hands2.7 remain. A complete rocking sequence still needs review.'),
'phase2_pan_left':(2.7,'Pan translates left with unchanged level rim. Static paint4.6 and containment4.5 provisional; panning action3.8, grip2.7. Do not claim the unbound generated gripping study is active here.'),
'phase2_partial_pan':(2.7,'One painted crystal cluster4.6 appears inside the pan as grains reduce. It is a pan discovery, not the geode reveal. Pan motion3.8 and remote actor contact2.7 remain; tiny cluster outlines read somewhat busy at this scale.'),
'phase2_earned_completion':(2.8,'Three painted mineral clusters4.6 remain inside the pan. Sampled containment4.5 provisional. Roshan claps4.6 as a static pose but its working-to-clap transition4.0 is abrupt. Room2.8 remains.'),
'phase3_invitation':(2.8,'Current closed geode preview4.5 shows the lavender shell and center seam. Its invitation floats above the scene3.8; procedural crystal backdrop and rectangular trays remain3.0. This preview is distinct from the large task.'),
'phase3_task_open':(2.7,'Closed authored geode4.5 rests on the painted slab with stable base and proportions. Five broad seam circles4.4 remain legible but are flat marks. Actual actor hands remain on the floor away from the geode2.7.'),
'phase3_five_seams_ready':(2.7,'All five seam marks are turquoise and the shell stays closed until the intentional pull. Closed material4.6/state4.5; markers4.4. Geode does not auto-open during passive waiting. Hands remain remote2.7.'),
'phase3_early_crack':(2.7,'The seam reveals cream mineral lining and crystals embedded inside4.6. Authored state/opening4.5 provisional preserves the base; no loot crystal leaves the stone. Minor fringe and discrete reveal remain at the inclusive priority threshold. Contact2.7 and room2.8 remain separate.'),
'phase3_middle_open':(2.7,'Two widening cavities show aqua and lavender crystals rooted within their rock4.6. Authored intermediate4.5 preserves center/base. Small facet reinterpretation and discrete width change remain priorities; contact2.7 is not repaired by this source.'),
'phase3_full_interior_before_award':(2.7,'Both stone halves reveal complete cream-lined interiors and rooted crystals4.6. Final state4.5 rests on the same slab and stays inside touch-safe task bounds. No expelled crystal or detached reward layer. Hands2.7 remain.'),
'phase3_earned_completion':(2.8,'At phase completion the geode stays open and its crystals stay inside4.6. Static clapping pose4.6, abrupt transition4.0. The later normal OperaAct celebration uses a different flat emblem; this still alone cannot establish that transition or entire career acceptance.'),
'actual_earned_library_return':(4.0,'Actual production OperaAct callback returns to the Library, records Geologist star and restores the base Roshan costume. Painted Library4.6. Flat Geologist card crest2.9 and caption/lower-fin overlap4.0 remain. Capture proves this isolated ordinary route, not natural story progression or device/child acceptance.'),
'actual_opera_venue':(4.0,'Existing painted Opera lobby4.6 has shell ornament and clear stairs/doors. The retained recent success caption hides most of Roshan4.0 in this deliberately quick route change. Practice book artwork4.6 is the existing arborist entry, not a separate Geologist story or lesson.'),
'actual_elevator_menu':(2.9,'Actual elevator opens the owner-directed developer replay menu. Fourteen other cards and the Geologist card are individually listed below. Geologist is still a flat crystal emblem2.9; Nursery and Teacher have inconsistent icon framing4.4/4.3. Other painted crests4.6. This developer-only label screen is not a new child reading requirement.'),
'actual_dev_geologist_entry':(2.8,'Actual developer Geologist card launches fresh phase0 with the same painted rock invitation4.6 and still-flat room2.8. No phase result or reward was forced. This proves the replay entry uses the same visible world, not an additional training art family.'),
'actual_dev_back_menu':(2.9,'Ordinary Back returns to the developer menu; existing cards stay visible and focused Back gains a yellow outline4.5. Geologist emblem2.9 remains. Replay cancel is separate from the earned Library completion.'),
}
views=[];frames=[];boards=[];ranges={}
for w in [1280,1600]:
 cap=read(f/f'attempt_02/CAPTURE_{w}.json');assert read(f/f'runtime_gate/capture{w}v2.receipt.json')['status']=='PASS';assert len(cap['views'])==29
 for x in cap['views']:
  y=dict(x);assert sha(b/y['path'])==y['sha256'];y['capture_state']=y['state'];y['state']=Path(y['path']).stem.removeprefix('geologist_'+str(w)+'_');score,note=notes[y['state']];y.update(direct_review=True,review_method='Direct native still inspection at both widths, all29 states without sampling.',score=score,evaluation=note,owner_acceptance=None);views.append(y)
 # Every board cell, including the partial final board, was directly inspected.
 m=read(f/f'BOARD_MANIFEST_{w}.json');assert len(m['frames'])==len(cap['motion_frames'])
 for x in m['boards']:
  y=dict(x);assert sha(b/y['path'])==y['sha256'];y.update(direct_review=True,review_method='Every declared cell inspected directly in row-major order; no sampled omissions. Empty final board cells are not frames.');boards.append(y)
 first_stage=None;first_return=None
 for x in cap['motion_frames']:
  y=dict(x);assert sha(b/y['path'])==y['sha256'];n=y['index'];in_work=bool(y['surface']);returned=y['game']=='level2';stage=not in_work and not returned
  if stage and first_stage is None:first_stage=n
  if returned and first_return is None:first_return=n
  note=('Authored stone opens with fixed center/base and crystals contained inside: geode/opening4.5 provisional, material/rooted4.6. Discrete state changes and minor fringe remain inclusive priorities. Room2.8 and floor-level remote hands2.7 remain.' if in_work else 'Actual normal OperaAct celebration replaces the open geode task with a large flat two-crystal emblem2.9. The same procedural strata/trays/crystal scenery remains; curtains2.9/lights3.2/confetti4.4 appear. This is a real shipping lifecycle transition, unlike the earlier empty callback. It is a mounted celebration weakness3.2; no crystal is animated flying out of the geode.' if stage else 'Actual production completion returns to the painted Library4.6, base Roshan and saved Geologist star. Caption covers lower fin4.0; unchanged vector career crest2.9 remains. This route fixture does not prove device/child/owner acceptance.')
  y.update(direct_review=True,review_method='All316 consecutive rendered frames directly reviewed across27 complete ordered boards, with4 additional native transition/return details.',native_detail_review=(w,n) in [(1280,110),(1280,142),(1600,107),(1600,134)],evaluation=note,scores=dict(geode_opening=4.5 if in_work else None,rooted_crystals=4.6 if in_work else None,room=4.6 if returned else 2.8,working_contact=2.7 if in_work else None,celebration_emblem=2.9 if stage else None,celebration_composition=3.2 if stage else None,return_composition=4.0 if returned else None),owner_acceptance=None,priority=True);frames.append(y)
 ranges[str(w)]=dict(frames=len(cap['motion_frames']),first_celebration_frame=first_stage,first_return_frame=first_return,last_frame=cap['motion_frames'][-1]['index'])
assert len(views)==58 and len(frames)==316 and len(boards)==27
objects=[]
def obj(key,name,score,view,note,action=None):
 ev=[x['path'] for x in views if x['state']==view];assert len(ev)==2
 objects.append(dict(id='GEO-ROUTE-'+key,name=name,mounted_score=score,complete_action_score=action,evaluation=note,evidence=ev,direct_review=True,owner_acceptance=None,priority=score<=4.5))
obj('LIBRARY','Painted Library environment',4.6,'normal_library_card','Existing warm books, rounded shell furniture, pearl lights and stone preserve established storybook language. This is mounted composition evidence; original source provenance/resolution remain in existing ledgers.')
obj('CREST','Geologist career crest',2.9,'actual_elevator_menu','Flat aqua/pink two-crystal polygons on navy base conflict with neighboring painted crests. Same crest is visible on Library card and at final celebration. Reuse the current painted geode artwork for a review candidate before commissioning another icon.')
obj('CARD-ROSHAN','Geologist Library picture',4.6,'normal_library_card','Existing complete mermaid/costume illustration is legible in the career card; do not regenerate merely to repair the crest below it.')
obj('LIBRARY-CAPTION','Library entry/return caption relationship',4.0,'actual_earned_library_return','Caption obscures the lower part of Roshan. Restore visual room/character clearance without changing saved star or protected portraits.')
obj('STRATA','Geologist procedural strata and room field',2.8,'phase0_invitation','Repeated straight angular lavender bands on dark faceted field lack handmade painted surfaces. Existing generated room references have good painting but insufficient native coverage and remain unbound; do not fake a2K master by upscaling.')
obj('FOSSIL-SIGN','Room fossil sign rectangle and ring',3.0,'phase0_invitation','Plain tan rectangle with one ring reads as a placeholder diagram.')
for n in range(3):obj('TRAY-'+str(n),'Outlined room tray '+str(n+1),3.0,'phase0_invitation','Thin mint rectangular outline on a dark inset has no painted toy material or usable support ownership.')
obj('CRYSTAL-ROOM','Procedural room crystal cluster',3.0,'phase0_invitation','Tall simple cyan/lavender polygons lack the painted mineral language; avoid painting unrelated replacement crystals over an existing painted copy.')
obj('ROOM-HALO','Room crystal outline ring',3.3,'phase0_invitation','Large transparent circle is diagram-like and unrelated to a readable physical support.')
obj('IMP','Existing geologist imp',4.6,'phase0_invitation','Rounded painted face, navy costume and readable magnifier match the established imp family.')
obj('IMP-SUPPORT','Imp relationship to the room crystals',3.0,'phase0_invitation','Boots float beside/above a crystal display without a grounded shelf or shared support.')
for key,state,name in [('ROCK','phase0_invitation','Layered-rock invitation'),('FOSSIL','phase1_invitation','Fossil invitation'),('PAN','phase2_invitation','Pan invitation'),('GEODE','phase3_invitation','Closed-geode invitation')]:
 obj('INVITE-'+key,name,4.5 if key=='GEODE' else 4.6,state,'Painted objective retains rounded silhouette, broad bands and child-readable proportions; current geode source remains provisional4.5.')
 obj('INVITE-HALO-'+key,name+' support/halo',3.8,state,'Object floats high above the actor; blue rings/cross marks are readable but lack authored support and a grounded approach. Preserve the approved object identity.')
obj('EARTH','Painted river bed',4.6,'phase0_task_open','Broad warm painted soil, stones and contour provide a calm legible task surface.')
obj('RIVER-NETWORK','Connected excavation and water',4.5,'phase0_earned_completion','Observed endpoint network joins; wet meaning is clear, minor segment seams remain. Earlier full river review supplies additional evidence; this route has sampled non-geode stills, not every river frame.')
obj('WORK-CONTACT','Roshan hands and raised work surface',2.7,'phase2_task_open','Approved complete body4.6 is mounted near the floor while work objects sit well above/right. A reusable connected pan-grip source exists but is unbound and must earn actual action acceptance.')
obj('SLAB','Painted mineral work slab',4.6,'phase3_task_open','Rounded cream plane with lavender chipped sides supports the specimen and preserves authored aspect.')
obj('SOIL','Concealing painted soil',4.6,'phase1_task_open','Painted earth fully conceals the fossil before brushing.')
obj('CLEARING','Rectangular soil-clearing edge',3.9,'phase1_partial_brush','Straight row removal reveals a grid operation; improve local brushed material state rather than conceal the surface with a different technique.')
obj('BRUSH','Painted fossil brush',4.6,'phase1_partial_brush','Warm handle, lavender wrap and turquoise bristle tips fit the toy palette.')
obj('BRUSH-CONTACT','Brush/hand/work contact',2.7,'phase1_partial_brush','Brush hovers far above the slab while hands reach toward floor. Bristle/work and hand/handle contact need authored evidence.')
for n in range(3):obj('FOSSIL-PIECE-'+str(n),'Conserved fossil third '+str(n+1),4.6,'phase1_brushed','Same existing approved fossil pixels preserve spiral identity; mechanically straight cut edge is reviewed separately in assembly4.5.')
obj('FOSSIL-TARGET','Fossil ghost target and sampled assembly',4.5,'phase1_two_pieces','Faded target stays clear as conserved pieces reconnect. Straight vertical cut silhouettes remain inclusive priorities; complete assembly motion unassigned.')
obj('PAN','Painted pan and aqua water',4.6,'phase2_task_open','Wide lavender rim and aqua water have authored broad value bands and legible containment.')
obj('PAN-MOTION','Actual pan lateral movement',3.8,'phase2_pan_right','Pan retains a level oval while shifting left/right; it does not visibly rock. Generated/Comfy motion studies remain separate unbound evidence.')
for n in range(20):obj('GRAIN-'+str(n),'Pan gold grain instance '+str(n+1),4.6,'phase2_task_open','Repeated warm painted grain, individually visible within the basin; no individual redesign needed merely because twenty instances share source.')
for n in range(3):obj('PAN-MINERAL-'+str(n),'Pan discovery cluster '+str(n+1),4.6,'phase2_earned_completion','Painted aqua/lavender crystal cluster remains inside the pan; source painting passes while complete panning action remains unassigned.')
for n in range(5):obj('SEAM-'+str(n),'Geode seam cue '+str(n+1),4.4,'phase3_five_seams_ready','Broad color marker is legible but flat; retains ordinary tap state without dominating the stone outline.')
obj('GEODE-OPENING','Current connected geode and rooted interior',4.5,'phase3_full_interior_before_award','All seven authored states and every opening frame preserve fixed support and crystals embedded within both stone cavities. Minor fringe/discrete reveals remain inclusive priorities.',4.5)
obj('CLAP','Existing geologist clapping pose',4.6,'phase3_earned_completion','Approved complete mermaid pose has readable joy and consistent costume; working-to-clap transition remains4.0.')
obj('TASK-CRYSTAL-POSE','Crystal-raising pose after river/fossil',4.0,'phase1_earned_completion','Unrelated crystal gesture weakens task semantics. It does not depict crystals flying from the newly opened geode.')
obj('BACK','Existing round Back control',4.5,'actual_dev_back_menu','Large purple contour, return arrow and focus cue remain clear and touch-readable.')
for label,score,note in [('Pastry Chef',4.6,'Warm painted cake crest'),('Detective',4.6,'Painted magnifier crest'),('Ballerina',4.6,'Painted shoes and oval frame'),('Candy Maker',4.6,'Painted sweets/utensils'),('Stuffie Surgeon',4.6,'Painted stethoscope/medical toy crest'),('Farmer',4.6,'Painted basket and produce'),('Boxer',4.6,'Painted glove crest'),('Magician',4.6,'Painted hat/wand crest'),('Painter',4.6,'Painted palette crest'),('Astronaut',4.6,'Painted rocket crest'),('Racecar Driver',4.6,'Painted wheel/car crest'),('Pop Star',4.6,'Painted microphone crest'),('Nursery Nurse',4.4,'Painted mobile lacks the common oval frame and has finer dangling details'),('Teacher',4.3,'Small whole mermaid on plain card is less readable and framed differently from other crests')]:obj('MENU-'+label.upper().replace(' ','-'),label+' replay icon',score,'actual_elevator_menu',note+'. This only scores the visible menu icon, not that career artwork or actions.')
detail_frames=[x for x in frames if x['native_detail_review']]
report=dict(status='BOUNDED_ACTUAL_LIBRARY_ROUTE_REVIEWED_GEODE4.5_ROOM_CONTACT_CELEBRATION_WEAK',reviewed_utc=now,baseline='c6f03791aee93f1443d423dd50334804e37313fb',source_files=snap,additional_fixture=dict(path=pfx+'/capture_v2.gd',sha256=sha(f/'capture_v2.gd')),views=views,frames=frames,boards=boards,individual_objects=objects,counts=dict(native_stills=58,continuous_frames=316,ordered_boards=27,native_motion_details=4,individual_objects=len(objects)),frame_ranges=ranges,scores=dict(geode_opening=4.5,rooted_crystal_semantics=4.6,procedural_room=2.8,working_contact=2.7,pan_action=3.8,soil_clearing=3.9,ordinary_celebration_emblem=2.9,ordinary_celebration_composition=3.2,return_composition=4.0,whole_career=None),owner_acceptance=None,qualification=cap['qualification']+' Every captured still/continuous geode frame reviewed; non-geode tasks have selected native states only, not all intervening frames.368-source fullCI2 and this extra fixture are separate evidence. No finding closure, dev integration, release,5/5 or comprehensive all-job acceptance.',scope_trace=read(f/'PLAN.json'))
write(f/'REVIEW.json',report);write(f/'OBJECTS.json',dict(objects=objects,review='REVIEW.json',qualification=report['qualification']))
def url(x):return '../../'+x
def fig(x,title):return '<figure><a href="'+url(x['path'])+'"><img src="'+url(x['path'])+'" alt="'+esc(title)+'"></a><figcaption>'+esc(title)+'</figcaption></figure>'
content='<h1>Geologist: actual Library route and Opera replay</h1><p>Current geode opening4.5/5 provisional, rooted crystals4.6. All58 native task/entry/return stills and316 consecutive geode-to-celebration-to-Library frames directly reviewed at1280×720 and1600×720.27 ordered boards contain every frame, including declared final partial boards.</p><p>The real celebration still switches to a flat crystal emblem2.9 and old stage scenery. Room2.8, hand contact2.7, soil clearing3.9, pan action3.8 and caption clearance4.0 remain priorities. An improved object does not pass the whole career. Final owner report/approval remains pending.</p><nav><a href="../job_artwork_refinement_live/index.html">Current all-job library</a> · <a href="REVIEW.json">Every written frame/image evaluation and source hashes</a> · <a href="OBJECTS.json">Individual objects</a> · <a href="PLAN.json">Actual-use trace and evidence boundaries</a> · <a href="../job_geode_coherent_runtime_v1_20261002/index.html">Seven mounted geode states</a> · <a href="../job_geode_coherent_runtime_v1_20261002/full_ci_v2/RECEIPT.json">Separate frozen-source full machine suite</a> · <a href="FAILED_ENTRY_ATTEMPT_01.json">Preserved failed entry fixture</a></nav><p>'+esc(report['qualification'])+'</p><h2>Each mounted object and relationship</h2><section class="objects">'
for x in objects:content+='<article id="'+x['id']+'"><h3>'+esc(x['name'])+' · '+str(x['mounted_score'])+'/5</h3><p>'+esc(x['evaluation'])+'</p><small>'+x['id']+' · '+('priority' if x['priority'] else 'provisional painted pass')+' · complete action '+('unassigned' if x['complete_action_score'] is None else str(x['complete_action_score']))+'</small><p>'+' · '.join('<a href="'+url(e)+'">Native '+str(w)+'</a>' for w,e in zip([1280,1600],x['evidence']))+'</p></article>'
content+='</section><h2>Every native task and route state</h2><section class="views">'
for x in views:content+='<article>'+fig(x,str(x['viewport'][0])+' '+x['state']+' · visible composition minimum '+str(x['score'])+'/5')+'<p>'+esc(x['evaluation'])+'</p></article>'
content+='</section><h2>Every consecutive geode, actual celebration and earned return frame</h2><section>'
for x in boards:content+=fig(x,str(x['width'])+' frames '+str(x['first_frame'])+'–'+str(x['last_frame'])+' · every'+str(x['count'])+' actual frame inspected')
content+='</section><h2>Native transition and return details</h2><section>'+''.join(fig(x,str(x['width'])+' frame'+str(x['index'])) for x in detail_frames)+'</section><h2>Individual continuous-frame evaluations</h2><section class="frames">'
for x in frames:content+='<article><h3>'+str(x['width'])+' frame'+str(x['index'])+'</h3><p>'+esc(x['evaluation'])+'</p><a href="'+url(x['path'])+'">Native frame</a><small> SHA256 '+x['sha256']+'</small></article>'
content+='</section>'
(f/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geologist actual Library route review</title><style>body{margin:0;background:#ececf7;color:#282047;font:17px/1.55 system-ui}main{max-width:1420px;margin:auto;padding:28px}section{display:grid;gap:18px;grid-template-columns:repeat(auto-fit,minmax(min(100%,420px),1fr))}article,figure{margin:0;background:white;padding:18px;border-radius:18px;min-width:0}img{width:100%;display:block}small{display:block;overflow-wrap:anywhere}a{color:#413785}.objects,.frames{grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr))}nav{padding:18px;background:white;border-radius:15px}</style><main>'+content+'</main></html>',encoding='utf-8',newline='\n')
write(live/'BROWSER_GEODE_REGIONS_V29.json',dict(status='PASS',recorded_utc=now,url='http://127.0.0.1:8880/audit/job_artwork_refinement_live/all_items.html',search='GEO-COHERENT-RUNTIME',observed_images=9,loaded_images=9,broken_images=0,individual_region_crops=7,whole_sources=2,viewport_width=1280,document_width=1265,mounted_score=4.5,object_sequence_score=4.5,complete_action_score=None,qualification='Read-only browser DOM and screenshot directly observed after V29 reload; score lanes and actual per-region crop offsets confirmed. Current actual Library route adds a separate weak celebration opinion.'))
# Link current evidence without rewriting earlier dated reviews.
entry=live/'index.html';s=entry.read_text(encoding='utf-8');banner='<aside style="padding:22px;background:#fff4dc;border-radius:18px"><h2>Latest geode and actual Library route</h2><p>Seven mounted geode states/opening4.5 provisional, rooted crystals4.6. Actual Library completion now reviewed:58 native stills/316 consecutive opening, celebration and return frames. The normal celebration still uses a flat emblem2.9; room2.8/contact2.7 remain weak.</p><a href="../job_geology_room_route_v1_20261002/index.html">Read every actual route evaluation and image</a> · <a href="../job_geode_coherent_runtime_v1_20261002/index.html">Review every mounted geode state</a></aside>'
assert banner not in s;pos=s.find('</h1>');assert pos>=0;s=s[:pos+5]+banner+s[pos+5:];entry.write_text(s,encoding='utf-8',newline='\n')
summary='Actual Library/elevator Geologist continuation (2026-10-02): ['+str(len(objects))+' individual mounted objects/relationships, all58 native stills and316 consecutive geode/normal celebration/earned Library-return frames on27 boards]('+pfx.removeprefix('audit/')+'/index.html) directly reviewed at1280/1600, plus4 native transition/return details. Actual OperaAct callback returns and saves the star; this replaces the earlier empty-callback evidence boundary without rewriting historical reports. Opening4.5/rooted crystals4.6; normal celebration still replaces the specimen with a flat emblem2.9/celebration composition3.2. Room2.8/contact2.7/clearing3.9/pan action3.8/return caption4.0 remain priorities. Source trace establishes normal Library freeplay and developer elevator replay, no separate Geologist ChapterTwo PHASE_SET or enabled two-act rollout. Main/Castle/save entry fixture and slowed readback remain bounded; other-task intervening frames, natural story/device/child/owner/full all-job acceptance and finding lifecycles remain open.368-source fullCI2 is separate from this additional fixture.'
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
 p=b/rel;s=p.read_text(encoding='utf-8');note=summary if '/findings/' not in rel else summary.replace(']('+pfx.removeprefix('audit/')+'/','](../'+pfx.removeprefix('audit/')+'/')+' MA-PLAY-004 remains IN_PROGRESS; MA-VIS-006/MA-OPERA-012 have no acceptance closure.';s=s.replace('\n\n','\n\n'+note+'\n\n',1);p.write_text(s,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');s+='\n| '+bt+pfx+'/index.html'+bt+' | 🟣 | '+bt+'CANDIDATE'+bt+'; all58 actual Library/elevator native stills/316 consecutive geode-celebration-real-return frames/27 ordered boards/4 native motion details and'+str(len(objects))+' individual mounted object opinions. Geode opening4.5/rooted4.6, actual flat celebration emblem2.9/composition3.2, room2.8/contact2.7/clearing3.9/pan3.8/caption4.0 remain. Failed entry fixture preserved; natural story/device/child/owner/all-job acceptance open.368-source suite separate from extra fixture. |\n';p.write_text(s,encoding='utf-8',newline='\n')
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n### Actual Library/elevator Geologist route review evidence (2026-10-02)\n\n'
all_images=views+frames+boards+[dict(path=x.relative_to(b).as_posix(),sha256=sha(x)) for x in (f/'attempt_01').rglob('*.webp')]
for x in all_images:
 if x['path'] not in s:s+='| '+bt+x['path']+bt+' | OfficialGodot4.7.2 Mobile capture of licensed project artwork | Project review evidence; source licenses unchanged | '+bt+pfx+'/REVIEW.json'+bt+' | '+('Uniform whole-scene ordered review board, no production pixels' if 'first_frame' in x else 'Exact native losslessWebP capture; failed-entry fixture retained without visual acceptance' if '/attempt_01/' in x['path'] else 'Exact native losslessWebP capture; directly reviewed')+'; SHA256 '+x['sha256']+' |\n'
p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geology-room-route-review-20261002.json';d=read(ip);d['validation'].append(dict(command='Direct complete native still/ordered-frame/individual-object review',result='PASS',evidence=pfx+'/REVIEW.json; visual priorities remain;368 production files literal unchanged.'))
d['acceptance_gaps']='Opening4.5 provisional; room2.8/contact2.7/normal celebration emblem2.9/composition3.2/clearing3.9/pan3.8/caption4.0 remain. Other-task intervening frames/natural story/device/child/owner/final all-job report. No finding closure/integration/release. Separate fullCI2 receipt covers368 frozen sources; extra fixture independently parsed/analyzed/captured.'
d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in f.rglob('*') if x.is_file()}|{'audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/BROWSER_GEODE_REGIONS_V29.json','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','ASSET_LICENSES.md'});write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{x.relative_to(b).as_posix() for x in f.rglob('*') if x.is_file()}|{'audit/job_artwork_refinement_live/BROWSER_GEODE_REGIONS_V29.json'}))
print(json.dumps(dict(status=report['status'],counts=report['counts'],ranges=ranges,license_images=len(all_images))))
