from pathlib import Path
import copy, datetime, hashlib, json, shutil, subprocess

R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
OLD=R/'assets_src/local_motion/nursery_connected_scrub_v3_20261002'
P=R/'assets_src/local_motion/nursery_connected_scrub_v4_20261002'
BASE='ea9f4e00a2af67fc6f81e16a2102754892a18cfd'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
    p.parent.mkdir(parents=True,exist_ok=True)
    p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R).decode().strip()==BASE
assert subprocess.check_output(['git','branch','--show-current'],cwd=R).decode().strip()=='codex/job-art-review-v2-20261001'
subprocess.run(['git','fetch','origin','codex/job-art-review-v2-20261001'],cwd=R,check=True,capture_output=True)
assert subprocess.check_output(['git','rev-parse','origin/codex/job-art-review-v2-20261001'],cwd=R).decode().strip()==BASE
assert read(OLD/'REVIEW_STATUS.json')['status']=='MACHINE_RENDER_COMPLETE_VISUAL_REJECTED'
assert not P.exists()
ip=R/'design/audit_impacts/job-nursery-scrub-prompt-a4-20261002.json'
assert not ip.exists()
P.mkdir();(P/'review_tools').mkdir();(P/'.gdignore').write_text('',encoding='utf-8')
old=read(OLD/'MANIFEST.json');rules=read(OLD/'PLAN.json')['rules']
scope='One bounded local prompt-only A4 Nursery scrub comparison. Preserve fresh attentive A2 native, exact A3 model input, seed, admitted settings and developed workflow. Replace tiny/frozen direction with two visible reciprocal palm strokes and limited natural elbow movement. No source edits, external upload, runtime or cinematic binding; preserve failures and review every native frame.'
plan=dict(status='PLANNED_BEFORE_COPY_OR_RENDER',baseline=BASE,created_utc=now(),scope=scope,rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],inventory=[dict(path=OLD.relative_to(R).as_posix()+'/attempt01/DIRECT_REVIEW.json',role='All41 A3 frames reviewed, action2.7/reciprocal2.8/fixture3.0 rejected; no accepted motion available'),dict(path=old['source_path'],sha256=old['source_sha256'],role='Fresh native attentive A2 still, static4.5, unchanged and unbound'),dict(path=OLD.relative_to(R).as_posix()+'/'+old['input_path'],sha256=old['input_sha256'],role='Exact existing whole-canvas technical model input reused unchanged')],gap='A3 instruction for tiny strokes and a fully frozen body produces a near-held contact and invented white head-to-basin arch. Test larger explicitly visible opposing palm strokes with limited natural low elbow motion; no assumption of success.',predeclared_review=dict(minimum_reciprocal_cycles=2,near_palm_screen_excursion_px=12,units='896x512 full native reference canvas; 12px intended excursion is an inspection target, not an unmeasured pass',attention='Eyes follow palms, head and support steady',contact='Both wrists and arms connected; palms maintain overlapping rubbing contact without clasp/clap',material='Tap off throughout; no water/foam path from hair/head/faucet; only tiny existing lather between palms',identity='Stable face, hair, apron, pockets, rainbow tail, basin and pedestal',exit='Low contact resting pose by final native frame; source-only seam must be inspected'),required_evidence=['Identical source/input/seed/settings/model/workflow hashes, changed prompt only','Developed benchmark and90second quiet-idle FIFO admission, no restart/cancel/duplicate/model install','Native receipt, direct decode of every41 full canvases and individual written native-frame opinions','All783 current production literal source bytes unchanged','Existing authority/coverage/2D gates, exact durable anonymous publication, owner/device/child/all-job acceptance separate'])
write(P/'PLAN.json',plan)
write(ip,dict(id='job-nursery-scrub-prompt-a4-20261002',scope=scope,baseline=BASE,rules=rules,findings=plan['findings'],files=[(P/'PLAN.json').relative_to(R).as_posix()],validation=[dict(command='Local prompt-only Nursery A4 and every native frame review',result='PENDING',evidence=P.relative_to(R).as_posix()+'/PLAN.json')],acceptance_gaps='Motion unreviewed; source4.5 is not action acceptance. Prior A3 action2.7 rejected, current game wash3.9/attention3.8 unchanged. No runtime/cinematic/device/child/owner/all-job/integration/release acceptance; pending old-source reference-upload and browser-status approvals unchanged.'))
for sub in ('inputs','prompts','workflows'):(P/sub).mkdir()
for binding in old['renderer']['bindings']:
    assert sha(OLD/binding['packet_path'])==binding['sha256']
    if binding.get('check_installed_bytes',True):assert sha(Path(binding['installed_path']))==binding['sha256']
    dest=P/binding['packet_path'];dest.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(OLD/binding['packet_path'],dest)
assert sha(R/old['source_path'])==old['source_sha256']
assert sha(OLD/old['input_path'])==old['input_sha256']
shutil.copyfile(OLD/old['input_path'],P/'inputs/NUR-SCRUB-A4.png')
prompt='''Roshan rubs her soapy palms together low over the bowl, looking directly at them. The lower palm remains open and cupped while the upper palm visibly slides along it, forwards and backwards twice. Each stroke travels two finger widths. Her wrists remain joined to her arms, and her low elbows bend naturally to perform the rubbing.
0.0-0.4s: upper palm slides forwards across the lower palm. 0.4-0.8s: slides backwards. 0.8-1.2s: forwards again. 1.2-1.7s: backwards again, settling in the original low palm contact. The hands keep touching; fingers remain open, never clasping or clapping.
Locked camera and steady head, torso, costume, rainbow tail, basin and pedestal. Preserve the soft painted storybook artwork. Faucet stays completely off. Tiny existing lather stays only between the palms. No raised hands, white arches or trails, hair movement, running water, new objects, text or reward effects.
Sound: silence.
'''
(P/'prompts/NUR-SCRUB-A4.txt').write_text(prompt,encoding='utf-8',newline='\n')
m=copy.deepcopy(old);m.update(id='nursery-connected-scrub-v4-20261002',created_utc=now(),input_path='inputs/NUR-SCRUB-A4.png',input_sha256=sha(P/'inputs/NUR-SCRUB-A4.png'),prompt_path='prompts/NUR-SCRUB-A4.txt',prompt_sha256=sha(P/'prompts/NUR-SCRUB-A4.txt'),queue_name='nursery_scrub_a4_20261002',status='BOUND_INPUT_READY_FOR_QUIET_IDLE_DISPATCH',visual_review=None,complete_action_score=None,intention='Two visible purposeful reciprocal low palm strokes with naturally accommodating elbows, then settle; down gaze already present in the source.',comparison=dict(prior_manifest=OLD.relative_to(R).as_posix()+'/MANIFEST.json',prior_review=OLD.relative_to(R).as_posix()+'/attempt01/DIRECT_REVIEW.json',changed='Prompt only: replace tiny/frozen direction with visible opposing palm strokes, explicit beat times and limited natural low elbow movement; tap remains off.',preserved='Exact native source, full technical input, seed2026100201, settings896x512/41frames/24steps and all developed workflow/model bytes. Every previous original/frame/failure/score remains unchanged.'))
m['input_visual_review']=dict(reviewed_utc=now(),method='Literal SHA-identical input to directly inspected A3 wholecanvas',prior_input_path=OLD.relative_to(R).as_posix()+'/'+old['input_path'],prior_input_sha256=old['input_sha256'],source_score_transfer=False,qualification='No input pixel or technical normalization change. A3 input was directly inspected; this is byte equivalence, not new motion acceptance.')
m['clip_contract'].update(timeline=prompt,required_review='Every41 native whole canvas: two visible reciprocal palm-sliding cycles, intended >=12px near palm excursion on896x512, continuously connected wrists/arms, down gaze, off tap, lather only between palms, stable hair/costume/rainbow tail/fixture/support and low resting exit. Measure actual displacement before any success claim. No source or machine score transfer.')
m['jobs'][0].update(id='NUR-SCRUB-A4',name='Visible reciprocal stroke prompt comparison',input_path=m['input_path'],input_sha256=m['input_sha256'],prompt_path=m['prompt_path'],prompt_sha256=m['prompt_sha256'],queue_name=m['queue_name'])
assert m['input_sha256']==old['input_sha256'] and m['prompt_sha256']!=old['prompt_sha256']
write(P/'MANIFEST.json',m)
worker=OLD/'review_tools/queue_nursery_motion_a3_v416.py';code=worker.read_text(encoding='utf-8')
changes={'nursery_connected_scrub_v3_20261002':'nursery_connected_scrub_v4_20261002','NUR-SCRUB-A3':'NUR-SCRUB-A4','build/nursery_local_scrub_a3_active_20261002':'build/nursery_local_scrub_a4_active_20261002'}
for a,b in changes.items():assert a in code;code=code.replace(a,b)
target=P/'review_tools/queue_nursery_motion_a4_v422.py';compile(code,str(target),'exec');target.write_text(code,encoding='utf-8',newline='\n')
write(P/'DISPATCHER_DERIVATION.json',dict(source_path=worker.relative_to(R).as_posix(),source_sha256=sha(worker),changes=changes,qualification='Only packet path/job identity/isolated state directory changed. Benchmark, quiet-idle, duplicate prevention and installed CLI/workflows unchanged.'))
write(P/'PROMPT_COMPARISON.json',dict(status='PASS_PROMPT_ONLY_COMPARISON_READY',prior_manifest=OLD.relative_to(R).as_posix()+'/MANIFEST.json',source_identical=True,source_sha256=m['source_sha256'],input_identical=True,input_sha256=m['input_sha256'],seed_identical=True,seed=m['seed'],settings=m['renderer']['settings'],workflow_bindings_identical=True,prior_prompt_sha256=old['prompt_sha256'],new_prompt_sha256=m['prompt_sha256'],reference_uploaded=False,runtime_integration=False,current_game_action_score=3.9,qualification='Changed prompt only; no motion opinion before complete review.'))
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
attrs=R/'.gitattributes';attrs.write_bytes(attrs.read_bytes()+b'\nassets_src/local_motion/nursery_connected_scrub_v4_20261002/** -text\n')
licenses=R/'ASSET_LICENSES.md';licenses.write_bytes(licenses.read_bytes()+b'\n| `assets_src/local_motion/nursery_connected_scrub_v4_20261002/**` | Existing developed local ComfyUI prompt-only A4 reference using unchanged fresh attentive Nursery native/input | Original project source; source/model provenance inherited from A3 manifest | Exact input/prompt/workflow/receipt hashes | Prompt-only two visible reciprocal strokes; native41-frame review required. Non-runtime motion reference, no external source upload or cinematic delivery. |\n')
note='Prompt-only Nursery A4 planning continuation (2026-10-02): [one bounded local comparison](../assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html) preserves the fresh attentive source, exact input/seed/admitted settings/developed workflow; changes only the tiny/frozen rub prompt to two visible opposing palm strokes with low natural elbows. A3 all41 frames are rejected action2.7/rub2.8/fixture3.0. A4 every41 native frames require independent review; no predicted pass. Current game wash3.9/attention3.8 and all783 production bytes unchanged. [Impact](../design/audit_impacts/job-nursery-scrub-prompt-a4-20261002.json).'
master=R/'audit/MASTER_AUDIT_2026-08-09.md';raw=master.read_text(encoding='utf-8');raw=raw.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+note+'\n',1).replace('### Development task index\n','### Development task index\n\n'+note+'\n',1);master.write_text(raw,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';ledger.write_bytes(ledger.read_bytes()+b'\n| `assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html` | '+ '🟣'.encode()+b' | `CANDIDATE_REFERENCE_ONLY`; prompt-only local comparison, exact fresh source/input/seed/settings/developed workflow unchanged. All41 native frames pending direct review; current game wash3.9/attention3.8 unchanged. No external reference upload/runtime/cinematic/device/child/owner/all-job acceptance. |\n')
(P/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Prompt-only Nursery A4</title><style>body{font:18px system-ui;max-width:1100px;margin:36px auto;padding:0 20px;background:#f1f5fa;color:#253449}img{width:100%;height:auto}</style><h1>Prompt-only Nursery A4</h1><p>One bounded local comparison: exact fresh attentive source/input, seed, admitted settings and developed workflow; prompt now requests two visible opposing palm strokes with natural low elbows.</p><img src="inputs/NUR-SCRUB-A4.png" width="896" height="512" alt="Unchanged whole-canvas technical model input"><p>Rendering and every41 native-frame motion opinions are pending. Source4.5 is separate; A3 action2.7 rejected and current game wash3.9/attention3.8 unchanged. No runtime/cinematic/device/child/owner/all-job acceptance.</p><p><a href="MANIFEST.json">Bound manifest</a> · <a href="PROMPT_COMPARISON.json">Prompt-only comparison</a> · <a href="../nursery_connected_scrub_v3_20261002/index.html">Preserved rejected A3/all41 frames</a></p></html>',encoding='utf-8',newline='\n')
d=read(ip);d['files']=sorted({x.relative_to(R).as_posix() for x in P.rglob('*') if x.is_file()}|{'.gitattributes','ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md'});d['validation'].append(dict(command='Exact source/input/seed/settings/workflow comparison, prompt-only change',result='PASS',evidence=(P/'PROMPT_COMPARISON.json').relative_to(R).as_posix()));write(ip,d)
# Preserve the completed A3 browser proof and correct pending review metadata.
for suffix in ('png','json'):shutil.copyfile(R.parent.parent.parent.parent/'Documents/mermaid-roshan-reef/tmp'/('BROWSER_A3_REVIEW_V421.'+suffix),OLD/('BROWSER_REVIEW_V421.'+suffix))
ai=R/'design/audit_impacts/job-nursery-scrub-fresh-a3-20261002.json';d=read(ai);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in OLD.rglob('*') if x.is_file()});d['validation']=[v for v in d['validation'] if v['result']!='PENDING']
for v in d['validation']:v['evidence']=v['evidence'].replace('every41 visual review pending.','All41 visual opinions completed independently; action2.7 rejected.')
d['validation'].append(dict(command='Actual temporary browser A3 report:7 complete boards/all41 frame cards/video ready896x512',result='PASS',evidence=(OLD/'BROWSER_REVIEW_V421.json').relative_to(R).as_posix()+'; '+(OLD/'BROWSER_REVIEW_V421.png').relative_to(R).as_posix()));write(ai,d)
print('A4_PROMPT_ONLY_READY|exact source/input/seed/settings/workflow|one bounded local FIFO|visual pending|A3 browser proof preserved')
