from pathlib import Path
import datetime,hashlib,html,json,shutil
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
P=R/'assets_src/local_motion/nursery_connected_scrub_v4_20261002';A=P/'attempt01';L=R/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
idx=read(A/'INDEX.json');assert len(idx['frames'])==41 and len(idx['boards'])==7
details=[0,3,8,12,16,20,24,28,32,36,39,40]
rows=[]
for row in idx['frames']:
 i=row['index'];assert sha(R/row['path'])==row['sha256']
 if i==0:score=4.5;note='Original low overlapping palms, quiet attentive gaze and intact source silhouette. A still contact pose demonstrates no reciprocal action.'
 elif i<3:score=4.4;note='Palm cluster remains close to the original contact; small edge/foam changes do not establish the intended forward stroke.'
 elif i<8:score=4.1;note='Extra pale curl/highlight begins beside the faucet base and basin rim despite the tap-off instruction. Hand cluster remains nearly held.'
 elif i<20:score=3.8;note='Thin pale traces accompany the spout/fixture and intermittent hair-edge highlights. Slight finger/lather deformation does not show an upper palm sliding across a distinct lower palm.'
 else:score=3.6;note='Hands change finger/lather shape near the same position instead of two readable reciprocal cycles. Hair, costume/tail and support highlights fluctuate; extra pale fixture traces remain visible. The large A3 head-to-basin arch is absent.'
 if i>=36:note+=' End pose retains joined low contact, but it never completes the directed two strokes or proves a seamless return.'
 rows.append(dict(**row,visual_frame_score=score,evaluation='Frame'+str(i)+' at'+format(row['timestamp_seconds'],'.3f')+'s: '+note+' Down gaze stays legible. Reference-only; current game/still-source scores unchanged.',direct_native_board_review=True,full_native_detail_review=i in details,current_game_score=None,owner_acceptance=None))
opinions=[
 ('source_identity',4.5,'Face, headband/flower and overall quiet helper silhouette remain recognizable; this is reference identity only.'),
 ('attention',4.6,'Eyes retain the source downward attention to the low work area across the entire take.'),
 ('contact',4.3,'Both forearms stay connected and low palms overlap. Later fingertip/lather reshaping makes the exact open lower palm less distinct.'),
 ('reciprocal_action',2.8,'No two clearly readable upper-palm forward/back strokes occur. Finger/foam reshaping and subtle whole cluster drift cannot substitute for sliding across the opposite palm.'),
 ('fixture_material',3.4,'The previous tall head-to-basin arch is absent, an improvement. New pale traces at the off faucet/rim and intermittent hair highlights still lack a truthful water/soap source.'),
 ('costume_tail_support',4.1,'Apron pocket motifs, scales/tail sheen and pedestal highlights crawl during the otherwise near-held body. No gross costume replacement, but temporal surface identity is insufficiently stable.'),
 ('entry_exit',3.5,'Low contact and attentive gaze persist at both boundaries, but the directed action is missing; final fingertip/lather and pale fixture marks differ. No seamless-loop acceptance.'),
 ('whole_action',3.2,'Prompt-only refinement removes the most conspicuous A3 arch but retains near-held hands and false material/identity activity. Reference action remains below4.5 and is rejected.')]
review=dict(status='ALL41_NATIVE_FRAMES_REVIEWED_REFERENCE_ACTION_REJECTED',reviewed_utc=now,boards_reviewed=[x['path'] for x in idx['boards']],native_frame_count=41,full_native_details=details,individual_frames=rows,component_opinions=[dict(item=k,score=s,evaluation=e,current_game_score=None,owner_acceptance=None) for k,s,e in opinions],whole_reference_action_score=3.2,attention_score=4.6,reciprocal_action_score=2.8,fixture_material_score=3.4,predeclared_target=dict(cycles=2,near_palm_screen_excursion_px=12,actual_coordinate_measurement=None,result='VISUAL_ACTION_FAILED; two readable reciprocal cycles absent; no numerical excursion/pass claim'),prior_comparison='A3 all41 reference frames2.7 rejected. A4 prompt-only3.2 removes the large white arch; smaller false pale fixture/hair activity and near-held hands remain. Same exact source/input/seed/settings/workflow.',current_source_score=4.5,current_game_action_score=3.9,current_game_attention_score=3.8,score_transfer=False,qualification='All41 complete native canvases directly inspected on7 original-size boards, with12 additional individual full-native details. Per-frame visual opinions never pass the whole action or current game. No runtime/cinematic/device/child/owner acceptance.')
write(A/'DIRECT_REVIEW.json',review)
write(P/'REVIEW_STATUS.json',dict(status='MACHINE_RENDER_COMPLETE_VISUAL_REJECTED',reviewed_utc=now,whole_reference_action_score=3.2,review_path=(A/'DIRECT_REVIEW.json').relative_to(R).as_posix(),manifest_sha256=sha(P/'MANIFEST.json'),native_prompt_id=idx['prompt_id'],native_frames_reviewed=41,score_transfer=False,runtime_integration=False,owner_approval=None,qualification=review['qualification']))
esc=html.escape
components=''.join('<article><h2>'+esc(k.replace('_',' '))+' · '+str(s)+'/5</h2><p>'+esc(e)+'</p><p>Reference opinion only; current-game score and owner acceptance not transferred.</p></article>' for k,s,e in opinions)
boards=''.join('<section><h2>Complete native frames '+str(b['first'])+'–'+str(b['first']+b['count']-1)+'</h2><a href="attempt01/'+Path(b['path']).name+'"><img src="attempt01/'+Path(b['path']).name+'" width="1792" height="1640" alt="All complete ordered native frames '+str(b['first'])+' through '+str(b['first']+b['count']-1)+'"></a><p>Each original896×512 canvas is pasted once at native size. QA labels only; no source pixels resampled.</p></section>' for b in idx['boards'])
frames=''.join('<article id="frame-'+str(x['index'])+'"><h2>Frame '+str(x['index'])+' · '+str(x['visual_frame_score'])+'/5 visual</h2><p>'+esc(x['evaluation'])+'</p><p><a href="attempt01/native_frames/'+Path(x['path']).name+'">Complete native896×512 original</a> · t='+format(x['timestamp_seconds'],'.3f')+'s</p><p class="hash">SHA-256 '+x['sha256']+'</p></article>' for x in rows)
video=next(Path(x['path']).name for x in idx['outputs'] if x['path'].endswith('.webm'))
(P/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Prompt-only Nursery A4: rejected motion</title><style>body{font:18px/1.5 system-ui;background:#edf4fa;color:#25304a;max-width:1250px;margin:32px auto;padding:0 20px}header,article,section{background:white;border-radius:16px;padding:20px;margin-bottom:22px}video,img{display:block;width:100%;height:auto}a{color:#504096}.hash{font-size:13px;overflow-wrap:anywhere}</style><header><h1>Prompt-only Nursery A4 · action3.2/5 rejected</h1><p>The large A3 white arch is gone, but the hands still do not perform two readable reciprocal strokes. Small false pale faucet/hair activity and costume/tail/pedestal shimmer remain. All41 complete native frames reviewed on7 native-size boards plus12 full-native details.</p><p>Attention4.6, reciprocal action2.8 and fixture material3.4. Source/input/seed/settings/developed workflow are identical to A3; changed prompt only. Native render success is separate from this rejected visual action. Current game wash3.9/attention3.8 and fresh source4.5 remain unchanged.</p><p><a href="attempt01/DIRECT_REVIEW.json">Every individual written frame and component opinion</a> · <a href="attempt01/INDEX.json">All native output/frame hashes</a> · <a href="PROMPT_COMPARISON.json">Prompt-only comparison</a> · <a href="MANIFEST.json">Exact bound generation manifest</a> · <a href="../nursery_connected_scrub_v3_20261002/index.html">Preserved rejected A3</a></p><p>No runtime/cinematic/device/child/owner/all-job/integration/release acceptance.</p></header><video controls preload="metadata" width="896" height="512" src="attempt01/'+video+'"></video><h2>Eight individual source/contact/action opinions</h2>'+components+'<h2>All seven complete native-size boards</h2>'+boards+'<h2>Every individual native frame</h2>'+frames+'</html>',encoding='utf-8',newline='\n')
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
history=L/'history_v38_before_a4_reference';assert not history.exists();history.mkdir()
for name in ('ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json'):shutil.copyfile(L/name,history/(name+'.original'))
d=read(L/'ALL_ITEMS.json');d.update(display_revision='V39_REJECTED_PROMPT_ONLY_NURSERY_A4',updated_utc=now);d['scope']=d['scope'].replace('V38 known register:','V39 known register:')+' Prompt-only local A4 adds a complete41-frame rejected reference action3.2, reciprocal2.8/material3.4/attention4.6. Large A3 white arch removed; no new counted items or current source/runtime opinions.';d.setdefault('review_resources',[]).append(dict(path=P.relative_to(R).as_posix()+'/index.html',scope='All41 prompt-only A4 native frames and8 individual component/action opinions; rejected3.2.'));write(L/'ALL_ITEMS.json',d)
raw=(L/'all_items.html').read_text(encoding='utf-8');raw=raw.replace('</header>','<p><a href="../../assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html">Prompt-only Nursery A4: all41 native frames individually reviewed</a> · reference action3.2 rejected/rubbing2.8/material3.4; attention4.6 remains separate. Current game unchanged.</p></header>',1);(L/'all_items.html').write_text(raw,encoding='utf-8',newline='\n')
note='Prompt-only Nursery A4 review continuation (2026-10-02): [every41 native frame on7 complete native-size boards and12 original details,8 component opinions](../assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html) directly inspected. Reference whole action3.2 rejected/rubbing2.8/fixture3.4, attention4.6 separate. Large A3 arch removed; false pale fixture/hair activity and near-held palms remain. Exact source/input/seed/settings/workflow unchanged; prompt-only. Current game wash3.9/attention3.8 and all783 production bytes unchanged. V39 retains1802 known items/713 source-cell-region priorities/377 source reviews required; reference frames never inflate the counted register. Both pending approvals and all runtime/device/child/owner/all-job/integration/release acceptance remain open.'
master=R/'audit/MASTER_AUDIT_2026-08-09.md';raw=master.read_text(encoding='utf-8');raw=raw.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+note+'\n',1).replace('### Development task index\n','### Development task index\n\n'+note+'\n',1);master.write_text(raw,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';raw=ledger.read_text(encoding='utf-8');start=raw.index('| `assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html`');end=raw.index('\n',start);raw=raw[:start]+'| `assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html` | 🟣 | `REJECTED_REFERENCE_STUDY`; exact fresh source/input/seed/settings/developed workflow unchanged, prompt-only direction change. Every41 native frame directly reviewed on7 native-size boards plus12 full-native details. Reference action3.2/rubbing2.8/fixture3.4 rejected, attention4.6 separate. Current game wash3.9/attention3.8 unchanged. No external reference upload/runtime/cinematic/device/child/owner/all-job acceptance. |'+raw[end:];ledger.write_text(raw,encoding='utf-8',newline='\n')
findings=R/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';findings.write_bytes(findings.read_bytes()+b'\nPrompt-only Nursery A4 review continuation (2026-10-02): [all41 native frames and8 component/action opinions](../../assets_src/local_motion/nursery_connected_scrub_v4_20261002/index.html) directly reviewed; reference action3.2/rubbing2.8/material3.4 rejected, attention4.6 separate. Removes tall A3 arch but hands still fail reciprocal work. Current game wash3.9/attention3.8 and all783 production bytes unchanged. MA-VIS-006/MA-PLAY-004 lifecycles unchanged, all owner/device/child/all-job acceptance open.\n')
ip=R/'design/audit_impacts/job-nursery-scrub-prompt-a4-20261002.json';impact=read(ip);impact['files']=sorted(set(impact['files'])|{x.relative_to(R).as_posix() for x in P.rglob('*') if x.is_file()}|{x.relative_to(R).as_posix() for x in history.rglob('*') if x.is_file()}|{'audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/all_items.html','audit/job_artwork_refinement_live/CURRENT_BOUNDARY_REFRESH.json'});impact['validation']=[v for v in impact['validation'] if v['result']!='PENDING']
for v in impact['validation']:v['evidence']=v['evidence'].replace('every41 visual review pending.','All41 native reviews complete, action3.2 rejected.')
impact['validation'].append(dict(command='Every41 complete native frame on7 native-size boards plus12 original details',result='FAIL',evidence=(A/'DIRECT_REVIEW.json').relative_to(R).as_posix()+'; reference action3.2 rejected/rubbing2.8/material3.4, attention4.6 separate.'))
impact['acceptance_gaps']='All41 native reference frames reviewed, action3.2 rejected. Larger arch removed but two reciprocal strokes absent and false pale fixture/hair activity remains. Current source4.5/current game wash3.9/attention3.8/all783 actual production bytes unchanged. No runtime/cinematic/device/child/owner/all-job/integration/release acceptance; no pending approval bypass.';write(ip,impact)
print('A4_REVIEW_COMPLETE_REJECTED|41 complete native frames|12 original details|action3.2/rub2.8/material3.4|current game unchanged')
