from pathlib import Path
import json,hashlib,datetime,shutil,html,os,subprocess
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');J=R/'audit/job_geology_painted_fracture_trial_v1_20261003';L=R/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
esc=lambda x:html.escape(str(x),quote=True)
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def url(path):return esc(os.path.relpath(R/path,J).replace('\\','/'))
assert not (J/'index.html').exists()
assert read(J/'DIRECT_REVIEW_ATTEMPT02.json')['consecutive_frames']==435
rev=[read(J/f'DIRECT_REVIEW_ATTEMPT0{i}.json') for i in [1,2]]
caps={f'{a}-{w}':read(J/f'attempt0{a}/CAPTURE_{w}.json') for a in [1,2] for w in [1280,1600]}
source='assets/opera/worlds/geology/painted_work_v1_20261001/fossil.png'
def view(path,label):return '<figure><a href="'+url(path)+'"><img loading="lazy" src="'+url(path)+'" alt="'+esc(label)+'"></a><figcaption>'+esc(label)+'</figcaption></figure>'
parts=['''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geologist — painted fossil fracture review</title>
<style>:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#eff4f6;color:#22334c;font:16px/1.55 system-ui,sans-serif}main{max-width:1360px;margin:auto;padding:28px}header,section{background:white;border:1px solid #cbd7e3;border-radius:18px;padding:24px;margin:0 0 24px}h1,h2,h3{line-height:1.2;color:#33415d}h1{font-size:32px;margin:10px 0}a{color:#284b91}p{max-width:1000px}.tag{display:inline-block;background:#e9e1f6;color:#53376e;padding:4px 12px;border-radius:16px;font-weight:650}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:18px}figure{margin:0}img{width:100%;height:auto;display:block;border-radius:8px;background:#f5f1fa}figcaption{font-size:14px;padding:7px 0}table{width:100%;border-collapse:collapse;font-size:15px}td,th{text-align:left;border-bottom:1px solid #d8e0e9;padding:12px;vertical-align:top}th{background:#f2f1f7}td:first-child{width:170px}td:nth-child(2){width:80px;font-weight:750}details{margin:18px 0;background:#f7f8fb;border-radius:10px;padding:14px}summary{cursor:pointer;font-weight:650}small,.muted{color:#58697c}code{overflow-wrap:anywhere;font-size:12px}button,select{padding:8px 12px;font:inherit;border:1px solid #899cb4;border-radius:7px;background:white}input[type=range]{width:100%}#frameCaption{overflow-wrap:anywhere}.frame-list{columns:3;font-size:13px}.frame-list a{display:block;margin:5px 0;break-inside:avoid}.table-wrap{overflow:auto}.source{max-width:500px;background:repeating-conic-gradient(#eee 0% 25%,#fff 0% 50%) 0/24px 24px}@media(max-width:720px){main{padding:10px}header,section{padding:16px}.frame-list{columns:1}table{min-width:850px}} </style>
<main><header><span class="tag">Reversible review candidate · production unchanged</span><h1>Painted fossil fragments, honest action review</h1>
<p>The second trial keeps the original painted fossil and gives each piece a complementary irregular fracture with a restrained plum contour. Its three fragments and reassembled specimen reach a <strong>provisional 4.5/5</strong>. The complete action remains <strong>3.6/5</strong>: the soil reveal jumps, the pieces appear at distant homes and Roshan’s hands do not contact the specimen.</p>
<p>Both attempts remain unbound. The current game still uses its previous fragment renderer and retains its own <strong>whole fossil action 3.2/5</strong> opinion. A1’s unfinished cut edges score4.4 and are preserved. A score4.5 meets the provisional floor and remains an inclusive priority.</p>
<p><a href="../job_artwork_refinement_live/all_items.html">All1821 known items and their current scores</a> · <a href="../job_geology_complete_actions_v1_20261003/index.html">Actual complete fossil/pan review</a> · <a href="../job_geode_current_recheck_v1_20261002/index.html">Corrected geode — crystals rooted inside both halves</a> · <a href="../job_geology_painted_invitation_fit_v1_20261003/index.html">Painted invitation and tray fit trials</a></p>
<p class="muted">Both widths, both complete trials:868 consecutive captured frames (864 fossil frames and four next-phase invitation endpoints),116 selected native canvases,94 ordered QA boards and40 independently inspected original native details. Twenty-four written component/action opinions. All783 production source files unchanged. Owner acceptance, physical device, child, ordinary story travel and comprehensive all-job completion remain open;377 source reviews remain outstanding.</p></header>''']
latest=caps['2-1280']['views']
hero=next(x['path'] for x in latest if x['path'].endswith('_phase1_brushed.webp'))
joined=next(x['path'] for x in latest if x['path'].endswith('_phase1_earned_completion.webp'))
parts+=['<section><h2>Latest fragment and join comparison</h2><div class="grid">',view(hero,'A2: exposed irregular fragments, original painted material, current action/contact weaknesses still visible.'),view(joined,'A2: all three snapped; added internal contours suppressed and original spiral restored.'),'</div></section>']
parts+=['''<section><h2>Inspect the complete sequence</h2><p>Every original full canvas is available below. Use the slider to inspect brush removal, sudden separation, dragging, snaps, completion hold and the next invitation. Captures follow actual intentional input and inherited mechanics; slow native readback does not establish natural phone timing.</p><label>Trial / native aspect <select id="lane"><option value="2-1280">A2 ·1280×720</option><option value="2-1600">A2 ·1600×720</option><option value="1-1280">A1 ·1280×720</option><option value="1-1600">A1 ·1600×720</option></select></label> <button id="previous">Previous</button> <button id="next">Next</button><input id="frameIndex" type="range" min="0" value="0"><a id="frameLink"><img id="frame" alt="Complete original captured native canvas"></a><p id="frameCaption"></p></section>''']
for a,r in enumerate(rev,1):
 parts.append(f'<section id="attempt0{a}"><h2>Attempt{a}: individual evaluations</h2><p>{r["consecutive_frames"]} consecutive frames /{r["selected_views"]} selected views /47 boards /20 original native details directly inspected. Source material, objects, contact and complete action are scored separately.</p><div class="table-wrap"><table><thead><tr><th>Item</th><th>Score /5</th><th>Written evaluation</th><th>Refinement</th></tr></thead><tbody>')
 for o in r['opinions']:parts.append('<tr><td>'+esc(o['item'])+'</td><td>'+str(o['score'])+'</td><td>'+esc(o['evaluation'])+'</td><td>'+esc(o['refinement'])+'</td></tr>')
 parts.append('</tbody></table></div><p><a href="DIRECT_REVIEW_ATTEMPT0'+str(a)+'.json">Exact review, hashes and scope</a></p>')
 for w in [1280,1600]:
  cap=caps[f'{a}-{w}']
  parts.append(f'<details><summary>All29 selected full canvases · A{a} ·{w}×720</summary><div class="grid">')
  for x in cap['views']:parts.append(view(x['path'],f'{x.get("phase_index","route")} · {x["state"]} · '+x['sha256'][:12]))
  parts.append('</div></details>')
  parts.append(f'<details><summary>All{len(cap["motion_frames"])} original consecutive frames · A{a} ·{w}</summary><div class="frame-list">')
  for x in cap['motion_frames']:
   parts.append('<a href="'+url(x['path'])+'">'+str(x['index'])+' · '+esc(x['surface'].get('stage',''))+' · '+str(x['time_msec'])+'ms · '+x['sha256'][:12]+'</a>')
  parts.append('</div><p><a href="attempt0'+str(a)+'/CAPTURE_'+str(w)+'.json">Original complete event/state/hash capture record</a></p></details>')
 parts.append('<details><summary>All47 ordered QA boards — full-aspect thumbnails, originals authoritative</summary><div class="grid">')
 for b in read(J/f'QA_BOARD_MANIFEST_A{a}.json')['boards']:parts.append(view(b['path'],f'{b["width"]} · {b["kind"]} · {b["first"]}–{b["last"]}, row-major; final blanks are not frames.'))
 parts.append('</div></details><details><summary>Twenty independently inspected original native details</summary><div class="grid">')
 for x in r['native_details']:parts.append(view(x['path'],Path(x['path']).name+' · '+x['sha256'][:12]))
 parts.append('</div></details></section>')
parts+=['<section><h2>Original material and reversible implementation</h2><p>The approved intact ammonite source already supplies the broad lavender stone bands, warm spiral and authored outer contour. The defect was its arbitrary straight-third renderer. New image generation would discard suitable material unnecessarily. The trial uses textured Canvas polygons; every pixel comes from the original raster with its original UV mapping, while shared boundaries partition the entire atlas without overlap. The2px plum lines are drawn only along opaque exposed cuts and disappear after neighboring snaps.</p><div class="source">',view(source,'Unchanged1024×1024 original fossil; transparency shown on checkerboard.'),'</div><p><code>'+source+'<br>SHA-256 '+sha(R/source)+'</code></p><p><a href="PLAN.json">Inventory and scoped plan</a> · <a href="PARTITION_GEOMETRY_PROOF.json">Complementary geometry and conserved UV proof</a> · <a href="painted_fracture_surface.gd">A2 renderer</a> · <a href="capture.gd">Actual-input review fixture</a> · <a href="attempt01/fixture_originals/painted_fracture_surface.gd.original">Exact A1 renderer</a> · <a href="attempt01/fixture_originals/capture.gd.original">Exact A1 fixture</a> · <a href="attempt01/fixture_originals/production_geology_surface.gd.original">Untouched production renderer</a></p><p>Touch margins, homes, targets, restore, progress, completion and actual world signal callables remain inherited. One explicit draw-only surface substitution occurs before inputs, with snapshot/transform/callback checks. No forced phases or completed results. Actual Library card → four intentional phases → normal earned Library return; Opera elevator developer entry/Back is a separate replay path. No ChapterTwo Geologist story set or enabled two-act rollout is inferred. Pan/geode have selected views in this trial; their complete actual actions have separate reports.</p></section>']
parts.append('<section><h2>Machine evidence and publication receipts</h2><p>All six checks for each attempt pass: parser, inference lint, official Godot4.7.2 analyzers for renderer and fixture, and fresh actual-input captures at both widths. Machine success does not accept the graphics, complete action, target device, child, owner, global2D debt or release.</p><ul>')
for a in [1,2]:
 for p in sorted((J/f'runtime_gate_a{a}').glob('*.receipt.json')):
  d=read(p);parts.append('<li>A'+str(a)+' · <a href="'+esc(os.path.relpath(p,J).replace('\\','/'))+'">'+esc(p.stem)+' · '+esc(d['status'])+'</a></li>')
parts+=['</ul><p><a href="SOURCE_CURRENT_BEFORE_CAPTURE.json">All783 original literal source hashes</a> · <a href="REGISTER_CHANGE_PROOF_V41.json">V41 candidate-only register proof</a> · <a href="QA_CELL_SPOT_CHECK_V466.json">Five thumbnail ordering spot checks, literal pixel differences retained</a> · <a href="PREFLIGHT_V465.json">Preserved pre-capture runner launch error and correction</a> · <a href="REPORT_HELPER_V467.json">Preserved report helper errors and bounded continuation</a></p><p>The prior immutable T revision was anonymously fetched and byte verified for every18803 required files including its closed map. Its full journal is durably preserved in ten lossless bounded parts, never replaced by a summary alone. This receipt concerns T only; the new review’s publication and hosted status require their own exact revision evidence.</p><p><a href="previous_t_remote_verified/RESULT.json">T remote verification receipt — revision, hashes, access mode and time</a> · <a href="previous_t_remote_verified/JOURNAL_INDEX.json">Every18803 row — lossless journal index</a> · <a href="https://github.com/Ebonyks/mermaid-roshan-reef/tree/ce154e1452c92252b90f5455989a21726d94ff62">Immutable T tree</a> · <a href="https://raw.githubusercontent.com/Ebonyks/mermaid-roshan-reef/ce154e1452c92252b90f5455989a21726d94ff62/audit/job_review_v2_20261001/GEOLOGY_COMPLETE_ACTION_AND_TRAY_SUPPLEMENT_FILES_V17.json">Direct T closed manifest</a></p><p>Outstanding priorities: fossil reveal/contact/celebration, pan motion/material continuity, flat room and currently flat trays, current Nursery washing/action/attention and remaining all-job source/action reviews. Original blocked Nursery reference upload and browser persistence requests remain pending; neither is retried. No finding lifecycle, production binding, dev/master integration or release acceptance is claimed.</p></section>']
jsdata={k:[dict(path=os.path.relpath(R/x['path'],J).replace('\\','/'),index=x['index'],time_msec=x['time_msec'],stage=x['surface'].get('stage',''),snapped=x['surface'].get('snapped'),complete=x['surface']['complete'],sha256=x['sha256']) for x in v['motion_frames']] for k,v in caps.items()}
parts.append('<script>const lanes='+json.dumps(jsdata,separators=(',',':'))+';const lane=document.getElementById("lane"),slider=document.getElementById("frameIndex"),img=document.getElementById("frame"),link=document.getElementById("frameLink"),caption=document.getElementById("frameCaption");function render(){const rows=lanes[lane.value];slider.max=rows.length-1;slider.value=Math.min(Number(slider.value),rows.length-1);const f=rows[slider.value];img.src=f.path;link.href=f.path;caption.textContent=`Frame${f.index}/${rows.length-1} · ${f.stage} · captured ${f.time_msec}ms · snapped ${JSON.stringify(f.snapped)} · complete ${f.complete} · SHA-256 ${f.sha256}`;}lane.onchange=()=>{slider.value=0;render()};slider.oninput=render;document.getElementById("previous").onclick=()=>{slider.value=Math.max(0,Number(slider.value)-1);render()};document.getElementById("next").onclick=()=>{slider.value=Math.min(Number(slider.max),Number(slider.value)+1);render()};render();</script></main></html>')
(J/'index.html').write_text('\n'.join(parts)+'\n',encoding='utf-8',newline='\n')
note='Painted fossil fracture continuation (2026-10-03): [both reversible trials and every868 consecutive frame/116 selected native canvases](PATH) directly reviewed on94 ordered boards plus40 original native details. A1 exposed edges4.4 rejected; A2 three fragments/join4.5 provisional, whole action3.6 remains belowfloor. Original painted source conserved; runtime fragment renderer, actual whole fossil3.2/pan3.4/contact2.7 and all783 production files unchanged. V41 appends24 unbound candidate opinions without changing1821 counted items/713 inclusive source-cell-region priorities/572 unique source-file priorities/38 current Geologist/10 Nursery/377 source reviews outstanding. All18803 T anonymous byte-verification rows preserved losslessly. No production/device/child/owner/all-job/finding lifecycle/integration/release acceptance.'
mp=R/'audit/MASTER_AUDIT_2026-08-09.md';t=mp.read_text(encoding='utf-8-sig');anchor='### Development task index\n';assert anchor in t;t=t.replace(anchor,anchor+'\n'+note.replace('PATH','job_geology_painted_fracture_trial_v1_20261003/index.html')+'\n',1);mp.write_text(t,encoding='utf-8',newline='\n')
ap=R/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';t=ap.read_text(encoding='utf-8-sig');t+='\n'+note.replace('PATH','../job_geology_painted_fracture_trial_v1_20261003/index.html')+' MA-VIS-006/MA-PLAY-004/MA-OPERA-012 retain existing lifecycle states.\n';ap.write_text(t,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';t=ledger.read_text(encoding='utf-8-sig');t+='\n| `audit/job_geology_painted_fracture_trial_v1_20261003/index.html` | 🟣 | `CANDIDATE_REVIEW`; two explicit draw-only counterfactuals with unchanged original raster. All868 consecutive frames/116 views/94 boards/40 original native details directly reviewed;24 component/action opinions. A1 cut edges4.4 rejected;A2 fragments/join4.5 provisional, whole3.6 belowfloor. V41 current production scores/counts and all783 source files unchanged. Complete18803 T anonymous rows durably lossless. No production/action/device/child/owner/all-job/finding closure/integration/release acceptance. |\n';ledger.write_text(t,encoding='utf-8',newline='\n')
lic=R/'ASSET_LICENSES.md';t=lic.read_text(encoding='utf-8-sig');t+='\n| `audit/job_geology_painted_fracture_trial_v1_20261003/attempt0{1,2}/native_{frames,views}/*`, `qa_boards/*` | Native game review captures and ordered QA thumbnails; unchanged painted fossil source `assets/opera/worlds/geology/painted_work_v1_20261001/fossil.png` retains its existing provenance/license row | Project review evidence; original underlying asset licenses unchanged | Local official Godot4.7.2 inherited input capture; source URL/provenance follows existing fossil row | Non-runtime draw-only textured-Canvas partition and exposed-edge contour trial; full native canvases, lossless review capture, FFmpeg QA scaling/tiling only. No source bitmap edits, new source generation, protected original change or production/cinematic delivery. A1/A2 and failures preserved. |\n';lic.write_text(t,encoding='utf-8',newline='\n')
attrs=R/'.gitattributes';t=attrs.read_text(encoding='utf-8-sig');t+='\n# Exact native evidence, raw logs, journals and immutable V40 history for fossil review.\naudit/job_geology_painted_fracture_trial_v1_20261003/** -text\naudit/job_artwork_refinement_live/ALL_ITEMS_V40.original.json -text\naudit/job_artwork_refinement_live/all_items_V40.original.html -text\naudit/job_artwork_refinement_live/BOUNDARY_V40.original.json -text\n';attrs.write_text(t,encoding='utf-8',newline='\n')
shutil.copyfile(Path(__file__),J/'review_tools'/Path(__file__).name)
ip=R/'design/audit_impacts/job-geology-painted-fracture-trial-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in J.rglob('*') if x.is_file()}|{x.relative_to(R).as_posix() for x in [mp,ap,ledger,lic,attrs]});write(ip,d)
allowed=R/'tmp/v2_preview_allowed.json';a=read(allowed)
if isinstance(a,list):a=sorted(set(a)|{x.relative_to(R).as_posix() for x in J.rglob('*') if x.is_file()})
elif isinstance(a,dict):
 key='allowed' if 'allowed' in a else 'paths';assert isinstance(a.get(key),list),list(a);a[key]=sorted(set(a[key])|{x.relative_to(R).as_posix() for x in J.rglob('*') if x.is_file()})
else:raise AssertionError(type(a))
write(allowed,a)
print(json.dumps({'status':'COMPLETE_ILLUSTRATED_DUAL_TRIAL_DRAFT','html_bytes':(J/'index.html').stat().st_size,'opinions':24,'frames':868,'selected_views':116,'boards':94,'native_details':40,'current_production':'UNCHANGED','owner_acceptance':None}))
