from pathlib import Path
import json,shutil,datetime,subprocess,hashlib
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');J=R/'audit/job_geology_painted_fracture_trial_v1_20261003'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
for src,dest in [('geology_fracture_report_v470.png','BrowserSequenceReviewV470.png'),('geology_fracture_hero_v470.png','BrowserLatestFragmentsV470.png')]:shutil.copyfile(Path(__file__).with_name(src),J/dest)
write(J/'BROWSER_REVIEW_V470.json',{'status':'ILLUSTRATED_REPORT_AND_SEQUENCE_CONTROLS_VERIFIED','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tab':'52','report':'index.html','controls':'Next changes A2 1280 frame0→1; aspect selector A2 1600 resets frame0/214 with correct original-native SHA. Both hero images and current/candidate qualifications visibly rendered.','screenshots':['BrowserLatestFragmentsV470.png','BrowserSequenceReviewV470.png'],'qualification':'Temporary read-only browser review, no persistence mark/status acceptance. Screenshots are page QA, not additional artwork or whole-action acceptance.'})
gh='C:/Program Files/GitHub CLI/gh.exe'
raw=subprocess.check_output([gh,'run','view','37090563245','--repo','Ebonyks/mermaid-roshan-reef','--json','headSha,status,conclusion,updatedAt,jobs,url'],cwd=R)
host=json.loads(raw);assert host['headSha']=='ce154e1452c92252b90f5455989a21726d94ff62'
host['captured_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();host['qualification']='Exact parent T hosted snapshot, separate from new U, visual/action/device/child/owner acceptance. Literal remaining/failing/advisory states unwaived.'
write(J/'previous_t_remote_verified/HOSTED_T_SNAPSHOT_V471.json',host)
print(json.dumps({'parent_T_status':host['status'],'parent_T_conclusion':host['conclusion'],'jobs':[{'name':x['name'],'status':x['status'],'conclusion':x['conclusion']} for x in host['jobs']]}),flush=True)
gates=Path(__file__).with_name('run_geology_report_gates_v453.py').read_text(encoding='utf-8-sig')
start=gates.index("py='C:/Users/Peter/AppData/Local/Python/bin/python.exe'")
end=gates.index('for packet,impact in')
header="from pathlib import Path\nimport json,datetime,hashlib,shutil,subprocess,concurrent.futures,time\nR=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');J=R/'audit/job_geology_painted_fracture_trial_v1_20261003';F=J\ndef read(p):return json.loads(p.read_text(encoding='utf-8-sig'))\ndef write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\\n',encoding='utf-8',newline='\\n')\nsha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()\n"
gates=header+gates[start:end]+"d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in J.rglob('*') if x.is_file()});d['validation'] += [dict(command=' '.join(x['command']),result='PASS' if x['status']=='PASS' else 'FAIL',evidence=(G/(label+'.receipt.json')).relative_to(R).as_posix()) for label,x in results];write(ip,d)\nassert all(x['status']=='PASS' for _,x in results),[(label,x['status']) for label,x in results]\nprint('U_FRESH_EXISTING_AUTHORITY_COVERAGE_2D_DOCUMENT_TESTS_PASS')\n"
gates=gates.replace('job-geology-complete-actions-20261003.json','job-geology-painted-fracture-trial-20261003.json')
compile(gates,'run_geology_report_gates_u_v472.py','exec');(J/'review_tools/run_geology_report_gates_u_v472.py').write_text(gates,encoding='utf-8',newline='\n')
shutil.copyfile(J/'review_tools/run_geology_report_gates_u_v472.py',Path(__file__).with_name('run_geology_report_gates_u_v472.py'))
publisher=(R/'audit/job_geology_complete_actions_v1_20261003/review_tools/publish_geology_checkpoint_t_v455.py').read_text(encoding='utf-8-sig')
for a,b in [('tmp/geology_review_t_publish_v455','tmp/geology_review_u_publish_v474'),('tmp/geology_review_t_remote_v455','tmp/geology_review_u_remote_v474'),('tmp/geology_review_t_sealed_v456.json','tmp/geology_review_u_sealed_v473.json'),('EXACT_SCOPED_GEOLOGY_T_BLOBS_SEALED','EXACT_SCOPED_GEOLOGY_U_BLOBS_SEALED'),('37086150331','37090563245'),('HOSTED_S_FINAL.json','HOSTED_T_FINAL.json'),('PARENT_S','PARENT_T'),('Exact parent S','Exact parent T')]:
 assert a in publisher,a;publisher=publisher.replace(a,b)
start=publisher.index("C=R/'audit/job_geology_complete_actions_v1_20261003'");end=publisher.index("assert len(read(R/'audit/job_artwork_refinement_live",start)
replacement="J=R/'audit/job_geology_painted_fracture_trial_v1_20261003'\nfor label in ('game2d','authority','development','document_tests'):assert read(J/'gates'/(label+'.receipt.json'))['status']=='PASS',label\nfor attempt in (1,2):\n cr=read(J/f'DIRECT_REVIEW_ATTEMPT0{attempt}.json');assert cr['consecutive_frames']==(433 if attempt==1 else 435) and cr['selected_views']==58 and len(cr['opinions'])==12 and cr['production_binding'] is False\n assert all(x['direct_review'] for x in read(J/f'QA_BOARD_MANIFEST_A{attempt}.json')['boards'])\n"
publisher=publisher[:start]+replacement+publisher[end:]
start=publisher.index("msg=out/'COMMIT_MESSAGE.txt'");end=publisher.index("run('commit'",start)
message='Record reversible painted fossil fracture trials and complete individual review\n\nReuse the unchanged1024-square painted ammonite source rather than regenerate suitable artwork. In a non-runtime inherited geology surface, partition its original atlas into three complementary irregular textured Canvas polygons with conserved UVs, mechanics and touch margins. Preserve exact A1 draw/capture fixtures before adding A2 restrained plum exposed-edge contours, bounded by read-only original alpha and suppressed after neighboring snaps. All production files remain unchanged.\n\nCapture actual intentional Library four-phase route, earned return and separate Opera elevator replay/Back at1280/1600 for each trial. Directly inspect every868 consecutive native input/wait frame (864 fossil and4 next-phase endpoints),116 selected canvases,94 full-aspect ordered boards and40 original native details. Record24 individual source/material/object/contact/transition/action opinions. A1 exposed cuts4.4 rejected; A2 fragments and join4.5 provisional, whole3.6 remains weak. Current production fossil3.2/pan3.4/contact2.7/room2.8 remain separate; the rooted geode opening is unchanged.\n\nAppend candidate history to illustrated registerV41 without changing1821 items, current source/mounted/action scores or priority counts. Preserve exact V40 register/page/boundary. Display both trials, all frames, opinions, original texture/fixtures/proof and failures. All783 production hashes unchanged. Preserve every18803 prior T anonymous remote journal row in10 bounded lossless shards, exact revision receipt and hosted snapshot.\n\nBoth trials pass parser/inference/officialGodot4.7.2 analyzers and fresh actual-input captures at both widths. Existing unchanged authority/coverage/52 document tests/2D no-regression and postcommit gates remain required; machine results do not pass graphics or strict-zero2D debt. Preserve pre-capture runner and report helper errors plus bounded corrections; no gate waiver. Topic publication waits for exact parent T hosted success and anonymously byte-verifies every new/unchanged closed-map dependency.\n\nNo runtime/protected original/source bitmap/security/workflow change, rejected reference upload/browser-persistence retry, owner approval, finding lifecycle closure, complete all-job/device/child acceptance, dev/master integration or release.\n'
publisher=publisher[:start]+"msg=out/'COMMIT_MESSAGE.txt';msg.write_text("+repr(message)+",encoding='utf-8',newline='\\n')\n"+publisher[end:]
publisher=publisher.replace('Exact parent T hosted completion; separate from new S','Exact parent T hosted completion; separate from new U')
publisher=publisher.replace('Durable geology action/source/three-trial review checkpoint only. All783 production bytes unchanged. Current fossil3.2/pan3.4/contact2.7/room2.8 remain weak. New tray4.6 and A3 selected prop floors4.5 remain unbound; whole counterfactual room4.2.','Durable dual fossil-fracture review checkpoint only. All783 production bytes unchanged. A1 fragment4.4 rejected;A2 fragments/join4.5 provisional,whole3.6 weak. Current fossil3.2/pan3.4/contact2.7/room2.8 remain independent.')
publisher=publisher.replace("time.sleep(60)","time.sleep(45)")
compile(publisher,'publish_geology_checkpoint_u_v474.py','exec');(J/'review_tools/publish_geology_checkpoint_u_v474.py').write_text(publisher,encoding='utf-8',newline='\n')
shutil.copyfile(J/'review_tools/publish_geology_checkpoint_u_v474.py',Path(__file__).with_name('publish_geology_checkpoint_u_v474.py'))
shutil.copyfile(Path(__file__),J/'review_tools'/Path(__file__).name)
ip=R/'design/audit_impacts/job-geology-painted-fracture-trial-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{x.relative_to(R).as_posix() for x in J.rglob('*') if x.is_file()});write(ip,d)
print('U_PUBLISHER_AND_FRESH_GATES_PREPARED_NOT_PUBLISHED')
