from pathlib import Path
import copy, datetime, hashlib, html, json, shutil, subprocess

b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');q=b/'audit/job_shared_entrance_sources_v1_20261003';l=b/'audit/job_artwork_refinement_live'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d,compact=False):
    n=p.with_name(p.name+'.new');n.write_text(json.dumps(d,ensure_ascii=False,**({'separators':(',',':')} if compact else {'indent':2}))+'\n',encoding='utf-8',newline='\n');assert json.loads(n.read_text(encoding='utf-8'))==d;n.replace(p)
plan=json.loads((q/'PLAN_AND_SOURCE_BOUNDARY.json').read_text(encoding='utf-8'))
assert not (q/'DIRECT_NATIVE_REVIEW.json').exists()
# Individually observed native-sheet/cell opinions. No score is borrowed from a machine gate.
data={
1:(4.5,'The scalloped cream shell basin and gold tap have rounded silhouettes and broad painted highlights. A thin pale lip and speckled edge remain at the inclusive refinement threshold. All eight fixture states omit the stream; that source fact does not establish a missing runtime stream because the caller may supply it separately.','Retain the basin/tap identity. Check the actual handle-to-stream contact and basin ripple in the current room; inspect edge clarity against that room before any local cleanup.',[
(4.5,'Closed tap and fluted basin read clearly; the pale outer lip needs a contextual edge check.'),(4.5,'Left handle turns outward while the shell and spout retain their main shape; no stream is authored in this cell.'),(4.5,'The next handle angle is readable without changing the bowl identity; water contact still requires the caller.'),(4.5,'Handle rotates downward beside the stem; the shell rim stays visibly separated from the tap.'),(4.5,'The returning handle angle preserves the gold stem and cream shell; minor lip sparkle remains.'),(4.5,'Handle is again tucked near the stem; no authored stream or basin-water payoff is visible.'),(4.5,'Return angle remains legible, with a slightly different basin edge width from rest.'),(4.5,'Final fixture resembles the closed rest; source sequencing alone cannot prove a completed water action.')]),
2:(4.2,'Copper pan one is painted and immediately recognizable. Its bowl changes from tall oval to broad shallow oval and then narrow oval while the hanging eye remains fixed; the handle also bends. Those are material/topology continuity gaps for a solid suspended pan.','Reuse the established copper rest identity; repair only failed swing states with a consistent rigid bowl, handle and fixed hook. Reduce mottled specular detail if it competes at mounted phone scale.',[
(4.4,'Rest has a clear hanging eye and warm copper bowl; fine mottled highlights are busier than broad storybook bands.'),(4.3,'Bowl shifts sideways beneath the fixed eye, but the neck bows and changes its apparent thickness.'),(4.1,'Bowl becomes a wide shallow ellipse without a matching rigid handle orientation; the solid-pan identity distorts.'),(4.2,'Bowl snaps to a tall narrow shape and the handle straightens, giving an inconsistent swing extreme.'),(4.3,'Bowl recovers its oval, but the bottom highlight and rim thickness drift from rest.'),(4.3,'Neck curves left while the bowl remains nearly front-facing; rigid suspension is not supported by this state.'),(4.4,'Bowl is broader and shallower than rest with a clearer rim; keep shape constant across the swing.'),(4.4,'Return retains the copper identity but differs in width and highlight pattern from the initial state.')]),
3:(4.3,'Copper pan two has a readable oval hanging eye and shallow bowl. Turned views are more plausible than pan one, but bowl depth, side wall and handle connection change markedly between keys.','Keep the painted rest and the intended hook swing. Redraw only discontinuous turned states with consistent side thickness, neck length and shared support pivot; actual temporal/contact review stays open.',[
(4.5,'Front rest is round and legible, with a clear rim and hanging eye.'),(4.5,'Small early turn preserves the shallow bowl and ring silhouette.'),(4.4,'Side wall begins to appear while the rim and handle junction thicken relative to rest.'),(4.3,'Stronger turn produces a deeper bowl and offsets the neck, weakening rigid-object continuity.'),(4.2,'Extreme turned view becomes narrow and deep; its side thickness and neck do not match the preceding state.'),(4.3,'Return view widens abruptly and loses much of the side wall.'),(4.4,'Near-front return keeps the hanging eye, but the bowl width and highlight differ from the opening.'),(4.5,'Final front state is readable and close to rest; full sequence still needs corrected intermediate geometry.')]),
4:(4.2,'Copper pan three keeps its broad circular silhouette and fixed ring but moves dark dents and bright hotspots around the bowl. The changing internal topography reads as a morphing surface rather than the documented swing.','Reuse the round copper design. Establish real orientation changes from the fixed hook and keep the bowl surface and painted light bands coherent; preserve the original source as history.',[
(4.4,'Round rest and short neck are clearly identifiable; hammered texture is relatively busy.'),(4.3,'A dark upper-left indentation appears where rest has a flatter painted surface.'),(4.2,'The dark indentation moves to the center while the outer bowl remains nearly unchanged.'),(4.3,'A high-right specular bulge replaces the previous center depression; topology reads differently.'),(4.2,'A dark lower-right dent appears without a corresponding overall pan turn.'),(4.3,'A lower central hotspot replaces the dent while the fixed ring and outline remain similar.'),(4.2,'The center dark spot returns, making the material appear to change shape.'),(4.3,'Final bowl is recognizable, but its highlight and surface depth differ from the initial state.')]),
5:(4.2,'The long copper ladle is a useful rounded prop. Several swing states bend its slender solid handle and alter the cup-to-handle joint instead of rotating one coherent object from the hanging eye.','Keep the rest ladle silhouette. Repair the bent intermediate handles, retain a rigid connection to the bowl, and inspect the rack contact at actual scale before acceptance.',[
(4.5,'Straight rest handle and small cup form a readable ladle silhouette.'),(4.4,'First slight turn narrows the cup, but the handle starts to bow.'),(4.2,'Handle develops a pronounced S bend while the hook stays fixed; solid-metal behavior fails.'),(4.3,'Handle bends into the neck as the cup shifts angle; junction consistency is weak.'),(4.2,'Extreme side cup is much thinner and the shaft bends sharply toward it.'),(4.4,'Returning cup remains narrow, with a softer curved neck than rest.'),(4.5,'Near-front return has a clear rounded cup and restrained copper highlights.'),(4.5,'Final cup and long neck remain legible; reuse after failed middle states are repaired.')]),
6:(4.4,'The shell oven is substantially painted and has a clear hinged-door action. Pale rim/fringe pixels and the cropped remnant on the top edge need contextual ownership review; the open door changes apparent width/hinge shape among states.','Preserve the oven body and lavender/gold identity. Verify the top-edge remnant against its owned room card and correct only proven foreign pixels; match door geometry across the opening and closing keys.',[
(4.5,'Closed lavender door and gold fittings sit clearly in the cream shell body; top-edge remnant remains visible.'),(4.4,'First lowering reveals warm interior, but the door rim thickens and shifts across the opening.'),(4.4,'Half-open panel is readable; hinge line and panel width need consistency with the closed door.'),(4.3,'Near-horizontal panel extends far right and becomes thinner, weakening the door-to-body connection.'),(4.4,'Fully lowered panel exposes the warm interior; its shape differs from the prior horizontal state.'),(4.4,'Closing panel regains a thicker rim and slightly different width.'),(4.4,'Near-closed door is readable, with altered lower edge geometry and pale fringe.'),(4.5,'Closed endpoint preserves the oven identity; source still does not prove mounted hand or safe heat contact.')]),
7:(4.5,'The mint shell fridge is a strong reusable painted prop: rounded door, gold handle and child-readable food clusters. Slight body/door outline changes and large discrete opening steps remain at the inclusive threshold for the whole source sequence.','Keep these exact strong rest and open states; check the current authored timeline, hinge continuity, recipe-menu handoff and room alpha ownership before repairing any bridge. Do not regenerate the established design for novelty.',[
(4.6,'Closed mint door, shell badge and long gold handle are coherent with the painted Castle family.'),(4.6,'Early latch/door state preserves the rounded fridge identity and restrained pastel shading.'),(4.5,'Narrow reveal shows real shelf contents; door/body edge alignment needs comparison with the next wide opening.'),(4.6,'Wide-open shelves present grouped fruit, milk and a cake clearly while the door remains attached.'),(4.6,'Second open key retains the same food arrangement and supported fridge body.'),(4.5,'Closing door returns to a narrow reveal in a large discrete step; intermediate motion is unverified.'),(4.5,'Near-closed state remains legible but has a slightly shifted edge and bottom outline.'),(4.6,'Closed endpoint remains a strong reusable mint/gold shell fixture.')]),
10:(4.5,'The Kitchen left foreground combines a lavender pot, coral, a teal utensil cup and a pearl shell bowl into a painted, rounded cluster. It is comparatively dense; its value separation from Roshan requires current mounted review.','Reuse the existing composition. Check foreground occlusion and calm the mounted scale or layering if needed; no source redesign is warranted without that evidence.',[]),
11:(4.1,'The Kitchen right foreground has a warm painted shell table, pink bowl and teal vessel. A disconnected lavender corner fragment sits at bottom right, and the table perimeter has irregular pale edges; a standalone ownership card is incomplete.','Trace the fragment to its original room ownership before deriving a local isolation. Preserve table, bowl and vessel pixels; verify the resulting card with Roshan and adjacent room layers before binding.',[]),
24:(2.6,'The curtain atlas uses flat coral fills, simple cyan rings and a heavy dark-grey arch rather than the painted material bands seen in the stronger Kitchen art. Opening states retain purple speckle in the aperture, and their lower curtain/shell extent grows relative to rest.','Inventory the approved painted Opera references first. Preserve the entrance arch, star, shell badge and curtain identity; replace only failed flat/material or contact states with individually reviewed painted equivalents and stable support. Current runtime ownership and timeline acceptance remain open.',[
(3.1,'Closed panels have a clear entrance silhouette, but their flat coral fill and dark-grey arch miss the painted material language.'),(3.0,'Narrow opening is readable; the interior carries speckled purple residue and the arch width changes slightly.'),(2.9,'Curtains gather at the sides, but their transition resembles door panels becoming cloth with little painted depth.'),(2.8,'Open aperture and tassel positions are clear; dark trim and residual interior pixels remain prominent.'),(2.7,'Lower curtain and shell badge extend down relative to early states; flat material and support drift remain.'),(2.7,'Open hold varies the side edges while retaining the longer lower extent and purple speckle.'),(2.7,'Another open key changes curtain width and aperture contour without a settled consistent material.'),(2.7,'Final open state still has the extended lower contour; the source keys do not provide a clean closed settle.')]),
25:(3.2,'Chandelier spokes, cyan drops and gold bulbs form a recognizable fixture but read as flat geometric components. Heavy charcoal canopy lines and many small intersections compete with the softer painted prop family. Drop shapes and positions vary among chase keys.','Reuse the established chandelier silhouette and palette from approved painted references where possible. Repair the material/edge treatment and lock drop attachment points before validating its local light chase in game.',[
(3.3,'Rest is identifiable, with flat cyan drops and a dark geometric canopy; fine spokes are visually busy.'),(3.3,'Early bulb change retains the canopy, but side drops swing/change shape against fixed attachment geometry.'),(3.2,'More lamps brighten while the left drop shifts and the center lower drop changes outline.'),(3.2,'Warm outer lamps read clearly, but their bright flat shapes and charcoal canopy still miss painted depth.'),(3.2,'Light chase keeps the broad fixture, with varying droplet offsets under the lower rail.'),(3.2,'Another bright key retains small disconnected-looking drop attachments and dense spoke crossings.'),(3.2,'The brightest rail keeps a clear outline but lets tiny gold highlights dominate the cyan drops.'),(3.2,'Final key remains flat and geometrically busy; source light states do not establish mounted chase quality.')]),
26:(3.3,'The marquee star is child-readable and has a largely stable outline, but its solid gold fill, flat pastel buttons and charcoal plinth lack the broader painted bands of the accepted storybook prop family.','Keep the five-point star and bulb positions. Find a suitable approved painted star first; otherwise repair this named material gap without changing its identity or chase semantics.',[
(3.4,'Unlit star and pastel bulbs are clear; flat gold and dark plinth remain below the painted style bar.'),(3.4,'Top bulb lights within its socket and preserves the star geometry.'),(3.4,'Top and right bulbs brighten coherently, but the surrounding star remains a flat slab.'),(3.4,'Three lit bulbs remain countable with a stable star outline.'),(3.3,'Additional light emphasis does not repair the flat face and charcoal platform.'),(3.3,'Similar chase key keeps the gold face readable but needs restrained painted volume.'),(3.3,'All edge bulbs read clearly while their flat discs and dark base still diverge from the stronger art.'),(3.3,'Center bulb lights as payoff; source material and base treatment remain priorities.')]),
27:(2.6,'The footlight rail is flat gold/charcoal. Native rest contains six lamps with a partial rightmost lens; early keys contain five, and later keys return to six. Lids also change from a tall disc to shallow caps. These are authored shape/count problems, not proof of a sampling error.','Preserve one six-lamp rail design and fixed bulb/socket locations. Inspect approved painted fixtures for reuse, then redraw only failed states so a light chase changes illumination rather than lamp count or cap topology.',[
(3.0,'Rest has six pastel lenses, but the rightmost lens is visibly incomplete inside the native authored card.'),(2.7,'Early lit key contains five lamps and a tall raised first lid, changing the fixture topology.'),(2.8,'Second lit key still has five lamps and two shallow caps unlike the prior tall lid.'),(2.7,'Six-lamp layout returns with a partial left cap/lens; count and ownership remain discontinuous.'),(2.8,'Four bright sockets occupy a six-lamp rail, but the flat caps and plinth remain stylistically weak.'),(2.8,'Five sockets brighten with six lamps present; material and cap consistency remain unresolved.'),(2.8,'Six bright sockets appear under taller round lids; the lid form changes again.'),(2.8,'Final all-lit state preserves six lamps but cannot repair the earlier count and partial-lens states.')]),
28:(4.0,'The left pearl sconce has a suitable shell-and-lavender-base identity, but its visible native footprint is only 28 by 37 pixels in each 256-square cell. Peak glow loses shell rib detail and bleaches local edge remnants; magnification cannot supply missing source detail.','Reuse the approved shell design at an honest native size. Review mounted readability and retained rib/contour detail through the glow; if detail is insufficient, derive from a larger suitable approved master before generating a replacement.',[
(4.3,'Left rest shows warm shell ribs and a lavender bracket, with a small stepped pink remnant on its right edge.'),(4.1,'Warmer glow lightens rib detail while the bracket stays legible.'),(3.8,'Peak white glow nearly erases shell ribs and flattens the upper shell into a white mass.'),(4.0,'Slight ribbing returns but the pale shell contour and right-edge remnant still wash out.'),(4.0,'Second bright key remains strongly bleached with limited interior shell separation.'),(4.1,'Warm pale glow is more readable than the white peak, but tiny native ribs remain weak.'),(3.9,'Upper shell brightens close to white again, obscuring its painted material.'),(4.2,'Settle regains warm ribs; the tiny footprint and pale fringe still require contextual review.')]),
29:(4.0,'The separately inspected right sconce retains the matching shell identity and 28 by 37 visible native footprint. Its left-edge remnants brighten along with the shell, and peak white glow erases ribbing. It cannot inherit acceptance from the other side.','Retain the paired design and inspect this exact side independently in context. Prefer a larger approved shell source if required; preserve modest local glow and correct only proven foreign alpha pixels.',[
(4.3,'Right rest shows the shell ribs and lavender support, with stepped pink remnants along its left edge.'),(4.1,'Warm early glow lightens the ribs and left-edge remnants together.'),(3.8,'White peak removes most ribbing and turns the shell into a flat bright silhouette.'),(4.0,'Pale ribs partly return; washed contour and bright left-edge remnants remain.'),(4.0,'Another bright key still flattens the small shell face.'),(4.1,'Warmer near-white light retains slightly more shell detail than the peak.'),(3.9,'Bright upper shell again loses its painted rib separation.'),(4.2,'Warm settle restores some ribs but the small native footprint and edge remnants remain priorities.')]),
30:(3.9,'The Opera left foreground has readable rounded aqua seats, lavender cushions and a sweeping shell balcony. Broad flat fills and thin light contours give less painted depth than the Kitchen cluster; pale shell lamps compete with seating.','Keep the shell balcony and seating layout. Compare the full rendered room before choosing a local painted-material repair; do not invent a new venue or replace the entire scene.',[]),
31:(3.9,'The independently inspected right foreground mirrors the shell balcony/seating family. Its aqua seat backs and lavender panels are clear but mostly flat, and the large bright shell is a competing focal point.','Preserve the paired staging and original art. Verify current scale, Roshan occlusion and figure/ground separation; refine only the demonstrated material or hierarchy gap.',[]),
140:(4.6,'The Kitchen pictogram has a rounded mint cooking pot, a warm scalloped badge and a restrained plum rim. It provides a recognizable non-reading kitchen cue with painted highlights and a compact clear silhouette.','Reuse the exact source. Verify only the mounted size/contrast and correct-room pointer; no source regeneration is justified by this review.',[])
}
opinions=[];sources=[]
for x in plan['source_files']:
    n=int(x['id'].split('-')[-1]);score,ev,ref,cells=data[n]
    assert sha(b/x['path'])==x['sha256'] and len(cells)==len(x['cells'])
    source=copy.deepcopy(x);source.update(source_review_status='DIRECTLY_REVIEWED_NATIVE_SOURCE',source_score=score,evaluation=ev,refinement=ref,owner_acceptance=None,source_pixels_modified=False)
    base=dict(id=x['id'],path=x['path'],sha256=x['sha256'],kind='source',score=score,evaluation=ev,refinement=ref,direct_native_review=True,current_mounted_score=None,current_complete_action_score=None,owner_acceptance=None)
    opinions.append(base)
    for c,(s,t) in zip(source['cells'],cells):
        ident=f'{x["id"]}-CELL-{c["index"]:02d}'
        c.update(id=ident,status='DIRECTLY_REVIEWED_AUTHORED_CELL',score=s,evaluation=t,refinement=ref)
        opinions.append(dict(id=ident,parent_source_id=x['id'],path=x['path'],sha256=x['sha256'],kind='source object region',region=c['region'],score=s,evaluation=t,refinement=ref,direct_native_review=True,current_mounted_score=None,current_complete_action_score=None,owner_acceptance=None))
    sources.append(source)
assert len(opinions)==122 and len(sources)==18
sources_weak=sum(x['source_score']<=4.5 for x in sources);cells_weak=sum(c['score']<=4.5 for x in sources for c in x['cells']);assert sources_weak==17 and cells_weak==99
qa=[]
for name in ['SharedFootlightCellsV533.png','SharedSconceLeftCellsV533.png','SharedSconceRightCellsV533.png']:
    shutil.copyfile(Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp')/name,q/name)
    qa.append(dict(path=(q/name).relative_to(b).as_posix(),sha256=sha(q/name),scope='Temporary browser CSS windows of unchanged native source; source-only inspection, not game capture.'))
review=dict(schema='reef.individual-native-prop-review.v1',status='ALL18_NATIVE_SOURCES_AND104_AUTHORED_CELLS_DIRECTLY_REVIEWED',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseline=plan['baseline'],source_count=18,authored_cell_count=104,individual_opinion_count=122,inclusive_source_priorities=sources_weak,inclusive_cell_priorities=cells_weak,source_files=sources,opinions=opinions,inspection_screenshots=qa,authority_rechecked=['audit/MASTER_AUDIT_2026-08-09.md#0-planning-entry','audit/MASTER_AUDIT_2026-08-09.md#development-task-index','design/06_COMPREHENSIVE_DESIGN_LANGUAGE.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','CASTLE_INTERACTION_AUDIT_2026-08-01.md','FABLE_CASTLE_ITEM_STYLE_AUDIT_2026-07-28.md'],historical_qualification='July source-item scores and earlier V2/V4 review evidence retain their original paths, pixels and scope. These are fresh drafting opinions of the exact current atlases/foreground/signs; they do not erase prior acceptance or claim current mounted failure. Two older ownership hashes are stale; current V2/V4 manifests match all 13 atlases exactly.',source_pixels_modified=False,production_changes=[],owner_acceptance=None,acceptance_gaps='No new current room capture, complete action/input/audio/lifecycle timeline, ordinary route, target-device, child, owner or game-wide true2D acceptance. All weak items remain priorities, not replacement authorization for unaffected approved art. The separate Candy current source repair and full suite are distinct evidence; no finding lifecycle change.')
write(q/'DIRECT_NATIVE_REVIEW.json',review)

out=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kitchen and Opera entrance art — individual review</title><style>body{margin:0;background:#eaf3f7;color:#26354e;font:17px/1.5 system-ui}main{max-width:1250px;margin:auto;padding:24px}header,article{background:white;border-radius:18px;padding:22px;margin:20px 0}h1,h2,h3{line-height:1.25}a{color:#51478c}code{overflow-wrap:anywhere;font-size:13px}.sheet{display:block;max-width:100%;max-height:900px;object-fit:contain;background:#c4d3df}.cells{display:flex;flex-wrap:wrap;gap:16px}.cell{width:252px;flex:1 0 252px;max-width:300px;background:#edf4f8;border-radius:12px;padding:14px}.detail{position:relative;overflow:hidden;background:#c3d3de;margin:8px 0}.detail img{position:absolute;max-width:none}small{font-size:13px}.priority{color:#954d2c}.reuse{color:#276156}nav{display:flex;flex-wrap:wrap;gap:14px}strong{font-weight:750}</style><main><header><nav><a href="../job_artwork_refinement_live/all_items.html">Full individual library</a><a href="../job_candy_workflow_current_v1_20261003/index.html">Current Candy action review</a><a href="DIRECT_NATIVE_REVIEW.json">All 122 written opinions</a><a href="PLAN_AND_SOURCE_BOUNDARY.json">Exact source boundary</a></nav><h1>Kitchen and Opera entrance artwork</h1><p><strong>18 existing originals and all 104 authored cells directly reviewed.</strong> Seventeen whole sources and 99 cells score 4.5/5 or lower and remain refinement priorities. The Kitchen sign and five individual fridge states score 4.6 as source opinions.</p><p>The Opera curtain, chandelier, marquee star and footlight materials are flat beside the painted Kitchen props. Footlight bulb count changes; several copper-pan states bend metal or change the bowl; small sconce glow peaks erase shell detail. Existing fridge/sign art offers stronger reusable material language.</p><p>Scores are first-pass drafting judgments of these exact native sources. Original pixels and previous reviews are preserved. No new source generation or game binding was made. Current room composition, hand contact, authored timeline, device, child and owner acceptance remain separate.</p><p>Two old ownership hashes differ; the current V2/V4 manifests independently match every atlas. The failed preparation and correction are retained in <a href="PREPARATION_FAILURE_V530.json">the provenance note</a>. Historical July item scores describe their original evidence and do not pass the current animation cells automatically.</p></header>']
for x in sources:
    src='/'+x['path'];label=Path(x['path']).stem.replace('_',' ')
    out.append(f'<article id="{x["id"]}"><h2>{x["id"]} · {html.escape(label)} · {x["source_score"]}/5</h2><p>{html.escape(x["evaluation"])}</p><p><strong>Refine:</strong> {html.escape(x["refinement"])}</p><p><a href="{src}">Complete original {x["dimensions"][0]} × {x["dimensions"][1]}</a> · <code>{x["sha256"]}</code></p><img class="sheet" src="{src}" alt="Complete existing native {html.escape(label)}">')
    contract=x['current_source_contract']
    if contract:
        timeline=contract['binding'].get('timeline_sequence');out.append(f'<p>Current source contract: <a href="/{contract["path"]}">{html.escape(Path(contract["path"]).name)}</a>; exact native hash matches. Authored grid {contract["binding"]["grid"]}; recorded timeline {html.escape(str(timeline))}. Current in-game playback was not recaptured in this source review.</p><h3>Each authored cell</h3><p>Details below are read-only CSS windows into the original sheet; magnification adds no source resolution.</p><div class="cells">')
    for c in x['cells']:
        rx,ry,rw,rh=c['region'];bx,by,ex,ey=c['alpha_bbox'];bx=max(0,bx-8);by=max(0,by-8);ex=min(rw,ex+8);ey=min(rh,ey+8)
        scale=min(232/(ex-bx),232/(ey-by));ww=(ex-bx)*scale;hh=(ey-by)*scale
        out.append(f'<section class="cell" id="{c["id"]}"><h3>Cell {c["index"]} · {c["score"]}/5</h3><div class="detail" style="width:{ww:.4f}px;height:{hh:.4f}px"><img src="{src}" alt="Exact native authored {html.escape(label)} cell {c["index"]}" style="width:{x["dimensions"][0]*scale:.4f}px;height:{x["dimensions"][1]*scale:.4f}px;left:{-(rx+bx)*scale:.4f}px;top:{-(ry+by)*scale:.4f}px"></div><p>{html.escape(c["evaluation"])}</p><small>Region {c["region"]}<br>Original alpha bounds {c["alpha_bbox"]}<br>Source state only; mounted/contact/action unreviewed.</small></section>')
    if contract:out.append('</div>')
    out.append('</article>')
out.append('<footer><p>Keep source quality, exact bytes, machine checks and complete runtime/owner acceptance separate. Global job review remains incomplete. <a href="../job_artwork_refinement_live/index.html">Return to the live audit entry</a>.</p></footer></main></html>')
(q/'index.html').write_text('\n'.join(out),encoding='utf-8',newline='\n')
shutil.copyfile(__file__,q/'review_tools/review_shared_entry_sources_v534.py')

for name,backup in [('ALL_ITEMS.json','ALL_ITEMS_V44.original.json'),('all_items.html','all_items_V44.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V44.original.json')]:
    assert not (l/backup).exists();shutil.copyfile(l/name,l/backup)
reg=json.loads((l/'ALL_ITEMS.json').read_text(encoding='utf-8'));assert len(reg['items'])==1934
tmpl=next(x for x in reg['items'] if x['id']=='CANDY-M-A10-STATE-1')
for x in sources:
    it=next(it for it in reg['items'] if it['id']==x['id']);assert it['current_source_score'] is None
    it['earlier_written_evaluation']=it['evaluation']
    it.update(current_source_score=x['source_score'],evaluation=x['evaluation'],refinement=x['refinement'],source_qualification='Fresh exact-native source review only. Each authored cell independently inspected. Prior contextual/source evidence is preserved; no current mounted action, device, child, owner or true2D acceptance.',priority=x['source_score']<=4.5,image_path=x['path'],image_scope='Unmodified whole native source; source opinion only',families=sorted(set(it['families'])|{'Shared Kitchen and Opera entrances'}),latest_refinement=dict(report=q.relative_to(b).as_posix()+'/index.html#'+x['id'],note=x['evaluation']),individual_review_utc=review['reviewed_utc'])
    it['original_reports'].append(q.relative_to(b).as_posix()+'/index.html#'+x['id'])
    for c in x['cells']:
        z=copy.deepcopy(tmpl);z.update(id=c['id'],kind='source object region',label=Path(x['path']).stem.replace('_',' ')+f' authored cell {c["index"]}',path=x['path'],parent_source_id=x['id'],region=c['region'],earlier_sha256=x['sha256'],current_checkout_sha256=x['sha256'],historical_source_score=None,current_source_score=c['score'],source_dimensions=x['dimensions'],preview_path=x['path'],image_path=x['path'],image_scope='Exact authored cell CSS window from unchanged native atlas; source state only',source_qualification='Existing prop cell individually inspected on full native sheet; source-only score, no mounted sampling/contact/complete action or owner acceptance.',evaluation=c['evaluation'],refinement=c['refinement'],priority=c['score']<=4.5,families=['Shared Kitchen and Opera entrances','Authored prop states'],original_reports=[q.relative_to(b).as_posix()+'/index.html#'+c['id']],latest_refinement=dict(report=q.relative_to(b).as_posix()+'/index.html#'+c['id'],note=c['evaluation']),individual_scope='Existing authored source prop state, independently reviewed; no actual runtime capture.',individual_review_utc=review['reviewed_utc'])
        reg['items'].append(z)
assert len(reg['items'])==2038 and len({x['id'] for x in reg['items']})==2038
reg['counts'].update(registered_items=2038,individual_source_object_regions=282,inclusive_current_source_priorities=888,unique_source_file_priorities=602,unreviewed_current_source=359,new_shared_entrance_source_opinions=18,new_shared_authored_prop_regions=104)
assert sum(x['current_source_score'] is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3'] for x in reg['items'])==888
reg.update(display_revision='V45',updated_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v45.py',scope='V45 directly reviews 18 existing shared Kitchen/Opera entrance natives and all104 authored prop cells. Known register2038 entries/1277 unique sources/328 pose cells/151 runtime-use entries/282 source object regions. Inclusive source-cell-region priorities888, unique source priorities602, current Candy use priorities48 and359 pending source reviews. All10 contact sources and52 Candy source states retained; whole unbound wrapping4.1 remains rejected. Exact Candy783-source boundary matches; older mounted Geologist/Nursery claims remain withheld after the shared-world delta. No production change from this source review, finding lifecycle closure, game-wide acceptance or owner approval.')
reg['review_resources'].append(dict(path=q.relative_to(b).as_posix()+'/index.html',scope='All18 existing shared entrance natives and104 individual authored cells directly reviewed;17 source/99 cell inclusive priorities, exact original pixels preserved.'))
write(l/'ALL_ITEMS.json',reg,compact=True);assert (l/'ALL_ITEMS.json').stat().st_size<4194304
shutil.copyfile(l/'review_tools/refresh_current_job_review_v44.py',l/'review_tools/refresh_current_job_review_v45.py')
for p in [l/'index.html',l/'all_items.html']:
    t=p.read_text(encoding='utf-8').replace('refresh_current_job_review_v44.py','refresh_current_job_review_v45.py')
    t=t.replace('<h1>', '<p><a href="../job_shared_entrance_sources_v1_20261003/index.html">New: 18 shared Kitchen/Opera sources and all104 authored prop cells</a> · 17 source/99 cell refinement priorities; original pixels preserved.</p><h1>',1)
    p.write_text(t,encoding='utf-8',newline='\n')
summary='Shared Kitchen/Opera entrance continuation (2026-10-03): [all18 existing native sources and104 authored prop cells](job_shared_entrance_sources_v1_20261003/index.html) directly inspected;122 written opinions,17 whole-source/99 cell inclusive priorities. Opera flat-material sources2.6–3.3, copper swing topology4.2–4.3, sconce detail/glow4.0 and Kitchen foreground remnant4.1 remain priorities. Fridge whole4.5 and Kitchen sign4.6 supply stronger reuse; no source pixel or production changes. Current V2/V4 manifests match all13 atlases; two older ownership hashes preserved as stale history. V45 known register2038 entries/888 source-cell-region priorities/602 unique source priorities/359 pending source reviews. Candy current48 priorities/783-source boundary unchanged; earlier Geologist/Nursery mounted claims remain withheld. Source opinions do not establish current room/action/device/child/owner/all-job acceptance; no finding lifecycle or integration/release change.'
master=b/'audit/MASTER_AUDIT_2026-08-09.md';t=master.read_text(encoding='utf-8');assert '## 0. Planning entry\n' in t;t=t.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+summary+'\n',1);master.write_text(t,encoding='utf-8',newline='\n')
active=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';t=active.read_text(encoding='utf-8');line,rest=t.split('\n',1);active.write_text(line+'\n\n'+summary.replace('(job_shared_entrance_sources','(../job_shared_entrance_sources')+'\n'+rest,encoding='utf-8',newline='\n')
ledger=b/'design/05_DOC_LEDGER.md';t=ledger.read_text(encoding='utf-8');t+='\n| `audit/job_shared_entrance_sources_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`;18 existing native sources/104 authored prop cells individually inspected,122 drafting opinions.17 source/99 cell priorities; no source pixel or runtime change, no current mounted/action/owner acceptance. |\n| `audit/job_shared_entrance_sources_v1_20261003/DIRECT_NATIVE_REVIEW.json` | 🟢 | `SUPPORTING_CURRENT`; exact hashes/regions/current manifests, individual grades and reuse/refinement guidance. Two historical ownership hash mismatches retained; they do not authorize current ownership acceptance. |\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V44.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact1934-entry register before18 newly assigned source opinions and104 authored prop cell entries. |\n';ledger.write_text(t,encoding='utf-8',newline='\n')
attrs=b/'.gitattributes';t=attrs.read_text(encoding='utf-8');t+='\naudit/job_shared_entrance_sources_v1_20261003/** -text\n'
for name in ['ALL_ITEMS_V44.original.json','all_items_V44.original.html','BOUNDARY_V44.original.json']:t+=f'audit/job_artwork_refinement_live/{name} -text\n'
attrs.write_text(t,encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-shared-entrance-source-review-20261003.json';impact=json.loads(ip.read_text(encoding='utf-8'))
impact['files']=sorted(set(impact['files'])|{p.relative_to(b).as_posix() for p in q.rglob('*') if p.is_file()}|{p.relative_to(b).as_posix() for p in [l/'ALL_ITEMS.json',l/'all_items.html',l/'index.html',l/'CURRENT_BOUNDARY_REFRESH.json',l/'ALL_ITEMS_V44.original.json',l/'all_items_V44.original.html',l/'BOUNDARY_V44.original.json',l/'review_tools/refresh_current_job_review_v45.py',master,active,ledger,attrs]})
impact['validation']=[dict(command='Direct native-sheet inspection18/18 plus individually reviewed104 authored cells; enlarged native-source CSS details for16 sconce states and8 footlight states',result='PASS',evidence='audit/job_shared_entrance_sources_v1_20261003/DIRECT_NATIVE_REVIEW.json; all122 opinions, exact hashes/regions and three native-source inspection screenshots. Source-only drafting review, not game capture.'),dict(command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v45.py',result='PENDING',evidence='CURRENT_BOUNDARY_REFRESH.json; all2038 registered item hashes and separate Candy783-source boundary must be rechecked'),dict(command='Current document authority and development coverage gates after source-review additions',result='PENDING',evidence='No inherited pass from earlier report revision.')]
impact['acceptance_gaps']=review['acceptance_gaps'];write(ip,impact)
refresh=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(l/'review_tools/refresh_current_job_review_v45.py')],cwd=b,text=True,capture_output=True);print(refresh.stdout);assert refresh.returncode==0,refresh.stderr
stamp=json.loads((l/'CURRENT_BOUNDARY_REFRESH.json').read_text(encoding='utf-8'));assert stamp['registered_source_matches']==2038 and stamp['candy_capture_boundary_match']
impact['validation'][1]['result']='PASS';impact['validation'][1]['evidence']='audit/job_artwork_refinement_live/CURRENT_BOUNDARY_REFRESH.json:2038/2038 exact item source hashes match; Candy783 current source boundary matches. Older Geologist/Nursery source-bound mounted claims remain withheld.';write(ip,impact)
ap=b/'tmp/v2_preview_allowed.json';write(ap,sorted(set(json.loads(ap.read_text()))|set(impact['files'])|{x['path'] for x in sources}|{x['current_source_contract']['path'] for x in sources if x['current_source_contract']}))
print(json.dumps(dict(status='V45_SOURCE_REVIEW_COMPLETE',items=2038,source_priorities=888,unique_source_priorities=602,unreviewed_sources=359,native_files=18,authored_cells=104,written_opinions=122,registry_bytes=(l/'ALL_ITEMS.json').stat().st_size,production_delta_from_this_review=False)))
