from pathlib import Path
import hashlib,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');out=b/'audit/job_geode_runtime_v1_20261001'
p=out/'REMAINING_PRIORITIES.json';d=json.loads(p.read_text());q={'id':'GEO-PRIORITY-OPENING-SEQUENCE','item':'Geode opening transitions','score':4.5,'score_scope':'Selected static/base progression only; complete timed action unassigned','capture':'attempt_03/native_views/geologist_1280_geode_middle_open.webp','capture_sha256':hashlib.sha256((out/'attempt_03/native_views/geologist_1280_geode_middle_open.webp').read_bytes()).hexdigest(),'source':None,'reason':'The sampled closed/crack/oblique/full states preserve rooted crystals and the common base, but selected still images do not establish every intervening frame or complete child-driven timing. The4.5 provisional minimum remains an inclusive refinement priority.','required':'Review the complete ordinary timed opening, especially state changes near40/90 logical pull and release/re-entry. Refine only an actually weak intermediate state or interaction; preserve the passing source states and never substitute loose crystals.','current_binding':'Actual production topic candidate captures; source4.6 and sampled progression4.5 are separate.'}
assert not any(x['id']==q['id'] for x in d['priorities']);d['priorities'].append(q);p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
p=out/'index.html';s=p.read_text(encoding='utf-8');marker='<h2>Preserved earlier attempts</h2>';assert marker in s
section='<article id="opening-transition-priority"><h2>Geode opening remains a sequence priority</h2><p>Sampled static/base progression:4.5/5, provisional. Individual painted states and rooted-crystal ownership:4.6/5. Complete timed action remains unassigned.</p><img loading="lazy" src="'+q['capture']+'" alt="Actual oblique geode opening state"><p>'+q['reason']+'</p><p><strong>Required evidence:</strong> '+q['required']+'</p></article>'
p.write_text(s.replace(marker,section+marker,1),encoding='utf-8',newline='\n');dest=out/'review_tools/retain_geode_transition_priority_v171.py';shutil.copyfile(__file__,dest)
ip=b/'design/audit_impacts/job-geode-painted-runtime-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in out.rglob('*') if p.is_file()});ip.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
print('Provisional4.5 geode progression retained as a distinct inclusive sequence priority.')
