from pathlib import Path
import datetime,hashlib,html,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');out=b/'audit/job_geode_runtime_v1_20261001'
src='assets_src/imagegen/geologist_painted_rebuild_v1_20261001/'
rows=[
 {'id':'GEO-PRIORITY-ROOM','item':'Actual geology room','score':2.8,'capture':'attempt_03/native_views/geologist_1280_geode_invitation.webp','source':None,'reason':'Dark flat bands and generic cave mural remain in the actual room. Existing grotto drafts do not meet native2048×2048 per-screen coverage; a visually attractive undersize image cannot establish runtime readiness.','required':'Inventory reusable approved native masters; preserve the approved composition, meet native coverage and tile seams, and inspect all four ordinary invitations/work contexts.'},
 {'id':'GEO-PRIORITY-INVITATIONS','item':'Four actual work invitations','score_range':[2.9,3.4],'capture':'attempt_03/native_views/geologist_1280_pan_invitation.webp','source':None,'reason':'PAN currently invites with a layered rock, FOSSIL with a minimal table, RIVER with an abstract halo, and GEODE with flat mural crystals. These are individually recorded in REVIEW.json, not approved by the new geode source.','required':'Show the actual task object and a stable support/arrival mark; preserve intentional touch and spoken/pointer instruction.'},
 {'id':'GEO-PRIORITY-WORK-FIELD','item':'Current ochre work panel','score':4.0,'capture':'attempt_03/native_views/geologist_1280_geode_earned_completion.webp','source':src+'work_surface/attempt_04/whole_canvas_1024.png','candidate_source_score':4.6,'reason':'The current large uniform rounded panel has little painted stone material. The separately reviewed stone slab is available but is not bound here; it must retain its native aspect and support every actual brush/piece/pan/geode state.','required':'Reuse the preserved painted slab without stretching it or allowing objects, homes, cues or gestures to float beyond its support.'},
 {'id':'GEO-PRIORITY-FOSSIL','item':'Active fossil and three assembly pieces','score':3.8,'assembly_score':3.9,'capture':'attempt_03/native_views/geologist_1280_fossil_brushed.webp','source':src+'fossil/attempt_02/whole_canvas_1024.png','candidate_source_score':4.6,'reason':'The live fossil and its conserved thirds remain flat SVG pixels. A complete painted fossil source is ready for a binding review; its more compact source ratio cannot be stretched into the old wide frame. The three pieces must reconstruct that same raster image.','required':'Preserve source proportions and one consistent source region across full fossil, faint target, three pieces and invitation. Check actual brushing, dragging, snapping and saved re-entry at both widths.'},
 {'id':'GEO-PRIORITY-FOSSIL-COVER','item':'Fossil dirt cover','score':3.2,'capture':'attempt_03/native_views/geologist_1280_fossil_task_open.webp','source':None,'reason':'The entire fossil is hidden by a uniform brown rectangle. Its flat cover is a distinct material problem; the unseen fossil gets no visible grade at this state.','required':'Find a reusable painted soil material or generate only this missing material. Preserve actual brush clearing and transparent-reveal continuity.'},
 {'id':'GEO-PRIORITY-PAN','item':'Live pan, grains and recovered minerals','score':4.0,'grain_score':3.8,'mineral_score':3.4,'capture':'attempt_03/native_views/geologist_1280_pan_partial_pan.webp','source':src+'washing_pan/attempt_02/whole_canvas_1024.png','candidate_source_score':4.6,'reason':'The live pan still consists of procedural ellipses; grains are discs and recovered minerals are flat polygons. Painted pan/grain/mineral sources were separately reviewed. The new geode reveal does not replace these objects.','required':'Bind intact painted sources at their own runtime paths, maintain pan/water geometry, and audit washing progression and mineral waterline at every earned stage.'},
 {'id':'GEO-PRIORITY-RIVER','item':'Live excavated river','score':3.8,'capture':'attempt_03/native_views/geologist_1280_river_earned_completion.webp','source':None,'reason':'Connected aqua rectangles and repeated circular nodes read like a diagram. They correctly track the intentional excavation, but lack the current painted terrain/water material language.','required':'Keep the existing connected-path behavior while replacing the material presentation and depicting digging at the actual point of contact.'},
 {'id':'GEO-PRIORITY-CONTACT','item':'Roshan working away from all four objects','score':2.7,'capture':'attempt_03/native_views/geologist_1280_geode_middle_open.webp','source':src+'panning_contact/attempt_01/whole_canvas_1024.png','candidate_source_score':4.6,'reason':'The current work animation crawls on the floor away from the active material. A connected static pan grip was reviewed separately; all three local video references remain below the full-action floor. A static grip image cannot establish travel, pickup, alternating rocking, release or return.','required':'Bind an appropriate working pose and prove meaningful hand/tool/object contact throughout each real action; inspect complete timed routes rather than grading selected poses as motion.'}]
for q in rows:
 q['capture_sha256']=hashlib.sha256((out/q['capture']).read_bytes()).hexdigest();q['current_binding']='Actual production topic candidate capture'
 if q['source']:
  p=b/q['source'];q['candidate_sha256']=hashlib.sha256(p.read_bytes()).hexdigest();q['candidate_dimensions']=list(Image.open(p).size);q['candidate_binding']='UNBOUND_SOURCE_ONLY'
q=out/'REMAINING_PRIORITIES.json';q.write_text(json.dumps({'status':'OPEN_INDIVIDUAL_GEOGRAPHICS_PRIORITIES','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'priorities':rows,'qualification':'Current native image review and reused source inventory. Not an implementation completion, score average, generation acceptance or final all-job report.'},indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
cards=[]
for q in rows:
 score=str(q.get('score',q.get('score_range')))+'/5'
 candidate=('<p>Previously reviewed candidate source:'+str(q['candidate_source_score'])+'/5, still unbound.</p><img loading="lazy" src="../../'+q['source']+'" alt="Previously reviewed unbound source for '+html.escape(q['item'])+'">') if q['source'] else ''
 cards.append('<article><h3>'+html.escape(q['item'])+'</h3><p>Current material/contact score:'+score+'</p><img loading="lazy" src="'+q['capture']+'" alt="Actual current scene: '+html.escape(q['item'])+'"><p>'+html.escape(q['reason'])+'</p>'+candidate+'<p><strong>Required evidence:</strong> '+html.escape(q['required'])+'</p></article>')
p=out/'index.html';s=p.read_text(encoding='utf-8');marker='<h2>Preserved earlier attempts</h2>';assert marker in s and 'id="remaining-priorities"' not in s
s=s.replace(marker,'<section id="remaining-priorities"><h2>Remaining individual review priorities</h2><p>Current below-floor artwork and interaction problems remain separate from the four passing geode source states. Candidate thumbnails show preserved previously reviewed sources; they do not imply a runtime replacement. <a href="REMAINING_PRIORITIES.json">Exact priority and source data</a>.</p><div class="grid">'+''.join(cards)+'</div></section>'+marker,1)
p.write_text(s,encoding='utf-8',newline='\n');dest=out/'review_tools/show_geology_remaining_priorities_v168.py';shutil.copyfile(__file__,dest)
ip=b/'design/audit_impacts/job-geode-painted-runtime-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in out.rglob('*') if p.is_file()});ip.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
print('Eight illustrated priority groups now distinguish current live weaknesses and preserved unbound replacement sources.')
