from pathlib import Path
import datetime,hashlib,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';f.mkdir(exist_ok=False);(f/'attempt_01').mkdir();(f/'review_tools').mkdir()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
refs=['assets/opera/worlds/geology/painted_geode_v1_20261001/closed.png','assets/opera/worlds/geology/painted_geode_v1_20261001/open_embedded.png']
prompt='''Use case: illustration-story. Asset: transparent 2D gameplay geode opening state atlas, eight carefully matched paintings in a precise4-column2-row grid, wide2:1 canvas. Image1 is the established CLOSED identity. Image2 is the established OPEN identity and rooted interior: three attached crystals in each concave cavity. Preserve these lavender stone shells, cream rims, aqua/lavender crystals and matte storybook brushwork. Generate the SAME geode eight times in consecutive opening states, left-to-right top row then bottom row. States: fully closed; hairline separation; slight10% reveal;20% reveal;35% reveal;50% reveal;70% reveal; fully opened. It splits into TWO coherent matching halves. The halves separate and gradually turn outward to reveal the crystals growing from inside. Crystals do not appear on the outside, detach, fall or become loot. Keep the SAME outer shell anatomy, exact crystal count/size/positions relative to their own cavities across all revealed states. Early crystals are correctly OCCLUDED by their shells, progressively uncovered. Keep fixed shell scale and base height across all eight cells: each cell has identical square dimensions, identical front camera, same geode center and the same grounded baseline near80% of the cell height. Both halves stay fully inside the cell with generous transparent gutters; no cropping or overlaps. The full-open state can be wider only because the two unchanged-size halves separate, never because the stone suddenly expands. No lighting, contour or crystal topology jumps between states. A polished painted children's storybook prop, rounded broad lavender/aqua shadows, subtle handmade irregularity, fine dark-plum contours, cream interior rim, broad quiet painted bands. No vector-flat diagram, photorealism, 3D, photographic mineral noise, white sticker halo, glow, labels, letters, numbers, grid lines, arrows, hands, tools, loose rewards, scenic background or floor. Actual transparent alpha everywhere outside the eight objects. Each state is one complete newly painted object image, not a blend of the supplied pixels.'''
(f/'attempt_01/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'PLAN.json',dict(created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),status='GENERATION_PENDING_UNBOUND',gap='Complete timed actual production opening4.2 has large source-state width jumps atpull40/90 and top drop atfull. Existing four individually good paintings cannot provide coherent intervening geometry. Named targeted gap only; preserve original geode family and rooted crystals.',references=[dict(path=p,sha256=sha(b/p),role='closed identity' if i==0 else 'open embedded material and crystal identity') for i,p in enumerate(refs)],inventory=['assets/opera/worlds/geology/painted_geode_v1_20261001/','assets_src/imagegen/geologist_painted_rebuild_v1_20261001/opening_geode/','audit/job_geology_river_runtime_v1_20261002/TIMED_REVIEW.json'],prompt_sha256=sha(f/'attempt_01/PROMPT.txt'),generation_method='built-in image_gen',acceptance='Each cell, transparency, coherent pair silhouette/base and all actual opening frames must be reviewed. Unbound native source does not establish contact/route/device/child/owner/global acceptance.'))
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
write(b/'design/audit_impacts/job-geode-coherent-opening-20261002.json',dict(id='job-geode-coherent-opening-20261002',scope='Targeted reversible geode opening-state source candidate for measured timed silhouette/scale discontinuities; existing crystals remain rooted inside. Source inventory and original exact hashes retained, current production source frozen while prior river fullCI runs.',baseline='40b1c7bfe025f284507c586fea61b9dd76b61423',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-MED-01','DL-INT-01','DL-INT-02','DL-INT-03','DL-INT-04','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-QA-03','DL-QA-06'],findings=['MA-PLAY-004','MA-VIS-006'],files=sorted(p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()),validation=[dict(command='Existing geode inventory and every312 timed frame review',result='PASS',evidence='audit/job_geology_river_runtime_v1_20261002/TIMED_REVIEW.json; measured opening4.2, material/embedded semantics4.6, no creative/full-action pass.'),dict(command='Generate and individually audit eight coherent authored state paintings',result='PENDING',evidence=f.relative_to(b).as_posix()+'/PLAN.json')],acceptance_gaps='Generated native source and each state, alpha, mounted progression, complete ordinary action/exit/training/story/device/child/owner all remain pending. Working hand contact2.7 is a distinct unaddressed gap; no finding closure or release.'))
print('Prepared targeted coherent-geode gap, exact two references and built-in prompt; production unchanged.')
