from pathlib import Path
import hashlib,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix();a=f/'attempt_09';a.mkdir(exist_ok=False)
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
prompt='''Paint TWO new intermediate opening states of the SAME lavender geode shown in the supplied six-state sheet. Wide2:1 transparent canvas, two equal square cells side by side, one complete geode in each, clean empty transparent gutters. Preserve EXACT established2D gouache material, lavender outer shell with aqua low shadow band, plum contour, cream rim and THREE rooted crystals in EACH purple concave cavity. Use the TOP RIGHT quarter-open painting and BOTTOM LEFT half-open painting as the endpoints: the new left painting is about one-third open; the new right painting is about five-twelfths open. They must lie visually between those endpoints with gently growing opening, never skip to fully open. Same two shell anatomy, same3+3 crystal sizes and locations, same fixed front camera and grounded base. Crystals are still partly obscured by their shells, progressively revealed. Keep stone size/height identical between the two new paintings; pair silhouette WIDTH approximately1.34 times its HEIGHT in the left cell and1.41 times its HEIGHT in the right cell. Maximum object width70% of each cell, plenty of clean transparent space all round, no clipping. The two concave interiors remain distinctly owned by their own shells; no common basin, exterior gems, loose loot or falling crystals. Broad matte pastel storybook brushwork and clean plum outlines, no new design. Clean transparent alpha outside every contour, no pink/blue fringes, glow, shadow patch, floor, scene, extra states, labels, letters or numbers. Actual2:1 transparent atlas of TWO coherent bridge states, not a copy of the six-state sheet.'''
(a/'PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(a/'PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=9,references=[dict(path=prefix+'/attempt_08/native.png',sha256=sha(f/'attempt_08/native.png'),role='two endpoint identities/style and fixed3+3 cavities')],prompt_sha256=sha(a/'PROMPT.txt'),gap='Read-only source silhouette aspects: quarter1.2576 tohalf1.4925 is a77px width step at330px fixed height. Two individually generated bridges targeting1.34/1.41 fill this named gap; no source interpolation/pixel synthesis. Other consecutive source steps are3–16px atthat height.'))
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['scope']+=' Add two authored intermediate bridge states for the measured quarter/half77px silhouette gap; ordinary gameplay atlas selection/mounting is allowed2D state art, no cinematic interpolation.';d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});write(ip,d)
print('Two targeted quarter/half bridge paintings prepared; read-only77px gap recorded, other source steps3–16px.')
