from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_01';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-6888f06b-8783-49f7-a672-e872dcbc7b38.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;rgba=im.convert('RGBA');cells=[]
for n in range(8):
 col=n%4;row=n//4;rect=(round(col*w/4),round(row*h/2),round((col+1)*w/4),round((row+1)*h/2)); region=rgba.crop(rect);bbox=region.getchannel('A').getbbox()
 score=3.8 if n==7 else 4.0
 cells.append(dict(id='GEO-COHERENT-A1-STATE-'+str(n),state_index=n,source_rect=list(rect),alpha_bbox_local=bbox,score=score,material_score=4.6,direct_review=True,evaluation='Painted lavender/cream material is coherent with the established stone, but pink/blue fringe and floating coloured alpha speckles contaminate the gutters. '+('Fully opened pair reaches the outer right boundary and is clipped; fails containment.' if n==7 else 'Intervening crystal anatomy/relative size changes between cells; source sequence not accepted.'),priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='REJECTED_SOURCE_SEQUENCE',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_01/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=3.8,cells=cells,qualification='Direct native whole-sheet inspection, eight individual cell opinions. Read-only alpha bounds; no pixel cleanup, normalization or runtime binding. Gutter artefacts, last-cell clipping and crystal topology drift prevent acceptance.'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=1,prompt_path=prefix+'/attempt_01/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=True,references=json.loads((f/'PLAN.json').read_text(encoding='utf-8'))['references'],acceptance='REJECTED_SOURCE_SEQUENCE'))
(f/'attempt_02').mkdir()
prompt='''Use case: illustration-story. Make one original polished painted children's storybook 2D gameplay state atlas on a WIDE2:1 transparent canvas, EXACTLY4 columns by2 rows, eight identical-size square cells. The atlas shows the SAME lavender geode opening in eight stages in row-major order. Rounded broad pastel lavender stone, a quiet aqua shadow band across the lower outer shell, thin clean plum contour, creamy warm ivory mineral rim and soft purple concave cavity. Inside each half, exactly THREE permanently attached chunky crystals: left cavity one tall aqua crystal, one medium lavender crystal behind/right and one short aqua crystal in front; right cavity one tall lavender crystal, one medium aqua crystal behind/left and one short aqua crystal in front. They never relocate, change size, multiply or fall. CLOSED hides all six completely. Stages1–8: closed; hairline crack;10% reveal;20% reveal;35% reveal;50% reveal;70% reveal; fully open. The unchanged-size two shells separate and turn outwards, progressively UNCOVERING their attached interiors. All cells use exactly the same shell scale, same fixed front camera and same grounded base height. Each object fits the central75% WIDTH of its own square cell even when fully open; use SMALLER objects and generous empty transparent gutters, never fill the cell edge. No part may approach or cross a cell boundary. Same base near80% cell height. The outer stone cannot inflate as it opens. Opening step sizes are small and coherent; the eight silhouettes evolve monotonically. Broad soft matte painted value bands and sparse gentle brush texture, aqua/lavender shadows and readable child's storybook shapes. Actual completely clean transparent alpha in gutters and outside every contour: NO stray coloured pixels, blue/red/magenta fringes, pink outline, coloured glow, opaque black, white background, checkerboard, contact shadow on a floor, loose sparkles or debris. No words, labels, numbers, lines, camera changes, hands, props, loot drops, duplicate crystals, photorealism, vector diagrams or3D. Fresh original generation with no image bindings.'''
(f/'attempt_02/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'attempt_02/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=2,references=[],prompt_sha256=sha(f/'attempt_02/PROMPT.txt'),targeted_change='Fresh generation removes reference alpha-fringe propagation, enforces75%-cell containment and exact fixed3+3 crystal anatomy. Preserve established described geode identity/material; no novel design.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n### Coherent geode opening source trials (2026-10-02)\n\n| `'+prefix+'/attempt_01/native.png` | Built-in OpenAI ImageGen with exact two existing project prop references | OpenAI generated project source; original reference provenance retained | `'+prefix+'/attempt_01/GENERATION.json` | Native exact bytes, unmodified; eight reviewed states, rejected3.8 sequence, no runtime binding; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native first generation whole sheet and eight individual cell reviews',result='PASS',evidence=prefix+'/attempt_01/REVIEW.json: source rejected3.8; no art-floor pass.'));write(ip,d)
print('A1 exact native preserved and every8 cells scored; rejected3.8. Fresh A2 prompt prepared without image bindings.')
