from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_06';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-45c9e15d-c05a-4a4e-b7da-b1e217dc66ab.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(6):cells.append(dict(id='GEO-COHERENT-A6-STATE-'+str(n),state_index=n,source_rect=[round(n%3*w/3),round(n//3*h/2),round((n%3+1)*w/3),round((n//3+1)*h/2)],score=3.6 if n>=4 else 3.8,material_score=4.4,direct_review=True,evaluation='Fresh paint remains recognizable but broad purple/aqua background glow fails cutout quality. '+('Lower opening merges the two interiors into one shared continuous basin and changes crystal count/ownership; fails two-shell identity.' if n>=4 else 'Background glow and developing crystal anatomy prevent acceptance.'),priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='REJECTED_GLOW_AND_CAVITY_OWNERSHIP',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_06/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=3.6,cells=cells,qualification='Every6 states directly reviewed; fresh source not accepted. No cleanup or runtime binding.'))
plan=json.loads((a/'PLAN.json').read_text(encoding='utf-8'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=6,prompt_path=prefix+'/attempt_06/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=True,references=[],acceptance='REJECTED_GLOW_AND_CAVITY_OWNERSHIP'))
(f/'attempt_07').mkdir()
prompt='''Edit the supplied SIX painted geode states into a clean transparent atlas on a WIDE2:1 canvas. THREE columns byTWO rows, SIX equal rectangular cells (not square); preserve the same six stone/crystal paintings and their exact3+3 attached interiors, in the same order. Remove the cream background and lavender ground patches entirely. Each object is alone on genuinely transparent alpha with no background colour, haze, glow, shadow, fringe or debris. Paint clean plum contours. Place all six objects at the same scale and the same base height within their rectangular cells, centered with generous gutters. Keep all contours fully inside the cells. The two cavity interiors stay distinct; no merged basin, loose gems or crystal-count changes. Preserve the broad2D lavender/aqua gouache material, cream rims and all original crystal identities. Only background extraction and consistent cell positioning; no design, lighting, camera or extra state changes. Wide landscape2:1 canvas with3-by2 rectangular-cell layout, actual clean transparent background. No text, grid, labels, outlines around cells or checkerboard.'''
(f/'attempt_07/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'attempt_07/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=7,references=[dict(path=prefix+'/attempt_04/native.png',sha256=sha(f/'attempt_04/native.png'),role='edit target: accepted individual paintings only')],prompt_sha256=sha(f/'attempt_07/PROMPT.txt'),targeted_change='Wide2:1 extraction/placement trial with rectangular cells. Prior3:2 extraction/fresh variants retain broad failed glow; native A1/A2 wide canvases had transparent gutters. This observed difference motivates a bounded trial, not a presumed technical cause or pass.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_06/native.png` | Fresh built-in OpenAI ImageGen | OpenAI generated project source | `'+prefix+'/attempt_06/GENERATION.json` | Native exact bytes; every6 states reviewed, rejected3.6 glow/cavity ownership, no runtime binding; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native sixth fresh generation every6 states',result='PASS',evidence=prefix+'/attempt_06/REVIEW.json: rejected3.6 glow/cavity ownership.'));write(ip,d)
print('A6 rejected3.6 glow/cavity ownership; wide rectangular-cell extraction A7 prepared without assuming success.')
