from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_07';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-45c22660-5dfe-45b2-a46e-15aeb3e67510.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(6):cells.append(dict(id='GEO-COHERENT-A7-STATE-'+str(n),state_index=n,source_rect=[round(n%3*w/3),round(n//3*h/2),round((n%3+1)*w/3),round((n//3+1)*h/2)],score=4.2 if n==4 else 4.4,material_score=4.6,direct_review=True,evaluation='Wide extraction now produces transparent gutters and preserves the established6 cavity crystals. '+('Bright magenta contamination between the two inner shell outlines fails clean foreground/background separation.' if n==4 else 'Thin pink/blue fringes remain on outer contour and source-cell baseline/scale differs; source cutout not accepted yet.'),priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='REFINEMENT_REQUIRED_CUTOUT_EDGES',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_07/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=4.2,cells=cells,qualification='Every6 native cells directly inspected. Broad extraction glow is gone, but cell4 central magenta contamination and fringe remain failures. No normalization or runtime binding.'))
plan=json.loads((a/'PLAN.json').read_text(encoding='utf-8'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=7,prompt_path=prefix+'/attempt_07/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=True,references=plan['references'],acceptance='REFINEMENT_REQUIRED_CUTOUT_EDGES'))
(f/'attempt_08').mkdir()
prompt='''Precise cleanup edit of this supplied transparent WIDE2:1 SIX-state geode atlas, same3 columns by2 rows and exact object positions. Keep all six paintings, lavender/aqua stone, plum contours, cream rims and all3+3 rooted crystals UNCHANGED. Remove ONLY the stray bright MAGENTA/PINK and electric BLUE fringe pixels outside the plum stone outlines, especially the MAGENTA BLOB between the two halves in the bottom MIDDLE cell. The empty space between those halves must be clean transparent, never pink. Clean transparent alpha in all gutters and outside every contour, no glow or ground shadow. Do not erase the actual plum outline or alter the geode/crystals; no new design, states, scale, background, light or text. Native canvas stays WIDE2:1 with3-by2 rectangular cells. Targeted edge/background cleanup only, all subject identities and existing opening states preserved.'''
(f/'attempt_08/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'attempt_08/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=8,references=[dict(path=prefix+'/attempt_07/native.png',sha256=sha(a/'native.png'),role='edit target: contour fringe/central magenta cleanup only')],prompt_sha256=sha(f/'attempt_08/PROMPT.txt'),targeted_change='Remove specific remaining edge contaminants without changing6 paintings. No procedural cleanup; built-in edit only.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_07/native.png` | Built-in OpenAI ImageGen wide extraction of A4 | OpenAI generated project source; A4 provenance retained | `'+prefix+'/attempt_07/GENERATION.json` | Native exact bytes; every6 states reviewed, source4.2–4.4/material4.6; edge contamination refinement required, unbound; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native seventh wide extraction every6 states',result='PASS',evidence=prefix+'/attempt_07/REVIEW.json: source4.2–4.4, material4.6; edge cleanup still required.'));write(ip,d)
print('A7 transparent-gutter improvement retained; specific magenta/fringe contamination fails4.2–4.4. Targeted A8 edit prepared.')
