from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_08';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-290c722f-25b0-4641-af7c-fdcde3cae95f.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(6):
 rect=[round(n%3*w/3),round(n//3*h/2),round((n%3+1)*w/3),round((n//3+1)*h/2)];reg=im.crop(rect); alpha=reg.getchannel('A'); mask=alpha.point(lambda v:255 if v>=128 else 0); box=mask.getbbox();assert box
 cells.append(dict(id='GEO-COHERENT-A8-STATE-'+str(n),state_index=n,source_rect=rect,alpha128_bbox_local=list(box),source_bbox=[rect[0]+box[0],rect[1]+box[1],box[2]-box[0],box[3]-box[1]],source_aspect=(box[2]-box[0])/(box[3]-box[1]),score=4.5,material_score=4.6,direct_review=True,evaluation='Established2D lavender/aqua stone and cream-rimmed cavities retain three rooted crystals each. Wide extraction has clear gutters; cleanup removes the central magenta blob. A thin residual contour fringe keeps this at the inclusive4.5 source floor and remains a refinement priority. Source-cell geometry/complete action require mounted review.',priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='SIX_INDIVIDUAL_SOURCE_CUTOUTS_PROVISIONAL_FLOOR',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_08/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=4.5,cells=cells,qualification='All6 native cells directly inspected. Each cutout reaches4.5 source floor; inclusive priority remains. Read-only alpha bounds used for atlas selection; no alpha pixel cleanup. Does not pass geometric sequence, acting, production binding, device, child or owner acceptance.'))
plan=json.loads((a/'PLAN.json').read_text(encoding='utf-8'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=8,prompt_path=prefix+'/attempt_08/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=True,references=plan['references'],acceptance='SIX_INDIVIDUAL_SOURCE_CUTOUTS_PROVISIONAL_FLOOR'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_08/native.png` | Built-in OpenAI ImageGen targeted edge cleanup of A7 | OpenAI generated project source; A7/A4 provenance retained | `'+prefix+'/attempt_08/GENERATION.json` | Native exact bytes; every6 states provisional source4.5/material4.6, unbound; no alpha cleanup; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native eighth targeted cleanup every6 states',result='PASS',evidence=prefix+'/attempt_08/REVIEW.json: each source4.5 provisional; residual fringe remains priority, geometric/actual action pending.'));write(ip,d)
print(json.dumps([dict(state=x['state_index'],aspect=round(x['source_aspect'],4),bbox=x['source_bbox']) for x in cells]))
