from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_05';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-d28d6670-f7ef-4016-9ad3-16daab3bb7f1.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(6):cells.append(dict(id='GEO-COHERENT-A5-STATE-'+str(n),state_index=n,source_rect=[round(n%3*w/3),round(n//3*h/2),round((n%3+1)*w/3),round((n//3+1)*h/2)],score=3.8,material_score=4.6,direct_review=True,evaluation='Existing geode paintings remain recognizable and rooted, but extraction produces broad purple/aqua glow throughout the background instead of a clean cutout. Failed background extraction, not runtime-ready.',priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='REJECTED_BACKGROUND_EXTRACTION',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_05/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=3.8,cells=cells,qualification='Every6 states directly inspected. Alpha requested does not establish alpha quality; broad background glow fails. No pixel cleanup, runtime binding or owner acceptance.'))
plan=json.loads((a/'PLAN.json').read_text(encoding='utf-8'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=5,prompt_path=prefix+'/attempt_05/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=True,references=plan['references'],acceptance='REJECTED_BACKGROUND_EXTRACTION'))
(f/'attempt_06').mkdir()
prompt='''A clean transparent sprite sheet of SIX matched gouache-painted children's storybook geode opening states, in3 columns and2 rows. The same rounded lavender geode with a pale aqua shadow band and thin plum contour, closed then tiny crack then quarter open then half open then three-quarter open then fully open, row-major. Inside EACH shell are three chunky crystals permanently rooted in its concave cream-rimmed violet cavity: left tall aqua/medium lavender/short aqua; right tall lavender/medium aqua/short aqua. Crystals are progressively uncovered by the two half-shells opening outward, never loose loot. Keep shell scale, crystal anatomy, camera and base height identical in all six square cells. Modest opening increments, same two shells throughout. Each complete object is SMALL within its cell, with generous empty transparent gutters; nothing clipped. Broad matte pastel painted bands, rounded toy-playset shapes, soft handmade brush texture, clean dark-plum contours. Polished2D illustration, no realistic mineral detail or3D lighting. Transparent background with no shadow, glow, coloured fringe, debris, labels, lines or text. Generate fresh.'''
(f/'attempt_06/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'attempt_06/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=6,references=[],prompt_sha256=sha(f/'attempt_06/PROMPT.txt'),targeted_change='Concise fresh six-state cutout prompt; preserve described existing palette/identity and3+3 rooted crystals, avoid extraction glow. Every state and mounted sequence still pending.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_05/native.png` | Built-in OpenAI ImageGen background extraction of A4 | OpenAI generated project source; A4 provenance retained | `'+prefix+'/attempt_05/GENERATION.json` | Native exact bytes; every6 states reviewed, rejected3.8 background glow, no runtime binding; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native fifth extraction every6 paintings',result='PASS',evidence=prefix+'/attempt_05/REVIEW.json: rejected3.8 background glow; stone material4.6 remains separate.'));write(ip,d)
print('Failed A5 extraction preserved3.8; concise fresh six-state A6 prepared.')
