from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_02';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-28a43356-3bf6-4d32-9d40-627eb92ccda6.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(8):
 rect=[round(n%4*w/4),round(n//4*h/2),round((n%4+1)*w/4),round((n//4+1)*h/2)]
 cells.append(dict(id='GEO-COHERENT-A2-STATE-'+str(n),state_index=n,source_rect=rect,score=3.9 if n==7 else 4.0,material_score=4.4,direct_review=True,evaluation='Fresh unbound painted source retains lavender/aqua/cream palette and rooted crystal intent, but white crust and blue/pink fringe remain around contours and coloured gutter speckles remain. '+('Final pair approaches the outer right edge with insufficient gutter.' if n==7 else 'Camera/stone silhouette and relative crystal sizes change between early and middle states; continuity is not passed.'),priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='REJECTED_SOURCE_SEQUENCE',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_02/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=3.9,cells=cells,qualification='Direct native sheet/every8 cell review. No normalization, cleanup or runtime binding. Fixed3+3 embedded topology improves the final states but cannot pass inconsistent edges/geometry.'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=2,prompt_path=prefix+'/attempt_02/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=True,references=[],acceptance='REJECTED_SOURCE_SEQUENCE'))
(f/'attempt_03').mkdir()
prompt='''Use case: illustration-story. Make one polished PAINTED children's storybook gameplay animation-state sheet: EXACTLY THREE COLUMNS and TWO ROWS, six equally sized square painting cells, overall3:2 landscape canvas. These are consecutive paintings of ONE geode on ONE unchanged little work slab, same front camera, same scale, same base, same lighting in every cell. Every cell is a complete opaque painting with a quiet flat light lavender-grey background and the SAME warm ivory/gold rounded stone work slab at the bottom. No alpha, no checkerboard, no borders or grid lines, no text. Geode is a rounded lavender stone with a subdued aqua shadow band low on the outer shell, thin dark-plum contours and warm creamy cavity rims. Broad quiet painted bands, gentle matte brushwork and handmade rounded toy-playset shapes; clean smooth contours. The six stages in row-major order: CLOSED; very small cracked opening with crystals mostly obscured; QUARTER OPEN; HALF OPEN; THREE-QUARTERS OPEN; FULLY OPEN. Same two solid half-shells separate and gradually turn outwards to uncover their cavities. Left half stays centered at the same x-coordinate and the same fixed base on the slab, right half pivots away gradually. The geode fits comfortably within each cell, max70% cell width, with generous uncluttered space around it. Keep each half's volume, silhouette anatomy and height identical through rotation: no swelling, shrinking, sliding upward or base hops. In the final state each cavity has exactly THREE crystals embedded into the mineral floor: left one tall aqua crystal, one medium lavender crystal behind/right, one short aqua crystal in front; right one tall lavender crystal, one medium aqua crystal behind/left, one short aqua crystal in front. The identical crystal cluster is gradually uncovered from the start, never appears on an outside shell or changes count, relative size or position. No detached gems, floating loot, falling crystals, debris or sparkles. The six stages must show a readable monotonic opening, no repeated final states and no abrupt camera/identity change. Friendly pastel cream, lavender and aqua with restrained plum outlines. Not photorealistic, not3D, not vector-flat, not noisy mineral texture, no pink/blue edge fringes, no white sticker halos, no glow. Fresh original generation, no image bindings. All six slab backgrounds and baselines match exactly.'''
(f/'attempt_03/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'attempt_03/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=3,references=[],prompt_sha256=sha(f/'attempt_03/PROMPT.txt'),targeted_change='Six complete opaque workstation paintings avoid defective cutout edges while testing fixed base and coherent opening; existing runtime slab/material remains preserved. This is ordinary gameplay state art, not cinematic delivery or acceptance.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_02/native.png` | Fresh built-in OpenAI ImageGen without image bindings | OpenAI generated project source | `'+prefix+'/attempt_02/GENERATION.json` | Native exact bytes; every8 states reviewed, rejected3.9 sequence, no runtime binding; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['scope']+=' After two individually reviewed rejected transparent sheets, test six complete opaque workstation paintings with preserved materials and fixed object/slab baseline, unbound; no cinematic exception or procedural subject repair.';d['validation'].append(dict(command='Native fresh second generation whole sheet and eight cell reviews',result='PASS',evidence=prefix+'/attempt_02/REVIEW.json: source rejected3.9, material4.4; no art-floor pass.'));write(ip,d)
print('A2 exact native/every8 state opinions preserved, rejected3.9. Six-state full opaque painted source experiment prepared.')
