from pathlib import Path
import datetime,hashlib,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write(f/'attempt_09/FAILURE.json',dict(status='NO_IMAGE_OUTPUT_TOOL_REJECTED',recorded_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),method='built-in image_gen',request_id='3d28a327-5020-46ba-af9a-3c2437fa176e',error='http400 moderation_blocked at output stage; category sexual',qualification='Prompt requested an educational geology specimen only; no generated image was returned or inspected. No source score or acceptance inferred. Failure preserved; retry clarifies the scientific rock subject.'))
a=f/'attempt_10';a.mkdir(exist_ok=False)
prompt='''Educational geology game artwork: TWO consecutive painted illustrations of a cracked MINERAL ROCK SPECIMEN with crystals growing inside it. Match the supplied lavender rock specimen and its aqua/lavender crystals. Wide2:1 transparent canvas, two separate square cells, one specimen per cell. The left rock is about one-third opened, the right rock slightly more opened but less than halfway. These states lie between the supplied top-right quarter-open specimen and bottom-left half-open specimen. Keep each solid stone shell's shape/height, camera, material and exact mineral cluster identity stable. Each stone part contains three permanently embedded crystals, same relative sizes/locations as the reference, still partly hidden by the rock. The crystals never become detached prizes. At equal height, left specimen width about1.34 times height, right about1.41 times height. Keep specimens small in each cell with generous transparent margins and identical base level. Broad matte lavender/aqua gouache bands, thin plum outlines, cream mineral rim, friendly storybook rock shapes. Clean transparent alpha around the rock, no background, haze, coloured fringe, floor shadow, glitter, text or labels. This is a scientific mineral specimen, no people or anatomy.'''
(a/'PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(a/'PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=10,references=[dict(path=prefix+'/attempt_08/native.png',sha256=sha(f/'attempt_08/native.png'),role='exact educational specimen style/mineral identity')],prompt_sha256=sha(a/'PROMPT.txt'),targeted_change='Clarify educational mineral-rock subject after failed output moderation of otherwise geology-only bridge request. Same two measured state gaps; no forbidden imagery or safety bypass.'))
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()});d['validation'].append(dict(command='Generate two bridge specimens attempt9',result='FAIL',evidence=prefix+'/attempt_09/FAILURE.json: tool returned no image, no visual opinion.'));write(ip,d)
print('Attempt9 no-image rejection preserved; explicit educational mineral-specimen retry prepared.')
