from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_03';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-b6066cd2-ef51-4f0e-b430-f9f027585c76.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(6):
 cells.append(dict(id='GEO-COHERENT-A3-STATE-'+str(n),state_index=n,source_rect=[round(n%3*w/3),round(n//3*h/2),round((n%3+1)*w/3),round((n//3+1)*h/2)],score=3.8,material_score=4.1,direct_review=True,evaluation='Opaque paint removes the transparent fringe issue, but rounded volumetric lighting, neutral brown-grey cavity and irregular extra front crystals move away from the established broad lavender/aqua storybook design. Camera/front orientation and cluster anatomy shift between states. Unbound failed style/continuity experiment.',priority=True,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='REJECTED_STYLE_AND_TOPOLOGY',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_03/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_score=3.8,cells=cells,qualification='Every6 native state paintings directly inspected; opaque background is a technical experiment, not permission to substitute a different style or accept sequence/acting. No runtime binding.'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=3,prompt_path=prefix+'/attempt_03/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=False,references=[],acceptance='REJECTED_STYLE_AND_TOPOLOGY'))
(f/'attempt_04').mkdir()
prompt='''Use case: illustration-story. Create a PAINTED2D storybook gameplay geode opening atlas, exactly3 equal columns by2 equal rows, six square cells on a3:2 landscape canvas. REFERENCE1: closed lavender geode identity, proportions, broad2D brushwork and aqua low shadow band. REFERENCE2: open shell identity, cream rims and exactly three crystals embedded in EACH cavity. Match these references closely, especially their flat broad GOUACHE painted value bands and warm plum outlines, not realistic stone or volumetric3D rendering. Make six consecutive states of the SAME object, row-major: closed, hairline cracked, quarter open, half open, three-quarters open, fully open. SAME6 crystal identities and exact relative sizes: left cavity tall aqua / medium lavender / short aqua, right cavity tall lavender / medium aqua / short aqua. The stone halves simply part and turn outward gradually; interiors are concealed at first and gradually uncovered. Crystals stay attached to their own cavity floors through every state. Preserve the outline/anatomy/scale of each shell, same camera and same bottom baseline across every cell. Every shell/base is at exactly the same height, no jump or swelling. Closed is narrower than full-open only because the unchanged-size halves part. Keep the whole object inside each cell, plenty of empty space all round, max75% cell width. Paint every cell on the EXACT SAME opaque light cream background with an unobtrusive soft lavender contact patch beneath the geode. No separate circular plinth, realistic floor, environmental scene, frame border or grid line. Background is a flat matte clean cream colour, not alpha: paint the OUTER contours freshly without any inherited coloured fringe. This is a2D painted children's book picture, broad soft lavender/aqua material bands, chunky simple crystal facets, cream rims and thin plum contours. NO photorealism,3D render, directional studio lights, realistic geological texture, brown-grey cavities, extra crystals, glitter, loose jewels, loot, glow, magenta/blue fringing, white sticker halos, labels, text, arrows or panel borders. Preserve the established crystal count and identities across all six; create small coherent opening changes rather than replacing a rock with a different-shaped specimen.'''
(f/'attempt_04/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
refs=[dict(path=p,sha256=sha(b/p),role='closed identity/style' if i==0 else 'embedded open identity/style') for i,p in enumerate(['assets/opera/worlds/geology/painted_geode_v1_20261001/closed.png','assets/opera/worlds/geology/painted_geode_v1_20261001/open_embedded.png'])]
write(f/'attempt_04/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=4,references=refs,prompt_sha256=sha(f/'attempt_04/PROMPT.txt'),targeted_change='Restore exact existing painted2D identity/3+3 crystals using two approved prop references; keep clean opaque card experiment. Three earlier rejected sheets retained.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_03/native.png` | Fresh built-in OpenAI ImageGen without image bindings | OpenAI generated project source | `'+prefix+'/attempt_03/GENERATION.json` | Native exact bytes; every6 states reviewed, rejected3.8 style/topology, no runtime binding; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native third generation whole sheet and six cell reviews',result='PASS',evidence=prefix+'/attempt_03/REVIEW.json: source rejected3.8 style/topology.'));write(ip,d)
print('A3 rejected3.8 style/topology and every6 states retained; exact original2D-reference A4 prepared.')
