from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_coherent_states_v1_20261002';prefix=f.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();a=f/'attempt_04';source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-d2512839-9cbb-49c3-8bd3-15dd59833fa3.png');shutil.copyfile(source,a/'native.png');assert sha(source)==sha(a/'native.png')
im=Image.open(a/'native.png');w,h=im.size;cells=[]
for n in range(6):
 cells.append(dict(id='GEO-COHERENT-A4-STATE-'+str(n),state_index=n,source_rect=[round(n%3*w/3),round(n//3*h/2),round((n%3+1)*w/3),round((n//3+1)*h/2)],score=4.6,direct_review=True,evaluation='Established broad lavender/aqua painted stone and plum contours return without cutout fringe. Cream rim and3+3 embedded clusters remain readable. '+('Closed exterior fully hides crystals.' if n==0 else 'Progressive opening reveals its own rooted mineral cavity.'),priority=False,owner_acceptance=None))
write(a/'REVIEW.json',dict(status='INDIVIDUAL_PAINTINGS_SOURCE_CANDIDATE_ONLY',reviewed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),native_path=prefix+'/attempt_04/native.png',sha256=sha(a/'native.png'),dimensions=[w,h],mode=im.mode,sheet_material_score=4.6,unmounted_sequence_score=4.4,cells=cells,qualification='Every6 painting directly reviewed. Individual material4.6 does not pass source-cell pivot mismatch, small final-state opening differences or opaque card mounting. Current gameplay opening remains4.2 until an isolated mounted sequence is reviewed. No production binding or owner acceptance.'))
plan=json.loads((a/'PLAN.json').read_text(encoding='utf-8'))
write(a/'GENERATION.json',dict(method='built-in image_gen',attempt=4,prompt_path=prefix+'/attempt_04/PROMPT.txt',prompt_sha256=sha(a/'PROMPT.txt'),native_source_path=str(source),native_sha256=sha(source),native_preserved_bytes=True,transparent_background_requested=False,references=plan['references'],acceptance='INDIVIDUAL_PAINTINGS_SOURCE_CANDIDATE_ONLY'))
(f/'attempt_05').mkdir()
prompt='''Use case: background-extraction. Edit target: supplied SIX-STATE painted geode sheet. Preserve the six exact painted objects, their locations, proportions, shell contours, broad lavender/aqua gouache brushwork, plum outlines, cream rims and every embedded crystal pixel identity as closely as possible. Remove ONLY the entire opaque cream background and ground shadow patches so this becomes a clean transparent3-column2-row gameplay state atlas. Keep the six objects separated in their existing cells; no resizing, recentering, new states, compositing, extra crystals, detached gems, lighting or style changes. Actual transparent alpha outside each contour and in every cell gutter. Smooth clean plum contour with no white/cream sticker rim, coloured glow, magenta/blue edge speckles or stray opaque pixels; remove the background up to the outer plum contour without eating the stone. Crystals stay rooted inside their original own cavity floors. No new text, numbers, labels, grid, floor or checkerboard. Keep the existing state order from closed through open, the same native image aspect and clear empty gutters.'''
(f/'attempt_05/PROMPT.txt').write_text(prompt,encoding='utf-8',newline='\n')
write(f/'attempt_05/PLAN.json',dict(status='GENERATION_PENDING_UNBOUND',attempt=5,references=[dict(path=prefix+'/attempt_04/native.png',sha256=sha(a/'native.png'),role='edit target: remove background only')],prompt_sha256=sha(f/'attempt_05/PROMPT.txt'),targeted_change='Clean background extraction only after A4 restores established material. Native original preserved; transparency and every cell/actual mounted opening must be reviewed independently.'))
p=b/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8')+'\n| `'+prefix+'/attempt_04/native.png` | Built-in OpenAI ImageGen with exact established closed/open prop references | OpenAI generated project source; reference provenance retained | `'+prefix+'/attempt_04/GENERATION.json` | Native exact bytes; every6 paintings material4.6, source sequence4.4 provisional/unbound; SHA256 '+sha(a/'native.png')+' |\n';p.write_text(s,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-coherent-opening-20261002.json';d=json.loads(ip.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Native reference-bound fourth generation every6 paintings',result='PASS',evidence=prefix+'/attempt_04/REVIEW.json: each material4.6 candidate, source-cell sequence4.4 unbound; no action-floor pass.'));write(ip,d)
print('A4 every6 source paintings4.6 individually; sequence4.4 unbound. Background-only extraction A5 prepared, originals preserved.')
