from pathlib import Path
import datetime,hashlib,json,re,shutil,subprocess
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geode_route_emblem_runtime_v1_20261002'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
remote=read(b/'tmp/geology_checkpoint_k_remote_v259/RESULT.json');assert remote['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES'
baseline=subprocess.check_output(['git','rev-parse','HEAD'],cwd=b,text=True).strip();assert baseline==remote['revision']
names=['scripts/castle_career_routes.gd','scripts/opera_career_world_2d.gd','scripts/opera_hotspot_catalog.gd'];before={rel:dict(path=rel,sha256=sha(f/'prior_source'/Path(rel).name),bytes=(f/'prior_source'/Path(rel).name).stat().st_size) for rel in names}
source='assets/opera/worlds/geology/coherent_geode_v1_20261002/opening_six_states.png';assert sha(b/source)=='e47a731414210ef70c0b5fffce2828922a15611c6093c244811ee0a283534503'
open_region=[1392.270574971815,556.446448703495,617.632468996618,393.668545659527];closed_region=[96.974069898534,68.112739571590,473.325817361894,421.375422773393];height=142*closed_region[3]/closed_region[2]
reuse=b/'assets_src/reuse/geology_geode_emblems_v1_20261002';resource=b/'assets/opera/worlds/geology/coherent_geode_v1_20261002/open_geode.tres';assert resource.read_bytes()==(reuse/'open_geode_unbound.tres').read_bytes()
def funcs(s):
 lines=s.splitlines(keepends=True);out={}
 for i,line in enumerate(lines):
  m=re.match(r'^(?:static )?func (\w+)',line)
  if not m:continue
  j=i+1
  while j<len(lines) and (not lines[j].strip() or lines[j].startswith(('\t',' '))):j+=1
  out[m.group(1)]=''.join(lines[i:j]).rstrip()
 return out

proof=[]
for rel in names:
 old=(f/'prior_source'/Path(rel).name).read_text();new=(b/rel).read_text();a=funcs(old);c=funcs(new);changed=[n for n in a if a[n]!=c[n]];assert set(a)==set(c);assert changed==(['_allowed_runtime_path'] if rel.endswith('opera_hotspot_catalog.gd') else []),(rel,changed)
 proof.append(dict(path=rel,before_sha256=before[rel]['sha256'],after_sha256=sha(b/rel),function_count=len(a),changed_functions=changed,unchanged_functions=[n for n in a if a[n]==c[n]]))
write(f/'MECHANIC_UNCHANGED.json',dict(status='ONLY_ART_METADATA_BINDINGS_AND_EXACT_ASSET_ALLOWLIST_CHANGED',baseline=baseline,records=proof,qualification='Castle and career-world function bodies all literal unchanged; catalog changes only GEODE art/path/aspect, added exact source metadata and one exact approved path. No target minimum, input, phase, reward, save, timer, return or progress code changes. Gutter/aspect/resource runtime validation still required.'))
scope='Reversibly reuse the accepted authored geode across actual Library crest and normal earned celebration; replace two individually reviewed flat vector defects2.9. Match closed invitation to the current seven-state family; old closed source is acceptable4.6 and retained, no invented source defect. Same whole atlas pixels/hash/alpha, one new open AtlasTexture metadata resource and current closed crop region; no generation, source image edits, mechanics or save changes.'
plan=dict(status='REVERSIBLE_RUNTIME_CANDIDATE_PENDING_GATES_AND_ACTUAL_REVIEW',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseline=baseline,scope=scope,inventory=[*before.values(),dict(path=source,sha256=sha(b/source),bytes=(b/source).stat().st_size),dict(path=(reuse/'REVIEW.json').relative_to(b).as_posix(),sha256=sha(reuse/'REVIEW.json'))],bindings=dict(crest=dict(path=resource.relative_to(b).as_posix(),width=50,rect=[50,50],source_opinion=4.5),goal=dict(path=resource.relative_to(b).as_posix(),rect=[220,220],source_opinion=4.6),invitation=dict(source=source,region=closed_region,width=142,height=height,offset=[-40,-70],motion='pulse',source_opinion=4.5)),cache_budget=dict(atlas_size=[2048,1024],format='RGBA8',nominal_decoded_bytes=8388608,shared_with='Current authored seven-state opening via ResourceLoader cache; the actual RID/cache claim must be checked in engine, not assumed.',qualification='Whole atlas is held even for a tiny icon. Device VRAM/overdraw/fps remain unmeasured. Previous invitation texture1024-square nominal4MiB; this change can load8MiB earlier. Source reuse does not itself prove a performance pass.'),required_evidence=['Parser/inference for all three changed GDScripts and separate review fixture.','Mandatory import and official Godot4.7.2 analyzer; existing whole catalog resource/aspect/alpha-gutter validation without relaxing it.','Actual normal Library card->all four intentional actions->normal celebration->earned Library return, and separate elevator developer replay/back, at1280/1600. No injected art, forced phases/results/callbacks.','Direct individual mounted stills and every consecutive captured opening/celebration/return frame with source hashes; source opinion never substitutes runtime opinion.','Fresh full unmodified CI on the new frozen literal source boundary; authority/development/2D gates; reversible exact topic publication plus anonymous every-file verification.','Physical device, child and owner final acceptance remain separate; no finding closure from machine checks.'])
write(f/'PLAN.json',plan)
oldfamily='audit/job_geology_room_route_v1_20261002';prefix=f.relative_to(b).as_posix();capture=(b/oldfamily/'capture_v2.gd').read_text();assert capture.count(oldfamily)==1;capture=capture.replace(oldfamily,prefix).replace('/attempt_02/','/attempt_01/');(f/'capture.gd').write_text(capture,encoding='utf-8',newline='\n')
runner=(b/oldfamily/'review_tools/run_geology_room_gates_v252.py').read_text().replace(oldfamily,prefix).replace('job-geology-room-route-review-20261002.json','job-geode-route-emblem-runtime-20261002.json').replace('capture_v2.gd','capture.gd').replace('run_geology_room_gates_v252.py','run_geode_route_gates_v276.py').replace('geology_room_route_','geode_route_emblems_').replace('_v252','_v276').replace("'scripts/opera_geology_surface.gd',", "'scripts/castle_career_routes.gd', 'scripts/opera_career_world_2d.gd', 'scripts/opera_hotspot_catalog.gd',")
(f/'review_tools/run_geode_route_gates_v276.py').write_text(runner,encoding='utf-8',newline='\n');compile(runner,'run_geode_route_gates_v276.py','exec');shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-route-emblem-runtime-20261002.json';assert not ip.exists();write(ip,dict(id='job-geode-route-emblem-runtime-20261002',scope=scope,baseline=baseline,rules=['DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-07','DL-VIS-08','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-MED-01','DL-INT-01','DL-INT-02','DL-INT-03','DL-INT-04','DL-INT-06','DL-INT-12','DL-SAVE-01','DL-SAVE-02','DL-QA-01','DL-QA-02','DL-QA-03','DL-QA-06'],findings=['MA-PLAY-004','MA-VIS-006','MA-OPERA-012'],files=sorted(set(names)|{resource.relative_to(b).as_posix(),'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md'}|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}),validation=[],acceptance_gaps='Fresh mounted route and full CI pending. Room2.8/contact2.7/pan3.8/clearing3.9/celebration composition3.2 remain weak; all-job/device/child/owner/native-background/strict-2D acceptance open. No lifecycle closure, dev/master integration or release.'))
p=b/'ASSET_LICENSES.md';s=p.read_text();s+='\n| `'+resource.relative_to(b).as_posix()+'` | Existing built-in Codex painted geode, exact AtlasTexture metadata reuse | Same generated-project-art provenance as `'+source+'` | `'+prefix+'/PLAN.json` | Reversible shared open geode for actual Library crest and normal celebration; native source pixels/alpha unchanged, original vectors preserved. |\n';p.write_text(s,encoding='utf-8',newline='\n')
note='Painted geode route continuation (2026-10-02): [Reversible binding and pending actual route review]('+prefix.removeprefix('audit/')+'/PLAN.json) reuses the same seven-state source for the Library crest, closed invitation and normal earned celebration. Source opinions4.5/4.6 are provisional; fresh runtime/gates/full CI are pending. Older flat vector crest/goal2.9 and acceptable closed source remain preserved. Room2.8/contact2.7/clearing3.9/pan3.8/celebration composition3.2 and all-job/device/child/owner acceptance remain open. No finding lifecycle change, integration or release.'
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
 p=b/rel;s=p.read_text();n=note.replace(']('+prefix.removeprefix('audit/'),'](../'+prefix.removeprefix('audit/')) if '/findings/' in rel else note;s=s.replace('\n\n','\n\n'+n+'\n\n',1);p.write_text(s,encoding='utf-8',newline='\n')
p=b/'design/05_DOC_LEDGER.md';s=p.read_text();s+='\n| `'+prefix+'/PLAN.json` | 🔵 | `SUPPORTING_CURRENT` reversible same authored geode crest/invitation/normal celebration binding at exact published checkpoint `'+baseline+'`; source4.5/4.6 does not grant actual route acceptance, fresh gates/full CI pending. Original flat emblem2.9 and acceptable previous closed source preserved. Remaining room/contact/action/stage/native-background/device/child/owner/strict-2D gaps and findings unchanged. |\n';p.write_text(s,encoding='utf-8',newline='\n')
allow=b/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()}|{resource.relative_to(b).as_posix(),source}))
print(json.dumps(dict(status=plan['status'],baseline=baseline,family=prefix,functions=[dict(path=x['path'],count=x['function_count'],changed=x['changed_functions']) for x in proof],source_image_unchanged=True)),flush=True)
