from pathlib import Path
import collections,hashlib,json,re,subprocess,html
P=Path('docs/handoffs/codex_flat_vector_art_2026-10-07');R=Path.cwd();BASE='92c9fe70319ef46bfaa8f61348a6f51512141ec3'
def load(n):return json.loads((P/n).read_text(encoding='utf8'))
def save(n,v):(P/n).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n',encoding='utf8', newline='\n')
inv=load('source_inventory.json');pieces=load('per_piece.json')['pieces'];scopes=load('source_scopes.json')['scopes'];tally=load('tally.json');cov=load('scene_coverage.json');contact=load('contact_index.json')['images']
# Shader and legacy stand-in coverage cannot disappear behind a file-extension count.
paths=subprocess.check_output(['git','ls-tree','-r','--name-only',BASE],cwd=R).decode().splitlines();shaders=[]
for path in paths:
    if Path(path).suffix.lower() in {'.gdshader','.shader'}:
        text=(R/path).read_text(encoding='utf8');consumers=[]
        for source in inv['scripts']:
            for i,l in enumerate((R/source['path']).read_text(encoding='utf8').splitlines(),1):
                if path in l or Path(path).name in l:consumers.append({'path':source['path'],'line':i,'expression':l.strip()})
        shaders.append({'path':path,'sha256_lf':hashlib.sha256(text.replace('\r\n','\n').encode()).hexdigest(),'shader_type':re.findall(r'shader_type\s+(\w+)',text),'static_consumers':consumers,'status':'NEEDS_CONTEXT_REVIEW','disposition':'Visible procedural dirt/water/ripple/material is art/effect review; invisible masks are functional. Spatial shaders retain separate shrinking 3D debt. No current visual exemption.'})
save('shader_inventory.json',{'schema':'reef.flat_vector_shaders/1','baseline':BASE,'shaders':shaders})
legacy=[s for s in scopes if any(k in ''.join(x['kind'] for x in load('primitive_sites.json')['sites'] if x['id'] in s['primitive_site_ids']) for k in ['Mesh.new/create'])]
save('legacy_standins.json',{'schema':'reef.flat_vector_legacy/1','baseline':BASE,'source_scopes':legacy,'note':'Candidate primitive-mesh stand-ins remain shrinking 3D debt; texture-backed cards are not automatically weak flat illustration. Their visual roles/normal reachability must be reviewed before retirement. No new 3D or archive resurrection.'})
# Explicit provenance/origin disposition for vector source files outside runtime.
assets=[x for shard in inv['image_shards'] for x in load(shard['path'])['images']]
save('vector_method_dispositions.json',{'schema':'reef.flat_vector_methods/1','baseline':BASE,'runtime_svgs':[x for x in assets if x['path'].startswith('assets/') and x['path'].endswith('.svg')],'source_or_review_vectors':[x for x in assets if x['path'].startswith('assets_src/') and x['path'].endswith('.svg')],'proven_valid_painted_vector_origin':[],'painted_vector_origin_gap':'No source-method claim is inferred from brush texture or file extension. If an otherwise valid painted vector-origin image is discovered, record style validity separately from literal-method removal and preserve pixels; no novelty redraw.','raster_candidates':'per_piece.json and source inventory include raster lookalikes; unknown origin remains unknown.'})
# Rich local/GitHub review index with searchable named designs and self-contained SVGs.
records=[]
for p in pieces:
    s=p['source'];records.append({'id':p['id'],'name':p['name'],'family':p['family'],'status':p['status'],'priority':p['priority'],'evidence':p['evidence_level'],'source':s['path'],'line':s['start_line'],'route':p['route_evidence'],'weakness':p['observed_weakness'],'proposal':p['proposed_update'],'brief':p['individual_brief_id']})
payload=json.dumps(records,ensure_ascii=False).replace('</',r'<\/')
body='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Flat-vector art audit R1</title><style>body{font:16px system-ui;background:#edf5f3;color:#2a2946;margin:24px auto;max-width:1300px;padding:0 20px}h1{font-size:30px}.notice{background:#fff0dc;padding:16px;border-radius:12px}input,select{padding:12px;margin:8px 8px 8px 0;font:inherit;border:1px solid #aaa;border-radius:8px}table{border-collapse:collapse;width:100%;background:white}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #ccc}summary{cursor:pointer}pre{white-space:pre-wrap}img.sheet{width:min(100%,660px);margin:8px}.svg{display:inline-block;background:white;margin:8px;padding:8px;width:180px}.svg img{width:160px;height:160px}a{color:#5c3793}small{display:block;color:#68607b}</style><h1>Flat-vector art audit: 2026-10-07</h1><p class="notice">224 named design/state families remain a lower bound. R2 adds192 current Mobile/Speedy captures: all15 free-play careers and70 actual open phases at two aspects. R3 adds100 Castle/Day One frames (292 cumulative):30/176 partial entries,zero complete;two functional texture-mask scopes dispositioned,367 unresolved. Source/historical boards below retain their original scope. No replacement or acceptance is claimed.</p><p><a href="live_v3/README.md">Current R3 visual review</a> · <a href="live_v2/README.md">R2 Castle/Opera evidence</a> · <a href="README.md">Handoff</a> · <a href="AUDIT.md">Audit</a> · <a href="PRODUCTION_BACKLOG.md">Production order</a> · <a href="tally.json">Tally</a> · <a href="MANIFEST.json">Manifest</a></p><h2>Context evidence</h2>'''
for path in sorted({r['packet_path'] for r in contact if r['packet_path'].endswith('.png')}):body+='<a href="'+path+'"><img class="sheet" src="'+path+'" alt="'+html.escape(path)+'"></a>'
body+='<h2>Actual SVG sources: review only</h2><p>Painted hotspot presentation may suppress source pixels. Visibility must be checked per consumer; format conversion does not repair weak art.</p>'
for path in sorted({r['packet_path'] for r in contact if r['packet_path'].endswith('.svg')}):body+='<div class="svg"><img src="'+path+'" alt="'+html.escape(path)+'"><small>'+html.escape(Path(path).stem)+'</small></div>'
body+='''<h2>Named designs</h2><input id="search" placeholder="Search object, route, source or brief"><select id="family"><option value="">All families</option></select><select id="status"><option value="">All status lanes</option></select><p id="count"></p><table><thead><tr><th>ID / object</th><th>Family / status</th><th>Evidence / current source</th><th>Context and proposed update</th></tr></thead><tbody id="rows"></tbody></table><script>const records='''+payload+''';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));for(const key of ['family','status']){for(const x of [...new Set(records.map(r=>r[key]))].sort()){const o=document.createElement('option');o.value=x;o.textContent=x;document.getElementById(key).append(o)}}function render(){const q=document.getElementById('search').value.toLowerCase(),f=document.getElementById('family').value,s=document.getElementById('status').value;const out=records.filter(r=>(!f||r.family===f)&&(!s||r.status===s)&&JSON.stringify(r).toLowerCase().includes(q));document.getElementById('count').textContent=out.length+' of '+records.length+' named design/state families (not a final individual-piece total)';document.getElementById('rows').innerHTML=out.map(r=>`<tr><td>${esc(r.id)}<br><b>${esc(r.name)}</b></td><td>${esc(r.family)}<br>${esc(r.status)}<small>${esc(r.priority)}</small></td><td>${esc(r.evidence)}<small><a href="https://github.com/Ebonyks/mermaid-roshan-reef/blob/'''+BASE+'''/${encodeURI(r.source)}${r.line?'#L'+r.line:''}">${esc(r.source)}${r.line?':'+r.line:''}</a></small></td><td><details><summary>${esc(r.route)}</summary><p>${esc(r.weakness)}</p><p>${esc(r.proposal)}</p><small>${esc(r.brief)} in per_piece_briefs.json</small></details></td></tr>`).join('')}for(const k of ['search','family','status'])document.getElementById(k).addEventListener('input',render);render();</script></html>'''
(P/'index.html').write_text(body,encoding='utf8', newline='\n')
print('SHADERS',len(shaders),'LEGACY SOURCE SCOPES',len(legacy),'HTML',len(body))
