from pathlib import Path
import hashlib,json,re
P=Path(__file__).resolve().parent;R=P.parents[2]
def get(n):return json.loads((P/n).read_text(encoding='utf8'))
def save(n,v):(P/n).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n',encoding='utf8', newline='\n')
piece=get('per_piece.json');briefs=get('contextual_briefs.json');coverage=get('scene_coverage.json');scopes=get('source_scopes.json')['scopes'];parents={b['family']:b for b in briefs['briefs']};careers={c['costume']:c for c in coverage['live_opera_careers']}
rootobs=get('context_review_observations.json')['observations'];garden=get('garden_context_review.json')['observations']
specific={
'Riverbed excavation cells':('Dry ground uses dots; excavated cells become solid circles joined with thick flat lines.','Prepare one painted riverbed/soil substrate with matching dug/dry cell variants. Any four-neighbour excavation remains valid; do not bake only the suggested path.','Dirt bed supports dry/dug cells and flowing channel edges; no detached stroke above soil.'),
'River source/sink pools':('Spring and sink are concentric flat circles/arcs with a color switch.','Use source-fitting painted spring mouth and receiving pool with dry/connected water states, at river_path_point(0) and the final path point.','Water emerges from source bank and enters receiving basin; pool rim/flow owns pixels once.'),
'Connected flowing channel':('Connected water uses uniform thick lines/circles and repeated arc highlights.','Derive painted open/connected current bands for every allowed cell junction; retain wet-cell masks as functional clipping. Inspect all four neighbour transitions.','Channel floor, banks and wet current share excavation contacts; no floating surface stripe.'),
'Fossil dirt-cover cells':('Uniform opaque rectangular dirt cells obscure the fossil, producing block edges during scrubbing.','Author granular dirt coverage on the actual fossil slab; retain scrub-grid masks and exact cleared-state progression.','Dirt lies on fossil surface; no extra opaque backing over revealed fragment.'),
'Fossil reveal slab and fragments':('Current whole fossil and three fragments derive from the spiral/polygon SVG.','Find a matching approved fossil-bearing slab or prepare one coherent painted shell-relief whole; derive all three matching fragments from its exact pixels.','Fragment edges reassemble to the same whole at fossil_piece_target, with unchanged home/drag/snapping geometry.'),
'Washing pan rim/body':('PAN_PATH is empty; the pan is rendered by nested flat ellipses.','Inventory the native geology candidate at full alpha. If unsuitable, author one whole pan in the existing overhead angle with readable rim thickness and substrate.','Pan body/rim supports water/sand, all wash contents stay inside its basin.'),
'Pan water/wash accents':('Pan water is a flat fill with procedural arcs.','Reuse an inspected compatible authored ripple/water family or derive local washing states from the same pan. Keep nine reversals and visual travel.','Local wet surface and ripples sit inside the pan, below rim and revealed mineral specimens.'),
'Pan sand covering':('Sand is procedural dots/fills over a flat pan.','Author sand-covered/washed/revealed states from the same pan identity and retain the existing reveal mask.','Sand occludes minerals only until washed; no detached dots above pan plane.'),
'Geode closed shell':('GEODE_PATH is empty; closed geode is a flat colored polygon.','Inspect available geology rocks, then supply one whole closed geode with painted stone volume in exact existing workbench orientation.','Closed rock sits on current workbench and owns its outer contour once.'),
'Geode matching opening halves':('Opening uses separately colored polygon halves with geometric interior crystal art.','Derive both opening halves and matched mineral interior from one source identity; author coherent opening endpoints and review seam frame-step.','Halves preserve the original shell outline/seam and expose one compatible interior, no pasted second crystal.'),
'Geode seam targets':('Five seam targets are diagram-like circles on the closed shell.','Make subtle object-bound painted seam/contact cues, preserving all five targets and 120px pull.','Cue follows actual crack on geode surface, never a detached screen marker.'),
'Mineral specimen token':('Minerals use geometric polygon/ellipse diagrams in the revealed pan.','Use distinguishable painted specimens matching the pan interior scale and warm reward hierarchy; preserve count/selection meaning.','Specimens settle in pan basin and are correctly occluded by sand/water until reveal.'),
'Crystal gallery arrangement':('Crystal gallery consists of a procedural geometric arrangement.','Inspect actual gallery end state and reuse suitable accepted crystal art with one measured gallery arrangement; preserve result identity.','Crystal feet rest on same display support; no duplicated baked/live crystals.'),
'Geology workbench surface':('Workbench is a flat rounded panel built through _draw_rounded_rect.','Prepare a tangible painted wood/stone work surface in the current 860x560 stage role, keeping the exact activity coordinate frame.','Workbench supports river/fossil/pan/geode objects; no extra translucent frame stack.'),
'Nursery safety mat':('Dolls draws a StyleBoxFlat mat with no authored textile volume.','Prepare one broad padded mat aligned with safe_mat_rect and real nursery floor perspective; keep safe landing and no-fail mercy.','All safely landed babies visibly rest on the mat, below their whole-body silhouettes.'),
'Nursery quilt seams and tufts':('Repeated straight quilting lines and dot tufts are drawn over the flat mat.','Include quilt seams and tufts in the same authored mat material, rather than separate full-surface overlays.','Seams follow mat plane, no marks drawn over baby faces.'),
'Nursery cradle sling':('Cradle is three thick stacked semicircle arcs.','Prepare a coherent whole soft cradle/sling matching bowl_rect and broad moving catch region; preserve painted babies and selected character mounting.','Caught baby enters and rests in sling; lip occlusion agrees with catcher and never covers required actor.'),
'Cradle focus halo':('Two U-shaped arcs pulse/bob around the cradle.','Use one subtle object-bound authored focus state or remove redundant cue after phone-context review, keeping discoverability.','Cue belongs to live cradle rim and remains below Roshan.'),
'Caught-baby progress pips':('Progress uses concentric flat color dots.','Use distinct pictured empty/earned baby/shell progress states in the same three positions, preserving earned count.','Progress sits in current HUD strip; does not compete with active baby/catcher.'),
'Safe-landing ring':('Procedural full-circle halo is drawn around safe-landed babies.','Use a bounded appropriate authored contact accent only if it explains safe landing; otherwise retain baby/mat state without extra decoration.','Payoff ring never overdraws baby contour or adds a second visual baby.'),
'Teacher circle/triangle/square lesson tokens':('Lesson tokens are uniform code shapes with no authored material.','Keep exact mathematical silhouettes, answer colors and counts; apply restrained painted material inside those identical shapes, not shell substitution.','Tokens sit flat on lesson board and inside the unchanged generous answer regions.'),
'Teacher counted dot/token family':('Counted objects are diagrammatic uniform circles.','Prepare consistent tangible counting tokens with identical item count, clear separation and current grouping; review both single and full groups.','Each group is readable on its board/answer area, no decorative token or mark that changes the count.'),
'Teacher pattern row sockets':('Pattern rows use diagram-like socket/selection framing.','Paint quiet board/socket material while keeping actual circle/triangle sequence and blank-answer location.','Pattern tokens belong to the same ordered row; target cue points at unresolved answer.'),
'Teacher count/add/match answer surface':('Answer choices and grouping frame use flat board-like panels.','Create quiet painted lesson-board material for each actual count/add/match layout; preserve exact answers, quantities and direct touch meaning.','Board backing stays beneath all tokens; selection does not obscure the lesson.'),
'Teacher hint button surface':('Hint button is a flat illustrated control candidate.','Use a pictured painted hint control at the current region with normal/pressed/focus states and unchanged demonstration logic.','Hint cue stays on actual button, not a distant lesson target.'),
'Teacher demo pointer':('Demo uses code-drawn pointer geometry.','Reuse approved authored ghost-hand/pointer if it targets the same live lesson region with correct scale and contact pose.','Tip points at actual lesson item or answer, no jumping/floating cue.'),
'Missing-import vector candle fallback':('Vector candle/flame path is guarded by availability of both painted sprites; normal art is already painted.','Keep accepted exact unlit/lit PNGs, prove availability at export/re-entry, then retire obsolete flat fallback and any recreation path.','Candle owns current holder/table contact and the whole Ember carry state, no new candle identity.'),
'Ember scout silhouette':('Source explicitly uses non-identifying polygon Scout art with identity_art_approved=false.','Find authoritative Scout source and prepare a whole-character arrival/look/exit action in Main Hall. Missing accepted source identity remains an exact gap.','Feet/body stage correctly near party table; identity cannot be invented from generic silhouette.'),
'Ember King silhouette':('Source explicitly uses non-identifying polygon King art with identity_art_approved=false.','Inventory owner-authoritative King/V4 sources; bind a complete arrival/approach/grasp/carry/exit performance to the accepted candle.','Whole body, hands and candle keep truthful grasp/support/occlusion; no detached moving arm.'),
'Ember Prince silhouette':('Source explicitly uses non-identifying polygon Prince art with identity_art_approved=false.','Locate the recovered authoritative thin-Prince package and inspect context compatibility before preparing full-character party poses.','Preserve sincere conflicted story, scale and party-stage footing; no newly invented Prince.'),
'Candle-taking line arm':('CandleTakingArm is a separate thick Line2D attached to placeholder staging.','Replace only through whole-unit compatible King grasp/carry poses with actual candle contact; do not author an independent limb-only substitute.','Hand grips the one candle; body/arm/costume continuity moves together.'),
'Garden common sprout':('Current source has smooth flat pastel leaf masses/angular contour and separate soil oval.','Derive a painted rooted sprout from this garden seed/soil context with rounded leaves; its states lead coherently into all five distinct flowers.','Stem/roots stay anchored at the existing slot bottom through growth.'),
'Garden watering can':('RGBA 272x286 can is a low-resolution rough painted-cutout/material candidate. Hidden scene RGB under alpha zero does not prove visible contamination; current fringe/context review is pending.','Inspect the existing valid-alpha can at its actual 130x137 display size and spout contact. Reuse it if fit is adequate; choose a suitable whole painted tool or named material/detail gap only if current visible review fails.','Can spout points at plant/soil and water contacts the actual bed; real handle-hole alpha.'),
'Flat leaf-mass bush':('Source image has smooth cel-like leaf masses; vector origin is unknown.','Trace actual current consumer and retain any accepted scope. Seek specifically needs high-grade tree/bush family under DL-VIS-09; reuse accepted appropriate foliage first.','Root/ground contact and hide/reveal occlusion belong to the activity, never a second bush over baked art.'),
'Belt target cue (painted belt retained)':('Belt uses painted texture; the helper adds target cue primitives.','Retain painted belt, disposition target cue via _draw_target at the actual belt endpoint. No belt redraw gap is established.','Cue hugs actual earned belt/selection region and does not cover actor.'),
'Paper/shell panel fill and border':('StorybookUI.panel_style returns a flat fill/border StyleBoxFlat.','Use inspected paper/shell material or bounded authored NinePatch for the same content margins, normal depth and screen-plane UI role.','Frame supports content without covering pictures; touch/focus geometry remains unchanged.'),
'Button normal/hover/pressed/focus/disabled material':('style_button creates states through flat material helpers.','Define one context-fitting authored material per button kind and explicit normal/pressed/focus/disabled states; keep same generous targets and cancellation.','Button picture and input own one region; authored rim cannot steal touch or hide content.'),
'Picture-choice card normal/pressed/focus material':('style_picture_button creates flat picture-card state material.','Retain source pictures and apply appropriate quiet painted card/frame states, preserving content margins and the same direct choice.','Frame stays beneath picture; selected/focus state readable at phone size.'),
'Saved logo symbol and color marks':('Child-authored marks are vector-rendered saved content; no disposable weakness is established from their method.','Preserve exact saved mark/color and registered banner/badge ownership. Only surrounding backing/UI material is a replacement candidate.','The chosen mark appears once on each registered banner, without generic duplicate. Do not erase or reinterpret child art.')
}
asset_reviews={}
for obs in rootobs+garden:
    for path in obs.get('sources',obs.get('paths',[])):
        if path.startswith('assets/'):
            asset_reviews.setdefault(path,[]).append({'observation_id':obs['id'],'evidence':obs.get('evidence'),'observation':obs.get('observed',obs.get('weakness')),'reference':'context_review_observations.json' if obs in rootobs else 'garden_context_review.json'})
new=[]
for row in piece['pieces']:
    parent=parents[row['family']];name=row['name'];path=row['source']['path'];fn=row['source']['function']
    family=row['family'];route_refs=[]
    if family.startswith('opera_') and family[6:] in careers:
        c=careers[family[6:]];route_refs=['opera.act.%02d'%c['save_bit']];route=c['route'];action='; '.join(p['name'] for p in c['phases'])
    elif family=='opera_shared':route_refs=['opera.act.%02d'%c['save_bit'] for c in coverage['live_opera_careers']];route='Shared Opera consumers across the 15 live career routes; each drawing guard/phase and exact object visibility must still be traced';action=name+' actual career phase/rest/action/contact/payoff; normal and missing-texture paths'
    elif family=='child_authored':route_refs=['ui.logo','game.logo_studio'];route='Castle banner maker and logo studio, including saved/reopened child designs';action='Child creation, selection, save and reopen; preserve all authored content and semantic state'
    elif family=='shared_ambience':route_refs=[r['id'] for r in coverage['entries'] if not r['id'].startswith(('ui.','game.','standalone.'))];route='LivingWorldCatalog stage-local routing; resolve which named motif row is visible for this design';action='Quiet idle/passive stage accent, never activity credit'
    elif family=='castle_rooms':room=name.split(':',1)[0].lower().replace(' ','_');route_refs=['castle.room.'+room];route='Castle room '+room+' current plate/fixture-rig route';action='Arrival/free play/dirty or clean state and doorway/fixture interaction'
    elif family=='day_one':route_refs=['castle.room.'+r for r in ['main_hall','bubble_bath','playroom','craft_room']];route='Day One dirty-state dressing and exterior; exact affected room guard/owner dirt scope still unbound';action='Room arrival/actual cleaning contact/dirt reduction/clean payoff; Pool repaired exclusion retained'
    elif family=='literal_svg':
        career='teacher' if 'teacher' in path else 'geologist';c=careers[career];route_refs=['opera.act.%02d'%c['save_bit']];route=c['route'];action='Exact catalog presentation/phase and specialist direct texture consumer; crest is Castle route-card icon'
    else:route='Current '+family+' consumer from '+path+':'+str(row['source']['start_line'] or 'asset')+' ('+fn+')';action=name+' active/rest/changed/payoff/settle states';route_refs=[r['id'] for r in coverage['entries'] if family.replace('picture_','') in r['id'] or (family=='shared_ui' and r['id'].startswith('ui.'))]
    if name in specific:obs,proposal,support=specific[name]
    elif name.startswith('Garden mature result'):
        n=name.rsplit(' ',1)[1];obs='Distinct current garden outcome '+n+' remains flat-look candidate; flower.png was directly inspected, other states retain dated evidence until source review.';proposal='For outcome '+n+', inspect its own native source and five-slot planted context, then produce this one distinguishable mature plant from the same rooted sprout/palette/scale family. Preserve its exact outcome/slot mapping; no duplicate flower substituted across two identities.';support='Stem/root bottom matches common sprout and actual planted soil; petals remain inside its current 228px slot without crowding neighbours.'
    elif family=='castle_rooms':obs='Flat shell language in '+name+' contrasts with painted furniture in source/historical context; current tile path and pixel region still require measurement.';proposal='For '+name+', preserve this room perspective, architectural silhouette/geometry and current furniture sources; derive a calm painted material at the existing native-master resolution and slice only after unique plate/card ownership is reviewed.';support='Same wall/floor/window contact and occlusion as existing room; independent furniture remains once, never painted twice.'
    elif 'fallback' in name.lower():obs='Flat fallback implementation is present in '+fn+'; normal-path visibility is unproven.';proposal='Prove which guard can render '+name+' on its current route. Retain accepted painted inputs; retire this flat recovery path after exact resource/export/lifecycle proof, or record its specific missing authored state.';support='Use existing support/socket transform from this function; no new object or geometry is authorized by fallback presence.'
    else:obs='Source-bound candidate '+name+' uses or delegates visible primitive/material construction in '+fn+'. No current phone-context quality verdict is claimed.';proposal='Review '+name+' during '+action+' on '+route+'. Preserve approved painted inputs. For its visible flat part, first inspect exact-purpose existing art; then author only this context-bound role/state with the same geometry, material and action, or remove a redundant decorative layer.';support='Measure '+name+' own support/contact/socket and occlusion from current captures and this source scope before production; preserve that relation through every changed state.'
    row['observed_weakness']=obs;row['proposed_update']=proposal;row['route_refs']=route_refs;row['route_evidence']=route;row['context_action']=action;row['source_image_reviews']=asset_reviews.get(path,[])
    # Follow drawing/material helpers so zero-direct-call wrappers are not falsely discarded.
    if Path(path).suffix=='.gd':
        lines=(R/path).read_text(encoding='utf8').splitlines();body='\n'.join(lines[(row['source']['start_line'] or 1)-1:row['source']['end_line']])
        helper_names=set(re.findall(r'\b(_draw_\w+|panel_style|_button_style)\(',body))
        helpers=[s['id'] for s in scopes if s['path']==path and s['scope'].split('.')[-1] in helper_names]
        row['source_scope_ids']=sorted(set(row['source_scope_ids']+helpers))
    brief={'id':'PIECE-'+row['id'],'piece_id':row['id'],'parent_brief_id':parent['id'],'name':name,'scene_route':route,'route_refs':route_refs,'action_state':action,'proposed_update':proposal,'palette':parent['palette'],'material':parent['material'],'lighting':parent['lighting'],'scale_perspective':parent['perspective_scale'],'support_contact_occlusion':support,'geometry':row['screen_coverage'],'required_states':'Capture '+name+' entry/rest, actual action/contact, changed state, payoff/settle and all variant/fallback states before replacement; animation/seam review when this role moves. Preserve its exact current action in '+action,'reuse_candidates':row['reuse_candidates'],'named_gap':row['named_gap'],'unchanged_contracts':row['unchanged_contracts'],'output_layer':row['replacement_output'],'missing_evidence':['Current Mobile exact-source route and per-piece visible bounds','Exact-purpose reuse/identity/alpha/license check','Device/child/owner acceptance after integration'],'authoring_scope':'Owner commissioned replacement mission; this initial packet audits/plans and makes no runtime/pixel change. Existing exact-art acceptance gates remain; no additional routine permission checkpoint.'}
    new.append(brief);row['individual_brief_id']=brief['id']
# Root notes and visual sheet review are source/historical evidence, never current acceptance.
for row in piece['pieces']:
    if row['name'] in {'Garden common sprout','Garden watering can','Garden mature result 2','Flat leaf-mass bush'}:row['evidence_level']='LOCAL_SOURCE_VISUALLY_INSPECTED; CURRENT_CONTEXT_GAP'
save('per_piece.json',piece);save('per_piece_briefs.json',{'schema':'reef.flat_vector_individual_briefs/1','baseline':piece['baseline'],'briefs':new,'note':'One brief per named design; unknown visible bounds/contact or uninspected states stay blocking. Family palette/output rules are inherited but each route, action and proposed update is piece-bound.'})
print('INDIVIDUAL_BRIEFS',len(new))
