from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');C=B/'assets_src/imagegen/candy_wrap_scene_context_v1_20261003';A=C/'attempt01';assert not A.exists();A.mkdir()
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-5081a4f0-9ef7-4e5b-8c72-329d3e05f2c2.png');shutil.copyfile(src,A/'native.png')
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
plan=read(C/'PLAN.json')
with Image.open(src) as im:dims=list(im.size);mode=im.mode;alpha=list(im.getchannel('A').getextrema()) if 'A' in im.getbands() else None
assert sha(src)==sha(A/'native.png')
write(A/'SOURCE.json',dict(attempt=1,method='builtin_imagegen_complete_scene_reference_compositing',original_path=str(src),native_path=(A/'native.png').relative_to(B).as_posix(),sha256=sha(src),dimensions=dims,mode=mode,alpha_extrema=alpha,prompt=plan['prompt'],prompt_sha256=plan['prompt_sha256'],references=[dict(path=x,sha256=sha(B/x)) for x in plan['references']],native_preserved=True,runtime_ready=False,runtime_bound=False,owner_acceptance=None,qualification='Complete flattened reference-study starting scene, not a cinematic accepted frame or new runtime background.'))
opinions=[
 ('Character/costume and painted identity',4.5,'Same teal shell cap, coral bows, brown/rainbow hair, face and waistcoat remain recognizable in a complete painted scene.'),
 ('Exactly two connected owned mittens',4.5,'Both coral quilted mittens visibly connect through bent sleeves to Roshan; no outside human arm is present in this starting still.'),
 ('Partial-fold grasp and attached gold sheet',4.5,'The left mitten holds the lower flap edge over the same supported red oval; the right braces the near/right paper. This is a partial starting state, not closure.'),
 ('Same supported foreground task',4.5,'One central red sweet rests on the gold sheet and lavender worktop; the central work relationship is legible.'),
 ('Attention to the task',4.5,'The head and large eyes incline toward the foreground work area; a continuous attention beat remains unproved.'),
 ('Foreground clutter and target singularity',3.8,'New left jar/red-sweet bowl and right candy bowl/utensil pot compete with the intended one working sweet. They violate the requested clean foreground.'),
 ('Room/table context and material',4.4,'The established candy-factory painting supplies natural room context, but bright machinery and newly added foreground clusters compete with contact.'),
 ('Whole contextual starting source',4.2,'Rejected for added foreground props and competing sweets. Exact two-hand source topology cannot average away the scene hierarchy failure. No local motion admitted yet.')]
write(A/'DIRECT_REVIEW.json',dict(status='REJECTED_ADDED_FOREGROUND_SWEETS_AND_TOOL_CLUTTER',reviewed_utc=now(),direct_complete_native_review=True,native_sha256=sha(src),whole_source_score=4.2,opinions=[dict(item=i,score=s,evaluation=e,priority=s<=4.5) for i,s,e in opinions],qualification='Complete native directly inspected; unbound contextual source4.2 rejected. Preserve the original while removing only the unwanted foreground additions. No runtime, motion, cinematic, device/child/owner acceptance.',runtime_bound=False,owner_acceptance=None))
prompt='''Use case: precise-object-edit
Image1 is the full painted Candy Maker scene to repair. Preserve Roshan’s entire exact face/hat/hair/rainbow/costume/body, her TWO connected coral oven mittens and forearms, their current gold-flap grasp, the single central red sweet and attached gold paper, the lavender tabletop, camera and the existing candy-factory background.
Remove ONLY the unwanted foreground side props: the large cropped glass candy jar and the bowl of red sweets at lower left; the bowl of colorful sweets at lower right; and the cropped utensil pot with its spatulas at the right edge. Replace each removed foreground area with the natural continuation of the SAME lavender table surface and its painted front edge. Keep the room painting behind this table exactly coherent; do not insert new decorations or objects.
The clean foreground now contains ONLY the two owned mitten hands, ONE central red sweet, ONE attached golden-paper sheet/flap and the existing lavender worktop. Preserve the partial-fold starting state with the red crescent still visible; do not finish the wrapper, tie necks, twist ends or change the hands. Do not add another sweet, jar, bowl, tool, hand, finger, character, sparkle, text or HUD.
Return the ENTIRE same complete flattened landscape16:9 scene with painted2D storybook materials and clean contours. No crop, cutout, blank/neutral field, poster frame, photorealistic3D or new scene. The only repair is removing the competing foreground additions.'''
write(C/'PLAN_A2.json',dict(status='TARGETED_REMOVE_COMPETING_FOREGROUND_ADDITIONS_PLANNED',planned_utc=now(),attempt=2,source_path=(A/'native.png').relative_to(B).as_posix(),source_sha256=sha(A/'native.png'),source_rejection='Complete scene4.2; foreground competition3.8.',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),runtime_bound=False,owner_acceptance=None))
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();path=(A/'native.png').relative_to(B).as_posix();assert ('| `'+path+'` |').encode() not in raw;raw+=('\n| `'+path+'` | Builtin ImageGen complete contextual Candy starting scene | Original generated project artwork with OpenAI; existing character/wrapper/backdrop source attribution retained | SOURCE.json records exact prompt/reference/native hashes | Full native preserved; competing foreground additions rejected4.2, no production/cinematic/motion/owner acceptance. |\n').encode();n=licenses.with_name(licenses.name+'.v575_next');n.write_bytes(raw);n.replace(licenses)
shutil.copyfile(__file__,C/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-painted-context-source-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in C.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'][-1].update(result='FAIL',evidence=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix()+'; whole4.2 rejected for foreground additions.');d['validation'].append(dict(command='Targeted A2 foreground cleanup with original hands/paper/source context preserved',result='PENDING',evidence='PLAN_A2.json; no predicted source or motion acceptance.'));write(ip,d)
print(json.dumps(dict(status='CONTEXT_A1_4_2_REJECTION_PRESERVED_A2_CLEANUP_PLANNED',dimensions=dims,mode=mode,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())))
