from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');C=B/'assets_src/imagegen/candy_wrap_scene_context_v1_20261003';assert not C.exists();C.mkdir(parents=True);(C/'review_tools').mkdir()
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
base=subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip();assert base=='2b109a233c14050567aaa84dc975119b2e18a77e'
pose='assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt13/native.png';bg='assets/opera/worlds/backdrops/world_candymaker.png';prior=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003'
inventory=[]
for path,role,score,note in [(pose,'existing_partial_fold_identity_and_specific_wrapper',4.5,'Complete partial-fold source, two connected coral mittens and one supported red oval under attached golden paper. No motion pass.'),(bg,'existing_candy_room_appearance_context',4.2,'Current painted candy factory; visually busy at source. Reuse scene identity as context reference, not a new background source acceptance.'),('assets/flats/castle/interactions_v4/background_tiles/room_kitchen_background_r0_c1.png','alternative_shared_room_style',4.6,'Calm painted Kitchen tile; does not by itself depict the complete Candy backdrop or hands. Not bound to this generation.'),((prior/'comparison_a4/inputs/CANDY-FOLD-A4.png').relative_to(B).as_posix(),'previous_failed_neutral_field_input',None,'Same neutral-field whole pose causes external-hand/body-distortion failure; preserve, do not reuse as the new context target.')]:
 p=B/path
 with Image.open(p) as im:dims=list(im.size)
 inventory.append(dict(path=path,sha256=sha(p),dimensions=dims,role=role,source_score=score,evaluation=note,direct_existing_source_review=True))
prompt='''Use case: compositing / illustration-story
Create ONE new complete flattened painted2D storybook scene, landscape16:9, for a local hand-action reference study. Image1 is the exact established Candy Maker character, costume, two coral quilted oven mittens, lavender worktop, red oval sweet and attached crinkled GOLD PAPER design. Image2 is the existing candy-factory room appearance. Preserve their identity and painted style; this is a clean scene with no game HUD.
Place the same complete waist-up Roshan naturally behind the same broad lavender worktop, large and clearly visible in the foreground of the existing pastel candy factory. Her whole head, hat, brown hair/rainbow ribbon, face, sleeves and BOTH arms/hands must be visible. Exactly two coral oven mittens, both continuously connected to her own bent forearms; no other person, external hand or bare human fingers. Her eyes attend to the gold flap and supported sweet.
Preserve the useful PARTIAL-FOLD starting action: one red oval sweet rests at the center of the same gold sheet on the worktop. The gold far flap is attached to that same underlying sheet and already lies across the upper part of the sweet, leaving a clear red crescent at the front. Her screen-left mitten visibly grasps the free lower edge of this attached flap between its palm and thumb, directly over the sweet. Her screen-right mitten braces the near/right side of the sweet and paper on the table. The gold flap is NOT yet fully closed; do not tie necks or twist ends yet. Show the paper, hand contact and remaining red crescent clearly at useful large foreground scale.
Use the existing room’s painted pastel aqua, lavender and coral architecture behind her, with its established rounded machines/shell trim. Keep distant details quieter than her face/hands/one working sweet. Her table sits naturally in this room; no neutral white field, poster, page, frame or artist drawing the character. Locked ordinary three-quarter table-work view, not a camera looking at a printed illustration. Broad painted satin value bands, clean plum contours, rounded child-readable shapes, restrained gold paper creases; no photorealism, realistic3D, PBR noise, vector-flat placeholders or white sticker rim.
Return the entire landscape scene with full character head/arms/worktop and generous clear margins. No labels/text/UI, no additional foreground sweet, duplicate arm/glove, magic particle effect or detached prop. This is one new complete starting still, not animation or runtime/owner acceptance.'''
write(C/'PLAN.json',dict(status='NEW_COMPLETE_PAINTED_CONTEXT_SOURCE_PLANNED_REFERENCE_ONLY',planned_utc=now(),baseline=base,profile='design/animation/ROSHAN_MOVEMENT_LANGUAGE.md',scope='One whole ImageGen scene source for a materially different context-framing experiment after A3/A4 extra-hand failures. Preserve established character/mitten/sweet/gold-paper identity; no game or cinematic delivery.',reuse_inventory=inventory,references=[pose,bg],prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),prior_failures=[dict(path=(prior/'comparison_a3/attempt01/DIRECT_REVIEW.json').relative_to(B).as_posix(),component_score=1.5),dict(path=(prior/'comparison_a4/attempt01/DIRECT_REVIEW.json').relative_to(B).as_posix(),component_score=0.8)],inference='The neutral-field pose may be read as an illustration manipulated by outside hands. Causal interpretation is unproven.',comparison_limits='Full-frame regeneration changes background context and can change source geometry/framing. This is an observational source-context comparison, not an isolated-variable pixel experiment or proof of causality.',required_evidence=['Whole returned native/alpha-or-RGB/dimensions/hash and exact prompt/reference provenance','Direct scene identity/exact-two-owned-mittens/grasp/attached paper/sweet support/style audit','Only then admit one quiet-idle developed local reference render at the same validated896x512/41frames/24fps/24steps/seed settings','All41 native frames/components reviewed independently; no static-score transfer or final cinematic delivery'],runtime_bound=False,owner_acceptance=None))
write(C/'PRIOR_CLIP_ENTRY_LABEL_LIMITATION.json',dict(status='INHERITED_ENTRY_LABEL_IS_NOT_ACTUAL_SOURCE_AUTHORITY',recorded_utc=now(),prior_manifest=(prior/'comparison_a4/MANIFEST.json').relative_to(B).as_posix(),declared_entry=read(prior/'comparison_a4/MANIFEST.json')['clip_contract']['entry'],actual_bound_source=pose,actual_bound_sha256=sha(B/pose),qualification='The old clip entry label still names A11 although the exact source/input and first native frames bind the A13 partial fold. Preserve historical manifest bytes; do not transfer this label to a new contract. Existing native reviews judged the actual partial-fold frames and remain rejected.'))
shutil.copyfile(__file__,C/'review_tools'/Path(__file__).name)
write(B/'design/audit_impacts/job-candy-painted-context-source-20261003.json',dict(id='job-candy-painted-context-source-20261003',scope='One reversible complete painted scene source and then a separately audited local reference-only far-fold study. Inventory and preserve actual source identity, current backdrop, rejected neutral-mat attempts and stale inherited entry label. No runtime or cinematic binding.',baseline=base,rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-04','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-READ-01','DL-READ-02','DL-READ-03','DL-MOT-01','DL-MOT-03','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-03','DL-QA-07'],findings=['MA-VIS-006','MA-PLAY-004'],files=[p.relative_to(B).as_posix() for p in C.rglob('*') if p.is_file()],validation=[dict(command='Existing pose/background/alternative/failed input reuse inventory and exact prior source-label check',result='PASS',evidence=(C/'PLAN.json').relative_to(B).as_posix()+' and PRIOR_CLIP_ENTRY_LABEL_LIMITATION.json; framing diagnosis remains an inference.'),dict(command='New complete scene native and direct identity/contact/style review',result='PENDING',evidence='No predicted score or source-to-motion/runtime acceptance.')],acceptance_gaps='Current in-game WRAP2.8; complete fold/neck pinch/opposing twist/release, ordinary game/input/interruption, all-job/source-cell/use coverage, device/child/owner/comprehensive report acceptance remain open. New full scene is reference-only, not a replacement multi-screen background or cinematic frame.'))
print(json.dumps(dict(status='PAINTED_CONTEXT_REUSE_GAP_AND_SOURCE_PLAN_SAVED',baseline=base,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())))
