from pathlib import Path
import copy,datetime,hashlib,json,shutil,subprocess

B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003';C=B/'assets_src/imagegen/candy_wrap_scene_context_v1_20261003';L=B/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):n=p.with_name(p.name+'.v582_next');n.write_bytes(raw);n.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())

# Keep the actually executed source-gallery helper and disclose the later anchor-only edit.
write(C/'SOURCE_REPORT_ANCHOR_EDIT_V582.json',dict(status='TWO_STABLE_HTML_ARTICLE_ANCHORS_ADDED',changed_file=(C/'index.html').relative_to(B).as_posix(),anchors=['attempt-1','attempt-2'],qualification='Report navigation edit after the executed v576/v577 helpers; artwork and individual opinions unchanged. Browser screenshot observes the saved final source page.'))
old=(P/'review_tools/build_candy_local_review_v565.py').read_text(encoding='utf-8')
old=old.replace("job-candy-shared-library-continuation-20261003.json","job-candy-painted-context-source-20261003.json")
needle="('a4','A4: prompt-only partial far-fold reference',P/'comparison_a4')]"
assert needle in old
old=old.replace(needle,"('a4','A4: prompt-only partial far-fold reference',P/'comparison_a4'),('a5','A5: complete painted scene far-fold reference',P/'comparison_a5'),('a6','A6: prompt-only downward covering fold',P/'comparison_a6')]")
old=old.replace("rel(packet/'inputs/CANDY-FOLD-A2.png')","rel(packet/read(packet/'MANIFEST.json')['input_path'])")
old=old.replace('Complete neck grip, opposing twist, release and runtime acceptance remain open.','A5 contextual far-fold3.1 fails by lifting the flap away; its two owned hands improve separately. A6 prompt-only downward covering fold is separately reviewed when its native results are available. Complete neck grip, opposing twist, release and runtime acceptance remain open.')
needle="body='<!doctype html>"
assert needle in old
old=old.replace(needle,"sources+='<div class=\"source\"><h2>Clean full painted context source · starting still4.5 provisional</h2><img src=\"../../imagegen/candy_wrap_scene_context_v1_20261003/attempt02/native.png\" width=\"1672\" height=\"941\" alt=\"Complete preserved clean painted room and partial golden-paper fold\"><p>Exactly two owned mittens and one working sweet. Source-only4.5; background4.4 remains a priority. A5 action3.1 is independently rejected. No full-wrapper or runtime pass.</p><a href=\"../../imagegen/candy_wrap_scene_context_v1_20261003/index.html\">Both complete source originals and16 individual written opinions</a></div>'\n"+needle)
old=old.replace("root=", "root=")
builder=P/'review_tools/build_candy_local_review_v582.py';builder.write_text(old,encoding='utf-8',newline='\n')

for name,target in [('ALL_ITEMS.json','ALL_ITEMS_V48.original.json'),('all_items.html','all_items_V48.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V48.original.json')]:
    assert not (L/target).exists();shutil.copyfile(L/name,L/target)
reg=read(L/'ALL_ITEMS.json');assert reg['display_revision']=='V48' and len(reg['items'])==2047
tmpl=next(x for x in reg['items'] if x['id']=='CANDY-M-SOURCE-13')
for i in [1,2]:
    a=C/f'attempt{i:02d}';s=read(a/'SOURCE.json');r=read(a/'DIRECT_REVIEW.json');z=copy.deepcopy(tmpl)
    for key in ['region','parent_source_id','label','latest_refinement']:z.pop(key,None)
    z.update(id=f'CANDY-CONTEXT-SOURCE-{i:02d}',aliases=[f'CANDY-CONTEXT-SOURCE-{i:02d}'],kind='source',path=s['native_path'],earlier_sha256=s['sha256'],current_checkout_sha256=s['sha256'],historical_source_score=None,current_source_score=r['whole_source_score'],evaluation=r['opinions'][-1]['evaluation'],refinement='A1 competing foreground additions rejected4.2 and preserved. A2 is only a partial-fold starting still4.5; local motion must independently cover and release this specific gold paper before any authored gameplay replacement.',families=['Day Two','Candy Maker','Unbound contextual wrapper sources'],original_reports=[C.relative_to(B).as_posix()+'/index.html'],source_qualification=r['qualification'],preview_path=s['native_path'],image_path=s['native_path'],image_scope='Complete preserved painted scene starting source; no motion/runtime/cinematic acceptance',native_reference_observations=[],current_byte_status='EXACT_REVIEWED_GENERATION_BYTES',source_dimensions=s['dimensions'],priority=True,protected_original=False,current_mounted_score=None,current_complete_action_score=None,individual_review_utc=r['reviewed_utc'],latest_refinement=dict(report=C.relative_to(B).as_posix()+'/index.html#attempt-'+str(i),note=r['qualification']))
    reg['items'].append(z)
pri=[x for x in reg['items'] if x.get('current_source_score') is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3']];unique={x['path'] for x in pri if x['kind'] in ['source','runtime source']};pending=[x for x in reg['items'] if x['kind']=='source' and x.get('current_source_score') is None]
assert len(reg['items'])==2049 and len(pri)==952 and len(unique)==663 and len(pending)==294
reg['counts'].update(unique_source_files=1285,registered_items=2049,inclusive_current_source_priorities=952,unique_source_file_priorities=663,unreviewed_current_source=294,new_candy_context_sources=2)
reg.update(display_revision='V49',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v49.py',scope='V49:2049 known entries/1285 primary sources/328 pose cells/151 runtime-use-action entries/285 source object regions.952 inclusive source-cell-region priorities/663 unique source-file priorities/294 unreviewed primary sources. Two complete painted Candy context natives/16 opinions preserve cluttered A1 source4.2 rejection and clean A2 starting still4.5 provisional, background4.4. Every205 A1-A5 local motion frame and50 components reviewed; A5 hand ownership4.5 but whole far-fold3.1 rejected for reverse lift, no cover or release. A6 one prompt-only direction comparison remains separately audited. Current WRAP2.8 and all783 production members unchanged. No complete source-cell/use/action/all-job/owner/integration/release acceptance.')
reg['current_byte_status_counts']['EXACT_REVIEWED_GENERATION_BYTES']+=2
reg['review_resources'].append(dict(path=C.relative_to(B).as_posix()+'/index.html',scope='Two complete context sources/16 individual opinions. Clean source4.5 provisional, independently failed A5 action3.1; A6 pending its own review.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304
shutil.copyfile(L/'review_tools/refresh_current_job_review_v48.py',L/'review_tools/refresh_current_job_review_v49.py')
notice='<p class="current-context-review"><a href="../../assets_src/imagegen/candy_wrap_scene_context_v1_20261003/index.html">Current Candy context source review: both original paintings and16 evaluations</a> · Clean starting still4.5 provisional; A5 hand ownership4.5/whole far-fold3.1 rejected. A6 direction comparison is separate. <strong>V49:2049 known entries/952 inclusive source-cell-region priorities/663 unique source priorities/294 primary sources still unreviewed.</strong> Current in-game WRAP2.8; source, action and owner acceptance remain separate.</p>'
for name in ['index.html','all_items.html']:
    p=L/name;t=p.read_text(encoding='utf-8').replace('refresh_current_job_review_v48.py','refresh_current_job_review_v49.py');t=t.replace('<h1>',notice+'<h1>',1);put(p,t.encode())

note='Candy context continuation (2026-10-03): [two complete painted scene sources and16 individual opinions](CONTEXT) preserve A1 clutter rejection4.2 and clean A2 starting still4.5 provisional, background4.4. [Every205 A1-A5 local native frames/35 original-size boards/16 native details/50 component opinions](MOTION) directly reviewed; A5 owned hands4.5 improve separately but the flap lifts away, whole far-fold3.1 rejected. One A6 prompt-only downward covering comparison keeps the exact source/input/seed/settings/developed workflow; its own native/action review remains separate. V49 known2049 entries/1285 primary sources/952 source-cell-region priorities/663 unique source priorities/294 unreviewed primary sources. Exact X all23846 anonymous remote bytes verified; exact X hosted status remains separately recorded. Current game WRAP2.8/all783 production members unchanged. Full wrapper/source-cell/use/action/device/child/owner/all-job/comprehensive report, finding lifecycle, integration and release remain open.'
for path,context,motion in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/imagegen/candy_wrap_scene_context_v1_20261003/index.html','../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/imagegen/candy_wrap_scene_context_v1_20261003/index.html','../../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html'),('audit/animation/README.md','../../assets_src/imagegen/candy_wrap_scene_context_v1_20261003/index.html','../../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html')]:
    p=B/path;t=p.read_text(encoding='utf-8');s=note.replace('CONTEXT',context).replace('MOTION',motion)
    if path.endswith('MASTER_AUDIT_2026-08-09.md'):
        for marker in ['## 0. Planning entry','### Development task index']:assert marker in t;t=t.replace(marker,marker+'\n\n'+s,1)
    else:i=t.index('\n')+1;t=t[:i]+'\n'+s+'\n'+t[i:]
    put(p,t.encode())
ledger=B/'design/05_DOC_LEDGER.md';t=ledger.read_text(encoding='utf-8');t+='\n| `assets_src/imagegen/candy_wrap_scene_context_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; two complete painted scene natives/16 source opinions preserve clutter4.2 rejection and clean4.5 partial-fold starting still, background4.4. A5 every41 native frames/10 components rejected3.1; A6 independent direction review separate. No game/cinematic/device/child/owner acceptance. |\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V48.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact2047-entry register before two new complete painted Candy context source opinions. |\n';put(ledger,t.encode())
shutil.copyfile(__file__,C/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-painted-context-source-20261003.json';d=read(ip)
d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in C.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS.json','index.html','all_items.html','CURRENT_BOUNDARY_REFRESH.json','ALL_ITEMS_V48.original.json','all_items_V48.original.html','BOUNDARY_V48.original.json','review_tools/refresh_current_job_review_v49.py']}|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md','design/05_DOC_LEDGER.md',builder.relative_to(B).as_posix(),'ASSET_LICENSES.md'})
write(ip,d)
cmd=['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(builder)];r=subprocess.run(cmd,cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);assert r.returncode==0,r.stderr.decode();print(r.stdout.decode().strip())
cmd=['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v49.py')];r=subprocess.run(cmd,cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);assert r.returncode==0,r.stderr.decode();print(r.stdout.decode().strip());assert read(L/'CURRENT_BOUNDARY_REFRESH.json')['registered_source_matches']==2049
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();path=(C/'BROWSER_SOURCE_REPORT_V578.jpg').relative_to(B).as_posix()
if ('| `'+path+'` |').encode() not in raw:raw+=('\n| `'+path+'` | Actual local browser screenshot of the clean Candy source review | Original project review layout and inherited displayed artwork provenance | BROWSER_VERIFY_V578.json binds exact screenshot and observed loaded sources/opinions | QA proof only, not production/cinematic pixels or owner acceptance. |\n').encode();put(licenses,raw)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for base in(C,P) for p in base.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for p in L.iterdir() if p.is_file()}))
print(json.dumps(dict(status='V49_TWO_CONTEXT_SOURCES_REGISTERED_ALL205_A1_A5_FRAMES_ILLUSTRATED',register_bytes=(L/'ALL_ITEMS.json').stat().st_size,registered_items=2049,inclusive_priorities=952,unique_source_priorities=663,primary_unreviewed=294,production_candy_boundary_matches=True)))
