from pathlib import Path
import ast,json,shutil
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003';IP=B/'design/audit_impacts/job-candy-twist-release-pose-20261003.json'
s=(B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003/review_tools/publish_neck_review_v618.py').read_text(encoding='utf-8')
s=s.replace("C=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003'","C=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003'").replace('job-candy-neck-grip-pose-20261003.json','job-candy-twist-release-pose-20261003.json').replace("BASE='876169d77d45f5fd2b5956eeda4f1e6da9926f19'","BASE='930614f3e8ab0d89177409ba92a2dd28dc228d54'").replace("MAP='audit/job_review_v2_20261001/CANDY_SPECIFIC_GRIP_MOTION_FILES_V25.json'","MAP='audit/job_review_v2_20261001/CANDY_TWIST_RELEASE_ENDPOINT_FILES_V26.json'").replace("PRIOR='audit/job_review_v2_20261001/SHARED_PROP_CELL_REVIEW_FILES_V24.json'","PRIOR='audit/job_review_v2_20261001/CANDY_SPECIFIC_GRIP_MOTION_FILES_V25.json'").replace('v25_unchanged_dependency_shards','v26_unchanged_dependency_shards').replace('tmp/neck_publish_v618','tmp/endpoint_publish_v634').replace('tmp/neck_remote_v618','tmp/endpoint_remote_v634').replace('tmp/neck_sealed_v618','tmp/endpoint_sealed_v634').replace('v618_next','v634_next').replace('PUBLICATION_BOUNDARY_V618.json','PUBLICATION_BOUNDARY_V634.json').replace('EXACT_SHARDED_NECK_REVIEW_BYTES_SEALED','EXACT_SHARDED_ENDPOINT_REVIEW_BYTES_SEALED')
start=s.index('def checks():\n');end=s.index('\ndef run(',start)
checks='''def checks():
    assert git('rev-parse','HEAD').decode().strip()==BASE and git('branch','--show-current').decode().strip()==BRANCH
    for label in ['authority','development','document_tests','game2d','register_parts']:assert read(C/'gates_v1'/(label+'.receipt.json'))['status']=='PASS',label
    sys.path.insert(0,str(L/'review_tools'));from register_parts_v51 import load_register
    reg=load_register(L);assert reg['display_revision']=='V53' and len(reg['items'])==2152 and reg['counts']['inclusive_current_source_priorities']==1055 and reg['counts']['unique_source_file_priorities']==678 and reg['counts']['unreviewed_current_source']==294
    stamp=read(L/'CURRENT_BOUNDARY_REFRESH.json');assert stamp['registry_items']==stamp['registered_source_matches']==2152 and stamp['assembled_registry_parts_verified'] and stamp['registry_root_sha256']==sha((L/'ALL_ITEMS.json').read_bytes()) and stamp['registry_parts']==reg['item_shards']
    previous=read(C/'previous_v52/ALL_ITEMS.json');current=read(L/'ALL_ITEMS.json');assert current['items'][:2054]==previous['items'] and current['item_shards']==previous['item_shards']
    review=read(C/'REVIEW_SUMMARY.json');assert review['native_sources']==10 and review['individual_source_opinions']==123 and review['twist_source_score']==review['release_source_score']==4.5 and review['prior_motion_reference_component_score']==1.8 and not review['new_motion_dispatched'] and review['motion_score'] is None and not review['runtime_bound'] and review['owner_acceptance'] is None
    opinion_count=0
    for stage in ['twist','release']:
        for i in range(1,6):
            folder=C/f'{stage}_attempt{i:02d}';r=read(folder/'DIRECT_REVIEW.json');source=read(folder/'SOURCE.json');opinion_count+=len(r['components']);assert sha((folder/'native.png').read_bytes())==r['native_sha256']==source['native_sha256'] and r['motion_score'] is None and not r['runtime_bound'];assert sha((B/source['prompt_path']).read_bytes())==source['prompt_sha256'] and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in source['references'])
    assert opinion_count==123
    prior=read(C/'previous_AB_remote_verified/RESULT.json');assert prior['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and prior['files_including_manifest']==24487
    boundary=read(P/'PRODUCTION_BOUNDARY.json');assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members'])
'''
s=s[:start]+checks+s[end:];s=s.replace("C/'previous_AA_remote_verified/RESULT.json'","C/'previous_AB_remote_verified/RESULT.json'").replace('PENDING_EXACT_GRIP_REJECTED_MOTION_REVIEW_STAGED_SEAL','PENDING_EXACT_TEN_ENDPOINT_REVIEW_STAGED_SEAL').replace('PREPARED_EXACT_GRIP_REJECTED_MOTION_PUBLICATION_SCOPE','PREPARED_EXACT_TWIST_RELEASE_ENDPOINT_PUBLICATION_SCOPE')
s=s.replace("v['command']=='Final expanded source-review structural/document/2D no-regression/register gates'","v['command']=='Source-only review structural/document/2D no-regression/register gates'").replace("C.relative_to(B).as_posix()+'/gates_v2;actual final authority/development,52 document tests,9 register-integrity tests and2D no-regression all pass. Strict2D remains UNSATISFIED;visual/action/owner independent.'","C.relative_to(B).as_posix()+'/gates_v1;actual authority/development,52 document tests,9 register-integrity tests and2D no-regression pass. Strict2D remains UNSATISFIED;visual/action/owner independent.'")
oldline=next(x for x in s.splitlines() if 'manifest=dict(schema=' in x);assert "qualification='V52" in oldline
qualification='V53 known2152 entries/1300 primary sources/1055 inclusive source-cell-region priorities/678 unique source priorities/294 unreviewed primary sources. Ten same-scene built-in ImageGen twist/release endpoint candidates and123 individual source opinions;four failed twist and four failed release natives retained. TwistA5 and releaseA5 source endpoints4.5 provisional;inherited room4.4 remains separately weak. Corrected opposed hand endpoint contacts,short opposite flexible-paper twists,fan conservation and quiet fully disengaged release. Previous local motion1.8 rejected;no new motion dispatched,no animation/current game score transfer. Prior2054 register records/literal88-item part unchanged,existing4MiB ceiling retained,52 document tests/9 register integrity tests pass. Actual browser proof and all24487 prior AB anonymous remote rows preserved losslessly. All783 production literals/current WRAP2.8 unchanged. No runtime,protected-original,3D,security/gate/workflow,finding-lifecycle,dev/master integration/release or complete fold-cover-gather-opposite-twist-supported-release/actual jobs/Opera training/ordinary route/device/child/owner/comprehensive all-job acceptance.'
newline=oldline[:oldline.index("qualification='V52")]+"qualification="+repr(qualification)+')';s=s.replace(oldline,newline)
start=s.index("message=OUT/'COMMIT_MESSAGE.txt';");end=s.index("\nrun('commit'",start)
message='Rebuild specific gold-wrapper twist and supported release endpoints\n\nPreserve ten complete ImageGen candidates and123 individual source opinions. Four rejected twist and four rejected release originals remain available. TwistA5/releaseA5 source endpoints4.5 provisional:owned opposing contact poses,short opposite thin-paper winding,conserved outward fans and quiet fully disengaged hands. Inherited room4.4 remains a priority.\n\nExtend the bounded V53 illustrated library to2152 known entries/1055 inclusive priorities/678 unique priority sources/294 pending primary reviews,keeping2054 prior root records and the literal88-item part unchanged. Preserve actual full-native browser proof,52 document tests/9 register integrity tests and all24487 prior AB anonymous remote verification rows.\n\nNo new motion dispatched. Previous local component1.8 remains rejected and current in-game WRAP2.8/all783 production literals stay unchanged. Full fold-cover-gather-opposite-twist-supported-release,actual job/Opera training/device/child/owner/comprehensive all-job acceptance,integration and release remain open.\n'
s=s[:start]+"message=OUT/'COMMIT_MESSAGE.txt';message.write_text("+repr(message)+",encoding='utf-8',newline='\\n')"+s[end:]
ast.parse(s);p=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/publish_endpoint_review_v634.py');p.write_bytes(s.encode());shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
d=json.loads(IP.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()});t=IP.with_name(IP.name+'.v634_next');t.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n');t.replace(IP);print('EXACT_ENDPOINT_TOPIC_PUBLISHER_BUILT',flush=True)
