from pathlib import Path
import datetime, hashlib, json, shutil, subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
T=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003'
IP=B/'design/audit_impacts/job-candy-twist-release-pose-20261003.json'
BASE='930614f3e8ab0d89177409ba92a2dd28dc228d54'
sha=lambda raw:hashlib.sha256(raw).hexdigest()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
    t=p.with_name(p.name+'.v620_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip()==BASE
assert not T.exists() and not IP.exists()
source='assets_src/imagegen/candy_neck_grip_pose_v1_20261003/attempt04/native.png'
assert sha((B/source).read_bytes())=='f1ff6a5f1d46d7e1bb7a53af02da82355ba603514349edec817a6bf73dafda1c'
with Image.open(B/source) as im:assert im.size==(1672,941) and im.mode=='RGB'
reuse=[]
for path,reason in [(source,'Same-scene untwisted two-neck grip4.5. Reuse exact identity, gold-paper material, small covered sweet, fans and table. Not an opposite-wrist twist or release.'),('assets_src/imagegen/candy_cover_pose_v1_20261003/attempt01/native.png','Exact prior cover/press pose4.5; preserves preceding workflow but has no neck twists or release.'),('assets_src/imagegen/candy_wrap_scene_context_v1_20261003/attempt02/native.png','Earlier same-scene partial fold4.5; visible red crescent is correct only before coverage.'),('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt07/native.png','Older static contact atlas has already closed neck rings before twisting and different scene registration. Cannot supply honest exact-scene twist or release.'),('assets/opera/worlds/widgets/widget_crank_candymaker_mover.png','Current mounted turquoise decorative sweet differs from proposed gold-paper replacement; no transfer of source scores to the actual game.')]:
    assert (B/path).is_file();reuse.append(dict(path=path,sha256=sha((B/path).read_bytes()),reuse_evaluation=reason))
prior=read(B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003/local_motion_a1/REVIEW_STATUS.json')
boundary_path=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json'
boundary=read(boundary_path)
assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members'])
T.mkdir();(T/'review_tools').mkdir();(T/'twist_attempt01').mkdir()
prompt="""Use case: precise-object-edit
Image 1 is the edit target: the ENTIRE existing painted Candy Maker scene. Draw the next still in this same wrapping action. Preserve the exact face, head, hair, rainbow forelock, teal shell-trimmed cap, coral bows, teal-and-coral costume, cream sleeves, teal cuffs, lavender table, factory room, camera, character scale, and the ONE small opaque gold-covered oval sweet at the same supported table centre. Maintain the same polished painted storybook contours and broad gold value bands. No new scene, new costume or realism.
Change only the existing two wrists, coral quilted mittens and the two SHORT paper necks they grip. Show a real OPPOSING DOUBLE TWIST around the sweet's horizontal left-to-right axis: the screen-left wrist rolls its mitten toward the viewer while the screen-right wrist rolls its mitten away. Show these as visibly different rolled mitten orientations, still naturally joined to their original cuffs and sleeves. Exactly TWO rounded oven mittens with one thumb each, no bare fingers, extra hands or detached gloves.
Each mitten's thumb and palm STILL tightly pinch its own short gold neck immediately beside the covered oval. Each short neck now winds into a soft compact helical GOLD-PAPER twist under that grip. The two necks visibly wind in opposite directions. Keep them short and made from the same single flexible continuous wrapper; no added string, bands, rings, collars, knots or rigid pipes. The central sweet stays a small low oval, covered and supported in place, with its top seam retained. Never turn it into a bag or large tube.
Each loose GOLD FAN remains OUTSIDE its own neck grip, joined continuously through that short twisted neck to the covered centre. The fans turn with their paper ends; they do not attach to the cuffs, turn into sleeve wings, split off or become held separate objects. Keep both neck-to-body and neck-to-fan connections readable, both distinct hand contacts, and room between the two mittens. No exposed red, loose mat beneath the sweet, extra candy, new props, glow, motion blur, text, collage, crop or camera movement. One entire landscape still at the end of the opposing wrist twist, with both hands still gripping; the released pose comes later."""
(T/'twist_attempt01/SENT_PROMPT.txt').write_bytes(prompt.encode())
rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-04','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-INT-02','DL-INT-03','DL-INT-04','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-03','DL-QA-04','DL-QA-05','DL-QA-06','DL-QA-07']
ref=dict(path=source,sha256=sha((B/source).read_bytes()),role='exact_full_scene_untwisted_grip_identity_gold_material_support_and_registration')
write(T/'PLAN.json',dict(status='TWIST_ENDPOINT_PLANNED_RELEASE_DEPENDS_ON_ACCEPTED_TWIST',baseline=BASE,planned_utc=now(),prior_turn_classification='PROGRESS:four complete neck-grip candidates/44 opinions and all41 native motion frames/10 component opinions published. Exact AB remote publication24487/24487 PASS. Grip4.5; motion1.8 rejected; actual WRAP2.8 unchanged.',scope='Reversible ImageGen rebuilding of the missing opposing-wrist double-twist and supported two-hand release endpoints in the same specific gold-paper scene. Preserve every native and failed opinion. No production binding, Comfy dispatch, runtime score or owner acceptance from a still.',rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],profile='design/animation/ROSHAN_MOVEMENT_LANGUAGE.md',protocol='design/animation/ANIMATION_PRODUCTION_PROTOCOL.md',intention='Roshan concentrates on the same supported covered sweet, twists its two short gold-paper necks with opposite wrist rolls, then disengages both mittens and settles beside it.',emotional_register='Quiet concentrating Ribbon Glide work, no celebration or bounce.',reuse_inventory=reuse,references=[ref],generation_gap='No exact same-scene opposite wrist twist or released endpoint exists. The developed local motion study1.8 loses fan ownership and contact without completing the twist or release. Old pre-tied contact atlas cannot replace causal workflow.',prior_motion_review='assets_src/imagegen/candy_neck_grip_pose_v1_20261003/local_motion_a1/REVIEW_STATUS.json',prior_motion_review_sha256=sha((B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003/local_motion_a1/REVIEW_STATUS.json').read_bytes()),generation_method='built_in_imagegen_precise_object_edit',required_evidence=['Full native RGB dimensions/hash and exact prompt/reference hashes for each attempt','Direct individual opinions for two owned mittens, BOTH short neck contacts, differing opposite wrist orientations relative to preceding grip, continuous single gold paper, each fan ownership, opaque small oval/support, scene/identity/material, and release only when actually shown','Refine named defects; retain every rejected native; source floor4.5 is provisional and inclusive4.5 priorities remain in the library','No new local motion until both endpoint sources pass the source bar; a motion study must preserve exact submitted manifest and expose all native frames/component opinions','Full partial fold to cover to gather to opposite twists to supported release chronology remains required in actual game and Opera training, not granted by two endpoint stills','Current bounded known-item library, source-bound browser proofs, applicable gates, lossless prior exact-head remote receipts and topic-branch publication'],attempts=[],twist_source_score=None,release_source_score=None,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None))
write(T/'twist_attempt01/PLAN.json',dict(status='PLANNED_NOT_GENERATED',references=[ref],prompt_sha256=sha(prompt.encode()),runtime_bound=False))
write(T/'PRODUCTION_BOUNDARY_BEFORE.json',dict(status='ALL783_CURRENT_LITERAL_PRODUCTION_MEMBERS_UNCHANGED',checked_utc=now(),source_boundary=boundary_path.relative_to(B).as_posix(),boundary_sha256=sha(boundary_path.read_bytes()),members=783,qualification='No production delta; no new runtime or visual acceptance.'))
shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
write(IP,dict(id='job-candy-twist-release-pose-20261003',scope='Reversible same-scene ImageGen opposite-wrist double-twist and supported release endpoint repair. Preserve specific gold wrapper, character, ownership and support; full workflow/all-jobs objective remains open. No production binding or finding closure.',baseline=BASE,rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],files=sorted(p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()),validation=[dict(command='Specific source reuse inventory/current production boundary',result='PASS',evidence='assets_src/imagegen/candy_twist_release_pose_v1_20261003/PLAN.json and PRODUCTION_BOUNDARY_BEFORE.json; no matching twist/release exists,all783 production literals unchanged.'),dict(command='Native endpoint generations and individual direct opinions',result='PENDING',evidence='twist_attempt01/SENT_PROMPT.txt; no output or score yet. Release depends on accepted twist.'),dict(command='Library/browser/document/no-regression gates and exact topic publication',result='PENDING',evidence='Current V52/2142 known entries preserved before new sources. No predicted gate outcome.')],acceptance_gaps='Full supported fold/cover/gather/opposite-twist/release motion; actual story job/Opera training/current WRAP2.8;294 pending Day One primary source opinions; other weak game/training/ordinary-route actions; inherited room4.4; device/child/owner comprehensive report remain open.'))
print(json.dumps(dict(status='PREPARED',prompt=prompt,prompt_sha256=sha(prompt.encode()),reference=str(B/source)),ensure_ascii=False))
