from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003';IP=B/'design/audit_impacts/job-candy-twist-release-pose-20261003.json';G=T/'gates_v1';G.mkdir()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 t=p.with_name(p.name+'.v633_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
dst=T/'BROWSER_RELEASE_PROOF_V632.jpg';shutil.copyfile('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/TWIST_RELEASE_PROOF_V632.jpg',dst)
with Image.open(dst) as im:dimensions=list(im.size);assert im.format=='JPEG'
write(T/'BROWSER_VERIFY_V632.json',dict(status='ALL15_LOADED_FULL_IMAGES10_CANDIDATES123_OPINIONS_AND_V53_SOURCE_RECORD_VERIFIED',checked_utc=now(),report_url='http://127.0.0.1:8880/assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html?revision=endpoints-v5#release_attempt05',candidate_articles=10,individual_opinions=123,loaded_images=15,native_dimensions=[1672,941],viewport=[1280,720],document_width=1265,full_release_image_bounds=dict(top=25.984375,bottom=636.046875,width=1084,height=610.0625),screenshot_path=dst.relative_to(B).as_posix(),screenshot_sha256=sha(dst.read_bytes()),screenshot_dimensions=dimensions,library_url='http://127.0.0.1:8880/audit/job_artwork_refinement_live/all_items.html?revision=endpoints-v53',library_registered_items=2152,library_inclusive_priorities=1055,library_unique_priority_sources=678,library_unreviewed_primary_sources=294,current_candy_use_action_priorities=48,filtered_id='CANDY-RELEASE-ENDPOINT-05',filtered_source_score=4.5,filtered_loaded_image=True,filtered_mounted_score=None,filtered_sequence_score=None,filtered_complete_action_score=None,qualification='Actual desktop source report/library observation only. The screenshot shows the complete source/native links/table context. No motion,actual gameplay/device/child/owner acceptance.'))
p=B/'ASSET_LICENSES.md';raw=p.read_bytes();row=('\n| `'+dst.relative_to(B).as_posix()+'` | Actual local-browser screenshot of specific gold-wrapper released endpoint report | Original project QA layout and inherited displayed generated-art attribution | `'+(T/'BROWSER_VERIFY_V632.json').relative_to(B).as_posix()+'` | Browser QA proof only;no gameplay/motion/device/child/owner approval. |\n').encode();assert dst.relative_to(B).as_posix().encode() not in raw;put(p,raw+row)
remote=T/'previous_AB_remote_verified';remote.mkdir();source=B/'tmp/neck_remote_v618';r=read(source/'RESULT.json');assert r['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and r['revision']=='930614f3e8ab0d89177409ba92a2dd28dc228d54' and r['files_including_manifest']==24487 and not r['failed_files'];shutil.copyfile(source/'RESULT.json',remote/'RESULT.json');shutil.copyfile(B/'tmp/neck_publish_v618/RECEIPT.json',remote/'PUBLICATION_RECEIPT.json')
raw=(source/'VERIFICATION_JOURNAL.jsonl').read_bytes();lines=raw.splitlines(keepends=True);assert len(lines)==24487 and all(json.loads(x)['matches'] for x in lines);parts=[];group=[];size=0
def emit():
 payload=b''.join(group);p=remote/f'JOURNAL_{len(parts)+1:03d}.jsonl';p.write_bytes(payload);assert len(payload)<=900000;parts.append(dict(path=p.relative_to(B).as_posix(),bytes=len(payload),sha256=sha(payload),rows=len(group)))
for line in lines:
 if group and size+len(line)>899000:emit();group=[];size=0
 group.append(line);size+=len(line)
if group:emit()
assert b''.join((B/x['path']).read_bytes() for x in parts)==raw;write(remote/'JOURNAL_SHARDS.json',dict(status='ALL24487_EXACT_AB_ANONYMOUS_REMOTE_ROWS_LOSSLESSLY_PRESERVED',revision=r['revision'],original_bytes=len(raw),original_sha256=sha(raw),original_rows=len(lines),parts=parts,shard_max_bytes=900000,qualification='Complete previous revision remote evidence only,not proof of this new endpoint revision or hosted/creative acceptance. Initial pending publication receipt remains separate.'))
H=T/'previous_AB_hosted_snapshot';H.mkdir();cmd=['C:/Program Files/GitHub CLI/gh.exe','run','view','37119657543','--repo','Ebonyks/mermaid-roshan-reef','--json','databaseId,headSha,status,conclusion,url,jobs'];rr=subprocess.run(cmd,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(H/'RUN.json').write_bytes(rr.stdout);(H/'RUN.stderr.log').write_bytes(rr.stderr);assert rr.returncode==0;data=json.loads(rr.stdout);assert data['headSha']==r['revision'];write(H/'VERIFICATION.json',dict(status='ACTUAL_PRIOR_EXACT_HEAD_HOSTED_SNAPSHOT',checked_utc=now(),command=cmd,exit_code=rr.returncode,revision=data['headSha'],run_id=data['databaseId'],run_status=data['status'],run_conclusion=data['conclusion'],jobs=[dict(name=j['name'],status=j['status'],conclusion=j['conclusion']) for j in data['jobs']],raw_sha256=sha(rr.stdout),qualification='Observed status only;pending remains pending. Never predicts new revision hosted or visual/action/owner acceptance.'))
boundary_path=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json';boundary=read(boundary_path);assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members']);write(T/'PRODUCTION_BOUNDARY_AFTER.json',dict(status='ALL783_CURRENT_LITERAL_PRODUCTION_MEMBERS_UNCHANGED_AFTER10_ENDPOINT_NATIVES',checked_utc=now(),source_boundary=boundary_path.relative_to(B).as_posix(),boundary_sha256=sha(boundary_path.read_bytes()),members=783,current_wrap_score=2.8,runtime_changed=False,qualification='No production delta only;no new graphics/action/owner acceptance.'))
old=(B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003/review_tools/run_neck_gate_v617.py').read_text(encoding='utf-8').replace('candy_neck_grip_pose_v1_20261003','candy_twist_release_pose_v1_20261003').replace('gates_v2','gates_v1').replace('CANDIDATE_NECK_SOURCE_V617.json','CANDIDATE_ENDPOINT_SOURCE_V633.json');put(T/'review_tools/run_endpoint_gate_v633.py',old.encode());shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}|{(G/(label+suffix)).relative_to(B).as_posix() for label in ['authority','development','document_tests','game2d','register_parts'] for suffix in ['.stdout.log','.stderr.log','.receipt.json']}|{(G/'CANDIDATE_ENDPOINT_SOURCE_V633.json').relative_to(B).as_posix()});d['validation'].append(dict(command='Actual endpoint report/V53 library browser verification',result='PASS',evidence=(T/'BROWSER_VERIFY_V632.json').relative_to(B).as_posix()+';15 loaded1672x941 images/10 articles/123 individual opinions,no overflow,filtered release4.5 has mounted/sequence/action unassigned.'));d['validation'].append(dict(command='Prior AB complete anonymous remote journal archival',result='PASS',evidence=remote.relative_to(B).as_posix()+'/RESULT.json and JOURNAL_SHARDS.json;all24487 literal rows preserved losslessly.'));d['validation'].append(dict(command='Source-only review structural/document/2D no-regression/register gates',result='PENDING',evidence=G.relative_to(B).as_posix()+';fresh candidate-bound checks required.'));d['validation'].append(dict(command='Runtime import/parser/lint/full probes for source-only endpoint additions',result='NOT_APPLICABLE',evidence='All new artwork remains under assets_src/.gdignore and all QA under audit/.gdignore;no production script,asset or import delta. All783 literals match. Existing official4.7.2 full82/82 process0 remains scoped;actual hosted status separately preserved.'));write(IP,d)
members=[]
for path in d['files']:
 p=B/path
 if not p.is_file() or path.startswith(G.relative_to(B).as_posix()+'/'):continue
 members.append(dict(path=path,bytes=p.stat().st_size,sha256=sha(p.read_bytes())))
write(G/'CANDIDATE_ENDPOINT_SOURCE_V633.json',dict(status='EXACT_TEN_NATIVE_ENDPOINT_AND123_OPINION_REVIEW_BYTES_FROZEN',baseline=d['baseline'],frozen_utc=now(),members=members,member_count=len(members),qualification='Actual source/report/browser/library working-tree state before checks. Later gate/impact/publication metadata separately sealed. No motion/current game/owner/integration/release acceptance.'))
print('BROWSER_PRIOR24487_REMOTE_AND_ENDPOINT_GATES_PREPARED',len(members),data['status'],data['conclusion'],flush=True)
