from pathlib import Path
import datetime, hashlib, json, shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
T=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003'
sha=lambda raw:hashlib.sha256(raw).hexdigest()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
    t=p.with_name(p.name+'.v621_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-89ab498a-187f-4ff6-b8c7-b354ff4f9727.png')
d=T/'twist_attempt01';native=d/'native.png';assert not native.exists();shutil.copyfile(src,native)
with Image.open(native) as im:dimensions=list(im.size);mode=im.mode
write(d/'SOURCE.json',dict(generation_method='built_in_imagegen_precise_object_edit',native_path=native.relative_to(B).as_posix(),native_sha256=sha(native.read_bytes()),dimensions=dimensions,mode=mode,default_generated_original=str(src),prompt_path=(d/'SENT_PROMPT.txt').relative_to(B).as_posix(),prompt_sha256=sha((d/'SENT_PROMPT.txt').read_bytes()),references=read(d/'PLAN.json')['references'],copied_without_pixel_changes=True,recorded_utc=now(),runtime_bound=False))
reviews=[('exactly_two_owned_mittens',4.6,'Two original coral mitten hands retain their own teal cuff/cream sleeve connections and stable quilted contours.'),('left_neck_contact',4.5,'Left thumb and palm keep hold of the short left paper neck, with the fan extending outside.'),('right_neck_contact',4.5,'Right thumb and palm hold the short right neck beside the covered oval.'),('opposite_wrist_pose_change',3.3,'Compared with the untwisted grip, the visible backs and inner thumb positions of both mittens remain almost the same. The paper closes, but a credible pair of opposite wrist rolls is not shown.'),('short_twisted_neck_material',4.4,'Compact helical gold folds replace lengthwise ridges; they read somewhat as neat thick rolls. Opposite winding is not clearly differentiated.'),('single_continuous_gold_wrapper',4.5,'Covered oval, short necks and two outward fans remain a continuous gold-paper object without a separate mat or added fastener.'),('outward_fan_ownership',4.5,'Both fans remain outside their grips, attached to the central wrapper rather than to the cuffs.'),('opaque_supported_small_oval',4.5,'The same low covered oval is supported on the same table at comparable size and centre; no exposed red.'),('character_table_registration',4.5,'Face, outfit, room, camera and table registration remain stable.'),('painted_gold_material',4.5,'Gold body and fans retain painted value bands, crinkle accents and coherent contours.'),('inherited_room_graphics',4.4,'The detailed inherited room remains a separate graphics priority.'),('whole_twist_endpoint',4.1,'A pleasant closed wrapper is insufficient: the two hands have not visibly performed the required opposite wrist rolls.')]
write(d/'DIRECT_REVIEW.json',dict(reviewed_utc=now(),review_method='direct_complete_native_original_imagegen_output_compared_with_exact_pre_twist_source',native_sha256=sha(native.read_bytes()),status='REJECTED_OPPOSITE_WRIST_ROLL_NOT_SHOWN',components=[dict(id=k,score=s,evaluation=v) for k,s,v in reviews],source_pose_score=4.1,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None,required_revision='Retain exact continuous covered gold wrapper, change the two mitten orientations to a visible opposite pair and differentiate short paper winding; do not treat instant closed paper as hand motion.'))
prompt="""Use case: precise-object-edit
Image 1 is the complete existing Candy Maker painting and edit target. Keep its exact full scene, character identity, clothing, cream sleeves and teal cuffs, lavender table, one small gold-covered oval sweet, short gold necks and loose gold fans. Keep the sweet supported at its current centre and size.
Correct the two existing MITTEN WRIST ORIENTATIONS. They currently look like the previous stationary gather pose even though the paper has closed. Draw a clearly different pair of OPPOSITE WRIST ROLLS about the sweet's horizontal long axis. The screen-LEFT coral mitten rolls toward the viewer: its thumb lobe is now visibly BELOW the left short neck, the palm above/behind it, so the neck is firmly pinched between them. The screen-RIGHT coral mitten rolls away from the viewer: its thumb lobe remains clearly ABOVE the right short neck, with its palm below/in front. Show the left glove's turned underside and the right glove's quilted back so these are visibly opposite rotated orientations, not mirrored stationary hands. Keep exactly one rounded thumb on each mitten, no bare fingers. Both naturally remain connected to their original teal cuffs and forearms; adjust the wrist/cuff angle gently, do not detach or stretch an arm.
At each grip the same thin gold-paper neck has two compact soft diagonal winding folds. The left and right winding directions are opposite, like a real double-twist sweet wrapper made by opposing wrists. No separate cord, band, ring, knot or added fastener. Preserve all of the existing gold sheet's continuous body-to-neck-to-fan joins and the top seam. Keep both loose fans outside their own grips, not attached to sleeves or held as separate objects. Keep the covered oval small, opaque and low on the tabletop, and both neck contacts visible. No red, new candy, mat, props, crop, camera change, text, magical effect, motion blur, 3D, realistic skin or flat vector replacement. Return one entire landscape still of the completed wrist rolls with both mittens still gripping. The hands have not released yet."""
a2=T/'twist_attempt02';a2.mkdir();(a2/'SENT_PROMPT.txt').write_bytes(prompt.encode())
ref=dict(path=native.relative_to(B).as_posix(),sha256=sha(native.read_bytes()),role='exact_full_scene_continuous_closed_gold_wrapper_targeted_opposite_wrist_pose_correction')
write(a2/'PLAN.json',dict(status='NAMED_OPPOSITE_WRIST_ORIENTATION_CORRECTION_PLANNED',references=[ref],prompt_sha256=sha(prompt.encode()),runtime_bound=False))
plan=read(T/'PLAN.json');plan['status']='TWIST_A1_REJECTED4_1_OPPOSITE_WRIST_ORIENTATION_A2_PLANNED';plan['attempts'].append(dict(stage='twist',attempt=1,source_pose_score=4.1,status='REJECTED_OPPOSITE_WRIST_ORIENTATION',review='twist_attempt01/DIRECT_REVIEW.json'));write(T/'PLAN.json',plan)
shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-twist-release-pose-20261003.json';impact=read(ip);impact['files']=sorted(set(impact['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()});impact['validation'][1]=dict(command='Native twist endpoint and individual direct review',result='FAIL',evidence='twist_attempt01/DIRECT_REVIEW.json;whole4.1/opposite wrist orientations3.3. Native retained,A2 named correction planned. No release/motion/runtime acceptance.');write(ip,impact)
print(json.dumps(dict(status='A1_PRESERVED_REJECTED4_1_A2_PLANNED',native_sha256=sha(native.read_bytes()),prompt=prompt,prompt_sha256=sha(prompt.encode()),reference=str(native)),ensure_ascii=False))
