from pathlib import Path
import copy,datetime,hashlib,html,json,shutil,subprocess,sys
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');T=B/'assets_src/imagegen/candy_twist_release_pose_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-twist-release-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):
 t=p.with_name(p.name+'.v631_next');t.write_bytes(raw);t.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
sys.path.insert(0,str(L/'review_tools'));from register_parts_v51 import load_register
assembled=load_register(L);reg=read(L/'ALL_ITEMS.json');assert assembled['display_revision']=='V52' and len(assembled['items'])==2142 and len(reg['items'])==2054
H=T/'previous_v52';H.mkdir()
for name in ['ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json']:shutil.copyfile(L/name,H/name)
before=copy.deepcopy(reg['items']);parts=copy.deepcopy(reg['item_shards']);reference=next(x for x in reg['items'] if x['id']=='CANDY-NECK-SOURCE-04')
attempts=[];opinions=0
for stage in ['twist','release']:
 for i in range(1,6):
  folder=T/f'{stage}_attempt{i:02d}';s=read(folder/'SOURCE.json');r=read(folder/'DIRECT_REVIEW.json');assert sha((B/s['native_path']).read_bytes())==s['native_sha256']==r['native_sha256'];assert all(sha((B/x['path']).read_bytes())==x['sha256'] for x in s['references'])
  opinions+=len(r['components']);attempts.append(dict(stage=stage,attempt=i,folder=folder.relative_to(T).as_posix(),source_score=r['source_pose_score'],status=r['status'],source=s,review=r))
  item_id=f'CANDY-{stage.upper()}-ENDPOINT-{i:02d}';z=copy.deepcopy(reference)
  z.update(id=item_id,aliases=[item_id],path=s['native_path'],earlier_sha256=s['native_sha256'],current_checkout_sha256=s['native_sha256'],current_source_score=r['source_pose_score'],evaluation=r['components'][-1]['evaluation'],refinement=r.get('required_revision') or 'Retain the achieved source endpoint. Independently prove the whole fold/cover/gather/opposite-twist/release trajectory and current job/training fit. Inherited room4.4 and owner acceptance remain open.',families=['Day Two','Candy Maker','Unbound specific gold-wrapper '+stage+' endpoint'],original_reports=[T.relative_to(B).as_posix()+'/index.html'],source_qualification='Complete exact native directly reviewed;'+str(len(r['components']))+' separate source opinions. '+r['status']+'. No motion/current game/owner acceptance.',preview_path=s['native_path'],image_path=s['native_path'],image_scope='Full preserved gold-wrapper '+stage+' endpoint candidate only;not an accepted motion frame',source_dimensions=s['dimensions'],individual_review_utc=r['reviewed_utc'],latest_refinement=dict(report=T.relative_to(B).as_posix()+f'/index.html#{stage}_attempt{i:02d}',note=f'{stage} attempt{i} source{r["source_pose_score"]};{len(r["components"])} individual opinions. All failed natives retained. Current game WRAP2.8 and previous local motion1.8 stay separate.'))
  reg['items'].append(z)
assert opinions==123 and len(attempts)==10
allitems=reg['items']+assembled['items'][2054:];pri=[x for x in allitems if x.get('current_source_score') is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3']];unique={x['path'] for x in pri if x['kind'] in ['source','runtime source']};pending=[x for x in allitems if x['kind']=='source' and x.get('current_source_score') is None]
assert len(allitems)==2152 and len(pri)==1055 and len(unique)==678 and len(pending)==294 and reg['items'][:2054]==before and reg['item_shards']==parts
reg['counts'].update(unique_source_files=1300,registered_items=2152,inclusive_current_source_priorities=1055,unique_source_file_priorities=678,unreviewed_current_source=294,new_candy_twist_release_sources=10)
reg.update(display_revision='V53',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v53.py',scope='V53:2152 known entries/1300 primary sources/328 pose cells/151 runtime-use-action entries/373 source object regions.1055 inclusive source-cell-region priorities/678 unique source-file priorities/294 unreviewed primary sources. Ten complete same-scene ImageGen twist/release candidates and123 individual opinions. TwistA5 and releaseA5 source endpoints4.5 provisional;inherited room4.4. Eight rejected candidates retained. Previous guarded local component1.8 rejected;no new motion dispatched and no score transfer. Current WRAP2.8/all783 production literals unchanged. Full fold-cover-gather-opposite-twist-supported-release,actual jobs/Opera training/ordinary routes/device/child/owner/comprehensive all-jobs acceptance remain open.')
reg['current_byte_status_counts']['EXACT_REVIEWED_GENERATION_BYTES']+=10;reg['review_resources'].append(dict(path=T.relative_to(B).as_posix()+'/index.html',scope='Ten exact complete twist/release endpoint natives/123 individual opinions;two endpoint sources4.5 provisional,room4.4. No new motion/current game acceptance.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304;shutil.copyfile(L/'review_tools/refresh_current_job_review_v52.py',L/'review_tools/refresh_current_job_review_v53.py')
notice='<p class="current-twist-release-review"><a href="../../assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html#release_attempt05">Specific gold-wrapper twist and release: ten complete candidates and123 evaluations</a> · twistA5/releaseA5 source4.5 provisional;room4.4. Previous motion1.8 rejected,actual game WRAP2.8 unchanged. <strong>V53:2152 known entries/1055 inclusive priorities/678 unique priority sources/294 unreviewed primary sources.</strong> Full workflow and owner acceptance remain open.</p>'
for name in ['index.html','all_items.html']:
 p=L/name;t=p.read_text(encoding='utf-8').replace('refresh_current_job_review_v52.py','refresh_current_job_review_v53.py');assert '<h1>' in t;put(p,t.replace('<h1>',notice+'<h1>',1).encode())
e=html.escape
out=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Candy wrapper twist and release review</title><style>body{margin:0;background:#eef2fa;color:#22304a;font:17px/1.55 system-ui}main{max-width:1120px;margin:auto;padding:24px}h1,h2,h3{line-height:1.2}a{color:#39459b}nav{display:flex;flex-wrap:wrap;gap:12px}article,section{margin:28px 0;padding:18px;background:white;border-radius:16px}img{display:block;width:100%;height:auto;aspect-ratio:1672/941;object-fit:contain}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #d7dce8;padding:10px;overflow-wrap:anywhere}th:first-child{width:23%}th:nth-child(2){width:9%}code{overflow-wrap:anywhere;font-size:13px}.status{padding:15px;background:#fff0cf;border-radius:12px}small{overflow-wrap:anywhere}figure{margin:14px 0}figcaption{margin:6px 0}</style><main><h1>Do the hands support this gold wrapper?</h1><p class="status"><strong>Two improved endpoint stills reach a provisional4.5/5. The actual motion does not yet pass.</strong> Previous local component1.8/5 is rejected; current in-game WRAP remains2.8/5. Ten complete native candidates and123 individual opinions are preserved here. The full physical workflow and actual game/Opera training still need proof.</p><p>The final twist pose has two owned mitten contacts with distinct rolled orientations and opposite short paper winding. The final release leaves both hands clear, preserving one table-supported covered sweet and its broad gold fans. Each opinion is limited to visible source pixels. A still cannot establish wrist rotation, contact throughout motion or a completed action in gameplay. The inherited factory room remains4.4/5.</p><nav><a href="#twist_attempt05">Final twist source</a><a href="#release_attempt05">Final released source</a><a href="#workflow">All five source stages</a><a href="../candy_neck_grip_pose_v1_20261003/local_motion_a1/index.html">Rejected41-frame motion</a><a href="../../../audit/job_artwork_refinement_live/all_items.html">Full2152-entry library</a></nav><section><h2>What is still required</h2><p>Partial fold → opaque cover → gather → opposite wrist twists → supported release must occur continuously, with the same sweet and gold sheet, two cuff-owned hands, stable table support and no fan/cuff merging. Both the actual story job and Opera training must bind this authored family and expose every contact/state before their scores change. No new Comfy study was dispatched in this endpoint revision.</p><p>The current mounted widget is a different turquoise decorative wrapper. These gold-paper paintings are unbound replacement studies. Device, child, owner and comprehensive all-job acceptance remain open;294 primary Day One source opinions and other weak jobs/actions remain in the library.</p></section>']
for a in attempts:
 r=a['review'];s=a['source'];folder=a['folder'];out.append(f'<article id="{folder}" data-stage="{a["stage"]}" data-attempt="{a["attempt"]}" data-source-score="{a["source_score"]}"><h2>{a["stage"].title()} attempt{a["attempt"]} · {a["source_score"]}/5</h2><p><strong>{e(a["status"])}</strong></p><figure><img src="{folder}/native.png" width="1672" height="941" alt="Full preserved {a["stage"]} candidate{a["attempt"]}"><figcaption>Complete unaltered native ·1672×941 RGB ·<a href="{folder}/native.png">Open original</a> ·<a href="{folder}/DIRECT_REVIEW.json">Individual source review</a> ·<a href="{folder}/SOURCE.json">Provenance</a> ·<a href="{folder}/SENT_PROMPT.txt">Exact prompt</a></figcaption></figure><table><thead><tr><th>Individual item or relationship</th><th>Score/5</th><th>Written evaluation</th></tr></thead><tbody>')
 for c in r['components']:out.append(f'<tr class="opinion"><td>{e(c["id"].replace("_"," "))}</td><td>{c["score"]}</td><td>{e(c["evaluation"])}</td></tr>')
 out.append('</tbody></table>'+('<p><strong>Required correction:</strong> '+e(r['required_revision'])+'</p>' if r.get('required_revision') else '')+'<p><small>Native SHA-256 <code>'+s['native_sha256']+'</code>. Source only;motion/action/runtime/owner unassigned.</small></p></article>')
out.append('<section id="workflow"><h2>Five source stages, still not an accepted animation</h2><p>These complete authored references keep the desired causal order visible. The space between them must be independently reviewed; they are not delivery frames or evidence of a continuous action.</p>')
stages=[('Partial fold','assets_src/imagegen/candy_wrap_scene_context_v1_20261003/attempt02/native.png'),('Covered/pressed','assets_src/imagegen/candy_cover_pose_v1_20261003/attempt01/native.png'),('Gathered untwisted grips','assets_src/imagegen/candy_neck_grip_pose_v1_20261003/attempt04/native.png'),('Opposed twist endpoint',T.relative_to(B).as_posix()+'/twist_attempt05/native.png'),('Supported released endpoint',T.relative_to(B).as_posix()+'/release_attempt05/native.png')]
for label,path in stages:
 rel=Path(__import__('os').path.relpath(B/path,T)).as_posix();out.append(f'<figure><h3>{e(label)}</h3><img src="{e(rel)}" width="1672" height="941" alt="Complete {e(label)} source"><figcaption><a href="{e(rel)}">Complete unchanged source</a> ·source4.5 provisional;whole motion unassigned</figcaption></figure>')
out.append('<p><a href="PLAN.json">Task plan/rules/reuse inventory</a> ·<a href="REVIEW_SUMMARY.json">Review summary</a> ·<a href="NEXT_ACTION_PLAN.json">Next required action</a></p></section></main></html>');put(T/'index.html',''.join(out).encode())
write(T/'REVIEW_SUMMARY.json',dict(status='TWO_ENDPOINT_SOURCES4_5_PROVISIONAL_FULL_ACTION_OPEN',reviewed_utc=now(),native_sources=10,individual_source_opinions=123,rejected_sources=8,twist_source_score=4.5,release_source_score=4.5,inherited_room_score=4.4,prior_motion_reference_component_score=1.8,new_motion_dispatched=False,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None,attempts=[{k:a[k] for k in ['stage','attempt','folder','source_score','status']} for a in attempts],qualification='Source endpoint opinions only;all inclusive4.5 priorities retained. Source endpoints cannot satisfy contact/motion/actual job/training/device/child/owner/comprehensive all-jobs acceptance.'))
write(T/'NEXT_ACTION_PLAN.json',dict(status='OPEN_NOT_DISPATCHED',next_required='Using the accepted source references and established guarded local Comfy workflow, test a small gather-to-opposing-twist-to-supported-release component. Preserve the exact submitted manifest BEFORE dispatch;review every native decoded frame and contact/wrist/paper/fan/support/release component separately. No model/workflow replacement or score transfer. Full fold/cover/gather/twist/release,current actual job/Opera training and broader all-jobs audit remain required.',source_references=[dict(label=label,path=path,sha256=sha((B/path).read_bytes())) for label,path in stages],current_game_wrap_score=2.8,previous_component_score=1.8,owner_acceptance=None))
note='Specific Candy twist/release continuation (2026-10-03): [ten complete native endpoint candidates and123 individual opinions](TWIST). Four failed twist and four failed release sources retained;twistA5/releaseA5 endpoint sources4.5 provisional,room4.4. Corrected opposing thumb-side contacts/rolled right glove,short opposite thin-paper winding,fan conservation and quiet fully disengaged hands. Previous local component1.8 remains rejected;no new motion dispatched. Current WRAP2.8/all783 production literals unchanged. V53 known2152 entries/1300 primary sources/1055 inclusive priorities/678 unique priority sources/294 pending primary opinions;prior2054 root entries and literal88-item part unchanged. Full fold-cover-gather-opposite-twist-supported-release,actual jobs/Opera training/ordinary routes/device/child/owner/comprehensive acceptance remain open. Finding lifecycle,integration and release unchanged.'
for path,link in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html'),('audit/animation/README.md','../../assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html')]:
 p=B/path;t=p.read_text(encoding='utf-8');n=note.replace('TWIST',link)
 if path.endswith('MASTER_AUDIT_2026-08-09.md'):
  for marker in ['## 0. Planning entry','### Development task index']:assert marker in t;t=t.replace(marker,marker+'\n\n'+n,1)
 else:i=t.index('\n')+1;t=t[:i]+'\n'+n+'\n'+t[i:]
 put(p,t.encode())
p=B/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8');t+='\n| `assets_src/imagegen/candy_twist_release_pose_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; ten complete preserved endpoint candidates/123 individual source opinions. TwistA5/releaseA5 source4.5 provisional;room4.4. Previous local motion1.8 rejected,no new motion/current game2.8/owner acceptance. |\n| `assets_src/imagegen/candy_twist_release_pose_v1_20261003/previous_v52/ALL_ITEMS.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact bounded V52 root before ten new endpoint sources;88-item literal part unchanged. |\n';put(p,t.encode())
p=B/'.gitattributes';t=p.read_text(encoding='utf-8');t+='\nassets_src/imagegen/candy_twist_release_pose_v1_20261003/** -text\n';put(p,t.encode())
p=B/'ASSET_LICENSES.md';raw=p.read_bytes();rows=[]
for a in attempts:rows.append('| `'+a['source']['native_path']+'` | OpenAI built-in ImageGen precise-object-edit;'+a['stage']+' attempt'+str(a['attempt'])+' | Generated project review artwork;inherited project references/provenance | `'+T.relative_to(B).as_posix()+'/'+a['folder']+'/SOURCE.json` binds exact prompt/reference/native hashes | Complete native copied without pixel changes;source-only '+str(a['source_score'])+'/5;'+('provisional endpoint' if a['attempt']==5 else 'rejected retained')+';no runtime/motion/owner acceptance. |')
put(p,raw+('\n'+'\n'.join(rows)+'\n').encode());shutil.copyfile(__file__,T/'review_tools'/Path(__file__).name)
impact=read(IP);impact['files']=sorted(set(impact['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS.json','index.html','all_items.html','CURRENT_BOUNDARY_REFRESH.json','review_tools/refresh_current_job_review_v53.py']}|{'.gitattributes','ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md','design/05_DOC_LEDGER.md'});write(IP,impact)
r=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v53.py')],cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(T/'REFRESH.stdout.log').write_bytes(r.stdout);(T/'REFRESH.stderr.log').write_bytes(r.stderr);assert r.returncode==0,r.stderr.decode(errors='replace');assert read(L/'CURRENT_BOUNDARY_REFRESH.json')['registered_source_matches']==2152;loaded=load_register(L);assert len(loaded['items'])==2152 and loaded['items'][:2054]==before
write(T/'REGISTER_EXTENSION_CHECK.json',dict(status='V53_ALL2152_SOURCE_HASHES_MATCH_PRIOR2054_AND88_PART_UNCHANGED',checked_utc=now(),root_bytes=(L/'ALL_ITEMS.json').stat().st_size,unchanged_previous_base_items=2054,unchanged_part_items=88,registry_parts=parts,registered_items=2152,inclusive_priorities=1055,unique_priority_sources=678,unreviewed_primary_sources=294,qualification='Literal source/known-entry integrity only;no complete action/game/device/child/owner acceptance.'))
impact=read(IP);impact['files']=sorted(set(impact['files'])|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()});impact['validation'].append(dict(command='V53 bounded known-item source refresh/prior-record preservation',result='PASS',evidence=(T/'REGISTER_EXTENSION_CHECK.json').relative_to(B).as_posix()+';2152/2152 literal source hashes,2054 prior records/88-item part unchanged;existing4MiB ceiling.'));write(IP,impact)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in T.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for p in L.rglob('*') if p.is_file()}));print(r.stdout.decode().strip());print('V53',len(allitems),len(pri),len(unique),len(pending),(L/'ALL_ITEMS.json').stat().st_size,'OPINIONS',opinions,flush=True)
