from pathlib import Path
from PIL import Image
import datetime,hashlib,html,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001'
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-ff2a2caa-ea93-43ab-80e5-df1c07af393c.png')
native=out/'attempt_05_native.png';assert not native.exists();shutil.copyfile(source,native)
im=Image.open(native);a=im.getchannel('A');b=a.point(lambda x:255 if x>=16 else 0).getbbox()
review={'status':'REJECTED_UNBOUND_SOURCE','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'native_path':native.relative_to(r).as_posix(),'native_sha256':hashlib.sha256(native.read_bytes()).hexdigest(),'provider_path':str(source),'method':'Built-in image_gen fresh text-only; no images bound; exact native RGBA preserved.','prompt_sha256':json.loads((out/'ATTEMPT_05_PROMPT.json').read_text())['prompt_sha256'],'source_score':4.3,'gesture_meaning_score':4.6,'identity_style_score':4.3,'native_fit_score':None,'complete_action_score':None,'evaluation':'The compact curved tail and rightward rainbow hair recover the doctor costume family; the joined hand lather is clear. The very large toddler/chibi head, plush dimensional cheeks, layered shiny hair and stocky tail still depart from the approved drawn atlas. This is a useful gesture draft but does not pass source identity/style,4.3 rejected. Tail hue is not itself a defect: owner2026-09-30 permits lavender-pink-purple or rainbow according to light.','technical':{'mode':im.mode,'dimensions':list(im.size),'alpha_extrema':a.getextrema(),'alpha_ge16_bbox':b,'silhouette_width_over_height':(b[2]-b[0])/(b[3]-b[1])},'owner_approval':'PENDING'}
(out/'ATTEMPT_05_REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
identity=r/'assets/characters/roshan_25d/roshan_base.png'
correction={'status':'AUDIT_ASSUMPTION_CORRECTED','authority':'audit/MASTER_AUDIT_2026-08-09.md; Roshan identity decision2026-09-30','explanation':'Lavender-pink-purple and rainbow tail variants are both owner-accepted identity colours according to lighting. The earlier attempt4 evaluation mentioning predominantly pink/lavender as variance must not be interpreted as a canonical colour defect. Its4.2 rejection rests on older facial/body proportions and long narrow silhouette/style difference. No original opinion or candidate is concealed; future review applies the actual authority.','base_identity_anchor':{'path':identity.relative_to(r).as_posix(),'sha256':hashlib.sha256(identity.read_bytes()).hexdigest(),'role':'Approved base-world identity anchor, directly viewed locally; not tool-uploaded or copied into generated candidate.'},'doctor_atlas_measured_alpha_ge16_cells':[{'cell':[0,0],'bbox':[44,18,213,237],'width_over_height':169/219},{'cell':[1,2],'bbox':[43,55,213,237],'width_over_height':170/182},{'cell':[2,2],'bbox':[42,54,214,237],'width_over_height':172/183}],'measurement_qualification':'Declared geometry from exact approved atlas; not a universal mandatory ratio, temporal loop or generated candidate acceptance.'}
(out/'QUALIFICATION_CORRECTION_V1.json').write_text(json.dumps(correction,indent=2)+'\n',encoding='utf-8')
prev=json.loads((out/'ATTEMPT_05_PROMPT.json').read_text())
prompt='''One intact full-body Doctor Roshan washing pose, a clean 2D anime storybook game illustration on actual transparent RGBA. Drawn warm-brown/plum outlines and broad pastel painted fills with a single gentle flat shadow band. Keep face and hair visibly drawn and matte, with no sculpted 3D skin or shiny plush texture.

She is the familiar young girl mermaid with a softly oval face, large drawn brown eyes, small nose, short brown bangs, shoulder-length warm caramel-brown waves, pearl flower hairclip, and one broad rainbow lock flowing to the RIGHT. Head is about one fifth of total figure height; no giant toddler/chibi head or adult glamour. Ivory short-sleeved doctor coat, coral collar/cuffs/hem and heart patch, teal gold-buttoned blouse, lavender waistband, cream/coral medicine satchel on her right hip. She looks attentively down at two attached hands rubbing together just below her chest in modest matte ivory/mint soap lather. Both forearms stay connected naturally to her shoulders. No tool or patient.

Single medium-width short mermaid tail in painted iridescent coral-gold-mint-aqua-lavender-pink scales, curved down and UP to the RIGHT in a broad C. One connected TWO-LOBED forked fan fin with a V notch at the tip, beside the lower coat. Fit the entire figure in a near-square compact silhouette about80 percent as wide as tall, generous transparent margins, head/hair and both fin lobes intact. Tail is neither a long dangling column nor a giant bulbous toddler body.

Polished gentle 2D children's storybook, readable rounded masses, restrained simple scale shapes and soft aqua/lavender shadows. No realism, 3D, heavy surface texture, gloss, halo, glitter, extra limbs, legs/feet, detached hands, lettering, UI, background, sink or ground/shadow plate. One fresh sprite, not a sheet.'''
sixth=dict(prev,attempt=6,preceding_rejected_candidate={'path':review['native_path'],'sha256':review['native_sha256'],'score':4.3,'tool_reference':False},targeted_change='Recover drawn anime/storybook identity and moderate child head/body proportions; retain clear attached hands and compact two-lobed tail.',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),base_identity_anchor=correction['base_identity_anchor'])
(out/'ATTEMPT_06_PROMPT.json').write_text(json.dumps(sixth,indent=2)+'\n',encoding='utf-8')
shutil.copyfile(Path(__file__),out/'executed_prepare_doctor_wash_attempt06_and_browser_archive_v6.py')
browser=r/'audit/job_review_v2_20261001/browser_review_v3';assert not browser.exists();browser.mkdir()
stage=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/day2_graphics_audit_20260930/tmp')
for name in ['wash_viewer_doctor_v5.png','wash_viewer_nursery_v5.png','wash_viewer_checks_v5.json']:shutil.copyfile(stage/name,browser/name)
(browser/'REVIEW.json').write_text(json.dumps({'status':'PASS_SCOPED_DESKTOP_WASH_VIEWER_CONTROLS','case_count':8,'case_final_frame_checks':'wash_viewer_checks_v5.json','screenshots':['wash_viewer_doctor_v5.png','wash_viewer_nursery_v5.png'],'native_keys_directly_reviewed':108,'total_captured_native_frames':1520,'every_native_frame_directly_reviewed':False,'qualification':'Eight case selections and keyboard final-frame controls checked at desktop1265px, no horizontal overflow in recorded DOM. Current screenshots show controls and part of corresponding native view. This is local browser behavior/layout evidence only; responsive layout, ordinary gameplay actions, remaining frames and device/child/owner acceptance remain pending.'},indent=2)+'\n',encoding='utf-8')
p=r/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8');s+='\n| `'+review['native_path']+'` | OpenAI built-in image_gen fresh text-only wash pose | OpenAI-generated project art; identity/design rights unchanged | Provider native exec-ff2a2caa-ea93-43ab-80e5-df1c07af393c.png; SHA-256 `'+review['native_sha256']+'` | Exact native RGBA unmodified; rejected source4.3, unbound |\n'
for p in browser.glob('*.png'):s+='| `'+p.relative_to(r).as_posix()+'` | Native in-app browser screenshot of authored local washing library | Existing project-art rights unchanged | SHA-256 `'+hashlib.sha256(p.read_bytes()).hexdigest()+'` | Exact screenshot; scoped desktop controls and partial native view, no art acceptance |\n'
(r/'ASSET_LICENSES.md').write_text(s,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for family in [out,browser] for x in family.rglob('*') if x.is_file()]));d['validation'].append({'command':'Direct doctor wash source attempt5 and identity-authority correction','result':'FAIL','evidence':'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/ATTEMPT_05_REVIEW.json; source4.3 rejected. QUALIFICATION_CORRECTION_V1.json explicitly permits owner-approved tail-colour variants; complete action pending.'});d['validation'].append({'command':'Desktop washing frame library controls','result':'PASS','evidence':'audit/job_review_v2_20261001/browser_review_v3/REVIEW.json; all8 case final-frame controls,1265px no horizontal overflow; browser-only scoped evidence.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'source_score':4.3,'decision':review['status'],'next_prompt_sha256':sixth['prompt_sha256'],'technical':review['technical'],'browser_cases_checked':8}))
