from pathlib import Path
from PIL import Image
import datetime,hashlib,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001'
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-33681976-7e8c-4183-9d43-ce864ecf6e04.png')
native=out/'attempt_02_native.png';assert not native.exists();shutil.copyfile(source,native)
im=Image.open(native);alpha=im.getchannel('A');bbox=alpha.point(lambda x:255 if x>=16 else 0).getbbox()
review={'status':'REJECTED_UNBOUND_SOURCE','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'native_path':native.relative_to(r).as_posix(),'native_sha256':hashlib.sha256(native.read_bytes()).hexdigest(),'provider_path':str(source),'method':'Built-in image_gen fresh text-only transparent request; native RGBA preserved. No images bound.','prompt_sha256':json.loads((out/'ATTEMPT_02_PROMPT.json').read_text())['prompt_sha256'],'source_score':4.3,'gesture_meaning_score':4.6,'style_finish_score':4.6,'identity_silhouette_score':4.2,'native_fit_score':None,'complete_action_score':None,'evaluation':'Flat colour bands, stronger plum contour, matte lather and smaller fin improve the storybook finish. The source remains a narrow portrait silhouette with a long low tail, instead of the approved near-square doctor cutout with its tail curling back up to the side. Head/hair width and simplified facial design also change the approved family. These identity/silhouette differences remain below the4.5 target; source4.3 rejected, despite promising finish/gesture4.6. Test no runtime binding or full action from this draft.','technical':{'mode':im.mode,'dimensions':list(im.size),'alpha_extrema':alpha.getextrema(),'alpha_ge16_bbox':bbox,'silhouette_width_over_height':(bbox[2]-bbox[0])/(bbox[3]-bbox[1])},'owner_approval':'PENDING'}
(out/'ATTEMPT_02_REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
second=json.loads((out/'ATTEMPT_02_PROMPT.json').read_text())
prompt='''Generate one fresh complete connected Doctor Roshan hands-washing sprite on a SQUARE canvas, not a long portrait. Actual transparent RGBA outside the character. This is a 2D storybook game cutout and a missing work pose, not a redesign.

Silhouette is the main constraint: the whole sprite fits a nearly square silhouette, width about80–90% of its height. The child is upright in front three-quarter view, with a compact torso. One single moderately short fish tail starts under the purple waistband, curves down in a broad C, then curls BACK UP on the right. Its one modest connected two-lobed fish fin ends to the right of the lower coat, around waist-to-lower-torso height, not hanging far below. Keep the face/head narrower than the flowing hair mass; the head must not dominate the torso. Leave clean transparent margins on all sides and show the entire hair, body and both fin lobes.

Text identity lock: warm peach small child mermaid, friendly large drawn brown eyes, brown soft bangs and caramel-brown wavy hair sweeping to her right; one broad pastel rainbow hair lock with a small cream pearl flower clip. Ivory short-sleeved little doctor's coat with coral collar/cuffs/hem, small rounded heart badge, teal blouse with tiny gold buttons, purple waistband; little ivory/coral medical pouch at the right hip. Gentle lavender-pink-purple/rainbow tail scales, simplified and matte. Two arms attach naturally to the shoulders and meet in front just below the chest, rubbing a small cream/mint soap lather. Look attentively down at the hands. No medical tool held, no bottle or bandage. No legs, feet, extra tails/arms or other characters.

Finish: polished 2D painted storybook cutout with restrained dark plum/brown contours, clear rounded forms, broad calm painted colour bands and soft simple aqua/lavender shadow shapes. Friendly drawn facial features; preserve a child sprite's proportions. Softer illustrated line weight than a heavy vector icon, while keeping crisp contours. No realistic skin or fingers, 3D/glass gloss, hair-strand rendering, glitter/refraction, ambient glow, shadow plate, opaque backdrop, water jets, sink, text, UI or camera effects. One intact fresh sprite only. Square composition with the compact curling-up tail and modest fin is essential.'''
third=dict(second,attempt=3,preceding_rejected_candidate={'path':review['native_path'],'sha256':review['native_sha256'],'score':4.3,'tool_reference':False},targeted_change='Compact approved-family near-square silhouette and upward curled tail; keep the flatter storybook finish and connected soap gesture.',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())
(out/'ATTEMPT_03_PROMPT.json').write_text(json.dumps(third,indent=2)+'\n',encoding='utf-8')
shutil.copyfile(Path(__file__),out/'executed_review_doctor_wash_attempt02_v1.py')
p=r/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8');s+='\n| `'+review['native_path']+'` | OpenAI built-in image_gen, fresh text-only Doctor Roshan wash pose | OpenAI-generated project art; identity/design rights unchanged | Provider native exec-33681976-7e8c-4183-9d43-ce864ecf6e04.png; SHA-256 `'+review['native_sha256']+'` | Exact native RGBA, unmodified; rejected source4.3; unbound review draft, no runtime/delivery or owner acceptance |\n';p.write_text(s,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in out.rglob('*') if x.is_file()]));d['validation'].append({'command':'Direct doctor wash source attempt2 evaluation','result':'FAIL','evidence':'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/ATTEMPT_02_REVIEW.json; finish/gesture4.6, silhouette4.2, overall source4.3 rejected. Fresh compact-silhouette attempt3 pending; native/timed/owner acceptance remains pending.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'score':4.3,'silhouette':review['technical'],'third_prompt_sha256':third['prompt_sha256']}))
