from pathlib import Path
from PIL import Image
import datetime,hashlib,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001'
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-aafb3d23-a0fa-47a9-acbd-9787189fd917.png')
native=out/'attempt_01_native.png';assert not native.exists();shutil.copyfile(source,native)
im=Image.open(native);alpha=im.getchannel('A');hist=alpha.histogram();count=im.width*im.height
technical={'mode':im.mode,'dimensions':list(im.size),'alpha_extrema':alpha.getextrema(),'nonzero_alpha_bbox':alpha.getbbox(),'alpha_ge16_bbox':alpha.point(lambda x:255 if x>=16 else 0).getbbox(),'zero_alpha_fraction':hist[0]/count,'low_nonzero_alpha_fraction':sum(hist[1:16])/count,'sample_rgba':{str(pt):list(im.getpixel(pt)) for pt in [(0,0),(20,400),(30,700),(500,20),(1023,1535)]}}
review={'status':'REJECTED_UNBOUND_SOURCE','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'native_path':native.relative_to(r).as_posix(),'native_sha256':hashlib.sha256(native.read_bytes()).hexdigest(),'provider_path':str(source),'method':'Built-in image_gen fresh text-only transparent request, no images bound. Native RGBA preserved without alteration.','prompt_sha256':json.loads((out/'ATTEMPT_01_PROMPT.json').read_text())['prompt_sha256'],'source_score':3.8,'gesture_meaning_score':4.6,'identity_style_score':3.8,'native_fit_score':None,'complete_action_score':None,'evaluation':'Both hands are attached and meet in soap lather below the chest, improving the intended washing gesture. The soft rounded face rendering, fine hair highlights and glimmering scales lean toward the life-like finish the owner rejected. The fin is large relative to the approved doctor cutout, and the soft halo/fringe needs technical/native-scale inspection. This is RGBA with real zero-alpha pixels; do not incorrectly call it an opaque image. Overall source draft3.8 is rejected and remains unbound.','technical':technical,'owner_approval':'PENDING','originals':'Unchanged; no protected artwork altered.'}
(out/'ATTEMPT_01_REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
first=json.loads((out/'ATTEMPT_01_PROMPT.json').read_text())
prompt=first['prompt'].split('Art finish:')[0]+'''Art finish: a genuinely FLAT 2D cel-painted storybook cartoon cutout. Use continuous visible navy/plum ink outlines around hair, face, clothes, forearms and tail; broad solid local-colour fills with only one simple aqua/lavender shadow band. Hair is a few clear brown rounded locks with the same broad pastel rainbow lock, without fine strands or glossy highlights. Eyes use flat brown shapes, a simple drawn dark upper contour and one tiny white dot highlight, not spherical glass. Nose and closed smile are small simple drawn marks. Skin has a calm flat peach fill, not modelled skin shading. Preserve the original costume description, connected small child body, hands-washing action and single curved tail. The fin must be a modest two-lobed tail tip, visibly smaller than the torso, not an enormous butterfly-like fin. Scales are subtle simplified painted shapes, not sparkling/glittering or reflective material. Cream/mint foam is matte with a clear plum contour and two flat tones. Absolutely no soft 3D rendering, realistic skin/hands, photo modelling, ambient glow/halo, gradient shadow plate, glitter, refraction, texture noise, fur, soft edge fog or background. Make a clean outlined cartoon game sprite at actual transparent RGBA alpha, with generous completely transparent margins on every side. One complete character only; no sink, patient, tool in hands, extra limbs, lettering or UI.'''
second=dict(first,attempt=2,preceding_rejected_candidate={'path':review['native_path'],'sha256':review['native_sha256'],'score':3.8,'tool_reference':False},targeted_change='Flatter illustrated contours/fills and modest approved-family fin proportions; gesture/identity costume description retained. Still a fresh text-only source generation, not reference fitting.',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())
(out/'ATTEMPT_02_PROMPT.json').write_text(json.dumps(second,indent=2)+'\n',encoding='utf-8')
shutil.copyfile(Path(__file__),out/'executed_review_doctor_wash_attempt01_v1.py')
p=r/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8');s+='\n| `'+review['native_path']+'` | OpenAI built-in image_gen, fresh text-only Doctor Roshan wash pose | OpenAI-generated project art; identity/design rights unchanged | Provider native exec-aafb3d23-a0fa-47a9-acbd-9787189fd917.png; SHA-256 `'+review['native_sha256']+'` | Exact native RGBA, unmodified; rejected source3.8; unbound review draft, not runtime/delivery or owner acceptance |\n';p.write_text(s,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in out.rglob('*') if x.is_file()]));d['validation'].append({'command':'Direct doctor wash source attempt1 evaluation','result':'FAIL','evidence':'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/ATTEMPT_01_REVIEW.json; gesture4.6 but overall source3.8 rejected. Fresh flatter attempt2 pending; no native/runtime/complete-action or owner approval.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'source_score':3.8,'decision':review['status'],'technical':technical,'next_prompt_sha256':second['prompt_sha256']}))
