from pathlib import Path
from PIL import Image
import datetime,hashlib,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001'
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-e8e6715f-988c-4936-b2f7-6f93bf82d2e2.png')
native=out/'attempt_03_native.png';assert not native.exists();shutil.copyfile(source,native)
im=Image.open(native);alpha=im.getchannel('A');bbox=alpha.point(lambda x:255 if x>=16 else 0).getbbox()
review={'status':'REJECTED_UNBOUND_SOURCE','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'native_path':native.relative_to(r).as_posix(),'native_sha256':hashlib.sha256(native.read_bytes()).hexdigest(),'provider_path':str(source),'method':'Built-in image_gen fresh text-only transparent request; exact native RGBA preserved. No images bound.','prompt_sha256':json.loads((out/'ATTEMPT_03_PROMPT.json').read_text())['prompt_sha256'],'source_score':3.9,'gesture_meaning_score':4.5,'identity_topology_score':3.9,'native_fit_score':None,'complete_action_score':None,'evaluation':'The upward tail curl and square canvas improve staging potential. Soft dimensional face/hair rendering returns, and the fin is one leaf-shaped fan rather than the approved connected two-lobed fish fin. A better body curve cannot compensate for the style/topology gap. Overall3.9 rejected, unbound; native source preserved.','technical':{'mode':im.mode,'dimensions':list(im.size),'alpha_extrema':alpha.getextrema(),'alpha_ge16_bbox':bbox,'silhouette_width_over_height':(bbox[2]-bbox[0])/(bbox[3]-bbox[1])},'owner_approval':'PENDING'}
(out/'ATTEMPT_03_REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
third=json.loads((out/'ATTEMPT_03_PROMPT.json').read_text())
prompt='''ONE full-body Doctor Roshan sprite, rubbing her attached two hands together in small matte cream/mint soap lather just below her chest. Front three-quarter view, looking gently down at her hands. Square composition and clean real RGBA transparency.

Use FLAT 2D inked storybook cartoon drawing: clear dark plum/brown contour lines, broad simple colour fills, one soft flat lavender shadow shape. No 3D modelling, realistic skin, hair strands, glossy eyes, glitter, light halos or gradient background. Friendly drawn brown eyes and simple small nose/smile. Warm peach skin; brown bangs and flowing rounded brown hair with one broad pastel rainbow lock and a cream pearl flower clip. Keep the head/face compact relative to the body, not a chibi oversized head. Ivory short-sleeved doctor coat with coral collar/cuffs/hem and small heart badge; teal gold-buttoned blouse; purple waistband; small ivory/coral medical pouch at her right hip.

One single lavender-pink-purple/rainbow-scaled fish tail, moderately short and broad, curves down from the waist then curls UP to the right in a wide C. The tail tip ends beside the lower coat. At that one tip there is ONE connected forked fish fin with TWO distinct rounded lobes: an upper fan and lower fan joined to the same tail stem, a clear V-shaped notch between them. Do not make a single leaf fin, extra flippers or multiple tails. Use simple matte pastel painted scales and fin bands. Make the complete figure about80–90% as wide as it is tall; generous fully transparent margins, full hair and both fin lobes in frame. No legs/feet, detached hands, bottle/bandage/tool held, sink, patient, text, UI, ground or shadow plate. One intact fresh sprite, not a sheet.'''
fourth=dict(third,attempt=4,preceding_rejected_candidate={'path':review['native_path'],'sha256':review['native_sha256'],'score':3.9,'tool_reference':False},targeted_change='Restore flat finish; maintain compact curling-up tail and explicit approved connected two-lobed fin topology.',prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest())
(out/'ATTEMPT_04_PROMPT.json').write_text(json.dumps(fourth,indent=2)+'\n',encoding='utf-8')
shutil.copyfile(Path(__file__),out/'executed_review_doctor_wash_attempt03_v1.py')
p=r/'ASSET_LICENSES.md';s=p.read_text(encoding='utf-8');s+='\n| `'+review['native_path']+'` | OpenAI built-in image_gen, fresh text-only Doctor Roshan wash pose | OpenAI-generated project art; identity/design rights unchanged | Provider native exec-e8e6715f-988c-4936-b2f7-6f93bf82d2e2.png; SHA-256 `'+review['native_sha256']+'` | Exact native RGBA, unmodified; rejected source3.9; unbound review draft, no runtime/delivery or owner acceptance |\n';p.write_text(s,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in out.rglob('*') if x.is_file()]));d['validation'].append({'command':'Direct doctor wash source attempt3 evaluation','result':'FAIL','evidence':'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/ATTEMPT_03_REVIEW.json; style/fin topology remains below target, source3.9 rejected. Fresh flatter two-lobed attempt4 pending; all native/timed/owner gates remain pending.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'source_score':3.9,'decision':'REJECTED_UNBOUND_SOURCE','technical':review['technical'],'next_prompt_sha256':fourth['prompt_sha256']}))
