from pathlib import Path
import hashlib,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
old=Path(__file__).resolve().parent
root=r/'audit/day_two_wash_complete_action_v1_20261001'
count=sum(len(x['ticks']) for x in json.loads((root/'KEY_BOARD_REGISTER_V2.json').read_text())['boards'])
assert count==108
shutil.copyfile(old/'finalize_selected_wash_review_v3.py',root/'failed_finalize_selected_wash_review_v3.py')
(root/'FINALIZER_COUNT_FAILURE_V3.json').write_text(json.dumps({'status':'FAIL_PRESERVED','reason':'The first selected-key finalizer incorrectly assumed104; the actual registered/deduplicated board key count is108. It stopped before HTML/authority updates. The corrected revision uses the actual register count; no artwork or process evidence changes.'},indent=2)+'\n',encoding='utf-8')
s=(old/'finalize_selected_wash_review_v3.py').read_text(encoding='utf-8').replace('104','108').replace('executed_finalize_selected_wash_review_v3.py','executed_finalize_selected_wash_review_v4.py')
(old/'finalize_selected_wash_review_v4.py').write_text(s,encoding='utf-8')
out=r/'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001';assert not out.exists();out.mkdir()
(out/'.gdignore').write_text('',encoding='utf-8')
prompt='''Create ONE original full-body transparent-background 2D storybook game sprite: Doctor Roshan carefully rubbing her two soapy hands together at upper-waist height. This is a fresh generation of the missing washing pose, one connected character, not floating hands and not a sprite sheet.

Identity and costume: a cheerful small child mermaid with a round face, big warm brown eyes, short soft brown bangs and flowing caramel-brown hair sweeping to her right. One broad pastel rainbow lock runs through the rightward hair, with a tiny cream pearl flower hairclip. Warm peach skin. Ivory short-sleeved little doctor coat with coral-peach collar, cuffs and hem, a small rounded coral heart badge; teal buttoned blouse, purple waistband; a small cream/coral medical pouch at the right hip. Her single continuous gently curved fish tail has pastel iridescent lavender-pink-purple/rainbow scales and ends in one connected two-lobed fish fin sweeping to her right. No legs, feet, separate tails, wing fins, adult anatomy or glamour.

Action and geometry: full head, hair, shoulders, two attached arms, torso and entire curved tail visible, in a front three-quarter view. Both elbows stay close to her sides; her forearms and clearly joined small hands meet just below the chest, gently rubbing a modest cream/mint soap lather. The hands are the readable working focus, away from her face. Her attentive gaze points down toward her own working hands. No medical tool held, no bottle, bandage, patient or other character. No basin/background included: the existing painted shell sink will be reused independently. Keep the head/body/fin silhouette quiet and stable, with generous transparent margins.

Art finish: polished hand-painted 2D children's storybook toy-playset art, clear rounded shapes, restrained navy/plum contours, broad flat painted value bands, soft aqua/lavender shadows, matte cream/mint foam and calm pastel colours. Friendly child proportions and simple readable fingers. No photoreal skin, realistic hands, 3D/PBR gloss, glass refraction, skin pores, harsh lighting, excessive tiny detail, neon fringe, UI frame, lettering, water jets, ground/shadow plate or opaque background. Actual clean RGBA transparency outside the complete intact sprite.'''
reference_paths=['assets/opera/worlds/actors/animation/roshan_doctor_sheet_a.png','assets_src/imagegen/opera_roshan_animation_2026-08-09/roshan_doctor_sheet_a_native.png','assets_src/concepts/opera_jobs_flat_2026-07-21/cards/opera_job_doctor_outfit_signature_action_pose.png','assets_src/concepts/opera_jobs_flat_2026-07-21/cards/opera_job_doctor_outfit_action_silhouette.png']
profile={'status':'GENERATION_PENDING_UNBOUND','baseline':'5b8bfb989ca8012924115d45901252808edb9b62','source_revision':'8e41deaf34f925869395cd8ab0affefe89f89ab5','gap':'WASH-DOCTOR-WORK-POSE-01: approved work row has stethoscope, hand/tool-at-face and bandage poses, no intact two-hands soap-washing pose. Source and concept inventory examined; two signature-action concept cards depict stethoscope/patient examination. Existing painted sink is reusable and will not be regenerated. Selected actual washing views score work meaning2.7; approach/contact remains separately unproved.','use_case':'illustration-story','method':'Built-in image_gen fresh text-only generation; no images bound/uploaded or copied as appearance pixels.','prompt':prompt,'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'text_identity_inventory':[{'path':p,'sha256':hashlib.sha256((r/p).read_bytes()).hexdigest(),'role':'Local inventory/identity description only; not tool-bound generation reference.'} for p in reference_paths],'rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-03','DL-ASSET-05','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-READ-01'],'source_score':None,'native_fit_score':None,'complete_action_score':None,'owner_approval':'PENDING','runtime_binding':'UNBOUND; originals retained.'}
(out/'ATTEMPT_01_PROMPT.json').write_text(json.dumps(profile,indent=2)+'\n',encoding='utf-8')
shutil.copyfile(Path(__file__),out/'executed_prepare_doctor_wash_source_v1.py')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['scope']+=' Named doctor washing pose gap: inventory approved doctor sheet and source masters/concept action cards, then fresh text-only image generation of one connected washing pose. Preserve originals and use existing painted sink; all identity/source/native/timed/owner scores pending.';d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in out.rglob('*') if x.is_file()]+[root.relative_to(r).as_posix()+'/failed_finalize_selected_wash_review_v3.py',root.relative_to(r).as_posix()+'/FINALIZER_COUNT_FAILURE_V3.json']));d['validation'].append({'command':'Named washing pose source inventory and first generation brief','result':'PENDING','evidence':'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/ATTEMPT_01_PROMPT.json; existing doctor art lacks intended verb. Generation, identity/source/native/contact/complete-action and owner review pending.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print('Prepared fresh single-pose doctor wash gap; corrected selected-key finalizer uses108 actual keys. Originals retained.')
