from pathlib import Path
import hashlib,json,re,shutil,subprocess
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'audit/job_geode_supported_celebration_v1_20261002';contact=b/'assets_src/imagegen/geologist_geode_contact_v1_20261002'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
ci=read(f/'full_ci_v3/RECEIPT.json');assert ci['status']=='PASS_UNMODIFIED_CURRENT_FULL_SUITE' and ci['source_unchanged'] and len(ci['source_checks'])==377 and len(ci['probe_results'])==82 and all(x['process_exit']==0 for x in ci['probe_results'])
assert all(sha(b/x['path'])==x['before_sha256'] for x in ci['source_checks'])
message=f"Official Godot 4.7.2 unmodified full suite 3 passes 82/82 trusted probes, process 0, with all 377 frozen local source files unchanged (375 rendered sources plus the corrected detector/test files). All {ci['raw_diagnostic_count']} raw engine diagnostics are retained and qualified; a green process does not mean error-free logs or visual acceptance. Suite 2's static model-detection failure remains preserved. Git's LF text bytes are checked separately through the publication newline bridge; image/audio bytes remain literal."
p=f/'index.html';s=p.read_text();a=s.index('<p id="machine-status">');z=s.index('</p>',a)+4;s=s[:a]+'<p id="machine-status">'+message+' <a href="full_ci_v3/RECEIPT.json">Full receipt</a> · <a href="full_ci_v3/ENGINE_DIAGNOSTICS.json">Raw diagnostics</a> · <a href="PUBLICATION_SOURCE_NEWLINE_BRIDGE_PREPARED_V335.json">Literal Windows / canonical Git text comparison</a>.</p>'+s[z:];p.write_text(s,encoding='utf-8',newline='\n')
review=read(f/'REVIEW.json');review['current_machine_evidence']={'receipt':'full_ci_v3/RECEIPT.json','status':ci['status'],'probe_count':82,'literal_local_source_count':377,'source_unchanged':True,'raw_diagnostic_count':ci['raw_diagnostic_count'],'visual_boundary_count':375,'qualification':message};review['qualification']=re.sub(r'Full CI2 failed at model discovery.*?machine boundary\.',message,review['qualification']);write(f/'REVIEW.json',review)
plan=read(f/'PLAN.json');plan['status']='DIRECT_SUPPORTED_GEODE_REVIEW_AND_CURRENT_LOCAL_MACHINE_VERIFICATION_RECORDED';write(f/'PLAN.json',plan)
for relative in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md']:
 p=b/relative;s=p.read_text().replace('fresh suite3 pending on377 machine sources, with all375 rendered sources unchanged.',message).replace('corrected suite3 pending on377 machine sources, no transferred machine/owner acceptance.',message+' No transferred owner acceptance.');p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=p.read_text();a=s.index('## MA-2D-002');z=s.index('\n## ',a+4);lines=s[a:z].splitlines();changed=False
for i,line in enumerate(lines):
 if line.startswith('| history |'):
  assert line.endswith(' |');lines[i]=line[:-2]+' 2026-10-02: a tracked valid WebP compressed payload containing an incidental X3D tag prefix exposed a model-sniff false-positive. The XML document-prefix repair retains disguised XML and binary model detection; expected negative failure, corrected regressions and full377-file/82-probe evidence are recorded in `audit/job_geode_supported_celebration_v1_20261002/MODEL_SNIFF_FALSE_POSITIVE_V328.json`. No screenshot bytes, debt ceiling or migration manifest changed; strict remains UNSATISFIED and lifecycle IN_PROGRESS. |';changed=True
assert changed;s=s[:a]+'\n'.join(lines)+s[z:];p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/job_review_v2_20261001/index.html';s=p.read_text().replace('Full suite 2 stopped in static verification; corrected suite 3 is pending on 377 files.','Full suite 2 static failure is preserved; corrected suite 3 passes 82/82 on all 377 unchanged frozen local sources.');s=re.sub(r'<p id="ci">.*?</p>','<p id="ci">'+message+'</p>',s);p.write_text(s,encoding='utf-8',newline='\n')
for folder in [f,contact]:
 write(folder/'HANDOFF_ROUTE_M.json',{'status':'REVIEW_PUBLICATION_PENDING','repository':'Ebonyks/mermaid-roshan-reef','branch':'codex/job-art-review-v2-20261001','review_entry':'audit/job_review_v2_20261001/index.html','recipient_access_mode':'Anonymous read of established public GitHub repository; no visibility/access changes','baseline':'bc2d14160a3f532895ed95c5db646e8cf0b451ad','qualification':'Topic review checkpoint only. Publication requires exact immutable manifest/payload/reference GET+SHA checks. No dev/master integration, all-job/owner approval or release.'})
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
p=b/'ASSET_LICENSES.md';s=p.read_text();s+='\n| `audit/job_geode_supported_celebration_v1_20261002/attempt_01/**`, `attempt_02/**`, `browser_*.png`; `assets_src/imagegen/geologist_geode_contact_v1_20261002/BROWSER_SOURCE_REVIEW_V332.png` | Actual authorized game captures and documentary contact-source browser review; original asset provenance stays attached to source rows | **Project-authored review evidence** | Respective `PLAN.json`, capture/review JSON and source generation receipts | Native game frames retained with hashes; ordered boards and browser backgrounds are review display only. Rejected trial/generation evidence separate; no device/child/owner acceptance. |\n';p.write_text(s,encoding='utf-8',newline='\n')
for name,folder in [('job-geode-supported-celebration-20261002.json',f),('job-geode-contact-source-20261002.json',contact)]:
 p=b/'design/audit_impacts'/name;d=read(p);d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in folder.rglob('*') if x.is_file()}|{'ASSET_LICENSES.md'});write(p,d)
assert all(sha(b/x['path'])==x['sha256'] for x in read(f/'SOURCE_CURRENT_BEFORE_CAPTURES.json')['source_files'])
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(b/'audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v33.py')],cwd=b,check=True)
p=b/'tmp/v2_preview_allowed.json';write(p,sorted(set(read(p))|set(read(b/'design/audit_impacts/job-geode-supported-celebration-20261002.json')['files'])|set(read(b/'design/audit_impacts/job-geode-contact-source-20261002.json')['files'])))
print(message)
