from pathlib import Path
import copy,datetime,hashlib,html,json,re,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=r/'audit/job_geode_supported_celebration_v1_20261002';live=r/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat();prefix=f.relative_to(r).as_posix()
snapshot=read(f/'SOURCE_CURRENT_BEFORE_CAPTURES.json');assert len(snapshot['source_files'])==375 and all(sha(r/x['path'])==x['sha256'] for x in snapshot['source_files'])
views=[];frames=[];boards=[];ranges={};state_hits={};contact_checks=[]
for width in [1280,1600]:
 assert read(f/f'runtime_gate/capture{width}v2.receipt.json')['status']=='PASS'
 cap=read(f/f'attempt_02/CAPTURE_{width}.json');width_frames=[];state_hits[width]={i:[] for i in range(7)}
 for x in cap['views']:
  assert sha(r/x['path'])==x['sha256'];x.update(direct_review=True,review_method='Complete native canvas directly inspected on whole-frame ordered still boards; key details also inspected at native size.',owner_acceptance=None)
  name=x['state'];scores={'room_context':2.8,'actor_work_contact':2.7}
  if x.get('surface',{}).get('mode')=='geology_geode':scores.update(specimen_material=4.6,object_progression=4.5,rooted_crystals=4.6)
  elif 'pan' in name:scores.update(pan_material=4.6,panning_action=3.8)
  elif x.get('surface',{}).get('mode')=='geology_fossil':scores.update(fossil_material=4.6,clearing_and_piece_geometry=3.9)
  if 'library' in name:scores={'library_material':4.6,'geologist_crest':4.5,'caption_placement':4.0}
  if 'menu' in name:scores={'geologist_menu_icon':4.6}
  if name=='invitation' and x['phase_index']==3:scores.update(closed_invitation=4.5)
  x['scores']=scores;views.append(x)
 for x in cap['motion_frames']:
  assert sha(r/x['path'])==x['sha256']
  if not x['act_active']:
   lane='earned_library_return';scores={'library_material':4.6,'caption_placement':4.0};evaluation='Actual saved-star Library return; small painted geode crest remains legible. The caption placement remains a separate weak relationship when shown.'
  elif x['celebration_stage']:
   lane='earned_supported_celebration';scores={'specimen_material':4.6,'rooted_crystals':4.6,'specimen_support_relationship':4.5,'slab_material':4.6,'slab_mounting':4.5,'whole_stage_context':4.1};evaluation='Both opened halves stay seated on the same painted slab. The geode does not bounce or release minerals; character cheer and confetti remain separate. Flat curtain/wall/floor materials keep the whole stage below the draft floor.'
   assert x['goal_anchor']=='painted_geology_display_slab'
   contact_checks.append({'width':width,'index':x['index'],'position':x['goal_position'],'size':x['goal_size'],'anchor':x['goal_anchor']})
  else:
   lane='geode_opening_and_completion_hold';scores={'specimen_material':4.6,'opening_progression':4.5,'rooted_crystals':4.6,'work_support':4.6,'actor_contact':2.7,'work_to_clap':4.0,'room_context':2.8};evaluation='The stone opens through authored pictures around a stable base; all visible minerals remain attached inside the shell. Roshan works remotely, then changes to clap; this does not pass embodied hand contact.'
   pull=float(x['surface'].get('pull',0));state=0 if pull<=0 else min(6,1+int(pull/20));state_hits[width][state].append(x['index']);x['observed_authored_state']=state
  x.update(direct_review=True,review_method='Every consecutive rendered frame directly inspected in row-major complete ordered boards; key transition/rest/return details inspected at native size.',review_lane=lane,scores=scores,evaluation=evaluation,owner_acceptance=None)
  width_frames.append(x);frames.append(x)
 ranges[width]={lane:[min(x['index'] for x in width_frames if x['review_lane']==lane),max(x['index'] for x in width_frames if x['review_lane']==lane)] for lane in {x['review_lane'] for x in width_frames}}
 cap.update(status='ALL_SELECTED_STILLS_AND_EVERY_CAPTURED_FRAME_DIRECTLY_REVIEWED',views=[x for x in views if x.get('viewport',[None])[0]==width],motion_frames=width_frames,reviewed_utc=now)
 # Width is also present in each original record; retain all29 actual stills.
 cap['views']=[x for x in views if x['path'] in {v['path'] for v in read(f/f'attempt_02/CAPTURE_{width}.json')['views']}]
 assert len(cap['views'])==29
 write(f/f'attempt_02/CAPTURE_{width}_REVIEWED.json',cap)
 manifest=read(f/f'BOARD_MANIFEST_V2_{width}.json')
 for b in manifest['boards']:assert sha(r/b['path'])==b['sha256'];b.update(direct_review=True,reviewed_utc=now);boards.append(b)
 assert all(state_hits[width][i] for i in range(7)), 'Do not assign a mounted state opinion without a captured occurrence.'
stills=read(f/'STILL_BOARD_MANIFEST_V2.json')['boards']
for b in stills:assert sha(r/b['path'])==b['sha256'];b.update(direct_review=True,reviewed_utc=now)
assert len(frames)==316 and len(views)==58 and len(boards)==27 and len(stills)==10
for width in [1280,1600]:
 checks=[x for x in contact_checks if x['width']==width];assert checks and len({x['position'] for x in checks})==1 and len({x['size'] for x in checks})==1
write(f/'STABLE_SUPPORT_FRAME_EVIDENCE.json',{'status':'ALL_CAPTURED_CELEBRATION_FRAMES_KEEP_EXACT_GOAL_POSITION_AND_SIZE','checks':contact_checks,'frame_ranges':ranges,'authored_state_occurrences':state_hits,'qualification':'Recorded node geometry and direct complete-frame inspection agree. Resource contract separately verifies painted-base contact. Desktop capture, not device/child/owner acceptance.'})
objects=[]
def opinion(id,name,score,art,evaluation,refinement):
 objects.append({'id':id,'name':name,'score':score,'artwork_score':art,'priority':score<=4.5,'evaluation':evaluation,'refinement':refinement,'qualification':'Fresh direct desktop native-canvas/ordered-frame review, provisional drafting opinion. Not device/child/owner or whole-job acceptance.','owner_acceptance':None})
opinion('GEO-USE-LIBRARY','Library geode crest · 50px',4.5,4.5,'Two outlined open halves and their cyan/violet interiors remain recognizable beneath the Geologist card at both widths. Tiny inner facets simplify at this size.','Keep the painted specimen identity; continue phone review and inclusive4.5 refinement.')
opinion('GEO-USE-INVITATION','Closed invitation · 142px',4.5,4.5,'One broad lavender/aqua stone and a clear plum seam remain legible inside the pulse halo. It matches the later opening family.','Keep the same closed source; its floating invitation and overall room context remain separate room priorities.')
opinion('GEO-USE-CELEBRATION','Opened geode · supported normal celebration',4.5,4.6,'Both cream-rimmed cavities hold rooted mineral groups. The unchanged painting rests on the same painted slab throughout every captured curtain-call frame; the generic prop bounce is absent. The former unsupported4.2 placement is replaced.','Retain this mounting. Inclusive4.5 refinement, phone/child/owner review and the flat stage remain open.')
opinion('GEO-USE-DEV-MENU','Developer menu geode · 80px',4.6,4.6,'The pale launcher tile gives the two painted halves sufficient separation; both cavity rims and cyan/violet crystal groups read at both widths.','Retain the same shared atlas/crop and menu caller.')
state_text=['The single rounded shell has a centered seam and fixed base.','The first crack reveals a narrow attached interior.','The widening cavity keeps the cream rim and fixed base.','The bridge state opens two related shell halves without releasing a crystal.','Both wider cavities preserve cyan/violet mineral ownership.','Two clear interiors stay bounded by their shell rims.','The completed pair retains embedded crystals and a stable resting base.']
for i,text in enumerate(state_text):opinion(f'GEO-OPEN-STATE-{i}',f'Authored opening state {i}/6',4.5,4.5,text+' Every recorded occurrence in both-width sequences was inspected.','Keep the authored state family; improve embodied hand work separately and complete phone/owner review.')
for item in [
 ('GEO-CAVITIES','Rooted crystal groups and cavity rims',4.6,4.6,'Cyan and violet facets remain inside both stone cavities through opening, hold and the supported celebration; no loose loot appears.','Retain the accepted cavity painting.'),
 ('GEO-SLAB','Painted work slab',4.6,4.6,'Cream top, lavender side and plum authored contour give the large opening a readable support, without stretching its source ratio.','Keep the source and existing specialist crop.'),
 ('GEO-USE-SUPPORT','Painted celebration support · 330px',4.5,4.6,'The same broad cream/lavender stone supports the opened pair between the cheering actors. Its stable footprint and palette agree with the specimen; sparse confetti briefly crosses it without hiding the cavities.','Retain the supported rest; complete device and owner review.'),
 ('GEO-CONTACT','Roshan hand/tool contact with work',2.7,None,'Roshan still crouches beside the work instead of reaching the slab, seam, brush or pan. A correct object response does not supply visible local hand work.','Author connected working poses and action/return, then review the complete actual route.'),
 ('GEO-CLAP','Work-to-clap transition',4.0,4.6,'The clapping painting remains cheerful and clear, but the shift from the remote crouch is abrupt and does not repair the missing work contact.','Connect working contact to a readable settle and cheer.'),
 ('GEO-ROOM','Flat geology room',2.8,None,'Uniform wall bands, dark wedges and flat floor still conflict with the painted specimen/actors; the wide viewport also retains outer navy strips.','Rebuild the owned room at the required native coverage with clear walk/contact positions.'),
 ('GEO-FLAT-FOSSIL','Room fossil rectangle and spiral',2.7,None,'A solid cream rectangle and single brown ring have no painted slab or fossil form. They remain in invitations, although removed from the new celebration.','Replace through one station/object owner; the duplicate painted-room trial is rejected.'),
 ('GEO-TRAYS','Three empty room tray outlines',2.9,None,'Three cyan rectangular outlines have no tray thickness/material and do not match the active painted panning dish; they are absent from the new celebration.','Resolve station ownership and actual PAN semantics before replacing the room display.'),
 ('GEO-HALO','Room polygon crystal cluster and ring',2.9,None,'Flat sharp polygons and a cyan ring remain an unrelated crystal representation beside/under the rival during room invitations.','Use one properly placed owned painted gallery representation, with clear actor space.'),
 ('GEO-CELEBRATION-CONTEXT','Whole celebration art/context',4.1,None,'The central supported geode and two separated actors are now readable, and old trays/gallery clutter no longer appears. Flat curtains, wall stripes and floor still prevent a whole-scene4.5 pass.','Replace the remaining named stage/environment artwork and review the whole composite.'),
 ('GEO-FOSSIL-CLEARING','Dirt clearing and fossil thirds',3.9,4.6,'Partial clearing still leaves straight rectangular openings and vertical source strips; the assembled fossil painting is coherent but the cut geometry looks mechanical.','Refine clearing edges and conserved piece boundaries, preserving correct puzzle behavior.'),
 ('GEO-PAN-ACTION','Panning action and resting minerals',3.8,4.6,'The painted dish rocks and grains give way to contained cyan specimens. Remote hands and the generic rocking/return keep the complete action weak.','Provide connected grip, alternating work and a quiet physically readable rest.'),
 ('GEO-RETURN-CAPTION','Earned Library return caption',4.0,None,'The earned return and star are correct. The large caption still covers Roshan lower tail and has changing left/right placement on the wider frame.','Refine caption clearance and review the actual return animation.'),
 ('GEO-LIBRARY-ART','Library painted room material',4.6,4.6,'Lavender stone, aqua windows and broad shell furniture remain coherent with the game palette. This material opinion does not approve every actor/caption relationship.','Keep approved room material; fix caption relationship separately.')]:opinion(*item)
details=['attempt_02/native_frames/geode_1280_0111.webp','attempt_02/native_frames/geode_1280_0125.webp','attempt_02/native_frames/geode_1280_0142.webp','attempt_02/native_frames/geode_1600_0120.webp','attempt_02/native_frames/geode_1600_0132.webp','attempt_02/native_views/geologist_1280_normal_library_card.webp','attempt_02/native_views/geologist_1600_phase3_invitation.webp','attempt_02/native_views/geologist_1600_actual_elevator_menu.webp']
details=[{'path':prefix+'/'+p,'sha256':sha(f/p),'direct_review':True} for p in details]
review={'status':'SUPPORTED_GEODE_DIRECT_REVIEW_RECORDED_WHOLE_ROOM_AND_CONTACT_PRIORITIES_OPEN','reviewed_utc':now,'baseline':snapshot['baseline'],'source_files':snapshot['source_files'],'views':views,'frames':frames,'boards':boards,'still_boards':stills,'individual_objects':objects,'native_details':details,'frame_ranges':ranges,'counts':{'native_stills':58,'consecutive_frames':316,'ordered_frame_boards':27,'still_boards':10,'native_details':8,'individual_opinions':len(objects)},'owner_acceptance':None,'review_method':'Every selected complete still and consecutive motion-frame cell inspected; eight key details inspected at native size. Metadata supplies factual indices/geometry, never substitutes direct visual review.','qualification':'Actual Library card, all four intentional viewport-input phases, normal earned curtain call and actual saved-star return; separate elevator developer replay/back. Isolated Main/Castle/save-entry fixture and slowed readback. Geologist has no separate ChapterTwo PHASE_SET or two-act rollout. Other phases have selected stills, not every intervening action frame. Whole training/story/device/child/owner/all-job acceptance remains open. Full CI2 separately pending on375 unchanged literal source files. The first room-prop trial remains rejected and mostly unreviewed; no opinions are inherited from it.'}
write(f/'REVIEW.json',review)
# Show every relevant captured canvas and retain the original failed room layout.
esc=html.escape
relative=lambda p:'../'+p.removeprefix('audit/') if p.startswith('audit/') else '../../'+p
rows=''.join(f'<tr id="{x["id"]}"><td>{esc(x["name"])}</td><td>{x["score"]}/5</td><td>{x["artwork_score"] if x["artwork_score"] is not None else "unassigned"}</td><td>{esc(x["evaluation"])}</td><td>{esc(x["refinement"])}</td></tr>' for x in objects)
gallery=lambda bs:''.join(f'<figure><a href="{esc(str(Path(b["path"]).relative_to(prefix)).replace(chr(92),"/"))}"><img loading="lazy" src="{esc(str(Path(b["path"]).relative_to(prefix)).replace(chr(92),"/"))}" alt="Complete ordered canvas board"></a><figcaption>{b.get("width","")} · '+(f'frames{b["first_frame"]}–{b["last_frame"]}' if 'first_frame' in b else f'{b["count"]} complete selected stills')+'</figcaption></figure>' for b in bs)
native_links=''.join(f'<li><a href="{esc(str(Path(x["path"]).relative_to(prefix)).replace(chr(92),"/"))}">{esc(Path(x["path"]).name)}</a> · {esc(x.get("review_lane",x.get("state","")))}</li>' for x in frames+views)
trial_links=''.join(f'<li><a href="{esc(str(p.relative_to(f)).replace(chr(92),"/"))}">{esc(p.name)}</a> · preserved rejected trial; direct-review coverage only where explicitly recorded</li>' for p in sorted((f/'attempt_01').rglob('*.webp')))
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Supported geode — current illustrated draft</title><style>body{max-width:1180px;margin:28px auto;padding:0 20px;background:#f4f5fc;color:#26304e;font:17px/1.6 system-ui}a{color:#44378d}h1{font-size:2.1rem}img{max-width:100%;height:auto;border-radius:10px}figure{margin:18px 0}figcaption,.note{font-size:.9rem;color:#53546a}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border:1px solid #c8c9d8;text-align:left;padding:9px;vertical-align:top}th{background:#e9e3f4}.pair{display:grid;grid-template-columns:1fr 1fr;gap:14px}details{border:1px solid #c8c9d8;padding:12px;margin:20px 0}summary{cursor:pointer;font-weight:650}@media(max-width:760px){.pair{grid-template-columns:1fr}table{display:block;overflow-x:auto}}</style><body>
<p><a href="../job_review_v2_20261001/index.html">Job graphics library</a> · <a href="../job_artwork_refinement_live/all_items.html">Individual register</a> · <a href="../job_geode_route_emblem_runtime_v1_20261002/index.html">Previous unsupported mounting and complete history</a></p>
<h1>The geode opens and stays on its stone</h1><p>Both halves reveal crystals rooted inside their cavities. The same painted open specimen now rests on the existing painted slab during the earned celebration. Its material is <b>4.6/5</b>; the supported mounting reaches the provisional <b>4.5/5 draft floor</b>, improving the earlier unsupported4.2. The inclusive≤4.5 refinement queue still includes it. This is a narrow improvement: the whole stage remains4.1 and the room/contact defects remain open.</p>
<figure><img src="attempt_02/native_frames/geode_1280_0125.webp" alt="Actual earned celebration with both geode halves resting on a painted stone"><figcaption>Current actual1280×720 Mobile desktop frame125. Source pixels are unchanged; only the supported placement and Geologist-only prop-bounce removal changed.</figcaption></figure>
<p id="machine-status">Fresh unmodified full suite2: pending on375 frozen literal source files. Parser, inference, import, resource contract and both actual-route captures pass separately. PreviousL machine evidence does not transfer to this source.</p>
<p>All58 selected native stills and all316 consecutive opening/celebration/real-return frames were directly inspected on27 ordered frame boards and10 still boards, with eight native-size details. Normal Library picture-card entry, all four intentional activities, production completion callback, saved star and exact Library return are exercised; the developer elevator/replay/back is separate. Main/Castle entry and save isolation are fixtures. Other activities have selected stills; their intervening animation frames, ordinary training/story entry, target phone, child and owner acceptance remain open.</p>
<h2>Individual current opinions</h2><p>Source material and mounted relationships are scored separately. No absent/hidden source is assigned an invented material score; no5/5 or whole-job approval is claimed.</p><table><thead><tr><th>Item</th><th>Mounted/relationship</th><th>Material</th><th>Written evaluation</th><th>Next refinement</th></tr></thead><tbody>'''+rows+'''</tbody></table>
<h2>Stable support and actual sequencing</h2><p>Every captured curtain-call frame has the exact same220px goal rectangle at(530,309.9352) on the1280 canvas. Its centered painted bottom sits at y490 on the slab; the one geometry owner supplies both placement and support. Actor cheer/confetti move separately. <a href="STABLE_SUPPORT_FRAME_EVIDENCE.json">Frame-by-frame geometry/state indices</a> · <a href="runtime_gate/contractv2.receipt.json">Engine resource/contact check</a> · <a href="SOURCE_CURRENT_BEFORE_CAPTURES.json">375-file literal boundary</a>.</p>
<p>The backdrop loads only the existing1024² slab source (nominal4MiB RGBA) via the same clipped atlas region. Source files and alpha stay unchanged. ResourceLoader sharing is checked; target-device VRAM/transparent-overdraw/fps are unmeasured. The opened atlas retains its separately recorded8MiB nominal source footprint.</p>
<details open><summary>Every captured opening/celebration/earned-return frame — 27 complete ordered boards</summary>'''+gallery(boards)+'''</details>
<details><summary>All58 selected complete canvases — 10 ordered still boards</summary>'''+gallery(stills)+'''</details>
<details><summary>All374 current native files — individual original links</summary><ol>'''+native_links+'''</ol></details>
<h2>Rejected room-prop reuse trial</h2><p>The reviewed painted sources remain good material4.6. Their trial mounting failed: duplicate active fossil/pan invitations, Roshan overlapping the lower specimen/dish, and the rival apparently standing on a mineral. Named relationships scored3.2/3.0/3.1. These room changes are removed from the current candidate; the original weak room props remain honest priorities for a separate owned-object/background rebuild. <a href="ROOM_PROP_TRIAL_REJECTION_V324.json">Four explicitly reviewed trial views and rejection reasons</a>.</p>
<div class="pair"><figure><img loading="lazy" src="attempt_01/native_views/geologist_1280_phase1_invitation.webp" alt="Rejected duplicate fossil layout"><figcaption>Rejected duplicate fossil and actor overlap.</figcaption></figure><figure><img loading="lazy" src="attempt_01/native_views/geologist_1280_phase2_invitation.webp" alt="Rejected duplicate panning dish layout"><figcaption>Rejected duplicate pan and actor overlap.</figcaption></figure></div>
<details><summary>Every preserved rejected trial native file — unreviewed except four stated views</summary><ol>'''+trial_links+'''</ol></details>
<h2>Written repair priorities and audit boundary</h2><p>Next geology work needs one visible object per station, a painted room with at least2048×2048 native per-screen coverage, clear actor/prop ownership and connected working hands. Existing room references1672×941/1254² do not meet that coverage; upscaling cannot repair it. Fossil grid clearing, pan grip/action/settle and Library-caption clearance retain their individual weak scores. The separately documented all-eight dated WASH review remains available: <a href="../job_wash_root_remaining_sequences_v1_20261002/index.html">2,074 frames /110 opinions across Doctor and Nursery</a>; it does not establish a current washing repair.</p>
<p><a href="PLAN.json">Plan and rules</a> · <a href="REVIEW.json">All written opinions/frame records</a> · <a href="full_ci_v2/RECEIPT.json">Current full regression receipt</a> · <a href="CHECKPOINT_L_REMOTE_VERIFIED.json">PreviousL complete anonymous remote verification</a>. Current finding lifecycles remain open; strict2D, ordinary routes, device/child/owner and comprehensive final approval remain separate. No dev/master integration or release.</p></body></html>'''
(f/'index.html').write_text(page,encoding='utf-8',newline='\n')
# Method-level preservation proof: only the two intended career methods change.
def methods(s):
 matches=list(re.finditer(r'^(?:static )?func (\w+)\(',s,re.M));return {m.group(1):s[m.start():matches[i+1].start() if i+1<len(matches) else len(s)].strip() for i,m in enumerate(matches)}
method_checks=[]
for filename,allowed in [('opera_career_world_2d.gd',{'_anchor_goal_prop','celebrate'}),('opera_world_backdrop_2d.gd',{'setup','_draw_geologist'})]:
 old=methods((f/'baseline'/filename).read_text());new=methods((r/'scripts'/filename).read_text());changed=[k for k in old if old[k]!=new.get(k)];assert set(changed)<=allowed
 method_checks.append({'path':'scripts/'+filename,'changed_existing_methods':changed,'new_methods':sorted(set(new)-set(old)),'unchanged_existing_methods':len(old)-len(changed),'baseline_sha256':sha(f/'baseline'/filename),'current_sha256':sha(r/'scripts'/filename)})
assert (f/'baseline/opera_geology_surface.gd').read_bytes()==(r/'scripts/opera_geology_surface.gd').read_bytes()
write(f/'PRESERVATION_AND_METHOD_DIFF.json',{'status':'SCOPED_METHOD_DIFF_SOURCE_PNGS_AND_GEOLOGY_MECHANICS_UNCHANGED','methods':method_checks,'unchanged_geology_surface':sha(r/'scripts/opera_geology_surface.gd'),'source_inventory_checks':[{'path':x['path'],'sha256':sha(r/x['path']),'unchanged':sha(r/x['path'])==x['sha256']} for x in read(f/'PLAN.json')['inventory'] if x['path'].endswith('.png')],'qualification':'Source proof is separate from the fresh full behavioral suite and visual/device/owner acceptance.'})
shutil.copyfile(__file__,f/'review_tools'/Path(__file__).name)
p=f/'PLAN.json';d=read(p);d.update(status=review['status'],current_review='REVIEW.json',current_capture_attempt='attempt_02',current_full_ci='full_ci_v2/RECEIPT.json');write(p,d)
p=r/'design/05_DOC_LEDGER.md';s=p.read_text();s+='\n| `audit/job_geode_supported_celebration_v1_20261002/index.html` | 🔵 | `SUPPORTING_CURRENT`: all58 native stills/316 real opening-celebration-return frames,27 ordered boards/10 still boards/eight native details directly reviewed. Supported specimen/slab mounting4.5 provisional, rooted/material4.6; whole stage4.1, room2.8/contact2.7/clearing3.9/pan3.8/caption4.0 remain. Duplicate painted room trial rejected; all trial views preserved with only four directly reviewed. Current375-source full suite2 pending, no transferred machine/owner acceptance. |\n';p.write_text(s,encoding='utf-8',newline='\n')
for rel,link in [('audit/MASTER_AUDIT_2026-08-09.md','job_geode_supported_celebration_v1_20261002/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../job_geode_supported_celebration_v1_20261002/index.html')]:
 p=r/rel;s=p.read_text();lines=s.splitlines(keepends=True);note=f'\nSupported geode continuation (2026-10-02): [58 current native stills and316 consecutive actual opening/celebration/earned Library-return frames]({link}) directly reviewed at1280/1600. Unchanged opened painting now stays on the painted slab throughout the normal curtain call; mounting4.5 provisional/rooted material4.6, whole stage4.1/room2.8/contact2.7 remain weak. Painted room reuse trial rejected for duplicate invitations and actor overlap; four named trial views reviewed, all other trial images unreviewed.375-source unmodified full suite2 pending. Training/story/device/child/owner/full all-job acceptance and MA-VIS-006/MA-PLAY-004/MA-OPERA-012 lifecycle states unchanged.\n'
 lines.insert(2,note);p.write_text(''.join(lines),encoding='utf-8',newline='\n')
p=r/'audit/job_review_v2_20261001/index.html';s=p.read_text();at=s.index('</h1>')+5;note='<p id="supported-geode-v325"><a href="../job_geode_supported_celebration_v1_20261002/index.html">Current supported geode: every58 native stills/316 actual frames</a> — specimen mounting4.5/rooted material4.6; whole stage4.1/room2.8/contact2.7 remain. Duplicate painted-room trial rejected; fresh375-source full suite pending.</p>';s=s[:at]+note+s[at:];p.write_text(s,encoding='utf-8',newline='\n')
p=r/'design/audit_impacts/job-geode-supported-celebration-20261002.json';d=read(p);d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in f.rglob('*') if p.is_file()}|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/job_review_v2_20261001/index.html'});d['validation'].append({'command':'Direct every-current-canvas/ordered-frame/individual-object review','result':'PASS','evidence':prefix+'/REVIEW.json; individual weak scores retained, not a whole-game satisfaction claim.'});write(p,d)
allow=r/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|set(d['files'])));
print(json.dumps({'status':review['status'],'counts':review['counts'],'ranges':ranges,'stable_celebration_samples':len(contact_checks),'full_ci_pending':True}))
