from pathlib import Path
import copy,datetime,hashlib,html,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';A=N/'attempt04';M=N/'local_motion_a1';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):t=p.with_name(p.name+'.v609_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-9965f05a-31f1-4030-939d-fbd993f55195.png');dst=A/'native.png';assert not dst.exists();shutil.copyfile(src,dst)
with Image.open(dst) as im:dims=list(im.size);mode=im.mode
plan=read(A/'PLAN.json');sent=(A/'SENT_PROMPT.txt').read_bytes()
write(A/'SOURCE.json',dict(attempt=4,generation_method='built_in_imagegen_precise_object_edit',original_path=str(src),native_path=dst.relative_to(B).as_posix(),native_sha256=sha(dst.read_bytes()),dimensions=dims,mode=mode,native_preserved=True,references=plan['references'],exact_sent_prompt=sent.decode(),prompt_sha256=sha(sent),prompt_file_path=(A/'SENT_PROMPT.txt').relative_to(B).as_posix(),runtime_ready=False,runtime_bound=False,owner_acceptance=None))
ops=[
('exactly_two_owned_mittens',4.6,'Exactly two original coral quilted mittens retain continuous teal-cuff and cream-sleeve attachments; no extra arm or bare fingers.'),
('left_neck_contact',4.5,'The existing left thumb opposes its palm across the short gathered neck immediately beside the oval. The loose fan extends outward beyond the grip.'),
('right_neck_contact',4.5,'The existing right thumb and palm visibly compress the right neck; the hand is no longer merely resting on a fan or finished collar.'),
('pre_twist_semantics',4.5,'Open lengthwise folds continue through both pinches without diagonal winding, strings, closed rings or finished twists. This depicts gathering before closure.'),
('single_continuous_gold_wrapper',4.5,'Neck ridges now bend smoothly into the same belly and fans instead of reading as inserted rigid rods. One gold sheet and one covered oval are legible.'),
('opaque_supported_small_oval',4.5,'The sweet remains completely covered, low and supported near the original table centre; no extra object, exposed red or leftover mat.'),
('outward_fan_ownership',4.5,'Both loose fan ends stay attached outside the short neck grips, retaining enough open paper for the later twists.'),
('character_table_registration',4.5,'The same full scene, costume, sleeve ownership and worktop remain stable enough for this source key. Actual temporal conservation and game placement are not established.'),
('painted_gold_material',4.5,'Flexible shallow gold folds share the belly/fan satin bands, restrained crinkles and plum contours. Remaining dense highlights are an inclusive refinement priority.'),
('inherited_room_graphics',4.4,'The retained detailed factory hierarchy remains independently weak. It is preserved to avoid an unrelated scene redesign, not approved as a current runtime room.'),
('whole_pre_twist_pose',4.5,'Provisional static drafting floor: both owned neck pinches, same opaque supported sweet, flexible continuous gold paper and honest untwisted ends. No motion, whole wrapping or current game/training acceptance.')]
write(A/'DIRECT_REVIEW.json',dict(reviewed_utc=now(),review_method='direct_complete_native_original_imagegen_output_and_prior_attempt_comparison',native_sha256=sha(dst.read_bytes()),status='PRETWIST_GRIP_STILL_4_5_PROVISIONAL_NO_MOTION_OR_RUNTIME_ACCEPTANCE',components=[dict(id=k,score=s,evaluation=e,priority=s<=4.5) for k,s,e in ops],source_pose_score=4.5,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,device_acceptance=None,child_acceptance=None,owner_acceptance=None))
rootplan=read(N/'PLAN.json');rootplan['status']='FOUR_NATIVE_CANDIDATES_REVIEWED_A4_STATIC_GRIP4_5_MOTION_PLANNED';rootplan['attempts'].append(dict(attempt=4,source_pose_score=4.5,status='PROVISIONAL_STATIC_FLOOR_ONLY',review='attempt04/DIRECT_REVIEW.json'));rootplan['source_pose_score']=4.5;write(N/'PLAN.json',rootplan)
write(N/'REVIEW_SUMMARY.json',dict(status='A4_STATIC_GRIP_FLOOR_NO_CURRENT_ACTION_ACCEPTANCE',native_sources=4,individual_source_opinions=44,attempt_scores=[3.2,4.2,4.3,4.5],selected_source='attempt04/native.png',both_owned_grips_score=4.5,pre_twist_stage_score=4.5,flexible_wrapper_score=4.5,inherited_room_score=4.4,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None,remaining=['Complete covering fold trajectory from earlier partial source','Opposing wrist rotations physically twist this same paper while the sweet stays supported','Both hands release beside the stable closed wrapper','Actual job and Opera training placement, input/task consequences, interruptions and ordinary route','Phone/device/child/owner and comprehensive all-job report acceptance']))
prompt='0–0.3s: keep both original coral mitten hands gripping the two short untwisted gold-paper necks beside the same small covered oval on the lavender table. 0.3–1.2s: both wrists turn gently in opposite directions, twisting only those gold-paper necks closed. The left wrist rolls away and the right wrist rolls toward the viewer; both remain attached to their original teal cuffs and cream sleeves. The same small central oval stays supported and fixed on the table; both loose fan ends turn with their own necks. 1.2–1.7s: both mittens loosen their grips and settle just outside the two finished twists, revealing one stable wrapped sweet resting on the table.\nKeep exactly the same girl, two attached mittens, one sweet and one continuous gold wrapper. Preserve painted gold paper, soft open fans, character, scene, camera and table. Small purposeful hand work followed by a quiet settle. No extra hands/fingers/arms, neck rings or strings, unwrapping, growing candy, disappearing wrapper, ghost cuffs, character drift, camera movement or sparkle.\nSound: silence.\n'
M.mkdir();[(M/x).mkdir() for x in ['inputs','prompts','workflows','review_tools','checks']]
old=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/comparison_a6';m=read(old/'MANIFEST.json');renderer=copy.deepcopy(m['renderer'])
for binding in renderer['bindings']:
 source=Path(binding['installed_path']);assert sha(source.read_bytes())==binding['sha256'];shutil.copyfile(old/binding['packet_path'],M/binding['packet_path']);assert sha((M/binding['packet_path']).read_bytes())==binding['sha256']
inputfile=M/'inputs/CANDY-NECK-A1.png'
with Image.open(dst) as im:
 norm=im.resize((896,504),Image.Resampling.LANCZOS);canvas=Image.new('RGB',(896,512),'black');canvas.paste(norm,(0,4));canvas.save(inputfile)
promptfile=M/'prompts/CANDY-NECK-A1.txt';promptfile.write_bytes(prompt.encode());job=dict(id='CANDY-NECK-A1',name='Specific gold-wrapper opposing neck twists and supported release',source_path=dst.relative_to(B).as_posix(),source_sha256=sha(dst.read_bytes()),input_path=inputfile.relative_to(M).as_posix(),input_sha256=sha(inputfile.read_bytes()),prompt_path=promptfile.relative_to(M).as_posix(),prompt_sha256=sha(prompt.encode()),queue_name='candy_neck_twist_a1_20261003',seed=2026100301,owner_approval=None)
manifest=dict(schema='reef.local-candy-motion-study.v1',id='candy-specific-neck-twist-a1-20261003',created_utc=now(),baseline=rootplan['baseline'],acceptance='LOCAL_MOTION_REFERENCE_ONLY',owner_approval=None,runtime_integration=False,authorization='Existing owner direction to use the developed local Comfy workflow for iterative job/action audit; no new model/install, external generation, game binding or cinematic delivery.',intention='Test whether the two source-bound owned grips can visibly twist this same gold paper in opposite directions and release the still-supported sweet.',profile=rootplan['profile'],register=rootplan['emotional_register'],source_status='STATIC_SOURCE_DRAFT_4.5_OWNER_UNASSIGNED',source_review=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix(),source_dimensions=dims,input_transform='Whole1672x941 scene normalized to896x504, black4px top/bottom on896x512; no crop, isolated subject change or repair.',renderer=renderer,jobs=[job],clip_contract=dict(entry='A4 two attached mittens grip untwisted necks of the same covered supported sweet; no covering trajectory supplied by this component.',exit='Both gold necks visibly twisted by opposing wrists, then both mittens released beside one stable table-supported wrapped sweet.',duration_seconds=41/24,timeline=prompt,required_review='All41 native canvases, both owned cuffs/mittens, bilateral maintained grip, opposite rotations, paper response, conserved covered oval/support, both releases, painted wrapper/character continuity. Component motion cannot accept complete wrapping/current game.'),status='INPUT_NORMALIZATION_DIRECT_REVIEW_AND_ADMISSION_PENDING',visual_review=None,complete_action_score=None,intended_component_only=True)
manifest.update({k:job[k] for k in ['source_path','source_sha256','input_path','input_sha256','prompt_path','prompt_sha256','queue_name','seed']});write(M/'MANIFEST.json',manifest)
worker=(B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/review_tools/queue_candy_wrap_a1_v544.py').read_text(encoding='utf-8').replace('assets_src/local_motion/candy_wrap_continuity_v1_20261003','assets_src/imagegen/candy_neck_grip_pose_v1_20261003/local_motion_a1').replace('CANDY-WRAP-A1','CANDY-NECK-A1').replace('build/candy_local_wrap_a1_active_20261003','build/candy_specific_neck_a1_active_20261003');put(M/'review_tools/queue_neck_a1_v609.py',worker.encode())
write(M/'PLAN.json',dict(status='SOURCE_A4_GRIP4_5_NEW_NAMED_NECK_TWIST_RELEASE_GAP',rules=rootplan['rules'],findings=rootplan['findings'],source_review=manifest['source_review'],acceptance='LOCAL_MOTION_REFERENCE_ONLY',quiet_idle_seconds=90,workflow_bindings=7,existing_failures_preserved='All6 whole/fold motion studies remain rejected; this is a new component from a new source pose, not a claim that those failures passed.',required_before_dispatch='Directly inspect complete normalized input, bind source/prompt/seven installed hashes, validate guarded worker.',required_after_render=manifest['clip_contract']['required_review'],runtime_integration=False,owner_approval=None))
esc=lambda x:html.escape(str(x));articles=[]
for i in range(1,5):
 folder=N/f'attempt{i:02d}';review=read(folder/'DIRECT_REVIEW.json');rows=''.join('<tr><td>'+esc(x['id'].replace('_',' '))+'</td><td>'+str(x['score'])+'/5</td><td>'+esc(x['evaluation'])+'</td></tr>' for x in review['components']);articles.append('<article id="attempt%02d"><h2>Attempt %d · %s/5 · %s</h2><img src="attempt%02d/native.png" alt="Full painted wrapper grip attempt %d"><table><thead><tr><th>Individual item</th><th>Draft score</th><th>Evaluation</th></tr></thead><tbody>%s</tbody></table><p><a href="attempt%02d/SOURCE.json">Native, prompt and reference provenance</a> · <a href="attempt%02d/DIRECT_REVIEW.json">Individual review</a></p></article>'%(i,i,review['source_pose_score'],esc(review['status']),i,i,rows,i,i))
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Specific gold wrapper · hand-contact review</title><style>body{max-width:1200px;margin:auto;padding:24px;background:#edf3fb;color:#25334b;font:17px/1.55 system-ui;box-sizing:border-box}h1,h2{line-height:1.2}article{background:white;padding:20px;border-radius:18px;margin:24px 0}img{display:block;width:100%;height:auto}table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;vertical-align:top;border-bottom:1px solid #d8e0eb}p,td{overflow-wrap:anywhere}a{color:#164c83}</style><h1>Specific gold wrapper · do the hands fit?</h1><p><strong>A4 static grip4.5/5 provisional · current in-game WRAP2.8/5.</strong> Both original sleeve-attached mittens now pinch the short untwisted necks of the same supported gold-covered sweet. Motion and current game/training placement still require review. Inherited room hierarchy remains4.4.</p><p><a href="#attempt04">Latest complete grip native and11 evaluations</a> · <a href="../candy_cover_pose_v1_20261003/index.html">Preceding complete-cover/press source</a> · <a href="../../../local_motion/candy_wrap_continuity_v1_20261003/index.html">All six rejected earlier local motion studies</a> · <a href="../../../../audit/job_artwork_refinement_live/all_items.html">All-items library</a> · <a href="PLAN.json">Reuse inventory and scope</a> · <a href="REVIEW_SUMMARY.json">Current acceptance boundaries</a></p><p>Every full native is preserved. A1 had premature tied rings and fan-top contact; A2 reached both grip floors but implied an early twist; A3 made the necks rigid; A4 restores flexible continuous paper. These are source poses, not sequential accepted animation frames.</p>'+''.join(articles)+'<article id="motion"><h2>Opposing neck twists and supported release · local motion reference</h2><p>A bounded study is prepared through the existing quiet-idle/FIFO Comfy workflow. <strong>No rendered sequence or motion score yet.</strong> Source, normalized input, prompt and seven unchanged workflow bindings are recorded. It does not supply the earlier covering fold or accept current game action.</p><p><a href="local_motion_a1/MANIFEST.json">Exact local study manifest</a> · <a href="local_motion_a1/PLAN.json">Component review criteria</a></p></article><p>Full wrapping still requires a coherent fold → cover → gather → opposing twists → release, followed by actual job/training, device, child and owner review. Scores at4.5 remain in the inclusive refinement queue.</p></html>'
page=page.replace('../../../local_motion/','../../local_motion/').replace('../../../../audit/','../../../audit/');put(N/'index.html',page.encode())
shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();rows=[]
for i in range(1,5):
 path=(N/f'attempt{i:02d}/native.png').relative_to(B).as_posix();assert path.encode() not in raw;rows.append('| `'+path+'` | Built-in ImageGen targeted same-scene gold-wrapper grip refinement | Original project generated artwork with OpenAI; character/room/wrapper attribution inherited from references | `'+(N/f'attempt{i:02d}/SOURCE.json').relative_to(B).as_posix()+'` | Entire native preserved separately; individual source review only, including rejected variants. No runtime, motion, cinematic, device, child or owner approval. |')
path=inputfile.relative_to(B).as_posix();rows.append('| `'+path+'` | Non-destructive whole-canvas normalization of A4 for local motion input | Inherits A4 project generated-art attribution | `'+(M/'MANIFEST.json').relative_to(B).as_posix()+'` | One uniform complete-scene resize and black padding only; native unchanged. Reference input only, no delivered gameplay/cinematic pixels. |');put(licenses,raw+('\n'+'\n'.join(rows)+'\n').encode())
d=read(IP);d['scope']+=' Also prepare one guarded local-reference opposing wrist twists and supported-release component from A4, preserving all earlier failures and full wrapping criteria.';d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'][1]=dict(command='Four exact native grip candidates and44 individual source opinions',result='PASS',evidence=(N/'REVIEW_SUMMARY.json').relative_to(B).as_posix()+';A1 3.2/A2 4.2/A3 4.3 preserved rejected,A4 whole static grip4.5 provisional,room4.4. Motion/current WRAP2.8 remain separate.');d['validation'].append(dict(command='Developed local opposing neck-twist/release component from new A4 source',result='PENDING',evidence=(M/'PLAN.json').relative_to(B).as_posix()+';normalized input direct review/admission/render/all41 native motion opinions pending. No new workflow/model/install.'));write(IP,d)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}));print('A4_STATIC_GRIP4_5_PRESERVED',sha(dst.read_bytes()),'SOURCES4_OPINIONS44_COMPONENT_MOTION_PREPARED',flush=True)
