from pathlib import Path
import ast,json,shutil
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json'
s=(B/'audit/job_shared_atlas_state_review_v1_20261003/review_tools/publish_atlas_review_v604.py').read_text(encoding='utf-8')
s=s.replace("C=B/'audit/job_shared_atlas_state_review_v1_20261003'","C=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003'").replace('job-shared-atlas-state-review-20261003.json','job-candy-neck-grip-pose-20261003.json').replace("BASE='c7817974fb23913c1d764c718a70a5932cacb883'","BASE='876169d77d45f5fd2b5956eeda4f1e6da9926f19'").replace("MAP='audit/job_review_v2_20261001/SHARED_PROP_CELL_REVIEW_FILES_V24.json'","MAP='audit/job_review_v2_20261001/CANDY_SPECIFIC_GRIP_MOTION_FILES_V25.json'").replace("PRIOR='audit/job_review_v2_20261001/CANDY_COVER_POSE_FILES_V23.json'","PRIOR='audit/job_review_v2_20261001/SHARED_PROP_CELL_REVIEW_FILES_V24.json'").replace('v24_unchanged_dependency_shards','v25_unchanged_dependency_shards').replace('tmp/atlas_publish_v604','tmp/neck_publish_v618').replace('tmp/atlas_remote_v604','tmp/neck_remote_v618').replace('tmp/atlas_sealed_v604','tmp/neck_sealed_v618').replace('v604_next','v618_next').replace('PUBLICATION_BOUNDARY_V604.json','PUBLICATION_BOUNDARY_V618.json').replace('EXACT_SHARDED_ATLAS_REVIEW_BYTES_SEALED','EXACT_SHARDED_NECK_REVIEW_BYTES_SEALED')
start=s.index('def checks():\n');end=s.index('\ndef run(',start)
checks='''def checks():
    assert git('rev-parse','HEAD').decode().strip()==BASE and git('branch','--show-current').decode().strip()==BRANCH
    for label in ['authority','development','document_tests','game2d','register_parts']:assert read(C/'gates_v2'/(label+'.receipt.json'))['status']=='PASS',label
    sys.path.insert(0,str(L/'review_tools'));from register_parts_v51 import load_register
    reg=load_register(L);assert reg['display_revision']=='V52' and len(reg['items'])==2142 and reg['counts']['inclusive_current_source_priorities']==1045 and reg['counts']['unique_source_file_priorities']==668 and reg['counts']['unreviewed_current_source']==294
    stamp=read(L/'CURRENT_BOUNDARY_REFRESH.json');assert stamp['registry_items']==stamp['registered_source_matches']==2142 and stamp['assembled_registry_parts_verified'] and stamp['registry_root_sha256']==sha((L/'ALL_ITEMS.json').read_bytes()) and stamp['registry_parts']==reg['item_shards']
    previous=read(C/'previous_v51/ALL_ITEMS.json');current=read(L/'ALL_ITEMS.json');assert current['items'][:2050]==previous['items'] and current['item_shards']==previous['item_shards']
    review=read(C/'REVIEW_SUMMARY.json');assert review['native_sources']==4 and review['individual_source_opinions']==44 and review['both_owned_grips_score']==4.5 and review['motion_reference_component_score']==1.8 and not review['runtime_bound'] and review['owner_acceptance'] is None
    for i in range(1,5):
        folder=C/f'attempt{i:02d}';r=read(folder/'DIRECT_REVIEW.json');source=read(folder/'SOURCE.json');assert len(r['components'])==11 and sha((folder/'native.png').read_bytes())==r['native_sha256']==source['native_sha256'] and r['motion_score'] is None and not r['runtime_bound']
    motion=read(C/'local_motion_a1/attempt01/DIRECT_REVIEW.json');assert motion['native_frames_reviewed']==len(motion['frames'])==41 and motion['component_opinions']==len(motion['components'])==10 and motion['whole_component_score']==1.8 and not motion['runtime_integration'] and all(x['direct_complete_native_review'] and sha((B/x['path']).read_bytes())==x['sha256'] for x in motion['frames'])
    assert read(C/'previous_AA_remote_verified/RESULT.json')['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES'
    boundary=read(P/'PRODUCTION_BOUNDARY.json');assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members'])
'''
s=s[:start]+checks+s[end:];start=s.index("if phase=='--prepare':\n");end=s.index("if phase=='--seal':\n",start)
prepare='''if phase=='--prepare':
    checks();assert read(C/'previous_AA_remote_verified/RESULT.json')['revision']==BASE
    dst=C/'review_tools'/Path(__file__).name
    if Path(__file__).resolve()!=dst.resolve():shutil.copyfile(__file__,dst)
    attrs=B/'.gitattributes';old=attrs.read_bytes();extra=('\\n'+MAP+' -text\\n'+SHARDS+'/** -text\\n').encode();assert (MAP+' -text').encode() not in old;n=attrs.with_name(attrs.name+'.v618_next');n.write_bytes(old+extra);n.replace(attrs)
    write(B/MAP,dict(status='PENDING_EXACT_GRIP_REJECTED_MOTION_REVIEW_STAGED_SEAL',base_revision=BASE,qualification='Placeholder metadata only;no predicted remote or creative acceptance.'))
    d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in C.rglob('*') if p.is_file()}|{MAP,'.gitattributes',C.relative_to(B).as_posix()+'/PUBLICATION_BOUNDARY_V618.json'})
    for v in d['validation']:
        if v['command']=='Final expanded source-review structural/document/2D no-regression/register gates':v.update(result='PASS',evidence=C.relative_to(B).as_posix()+'/gates_v2;actual final authority/development,52 document tests,9 register-integrity tests and2D no-regression all pass. Strict2D remains UNSATISFIED;visual/action/owner independent.')
    write(IP,d);print('PREPARED_EXACT_GRIP_REJECTED_MOTION_PUBLICATION_SCOPE',len(d['files']),flush=True);sys.exit(0)
'''
s=s[:start]+prepare+s[end:]
oldline=next(x for x in s.splitlines() if 'manifest=dict(schema=' in x);assert "qualification='V51" in oldline
qualification='V52 known2142 entries/1290 primary sources/1045 inclusive source-cell-region priorities/668 unique source priorities/294 unreviewed primary sources. Four same-scene built-in ImageGen grip natives and44 individual source opinions:A1 3.2,A2 4.2,A3 4.3 rejected,A4 both owned untwisted flexible-gold neck grips/whole still4.5 provisional,inherited room4.4. One existing guarded local Comfy opposing twist/release component1.8 rejected;all41 native canvases/41 pose opinions/10 component opinions inspected. Gold fans detach from central wrapper into cuffs,no proper opposing twists or release. Exact submitted manifest/input/prompt/seven unchanged workflows and native outputs preserved. Prior2050 register records and literal88-item part unchanged,existing4MiB ceiling retained,52 document tests/9 register integrity tests pass. Actual browser proof preserved;all783 production literals/current WRAP2.8 unchanged. Complete prior AA24298 anonymous remote rows preserved losslessly. No runtime,protected originals,3D,security/gates/workflows,finding lifecycle,dev/master integration/release or complete wrapping/job/training/device/child/owner/comprehensive all-job acceptance.'
newline=oldline[:oldline.index("qualification='V51")]+"qualification="+repr(qualification)+')';s=s.replace(oldline,newline)
start=s.index("message=OUT/'COMMIT_MESSAGE.txt';");end=s.index("\nrun('commit'",start)
message='Refine specific gold-wrapper neck grips and reject broken motion\n\nPreserve four full ImageGen candidates and44 individual source opinions. A1 premature tied rings/fan contact3.2,A2 early twist4.2,A3 rigid neck material4.3 rejected. A4 both owned mitten neck grips,untwisted flexible gold paper and whole source4.5 provisional;inherited room4.4 remains weak.\n\nTest opposing wrist twists and supported release through the existing guarded local Comfy workflow. All41 native decoded reference canvases/41 pose opinions/10 components are inspected;whole component1.8 rejected because gold fans detach from central paper into cuffs,opposing twists and stable release fail. Preserve exact submitted manifest,prompt,input,seven workflows and outputs. No game or cinematic binding.\n\nExtend the bounded illustrated V52 library to2142 entries/1045 inclusive priorities/668 unique priority sources/294 pending primary reviews,keeping all2050 prior records and88-item part unchanged. Save actual browser proof,52 document tests/9 integrity tests and all24298 prior AA anonymous remote verification rows. All783 current production members remain unchanged and current WRAP stays2.8. Full wrapping,current job/training/device/child/owner/comprehensive approval,integration and release remain open.\n'
s=s[:start]+"message=OUT/'COMMIT_MESSAGE.txt';message.write_text("+repr(message)+",encoding='utf-8',newline='\\n')"+s[end:]
s=s.replace("for name,args in [('authority',['tools/audit_document_authority.py']),('development',['tools/audit_development.py','--base','auto']),('game2d',['tools/audit_game_2d.py','--regression-gate'])]:run('precommit_'","for name,args in [('authority',['tools/audit_document_authority.py']),('development',['tools/audit_development.py','--base','auto'])]:run('precommit_'")
ast.parse(s);p=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/publish_neck_review_v618.py');p.write_bytes(s.encode());shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
d=json.loads(IP.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()});t=IP.with_name(IP.name+'.v618_next');t.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n');t.replace(IP);print('EXACT_TOPIC_PUBLISHER_BUILT_PENDING_FINAL_GATES',flush=True)
