from pathlib import Path
import copy,datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';M=N/'local_motion_a1';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json';G=N/'gates_v2';G.mkdir()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):t=p.with_name(p.name+'.v617_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
submitted=read(M/'MANIFEST.json');submitted.pop('component_motion_score');submitted['visual_review']=None;submitted['status']='EXACT_SOURCE_INPUT_PROMPT_SEVEN_BINDINGS_DIRECTLY_REVIEWED_ADMISSION_CHECK_PENDING';raw=(json.dumps(submitted,ensure_ascii=False,indent=2)+'\n').encode();state=read(M/'attempt01/DISPATCH_STATE.json');assert sha(raw)==state['manifest_sha256'];put(M/'attempt01/SUBMITTED_MANIFEST.exact.json',raw)
write(M/'attempt01/SUBMISSION_BOUNDARY_CHECK.json',dict(status='EXACT_SUBMITTED_MANIFEST_BYTES_RECONSTRUCTED_AND_SHA_VERIFIED',checked_utc=now(),submitted_manifest_sha256=sha(raw),dispatch_state_sha256=sha((M/'attempt01/DISPATCH_STATE.json').read_bytes()),qualification='Current manifest adds observed review status;the literal pre-dispatch manifest is separately preserved and matches the actual OS-locked worker receipt. Reconstruction changes only those post-review metadata fields;no model/input/prompt/graph bytes change.'))
dst=N/'BROWSER_MOTION_PROOF_V616.jpg';shutil.copyfile(Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/NECK_MOTION_PROOF_V616.jpg'),dst)
with Image.open(dst) as im:dims=list(im.size);assert im.format=='JPEG'
write(N/'BROWSER_MOTION_VERIFY_V616.json',dict(status='ACTUAL_REJECTED_MOTION_VIDEO_AND41_INDIVIDUAL_ARTICLES10_COMPONENTS_VERIFIED',checked_utc=now(),url='http://127.0.0.1:8880/assets_src/imagegen/candy_neck_grip_pose_v1_20261003/local_motion_a1/index.html?revision=motion-a1#frame30',individual_frame_articles=41,component_rows=10,video_ready_state=4,video_source='attempt01/candy_neck_twist_a1_20261003_20261003T110741Z_ece477_00002_.mp4',directly_observed_frame=30,frame_native_dimensions=[896,512],frame_loaded=True,frame_bounds=dict(top=100.109375,bottom=719.53125,height=619.421875),viewport=[1280,720],document_width=1265,screenshot_path=dst.relative_to(B).as_posix(),screenshot_sha256=sha(dst.read_bytes()),screenshot_dimensions=dims,layout_repair='Exact7:4 native image aspect reserved to prevent lazy-loading anchor shifts;no artwork edit.',qualification='Actual desktop QA of the rejected local reference report and loaded frame30 only;not a claim that all offscreen lazy images were browser-loaded or that gameplay/device/child/owner passed. All41 natives were independently seen on unchanged original-size boards.'))
p=B/'ASSET_LICENSES.md';raw=p.read_bytes();row=('\n| `'+dst.relative_to(B).as_posix()+'` | Actual browser proof of rejected local neck-motion frame30 | Original project QA layout and inherited displayed generated-study attribution | `'+(N/'BROWSER_MOTION_VERIFY_V616.json').relative_to(B).as_posix()+'` | QA screenshot only;shows rejected fan/cuff topology. No production or creative acceptance. |\n').encode();assert dst.relative_to(B).as_posix().encode() not in raw;put(p,raw+row)
boundary=read(B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json');assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members']);write(N/'PRODUCTION_BOUNDARY_CHECK_AFTER_REVIEW.json',dict(status='ALL783_LITERAL_CURRENT_PRODUCTION_MEMBERS_UNCHANGED_AFTER4_NATIVES_AND41_LOCAL_FRAMES',checked_utc=now(),source_boundary='assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json',boundary_sha256=sha((B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json').read_bytes()),members=783,current_wrap_score=2.8,runtime_changed=False,qualification='Literal unchanged-production evidence only;no visual/action/owner pass.'))
write(N/'NEXT_ACTION_PLAN.json',dict(status='OPEN_NOT_DISPATCHED',specific_gap='No exact same-scene supported double-twist endpoint or released endpoint exists. Current local component1.8 detaches fans into cuffs;source-grip4.5 alone does not control the next topology.',reuse_inventory='Preserve and use A4 correct untwisted grip with the covered small supported gold oval. Earlier contact atlases/current decorative wrapper cannot prove these exact scene/owned-hand endpoints.',next_required='Targeted ImageGen complete same-scene endpoint studies for opposing wrists with both short gold necks physically twisted,then both mittens released beside the stable wrapped sweet;audit individually before any further local motion study. Preserve all failed variants,full fold-to-release objective and current game/training requirements.',no_source_score_transfer=True,current_game_wrap_score=2.8,owner_acceptance=None))
old=(N/'review_tools/run_neck_gate_v613.py').read_text(encoding='utf-8').replace('gates_v1','gates_v2').replace('CANDIDATE_NECK_SOURCE_V613.json','CANDIDATE_NECK_SOURCE_V617.json');put(N/'review_tools/run_neck_gate_v617.py',old.encode());shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}|{(G/(label+suffix)).relative_to(B).as_posix() for label in ['authority','development','document_tests','game2d','register_parts'] for suffix in ['.stdout.log','.stderr.log','.receipt.json']}|{(G/'CANDIDATE_NECK_SOURCE_V617.json').relative_to(B).as_posix()});d['validation'].append(dict(command='Actual rejected motion-report browser verification and exact submitted manifest recovery',result='PASS',evidence=(N/'BROWSER_MOTION_VERIFY_V616.json').relative_to(B).as_posix()+';41 frame articles/10 components,video metadata/loaded frame30/no overflow;submitted manifest SHA matches original dispatch state. Page QA only.'));d['validation'].append(dict(command='Final expanded source-review structural/document/2D no-regression/register gates',result='PENDING',evidence=G.relative_to(B).as_posix()+';new41-frame reference/review/source/report additions require fresh final scope checks. Preliminary v1 actual gates preserved.'));write(IP,d)
members=[]
for path in d['files']:
 p=B/path
 if not p.is_file() or path.startswith(G.relative_to(B).as_posix()+'/'):continue
 members.append(dict(path=path,bytes=p.stat().st_size,sha256=sha(p.read_bytes())))
write(G/'CANDIDATE_NECK_SOURCE_V617.json',dict(status='EXACT_COMPLETE_GRIP_AND_REJECTED_LOCAL_MOTION_REVIEW_SOURCE_FROZEN',baseline=d['baseline'],frozen_utc=now(),members=members,member_count=len(members),qualification='Actual complete source/rejected-motion/browser review state before final checks. Later check/impact/publication metadata separately sealed;no current game/owner/integration/release acceptance.'))
print('FINAL_GRIP_REJECTED_MOTION_SCOPE_FROZEN',len(members),'SUBMITTED_SHA',sha((M/'attempt01/SUBMITTED_MANIFEST.exact.json').read_bytes()),flush=True)
