from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json';G=N/'gates_v1';G.mkdir()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):t=p.with_name(p.name+'.v613_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
dst=N/'BROWSER_REPORT_PROOF_V612.jpg';shutil.copyfile(Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/NECK_REPORT_PROOF_V612.jpg'),dst)
with Image.open(dst) as im:dims=list(im.size);fmt=im.format
assert fmt=='JPEG';write(N/'BROWSER_VERIFY_V612.json',dict(status='FOUR_LOADED_COMPLETE_NATIVE_IMAGES44_OPINIONS_AND_V52_SOURCE_RECORD_VERIFIED',checked_utc=now(),report_url='http://127.0.0.1:8880/assets_src/imagegen/candy_neck_grip_pose_v1_20261003/index.html?revision=grip-v4#attempt04',loaded_native_images=4,native_dimensions=[1672,941],individual_opinions=44,viewport=[1280,720],document_width=1265,full_a4_image_bounds=dict(top=15.46875,bottom=641.296875,width=1112,height=625.828125),screenshot_path=dst.relative_to(B).as_posix(),screenshot_sha256=sha(dst.read_bytes()),screenshot_dimensions=dims,library_url='http://127.0.0.1:8880/audit/job_artwork_refinement_live/all_items.html?revision=grip-v52',library_registered_items=2142,library_inclusive_priorities=1045,library_unreviewed_primary_sources=294,filtered_id='CANDY-NECK-SOURCE-04',filtered_source_score=4.5,filtered_loaded_image=True,filtered_mounted_score=None,filtered_complete_action_score=None,qualification='Actual desktop source report/library observation only;pending local motion/current game/device/child/owner acceptance separate.'))
p=B/'ASSET_LICENSES.md';raw=p.read_bytes();row=('\n| `'+dst.relative_to(B).as_posix()+'` | Actual local-browser screenshot of gold-wrapper grip review | Original project QA layout and displayed-art attribution inherited | `'+(N/'BROWSER_VERIFY_V612.json').relative_to(B).as_posix()+'` binds actual loaded natives and source-only record | QA proof only;no game/motion/cinematic/device/child/owner approval. |\n').encode();assert dst.relative_to(B).as_posix().encode() not in raw;put(p,raw+row)
remote=N/'previous_AA_remote_verified';remote.mkdir();source=B/'tmp/atlas_remote_v604';r=read(source/'RESULT.json');assert r['status']=='PASS_ALL_ANONYMOUS_REMOTE_BYTES' and r['revision']=='876169d77d45f5fd2b5956eeda4f1e6da9926f19' and r['files_including_manifest']==24298 and not r['failed_files'];shutil.copyfile(source/'RESULT.json',remote/'RESULT.json');shutil.copyfile(B/'tmp/atlas_publish_v604/RECEIPT.json',remote/'PUBLICATION_RECEIPT.json')
raw=(source/'VERIFICATION_JOURNAL.jsonl').read_bytes();lines=raw.splitlines(keepends=True);assert len(lines)==24298 and all(json.loads(x)['matches'] for x in lines);parts=[];group=[];size=0
def emit():
 payload=b''.join(group);p=remote/f'JOURNAL_{len(parts)+1:03d}.jsonl';p.write_bytes(payload);assert len(payload)<=900000;parts.append(dict(path=p.relative_to(B).as_posix(),bytes=len(payload),sha256=sha(payload),rows=len(group)))
for line in lines:
 if group and size+len(line)>899000:emit();group=[];size=0
 group.append(line);size+=len(line)
if group:emit()
assert b''.join((B/x['path']).read_bytes() for x in parts)==raw;write(remote/'JOURNAL_SHARDS.json',dict(status='ALL24298_EXACT_AA_ANONYMOUS_REMOTE_ROWS_LOSSLESSLY_PRESERVED',revision=r['revision'],original_bytes=len(raw),original_sha256=sha(raw),original_rows=len(lines),parts=parts,shard_max_bytes=900000,qualification='Literal complete previous revision proof only;not proof of this new grip study or hosted/creative acceptance. Initial pending publication receipt retained separately.'))
H=N/'previous_AA_hosted_snapshot';H.mkdir();cmd=['C:/Program Files/GitHub CLI/gh.exe','run','view','37117318744','--repo','Ebonyks/mermaid-roshan-reef','--json','databaseId,headSha,status,conclusion,url,jobs'];rr=subprocess.run(cmd,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(H/'RUN.json').write_bytes(rr.stdout);(H/'RUN.stderr.log').write_bytes(rr.stderr);assert rr.returncode==0;data=json.loads(rr.stdout);assert data['headSha']==r['revision'];write(H/'VERIFICATION.json',dict(status='ACTUAL_PRIOR_EXACT_HEAD_HOSTED_SNAPSHOT',checked_utc=now(),command=cmd,exit_code=rr.returncode,revision=data['headSha'],run_id=data['databaseId'],run_status=data['status'],run_conclusion=data['conclusion'],jobs=[dict(name=j['name'],status=j['status'],conclusion=j['conclusion']) for j in data['jobs']],raw_sha256=sha(rr.stdout),qualification='Observed actual status only. Pending jobs remain pending;this never predicts new review hosted or visual/action/owner acceptance.'))
old=(B/'assets_src/imagegen/candy_cover_pose_v1_20261003/review_tools/run_cover_gate_v593.py').read_text(encoding='utf-8');old=old.replace('candy_cover_pose_v1_20261003','candy_neck_grip_pose_v1_20261003').replace('CANDIDATE_COVER_SOURCE_V593.json','CANDIDATE_NECK_SOURCE_V613.json').replace("'game2d':['tools/audit_game_2d.py','--regression-gate']","'game2d':['tools/audit_game_2d.py','--regression-gate'],'register_parts':['audit/job_artwork_refinement_live/review_tools/test_register_parts_v51.py']");put(N/'review_tools/run_neck_gate_v613.py',old.encode());shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}|{(G/(label+suffix)).relative_to(B).as_posix() for label in ['authority','development','document_tests','game2d','register_parts'] for suffix in ['.stdout.log','.stderr.log','.receipt.json']}|{(G/'CANDIDATE_NECK_SOURCE_V613.json').relative_to(B).as_posix()});d['validation'].append(dict(command='Actual source-report/V52 library browser verification',result='PASS',evidence=(N/'BROWSER_VERIFY_V612.json').relative_to(B).as_posix()+';four loaded1672x941 originals/44 written opinions,no overflow,exact A4 record has motion/mounted/action unassigned.'));d['validation'].append(dict(command='Prior AA complete exact anonymous remote journal archival',result='PASS',evidence=remote.relative_to(B).as_posix()+'/RESULT.json and JOURNAL_SHARDS.json;all24298 literal rows preserved.'));d['validation'].append(dict(command='New runtime import/parser/lint/full probes for source-only review additions',result='NOT_APPLICABLE',evidence='All changed artwork is source/QA/local-reference under assets_src/.gdignore or audit/.gdignore. No production script/asset/import delta;783 exact literals rechecked. Existing official4.7.2 full82/82 process0 evidence stays scoped;new hosted status separate.'));write(IP,d)
members=[]
for path in d['files']:
 p=B/path
 if not p.is_file() or path.startswith(G.relative_to(B).as_posix()+'/'):continue
 members.append(dict(path=path,bytes=p.stat().st_size,sha256=sha(p.read_bytes())))
write(G/'CANDIDATE_NECK_SOURCE_V613.json',dict(status='EXACT_GRIP_REVIEW_SOURCE_FROZEN_FOR_PRELIMINARY_GATES_MOTION_PENDING',baseline=d['baseline'],frozen_utc=now(),members=members,member_count=len(members),qualification='Historical pre-gate working-tree review snapshot. Motion and final publication still pending;later final source-bound gates/seal required.'))
print('BROWSER_PRIOR24298_REMOTE_AND_PRELIMINARY_GATES_PREPARED',len(members),data['status'],data['conclusion'],flush=True)
