from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
 n=p.with_name(p.name+'.v605_next');n.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());n.replace(p)
BASE='876169d77d45f5fd2b5956eeda4f1e6da9926f19'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=B,text=True).strip()==BASE and not N.exists() and not IP.exists()
source='assets_src/imagegen/candy_cover_pose_v1_20261003/attempt01/native.png';reference_hash=sha((B/source).read_bytes());assert reference_hash=='9e1f2cbcbe0bfc6e0f7a2cebd8c3c50e1e09dfb3f6156e7798ce0a9b3e22a87d'
with Image.open(B/source) as im:assert im.size==(1672,941) and im.mode=='RGB'
reuse=[]
for path,reason in [
(source,'Exact clean contextual covering/pressing still4.5, cover4.6. Reuse full scene; its palms press the body, not the untwisted necks.'),
('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt07/native.png','Existing four-key atlas has useful owned hands/static contact, but its pinch endpoints already have closed/tied neck rings and a different scene/table registration. Direct native inspection confirms it is not this pre-twist key.'),
('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt12/native.png','Existing gathered-grip revision is recorded4.3/rejected; cannot transfer its opinion or pose to this exact clean contextual source.'),
('assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt13/native.png','Existing partial-fold source4.5 leaves coverage4.2 and does not supply this continuous covered-oval neck grip.'),
('assets_src/imagegen/candy_wrap_scene_context_v1_20261003/attempt02/native.png','Exact contextual earlier partial-fold still4.5; preserve as the preceding fold reference, not a ready neck grip.'),
('assets/opera/worlds/widgets/widget_crank_candymaker_mover.png','Current decorative prewrapped sweet is not supported paper gathering with Roshan-owned hands.')]:
 assert (B/path).is_file();reuse.append(dict(path=path,sha256=sha((B/path).read_bytes()),reuse_evaluation=reason))
boundary=read(B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json');assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members'])
N.mkdir();(N/'review_tools').mkdir();(N/'attempt01').mkdir()
prompt="Use case: precise-object-edit\nImage 1 is the complete existing painted Candy Maker scene and the edit target. Return one ENTIRE landscape painting in the SAME framing, with one targeted next action pose: Roshan gathers the two UNTWiSTED narrow paper necks beside the SAME small covered oval sweet.\nPreserve her exact face, head, eyes, brown hair and rainbow forelock, shell-trimmed teal cap, coral bows, teal-and-coral costume, cream sleeves, two teal cuffs and exactly TWO coral quilted oven-mitten hands. Preserve the candy-factory background, lavender tabletop, camera, character size and the supported sweet's original centre, size and low oval volume. No new scene or redesign. Her face remains attentive to the work.\nThe same continuous opaque GOLD PAPER is now snugly folded around that same small oval sweet, with one broad seam on its top and two open flat fan-shaped side ends. All red remains hidden. There is no leftover separate gold mat beneath it. The paper has not become a new object: the central body, the short neck on each side, and the two loose fans form ONE continuous sheet. Keep the belly small; do not enlarge it into a cushion, bread loaf, bag, tube or bulky cylinder.\nMove only her existing forearms, wrists and mitten contact poses as needed for this next grip, keeping each hand naturally connected to its original cuff and sleeve. Her screen-left mitten's existing thumb and palm pinch the short LEFT neck immediately beside the oval body. Her screen-right mitten's thumb and palm pinch the short RIGHT neck immediately beside the oval body. Each short gold neck is visibly compressed BETWEEN that mitten's thumb and palm; each loose fan extends OUTWARD beyond the grip. Neither hand grips the outside fan tip or presses the centre belly. Keep enough separation to show both neck contacts, the small central wrapped oval, and both continuous loose side ends. No floating mitten, extra arm, bare finger or outside operator.\nThis is the gathered-neck grip BEFORE any twist. Both gold necks are soft narrow gathers with open untwisted folds, not already rolled closed. NO tied rings, bands, strings, knots, spiralled finished twists or magical instant closure. The wrapped sweet remains supported on the same table. Preserve the same broad painted satin-gold value bands, restrained crinkles and plum contours; the mittens stay rounded and graphic. No photorealism, realistic skin, 3D rendering, flat vector replacement, collage, UI, text, sparkle, crop or camera movement. One still pose only; do not imply that the whole wrapping action has passed."
(N/'SENT_PROMPT.txt').write_bytes(prompt.encode());prompt_hash=sha(prompt.encode())
rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-04','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-INT-02','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-03','DL-QA-07']
write(N/'PLAN.json',dict(status='SPECIFIC_UNTWISTED_NECK_GRIP_PLANNED_NO_OUTPUT_YET',planned_utc=now(),baseline=BASE,prior_turn_classification='PROGRESS:all88 native cells/33 relationships and V51 known2138 entries published;all24298 anonymous exact-head files verified. Current head hosted result remains separately pending.',scope='Develop the missing honest gathered-neck grip on the same clean painted gold-wrapper scene, preserve every native/rejection and compare both owned hand contacts. This pose contributes to the original complete wrapping objective; it cannot replace the missing fold trajectory, opposite twists, supported release or actual game/training acceptance.',rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],profile='design/animation/ROSHAN_MOVEMENT_LANGUAGE.md',protocol='design/animation/ANIMATION_PRODUCTION_PROTOCOL.md',intention='Roshan attends to the same supported covered sweet and pinches the two short untwisted gold necks with her own two sleeve-attached mittens, ready to twist.',emotional_register='Compact concentrating Ribbon Glide work; no decorative bounce or celebration.',reuse_inventory=reuse,references=[dict(path=source,sha256=reference_hash,role='edit_target_exact_full_scene_identity_gold_material_and_supported_covered_sweet')],generation_gap='No exact contextual pre-twist key exists with both contacts on untwisted short necks. Earlier closed ring endpoints cannot stand in for visible gathering before the twist.',prompt_path='SENT_PROMPT.txt',prompt_sha256=prompt_hash,generation_method='built_in_imagegen_precise_object_edit',required_evidence=['Complete native dimensions/mode/hash, exact sent prompt/reference hashes','Individual direct source opinions for exactly2 owned hands, both neck contacts and fan ownership, continuous gold sheet/opaque conserved oval, untwisted-before-twist semantics, stable table/identity/material/foreground','Retain failed variants and refine only named defects until the requested source contacts/identity reach4.5 or higher; inherited room4.4 remains independently weak','Full fold/gather/opposite wrist twists/supported release remains required; no source still or later local Comfy study transfers to current game WRAP2.8','Current known-item register parts stay literal bounded/fail-closed; fresh source-bound review/structural/document/no-regression gates and exact topic publication','Actual ordinary job/training/current source-to-runtime/device/child/owner/comprehensive report remain open'],source_pose_score=None,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None))
write(N/'PRODUCTION_BOUNDARY_CHECK.json',dict(status='ALL783_CURRENT_LITERAL_PRODUCTION_MEMBERS_UNCHANGED_BEFORE_NECK_GRIP_STUDY',checked_utc=now(),source_boundary='assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json',boundary_sha256=sha((B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json').read_bytes()),members=783,qualification='No production delta only; no new action/runtime/owner acceptance.'))
shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
write(IP,dict(id='job-candy-neck-grip-pose-20261003',scope='Reversible same-scene ImageGen refinement of the two pre-twist short-neck grips, preserving complete gold-wrapper/character/table identity. Keep full wrapping and all-jobs objective intact;no production binding or finding closure.',baseline=BASE,rules=rules,findings=['MA-VIS-006','MA-PLAY-004'],files=sorted(p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()),validation=[dict(command='Existing source inventory and exact current production check',result='PASS',evidence='assets_src/imagegen/candy_neck_grip_pose_v1_20261003/PLAN.json and PRODUCTION_BOUNDARY_CHECK.json;pre-tied old endpoints fail this gap,all783 literals unchanged.'),dict(command='Fresh native neck-grip generation and individual direct review',result='PENDING',evidence='assets_src/imagegen/candy_neck_grip_pose_v1_20261003/SENT_PROMPT.txt;no output/score yet.'),dict(command='Current register/actual browser/source-bound gates and exact topic publication',result='PENDING',evidence='Current V51/2138 register preserved before any new source opinion. No prediction of outcome.')],acceptance_gaps='Full fold/gather/opposite wrist twists/supported release/current game WRAP2.8,294 primary opinions,all other weak game/training/ordinary-route source/use/action,phone/device/child/owner/comprehensive report acceptance remain open. Inherited room4.4 remains a separate priority.'))
print('PREPARED_SPECIFIC_UNTWISTED_NECK_GAP',prompt_hash,len(reuse),flush=True)

