from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003'
sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def put(p,raw):t=p.with_name(p.name+'.v608_next');t.write_bytes(raw);t.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
src=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-d06950da-3f3f-4e53-aea9-0a03afd808e9.png');dst=N/'attempt03/native.png';assert not dst.exists();shutil.copyfile(src,dst)
with Image.open(dst) as im:dims=list(im.size);mode=im.mode
prior=read(N/'attempt03/PLAN.json');prompt_path=N/'attempt03/SENT_PROMPT.txt'
write(N/'attempt03/SOURCE.json',dict(method='built_in_imagegen_precise_object_edit',native_path=dst.relative_to(B).as_posix(),native_sha256=sha(dst.read_bytes()),native_dimensions=dims,native_mode=mode,default_generated_original=str(src),prompt_path=prompt_path.relative_to(B).as_posix(),prompt_sha256=sha(prompt_path.read_bytes()),references=prior['references'],copied_without_pixel_changes=True,recorded_utc=now(),runtime_bound=False))
reviews=[('exactly_two_owned_mittens',4.6,'Both coral mitten hands retain their original cuff/sleeve connections and distinct thumb lobes.'),('left_neck_contact',4.5,'The original left thumb and palm visibly pinch the short neck beside the belly; the fan extends beyond it.'),('right_neck_contact',4.5,'The original right thumb and palm oppose across the right neck while the same covered sweet remains supported.'),('pre_twist_semantics',4.5,'The neck folds now run lengthwise without diagonal winding, finished collars or tied rings. The ends remain open.'),('single_continuous_gold_wrapper',4.3,'The four rigid outlined ridges look like separate rods inserted between the belly and fan, weakening flexible single-sheet continuity.'),('opaque_supported_small_oval',4.5,'One fully covered low oval remains on the same table at stable size; no exposed red or extra sweet.'),('outward_fan_ownership',4.5,'Both gold fan ends remain outside the grips and belong to the central task.'),('character_table_registration',4.5,'Whole character, scene and supported task remain coherent; no unrelated redesign.'),('painted_gold_material',4.3,'Belly and fans retain painted gold but the necks read as hard corrugated tubes rather than gathered thin paper.'),('inherited_room_graphics',4.4,'The unchanged detailed room remains a separate weak source priority.'),('whole_pre_twist_pose',4.3,'Grip and before-twist action are legible, but the neck material still misses this specific flexible wrapper.')]
write(N/'attempt03/DIRECT_REVIEW.json',dict(reviewed_utc=now(),review_method='direct_complete_native_original_imagegen_output',native_sha256=sha(dst.read_bytes()),status='REJECTED_RIGID_ROD_LIKE_NECK_MATERIAL',components=[dict(id=k,score=s,evaluation=v) for k,s,v in reviews],source_pose_score=4.3,motion_score=None,current_game_wrap_score=2.8,runtime_bound=False,owner_acceptance=None,required_revision='Soften the open lengthwise folds into one continuous thin gold-paper sheet, preserving both achieved grips and untwisted state.'))
prompt="Use case: precise-object-edit\nImage 1 is the complete existing painted Candy Maker scene and edit target. Keep the whole scene and BOTH achieved mitten thumb-and-palm pinches in exactly the same place. Keep one small gold covered oval sweet supported at its table centre, the exact two attached mitten hands, cuffs, sleeves, character and factory framing. Correct ONLY the paper surface of the two short UNTWISTED NECKS.\nThe current four horizontal gold ridges look like separate hard pipes or mechanical bars. Redraw them as ONE THIN FLEXIBLE CONTINUOUS GOLD PAPER SHEET gently gathered into shallow open lengthwise folds between each thumb and palm. Use soft irregular narrow satin-gold fold valleys and broad gentle painted highlights, with no dark internal outlines dividing rods. The paper continues smoothly from the oval's surface THROUGH each neck pinch and into the existing loose outer fan. The neck's outer contour softly converges under pressure, with modest natural paper wrinkles; keep the short unsealed gathered necks, not tubes, rings, collars, cord, corrugated hose or tied cuffs. Do not rotate the paper diagonally, cross/braid folds or add a twist. The loose fans remain open and all red stays hidden. No separate flat mat or extra object. Every fold belongs to the same crinkled gold wrapper material as the belly and fans. Preserve both correct neck grips, table support, small scale and all other pixels as closely as possible. No extra hands/fingers, vector art, realism, text, crop or camera move. Return one entire landscape painting of the pre-twist gather."
(N/'attempt04').mkdir();(N/'attempt04/SENT_PROMPT.txt').write_bytes(prompt.encode());ref=dict(path=dst.relative_to(B).as_posix(),sha256=sha(dst.read_bytes()),role='edit_target_exact_owned_grips_and_untwisted_stage_neck_material_only_failed')
write(N/'attempt04/PLAN.json',dict(status='TARGETED_FLEXIBLE_SINGLE_SHEET_NECK_MATERIAL_CORRECTION_PLANNED',named_defect='A3 gold necks look like rigid separate outlined rods',prompt_sha256=sha(prompt.encode()),references=[ref],runtime_bound=False))
plan=read(N/'PLAN.json');plan['status']='ATTEMPT03_CONTACT_STAGE4_5_MATERIAL4_3_ATTEMPT04_TARGETED_CORRECTION';plan['attempts'].append(dict(attempt=3,source_pose_score=4.3,status='REJECTED_NECK_MATERIAL',review='attempt03/DIRECT_REVIEW.json'));write(N/'PLAN.json',plan)
put(N/'review_tools/preserve_neck_v607.py',Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/preserve_neck_v607.py').read_bytes());shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()});d['validation'][1]=dict(command='Native grip generation and separate contact/stage/material review',result='FAIL',evidence='assets_src/imagegen/candy_neck_grip_pose_v1_20261003/attempt03/DIRECT_REVIEW.json;both grips and pre-twist4.5,neck material4.3. All three natives/rejections retained,A4 material-only edit planned.');write(ip,d)
print('A3_PRESERVED_REJECTED_MATERIAL4_3',sha(dst.read_bytes()),'A4_PROMPT',sha(prompt.encode()),flush=True)
