from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';M=N/'local_motion_a1';A=M/'attempt01';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):t=p.with_name(p.name+'.v615_next');t.write_bytes(raw);t.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
index=read(A/'INDEX.json');assert len(index['frames'])==41
notes=[
'Initial two connected mitten grips and one gold oval are visible; this opening alone cannot demonstrate the instructed twist.',
'Both short gold necks remain between the mitten lobes; no visible opposing wrist rotation yet.',
'Figure and working object contract relative to the retained room; the two grips stay broadly similar.',
'The initial pose is reduced against the fixed tabletop; gold fans remain loose and no neck closure is shown.',
'Both hands stay near their original short necks; the action still reads as holding rather than opposite twisting.',
'Small forearm movement changes posture, with the two long gold folds still open between body and fans.',
'Same gold oval remains table-supported, but wrists have not visibly rolled opposite directions.',
'The figure remains smaller than entry; both fans stay open and their folds are not being wound closed.',
'Hands gently reposition without a readable two-sided opposing rotation; oval remains opaque.',
'Both gold fans are still connected and spread; the requested twist has not become visible.',
'Small pose/candy shape variation occurs with no distinct contact-driven neck closure.',
'Both mittens retain cuff connections at this stage; the work remains a hold rather than a completed twist.',
'Hands remain over the two neck groups; central gold body changes width slightly without demonstrated wrist torque.',
'Source identity persists; loose fan folds remain open and no finished neck is formed.',
'Both mitten palms stay near the same necks while the body/working footprint varies against the room.',
'The neck folds are still long and parallel; an opposing wrist turn is not readable.',
'The two hands move forward/down together rather than visibly rotating oppositely on their own necks.',
'Central sweet remains covered and low, while paper folds remain open rather than wound closed.',
'Both mittens become more vertical; fans and short necks move without a legible twist consequence.',
'The wrists change together, not as a clear opposing pair; paper fan surfaces flatten and shift.',
'Both hands continue pointing down over the necks; the supported oval persists but neither twist is demonstrated.',
'Fans are changing silhouette while both mittens stay near the body; no stable finished neck appears.',
'Neck pleats elongate horizontally; fan edges change more than the central covered oval.',
'Gold ends begin reading as separate side flaps, with the two mittens still pressing over long open pleats.',
'Both gold fans lift beside the arms while multiple long gold strip ends remain attached to the oval.',
'Left and right fans rise toward the cuffs, separating from the central neck strips; continuous sheet ownership fails.',
'Gold fans are now displaced outside the cuffs while neck strips stay at the oval; no proper closed wrapper.',
'Both loose paper fans remain separate from the central strip groups, contradicting a single sheet twisted by the hands.',
'Hands still point toward the covered body; raised outside fans are disconnected from the low neck strips.',
'Gold fans and teal cuff areas begin merging with motion smearing; central paper ends remain separate.',
'Both gold fan ends grow into raised cuff-like appendages; mitten lobes elongate and the wrapper necks stay on the table.',
'Large gold fans visibly attach outside the teal cuffs while separate neck strips end beside the central candy.',
'Coral mittens acquire extended finger-like lobes; fan/cuff hybrids remain raised and neither hand rests beside a closed twist.',
'Both large fan/cuff hybrids persist; central candy has bare parallel paper-strip ends instead of finished twisted necks.',
'Original two hands are still broadly identifiable, but paper and sleeve topology are materially corrupted.',
'Both hands remain above the central neck strips; gold fans stay fused outside their cuffs rather than attached to the wrapper.',
'Late pose holds the two cuff-mounted gold fans; no supported stable double-twist completion or released hands.',
'Raised gold fan/cuff forms persist; covered oval remains low but wrapper topology and release are wrong.',
'The two coral hands stay near the strip ends; disconnected gold fans are still part of the cuffs.',
'Final near-hold still contains both fan/cuff hybrids and extended mitten lobes, not a proper settle.',
'Final endpoint has one covered central body with exposed parallel neck strips and two gold fans fused to cuffs; both release and complete wrapper fail.'
];assert len(notes)==41
frames=[]
for row,note in zip(index['frames'],notes):
 assert sha((B/row['path']).read_bytes())==row['sha256'];frames.append(dict(**row,direct_complete_native_review=True,whole_component_motion_score=None,pose_graphics_score=4.4 if row['index']<2 else (4.0 if row['index']<22 else (3.2 if row['index']<25 else (2.3 if row['index']<29 else 1.4))),evaluation=note,priority=True,current_game_score=None,owner_acceptance=None))
ops=[('exactly_two_hand_count',4.5,'Two principal hand groups remain visible throughout, with no extra operator. This bounded count success does not approve their shape/contact/material topology.'),('sleeve_cuff_mitten_topology',2.8,'Late gold fans merge with teal cuffs and the coral mitten lobes stretch into finger-like forms; original simple sleeve-owned mitten design fails.'),('both_neck_grips_through_action',3.3,'Early source grips are useful, but later paper-strip ends and outside fans split around the hands instead of remaining one gripped sheet.'),('opposing_wrist_rotation',1.9,'Small forward/down motion and posture changes occur; the hands do not clearly turn opposite ways while retaining their own short-neck contacts.'),('specific_gold_paper_response',1.5,'Neck folds stay long/open and the loose fans rise toward the arms, rather than turning with short rolled necks closed by the mittens.'),('single_wrapper_fan_conservation',0.9,'By frames25-40 the fans detach from the central strip groups and become large gold cuff appendages. One continuous paper sheet is not conserved.'),('covered_oval_and_table_support',4.0,'The central gold body remains covered and low on the table, but size/working footprint changes and its detached neck/fan topology undermine identity conservation.'),('two_hand_release_and_settle',1.0,'Neither hand cleanly releases beside two stable finished twists. The endpoint holds corrupted cuff/fan forms above bare paper-strip ends.'),('character_scene_registration',3.7,'Figure and working-object scale contract against the retained room early, and late costume/hand silhouette drifts. Stable source placement is not maintained.'),('whole_neck_twist_release_component',1.8,'Rejected: useful entry grips cannot outweigh missing opposing twists, detached paper fans, corrupted cuffs and absent stable release. No current game or complete wrapping acceptance.')]
review=dict(status='REJECTED_GOLD_FANS_DETACH_AND_MERGE_WITH_CUFFS_NO_OPPOSING_TWIST_RELEASE',reviewed_utc=now(),reviewer='Codex direct complete native-frame drafting review',native_frames_reviewed=41,boards_directly_reviewed=7,individual_frame_opinions=41,component_opinions=10,frames=frames,components=[dict(id=k,score=s,evaluation=e,priority=s<=4.5) for k,s,e in ops],whole_component_score=1.8,source_still_score=4.5,current_game_wrap_score=2.8,complete_wrapping_score=None,acceptance='LOCAL_MOTION_REFERENCE_ONLY',runtime_integration=False,device_acceptance=None,child_acceptance=None,owner_acceptance=None)
write(A/'DIRECT_REVIEW.json',review);write(M/'REVIEW_STATUS.json',{k:review[k] for k in ['status','reviewed_utc','native_frames_reviewed','component_opinions','whole_component_score','source_still_score','current_game_wrap_score','complete_wrapping_score','acceptance','runtime_integration','owner_acceptance']})
m=read(M/'MANIFEST.json');m['status']=review['status'];m['visual_review']=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix();m['component_motion_score']=1.8;m['complete_action_score']=None;write(M/'MANIFEST.json',m)
summary=read(N/'REVIEW_SUMMARY.json');summary['status']='A4_GRIP_STILL4_5_LOCAL_COMPONENT1_8_REJECTED_CURRENT_WRAP2_8';summary['motion_reference_component_score']=1.8;summary['motion_frames_reviewed']=41;summary['motion_component_opinions']=10;summary['motion_review']=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix();write(N/'REVIEW_SUMMARY.json',summary)
plan=read(N/'PLAN.json');plan['status']='A4_STATIC_GRIP4_5_LOCAL_NECK_TWIST_RELEASE1_8_REJECTED';plan['local_motion_component_review']=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix();plan['local_motion_component_score']=1.8;write(N/'PLAN.json',plan)
esc=lambda x:html.escape(str(x));rows=''.join('<tr><td>'+esc(k.replace('_',' '))+'</td><td>'+str(s)+'/5</td><td>'+esc(e)+'</td></tr>' for k,s,e in ops);movie=next(x['path'] for x in index['outputs'] if x['path'].endswith('.mp4'));articles=''.join('<article id="frame%02d"><h2>Frame %d · %.3fs · pose graphics%s/5</h2><img loading="lazy" src="%s" alt="Complete rejected local reference frame %d"><p>%s</p><p>Complete motion/current game/owner score unassigned for this individual canvas.</p></article>'%(x['index'],x['index'],x['timestamp_seconds'],x['pose_graphics_score'],Path(x['path']).relative_to(M.relative_to(B)).as_posix(),x['index'],esc(x['evaluation'])) for x in frames)
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gold-wrapper neck motion · rejected1.8</title><style>body{max-width:1120px;margin:auto;padding:24px;background:#edf3fb;color:#25334b;font:17px/1.55 system-ui}article{background:white;padding:18px;border-radius:16px;margin:24px 0}img,video{width:100%;height:auto;display:block}td,th{padding:10px;text-align:left;vertical-align:top;border-bottom:1px solid #d5e0ef}table{width:100%;border-collapse:collapse}td,p{overflow-wrap:anywhere}a{color:#164c83}</style><h1>Specific gold-wrapper neck motion · rejected1.8/5</h1><p>All41 complete decoded896×512 canvases and10 component opinions were directly reviewed. The fans detach from the central wrapper and merge into the cuffs; no clear opposing twists or stable release. <strong>A4 static source4.5/current in-game WRAP2.8 remain separate.</strong> LOCAL_MOTION_REFERENCE_ONLY;no production or cinematic binding.</p><p><a href="../index.html#attempt04">Corrected source grip and rejected variants</a> · <a href="attempt01/DIRECT_REVIEW.json">All individual frame/component scores</a> · <a href="MANIFEST.json">Exact source/input/prompt/seven workflow bindings</a></p><video controls preload="metadata" src="'+Path(movie).relative_to(M.relative_to(B)).as_posix()+'"></video><table><thead><tr><th>Component</th><th>Draft score</th><th>Evaluation</th></tr></thead><tbody>'+rows+'</tbody></table>'+articles+'<p>Next study needs the missing exact supported twist/release poses before further motion attempts. Preserve all failures;never repair generated frames by moving or warping subjects. Whole wrapping and ordinary game/training/device/child/owner/comprehensive report remain open.</p></html>';put(M/'index.html',page.encode())
p=N/'index.html';t=p.read_text(encoding='utf-8');t=t.replace('<strong>No rendered sequence or motion score yet.</strong>','<strong>Rendered component1.8/5 rejected;all41 canvases and10 opinions directly reviewed.</strong> Gold fans detach and merge into cuffs;opposing twists and stable release fail.');t=t.replace('<a href="local_motion_a1/MANIFEST.json">Exact local study manifest</a>','<a href="local_motion_a1/index.html">Rejected movie,all41 images and individual reviews</a> · <a href="local_motion_a1/MANIFEST.json">Exact local study manifest</a>');put(p,t.encode())
reg=read(L/'ALL_ITEMS.json');assert reg['display_revision']=='V52';reg['scope']=reg['scope'].replace('One local-reference opposing wrist twist/release component is being tested;no motion score yet.','One local-reference opposing wrist twist/release component1.8 rejected;all41 native canvases/10 components individually reviewed. Gold fans detach into cuffs;no correct opposing twists/release.');write(L/'ALL_ITEMS.json',reg,True)
for path in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md']:
 p=B/path;t=p.read_text(encoding='utf-8');t=t.replace('A guarded existing local Comfy opposing wrist-twist/release component is prepared;no rendered motion score yet.','Existing guarded local Comfy opposing wrist-twist/release component1.8 rejected:all41 native canvases/10 component opinions reviewed;gold fans detach into cuffs,no clear opposing twists/stable release.');put(p,t.encode())
p=B/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8').replace('Local motion reference pending,whole wrapping/current game2.8/owner acceptance open.','Local neck motion reference1.8 rejected,41 frames/10 opinions;whole wrapping/current game2.8/owner acceptance open.');t+='\n| `assets_src/imagegen/candy_neck_grip_pose_v1_20261003/local_motion_a1/index.html` | 🟢 | `SUPPORTING_CURRENT`;41 complete native decoded reference canvases/10 component opinions,whole neck-twist/release1.8 rejected. Gold fans detach into cuffs;static grip4.5/current game2.8 remain separate. No production/cinematic/owner acceptance. |\n';put(p,t.encode())
licenses=B/'ASSET_LICENSES.md';raw=licenses.read_bytes();rows=[]
for x in index['outputs']+index['frames']+index['boards']:
 path=x['path'];assert path.encode() not in raw;role='Decoded complete local reference frame' if 'index' in x else ('Labeled original-size reference-frame QA board' if x.get('qa_only') else 'Complete local Comfy motion reference video');rows.append('| `'+path+'` | '+role+' from source A4 through unchanged pinned local workflow | Existing pinned model/workflow receipts and inherited project character/wrapper attribution | `'+(A/'INDEX.json').relative_to(B).as_posix()+'` records exact bytes;MANIFEST binds source and seven workflows | Preserved rejected reference only;no runtime/cinematic/device/child/owner approval. QA boards retain original-size frames without resampling. |')
put(licenses,raw+('\n'+'\n'.join(rows)+'\n').encode());shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()});d['validation'].append(dict(command='Direct every41 native local reference canvas and10 neck-twist/release components',result='FAIL',evidence=(A/'DIRECT_REVIEW.json').relative_to(B).as_posix()+';whole component1.8 rejected,gold fans detach into cuffs,no proper opposing twists/release. A4 static4.5/current WRAP2.8 unchanged.'));write(IP,d)
rr=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v52.py')],cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);assert rr.returncode==0,rr.stderr.decode(errors='replace');put(N/'REFRESH.stdout.log',rr.stdout);put(N/'REFRESH.stderr.log',rr.stderr)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}));print('NECK_MOTION_REJECTED1_8_ALL41_POSES10_COMPONENTS_LICENSED',len(frames),len(ops),flush=True)
