from pathlib import Path
import copy,datetime,hashlib,json,shutil,subprocess,sys
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');N=B/'assets_src/imagegen/candy_neck_grip_pose_v1_20261003';L=B/'audit/job_artwork_refinement_live';IP=B/'design/audit_impacts/job-candy-neck-grip-pose-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def put(p,raw):t=p.with_name(p.name+'.v611_next');t.write_bytes(raw);t.replace(p)
def write(p,d,compact=False):put(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
sys.path.insert(0,str(L/'review_tools'));from register_parts_v51 import load_register
assembled=load_register(L);reg=read(L/'ALL_ITEMS.json');assert assembled['display_revision']=='V51' and len(assembled['items'])==2138 and len(reg['items'])==2050
H=N/'previous_v51';H.mkdir()
for name in ['ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json']:shutil.copyfile(L/name,H/name)
before=copy.deepcopy(reg['items']);parts=copy.deepcopy(reg['item_shards']);reference=next(x for x in reg['items'] if x['id']=='CANDY-COVER-SOURCE-01')
for i in range(1,5):
 folder=N/f'attempt{i:02d}';s=read(folder/'SOURCE.json');r=read(folder/'DIRECT_REVIEW.json');z=copy.deepcopy(reference);dims=s.get('dimensions',s.get('native_dimensions'));z.update(id=f'CANDY-NECK-SOURCE-{i:02d}',aliases=[f'CANDY-NECK-SOURCE-{i:02d}'],path=s['native_path'],earlier_sha256=s['native_sha256'],current_checkout_sha256=s['native_sha256'],current_source_score=r['source_pose_score'],evaluation=r['components'][-1]['evaluation'],refinement=r.get('required_revision','Retain achieved static grip. Independently prove opposing wrists, gold-paper response, supported release, whole wrapping and current game/training context;room4.4 remains weak.'),families=['Day Two','Candy Maker','Unbound specific gold-wrapper neck grip'],original_reports=[N.relative_to(B).as_posix()+'/index.html'],source_qualification='Complete same-scene native directly reviewed;11 separate source opinions. '+r['status']+'. No motion/current game/owner acceptance.',preview_path=s['native_path'],image_path=s['native_path'],image_scope='Full preserved gold-wrapper grip candidate only; not an accepted motion frame',source_dimensions=dims,individual_review_utc=r['reviewed_utc'],latest_refinement=dict(report=N.relative_to(B).as_posix()+f'/index.html#attempt{i:02d}',note=f'Attempt{i} source{r["source_pose_score"]};11 individual opinions. All prior failed natives retained. Current game WRAP2.8 stays separate.'));reg['items'].append(z)
allitems=reg['items']+assembled['items'][2050:];pri=[x for x in allitems if x.get('current_source_score') is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3']];unique={x['path'] for x in pri if x['kind'] in ['source','runtime source']};pending=[x for x in allitems if x['kind']=='source' and x.get('current_source_score') is None]
assert len(allitems)==2142 and len(pri)==1045 and len(unique)==668 and len(pending)==294 and reg['items'][:2050]==before and reg['item_shards']==parts
reg['counts'].update(unique_source_files=1290,registered_items=2142,inclusive_current_source_priorities=1045,unique_source_file_priorities=668,unreviewed_current_source=294,new_candy_neck_grip_sources=4)
reg.update(display_revision='V52',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v52.py',scope='V52:2142 known entries/1290 primary sources/328 pose cells/151 runtime-use-action entries/373 source object regions.1045 inclusive source-cell-region priorities/668 unique source-file priorities/294 unreviewed primary sources. Four full specific gold-wrapper grip natives and44 separate source opinions:3.2/4.2/4.3 rejected,A4 grip still4.5 provisional/inherited room4.4. One local-reference opposing wrist twist/release component is being tested;no motion score yet. Existing complete wrapping/fold studies remain rejected and current WRAP2.8/all783 production literals unchanged. Ordinary job/training/source-to-runtime/device/child/owner/comprehensive all-jobs acceptance remains open.')
reg['current_byte_status_counts']['EXACT_REVIEWED_GENERATION_BYTES']+=4;reg['review_resources'].append(dict(path=N.relative_to(B).as_posix()+'/index.html',scope='Four exact complete same-scene gold-wrapper grip natives/44 individual opinions;A4 static grip4.5 provisional/room4.4. Motion/current game not accepted.'))
write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304;shutil.copyfile(L/'review_tools/refresh_current_job_review_v51.py',L/'review_tools/refresh_current_job_review_v52.py')
notice='<p class="current-neck-review"><a href="../../assets_src/imagegen/candy_neck_grip_pose_v1_20261003/index.html#attempt04">Latest specific gold-wrapper hand-contact review: four complete natives and44 evaluations</a> · A4 static grip4.5/5 provisional; both hands pinch soft untwisted necks. Room4.4 remains weak; motion and current game not accepted. <strong>V52:2142 known entries/1045 source-cell-region priorities/668 unique priority sources/294 unreviewed primary sources.</strong> Current WRAP2.8 remains separate.</p>'
for name in ['index.html','all_items.html']:
 p=L/name;t=p.read_text(encoding='utf-8').replace('refresh_current_job_review_v51.py','refresh_current_job_review_v52.py');assert '<h1>' in t;put(p,t.replace('<h1>',notice+'<h1>',1).encode())
note='Specific Candy wrapper-hand continuation (2026-10-03): [four complete same-scene ImageGen grip candidates and44 individual source opinions](NECK). A1 premature rings/fan contact3.2,A2 early twist4.2,A3 rigid neck material4.3 rejected;A4 both attached neck grips/untwisted flexible gold paper/whole still4.5 provisional,inherited room4.4. A guarded existing local Comfy opposing wrist-twist/release component is prepared;no rendered motion score yet. Full fold-cover-gather-twist-release,current game WRAP2.8/all783 unchanged production literals,ordinary jobs/training/device/child/owner/comprehensive all-jobs acceptance remain open. V52 known2142 entries/1290 primary sources/1045 inclusive source-cell-region priorities/668 unique source priorities/294 unreviewed primary sources. Finding lifecycle,integration and release unchanged.'
for path,link in [('audit/MASTER_AUDIT_2026-08-09.md','../assets_src/imagegen/candy_neck_grip_pose_v1_20261003/index.html'),('audit/findings/ACTIVE_FINDINGS_2026-08-13.md','../../assets_src/imagegen/candy_neck_grip_pose_v1_20261003/index.html'),('audit/animation/README.md','../../assets_src/imagegen/candy_neck_grip_pose_v1_20261003/index.html')]:
 p=B/path;t=p.read_text(encoding='utf-8');n=note.replace('NECK',link)
 if path.endswith('MASTER_AUDIT_2026-08-09.md'):
  for marker in ['## 0. Planning entry','### Development task index']:assert marker in t;t=t.replace(marker,marker+'\n\n'+n,1)
 else:i=t.index('\n')+1;t=t[:i]+'\n'+n+'\n'+t[i:]
 put(p,t.encode())
p=B/'design/05_DOC_LEDGER.md';t=p.read_text(encoding='utf-8');t+='\n| `assets_src/imagegen/candy_neck_grip_pose_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; four complete preserved gold-wrapper grip natives/44 source opinions. A4 both grips and untwisted flexible paper4.5 provisional;room4.4. Local motion reference pending,whole wrapping/current game2.8/owner acceptance open. |\n| `assets_src/imagegen/candy_neck_grip_pose_v1_20261003/previous_v51/ALL_ITEMS.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact bounded V51 root before four new grip sources,its88-item part unchanged. |\n';put(p,t.encode())
p=B/'.gitattributes';t=p.read_text(encoding='utf-8');t+='\nassets_src/imagegen/candy_neck_grip_pose_v1_20261003/** -text\n';put(p,t.encode());shutil.copyfile(__file__,N/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}|{(L/x).relative_to(B).as_posix() for x in ['ALL_ITEMS.json','index.html','all_items.html','CURRENT_BOUNDARY_REFRESH.json','review_tools/refresh_current_job_review_v52.py']}|{'.gitattributes','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','audit/animation/README.md','design/05_DOC_LEDGER.md'});write(IP,d)
r=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v52.py')],cwd=B,capture_output=True,creationflags=subprocess.CREATE_NO_WINDOW);(N/'REFRESH.stdout.log').write_bytes(r.stdout);(N/'REFRESH.stderr.log').write_bytes(r.stderr);assert r.returncode==0,r.stderr.decode(errors='replace');assert read(L/'CURRENT_BOUNDARY_REFRESH.json')['registered_source_matches']==2142;loaded=load_register(L);assert len(loaded['items'])==2142 and loaded['items'][:2050]==before
write(N/'REGISTER_EXTENSION_CHECK.json',dict(status='V52_ALL2142_SOURCE_HASHES_MATCH_PRIOR2050_AND88_PART_UNCHANGED',checked_utc=now(),root_bytes=(L/'ALL_ITEMS.json').stat().st_size,unchanged_previous_base_items=2050,unchanged_part_items=88,registry_parts=parts,registered_items=2142,inclusive_priorities=1045,unique_priority_sources=668,unreviewed_primary_sources=294,qualification='Literal source/known-entry integrity only;no new complete action/game/device/child/owner acceptance.'))
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()});d['validation'].append(dict(command='V52 bounded known-item source refresh and prior-record preservation',result='PASS',evidence=(N/'REGISTER_EXTENSION_CHECK.json').relative_to(B).as_posix()+';2142/2142 source hashes,prior2050 records/88-item literal part unchanged,existing4MiB ceiling.'));write(IP,d)
allow=B/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|{p.relative_to(B).as_posix() for p in N.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for p in L.rglob('*') if p.is_file()}));print(r.stdout.decode().strip());print('V52',len(allitems),len(pri),len(unique),len(pending),(L/'ALL_ITEMS.json').stat().st_size,flush=True)
