extends SceneTree
func _initialize() -> void:
	var image_geologist_fossil := Image.new()
	assert(image_geologist_fossil.load_svg_from_string(FileAccess.get_file_as_string("res://assets/opera/worlds/hotspots/geologist_fossil.svg")) == OK)
	assert(image_geologist_fossil.save_png("res://audit/job_source_review_nursery_teacher_geology_v1_20261001/geologist_fossil_native.png") == OK)
	var image_geologist_layered_rock := Image.new()
	assert(image_geologist_layered_rock.load_svg_from_string(FileAccess.get_file_as_string("res://assets/opera/worlds/hotspots/geologist_layered_rock.svg")) == OK)
	assert(image_geologist_layered_rock.save_png("res://audit/job_source_review_nursery_teacher_geology_v1_20261001/geologist_layered_rock_native.png") == OK)
	var image_teacher_lesson_board := Image.new()
	assert(image_teacher_lesson_board.load_svg_from_string(FileAccess.get_file_as_string("res://assets/opera/worlds/hotspots/teacher_lesson_board.svg")) == OK)
	assert(image_teacher_lesson_board.save_png("res://audit/job_source_review_nursery_teacher_geology_v1_20261001/teacher_lesson_board_native.png") == OK)
	var image_goal_geologist := Image.new()
	assert(image_goal_geologist.load_svg_from_string(FileAccess.get_file_as_string("res://assets/opera/worlds/props/goal_geologist.svg")) == OK)
	assert(image_goal_geologist.save_png("res://audit/job_source_review_nursery_teacher_geology_v1_20261001/goal_geologist_native.png") == OK)
	var image_opera_crest_geologist := Image.new()
	assert(image_opera_crest_geologist.load_svg_from_string(FileAccess.get_file_as_string("res://assets/opera/worlds/ui/crests/opera_crest_geologist.svg")) == OK)
	assert(image_opera_crest_geologist.save_png("res://audit/job_source_review_nursery_teacher_geology_v1_20261001/opera_crest_geologist_native.png") == OK)
	print("JOB_SOURCE_SVG_NATIVE|5_RENDERED|NO_RUNTIME_EDIT")
	quit(0)
