from pathlib import Path
import datetime,hashlib,json,shutil
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
f=b/'assets_src/imagegen/geologist_geode_contact_v1_20261002';f.mkdir(exist_ok=False)
(f/'.gdignore').write_text('',encoding='utf-8');(f/'attempt_01').mkdir();(f/'review_tools').mkdir()
refs=['assets/opera/worlds/actors/animation/roshan_geologist_sheet_a.png','assets_src/imagegen/geologist_painted_rebuild_v1_20261001/open_geode/attempt_02/native.png','assets/opera/worlds/geology/painted_work_v1_20261001/work_slab.png']
inventory=refs+['assets_src/imagegen/geologist_painted_rebuild_v1_20261001/panning_contact/attempt_01/native.png']
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
prompt='''Use case: illustration-story. Generate ONE new transparent gameplay work cutout, not an atlas or a room. It repairs Geologist Roshan's missing hand-to-geode contact.
IMAGE_1 is Roshan geologist identity/costume authority only: same friendly young child's face, brown eyes, brown wavy hair with rainbow locks, tan exploration cap and round cyan lens, lilac puff sleeves, teal pocket vest, brown utility belt/pouch, lavender/aqua MERMAID tail and full rainbow fluke. Use the complete-tail cells. Exactly one Roshan; no human legs. Do not copy the crawling poses or sample-in-hand reward pose.
IMAGE_2 is the approved geode identity only: two matching lavender/aqua stone shell halves with plum contours, cream cavity rims and cyan/violet crystals permanently ROOTED INSIDE both cavities. Keep its mineral family and matte broad painted bands. No loose crystal in any hand, on the slab, or outside its cavity.
IMAGE_3 is the approved low cream/lavender stone support identity only. Preserve its broad rounded slab and readable top/side bands.
Primary request: Roshan sits at the LEFT of a small stone work slab, facing three-quarter RIGHT. Her complete mermaid tail curls left and rests; her torso leans toward her work. On the RIGHT the TWO OPEN GEODE HALVES rest upright on the slab, at a practical hand-working height. Both her connected arms reach the specimen: her left hand clearly braces the outside of the left shell, and her right hand clearly holds the outside rim of the right shell. Fingers curl around the shell EXTERIORS, thumbs on outer rims, leaving both crystal interiors visible. Show actual connected hand-to-stone contact, with no floating hand and no arm through a cavity. She looks at the geode with a small pleased, attentive smile. This is the quietly settled end of opening the stone, before celebration; no applause or reward carrying. The specimen is child-hand-sized, not a giant chest. The stone supports both halves rather than floating beneath them.
Style: polished 2D hand-painted children's storybook game art matching these sources. Rounded broad forms, calm high-key cream/lavender/aqua bands, clean warm-brown/plum outlines, slight handmade asymmetry and restrained painted texture. Match the established face and proportions. No photorealism, lifelike anatomy, glossy plastic, mesh rendering or flat vector replacement. The hands' contact must read clearly at phone size.
Composition: ONE connected complete character/geode/support cutout on a landscape canvas. Full cap, hair, body, tail, fin, both arms/hands, both complete halves and entire slab within generous genuine transparent margins. Keep the geode cavities separated and fully readable. No room, ground backdrop, floor shadow, text, sparkle veil, extra objects, extra arms, extra characters, detached minerals, white sticker rim, or duplicate specimen. Genuine RGBA transparency. This is a static gameplay source candidate, not a finished animation or cinematic frame.'''
(f/'attempt_01/PROMPT.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
plan={'status':'NAMED_CONTACT_GAP_GENERATION_PLANNED','baseline':'bc2d14160a3f532895ed95c5db646e8cf0b451ad','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'One static connected Geologist Roshan/geode/support work source. Current actual hand-contact scores 2.7 despite rooted opening material 4.6. No runtime binding, animation, geometry/input/save/reward changes. Preserve every candidate and judge source/contact separately from mounted action.','rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-VIS-06','DL-VIS-07','DL-MOT-01','DL-MOT-03'],'findings':['MA-PLAY-004','MA-VIS-006'],'inventory':[{'path':p,'sha256':sha(b/p),'role':'identity reference' if p in refs else 'existing pan-specific connected pose; source good but wrong object/grip for geode opening'} for p in inventory],'gap':'Existing work cells crouch with palms near the floor or point/hold a loose sample; they cannot brace both actual shell halves. Existing pan compound provides panning grip, not geode opening contact. Approved mineral/slab/identity artwork remains suitable as reference and is preserved.','references':refs,'prompt_sha256':sha(f/'attempt_01/PROMPT.txt'),'method':'builtin image_gen, transparent true','acceptance_gaps':'Static source only, complete action/actual mounting/arrival/opening/settle/return and device/child/owner approval remain separate.'}
(f/'PLAN.json').write_text(json.dumps(plan,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
impact={'id':'job-geode-contact-source-20261002','scope':plan['scope'],'baseline':plan['baseline'],'rules':plan['rules'],'findings':plan['findings'],'files':[p.relative_to(b).as_posix() for p in f.rglob('*') if p.is_file()],'validation':[{'command':'Inventory current geologist work cells, approved geode/slab and existing pan compound','result':'PASS','evidence':f.relative_to(b).as_posix()+'/PLAN.json; native sources directly viewed; exact references and prompt hash recorded before generation.'}],'acceptance_gaps':plan['acceptance_gaps']}
(b/'design/audit_impacts/job-geode-contact-source-20261002.json').write_text(json.dumps(impact,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
print('Named missing contact source planned; frozen game/machine boundary unchanged.')
