from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_contact_v1_20261002'
native=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-50a69702-0f15-4bdb-964f-abc082b04ea4.png');p=f/'attempt_01/native.png';assert not p.exists();shutil.copyfile(native,p)
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
im=Image.open(p);im.load();assert im.mode=='RGBA'
alpha=im.getchannel('A');hist=alpha.histogram();solid=alpha.point(lambda a:255 if a>=8 else 0).getbbox()
record={'status':'REJECTED_CONTACT_SCALE_AND_REACH_SOURCE_RETAINED','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'path':p.relative_to(b).as_posix(),'sha256':sha(p),'dimensions':list(im.size),'mode':im.mode,'alpha_zero_pixels':hist[0],'alpha_nonzero_below8_pixels':sum(hist[1:8]),'alpha_atleast8_bounds':solid,'generation_method':'builtin image_gen, transparent_background true, approved three references in PLAN.json','native_generator_path':str(native),'prompt_sha256':sha(f/'attempt_01/PROMPT.txt'),'source_material_score':4.6,'rooted_crystal_semantics_score':4.6,'near_hand_contact_score':4.6,'far_hand_reach_score':4.3,'practical_work_scale_score':4.1,'complete_static_pose_score':4.3,'evaluation':'Friendly face, full mermaid fin and current tan/teal/lilac costume remain readable. Both cream-rimmed cavities keep cyan/violet crystals rooted inside and sit on the stone. Near fingers visibly contact the left shell. The two halves are chest-sized instead of hand-sized; the far hand requires a very long mostly hidden reach across the pair. Reject this as the practical working source despite its good painted material.','refinement':'Reduce both geode halves and the slab while preserving Roshan scale. Show the entire far upper arm, elbow and forearm with plausible length above the low specimen. Keep the interiors visible and both grips on outer shells.','qualification':'One native static source directly reviewed, not mounted gameplay, continuous animation, whole-job or owner acceptance.'}
write(f/'attempt_01/SOURCE_REVIEW.json',record)
(f/'attempt_02').mkdir()
prompt='''Use case: illustration-story. Create a corrected new complete transparent static gameplay cutout, keeping the approved visual identity.
IMAGE_1 is the rejected first contact draft, used only to identify the specific scale/reach defect to fix. Keep Roshan's identity, costume, full rainbow tail and friendly attentive expression. Rebuild the contact geometry rather than preserving the defect. IMAGE_2 is the original approved geologist Roshan identity atlas. IMAGE_3 is the approved two-half rooted-crystal geode design. IMAGE_4 is the approved cream/lavender stone slab material/design.
Specific correction: keep Roshan at the same large child scale but make EACH geode half ONLY about 60% the first draft's height and width. The complete two-half geode is narrower than her curled tail-to-face width. Make the slab similarly shorter and smaller so this is practical close work, not a giant chest. The geode stands on the slab at her lower-chest/waist level. Her torso is to its LEFT facing RIGHT; full mermaid tail curls left, full fin visible.
Both hands physically grip the EXTERIOR of the two small shell halves, not crystals. The near arm has a bent elbow and fingers clearly curling around the left shell outside. The far shoulder, upper arm, bent elbow and forearm must ALL be visible above/behind the lowered small geode, following one clear anatomically connected line to fingers curled around the right shell. Both arm lengths must agree; no enormous hidden horizontal arm. Move her torso closer to the work if needed. Both open cream cavity rims and cyan/violet embedded crystal groups stay clearly visible, firmly ROOTED in their shells; no detached minerals, carrying, applause or loose loot.
Style: same polished 2D painted children's storybook art, rounded child-readable forms, clean warm-brown/plum contours, broad matte lavender/aqua/cream bands, slight handmade asymmetry. Preserve the original friendly child face, brown eyes, brown/rainbow hair, tan exploration cap with cyan lens, teal vest, lilac puff sleeves, brown belt/pouch, lavender/aqua mermaid tail. No realism, plastic, mesh appearance, flat vector graphics or new costume.
ONE complete connected character/small-geode/slab cutout, landscape canvas with generous genuine RGBA transparent margins. Complete head, hair, fin, hands, two halves and slab entirely inside canvas. No ground/backdrop/floor shadow/text/extra figures/extra arms/duplicate stones/white sticker border. This is an unbound static work-source candidate, not a cinematic or a finished animation.'''
(f/'attempt_02/PROMPT.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
write(f/'attempt_02/PLAN.json',{'status':'NAMED_A1_SCALE_REACH_CORRECTION_PLANNED','references':[p.relative_to(b).as_posix()]+json.loads((f/'PLAN.json').read_text())['references'],'prompt_sha256':sha(f/'attempt_02/PROMPT.txt'),'gap':'A1 practical scale4.1/far reach4.3; preserve rejected source and reduce specimen/support while keeping whole connected arms visible.'})
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
ip=b/'design/audit_impacts/job-geode-contact-source-20261002.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in f.rglob('*') if x.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append({'command':'Native first geode-contact candidate review','result':'FAIL','evidence':f.relative_to(b).as_posix()+'/attempt_01/SOURCE_REVIEW.json; static pose4.3/scale4.1/far reach4.3 despite material/rooted semantics4.6.'});write(ip,d)
license=b/'ASSET_LICENSES.md';s=license.read_text();s+='\n| `assets_src/imagegen/geologist_geode_contact_v1_20261002/attempt_01/native.png` | Built-in OpenAI image generation from the preserved geologist identity, rooted geode and painted slab references listed with hashes in `PLAN.json` | **Project-generated art** | `assets_src/imagegen/geologist_geode_contact_v1_20261002/PLAN.json` | Native RGBA unchanged; rejected static work-scale/reach candidate retained outside runtime; no protected original changed; generated 2026-10-02. |\n';license.write_text(s,encoding='utf-8',newline='\n')
print('A1 rejected and preserved; targeted smaller-specimen/visible-arm retry prepared.')
