from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_contact_v1_20261002'
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-d20395e2-5796-483d-93a1-3afac54d9593.png');p=f/'attempt_02/native.png';assert not p.exists();shutil.copyfile(source,p)
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
im=Image.open(p);im.load();a=im.getchannel('A');h=a.histogram();assert im.mode=='RGBA' and h[0]>im.width*im.height//2
review={'id':'GEO-CONTACT-SOURCE-02','status':'PROVISIONALLY_SELECTED_STATIC_SOURCE_ONLY_UNBOUND','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'path':p.relative_to(b).as_posix(),'sha256':sha(p),'dimensions':list(im.size),'mode':im.mode,'alpha_zero_pixels':h[0],'alpha_nonzero_below8_pixels':sum(h[1:8]),'alpha_atleast8_bounds':a.point(lambda x:255 if x>=8 else 0).getbbox(),'maximum_alpha':max(i for i,n in enumerate(h) if n),'generation_method':'builtin image_gen; transparent_background true; corrected complete generation from four role-bound references in attempt_02/PLAN.json','native_generator_path':str(source),'prompt_sha256':sha(f/'attempt_02/PROMPT.txt'),'source_material_score':4.6,'identity_score':4.6,'rooted_crystal_semantics_score':4.6,'near_hand_contact_score':4.6,'far_hand_reach_score':4.5,'practical_work_scale_score':4.6,'complete_static_pose_score':4.5,'evaluation':'The reduced pair now sits at a practical waist-level work scale on a smaller broad cream/lavender slab. Roshan has her complete curled rainbow fin, brown/rainbow hair and tan/teal/lilac geologist costume. Near fingers brace the left outer shell; the far upper arm runs from her shoulder toward the right outer grip, with proportions agreeing with the near arm. A short far forearm/elbow portion remains naturally occluded by the shell, so the static contact remains at the inclusive 4.5 drafting floor. Both cyan/violet mineral groups remain rooted inside cream rims. Material/identity/rooted semantics4.6; complete static pose4.5. Native alpha is preserved, including its low-level edge trace.','refinement':'Retain this source candidate. Test practical actual-work scale, contact anchors, the approach-to-grip/opening/settle/return states and compatibility with the existing independently opening geode before any runtime binding; do not show this settled compound alongside another painted geode.','mounted_score':None,'complete_action_score':None,'owner_acceptance':None,'qualification':'Native static source directly reviewed only. Source floor does not grant runtime, accepted animation, ordinary route, target-device, child, owner or whole-job acceptance.'}
write(f/'attempt_02/SOURCE_REVIEW.json',review)
plan=json.loads((f/'PLAN.json').read_text());plan.update(status=review['status'],selected='attempt_02/native.png',rejected=['attempt_01/native.png'],current_review='attempt_02/SOURCE_REVIEW.json');write(f/'PLAN.json',plan)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geologist geode hand contact — unbound source drafts</title><style>body{max-width:1120px;margin:25px auto;padding:0 20px;background:#f1f4fa;color:#273149;font:17px/1.6 system-ui}img{display:block;max-width:100%;height:auto}.checker{background:repeating-conic-gradient(#e3eaf1 0% 25%,white 0% 50%) 50%/28px 28px}.aqua{background:#bbe9e5}figure{margin:20px 0}figcaption{padding:10px}table{border-collapse:collapse;width:100%}td,th{padding:9px;text-align:left;vertical-align:top;border:1px solid #c7d0df}a{color:#4d3c8f}</style><body>
<p><a href="../../../audit/job_review_v2_20261001/index.html">Job artwork library</a> · <a href="../../../audit/job_artwork_refinement_live/all_items.html">Individual register</a></p>
<h1>Hands work on the geode; crystals stay inside</h1><p>This drafts the missing Geologist work contact, currently <b>2.7/5 in the game</b>. The second complete transparent source reaches <b>4.5/5 provisionally for the static pose</b>, with material, identity and rooted-crystal semantics <b>4.6/5</b>. It is <b>unbound</b>: complete opening, arrival, release and return still require real action review. No source pixels are combined with the live opening as a shortcut.</p>
<figure class="checker"><img src="attempt_02/native.png" width="1536" height="1024" alt="Unbound corrected geode-work candidate with both hands contacting smaller supported halves"><figcaption>Attempt 2, unchanged native RGBA on a browser checker display. Full mermaid tail and both open cavities are preserved.</figcaption></figure>
<table><tr><th>Individual source or relationship</th><th>Draft score</th><th>Evaluation and next work</th></tr><tr><td>Painted character/material/identity</td><td>4.6</td><td>Current tan cap, cyan lens, teal/lilac costume and complete rainbow tail stay clear in broad painted values.</td></tr><tr><td>Rooted geode interior</td><td>4.6</td><td>Both cream cavity rims contain cyan/violet mineral groups. No crystal appears in a hand or as detached loot.</td></tr><tr><td>Practical work scale and support</td><td>4.6</td><td>Small specimen at waist level rests on the low stone; pose and prop agree in scale.</td></tr><tr><td>Near hand-to-shell contact</td><td>4.6</td><td>Connected fingers visibly brace the exterior without hiding the interior.</td></tr><tr><td>Far reach/contact</td><td>4.5</td><td>Arm lengths are plausible; a short section remains occluded by the shell. Confirm both anchors and clearance in actual work.</td></tr><tr><td>Complete static work source</td><td>4.5</td><td>Provisionally retain at the inclusive refinement floor. This single settled pose cannot establish continuous opening or live gameplay acceptance.</td></tr><tr><td>Current live working contact</td><td>2.7</td><td>Unchanged; Roshan still crouches beside the work. Never substitute the source score for the actual mounted evaluation.</td></tr></table>
<figure class="aqua"><img src="attempt_02/native.png" width="1536" height="1024" alt="Same unchanged source against aqua for transparency review"><figcaption>Browser background only; the same native source pixels and alpha are unchanged.</figcaption></figure>
<h2>Rejected first candidate</h2><p>Material and rooted semantics are 4.6, but whole static pose <b>4.3</b>, practical scale <b>4.1</b> and far reach <b>4.3</b>. Chest-sized halves forced an excessive mostly hidden reach. Its original is preserved; the corrected candidate reduces the specimen/support and exposes a plausible shoulder-to-grip line.</p><figure class="checker"><img src="attempt_01/native.png" width="1536" height="1024" alt="Rejected oversized-geode and long-reach first work candidate"></figure>
<p><a href="PLAN.json">Inventory, named gap and reference hashes</a> · <a href="attempt_01/SOURCE_REVIEW.json">Rejected attempt review</a> · <a href="attempt_02/SOURCE_REVIEW.json">Selected source review and exact hash</a> · <a href="attempt_02/PROMPT.txt">Executed built-in imagegen prompt</a>. Originals and generator outputs stay separate; no protected book/voice/friend source changed. Target-device/child/owner, complete-action and all-job approval remain open.</p></body></html>'''
(f/'index.html').write_text(html,encoding='utf-8',newline='\n')
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
license=b/'ASSET_LICENSES.md';s=license.read_text();s+='\n| `assets_src/imagegen/geologist_geode_contact_v1_20261002/attempt_02/native.png` | Built-in OpenAI image generation with role-bound rejected A1/approved identity/rooted geode/slab references | **Project-generated art** | `assets_src/imagegen/geologist_geode_contact_v1_20261002/attempt_02/PLAN.json` | Native RGBA unchanged; smaller supported specimen and connected work grips; static pose4.5/material4.6 provisional, unbound, no accepted motion/runtime/device/owner claim; generated 2026-10-02. |\n';license.write_text(s,encoding='utf-8',newline='\n')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();s+='\n| `assets_src/imagegen/geologist_geode_contact_v1_20261002/index.html` | 🟣 | `CANDIDATE`; two preserved native static contact sources. A1 rejected whole pose4.3/scale4.1/far reach4.3; A2 material/identity/rooted semantics4.6, contact/whole static pose4.5 provisional. Both are unbound and confer no complete animation, live-work improvement, device/child/owner or all-job acceptance. Existing live contact2.7 remains. |\n';ledger.write_text(s,encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-geode-contact-source-20261002.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{x.relative_to(b).as_posix() for x in f.rglob('*') if x.is_file()}|{'design/05_DOC_LEDGER.md'});d['validation'].append({'command':'Direct native complete second geode contact source review','result':'PASS','evidence':f.relative_to(b).as_posix()+'/attempt_02/SOURCE_REVIEW.json; static floor4.5 only, mounted/action/owner lanes unassigned.'});write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';lst=json.loads(allow.read_text());write(allow,sorted(set(lst)|set(d['files'])))
print('Second work source preserved and reviewed: static pose4.5, unbound; first failure preserved.')
