from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
b=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=b/'assets_src/imagegen/geologist_geode_contact_v1_20261002';work=b/'audit/job_geode_supported_celebration_v1_20261002';live=b/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not (live/'ALL_ITEMS_V32.original.json').exists()
shutil.copyfile(live/'ALL_ITEMS.json',live/'ALL_ITEMS_V32.original.json');shutil.copyfile(live/'all_items.html',live/'ALL_ITEMS_V32.original.html')
d=read(live/'ALL_ITEMS.json');assert len(d['items'])==1727
for n in [1,2]:
 v=read(f/f'attempt_0{n}/SOURCE_REVIEW.json');score=v['complete_static_pose_score'];path=v['path'];ref=f.relative_to(b).as_posix()
 item={'id':f'GEO-CONTACT-SOURCE-0{n}','aliases':[f'GEO-CONTACT-SOURCE-0{n}'],'kind':'source','path':path,'region':None,'source_dimensions':v['dimensions'],'earlier_sha256':v['sha256'],'historical_source_score':score,'current_source_score':score,'evaluation':v['evaluation'],'refinement':v['refinement'],'families':['Geologist','Unbound geode work-contact source; '+('rejected first candidate' if n==1 else 'provisionally selected second candidate')],'original_reports':[ref+'/index.html'],'source_qualification':v['qualification'],'preview_path':path,'native_reference_observations':[],'current_checkout_sha256':v['sha256'],'current_byte_status':'NEW_NAMED_GENERATED_SOURCE','priority':score<=4.5,'protected_original':False,'current_mounted_score':None,'current_complete_action_score':None,'image_path':path,'image_scope':'Unchanged native static source on the register background; unbound, no mounted/action score','owner_acceptance':None,'latest_refinement':{'report':ref+'/index.html','note':'Native static pose '+str(score)+'/5; painted material 4.6. '+v['evaluation']},'current_capture_review':ref+f'/attempt_0{n}/SOURCE_REVIEW.json','current_reviewed_utc':v['reviewed_utc']}
 d['items'].append(item)
d['created_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();d['counts'].update(unique_source_files=1247,registered_items=1729,inclusive_current_source_priorities=678,new_named_generated_sources=2)
d['counts']['exact_earlier_bytes']=sum(x['current_byte_status']=='EXACT_EARLIER_BYTES' for x in d['items']);d['counts']['changed_bytes']=sum(x['current_byte_status']=='CHANGED_BYTES' for x in d['items'])
d['scope']='V33 known source union: 1247 unique source files + 328 pose cells + 50 runtime prop-use regions + 104 source-object regions = 1729 entries. Two newly generated contact candidates are individually reviewed, source-only and unbound; first pose4.3 rejected, second static pose4.5 provisional, both material4.6. Five current geode uses retain direct review on the same 375 unchanged rendered source files. Full verification separately includes those sources plus two corrected detector/test files (377). Exact V31/V32 register bytes are preserved. Other opinions retain their dates. 678 source/cell/region inclusive priorities and 385 source reviews unassigned; four additional current geode mounted priorities. No exhaustive actual-use/all-job/complete-action/device/child/owner acceptance.'
d['refresh_command']='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v33.py';write(live/'ALL_ITEMS.json',d)
tool=live/'review_tools/refresh_current_job_review_v33.py';shutil.copyfile(live/'review_tools/refresh_current_job_review_v32.py',tool)
p=live/'all_items.html';s=p.read_text().replace('refresh_current_job_review_v32.py','refresh_current_job_review_v33.py');s=s.replace('<p id="summary">','<p><a href="../../assets_src/imagegen/geologist_geode_contact_v1_20261002/index.html">Two new geode hand-contact sources</a>: first static pose 4.3 rejected, second 4.5 provisional and unbound; live working contact remains 2.7.</p><p id="summary">');p.write_text(s,encoding='utf-8',newline='\n')
p=b/'audit/job_review_v2_20261001/index.html';s=p.read_text().replace('1,727 entries','1,729 entries').replace('1,245 unique source files','1,247 unique source files').replace('676 known source/cell/region priorities across 547','678 known source/cell/region priorities across 549').replace('refresh_current_job_review_v32.py','refresh_current_job_review_v33.py')
s=s.replace('fresh 375-source full suite pending.','Full suite 2 stopped in static verification; corrected suite 3 is pending on 377 files.')
s=s.replace('<p id="ci">Current unmodified full regression suite is running on 375 frozen literal source files.</p>','<p id="ci">Corrected full suite 3 is running on 377 frozen machine-verification sources: the unchanged 375 rendered source files plus the corrected model detector and tests.</p>')
s=s.replace('full_ci_v2/RECEIPT.json\">Current suite receipt','full_ci_v3/RECEIPT.json\">Current suite receipt').replace("fetch('../job_geode_supported_celebration_v1_20261002/full_ci_v2/RECEIPT.json')","fetch('../job_geode_supported_celebration_v1_20261002/full_ci_v3/RECEIPT.json')")
s=s.replace('against 375 frozen literal source files.','against 377 frozen literal machine sources (375 captured source files unchanged plus the detector/test repair). The preserved <a href="../job_geode_supported_celebration_v1_20261002/full_ci_v2/RECEIPT.json">suite 2 static failure</a> misclassified a valid previously published WebP as an XML model; <a href="../job_geode_supported_celebration_v1_20261002/MODEL_SNIFF_FALSE_POSITIVE_V328.json">focused detector correction and negative tests</a> are recorded separately.')
s=s.replace('</section>\n<section><h2>All known','<p><a href="../../assets_src/imagegen/geologist_geode_contact_v1_20261002/index.html">New connected work-pose candidates</a>: first static source rejected 4.3 for excessive specimen scale/reach; regenerated second source reaches static 4.5 provisionally. Both native originals/prompts/reviews are preserved and unbound; live working contact remains 2.7 until actual complete action is rebuilt and reviewed.</p></section>\n<section><h2>All known',1)
p.write_text(s,encoding='utf-8',newline='\n')
p=work/'index.html';s=p.read_text();a=s.index('<p id="machine-status">');z=s.index('</p>',a)+4;s=s[:a]+'<p id="machine-status">Fresh unmodified full suite 3: pending on 377 frozen machine sources, comprising the same 375 unchanged rendered sources plus the model detector and its regression tests. Suite 2 stopped before any of 82 gameplay probes after a valid tracked WebP was misclassified as an XML model; <a href="MODEL_SNIFF_FALSE_POSITIVE_V328.json">exact cause and focused correction</a> and <a href="full_ci_v2/RECEIPT.json">failed receipt</a> are preserved. Parser, inference, import, resource contract and actual-route captures pass separately. No previous green evidence transfers to this verification boundary.</p>'+s[z:];s=s.replace('full_ci_v2/RECEIPT.json\">Current full regression receipt','full_ci_v3/RECEIPT.json\">Current full regression receipt');s=s.replace('<h2>Written repair priorities','<p><a href="../../assets_src/imagegen/geologist_geode_contact_v1_20261002/index.html">New connected work-source draft</a>: first pose 4.3 rejected, regenerated second pose 4.5 provisional/source material 4.6, both preserved and unbound. Current actual working contact remains 2.7.</p><h2>Written repair priorities');p.write_text(s,encoding='utf-8',newline='\n')
v=read(work/'REVIEW.json');v['qualification']=v['qualification'].replace('Full CI2 separately pending on 375 unchanged literal source files.','Full CI2 failed at model discovery before any gameplay probes; corrected suite3 separately pending on377 machine sources. All375 direct visual capture sources stay unchanged; two verification-tool files are added only to the machine boundary.');write(work/'REVIEW.json',v)
plan=read(work/'PLAN.json');plan['current_full_ci']='full_ci_v3/RECEIPT.json';plan['current_machine_source']='SOURCE_CURRENT_MACHINE_V3.json';write(work/'PLAN.json',plan)
shutil.copyfile(Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/geode_contact_source_v332.png'),f/'BROWSER_SOURCE_REVIEW_V332.png')
write(f/'BROWSER_SOURCE_REVIEW_V332.json',{'status':'DIRECT_BROWSER_SOURCE_REVIEW_RECORDED','source_views':['attempt_02/native.png on checker','attempt_02/native.png on aqua','rejected attempt_01/native.png on checker'],'images_loaded':3,'broken_images':0,'individual_opinion_rows':7,'native_source_dimensions':[1536,1024],'screenshot':'BROWSER_SOURCE_REVIEW_V332.png','evaluation':'The corrected native stays clean against both neutral backgrounds, with the complete fin, two contained interiors, near contact and plausible far reach visible. A low-level alpha trace remains in the original, not an opaque background. Static floor4.5 only; current game contact2.7 is unchanged.','qualification':'Browser backgrounds change only the review display, never source pixels. Unbound source review is separate from mounted/complete-action/owner acceptance.'})
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
attr=b/'.gitattributes';s=attr.read_text();s+='\nassets_src/imagegen/geologist_geode_contact_v1_20261002/** -text\naudit/job_artwork_refinement_live/ALL_ITEMS_V32.original.* -text\n';attr.write_text(s,encoding='utf-8',newline='\n')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();s=s.replace('V32 searchable known union: 1727 entries / 1245 unique sources','V33 searchable known union: 1729 entries / 1247 unique sources').replace('unchanged 676 source priorities / 385','678 source priorities / 385').replace('refresh V32 withholds','refresh V33 withholds').replace('Current375-source full suite2 pending, no transferred machine/owner acceptance.','Same375 rendered sources unchanged. Suite2 static model false-positive failure preserved; corrected suite3 pending on377 machine sources, no transferred machine/owner acceptance.');s+='\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V32.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact prior 1727-entry register before the two new unbound contact sources. |\n';ledger.write_text(s,encoding='utf-8',newline='\n')
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
 p=b/rel;s=p.read_text();s=s.replace('unreviewed.375-source unmodified full suite2 pending.','unreviewed. Full suite2 failed before gameplay probes because compressed WebP bytes were mistaken for an XML model. Focused corrected scanner/tests pass; fresh suite3 pending on377 machine sources, with all375 rendered sources unchanged.');p.write_text(s,encoding='utf-8',newline='\n')
for impactname,folder in [('job-geode-contact-source-20261002.json',f),('job-geode-supported-celebration-20261002.json',work)]:
 p=b/'design/audit_impacts'/impactname;v=read(p);v['files']=sorted(set(v['files'])|{x.relative_to(b).as_posix() for x in folder.rglob('*') if x.is_file()}|{'.gitattributes','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/ALL_ITEMS_V32.original.json','audit/job_artwork_refinement_live/ALL_ITEMS_V32.original.html','audit/job_artwork_refinement_live/all_items.html',tool.relative_to(b).as_posix(),'audit/job_review_v2_20261001/index.html'});write(p,v)
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(tool)],cwd=b,check=True)
allow=b/'tmp/v2_preview_allowed.json';lst=read(allow);covered=read(b/'design/audit_impacts/job-geode-contact-source-20261002.json')['files']+read(b/'design/audit_impacts/job-geode-supported-celebration-20261002.json')['files'];write(allow,sorted(set(lst)|set(covered)))
assert all(sha(b/x['path'])==x['sha256'] for x in read(work/'SOURCE_CURRENT_MACHINE_V3.json')['source_files'])
print('V33:1729 known entries,678 inclusive source/cell/region priorities,385 source opinions unassigned; all377 frozen machine sources unchanged.')
