from pathlib import Path
import json, subprocess, hashlib, datetime, shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
def read(p):return json.loads((r/p).read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def rel(p):return p.relative_to(r).as_posix()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
counts=read('audit/job_artwork_refinement_live/ALL_ITEMS.json')['counts']
assert counts['registered_items']==1553 and counts['inclusive_current_source_priorities']==579
root_entry='audit/job_review_v2_20261001/index.html'
banner='<section id="geode-embedded-owner-correction"><h2>Current geode correction and full native geology/teacher comparison</h2><p>The opened geode now has three crystals embedded in each concave mineral cavity. ImageGen native source4.6; revised individual open object-in-layout4.5 provisional. Earlier empty interiors/loose reward semantics are owner-rejected3.0, with all original drafts preserved.</p><p><a href="../job_geode_embedded_mount_v2_20261001/index.html">New opening and all48 geode native views</a> · <a href="../job_geology_painted_mount_v1_20261001/index.html">All78 painted geology contexts</a> · <a href="../job_vector_mount_review_v1_20261001/index.html">All76 teacher/earlier geology contexts</a> · <a href="../../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html">Every painted source and attempt</a></p><p>All202 native comparison captures are directly reviewed, individually scored and displayed with hashes. Hidden artwork remains unassigned. The reference room fails native resolution; fossil masking/assembly, slab stretching, panning material, hand contact and complete ordinary routes remain below target or unreviewed.</p><p>Current known-item register:1553 items/1182 unique source files/579 inclusive≤4.5 source priorities/388 unassigned source opinions. These discovery counts include shared dependencies and unbound drafts; they do not establish exhaustive actual use or all-game approval. <a href="../job_artwork_refinement_live/ALL_ITEMS.html">Browse every known item</a>.</p></section>'
for f in [root_entry,'audit/job_artwork_refinement_live/index.html']:
 p=r/f;s=p.read_text(encoding='utf-8');start=s.index('<main>')+len('<main>')
 if f!=root_entry:
  local= banner.replace('../job_geode','../job_geode').replace('../job_artwork_refinement_live/ALL_ITEMS.html','ALL_ITEMS.html')
 else:local=banner
 s=s[:start]+local+s[start:];p.write_text(s,encoding='utf-8',newline='\n')

master=r/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8');entry='Geode embedded-crystal correction and native comparison supplement (2026-10-01): [new illustrated opening](job_geode_embedded_mount_v2_20261001/index.html) retains13 native ImageGen originals/24 neutral displays/8 whole-canvas derivatives, with new embedded cavity source4.6 and revised isolated open-object placement4.5 provisional. Earlier empty interiors/loose crystal reward semantics are owner-rejected3.0; dated source opinions and failed placement remain historical. [All202 native comparisons](job_review_v2_20261001/index.html#geode-embedded-owner-correction) directly evaluate76 earlier vector/teacher,78 painted geology and48 geode endpoint views at1280/1600 widths. Masked/absent objects receive no mounted score; fossil masking/assembly, slab ratio, pan material, invitation support, connected hands and complete routes remain open. Current known register1553 entries/1182 sources/579 inclusive priorities/388 unassigned, including shared/unbound references. Published review6edb4ca8 full hosted run36950549322 succeeds; this does not grant current uncommitted supplement or visual/owner acceptance. [Impact](../design/audit_impacts/job-geology-painted-rebuild-20261001.json). No lifecycle closure or final comprehensive approval.\n\n'
anchor=s.index('## 0.');next_para=s.index('\n\n',anchor)+2;s=s[:next_para]+entry+s[next_para:];master.write_text(s,encoding='utf-8',newline='\n')

findings=r/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text(encoding='utf-8')
history=' 2026-10-01 geode correction: owner rejects empty geode/loose loot semantics. New painted embedded-interior source4.6 and revised isolated open-object placement4.5 remain provisional; all202 teacher/geology native fixture captures directly inspected with individual scores and hidden objects unassigned. Fossil masking/assembly, slab aspect, pan material, invitation support, connected actor work and complete ordinary training/story traversal remain open. [Current illustrated evidence](../job_geode_embedded_mount_v2_20261001/index.html), [all native comparisons](../job_review_v2_20261001/index.html#geode-embedded-owner-correction), [impact](../../design/audit_impacts/job-geology-painted-rebuild-20261001.json). No lifecycle change or complete-action/device/child/owner acceptance.'
for finding in ['MA-VIS-006','MA-PLAY-004']:
 start=s.index('## '+finding+'\n');end=s.find('\n## ',start+4);end=len(s) if end<0 else end;block=s[start:end];lines=block.splitlines(keepends=True)
 for i,line in enumerate(lines):
  if line.startswith('| history |'):
   assert line.rstrip().endswith('|');lines[i]=line.rstrip()[:-1]+history+' |\n';break
 else:raise AssertionError('Missing history '+finding)
 s=s[:start]+''.join(lines)+s[end:]
findings.write_text(s,encoding='utf-8',newline='\n')

ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');lines=s.splitlines()
for i,line in enumerate(lines):
 if line.startswith('| `assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html`'):
  lines[i]='| `assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html` | 🟣 | `CANDIDATE`;13 native ImageGen painted originals,24 neutral alpha displays and8 whole-canvas technical derivatives directly reviewed. Owner correction rejects empty geode/loose reward semantics3.0; embedded-interior source4.6 is unbound, isolated revised object placement4.5 provisional. All202 teacher/geology native comparisons individually scored. The1672×941 room is reference-only and fails native coverage; fossil masking/assembly, slab aspect, pan material, contact, full ordinary training/story/device/child/owner and comprehensive final approval remain open. |'
lines.extend(['','| `audit/job_geode_embedded_mount_v2_20261001/index.html` | 🟣 | `CANDIDATE`;48 directly inspected native opening views at1280/1600 widths, isolated original/literal/painted lanes and inherited seam/pull input; endpoint completion callbacks disconnected only in fixture to prevent awards/save. New crystals remain embedded in each cavity; initial overhang preserved, revised isolated placement4.5 provisional. Full career/training/story/device/child/owner acceptance remains open. |','| `audit/job_geology_painted_mount_v1_20261001/index.html` | 🔵 | `SUPPORTING_CURRENT`;78 native three-lane geology fixture captures directly inspected with individual hashes/scores, including masked source and study-only closed-texture reset defect. Painted room reference is under native resolution. No actual complete-route, runtime binding or owner pass. |','| `audit/job_vector_mount_review_v1_20261001/index.html` | 🔵 | `SUPPORTING_CURRENT`;76 native teacher/geology original/candidate fixture views directly inspected. Geology vector scores are owner-rejected; improved teacher invitation4.5 provisional. Actual opened lessons do not display replacement board pixels. Runtime failure/repair receipts preserved. |'])
ledger.write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')

# Exact already-published D CI evidence, fetched in full; no claims about this uncommitted supplement.
out=r/'audit/job_review_v2_20261001/hosted_native_supplement_v2';assert not out.exists();out.mkdir()
gh='C:/Program Files/GitHub CLI/gh.exe';run='36950549322';repo='Ebonyks/mermaid-roshan-reef'
metadata_cmd=[gh,'run','view',run,'--repo',repo,'--json','status,conclusion,headSha,jobs,url,createdAt,updatedAt']
p=subprocess.run(metadata_cmd,cwd=r,stdout=subprocess.PIPE,stderr=subprocess.PIPE,creationflags=subprocess.CREATE_NO_WINDOW);(out/'metadata.stderr.log').write_bytes(p.stderr);assert p.returncode==0;(out/'RUN.json').write_bytes(p.stdout)
raw_cmd=[gh,'run','view',run,'--repo',repo,'--log'];p=subprocess.run(raw_cmd,cwd=r,stdout=subprocess.PIPE,stderr=subprocess.PIPE,creationflags=subprocess.CREATE_NO_WINDOW);(out/'download.stderr.log').write_bytes(p.stderr);assert p.returncode==0;(out/'RAW.log').write_bytes(p.stdout)
md=json.loads((out/'RUN.json').read_text());assert md['headSha']=='6edb4ca8c57bfbfe3123636863a29c95165ac23f' and md['conclusion']=='success' and all(x['conclusion']=='success' for x in md['jobs'])
write(out/'RECEIPT.json',dict(status='PASS_EXACT_PUBLISHED_D_CI',head=md['headSha'],run_id=run,url=md['url'],fetched_utc=now,jobs=[dict(name=x['name'],conclusion=x['conclusion']) for x in md['jobs']],raw_log_bytes=len(p.stdout),raw_log_sha256=hashlib.sha256(p.stdout).hexdigest(),metadata_command=metadata_cmd,raw_command=raw_cmd,qualification='Machine acceptance for published6edb4ca8 only, no latest uncommitted supplement/art/action/device/child/owner/strict2D acceptance.'))
(out/'index.html').write_text('<!doctype html><meta charset="utf-8"><h1>Published review6edb4ca8 — full CI passed</h1><p><a href="RECEIPT.json">Exact machine receipt</a> · <a href="RUN.json">Full run metadata</a> · <a href="RAW.log">Complete raw log</a></p><p>Machine verification is separate from visual and owner acceptance.</p>',encoding='utf-8')

imp=r/'design/audit_impacts/job-geology-painted-rebuild-20261001.json';d=read(rel(imp))
d['scope']+=' Individually review and archive all202 exact native capture bytes with scores/nulls, preserve initial geode overhang and prior empty-interior source opinions, publish current V14 exact-hash item register and source reviewV2; update authority/finding history without lifecycle closure.'
d['scope']=d['scope'].replace(' Add separate disposable embedded-geode endpoint captures: preserve half aspect, repair the study-only closed texture reset, use inherited seam/pull input, disconnect only fixture endpoint completion callbacks to prevent career awards/save writes. Add separate disposable embedded-geode endpoint captures: preserve half aspect, repair the study-only closed texture reset, use inherited seam/pull input, disconnect only fixture endpoint completion callbacks to prevent career awards/save writes.',' Add separate disposable embedded-geode endpoint captures: preserve half aspect, repair the study-only closed texture reset, use inherited seam/pull input, disconnect only fixture endpoint completion callbacks to prevent career awards/save writes.')
prefixes=['assets_src/imagegen/geologist_painted_rebuild_v1_20261001','assets_src/vector/job_geology_teacher_refinement_v1_20261001','audit/job_geode_embedded_mount_v2_20261001','audit/job_geology_painted_mount_v1_20261001','audit/job_vector_mount_review_v1_20261001','audit/job_review_v2_20261001/hosted_native_supplement_v2','audit/job_review_v2_20261001/current_native_supplement_remote_v2']
named=['ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md',root_entry,'audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/ALL_ITEMS.html','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v14.py','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v14.py']
shutil.copyfile(__file__,r/'audit/job_geode_embedded_mount_v2_20261001/executed_record_authority_v102.py')
d['files']=sorted(set(d['files'])|set(named)|{rel(p) for prefix in prefixes for p in (r/prefix).rglob('*') if p.is_file()})
d['validation'].extend([dict(command='Direct native image review202/202 with qualified individual scores and exact source/viewport/progress/hash evidence',result='PASS',evidence='audit/job_geode_embedded_mount_v2_20261001/ALL_NATIVE_REVIEWS.json; audit/job_geology_painted_mount_v1_20261001/attempt_02/REVIEW.json; audit/job_vector_mount_review_v1_20261001/attempt_02/REVIEW.json'),dict(command='Official4.7.2 revised320px embedded-geode fixture parser/inference/analyzer/native/325 unchanged-source guard',result='PASS',evidence='audit/job_geode_embedded_mount_v2_20261001/attempt_02/PROCESS_RECEIPT.json'),dict(command='Current V14 source-hash register with owner semantic overlay and13 native source originals',result='PASS',evidence='audit/job_artwork_refinement_live/ALL_ITEMS.json'),dict(command='Exact published6edb4ca8 full GitHub CI run36950549322',result='PASS',evidence=rel(out/'RECEIPT.json'))])
d['acceptance_gaps']='No production geology binding changed.13-source finish opinions and202 native fixture scores remain separate from complete ordinary training/story careers, all-job actual-use completeness,388 unassigned source opinions, native room resolution, slab aspect, fossil masking/assembly, pan graphics, connected contact, continuous geode opening, device, child, owner and final report approval. Strict2D remains UNSATISFIED.';write(imp,d)
print('Authority/finding history and exactD CI archive recorded; coverage',len(d['files']),'files; rawCI',len(p.stdout),'bytes')
