from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess,sys
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'assets_src/imagegen/day2_doctor_wash_motion_v1_20261001'
source='assets_src/imagegen/day2_doctor_wash_motion_v1_20261001/motion_key01_attempt01_native.png'
review=dict(status='CANDIDATE_AT_SOURCE_FLOOR_UNBOUND',checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),id='WASH-DOCTOR-MOTION-KEY01',path=source,sha256=hashlib.sha256((r/source).read_bytes()).hexdigest(),source_score=4.5,identity_score=4.5,hand_contact_source_score=4.5,evaluation='The same warm child face, doctor coat, broad pastel tail and intact two-lobed fin remain registered with the prior draft. One attached hand now strokes the back of the other, with readable finger contact and attached lather. The static painted source meets the4.5 floor; original-body/native contact and continuous rubbing remain unreviewed.',alpha_evaluation='The apparent bright red flecks in the transparency display are alpha1/255 RGB samples. Direct original-size white and aqua composites show no visible disconnected red cluster. No manual alpha deletion, mask, colour cleanup or pixel repair was applied; do not misreport raw hidden/near-hidden RGB as an opaque subject defect.',source_input='assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/attempt_06_native.png',source_input_sha256='3ada2bd00859314ece42ccffa2dc20aae9543086b1161d6e8336689021c99d2c',direct_review=['Built-in generated full RGBA output','Original-size neutral white and aqua compositing views'],mounted_score=None,continuous_motion_score=None,complete_action_score=None,owner_accepted=False,qualification='Source-only floor. A consecutive key may have small finger travel; exact hand/body registration, native sink contact, full action, current runtime, device, child and owner acceptance remain pending. Original bindings unchanged.')
(out/'MOTION_KEY01_ATTEMPT01_REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8',newline='\n')
(out/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor washing: consecutive source-key study</title><style>body{background:#edf4fa;color:#25304a;font:17px/1.5 system-ui;margin:0}main{max-width:1120px;margin:auto;padding:24px}section{background:white;border-radius:16px;padding:22px;margin:20px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px}figure{margin:0}img{display:block;max-width:100%;width:100%;height:430px;object-fit:contain;background:repeating-conic-gradient(#dce5ed 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}a{color:#504096}code{overflow-wrap:anywhere}</style><main><section><a href="../../../audit/job_review_v2_20261001/index.html">Current review entry</a><h1>Doctor washing: one consecutive source-key draft</h1><p>The existing painted sink will be reused. This complete generated character key addresses the named missing hand-rubbing pose; it is an unbound4.5 source-floor candidate. Native contact, exact registration and the full action remain pending.</p><p><a href="MOTION_KEY01_ATTEMPT01_REVIEW.json">Individual written evaluation</a> · <a href="MOTION_KEY01_ATTEMPT01_PROMPT.json">Exact prompt, reference and hashes</a> · <a href="PROFILE.json">Reuse inventory and gap</a></p></section><section class="grid"><figure><img src="../day2_doctor_wash_pose_v1_20261001/attempt_06_native.png" alt="Earlier doctor wash source6"><figcaption>Earlier draft/source4.5. Original bindings unchanged.</figcaption></figure><figure><img src="motion_key01_attempt01_native.png" alt="Consecutive hand rubbing key"><figcaption>New complete generated key/source4.5. Timed and mounted acceptance pending.</figcaption></figure></section><section><h2>Alpha interpretation</h2><p>Apparent red remnants in the transparency display have measured alpha1/255 at the inspected samples. These neutral composites were directly inspected at original size; they show no visible disconnected cluster. The native RGBA remains unmodified.</p><div class="grid"><figure><img src="motion_key01_attempt01_review_white.png" alt="White neutral alpha review"><figcaption>Review-only white composite.</figcaption></figure><figure><img src="motion_key01_attempt01_review_aqua.png" alt="Aqua neutral alpha review"><figcaption>Review-only aqua composite.</figcaption></figure></div><p><a href="MOTION_KEY01_ATTEMPT01_ALPHA.json">Exact alpha measurements</a></p></section></main></html>''',encoding='utf-8',newline='\n')
profile=out/'PROFILE.json';d=json.loads(profile.read_text(encoding='utf-8'));d['status']='ONE_SOURCE_FLOOR_KEY_UNBOUND';d['current_review']='MOTION_KEY01_ATTEMPT01_REVIEW.json';profile.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
shutil.copyfile(__file__,out/'executed_review_doctor_motion_key_v24.py')
license=r/'ASSET_LICENSES.md';s=license.read_text(encoding='utf-8')
for p in out.glob('*.png'):
 rel=p.relative_to(r).as_posix()
 assert '| '+rel+' |' not in s
 desc='Whole complete built-in imagegen RGBA; generated draft input, no protected originals; unbound source4.5, native/timed/owner pending.' if p.name.endswith('_native.png') else 'Review-only alpha compositing on a neutral '+('white' if 'white' in p.name else 'aqua')+' field; generated source pixels unchanged, not delivery/runtime artwork.'
 s+='\n| '+rel+' | OpenAI/Codex built-in imagegen, owner-commissioned game-art study2026-10-01 | Generated project artwork; underlying generated draft retains provenance | Built-in tool; exact prompt/reference/profile beside source | '+desc+' |\n'
license.write_text(s,encoding='utf-8',newline='\n')
ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');line='| `assets_src/imagegen/day2_doctor_wash_motion_v1_20261001/index.html` | 🟣 | `CANDIDATE`; one generated consecutive doctor hand-rubbing source4.5 and exact input/prompt/native hashes; neutral alpha interpretation, no runtime/timed/device/child/owner acceptance. |\n'
assert '`assets_src/imagegen/day2_doctor_wash_motion_v1_20261001/index.html`' not in s;ledger.write_text(s+'\n'+line,encoding='utf-8',newline='\n')
family=r/'audit/job_review_v2_20261001';old=family/'review_tools/build_current_job_item_register_v7.py';new=family/'review_tools/build_current_job_item_register_v8.py'
s=old.read_text(encoding='utf-8');needle='for q in items.values():\n p=q[\'path\']'
assert s.count(needle)==1
block="""motion=read('assets_src/imagegen/day2_doctor_wash_motion_v1_20261001/MOTION_KEY01_ATTEMPT01_REVIEW.json');p=motion['path']
items[p]=dict(id=motion['id'],aliases=[],kind='source',path=p,earlier_sha256=motion['sha256'],historical_source_score=motion['source_score'],evaluation=motion['evaluation'],refinement='Evaluate the exact native sink/hands registration and consecutive keys before binding; source-floor4.5 does not pass the washing action.',families=['Day Two washing','Unbound consecutive doctor motion key'],original_reports=['assets_src/imagegen/day2_doctor_wash_motion_v1_20261001/index.html'],source_qualification=motion['qualification'],preview_path=p,native_reference_observations=[],runtime_binding_state=motion['status'])
"""
s=s.replace(needle,block+needle).replace('build_current_job_item_register_v7.py','build_current_job_item_register_v8.py');new.write_text(s,encoding='utf-8',newline='\n')
subprocess.run([sys.executable,'-X','utf8','-B',str(new)],cwd=r,check=True)
counts=json.loads((r/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text(encoding='utf-8'))['counts']
impact=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(impact.read_text(encoding='utf-8'));d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in out.rglob('*') if p.is_file()}|{new.relative_to(r).as_posix(),'ASSET_LICENSES.md','design/05_DOC_LEDGER.md'});impact.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
allowed=r/'tmp/v2_preview_allowed.json';d=json.loads(allowed.read_text(encoding='utf-8'));d=sorted(set(d)|{p.relative_to(r).as_posix() for p in out.rglob('*') if p.is_file()}|{new.relative_to(r).as_posix()});allowed.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
print(json.dumps(dict(source_score=review['source_score'],status=review['status'],counts=counts)))
