from pathlib import Path
from PIL import Image,ImageDraw
import numpy as np,json,hashlib
p=Path(__file__).resolve().parent;d=p/'visual';rows=[];board=Image.new('RGB',(1280,760),'#20343e');draw=ImageDraw.Draw(board)
for i,name in enumerate(['canvas_screen_3_day','canvas_screen_3_night']):
 g=json.loads((d/(name+'_geometry.json')).read_text());rest=Image.open(d/(name+'_rest.png')).convert('RGB');a=np.asarray(rest).astype(int);mask=Image.new('L',rest.size);ImageDraw.Draw(mask).line([tuple(x) for x in g['screen_points']],fill=255,width=max(1,round(g['width'])));mask.save(p/(name+'_pathmask.png'));sel=np.array(mask)>0;assert sel.sum()>0
 comparisons=[];union=np.zeros(sel.shape,bool)
 for k in range(1,4):
  b=np.asarray(Image.open(d/f'{name}_retired{k}.png').convert('RGB')).astype(int);c=np.asarray(Image.open(d/f'{name}_restored{k}.png').convert('RGB')).astype(int);delta=abs(a-b).max(2);union|=(delta>2)&sel;comparisons.append({'retired_pose':k,'path_changed_over_2_codes':int(((delta>2)&sel).sum()),'path_max_delta':int(delta[sel].max()),'full_frame_restoration_max_error':int(abs(a-c).max())})
 marked=np.array(rest);marked[union]=[255,20,40];overlay=Image.fromarray(marked);overlay.save(p/(name+'_path-overlap.png'));crop=overlay.copy();crop.thumbnail((640,360));board.paste(rest.resize((640,360)),(0,i*380+20));board.paste(crop,(640,i*380+20));draw.text((5,i*380+3),name+' current rest',fill='white');draw.text((645,i*380+3),'red: retired pose changes inside path corridor',fill='white');rows.append({'view':name,'path_mask_pixels':int(sel.sum()),'retired_changed_union':int(union.sum()),'comparisons':comparisons})
board.save(p/'path-gpu-board.jpg',quality=94);report={'status':'GPU_CONTAINMENT_PASS_REPLACEMENT_MOTION_PENDING','rows':rows,'passed':all(c['full_frame_restoration_max_error']==0 for r in rows for c in r['comparisons']),'scope':'Actual imported Mobile1280x720 day/night renders. All unrelated clocks frozen; force retired approach-bank poses1..3, then let current controller reset its quarantined card to0. Path corridor projected with actual Canvas transform. This verifies disabled-card containment only, not full live-world or all path-edge acceptance.','captures':{f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(d.glob('*.png'))}};(p/'GPU_RESULT.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='captures'},indent=2))
