from pathlib import Path
import datetime,hashlib,json,shutil
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');M=B/'assets_src/imagegen/candy_wrap_contact_v1_20261003';P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003'
prompt='''Use case: precise-object-edit. Asset type: ONE transparent painted 2D Candy Maker working pose; a physical far-edge paper fold, not a motion clip or pose sheet.
IMAGE_1 is the complete edit target. Keep the exact child face, hair/rainbow ribbon, cap, costume, head position, lavender tabletop outline, camera and sweet center/size. Keep the gold paper attached as one continuous sheet.
Change ONLY the local paper fold, left-on-screen mitten position and its connected forearm bend. The left-on-screen coral quilted mitten has now carried its held FAR gold-paper edge forward and downward across the SAME red oval. That gold flap curves over the far rim and lies across the upper TWO THIRDS of the red sweet; only a narrow red crescent on its near/front third remains visible. The left mitten still visibly pinches the FREE EDGE of that flap, immediately above the remaining red crescent, near the sweet center. This mitten has advanced toward the viewer and toward the sweet; do not leave it at the old outer-left corner. The right-on-screen mitten remains in its original supporting position beside the right of the sweet, firmly connected to its sleeve. The near/front long edge remains spread flat on the table, ready for the next fold.
This is one meaningful halfway fold: no finished tube, no necks, no twisted fans, no extra sweet, no floating glove. Preserve exactly two quilted coral mittens, broad painted gold creases, plum outlines and lavender shading. The flap must physically cover the SAME red oval without moving or enlarging it. Do not keep the whole sweet exposed. Preserve genuine transparent background and complete original silhouette, no labels or background. Return the complete single pose.
'''
source=M/'attempt11/native.png';assert hashlib.sha256(source.read_bytes()).hexdigest()=='884af7e93b6a19bd15f59f81a88e94368ca513955f3eda93141bbad4b38ddbe6'
path=M/'PLAN_A12.json';assert not path.exists();path.write_text(json.dumps(dict(planned_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),attempt=12,source=str(source),source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),inventory='All existing ten four-pose contact sources, A11 full-pose far grip, three wrapper sources and both local takes reviewed. Earlier A10 bridge has unresolved candy size/contact continuity; A11 is a starting grip only. A1 whole2.4 and A2 far-fold1.8 leave the sweet exposed. No suitable same-scale advancing far-flap source exists.',gap='One explicit mid-fold gold flap carried by a connected mitten across the same supported sweet.',validation='Inspect full original native and individual hand/paper/support/identity opinions before use; source-only until separate motion/runtime review.',production_binding=False,owner_acceptance=None),indent=2)+'\n',encoding='utf-8')
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-local-wrap-continuity-20261003.json';d=json.loads(ip.read_text(encoding='utf-8'));d['scope']+=' After all41 A2 native canvases fail the far-fold component1.8, repair the single missing advancing far-flap pose through builtin ImageGen A12. Existing identity/table/sweet anchors remain requirements, not presumed passes. Preserve every failed study and generated native; no runtime change.';d['files']=sorted(set(d['files'])|{path.relative_to(B).as_posix(),(P/'review_tools'/Path(__file__).name).relative_to(B).as_posix()});n=ip.with_name(ip.name+'.v552_next');n.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8');n.replace(ip)
print('A12 named-gap plan recorded before generation.')
