from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003';S=B/'audit/job_shared_background_review_v1_20261003';T=B/'assets_src/imagegen/playroom_stacking_toy_painted_v1_20261003';IP=B/'design/audit_impacts/job-candy-shared-library-continuation-20261003.json';read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def put(p,raw):n=p.with_name(p.name+'.v571_next');n.write_bytes(raw);n.replace(p)
def write(p,d):put(p,(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode())
write(S/'BROWSER_INITIAL_OVERFLOW_V570.json',dict(status='REPORT_FILTERS_PASS_LONG_SOURCE_PATH_OVERFLOW_FAIL',checked_utc=now(),url='http://127.0.0.1:8880/audit/job_shared_background_review_v1_20261003/index.html?revision=v48',sources=65,priorities=53,context_images=6,filter_counts=[53,65],horizontal_overflow=True,qualification='Actual desktop DOM observation; source/path wrapping repair required. No game/visual acceptance claim.'))
for p in [S/'index.html',T/'index.html']:
 t=p.read_text();t=t.replace('</style>','p,small{overflow-wrap:anywhere}body{box-sizing:border-box}.grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr))}</style>',1);put(p,t.encode())
im=Image.open(T/'attempt03/native.png');a=im.getchannel('A');w,h=im.size;edges={}
for name,box in [('left',(0,0,1,h)),('right',(w-1,0,w,h)),('top',(0,0,w,1)),('bottom',(0,h-1,w,h))]:
 v=list(a.crop(box).get_flattened_data());edges[name]=dict(nonzero_pixels=sum(x>0 for x in v),pixels_at_least128=sum(x>=128 for x in v),maximum=max(v))
threshold=a.point(lambda x:255 if x>=128 else 0);bbox=list(threshold.getbbox());assert all(x['pixels_at_least128']==0 for x in edges.values())
write(T/'attempt03/ALPHA_EDGE_EVIDENCE.json',dict(status='OPAQUE_OBJECT_OUTLINE_COMPLETE_TINY_ALPHA1_EDGE_TRACES_RETAINED',checked_utc=now(),native_sha256=sha(T/'attempt03/native.png'),native_dimensions=[w,h],literal_alpha_bbox=list(a.getbbox()),alpha128_bbox=bbox,edge_samples=edges,qualification='Only alpha1 traces touch left/bottom; no alpha>=128 object pixels meet canvas edge. Complete native remains untouched. This distinguishes almost-transparent edge noise from a clipped opaque base; provide whole-canvas padding in later technical conversion, and inspect phone-size mounted contours independently.'))
write(P/'BROWSER_CONTROL_OBSERVATIONS_V570.json',dict(status='ACTUAL_NATIVE_VIDEO_FRAME_CONTROLS_AND_SOURCE_GALLERY_PASS',checked_utc=now(),url='http://127.0.0.1:8880/assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html?revision=v48',native_articles=164,component_rows=40,a4_selected_frame=40,a4_frame_score=0.5,a4_native_play=dict(paused=False,time_seconds=0.243829,width=896,height=512),a4_native_pause=dict(paused=True,time_seconds=0.285401),horizontal_overflow=False,stacker_source_images=[dict(attempt=i,width=1236 if i<3 else 1199,height=1272 if i<3 else 1312,complete=True) for i in [1,2,3]],stacker_opinions=21,qualification='Actual browser reads of report controls/source loading, not creative/runtime acceptance. Shared source report initial overflow separately retained before wrapping fix.'))
G=P/'gates_v2';G.mkdir(exist_ok=False)
write(G/'PLAN.json',dict(status='FRESH_EXPANDED_REVIEW_GATES_PLANNED',planned_utc=now(),baseline='ae3880df4244139a4f681034b530a5ee2c68895d',scope='Expanded A3/A4 motion/source/context/library/painted toy review artifacts, no production source delta.',commands=[['tools/audit_document_authority.py'],['tools/audit_development.py','--base','auto'],['-m','unittest','tools.tests.test_audit_document_authority','tools.tests.test_audit_development'],['tools/audit_game_2d.py','--regression-gate']],qualification='Structural and no-regression checks only. No full visual, strict zero-debt, new production or owner acceptance.'))
for name in ['authority','development','document_tests','game2d']:
 for suffix in ['stdout.log','stderr.log']:put(G/(name+'.'+suffix),b'')
 write(G/(name+'.receipt.json'),dict(status='PENDING',qualification='Placeholder before actual process execution; no inherited pass.'))
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
d=read(IP);d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for folder in [P,S,T] for p in folder.rglob('*') if p.is_file()});d['scope']+=' Preserve real report overflow failure, repair filename wrapping and independently distinguish alpha1 edge noise from clipped opaque toy contours.';write(IP,d)
print(json.dumps(dict(status='RESPONSIVE_WRAP_AND_NATIVE_ALPHA_EVIDENCE_SAVED_FRESH_GATES_PLANNED',opaque_alpha_bbox=bbox)))
