from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');M=B/'assets_src/imagegen/candy_wrap_contact_v1_20261003';P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003';A=M/'attempt12'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
 n=p.with_name(p.name+'.v553_next');n.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8');n.replace(p)
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-8e4fa07f-deb9-46e9-85c1-d0507b93616e.png');assert not A.exists();A.mkdir();shutil.copyfile(source,A/'native.png');plan=read(M/'PLAN_A12.json')
with Image.open(A/'native.png') as im:dims=list(im.size);mode=im.mode;alpha=list(im.getchannel('A').getextrema())
assert dims==[1254,1254] and sha(source)==sha(A/'native.png')
write(A/'SOURCE.json',dict(attempt=12,method='builtin_imagegen_precise_object_edit',native_path=(A/'native.png').relative_to(B).as_posix(),source_original=str(source),sha256=sha(source),dimensions=dims,mode=mode,alpha_extrema=alpha,reference_path='assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt11/native.png',reference_sha256=plan['source_sha256'],prompt=plan['prompt'],prompt_sha256=plan['prompt_sha256'],regions=[[0,0,1254,1254]],grid=[1,1],native_preserved=True,runtime_ready=False,runtime_bound=False,owner_acceptance=None,qualification='Exact single whole pose preserved. Paper now partly covers the sweet, but left mitten holds the high/rear flap point rather than its lower free edge. No motion/runtime pass.'))
opinions=[('Same gold-paper partial fold',4.5,'One attached gold flap now lies diagonally over the upper sweet. Material remains recognizable; a larger red crescent than requested remains.'),('Required free-edge grip',3.9,'Left mitten advances inward but still holds the high/rear corner of the raised triangular flap. Its thumb/palm do not pinch the lower free edge across the sweet.'),('Connected arms',4.5,'Both quilted mittens remain connected through sleeves; no extra hands.'),('Supported same sweet',4.5,'Red oval remains on the same gold sheet/table with visually similar center/scale; no measured anchor tolerance pass.'),('Identity and material',4.5,'Recognizable costume, hair, face and broad painted gold/lavender material retained.'),('Requested two-thirds cover',4.2,'The gold flap partly covers the upper sweet but leaves a broad red crescent; exact prescribed coverage not met.'),('Whole required source role',4.3,'Reject this exact required free-edge grip role. Preserve the useful partial paper state, but repair the mitten grasp before another motion study.')]
write(A/'DIRECT_REVIEW.json',dict(status='PARTIAL_FOLD_VISIBLE_REQUIRED_FREE_EDGE_GRIP_REJECTED',reviewed_utc=now(),direct_native_review=True,native_sha256=sha(source),whole_source_score=4.3,production_binding=False,owner_acceptance=None,opinions=[dict(item=i,score=s,evaluation=e) for i,s,e in opinions],qualification='Complete generated native directly inspected. Whole source4.3 remains weak. Native is unbound/NPOT and not a temporal frame or current-game pass.'))
prompt='''Use case: precise-object-edit. ONE transparent complete painted 2D Candy Maker pose. IMAGE_1 is the exact edit target.
Correct ONLY the LEFT-ON-SCREEN coral oven mitten, its continuously connected forearm bend, and the local gold flap necessary for a real grasp. Currently this mitten holds the high/rear flap corner. Move this mitten DOWN and slightly RIGHT, directly over the red sweet. Its palm presses the left quarter of the covering gold flap, and its single mitten THUMB visibly curls UNDER the LOWER FREE EDGE of that flap, immediately above the remaining red crescent. The gold lower free edge is visibly pinched between thumb and palm at the sweet's left-of-center point. Show this real over-and-under grasp, not a mitten touching the rear triangular peak. Lower the raised peak so the gold flap lies snugly across the upper two thirds of the same oval, leaving a narrow red crescent at the near/front edge. The same paper stays continuously attached to the sheet beneath the sweet.
Keep exactly the same red sweet center/size, right-on-screen bracing mitten and forearm, table, complete head/hair/rainbow/cap, body/costume, camera, painted materials and transparent backdrop. Two mittened hands only; no bare fingers, no detached arm. No completed wrapper necks, no twist, no extra candy, no text or background. Return the entire same single pose. A useful free-edge grip is the sole correction.
'''
write(M/'PLAN_A13.json',dict(planned_utc=now(),attempt=13,source=str(A/'native.png'),source_sha256=sha(source),prompt=prompt,prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),inventory='A12 now supplies a useful partial fold, but required lower free-edge grasp3.9/whole4.3 fails. Existing A11 starting grip and prior atlas states do not supply that same supported partial-fold grasp.',gap='Single connected mitten thumb-under/palm-over grasp on the gold lower free flap edge; preserve all other pixels semantically.',production_binding=False,owner_acceptance=None))
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
ip=B/'design/audit_impacts/job-candy-local-wrap-continuity-20261003.json';d=read(ip);d['scope']+=' A12 partial paper state is visible but exact free-edge grip fails3.9/whole4.3; preserve it and regenerate only that local mitten/flap grasp as A13 before action use.';d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in A.rglob('*') if p.is_file()}|{(M/'PLAN_A13.json').relative_to(B).as_posix(),(P/'review_tools'/Path(__file__).name).relative_to(B).as_posix()});write(ip,d)
print('A12 exact native archived; required free-edge grip rejected. A13 scoped before generation.')
