from pathlib import Path
import copy,datetime,hashlib,html,json,shutil,subprocess
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');P=B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003';M=B/'assets_src/imagegen/candy_wrap_contact_v1_20261003';L=B/'audit/job_artwork_refinement_live';A=M/'attempt13';IP=B/'design/audit_impacts/job-candy-local-wrap-continuity-20261003.json'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def update(p,raw):
 n=p.with_name(p.name+'.v554_next');n.write_bytes(raw);n.replace(p)
def write(p,d,compact=False):update(p,(json.dumps(d,ensure_ascii=False,indent=None if compact else 2,separators=(',',':') if compact else None)+'\n').encode())
source=Path('C:/Users/Peter/.codex/generated_images/01a0f309-110a-7602-af22-f30d657bd017/exec-bc62f7f4-0e06-487e-8dc2-9d7b65e3bd71.png');assert not A.exists();A.mkdir();shutil.copyfile(source,A/'native.png');plan=read(M/'PLAN_A13.json')
with Image.open(A/'native.png') as im:dims=list(im.size);mode=im.mode;alpha=list(im.getchannel('A').getextrema())
assert dims==[1254,1254] and sha(source)==sha(A/'native.png')
write(A/'SOURCE.json',dict(attempt=13,method='builtin_imagegen_precise_object_edit',native_path=(A/'native.png').relative_to(B).as_posix(),source_original=str(source),sha256=sha(source),dimensions=dims,mode=mode,alpha_extrema=alpha,reference_path='assets_src/imagegen/candy_wrap_contact_v1_20261003/attempt12/native.png',reference_sha256=plan['source_sha256'],prompt=plan['prompt'],prompt_sha256=plan['prompt_sha256'],regions=[[0,0,1254,1254]],grid=[1,1],native_preserved=True,runtime_ready=False,runtime_bound=False,owner_acceptance=None,qualification='Exact single whole pose preserved; useful partial-fold clamp source, not the complete wrapping action. No runtime/anchor-tolerance/motion pass.'))
opinions=[('Partial fold and lower mitten clamp',4.5,'Left palm now reaches the lower flap edge over the sweet; its thumb lobe opposes the palm on the flap. The lowered gold flap reads as a useful partial fold rather than the A12 rear-point hold. Static draft only.'),('Connected hands',4.5,'Two quilted mitten contours connect through bent sleeves; the left hand is advanced toward the sweet and the right retains support.'),('Same supported sweet',4.5,'The same red oval remains beneath the flap on the same worktop; no measured inter-source anchor tolerance is claimed.'),('Golden paper material',4.5,'Single attached crinkled gold sheet and plum contour agree with the specific wrapper. Free flap edge stays readable above the remaining red crescent.'),('Exact requested two-thirds coverage',4.2,'A broad red crescent remains. This is a partial-fold source, not an exact two-thirds-covered or fully closed state.'),('Identity and style',4.5,'Same child face, cap, rainbow hair, waistcoat and lavender table remain recognizable in the painted 2D family.'),('Whole partial-fold source',4.5,'Provisional floor for one partial fold pose. Stronger useful clamp than A12; it cannot pass a continuous fold, neck pinch, opposing twist, release, in-game use or owner acceptance.')]
write(A/'DIRECT_REVIEW.json',dict(status='PARTIAL_FOLD_SOURCE_4_5_PROVISIONAL_EXACT_COVERAGE_ROLE_4_2',reviewed_utc=now(),direct_native_review=True,native_sha256=sha(source),whole_source_score=4.5,requested_exact_coverage_score=4.2,production_binding=False,owner_acceptance=None,opinions=[dict(item=i,score=s,evaluation=e) for i,s,e in opinions],qualification='Complete original native directly inspected. Useful partial-fold pose reaches source-only drafting floor4.5 and remains an inclusive priority. Exact requested coverage4.2 is not met. No source-to-motion/runtime/owner acceptance transfer.'))
for i in [12,13]:
 a=M/f'attempt{i:02d}';s=read(a/'SOURCE.json');r=read(a/'DIRECT_REVIEW.json')
 rows=''.join('<li><strong>'+html.escape(x['item'])+' · '+str(x['score'])+'/5</strong>: '+html.escape(x['evaluation'])+'</li>' for x in r['opinions'])
 text='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Candy contact source '+str(i)+'</title><style>body{font:18px/1.5 system-ui;max-width:980px;margin:30px auto;padding:20px;background:#edf5fa;color:#25344b}img{width:100%;height:auto;background:#e3edf3}li{margin:14px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}a{color:#454590}</style><h1>Candy contact source '+str(i)+' · '+str(r['whole_source_score'])+'/5</h1><p>'+html.escape(r['status'])+'</p><img src="native.png" width="1254" height="1254" alt="Complete original partial-fold source '+str(i)+'"><ul>'+rows+'</ul><p>'+html.escape(r['qualification'])+'</p><p><a href="../index.html">All contact sources</a> · <a href="../../../local_motion/candy_wrap_continuity_v1_20261003/index.html">Every native motion frame</a> · <a href="SOURCE.json">Exact provenance</a> · <a href="DIRECT_REVIEW.json">Individual review</a></p><details><summary>Exact generation prompt</summary><pre>'+html.escape(s['prompt'])+'</pre></details></html>'
 update(a/'index.html',text.encode())
for name in ['COMPLETE_SOURCE_REVIEW.json','index.html']:
 target=M/(name+'.before_a11_a12_a13.original');assert not target.exists();shutil.copyfile(M/name,target)
ms=read(M/'COMPLETE_SOURCE_REVIEW.json');assert len(ms['sources'])==10
for i in [11,12,13]:
 a=M/f'attempt{i:02d}';s=read(a/'SOURCE.json');r=read(a/'DIRECT_REVIEW.json');ms['sources'].append(dict(attempt=i,source=s,whole_source_score=r['whole_source_score'],source_review=r,state_opinions=[dict(state='Whole far-edge grip' if i==11 else 'Whole partial fold',region=[0,0,1254,1254],score=r['whole_source_score'],scope='One complete authored pose, not four quarter states; static source only.')],production_binding=False,owner_acceptance=None))
ms.update(reviewed_utc=now(),qualification='All13 complete contact natives and43 authored state regions directly reviewed. A11 near-role4.0 fails; alternate far-start4.5 provisional. A12 required free-edge role3.9/whole4.3 fails. A13 partial fold4.5 provisional, exact coverage4.2 fails. All old source/bridge/motion failures preserved. Local A1 whole2.4/A2 far-fold1.8 rejected; current in-game WRAP2.8 unchanged.');write(M/'COMPLETE_SOURCE_REVIEW.json',ms)
extra='<section><h2>New whole-pose fold sources: A11–A13</h2><p>All13 contact natives/43 state regions are now reviewed. These three single poses use the entire1254×1254 native canvas; none is sampled as four quarters. Every native and failed role is preserved. Source quality is separate from actual wrapping.</p>'
for i in [11,12,13]:
 r=read(M/f'attempt{i:02d}/DIRECT_REVIEW.json');extra+=f'<article id="attempt{i}"><h3>A{i} · complete source {r["whole_source_score"]}/5</h3><a href="attempt{i:02d}/index.html"><img src="attempt{i:02d}/native.png" width="1254" height="1254" alt="Entire original Candy fold source {i}"></a><p>{html.escape(r["qualification"])}</p><a href="attempt{i:02d}/index.html">Every individual opinion and prompt</a></article>'
extra+='</section>';t=(M/'index.html').read_text(encoding='utf-8');h=t.index('</h1>')+5;update(M/'index.html',(t[:h]+extra+t[h:]).encode())
for name,target in [('ALL_ITEMS.json','ALL_ITEMS_V45.original.json'),('all_items.html','all_items_V45.original.html'),('CURRENT_BOUNDARY_REFRESH.json','BOUNDARY_V45.original.json')]:assert not (L/target).exists();shutil.copyfile(L/name,L/target)
reg=read(L/'ALL_ITEMS.json');assert len(reg['items'])==2038
tmpl=next(x for x in reg['items'] if x['id']=='CANDY-M-SOURCE-10')
for i in [11,12,13]:
 a=M/f'attempt{i:02d}';s=read(a/'SOURCE.json');r=read(a/'DIRECT_REVIEW.json');path=s['native_path'];report=a.relative_to(B).as_posix()+'/index.html';evaluation=' '.join(x['evaluation'] for x in r['opinions'] if x['item'] in ['Whole partial-fold source','Whole required source role','Alternate far-fold source']) or r['qualification']
 z=copy.deepcopy(tmpl);z.update(id=f'CANDY-M-SOURCE-{i}',kind='source',label=f'Candy full-pose fold source {i}',path=path,earlier_sha256=s['sha256'],current_checkout_sha256=s['sha256'],historical_source_score=None,current_source_score=r['whole_source_score'],source_dimensions=s['dimensions'],preview_path=path,image_path=path,image_scope='Entire1254-square original single pose; no quarter sampling',families=['Candy Maker','Unbound contact sources'],original_reports=[report],source_qualification=r['qualification']+' Original NPOT source is not runtime-ready.',evaluation=evaluation,refinement='Inspect continuous paper/mitten contact, same sweet, neck pinch, counter-twist and released support independently. Preserve failed requested roles.',priority=True,latest_refinement=dict(report=report,note=evaluation),individual_review_utc=r['reviewed_utc']);reg['items'].append(z)
 z=copy.deepcopy(z);z.update(id=f'CANDY-M-A{i}-STATE-1',kind='source object region',region=[0,0,1254,1254],parent_source_id=f'CANDY-M-SOURCE-{i}',families=['Candy Maker','Unbound contact state regions'],individual_scope='One full authored pose. This state is the entire source, not a quarter and not complete-action evidence.');reg['items'].append(z)
assert len(reg['items'])==len({x['id'] for x in reg['items']})==2044
assert sum(x['current_source_score'] is not None and x['current_source_score']<=4.5 and x.get('capture_family') not in ['geode_current_v1','nursery_wash_v3'] for x in reg['items'])==894
reg['counts'].update(unique_source_files=1280,registered_items=2044,individual_source_object_regions=285,inclusive_current_source_priorities=894,unique_source_file_priorities=605,new_candy_generated_sources=16,new_candy_state_regions=55,exact_earlier_bytes=reg['counts']['exact_earlier_bytes']+6)
reg.update(display_revision='V46',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v46.py',scope='V46 known register2044 items/1280 sources/328 pose cells/151 runtime-use/action entries/285 source object regions.894 inclusive source-cell-region priorities/605 unique source priorities/359 pending source reviews. Six new entries represent three single whole contact poses A11-A13; no review video frames inflate source counts. All82 new local reference canvases and20 component opinions reviewed: whole A1 wrapping2.4/far-fold A2 component1.8 rejected. Candy production48 priorities/783 boundary unchanged; older Geologist/Nursery mounted claims withheld. No full all-job, owner, integration or release acceptance.')
reg['review_resources'].append(dict(path=P.relative_to(B).as_posix()+'/index.html',scope='All82 unchanged native A1/A2 reference canvases/14 ordered boards/six details/20 component opinions; wrapping2.4/far-fold1.8 rejected. All13 contact natives and43 authored states now reviewed. No runtime change.'));write(L/'ALL_ITEMS.json',reg,True);assert (L/'ALL_ITEMS.json').stat().st_size<4194304
shutil.copyfile(L/'review_tools/refresh_current_job_review_v45.py',L/'review_tools/refresh_current_job_review_v46.py')
notice='<p><a href="../../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html">New: every82 Candy local reference canvas and20 component opinions</a> · A1 whole2.4/A2 far-fold1.8 rejected. All13 contact originals/43 state regions scored. V46 contains2044 entries/894 inclusive source priorities/605 unique source priorities/359 pending source reviews. Current Candy WRAP2.8 remains unchanged.</p>'
for name in ['index.html','all_items.html']:
 t=(L/name).read_text(encoding='utf-8').replace('refresh_current_job_review_v45.py','refresh_current_job_review_v46.py');t=t.replace('<h1>',notice+'<h1>',1);update(L/name,t.encode())
builder=(P/'review_tools/build_candy_local_review_v550.py').read_text(encoding='utf-8');target='script=\'const TAKES=';assert target in builder
addition='''for extra_attempt in [12,13]:
    extra_native=M/f'attempt{extra_attempt:02d}/native.png'
    extra_review=read(M/f'attempt{extra_attempt:02d}/DIRECT_REVIEW.json')
    sources+='<div class="source"><h2>Whole pose A'+str(extra_attempt)+' · '+str(extra_review['whole_source_score'])+'/5</h2><img src="'+esc(rel(extra_native))+'" width="1254" height="1254" alt="Complete original partial-fold source '+str(extra_attempt)+'"><p>'+esc(extra_review['qualification'])+'</p><a href="'+esc(rel(extra_native.with_name('index.html')))+'">Every source opinion and prompt</a></div>'
'''
builder=builder.replace(target,addition+target,1).replace('A2 tests one far-edge fold and cannot establish complete neck grip, opposing twist, release or runtime acceptance.','A2 far-edge fold1.8 is rejected: all41 frames leave the sweet exposed. A12 grip4.3 is rejected; A13 partial fold4.5 is source-only. Complete neck grip, opposing twist, release and runtime acceptance remain open.')
update(P/'review_tools/build_candy_local_review_v554.py',builder.encode());runner=B/'tmp/build_candy_local_review_v554.py';shutil.copyfile(P/'review_tools/build_candy_local_review_v554.py',runner)
summary='Candy local wrapping continuation (2026-10-03): [every82 native Comfy reference canvas,14 original-size boards,six native details and20 component opinions](PLACEHOLDER) directly reviewed. A1 full wrapping2.4 and A2 far-edge fold1.8 are rejected; the paper never covers the sweet. Three additional complete ImageGen poses are preserved: A11 alternate far-start4.5 (requested near role4.0 failed), A12 grip4.3 rejected, A13 partial fold4.5 provisional (exact coverage4.2 failed). All13 contact natives/43 authored states reviewed; no production binding. V46 register2044 entries/894 source-cell-region priorities/605 unique source priorities/359 pending source reviews; Candy current48 priorities/783 unchanged production members. Older Geologist/Nursery mounted claims remain withheld. Full wrapping, remaining job coverage, device/child/owner and complete report acceptance remain open; finding lifecycles, integration and release unchanged.'
master=B/'audit/MASTER_AUDIT_2026-08-09.md';text=master.read_text(encoding='utf-8');marker='Shared Kitchen/Opera entrance continuation (2026-10-03):';assert text.count(marker)>=1;text=text.replace(marker,summary.replace('PLACEHOLDER','../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html')+'\n\n'+marker,1)
index_marker='## Development task index';assert index_marker in text;pos=text.index(index_marker);after=text.index('\n',pos)+1;text=text[:after]+'\n'+summary.replace('PLACEHOLDER','../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html')+'\n'+text[after:];update(master,text.encode())
f=B/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';text=f.read_text(encoding='utf-8');pos=text.index('\n')+1;update(f,(text[:pos]+'\n'+summary.replace('PLACEHOLDER','../../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html')+'\n'+text[pos:]).encode())
f=B/'audit/animation/README.md';text=f.read_text(encoding='utf-8');marker='## Start an animation task here';assert marker in text;update(f,text.replace(marker,summary.replace('PLACEHOLDER','../../assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html')+'\n\n'+marker,1).encode())
f=B/'design/05_DOC_LEDGER.md';text=f.read_text(encoding='utf-8');text=text.replace('all10 preserved original sources/40 individual authored states reviewed. A7 static4.5; A8/A9/A10 bridges4.1/4.1/4.2 rejected; no production binding.','all13 preserved original sources/43 individual authored states reviewed. A11 alternate far-start4.5/requested near4.0; A12 grip4.3 rejected; A13 partial fold4.5/exact coverage4.2. Earlier bridges remain rejected; no production binding.')
text+='\n| `assets_src/local_motion/candy_wrap_continuity_v1_20261003/index.html` | 🟢 | `SUPPORTING_CURRENT`; all82 local reference native canvases/14 boards/six details/20 component opinions. A1 complete wrap2.4 and A2 far-fold1.8 rejected.13 contact originals/43 source states reviewed; source/action lanes separate, no runtime or owner acceptance. |\n| `audit/job_artwork_refinement_live/ALL_ITEMS_V45.original.json` | ⚪ | `HISTORICAL_SUPPORTING`; exact2038-entry register before three additional single whole contact sources and three complete pose regions. |\n';update(f,text.encode())
licenses=(B/'ASSET_LICENSES.md').read_bytes()
for i in [12,13]:
 path=(M/f'attempt{i:02d}/native.png').relative_to(B).as_posix();assert ('| `'+path+'` |').encode() not in licenses;licenses+=('\n| `'+path+'` | Builtin ImageGen precise-object edit; exact full RGBA original | Original project artwork generated with OpenAI; inherited source attribution retained | SOURCE.json binds exact native/reference/prompt hashes | Preserved unbound source, no post-generation bitmap edits; static drafting review only, no cinematic/runtime/owner acceptance. |\n').encode()
update(B/'ASSET_LICENSES.md',licenses)
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
d=read(IP);affected=[master,B/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md',B/'audit/animation/README.md',B/'design/05_DOC_LEDGER.md',B/'ASSET_LICENSES.md']+[L/x for x in ['ALL_ITEMS.json','ALL_ITEMS_V45.original.json','all_items.html','all_items_V45.original.html','BOUNDARY_V45.original.json','CURRENT_BOUNDARY_REFRESH.json','index.html','review_tools/refresh_current_job_review_v46.py']]+[M/x for x in ['COMPLETE_SOURCE_REVIEW.json','COMPLETE_SOURCE_REVIEW.json.before_a11_a12_a13.original','index.html','index.html.before_a11_a12_a13.original']]
d['files']=sorted(set(d['files'])|{p.relative_to(B).as_posix() for p in affected}|{p.relative_to(B).as_posix() for p in P.rglob('*') if p.is_file()}|{p.relative_to(B).as_posix() for i in [11,12,13] for p in (M/f'attempt{i:02d}').rglob('*') if p.is_file()});write(IP,d)
r=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v46.py')],cwd=B,capture_output=True,check=True,creationflags=subprocess.CREATE_NO_WINDOW);print(r.stdout.decode().strip());stamp=read(L/'CURRENT_BOUNDARY_REFRESH.json');assert stamp['registered_source_matches']==2044 and stamp['candy_capture_boundary_match']
bound=read(P/'PRODUCTION_BOUNDARY.json');bad=[x for x in bound['members'] if sha(B/x['path'])!=x['sha256']];assert len(bound['members'])==783 and not bad;write(P/'PRODUCTION_BOUNDARY_END.json',dict(status='ALL783_LITERAL_CURRENT_MEMBERS_UNCHANGED_AFTER_REVIEW',checked_utc=now(),baseline=bound['baseline'],boundary_path='assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json',boundary_sha256=sha(P/'PRODUCTION_BOUNDARY.json'),members_checked=783,changed_members=bad,qualification='No runtime change; preceding full local82/82 CI remains bound to identical783 production members. This does not transfer visual/action/owner acceptance.'))
d=read(IP);d['files']=sorted(set(d['files'])|{(P/'PRODUCTION_BOUNDARY_END.json').relative_to(B).as_posix()});d['validation'].append(dict(command='V46 exact known-source refresh and end783-member production boundary',result='PASS',evidence='2044/2044 registered item hashes match; Candy boundary matches; PRODUCTION_BOUNDARY_END.json. Older mounted claims remain withheld.'));d['acceptance_gaps']='A1 whole2.4 and A2 fold1.8 rejected. A11 requested near4.0/A12 grip4.3/exact A13 coverage4.2 remain named role priorities; A13 partial-fold source4.5 is provisional only. Whole wrapping and ordinary game input/exit, full all-job audit, target-device, child, owner and comprehensive report approval remain open. No production binding/integration/release/finding closure.';write(IP,d)
print(json.dumps(dict(registry=2044,source_priorities=894,unique_source_priorities=605,native_sources=13,state_regions=43,production_unchanged=783,registry_bytes=(L/'ALL_ITEMS.json').stat().st_size)))
