from pathlib import Path
import json,re,shutil,urllib.request,datetime,hashlib
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');impact=b/'design/audit_impacts/job-pan-painted-placement-20261001.json';parent=b/'audit/job_pan_painted_mount_v3_20261001'
def rel(p):return p.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();text='Pan material/layout continuation (2026-10-01): [every60 new native pan view](job_pan_painted_mount_v3_20261001/index.html) directly inspected, preserving hidden/displaced-support failures. Reused pan/slab/mineral material and newly generated grain reach source/isolated4.6; selected static invitation/mineral-water contact4.5 provisional. Actor-work contact2.7, native room coverage, naturally timed complete career/training/story routes, target device/child/owner and final comprehensive report remain open. Current known register1557 entries/1186 sources/579 inclusive priorities/388 unassigned; all280 teacher/geology/pan native comparisons directly reviewed. [Current15 ImageGen originals/28 neutral fields/10 whole-canvas derivatives](../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html) retain every earlier source opinion. [Published geology revisiondea7425a anonymous540-file verification](job_review_v2_20261001/geology_remote_verified_v3/RESULT.json) proves bytes only; hosted exact-head run36956816389 is pending in the recorded snapshot. [Impact](../design/audit_impacts/job-pan-painted-placement-20261001.json). No production replacement or lifecycle closure.\n\n';assert 'Pan material/layout continuation' not in s;s=s.replace('## 0. Planning entry\n\n','## 0. Planning entry\n\n'+text,1);master.write_text(s,encoding='utf-8')
findings=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text()
for ident in ['MA-VIS-006','MA-PLAY-004']:
 start=s.index('\n## '+ident+'\n');end=s.find('\n## ',start+1);end=len(s) if end<0 else end;section=s[start:end]
 addition=' 2026-10-01 pan continuation: all60 additional native views and280 total teacher/geology/pan comparisons directly evaluated; current15 native painted sources remain unbound. Source/isolated pan/slab/grain/mineral4.6 and selected static contact4.5 are separate from actor-work2.7, full ordinary training/story/device/child/owner and final-report acceptance. Failed support layers/placement remain preserved at `audit/job_pan_painted_mount_v3_20261001/index.html`; lifecycle unchanged.'
 lines=section.splitlines();hit=next(i for i,l in enumerate(lines) if l.startswith('| history |'));lines[hit]=lines[hit].rstrip().removesuffix('|').rstrip()+addition+' |';section='\n'.join(lines)+'\n';s=s[:start]+section+s[end:]
findings.write_text(s,encoding='utf-8')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();lines=s.splitlines()
for i,l in enumerate(lines):
 if l.startswith('| `assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html`'):
  lines[i]=l.replace('14 native','15 native').replace('26 neutral','28 neutral').replace('9 whole-canvas','10 whole-canvas').replace('All220','All280')+' '
rows=['| `audit/job_pan_painted_mount_v3_20261001/index.html` | 🟣 | `CANDIDATE`; every60 new native pan view directly inspected with individual scores/hashes at1280/1600. Previous hidden/displaced support failures preserved. Current intact pan/slab/grain/mineral material4.6, selected static contact4.5 provisional; actor contact2.7, native room coverage and complete ordinary routes/device/child/owner/final report remain open. |','| `audit/job_review_v2_20261001/geology_remote_verified_v3/RESULT.json` | 🔵 | `GENERATED_REPORT`; anonymous normal-TLS GET verification of exactdea7425a geology supplement539 payload files plus its immutable manifest, every byte/hash matched. Publication/provenance evidence only; current hosted exact-head validation and visual/owner acceptance separate. |']
for row in rows:
 if row.split('`')[1] not in s:lines.append(row)
ledger.write_text('\n'.join(lines)+'\n',encoding='utf-8')
for f in ['audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html']:
 p=b/f;s=p.read_text();base='../job_pan_painted_mount_v3_20261001/'
 banner='<section id="pan-material-layout-v3"><h2>Current pan material/layout continuation</h2><p>Known1557 entries/1186 sources,579 inclusive source priorities and388 unassigned source opinions.15 preserved ImageGen geology originals/28 neutral fields/10 technical derivatives. Every280 teacher/geology/pan native comparison directly inspected, including all60 new pan views. Current pan/slab/grain/mineral source/isolated material4.6; static invitation/water contact4.5 provisional. Roshan contact2.7, full ordinary career/training/story routes, native room coverage, target device/child/owner and comprehensive final approval remain open.</p><p><a href="'+base+'index.html">All60 illustrated pan iterations, including failed attempts</a> · <a href="'+base+'attempt_04/index.html">Current6 changed native views</a> · <a href="../job_geode_embedded_mount_v2_20261001/index.html">Owner-corrected embedded geode opening</a></p></section>'
 assert 'pan-material-layout-v3' not in s;i=s.index('<h1');end=s.index('</h1>',i)+5;s=s[:end]+banner+s[end:];p.write_text(s,encoding='utf-8')
shutil.copyfile(__file__,parent/'executed_update_pan_review_contract_v123.py')
named=['ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/ALL_ITEMS.html','audit/job_artwork_refinement_live/STATUS.json','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v16.py','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v16.py']
prefixes=[parent,b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001',b/'audit/job_review_v2_20261001/geology_remote_verified_v3']
d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|set(named)|{rel(p) for folder in prefixes for p in folder.rglob('*') if p.is_file()});write(impact,d)
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(d['files']);allowed.add(rel(impact));write(allow,sorted(allowed))
http=[]
for path in ['audit/job_pan_painted_mount_v3_20261001/index.html','audit/job_pan_painted_mount_v3_20261001/attempt_04/index.html','assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html','assets_src/imagegen/geologist_painted_rebuild_v1_20261001/pan_grain/attempt_01/native.png','audit/job_artwork_refinement_live/ALL_ITEMS.html']:
 with urllib.request.urlopen('http://127.0.0.1:8880/'+path,timeout=10) as response:raw=response.read();status=response.status
 assert status==200 and hashlib.sha256(raw).hexdigest()==hashlib.sha256((b/path).read_bytes()).hexdigest();http.append(dict(path=path,status=status,sha256=hashlib.sha256(raw).hexdigest(),bytes=len(raw)))
write(parent/'LOCAL_PREVIEW_HTTP.json',dict(status='PASS_FIVE_EXACT_LOOPBACK_PREVIEWS',checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),files=http));d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|{rel(parent/'LOCAL_PREVIEW_HTTP.json')});write(impact,d);print('Contract/history/ledger/current entries and exact preview checks updated')
