from pathlib import Path
import json,hashlib,html,datetime,shutil
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');out=b/'audit/job_pan_painted_mount_v3_20261001'
def rel(p):return p.relative_to(b).as_posix()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();capture=json.loads((out/'native_views/CAPTURE_RECEIPT.json').read_text());rows=[]
for view in capture['views']:
 v=dict(view);v['archive_path']=rel(out/'native_views'/v['path']);assert hashlib.sha256((b/v['archive_path']).read_bytes()).hexdigest()==v['sha256'];v['direct_native_review']=True;v['reviewed_utc']=now
 painted=v['variant']=='painted_staging';literal=v['variant']=='literal_raster';inv=v['state']=='invitation';partial=v['state']=='partial_panning_reversals'
 scores=dict(object_finish=4.6 if painted else 4.6 if literal and not inv else 3.9 if literal else 3.5 if not inv else 3.9,object_semantics=4.6 if painted else 3.0 if inv else 4.5,object_geometry=4.6 if painted else 4.4 if literal and not inv else None,scene_style=4.4 if painted else 2.8,layout=4.4 if painted else 3.0,invitation_support=4.0 if inv and painted else None,slab_geometry=4.6 if painted and not inv else None,grain_finish=3.8 if not inv else None,grain_containment=4.6 if painted and not inv else 4.1 if literal and not inv else None,mineral_finish=4.6 if partial and painted else 3.8 if partial else None,mineral_containment=4.6 if partial and painted else 3.4 if partial and literal else None,mineral_water_contact=4.2 if partial and painted else None,actor_work_contact=2.7 if not inv else None,complete_action=None)
 if inv:
  evaluation='The painted pan preserves its2.06 oval ratio and honestly invites panning; warm plum matte rim and water remain clear at native invitation size4.6. It still hovers in front of a side ledge instead of resting on a support4.0. Room finish is coherent4.4 but its source remains under native resolution.' if painted else 'The cue remains a layered rock rather than a panning dish, semantic3.0. Literal painted replacement changes the material but retains the wrong object. Flat stripe room, rectangular trays and procedural reward crystals remain weak2.8.'
 else:
  evaluation='The pan and slab retain their authored ratios4.6 and form a much calmer horizontal work plane. The reduced interior scatter keeps every visible grain inside the water4.6, but the dots still have flat circle finish3.8.' if painted else 'Procedural work staging remains flat and separate from Roshan. The literal pan source is stretched to the inherited520x320 rectangle4.4; grains still sit against the front rim4.1. Whole scene remains2.8 and actor hands do not contact the pan2.7.'
  if painted and partial:evaluation+=' Reused painted cluster finish4.6 replaces the flat pentagon; its complete base is inside the basin4.6 but absent local water contact makes it appear to float4.2. This still requires correction.'
  if painted:evaluation+=' Roshan remains remote from the work2.7, so these isolated object improvements do not pass the whole action.'
 v.update(scores=scores,evaluation=evaluation,priority_dimensions=[k for k,x in scores.items() if x is not None and x<=4.5],qualification='Unmodified individual native Godot4.7.2 Mobile desktop view, directly inspected. Phase-selected fixture followed by actual viewport approach and three inherited reversals. Not a completed job, ordinary training/story route, device, child or owner approval.',owner_acceptance=None,production_binding_changed=False);rows.append(v)
assert len(rows)==18
review=dict(schema='reef.individual-native-graphics-review.v1',status='18_OF18_DIRECTLY_REVIEWED_PLACEMENT_IMPROVED_DETAILS_OPEN',native_views=18,directly_reviewed=18,reviewed_utc=now,views=rows,qualification='Source4.6/art ratio4.6 and containment4.6 do not imply complete-action acceptance. Flat grain3.8, mineral contact4.2, invitation support4.0 and actor contact2.7 remain priorities.')
write(out/'REVIEW.json',review);shutil.copyfile(__file__,out/'executed_record_pan_geometry_v113.py')
cards=[]
for v in rows:
 scores='; '.join(k.replace('_',' ')+' '+str(x)+'/5' for k,x in v['scores'].items() if x is not None)
 cards.append('<article id="'+v['id']+'"><h2>'+html.escape(v['id'])+'</h2><img loading="lazy" src="native_views/'+v['path']+'" alt="'+v['id']+'"><p>'+html.escape(scores)+'</p><p>'+html.escape(v['evaluation'])+'</p><small>'+html.escape(v['qualification'])+'</small></article>')
(out/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>Pan painted placement revision3</title><style>body{background:#eef5f4;color:#302949;font:17px/1.5 system-ui;max-width:1500px;margin:auto;padding:24px}article{background:white;padding:20px;margin:28px 0}img{width:100%;height:auto}small{display:block}a{color:#4850a7}</style><h1>Pan placement revision3 — all18 native views</h1><p>18/18 individually inspected. Pan/slab ratios and basin containment4.6; flat grain3.8, floating mineral contact4.2, invitation support4.0 and actor contact2.7 still need work. Original/literal/painted lanes at1280 and1600 widths share inherited input/progress. No complete-action or owner acceptance.</p><p><a href="../job_pan_painted_mount_v2_20261001/index.html">Earlier18 views</a> · <a href="REVIEW.json">Individual scores/hashes</a> · <a href="PROCESS_RECEIPT.json">Machine evidence</a></p>'+''.join(cards),encoding='utf-8')
license=b/'ASSET_LICENSES.md';existing=license.read_text(encoding='utf-8')
with license.open('a',encoding='utf-8',newline='\n') as f:
 for v in rows:
  if v['archive_path'] not in existing:f.write('\n| `'+v['archive_path']+'` | Project-owned Godot4.7.2 Mobile fixture capture; underlying asset provenance retained | Internal review evidence | Local inherited-input PAN study; exact complete viewport bytes preserved, no pixel edits or runtime binding; SHA256 '+v['sha256']+' |\n')
impact=b/'design/audit_impacts/job-pan-painted-placement-20261001.json';d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in out.rglob('*') if p.is_file()}|{'ASSET_LICENSES.md'});d['validation'].append(dict(command='Direct individual native review18/18 at two widths',result='PASS',evidence=rel(out/'REVIEW.json')+'; scoped visual review completed, overall action remains below floor and unaccepted'));write(impact,d)
print('Recorded all18 native reviews; original opinions retained;238 total native comparisons now directly inspected')
