from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
staging=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/day2_graphics_audit_20260930/tmp')
base='6edb4ca8c57bfbfe3123636863a29c95165ac23f'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=r,text=True).strip()==base
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def rel(p):return p.relative_to(r).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
remote=r/'audit/job_review_v2_20261001/current_native_supplement_remote_v2';assert not remote.exists();remote.mkdir();(remote/'.gdignore').write_text('')
receipt=read(r/'tmp/native_supplement_remote_v84/RESULT.json');assert receipt['status']=='PASS_ALL_IMMUTABLE_NATIVE_SUPPLEMENT_BYTES' and receipt['verified_files']==444 and receipt['revision']==base
for p in (r/'tmp/native_supplement_remote_v84').iterdir():
 if p.is_file():shutil.copyfile(p,remote/p.name)
for p in (r/'tmp').glob('native_supplement_v83_*.log'):shutil.copyfile(p,remote/p.name)
for name in ['native_supplement_commit_v83.RECEIPT.json','native_supplement_commit_v83.stdout.log','native_supplement_commit_v83.stderr.log']:shutil.copyfile(r/'tmp'/name,remote/name)
shutil.copyfile(staging/'commit_and_publish_native_supplement_v83.py',remote/'executed_commit_and_publish_native_supplement_v83.py')
(remote/'index.html').write_text('<!doctype html><html><meta charset="utf-8"><title>Exact native supplement byte receipt</title><body><h1>444 immutable payloads verified</h1><p>Revision6edb4ca8,43,281,662 bytes, map74,166 bytes. Anonymous normal-TLS complete GET:2026-10-02T01:22:09Z through01:22:22Z. No failures. Earlier maps retain their original immutable revisions. This receipt archive is a later local supplement, not part of the verified payload.</p><p><a href="RESULT.json">Complete remote receipt</a> · <a href="FETCH_JOURNAL.jsonl">Every path/hash/time</a> · <a href="https://github.com/Ebonyks/mermaid-roshan-reef/actions/runs/36950549322">Exact-head hosted check</a></p><p>Hosted pending at archive preparation. Source/context/action/device/child/owner, integration and release claims remain separate.</p></body></html>',encoding='utf-8')
out=r/'audit/job_vector_mount_review_v1_20261001';assert not out.exists();out.mkdir();(out/'.gdignore').write_text('')
shutil.copyfile(__file__,out/'executed_prepare_vector_mount_review_v85.py')
selected=read(r/'assets_src/vector/job_geology_teacher_refinement_v1_20261001/SELECTED_SOURCES_V1.json')['items'];assert len(selected)==5
write(out/'PROFILE.json',dict(status='PREPARED_NATIVE_SOURCE_TO_CONTEXT_REVIEW',baseline=base,prepared_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),sources=[dict(source_path=x['source_path'],source_sha256=sha(r/x['source_path']),candidate_path=x['path'],candidate_sha256=sha(r/x['path']),candidate_source_score=x['source_score']) for x in selected],scope='Teacher PATTERN/COUNT/ADD/MATCH and Geologist RIVER/FOSSIL/PAN/GEODE at1280x720 and1600x720. Exact original/candidate invitation and task snapshots, plus causal fossil partial-brush/assembly and geode partial-open states through actual viewport touch input. Each phase is explicitly selected in a disposable fixture, followed by actual approach; no claim of an unbroken whole-job run. Crest actual room-card50px review is separate and pending.',runtime_binding_changed=False,save_protection='Existing reward_policy=dev_playtest suppresses job checkpoint writes; main processing frozen, original stars/saved learning/checkpoints must remain unchanged.',acceptance_gaps='All context grades pending actual native capture and direct image review. Candidate source4.5 does not pass enlarged fossil geometry, pan invitation semantics, crystal occlusion, lesson activity, actor continuity, device/child/owner or whole-job action.'))
(out/'index.html').write_text('<!doctype html><html><meta charset="utf-8"><title>Teacher/geologist vector mount study</title><body><h1>Native source-to-context study prepared</h1><p>Every current and reversible prop is reviewed at its exact invitation/task size. Original sources and bindings remain unchanged. Native captures and individual context opinions are pending.</p><p><a href="PROFILE.json">Scope, hashes and limits</a> · <a href="../../assets_src/vector/job_geology_teacher_refinement_v1_20261001/index.html">All8 source attempts</a></p></body></html>',encoding='utf-8')
template=read(r/'design/audit_impacts/job-nursery-teacher-geology-native-review-20261001.json')
write(r/'design/audit_impacts/job-vector-mounted-review-20261001.json',dict(id='job-vector-mounted-review-20261001',scope='Reversible test-only mounting of the existing5 source-floor vector candidates in actual teacher/geology world/surface owners. Inspect individual original/candidate invitations and meaningful partial action states with literal source hashes, real viewport input and unchanged reward/checkpoint guard. Current50px crest owner and complete career/story/device/child/owner acceptance stay pending. Archive exactD444-file anonymous publication receipt separately; earlier closed byte maps and scores unchanged.',baseline=base,rules=sorted(set(template['rules'])|{'DL-INT-02','DL-MOT-01','DL-MOT-03','DL-MOT-04','DL-ASSET-05'}),findings=['MA-VIS-006','MA-PLAY-004'],files=sorted(rel(p) for folder in [remote,out] for p in folder.rglob('*') if p.is_file()),validation=[dict(command='Anonymous exact-head complete payload fetch444/444 and map',result='PASS',evidence=rel(remote/'RESULT.json')),dict(command='Native fixture parse/lint/analyzer/actual-input capture and direct context review',result='PENDING',evidence=rel(out/'PROFILE.json'))],acceptance_gaps='No source floor transfers to action. Native context opinions, whole career/story sequencing, independent actor-work contact, actual50px crest, device/child/owner, strict2D and release remain separate.'))
print(json.dumps(dict(status='PREPARED_VECTOR_MOUNT_SCOPE_AND_ARCHIVED_EXACT_D_REMOTE_RECEIPT',report=rel(out),archived_remote_files=receipt['verified_files'],source_candidates=len(selected))))
