from pathlib import Path
import json,hashlib,shutil,subprocess,datetime
from PIL import Image
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');packet=b/'assets_src/local_motion/day2_geologist_pan_motion_v1_20261001';state_dir=b/'build/geologist_local_pan_study_v1_20261001';state=json.loads((state_dir/'STATE.json').read_text());assert state['status']=='MACHINE_RENDER_PASS_VISUAL_AUDIT_PENDING';out=packet/'attempt_01';out.mkdir(exist_ok=False)
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
rp=Path(state['receipt_path']);receipt=json.loads(rp.read_text());assert receipt['status']=='PASS';manifest=json.loads((packet/'MANIFEST.json').read_text());assert receipt['source_sha256']==manifest['job']['input_sha256'];graph=json.loads(rp.with_name('workflow.api.json').read_text());assert graph['1']['inputs']['unet_name']=='Wan2.2-TI2V-5B-Q4_K_S.gguf' and graph['2']['inputs']['clip_name']=='umt5-xxl-encoder-Q4_K_S.gguf'
for name in ['RENDER_RECEIPT.json','workflow.api.json','COMFY_HISTORY.json']:shutil.copyfile(rp.with_name(name),out/name)
shutil.copyfile(state_dir/'STATE.json',out/'WORKER_STATE.json');shutil.copyfile(state_dir/'CLI.stdout_stderr.log',out/'CLI.stdout_stderr.log');outputs=[]
for x in receipt['outputs']:
 p=Path(x['path']);assert p.resolve().is_relative_to(Path('H:/MermaidReefTools/LocalVideo/output').resolve());assert sha(p)==x['sha256'];target=out/('native_output'+p.suffix);shutil.copyfile(p,target);assert sha(target)==x['sha256'];outputs.append(dict(provider_path=str(p),path=rel(target),bytes=target.stat().st_size,sha256=sha(target),transformation='Byte-identical complete original output; no pixel repair, retiming or interpolation.'))
native=out/'native_output.webm';frames=out/'native_frames';frames.mkdir();ffmpeg='C:/Users/Peter/AppData/Local/Programs/MermaidReefTools/FFmpeg/8.1.2/bin/ffmpeg.exe';cmd=[ffmpeg,'-nostdin','-hide_banner','-loglevel','error','-n','-i',str(native),'-fps_mode','passthrough',str(frames/'%04d.png')]
with (out/'decode.stdout.log').open('wb') as a,(out/'decode.stderr.log').open('wb') as c:p=subprocess.run(cmd,stdout=a,stderr=c,creationflags=subprocess.CREATE_NO_WINDOW,timeout=120)
assert p.returncode==0;rows=[]
for index,p in enumerate(sorted(frames.glob('*.png'))):
 im=Image.open(p);assert im.size==(896,512);rows.append(dict(index=index,timestamp_seconds=index/24,path=p.relative_to(packet).as_posix(),sha256=sha(p),bytes=p.stat().st_size,dimensions=list(im.size),visual_score=None,visual_review='PENDING_DIRECT'))
assert len(rows)==41;write(out/'FRAME_CATALOG.json',dict(status='ALL41_NATIVE_OUTPUT_FRAMES_DECODED_VISUAL_REVIEW_PENDING',source_outputs=outputs,native_frames=rows,decode_command=cmd,checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),qualification='Lossless whole-frame decoding of preserved local reference webm, not authored ImageGen/runtime/cinematic delivery frames. Source4.6 does not carry into motion scores.'));shutil.copyfile(__file__,out/'executed_archive_geologist_motion_v140.py')
with (b/'ASSET_LICENSES.md').open('a',encoding='utf-8',newline='\n') as f:
 for p in [out/'native_output.webm',out/'native_output.mp4',*sorted(frames.glob('*.png'))]:f.write('\n| `'+rel(p)+'` | Developed local ComfyUI Wan2.2 GGUF workflow; named geologist pan study2026-10-01 | Project motion reference output; exact model/source provenance retained in bound workflows and RENDER_RECEIPT.json | Local generated reference | '+('Lossless complete-frame decode of preserved video' if p.suffix=='.png' else 'Byte-identical original local CLI output')+'; no repair/retiming/interpolation; SHA256 '+sha(p)+'; artistic/runtime/cinematic/owner acceptance pending |\n')
ip=b/'design/audit_impacts/job-geologist-panning-local-motion-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in packet.rglob('*') if p.is_file()});d['validation'].append(dict(command='Developed exact GGUF workflow completion and lossless41-frame archive',result='PASS',evidence=rel(out/'WORKER_STATE.json')+'; all41 visual scores still unassigned'));write(ip,d)
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(d['files']);write(allow,sorted(allowed));print(json.dumps(dict(status='ALL41_FRAME_AUDITS_PENDING',prompt_id=receipt['prompt_id'],render_seconds=receipt['elapsed_seconds'],native_video=rel(native))))
