from pathlib import Path
import shutil,json
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');parent=b/'audit/job_pan_painted_mount_v3_20261001';out=parent/'attempt_02'
code=(parent/'executed_record_pan_geometry_v113.py').read_text().replace("out=b/'audit/job_pan_painted_mount_v3_20261001'","out=b/'audit/job_pan_painted_mount_v3_20261001/attempt_02'").replace('grain_finish=3.8 if not inv else None','grain_finish=4.6 if painted and not inv else 3.8 if not inv else None').replace('mineral_water_contact=4.2 if partial and painted else None','mineral_water_contact=4.3 if partial and painted else None')
code=code.replace('but the dots still have flat circle finish3.8.','and the freshly painted honey-ochre grains resolve flat dot finish at native size4.6.').replace('absent local water contact makes it appear to float4.2.','the very faint water-contact ellipse still does not convincingly seat it4.3.').replace('It still hovers in front of a side ledge instead of resting on a support4.0.','The attempted support is completely hidden by its lower draw layer, so it receives no visible-object score; the invitation still hovers4.0. This is a disposable fixture defect, not a new production finding.').replace('Flat grain3.8, mineral contact4.2','Painted grain4.6, mineral contact4.3').replace('flat grain3.8, floating mineral contact4.2','painted grain4.6, faint mineral contact4.3').replace('flat grain3.8, mineral contact4.2','painted grain4.6, faint mineral contact4.3').replace('executed_record_pan_geometry_v113.py','executed_record_pan_details_v117.py').replace('238 total native comparisons','256 total native comparisons')
exec(compile(code,str(__file__),'exec'))
review=json.loads((out/'REVIEW.json').read_text())
for v in review['views']:
 if v['state']=='invitation' and v['variant']=='painted_staging':v['scores']['attempted_support_object_finish']=None;v['attempted_support_visible']=False
(out/'REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
grain=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/pan_grain/attempt_01';d=json.loads((grain/'whole_canvas_1024.json').read_text());d['review']='Complete whole-canvas derivative directly inspected; authored material/alpha preserved4.6. No runtime binding or full action acceptance.';(grain/'whole_canvas_1024.json').write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
