from pathlib import Path
import json,hashlib,shutil,subprocess,sys,time,re
from PIL import Image
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');parent=b/'audit/job_pan_painted_mount_v3_20261001';out=parent/'attempt_02';out.mkdir(exist_ok=False)
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8',newline='\n')
grain=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/pan_grain/attempt_01';im=Image.open(grain/'native.png');assert not (grain/'whole_canvas_1024.png').exists();im.resize((1024,683),Image.Resampling.LANCZOS).save(grain/'whole_canvas_1024.png')
write(grain/'whole_canvas_1024.json',dict(source=rel(grain/'native.png'),source_sha256=sha(grain/'native.png'),output=rel(grain/'whole_canvas_1024.png'),sha256=sha(grain/'whole_canvas_1024.png'),source_dimensions=list(im.size),dimensions=[1024,683],method='Uniform whole-canvas RGBA size normalization only; no alpha/pixel repair/crop/relight.',review='PENDING_DIRECT_DERIVATIVE_REVIEW'))
write(grain/'SOURCE_REVIEW.json',dict(source_score=4.6,evaluation='One irregular complete honey-ochre pebble uses broad matte cream/gold/lavender values and a warm plum silhouette. It resolves the named flat-circle material gap without a new pan/character/background. Native and both neutral fields are directly inspected. Low-alpha trace below8 is not a baked opaque halo or cropped silhouette. Tiny native game-size mounting remains pending.',qualification='Source-only unbound drafting opinion; no complete-action/device/child/owner acceptance.',native_direct_review=True,neutral_previews_direct_review=[rel(grain/'audit_white.png'),rel(grain/'audit_aqua.png')],owner_acceptance=None))
code=(parent/'capture.gd').read_text().replace('tmp/pan_geometry_v112/native_views','tmp/pan_details_v116/native_views').replace('res://'+rel(parent/'study_surface.gd'),'res://'+rel(out/'study_surface.gd'))
code=code.replace('const PAINTED_PATHS := {','const PAINTED_PATHS := {\n "pan_grain": "res://'+rel(grain/'whole_canvas_1024.png')+'",')
small=Image.open(grain/'whole_canvas_1024.png');bounds=small.getchannel('A').point(lambda p:255 if p>=16 else 0).getbbox();code=code.replace('const SOURCE_BOXES := {','const SOURCE_BOXES := {\n "pan_grain": '+json.dumps(list(bounds))+',')
code=code.replace('var study_background: TextureRect','var study_background: TextureRect\nvar invitation_support: TextureRect')
code=code.replace('study.work_texture = painted_textures["work_surface"] as Texture2D','study.work_texture = painted_textures["work_surface"] as Texture2D\n\t\t\t\tstudy.grain_texture = painted_textures["pan_grain"] as Texture2D')
code=code.replace('var use_new := lane != "original"','var use_new := lane != "original"\n\t\tif invitation_support != null:\n\t\t\tinvitation_support.visible = false')
code=code.replace('active.object_size = Vector2(fit_width, fit_width / ratio)','active.object_size = Vector2(fit_width, fit_width / ratio)\n\t\t\tif not world.task_open:\n\t\t\t\tif invitation_support == null:\n\t\t\t\t\tinvitation_support = TextureRect.new()\n\t\t\t\t\tinvitation_support.name = "DISPOSABLE_PAINTED_INVITATION_SUPPORT"\n\t\t\t\t\tinvitation_support.texture = painted_textures["work_surface"] as Texture2D\n\t\t\t\t\tinvitation_support.expand_mode = TextureRect.EXPAND_IGNORE_SIZE\n\t\t\t\t\tinvitation_support.stretch_mode = TextureRect.STRETCH_SCALE\n\t\t\t\t\tinvitation_support.mouse_filter = Control.MOUSE_FILTER_IGNORE\n\t\t\t\t\tinvitation_support.z_index = -1\n\t\t\t\t\tactive.add_child(invitation_support)\n\t\t\t\tvar support_size := Vector2(176.0, 176.0 * study.work_texture.get_height() / float(study.work_texture.get_width()))\n\t\t\t\tinvitation_support.size = support_size\n\t\t\t\tinvitation_support.position = active.object_center + Vector2(-support_size.x * 0.5, active.object_size.y * 0.42)\n\t\t\t\tinvitation_support.visible = true')
code=code.replace('study_background.visible = false\n\tworld.backdrop_node.visible = true','study_background.visible = false\n\tif invitation_support != null:\n\t\tinvitation_support.visible = false\n\tworld.backdrop_node.visible = true')
code=code.replace('world.queue_free()\n\t\t\t\tawait _wait(4)','world.queue_free()\n\t\t\t\tinvitation_support = null\n\t\t\t\tawait _wait(4)')
code=code.replace('aspect-preserving pan/slab drawing and safe water-region grain/mineral layout study.','aspect-preserving pan/slab drawing, source-reused painted grains, basin mineral contact and small invitation-support study.')
(out/'.gdignore').write_text('');(out/'capture.gd').write_text(code,encoding='utf-8',newline='\n')
surface=(parent/'study_surface.gd').read_text().replace('var work_texture: Texture2D','var work_texture: Texture2D\nvar grain_texture: Texture2D')
surface=surface.replace('draw_circle(grain_pos, 6.0, Color("#d5a761"))','var grain_size := Vector2(15.0 * grain_texture.get_width() / float(grain_texture.get_height()), 15.0)\n\t\tdraw_texture_rect(grain_texture, Rect2(grain_pos - grain_size * 0.5, grain_size), false)')
surface=surface.replace('draw_texture_rect(crystals_texture, Rect2(base - Vector2(mineral_size.x * 0.5, mineral_size.y), mineral_size), false)','_draw_ellipse(base + Vector2(0.0, -2.0), Vector2(24.0, 6.0), Color(0.22, 0.60, 0.65, 0.35), Color(0.57, 0.89, 0.88, 0.72), 2.0)\n\t\tdraw_texture_rect(crystals_texture, Rect2(base - Vector2(mineral_size.x * 0.5, mineral_size.y), mineral_size), false)')
(out/'study_surface.gd').write_text(surface,encoding='utf-8',newline='\n');shutil.copyfile(__file__,out/'executed_capture_pan_details_v116.py')
snapshot=json.loads((b/'audit/job_review_v2_20261001/full_ci_candidate_retry_v2/SOURCE_BEFORE.json').read_text())['source_files'];before={x['path']:sha(b/x['path']) for x in snapshot};assert len(before)==325 and all(before[x['path']]==x['sha256'] for x in snapshot);write(out/'SOURCE_BEFORE.json',before)
write(out/'PROFILE.json',dict(status='PREPARED_GRAIN_AND_CONTACT_REFINEMENT',views=18,grain_source=rel(grain/'native.png'),sha256=sha(grain/'native.png'),whole_canvas_output=rel(grain/'whole_canvas_1024.png'),alpha16_atlas_region=list(bounds),changes='Painted grain sprites, source-reused small slab invitation support and sparse2D mineral water-contact ellipse. No source repair/relight, production input change or actual route pass.'))
impact=b/'design/audit_impacts/job-pan-painted-placement-20261001.json'
def cover():
 d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|{rel(p) for folder in [out,grain] for p in folder.rglob('*') if p.is_file()});write(impact,d)
cover();native=b/'tmp/pan_details_v116/native_views';native.mkdir(parents=True)
godot='C:/Users/Peter/AppData/Local/Programs/MermaidReefTools/Godot/4.7.2/godot_console.exe';cmds=[('parser',[sys.executable,'-X','utf8','-B','-m','gdtoolkit.parser',rel(out/'capture.gd'),rel(out/'study_surface.gd')]),('inference',[sys.executable,'-X','utf8','-B','tools/lint_inference.py',rel(out/'capture.gd'),rel(out/'study_surface.gd')]),('analyzer',[godot,'--headless','--path',str(b),'--check-only','--script','res://'+rel(out/'capture.gd')]),('native',[godot,'--path',str(b),'--script','res://'+rel(out/'capture.gd')])];rows=[]
for name,cmd in cmds:
 so=out/(name+'.stdout.log');se=out/(name+'.stderr.log');so.touch();se.touch();cover();start=time.monotonic()
 with so.open('wb') as a,se.open('wb') as c:
  try:p=subprocess.run(cmd,cwd=b,stdout=a,stderr=c,timeout=240 if name!='native' else 600,creationflags=subprocess.CREATE_NO_WINDOW);code=p.returncode;timed=False
  except subprocess.TimeoutExpired:code=None;timed=True
 rows.append(dict(name=name,command=cmd,process_exit=code,timed_out=timed,seconds=time.monotonic()-start,stdout=rel(so),stderr=rel(se)));print(name,code,flush=True)
 if code!=0:print(se.read_text(encoding='utf-8',errors='replace')[-1400:],flush=True);break
passed=len(rows)==4 and all(x['process_exit']==0 for x in rows) and all(sha(b/p)==h for p,h in before.items())
if passed:shutil.copytree(native,out/'native_views')
write(out/'PROCESS_RECEIPT.json',dict(status='PASS_MACHINE_NATIVE_CAPTURE' if passed else 'FAIL_PRESERVED',processes=rows,original325_sources_unchanged=all(sha(b/p)==h for p,h in before.items()),qualification='Machine capture only. Direct source derivative/native review pending. No complete action, route or owner acceptance.'));cover();d=json.loads(impact.read_text());d['validation'].append(dict(command='Painted grain/invitation support/water-contact official4.7.2 analyzer and18-view native input capture',result='PASS' if passed else 'FAIL',evidence=rel(out/'PROCESS_RECEIPT.json')));write(impact,d);raise SystemExit(0 if passed else 1)
