from pathlib import Path
import datetime,hashlib,html,json,shutil,subprocess
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
P=R/'audit/day_one_unassigned_sources_v3_20261002';L=R/'audit/job_artwork_refinement_live'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,obj):p.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
plan=read(P/'PLAN.json');assert len(plan['inventory'])==8
opinions=[
 (3.1,'Carrot','The128px source is a hard orange horizontal wedge with narrow brown transverse marks. Its carrot point reads, but the blocky broad end has no green crown, the contour has small jagged protrusions, and almost flat fill lacks the broad painted form of the newer props. Native detail is already sparse; it cannot support an enlarged high-resolution objective. Actual icon/prop scale and use remain unverified.','Inventory existing painted carrot/vegetable sources first. Reuse a complete leafy carrot with clean purple or warm-brown contour and two calm painted value bands; otherwise generate only that named small-prop gap. Do not scale this128px wedge up as a quality repair.'),
 (3.8,'Pine tree','Four exact triangular tiers and a square-ended trunk form a legible conifer silhouette. Aqua/green highlights and deep-indigo outline broadly fit the palette, but hard ruler-like diagonals, identical tier construction and the almost rectangular trunk read as a geometric diagram beside the painted job art. The quiet shadow treatment is preferable to photographic detail.','Check existing authored tree cutouts before generation. A reuse candidate needs slightly irregular rounded bough masses, a softer trunk connection and broad painted shading. Keep this diagram when its actual context deliberately requires a simple symbol; no mounted-context approval is inferred.'),
 (4.4,'Rainbow swatch','The arched rainbow fin/swatch has rounded scallops, broad warm-to-cool bands and contained cream glints. It reads clearly and is close to the toy-storybook palette. Thin blue/green pixel specks and fringe occur along the upper cutout edge, and the symmetric fan is a decorative motif rather than evidence of an attached mermaid tail.','Prefer exact reuse at an appropriate motif scale after checking alpha-edge presentation on the actual pale/cool backgrounds. Preserve this master; any authorized technical cleanup must be a derivative. Do not use this isolated swatch to replace approved Roshan tail anatomy.'),
 (3.2,'Snowman contact fragment','The painted snow texture, coal shapes, carrot and pink-coated Roshan have lively storybook surface work. As a256x512 complete source, however, Roshan is cut off at the left, the snowman head extends past the top/right and the right body contour meets the canvas edge. Floating snow accents and partial limbs prevent a self-contained objective or contact asset. This may be an intentionally cropped source fragment; actual staging is unknown.','Locate the complete same-scene source and current sampling rectangle. Reuse a complete source/crop only if it retains the intended actor/contact and contour; record a missing-source gap rather than replacing canon. This cutout cannot independently prove placing a carrot into a snowman.'),
 (3.8,'Sprout','Two broad leaves and a mound are easy to recognize against alpha, with aqua/lavender/brown muted shading. The stem is a tall straight rectangle with a square cap, the leaves have conspicuous polygon corners, and the horizontal mound has sharp notches at both ends. The result looks assembled from simple geometric shapes rather than a small painted living plant.','Inventory the existing gardener/arborist plant family. Prefer an intact young plant with rounded asymmetric leaves, a gently bending stem and one grounded soil mound; avoid regenerating approved foliage merely for variety. Actual planting and tool-contact sequence remains unreviewed.'),
 (4.5,'Painted star','The complete1024x512 star has softly rounded points, warm yellow painted bands, pale highlights and a lavender lower edge. Its intentionally wide silhouette is clean and recognizable. A fine blue/green fringe appears at portions of the alpha boundary; the interior brush marks remain grouped rather than noisy. It meets the provisional source floor, with actual screen-size/edge behavior still required.','Reuse this exact star if its mounted reward/decoration scale and alpha edge pass. Keep it in the inclusive <=4.5 priority list for final context refinement; its source floor does not pass reward timing or owner acceptance.'),
 (4.3,'Painted sun','Warm yellow/orange broad paint and lavender/plum contours match the palette. The tall oval and needle-like long top/bottom rays make this512x1024 source much narrower and sharper than a friendly rounded sun motif; shorter side rays are softer. It is readable as an emblem, but its exact shape and slender ray tips need actual phone-size review.','Inventory existing sun/emblem artwork and verify whether this elongated aspect is intentional in its real slot. Reuse a rounded painted sun where available; otherwise request a small motif-specific shape refinement. Do not stretch the approved source non-uniformly to fake a round sun.'),
 (4.6,'Painted crystal-facet texture','The complete1024-square texture has large lavender, aqua, pink and periwinkle facets separated by broad plum bands. Directional brushwork gives each face a painted material, with grouped value changes and no photographic surface noise. It is a coherent decorative material source rather than a freestanding crystal specimen. Repeating seams and room-scale use were not inspected.','Retain this exact painted source for a suitable decorative role. Test joins and contrast before any tiled use. Its1K native canvas is not a2048x2048 playable-screen background master and does not repair rooted crystal geometry or the current flat Geologist room by itself.')
]
rows=[]
for binding,opinion in zip(plan['inventory'],opinions):
 score,name,evaluation,refinement=opinion;assert sha(R/binding['path'])==binding['sha256']
 rows.append(dict(**binding,name=name,reviewed_utc=now,reviewer='Root direct full-native original visual inspection',native_review=True,source_score=score,inclusive_priority=score<=4.5,evaluation=evaluation,refinement=refinement,source_opinion_scope='Whole original source only; discovery candidate use is unverified',current_mounted_score=None,current_complete_action_score=None,owner_acceptance=None,source_modified=False))
write(P/'DIRECT_REVIEW.json',dict(status='ALL8_FULL_NATIVE_SOURCE_ORIGINALS_REVIEWED',reviewed_utc=now,baseline=plan['baseline'],individual_sources=rows,source_count=8,inclusive_priorities=7,below_floor=6,source_floor_met=2,qualification='Eight previously unassigned source opinions; no montage substitutes for direct originals. Dependencies are conservative discovery candidates, not confirmed job bindings. Native source opinions do not transfer to mounted/action/device/child/owner acceptance. Originals unchanged.'))
cards=[]
for row in rows:
 esc=html.escape;path='../../'+row['path'];cards.append('<article id="'+row['id']+'"><h2>'+row['id']+' · '+esc(row['name'])+' · '+str(row['source_score'])+'/5 source</h2><figure><a href="'+esc(path)+'"><img src="'+esc(path)+'" width="'+str(row['dimensions'][0])+'" height="'+str(row['dimensions'][1])+'" alt="Complete native '+esc(row['name'])+' source"></a></figure><p>'+esc(row['evaluation'])+'</p><p><strong>Refinement:</strong> '+esc(row['refinement'])+'</p><p class="meta">Native '+str(row['dimensions'])+' · SHA-256 '+row['sha256']+' · original unchanged. '+('Inclusive priority <=4.5.' if row['inclusive_priority'] else 'Above source floor.')+' Mounted/action/owner acceptance: unreviewed.</p></article>')
(P/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eight previously unreviewed Day One sources</title><style>body{font:18px/1.5 system-ui;background:#edf4fa;color:#25304a;max-width:1160px;margin:32px auto;padding:0 20px}header,article{padding:20px;background:white;border-radius:16px;margin-bottom:24px}figure{margin:0;background:repeating-conic-gradient(#dce5ed 0% 25%,#f8fbff 0% 50%) 50%/24px 24px}img{display:block;max-width:100%;height:auto;margin:auto}a{color:#504096}.meta{font-size:13px;overflow-wrap:anywhere}</style><header><h1>Eight previously unreviewed Day One candidate sources</h1><p>All eight complete native originals directly inspected individually. Seven inclusive priorities; six below4.5 and two at or above the source floor. The painted star remains4.5 inclusive-priority; crystal texture4.6 is suitable source reuse. Native styles, crop limits and refinement are written individually below.</p><p>These are conservative discovery candidates. Actual job use, mounted screen scale, tool/contact/action sequencing, target-device, child and owner acceptance remain open. No source modified or regenerated in this review. Current783 production source bytes unchanged.</p><p><a href="DIRECT_REVIEW.json">All individual written opinions/hashes</a> · <a href="PLAN.json">Declared scope/required evidence</a> · <a href="../job_artwork_refinement_live/all_items.html">Current known artwork library</a></p></header>'+''.join(cards)+'</html>',encoding='utf-8',newline='\n')
history=L/'history_v37_before_eight_source_reviews';assert not history.exists();history.mkdir()
for name in ('ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json'):shutil.copyfile(L/name,history/(name+'.original'))
d=read(L/'ALL_ITEMS.json');byid={x['id']:x for x in rows}
for item in d['items']:
 if item['id'] not in byid:continue
 row=byid[item['id']];assert item.get('current_source_score') is None and item['current_checkout_sha256']==row['sha256']
 item.update(current_source_score=row['source_score'],evaluation=row['evaluation'],refinement=row['refinement'],priority=row['inclusive_priority'],latest_source_sha256=row['sha256'],source_reviewed_utc=now,source_qualification=row['source_opinion_scope']+'; actual mounted/action/device/child/owner evidence remains open.',latest_source_review=P.relative_to(R).as_posix()+'/DIRECT_REVIEW.json')
 item['original_reports']=list(dict.fromkeys(item.get('original_reports',[])+[P.relative_to(R).as_posix()+'/index.html']))
 item['latest_refinement']=dict(report=P.relative_to(R).as_posix()+'/index.html',note='First direct source opinion; original bytes unchanged; no runtime acceptance transfer.')
c=d['counts'];c['inclusive_current_source_priorities']=sum(x.get('capture_family') not in ('geode_current_v1','nursery_wash_v3') and x.get('current_source_score') is not None and x['current_source_score']<=4.5 for x in d['items']);c['unique_source_file_priorities']=sum(x['kind']=='source' and x.get('current_source_score') is not None and x['current_source_score']<=4.5 for x in d['items']);c['unreviewed_current_source']=sum(x['kind']=='source' and x.get('current_source_score') is None for x in d['items'])
assert c['inclusive_current_source_priorities']==713 and c['unique_source_file_priorities']==570 and c['unreviewed_current_source']==377
d.update(display_revision='V38_EIGHT_MORE_DIRECT_SOURCE_OPINIONS',updated_utc=now,scope='V38 known register:1263 unique source files,328 pose cells,85 runtime state/use/action entries and126 source object regions =1802 entries. Eight previously unassigned Day One discovery candidates now have individual full-native source opinions: seven inclusive priorities, six below4.5, star4.5 and painted crystal texture4.6 provisional. Known source/cell/region priorities713 (570 unique source files);377 source reviews remain. Existing current Geologist23 state/use/action priorities and Nursery10 priorities remain unchanged; whole Nursery wash3.9/attention3.8. Fresh still4.5 and rejected A3 reference action2.7 are separate. Complete timed pan/fossil actions, actual-use discovery, ordinary full-career/training breadth, device/child/owner/all-job acceptance remain open. All783 recorded actual production bytes unchanged. No source or runtime binding changed. All original dated opinions/history retained.')
d.setdefault('review_resources',[]).append(dict(path=P.relative_to(R).as_posix()+'/index.html',scope='Eight complete native previously unassigned source originals; written individual opinions, seven inclusive priorities. Discovery use unverified.'))
write(L/'ALL_ITEMS.json',d)
raw=(L/'all_items.html').read_text(encoding='utf-8');raw=raw.replace('</header>','<p><a href="../day_one_unassigned_sources_v3_20261002/index.html">Eight additional full-native source reviews</a>: six below4.5, painted star4.5 inclusive-priority and crystal texture4.6 provisional. Actual job binding/action acceptance remains open.</p></header>',1);(L/'all_items.html').write_text(raw,encoding='utf-8',newline='\n')
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
note='Eight unassigned source reviews continuation (2026-10-02): [every8 complete native Day One discovery candidate with individual written score/refinement/hash](day_one_unassigned_sources_v3_20261002/index.html) directly inspected. Carrot3.1/pine3.8/rainbow4.4/snowman fragment3.2/sprout3.8/star4.5/sun4.3/crystal texture4.6. Six below floor; seven inclusive priorities; no artwork changes. RegisterV38 remains1802 entries,713 known source/cell/region priorities (570 unique source files),377 source reviews still required. Actual job use/mounted/action/ordinary routes/device/child/owner/all-job acceptance remain open; all783 actual production bytes unchanged.'
master=R/'audit/MASTER_AUDIT_2026-08-09.md';raw=master.read_text(encoding='utf-8');raw=raw.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+note+'\n',1).replace('### Development task index\n','### Development task index\n\n'+note+'\n',1);master.write_text(raw,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';ledger.write_bytes(ledger.read_bytes()+b'\n| `audit/day_one_unassigned_sources_v3_20261002/index.html` | '+ '🟣'.encode()+b' | `SOURCE_REVIEW_DRAFT`; all8 native discovery candidates individually reviewed, seven inclusive priorities/six below4.5. Source-only; actual job use, mounting, action/device/child/owner/all-job acceptance unverified. Original sources unchanged; live register preserves prior history. |\n')
findings=R/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';findings.write_bytes(findings.read_bytes()+b'\nEight unassigned source review continuation (2026-10-02): [all8 complete native Day One discovery candidates with individual opinions](../day_one_unassigned_sources_v3_20261002/index.html) directly inspected; seven inclusive priorities/six below4.5. V38 source reviews outstanding377. Dependency discovery is not actual mounted/action evidence, no source edits or finding lifecycle change; MA-VIS-006 remains open.\n')
licenses=R/'ASSET_LICENSES.md';licenses.write_bytes(licenses.read_bytes()+b'\n| `audit/day_one_unassigned_sources_v3_20261002/**` | Original project source-review documentation and diagnostic browser proof | Original project review; referenced source licenses unchanged | Literal source SHA256 and individual native opinions | No source artwork modification; conservative discovery candidates only, no runtime/action acceptance. |\n')
ip=R/'design/audit_impacts/job-unassigned-source-eight-20261002.json';impact=read(ip);impact['files']=sorted({x.relative_to(R).as_posix() for x in P.rglob('*') if x.is_file()}|{x.relative_to(R).as_posix() for x in history.rglob('*') if x.is_file()}|{'ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/all_items.html','audit/job_artwork_refinement_live/CURRENT_BOUNDARY_REFRESH.json'})
impact['validation']=[dict(command='Eight full-native original individual direct visual reviews',result='PASS',evidence=P.relative_to(R).as_posix()+'/DIRECT_REVIEW.json; source-only opinions, six below4.5 preserved')];impact['acceptance_gaps']='All8 original sources reviewed; six below4.5/seven inclusive priorities. No source modified.377 source reviews remain. Conservative discovery candidate use, mounting, action sequencing, target-device, child, owner and all-job completion remain open. No finding lifecycle closure.';write(ip,impact)
proc=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(L/'review_tools/refresh_current_job_review_v35.py')],cwd=R,capture_output=True,check=True)
print(proc.stdout.decode().strip());print('EIGHT_SOURCE_OPINIONS_RECORDED|all8 direct native|713 known priorities|377 source reviews required|783 actual production bytes unchanged')
