"""Render the source-bound review packet; this tool never generates artwork grades."""
from pathlib import Path
import argparse, hashlib, html, json
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "assets_src/imagegen/day2_replacements_batch1_20260930"
def sha(path):
	return hashlib.sha256(path.read_bytes()).hexdigest()
def check(data):
	assert (BASE / ".gdignore").exists()
	assert data["owner_approval"] is None and not data["runtime_integration"]
	assert len(data["items"]) == len({x["id"] for x in data["items"]}) == 8
	for x in data["items"]:
		assert sha(ROOT/x["source_path"]) == sha(ROOT/x["source_reference"]) == x["source_sha256"]
		assert sha(ROOT/x["selected_candidate"]) == x["selected_sha256"] == x["visual_reviewed_sha256"]
		assert 4.5 <= x["quality_score"] < 5 and x["source_review_complete"] and x["owner_approval"] is None
		assert all(4.5 <= value < 5 for value in x["criteria_scores"].values())
		im=Image.open(ROOT/x["selected_candidate"])
		assert im.mode == "RGBA" and im.size == (1024,1024)
		alpha=im.getchannel("A")
		assert alpha.getextrema() == (0,255)
		assert all(im.getpixel(p)[3] == 0 for p in [(0,0),(1023,0),(0,1023),(1023,1023)])
		bbox=alpha.point(lambda value:255 if value>=8 else 0).getbbox()
		assert bbox and bbox[0]>0 and bbox[1]>0 and bbox[2]<1024 and bbox[3]<1024
		for a in x["attempts"]:
			assert sha(ROOT/a["native_path"]) == a["native_sha256"]
			assert sha(ROOT/a["prompt_path"]) == a["prompt_sha256"]
			assert all(sha(ROOT/r["path"]) == r["sha256"] for r in a["bound_references"])
		a=next(a for a in x["attempts"] if a["attempt"]==x["selected_attempt"])
		assert a["score"]==x["quality_score"] and a["review"]=="SELECTED_CANDIDATE_MEETS_DRAFT_SOURCE_TARGET"
	assert data["generation_count"]==sum(len(x["attempts"]) for x in data["items"])
	print("DAY2_REPLACEMENTS|PASS|8 selected candidates; 9 native attempts; exact original/prompt/reference/output hashes; 1024 RGBA; owner approval pending")
def relative(path):
	return Path(path).relative_to(BASE.relative_to(ROOT)).as_posix()
def build(data):
	check(data)
	lines=["# Day Two replacement artwork — first approval batch","","Status: **candidate files ready for user review; user approval pending**. Eight separate replacement files address named source-image defects. No live game texture or protected original is changed. The original 637-image audit and 432-item inclusive priority queue retain their history.","","[Illustrated before/after review](index.html) · [Exact manifest and prompts](MANIFEST.json)","","## Result and scoring","","Eight selected candidates score **4.6–4.7/5** in Codex source review, meeting the requested minimum **4.5/5**. Nine built-in imagegen edit calls were used: eight initial candidates and one precise Kitchen correction. The first Kitchen candidate is retained and rejected at 4.3 for changing the pot emblem.","","The five criteria are identity/visual role, contour/isolation, palette/value, painted material finish and small-scale readability. Each also meets 4.5 in this draft. These are authored visual opinions bound to exact selected hashes; this tool checks the binding and never grades a new image. No 5/5 or owner/runtime acceptance is claimed under DL-VIS-07 and DL-VIS-08.","","## Individual results","","| Item | Original score | Selected score | Attempts |","|---|---:|---:|---:|"]
	for x in data["items"]:
		lines.append(f'| {x["id"]} — {x["name"]} | {x["source_score"]}/5 | {x["quality_score"]}/5 | {len(x["attempts"])} |')
	lines += ["","![Before/after and small-scale inspection](comparison_board.png)","","The board and HTML show inspection-only composites on neutral cream/navy mats. These are source readability proxies, not current runtime screenshots or generation inputs. Wheel previews use the actual 36px draw size, badges use 64px, and other proxies use 112px. Comparison-board pixels never become replacement art.",""]
	cards=[]
	for x in data["items"]:
		before,after=relative(x["source_reference"]),relative(x["selected_candidate"])
		lines += [f'## {x["id"]} — {x["name"]}',"",f'**Before {x["source_score"]}/5 → candidate {x["quality_score"]}/5.** {x["evaluation"]}',"",f'**Interaction/integration review:** {x["runtime_review_required"]}',"",f'[Original comparison reference]({before}) · [Selected 1024px RGBA candidate]({after})',"","Criterion scores: "+"; ".join(f'{k.replace("_"," ")} {v}/5' for k,v in x["criteria_scores"].items())+".","",f'Source: {x["source_path"]}. Source SHA-256: {x["source_sha256"]}. Selected SHA-256: {x["selected_sha256"]}.',""]
		size=36 if x["id"]=="D2A-0495" else 64 if x["id"] in ("D2A-0635","D2A-0636","D2A-0637") else 112
		attempts="".join(f'<li>Attempt {a["attempt"]}: {html.escape(a["review"])} · {a["score"]}/5 · <a href="{relative(a["native_path"])}">native PNG</a> · <a href="{relative(a["prompt_path"])}">exact prompt</a></li>' for a in x["attempts"])
		cards.append(f'''<article id="{x["id"]}"><h2>{x["id"]} · {html.escape(x["name"])}</h2><p class="score">{x["source_score"]}/5 → {x["quality_score"]}/5 <span>Draft source review · owner approval pending</span></p><div class="pair"><figure><div class="mat"><img src="{before}" alt="Original {html.escape(x["name"])}"></div><figcaption>Existing source</figcaption></figure><figure><div class="mat"><a href="{after}"><img src="{after}" alt="Selected {html.escape(x["name"])}"></a></div><figcaption>Selected candidate · click for full size</figcaption></figure></div><p>{html.escape(x["evaluation"])}</p><div class="proxies"><div class="light"><img src="{after}" style="width:{size}px;height:{size}px" alt="Light small-scale proxy"></div><div class="dark"><img src="{after}" style="width:{size}px;height:{size}px" alt="Dark small-scale proxy"></div></div><p class="small">{size}px source proxy; not a runtime capture.</p><details><summary>Interaction, attempts and provenance</summary><p>{html.escape(x["runtime_review_required"])}</p><ul>{attempts}</ul><p class="hash">Original SHA-256 {x["source_sha256"]}<br>Selected SHA-256 {x["selected_sha256"]}</p></details></article>''')
	lines += ["## Reuse, provenance and technical handling","",f'Task baseline: exact integration {data["source_revision"]}. Existing sources, physical-door/elevator manifest, source masters, Tree Book and specialist draw routes were inventoried. Every generation binds existing artwork as identity reference; no unrelated scene or full actor redesign is commissioned.',""]
	lines += [f'- **{key.title()}:** {reason}' for key,reason in data["source_gap_and_reuse"].items()]
	lines += ["","Every native 1254×1254 generated PNG is preserved byte-for-byte. Selected textures are whole-canvas aspect-preserving reductions to 1024×1024. No subject is cropped, shifted, warped, keyed, composited or locally repaired in post-processing. Native/selected hashes, complete prompts, bound reference roles/hashes and attempt decisions are in MANIFEST.json. The .gdignore keeps native, rejected and review art outside runtime import.","","Selected files have true RGBA, transparent corners and a complete visible alpha>=8 footprint inside the canvas. Very faint alpha 1–7 residue can extend outside that footprint; it is recorded rather than silently deleted. The reviewed light/dark proxies show no visible plates, bars or solid edge clipping. Actual game sampling and device presentation still need review.","","## Remaining queue and next decisions","","This is the initial eight-item set, not a claim that all 432 priorities are repaired. The remaining **424** original queue entries include **149 inactive, retired or reference alternatives**, plus actor atlases, background families, vector/procedural graphics and context-dependent items. Each needs its own usage/reuse decision.","","The faceted racer portrait D2A-0054 should first be compared with the existing painted racer-imp family and real draw route. The ballet flower disc, Detective spotlight, opaque Painter brush and Candy cart remain route-dependent candidates. Old tail-cropped Roshan cards should give way to existing full-tail atlases where applicable. Protected doll originals remain intact; later isolation needs separate attributed derivatives. Background families require native-coverage, composition and seam review and cannot be regenerated tile by tile. None is silently marked repaired by this batch.","","## Verification and user approval","","Machine evidence is in [VERIFICATION.json](VERIFICATION.json): exact source/reference/prompt/output hashes, 1024 RGBA/margins, original preservation, browser/image decoding, document authority, change coverage and the shrinking 2D gate. Full CI results are linked when available. Checks never supply visual ratings or user approval.","","**User decision requested:** approve this report and the eight selected source candidates, or name item IDs for another revision. Approval must come from the user. All owner_approval fields remain null until that response. Runtime integration, live motion/contact, target device, child and whole-game acceptance are separate. No finding is closed and no release is authorized by this draft.",""]
	(BASE/"REPORT.md").write_text("\n".join(lines).rstrip()+"\n",encoding="utf-8")
	page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Day Two replacement artwork approval batch</title><style>*{box-sizing:border-box}body{margin:0;background:#fbf8ef;color:#29253e;font:17px/1.6 system-ui}header,main{max-width:1120px;margin:auto;padding:30px}h1{font-family:Georgia,serif;font-size:clamp(30px,5vw,56px);line-height:1.15}h2{font-size:22px}a{color:#5b397d}.notice{background:#eee5f3;border-left:5px solid #765596;padding:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}article{background:white;border:1px solid #d8cfe1;border-radius:16px;padding:20px;min-width:0}article p{overflow-wrap:anywhere}.score{font-weight:bold;font-size:24px}.score span{display:block;font-size:14px;font-weight:normal}.pair{display:grid;grid-template-columns:1fr 1fr;gap:12px}figure{margin:0}.mat{background:#e7deef;border-radius:9px;display:flex;align-items:center;justify-content:center;height:220px}.mat img{width:100%;height:210px;object-fit:contain}.mat a{display:block;width:100%;height:100%}figcaption,.small{font-size:13px}.proxies{display:grid;grid-template-columns:1fr 1fr;gap:12px}.proxies>div{height:145px;display:flex;align-items:center;justify-content:center;border-radius:8px}.light{background:#fff8e4}.dark{background:#18203b}.proxies img{object-fit:contain}.hash{font:12px/1.6 monospace;overflow-wrap:anywhere}summary{cursor:pointer;font-weight:600}.board{max-width:100%;height:auto}@media(max-width:700px){header,main{padding:18px}.grid{grid-template-columns:1fr}.mat{height:190px}.mat img{height:180px}}</style><header><p>Mermaid Roshan · 30 September 2026</p><h1>Eight replacement candidates<br>ready for your review</h1><p>Before/after artwork, scores, small-scale checks and every generation attempt.</p><p class="notice">All eight meet the 4.5/5 draft source target. Your approval is pending. Originals, gameplay and saves are preserved; these are separate review files.</p><p><a href="REPORT.md">Comprehensive report</a> · <a href="MANIFEST.json">Manifest and provenance</a> · <a href="VERIFICATION.json">Machine verification</a> · <a href="selected/">Selected files</a></p><p>Approve the report and all eight candidates in chat, or name IDs for revision. This page never records approval on your behalf.</p></header><main><div class="grid">CARDS</div><details><summary>Full comparison board</summary><img class="board" src="comparison_board.png" alt="Eight before/after comparisons and small source proxies"></details></main></html>'''.replace("CARDS","".join(cards))
	(BASE/"index.html").write_text(page,encoding="utf-8")
	print("Rendered report and illustrated approval page; authored scores unchanged.")
if __name__=="__main__":
	parser=argparse.ArgumentParser();parser.add_argument("--check",action="store_true");args=parser.parse_args()
	data=json.loads((BASE/"MANIFEST.json").read_text(encoding="utf-8"))
	check(data) if args.check else build(data)
