#!/usr/bin/env python3
"""Expand a short owner prompt into a reviewable plan, without executing it.

Recipes in design/reference/recipes/ are rendered from the prompt catalogue, so
the two cannot drift: edit design/reference/prompt_intents.json, then run
`python -B tools/plan_prompt.py --render-recipes` and `--check`.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

try:
    from tools.build_study_roadmap import stale_strength_evidence, validate_strengths
except ModuleNotFoundError:  # Direct execution from tools/.
    from build_study_roadmap import stale_strength_evidence, validate_strengths

ROOT = Path(__file__).resolve().parents[1]
CATALOGUE = "design/reference/prompt_intents.json"
STRENGTHS = "design/reference/strengths.json"
RECIPE_STATUS = ("Status: `SUPPORTING_CURRENT` planning recipe. It routes current authority; it grants no content "
                 "commission, generation budget, acceptance or release beyond the owner instruction and binding contract.")
RECIPE_RULES = ("Rules: `DL-AUTH-05` through `DL-AUTH-07`, `DL-PLAN-01` through `DL-PLAN-06`, and all affected child, "
                "interaction, save, medium, motion/cinematic, audio and acceptance rules. Consult live canonical findings; "
                "do not copy historical counts or superseded engine/3D directions.")
RECIPE_PATTERNS = ("Pattern references are the hash-bound seed entries in the strengths register; no maintained PAT/EX "
                   "catalogue or promoted exemplar is implied. Owner-decision defaults `ODR-LOOP-Q1`–`Q8` are operating "
                   "defaults, not answers. The recorded Roshan decisions `ODR-ROSHAN-IDENTITY`, `ODR-ROSHAN-IRIDESCENT`, "
                   "`ODR-ROSHAN-Q12`–`Q16` retain their exact scopes.")
RECIPE_ROLES = ("Claude writes specifications, audits and study reports; Codex builds code and every image, board and capture. "
                "An owner's explicit request in the current task may change who implements non-image work; images keep the "
                "CLAUDE.md exception (an explicit owner request for one specific image covers only that image). "
                "A plan generated by `tools/plan_prompt.py` executes nothing.")
NO_TOUCHPOINTS = "None within the existing authorized scope. Preserve explicitly reserved decisions and acceptance gates."
JOB_BEAT_FIELDS = ["act", "verb", "requires", "result_state", "child_action", "visible_change", "voice_key", "line", "pointer", "contact"]


class IntentError(ValueError):
    """No single intent matched; carries the closest catalogue candidates."""

    def __init__(self, message: str, candidates: list[dict]):
        super().__init__(message)
        self.candidates = candidates


def load_catalogue(root: Path) -> dict:
    return json.loads((root / CATALOGUE).read_text(encoding="utf-8"))


def validate_catalogue(root: Path, catalogue: dict) -> list[str]:
    errors: list[str] = []
    ids: set[str] = set()
    for intent in catalogue.get("intents", []):
        identifier = intent.get("id", "")
        if not re.fullmatch(r"INT-[A-Z-]+", identifier) or identifier in ids:
            errors.append(f"invalid or duplicate intent: {identifier}")
        ids.add(identifier)
        recipe = intent.get("recipe", {})
        if not recipe.get("id") or not recipe.get("path"):
            errors.append(f"{identifier}: missing recipe")
        elif not (root / recipe["path"]).is_file():
            errors.append(f"{identifier}: missing recipe file {recipe['path']}")
        for key in ("says", "match_patterns", "read_first", "expand", "gates", "write_backs"):
            if not intent.get(key):
                errors.append(f"{identifier}: missing {key}")
        for reference in intent.get("read_first", []):
            path = reference.split("#", 1)[0]
            if not (root / path).is_file():
                errors.append(f"{identifier}: missing reference {path}")
        for pattern in intent.get("match_patterns", []):
            try:
                re.compile(pattern, re.IGNORECASE)
            except re.error as error:
                errors.append(f"{identifier}: bad match pattern: {error}")
        for touchpoint in intent.get("owner_touchpoints", []):
            if not str(touchpoint.get("question", "")).rstrip().endswith("?") or not touchpoint.get("default") or not touchpoint.get("trigger"):
                errors.append(f"{identifier}: owner touchpoints need a question, a default and a trigger")
    return errors


def _matches(intent: dict, prompt: str, anchored: bool) -> bool:
    return any(pattern.startswith("^") == anchored and re.search(pattern, prompt, re.IGNORECASE)
               for pattern in intent["match_patterns"])


def candidates_for(prompt: str, catalogue: dict, limit: int = 3) -> list[dict]:
    """Closest intents by shared words with their example phrasings."""
    words = set(re.findall(r"[a-z]+", prompt.lower())) - {"a", "an", "the", "to", "of", "in", "and", "for", "do", "make"}
    scored = []
    for intent in catalogue["intents"]:
        vocabulary = set(re.findall(r"[a-z]+", " ".join(intent["says"] + [intent["id"], intent.get("minimum_input", "")]).lower()))
        scored.append((len(words & vocabulary), intent["id"], intent))
    scored.sort(key=lambda row: (-row[0], row[1]))
    return [{"intent": row[2]["id"], "example": row[2]["says"][0], "minimum_input": row[2].get("minimum_input", "")}
            for row in scored[:limit]]


def infer_intent(prompt: str, catalogue: dict) -> dict:
    """A leading verb (fix, retire, ship it...) decides first; then any single match."""
    for anchored in (True, False):
        matches = [intent for intent in catalogue["intents"] if _matches(intent, prompt, anchored)]
        if len(matches) == 1:
            return matches[0]
        if len(matches) > 1:
            raise IntentError("Prompt matches several intents: " + ", ".join(item["id"] for item in matches)
                              + ". Say it with one of the example phrasings, or use --intent.",
                              [{"intent": item["id"], "example": item["says"][0], "minimum_input": item.get("minimum_input", "")} for item in matches])
    raise IntentError("No recipe matches this prompt yet. Closest recipes are listed; say it like one of the examples, "
                      "or use --intent. A missing recipe is a lesson for the next study.", candidates_for(prompt, catalogue))


def save_inventory(root: Path) -> dict:
    """Read allocation sites; the plan never trusts seed counts as live facts."""
    house = (root / "scripts/opera_house.gd").read_text(encoding="utf-8")
    save = (root / "scripts/save_state.gd").read_text(encoding="utf-8")
    bits = sorted({int(value) for value in re.findall(r'"save_bit"\s*:\s*(\d+)', house)})
    if not bits:
        raise ValueError("Cannot allocate: no save_bit records found; inspect the current extension path.")
    retired = sorted({int(value) for value in re.findall(r'\{\s*"save_bit"\s*:\s*(\d+)\s*,\s*"retired"\s*:\s*true\s*\}', house)})
    next_bit = max(bits) + 1  # Includes retired rows: identities are never reused.
    mask_match = re.search(r"const OPERA_ACTIVE_STAR_MASK\s*(?::[^=\n]+)?[:=]*\s*(0x[0-9A-Fa-f]+|\d+)", save)
    count_match = re.search(r"const OPERA_ACTIVE_ACT_COUNT\s*(?::[^=\n]+)?[:=]*\s*(\d+)", save)
    if not mask_match or not count_match:
        raise ValueError("Cannot read the live save mask/count; no allocation guess is permitted.")
    namespace_bound = (1 << next_bit) - 1
    proposed_bound = (1 << (next_bit + 1)) - 1
    clamp_sites = [index for index, line in enumerate(save.splitlines(), 1)
                   if re.search(rf"\b{namespace_bound}\b", line)]
    if not clamp_sites:
        raise ValueError(f"No literal {namespace_bound} clamp found in scripts/save_state.gd; inspect the clamp sites "
                         "(they may be written as expressions) before allocating a bit.")
    retired_text = ", ".join(str(bit) for bit in retired) or "none recorded"
    return {
        "next_bit": next_bit, "current_active_mask": hex(int(mask_match.group(1), 0)),
        "proposed_active_mask": hex(int(mask_match.group(1), 0) | (1 << next_bit)),
        "current_active_count": int(count_match.group(1)),
        "proposed_active_count": int(count_match.group(1)) + 1,
        "proposed_namespace_bound": proposed_bound,
        "current_namespace_bound": namespace_bound,
        "namespace_clamp_lines": clamp_sites,
        "retired_bits": retired,
        "source": ["scripts/opera_house.gd", "scripts/save_state.gd"],
        "caveat": (f"Plan only, measured at this head. Re-read the load, write and both shared normaliser clamp sites at "
                   f"implementation head; all {len(clamp_sites)} clamps of {namespace_bound} must become {proposed_bound} "
                   f"for bit {next_bit}. Exercise external merge through the shared normaliser. Never reuse retired "
                   f"(tombstone) bits ({retired_text}); retain every existing save key and add new keys with defaults. "
                   "If the platform or namespace changed, derive bounds from its live catalogue instead of this plan."),
    }


def job_name(prompt: str) -> str | None:
    """The job the owner named, e.g. "add a bakery job" -> "bakery"."""
    for pattern in (r"\bjob\s*:\s*([A-Za-z][A-Za-z -]{0,40}?)\s*$",
                    r"\b(?:add|new|plan)\b(?:\s+(?:a|an|the))?\s+([A-Za-z][A-Za-z -]{0,40}?)\s+(?:job|career)\b"):
        match = re.search(pattern, prompt.strip(), re.IGNORECASE)
        if match:
            return match.group(1).strip().lower()
    return None


def job_card_scaffold(prompt: str) -> dict:
    """What the agent must design for the named job; no job's answer is stored here."""
    name = job_name(prompt) or "the job the owner named"
    return {
        "job": name,
        "status": "TO_DESIGN",
        "premise": f"One sentence a four-year-old would enjoy: what Roshan does as a {name}, and what is different at the end.",
        "home": "Propose one thematic castle room with the reason it fits (read scripts/castle_career_routes.gd), "
                "or the existing Opera freeplay venue. The owner confirms the premise and room before anything permanent is added.",
        "beats": f"Design four to six beats for {name} from the job itself, grouped Teach / Play / Twist / Bow. "
                 "Every beat is a different verb, requires the previous beat's saved state and the child's one-finger action, "
                 "and leaves a visible, truthful change that stays. Do not copy another job's verbs or payoff.",
        "beat_fields": JOB_BEAT_FIELDS,
        "state_rules": "One finger, a voice line plus a pointer for every objective, no fail state. Idle input, a timer or a "
                       "demonstration never finishes a beat or awards progress. Back or focus loss cancels the unfinished "
                       "action and keeps completed checkpoints.",
        "imp": "Competitive careers end in the DL-INT-14 contest (hidden imp, one head-to-head job-skill contest, a win beat of "
               "at most 2 s, instant rematch with nothing lost, no idle win or loss, slower each rematch to a floor). The "
               "contest-only restart scope awaits owner confirmation. Learning careers use the inverted form.",
        "quality_gate": "5/5 is a target that needs owner acceptance in runtime context (DL-VIS-07); machine checks grant no score.",
    }


def binding_strengths(root: Path, intent: dict) -> list[dict]:
    """Bind strengths accepted first; changed evidence is flagged, not fatal."""
    document = json.loads((root / STRENGTHS).read_text(encoding="utf-8"))
    errors = validate_strengths(root, document, check_hashes=False)
    if errors:
        raise ValueError("Strength register invalid: " + "; ".join(errors))
    stale = {row["id"] for row in stale_strength_evidence(root, document)}
    bound = [strength for strength in document["strengths"] if strength["id"] in intent.get("strengths", [])]
    bound.sort(key=lambda item: (item["tier"] != "accepted", item["id"]))
    rows = []
    for item in bound:
        row = {"id": item["id"], "tier": item["tier"], "scope": item["acceptance_scope"]}
        if item["id"] in stale:
            row["evidence_changed"] = True
            row["scope"] += " Evidence changed since review: re-review before relying on it."
        rows.append(row)
    return rows


def build_plan(root: Path, prompt: str, intent_id: str | None = None) -> dict:
    catalogue = load_catalogue(root)
    errors = validate_catalogue(root, catalogue)
    if errors:
        raise ValueError("; ".join(errors))
    if intent_id:
        intent = next((item for item in catalogue["intents"] if item["id"] == intent_id), None)
        if intent is None:
            raise ValueError(f"Unknown intent {intent_id}")
    else:
        intent = infer_intent(prompt, catalogue)
    plan = {
        "schema": "prompt_plan/1", "status": "PLAN_ONLY", "prompt": prompt,
        "intent": intent["id"], "recipe": intent["recipe"],
        "defaults": intent["defaults"], "read_first": intent["read_first"],
        "strengths": binding_strengths(root, intent),
        "steps": intent["expand"], "variety_rules": intent["variety_rules"],
        "owner_touchpoints": intent["owner_touchpoints"], "gates": intent["gates"],
        "write_backs": intent["write_backs"],
        "acceptance": "Machine, visual, device, child and owner evidence remain separate; this plan grants none.",
    }
    if intent["id"] == "INT-ADD-JOB":
        plan["save_allocation"] = save_inventory(root)
        plan["job_card"] = job_card_scaffold(prompt)
    return plan


def render_plan(plan: dict) -> str:
    rows = [f"# Prompt plan: {plan['prompt']}", "", f"Status: `{plan['status']}`. Recipe: `{plan['recipe']['id']}` ({plan['recipe']['path']}).", "", plan["acceptance"], ""]
    for heading, key in (("Read first", "read_first"), ("Build plan", "steps"), ("Variety", "variety_rules"), ("Gates", "gates"), ("Write back", "write_backs")):
        rows += [f"## {heading}", ""] + [f"- {item}" for item in plan[key]] + [""]
    rows += ["## Owner touchpoints", ""]
    rows += [f"{index}. {item['question']} Default: {item['default']}. Trigger: {item['trigger']}." for index, item in enumerate(plan["owner_touchpoints"], 1)] or ["None for authorized scope."]
    for key in ("strengths", "save_allocation", "job_card"):
        if key in plan:
            rows += ["", f"## {key.replace('_', ' ').title()}", "", "```json", json.dumps(plan[key], indent=2, ensure_ascii=False), "```"]
    return "\n".join(rows) + "\n"


def render_recipe(intent: dict, strengths: dict) -> str:
    """One recipe page, rendered from its catalogue entry."""
    recipe = intent["recipe"]
    title = recipe["id"].removeprefix("REC-").replace("-", " ").title()
    tiers = {item["id"]: item["tier"] for item in strengths.get("strengths", [])}
    bound = sorted(intent.get("strengths", []), key=lambda identifier: (tiers.get(identifier) != "accepted", identifier))
    lines = [f"# {recipe['id']}: {title}", "", RECIPE_STATUS, "",
             f"Intent: `{intent['id']}`. Example: {intent['says'][0]}. Minimum input: {intent.get('minimum_input', 'none')}.", "",
             f"Default: {intent['defaults']}", "", "## Read first", ""]
    lines += [f"- `{path}`" for path in intent["read_first"]]
    lines += ["", RECIPE_RULES, "",
              "Bound strengths (accepted first; candidates explicitly remain candidates): "
              + (", ".join(f"`{identifier}` ({tiers.get(identifier, 'unregistered')})" for identifier in bound) or "none") + ".", "",
              RECIPE_PATTERNS, "", "## Expand", ""]
    lines += [f"{index}. {step}" for index, step in enumerate(intent["expand"], 1)]
    lines += ["", "## Variety", ""] + [f"- {rule}" for rule in intent["variety_rules"]]
    lines += ["", "## Owner touchpoints", ""]
    lines += [f"{index}. {item['question']} Default: {item['default']}. Trigger: {item['trigger']}."
              for index, item in enumerate(intent["owner_touchpoints"], 1)] or [NO_TOUCHPOINTS]
    lines += ["", "## Build and check", "", RECIPE_ROLES, ""] + [f"- {gate}" for gate in intent["gates"]]
    lines += ["", "## Learn", ""] + [f"- {item}" for item in intent["write_backs"]]
    lines += ["", "## Revision and served prompts", ""]
    lines += [f"- {entry}" for entry in intent.get("revision_history", [])]
    served = intent.get("served_prompts") or []
    lines += [f"- Served: {entry}" for entry in served] or ["- No completed served prompt or runtime/owner acceptance is claimed."]
    return "\n".join(lines) + "\n"


def recipe_drift(root: Path, catalogue: dict) -> list[str]:
    strengths = json.loads((root / STRENGTHS).read_text(encoding="utf-8"))
    drift = []
    for intent in catalogue.get("intents", []):
        path = root / intent["recipe"]["path"]
        if not path.is_file() or path.read_bytes().replace(b"\r\n", b"\n").decode("utf-8") != render_recipe(intent, strengths):
            drift.append(f"{intent['recipe']['path']}: out of date with {CATALOGUE}; run --render-recipes")
    return drift


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("prompt", nargs="?")
    parser.add_argument("--intent")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--check", action="store_true", help="Validate the catalogue and that every recipe matches it")
    parser.add_argument("--render-recipes", action="store_true", help="Rewrite design/reference/recipes/ from the catalogue")
    args = parser.parse_args(argv)
    if args.render_recipes:
        catalogue = load_catalogue(args.root)
        strengths = json.loads((args.root / STRENGTHS).read_text(encoding="utf-8"))
        for intent in catalogue["intents"]:
            (args.root / intent["recipe"]["path"]).write_text(render_recipe(intent, strengths), encoding="utf-8", newline="\n")
        print(f"PROMPTS: rendered {len(catalogue['intents'])} recipes")
        return 0
    if args.check:
        catalogue = load_catalogue(args.root)
        errors = validate_catalogue(args.root, catalogue) + recipe_drift(args.root, catalogue)
        print("\n".join(errors) if errors else "PROMPTS: ALL OK")
        return int(bool(errors))
    if not args.prompt:
        parser.error("prompt required unless --check or --render-recipes")
    try:
        plan = build_plan(args.root, args.prompt, args.intent)
    except IntentError as error:
        print(f"PROMPT|NEEDS_INTENT|{error}")
        for row in error.candidates:
            print(f"- {row['intent']}: say it like \"{row['example']}\" (needs: {row['minimum_input'] or 'nothing more'})")
        return 2
    except (OSError, ValueError, KeyError) as error:
        parser.error(str(error))
    print(json.dumps(plan, indent=2, ensure_ascii=False) if args.json else render_plan(plan), end="\n" if args.json else "")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
