from pathlib import Path
import json,hashlib,datetime,html,shutil
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');packet=b/'assets_src/local_motion/day2_geologist_pan_motion_v3_20261001';out=packet/'attempt_01';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
cat=json.loads((out/'FRAME_CATALOG.json').read_text());rows=[]
for v0 in cat['native_frames']:
 v=dict(v0);i=v['index'];assert sha(packet/v['path'])==v['sha256']
 if i<=2:phase='entry';ev='Painted identity, full fin and rim contact remain clear. Early water/pan-height changes begin immediately; an entry hold is not an alternating action.';grip=4.5;rigid=4.5;verb=None;ret=None;emotion=4.5
 elif i<=7:phase='first tilt transition';ev='A visible left-low/right-high tilt starts, with local arm movement. Far fingers smear or partly disappear during the transition, and the rim has doubled/softened contours. This readable movement does not excuse topology and rigid-prop defects.';grip=3.2 if i==5 else 3.8;rigid=3.8;verb=4.5;ret=None;emotion=4.5
 elif i<=20:phase='first tilted hold';ev='The right side stays high and left side low; the held tilt is legible, hands again grip the rim, and the torso/tail stay quiet. No opposite-direction rock occurs in this span. Water mostly stays inside; the slight ellipse/edge changes still need rigid-vessel review.';grip=4.5;rigid=4.4;verb=3.8;ret=None;emotion=4.4
 elif i<=29:phase='continued same-direction hold';ev='The same raised-right tilt continues instead of reversing. The mouth changes from a smile to an open O without a specified emotion beat. Identity/full fin remain recognizable; this is not two alternating panning cycles.';grip=4.5;rigid=4.4;verb=3.4;ret=None;emotion=4.1
 elif i<=36:phase='return transition';ev='Pan lowers toward level with attached local arms, but far-hand and vessel edges smear/duplicate again. The body stays largely stable. The return must retain readable fingers and a rigid single rim in every frame.';grip=3.8;rigid=3.8;verb=4.2;ret=4.0;emotion=4.1
 else:phase='final level pose';ev='Pan becomes level near the entry height, but source mouth/expression is not restored and rim shading/outline remain changed. No opposite-direction tilt or complete loop occurs. A closer endpoint is useful reference, not clean neutral-return acceptance.';grip=4.4;rigid=4.1;verb=3.4;ret=4.2;emotion=4.1
 v.update(visual_review='DIRECT_NATIVE_ORIGINAL_RESOLUTION',reviewed_utc=now,phase=phase,scores=dict(painted_identity=4.6 if i<3 else 4.5,hand_rim_contact=grip,vessel_rigidity=rigid,body_stability=4.6,water_containment=4.4,intended_action=verb,neutral_return=ret,expression_continuity=emotion),evaluation=ev,owner_approval=None,runtime_accepted=False);v['visual_score']=min(x for x in v['scores'].values() if x is not None);rows.append(v)
assert len(rows)==41;qualification='Every41 original896x512 frame directly inspected;123 across all three comparable attempts. Source4.6 remains separate. Clear single tilt improves over still trials but failed transition fingers/rim, missing opposite rock and expression/return remain below4.5. Local Wan motion reference only; no runtime/cinematic, full route/device/child/owner acceptance.'
review=dict(status='ALL41_DIRECTLY_REVIEWED_MOTION_REFINEMENT_REQUIRED',reviewed_utc=now,source_score=4.6,motion_reference_score=4.0,alternating_panning_score=3.4,neutral_return_score=4.2,hand_contact_score=3.8,minimum_hand_topology_score=3.2,moving_vessel_rigidity_score=3.8,water_containment_score=4.4,body_stability_score=4.6,frames=rows,qualification=qualification,next_named_gap='Preserve local articulated tilt while repairing every moving finger/rim frame and adding the opposite tilt/neutral expression return. No good source-art redesign is justified.');write(out/'REVIEW.json',review);cat.update(status=review['status'],native_frames=rows,visual_review=rel(out/'REVIEW.json'));write(out/'FRAME_CATALOG.json',cat)
head='<!doctype html><meta charset="utf-8"><style>body{font:18px/1.5 system-ui;color:#302949;background:#eef5f4;max-width:1200px;margin:auto;padding:24px}article{background:white;padding:20px;margin:24px 0}img,video{width:100%;height:auto}small{overflow-wrap:anywhere}</style>'
cards=['<article><h2>Frame '+str(v['index'])+' · '+format(v['timestamp_seconds'],'.3f')+'s · '+v['phase']+'</h2><img loading="lazy" src="native_frames/'+Path(v['path']).name+'" alt="Native frame '+str(v['index'])+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+': '+str(s)+'/5' for k,s in v['scores'].items() if s is not None))+'</p><small>SHA256 '+v['sha256']+'</small></article>' for v in rows]
(out/'index.html').write_text(head+'<h1>Panning attempt3 —4.0/5; refinement required</h1><p>Visible single tilt, but alternating rock3.4, transition hands/rim3.8 (worst fingers3.2), return4.2. Source remains4.6. Every41 frame shown.</p><video controls src="native_output.mp4"></video><p>'+html.escape(qualification)+'</p><a href="REVIEW.json">Individual evaluations/hashes</a>'+''.join(cards),encoding='utf-8')
manifest=json.loads((packet/'MANIFEST.json').read_text());assert sha(out/'MANIFEST_AT_SUBMISSION.json')==json.loads((out/'WORKER_STATE.json').read_text())['manifest_sha256'];manifest.update(output_state='Native machine PASS; every41 frames directly inspected. Reference4.0; alternating rock3.4, moving fingers/rim3.8 (minimum fingers3.2), neutral return4.2 remain below4.5. No production acceptance.',visual_review='attempt_01/REVIEW.json');write(packet/'MANIFEST.json',manifest)
(packet/'index.html').write_text(head+'<h1>Third panning motion —4.0/5</h1><p>Visible articulated single tilt; repeated reverse rocking and clean transition fingers/rim remain weak. Every41 frame individually evaluated;123 across the three comparable attempts.</p><video controls src="attempt_01/native_output.mp4"></video><p><a href="attempt_01/index.html">Every original frame and written score</a> · <a href="attempt_01/MANIFEST_AT_SUBMISSION.json">Exact submission</a> · <a href="MANIFEST.json">Current status/bindings</a></p><p>'+html.escape(qualification)+'</p>',encoding='utf-8');shutil.copyfile(__file__,out/'executed_record_review_v151.py')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Panning reference third review (2026-10-01): [every41 third native frame](../'+rel(out/'index.html')+') directly inspected,123 total. Short prompt produces a visible single tilt, reference4.0; alternating action3.4/transition hand and rim3.8 (minimum fingers3.2)/return4.2 remain below4.5. Stable body4.6 does not approve the failed moving components. Source unchanged4.6; no runtime/cinematic/route/device/child/owner or comprehensive goal acceptance.';s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+entry+'\n',1);master.write_text(s,encoding='utf-8')
ledger=b/'design/05_DOC_LEDGER.md';lines=ledger.read_text().splitlines();needle='| `'+rel(packet/'index.html')+'`';lines=[(needle+' | 🟣 | `CANDIDATE_REFERENCE_ONLY`; all41 native frames individually reviewed,123 across three comparable attempts. Reference4.0, alternating action3.4/moving fingers-rim3.8 (minimum fingers3.2)/return4.2 remain below floor; source/body4.6 does not confer motion/runtime/cinematic/owner acceptance. |' if x.startswith(needle) else x) for x in lines];ledger.write_text('\n'.join(lines)+'\n',encoding='utf-8')
ip=b/'design/audit_impacts/job-geologist-panning-local-motion-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(p) for p in packet.rglob('*') if p.is_file()});d['validation'].append(dict(command='Direct original-resolution ordered inspection of every41 third native motion frame',result='PASS',evidence=rel(out/'REVIEW.json')+'; inspection complete; failed moving fingers/rim/alternation/return remain open.'));write(ip,d);allow=b/'tmp/v2_preview_allowed.json';a=set(json.loads(allow.read_text()));a.update(d['files']);write(allow,sorted(a));print('ALL123 frames DIRECT; third reference4.0 remains below floor')
