"""Prepare bounded source-preserving quality repairs, never new narrative scenes."""
from pathlib import Path
import json,hashlib,shutil
V=Path(__file__).resolve().parent;L=V.parents[1];R=L.parents[2]
V.joinpath('art').mkdir(exist_ok=True)
def save(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='\n')
if not (V/'BOOK_BASELINE.json').exists():shutil.copy2(L/'book.json',V/'BOOK_BASELINE.json')
B=json.loads((V/'BOOK_BASELINE.json').read_text(encoding='utf8'))
def src(k):return (L/B['sources'][k]['file']).resolve().relative_to(R).as_posix()
base=src('landscape_base');bunny='assets/sprites/dust_bunnies/dust_bunny_idle.png';lamma='assets/sprites/stuffie_studio/lamma.png'
roshan='assets_src/cinematics/roshan_swim_motion_auditions_2026-09-12/references/approved-front.png'
attic='books/chapter_one/landscape/art/event_borders/attic_atlas.png'
toy='assets/flats/castle/rooms/room_playroom_item_stacking_toy.png'
chest='assets/sprites/stuffie_studio/toy_chest.png'
jobs=[]
def job(id,page,refs,prompt,gap,transparent=False):jobs.append(dict(id=id,page=page,refs=refs,prompt=prompt,gap=gap,transparent=transparent,attempt=1,review='PENDING'))
bank='''Edit IMAGE_1 as a 7:5 landscape stationery background, same native aspect ratio. Preserve its clear light-blue watercolor field, crisp navy dotted perimeter, bubbles and two LOW BLUE seafloor banks. No writing, letters, main story figures or foreground pictures. All new decorations ENTIRELY within bottom15% (top y>=0.86), each individual width AND height <=12% canvas. Keep central x38%-62% completely empty. Objects only on the left/right bank, nestled into blue ground with narrow contact shadow and sand overlapping their base; never stickers hovering or square masks. Clean polished 2D watercolor, broad colors, navy/purple contours; crisp, no noise. Tiny playful details must read at print size, not photoreal. Dust bunny identity if present comes ONLY from IMAGE_2: lavender cloud body, forehead curl, TWO round spiral ears on pearl knobs, two pearl hand nubs, no legs/furry rabbit. Vary poses and count. Change only lower bank details. '''
job('bank05',5,[base,bunny,src('v22_scene_08')],bank+'LEFT: one little eager bunny peeks over a small blue shell basket with a folded pink towel. RIGHT: a rounded turquoise soap bottle resting against a shallow lavender soap dish. No brush or sponge because those are the large foreground story objects.', 'Existing lone idle bunny/soap fragment have weak event performance.')
job('bank07',7,[base,bunny,src('v22_scene_08')],bank+'LEFT: one bunny leaning to admire its face in a tiny standing gold shell hand mirror, delight, both ears distinguishable. RIGHT: one neatly folded lavender hand towel beside a small teal soap dish. No sink, brush, sponge or duplicate main action.', 'Sink-page border repeats the supply-page idle figure; give clean reflection gag.')
job('bank08',8,[base,bunny,'assets/flats/castle/rooms/room_bubble_bath_item_rubber_duck.png'],bank+'LEFT: one low crouching bunny gently pushes the tiny yellow rubber duck in IMAGE_3 along the blue bank using one pearl nub. RIGHT: a rolled lavender towel with the little gold bath plug and loose short chain, all grounded. No brush/sponge/tub.', 'Existing duck and generic cup lack playful drained-bath context.')
job('bank11',11,[src('v22_bg_10_objects'),bunny],bank+'Keep the actual pink crumpled snack wrapper on LEFT and dented algae-coated can plus blue lid on RIGHT. Refine them into the banks with short matching contact shadows and low algae tendril, clearly discarded rubbish, retaining exact shapes/colors. Add a second SMALL folded paper scrap behind the wrapper. No bunnies, clean toiletries, smudge or new cleaning tools.', 'Grounding and richness of true pool rubbish, no generic clean pool props.')
job('bank16',16,[base,bunny,'assets/flats/castle/interactions_v4/rest_cards/mermaid_pool_seahorse_fountain_rest.png'],bank+'LEFT: a tiny recognizable miniature of the cleared pastel seahorse fountain IMAGE_3, its crest starts below y86%, short clear stream returns to own basin. RIGHT: one little bunny rests its two pearl paws on a small pink flower-shaped cup and gazes warmly up toward the later hug. No additional characters/mermaids. Fountain height <=11%, no above-zone crest.', 'Old fountain crest above15% and lonely repeated bank shells; thankfulness echo.')
job('bank20',20,[base,bunny,toy],bank+'LEFT at x22%: tiny apologetic bunny, curled ears drooped sideways, pearl hands together, eyes looking upward, shy closed mouth. A small orange stacking ring lies beside it. RIGHT at x76%: second little bunny with one ear lower, one pearl hand behind head, sheepish upward glance, beside two tiny toy blocks. Exactly TWO bunnies each7%-9% canvas height; ears below86%. No speech bubbles/text (added later as editable typography). Preserve whole clear center and actualbankcontact.', 'Small apology bunnies need different poses, toy context and strict lower-zone placement.')
job('bank24',24,[base,bunny,attic],bank+'LEFT: tiny dusty blue-and-gold chest from IMAGE_3 with two skewed closed lavender books beside it. RIGHT: exactly TWO scared cowering bunnies; one squashes low with worried brows and tucked spiral ears, other hides under a pink scallop shell with both wide worried eyes peeking out. No rainbow, couch, smile or victory. Some little dusty closed book behind cower group is enough. Silhouettes clear, each<=10% height.', 'Cower poses and grounded attic clues need stronger expressiveness.')
job('bank25',25,[src('v22_bg_26_ground'),bunny,attic],bank+'Keep its small game-style turquoise/gold cloud couch on RIGHT with exactly TWO bunnies sitting comfortably, but refine actions. One brings a single popcorn kernel to mouth with pearl hand above a little striped popcorn cup. Other leans forward hopefully with clasped pearl hands toward later Roshan, warm supportive expression, not victory yelling. LEFT retain turquoise attic jar and partly opened lavender book. No huge brush/suds; every ear<=y86% start, couch<=12%width and all coherent blue-bankcontact.', 'Couch is good reusable geometry; strengthen distinct popcorn/support acting.')
job('bank30',30,[base,bunny,toy],bank+'LEFT: TWO small bunnies cooperate quietly, one passing an orange stacking ring to the other beside a very small colored ring stack from IMAGE_3. Different low poses, calm grateful expressions, no giant rainbow character. RIGHT: a tiny clean turquoise attic lamp and an opened purple book, restored objects. Do not repeat foreground rainbow Puff or Roshan. Allgroupnotcentral,eachindividual<=12%.', 'Existing generic puzzle pieces lack clear game-toy detail in friendship reflection.')
job('bank31',31,[base,bunny,toy,chest,lamma],bank+'LEFT: ONE low bunny slides an orange ring gently beside a small blue-and-gold toy chest IMAGE_4. A very subtle hidden Lamma peek comes from behind chest: unmistakable off-white fluffy oval forehead, TWO sideways ears with blue inner ears, navy eyes/lashes, peach tiny nose/mouth from IMAGE_5; head about60pixels wide on1484canvas, torsohidden, no eggs, clues, labels or arrows. RIGHT: second small bunny fits a ring onto the little stacking sailboat toy. ExactlyTWO bunniestotal and ONE hiddenLamma. Both banks show gentle socialplay; noidenticalpose, stars confetti orforeground Eagle.', 'Weak generic hidden face and repetitive toy poses; actual Lamma with quiet gentle play.')
job('castle03',3,[src('v28_castle_entry_source'),roshan], 'Restore the existing IMAGE_1 Grok frame at crisp native picture-book detail as 7:5 fullart. Preserve EXACT open red double-door castle entry, dark dusty hall beyond, Daddy on LEFT and Roshan reaching on RIGHT, both complete same positions/scale/gesture and unchanged scene/canon. This is owner-authorized source-resolution restoration; no new staging or scene. Keep Daddy glasses/crown/navycoat/tealcape/rainbowtail; Roshan plainpinkblouse/lavenderflutter sleeves, gold turquoise crown, brown rainbow-streak hair and ONE lilactail withrainbowfin from IMAGE_2. Smooth authored outline and broad pastel paint, nophotoreal extra finegrain. Preserve single original windows and seamless red door, no duplicated architecture. Extend only enough quiet original upperwall/arch to fit7:5, no mirrored strip. UpperRIGHT dark arch keeps quiet uniform purple shadow for later white text, no text.', '1264x720 full-art source is materially softer than other pages and entry is cramped.')
job('lamma09',9,[src('v22_scene_08'),lamma], 'Local inpaint IMAGE_1 only in the lowerLEFT towelbasket. Preserve all existing scene/art exactly. Add a very subtle Lamma head peeking from BEHIND the pink rolled towel, partly hidden by towelrim. IMAGE_2 exact identity: off-white fluffy oval head, TWO sideways ears blue inner ears, navy round eyes with eyelashes, tiny peach nose/mouth. Head approx70pxwide on1484canvas, not a bunny, not large or showcased, torsohidden. No labels/arrows/words/eggs. Keep towels, basket, Roshan, bath, bunny, furniture, lights, all colors and scene untouched; no redraw. Native7:5.', 'Previous cameo is generic ambiguous tiny face; owner says not recognizably present.')
job('fountain14',14,[src('approved_fountain_clear_v2'),roshan], 'Targeted identity inpainting ONLY Roshan neckline/wrists in IMAGE_1. Remove pearl necklace and bracelet that drift from IMAGE_2; plain pink crewneck blouse with lavender flutter sleeves and bare wrists. Preserve EXACT face, joy, crown, brownrainbowhair, arms, hands HOLDING THE EXISTING PINK CUP, tail, seahorse fountain, running water, allroomgeometry and setting. Cup and twohands contactsunchanged. Upperright violetwall remainsquiet for later caption. No text or fullsceneredraw. Polished2Dbookstyle notphotoreal.', 'Roshan pearl jewelry added on this page unlike canonical blouse/other pages.')
job('listen17',17,[src('v22_scene_16'),roshan], 'Targeted character edit in IMAGE_1: preserve entire dusty toy-storeroom, open doors, props, lavender bunny and exact Roshanbody/scale/tail/position. Refine ONLY Roshanhead/onearm to a gentle listening reaction to chirp from right: eyes glance RIGHT, mouth small curious smile, right hand near ear, unchanged identity plain pinkblouse lavenderflutter sleeves goldturquoisecrown brownrainbowhair. Retain source staging and no new scene/story beat. No extracharacters. Lowerfloor remainsdark quiet forwhitecaption. No text.', 'Static neutral atlas pose fails listening intent; bounded acting/identity repair.')
for id,page,key in [('rescue18',18,'rescue_trapped'),('rescue19',19,'approved_rescue_release')]:
 job(id,page,[src(key),src('v22_scene_16'),bunny,roshan], 'Bounded background/wardrobe repair in IMAGE_1. Keep ALL foreground characters, faces, size, positions, same rescue action, brush position/contact, BabyEaglepinkcrest pastelturquoise/yellowbody pinkblackwings grayfeet. Exactly TWO canonical lavender curl-ear cloudbunnies, no extras, nofur/legs. Preserve toyhall architecture, windows, toy bins and floor layout. Locally add gentle painted lavenderdust in roomcorners, a few cobwebs high corners, dustytoybin rims, muted lavenderfloor tones to connect to dusty playroom entry IMAGE_2; do NOT change roomshape/staging or darken it scary. Restore Roshan neckline to plainpinkblouse lavenderflutters as IMAGE_4, no necklace/buttons. Keep bottom12% quieter low-detailfloor for later native caption; no words. Source-preserving local repair, no replacement scene.', 'Dirty entry abruptly changes to spotless hall; local dust continuity and blouse lock.')
job('table22',22,[src('v22_scene_22_fit')], 'Local inpaint IMAGE_1 ONLY the large purple paint puddle on front tabletop next to brush: wipe it clean, preserving the same tabletopwood/color and tiny wet shine. The table should clearly be finishedclean. Keep Roshan exact spongecontact, hands, face, body, all toolspositions, shelves, room and scene. No fullredraw, rearrangement or newtext. Preserve7:5canvas.', 'Finished-clean caption contradicts substantial remaining paint puddle.')
job('sponge25',25,[src('v28_puff_reassurance'),src('v27_scrub')], 'Targeted inpaint of IMAGE_1 ONLY the pinkstar sponge in Roshan outstretched hand. Replace that smallheld supply with same softyellow roundedrectangular soapy sponge she uses in IMAGE_2; keep grippingfingers, handgesture, exactly same supplyboundingbox and orientation. All Roshanidentity/pose/scale/body/crown/face, Puff, spacing, transparentoutsidecontours remainunchanged. No scene/background, no new prop or action. Genuine transparentRGBA exterior; preserve allnaturalholes.', 'Reassurance supply mismatches following four-page washing sequence.',True)
for page,key in [(27,'R09_suds'),(28,'R10_jump'),(29,'R11_land')]:
 job('ceiling'+str(page),page,[src(key)], 'Source-preserving upward outpaint of IMAGE_1 to exact7:5landscape. Entire existing flattened 16:9scene is anchoredatBOTTOM withoutcrop/scale distortion/redraw. Add ONLY missing upper~21%roomceiling above existing scene, continuous perspective vanishinglines and samelavenderlargebrickpaint. New top ceiling quieter/lowercontrast for white nativecaption, no addedlights/windows/objects/text. ONE uninterrupted vaultedroom, no duplicate horizontalstrip/seam. ALL originalcharacters, action, props, water/dust and staging unchanged. Output complete7:5 but only newceilingregion willbe used with unchanged native scene pixelsbelow. Crispnativepaintingsame resolution, no noise.', 'Current ceiling strips are visibly blurred/stretched and join abruptly.')
job('nap32',32,[src('bubble_nap'),bunny], 'Targeted inpaint IMAGE_1 ONLY the TWO tiny sleeping lavender bunnies at bottomLEFT/right. Restore canonical foreheadcurl, two spiralearshapes/pearlknobattachment from IMAGE_2 while eyes stayclosed peacefully; cloudbodies, nofur/legs, retain exactsleepingpositions,size and partialbubbleocclusion. Main napfamily, rainbowPuff, allbubbles, lighting, furniture, ceiling and composition untouched. No fullsceneredraw or text.', 'Sleeping littlebunny curled-ear/forehead topology drift.')
save(V/'generation_jobs.json',jobs)
impact=dict(id='picture-book-v29-polish-20260930',scope='Comprehensive static-book quality iteration, language proofread, bounded character/scene repairs, event-specific banks and two recognizable unprompted Lamma peeks. No game/runtime/protected-original change.',baseline='5da33b22c9b95358d98defe8e340a901d5470991',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-06','DL-ASSET-08'],findings=[],no_findings_reason='Scoped static picture-book polish; game-wide findings remain unchanged and no closure is claimed.',files=['books/chapter_one/landscape/revisions/v29_polish/prepare_revision.py','books/chapter_one/landscape/revisions/v29_polish/generation_jobs.json','books/chapter_one/landscape/revisions/v29_polish/BOOK_BASELINE.json'],validation=[dict(command='Independent whole-book language, character and original-style baseline audit; source-preserving generation review and complete PDF re-render',result='PENDING',evidence='books/chapter_one/landscape/revisions/v29_polish/')],acceptance_gaps='Target4.9/5 craft-quality goal; no automatic master-audit satisfaction. Actual SLP, owner, child and print proof acceptance remain pending; currentnativeart resolution verified honestly.')
save(R/'design/audit_impacts/picture-book-polish-v29-20260930.json',impact)
print(len(jobs),'targeted jobs')
