from pathlib import Path
import datetime,html,json,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
root=r/'audit/day_two_wash_complete_action_v1_20261001'
p=root/'KEY_BOARD_REGISTER_V2.json';d=json.loads(p.read_text())
assert len(d['boards'])==20
for row in d['boards']:row['direct_visual_review']='DIRECT_SELECTED_KEYS'
d['directly_reviewed_selected_native_keys']=sum(len(x['ticks']) for x in d['boards'])
d['every_native_frame_directly_reviewed']=False
p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
p=root/'REVIEW.json';review=json.loads(p.read_text())
review['status']='PARTIAL_SELECTED_SEQUENCE_REVIEW'
review['checked_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat()
review['direct_selected_boards']=20;review['direct_selected_keys']=d['directly_reviewed_selected_native_keys'];review['every_native_frame_directly_reviewed']=False
for case in review['cases']:
    doctor=case['career']=='doctor'
    case.update(draw_subject_score=2.9 if doctor else 2.2,acting_score=2.7 if doctor else 2.8,completion_score=2.5,context_score=2.8 if doctor else 2.4,direct_review='DIRECT_SELECTED_WORK_POSES_AND_BOUNDARIES',sampled_workflow_score=2.7 if doctor else 2.2,complete_action_score=None,contact_after_approach_score=None)
    case['evaluation']=('The bowl, tall faucet and detached circular hands have the visual finish of a flat control diagram, while the room uses painted storybook materials. Roshan holds the same hand-at-face doctor work cell throughout the sampled hold; it does not show washing. Rings and pearls accumulate, then the marked pink bop puff and unrelated cheer replace the intended clean-hand consequence. The panel clears when FIND arms. Actor placement in this direct-open fixture is not evidence about arrival/contact in the normal route.' if doctor else 'The wash subject is absent: the selected views show the dark activity bloom, circle cue and progress pearls without a basin or hands. The work row cycles soap, bottle and other care poses, so the held verb changes visually while the phase remains WASH HANDS. The marked pink bop puff is unrelated to washing. The panel clears when CATCH BABIES arms and a baby preview appears. These selected boundaries do not establish the full catch action or ordinary approach/contact.')
    case['refinement']=('Reuse the painted shell sink and fresh foam only after their native contact/scale fit is demonstrated. The approved doctor work row lacks an intact connected washing pose; add only that named source gap. Replace washing-specific draw/contact/settle and completion effects, preserving intentional input and progression.' if doctor else 'Test the approved work-row soap-in-hands cell0 with an existing painted sink. Keep bottle/towel poses out of washing. Fix the draw dispatch and literal contact; a decorative ring or stronger foam sprite does not replace visible hands washing. Keep complete motion and approach acceptance pending.')
review['individual_priorities']=[
    {'id':'WASH-DOCTOR-SURFACE-01','score':2.9,'lane':'drawn subject/context','source':'scripts/opera_gesture_surface.gd','evaluation':'Flat faucet, oval basin and detached round hands mismatch the painted room; no convincing connected washing subject.'},
    {'id':'WASH-NURSERY-SURFACE-01','score':2.2,'lane':'drawn subject/context','source':'scripts/opera_gesture_surface.gd','evaluation':'Nursery wash draw is bypassed by the nonempty widget-template return; selected active views contain no basin or washing hands.'},
    {'id':'WASH-DOCTOR-WORK-POSE-01','score':2.7,'lane':'washing meaning; source art score separate','source':'assets/opera/worlds/actors/animation/roshan_doctor_sheet_a.png','region':[256,512,256,256],'evaluation':'Pinned work1 brings a hand/tool to the face; it cannot demonstrate hands washing. Do not claim that doctor cycles all medical tools.'},
    {'id':'WASH-NURSERY-WORK-POSE-01','score':2.8,'lane':'washing meaning; source art score separate','source':'assets/opera/worlds/actors/animation/roshan_nursery_sheet_a.png','regions':[[0,512,256,256],[256,512,256,256],[512,512,256,256],[768,512,256,256]],'evaluation':'All four work cells occur during WASH HANDS, including bottle and care gestures. Only soap cell0 is the initial reuse candidate; it is a pose key, not a proven chronological wash loop.'},
    {'id':'WASH-COMPLETION-PUFF-01','score':2.5,'lane':'source and washing context','source':'assets/opera/worlds/props/fx_bop_puff.png','evaluation':'Pink dust/bop cloud includes visible square marks and explains no clean-hand consequence. Boxing puff reuse does not confer washing acceptance.'},
    {'id':'WASH-PROGRESS-PEARLS-01','score':3.5,'lane':'washing consequence/readability','source':'scripts/opera_career_world_2d.gd','evaluation':'The small generic pearl row accumulates without corresponding visible hand cleaning. Keep a literal local soap/rinse result as the primary progress cue.'}
]
p.write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
p=root/'index.html';s=p.read_text(encoding='utf-8')
s=s.replace('Machine capture succeeded; direct sequence evaluation is pending.', 'Machine capture succeeded. All 20 selected boards (104 native keys) were directly evaluated; the remaining native frames and complete ordinary actions remain unreviewed.')
assert d['directly_reviewed_selected_native_keys']==104
s=s.replace(' · visual review pending',' · directly reviewed selected keys')
table='<section><h2>Individual priorities</h2><p>Draft scores for the selected washing views; source-art identity, actual approach/contact and complete-action acceptance stay separate.</p><table><thead><tr><th>Item</th><th>Score /5</th><th>Evaluation</th></tr></thead><tbody>'
for row in review['individual_priorities']:table+='<tr><td>'+html.escape(row['id'])+'</td><td>'+str(row['score'])+'</td><td>'+html.escape(row['evaluation'])+'</td></tr>'
table+='</tbody></table><p>Doctor sampled workflow: 2.7. Nursery sampled workflow: 2.2. Neither is a complete-action pass. Ordinary launch, approach/contact, natural wall-clock timing, phone, child and owner acceptance remain pending.</p></section>'
s=s.replace('<section><h2>Every native frame</h2>',table+'<section><h2>Every native frame</h2>')
s=s.replace('.note{','table{width:100%;border-collapse:collapse}td,th{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #dde4ed}td:first-child{overflow-wrap:anywhere}.note{')
p.write_text(s,encoding='utf-8')
shutil.copyfile(Path(__file__),root/'executed_finalize_selected_wash_review_v3.py')
p=r/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8').replace('selected-board/direct complete evaluation pending. Direct task opening bypasses approach;', '20 selected boards/104 keys directly reviewed: doctor draw2.9/work2.7, nursery draw2.2/work2.8 and washing puff2.5 remain priorities. Every native frame/complete ordinary action remains unreviewed. Direct task opening bypasses approach;');p.write_text(s,encoding='utf-8')
p=r/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');needle='## 0. Planning entry\n';entry='\nWashing sequence supplement (2026-10-01): [eight unchanged-art local hold fixtures](day_two_wash_complete_action_v1_20261001/index.html) retain all1520 native frames and the first runtime fixture failure. All20 selected boards/104 keys directly evaluated show doctor surface2.9/work meaning2.7, nursery missing subject2.2/work meaning2.8 and shared marked washing puff2.5. Every frame, natural timing, ordinary approach/root routes and phone/child/owner acceptance remain separate. Existing painted sink/soap-pose reuse and the named missing doctor wash pose are the next bounded refinements. [Impact](../design/audit_impacts/job-review-separate-v2-20261001.json). No finding closure.\n';assert 'Washing sequence supplement' not in s;s=s.replace(needle,needle+entry,1);s=s.replace('1140 source files, 240 pose cells and6 current pool prop regions (1386 addressable entries). 481 source opinions','1143 source files, 240 pose cells and6 current pool prop regions (1389 addressable entries). 482 source opinions');p.write_text(s,encoding='utf-8')
p=r/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=p.read_text(encoding='utf-8');start=s.index('## MA-VIS-006\n');end=s.find('\n## ',start+1);part=s[start:end];hist=[x for x in part.splitlines() if x.startswith('| history |')];assert len(hist)==1;old=hist[0];extra=' 2026-10-01: [Washing hold evidence](../day_two_wash_complete_action_v1_20261001/index.html) preserves1520 native frames; only20 selected boards/104 keys directly reviewed. Doctor draw2.9/work2.7, nursery skipped subject2.2/work2.8 and marked completion puff2.5 remain individual priorities; complete ordinary action/approach and external acceptance remain pending. No lifecycle closure.';part=part.replace(old,old[:-2]+extra+' |');s=s[:start]+part+s[end:];p.write_text(s,encoding='utf-8')
p=r/'audit/job_review_v2_20261001/index.html';s=p.read_text(encoding='utf-8').replace('</main>', '<p><a href="../day_two_wash_complete_action_v1_20261001/index.html">Eight washing sequences: every native frame and six individual priorities</a> · 1,520 captured frames; 104 selected keys directly reviewed; complete route and owner acceptance pending.</p></main>');p.write_text(s,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in root.rglob('*') if x.is_file()]));d['validation'].append({'command':'Direct review of20 selected washing boards/104 keys','result':'PENDING','evidence':'audit/day_two_wash_complete_action_v1_20261001/REVIEW.json; named draw/pose/puff/pearl opinions below4.5. Selected review complete; every1520-frame and complete route/action acceptance remains open. No partial visual result relabeled PASS.'});p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
print('Recorded six individual washing priorities and direct20-board/104-key review; complete acceptance remains pending.')
