from pathlib import Path
from PIL import Image
import datetime,hashlib,html,json,posixpath,shutil
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');f=r/'audit/job_wash_root_doctor_sequence_v1_20261002';old=r/'audit/day_two_wash_complete_action_v1_20261001/root_route_attempt_03';prefix=f.relative_to(r).as_posix()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();m=read(f/'BOARD_MANIFEST.json');assert len(m['frames'])==256 and len(m['boards'])==22
for b in m['boards']:assert sha(r/b['path'])==b['sha256'];b['direct_review']=True;b['reviewed_utc']=now
for x in m['frames']:
 assert sha(r/x['path'])==x['sha256'];x['direct_review']=True;x['reviewed_utc']=now;x['owner_acceptance']=None
 i=x['capture_index']
 if i<17:lane='passive start';note='The Doctor character and medical playset are visible; the invitation pulses without wash progress.'
 elif i<32:lane='input-requested approach';note='Roshan travels toward the left medical invitation. This arrival does not establish basin contact; the later wash widget is far to the right.'
 elif i<50:lane='hotspot opening';note='The invitation opens after approach, while the actor remains at the left medical doorway. No washing or progress is shown yet.'
 elif i<67:lane='wash opened, before hold';note='The independent basin widget fades into the right side over other furniture. Peach hand symbols and a faucet shape appear, but no embodied subject reaches them.'
 elif i<175:lane='intentional held wash';note='The held interaction advances progress while white loops grow around the flat basin. Roshan remains far left; the peach hand symbols do not form a readable palm-rubbing and rinse action.'
 elif i<242:lane='earned feedback and wait';note='A brief pink puff and cheerful body pose acknowledge completion. The basin then remains with loop graphics; no matched clean hands or visible rinse resolves the washing action.'
 else:lane='next FIND phase armed';note='The wash widget disappears and a new left-side medical target is armed. This is a phase advance inside the activity, not completion of the entire Doctor career or a room return.'
 x['review_lane']=lane;x['evaluation']=note
 x['scores']={'complete_wash_workflow':2.7,'actor_contact_spatial_relation':2.3,'washing_subject_rub_and_rinse':2.2,'basin_artwork':2.9}
m['status']='EVERY256_PRESERVED_FRAMES_DIRECTLY_REVIEWED';m['reviewed_utc']=now;write(f/'BOARD_MANIFEST.json',m)
objects=[
 ('DOC-WASH-BASIN','Basin and faucet artwork',2.9,'The flat cyan ellipse, plum rim and yellow faucet are readable as a symbol but clash with the authored painted room. They remain an independent interface object rather than a supported physical sink.','Use the already reviewed painted basin family where it fits; preserve the original and require actual mounted contact.'),
 ('DOC-WASH-HANDS','Peach hand symbols and missing embodied wash subject',2.2,'Two peach discs and short wrist shapes sit inside the basin. No fingers, connected arms, palm surfaces or clean ending make the actual washing subject legible.','Bind an authored reaching/rubbing/rinsing subject with a coherent body connection, not bubbles alone.'),
 ('DOC-WASH-RUB','Rubbing and rinse graphics',2.3,'Growing white loops communicate activity, but the sequence does not show palms moving against each other, dirt being removed, or a water stream rinsing them.','Audit separate reach, rub, water-on rinse and quiet clean rest states.'),
 ('DOC-WASH-CONTACT','Roshan-to-basin contact',2.3,'Roshan arrives at the left invitation while the working basin stays far to the right. Her work pose does not reach the visible basin or the peach symbols.','Stage her at the actual work surface and synchronize hand/tool contact before progress.'),
 ('DOC-WASH-SPACE','Work popup placement in the room',2.3,'The translucent wash overlay covers right-side seats and a garden nook, far from the medical doorway Roshan approached. The object and its invitation do not share a readable place.','Give the task one honest physical location and one coordinate transform at both widths.'),
 ('DOC-WASH-OVAL','Dark translucent oval behind the widget',3.2,'The oval makes the small symbol visible, but darkens unrelated seats and garden furniture without forming a physical work area.','Use restrained local contrast around the supported basin and connected subject.'),
 ('DOC-WASH-PIPS','Progress pip row',4.0,'Warm dots fill along a clear row; they acknowledge the held action but appear separately over the garden rather than beside the physical washing surface.','Keep readable progress feedback near the actual working object and avoid taking over the scene.'),
 ('DOC-WASH-PUFF','Pink completion puff',3.2,'The brief pink cloud sits inside the basin and looks like a generic impact/reward effect. It does not reveal visibly cleaned hands or establish a finished rinse.','Use a specific clean resting state and quiet completion feedback; preserve the dated puff.'),
 ('DOC-WASH-ACTING','Roshan work and cheer acting',3.8,'The cheerful authored pose is clear and friendly. Work-to-cheer remains remote from the basin and replaces the missing rub/rinse action with a pose switch.','Retain character identity, add actual authored contact, then polish the work-to-rest transition.'),
 ('DOC-WASH-NEXT','Wash-to-FIND transition',3.2,'The wash popup closes and the next starfish target appears normally. The washing subject has no matched clean rest or local departure before that advance.','Show the completed clean state before returning attention to the next physical target.'),
 ('DOC-WASH-PLAYSET','Painted medical playset material in this capture',4.6,'Rounded shell seating, aqua water and warm stone read as an authored pastel medical playset. This narrow material opinion does not individually approve every baked background object or its native resolution.','Retain provisionally; assess actual task hierarchy and native coverage separately.'),
 ('DOC-WASH-WORKFLOW','Complete captured washing workflow',2.7,'Approach and input routing work, but the child sees a remote symbol instead of connected hands reaching, rubbing, rinsing and resting clean. Every captured frame confirms the same logical gap.','Repair connected subject/contact and the full washing sequence before granting a 4.5 whole-action opinion.')]
opinions=[dict(id=id,name=name,score=score,evaluation=note,refinement=refine,priority=score<=4.5,owner_acceptance=None) for id,name,score,note,refine in objects]
indices=[0,51,80,145,176,210,243,255];details=[dict(path=m['frames'][i]['path'],sha256=m['frames'][i]['sha256'],frame=i,direct_review=True) for i in indices]
profile=read(old/'PROFILE.json');checks=[]
for p,h in profile['source_before'].items():
 file=r/p;cur=sha(file) if file.is_file() else None;checks.append(dict(path=p,capture_sha256=h,current_sha256=cur,match=cur==h))
write(f/'HISTORICAL_CAPTURE_SOURCE_FRESHNESS.json',dict(status='HISTORICAL_CAPTURE_SOURCE_BOUNDARY_COMPARED',checked_utc=now,source_count=len(checks),matched=sum(x['match'] for x in checks),changed_or_unavailable=[x for x in checks if not x['match']],qualification='Captured2026-10-01 sources stay authoritative for these preserved images. Whole-source differences cannot be assumed irrelevant to Doctor; this is a fresh visual review of dated capture, not a new current capture or runtime acceptance.'))
facts={'first_interaction_request':17,'first_hotspot_opening':32,'first_task_open':50,'opened_event_label':51,'first_surface_held':67,'first_surface_complete':175,'completion_event_label':176,'first_next_phase':242,'next_phase_event_label':243}
review=dict(status='EVERY256_DOCTOR_TRAINING_FRAMES_REVIEWED_WASHING_WEAK',reviewed_utc=now,baseline=profile['baseline'],publication_baseline='c8f88df058434f1fd1b6d7fade712677003c641a',case=m['case'],frames=m['frames'],boards=m['boards'],native_details=details,individual_objects=opinions,transition_facts=facts,counts=dict(frames=256,complete_boards=22,native_details=8,individual_opinions=12,remaining_other_captured_case_frames=1818,prior_four_selected_frames=4,new_additional_directly_reviewed_frames=252),source_freshness='HISTORICAL_CAPTURE_SOURCE_FRESHNESS.json',owner_acceptance=None,qualification='All256 frames directly inspected on22 complete whole-canvas boards plus eight full native details. The earlier four-frame opinion is preserved; no generated, interpolated or substituted frames. Event labels trail first actual boolean states by one frame at opening/completion/advance; both are recorded. Actual hotspot/held-input route uses the established training/birthday catalog fixture, not ordinary MainMenu story entry. This is one complete preserved training WASH phase, not the entire Doctor career, all eight cases, current game/device/child/owner acceptance or a new repair. Other seven cases total1818frames and remain independently unreviewed. Source and motion studies remain unbound; no production/art changes.')
write(f/'REVIEW.json',review)
write(f/'REQUIRED_UNCHANGED_REFERENCES.json',dict(schema='reef.unchanged-review-references.v1',baseline=review['publication_baseline'],files={x['path']:[(r/x['path']).stat().st_size,x['sha256']] for x in m['frames']},qualification='Previously tracked unchanged binary native frames, required by this illustrated report. Verify current immutable remote revision anonymously as well as new payload; no duplicate native copies.'))
esc=html.escape;url=lambda p:posixpath.relpath(p,prefix)
def figure(p,caption):
 with Image.open(r/p) as im:w,h=im.size
 return f'<figure><a href="{esc(url(p))}"><img loading="lazy" width="{w}" height="{h}" src="{esc(url(p))}" alt="{esc(caption)}"></a><figcaption>{esc(caption)}</figcaption></figure>'
css='body{background:#eef4f9;color:#26374d;margin:0;font:17px/1.6 system-ui}main{max-width:1220px;margin:auto;padding:24px}section,article,details{background:white;padding:22px;margin:22px 0;border:1px solid #ccd8e4;border-radius:18px}h1,h2,h3{color:#49347b;line-height:1.25}a{color:#49347b}figure{margin:18px 0;background:#f1f7fb}img{display:block;width:100%;height:auto}figcaption{padding:12px;overflow-wrap:anywhere}.weak{border-left:6px solid #ba7848}code{overflow-wrap:anywhere}summary{cursor:pointer;font-weight:650}'
parts=[f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Doctor washing · every preserved training frame</title><style>{css}</style><main><h1>Doctor washing: every preserved training frame</h1><p>All 256 consecutive frames of the 1280-pixel Opera training WASH route are now directly reviewed, including approach, actual hotspot opening, held washing, completion feedback and the next FIND phase. The earlier four selected frames remain preserved.</p><p>Complete workflow <strong>2.7/5</strong>; spatial contact <strong>2.3/5</strong>; embodied washing subject <strong>2.2/5</strong>; basin artwork <strong>2.9/5</strong>. These are first-pass opinions, with every score at or below 4.5 still a priority.</p><p>This is a fresh review of the preserved October 1 capture, not a new current capture. Other seven cases contain 1,818 frames and remain separately unreviewed. The fixture initializes catalog state before real touch input; it does not establish a natural MainMenu story launch, device timing, final owner approval or a completed washing repair.</p><nav><a href="../job_artwork_refinement_live/index.html">All-jobs review entry</a> · <a href="../day_two_wash_complete_action_v1_20261001/root_route_attempt_03/index.html">Earlier four-frame review and all eight cases</a> · <a href="REVIEW.json">Every frame, scores and event facts</a> · <a href="HISTORICAL_CAPTURE_SOURCE_FRESHNESS.json">Dated source/current comparison</a></nav><section><h2>The missing logical action</h2><p>Roshan travels to the left medical doorway while an independent flat basin opens far to the right. Peach hand symbols and growing white loops appear in the basin. Her body never reaches them, the symbols do not visibly rub or rinse, and completion feedback does not reveal a matched clean subject. Clear input routing does not supply the missing contact.</p>']
for x in details:parts.append(figure(x['path'],f'Native frame {x["frame"]}: '+m['frames'][x['frame']]['evaluation']))
parts.append('</section><section><h2>Twelve individual objects and relationships</h2>')
for x in opinions:parts.append(f'<article class="{"weak" if x["priority"] else "good"}" id="{x["id"]}"><h3>{esc(x["name"])} · {x["score"]}/5</h3><p>{esc(x["evaluation"])}</p><p>Next refinement: {esc(x["refinement"])}</p></article>')
parts.append('</section><section><h2>All 22 complete ordered boards</h2><p>Read each board left to right, top to bottom. Every captured canvas appears exactly once; the last board has four real frames and eight blank cells. Whole-canvas normalization is for report display only. The native originals stay unchanged.</p>')
for b in m['boards']:parts.append(figure(b['path'],f'Frames {b["first_frame"]}–{b["last_frame"]}: every{b["count"]} frame directly inspected.'))
parts.append('<details><summary>Every native frame and its recorded evaluation</summary>')
for x in m['frames']:parts.append(f'<p><a href="{esc(url(x["path"]))}">Frame {x["capture_index"]:04d}</a> · {esc(x["review_lane"])} · {esc(x["evaluation"])}</p>')
parts.append('</details></section><section><h2>Actual states and event labels</h2><p>First actual task-open state:50; opened-event label:51. First held-input state:67. First completed surface:175; completion-event label:176. First FIND phase:242; next-phase-event label:243. These differences are preserved rather than treating the labels as exact first visual transitions.</p><p>Other cases, actual target-device use, ordinary story launch, child/owner acceptance, current-source rerender and the full reach–rub–rinse–rest action remain open. No source files, mechanics, save keys, rewards or tests changed.</p></section></main></html>')
(f/'index.html').write_text(''.join(parts),encoding='utf-8',newline='\n')
p=f/'PLAN.json';d=read(p);d['status']='EVERY256_PRESERVED_FRAMES_DIRECT_REVIEW_COMPLETE_WEAK_ACTION';d['review']='REVIEW.json';write(p,d)
shutil.copyfile(Path(__file__),f/'review_tools'/Path(__file__).name)
note='Doctor wash review continuation (2026-10-02): [every256 preserved1280px training WASH frames on22 complete boards, eight native details and12 individual opinions](job_wash_root_doctor_sequence_v1_20261002/index.html) directly inspected. Earlier four-frame opinion stays historical;252 additional frames now reviewed. Workflow2.7/contact2.3/embodied subject2.2/basin2.9 remain weak. Actual states open50/complete175/next phase242 are separated from later event labels51/176/243. This is a fresh review of the datedOctober1 input-driven catalog fixture, not current capture, natural story/device/child/owner acceptance or a repair. Other seven cases1818frames remain independently unreviewed; findings stay open.'
for rel in ['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md']:
 p=r/rel;s=p.read_text(encoding='utf-8');n=note.replace('](job_wash_','](../job_wash_') if '/findings/' in rel else note;s=s.replace('\n\n','\n\n'+n+'\n\n',1);p.write_text(s,encoding='utf-8',newline='\n')
ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');s+='\n| `'+prefix+'/index.html` | 🔵 | `SUPPORTING_CURRENT` direct review of all256 preservedOctober1 Doctor1280 training WASH frames/22 complete boards/eight native details/12 named object-context opinions. Workflow2.7/contact2.3/subject2.2/basin2.9 remain weak; event labels and first actual states separated. Dated capture/source freshness qualified; other1818 case frames and current/story/device/child/owner acceptance remain open. No runtime/art or finding-lifecycle change. |\n';ledger.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/job_artwork_refinement_live/index.html';s=p.read_text(encoding='utf-8');i=s.index('</h1>')+len('</h1>');s=s[:i]+'<p><a href="../job_wash_root_doctor_sequence_v1_20261002/index.html">Doctor washing: all256 preserved training frames now reviewed</a> — workflow2.7/contact2.3/subject2.2/basin2.9 remain weak; other1818 frames, current capture and owner acceptance remain open.</p>'+s[i:];p.write_text(s,encoding='utf-8',newline='\n')
ip=r/'design/audit_impacts/job-wash-root-doctor-sequence-review-20261002.json';d=read(ip);d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in f.rglob('*') if p.is_file()}|{'audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md','audit/job_artwork_refinement_live/index.html'});d['validation']=[dict(command='Direct every256 preserved Doctor training WASH frame review',result='PASS',evidence=prefix+'/REVIEW.json; review complete, graphics/action below4.5 remain explicit.')];d['acceptance_gaps']=review['qualification'];write(ip,d)
allow=r/'tmp/v2_preview_allowed.json';write(allow,sorted(set(read(allow))|set(d['files'])))
print('Every256 preserved Doctor frames/22boards/eight details reviewed;12 opinions recorded.252 newly reviewed,1818 other-case frames remain.')
