"""Show actual recto/verso pairs without changing the 34 authored book pages."""
from pathlib import Path
import html,json,hashlib
V=Path(__file__).resolve().parent
def img(n):return f'<img src="complete/page_{n:02}.png" alt="'+('Front cover' if n==0 else 'Rear cover' if n==33 else f'Story page {n}')+'">'
def page(n):return '<figure>'+img(n)+f'<figcaption>Story {n} · '+('right / recto' if n%2 else 'left / verso')+'</figcaption></figure>'
blank='<figure class="blank"><div>Unprinted inside cover</div></figure>'
rows=['<section class="single"><h2>Front cover · exterior</h2>'+img(0)+'</section>','<section><h2>Opening</h2><div class="spread">'+blank+page(1)+'</div></section>']
for n in range(2,32,2):
 rows.append(f'<section id="spread-{n}"><h2>Story {n}–{n+1}</h2><div class="spread">'+page(n)+page(n+1)+'</div></section>')
rows+=['<section><h2>Ending</h2><div class="spread">'+page(32)+blank+'</div></section>','<section class="single"><h2>Rear cover · exterior</h2>'+img(33)+'</section>']
doc='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mermaid Roshan · bound spread dummy</title><style>body{margin:0;background:#173449;color:#eef9ff;font:18px/1.5 system-ui}header,main{max-width:1500px;margin:auto;padding:24px}section{margin-bottom:40px}.spread{display:grid;grid-template-columns:1fr 1fr;gap:0;border:2px solid #496a80}figure{margin:0}img{width:100%;display:block}figcaption{padding:8px 14px;background:#294b64}.blank{display:flex;align-items:center;justify-content:center;background:#e8edf0;color:#657480;min-height:260px}.single{max-width:750px;margin:30px auto}a{color:#a9e5ff}.note{background:#294b64;padding:20px;border-radius:12px}</style><header><h1>Bound spread dummy</h1><p>34 authored pages: front cover,32 story pages,rear cover.7×5 inches landscape. This preview shows intended binding positions; it does not impose printer sheets.</p><p class="note">Give the printer the front/rear art as exterior covers and PDF positions2–33 as the32-page interior. Keep story1 on a right-hand page. Leave inside covers unprinted; these are physical cover surfaces, not added story pages. Do not duplex the cover-inclusive PDF as a simple loose stack. Printer-specific spine, bleed, stock, color and imposition require a physical proof.</p><p>Story23 ends on the right with the glowing door; turning it reveals Puff on24. Story27 ends on the right with bubbles; turning it reveals rainbow Puff on28. No story art crosses a gutter. Read at100% to check type size; this screen preview cannot certify paper/color or binding.</p><p><a href="AUDIT_REVIEW.html">Before/after audit</a> · <a href="complete/READ_BOOK.html">Reader</a> · <a href="SLP_REVIEW_PACKET.html">Language packet</a></p></header><main>'''+''.join(rows)+'</main></html>'
(V/'PRINT_DUMMY.html').write_text(doc,encoding='utf-8',newline='\n')
proof=V/'complete/Mermaid_Roshan_LANDSCAPE_ROUGH.pdf'
e={'pdf_sha256':hashlib.sha256(proof.read_bytes()).hexdigest(),'authored_pages':34,'interior_pdf_positions_one_based':[2,33],'interior_story_pages':32,'first_story_side':'right / recto','exterior_cover_pdf_positions_one_based':[1,34],'unprinted_inside_cover_surfaces':2,'reveals':[{'setup_story_page':23,'setup_side':'right','reveal_story_page':24,'reveal_side':'left'},{'setup_story_page':27,'setup_side':'right','reveal_story_page':28,'reveal_side':'left'}],'physical_print_acceptance':'OPEN; printer trim/bleed/spine/color/stock/density and bound dummy not certified.'}
(V/'print_pagination.json').write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8',newline='\n')
print('Wrote exact recto/verso spread dummy and print pagination.')
