from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
r=Path(__file__).resolve().parents[1]
audit=r/'audit/day_two_wash_bubble_reuse_v1_20261001'
art=r/'assets_src/imagegen/day2_wash_foam_v1_20261001'
assert not audit.exists() and not art.exists();audit.mkdir();art.mkdir()
(audit/'.gdignore').write_text('');(art/'.gdignore').write_text('')
for name in ['PROFILE.json','PROCESS_RECEIPT.json','parser.stdout.log','parser.stderr.log','inference.stdout.log','inference.stderr.log','analyzer.stdout.log','analyzer.stderr.log','native.stdout.log','native.stderr.log']:
    shutil.copyfile(r/'tmp/wash_bubble_reuse_v1'/name,audit/name)
shutil.copytree(r/'tmp/wash_bubble_reuse_v1/native_views',audit/'native_views')
shutil.copyfile(r/'tmp/capture_wash_bubble_reuse_v1.gd',audit/'executed_capture_wash_bubble_reuse_v1.gd')
shutil.copyfile(Path(__file__),audit/'prepare_wash_foam_candidate_v1.py')
shutil.copyfile(r/'tmp/run_wash_bubble_reuse_v1.py',audit/'executed_run_wash_bubble_reuse_v1.py')
direct=['doctor_1280_original.webp','doctor_1280_cell0_131.webp','doctor_1280_cell2_131.webp','doctor_1280_cell2_180.webp','doctor_1280_original_activity_initial.webp','nursery_1280_original.webp','nursery_1280_cell0_131.webp','nursery_1280_cell2_131.webp','nursery_1280_cell2_180.webp','nursery_1280_original_activity_initial.webp']
receipt=json.loads((audit/'native_views/CAPTURE_RECEIPT.json').read_text())
items=[]
for row in receipt['views']:
    reviewed=row['path'] in direct
    score=None;evaluation='Captured; this full native view has not yet been directly visually reviewed.'
    if reviewed:
        if 'original_activity' in row['path']:
            score=2.2 if row['career']=='nursery' else 2.9
            evaluation='Empty target circle in the actual nursery WASH HANDS activity; neither basin nor washing hands are drawn. Nonempty nursery widget template returns before the dedicated nursery_wash helper.' if row['career']=='nursery' else 'The literal sink/faucet/hands communicate the subject, but schematic circles and lines conflict with the detailed painted room; the separate action focus floats on the right while Roshan stays away. Initial mounted view only; complete washing action is unreviewed.'
        elif row['atlas_cell']<0:
            score=3.0
            evaluation='Broken concentric rings read as a diagram rather than painted soap. The doctor invitation is attached to the stethoscope, away from the painted shell basin.' if row['career']=='doctor' else 'Peach concentric rings and large blue halo float beside Roshan, with no literal soap/basin subject at that position.'
        else:
            score=4.0 if row['career']=='doctor' else 3.7
            evaluation='Cleaner literal bubbles, but ink-heavy glossy blue water-burst design remains below the source style target. Doctor placement still indicates the stethoscope instead of the wash basin.' if row['career']=='doctor' else 'Cleaner literal bubbles, but glossy blue attack-effect styling remains below the source target; floating bubbles beside Roshan do not establish a basin or washing hands.'
            if row['atlas_cell']==0:evaluation+=' The small initial cluster is especially weak at the131px canvas size.'
    items.append({'path':'native_views/'+row['path'],'sha256':row['sha256'],'career':row['career'],'variant':row['path'],'direct_full_native_review':reviewed,'initial_mounted_score':score,'complete_action_score':None,'evaluation':evaluation})
review={'schema':'reef.wash-source-reuse-review.v1','baseline':'8e41deaf34f925869395cd8ab0affefe89f89ab5','status':'REUSE_BELOW_TARGET_AND_DRAW_ROUTE_PRIORITIES_OPEN','reviewed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'captured_views':20,'direct_full_native_views':10,'remaining_full_native_views_unreviewed':10,'items':items,'source_reviews':[{'path':'assets/sprites/fx_water/fx_water_bubble_burst_atlas.png','sha256':hashlib.sha256((r/'assets/sprites/fx_water/fx_water_bubble_burst_atlas.png').read_bytes()).hexdigest(),'whole_atlas_source_score':4.1,'cell0_source_score':4.4,'cell2_source_score':4.4,'evaluation':'Cells0 and2 have readable, clean circles and restrained highlights; their heavy blue/navy rims and glossy water treatment are a poor match for a soft painted soap cluster. Later cells also contain irregular bright sparkle fringes. Entire atlas and the cell0/cell2 mounted variants directly viewed; individual later cell scores remain unreviewed.'}], 'priorities':[{'id':'WASH-DOCTOR-ANCHOR-01','score':3.0,'evidence':'native_views/doctor_1280_original.webp','issue':'Wash invitation center336.31,217.30 is over the stethoscope. The visible shell wash basin is a separate painted object farther right.'},{'id':'WASH-NURSERY-DRAW-01','score':2.2,'evidence':'native_views/nursery_1280_original_activity_initial.webp','issue':'WASH HANDS uses visual_context nursery_wash with widget_template nursery; generic widget branch returns before the dedicated nursery context helper, leaving a circular cue without a washing subject.'},{'id':'WASH-DOCTOR-SUBJECT-01','score':2.9,'evidence':'native_views/doctor_1280_original_activity_initial.webp','issue':'Drawn sink/hands/faucet are schematic, and the action view is remote from Roshan. Source restyle alone cannot prove connected washing acting.'}],'generation_gap':'Existing wide ring art3.0 and tested bubble-burst reuse source cells4.4 fail the individual4.5 style target. Generate only a clean matte painted soap-foam cluster, fresh text-only, preserving originals. Placement, draw dispatch, hands, contact and complete action remain separate repairs.','acceptance':'Draft opinions only. No source reuse selected for runtime, no complete action accepted, and no phone/child/owner/global acceptance.'}
(audit/'REVIEW.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
prompt='''Use case: illustration-story
Asset type: transparent 2D soap-foam cutout for a preschool mermaid storybook game.
Primary request: create ONE freshly drawn, polished, compact cluster of clean soap foam and a few round soap bubbles, suitable for a washing-hands activity. A low, wide, scalloped foam cushion made from five or six overlapping rounded lobes, with three small airy bubbles rising just above it. The content silhouette is about1.7 times wider than tall and remains clear at80 pixels wide.
Style/medium: hand-painted and hand-inked TWO-DIMENSIONAL children's storybook toy-playset art. Rounded friendly forms; thin confident muted navy-purple contours; broad painted value bands; two or three quiet tones per lobe. Matte simplified paint, tiny restrained cream highlight patches, soft aqua and lavender shadows. Soft pastel cream, mint-aqua, pale blue and lavender. An illustration, with no realistic optical reflections or simulated glass.
Composition: centered complete cluster, generous transparent margin on every side, clean isolated alpha, no clipping. A flat front view, not an isometric object. True transparent background.
Constraints: only the foam/bubbles. No sink, tap, hands, character, room, floor, label, letters, border, diagram rings, star sparkles or drop shadow. No photorealism,3D rendering, shiny plastic, gradients that imply realistic spherical volume, glass/refraction, glitter, white fringe, watermark or logo. Keep every bubble circular and each outline clean and continuous.'''
profile={'schema':'reef.fresh-source-generation.v1','baseline':'8e41deaf34f925869395cd8ab0affefe89f89ab5','scope':'Fresh narrow soap-foam source gap only; doctor and nursery old art preserved. No runtime binding or action score.','generation_method':'Built-in image_gen, fresh text-only generation','input_image_bindings':[],'attempt':1,'transparent_background':True,'prompt':prompt,'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'reuse_evidence':'audit/day_two_wash_bubble_reuse_v1_20261001/REVIEW.json','target_source_score':4.5,'selection':'PENDING direct source and native-context review'}
(art/'ATTEMPT_01_PROMPT.json').write_text(json.dumps(profile,indent=2)+'\n',encoding='utf-8')
files=sorted(p.relative_to(r).as_posix() for folder in [audit,art] for p in folder.rglob('*') if p.is_file())
impact={'id':'day-two-wash-bubble-reuse-and-foam-v1-20261001','baseline':'8e41deaf34f925869395cd8ab0affefe89f89ab5','scope':'Audit actual doctor/nursery wash invitation and initial activity artwork in twenty native views, retain ten direct current visual evaluations and ten unreviewed wide views, test approved existing bubble atlas before a narrow fresh matte foam generation. Record misplaced doctor invitation and skipped nursery drawing helper as individual priorities. Preserve every production asset and source; candidates remain unbound.','rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-05','DL-READ-01','DL-INT-02','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-03'],'findings':['MA-VIS-006','MA-PLAY-004'],'files':files,'validation':[{'command':'Existing bubble reuse native fixture parser/inference/Godot analyzer/capture','result':'PASS','evidence':'audit/day_two_wash_bubble_reuse_v1_20261001/PROCESS_RECEIPT.json: all four processes0;329 exact source hashes unchanged,20 full native views.'},{'command':'Direct visual initial mounted/source reuse evaluation','result':'PASS','evidence':'audit/day_two_wash_bubble_reuse_v1_20261001/REVIEW.json: ten direct native views evaluated, existing source cells4.4 fail the style target and mounted priorities remain. PASS means evaluations are recorded, not creative acceptance.'},{'command':'Fresh foam candidate source/native review','result':'PENDING','evidence':'assets_src/imagegen/day2_wash_foam_v1_20261001/ATTEMPT_01_PROMPT.json: generation and evaluation not yet completed.'}],'acceptance_gaps':'Ten wide full native views unreviewed. Complete wash actions, ordinary training/story routes, hand/contact/placement repairs, source/native4.5 selection, device/child/owner/global acceptance pending. No runtime implementation, finding closure, integration or release.'}
(r/'design/audit_impacts/day-two-wash-bubble-reuse-and-foam-v1-20261001.json').write_text(json.dumps(impact,indent=2)+'\n',encoding='utf-8')
print('WASH_REUSE_AND_FRESH_PROMPT_RECORDED|20 captured|10direct|all production bytes preserved',flush=True)
