from pathlib import Path
import json,hashlib,datetime,shutil,html,subprocess
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
packet=b/'assets_src/local_motion/day2_geologist_pan_motion_v1_20261001';out=packet/'attempt_01';retry=b/'assets_src/local_motion/day2_geologist_pan_motion_v2_20261001'
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
ip=b/'design/audit_impacts/job-geologist-panning-local-motion-20261001.json';impact=json.loads(ip.read_text());impact['scope']+=' Directly inspect all41 original reference frames, preserve the failed first motion3.8, and prepare a prompt-only left/right-roll retry with the same source/input/seed/settings/model/workflow. No good source art is regenerated to repair ambiguous action direction.';impact['files']=sorted(set(impact['files'])|{rel(out/'REVIEW.json'),rel(out/'index.html'),rel(packet/'executed_review_retry_v142.py'),'audit/findings/ACTIVE_FINDINGS_2026-08-13.md'});write(ip,impact)
cat=json.loads((out/'FRAME_CATALOG.json').read_text());assert len(cat['native_frames'])==41;rows=[]
for v0 in cat['native_frames']:
 v=dict(v0);i=v['index'];p=packet/v['path'];assert sha(p)==v['sha256']
 if i<=4:phase='entry hold';ev='Identity, full fin, cap and costume remain recognizable; both hands retain the rim. A nearly still held pose is an entry, not proof of panning.';action=None;water=4.5;quality=4.6;body=4.6
 elif i<=9:phase='first intended tilt';ev='Basin/front wall flattens slightly while the grips hold. There is no clearly readable left-side-down/right-side-up roll; faint new pale streaking develops below the near wall.';action=3.4;water=4.2;quality=4.5;body=4.5
 elif i<=20:phase='first tilt / reversal boundary';ev='The flattened basin stays nearly level. A pale water-like streak lies outside the left wall near the hip, weakening containment. No clear signed roll or directional reversal is visible; tail and head drift slightly.';action=3.4;water=3.8;quality=4.5;body=4.4
 elif i<=30:phase='second intended tilt';ev='The bowl is still held almost level with modest water-texture changes. Hands remain connected, but alternating left/right rocking is not legible. The painted identity is retained.';action=3.4;water=4.0;quality=4.5;body=4.5
 else:phase='intended settle';ev='Hands and pan move down/left instead of settling to the entry pose. Head/face also drift; the held-pan connection remains readable. Late pale streaking outside the vessel weakens containment. No clean loop/return is accepted.';action=3.6;water=3.8 if i>=38 else 4.0;quality=4.5;body=4.4
 v.update(visual_review='DIRECT_NATIVE_ORIGINAL_RESOLUTION',reviewed_utc=now,visual_score=min(x for x in [quality,water,body,action] if x is not None),phase=phase,scores=dict(painted_identity=quality,hand_rim_contact=4.6 if i<5 else 4.5,body_stability=body,water_containment=water,intended_action=action,neutral_return=3.6 if i>=31 else None),evaluation=ev,owner_approval=None,runtime_accepted=False);rows.append(v)
qualification='Every41 original896x512 reference frame directly inspected in ordered batches. Scores are drafting opinions, separated by visible identity/contact/phase; no measured angles claimed. Wan reference pixels are not authored ImageGen runtime/cinematic delivery. Source4.6 remains separate; ordinary routes, device/child/owner and full report remain open.'
review=dict(status='ALL41_DIRECTLY_REVIEWED_MOTION_RETRY_REQUIRED',reviewed_utc=now,source_score=4.6,motion_reference_score=3.8,alternating_panning_score=3.4,neutral_return_score=3.6,hand_contact_score=4.5,frames=rows,qualification=qualification,retry='Same source/input/seed/settings/workflow; change action instruction only to explicit roll left/right/neutral.');write(out/'REVIEW.json',review);cat.update(status=review['status'],native_frames=rows,visual_review=rel(out/'REVIEW.json'));write(out/'FRAME_CATALOG.json',cat)
cards=['<article><h2>Frame '+str(v['index'])+' · '+format(v['timestamp_seconds'],'.3f')+'s · '+v['phase']+'</h2><img loading="lazy" src="native_frames/'+Path(v['path']).name+'" alt="Native frame '+str(v['index'])+'"><p>'+html.escape(v['evaluation'])+'</p><p>'+html.escape('; '.join(k.replace('_',' ')+': '+str(s)+'/5' for k,s in v['scores'].items() if s is not None))+'</p><small>SHA256 '+v['sha256']+'</small></article>' for v in rows]
head='<!doctype html><meta charset="utf-8"><style>body{font:18px/1.5 system-ui;color:#302949;background:#eef5f4;max-width:1200px;margin:auto;padding:24px}article{background:white;padding:20px;margin:24px 0}img,video{width:100%;height:auto}small{overflow-wrap:anywhere}</style>'
(out/'index.html').write_text(head+'<title>Panning motion attempt1 — all41 frames</title><h1>First panning motion —3.8/5; retry required</h1><p>Connected grip4.5; alternating rock3.4; neutral return3.6. Source art remains4.6. All41 frames individually inspected and shown below.</p><video controls loop src="native_output.mp4"></video><p>'+html.escape(qualification)+'</p><a href="REVIEW.json">Individual frame scores/hashes</a> · <a href="RENDER_RECEIPT.json">Original native generation receipt</a>'+''.join(cards),encoding='utf-8')
m=json.loads((packet/'MANIFEST.json').read_text());m['output_state']='First native output machine PASS; every41 frames directly reviewed; motion3.8/action3.4/return3.6 fail the4.5 floor. Preserved for comparison; source4.6 unchanged.';m['visual_review']='attempt_01/REVIEW.json';write(packet/'MANIFEST.json',m)
(packet/'index.html').write_text(head+'<h1>Geologist panning motion — local reference</h1><p>First attempt3.8/5: rim contact survives, but alternating rocking and return fail. Every41 native frame is individually scored and displayed. Source4.6 is unchanged.</p><video controls src="attempt_01/native_output.mp4"></video><p><a href="attempt_01/index.html">Every41 frame with written scores</a> · <a href="MANIFEST.json">Exact bindings</a> · <a href="PROFILE.json">Action profile</a> · <a href="../day2_geologist_pan_motion_v2_20261001/index.html">Prompt-only retry</a></p><img src="inputs/geologist_pan_full_source.png" alt="Unchanged full source input"><p>'+html.escape(qualification)+'</p>',encoding='utf-8')
retry.mkdir(exist_ok=False);(retry/'.gdignore').write_text('');(retry/'inputs').mkdir();(retry/'prompts').mkdir();shutil.copytree(packet/'workflows',retry/'workflows');shutil.copyfile(packet/'inputs/geologist_pan_full_source.png',retry/'inputs/geologist_pan_full_source.png')
prompt='''Fixed camera. This exact painted mermaid gently rocks the rigid pan LEFT, RIGHT, then LEVEL, while both hands keep their rim grips. At0.0-0.20s hold the starting pose. At0.20-0.65s roll the pan around its front-to-back centre axis: LEFT rim drops about20pixels, RIGHT rim rises about20pixels, approximately8degrees. Attached elbows and wrists articulate locally to keep both grips. At0.65-1.15s reverse clearly: LEFT rim rises about20pixels, RIGHT rim drops about20pixels, approximately8degrees the opposite way. At1.15-1.67s return the pan and BOTH hands exactly to their starting positions and hold level. Water moves mildly but stays completely inside the pan. Keep the pan size and rigid wall shape unchanged. Her head, face, cap, hair, costume, torso, curled tail and full rainbow fin stay still. Same plain pale aqua background and exact2D storybook paint. No fore-aft flattening, lowering the bowl, whole-body slide, detached hands, spilled water, white streaks outside the vessel, extra objects, extra limbs, legs, realistic textures, zoom or camera movement. Sound: silence.'''
(retry/'prompts/geologist_pan_full_source.txt').write_text(prompt+'\n',encoding='utf-8',newline='\n')
worker=retry/'run_geologist_comfy_pan_v142.py';code=(packet/'run_geologist_comfy_pan_v134.py').read_text().replace('day2_geologist_pan_motion_v1_20261001','day2_geologist_pan_motion_v2_20261001').replace('geologist_local_pan_study_v1_20261001','geologist_local_pan_study_v2_20261001');worker.write_text(code,encoding='utf-8',newline='\n')
rm=json.loads((packet/'MANIFEST.json').read_text());rm.update(id='DAY2-GEOLOGIST-PAN-LOCAL-V2',previous_attempt=rel(out/'REVIEW.json'),visual_review=None,output_state='Prepared prompt-only retry; visual scores pending.',worker_sha256=sha(worker));rm['job'].update(id='GEO-PAN-MOTION-REFERENCE02',queue_name='d2m_geologist_pan_v2_20261001',prompt_sha256=sha(retry/'prompts/geologist_pan_full_source.txt'))
for binding in rm['renderer']['bindings']:
 if binding['packet_path']=='workflows/render_gguf.py':binding['installed_path']=str(retry/'workflows/render_gguf.py')
 assert sha(retry/binding['packet_path'])==binding['sha256']
assert rm['job']['seed']==2026100134 and sha(retry/'inputs/geologist_pan_full_source.png')==rm['job']['input_sha256'];write(retry/'MANIFEST.json',rm)
profile=json.loads((packet/'PROFILE.json').read_text());profile.update(status='PREPARED_PROMPT_ONLY_ROLL_RETRY_REFERENCE',previous_motion_review=rel(out/'REVIEW.json'),phases={'ready':[0,.2],'left_roll':[.2,.65],'right_roll':[.65,1.15],'neutral_settle':[1.15,1.67]},single_changed_factor='Prompt action direction/clear return only; source/input/model/workflow/seed/settings identical.');write(retry/'PROFILE.json',profile)
write(retry/'COMPARABILITY.json',dict(source_and_input_identical=True,seed_identical=True,settings_identical=True,workflow_bindings_identical=True,changed_factor='Prompt only',previous_prompt_sha256=m['job']['prompt_sha256'],new_prompt_sha256=rm['job']['prompt_sha256'],source_sha256=rm['job']['source_sha256'],input_sha256=rm['job']['input_sha256'],previous_motion=3.8,qualification=qualification))
shutil.copyfile(__file__,packet/'executed_review_retry_v142.py');shutil.copyfile(__file__,retry/'executed_prepare_retry_v142.py')
(retry/'index.html').write_text(head+'<h1>Panning retry — explicit left/right roll</h1><p>Prepared with byte-identical input, same seed/settings/model/workflow. Only the action prompt changes. The first3.8 motion draft remains preserved; this attempt has no visual score yet.</p><img src="inputs/geologist_pan_full_source.png" alt="Exact unchanged input"><p><a href="MANIFEST.json">Exact bindings</a> · <a href="COMPARABILITY.json">Single-factor comparison</a> · <a href="prompts/geologist_pan_full_source.txt">Exact action prompt</a> · <a href="../day2_geologist_pan_motion_v1_20261001/attempt_01/index.html">Every first-attempt frame</a></p><p>LOCAL_MOTION_REFERENCE_ONLY; no runtime/cinematic/owner acceptance.</p>',encoding='utf-8')
with (b/'ASSET_LICENSES.md').open('a',encoding='utf-8',newline='\n') as f:f.write('\n| `'+rel(retry/'inputs/geologist_pan_full_source.png')+'` | Byte-identical previous complete-canvas geologist model input; source attribution unchanged | OpenAI generated output terms; original project art | https://openai.com/policies/terms-of-use/ | No new pixels/repair; prompt-only motion retry. SHA256 '+rm['job']['input_sha256']+' |\n')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();s+='\n| `'+rel(retry/'index.html')+'` | 🟣 | `CANDIDATE_REFERENCE_ONLY`; prompt-only roll retry; same source/input/seed/settings/workflow. First41 frames directly inspected: motion3.8/action3.4/return3.6 remain failed. No production/cinematic/owner acceptance. |\n';ledger.write_text(s,encoding='utf-8')
master=b/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text();entry='Local panning motion review (2026-10-01): [every41 native reference frame](../'+rel(out/'index.html')+') directly inspected; grip4.5 but alternating rock3.4/return3.6/reference3.8 fail the4.5 floor. [Prompt-only roll retry](../'+rel(retry/'index.html')+') keeps exact source/input/seed/settings/workflow. No source regeneration, production binding, full-route/device/child/owner/cinematic approval.';s=s.replace('## 0. Planning entry\n','## 0. Planning entry\n\n'+entry+'\n',1);master.write_text(s,encoding='utf-8')
findings=b/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';s=findings.read_text();start=s.index('\n## MA-PLAY-004\n');end=s.find('\n## ',start+1);sec=s[start:end];lines=sec.splitlines();i=next(i for i,x in enumerate(lines) if x.startswith('| history |'));lines[i]=lines[i].rstrip().removesuffix('|').rstrip()+' 2026-10-01 local pan motion: all41 frames directly reviewed; grip4.5/reference3.8/alternating action3.4/return3.6. Prompt-only same-source/settings/seed roll retry prepared; no production binding or lifecycle closure. |';s=s[:start]+'\n'.join(lines)+'\n'+s[end:];findings.write_text(s,encoding='utf-8')
impact=json.loads(ip.read_text());impact['files']=sorted(set(impact['files'])|{rel(p) for prefix in [packet,retry] for p in prefix.rglob('*') if p.is_file()});impact['validation'].append(dict(command='Direct original-resolution ordered inspection of every41 first motion frame',result='PASS',evidence=rel(out/'REVIEW.json')+'; inspection complete; motion3.8/action3.4/return3.6 remain failed.'));impact['validation'].append(dict(command='Prompt-only retry same-source/input/seed/settings/workflow comparison',result='PASS',evidence=rel(retry/'COMPARABILITY.json')));write(ip,impact)
allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(impact['files']);write(allow,sorted(allowed));print(json.dumps(dict(first_motion=3.8,first_direct_frames=41,retry_worker=rel(worker),source_unchanged=True)))
