from pathlib import Path
import copy, datetime, hashlib, json, shutil, subprocess
R=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
OLD=R/'assets_src/local_motion/nursery_connected_scrub_v1_20261002'
P=R/'assets_src/local_motion/nursery_connected_scrub_v2_20261002'
BASE='72a15c1c49456e37d81c733b8dd6ef4cdc736a45'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R).decode().strip()==BASE
subprocess.run(['git','fetch','origin','codex/job-art-review-v2-20261001'],cwd=R,check=True,capture_output=True)
assert subprocess.check_output(['git','rev-parse','origin/codex/job-art-review-v2-20261001'],cwd=R).decode().strip()==BASE
assert not P.exists()
review=read(OLD/'attempt01/DIRECT_REVIEW.json')
assert read(OLD/'REVIEW_STATUS.json')['status']=='MACHINE_RENDER_COMPLETE_VISUAL_REJECTED'
P.mkdir();(P/'review_tools').mkdir();(P/'.gdignore').write_text('',encoding='utf-8')
plan=dict(status='PLANNED_BEFORE_RENDER',baseline=BASE,created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),scope='One bounded local prompt-only A2 comparison for reciprocal Nursery palm rubbing. Same exact source/input/seed/settings/developed workflow as rejected A1. Reduce temporal and gaze requests to concentrate on the named missing scrub. No reference leaves the computer. Preserve A1 and every new frame/failure. No runtime or cinematic integration.',rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-ASSET-04','DL-ASSET-05','DL-ASSET-06','DL-MED-01','DL-MOT-01','DL-MOT-03','DL-MOT-10','DL-MOT-11','DL-MOT-12','DL-MOT-13','DL-QA-01','DL-QA-03','DL-QA-06','DL-QA-07'],findings=['MA-VIS-006','MA-PLAY-004'],gap='A1 forms a clasp and holds rather than showing two reciprocal rubs; current game wash action3.9 and attention3.8 remain separate. Existing still art cannot supply articulated scrub.',required_evidence=['Exact source/input/settings/seed/workflow equivalence to A1','One quiet-idle FIFO submission, no duplicate/restart/cancel/install','Native renderer receipt and41 unchanged decoded frames','All41 direct visual reviews with contact/material/fixtures/rubbing/entry-exit scores','All783 current production source bytes unchanged','Required document/coverage gates and durable exact anonymous publication; no creative/device/child/owner claim'])
write(P/'PLAN.json',plan)
shutil.copyfile(Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/prepare_nursery_scrub_a2_v401.py'),P/'review_tools/prepare_nursery_scrub_a2_v401.failed_original.py')
write(P/'PREPARATION_FAILURE_V401.json',dict(status='PRESERVED_PREPARATION_ASSERTION_FAILURE_NO_RENDER',error='Old review status was MACHINE_RENDER_COMPLETE_VISUAL_REJECTED, not a string starting REJECTED. Wrong metadata assertion failed before artifact creation or submission.',source='review_tools/prepare_nursery_scrub_a2_v401.failed_original.py',source_sha256=sha(P/'review_tools/prepare_nursery_scrub_a2_v401.failed_original.py'),repair='Read exact established A1 status, preserve rejected A1, no grade change or waiver.'))
ip=R/'design/audit_impacts/job-nursery-scrub-a2-20261002.json'
write(ip,dict(id='job-nursery-scrub-a2-20261002',scope=plan['scope'],baseline=BASE,rules=plan['rules'],findings=plan['findings'],files=[(P/'PLAN.json').relative_to(R).as_posix()],validation=[dict(command='Local Nursery reciprocal scrub prompt-only A2',result='PENDING',evidence=(P/'PLAN.json').relative_to(R).as_posix())],acceptance_gaps='Source and current game opinions unchanged. Local video is reference only, does not satisfy full-frame cinematic rule and is never runtime playback. Complete scrutiny of41 native frames, source truth, contact/attention/return, actual game mounting/action/ordinary routes, target device, child, owner, all-job final report and integration/release remain separate. Explicit external Nursery reference-upload approval and preview-tab status permission remain pending; no bypass.'))
for sub in ('inputs','prompts','workflows'):(P/sub).mkdir()
m=copy.deepcopy(read(OLD/'MANIFEST.json'))
assert len(m['jobs'])==1
for x in m['renderer']['bindings']:
 source=OLD/x['packet_path'];assert sha(source)==x['sha256']==sha(Path(x['installed_path']))
 target=P/x['packet_path'];target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(source,target)
shutil.copyfile(OLD/m['input_path'],P/'inputs/NUR-SCRUB-A2.png')
prompt='''Keeping her hands touching low above the basin, Roshan gently slides her near palm left and right across her far cupped palm twice, then rests in the starting contact pose. Tiny horizontal rubbing strokes; fingers slide over the palm, elbows stay low, wrists remain connected. Hands never rise or clasp.
Locked camera. Keep her head, body, hair, costume, rainbow tail, basin, faucet, pedestal, soft painted outlines and neutral background still. Faucet stays off. No clapping, prayer pose, hand lift, new object, soap trail to the faucet, text or reward effects.
Sound: silence.
'''
(P/'prompts/NUR-SCRUB-A2.txt').write_text(prompt,encoding='utf-8',newline='\n')
m.update(id='nursery-connected-scrub-v2-20261002',baseline=BASE,created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),intention='Two short reciprocal low palm-rubbing strokes and return; concentrate on action. Source gaze is preserved as a separately weak unresolved attention issue.',input_path='inputs/NUR-SCRUB-A2.png',prompt_path='prompts/NUR-SCRUB-A2.txt',queue_name='nursery_scrub_a2_20261002',status='BOUND_INPUT_READY_FOR_QUIET_IDLE_DISPATCH',visual_review=None,complete_action_score=None,comparison=dict(prior_manifest=OLD.relative_to(R).as_posix()+'/MANIFEST.json',prior_review=OLD.relative_to(R).as_posix()+'/attempt01/DIRECT_REVIEW.json',changed='Prompt only; gaze/acting changes removed to isolate reciprocal rubbing',preserved='Exact original input bytes, source pixels, seed2026100201, settings896x512/41frames/24steps, installed developed workflow bytes; source and native A1 preserved'))
m['input_sha256']=sha(P/m['input_path']);m['prompt_sha256']=sha(P/m['prompt_path'])
assert m['input_sha256']==read(OLD/'MANIFEST.json')['input_sha256']
m['clip_contract'].update(entry='Same low palm-contact source pose; faucet off.',exit='Same low palm contact, no claimed seamless loop; source gaze remains an open issue.',timeline=prompt,required_review='All41 unchanged native frames: joined wrists, opposite-palm sliding contact, two small reciprocal rubs, stable body/tail/material/fixtures and clean entry/exit. Attention remains separate and below floor if source forward gaze persists.')
m['jobs'][0].update(id='NUR-SCRUB-A2',name='Reciprocal low palm rubbing prompt comparison',input_path=m['input_path'],input_sha256=m['input_sha256'],prompt_path=m['prompt_path'],prompt_sha256=m['prompt_sha256'],queue_name=m['queue_name'])
write(P/'MANIFEST.json',m)
worker=R/'audit/job_nursery_wash_connected_v1_20261002/review_tools/queue_nursery_motion_v367.py'
text=worker.read_text(encoding='utf-8');original_sha=sha(worker)
changes={'nursery_connected_scrub_v1_20261002':'nursery_connected_scrub_v2_20261002','NUR-SCRUB-A1':'NUR-SCRUB-A2','build/nursery_local_scrub_active_20261002':'build/nursery_local_scrub_a2_active_20261002'}
for a,b in changes.items():assert a in text;text=text.replace(a,b)
target=P/'review_tools/queue_nursery_motion_a2_v401.py';target.write_text(text,encoding='utf-8',newline='\n');compile(text,str(target),'exec')
write(P/'DISPATCHER_DERIVATION.json',dict(source_path=worker.relative_to(R).as_posix(),source_sha256=original_sha,changes=changes,qualification='Only packet path, one job ID and isolated state directory changed. Existing renderer CLI and installed workflow are unchanged.'))
shutil.copyfile(__file__,P/'review_tools'/Path(__file__).name)
write(P/'INPUT_COMPARISON.json',dict(status='PASS_IDENTICAL_A1_INPUT_SOURCE_SETTINGS_SEED_WORKFLOW',input_sha256=m['input_sha256'],source_sha256=m['source_sha256'],seed=m['seed'],settings=m['renderer']['settings'],changed='Short reciprocal-rub prompt only',prior_rejected_review=plan['gap'],reference_uploaded=False,external_service_used=False))
attrs=R/'.gitattributes';attrs.write_bytes(attrs.read_bytes()+b'\nassets_src/local_motion/nursery_connected_scrub_v2_20261002/** -text\n')
licenses=R/'ASSET_LICENSES.md';licenses.write_bytes(licenses.read_bytes()+b'\n| `assets_src/local_motion/nursery_connected_scrub_v2_20261002/**` | Local ComfyUI prompt-only A2 motion reference from preserved Nursery palm02 | Original project draft reference, inherited source provenance | Exact MANIFEST source/input/prompt/workflow hashes and native receipts | Input/source/seed/settings/workflow identical to rejected A1; new reciprocal-rub prompt only. Reference-only, never runtime/cinematic delivery pixels; every native frame requires review. |\n')
for file,heading in [('audit/MASTER_AUDIT_2026-08-09.md','## 0. Planning entry'),('audit/MASTER_AUDIT_2026-08-09.md','### Development task index')]:
 p=R/file;s=p.read_text(encoding='utf-8');note='Nursery scrub A2 continuation (2026-10-02): [bounded local reciprocal-rubbing comparison](../assets_src/local_motion/nursery_connected_scrub_v2_20261002/index.html) keeps exact rejected-A1 source/input/seed/settings/developed workflow. Prompt-only focus on two low back-and-forth rubs; source gaze remains separate. All41 native frames require direct review; current game action3.9 and attention3.8 unchanged. No external reference upload, runtime/cinematic/device/child/owner or all-job acceptance. [Impact](../design/audit_impacts/job-nursery-scrub-a2-20261002.json).'
 s=s.replace(heading+'\n',heading+'\n\n'+note+'\n',1);p.write_text(s,encoding='utf-8',newline='\n')
ledger=R/'design/05_DOC_LEDGER.md';ledger.write_bytes(ledger.read_bytes()+b'\n| `assets_src/local_motion/nursery_connected_scrub_v2_20261002/index.html` | '+ '🟣'.encode()+b' | `CANDIDATE_REFERENCE_ONLY`; prompt-only low reciprocal-rub A2 retains exact rejected-A1 source/input/seed/settings/developed local workflow. All41 native frames pending direct review, current game action3.9/attention3.8 unchanged. No external reference upload or runtime/cinematic/device/child/owner/all-job acceptance. |\n')
(P/'index.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Nursery reciprocal scrub A2</title><style>body{font:18px system-ui;max-width:1000px;margin:36px auto;padding:0 20px;background:#f1f5fa;color:#24334b}a{color:#25477c}</style><h1>Nursery reciprocal scrub A2</h1><p>One local prompt-only comparison. A1 forms a clasp instead of reciprocal rubbing; its failed output remains preserved. A2 keeps exact input/source/seed/settings/developed workflow and asks for two tiny horizontal palm-rubbing strokes.</p><p>Rendering and all41-frame visual review are pending. Current game action3.9, attention3.8 and room2.9 remain unchanged. Source gaze is a separate unresolved priority; no gaze repair is claimed.</p><p>Local motion reference only. No reference leaves this computer. No runtime/cinematic delivery, device, child, owner or all-job approval.</p><p><a href="MANIFEST.json">Complete bound manifest</a> · <a href="INPUT_COMPARISON.json">Exact A1 comparison</a> · <a href="prompts/NUR-SCRUB-A2.txt">Final prompt</a> · <a href="../nursery_connected_scrub_v1_20261002/index.html">Preserved rejected A1</a></p></html>',encoding='utf-8',newline='\n')
d=read(ip);d['files']=sorted({p.relative_to(R).as_posix() for p in P.rglob('*') if p.is_file()}|{'.gitattributes','ASSET_LICENSES.md','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md'});write(ip,d)
print('NURSERY_A2_PREPARED|Same input/source/seed/settings/developed workflow|one prompt-only reference|external uploads false')
