from pathlib import Path
import datetime,hashlib,json,shutil
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');ROOT=Path('C:/Users/Peter/Documents/mermaid-roshan-reef');L=B/'audit/job_artwork_refinement_live';S=B/'audit/job_shared_atlas_state_review_v1_20261003'
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):
 n=p.with_name(p.name+'.v599_next');n.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());n.replace(p)
def textwrite(p,text):
 n=p.with_name(p.name+'.v599_next');n.write_bytes(text.encode());n.replace(p)
ip=B/'design/audit_impacts/job-shared-atlas-state-review-20261003.json';impact=read(ip)
planned=['audit/job_artwork_refinement_live/'+x for x in ['ALL_ITEMS.json','ATLAS_STATE_ITEMS_V51.json','CURRENT_BOUNDARY_REFRESH.json','all_items.html','index.html','review_tools/register_parts_v51.py','review_tools/load_register_parts_v51.js','review_tools/test_register_parts_v51.py','review_tools/refresh_current_job_review_v51.py']]+['audit/MASTER_AUDIT_2026-08-09.md','audit/findings/ACTIVE_FINDINGS_2026-08-13.md','design/05_DOC_LEDGER.md']
impact['files']=sorted(set(impact['files']+planned));write(ip,impact)
history=S/'previous_v50';history.mkdir(exist_ok=True)
for src in ['ALL_ITEMS.json','all_items.html','CURRENT_BOUNDARY_REFRESH.json']:
 dst=history/src
 if dst.exists():
  if src=='ALL_ITEMS.json' and read(L/src).get('display_revision')=='V51':
   pending=(L/src).with_name(src+'.v599_restore');pending.write_bytes(dst.read_bytes());pending.replace(L/src)
  else:assert dst.read_bytes()==(L/src).read_bytes(),'Do not overwrite the exact V50 archive'
 else:shutil.copyfile(L/src,dst)
registry=read(L/'ALL_ITEMS.json');assert len(registry['items'])==2050 and registry['counts']['registered_items']==2050 and not registry.get('item_shards')
review=read(S/'DIRECT_CELL_REVIEW.json');assert review['individual_source_cells']==88
added=[]
for a in review['atlases']:
 for c in a['cells']:
  added.append(dict(id=c['id'],aliases=[],kind='source object region',path=a['source_path'],region=c['source_region'],source_dimensions=a['source_dimensions'],earlier_sha256=a['source_sha256'],historical_source_score=c['source_cell_score'],evaluation=c['evaluation'],refinement='Preserve the exact prop identity, support and conserved parts through every authored state; repair the named source weakness, then inspect actual mounted/game/training action. Source cell alone cannot pass a complete interaction.',families=['Shared Library/Playroom entrances','Individual authored prop state'],original_reports=['audit/job_shared_atlas_state_review_v1_20261003/index.html#'+c['id']],source_qualification='Exact unchanged native cell directly viewed and individually graded. Literal manifest use '+str(c['referenced_in_declared_timeline'])+'; source relationships/declared order are separate from current mounted and complete action acceptance.',preview_path=c['qa_path'],native_reference_observations=[],latest_refinement=dict(report='audit/job_shared_atlas_state_review_v1_20261003/index.html#'+c['id'],note='Individual source-cell and static relationship review; no production artwork replacement.'),current_checkout_sha256=a['source_sha256'],current_byte_status='EXACT_EARLIER_BYTES',current_source_score=c['source_cell_score'],priority=c['priority'],protected_original=False,current_mounted_score=None,current_complete_action_score=None,image_path=a['source_path'],image_scope='Exact atlas region; individually seen at original native crop size',individual_review_utc=review['reviewed_utc'],authored_frame_index=c['frame_index'],referenced_in_declared_timeline=c['referenced_in_declared_timeline'],current_binding=a['manifest_path'],binding_sha256=a['manifest_sha256']))
assert len(added)==88
part=L/'ATLAS_STATE_ITEMS_V51.json';write(part,dict(schema='reef.job-artwork-item-part.v1',created_utc=now(),source_review='audit/job_shared_atlas_state_review_v1_20261003/DIRECT_CELL_REVIEW.json',items=added,qualification='88 additional individually reviewed native source regions, not 88 new source files or runtime/action passes.'))
descriptor=dict(path=part.name,bytes=part.stat().st_size,sha256=sha(part.read_bytes()),items=len(added));registry['item_shards']=[descriptor]
assembled=registry['items']+added;counts=registry['counts'];assert len(assembled)==2138
counts.update(registered_items=len(assembled),individual_source_object_regions=sum(q['kind']=='source object region' for q in assembled),inclusive_current_source_priorities=sum(q.get('capture_family') not in ['geode_current_v1','nursery_wash_v3'] and q.get('current_source_score') is not None and q['current_source_score']<=4.5 for q in assembled),new_shared_atlas_state_regions=88)
assert counts['individual_source_object_regions']==373 and counts['inclusive_current_source_priorities']==1041 and counts['unique_source_files']==1286 and counts['unreviewed_current_source']==294
registry.update(display_revision='V51',updated_utc=now(),refresh_command='python -B audit/job_artwork_refinement_live/review_tools/refresh_current_job_review_v51.py')
registry['qualification']+=' V51 items are the root items plus literal hash/size/count-verified item_shards. Missing or altered parts block assembly; keep every JSON below the existing4MiB scanner ceiling. Source/cell/region opinions remain distinct from mounted and complete-action acceptance.'
textwrite(L/'ALL_ITEMS.json',json.dumps(registry,ensure_ascii=False,separators=(',',':'))+'\n');assert (L/'ALL_ITEMS.json').stat().st_size<=4194304 and part.stat().st_size<=4194304
for name in ['register_parts_v51.py','load_register_parts_v51.js','test_register_parts_v51.py']:shutil.copyfile(ROOT/'tmp'/name,L/'review_tools'/name)
ref=(L/'review_tools/refresh_current_job_review_v50.py').read_text(encoding='utf-8');old="registry=json.loads((live/'ALL_ITEMS.json').read_text(encoding='utf-8-sig'))";assert ref.count(old)==1
ref=ref.replace(old,'from register_parts_v51 import load_register\nregistry=load_register(live)')
old="(live/'CURRENT_BOUNDARY_REFRESH.json').write_text";assert ref.count(old)==1
ref=ref.replace(old,"stamp.update(registry_root_sha256=sha(live/'ALL_ITEMS.json'),registry_parts=registry['item_shards'],assembled_registry_parts_verified=True)\n"+old)
textwrite(L/'review_tools/refresh_current_job_review_v51.py',ref)
page=(L/'all_items.html').read_text(encoding='utf-8');old="fetch('ALL_ITEMS.json').then(x=>{if(!x.ok)throw Error(x.status);return x.json()})";assert page.count(old)==1;page=page.replace(old,'loadVerifiedRegisterV51()')
old='then(([d,stamp])=>{const checks=';assert page.count(old)==1;page=page.replace(old,"then(([d,stamp])=>{if(stamp.registry_root_sha256!==d.verified_root_sha256||!stamp.assembled_registry_parts_verified||stamp.registry_items!==d.items.length||JSON.stringify(stamp.registry_parts)!==JSON.stringify(d.item_shards))throw Error('Register changed since its literal boundary refresh; rerun the recorded V51 refresh command');const checks=")
at=page.index('<script>');page=page[:at]+'<script src="review_tools/load_register_parts_v51.js"></script>'+page[at:]
notice='<p><a href="../job_shared_atlas_state_review_v1_20261003/index.html">New: all88 individual Library/Playroom prop states and33 source relationships</a> · V51:2138 entries/1286 primary sources/1041 inclusive source-cell-region priorities/664 unique source priorities/294 primary source opinions pending. <a href="ATLAS_STATE_ITEMS_V51.json">Hash-bound additional88 records</a>; the complete written register requires the root plus this part. No production artwork changed.</p>'
page=page.replace('<header>','<header>'+notice,1);textwrite(L/'all_items.html',page)
entry=(L/'index.html').read_text(encoding='utf-8');at=entry.index('<main>')+len('<main>');entry=entry[:at]+'<section id="shared-atlas-v51"><h2>Current individual shared-prop source coverage</h2>'+notice+'<p>All88 native cells have separate written source opinions; all remain inclusive priorities. Tent occlusion and three-block identity are useful bounded successes. Ring duplication/colour changes, ambiguous stuffie waving parts, book transitions and the sailboat loop seam need refinement. Declared order is source evidence; complete played game/training action and owner approval remain open.</p></section>'+entry[at:];textwrite(L/'index.html',entry)
master=B/'audit/MASTER_AUDIT_2026-08-09.md';m=master.read_text(encoding='utf-8');marker='### Development task index\n';assert m.count(marker)==1
summary='Shared-prop individual-state continuation (2026-10-03): [all88 native Library/Playroom cells and33 static source relationships](job_shared_atlas_state_review_v1_20261003/index.html) separately inspected/scored, all88 inclusive priorities. Ring duplication/colour/pearl continuity, changing wave silhouettes, page-turn/return gaps and sailboat loop identity remain weak; tent occlusion and three-block identity are bounded source successes. Literal tent timeline omits5/6/7. V51 known2138 entries/1286 primary sources/1041 source-cell-region priorities/664 unique source priorities/294 unreviewed primary sources; root plus one literal hash/size/count-bound part, existing4MiB ceiling retained. All783 production literals unchanged. Complete timed/source-to-runtime/game/training/device/child/owner/comprehensive report, finding lifecycle, integration and release remain open.\n\n'
textwrite(master,m.replace(marker,marker+'\n'+summary,1))
ledger=B/'design/05_DOC_LEDGER.md';ld=ledger.read_text(encoding='utf-8');lines=ld.splitlines();hits=[i for i,x in enumerate(lines) if 'job_artwork_refinement_live/index.html' in x]
assert hits,'Current illustrated review ledger route must exist'
lines[hits[0]]+=' V51 adds [88 individual shared-prop states](../audit/job_shared_atlas_state_review_v1_20261003/index.html):2138 known entries/1041 source-cell-region priorities;294 primary sources remain unreviewed. Root and literal verified register part are jointly required; no source/runtime/action/finding/owner acceptance follows.';textwrite(ledger,'\n'.join(lines)+'\n')
finding=B/'audit/findings/ACTIVE_FINDINGS_2026-08-13.md';f=finding.read_text(encoding='utf-8');start=f.index('### MA-VIS-006');end=f.find('\n### ',start+1);assert end>start
f=f[:end]+'\nScoped source evidence (2026-10-03): [all88 Library/Playroom atlas cells and33 source relationships](../job_shared_atlas_state_review_v1_20261003/index.html) now have individual native inspections. V51 known2138 entries/1041 inclusive source-cell-region priorities;294 primary source opinions remain unassigned. Source-only evidence, all783 production members unchanged. This does not repair or close `MA-VIS-006`; complete mounted/game/training/device/child/owner acceptance stays open. [Impact](../../design/audit_impacts/job-shared-atlas-state-review-20261003.json).\n'+f[end:];textwrite(finding,f)
shutil.copyfile(__file__,S/'review_tools'/Path(__file__).name)
write(S/'REGISTER_PART_CHECK.json',dict(status='V51_BOUND_PART_WRITTEN_REFRESH_AND_NEGATIVE_TESTS_PENDING',checked_utc=now(),root_bytes=(L/'ALL_ITEMS.json').stat().st_size,root_sha256=sha((L/'ALL_ITEMS.json').read_bytes()),part=descriptor,base_items=2050,additional_cells=88,assembled_items=2138,primary_sources=1286,source_object_regions=373,inclusive_source_cell_region_priorities=1041,unreviewed_primary_sources=294,scanner_ceiling_bytes=4194304,runtime_changed=False,qualification='Literal root and part verification, meaningful missing/tampered/duplicate/path/ceiling/count negative tests and browser QA still required.'))
impact=read(ip);impact['files']=sorted(set(impact['files']+[p.relative_to(B).as_posix() for p in S.rglob('*') if p.is_file()]));write(ip,impact)
print('V51_WRITTEN',counts['registered_items'],counts['inclusive_current_source_priorities'],(L/'ALL_ITEMS.json').stat().st_size,descriptor,flush=True)
