from pathlib import Path
import datetime,hashlib,json,shutil
from PIL import Image
B=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');S=B/'audit/job_shared_atlas_state_review_v1_20261003';S.mkdir();(S/'native_cells').mkdir();(S/'review_tools').mkdir()
read=lambda p:json.loads(p.read_text(encoding='utf-8-sig'));sha=lambda raw:hashlib.sha256(raw).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,d):n=p.with_name(p.name+'.v597_next');n.write_bytes((json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode());n.replace(p)
selected=[x for x in read(B/'audit/job_shared_background_review_v1_20261003/DIRECT_SOURCE_REVIEW.json')['sources'] if 'sheet' in x['path'] or 'atlas' in x['path']];assert len(selected)==11
manifest_paths=['assets/flats/castle/interactions_v2/castle_interactions_v2.json','assets/flats/castle/interactions_v4/castle_interactions_v4.json'];lookup={}
for path in manifest_paths:
    raw=(B/path).read_bytes()
    for x in json.loads(raw)['assets']:
        if x.get('sheet'):lookup[x['sheet']]=(path,sha(raw),x)
rules=['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-01','DL-ASSET-02','DL-ASSET-03','DL-VIS-01','DL-VIS-02','DL-VIS-03','DL-VIS-04','DL-VIS-05','DL-VIS-07','DL-INT-02','DL-MOT-11','DL-QA-03','DL-QA-07']
write(S/'PLAN.json',dict(status='ALL88_SHARED_NATIVE_STATES_PREPARED_FOR_INDIVIDUAL_REVIEW',baseline='c7817974fb23913c1d764c718a70a5932cacb883',planned_utc=now(),scope='Complete all11 omitted Library/Playroom atlases and88 authored cells. Compare fixed object/material/palette/count/support and declared key-order semantics. Preserve unchanged native pixels as individual QA crops; no artwork replacement or production mutation.',rules=rules,findings=['MA-VIS-006'],relationship_to_MA_PLAY_004='Logical workflow/continuity contributes to the wider owner audit; no Roshan-owned job action or MA-PLAY-004 repair/closure is claimed by this shared-object source review.',sources=[dict(id=x['id'],path=x['path'],sha256=x['sha256'],existing_whole_source_score=x['source_score']) for x in selected],required_evidence=['Every88 native source cell directly inspected and individually scored, all objects/relationships relevant to count,identity,material and action meaning','Literal manifest geometry and source hashes, decoded crop pixel hashes, no resampling or source modification','Illustrated original-source/all-cell review, individual written opinions and separate key-order player without actual-game/motion acceptance','Current known-item hash refresh and all783 production bytes unchanged','Bounded register parts with fail-closed hash/size/count/ID checks; retain existing4MiB scan ceiling','Fresh authority/development/document tests/no-regression gates and exact topic publication'],runtime_changed=False,owner_acceptance=None))
IP=B/'design/audit_impacts/job-shared-atlas-state-review-20261003.json'
write(IP,dict(id='job-shared-atlas-state-review-20261003',scope='Complete the remaining88 individually authored shared-object atlas state opinions and preserve exact native inspection pixels; extend illustrated refreshable register through bounded parts without raising the scanner ceiling. No production/scene/source redesign or finding closure.',baseline='c7817974fb23913c1d764c718a70a5932cacb883',rules=rules,findings=['MA-VIS-006'],files=[(S/'PLAN.json').relative_to(B).as_posix()],validation=[dict(command='Direct native88-state and declared-key-order review',result='PENDING',evidence='audit/job_shared_atlas_state_review_v1_20261003/PLAN.json;11 known weak whole sources are not individual state coverage.'),dict(command='Exact current production source comparison',result='PENDING',evidence='No runtime changes planned; verify all783 actual frozen Candy boundary members.'),dict(command='Bounded registry loading and fresh authority/development/document/no-regression gates',result='PENDING',evidence='Current monolithic V50 register is close to4MiB. Preserve it as history, add fail-closed bounded parts rather than weakening the ceiling.')],acceptance_gaps='294 primary source reviews, complete actual-use/action/game/training/ordinary-route coverage, weak-art regeneration and continuous contact, phone/device/child/owner/comprehensive report acceptance remain open. Shared native source states cannot grant those later claims.'))
atlases=[]
for x in selected:
    src=B/x['path'];raw=src.read_bytes();assert sha(raw)==x['sha256'];mp,mh,asset=lookup[x['path']];cols,rows=asset['grid'];cw,ch=asset['cell_size'];assert asset['authored_frame_count']==8 and cols*rows==8
    out=S/'native_cells'/x['id'];out.mkdir();cells=[]
    with Image.open(src) as im:
        assert list(im.size)==[cols*cw,rows*ch]
        for i in range(8):
            left=(i%cols)*cw;top=(i//cols)*ch;box=[left,top,left+cw,top+ch];cell=im.crop(tuple(box));dst=out/f'state_{i:02d}.png';cell.save(dst);cells.append(dict(id=x['id']+f'-CELL-{i:02d}',frame_index=i,source_region=[left,top,cw,ch],qa_path=dst.relative_to(B).as_posix(),qa_bytes=dst.stat().st_size,qa_sha256=sha(dst.read_bytes()),decoded_pixel_sha256=sha(cell.tobytes()),dimensions=list(cell.size),mode=cell.mode))
        dims=list(im.size);mode=im.mode
    atlases.append(dict(id=x['id'],source_path=x['path'],source_sha256=x['sha256'],source_dimensions=dims,source_mode=mode,existing_whole_source_score=x['source_score'],manifest_path=mp,manifest_sha256=mh,asset_id=asset['id'],semantic_action=asset.get('semantic_action',asset.get('animation_behavior',{}).get('action')),grid=[cols,rows],cell_size=[cw,ch],declared_key_order=asset.get('timeline_sequence',list(range(8))),declared_frame_duration_seconds=asset.get('frame_duration_seconds',asset.get('frame_duration',0.1375)),cells=cells))
write(S/'SOURCE_INDEX.json',dict(status='88_EXACT_NATIVE_QA_CROPS_NO_ARTWORK_MODIFICATION',baseline='c7817974fb23913c1d764c718a70a5932cacb883',created_utc=now(),atlases=atlases,native_source_files=11,native_cells=88,no_resampling=True,no_source_modification=True,visual_review_complete=False,runtime_changed=False,owner_acceptance=None))
boundary=read(B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json');assert len(boundary['members'])==783 and all(sha((B/x['path']).read_bytes())==x['sha256'] for x in boundary['members']);write(S/'PRODUCTION_BOUNDARY_CHECK.json',dict(status='ALL783_CURRENT_LITERAL_PRODUCTION_MEMBERS_UNCHANGED',checked_utc=now(),boundary_path='assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json',boundary_sha256=sha((B/'assets_src/local_motion/candy_wrap_continuity_v1_20261003/PRODUCTION_BOUNDARY.json').read_bytes()),members=783,qualification='Exact no-production-delta check only, no gameplay/motion/device/child/owner acceptance.'))
shutil.copyfile(__file__,S/'review_tools'/Path(__file__).name);d=read(IP);d['files']=sorted(p.relative_to(B).as_posix() for p in S.rglob('*') if p.is_file());d['validation'][1].update(result='PASS',evidence='audit/job_shared_atlas_state_review_v1_20261003/PRODUCTION_BOUNDARY_CHECK.json;all783 literal members unchanged.');write(IP,d)
print('ALL88_NATIVE_CELLS_PREPARED',[(a['id'],a['cell_size'],a['semantic_action']) for a in atlases],flush=True)
