from pathlib import Path
import datetime, hashlib, json, shutil, subprocess

r = Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
d = r / 'assets_src/imagegen/day2_doctor_wash_reach_v1_20261001'
assert not d.exists()
d.mkdir(parents=True)
(d / '.gdignore').write_text('', encoding='utf-8')
source = 'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/attempt_06_native.png'
source_sha = hashlib.sha256((r / source).read_bytes()).hexdigest()
assert source_sha == '3ada2bd00859314ece42ccffa2dc20aae9543086b1161d6e8336689021c99d2c'
prompt = '''Edit the supplied complete transparent Doctor Roshan sprite for one exact gameplay gap: she must extend her attached hands toward a washing basin beside her on IMAGE RIGHT, so the sink can sit beside her body rather than hiding her chest and tail. Return one new complete transparent RGBA full-body 2D storybook sprite.

Preserve the source's drawn child identity, softly oval face, large brown eyes, caramel curls, pearl flower, broad rainbow forelock to the right, ivory short-sleeved doctor coat with coral trim and heart patch, teal blouse, lavender waistband, medicine satchel at image left, rainbow scale tail curving to image right, two joined fin lobes with V notch, entire silhouette and overall framing. Keep the same head/body proportions, flat painted warmth, fine brown/plum contours and aqua/lavender shadows. All of the head, hair, satchel, tail and fin must remain inside generous transparent margins.

Change the connected shoulders, elbows and hands only as needed for this clear purposeful working pose. Both upper arms remain attached, elbows bend naturally, and both forearms reach diagonally down and OUT to image right, away from the blouse. Put the two-hand contact cluster at approximately x=720,y=650 on the source1122x1402 canvas (about64 percent across and46 percent down). The hand cluster sits clearly to the right of the chest, with visible air between forearms and torso. Her left palm rests on and gently rubs the BACK of her right hand; the right fingers point slightly down/right in one relaxed grouped shape. Show small matte ivory/mint soap lather where the two hands touch, with the silhouettes of both hands still readable. Keep hands child-sized but generous enough to read in a small game sprite; no tiny interlaced fingers. Eyes attend to her hands, calm concentrated small smile. Do not put hands back into a clasp against her chest.

No sink, faucet, basin, water jet, patient, tool, background, ground shadow plate, lettering or UI; the existing game sink will be reused separately. No floating hands, extra fingers/limbs, detached wrists, adult anatomy, giant head, glossy skin, realistic rendering, 3D, glitter, halo or sticker border. Preserve the entire native figure rather than giving a crop or a sheet.'''
profile = {'id': 'WASH-DOCTOR-REACH-KEY01', 'status': 'GENERATION_PENDING_UNBOUND', 'baseline': subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=r, text=True).strip(), 'prepared_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(), 'gap': 'All58 native static sink placements reviewed; chest-level hands force cabinet/body occlusion and fail contact4.2, clean result4.0. Prior41-frame rub study has purposeful motion4.0/return3.5. Existing doctor atlas/tool poses and all6 fresh washing candidates lack an outward two-hand reach suitable for a side basin. Reuse the exact existing painted sink; no sink redesign or approved/protected original change.', 'evidence': ['audit/day_two_wash_contact_study_v1_20261001/attempt_01/REVIEW.json', 'audit/day_two_wash_contact_study_v1_20261001/attempt_02/REVIEW.json', 'audit/day_two_wash_contact_study_v1_20261001/attempt_03/REVIEW.json', 'assets_src/local_motion/day2_doctor_wash_rub_study_v1_20261001/attempt_01/REVIEW.json'], 'method': 'Built-in imagegen complete RGBA edit of unbound generated source-only draft; no manual pixel repair or motion synthesis.', 'input': {'path': source, 'sha256': source_sha, 'role': 'Full-body identity/style/pose starting candidate, unbound4.5 source draft'}, 'prompt': prompt, 'prompt_sha256': hashlib.sha256(prompt.encode('utf-8')).hexdigest(), 'intention': 'Attention to connected soapy hands, purposeful back-of-hand rub above side basin, visible rinse/clean result, quiet return. This file addresses working-pose source coverage only.', 'movement_profile': 'design/animation/ROSHAN_MOVEMENT_LANGUAGE.md', 'requested_hand_landmark': [720,650], 'runtime_binding': False, 'source_score': None, 'mounted_contact_score': None, 'whole_action_score': None, 'owner_accepted': False, 'qualification': 'Source/mounted/complete-action scores must be independently reviewed. No new runtime action, water causality, sequence, device/child/owner or cinematic acceptance.'}
(d / 'ATTEMPT01_PROMPT.json').write_text(json.dumps(profile, indent=2) + '\n', encoding='utf-8')
(r / 'tmp/doctor_reach_prompt_v56.txt').write_text(prompt, encoding='utf-8')
shutil.copyfile(__file__, d / 'executed_prepare_doctor_reach_source_v56.py')
ip = r / 'design/audit_impacts/job-wash-contact-study-20261001.json'
impact = json.loads(ip.read_text(encoding='utf-8'))
impact['scope'] += ' Named outward connected-hand source edit to let the reused basin sit beside the body after58 below-floor native placements; source and contact/causal action must be reviewed separately.'
impact['files'] = sorted(set(impact['files']) | {str(p.relative_to(r)).replace('\\','/') for p in d.rglob('*') if p.is_file()})
impact['validation'].append({'command': 'Direct native source and exact game-size side-basin contact review', 'result': 'PENDING', 'evidence': 'assets_src/imagegen/day2_doctor_wash_reach_v1_20261001/ATTEMPT01_PROMPT.json; generation and subsequent native context evidence pending.'})
ip.write_text(json.dumps(impact, indent=2) + '\n', encoding='utf-8')
print(json.dumps({'status': profile['status'], 'path': str(d), 'prompt_sha256': profile['prompt_sha256'], 'input': profile['input']}))
