from pathlib import Path
import json,hashlib,html,datetime
b=Path(r'C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef');out=b/'audit/job_review_v2_20261001';src=b/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def rel(p):return p.relative_to(b).as_posix()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def href(path):return '../../'+path
def esc(x):return html.escape(str(x))
sources=json.loads((src/'REVIEW_V6.json').read_text());assert len(sources['items'])==18
stills=['audit/job_geode_opening_states_v3_20261001/attempt_03/REVIEW.json','audit/job_pan_gripping_pose_study_v2_20261001/REVIEW.json'];rows=[];cards=[]
for path in stills:
 review=json.loads((b/path).read_text())
 for v in review['views']:
  image_path=v['archive_path'];assert sha(b/image_path)==v['sha256'] and v['direct_native_review'];criteria=v['scores'];priorities={k:s for k,s in criteria.items() if s is not None and s<=4.5};pending=[k for k,s in criteria.items() if s is None];row=dict(id=v['id'],evidence='SELECTED_STATIC_NATIVE_STUDY',review_path=path,image_path=image_path,image_sha256=v['sha256'],criteria=criteria,inclusive_priorities=priorities,not_scored=pending,evaluation=v['evaluation'],qualification=v['qualification'],owner_acceptance=None,production_binding_changed=False);rows.append(row)
  cards.append('<article data-priority="'+('yes' if priorities else 'no')+'"><h3>'+esc(v['id'])+'</h3><img loading="lazy" src="'+href(image_path)+'" alt="'+esc(v['id'])+'"><p>'+esc(v['evaluation'])+'</p><table><tr><th>Criterion</th><th>Score /5</th><th>Draft status</th></tr>'+''.join('<tr><td>'+esc(k.replace('_',' '))+'</td><td>'+('Unscored' if s is None else str(s))+'</td><td>'+('Acceptance open' if s is None else 'Priority ≤4.5' if s<=4.5 else 'Individual criterion above floor')+'</td></tr>' for k,s in criteria.items())+'</table><p class="note">'+esc(v['qualification'])+'</p><a href="'+href(path)+'">Exact source review</a></article>')
motion=[]
for n in [1,2,3]:
 packet=b/('assets_src/local_motion/day2_geologist_pan_motion_v'+str(n)+'_20261001');p=packet/'attempt_01/REVIEW.json'
 if not p.exists():motion.append(dict(attempt=n,status='PENDING_DIRECT_REVIEW',source_score=4.6,score=None,packet=rel(packet/'index.html')));continue
 d=json.loads(p.read_text());assert len(d['frames'])==41;assert all(v['visual_review']=='DIRECT_NATIVE_ORIGINAL_RESOLUTION' for v in d['frames']);motion.append(dict(attempt=n,status=d['status'],source_score=d['source_score'],score=d['motion_reference_score'],alternating_panning=d['alternating_panning_score'],neutral_return=d['neutral_return_score'],hand_contact=d['hand_contact_score'],review=rel(p),gallery=rel(packet/'attempt_01/index.html'),direct_frames=41))
counts=json.loads((b/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text())['counts'];data=dict(status='DRAFT_GEOLOGY_CONTINUATION_NO_WHOLE_JOB_PASS',created_utc=now,source_review=rel(src/'REVIEW_V6.json'),source_originals=18,direct_neutral_source_displays=34,direct_whole_canvas_derivatives=13,current_static_views=16,total_selected_teacher_geology_pan_views=312,current_native_contexts=rows,local_motion_attempts=motion,known_all_job_register_counts=counts,priority_rule='Each scored source/component/state at4.5/5 or lower remains an individual priority; missing/absent evidence receives no invented mounted/action score. A source4.6 never grants a context/action/global pass.',remaining_acceptance='Ordinary complete training/story routes, Roshan local geode work/contact, panning support/action/return, source register unassigned388, room native coverage, device/child/owner and comprehensive final-report approval remain open.325 production sources and all live bindings unchanged.');write(out/'GEOLOGY_CONTEXT_PRIORITIES_V5.json',data)
source_cards=[]
for v in sources['items']:
 p=b/v['path'];assert sha(p)==v['sha256'];preview=p.with_name('audit_aqua.png');view=rel(preview if preview.exists() else p);source_cards.append('<article><h3>'+esc(v.get('id',v['path']))+' · source '+esc(v.get('source_score','unscored'))+'/5</h3><img loading="lazy" src="'+href(view)+'" alt="'+esc(v.get('id','Source artwork'))+'"><p>'+esc(v.get('evaluation','See the preserved individual source review.'))+'</p><p class="note">'+esc(v.get('qualification',v.get('status','')))+' · Owner approval open.</p><a href="'+href(v['path'])+'">Preserved native output</a></article>')
motion_html=[]
for m in motion:
 if m['score'] is None:motion_html.append('<article><h3>Local motion attempt'+str(m['attempt'])+' — pending direct review</h3><a href="'+href(m['packet'])+'">Exact prepared source/workflow/prompt</a></article>');continue
 packet_path=m['gallery'].removesuffix('/index.html');motion_html.append('<article><h3>Local motion attempt'+str(m['attempt'])+' · '+str(m['score'])+'/5</h3><video controls preload="metadata" src="'+href(packet_path+'/native_output.mp4')+'"></video><p>Every41 frames directly inspected. Alternating rock '+str(m['alternating_panning'])+'; neutral return '+str(m['neutral_return'])+'; hand contact '+str(m['hand_contact'])+'. Source remains4.6. This is a local motion reference; no runtime/cinematic acceptance.</p><a href="'+href(m['gallery'])+'">Every frame with individual written evaluation</a></article>')
intro='''<h1>Geologist artwork: rooted crystals and remaining interaction priorities</h1><p>This is the geology continuation of the open all-job audit. The owner rejected flat vector geology art and the loose-crystal loot ending. Current replacement sources preserve painted lavender/aqua rock, cream cavity rims and crystal growths inside each half. None of the source opinions below establish a complete job pass.</p><p>The new narrow crack exposes only occluded crystal tips; the middle state turns the cavities partly toward the child; the endpoint opens to three rooted crystals in each half. No separate reward sprite falls from the shell. The full endpoint cards now share the same515px base as the closed/intermediate states. Embedded material4.6 and selected static progression/base4.5 provisional remain separate from invitation placement3.8 and remote actor contact2.7.</p><p>Both pan hands now grip the rim in the static source4.6. The new card retains the cap, teal vest, pink shirt, brown pouch, rainbow hair and whole fin. Its tabletop support4.3 still needs refinement. Whole-card translation in the static fixture supplies no wrist/elbow rocking, approach, pickup, release or return. Every local motion frame is reviewed independently below.</p><p>The generated grotto is1672×941 and remains reference-only; it fails native background coverage. Uniform upscaling is not a resolution pass. Static sidebars at1600 show the unchanged inherited aspect presentation. These studies preserve all325 production source bytes and live game input/reward/save behavior.</p><p>All earlier rejected images, withdrawn opinions, hidden/displaced support failures and the failed initial geode capture remain preserved. The corrected capture is separate evidence. Current known all-job register1563 entries/1192 sources includes579 inclusive source priorities and388 unassigned; this register is still incomplete. Source priorities and the per-context table below cannot be collapsed into a global average.</p>'''
links='<nav><a href="../../assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html">All source versions/prompts/provenance</a> · <a href="../job_geode_opening_states_v3_20261001/index.html">Every geode capture attempt</a> · <a href="../job_artwork_refinement_live/ALL_ITEMS.html">Known all-job individual artwork register</a> · <a href="GEOLOGY_CONTEXT_PRIORITIES_V5.json">Exact context-priority data</a></nav>'
style='<!doctype html><meta charset="utf-8"><title>Geologist artwork continuation and individual priorities</title><style>body{font:18px/1.55 system-ui;background:#eef5f4;color:#302949;max-width:1500px;margin:auto;padding:28px}article{background:white;border-radius:14px;padding:22px;margin:28px 0}img,video{display:block;max-width:100%;height:auto;margin:18px auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:9px;border-bottom:1px solid #d2ddd9}nav a{display:inline-block;margin:8px}.note{font-size:15px;color:#554c67}button{font:inherit;padding:12px;margin:10px}</style>'
(out/'GEOLOGY_CONTINUATION_REPORT_V5.html').write_text(style+intro+links+'<h2>Individual current native states and interaction scores</h2><p>Every16 current pan/geode selected view is shown. Source/component/state scores are separate. Unscored means evidence is absent, pending or outside this view.</p>'+''.join(cards)+'<h2>Motion attempts and every ordered frame</h2>'+''.join(motion_html)+'<h2>Every18 preserved ImageGen native source</h2><p>Earlier defects retain their own score/status. Source-only and technical-derivative opinions do not approve a mounted action.</p>'+''.join(source_cards)+'<h2>Next named repairs</h2><ul><li>Geode: supporting invitation placement and local attached hand work; timed opening/return through ordinary routes.</li><li>Panning: tabletop support and clearly articulated alternating rocking/neutral return.</li><li>Other jobs: nursery contact/settling, boxing guard/impact/counter/belt acting, doctor washing/contact/water and remaining ordinary-job phases retain their earlier individual priorities.</li><li>Inspect every unassigned source and current live context; only then prepare the comprehensive final report for owner approval.</li></ul>',encoding='utf-8')
for p in [out/'index.html',b/'audit/job_artwork_refinement_live/index.html']:
 s=p.read_text();banner='<section id="geology-context-report-current"><h2>Current geology written report and individual context priorities</h2><p>Every18 source image and16 current selected native state displayed, with source/placement/contact/motion scores kept separate.312 direct teacher/geology/pan comparisons; current motion attempts and every reviewed frame included. The all-job audit and comprehensive owner report remain open.</p><a href="'+('GEOLOGY_CONTINUATION_REPORT_V5.html' if p.parent==out else '../job_review_v2_20261001/GEOLOGY_CONTINUATION_REPORT_V5.html')+'">Read the illustrated continuation report</a></section>'
 if 'geology-context-report-current' not in s:i=s.index('</h1>')+5;s=s[:i]+banner+s[i:];p.write_text(s,encoding='utf-8')
ledger=b/'design/05_DOC_LEDGER.md';s=ledger.read_text();needle='| `audit/job_review_v2_20261001/GEOLOGY_CONTINUATION_REPORT_V5.html`';line=needle+' | 🟣 | `DRAFT_REVIEW`;18 preserved sources/16 current selected native states with individual separated scores,312 direct static comparisons, and exact per-frame local motion reviews. Source4.6 does not pass weak interaction/placement or incomplete all-job/route/device/child/owner/final report. |';lines=s.splitlines();lines=[line if x.startswith(needle) else x for x in lines];
if not any(x.startswith(needle) for x in s.splitlines()):lines.append(line)
ledger.write_text('\n'.join(lines)+'\n',encoding='utf-8');shutil_path=out/'review_tools/build_geology_context_report_v149.py';shutil_path.write_text(Path(__file__).read_text(),encoding='utf-8')
ip=b/'design/audit_impacts/job-geology-opening-motion-review-checkpoint-20261001.json';d=json.loads(ip.read_text());d['files']=sorted(set(d['files'])|{rel(out/'GEOLOGY_CONTINUATION_REPORT_V5.html'),rel(out/'GEOLOGY_CONTEXT_PRIORITIES_V5.json'),rel(shutil_path),'audit/job_review_v2_20261001/index.html','audit/job_artwork_refinement_live/index.html','design/05_DOC_LEDGER.md'});d['validation'].append(dict(command='Exact source/context evidence hashes and direct-review flags for every18 source and16 current static view',result='PASS',evidence=rel(out/'GEOLOGY_CONTEXT_PRIORITIES_V5.json')+'; each motion attempt status remains separately qualified.'));write(ip,d);allow=b/'tmp/v2_preview_allowed.json';allowed=set(json.loads(allow.read_text()));allowed.update(d['files']);write(allow,sorted(allowed));print(json.dumps(dict(source_images=18,current_static_views=16,direct_motion_frames=sum(x.get('direct_frames',0) for x in motion),report=rel(out/'GEOLOGY_CONTINUATION_REPORT_V5.html'))))
