from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
directory=r/'audit/job_review_v2_20261001/review_tools';source=directory/'build_current_job_item_register_v8.py';target=directory/'build_current_job_item_register_v9.py';assert not target.exists()
s=source.read_text(encoding='utf-8');marker="for q in items.values():\n p=q['path']\n";assert s.count(marker)==1
block="""clean=read('assets_src/imagegen/day2_doctor_wash_clean_result_v1_20261001/ATTEMPT01_REVIEW.json');p=clean['path']
items[p]=dict(id=clean['id'],aliases=[],kind='source',path=p,earlier_sha256=clean['sha256'],historical_source_score=clean['source_score'],evaluation=clean['evaluation'],refinement='Clean finishing source4.5 remains unbound. All58 exact native static sink placements are individually reviewed below4.5; clean result4.0 in the closer fixture. Local rub study4.0/return3.5 is reference only. Refine literal contact and complete wet/rub/rinse/clean/settle/return before accepting the game object.',families=['Day Two washing','Unbound doctor clean-hands source'],original_reports=['assets_src/imagegen/day2_doctor_wash_clean_result_v1_20261001/index.html'],source_qualification=clean['qualification'],preview_path=p,native_reference_observations=[],runtime_binding_state=clean['status'],latest_refinement=dict(report='audit/day_two_wash_contact_study_v1_20261001/attempt_03/index.html',note='All14 closer native static views directly reviewed; clean ending4.0 and washing contact4.2 remain below floor. The source-only4.5 opinion is not mounted/action acceptance.'))
"""
s=s.replace(marker,block+marker);target.write_text(s,encoding='utf-8',newline='\n')
p=subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(target)],cwd=r,check=True,capture_output=True,text=True);print(p.stdout.strip())
counts=json.loads((r/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text(encoding='utf-8'))['counts'];assert counts['registered_items']==1429 and counts['unique_source_files']==1151 and counts['inclusive_current_source_priorities']==556 and counts['unreviewed_current_source']==403
entry=r/'audit/job_review_v2_20261001/index.html';s=entry.read_text(encoding='utf-8').rstrip();s=s.replace('Search1,428 known','Search1,429 known').replace('contains555 source priorities','contains556 source priorities').replace('catalogues1150 source files','catalogues1151 source files')
s=s.replace('HostedCI run36941786030 remains pending','HostedCI run36941786030 failed audit-impact coverage')
s=s.replace('The next refinement will reuse','The next refinement will reuse')
s=s.removesuffix('</main></html>')+'<section><h2>Complete local motion review and hosted coverage correction</h2><p><a href="../../assets_src/local_motion/day2_doctor_wash_rub_study_v1_20261001/index.html">Every41 local doctor rubbing frames</a> are individually reviewed: motion4.0 and return3.5 remain below floor. Native video, individual frames, exact prompt/workflow and rejected history are preserved as reference only.</p><p><a href="../day_two_wash_contact_study_v1_20261001/attempt_03/index.html">All14 closer sink placements</a> complete58 directly reviewed native static views across three attempts. Washing contact4.2 and clean result4.0 remain weak.</p><p><a href="hosted_current_b_failure_v1/RECEIPT.json">Hosted run36941786030 failed</a> at static audit coverage, before game probes. The working expanded impact record was not staged in the earlier checkpoint; the next revision includes that record and this evidence. Anonymous byte verification ofc211 remains valid; no retroactive hosted pass is claimed.</p></section></main></html>'
entry.write_text(s,encoding='utf-8',newline='\n')
remote=r/'audit/job_review_v2_20261001/current_b_remote_v1/index.html';s=remote.read_text(encoding='utf-8');s=s.replace('HostedCI run36941786030 remains pending at this observation.','The earlier pending observation is preserved in PUBLICATION_STATE.json. <a href="../hosted_current_b_failure_v1/RECEIPT.json">Hosted run36941786030 subsequently failed audit-impact coverage</a>, before game probes.');remote.write_text(s,encoding='utf-8',newline='\n')
master=r/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8');old='HostedCI run36941786030, all-owner/global acceptance, integration and release remain pending.';assert s.count(old)==1;s=s.replace(old,'[HostedCI run36941786030 failed audit-impact coverage](job_review_v2_20261001/hosted_current_b_failure_v1/RECEIPT.json) before game probes. The expanded working record was omitted from that commit and is corrected in the next review revision. All-owner/global acceptance, integration and release remain pending.')
marker='## 0. Planning entry\n';assert s.count(marker)==1
note='\nWashing iteration and local motion (2026-10-01): [all14 closer-contact views](day_two_wash_contact_study_v1_20261001/attempt_03/index.html) complete58 directly reviewed native static placements; contact4.2/clean result4.0 remains below floor. [Every41 doctor rubbing reference frames](../assets_src/local_motion/day2_doctor_wash_rub_study_v1_20261001/index.html) is individually scored; motion4.0 and return3.5 remain weak. The searchable register now has1429 entries, including1151 source files,556 inclusive priorities and403 unassigned source opinions. These counts include unbound/rejected/reference sources and do not claim exhaustive current live weak objects. [Motion impact](../design/audit_impacts/job-doctor-local-rub-study-20261001.json). No finding closure, runtime action or owner acceptance.\n'
s=s.replace(marker,marker+note);master.write_text(s,encoding='utf-8',newline='\n')
ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8');s=s.replace('Same-tree ancestry headfb03 hostedCI remains pending;','Same-tree ancestry headfb03 hostedCI failed audit-impact coverage before probes;')
rows=[('audit/day_two_wash_contact_study_v1_20261001/attempt_03/index.html','CANDIDATE; all14 closer native static views directly reviewed, washing contact4.2/clean result4.0/composition4.1 below floor. Source artwork preserved; complete action and owner/device/child acceptance open.'),('assets_src/local_motion/day2_doctor_wash_rub_study_v1_20261001/index.html','MOTION_REFERENCE_REVIEW; developed unchanged local ComfyUI quick GGUF render passes machine checks. All41 native frames directly scored: reference motion4.0/return3.5 below floor. No runtime or cinematic delivery acceptance; originals and failed action retained.')]
for path,description in rows:assert path not in s;s+='\n| `'+path+'` | 🟣 | `'+description.split(';')[0]+'`; '+description.split(';',1)[1].strip()+' |\n'
ledger.write_text(s,encoding='utf-8',newline='\n')
record=r/'design/audit_impacts/job-review-current-remote-receipt-20261001.json';d=json.loads(record.read_text(encoding='utf-8'));d['scope']+=' Correct the previously omitted expanded staged coverage record after hosted failure; update current register/authority and preserve all later wash/static/motion evidence separately from c211 verification.'
d['files']=sorted(set(d['files'])|{'design/audit_impacts/job-review-separate-v2-20261001.json','audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/all_items.html','audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/STATUS.json','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v9.py','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v9.py'})
receipt=r/'audit/job_review_v2_20261001/STAGING_COVERAGE_CORRECTION_V1.json'
old=json.loads(subprocess.check_output(['git','show','fb03e0ac3dda1658e9ea188d33cc6e084871642b:design/audit_impacts/job-review-separate-v2-20261001.json'],cwd=r));current=json.loads((r/'design/audit_impacts/job-review-separate-v2-20261001.json').read_text(encoding='utf-8'))
data={'status':'CORRECTION_PREPARED_GATES_PENDING','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'failed_head':'fb03e0ac3dda1658e9ea188d33cc6e084871642b','failed_run':36941786030,'committed_coverage_entries':len(old['files']),'working_expanded_coverage_entries':len(current['files']),'cause':'The expanded working impact record was not staged before the content commit. Hosted static coverage correctly rejected omitted entries before game probes.','repair':'Stage the expanded record in the next reversible review revision. Verify current authority/development/no-regression gates, then compare every staged changed path to coverage and verify the committed impact bytes immediately after commit. Hosted retry stays independent.','qualification':'No scanner, workflow, sourceA manifest, threshold or CI checker change; failed hosted evidence remains preserved. Original c211 exact-byte verification is unchanged.'}
receipt.write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8');shutil.copyfile(__file__,directory/'executed_prepare_register_v9_and_authority_v49.py');d['files']=sorted(set(d['files'])|{receipt.relative_to(r).as_posix(),(directory/'executed_prepare_register_v9_and_authority_v49.py').relative_to(r).as_posix()});record.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
allow=r/'tmp/v2_preview_allowed.json';a=set(json.loads(allow.read_text(encoding='utf-8')));a.update(d['files']);allow.write_text(json.dumps(sorted(a),indent=2)+'\n',encoding='utf-8')
print('AUTHORITY_CURRENT; source counts include unbound/rejected/reference items, no global acceptance.')
