from pathlib import Path
import json,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
family=r/'audit/job_review_v2_20261001';tools=family/'review_tools'
counts=json.loads((r/'audit/job_artwork_refinement_live/ALL_ITEMS.json').read_text())['counts']
p=r/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');s=s.replace('1143 source files, 240 pose cells and6 current pool prop regions (1389 addressable entries). 482 source opinions','1149 source files, 240 pose cells and6 current pool prop regions (1395 addressable entries). 488 source opinions')
for row in s.splitlines():
 if row.startswith('Known individual job-art register'):
  new=row.replace('No new visual opinion, complete-action pass, finding closure or owner acceptance follows from registration.','Six fresh doctor wash drafts now have separately recorded source opinions; attempt6 reaches source4.5 and remains unbound. No complete-action pass, finding closure or owner acceptance follows from registration.').replace('../design/audit_impacts/day-two-boxing-live-refinement-v1-20261001.json','../design/audit_impacts/job-review-separate-v2-20261001.json');s=s.replace(row,new)
s=s.replace('Current325-file wholeCI passes82/82 with unchanged literal hashes; earlier81/82 failures are preserved.','The sourceA325-file wholeCI boundary passed82/82 with unchanged literal hashes before its larger manifests were sealed; earlier81/82 failures and the distinctV2 failed full run remain preserved.')
new='Distinct V2 review checkpoint (2026-10-01): [current illustrated entry](job_review_v2_20261001/index.html) preserves immutable sourceA maps and original five manifests. Its first local full suite records80 passing probes and two process127 failures; both unchanged probes pass direct isolated retries, but the complete suite remains failed. [Washing library](day_two_wash_complete_action_v1_20261001/index.html) exposes1520 frames in8 task-open hold fixtures and108 directly reviewed keys. Complete ordinary routes/contact/timing remain pending; doctor sampled workflow2.7 and nursery2.2 remain weak. [Six doctor source drafts](../assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/index.html) preserve five rejections and one unbound4.5 source candidate. Current publication, hosted machine evidence and all-owner/global acceptance remain pending. [Impact](../design/audit_impacts/job-review-separate-v2-20261001.json). No finding closure.\n\n'
assert 'Distinct V2 review checkpoint (2026-10-01):' not in s;s=s.replace('# Mermaid Roshan: Reef of Light — game-wide master audit\n','# Mermaid Roshan: Reef of Light — game-wide master audit\n\n'+new,1);p.write_text(s,encoding='utf-8')
p=family/'index.html';s=p.read_text();s=s.replace('Search1,389','Search1,395').replace('contains482 source priorities','contains488 source priorities').replace('catalogues1143 source files','catalogues1149 source files').replace('complete washing sequences are unreviewed.','108 selected washing keys are directly reviewed, while the remaining frames and complete ordinary actions remain unreviewed.');s=s.replace('Current V2 gates and publication remain pending;','Initial V2 authority/development gates pass and the full suite records80/82 passing probes, with two process127 failures preserved. Both unchanged probes pass direct retries; the full suite remains failed. V2 publication and hosted evidence remain pending;');p.write_text(s,encoding='utf-8')
original=tools/'run_v2_full_ci_v1.py';retry=tools/'run_v2_full_ci_retry_v2.py'
assert not retry.exists();code=original.read_text().replace('full_ci_candidate_v1','full_ci_candidate_retry_v2').replace('Official Godot4.7.2 unmodified distinctV2 scripts/ci.sh','Official Godot4.7.2 unmodified distinctV2 full retry2 scripts/ci.sh');retry.write_text(code,encoding='utf-8')
subprocess.run(['C:/Users/Peter/AppData/Local/Python/bin/python.exe','-X','utf8','-B',str(retry),'--prepare'],cwd=r,check=True)
shutil.copyfile(Path(__file__),tools/'executed_prepare_review_publication_and_ci_retry_v8.py')
# The V5 checker extends V4 to every captured wash frame and the new doctor report.
old=family/'resource_checks_v3/executed_check_distinct_review_resources_v4.py';checker=tools/'check_distinct_review_resources_v5.py'
code=old.read_text().replace("resource_checks_v3';assert", "resource_checks_v4';assert").replace("'audit/day_two_boxing_live_refinement_v1_20261001/index.html']", "'audit/day_two_boxing_live_refinement_v1_20261001/index.html','audit/day_two_wash_complete_action_v1_20261001/index.html','assets_src/imagegen/day2_doctor_wash_pose_v1_20261001/index.html']")
needle='def head(p):'
addition="wash=json.loads((r/'audit/day_two_wash_complete_action_v1_20261001/FRAME_VIEWER_DATA_V2.json').read_text())\npaths.update('audit/day_two_wash_complete_action_v1_20261001/local_hold_attempt_02/native_frames/'+x['path'] for x in wash['frames'])\n"
assert needle in code;code=code.replace(needle,addition+needle).replace('executed_check_distinct_review_resources_v4.py','executed_check_distinct_review_resources_v5.py').replace("'command':'check_distinct_review_resources_v2.py'","'command':'check_distinct_review_resources_v5.py'").replace('resource_checks_v3/RECEIPT.json','resource_checks_v4/RECEIPT.json');checker.write_text(code,encoding='utf-8')
p=r/'design/audit_impacts/job-review-separate-v2-20261001.json';d=json.loads(p.read_text());d['files']=sorted(set(d['files']+[x.relative_to(r).as_posix() for x in family.rglob('*') if x.is_file()]+['audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md','ASSET_LICENSES.md']));p.write_text(json.dumps(d,indent=2)+'\n',encoding='utf-8')
paths=set(d['files'])|{p.relative_to(r).as_posix() for p in (r/'assets_src/imagegen/day2_doctor_wash_pose_v1_20261001').rglob('*') if p.is_file()}
paths={x for x in paths if (r/x).is_file()}
assert all(not x.startswith(('.git/','.secrets/','.codex/','.claude/','.github/')) and Path(x).name.lower() not in {'agents.md','security.md','claude.md'} for x in paths)
stage=r/'tmp/v2_exact_owned_stage_v8.bin';stage.write_bytes(b'\0'.join(x.encode() for x in sorted(paths))+b'\0')
subprocess.run(['git','add','-f','--sparse','--pathspec-from-file='+str(stage),'--pathspec-file-nul'],cwd=r,check=True)
print(json.dumps({'counts':counts,'exact_owned_paths_staged':len(paths),'full_retry':'Prepared only; source must remain frozen during run','resource_checker':str(checker)}))
