from pathlib import Path
import datetime,hashlib,html,json,posixpath,shutil,subprocess
from PIL import Image
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
out=r/'audit/job_geode_runtime_v1_20261001';impact=r/'design/audit_impacts/job-geode-painted-runtime-20261001.json'
write=lambda p,d:p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
stamp=datetime.datetime.now(datetime.timezone.utc).isoformat()
family=r/'assets_src/imagegen/geologist_painted_rebuild_v1_20261001'
planned=['audit/job_review_v2_20261001/review_tools/record_geode_runtime_review_v161.py','audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v19.py','audit/job_artwork_refinement_live/review_tools/build_current_job_item_register_v19.py',
 'audit/job_artwork_refinement_live/ALL_ITEMS.json','audit/job_artwork_refinement_live/all_items.html','audit/job_artwork_refinement_live/index.html','audit/job_artwork_refinement_live/STATUS.json','audit/job_review_v2_20261001/index.html','audit/job_review_v2_20261001/GEOLOGY_CONTINUATION_REPORT_V5.html',
 'assets_src/imagegen/geologist_painted_rebuild_v1_20261001/REVIEW_V7.json','assets_src/imagegen/geologist_painted_rebuild_v1_20261001/index.html','audit/job_geode_runtime_v1_20261001/attempt_03/REVIEW.json','audit/job_geode_runtime_v1_20261001/ARTWORK_ITEMS.json']
d=json.loads(impact.read_text());d['files']=sorted(set(d['files'])|set(planned));d['scope']+=' Record every36 directly inspected current production native view with separate object/panel/room/contact/visibility scores, and expose every90 archived native view honestly (only43 currently directly inspected). Add four exact new runtime PNG source entries to the searchable known-item register and update only their binding facts. Repair one verified GitHub-case-sensitive ALL_ITEMS.html link to the actual tracked all_items.html path; originalG revision preserves the old report bytes.';write(impact,d)
views=[];events=[]
for width in [1280,1600]:
 cap=json.loads((out/'attempt_03'/('CAPTURE_'+str(width)+'.json')).read_text())
 assert len(cap['views'])==18
 events += [dict(x,viewport_width=width) for x in cap['events']]
 for x in cap['views']:
  x=dict(x);p=out/'attempt_03'/x['path'];assert Image.open(p).size==(width,720)
  phase=x['phase'];state=x['state'];scores={'room_finish':2.8,'object_finish':None,'invitation':None,'work_panel':None,'actor_identity':4.6,'actor_work_contact':None,'celebration_visibility':None,'scene_coherence':3.4,'selected_static_progression':None,'complete_timed_action':None}
  if state=='invitation':
   scores['invitation']={'RIVER':2.9,'FOSSIL':3.0,'PAN':3.0,'GEODE':3.4}[phase]
   text={'RIVER':'The generic halo floats above Roshan and the minimal mural; it does not depict a spring or readable dig site.','FOSSIL':'Halo locates a generic flat table, with little illustrated fossil identity.','PAN':'The invitation still displays a flat layered rock rather than the pan used by this task.','GEODE':'A halo above the imp and flat mural crystals remains the invitation; this is not the new painted closed geode.'}[phase]
   text+=' Dark striped procedural room2.8 and abstract work landmarks remain priorities. Full-finned idle actor is clear4.6; no new geode source is visible here.'
  else:
   scores['work_panel']=4.0
   if state!='earned_completion':scores['actor_work_contact']=2.7
   else:scores['celebration_visibility']=4.6
   if phase=='GEODE':
    scores['object_finish']=4.6;scores['scene_coherence']=4.0
    if state not in ['task_open','five_seams_ready']:scores['selected_static_progression']=4.5
    text={'task_open':'Closed shell has broad brushed lavender bands, a clear plum rim and a large readable seam. Five yellow markers are visible on the actual object.',
     'five_seams_ready':'All five earned markers become aqua while the shell stays closed; a drag is still required to reveal the interior.',
     'early_crack':'The narrow authored crack shows cream cavity rims and occluded cyan/lilac tips; no detached mineral layer appears.',
     'middle_open':'Oblique cavities expose three rooted crystals per half. Color order remains consistent; both shell bases stay on the same515 logical baseline.',
     'full_interior_before_award':'Both complete cavities show the six rooted crystals. The object is fully illustrated before the final120px progress threshold; half widths retain source proportions.',
     'earned_completion':'The fully exposed interiors retain their rooted crystals. Roshan is now visible at the task rest and uses the existing clapping pose, with no extra crystal in her hand.'}[state]
    text+=' Geode finish/embedded ownership4.6 and sampled four-state/base progression4.5 provisional are separate from old panel4.0, dark procedural room2.8 and remote crawling work contact2.7. Full intervening timed frames, castle/story entry, device, child and owner acceptance remain open.'
   elif phase=='RIVER':
    scores['object_finish']=3.8 if state=='earned_completion' else 3.5
    text='The intentional touch route creates a legible connected aqua channel, but its straight rectangular strips and repeated circular junctions read as a diagram rather than painted soil/water. '+('The complete channel and now-visible cheer are retained.' if state=='earned_completion' else 'The blank work field and two endpoint rings give little environmental context.')+' Object3.8 at completion /3.5 initially, old panel4.0 and room2.8 remain priorities. Roshan crawls remotely instead of digging with visible hand contact2.7.'
   elif phase=='FOSSIL':
    if state=='task_open':scores['cover_finish']=3.2;text='A uniform opaque brown rectangle covers the fossil completely. The unseen fossil receives no visible object score; cover material3.2 is flat and the brush demonstration remains remote from Roshan.'
    else:scores['object_finish']=3.8;scores['assembly_readability']=3.9;text='The spiral and three conserved puzzle thirds are readable, but the active fossil is still the old flat SVG. Broad cream/plum lines do not supply the missing painted material. Source3.8 / assembly3.9 remain priorities; the new painted fossil draft is still unbound.'
    text+=' Old panel4.0, room2.8 and remote work contact2.7 remain separate. The actual phase advances only after deliberate assembly; celebration remains visible after the rest repair.'
   else:
    scores['object_finish']=4.0;scores['grain_finish']=3.8;scores['mineral_finish']=3.4 if state!='task_open' else None
    text='The active pan remains a procedural ellipse with broad navy rings and aqua water. Grains are simple discs3.8; earned minerals are outlined polygons3.4. Pan finish4.0 and remote floor-crawling contact2.7 remain priorities. The source4.6 painted pan and connected gripping draft have not been bound into this production state. Correct source provenance does not approve these current objects.'
   if state=='earned_completion':text+=' The actor stays outside the opaque work panel; visible cheer4.6 repairs the observed disappearance, without claiming contact or complete acting.'
  x.update(path='attempt_03/'+x['path'],sha256=sha(p),direct_native_review=True,reviewed_utc=stamp,scores=scores,evaluation=text,qualification=x['qualification']+' Main HUD/player are suppressed for career entry fixture; no complete castle-hub/story route or target-device rendering claim. All36 current screenshots directly inspected; intervening timed frames not graded.',owner_acceptance=None)
  views.append(x)
review={'status':'ALL36_CURRENT_NATIVE_PRODUCTION_VIEWS_DIRECTLY_REVIEWED_WITH_OPEN_PRIORITIES','reviewed_utc':stamp,'source_boundary':'full_ci_v2/SOURCE_BEFORE.json','views':views,'events':events,'source_finish':4.6,'geode_rooted_interior':4.6,'sampled_four_state_progression':4.5,'complete_timed_action':None,'owner_acceptance':None,'current_runtime_source_files':334,'previous_archives':{'root':{'captured':18,'directly_reviewed':6,'record':'ATTEMPT_01_BASELINE_REVIEW.json'},'attempt_02':{'captured':36,'directly_reviewed':1,'note':'Only1280 geode completion directly checked before choosing the existing clapping pose; remaining35 have no new individual scores.'}},'qualification':'Actual world/surface/art through ordinary viewport invitation/approach/work and phase advance, entry fixture isolated. This score record is not all-game quality, full timed motion, castle/story traversal, physical device, child, owner, integration or final comprehensive report acceptance.'}
write(out/'REVIEW.json',review);write(out/'attempt_03/REVIEW.json',review)
art_items=[]
for name,state in [('closed.png','closed shell'),('early_crack.png','narrow opening'),('middle_open.png','oblique exposed cavities'),('open_embedded.png','fully exposed rooted interiors')]:
 path='assets/opera/worlds/geology/painted_geode_v1_20261001/'+name
 art_items.append({'id':'GEO-RUNTIME-'+name.upper().replace('.PNG',''),'path':path,'sha256':sha(r/path),'source_finish':4.6,'mounted_object_finish':4.6,'complete_action_score':None,'evaluation':'Broad painted lavender/plum shell, cream cavity lining and cyan/lilac embedded crystals preserve the source state. Exact intact technical derivative copied; source contours and material unchanged. '+state+' is individually visible in the current actual production captures.','runtime_binding':'OperaGeologySurface production candidate, topic branch only','evidence':[x['path'] for x in views if x['phase']=='GEODE' and x['state']!='invitation'],'owner_acceptance':None})
for side,color,role in [('left','cyan','tall rear crystal'),('left','lilac','middle crystal'),('left','cyan','small front crystal'),('right','lilac','tall rear crystal'),('right','cyan','middle crystal'),('right','cyan','small front crystal')]:
 art_items.append({'id':'GEO-EMBEDDED-'+side.upper()+'-'+str(sum(q['id'].startswith('GEO-EMBEDDED-'+side.upper()) for q in art_items)+1),'path':'assets/opera/worlds/geology/painted_geode_v1_20261001/open_embedded.png','role':side+' cavity '+color+' '+role,'source_finish':4.6,'mounted_object_finish':4.6,'evaluation':'Root visibly belongs inside this cream-lined cavity; facet colors and broad value bands stay consistent across oblique/full authored states. This is an embedded painted component, not an independently collected runtime prop.','independent_runtime_object':False,'complete_action_score':None,'owner_acceptance':None})
write(out/'ARTWORK_ITEMS.json',{'status':'TEN_INDIVIDUALLY_NAMED_GEODE_ART_COMPONENTS_REVIEWED','items':art_items,'qualification':'Four copied source states and six named embedded components; shared PNG pixels are not duplicated runtime objects or ten unique images. Room, invitation, panel and actor contact remain individually below floor in REVIEW.json.'})
esc=html.escape
parts=['<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Geode and full geology career — production review</title><style>body{background:#edf7f6;color:#302846;font:17px/1.5 system-ui;max-width:1300px;margin:auto;padding:25px}a{color:#325c8b}article{background:#fffaf0;padding:18px;margin:20px 0;border-radius:16px}img{max-width:100%;height:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:18px}.phone img{max-width:480px}pre{white-space:pre-wrap;overflow-wrap:anywhere}summary{cursor:pointer}button,input{font:inherit}small{display:block}.notice{background:#d7ebea;padding:20px;border-radius:16px}</style></head><body><h1>Geode and the full geology career</h1><p>The game candidate now opens a painted geode to reveal crystals rooted inside both cavities. Four unchanged reviewed source states are bound at separate runtime paths. The first complete touch run also exposed an actor hidden behind the work panel; that defect is preserved below and her celebration rest is corrected.</p><p class="notice">All36 current production screenshots, spanning every ordinary RIVER/FOSSIL/PAN/GEODE phase at1280×720 and1600×720, were directly inspected. Geode object finish4.6; sampled four-state/base progression4.5 provisional. Room2.8, invitation2.9–3.4, panel4.0, remote actor contact2.7 and flat fossil/pan3.8–4.0 remain priorities. This is a continuation report, not the owner-approved comprehensive final report. Career entry is staged, main HUD suppressed; full castle/story entrances, intervening motion frames, device/child/owner acceptance remain open.</p><p><a href="REVIEW.json">Every individual evaluation</a> · <a href="ARTWORK_ITEMS.json">Four states and six embedded crystal components</a> · <a href="PROVENANCE.json">Exact-byte source provenance</a> · <a href="full_ci_v2/RECEIPT.json">Fresh334-source entire-suite receipt</a> · <a href="../job_artwork_refinement_live/all_items.html">All known job items</a> · <a href="../job_review_v2_20261001/GEOLOGY_CONTINUATION_REPORT_V5.html">Earlier illustrated drafts and all123 panning reference frames</a></p><div id="machine" class="notice">Fresh full suite result pending; source scores do not establish a green run.</div><h2>Current four-state reveal</h2><p>Select an actual production view. The preview changes between intact archived frames; it creates no delivery pixels or motion.</p><label>State <input id="sequence" type="range" min="0" max="4" value="4"></label><button id="phone">Toggle phone-size display</button><figure id="stage"><img id="reveal" src="attempt_03/native_views/geologist_1280_geode_earned_completion.webp" alt="Painted geode reveals its rooted interiors"><figcaption id="caption">Earned reveal: roots remain in the two cavities; Roshan claps.</figcaption></figure><h2>Individual artwork</h2><div class="grid">']
for x in art_items[:4]:parts.append('<article><h3>'+esc(x['id'])+'</h3><img src="../../'+esc(x['path'])+'" alt="'+esc(x['id'])+'"><p>Source/mounted object4.6; full action unassigned.</p><p>'+esc(x['evaluation'])+'</p><small>'+esc(x['sha256'])+'</small></article>')
parts.append('</div><h2>Every current native view</h2>')
for x in views:parts.append('<article id="'+esc(x['id'])+'"><h3>'+esc(x['id'])+'</h3><a href="'+esc(x['path'])+'"><img loading="lazy" src="'+esc(x['path'])+'" alt="'+esc(x['id'])+'"></a><p>'+esc(x['evaluation'])+'</p><pre>'+esc(json.dumps(x['scores'],ensure_ascii=False))+'</pre><small>Native SHA-256 '+x['sha256']+' · all scores are bounded drafting opinions.</small></article>')
parts.append('<h2>Preserved earlier attempts</h2><p>First18-view run: six directly inspected, including the invisible completion actor. Intermediate36-view run: one completion directly inspected; the remaining views are available but unscored. None is silently promoted to current acceptance.</p>')
for lane,widths,direct in [('',[1280],6),('attempt_02/',[1280,1600],1)]:
 parts.append('<details><summary>'+('First captured boundary' if not lane else 'Visible celebration before clapping selection')+'</summary><div class="grid">')
 for width in widths:
  cap=json.loads((out/lane/('CAPTURE_'+str(width)+'.json')).read_text())
  for x in cap['views']:parts.append('<article><a href="'+lane+esc(x['path'])+'"><img loading="lazy" src="'+lane+esc(x['path'])+'" alt="'+esc(x['id'])+'"></a><small>'+esc(x['id'])+' · earlier boundary; direct review count stated above.</small></article>')
 parts.append('</div></details>')
parts.append('''<script>const frames=['task_open','early_crack','middle_open','full_interior_before_award','earned_completion'];document.querySelector('#sequence').oninput=e=>{const v=frames[+e.target.value];document.querySelector('#reveal').src='attempt_03/native_views/geologist_1280_geode_'+v+'.webp';document.querySelector('#caption').textContent=v.replaceAll('_',' ')};document.querySelector('#phone').onclick=()=>document.querySelector('#stage').classList.toggle('phone');fetch('full_ci_v2/RECEIPT.json').then(x=>x.json()).then(d=>document.querySelector('#machine').textContent=d.status+'; '+(d.probe_results?.length??0)+' trusted probe results; '+(d.source_checks?.length??334)+' source checks. Machine verification is separate from visual/device/child/owner acceptance.').catch(()=>{});</script></body></html>''')
(out/'index.html').write_text(''.join(parts),encoding='utf-8',newline='\n')
v7=json.loads((family/'REVIEW_V6.json').read_text());v7['reviewed_utc']=stamp;v7['runtime_binding_supplement']={'report':'audit/job_geode_runtime_v1_20261001/index.html','current_native_views_directly_reviewed':36,'runtime_states':art_items[:4],'qualification':'Four selected geode sources bound on candidate work branch only. Source opinions unchanged; other painted drafts remain unbound and all surrounding priorities remain open.'}
for x in v7['items']:
 if x['path'] in [q['source_path'].replace('/whole_canvas_1024.png','/native.png') for q in json.loads((out/'PROVENANCE.json').read_text())['items']]:
  x['status']='SELECTED_SOURCE_BOUND_IN_RUNTIME_CANDIDATE';x['runtime_review']='audit/job_geode_runtime_v1_20261001/index.html';x['qualification']+=' Four-state production candidate now rendered through ordinary touch route; surrounding contact/room/motion/owner acceptance still open.'
write(family/'REVIEW_V7.json',v7)
for target,rel in [(family/'index.html','../../../audit/job_geode_runtime_v1_20261001/index.html'),(r/'audit/job_review_v2_20261001/index.html','../job_geode_runtime_v1_20261001/index.html'),(r/'audit/job_artwork_refinement_live/index.html','../job_geode_runtime_v1_20261001/index.html')]:
 s=target.read_text(encoding='utf-8');banner='<section id="geode-production-current"><h2>Current actual geode game candidate</h2><p><a href="'+rel+'">Every36 current native production view and individual written evaluation</a>: rooted geode4.6, sampled progression4.5 provisional, visible clapping celebration4.6. Actual room2.8, remote contact2.7 and flat fossil/pan/invitations remain priorities. New source boundary requires its own334-source fresh complete suite. All90 archived captures exposed honestly;43 direct current/earlier reviews, not90. Final all-job report and owner approval remain open.</p></section>'
 if '<body>' in s:s=s.replace('<body>','<body>'+banner,1)
 else:
  i=s.find('<body');j=s.find('>',i);s=s[:j+1]+banner+s[j+1:]
 target.write_text(s,encoding='utf-8',newline='\n')
p=r/'audit/job_review_v2_20261001/GEOLOGY_CONTINUATION_REPORT_V5.html';s=p.read_text(encoding='utf-8');assert 'ALL_ITEMS.html' in s;s=s.replace('ALL_ITEMS.html','all_items.html');p.write_text(s,encoding='utf-8',newline='\n')
# Preserve source-only inventory semantics: mounted/context grades live in the
# inspectable native report, not a global source average.
source=(r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v18.py').read_text(encoding='utf-8').replace('REVIEW_V6.json','REVIEW_V7.json').replace('job-review-separate-v2-20261001.json','job-geode-painted-runtime-20261001.json')
inject='''# Four copied geode runtime candidates; every source and native state directly inspected.
for name in ['closed.png','early_crack.png','middle_open.png','open_embedded.png']:
 p='assets/opera/worlds/geology/painted_geode_v1_20261001/'+name;actual=hashlib.sha256((r/p).read_bytes()).hexdigest()
 items[p]=dict(id='GEO-RUNTIME-'+name.upper().replace('.PNG',''),aliases=[],kind='source',path=p,earlier_sha256=actual,historical_source_score=4.6,latest_source_score=4.6,latest_source_sha256=actual,evaluation='Exact copied painted geode derivative retains broad lavender/plum/cream material and rooted cyan/lilac interiors. This runtime source and all36 current ordinary-touch native views directly inspected; geode object4.6, room2.8/contact2.7/old panel4.0 remain separately belowfloor.',refinement='Continue remote actor contact, actual invitation/room and full timed opening; do not redraw passing source pixels to repair a staging defect.',families=['Geologist','Actual production geode candidate'],original_reports=['audit/job_geode_runtime_v1_20261001/index.html'],source_qualification='Current source4.6; production work-branch candidate only; mounted/action/context scores separate; no device/child/owner/all-game acceptance.',preview_path=p,native_reference_observations=[],runtime_binding_state='PRODUCTION_CANDIDATE_TOPIC_ONLY',latest_refinement=dict(report='audit/job_geode_runtime_v1_20261001/index.html',note='Every36 current production view; rooted reveal4.6, static/base progression4.5 provisional, remote contact2.7 and room2.8 remain priorities.'))
'''
assert 'for q in items.values():' in source;source=source.replace('for q in items.values():',inject+'\nfor q in items.values():',1)
(r/'audit/job_review_v2_20261001/review_tools/build_current_job_item_register_v19.py').write_text(source,encoding='utf-8',newline='\n')
with (r/'ASSET_LICENSES.md').open('a',encoding='utf-8',newline='\n') as f:
 f.write('\n<!-- Actual geode career captures90; current36 directly inspected, earlier7 direct. -->\n')
 for p in sorted(out.rglob('*.webp')):f.write('| `'+p.relative_to(r).as_posix()+'` | Official Godot4.7.2 native Mobile desktop rendering of project-owned/generated artwork | `tools/capture_geode_runtime_route.gd`; exact source/attempt receipts | Native lossless screenshot, no pixel editing; first18/intermediate36/current36 source boundaries preserved. SHA-256 `'+sha(p)+'`. |\n')
p=r/'audit/MASTER_AUDIT_2026-08-09.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();lines=[('Painted geode production review (2026-10-01): [all36 current native views](job_geode_runtime_v1_20261001/index.html) directly inspected across ordinary four-phase viewport-input career progression at1280/1600. Four reviewed sources bound at separate runtime paths: rooted interior4.6/sampled progression4.5 provisional. An actual first-run completion hid Roshan behind the work panel; preserved18-view baseline and intermediate36 views, task-rest repair/current visible clapping4.6. Room2.8, invitation2.9–3.4, remote work2.7, flat fossil/pan remain priorities. Fresh334-source whole suite pending; prior325 source result no longer validates changed runtime. Castle/story entry, intervening frames/device/child/owner/all-job final report open. [Impact](../design/audit_impacts/job-geode-painted-runtime-20261001.json). No closure/integration/release.' if line.startswith('Painted geode production candidate (2026-10-01):') else line) for line in lines];p.write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
p=r/'design/05_DOC_LEDGER.md';s=p.read_text(encoding='utf-8');lines=s.splitlines();lines=[('| `audit/job_geode_runtime_v1_20261001/index.html` | 🟣 | `CANDIDATE`; actual four-phase viewport-input career at both widths, all36 current native views directly inspected. Rooted geode4.6/static progression4.5 provisional; first completion actor disappearance preserved and task rest repaired/current clapping4.6. Room2.8/contact2.7/flat siblings remain priorities; new334-source entire suite pending. Earlier54 native archives only7 direct, exposed without acceptance. No castle/story entry, full timed motion/device/child/owner/integration/final report acceptance. |' if '`audit/job_geode_runtime_v1_20261001/index.html`' in line else line) for line in lines];p.write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
d=json.loads(impact.read_text());d['validation'].append({'command':'Direct original native current production artwork/context review all36 views at1280/1600','result':'PASS','evidence':'audit/job_geode_runtime_v1_20261001/REVIEW.json; PASS means inspection coverage only. Object4.6/rooted semantics4.6/selected progression4.5, room2.8/contact2.7 remain failed quality criteria.'});d['files']=sorted(set(d['files'])|{p.relative_to(r).as_posix() for p in out.rglob('*') if p.is_file()});write(impact,d)
shutil.copyfile(Path(__file__),r/'audit/job_review_v2_20261001/review_tools/record_geode_runtime_review_v161.py')
print('All36 current native views individually scored;90 archived views displayed honestly; four runtime source entries prepared.')
