from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
r=Path('C:/Users/Peter/.codex/worktrees/job-art-review-v2-20261001/mermaid-roshan-reef')
a=Path('C:/Users/Peter/Documents/mermaid-roshan-reef/tmp/day2_graphics_audit_20260930')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
raw=r/'tmp/current_b_remote_v33';out=r/'audit/job_review_v2_20261001/current_b_remote_v1'
assert not out.exists();result=json.loads((raw/'attempt_01/RESULT.json').read_text(encoding='utf-8'))
assert result['status']=='PASS_ALL_IMMUTABLE_CURRENT_B_BYTES' and result['required_files']==result['verified_files']==13534 and result['failures']==[]
index=r/'audit/job_review_v2_20261001/CURRENT_B_FILES_V1.json'
assert sha(index)==result['manifest_sha256']=='76f46664a2e4967161593fe831ef9024dad9a8dfc4a191b34652b6d512691798'
b=result['revision'];m='fb03e0ac3dda1658e9ea188d33cc6e084871642b';source='8e41deaf34f925869395cd8ab0affefe89f89ab5'
def git(*args):return subprocess.check_output(['git',*args],cwd=r,text=True).strip()
assert git('rev-parse',b+'^{tree}')==git('rev-parse',m+'^{tree}')==result['tree']
assert git('diff','--name-only',b,m)==''
assert git('show','-s','--format=%P',m).split()==[b,source]
assert git('ls-remote','--heads','origin','codex/job-art-review-v2-20261001').split()[0]==m
impact=r/'design/audit_impacts/job-review-current-remote-receipt-20261001.json'
d={'id':'job-review-current-remote-receipt-20261001','scope':'Archive complete anonymous byte verification of immutable currentB c211, distinguish the unchanged-tree published ancestry headfb03 and hosted CI pending state, and connect reversible wash study/clean source evaluations. Historical sourceA failures and original manifests remain unchanged.','baseline':m,'rules':['DL-AUTH-05','DL-AUTH-06','DL-AUTH-07','DL-ASSET-04','DL-VIS-07','DL-VIS-08','DL-QA-03','DL-QA-09'],'findings':[],'no_findings_reason':'Publication and traceability evidence only. No new game defect is invented, no existing finding is closed and no visual or runtime acceptance is claimed.','files':[],'validation':[{'command':'Anonymous normal-TLS immutable GET and SHA256 of every declared currentB file','result':'PASS','evidence':'audit/job_review_v2_20261001/current_b_remote_v1/RESULT.json;13534/13534 and3962010841 payload bytes, empty failures.'},{'command':'Git content-tree and published ancestry verification','result':'PASS','evidence':'audit/job_review_v2_20261001/current_b_remote_v1/PUBLICATION_STATE.json;fb03 andc211 trees identical; sourceA original manifest commits retained.'},{'command':'Hosted Probe suite run36941786030 on exact published fb03','result':'PENDING','evidence':'https://github.com/Ebonyks/mermaid-roshan-reef/actions/runs/36941786030; observed in progress, no hosted pass claimed.'}],'acceptance_gaps':'Remote receipt proves immutable source/review bytes, not all-source graphics scores, full-action/native-device/child/owner acceptance, strict2D satisfaction, integration or release.'}
write(impact,d)
out.mkdir()
for sourcepath,name in [(raw/'CHECKPOINT_IDENTITY.json','CHECKPOINT_IDENTITY.json'),(raw/'FETCH_JOURNAL.jsonl','FETCH_JOURNAL.jsonl'),(raw/'attempt_01/RESULT.json','RESULT.json'),(a/'tmp/verify_current_b_remote_bytes_v33.py','executed_verify_current_b_remote_bytes_v33.py')]:
 shutil.copyfile(sourcepath,out/name);assert sha(sourcepath)==sha(out/name)
shutil.copyfile(__file__,out/'executed_archive_current_remote_receipt_v40.py')
publication={'status':'PUBLISHED_REVIEW_BYTES_VERIFIED_HOSTED_PENDING','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'repository':'Ebonyks/mermaid-roshan-reef','branch':'codex/job-art-review-v2-20261001','published_head':m,'content_commit':b,'tree':result['tree'],'ancestry_only_merge_parents':[b,source],'changed_project_files_between_content_and_ancestry_head':[],'access_mode':result['access_mode'],'entry':result['entry'],'immutable_tree':'https://github.com/Ebonyks/mermaid-roshan-reef/tree/'+b,'direct_manifest':result['manifest'],'verification_receipt':'RESULT.json','first_push_failure':'First branch creation failed withHTTP500/RPCdisconnect. It does not identify the exact provider cause. A transient push-negotiate retry still attempted a3.263GB duplicate pack and was stopped only in its verified owned process tree. No history was force-pushed and no original sourceA manifest was rewritten.','successful_retry':'Metadata-only ours merge records the already-published immutable sourceA parent while preserving the content tree. Final normal push completed after the missing-object payload estimate fell to266492175 bytes.','hosted_run':{'id':36941786030,'head':m,'url':'https://github.com/Ebonyks/mermaid-roshan-reef/actions/runs/36941786030','status':'IN_PROGRESS_AT_LAST_OBSERVATION','conclusion':None},'qualification':d['acceptance_gaps'],'later_studies':'Contact44 static views and clean finishing source are later uncommitted review work. They are not included in this immutable c211 byte-verification claim.'}
write(out/'PUBLICATION_STATE.json',publication)
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Published review byte verification</title><style>body{font:18px/1.6 system-ui;color:#253447;background:#eef4fa;margin:0}main{max-width:1000px;margin:auto;padding:24px}section{padding:24px;background:white;border-radius:18px}p,a,code{overflow-wrap:anywhere}</style><main><section><h1>Published review: every declared byte verified</h1><p>The immutable content checkpointc2116877 was anonymously fetched using normal TLS. All13534 required files and3962010841 payload bytes matched their declared SHA256 hashes. The2309610-byte index was separately fetched and matched. Check completed'+result['checked_utc']+'.</p><p><a href="'+result['entry']+'">GitHub review entry</a> · <a href="'+publication['immutable_tree']+'">Immutable content tree</a> · <a href="'+result['manifest']+'">Direct file manifest</a></p><p><a href="RESULT.json">Verification receipt</a> · <a href="FETCH_JOURNAL.jsonl">Every actual GET/hash/check time</a> · <a href="PUBLICATION_STATE.json">Published ancestry and retry qualifications</a> · <a href="CHECKPOINT_IDENTITY.json">Fetched index identity</a></p><p>Published headfb03e0ac has exactly the same content tree as c2116877. It records sourceA ancestry while leaving its original manifests preserved. HostedCI run36941786030 remains pending at this observation.</p><p>'+d['acceptance_gaps']+'</p><p>Later contact and clean-hands studies are separate revision work and are not included in this checkpoint receipt.</p></section></main></html>'
(out/'index.html').write_text(page,encoding='utf-8',newline='\n')

entry=r/'audit/job_review_v2_20261001/index.html';s=entry.read_text(encoding='utf-8')
old='V2 publication and hosted evidence remain pending; the scanner and baseline have not been weakened.'
assert s.count(old)==1
s=s.replace(old,'V2 content checkpointc2116877 is published and all13534 current declared files have passed anonymous exact-byte verification. Published ancestry headfb03e0ac has the same content tree. <a href="current_b_remote_v1/index.html">Remote receipt and immutable GitHub links</a> preserve the distinction from pending hostedCI; the scanner and baseline have not been weakened.')
assert s.endswith('</main></html>')
s=s[:-len('</main></html>')]+'<section><h2>Later washing studies</h2><p><a href="../day_two_wash_contact_study_v1_20261001/attempt_01/index.html">All26 first static placements</a> and <a href="../day_two_wash_contact_study_v1_20261001/attempt_02/index.html">all18 layered placements</a> have individual native-view evaluations. Every tested contact remains below4.5; the source artwork is preserved.</p><p><a href="../../assets_src/imagegen/day2_doctor_wash_clean_result_v1_20261001/index.html">Clean-hands finishing source</a> reaches4.5 as an unbound draft. Game-size contact and the complete washing action remain open. These later files are outside the immutable c211 file map until a separately verified publication.</p></section></main></html>'
entry.write_text(s,encoding='utf-8',newline='\n')
master=r/'audit/MASTER_AUDIT_2026-08-09.md';s=master.read_text(encoding='utf-8')
old='Current publication, hosted machine evidence and all-owner/global acceptance remain pending.'
assert s.count(old)==1
s=s.replace(old,'Content checkpointc2116877 is published; [all13534 current declared files anonymously match exact hashes](job_review_v2_20261001/current_b_remote_v1/index.html). Published ancestry headfb03e0ac preserves the same tree and original sourceA manifests. HostedCI run36941786030, all-owner/global acceptance, integration and release remain pending.')
marker='## 0. Planning entry\n'
assert s.count(marker)==1
note='\nWashing contact follow-up (2026-10-01): [all26 first placements](day_two_wash_contact_study_v1_20261001/attempt_01/index.html) and [all18 layered placements](day_two_wash_contact_study_v1_20261001/attempt_02/index.html) are directly evaluated at native desktop sizes. Layered contact3.7–4.0/composition4.0–4.1 remains below the4.5 floor; all source pixels are preserved. [Clean-hands ending](../assets_src/imagegen/day2_doctor_wash_clean_result_v1_20261001/index.html) is an unbound source-only4.5 draft. Water/soap/clean causality, complete timed action, ordinary routes and device/child/owner acceptance remain open. [Contact impact](../design/audit_impacts/job-wash-contact-study-20261001.json); [publication impact](../design/audit_impacts/job-review-current-remote-receipt-20261001.json). No finding closure.\n'
s=s.replace(marker,marker+note);master.write_text(s,encoding='utf-8',newline='\n')
ledger=r/'design/05_DOC_LEDGER.md';s=ledger.read_text(encoding='utf-8')
old='normal-TLS anonymous original-byte receipt is separate from original hosted-red and pending current V2 gates.'
assert s.count(old)==1
s=s.replace(old,'normal-TLS anonymous original-byte receipt is separate from original hosted-red. Currentc211 content checkpoint is published: all13534 declared files and3962010841 bytes anonymously verified. Same-tree ancestry headfb03 hostedCI remains pending; unmodified local82/82 process verification retains51 diagnostics.')
for path,description in [
 ('audit/job_review_v2_20261001/current_b_remote_v1/index.html','CANDIDATE_PUBLICATION_EVIDENCE; immutable c211 anonymous exact-byte verification, all13534 files; published fb03 tree identical. HostedCI and visual/action/device/child/owner acceptance remain separate.'),
 ('audit/day_two_wash_contact_study_v1_20261001/attempt_01/index.html','CANDIDATE; all26 individual full native static views directly reviewed, contact2.0–3.8/composition2.8–4.0 below floor. Unchanged sources, no runtime/action acceptance.'),
 ('audit/day_two_wash_contact_study_v1_20261001/attempt_02/index.html','CANDIDATE; all18 individual full native static views directly reviewed;16 layered contact3.7–4.0/composition4.0–4.1 and two original2.3/2.9. Unchanged source regions; complete washing and owner/device/child acceptance remain open.'),
 ('assets_src/imagegen/day2_doctor_wash_clean_result_v1_20261001/index.html','CANDIDATE; one complete clean-hands ending source4.5; exact input/prompt/native provenance and neutral alpha review. Unbound, all mounted/contact/timing/action/device/child/owner scores pending.')]:
 assert path not in s;s+='\n| `'+path+'` | 🟣 | `'+description.split(';')[0]+'`; '+description.split(';',1)[1].strip()+' |\n'
ledger.write_text(s,encoding='utf-8',newline='\n')
d['files']=sorted({x.relative_to(r).as_posix() for x in out.rglob('*') if x.is_file()}|{'audit/job_review_v2_20261001/index.html','audit/MASTER_AUDIT_2026-08-09.md','design/05_DOC_LEDGER.md'})
write(impact,d)
allow=r/'tmp/v2_preview_allowed.json';allowset=set(json.loads(allow.read_text(encoding='utf-8')));allowset.update(d['files']);write(allow,sorted(allowset))
print(json.dumps({'status':result['status'],'files':result['verified_files'],'bytes':result['verified_bytes'],'original_currentB_index_unchanged':sha(index)==result['manifest_sha256'],'new_remote_evidence_files':len(list(out.iterdir())),'hosted':'pending','later_studies':'separate uncommitted revision'}))
